### PR TITLE
Improved test diagnostics on Windows

### PR DESCRIPTION
**Pull request by jonhawkes**

### CODE REVIEW

**Review by neilgsyoung — APPROVED** [review]

**Comment by jonhawkes** [comment]
#build
#run-libby-bot

**Comment by jonhawkes** [comment]
#build
#run-libby-bot

**Comment by jonhawkes** [comment]
#build
#run-libby-bot

**Comment by jonhawkes** [comment]
#build
#run-libby-bot

**Comment by jonhawkes** [comment]
#build
#run-libby-bot

**Comment by jonhawkes** [comment]
#build
#run-libby-bot

**Comment by jonhawkes** [comment]
#build
#run-libby-bot

**Comment by jonhawkes** [comment]
#build
#run-libby-bot

**Comment by jonhawkes** [comment]
#build
#run-libby-bot

**Comment by hcs-ibm** [comment]
L2 message review complete

**Comment by jonhawkes** [comment]
#build
#run-libby-bot

**Pull request merged**
