### PR TITLE
20716 feature buckets

### LINKED ISSUE #20716: Update the build.featureStartXYZ buckets to run fewer tests
The build.featureStartAToL and build.featureStartMToZ buckets run too many tests.  We have features that are stable and proven which should be skipped.  May just want to run these on a build definition by itself vs platform related build defs as well.  Could look at resolution apis vs actually starting servers to run features.

### PR DESCRIPTION
**Pull request by tbitonti**
Test only update.

This update splits the two single feature start test buckets into four buckets:

- **Removed:**
  - build.featureStart.aToL_fat
  - build.featureStart.mToZ_fat
- **Added:**
  - build.featureStart.base
  - build.featureStart.part1_fat
  - build.featureStart.part2_fat
  - build.featureStart.part3_fat
  - build.featureStart.part4_fat

**Main updates:**
- Common code was relocated to the 'base' project.
  - Feature specific settings were consolidated into the base project.
- The number of parts was increased from '2' to '4'.
  - Dividing into '4' instead of '3' gives us more of a buffer for new single feature tests.
  - Each of the feature start parts takes an equal portion of the single features which are to be tested.
- In the future, the number of parts can be increased by copying an existing part project and adjusting the part parameters.
- The base test code was substantially updated.

### CODE REVIEW

**Comment by tbitonti** [comment]
For issue #20716

**Comment by tbitonti** [comment]
#build

**Comment by tbitonti** [comment]
This is a test only update.  The same tests which were performed before the update are performed after the update, with the difference that the tests are split between four buckets now instead of two.  The update was run by verifying that the tests still run.

**Comment by tbitonti** [comment]
#build

**Comment by tbitonti** [comment]
#libby

**Comment by tbitonti** [comment]
#build

**Comment by tbitonti** [comment]
#libby

**Comment by tbitonti** [comment]
Test failure:
```
junit.framework.AssertionFailedError: 2022-09-28-14:51:38:570 Features [ [rtcommGateway-1.0] ] should have started.
	at com.ibm.ws.simple.base.FeaturesStartTestBase.testStartFeatures(FeaturesStartTestBase.java:970)
	at com.ibm.ws.simple.FeaturesStartTest4.testStartFeaturesPart4(FeaturesStartTest4.java:56)
```
The 'allowedErrors' table was incorrectly constructed.

**Comment by tbitonti** [comment]
#build

**Comment by tbitonti** [comment]
#libby

**Comment by tbitonti** [comment]
Test failures:

- build.featureStart.part4_fat FAT tests
  - com.ibm.ws.simple.FeaturesStartTest4
    - testStartFeaturesPart4
- com.ibm.ws.automation.healing_fat FAT tests
  - com.ibm.ws.automation.test.HealingTest
    - testLibertyRunbook

The first is an error in the test data; fixing and rerunning.  The second is a known defect.

**Comment by tbitonti** [comment]
#libby

**Comment by tbitonti** [comment]
#build

**Comment by tbitonti** [comment]
Results for the updated FATS:

- build.featureStart.part1_fat FAT tests
  - com.ibm.ws.simple.FeaturesStartTest1
    - testStartFeaturesPart1 7 m 59 s, 9 m 20 s
- build.featureStart.part2_fat FAT tests
  - com.ibm.ws.simple.FeaturesStartTest2
    - testStartFeaturesPart2 8 m 33 s, 9 m 46 s
- build.featureStart.part3_fat FAT tests
  - com.ibm.ws.simple.FeaturesStartTest3
    - testStartFeaturesPart3 9 m 23 s, 8 m 57 s
- build.featureStart.part4_fat FAT tests
  - com.ibm.ws.simple.FeaturesStartTest4
    - testStartFeaturesPart4 8 m 18 s, 7 m 57 s

**Review by jimblye — APPROVED** [review]

**Comment by tbitonti** [comment]
Failures are unrelated:
- io.openliberty.wsoc.2.1.internal_fat FAT tests
  - io.openliberty.wsoc.tests.Basic21Test
    - testUserPropertiesOnServer

**Pull request merged**
