### PR TITLE
Add jakartaee-8.0 feature

### PR DESCRIPTION
**Pull request by aguibert**

### CODE REVIEW

**Comment by aguibert** [comment]
#build

**Comment by tevans78** [comment]
Going straight to GA with this?

**Comment by aguibert** [comment]
@tevans78 yes I was planning to since OpenLiberty 19009 already claimed support for Jakarta EE 8 . Also, this change is a fairly straightforward copy+rename of the existing `javaee-8.0` feature.

**Comment by aguibert** [comment]
also got written approval from Alasdair via Slack -- proceeding with merge

**Pull request merged**
