### PR TITLE
Further enabling of jakartaee in jsonb FAT

### PR DESCRIPTION
**Pull request by anjumfatima90**
for issue #11278
Run FAT:
JSON

### CODE REVIEW

**Review by dazavala — APPROVED** [review]
Changes look good.  I noticed copyrights need updating, and there are several occurrences in this fat.  Same and less so for the jsonp 1.1 FAT.  I would prefer you update copyrights in the jsonb fat today, otherwise we will immediately update copyrights for all json ee9 test files in a separate PR.  Thanks!

**Comment by anjumfatima90** [comment]
#build

**Comment by anjumfatima90** [comment]
#build

**Comment by anjumfatima90** [comment]
#libby

**Comment by dazavala** [comment]
Fixes #11633

**Pull request merged**
