### PR TITLE
Add debug for krb5 fat failure on windows

### PR DESCRIPTION
**Pull request by brenthdaniel**

### CODE REVIEW

**Comment by brenthdaniel** [comment]
#build

**Comment by brenthdaniel** [comment]
Looks like this ran into an artifactory failure.. 
#build again

**Review by hlhoots — APPROVED** [review]
LGTM

**Comment by brenthdaniel** [comment]
#build

**Comment by brenthdaniel** [comment]
Shelving this for now because we added support to dump the server on a failure in all cases in another PR.  I also have no idea why this PR would consistently run into artifactory failures.

**Pull request closed without merging**
