### PR TITLE
Update mp features to use new internal webBundle feature to not depend on servlet with EE10

### PR DESCRIPTION
**Pull request by jhanders34**
- Change from having a single webBundle internal feature and have features only depend on singleton features.
- Update mpOpenAPI-3.1 to only work with EE10 and depend on the internal webBundle feature so it doesn't depend on the servlet 6.0 public feature any longer.
- Update mpOpenAPI FATs to have servlet feature in their server.xml so they work when run with MP 6 features since the FATs use a servlet as part of their tests.
- Update mpHealth-4.0 to use internal webBundle feature so that when using MP6 features the public servlet 6.0 feature is not enabled.
- Update mpHealth-4.0 FATs to have servlet feature added to their server.xml when the FAT uses a servlet as part of its test.
- Add a repeat to run mpConfig 3.0 TCK with EE10 features
- Change to use the rest test protocol and not have servlet added to the mpConfig 3.0 TCK server.xml.
- Add new ignore warning when stopping the mpConfig 3.0 TCK server for new warning for CDI 4.0
- Add the cdi 3.0 compatibility setting in mpConfig TCK server.xml default behavior change in 4.0 so that tests pass

### CODE REVIEW

**Comment by jhanders34** [comment]
#build

**Comment by jhanders34** [comment]
https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_qn3LICJnEe2b2O1gXXKb4w is the build to watch.

**Comment by Azquelt** [comment]
Testing locally, I don't think it should be necessary to add servlet to the mpOpenApi FAT tests except for `OpenAPIMergeTestServer`.

Technically `ApplicationProcessorTest` does use a servlet as well, but it's a negative test (checking that an application with a servlet is not used) so it shouldn't fail and I think I'd prefer to be missing the coverage of that test vs. missing the coverage of mpOpenApi-3.1 without servlet.

Either way we'll need a new issue to ensure that we update the FATs to separate out the tests that need servlet from the ones that don't.

**Comment by Azquelt** [comment]
`io.openliberty.microprofile.openapi.3.1.internal_fat_tck` has a repeat for mpOpenAPI-3.1 + EE9 which runs in FULL mode which I would expect to fail with your changes here. The repeat should be removed.

**Comment by jhanders34** [comment]
> `io.openliberty.microprofile.openapi.3.1.internal_fat_tck` has a repeat for mpOpenAPI-3.1 + EE9 which runs in FULL mode which I would expect to fail with your changes here. The repeat should be removed.

The change you are suggesting is in this PR.  Am I missing something?

**Comment by jhanders34** [comment]
> Testing locally, I don't think it should be necessary to add servlet to the mpOpenApi FAT tests except for `OpenAPIMergeTestServer`.
> 
> Technically `ApplicationProcessorTest` does use a servlet as well, but it's a negative test (checking that an application with a servlet is not used) so it shouldn't fail and I think I'd prefer to be missing the coverage of that test vs. missing the coverage of mpOpenApi-3.1 without servlet.
> 
> Either way we'll need a new issue to ensure that we update the FATs to separate out the tests that need servlet from the ones that don't.

I was careful to only update the server.xmls for tests that used a servlet.  There are some that I did not update because the tests didn't require an application with a servlet.  If it isn't needed in some of them, then I will remove them.

**Comment by Azquelt** [comment]
> The change you are suggesting is in this PR. Am I missing something?

Sorry, my mistake.

**Comment by Azquelt** [comment]
> I was careful to only update the server.xmls for tests that used a servlet. There are some that I did not update because the tests didn't require an application with a servlet. If it isn't needed in some of them, then I will remove them.

For whatever reason several of the tests extend `FATServletClient` but none of them deploy a `FATServlet`.

The only tests I could see that actually deploy a servlet were the ones that are checking that a web application which doesn't contain a JAX-RS application is ignored.

**Comment by jhanders34** [comment]
> For whatever reason several of the tests extend `FATServletClient` but none of them deploy a `FATServlet`.
> 
> The only tests I could see that actually deploy a servlet were the ones that are checking that a web application which doesn't contain a JAX-RS application is ignored.

The server.xml updates are in.

**Comment by jhanders34** [comment]
#libby #build

**Comment by jhanders34** [comment]
#libby #build

**Review by tevans78 — APPROVED** [review]

**Pull request merged**
