### PR TITLE
23781 update test ng

### LINKED ISSUE #23781: Update to TestNG 7.5.x
https://repo1.maven.org/maven2/org/testng/testng/7.7.1/

### PR DESCRIPTION
**Pull request by benjamin-confino**
Update TestNG to 7.5.0 custom release

Update Arquillian testng to last known good release
Update Arquillian Jarkata to latest
Update Arquillian Liberty Container to latest

Simplyify Arquillian Logging extensions

fixes https://github.com/OpenLiberty/open-liberty/issues/23781

### CODE REVIEW

**Comment by benjamin-confino** [comment]
#build

**Comment by benjamin-confino** [comment]
#build

**Comment by benjamin-confino** [comment]
#build

**Comment by benjamin-confino** [comment]
#build

**Comment by benjamin-confino** [comment]
#build

**Comment by benjamin-confino** [comment]
#build

**Comment by benjamin-confino** [comment]
#build

**Comment by benjamin-confino** [comment]
#build

**Comment by benjamin-confino** [comment]
#build

**Comment by abutch3r** [comment]
#build

**Comment by abutch3r** [comment]
#build

**Pull request closed without merging**
