### PR TITLE
Update detect-secrets scanner and false-positives

### PR DESCRIPTION
**Pull request by mbroz2**
This PR is to update how we scan using detect-secrets and to address the resulting false-positives.

- [X] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [X] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [X] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

### CODE REVIEW

**Comment by mbroz2** [comment]
The remaining 328 items will be worked through by the security team.

**Comment by mbroz2** [comment]
#build

**Comment by mbroz2** [comment]
!build

**Comment by mbroz2** [comment]
#libby

**Review by tevans78 — APPROVED** [review]

**Comment by mbroz2** [comment]
Green build (though the code changes should have zero impact on anything that currently occurs as part of the build)

**Pull request merged**
