### PR TITLE
Do not include unshipped bundles in build.image

### PR DESCRIPTION
**Pull request by jhanders34**
- Do not publish bundles that are not shipped to build.image as part of the build.
- Make XML Binding settings use Java 11
- Add featureUtility.bat to the kernel feature file

### CODE REVIEW

**Comment by jhanders34** [comment]
#build

**Comment by jhanders34** [comment]
#build

**Review by idlewis — APPROVED** [review]
lgtm

**Review by tjwatson — APPROVED** [review]

**Comment by jhanders34** [comment]
#libby

I had the build run a child build with the failing test and it passed.  Will merge.

**Pull request merged**
