### PR TITLE
test bucket to be used for heritage settings plugin point

### PR DESCRIPTION
**Pull request by njr-11**
Create a test bucket where we can test JDBC heritage settings.

### CODE REVIEW

**Comment by njr-11** [comment]
#build

**Comment by njr-11** [comment]
#build
#run-libby-bot

**Review by KyleAure — APPROVED** [review]

**Comment by njr-11** [comment]
#build
#run-libby-bot

**Comment by njr-11** [comment]
#build

**Comment by njr-11** [comment]
#build

**Comment by njr-11** [comment]
commits were included under 15983

**Pull request merged**
