### PR TITLE
move ee9 transform func from oidc to security common

### PR DESCRIPTION
**Pull request by jimmy1wu**

### CODE REVIEW

**Comment by jimmy1wu** [comment]
#build

**Review by c00crane — APPROVED** [review]
When running your personal build, please include (at least a subset of) the following projects in your spawn.fullfat.buckets:
com.ibm.ws.security.oidc.client_fat
com.ibm.ws.security.oidc.server_fat.jaxrs.config
com.ibm.ws.security.oidc.client_fat.jaxrs
com.ibm.ws.security.oidc.server_fat.oidc
com.ibm.ws.security.saml.sso_fat
com.ibm.ws.security.saml.sso_fat.2
com.ibm.ws.security.saml.sso_fat.3
com.ibm.ws.security.saml.sso_fat.common
com.ibm.ws.security.saml.sso_fat.config
com.ibm.ws.security.saml.sso_fat.config.mapToUserRegistry
com.ibm.ws.security.saml.sso_fat.endpoint.samlmetadata
com.ibm.ws.security.saml.sso_fat.jaxrs
com.ibm.ws.security.saml.sso_fat.jaxrs.config
com.ibm.ws.security.saml.sso_fat.logout
com.ibm.ws.security.saml.sso_fat.logout.IDP_initiated
com.ibm.ws.security.saml.sso_fat.logout.httpServletRequest
com.ibm.ws.security.saml.sso_fat.logout.ibm_security_logout

**Comment by jimmy1wu** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.security.oidc.client_fat,com.ibm.ws.security.oidc.server_fat.jaxrs.config,com.ibm.ws.security.oidc.client_fat.jaxrs,com.ibm.ws.security.oidc.server_fat.oidc,com.ibm.ws.security.saml.sso_fat,com.ibm.ws.security.saml.sso_fat.2,com.ibm.ws.security.saml.sso_fat.3,com.ibm.ws.security.saml.sso_fat.common,com.ibm.ws.security.saml.sso_fat.config,com.ibm.ws.security.saml.sso_fat.config.mapToUserRegistry,com.ibm.ws.security.saml.sso_fat.endpoint.samlmetadata,com.ibm.ws.security.saml.sso_fat.jaxrs,com.ibm.ws.security.saml.sso_fat.jaxrs.config,com.ibm.ws.security.saml.sso_fat.logout,com.ibm.ws.security.saml.sso_fat.logout.IDP_initiated,com.ibm.ws.security.saml.sso_fat.logout.httpServletRequest,com.ibm.ws.security.saml.sso_fat.logout.ibm_security_logout

**Comment by jimmy1wu** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.security.oidc.client_fat,com.ibm.ws.security.oidc.server_fat.jaxrs.config,com.ibm.ws.security.oidc.client_fat.jaxrs,com.ibm.ws.security.oidc.server_fat.oidc,com.ibm.ws.security.saml.sso_fat,com.ibm.ws.security.saml.sso_fat.2,com.ibm.ws.security.saml.sso_fat.3,com.ibm.ws.security.saml.sso_fat.config,com.ibm.ws.security.saml.sso_fat.config.mapToUserRegistry,com.ibm.ws.security.saml.sso_fat.endpoint.samlmetadata,com.ibm.ws.security.saml.sso_fat.jaxrs,com.ibm.ws.security.saml.sso_fat.jaxrs.config,com.ibm.ws.security.saml.sso_fat.logout,com.ibm.ws.security.saml.sso_fat.logout.IDP_initiated,com.ibm.ws.security.saml.sso_fat.logout.httpServletRequest,com.ibm.ws.security.saml.sso_fat.logout.ibm_security_logout

**Comment by jimmy1wu** [comment]
build error is unrelated

**Pull request merged**
