### PR TITLE
Make cpuinfo compile on Java 7/8

### PR DESCRIPTION
**Pull request by NottyCode**
While everyone was encouraged to upgrade to Java 11 not supporting Java 7/8 is causing some issues so delivering a fix (I hope).

### CODE REVIEW

**Comment by NottyCode** [comment]
#build this please Mx Libby

**Comment by NottyCode** [comment]
@jhanders34 I spoke to someone from the OpenJ9 team and they said that it has always supported the com.sun.management package so I don't think this would be correct. IBM Java has not, but that changed in Feb 2017 and OpenJ9 didn't happen until September 2017.

**Comment by jhanders34** [comment]
The changes in this PR should work as well at runtime.  The problem with compile was specific to IBM JDKs that didn't have the com.sun.management.OperatingSystemMXBean or had it, but gradle build didn't find it for some reason.

**Comment by NottyCode** [comment]
Build is good.

**Pull request merged**
