### PR TITLE
437 remember me

### PR DESCRIPTION
**Pull request by teddyjtorres**
For issue #437

### CODE REVIEW

**Comment by teddyjtorres** [comment]
#build

**Comment by toshiyamamoto** [comment]
Per the JSR375 specification, the priority of the RememberMe IdentityStore would be PLATFORM_BEFORE + 210, but the current annotation states PLATFORM_BEFORE. (No +210).

**Comment by toshiyamamoto** [comment]
Please ignore my previous message, the file which was commented was deleted.

**Comment by toshiyamamoto** [comment]
Is it OK that the package of RememberMe IdentityStore is com.ibm.ws.security.javaeesec.cdi.extensions which is excluded from the bean scanning (per beans.xml)?

**Comment by toshiyamamoto** [comment]
I'm sorry there was a typo in my previous question, it's not RememberMe IdentityStore, but RememberMe Interceptor.

**Comment by toshiyamamoto** [comment]
In interceptValidateRequest method in RememberMeInterceptor class, there is not a null object check for the instance of RememberMeIdentityStore. Is RememberMeIdentityStore always available in this code path?

**Comment by teddyjtorres** [comment]
Hi Toshi. The interceptor is scanned when added from the CDI extension like this,

AnnotatedType<RememberMeInterceptor> rememberMeInterceptorInterceptorType = beanManager.createAnnotatedType(RememberMeInterceptor.class);
beforeBeanDiscovery.addAnnotatedType(rememberMeInterceptorInterceptorType);

The spec says that the app must provide the RememberMeIdentityStore when using RememberMe,

"The RememberMe annotation is used to configure a RememberMeIdentityStore, which must be provided by the application. To use RememberMe, the application must provide an
HttpAuthenticationMechanism and annotate the HttpAuthenticationMechanism with the RememberMe
annotation."

If CDI fails to get one, then the CDI exception is raised and converted to the AuthException by the AuthModule and a 403 is sent to the browser.

**Comment by toshiyamamoto** [comment]
Thank you Teddy. Approved.

**Comment by teddyjtorres** [comment]
Thank you!

**Pull request merged**
