### PR TITLE
29256 add gzip tests

### LINKED ISSUE #29256: Add FATs for testing GZIP Interceptors
Need to add some FATs for testing enabling of GZIPOutInterceptor and GZIPInInterceptor.

### PR DESCRIPTION
**Pull request by sawadood**
- [X ] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [X ] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [ ] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

Fixes #29256

### CODE REVIEW

**Comment by sawadood** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.jaxws.2.2.webcontainer_fat, com.ibm.ws.jaxws.2.2.webcontainer_fat_extended, com.ibm.ws.jaxws.cdi_fat, com.ibm
.ws.jaxws.clientcontainer_fat, com.ibm.ws.jaxws.ejb_fat, io.openliberty.jaxrs.2.1.jaxws.2.2_fat, io.openliberty.jaxws.beanvalidation_fat,  io.openliberty.jaxws.global.handler.internal_fat, io.openliberty.jaxws.security_fat, io.openliberty.jaxws.security_fat.1, io.openliberty.jaxws.security_fat.ssl, io.openliberty.jaxws.tools_fat, io.openliberty.jaxws.wsat_fat, io.openliberty.jaxws_fat, com.ibm.ws.wsat.common_fat, com.ibm.ws.wsat.concurrent_fat, com.ibm.ws.wsat.migration_fat.1, com.ibm.ws.wsat.migration_fat.2, com.ibm.ws.wsat.migration_fat.3, com.ibm.ws.wsat.migration_fat.4, com.ibm.ws.wsat.migration_fat.5, com.ibm.ws.wsat.migration_fat.6, com.ibm.ws.wsat.migration_fat.7, com.ibm.ws.wsat.recovery_fat.lps, com.ibm.ws.wsat.recovery_fat.multi.1, com.ibm.ws.wsat.recovery_fat.multi.2, com.ibm.ws.wsat.recovery_fat.multi.3, com.ibm.ws.wsat.recovery_fat.multi.4, com.ibm.ws.wsat.recovery_fat.multi.5, com.ibm.ws.wsat.recovery_fat.multi.6, com.ibm.ws.wsat.recovery_fat.multi.7, com.ibm.ws.wsat.recovery_fat.single.1, com.ibm.ws.wsat.recovery_fat.single.2, com.ibm.ws.wsat_fat.assertion, com.ibm.ws.wsat_fat.db, com.ibm.ws.wsat_fat.db_optional, com.ibm.ws.wsat_fat.dbs, com.ibm.ws.wsat_fat.dbs_optional, com.ibm.ws.wsat_fat.multi, com.ibm.ws.wsat_fat.multi.misroute, com.ibm.ws.wsat_fat.ssl, com.ibm.ws.wsat_fat.ssl.misroute, io.openliberty.jaxws.wsat_fat, com.ibm.ws.wssecurity_fat.wsscxf.1, com.ibm.ws.wssecurity_fat.wsscxf.2, com.ibm.ws.wssecurity_fat.wsscxf.3, com.ibm.ws.wssecurity_fat.wsscxf.4, com.ibm.ws.wssecurity_fat.wsscxf.saml.1, com.ibm.ws.wssecurity_fat.wsscxf.saml.2, com.ibm.ws.wssecurity_fat.wsscxf.saml.3, com.ibm.ws.wssecurity_fat.wsscxf.saml.5, com.ibm.ws.wssecurity_fat.wsscxf.saml.6, io.openliberty.xmlws.4.0.internal_fat

**Review by neuwerk — APPROVED** [review]
Changes look good to me.

**Comment by sawadood** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.jaxws.2.2.webcontainer_fat, com.ibm.ws.jaxws.2.2.webcontainer_fat_extended, com.ibm.ws.jaxws.cdi_fat, com.ibm
.ws.jaxws.clientcontainer_fat, com.ibm.ws.jaxws.ejb_fat, io.openliberty.jaxrs.2.1.jaxws.2.2_fat, io.openliberty.jaxws.beanvalidation_fat, io.openliberty.jaxws.global.handler.internal_fat, io.openliberty.jaxws.security_fat, io.openliberty.jaxws.security_fat.1, io.openliberty.jaxws.security_fat.ssl, io.openliberty.jaxws.tools_fat, io.openliberty.jaxws.wsat_fat, io.openliberty.jaxws_fat, com.ibm.ws.wsat.common_fat, com.ibm.ws.wsat.concurrent_fat, com.ibm.ws.wsat.migration_fat.1, com.ibm.ws.wsat.migration_fat.2, com.ibm.ws.wsat.migration_fat.3, com.ibm.ws.wsat.migration_fat.4, com.ibm.ws.wsat.migration_fat.5, com.ibm.ws.wsat.migration_fat.6, com.ibm.ws.wsat.migration_fat.7, com.ibm.ws.wsat.recovery_fat.lps, com.ibm.ws.wsat.recovery_fat.multi.1, com.ibm.ws.wsat.recovery_fat.multi.2, com.ibm.ws.wsat.recovery_fat.multi.3, com.ibm.ws.wsat.recovery_fat.multi.4, com.ibm.ws.wsat.recovery_fat.multi.5, com.ibm.ws.wsat.recovery_fat.multi.6, com.ibm.ws.wsat.recovery_fat.multi.7, com.ibm.ws.wsat.recovery_fat.single.1, com.ibm.ws.wsat.recovery_fat.single.2, com.ibm.ws.wsat_fat.assertion, com.ibm.ws.wsat_fat.db, com.ibm.ws.wsat_fat.db_optional, com.ibm.ws.wsat_fat.dbs, com.ibm.ws.wsat_fat.dbs_optional, com.ibm.ws.wsat_fat.multi, com.ibm.ws.wsat_fat.multi.misroute, com.ibm.ws.wsat_fat.ssl, com.ibm.ws.wsat_fat.ssl.misroute, io.openliberty.jaxws.wsat_fat, com.ibm.ws.wssecurity_fat.wsscxf.1, com.ibm.ws.wssecurity_fat.wsscxf.2, com.ibm.ws.wssecurity_fat.wsscxf.3, com.ibm.ws.wssecurity_fat.wsscxf.4, com.ibm.ws.wssecurity_fat.wsscxf.saml.1, com.ibm.ws.wssecurity_fat.wsscxf.saml.2, com.ibm.ws.wssecurity_fat.wsscxf.saml.3, com.ibm.ws.wssecurity_fat.wsscxf.saml.5, com.ibm.ws.wssecurity_fat.wsscxf.saml.6, io.openliberty.xmlws.4.0.internal_fat

**Comment by sawadood** [comment]
One failure was caused by incorrect list of fat tests

**Comment by sawadood** [comment]
#libby

**Pull request merged**
