### PR TITLE
Fix G.hasKey Error  in MyFaces's JavaScript code

### LINKED ISSUE #28698: MYFACES-4672: Ajax MultiPart File Upload Encounters 'Uncaught TypeError: G.hasKey is not a function'
**Describe the bug**  
A JavaScript error is encountered during XHR file upload request. 
```
Uncaught TypeError: G.hasKey is not a function
at eval ( eval at appendIssuingItem (jsf.jx.xhtml?In=javax.feaces:13:72889)
at J.<computed>.appendIssuingItem ( jsf.js.xhtml?In=javax.faces:12:72889)
at constructor_.getFormData (jsf.js.xhtml?In=javax.faces:13:87643)
```

Note: This is a regression caused https://github.com/OpenLiberty/open-liberty/issues/26221 (MYFACES-4606)

**Steps to Reproduce**  

Code looks something like this: 
```
            <h:inputFile id="someFileID" value="#{someFileBean.file}">
                <f:ajax event="change"/>
            </h:inputFile>
```

**Expected behavior**  
No errors should occur.  

**Diagnostic information:**  
 - OpenLiberty Version: 24.0.0.1-24.0.0.7
 - Affected feature(s) jsf-2.2, jsf-2.3, faces-3.0
 - Java Version: N/A

**Additional context**  
https://issues.apache.org/jira/browse/MYFACES-4672

### PR DESCRIPTION
**Pull request by volosied**
fixes #28698 
fixes PH62139

### CODE REVIEW

**Comment by volosied** [comment]
#build

**Comment by volosied** [comment]
#build #fat.buckets.to.run=com.ibm.ws.jsf.2.2_fat,com.ibm.ws.jsf.2.3_fat,com.ibm.ws.jsf_fat_lWAS_jsf2.3

**Comment by volosied** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jsf.2.2_fat

**Comment by volosied** [comment]
#build

**Comment by volosied** [comment]
#build

**Review by pnicolucci — APPROVED** [review]

**Comment by volosied** [comment]
#libby

**Pull request merged**
