### PR TITLE
Add @SkipIfCheckpointNotSupported to the test

### PR DESCRIPTION
**Pull request by anjumfatima90**

### CODE REVIEW

**Review by tjwatson — APPROVED** [review]

**Comment by tjwatson** [comment]
#build

**Review by tjwatson — APPROVED** [review]
Approved to add the annotations.  We should merge this as soon as we can.  Could you open a separate PR that does the following:

In `componenttest.topology.impl.LibertyServer.doCheckpoint()` could you update the method to not have `&& getCheckpointSupported()`:

```java
    private boolean doCheckpoint() {
        return (checkpointInfo != null);
    }
```
This would have caused the tests to fail if run on non criu JVMs.

**Comment by tjwatson** [comment]
#libby

**Comment by anjumfatima90** [comment]
> Approved to add the annotations. We should merge this as soon as we can. Could you open a separate PR that does the following:
> 
> In `componenttest.topology.impl.LibertyServer.doCheckpoint()` could you update the method to not have `&& getCheckpointSupported()`:
> 
> ```java
>     private boolean doCheckpoint() {
>         return (checkpointInfo != null);
>     }
> ```
> 
> This would have caused the tests to fail if run on non criu JVMs.

Added this new PR https://github.com/OpenLiberty/open-liberty/pull/24032

**Pull request merged**
