### PR TITLE
Enable FacesDataModel tests for EE10

### PR DESCRIPTION
**Pull request by pnicolucci**
for #22368

### CODE REVIEW

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
Java 17 build: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_RJFMEKfcEe24er7gxU0d3Q

**Comment by pnicolucci** [comment]
Java17 tests were successful

**Review by volosied — APPROVED** [review]

**Pull request merged**
