### PR TITLE
add test on return.security.error

### PR DESCRIPTION
**Pull request by meiaus**
issue https://github.com/OpenLiberty/open-liberty/issues/24772

### CODE REVIEW

**Comment by meiaus** [comment]
#run-libby-bot

**Comment by meiaus** [comment]
#run-libby-bot

**Comment by meiaus** [comment]
#run-libby-bot

**Comment by meiaus** [comment]
#run-libby-bot

**Comment by meiaus** [comment]
#build

**Comment by meiaus** [comment]
#run-libby-bot

**Comment by meiaus** [comment]
#build

**Comment by meiaus** [comment]
PB result:

1. With the specified FAT only: passed:
image


image


2. With `All`: passed but one error from other FAT not related

image


image

3. With `soe.platform.requests` `RHEL9_X86_REDHAT_8_64,AIX73_POWER10_PPC_IBM_SEMERUJDK17_OPENJ9_64_EBC`: passed


image


image

**Review by arunavemulapalli — APPROVED** [review]

**Pull request merged**
