### PR TITLE
Explore tool accessibility fixes

### PR DESCRIPTION
**Pull request by lavenal**
This PR fixes the following accessibility issues in Explore admin center tool:

- img role with no label
  - use aria-labelledby attribute to point to an existing label
  - otherwise use aria-label
- accessible name not matching visible label text
  - replace aria-label with aria-labelledby attribute to point to an existing label
  - replace aria-label with alt attribute
  - remove unnecessary aria-label when there is visible text or title attribute

The Explore dashboard (for both collective and standalone server), collective view, and object view panels are all scanned with no accessibility violation. In addition, those panels are read by the JAWS screen reader to ensure the correct info is provided to users with disabilities.

### CODE REVIEW

**Comment by lavenal** [comment]
#build

**Review by k8vance88 — APPROVED** [review]

**Comment by lavenal** [comment]
#build

**Comment by lavenal** [comment]
#build

**Comment by lavenal** [comment]
#build

**Comment by lavenal** [comment]
#run-libby-bot

**Pull request merged**
