### PR TITLE
Issue #19372: Update TestEDR.war formatting

### LINKED ISSUE #19372: Update com.ibm.ws.jsp.2.3_fat TestEDR.war formatting
Minor  formatting clean up as well as correcting the copyright date in the web.xml

### PR DESCRIPTION
**Pull request by pnicolucci**
fixes #19372

### CODE REVIEW

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#libby

**Comment by pnicolucci** [comment]
#build

**Review by epj — APPROVED** [review]
looks good

**Comment by pnicolucci** [comment]
#libby

**Pull request merged**
