### PR TITLE
Add isActive method for endpoints

### PR DESCRIPTION
**Pull request by brenthdaniel**

### CODE REVIEW

**Comment by brenthdaniel** [comment]
#build

**Comment by brenthdaniel** [comment]
#build

**Comment by brenthdaniel** [comment]
#build

**Comment by brenthdaniel** [comment]
#build

**Comment by brenthdaniel** [comment]
#build

**Comment by brenthdaniel** [comment]
rebasing and rebuilding because this has been sitting around for a while
#build

**Comment by brenthdaniel** [comment]
#build

**Comment by brenthdaniel** [comment]
#run-libby-bot

**Review by hlhoots — APPROVED** [review]
looks good to me.

**Comment by brenthdaniel** [comment]
PR for #16079

**Pull request merged**
