### PR TITLE
Potential fix for CDI clobbering issue.

### PR DESCRIPTION
**Pull request by andymc12**

### CODE REVIEW

**Comment by andymc12** [comment]
#build

**Comment by andymc12** [comment]
#build

**Comment by andymc12** [comment]
#build

**Comment by andymc12** [comment]
#build

**Comment by andymc12** [comment]
#build

**Comment by andymc12** [comment]
A few tweaks - new #build

**Comment by andymc12** [comment]
Made some code review changes, so time for a new #build to test them.

**Comment by andymc12** [comment]
Failures due to unrelated JMS changes, but prevented tests from executing... new #build after rebasing.

**Comment by andymc12** [comment]
Still more unrelated failures preventing the tests from executing... #build again.

**Comment by andymc12** [comment]
#build

**Comment by jim-krueger** [comment]
See RTC defect 246427 for additional details.

**Pull request merged**
