### PR TITLE
Admin Center - make changes for oidc icons to use Subsystem-Icon

### PR DESCRIPTION
**Pull request by aknguyen7**
This issue is to fix the problem with the zip packaging to include the icons for com.ibm.websphere.appserver.openidConnectServer-1.0 feature

### CODE REVIEW

**Comment by aknguyen7** [comment]
#build

**Review by cbridgha — APPROVED** [review]
LGTM

**Comment by aknguyen7** [comment]
#build

**Comment by aknguyen7** [comment]
#build

**Comment by aknguyen7** [comment]
#libby

**Review by cbridgha — APPROVED** [review]
LGTM again. :)

**Comment by aknguyen7** [comment]
#build

**Comment by aknguyen7** [comment]
#build

**Comment by aknguyen7** [comment]
#build

**Comment by aknguyen7** [comment]
#libby

**Review by cbridgha — APPROVED** [review]
LGTM

**Comment by aknguyen7** [comment]
the actual fix is in a different team @ https://github.com/OpenLiberty/open-liberty/issues/17150

**Pull request closed without merging**
