### PR TITLE
Update faces-3.0 to use MyFaces 3.0.2

### LINKED ISSUE #21502: Update the faces-3.0 feature to MyFaces 3.0.2
**Describe the bug**  
The following issues have been fixed in the 3.0.2 update: 

[[MYFACES-4405](https://issues.apache.org/jira/browse/MYFACES-4405)] - Wrong translation on myfaces/api/src/main/resources/javax/faces/Messages_pt.properties and pt_BR for DoubleRangeValidator.NOT_IN_RANGE
    [[MYFACES-4409](https://issues.apache.org/jira/browse/MYFACES-4409)] - possible NPE in CheckDuplicateIdFaceletUtils
    [[MYFACES-4423](https://issues.apache.org/jira/browse/MYFACES-4423)] - oam.Flash.REDIRECT should not be set when flash is disabled
    [[MYFACES-4431](https://issues.apache.org/jira/browse/MYFACES-4431)] - Custom NavigationHandler throws NPE during flow handling
    [[MYFACES-4433](https://issues.apache.org/jira/browse/MYFACES-4433)] - Memory Leak with ViewScopeBeanHolder's storageMap

Note that some issues have already been fixed in earlier Liberty releases, such as MYFACES-4433.

There have also been some improvements relating to the renderer classes: 
[[MYFACES-4428](https://issues.apache.org/jira/browse/MYFACES-4428)] - Separate "begin tag" code from "end tag" code in HtmlTextRendererBase
[[MYFACES-4430](https://issues.apache.org/jira/browse/MYFACES-4430)] - Separate "begin tag" code from "end tag" code for HtmlCheckboxRendererBase

These render changes mean that a [third party API package](https://openliberty.io/docs/latest/reference/feature/faces-3.0.html#_third_party_api_packages_provided_by_this_feature) is no longer compatible with previous versions. Applications will need to be updated if they extend these classes. The list below contains the method changes: 

- org.apache.myfaces.shared.renderkit.html.HtmlTextareaRendererBase
   - protected method encodeTextArea removed, and encodeBegin added
   - encodeTextArea changed to encodeEnd
- org.apache.myfaces.shared.renderkit.html.HtmlCheckboxRendererBase
   - encodeBegin added
- org.apache.myfaces.shared.renderkit.html.HtmlSecretRendererBase
   - encodeBegin added
- org.apache.myfaces.shared.renderkit.html.HtmlTextRendererBase
   - encodeBegin added

**Steps to Reproduce**  
Please see the JIRA issues for additional details.

**Expected behavior**  
Please see the JIRA issues for additional details.

**Diagnostic information:**  
 - OpenLiberty Version: 21.0.0.7-23.0.0.6
 - Affected feature(s) faces-3.0
 - Java Version: n/a
 - server.xml configuration: n/a

**Additional context**  
Release Notes: https://issues.apache.org/jira/secure/ReleaseNote.jspa?projectId=10600&version=12350353

### PR DESCRIPTION
**Pull request by volosied**
fixes #21502

Overlay Notes: 
 MYFACES-4431 - NavigationHandlerImpl Class
 MYFACES-4433 - ViewScope Classes
 MYFACES-4394 - JsfArtifactProducer & ImplicitObjectResolver. Missed in 3.0.2, but will be included in 3.0.3. Overlay is kept for this reason.
 MYFACES-4450   - CommonPropertyUtils

### CODE REVIEW

**Comment by volosied** [comment]
#build 

With CD PR to avoid feature check errors: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_MpZtsPnLEe2AJdN4arOZQA

**Comment by volosied** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jsf.2.3_fat,com.ibm.ws.jsf.2.2_fat,io.openliberty.org.apache.myfaces.4.0_fat,com.ibm.ws.jsf_fat_lWAS_faces3.0

**Comment by volosied** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jsf.2.3_fat,com.ibm.ws.jsf.2.2_fat,io.openliberty.org.apache.myfaces.4.0_fat,com.ibm.ws.jsf_fat_lWAS_faces3.0

**Review by pnicolucci — COMMENTED** [review]
Overall this looks good. I did notice there was a JSF failure in the personal build. Please check that.

**Review by pnicolucci — COMMENTED** [review]
Missing updates to `dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml`

**Comment by volosied** [comment]
The one JSF failure (testELResolutionImplicitObjects_EE9_FEATURES) was caused by MYFACES-4394. I thought the fix was in 3.0.2, but it's not.  I added the overlay back in and we can remove it once we update to 3.0.3.  See `https://github.com/apache/myfaces/pull/282`

**Comment by volosied** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jsf.2.3_fat,com.ibm.ws.jsf.2.2_fat,io.openliberty.org.apache.myfaces.4.0_fat,com.ibm.ws.jsf_fat_lWAS_faces3.0

**Comment by volosied** [comment]
Latest build running: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_yiMLQAZiEe6Gnsx4pF5sWA&tab=com.ibm.team.build.web.ui.internal.editors.result.overview.OverviewPage

**Comment by volosied** [comment]
#libby

**Review by pnicolucci — APPROVED** [review]

**Pull request merged**
