### PR TITLE
MicroProfile OpenTracing 2.0 implementation

### PR DESCRIPTION
**Pull request by fmhwong**
MicroProfile OpenTracing 2.0 implementation.

- Created a new feature `mpOpenTracing-2.0`.
- Updated OpenTracing API from 0.31.0 to 0.33.0.  This is a breaking change and migration is required for customer applications.
- Updated MicroProfile dependencies versions

### CODE REVIEW

**Comment by dmuelle** [comment]
HI @fmhwong do the English nlsprops files require ID review at this time?

**Comment by fmhwong** [comment]
@dumelle They are the same as 1.3 so no review is needed.

**Comment by andrea-pichler** [comment]
Completed the requested L2 message review

**Comment by fmhwong** [comment]
Closing.

**Pull request closed without merging**
