### PR TITLE
Update testJavaTimeSupport to check for narrow no break space in Java 20

### LINKED ISSUE #24009: Update JSF23CDIGeneralTests#testJavaTimeSupport to Support nnbsp in Java 20
Java 20 Updated to [CLDR 42]( https://cldr.unicode.org/index/downloads/cldr-42) which includes the following change: 

 - Large-scale normalization of different kinds of spaces (see Migration) 
  -  https://unicode-org.atlassian.net/browse/CLDR-14032
  
This means that a new space is used when formatting times.  Specifically between the minutes and AM/PM markers. Java 19 and earlier used a regular space (`U+0020`) while Java 20 now uses a narrow no break space (`U+00A0`). This causes our tests to fail as they don't match the exact expectations. 
  
 See assertions in the code here: https://github.com/OpenLiberty/open-liberty/blob/e09e937bd8e87ee850c82fc5b6f8a50a736edb28/dev/com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/tests/JSF23CDIGeneralTests.java#L655-L661
 
 Defects: 294162 & 293657

### PR DESCRIPTION
**Pull request by volosied**
fixes #24009

### CODE REVIEW

**Comment by volosied** [comment]
Java 20 Build: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_9sf0YJkxEe2YL83b0ePHDw (accidentally set com.ibm.ws.jsp.2.3_fat instead of com.ibm.ws.jsf.2.3_fat, but testJavaTimeSupport should still run as it's a LITE mode test)

**Comment by volosied** [comment]
Java 20 Build Passed: image

**Comment by volosied** [comment]
#build

**Comment by volosied** [comment]
All tests in JSF 2.3 FAT passed, but  unrelated child build timeout caused a failure

**Review by pnicolucci — APPROVED** [review]

**Comment by volosied** [comment]
#libby

**Pull request merged**
