### PR TITLE
Fix Timeout issue

### LINKED ISSUE #9697: Return to LDAP primary server after failover can be delayed
When using an LDAP registry with a returnToPrimary attribute enabled and with backup LDAP servers configured, this error occurred after failing over to a backup server in the case where the primary LDAP server goes down. After the primary server comes up, there are regular checks to see whether we can switch back to using it. However, there was a window of time where we should have returned to the primary but the check was delayed. This problem was found in automated testing.

### PR DESCRIPTION
**Pull request by agiridharan**
fixes #9697

### CODE REVIEW

**Comment by agiridharan** [comment]
#build

**Comment by wraschke** [comment]
#run-libby-bot

**Comment by wraschke** [comment]
#run-libby-bot

**Comment by agiridharan** [comment]
#build

**Comment by agiridharan** [comment]
#run-libby-bot

**Comment by agiridharan** [comment]
#run-libby-bot

**Pull request merged**
