### PR TITLE
Update inject and cdi api

### PR DESCRIPTION
**Pull request by benjamin-confino**
jakarta.inject-api from 2.0.0-RC4 to 2.0.0
jakarta.enterprise.cdi-api from 3.0.0-M4 to 3.0.0
weld-se-core from 4.0.0.Alpha3 to 4.0.0.Beta5
weld-osgi-bundle 4.0.0.Alpha3 to 4.0.0.Beta5

### CODE REVIEW

**Comment by benjamin-confino** [comment]
#build

**Comment by benjamin-confino** [comment]
#build

**Comment by benjamin-confino** [comment]
#build

**Comment by benjamin-confino** [comment]
#build

**Comment by benjamin-confino** [comment]
#run-libby-bot

**Review by tevans78 — APPROVED** [review]

**Comment by wraschke** [comment]
This causes a hard break in `io.openliberty.org.jboss.weld4 io.openliberty.weld.jsf.WeldJSFCheckSumTest.testCheckSumForFacesUrlTransformer` so we have to revert. Please see https://ibm-cloud.slack.com/archives/C30NGUQ9E/p1605209394010500 for more details.

**Comment by volosied** [comment]
When this change is reintroduced it should be contain the new checksums. See here: https://github.com/OpenLiberty/open-liberty/pull/14951

**Comment by tevans78** [comment]
> When this change is reintroduced it should be contain the new checksums. See here: #14951

...and check if the source has changed; if it has, the JSF versions need to be re-merged.

**Pull request merged**
