### PR TITLE
Remove duplicate property name from jwtBuilder scope description

### PR DESCRIPTION
**Pull request by jaimb1**
Addresses https://github.com/OpenLiberty/open-liberty/issues/15820

### CODE REVIEW

**Comment by andrea-mh** [comment]
No message review requested from L2

**Comment by jaimb1** [comment]
Got the confirmation on my signed CLA:

Screen Shot 2021-03-03 at 9 13 09 AM

**Comment by anjumfatima90** [comment]
#build

**Comment by hlhoots** [comment]
#build

**Comment by hlhoots** [comment]
#run-libby-bot

**Comment by anjumfatima90** [comment]
#build

**Review by ayoho — APPROVED** [review]

**Pull request merged**
