### PR TITLE
removing obsolete channelwritetype from metadata and webcontainer properties

### LINKED ISSUE #8395: remove obsolete com.ibm.ws.webcontainer.channelwritetype from Liberty's metadata and web container properties

### PR DESCRIPTION
**Pull request by epj**
fixes #8395

### CODE REVIEW

**Comment by epj** [comment]
@chirp1 I see this is tagged ID review not needed.  Should I take you off as reviewer?

**Comment by skasund** [comment]
L2 message review not required

**Comment by epj** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.webcontainer.servlet.4.0_fat,com.ibm.ws.jsp.2.3_fat,com.ibm.ws.jsf.2.3_fat

**Comment by epj** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.webcontainer.servlet.4.0_fat,com.ibm.ws.jsp.2.3_fat,com.ibm.ws.jsf.2.3_fat

**Comment by epj** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.webcontainer.servlet.4.0_fat,com.ibm.ws.jsp.2.3_fat,com.ibm.ws.jsf.2.3_fat

**Comment by pnicolucci** [comment]
#run-libby-bot

**Comment by epj** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.webcontainer.servlet.4.0_fat,com.ibm.ws.jsp.2.3_fat,com.ibm.ws.jsf.2.3_fat

**Comment by epj** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.webcontainer.servlet.4.0_fat,com.ibm.ws.jsp.2.3_fat,com.ibm.ws.jsf.2.3_fat

**Comment by epj** [comment]
#run-libby-bot

**Comment by epj** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.webcontainer.servlet.4.0_fat,com.ibm.ws.jsp.2.3_fat,com.ibm.ws.jsf.2.3_fat

**Comment by epj** [comment]
The build epj-8524-20191118-1553 has an error unrelated to this change, which an existing defect open.

**Pull request merged**
