### PR TITLE
zip file cache introspector w/ fat tests

### PR DESCRIPTION
**Pull request by bberry1675**
Added a zip file cache introspector to the set of inspections performed on liberty Dump command.

### CODE REVIEW

**Comment by bberry1675** [comment]
#build

**Comment by bberry1675** [comment]
#build

**Comment by bberry1675** [comment]
#build

**Comment by bberry1675** [comment]
#build

**Comment by bberry1675** [comment]
#build

**Comment by bberry1675** [comment]
#build

**Comment by bberry1675** [comment]
#build

**Comment by bberry1675** [comment]
#build

**Comment by bberry1675** [comment]
previous build seems to have failed due to a build issue, running rebuild

**Comment by bberry1675** [comment]
#build

**Comment by bberry1675** [comment]
#build

**Comment by bberry1675** [comment]
## Build Failures
### com.ibm.ws.request.timing_fat
Intermittent failure occurred in one of the spawned child builds. WI 245159 open for problem
### com.ibm.ws.kernel.metatype.helper_fat
WI 264873 problem not related to introspector code. In progress issue #17849.

**Comment by tbitonti** [comment]
For issue:
https://github.com/OpenLiberty/open-liberty/issues/8441

**Pull request merged**
