### PR TITLE
Fix MYFACES-4628

### LINKED ISSUE #26390: Port MYFACES-4628
**Describe the bug**  
A 'value is required' message will appear erroneously if you submit a required select tag where one of the selections is disabled.  In the code below, if you select `Val1` then the message will occur even though only Val3 is disabled. 

This message should not occur. 

**Steps to Reproduce**  
Example code: 
```
       <h:selectOneMenu label="MYFACES-4628" required="true" value="#{someBean.someValue}">
         <f:selectItem itemLabel="Val 1" itemValue="Val1" />
         <f:selectItem itemLabel="Val 2" itemValue="Val2" />
         <f:selectItem itemLabel="Val 3" itemValue="Val3" itemDisabled="true"/> 
       </h:selectOneMenu>
```

**Expected behavior**  
No errors should occur when submitting  required option `Val 1` or `Val 2`.

**Diagnostic information:**  
 - OpenLiberty Version: 23.0.0.3 - 23.0.0.10
 - Affected feature(s) : faces-4.0
 - Java Version: n/a
 - server.xml configuration (WITHOUT sensitive information like passwords)
 - If it would be useful, upload the messages.log file found in `$WLP_OUTPUT_DIR/messages.log`

**Additional context**  
https://issues.apache.org/jira/browse/MYFACES-4628

### PR DESCRIPTION
**Pull request by volosied**
fixes #26390

### CODE REVIEW

**Comment by wraschke** [comment]
Ignore this comment.

**Comment by wraschke** [comment]
#libby

**Comment by volosied** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jsf.2.2_fat,com.ibm.ws.jsf.2.3_fat

**Comment by wraschke** [comment]
#libby

**Comment by wraschke** [comment]
#libby

**Comment by wraschke** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jsf.2.2_fat,com.ibm.ws.jsf.2.3_fat
#libby

**Review by pnicolucci — COMMENTED** [review]
The changes look good. I'd like to see a test case added for this.

**Comment by volosied** [comment]
#build

**Comment by volosied** [comment]
#build

**Comment by volosied** [comment]
semi-colon caused the build to fail :/ 

Restarted the build.

**Comment by volosied** [comment]
Builds looks good -- only 1 unrelated failure in the `io.openliberty.jakarta.concurrency.3.1_fat_tck` FAT

**Comment by volosied** [comment]
#build

**Review by pnicolucci — APPROVED** [review]

**Comment by volosied** [comment]
#libby

**Pull request merged**
