### PR TITLE
Updates for running the Bean Validation tests with Jakarta EE 10 features

### LINKED ISSUE #20500: Ensure BeanValidation testing with EE 10 features
User story:
"As a user of Liberty, I want the current version of Jakarta Bean Validation to work with Jakarta EE 10 so that I can write applications that combine Bean Validation with other Jakarta EE 10 features."

This story is mainly to test the combinations of these features in our automated test.

### PR DESCRIPTION
**Pull request by mswatosh**
fixes #20500 

Updates the bean validation test to repeat with EE10 features

### CODE REVIEW

**Comment by mswatosh** [comment]
#build

**Review by njr-11 — APPROVED** [review]

**Comment by mswatosh** [comment]
#build

**Comment by mswatosh** [comment]
#build

**Comment by mswatosh** [comment]
#build

**Pull request merged**
