### PR TITLE
Add mpMetrics 5.0 integration with Fault Tolerance

### PR DESCRIPTION
**Pull request by Azquelt**
Builds on #22838 and #22857

Add a new MetricRecorder implementation for the MP Metrics 5.0 API. Most of the code is shared with the existing implementation for MP Metrics 3.0+.

Use 4.0.2-RC1 TCK and enable repeat against MP 6.0.

For #22046

### CODE REVIEW

**Comment by Azquelt** [comment]
#build

**Comment by Azquelt** [comment]
Rebased on #22857 which should fix the high memory usage when using Histograms which caused an OOM error in the personal build.

**Comment by Azquelt** [comment]
#libby
#build

**Comment by Azquelt** [comment]
Updated the FT 4.0 + Metrics 5.0 autofeature to be `noship` - it should be set to `beta` at the same time as `mpMetrics-5.0`

**Comment by Azquelt** [comment]
#libby
#build

**Review by Channyboy — APPROVED** [review]

**Comment by Azquelt** [comment]
The 1017 personal build was good.

The earlier 1007 personal build failed due to an RTC connection error and not due to any test failures.

**Pull request merged**
