### PR TITLE
Issue #16478: Remove SharedServer from WCServerHttpUnit

### LINKED ISSUE #16478: Remove SharedServer from WCServerHttpUnit Servlet 3.1 FAT

### PR DESCRIPTION
**Pull request by pnicolucci**
fixes #16478

### CODE REVIEW

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Review by isaacrivriv — APPROVED** [review]
Looks good to me thanks!

**Comment by pnicolucci** [comment]
#run-libby-bot

**Pull request merged**
