### PR TITLE
Port MYFACES-4606 (updated fix)

### LINKED ISSUE #26221: Port MYFACES-4606 (Issuing Element Not Found in Request Parameter Map for Ajax Requests) to Liberty
**Describe the bug**  
Take the following example, which requires a particular button to be pressed for some input.
```
<h:inputText required="#{not empty param[someButton.clientId]} ... />

<h:commandButton id="someButton" value="Submit" binding="#{someButton}">
    <f:ajax event="click" ... />
</h:commandButton>

```
When 'someButton' is pressed, the JSF Javascript logic should include the button's id in the request parameter map during the request (due to the binding attribute). 
If the issuing element is not sent as part of the request, then it can cause the required check to be evaluated improperly. 
This previously worked in MyFaces 2.0, but not in MyFaces 2.2 (or higher).
_Note that only ajax requests were broken._

**Steps to Reproduce**  
See code above. 

**Expected behavior**  
The id of the pressed button should be included in the request parameters. 

**Diagnostic information:**  
 - OpenLiberty Version: All
 - Affected feature(s) jsf-2.2, jsf-2.3, faces-3.0, faces-4.0
 - Java Version: n/a
 - server.xml configuration: n/a

**Additional context**  
https://issues.apache.org/jira/browse/MYFACES-4606
https://stackoverflow.com/questions/14729982/validate-input-as-required-only-if-certain-command-button-is-pressed/14730658#14730658

### PR DESCRIPTION
**Pull request by volosied**
fixes https://github.com/OpenLiberty/open-liberty/issues/26221

EE10 and EE9.1 TCKs pass.

### CODE REVIEW

**Comment by volosied** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jsf.2.3_fat,com.ibm.ws.jsf.2.2_fat

**Comment by dmuelle** [comment]
LIbbybot claims there is an nls.props file to review here but I dont see one. Adding the `Id review not needed` label. If that's not correct, let me know. Thanks

**Comment by posmith** [comment]
L2 message review not required.

**Review by pnicolucci — APPROVED** [review]

**Comment by volosied** [comment]
#libby

**Comment by volosied** [comment]
#Fixes PH55398

**Pull request merged**
