### PR TITLE
Wsoc add eeCompatible

### LINKED ISSUE #13313: Investigate need to add eeCompatible feature to websocket 1.0 / 1.1
The websocket-2.0 feature adds a dependency on the eeCompatible-9.0 feature.

Investigate if we need to add an earlier version of the feature to the older websocket features.

We have similar issues opened for EL: https://github.com/OpenLiberty/open-liberty/issues/13306 and JSP: https://github.com/openliberty/open-liberty/issues/13088

Based on [this](https://www.ibm.com/support/knowledgecenter/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/rwlp_prog_model_supported_combos.html) it looks like websocket-1.0 and 1.1 require compatibility for ee6, ee7 and ee8. The only ee6 feature which isnt compatible with them is servlet-3.0 which we do not have available on OL and is already covered by a singleton feature error on CL. Besides that based on the Java EE Specs, it looks like websocket 1.0 was released in EE7 and websocket 1.1 was released in EE8 however, it looks like websocket-1.1 was added on liberty in EE7 and originally pulls in servlet-3.1 so switching over base eeCompatible to be EE7 to not introduce a breaking change

### PR DESCRIPTION
**Pull request by isaacrivriv**
fixes #13313

Added eeCompatible to wsoc features according to when it was released and which other features it pulls in

### CODE REVIEW

**Comment by isaacrivriv** [comment]
#build

**Comment by isaacrivriv** [comment]
#build

**Comment by isaacrivriv** [comment]
https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_8q_xkBcOEeuFUN9G2T7ZeA&tab=com.ibm.team.build.web.ui.internal.editors.result.overview.OverviewPage reference to build running full all fats

**Comment by isaacrivriv** [comment]
#build

**Comment by isaacrivriv** [comment]
#build

**Review by pnicolucci — APPROVED** [review]

**Comment by pnicolucci** [comment]
#run-libby-bot

**Comment by isaacrivriv** [comment]
#build

**Comment by isaacrivriv** [comment]
#run-libby-bot

**Review by cbridgha — APPROVED** [review]
LGTM

**Pull request merged**
