### PR TITLE
MP OpenAPI 1.0 fixes

### PR DESCRIPTION
**Pull request by arturdzm**

### CODE REVIEW

**Comment by arturdzm** [comment]
#build

**Comment by leochr** [comment]
#build

**Comment by leochr** [comment]
Latest personal build looks good. Failures are in unrelated components(com.ibm.ws.frappe*). https://wasrtc.hursley.ibm.com:9443/jazz/resource/itemOid/com.ibm.team.build.BuildResult/_YeV6sA7HEeiStsw2He7iFw

**Comment by leochr** [comment]
@OpenLiberty/message-reviewer 

Please note that some of the messages are ported from commercial Liberty (link to message file is provided below), so they were previously reviewed (so don't believe need to be reviewed here again). 

Link to commercial Liberty message file: https://github.ibm.com/was-liberty/WS-CD-Open/blob/integration/dev/com.ibm.ws.openapi/resources/com/ibm/ws/openapi/internal/resources/OpenAPIMessages.nlsprops

List of new messages that need review:

OPENAPI_FILTER_LOAD_ERROR=CWWKO1657E: Failed to load OpenAPI filter class: {0}.
 OPENAPI_FILTER_LOAD_ERROR.explanation=Specified OpenAPI filter class could not be found or loaded.
 OPENAPI_FILTER_LOAD_ERROR.useraction=Make sure the class specified exists and implements OASFilter interface.
 
 OPENAPI_MODEL_READER_LOAD_ERROR=CWWKO1658E: Failed to load OpenAPI model reader class: {0}.
 OPENAPI_MODEL_READER_LOAD_ERROR.explanation=Specified OpenAPI model reader class could not be found or loaded.
 OPENAPI_MODEL_READER_LOAD_ERROR.useraction=Make sure the class specified exists and implements OASModelReader interface.
 
 OPENAPI_FILE_PARSE_ERROR=CWWKO1659E: Failed to parse OpenAPI document for application: {0}.
 OPENAPI_FILE_PARSE_ERROR.explanation=Failed to parse OpenAPI document from META-INF folder.
 OPENAPI_FILE_PARSE_ERROR.useraction=Make sure the file is in correct YAML or JSON format.

**Comment by leochr** [comment]
Closing this one since we have another PR that includes all these commits and will be easy to review the messages.
https://github.com/OpenLiberty/open-liberty/pull/2131

**Pull request closed without merging**
