### PR TITLE
Issue #14069: Enable JSF 2.2 tests for Jakarta EE9

### LINKED ISSUE #14069: Enable EE9 RepeatTests in JSF 2.2 FAT Bucket
- Some of them just need expected string to be changed from javax to jakarta.  
- 3.0 changes some of log messages, so some tests  (testBeanValidation11Disabled_EE9_FEATURES)  will need to search for new  text
- Others will need some more investigation (such as the *MyContract_viaURL_MapDirectory tests). 

The following tests will need to be investigated: 
 
Failures: 
```
	testBeanValidation11Disabled_EE9_FEATURES	Failure	2020-09-21-15:38:54:973 The following message was not found in the trace log: MyFaces Bean Validation support disabled
junit.framework.AssertionFailedError: 2020-09-21-15:38:54:973 The following message was not found in the trace log: MyFaces Bean Validation support disabled

	check_default_FACELETS_BUFFER_SIZE_EE9_FEATURES	Failure	2020-09-21-15:39:36:580 No context init parameter 'javax.faces.FACELETS_BUFFER_SIZE' found, using default value '1024'
junit.framework.AssertionFailedError: 2020-09-21-15:39:36:580 No context init parameter 'javax.faces.FACELETS_BUFFER_SIZE' found, using default value '1024'

	Test9_MyContract_viaURL_MapDirectory_EE9_FEATURES	Failure	2020-09-21-15:40:55:230 null
junit.framework.AssertionFailedError: 2020-09-21-15:40:55:230 null

	Test10_MyContract_viaURL_MapDirectory_EE9_FEATURES	Failure	2020-09-21-15:40:55:407 null
junit.framework.AssertionFailedError: 2020-09-21-15:40:55:407 null

	Test11_MyContract_viaMultipleURL_MapSpecific_EE9_FEATURES	Failure	2020-09-21-15:40:55:570 null
junit.framework.AssertionFailedError: 2020-09-21-15:40:55:570 null

	Test12_Contract_viaURL_MapSpecific_EE9_FEATURES	Failure	2020-09-21-15:40:55:735 null
junit.framework.AssertionFailedError: 2020-09-21-15:40:55:735 null

	Test14_MyContract_viaURL_withfView_EE9_FEATURES	Failure	2020-09-21-15:40:56:024 null
junit.framework.AssertionFailedError: 2020-09-21-15:40:56:024 null

	Test15_MyContract_viaURL_StarMapping_EE9_FEATURES	Failure	2020-09-21-15:40:56:184 null
junit.framework.AssertionFailedError: 2020-09-21-15:40:56:184 null

	Test16_MyContract_viaURL_MultipleContract_EE9_FEATURES	Failure	2020-09-21-15:40:56:361 null
junit.framework.AssertionFailedError: 2020-09-21-15:40:56:361 null

	JSF22ClientWindow_TestSimpleLink_EE9_FEATURES	Failure	2020-09-21-15:41:48:034 null
junit.framework.AssertionFailedError: 2020-09-21-15:41:48:034 null

	JSF22ClientWindow_TestSimpleLinkNewWindow_EE9_FEATURES	Failure	2020-09-21-15:41:48:292 null
junit.framework.AssertionFailedError: 2020-09-21-15:41:48:292 null

	JSF22ClientWindow_TestMultipleBasePages_EE9_FEATURES	Failure	2020-09-21-15:41:49:976 null
junit.framework.AssertionFailedError: 2020-09-21-15:41:49:976 null

	testELException_EE9_FEATURES	Failure	2020-09-21-15:42:33:517 null
junit.framework.AssertionFailedError: 2020-09-21-15:42:33:517 null

	testCSRF_EE9_FEATURES	Failure	2020-09-21-15:43:44:946 Invalid response from server. This page does NOT contain the token = This is a protected page. If an app requests this page, it should get an error.
junit.framework.AssertionFailedError: 2020-09-21-15:43:44:946 Invalid response from server. This page does NOT contain the token = This is a protected page. If an app requests this page, it should get an error.

	testFlashEvents_EE9_FEATURES	Failure	2020-09-21-15:46:04:624 The expected number of PostPutFlashValueEvent calls did not occur
junit.framework.AssertionFailedError: 2020-09-21-15:46:04:624 The expected number of PostPutFlashValueEvent calls did not occur

	testBeanValidation11Enabled_EE9_FEATURES	Failure	2020-09-21-15:47:21:585 Correct message not found
junit.framework.AssertionFailedError: 2020-09-21-15:47:21:585 Correct message not found
```

Errors: 

```
testViewStateId_EE9_FEATURES  --    2020-09-21-15:45:07:181 elementName=[*] attributeName=[name] attributeValue=[javax.faces.ViewState]

testPI89168_EE9_FEATURES -- 2020-09-21-15:50:24:564 elementName=[input] attributeName=[name] attributeValue=[javax.faces.ViewState] 
```

### PR DESCRIPTION
**Pull request by pnicolucci**
fixes #14069

Enabling the jsf 2.2 FAT for Jakarta EE9 faces-3.0 feature.

In addition I did some minor clean up of the tests. 

One test in particular `JSF22MiscellaneousTests.java ` was driving a request to the wrong context root for test `testViewScopeBindingSerialize`

### CODE REVIEW

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
PB:https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_B_jgcAXBEeuIgpJAZoWiKQ

**Comment by pnicolucci** [comment]
PB:https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_lXFSoAZZEeuIgpJAZoWiKQ

**Comment by pnicolucci** [comment]
PB: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_PxsW8Ab7EeuIgpJAZoWiKQ

**Comment by pnicolucci** [comment]
PB:https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_qz4ToAc3EeuIgpJAZoWiKQ

**Comment by pnicolucci** [comment]
Latest personal build pointing to ws-cd-open integration branch to avoid issues with the servlet renaming not being in master yet looks good all the JSF 2.2 tests passed 100% in lite and full mode. The only failure is outside of the jsf 2.2 test bucket.

**Review by volosied — APPROVED** [review]
LGTM, thanks!

**Comment by pnicolucci** [comment]
#run-libby-bot

**Pull request merged**
