### PR TITLE
Issue #20400: Create Servlet 6.0 FAT Bucket

### LINKED ISSUE #20400: Create Servlet 6.0 FAT bucket

### PR DESCRIPTION
**Pull request by pnicolucci**
fixes #20400

### CODE REVIEW

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#libby

**Review by volosied — APPROVED** [review]
This looks fine to me

**Comment by pnicolucci** [comment]
Making some minor changes here I'll request a new review when ready after a good personal build

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
#libby #build

**Review by pmd1nh — APPROVED** [review]

**Pull request merged**
