### PR TITLE
Update FeatureList and EsaResourceImpl for Java 23

### PR DESCRIPTION
**Pull request by gjwatts**
- [x] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [x] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [x] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

Update FeatureList and EsaResourceImpl to add Java 23.

Previous version for reference -> https://github.com/OpenLiberty/open-liberty/pull/27590

This PR should not be merged until after the GM build is cut for the release prior to the release that we plan to support Java 23.

### CODE REVIEW

**Comment by gjwatts** [comment]
#build

**Comment by gjwatts** [comment]
#build

**Comment by gjwatts** [comment]
#build

**Comment by gjwatts** [comment]
#build

**Comment by gjwatts** [comment]
#libbybot

**Comment by gjwatts** [comment]
Two failures which are known UI component defects.

**Comment by gjwatts** [comment]
#build

**Review by cbridgha — APPROVED** [review]
Looks good

**Pull request merged**
