### PR TITLE
21243_bootstrap_upgrade.

### LINKED ISSUE #21243: Admin Center upgrade bootstrap
The upgrade isn't as simple as updating the Jars. There are some changes to our CSS that will need to be made. 

1 issue is with .sr_only needs to be migrated to a different CSS class. I suspect there will be other minor issues as well.

### PR DESCRIPTION
**Pull request by sarinjacobsunny**
21243_bootstrap_upgrade.

### CODE REVIEW

**Review by k8vance88 — APPROVED** [review]

**Comment by sarinjacobsunny** [comment]
#build

**Comment by sarinjacobsunny** [comment]
https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=__SjcsAwaEe2vacLbpVXjpQ

**Review by k8vance88 — APPROVED** [review]

**Comment by k8vance88** [comment]
#run-libby-bot

**Comment by sarinjacobsunny** [comment]
Build against WS-CD-Open integration branch(With commented test cases).
https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_phK9YA5yEe2vacLbpVXjpQ&tab=com.ibm.team.build.web.ui.internal.editors.result.overview.OverviewPage

**Comment by sarinjacobsunny** [comment]
#run-libby-bot

**Pull request merged**
