### PR TITLE
Publish less things to build.image

### PR DESCRIPTION
**Pull request by jhanders34**
- Update to not publish test bundles that are not needed to be in the wlp/lib directory
- Update jsonp-2.0 to use the 2.0 bundle instead of the transformed 1.1 bundle.
- Remove com.ibm.ws.org.jose4j.0.5.1 which isn't used any longer.
- Do not publish the non transformed resteasy bundles that are not used.

### CODE REVIEW

**Comment by jhanders34** [comment]
#build

**Comment by jhanders34** [comment]
#libby #build

**Comment by jhanders34** [comment]
#libby #build

**Comment by jhanders34** [comment]
#libby #build

**Comment by jhanders34** [comment]
#libby #build

**Review by cbridgha — APPROVED** [review]
Thanks - changes look great

**Review by dazavala — APPROVED** [review]
Thanks, @jhanders34.  Changes regarding glassfish 2.0 update look correct.

**Review by jvanhill — APPROVED** [review]

**Pull request merged**
