### PR TITLE
Suppressed CloneNotSupportedException For Issue #25830

### PR DESCRIPTION
**Pull request by simysc**
This PR is to suppress the exception called "CloneNotSupportedException" which is caught while trying to clone MessageDigest with algorithm SHA-512 on Liberty.

### CODE REVIEW

**Comment by simysc** [comment]
#build

**Review by una-tapa — CHANGES_REQUESTED** [review]
This code is checking the debug but doing nothing. 

if (tc.isDebugEnabled()) {
                /*
                 * commented out to suppress CloneNotSupportedException
                 * Tr.debug(tc, "CloneNotSupportedException caught while trying to clone MessageDigest with algorithm " + SHA_512
                 * + ". This is pretty unlikely, and we need to get details about the JDK which is in use.",
                 * cnse);
                 */
            }

Can we change it to something like below? 
No check, and add reasons in the comment. 

catch (CloneNotSupportedException cnse) {
           //Implementation of clone is optional in Java. When clone does not work, just return a new instance. 
            return MessageDigest.getInstance(SHA_512);
        }

**Comment by simysc** [comment]
#build

**Review by una-tapa — DISMISSED** [review]
The code change looks good. Thanks, Simy.

**Comment by simysc** [comment]
#Libby

**Comment by simysc** [comment]
#build

**Review by una-tapa — APPROVED** [review]
copyright looks good.

**Comment by simysc** [comment]
#Libby

**Comment by simysc** [comment]
#build

**Comment by simysc** [comment]
#Libby

**Comment by simysc** [comment]
#libby

**Pull request merged**
