### PR TITLE
Issue 1565: Fix exception when parsing faces-config-extension element.

### PR DESCRIPTION
**Pull request by ebreijo**

### CODE REVIEW

**Comment by ebreijo** [comment]
fixes #1565

**Comment by ebreijo** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jsf_fat_jsf2.3,com.ibm.ws.jsf_fat_lWAS_jsf2.3,com.ibm.ws.jsf.2.2_fat_jsf2.3,com.ibm.ws.jsf.2.3_fat,com.ibm.ws.javaee.ddmodel_fat,com.ibm.ws.javaee.ddmodel_bvt

**Comment by pnicolucci** [comment]
The issue in the DDParser.skipSubTree is that it parses out fine what we have inside the <faces-config-extention>, example:

    <faces-config-extension>
        <facelets-template-mapping>
            <url-pattern>/templates/*</url-pattern>
        </facelets-template-mapping>
    </faces-config-extension>

But after finishing checking the ending tag facelets-template-mapping, the next XMLStreamReader is assuming that there are characters between:
        </facelets-template-mapping>
    </faces-config-extension>

As a result, it goes inside the DDParser.skipSubtree again, and when it start processing the last two elements, that is:

    </faces-config-extension>  
</faces-config>

Those two are ending elements, and it never return from the skipSubTree method, resulting in the exception is thrown.

**Comment by ebreijo** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jsf_fat_jsf2.3,com.ibm.ws.jsf_fat_lWAS_jsf2.3,com.ibm.ws.jsf.2.2_fat_jsf2.3,com.ibm.ws.jsf.2.3_fat

**Comment by ebreijo** [comment]
All the JSF 2.3 tests and toleration tests passed, also the ddmodel tests passed. The only error in the build is an invalid test bucket on com.ibm.ws.javaee.ddmodel_bvt but we should be fine integration this fix.

**Pull request merged**
