### PR TITLE
Issue #19785: When calling isValidGroup on a federated SAF registry w…

### LINKED ISSUE #19785: Federated SAF registries can incorrectly claim a SAF user or group is not in the realm when calling `UserRegistry.isValidGroup`
**Describe the bug**  
Calling `UserRegistry.isValidGroup` when using `federatedRegistry-1.0` can result in a CWIML0515E error message that claims the \<GROUP\> is not in the scope of the \<REALM\>, when in fact it is.

```
com.ibm.ws.security.registry.RegistryException: CWIML0515E: The user registry operation could not be completed. The <GROUP> entity is not in the scope of the <REALM> realm. Specify an entity that is in the scope of the configured realm in the server.xml file.
        at com.ibm.ws.security.wim.registry.util.ValidBridge.isValidGroup(ValidBridge.java:215)
        at com.ibm.ws.security.wim.registry.WIMUserRegistry.isValidGroup(WIMUserRegistry.java:455)
        at com.ibm.ws.security.registry.internal.UserRegistryWrapper.isValidGroup(UserRegistryWrapper.java:231)
        ...
```

**Steps to Reproduce**  
Federate a SAF registry and call the `UserRegistry.isValidGroup` method with a group that is in the SAF registry.

**Expected behavior**  
The `UserRegistry.isValidGroup` call should return `true` instead of an exception.

**Diagnostic information:**  
 - OpenLiberty Version: Any
 - Affected feature(s): federatedRegistry-1.0, zosSecurity-1.0 (WebSphere Liberty only)
 - Java Version: Any

**Additional context**  
None.

### PR DESCRIPTION
**Pull request by jvanhill**
…ith a valid group, a RegistryException with a CWIML0515E error message is thrown, incorrectly indicating the valid group is not a member of the realm.

fixes #19785

### CODE REVIEW

**Comment by jvanhill** [comment]
#build

**Comment by jvanhill** [comment]
Canceled previous build to enable running SAF registry fats in a new build.

https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_kFgpMHPjEeyR3udAJ5ctvQ

**Comment by jvanhill** [comment]
#build
#spawn.zos=true

**Comment by jvanhill** [comment]
#libby

**Comment by jvanhill** [comment]
Cancelled previous build, replaced with one that would spawn a zOS build.

https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_pSnAwHk0Eeyxm-wYSNWOrg

**Comment by jvanhill** [comment]
#libby

**Comment by jvanhill** [comment]
Rebuilt after rebasing with more changes made for zOS build.

https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_QebowHlxEeyxm-wYSNWOrg

**Comment by jvanhill** [comment]
Respin due to zOS build machine issues.

https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_Ie5YYHoLEeyxm-wYSNWOrg

**Comment by jvanhill** [comment]
Respun due to zOS and Consul issues.

https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_--9WUHrSEeyxm-wYSNWOrg

**Comment by jvanhill** [comment]
Respun due to zOS and Consul issues.

https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_--9WUHrSEeyxm-wYSNWOrg

**Comment by jvanhill** [comment]
#libby

**Comment by jvanhill** [comment]
https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_jyFncH1mEeykJKbDLxYjRw

**Comment by jvanhill** [comment]
Respun setting fat.buckets.to.run from auto to specify my buckets.

https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_WuDqAH4iEeykJKbDLxYjRw

**Review by kristip17 — APPROVED** [review]

**Pull request merged**
