### PR TITLE
MYFACES-4495

### LINKED ISSUE #23295: MYFACES-4495
https://issues.apache.org/jira/browse/MYFACES-4495

### PR DESCRIPTION
**Pull request by pnicolucci**
fixes #23295
https://issues.apache.org/jira/browse/MYFACES-4495

### CODE REVIEW

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
#libby #build

**Review by volosied — APPROVED** [review]
Looks good!

**Pull request merged**
