### PR TITLE
21541 Reintroduce 21411: Artifact error message updates

### PR DESCRIPTION
**Pull request by tbitonti**
PR for issue #21541: Reintroduce 21411, with fixes.

### CODE REVIEW

**Comment by tbitonti** [comment]
#build

**Review by cbridgha — APPROVED** [review]
Looks good

**Review by helyarp — COMMENTED** [review]
Looks good!

**Comment by skasund** [comment]
L2 message review completed

**Comment by tbitonti** [comment]
#build

**Comment by tbitonti** [comment]
#build

**Comment by tbitonti** [comment]
Test failures are unrelated:
```
no component | 86204 | 1 | 1 |   |  
com.ibm.ws.collective.repository_fat FAT tests | 64 | 0 | 1 |   |  
junit.framework.TestSuite | 1 | 0 | 1 | 0 s | 2
com.ibm.ws.collective.repository.fat.CollectiveRegistrationMBeanTest | 1 | 0 | 1 | 0 s | 1
com.ibm.ws.eba.app.runtime_fat FAT tests | 2 | 1 | 0 |   |  
com.ibm.ws.eba.app.runtime.dynamic.fat.TestDynamic | 1 | 1 | 0 | 52 s | 1
testDynamicFeatureOnEE7
```

**Comment by tbitonti** [comment]
#libby

**Pull request merged**
