### PR TITLE
Revert "Revert "Move com.ibm.ws.ui_fat test bucket to open liberty""

### PR DESCRIPTION
**Pull request by lavenal**
Reverts OpenLiberty/open-liberty#21621

### CODE REVIEW

**Comment by lavenal** [comment]
#build

**Comment by lavenal** [comment]
#link 291195

**Comment by lavenal** [comment]
#link 291195

**Comment by lavenal** [comment]
#run-libby-bot

**Comment by lavenal** [comment]
#run-libby-bot

**Review by amyreit — COMMENTED** [review]
looks like all the appropriate versions of each test run correctly now - not sure how we prove it works in a build against only OL where it broke before...

**Review by amyreit — APPROVED** [review]

**Comment by lavenal** [comment]
Fixed #21622

**Pull request merged**
