### PR TITLE
Renaming the Jakarta Bean Validation feature to Jakarta Validation

### LINKED ISSUE #25906: Rename the Jakarta Bean Validation feature to Jakarta Validation
User Story:
"As an administrator, I want Open Liberty features names to align with Jakarta EE feature names, so I can easily identify the specification I want to use"
https://github.com/jakartaee/validation/issues/183

There is a design issue to determine how to handle the rename: https://github.com/OpenLiberty/open-liberty/issues/26604

The design choice was:
`
Use validation-3.1 for the upcoming Jakarta Validation feature. Keep the symbolic name io.openliberty.beanValidation-3.1 to allow ibm.tolerates. We can use WLP-AlsoKnownAs: beanValidation-3.1 to notify users who try to use beanValidation-3.1. This would be the first time we had a feature with an IBM-ShortName which didn't match the symbolicName.
`

### PR DESCRIPTION
**Pull request by gauthamkrishnanibm**
Using validation-3.1 for the upcoming Jakarta Validation feature. Keeping the symbolic name io.openliberty.beanValidation-3.1.

Also renaming the corresponding file and folder.

fixes #25906

### CODE REVIEW

**Comment by gauthamkrishnanibm** [comment]
#build

**Comment by gauthamkrishnanibm** [comment]
#build

**Comment by helyarp** [comment]
`[beanValidation-3.1.properties` files were renamed with no changed. No ID review needed.

**Comment by gauthamkrishnanibm** [comment]
#build

**Comment by gauthamkrishnanibm** [comment]
#build

**Comment by gauthamkrishnanibm** [comment]
#build

**Comment by gauthamkrishnanibm** [comment]
#build

**Comment by gauthamkrishnanibm** [comment]
#build

**Comment by mswatosh** [comment]
#build fat.test.mode=full
#libby

**Comment by mswatosh** [comment]
@cbridgha Can you check the Versionless changes? We got it passing the unit tests, but this is the first time I've worked with the versionless features

**Comment by gauthamkrishnanibm** [comment]
#build fat.test.mode=full
#libby

**Review by cbridgha — APPROVED** [review]
Thanks looks good!

**Review by mswatosh — APPROVED** [review]

**Pull request merged**
