### PR TITLE
Issue #18381: Remove ibm:beta=true for configurable http header metatype

### LINKED ISSUE #18381: Remove ibm:beta="true" from configurable http header metatype when ready

### PR DESCRIPTION
**Pull request by pnicolucci**
fixes #18381

### CODE REVIEW

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#libby

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.webcontainer.servlet.4.0_fat

**Comment by pnicolucci** [comment]
#libby

**Review by mrsaldana — APPROVED** [review]

**Comment by pnicolucci** [comment]
#libby

**Comment by pnicolucci** [comment]
Latest personal build has 1 failure that already has an existing build break defect. The build is good enough for us to merge this PR.

**Pull request merged**
