### PR TITLE
Issue #14973: Update Jakarta Standard Tag Lib API to 2.0.0

### LINKED ISSUE #14973: Pull in the latest API JARs for Jakarta Standard Tag Library 2.0
Pull in the latest Jakarta Standard Tag Library JARS from Eclipse

JSTL: https://repo1.maven.org/maven2/jakarta/servlet/jsp/jstl/jakarta.servlet.jsp.jstl-api/

    Latest release is still 2.0.0-RC1

### PR DESCRIPTION
**Pull request by pnicolucci**
fixes #14973

### CODE REVIEW

**Comment by pnicolucci** [comment]
#build

**Review by volosied — APPROVED** [review]
looks good

**Review by isaacrivriv — APPROVED** [review]
Looks good. Thanks!

**Comment by pnicolucci** [comment]
#run-libby-bot

**Pull request merged**
