### PR TITLE
Fix release builds and fix things building in eclipse

### PR DESCRIPTION
**Pull request by jhanders34**
- Update CoordinatorFactoryServiceTest to be able to run first or on its
own.  If it doesn't run in the same JVM as previous unit tests, it will
fail.
- Update dependabot pom for new changes
- Update .classpath for transaction.cloud_fat.7 to build in eclipse.

### CODE REVIEW

**Comment by jhanders34** [comment]
#build

**Comment by jhanders34** [comment]
I did run all tests individually in com.ibm.ws.wsat.common and only this one failed.

**Comment by jhanders34** [comment]
#build

**Review by tkburroughs — APPROVED** [review]

**Comment by tkburroughs** [comment]
@jhanders34 merged

**Pull request merged**
