### PR TITLE
Slim down HADB tests

### PR DESCRIPTION
**Pull request by jonhawkes**
#build

### CODE REVIEW

**Comment by jonhawkes** [comment]
#build

**Comment by jonhawkes** [comment]
#build

**Comment by jonhawkes** [comment]
#libby #build

**Comment by jonhawkes** [comment]
#libby #build

**Comment by jonhawkes** [comment]
#libby #build

**Review by neilgsyoung — DISMISSED** [review]

**Comment by jonhawkes** [comment]
#libby #build

**Comment by jonhawkes** [comment]
#libby #build

**Comment by jonhawkes** [comment]
#libby #build

**Comment by jonhawkes** [comment]
#libby #build

**Pull request closed without merging**
