### PR TITLE
Consolidate the JPA Container BeanValidation FAT

### PR DESCRIPTION
**Pull request by dazey3**
for #19616

Move the BeanValidation tests from com.ibm.ws.jpa_22_fat
Port the BeanValidation tests from closed liberty
Run tests for jpa and jpaContainer features. Test against Hibernate and OpenJPA

### CODE REVIEW

**Comment by dazey3** [comment]
#build

**Comment by dazey3** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jpa.tests.beanvalidation_jpa_2.0_fat,com.ibm.ws.jpa.tests.beanvalidation_jpa_2.1_fat,com.ibm.ws.jpa.tests.beanvalidation_jpa_2.2_fat,com.ibm.ws.jpa.tests.beanvalidation_jpa_3.0_fat,com.ibm.ws.jpa_22_fat

**Comment by dazey3** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jpa.tests.beanvalidation_jpa_2.0_fat,com.ibm.ws.jpa.tests.beanvalidation_jpa_2.1_fat,com.ibm.ws.jpa.tests.beanvalidation_jpa_2.2_fat,com.ibm.ws.jpa.tests.beanvalidation_jpa_3.0_fat,com.ibm.ws.jpa_22_fat

**Review by jgrassel — APPROVED** [review]

**Comment by dazey3** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jpa.tests.beanvalidation_jpa_2.0_fat,com.ibm.ws.jpa.tests.beanvalidation_jpa_2.1_fat,com.ibm.ws.jpa.tests.beanvalidation_jpa_2.2_fat,com.ibm.ws.jpa.tests.beanvalidation_jpa_3.0_fat,com.ibm.ws.jpa_22_fat

**Comment by dazey3** [comment]
#run-libby-bot

**Pull request merged**
