### PR TITLE
Remove beta guard from MpTelemetry 2.0

### LINKED ISSUE #29445: Remove beta guard from MpTelemetry 2.0
MpTelemetry features need changing from kind=beta to kind=ga

### PR DESCRIPTION
**Pull request by Yas-Franco**
- [x] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [x] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [x] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

Fixes #29445

### CODE REVIEW

**Comment by Yas-Franco** [comment]
#build 
#spawn.fullfat.buckets=io.openliberty.microprofile.telemetry.1.0.internal_fat,io.openliberty.microprofile.telemetry.1.0.internal.container_fat,io.openliberty.microprofile.telemetry.1.0.internal_fat_tck,io.openliberty.microprofile.telemetry.1.1.internal_fat_tck,io.openliberty.microprofile.telemetry.2.0.internal_fat_tck

**Review by pgunapal — CHANGES_REQUESTED** [review]
Need also remove the beta guard from the metatype.xml:
https://github.com/OpenLiberty/open-liberty/blob/integration/dev/io.openliberty.microprofile.telemetry.2.0.logging.internal/resources/OSGI-INF/metatype/metatype.xml

**Comment by Yas-Franco** [comment]
#build
#spawn.fullfat.buckets=io.openliberty.microprofile.telemetry.1.0.internal_fat,io.openliberty.microprofile.telemetry.1.0.internal.container_fat,io.openliberty.microprofile.telemetry.1.0.internal_fat_tck,io.openliberty.microprofile.telemetry.1.1.internal_fat_tck,io.openliberty.microprofile.telemetry.2.0.internal_fat_tck,io.openliberty.microprofile.telemetry.2.0.logging.internal.container_fat,io.openliberty.http.monitor_fat

**Comment by Yas-Franco** [comment]
#libby

**Review by pgunapal — DISMISSED** [review]
Logging side, looks good. I think we can completely remove the `ibm:beta=false` attribute in the metatype.xml, for consistency.

**Review by pgunapal — DISMISSED** [review]
Looks good!

**Comment by yasmin-aumeeruddy** [comment]
#libby
#build
#spawn.fullfat.buckets=io.openliberty.microprofile.telemetry.1.0.internal_fat,io.openliberty.microprofile.telemetry.1.0.internal.container_fat,io.openliberty.microprofile.telemetry.1.0.internal_fat_tck,io.openliberty.microprofile.telemetry.1.1.internal_fat_tck,io.openliberty.microprofile.telemetry.2.0.internal_fat_tck,io.openliberty.microprofile.telemetry.2.0.logging.internal.container_fat,io.openliberty.http.monitor_fat

**Review by pgunapal — APPROVED** [review]
Looks good!

**Comment by Yas-Franco** [comment]
#libby
#build
#spawn.fullfat.buckets=io.openliberty.microprofile.telemetry.1.0.internal_fat,io.openliberty.microprofile.telemetry.1.0.internal.container_fat,io.openliberty.microprofile.telemetry.1.0.internal_fat_tck,io.openliberty.microprofile.telemetry.1.1.internal_fat_tck,io.openliberty.microprofile.telemetry.2.0.internal_fat_tck,io.openliberty.microprofile.telemetry.2.0.logging.internal.container_fat,io.openliberty.http.monitor_fat

**Pull request merged**
