### PR TITLE
Remove spring boot 1.5.x test application project and use the pre-built artifact in FAT

### PR DESCRIPTION
**Pull request by anjumfatima90**
Deleted the com.ibm.ws.springboot.support.version15.test.app test project and used the spring boot 1.5.x application jar downloaded from artifactory.

### CODE REVIEW

**Comment by anjumfatima90** [comment]
Java 8 build
https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_ZJPeoLhFEe2r6re_Zvbagg

**Comment by anjumfatima90** [comment]
#build

**Review by tjwatson — APPROVED** [review]
LGTM

**Comment by anjumfatima90** [comment]
#libby

**Pull request merged**
