### PR TITLE
Split oidc client fat

### PR DESCRIPTION
**Pull request by c00crane**
The com.ibm.ws.security.oidc.client_fat project has been running over the 3 hour full FAT and 1 hour lite FAT limit.
The project has always taken quite some time to run, but, recently, it was enabled to run with EE9.  The transforms have added a good bit to the runtime.  We also added new tests to support additional Signature Algorithms and Encryption.
I'm splitting com.ibm.ws.security.oidc.client_fat into com.ibm.ws.security.oidc.client_fat.1 and com.ibm.ws.security.oidc.client_fat.2 - com.ibm.ws.security.oidc.client_fat will no longer exist.
Even after splitting the FAT, com.ibm.ws.security.oidc.client_fat.1 took quite some time.  The tests that were moved into the com.ibm.ws.security.oidc.client_fat.1 project share many common tests and configs, so, they need to be kept together.  The reason that they take so long to run is that most of the tests cases reconfig the servers.  This is time consuming.
I've replaced the reconfig where possible with the use of unique openidConnectClient and openidConnectProvider/oauthProvider combinations used via invoking specific new servlet names.  The OP and RP server.xml's will now have multiple config instances.

com.ibm.ws.security.oidc.client_fat.1 runs the following classes:

> OidcClientBasicTests.class,
> OidcClientConsentTests.class,
> OidcClientDiscoveryBasicTests.class,
> OidcClientDiscoveryErrorTests.class,
> OidcClientDiscoveryJWTBasicTests.class,

com.ibm.ws.security.oidc.client_fat.2 runs the following classes:

> OidcClientCookieNameTests.class,
> OidcClientLTPACookieTests.class,
> OidcClientSameSiteTests.class,
> OidcClientWasReqURLTests.class,
> OidcClientSignatureAlgTests.class,
> OidcClientEncryptionTests.class

### CODE REVIEW

**Comment by c00crane** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.security.oidc.client_fat.1,com.ibm.ws.security.oidc.client_fat.2, com.ibm.ws.security.oidc.client_fat
Expecting com.ibm.ws.security.oidc.client_fat to be listed as invalid in test results.

**Comment by c00crane** [comment]
#run_libby_bot

**Comment by c00crane** [comment]
#run.libby.bot

**Comment by c00crane** [comment]
#run-libby-bot

**Comment by c00crane** [comment]
#run-libby-bot
#build
#spawn.fullfat.buckets=com.ibm.ws.security.oidc.client_fat.1,com.ibm.ws.security.oidc.client_fat.2, com.ibm.ws.security.oidc.client_fat

**Comment by c00crane** [comment]
#run-libby-bot

**Comment by c00crane** [comment]
#run-libby-bot

**Review by teddyjtorres — APPROVED** [review]

**Comment by c00crane** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.security.oidc.client_fat.1,com.ibm.ws.security.oidc.client_fat.2, com.ibm.ws.security.oidc.client_fat

**Comment by c00crane** [comment]
#run_libby_bot

**Comment by c00crane** [comment]
#run-libby-bot

**Comment by c00crane** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.security.oidc.client_fat.1,com.ibm.ws.security.oidc.client_fat.2, com.ibm.ws.security.oidc.client_fat

**Comment by c00crane** [comment]
#run-libby-bot

**Comment by c00crane** [comment]
The first personal builds failed because the oidc client jar was included in the .classpath of several projects in another release.  Then we hit an issue where discovery wasn't ready when we attempted to use it - I added a method that will try for up to 20 seconds to use the discovery endpoint in the OP before starting the RP.  This should prevent issues where tests fail because we do not have an authorization endpoint (set from the discovery endpoint being called from the RP).

**Pull request merged**
