### PR TITLE
Code cleanup feature repository

### PR DESCRIPTION
**Pull request by jimblye**
Just some code cleanup in FeatureRespository.java

### CODE REVIEW

**Comment by jimblye** [comment]
#build

**Comment by jimblye** [comment]
#build

**Comment by jimblye** [comment]
#build

**Comment by jimblye** [comment]
#build

**Comment by jimblye** [comment]
#libby

**Comment by jimblye** [comment]
#build

**Review by tbitonti — DISMISSED** [review]

**Comment by jimblye** [comment]
#libby

**Review by tbitonti — DISMISSED** [review]

**Comment by jimblye** [comment]
#build

**Comment by hlhoots** [comment]
#build

**Comment by hlhoots** [comment]
Good build. Merging.

**Comment by hlhoots** [comment]
#build

**Review by tbitonti — APPROVED** [review]

**Comment by hlhoots** [comment]
Had a merge conflict. Fixed in UI, and new build kicked off.

**Review by cbridgha — APPROVED** [review]
looks good

**Comment by hlhoots** [comment]
build had 1 oracle db error - unrelated to our changes. merging.

**Comment by hlhoots** [comment]
#libby

**Pull request merged**
