### PR TITLE
Update to Bnd 4.3.1

### PR DESCRIPTION
**Pull request by fritze2**

### CODE REVIEW

**Comment by fritze2** [comment]
#build

**Comment by fritze2** [comment]
#build

**Comment by fritze2** [comment]
#build

**Comment by fritze2** [comment]
#build

**Comment by fritze2** [comment]
#build

**Comment by fritze2** [comment]
#build

**Comment by fritze2** [comment]
#build

**Comment by fritze2** [comment]
#build

**Comment by fritze2** [comment]
Full FAT build:
https://wasrtc.hursley.ibm.com:9443/jazz/resource/itemOid/com.ibm.team.build.BuildResult/_RkX-wDjlEeqMFJAuP7DaNg

The failure in com.ibm.ws.webservices.javaee.common_fat is unique to this PR and is fixed by commit 262e3d7 and tested by personal build:
https://wasrtc.hursley.ibm.com:9443/jazz/resource/itemOid/com.ibm.team.build.BuildResult/_aU03NjuXEeqMye9II9MD-g

**Comment by fritze2** [comment]
#build

**Comment by fritze2** [comment]
#build

**Comment by fritze2** [comment]
#build

**Comment by fritze2** [comment]
#build

**Comment by fritze2** [comment]
Build at https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_HbR3IGLPEeqDwI5U1uUYvg&tab=com.ibm.team.build.web.ui.internal.editors.result.test.TestProvider  completed successfully with two known defects, so I am ready to review.

**Comment by wraschke** [comment]
#run-libby-bot

**Comment by wraschke** [comment]
#run-libby

**Pull request merged**
