### PR TITLE
managed executors with virtual=true in deployment descriptor

### PR DESCRIPTION
**Pull request by njr-11**
managed-executor and managed-scheduled-executor from application.xml and web.xml deployment descriptors configuring virtual=true

- [x] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [x] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [x] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

### CODE REVIEW

**Comment by njr-11** [comment]
#build

**Comment by njr-11** [comment]
#libby

**Comment by wraschke** [comment]
!build

**Comment by wraschke** [comment]
#libby

**Review by jmstephensgit — APPROVED** [review]

**Pull request merged**
