### PR TITLE
CXF Features Logging Bundle

### PR DESCRIPTION
**Pull request by BerksanAtes**
For #9404

### CODE REVIEW

**Comment by BerksanAtes** [comment]
#build

**Comment by BerksanAtes** [comment]
#build

**Comment by BerksanAtes** [comment]
#libbybot

**Comment by BerksanAtes** [comment]
#build

**Comment by BerksanAtes** [comment]
#build

**Review by neuwerk — APPROVED** [review]
Changes look good to me, I assume that you add the `com.ibm.ws.org.apache.cxf.cxf.rt.features.logging.3.2` bundle to the jaxws-2.3 feature and `com.ibm.ws.org.apache.cxf.cxf.rt.features.logging.3.2.jakarta` to xmlWS-3.0 in your next PR?

**Comment by BerksanAtes** [comment]
#libbybot

**Comment by BerksanAtes** [comment]
#run-libby-bot

**Pull request merged**
