### PR TITLE
Redeliver PR for 20358 and 20357: Bulk of logout token creation

### PR DESCRIPTION
**Pull request by ayoho**
For #20699. Redelivering https://github.com/OpenLiberty/open-liberty/pull/20610

### CODE REVIEW

**Comment by ayoho** [comment]
#build

**Comment by ayoho** [comment]
#libby
#build

**Comment by ayoho** [comment]
ID and L2 review not required since messages were already reviewed in https://github.com/OpenLiberty/open-liberty/pull/20610. The only NLS changes since then are to fix two message IDs.

**Review by teddyjtorres — APPROVED** [review]

**Comment by ayoho** [comment]
For #20358

**Pull request merged**
