### PR TITLE
Replace unused fields with 'XXXXXXX' and remove unused fields from FFDC logs

### PR DESCRIPTION
**Pull request by ellen-lau**
fixes: #13635

This is a reiteration of this PR: https://github.com/OpenLiberty/open-liberty/pull/13657 which replaces unused fields with 'XXXXXXX' in JSON Logging. This PR has an additional commit to remove fields `DATEOFFIRSTOCCURENCE`, `COUNT`, `LABEL`, and `SOURCEID` from FFDC logs in both JSON Logging and logstashCollector since those four fields are never used.

#build

### CODE REVIEW

**Comment by ellen-lau** [comment]
#build

**Comment by ellen-lau** [comment]
#build

**Review by donbourne — APPROVED** [review]

**Comment by ellen-lau** [comment]
#build

**Comment by ellen-lau** [comment]
#build

**Comment by ellen-lau** [comment]
Build has one unrelated UI test failure.

**Pull request merged**
