### PR TITLE
update weld to 3.0.4

### PR DESCRIPTION
**Pull request by benjamin-confino**

### CODE REVIEW

**Comment by benjamin-confino** [comment]
#build

**Comment by benjamin-confino** [comment]
I see java.net.BindException: Address already in use maybe just a test glitch?

**Comment by benjamin-confino** [comment]
#build

**Comment by benjamin-confino** [comment]
#build

**Comment by benjamin-confino** [comment]
#build

**Comment by benjamin-confino** [comment]
#build

**Comment by benjamin-confino** [comment]
#build

**Comment by benjamin-confino** [comment]
#build

**Comment by benjamin-confino** [comment]
#build 

Last build was good, but one CDI test failed. EnablingBeansXmlValidationTest. It might be an internal weld change as I see 

> [WARNING ] WELD-001208: Error when validating null@3 against xsd. cvc-elt.1: Cannot find the declaration of element 'WebBeans'. 

Which means it is attempting to validate, and weld sees the file, but it doesn't throw an error.

**Comment by benjamin-confino** [comment]
#build

**Comment by benjamin-confino** [comment]
#build

**Comment by benjamin-confino** [comment]
#build

**Comment by benjamin-confino** [comment]
#build

**Comment by benjamin-confino** [comment]
#build

**Comment by benjamin-confino** [comment]
#build

**Comment by benjamin-confino** [comment]
#build

**Comment by CassTucker** [comment]
@benjamin-confino  legal approves the inclusion of both classfilewriter and weld.  I'll clear with next proposal.

**Comment by CassTucker** [comment]
Legal approves this move from weld 3.0.3 to 3.0.5.. thanks for letting me know of the change

**Pull request merged**
