### PR TITLE
testMultiSharedNonDurableConsumer_SecOff test infrastructure stall

### PR DESCRIPTION
**Pull request by AndrewDJBanks**

### CODE REVIEW

**Comment by AndrewDJBanks** [comment]
fixes #16565

**Comment by AndrewDJBanks** [comment]
#build

**Comment by AndrewDJBanks** [comment]
#build

**Review by sakerl — APPROVED** [review]

**Comment by AndrewDJBanks** [comment]
#libbybot

**Comment by AndrewDJBanks** [comment]
#build

**Comment by AndrewDJBanks** [comment]
#build

**Pull request merged**
