### PR TITLE
Issue #11940: Final Jakarta Annotation API

### LINKED ISSUE #11940: Update jakarta.annotation API version from RC1 to final
Initial API delivery was with RC1. Once the final version is approved and published, need to update to the final version.

### PR DESCRIPTION
**Pull request by tkburroughs**
Update the Jakart Annotation API to final version

fixes #11940

### CODE REVIEW

**Comment by tkburroughs** [comment]
#build

**Review by brideck — APPROVED** [review]

**Comment by tkburroughs** [comment]
#build

**Comment by tkburroughs** [comment]
#build

**Comment by tkburroughs** [comment]
#run-libby-bot

**Pull request merged**
