### PR TITLE
Create cdi 3.0

### PR DESCRIPTION
**Pull request by tevans78**
#build

### CODE REVIEW

**Comment by tevans78** [comment]
#build
#run-libby-bot

**Comment by tevans78** [comment]
#build
#libby-bot

**Comment by tevans78** [comment]
#build
#libby-bot

**Comment by tevans78** [comment]
#build
#libby-bot

**Comment by andrea-pichler** [comment]
No message review requested from L2

**Comment by tevans78** [comment]
#build
#run-libby-bot

**Comment by tevans78** [comment]
#build

**Comment by tevans78** [comment]
#run-libby-bot
I'm rolling the dice on this one ... although there are more failures than I would like in the PB, I don't think any are related to this PR and I want to get it in soon to avoid other clashes!

**Pull request merged**
