### PR TITLE
Fix method isDefaultRecoveryLog

### PR DESCRIPTION
**Pull request by dazavala**
Remove the method and fix corresponding test server to use the exact default value specified in transaction metatype.

### CODE REVIEW

**Comment by dazavala** [comment]
#build

**Comment by dazavala** [comment]
#libby

**Comment by dazavala** [comment]
#build
There were some unxpected FFDCs for XAExceptions in the com.ibm.ws.wsat_fat.ssl.misroute FAT tests.  The symptoms resemble some existing non-reproducible breaks.  Attempting another build and local FAT runs.

**Comment by dazavala** [comment]
#build

**Comment by dazavala** [comment]
#build

**Comment by dazavala** [comment]
[InstantOn build](https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_y7M-0HHnEe6LyICjST0JEw&tab=com.ibm.team.build.web.ui.internal.editors.result.overview.OverviewPage) passed as well. @jonhawkes This solution is ready for review.

**Comment by dazavala** [comment]
#libby

**Review by jonhawkes — APPROVED** [review]

**Pull request merged**
