### PR TITLE
Update Eclipselink from 4.0.1 to 4.0.2.

### PR DESCRIPTION
**Pull request by jgrassel**
EclipseLink 4.0.2 was released two weeks ago., so updating the Eclipselink used by the 'jpa-3.1' feature to the newer level.  Don't forget to grab the assets from maven central and upload them to artifactory before running a build.

for #27500

### CODE REVIEW

**Comment by jgrassel** [comment]
@tkburroughs

**Comment by tkburroughs** [comment]
@jgrassel Thanks.  I suspect the overlay files will need to be merged with the 4.0.2 level; will look into it.

**Comment by jgrassel** [comment]
I see that Jared delivered a few changes to the ASM Factory & related classes as overlays in the Open Liberty repo in `io.openliberty.persistence.3.1.thirdparty`, which I do not see in the current state of EclipseLink's main branch.  So these changes still need to be integrated into EclipseLink.

If Jared wants to create a Pull Request on EclipseLink for the performance changes he made, I'll be happy to review and commit it for him.

**Comment by tkburroughs** [comment]
Correct, the changes in the open-liberty overlay files will eventually need to be delivered back to eclipselink.  However, in the meantime, in order to move open-liberty up to eclipselink 4.0.2, since 4.0.2 updated some of the classes in the overlay, the changes from Jared (i.e., [PR 25507](https://github.com/OpenLiberty/open-liberty/pull/25507)) will need to be applied to the new versions from 4.0.2... updating the overlay along with the change to consume the new 4.0.2 level.  We will look into getting that done.

**Comment by jgrassel** [comment]
I took a look at the history of the overlay files in 4.0.2, and spotted two files which were updated in 4.0.2.  I've updated the overlays with an additional commit to this PR.

**Comment by anija-anil** [comment]
#build

**Comment by jgrassel** [comment]
@tkburroughs Given #25695 should I close this PR?

**Comment by tkburroughs** [comment]
@jgrassel No, keep this PR open; I believe we will merge it.  At this time, we are unable to use `#build` for a PR from an external contributor, but I think we should be able to merge it once we are happy with the build results.  Should be next week.

**Comment by jgrassel** [comment]
Not sure what Libby's complaining about, I signed the CLA a good while ago, it even stamped the label.

**Comment by tkburroughs** [comment]
That is a general message indicating BOTH must be true; you are fine on CLA. Currently PRs created by external contributors cannot go through the automated build process, so we must create another PR with the same commits in order to build & test.  Once completed, then the original PR may be merged.  The goal is to improve this process in the future to make it easier.

**Comment by jgrassel** [comment]
Now like I said, my offer to integrate Jared's changes into ECL remains open, all he needs to do is just create a PR on the EclipseLink project, I'll review and merge it.  I just want him to get credit for his work.

**Comment by tkburroughs** [comment]
#libby

**Review by tkburroughs — APPROVED** [review]

**Comment by tkburroughs** [comment]
Testing completed using cherry-pick pr : https://github.com/OpenLiberty/open-liberty/pull/25695

**Pull request merged**
