### PR TITLE
Make ORBWrapperInternal an ApplicationPrereq

### PR DESCRIPTION
**Pull request by joe-chacko**
#build

### CODE REVIEW

**Comment by joe-chacko** [comment]
@ngmr spotted an omission, which I've now redressed.
#build

**Comment by joe-chacko** [comment]
#build #run-libby-bot

**Comment by ngmr** [comment]
#build

**Comment by joe-chacko** [comment]
Added a user registry to fatTestPorts.xml
#build again

**Comment by joe-chacko** [comment]
Added a user to the user registry.
#run-libby-bot
#build

**Comment by joe-chacko** [comment]
Adding a UserRegistry to fatTestPorts failed because it clashed with the quickStartSecurity entry in other tests.
We've now added individual quickStartSecurity entries to the server configs for the affected transactions tests.
#run-libby-bot
#build

**Comment by joe-chacko** [comment]
#run-libby-bot
#build

**Comment by joe-chacko** [comment]
Other test fixes are now ready, so #build again and while you are at it, #run-libby-bot

**Comment by joe-chacko** [comment]
There were fewer test failures in the latest build.
The remaining failures are at least in part due to the use of local LDAP servers.
I have re-spun the build with the local ldap setting turned off (so it can use a remote LDAP server).
The re-spun build is here:
https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_-MY5ECdQEeyWeMDU9jagxQ

**Comment by tevans78** [comment]
@joe-chacko is this still an active PR? Does it still need approval?

**Comment by joe-chacko** [comment]
> @joe-chacko is this still an active PR? Does it still need approval?

It is still under development. I've marked the PR as draft to make that clear.

**Comment by joe-chacko** [comment]
#build

**Comment by joe-chacko** [comment]
This work will be delivered under another PR

**Pull request closed without merging**
