### PR TITLE
grpc: SSL context should not be applied to plain connections

### LINKED ISSUE #13796: SSL context should not be applied to a plain connection
An ffdc entry is generated when running gRPC with java 8. The problem occurs since SSL context is applied to a non-secure plain connection. Currently there's a workaround to suppress the expected exception. 

A [link](https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.workitem.viewWorkItem&id=277526) to the respective RTC issue.

```
Stack Dump = java.lang.IllegalStateException: Could not find TLS ALPN provider; no working netty-tcnative, Conscrypt, or Jetty NPN/ALPN available
        at io.grpc.netty.shaded.io.grpc.netty.GrpcSslContexts.defaultSslProvider(GrpcSslContexts.java:233)
        at io.grpc.netty.shaded.io.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:144)
        at io.grpc.netty.shaded.io.grpc.netty.GrpcSslContexts.forClient(GrpcSslContexts.java:93)
        at io.openliberty.grpc.internal.client.security.ssl.LibertyGrpcClientSSLSupport.getOutboundClientSSLContext(LibertyGrpcClientSSLSupport.java:99)
        at io.openliberty.grpc.internal.client.LibertyManagedChannelProvider.addLibertySSLConfig(LibertyManagedChannelProvider.java:84)
        at io.openliberty.grpc.internal.client.LibertyManagedChannelProvider.configureLibertyBuilder(LibertyManagedChannelProvider.java:66)
        at io.openliberty.grpc.internal.client.LibertyManagedChannelProvider.builderForAddress(LibertyManagedChannelProvider.java:51)
        at io.openliberty.grpc.internal.client.LibertyManagedChannelProvider.builderForAddress(LibertyManagedChannelProvider.java:33)
        at io.grpc.ManagedChannelBuilder.forAddress(ManagedChannelBuilder.java:39)
        at com.ibm.ws.grpc.fat.helloworld.client.HelloWorldClientServlet.startService(HelloWorldClientServlet.java:42)
        at com.ibm.ws.grpc.fat.helloworld.client.HelloWorldClientServlet.doPost(HelloWorldClientServlet.java:99)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:706)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:791)
        at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1230)
        at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:729)
        at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:426)
        at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1226)
        at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1010)
        at com.ibm.ws.webcontainer.servlet.CacheServletWrapper.handleRequest(CacheServletWrapper.java:75)
        at com.ibm.ws.webcontainer40.servlet.CacheServletWrapper40.handleRequest(CacheServletWrapper40.java:83)
        at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:936)
        at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.run(DynamicVirtualHost.java:279)
        at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink$TaskWrapper.run(HttpDispatcherLink.java:1134)
        at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.wrapHandlerAndExecute(HttpDispatcherLink.java:415)
        at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.ready(HttpDispatcherLink.java:374)
        at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:577)
        at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleNewRequest(HttpInboundLink.java:511)
        at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.processRequest(HttpInboundLink.java:359)
        at com.ibm.ws.http.channel.internal.inbound.HttpICLReadCallback.complete(HttpICLReadCallback.java:70)
        at com.ibm.ws.tcpchannel.internal.WorkQueueManager.requestComplete(WorkQueueManager.java:504)
        at com.ibm.ws.tcpchannel.internal.WorkQueueManager.attemptIO(WorkQueueManager.java:574)
        at com.ibm.ws.tcpchannel.internal.WorkQueueManager.workerRun(WorkQueueManager.java:958)
        at com.ibm.ws.tcpchannel.internal.WorkQueueManager$Worker.run(WorkQueueManager.java:1047)
        at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:239)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.lang.Thread.run(Thread.java:812)
```

### PR DESCRIPTION
**Pull request by annaguri**
fixes #13796

### CODE REVIEW

**Comment by annaguri** [comment]
#build

**Comment by annaguri** [comment]
#build

**Comment by annaguri** [comment]
#run-libby-bot

**Review by wtlucy — APPROVED** [review]

**Comment by annaguri** [comment]
The build failures are not related to this PR. The errors are in another package Merging the PR.

**Pull request closed without merging**
