### PR TITLE
Get Eclipse building again and other fixes

### PR DESCRIPTION
**Pull request by jhanders34**
- Remove non existent / empty source folders from .classpath files
- Update to include generated source directory for hibernate generated code so that things build in eclipse without having to run a gradle build
- Update to mark wsoc.2.1 bundle as Java 11 compilation and wsoc-2.2 bundle as Java 17 compilation in bnd.bnd and eclipse files
- Add missing .settings files to new telemetry logging project

### CODE REVIEW

**Comment by jhanders34** [comment]
#build

**Comment by jhanders34** [comment]
#build

**Review by volosied — APPROVED** [review]
Looks good -- thanks!

**Comment by jhanders34** [comment]
#libby

**Review by KyleAure — APPROVED** [review]

**Review by pgunapal — APPROVED** [review]
LGTM - Thanks!

**Pull request merged**
