### PR TITLE
Invalidate cached config when an error or warning occurs

### PR DESCRIPTION
**Pull request by brenthdaniel**
Invalidate the configuration cache by setting the timestamp to '-1' when an error or warning during processing occurs.

### CODE REVIEW

**Comment by brenthdaniel** [comment]
#build

**Comment by brenthdaniel** [comment]
#15818

**Comment by brenthdaniel** [comment]
#build

**Review by hlhoots — APPROVED** [review]
LGTM.

**Review by jimblye — APPROVED** [review]

**Comment by brenthdaniel** [comment]
#run-libby-bot

**Pull request merged**
