### PR TITLE
Start using Jakarta Data API 1.0.0-RC1

### PR DESCRIPTION
**Pull request by KyleAure**
Start using Jakarta Data 1.0.0-RC1 released here https://github.com/jakartaee/data/issues/631

### CODE REVIEW

**Review by njr-11 — DISMISSED** [review]

**Comment by KyleAure** [comment]
#build

**Comment by KyleAure** [comment]
#libby - recheck headers
#build - personal build

**Comment by KyleAure** [comment]
#libby - recheck headers
#build - personal build

**Comment by KyleAure** [comment]
#libby - recheck headers
#build - personal build

**Review by njr-11 — APPROVED** [review]

**Pull request merged**
