### PR TITLE
Adjusting AuthUtil to process trailing whitespace

### LINKED ISSUE #30027: Adjust AuthUtil to Handle Missing Trailing Whitespace
**Problem Description**  

This issue addresses a problem in the `getBearerTokenFromHeader` method, where the method behaves incorrectly if the `Authorization ` header is lacking a trailing whitespace after the authentication scheme (e.g, "Bearer" as opposed to "Bearer "). 

In the current implementation, the method expects the `rawHeaderValue` (matching the value of the `Authorization` header) to start with the `scheme` including a trailing whitespace. However, some HTTP libraries trim trailing whitespaces from header values, resulting in the rawHeaderValue being "Bearer". When this happens, the method fails to recognize the scheme, leading to unintended failures.

**Additional Context**

[RFC 6750](https://datatracker.ietf.org/doc/html/rfc6750#section-2.1) defines the OAuth 2.0 Authorization Framework as:

`Authorization = "Bearer" 1*SP b64token`

The scheme "Bearer" is followed by a space and then the token. However according to [RFC 7320](https://datatracker.ietf.org/doc/html/rfc7230#section-7), there flexibility in whitespace handling. It specifies that HTTP headers can include optional whitespace (OWS). Clients or intermediaries may omit or trim such whitespaces to improve robustness. 

Resolves: #30025

### PR DESCRIPTION
**Pull request by mrsaldana**
- [x] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [x] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [x] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

Fixes #30027

### CODE REVIEW

**Comment by mrsaldana** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.security.social_fat.okdServiceLogin

**Comment by mrsaldana** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.security.social_fat.okdServiceLogin

**Review by isaacrivriv — APPROVED** [review]
Nice catch here, thanks!

**Review by ayoho — APPROVED** [review]

**Comment by mrsaldana** [comment]
#run-libby-bot

**Pull request merged**
