### PR TITLE
28206 - Server Config - Source -  violations on a11y checkpoint 1.4.3

### PR DESCRIPTION
**Pull request by aknguyen7**
update color contrast ratio for a1y11 violation server config - source 
fix [28206](https://github.ibm.com/websphere/WS-CD-Open/issues/28206)

### CODE REVIEW

**Review by steven1046 — APPROVED** [review]

**Comment by aknguyen7** [comment]
#build

**Comment by aknguyen7** [comment]
#build

**Comment by aknguyen7** [comment]
#build

**Comment by aknguyen7** [comment]
#build

**Comment by aknguyen7** [comment]
#build

**Comment by aknguyen7** [comment]
#build

**Comment by aknguyen7** [comment]
#build

**Comment by aknguyen7** [comment]
green build, all ui tests passed

image

image

image

**Pull request merged**
