### PR TITLE
Do not reprocess config files on restore from file monitor

### PR DESCRIPTION
**Pull request by tjwatson**

### CODE REVIEW

**Comment by tjwatson** [comment]
#build

**Comment by tjwatson** [comment]
#build

**Comment by dazavala** [comment]
Build Liberty Personal Build - EBC tjwatson-27884-20240311-0853 - Looks good.  Three breaks: two existing in springBoot and Library FAT, one new break in UI but the symptom is intermittent in the FAT bucket.

Waiting for InstantOn build [tjwatson-OL27884-20240311-0849](https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_Dg4K4N-1Ee62Qc2Tit17uw)

**Comment by dazavala** [comment]
#build

**Comment by dazavala** [comment]
The personal has an unaccounted hard break in `com.ibm.ws.grpc_fat - ConsumerEndpointFATServlet.testGetMultiAppsInfo_EE10_FEATURES`.  The symptom has been reproducing in this FAT suite since March 11 and is not related to these changes.

**Review by dazavala — APPROVED** [review]
LGTM.

**Pull request merged**
