### PR TITLE
Update Server Working Dir test cases

### PR DESCRIPTION
**Pull request by hlhoots**
#build

### CODE REVIEW

**Comment by hlhoots** [comment]
#build

**Comment by hlhoots** [comment]
This PR is required for #15128

**Comment by hlhoots** [comment]
windows build: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_KKSYIFQ4EeysneUx1bJGow

jdk 17 hotspot build: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_wldTAFQ3EeysneUx1bJGow&tab=com.ibm.team.build.web.ui.internal.editors.result.overview.OverviewPage

**Review by brenthdaniel — APPROVED** [review]

**Comment by hlhoots** [comment]
java 17 hotspot build was good.

**Review by jimblye — APPROVED** [review]

**Comment by jimblye** [comment]
#build 
#libby

**Comment by hlhoots** [comment]
personal and windows builds good.  merging.

**Pull request merged**
