### PR TITLE
The WebContainer properties may not be updated accordingly 

### LINKED ISSUE #14174: The WebContainer properties may not be updated accordingly.
The WebContainer properties may not be updated accordingly during the dynamic server restarting.

Scenario:

1. A WebContainer's custom property A, which has a default value of true, is set to false in the server.xml
2. After the initial server started, property A is explicitly deleted/removed from server.xml.  This causes a soft (or implicit) server restart due to configuration changed.
3. Upon restarted, property A retains its false value instead of the default true value.

This problem does not happen if:
1. The server is explicitly stopped and started after the configuration is modified.
2. OR property A is explicitly changed its value (i.e set to true in this case), and server is implicitly restarted.

### PR DESCRIPTION
**Pull request by pmd1nh**
fixes #14174

### CODE REVIEW

**Comment by pmd1nh** [comment]
#build     
#spawn.fullfat.buckets=com.ibm.ws.webcontainer.servlet.3.1_fat

**Comment by pmd1nh** [comment]
test_DecodeUrlPlusSignDefault_Servlet5 | 1 | 0 | 0 | 0 s | 16
-- | -- | -- | -- | -- | --
test_DecodeUrlPlusSignDefault | 1 | 0 | 0 | 0 s | 17
test_DecodeUrlPlusSign | 1 | 0 | 0 | 14 s | 18
  |   |   |   |   |

**Comment by pmd1nh** [comment]
#build     #spawn.fullfat.buckets=com.ibm.ws.webcontainer_fat,com.ibm.ws.webcontainer.servlet.3.1_fat,com.ibm.ws.webcontainer.servlet.4.0_fat,com.ibm.ws.webcontainer_fat_lWAS,com.ibm.ws.webcontainer_fat_servlet31_webcontainerlWAS,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0.lWAS

**Comment by pmd1nh** [comment]
The static properties in WC class is alive during the update server.xml.  Thus even the WC property was removed/deleted from the server.xml, it is not updated in the static properties.  During the setting, the cached (but obsoleted) entry is detected and used to set the value (instead of the default value).

The problem does not occur if the property was explicitly set (even for the default value).

**Comment by pmd1nh** [comment]
All tests are good.  4 failed tests are unrelated


com.ibm.ws.ui.tool.explore_fat.gui.nd FAT tests | 48 | 4 | 0 |   |  
-- | -- | -- | -- | -- | --
com.ibm.ws.ui.tool.explore.fat.gui.nd.tests.ExploreSearchBarTest | 18 | 3 | 0 | 6 m 38 s | 7
com.ibm.ws.ui.tool.explore.fat.gui.nd.tests.TaggingTest | 1 | 1 | 0 | 1 m 12 s | 5

**Comment by pmd1nh** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.webcontainer_fat,com.ibm.ws.webcontainer.servlet.3.1_fat,com.ibm.ws.webcontainer.servlet.4.0_fat,com.ibm.ws.webcontainer_fat_lWAS,com.ibm.ws.webcontainer_fat_servlet31_webcontainerlWAS,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0.lWAS

**Comment by pmd1nh** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.webcontainer_fat,com.ibm.ws.webcontainer.servlet.3.1_fat,com.ibm.ws.webcontainer.servlet.4.0_fat,com.ibm.ws.webcontainer_fat_lWAS,com.ibm.ws.webcontainer_fat_servlet31_webcontainerlWAS,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0.lWAS

**Comment by pnicolucci** [comment]
#run-libby-bot

**Review by pnicolucci — APPROVED** [review]

**Comment by pnicolucci** [comment]
@pmd1nh are we good to go with this?

**Comment by pmd1nh** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.webcontainer_fat,com.ibm.ws.webcontainer.servlet.3.1_fat,com.ibm.ws.webcontainer.servlet.4.0_fat,com.ibm.ws.webcontainer_fat_lWAS,com.ibm.ws.webcontainer_fat_servlet31_webcontainerlWAS,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0.lWAS

**Comment by pmd1nh** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.webcontainer_fat,com.ibm.ws.webcontainer.servlet.3.1_fat,com.ibm.ws.webcontainer.servlet.4.0_fat,com.ibm.ws.webcontainer_fat_lWAS,com.ibm.ws.webcontainer_fat_servlet31_webcontainerlWAS,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0.lWAS

**Pull request merged**
