### PR TITLE
Updates for session.db

### PR DESCRIPTION
**Pull request by hlhoots**

### CODE REVIEW

**Comment by hlhoots** [comment]
PR for #118 

#build

**Comment by hlhoots** [comment]
#build

**Comment by hlhoots** [comment]
#build

**Comment by hlhoots** [comment]
#build

**Comment by hlhoots** [comment]
#build

**Comment by wraschke** [comment]
#build

**Comment by hlhoots** [comment]
IM build was good (this one had issues in prior builds and now seems resolved).  Personal build had 8 failures in jaxrs, but seem unrelated to the changes made for session.db.

**Comment by hlhoots** [comment]
#build

**Comment by hlhoots** [comment]
#build

**Comment by hlhoots** [comment]
#build  2nd try

**Comment by hlhoots** [comment]
#build 

encountered errors from #271 which has been reverted by #302.  rebase and rebuild.

**Comment by hlhoots** [comment]
Last IM build was good, but didnt like the errors in the PB.  Trying a rebuild of it here: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_RBu26aUWEeee-IeTp-fxEQ

**Comment by hlhoots** [comment]
#build

**Pull request merged**
