### PR TITLE
Replace Weld 3.0.2 with 3.0.3

### PR DESCRIPTION
**Pull request by Azquelt**

### CODE REVIEW

**Comment by ewhoch** [comment]
Sorry for the confusion on the checklist, this is 1 of 6 PRs that were affected by the rollout of checklists for openliberty. It's not quite ready yet and being turned off, so for this PR please ignore the 'yellow' status check below, but do be on the lookout for future changes to how PRs are created and managed.

**Comment by Azquelt** [comment]
#build

**Comment by Azquelt** [comment]
#build

**Comment by Azquelt** [comment]
Last build looks good, one test timed out which looks to be unrelated.

**Comment by tevans78** [comment]
#fixes 2241

**Pull request merged**
