### PR TITLE
Issue #13522: Remove internal on enableMultiReadOfPostData metaType

### LINKED ISSUE #13522: Publish the WebContainer property enableMultiReadOfPostData
This property was introduced by 

https://www.ibm.com/support/pages/apar/PI80313

However, it is not published.

### PR DESCRIPTION
**Pull request by pnicolucci**
fixes #13522

### CODE REVIEW

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Review by wtlucy — APPROVED** [review]
LGTM

**Comment by pnicolucci** [comment]
#run-libby-bot

**Pull request merged**
