### PR TITLE
Migrate JPA20 Spec Test Bucket Query Lock Mode to OL

### PR DESCRIPTION
**Pull request by jgrassel**
Signed-off-by: Joe Grassel <jgrassel@us.ibm.com>

Migrating QueryLockMode test bucket to Open Liberty.

### CODE REVIEW

**Comment by jgrassel** [comment]
#build

**Comment by jgrassel** [comment]
JPA Spec20 test cases passed, fat failures are unrelated.

**Comment by olendvcook** [comment]
@jgrassel merged

**Comment by jgrassel** [comment]
#build

**Pull request merged**
