### PR TITLE
Add remaining basic wsoc tests

### LINKED ISSUE #15122: Migrate remaining basic tests
Following the [issue](https://github.com/OpenLiberty/open-liberty/issues/5207) to port wsoc tests we identified some header tests dependent on some additional features of the SharedServer in CL which weren't available in OL. Need to migrate and update the tests to run on OL

### PR DESCRIPTION
**Pull request by isaacrivriv**
fixes #15122

### CODE REVIEW

**Comment by isaacrivriv** [comment]
#build

**Comment by isaacrivriv** [comment]
#build

**Comment by isaacrivriv** [comment]
#build

**Comment by isaacrivriv** [comment]
#run-libby-bot

**Review by volosied — APPROVED** [review]
LGTM

**Review by billw1024 — APPROVED** [review]
nice job

**Review by pnicolucci — APPROVED** [review]
Good work.

**Pull request merged**
