### PR TITLE
Issue #20416: Add test for getRealPath clarification

### LINKED ISSUE #20416: Servlet 6.0: Clarify the behaviour of getRealPath(String).
Spec issue: `https://github.com/eclipse-ee4j/servlet-api/issues/105`

See "Appendix A: Change Log" here: https://github.com/eclipse-ee4j/servlet-api/blob/master/spec/src/main/asciidoc/servlet-spec-body.adoc

ServletContext Javadoc to review: https://jakarta.ee/specifications/servlet/6.0/apidocs/jakarta.servlet/jakarta/servlet/servletcontext

> getRealPath
> 
>     [String](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/String.html?is-external=true) getRealPath​([String](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/String.html?is-external=true) path)
> 
>     Gets the real path corresponding to the given virtual path.
> 
>     **The path should begin with a / and is interpreted as relative to the current context root. If the path does not begin with a /, the container will behave as if the method was called with / appended to the beginning of the provided path.**
> 
>     For example, if path is equal to /index.html, this method will return the absolute file path on the server's filesystem to which a request of the form http://<host>:<port>/<contextPath>/index.html would be mapped, where <contextPath> corresponds to the context path of this ServletContext.
> 
>     The real path returned will be in a form appropriate to the computer and operating system on which the servlet container is running, including the proper path separators.
> 
>     Resources inside the /META-INF/resources directories of JAR files bundled in the application's /WEB-INF/lib directory must be considered only if the container has unpacked them from their containing JAR file, in which case the path to the unpacked location must be returned.
> 
>     This method returns null if the servlet container is unable to translate the given virtual path to a real path.
> 
>     Parameters:
>         path - the virtual path to be translated to a real path
>     Returns:
>         the real path, or null if the translation cannot be performed

At a glance I think we already behave the way: https://github.com/OpenLiberty/open-liberty/blob/integration/dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/osgi/webapp/WebApp.java#L695

**The path should begin with a / and is interpreted as relative to the current context root. If the path does not begin with a /, the container will behave as if the method was called with / appended to the beginning of the provided path.**

Todo: Do we have any tests that verify this? If not then one should be added to make sure everything is correct.

### PR DESCRIPTION
**Pull request by pnicolucci**
fixes #20416

### CODE REVIEW

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Review by volosied — APPROVED** [review]
Looks good to me

**Comment by pnicolucci** [comment]
#libby

**Pull request merged**
