### PR TITLE
Streamline basic recovery tests

### PR DESCRIPTION
**Pull request by jonhawkes**
#build

### CODE REVIEW

**Comment by jonhawkes** [comment]
#libby #build

**Comment by jonhawkes** [comment]
#build

**Comment by jonhawkes** [comment]
#pb

**Comment by jonhawkes** [comment]
#libby #build

**Comment by jonhawkes** [comment]
#libby #build

**Comment by jonhawkes** [comment]
#libby #build

**Comment by jonhawkes** [comment]
#build #libby #pb

**Review by neilgsyoung — APPROVED** [review]
Looks good

**Pull request merged**
