### PR TITLE
fix split on spaces to get multiple spaces

### PR DESCRIPTION
**Pull request by acdemyers**
Make sure multiple spaces between ciphers are ignored.

### CODE REVIEW

**Comment by acdemyers** [comment]
#build

**Comment by acdemyers** [comment]
fixes #16037

**Comment by bmarwell** [comment]
Hi @acdemyers – thank you very much! I appreciate this PR! :)

**Comment by acdemyers** [comment]
#build

**Review by emilytee — APPROVED** [review]

**Pull request merged**
