### PR TITLE
Port MYFACES-4533  to Faces 4.0

### PR DESCRIPTION
**Pull request by volosied**
for #24145

See `https://github.com/apache/myfaces/pull/510/files#diff-f5343df86175c0d709795a2c7e162b8c35e347e84321649452e98b78186edc27`

### CODE REVIEW

**Comment by volosied** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jsf.2.3_fat,com.ibm.ws.jsf.2.2_fat,io.openliberty.org.apache.myfaces.4.0_fat

**Comment by volosied** [comment]
Seeing HTMLUnit errors in the build like so:
```
Caused by: net.sourceforge.htmlunit.corejs.javascript.EcmaError: TypeError: Cannot find function getAttribute in object [object Text]. (http://localhost:8010/JSF22Miscellaneous/jakarta.faces.resource/faces.js.xhtml?ln=jakarta.faces&stage=Development#5213) 
```

JS:
```

    /**
     * resolve the viewRoot id in a naming container situation
     * (aka ViewState element name is prefixed)
     * @param form
     * @return a string (never null) which is either emtpy or contains the prefix for the ViewState
     * (including the separator)
     */
    _resolveViewRootId: function(form, separatorChar) /*string*/ {
        form = this._Dom.byId(form);
        var _t = this;
        var foundNames = this._Dom.findAll(form, function(node) {
            var name = node.getAttribute("name"); <---------------------------------- Problematic Line
            if(!name || name.indexOf("jakarta.faces.ViewState") <= 0) {
                return false;
            }
            return node;
        }, true);
        if(!foundNames.length) {
            return "";
        }
        return foundNames[0].name.split(separatorChar, 2)[0] + separatorChar;
    },
```
   
Manual test shows no problems.

**Comment by volosied** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jsf.2.3_fat,com.ibm.ws.jsf.2.2_fat,io.openliberty.org.apache.myfaces.4.0_fat

**Comment by volosied** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jsf.2.3_fat,com.ibm.ws.jsf.2.2_fat,io.openliberty.org.apache.myfaces.4.0_fat

**Comment by volosied** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jsf.2.3_fat,com.ibm.ws.jsf.2.2_fat,io.openliberty.org.apache.myfaces.4.0_fat

**Review by pnicolucci — APPROVED** [review]

**Comment by volosied** [comment]
#libby

**Pull request merged**
