### PR TITLE
Ensure consistent handling of Accept-Language header

### PR DESCRIPTION
**Pull request by andymc12**
Specifically this fixes how JAX-RS 2.1 / CXF handles "blank" languages - these should be treated as "und" (undefined).

### CODE REVIEW

**Comment by andymc12** [comment]
#build

**Comment by andymc12** [comment]
Minor tweaks - new #build

**Comment by andymc12** [comment]
Corrected behavior for case where `Accept-Language` header exists, but has no value. New #build

**Comment by andymc12** [comment]
#libby

**Review by WhiteCat22 — APPROVED** [review]

**Comment by andymc12** [comment]
Fixes #18348

**Pull request merged**
