### PR TITLE
Added repeat test to test applications that use the checkpointFATServer

### PR DESCRIPTION
**Pull request by KeenanMcCarthy**
Added rule to perform repeated tests such that the test application will be run as both Java EE 8 and Jakarta EE 9.

### CODE REVIEW

**Comment by KeenanMcCarthy** [comment]
#libby
#build

**Comment by KeenanMcCarthy** [comment]
#build

**Review by tjwatson — APPROVED** [review]
LGTM

**Comment by KeenanMcCarthy** [comment]
#libby

**Pull request merged**
