### PR TITLE
Use mvn wrapper

### LINKED ISSUE #24289: Update TCKs to use mvn wrapper scripts
The TCKs are currently set up to use a copy of mvn which is pre-installed on the build machine. It would be better if they used the mvnw wrapper script which downloads mvn as and when it is needed.

https://github.ibm.com/websphere/WS-CD-Open/issues/26032

### PR DESCRIPTION
**Pull request by tevans78**
Use the wrapper instead of relying on mvn being installed on each test VM

Fixes https://github.com/OpenLiberty/open-liberty/issues/24289

### CODE REVIEW

**Comment by tevans78** [comment]
#build

**Comment by tevans78** [comment]
#build

**Comment by tevans78** [comment]
#build

**Comment by tevans78** [comment]
PB: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_7_OWkMjOEe21SqRkHwL18g

**Comment by tevans78** [comment]
#build

**Comment by tevans78** [comment]
#build

**Comment by tevans78** [comment]
#build

**Comment by tevans78** [comment]
Minimal PB with more debug: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_WXeikMyGEe2yDpyHOcT1OQ

**Comment by tevans78** [comment]
#build

**Comment by tevans78** [comment]
#build

**Review by cbridgha — APPROVED** [review]
looks good

**Review by benjamin-confino — APPROVED** [review]

**Comment by tevans78** [comment]
#libby

**Comment by tevans78** [comment]
Libby isn't responding so forcing the merge.

**Pull request merged**
