### PR TITLE
Initialize tryShellExtensions before using it

### LINKED ISSUE #27398: Server start fails on OS/400
Problem caused by #27005, which rearranged the server script to move functions to the top and main execution path to the bottom.   The "escapeForEval" functions are defined inside an if-then-else block, which gets executed before main.   The "if" statement references a variable that needs to be initialized for OS/400.

### PR DESCRIPTION
**Pull request by jimblye**
Fixes #27398 
It's best to turn off white space when reviewing.  The change is pretty simple.

### CODE REVIEW

**Comment by jimblye** [comment]
#fullphbbeta

**Comment by fritze2** [comment]
#build
#soe.platform.requests="‪Liberty Full FAT (Entire SOE) Build (ISERIES74_POWER10_PPC_IBMJDK8_EBC) - Liberty"

Not sure if this works, but if not, then I will re-request the submitted build and manually add `soe.platform.requests` to it.

**Comment by fritze2** [comment]
It didn't work, so I re-requested it from the RTC dashboard and set these additional properties.
https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_3FGzQLYeEe6cj5m6UcXbGA
```
fat.buckets.to.run=com.ibm.ws.kernel.boot_fat
spawn.fullfat.buckets=com.ibm.ws.kernel.boot_fat
soe.platform.requests=Liberty Full FAT (Entire SOE) Build (ISERIES74_POWER10_PPC_IBMJDK8_EBC) - Liberty
```

**Review by tbitonti — APPROVED** [review]

**Comment by fritze2** [comment]
Last build failed to run on the IBMi platform because of user error in my requesting. The property should've been:
```
soe.platform.requests=ISERIES74_POWER10_PPC_IBMJDK8_EBC
```
Got another request submitted.
https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_5hy5ELbXEe6cj5m6UcXbGA
Edit: And z/OS testing is required, so this additional property is needed to run z/OS packaging steps.
```
spawn.zos=true
```
Another request submitted at:
https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_jrG80LbbEe6cj5m6UcXbGA

**Pull request merged**
