### PR TITLE
Enable Tran Manager startup and initial recovery at checkpoint

### PR DESCRIPTION
**Pull request by dazavala**
Improve InstantOn performance of the transaction feature by enabling the transaction manager to startup and, when possible, to perform initial local recovery during checkpoint.  During restore the transaction mgmt and recovery services must tolerate restart and reconfiguration within a server environment that may change the configuration of recovery log resources, transactional datasources, and transaction feature configuration -- e.g. recoveryId.

### CODE REVIEW

**Comment by dazavala** [comment]
#build
Verify these changes do not regress the transaction feature within a normal server.

**Comment by dazavala** [comment]
#build

**Comment by dazavala** [comment]
@jonhawkes Here's a rundown of the behavior changes in commit [Enable Tran Manager startup and initial recovery at checkpoint](https://github.com/OpenLiberty/open-liberty/pull/26262/commits/51f9f48b79c5b78377275184342f829b873546f2)

1. Start the TransactionManagerService (TMS) during checkpoint.

   - Added method JTMCP.isStartupEnabled() to simplify/encapsulate necessary conditions to start TMS.  Currently TMS is allowed to start/restart in any checkpoint phase and restore, just as it would in a normal server.  Debug info for checkpoint phase was added for serviceability.
 
   - Removed multithreaded restore hook that starts TMS early during restore.

   - Revised TMS.doStartup() back it's original definition and removed method TMS.doStartup0(). 

2. Leave the tranlog dir in checkpoint image to optimize performance. The i/o to create new recovery logs is expensive according to perf team.

   - Removed checkpoint prepare hook that deletes tranlog dir at checkpoint.
   
3. Remove the tranlog dir before new tranlog dir is created whenever transactionLogDirectory changes during the restore config update. 

4. Enable local initial recovery on startup during server checkpoint.

   - Disabled (override) shutdownOnLogFailure during checkpoint to allow checkpoint dump whenever initial local recovery fails.  The failure must be due to inaccessible recovery log resource, because global transactions are still not allowed during checkpoint -- that is, there should be no transactions to recover during checkpoint.  
  
   - Enabled (override) recoverOnStart during checkpoint for default recovery log configuration (i.e. transactionLogDirectory=${server.config.dir}tranlog and datasourceRef not set.)  This is a perf enhancement to do as much work as possible before the checkpoint dump.

   - Added method to detect default recovery log configuration. 

   - Disabled (override) recoverOnStart during checkpoint beforeAppStart whenever datasourceRef is set (SQL recovery log).  Initial local recovery will prematurely trigger the checkpoint dump when getting a connection to the tranlog datasource.

   - Removed override of waitForRecovery as it is no longer necessary.

   - Shutdown the TxTMHelper (TMService) whenever local initial recovery fails during checkpoint. This will force the TMService -- i.e. the recovery director, recovery agents, etc -- to reinitialize during restore using the updated config and env vars within the container environment.

   - Added transition TMState.STOPPED --> TMState.RECOVERY in TxTMHelper to enable restart during restore, after being shutdown/STOPPED in checkpoint. 

   - Allow deep shutdown() to execute during checkpoint when TMState.INACTIVE.  This will ensure deep initialization during restore.  Also, during shutdown skip waiting on the resync semaphore as the current thread will not interrupt (w/o further changes) and eventually fail checkpoint.  Since TMState is INACTIVE, there cannot be a sync in progress.

**Comment by dazavala** [comment]
Build results shown at cognitive build analysis look good, but build is no longer in RTC (?!?).
#build

**Comment by dazavala** [comment]
[Review changes](https://github.com/OpenLiberty/open-liberty/pull/26262/commits/bc0208249b28294c0e79eaf58f01011f29f78402) modify the final solution to not remove the tranlog dir contained in the checkpoint image whenever transactionLogDirectory is updated for checkpoint restore.

**Comment by dazavala** [comment]
#build review changes

**Comment by dazavala** [comment]
#libby

**Comment by dazavala** [comment]
#build
Review changes

**Comment by dazavala** [comment]
#build

**Comment by dazavala** [comment]
#libby

**Comment by dazavala** [comment]
#build

**Review by jonhawkes — APPROVED** [review]

**Comment by dazavala** [comment]
#libby

Passing InstantOn build: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_8xw0sGBWEe6P7Leypp4Wfg.

Passing personal build: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_8xw0sGBWEe6P7Leypp4Wfg

**Pull request merged**
