### PR TITLE
JAX-WS: Increase timeouts for various tests

### PR DESCRIPTION
**Pull request by neuwerk**
This pull request increases the timeouts of a couple of test buckets that have their timeouts set to only 10 seconds and are failing a whole lot of builds for this reason.

### CODE REVIEW

**Comment by neuwerk** [comment]
#build

**Review by arunavemulapalli — APPROVED** [review]

**Comment by neuwerk** [comment]
#build

**Comment by neuwerk** [comment]
#build

**Comment by neuwerk** [comment]
#build

**Comment by neuwerk** [comment]
#build

**Comment by neuwerk** [comment]
#run-libby-bot

**Pull request merged**
