### PR TITLE
Remove duplicate message keys from explore tool

### PR DESCRIPTION
**Pull request by lavenal**
Remove duplicate message key SAVE and NO_APPS_RUNNING

### CODE REVIEW

**Comment by lavenal** [comment]
fixed #19316

**Comment by lavenal** [comment]
#build

**Comment by dmuelle** [comment]
since no new messages are added, adding the "ID Review not Needed" label. If that's not correct, let me know. Thanks

**Comment by lavenal** [comment]
#build

**Comment by lavenal** [comment]
All UI tests passed in the PB.

**Review by k8vance88 — APPROVED** [review]

**Pull request merged**
