### PR TITLE
Fix issue with states getting changes in two new getPolicyConfig methods

### PR DESCRIPTION
**Pull request by emilytee**

### CODE REVIEW

**Comment by emilytee** [comment]
Update the PolicyConfigurationFactory's two new getPolicyConfiguration methods to not change the state as per the spec: 
If at the time of the call, the identified policy context does not exist in the provider, then the policy context
     * will <strong>not</strong> be created in the provider and a null will be returned. No state transition of any kind
     * is allowed to occur, the <code>PolicyConfiguration</code> instance is to be returned as-is.

**Comment by emilytee** [comment]
#run-libby-bot

**Comment by emilytee** [comment]
#build

**Review by jhanders34 — APPROVED** [review]

**Comment by emilytee** [comment]
#build

**Comment by emilytee** [comment]
#run-libby-bot

**Pull request merged**
