### PR TITLE
Move JPA DDL execution code to JPA framework

### PR DESCRIPTION
**Pull request by dazey3**
Consolidate the implementation of the JPA DDL execution code to the common framework

Signed-off-by: Will Dazey <dazeydev.3@gmail.com>

### CODE REVIEW

**Comment by dazey3** [comment]
#build

**Comment by dazey3** [comment]
#build

**Review by jgrassel — APPROVED** [review]

**Comment by dazey3** [comment]
#build

**Comment by dazey3** [comment]
#run-libby-bot

**Comment by dazey3** [comment]
#build

**Comment by dazey3** [comment]
#run-libby-bot

**Pull request merged**
