### PR TITLE
Improve JPA FAT framework

### PR DESCRIPTION
**Pull request by dazey3**
Improvement to the JPA FAT servlet framework to extract the DatabaseManagement application code to another Servlet class. In this way, FAT that don't need the DatabaseManagement application can still use the servlet framework without needing the DBManagement app too.

### CODE REVIEW

**Comment by dazey3** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jpa.tests.spec10.injection.defaultPersistenceUnit_fat,com.ibm.ws.jpa.tests.eclipselink_jpa_2.2_fat,com.ibm.ws.jpa.tests.spec21.cdi_fat

**Review by jgrassel — DISMISSED** [review]
lgtm

**Comment by dazey3** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jpa.tests.spec10.injection.defaultPersistenceUnit_fat,com.ibm.ws.jpa.tests.eclipselink_jpa_2.2_fat,com.ibm.ws.jpa.tests.spec21.cdi_fat

**Review by jgrassel — APPROVED** [review]

**Comment by dazey3** [comment]
#run-libby-bot

**Pull request merged**
