### PR TITLE
Issue #18781: Upgrade Bouncy Castle dependencies from 1.61 to 1.69.

### LINKED ISSUE #18781: Upgrade org.bouncycastle:bcprov-jdk15on to version 1.66 or later
Upgrade org.bouncycastle:bcprov-jdk15on to version 1.66 or later. For example:

```
<dependency>
  <groupId>org.bouncycastle</groupId>
  <artifactId>bcprov-jdk15on</artifactId>
  <version>[1.66,)</version>
</dependency>
```

### PR DESCRIPTION
**Pull request by jvanhill**
fixes #18781 

I have uploaded the following artifacts to Artifactory:
- org.bouncycastle:bcpkix-jdk15on:1.69
- org.bouncycastle:bcprov-jdk15on:1.69
- org.bouncycastle:bcutil-jdk15on:1.69

### CODE REVIEW

**Comment by jvanhill** [comment]
#build

**Comment by jvanhill** [comment]
#build

**Review by andymc12 — APPROVED** [review]
LGTM - thanks @jvanhill!

**Review by kristip17 — APPROVED** [review]

**Comment by jvanhill** [comment]
#libby

**Pull request merged**
