### PR TITLE
Revert "Open com.sun.jndi.dns to jdk.naming.dns module"

### PR DESCRIPTION
**Pull request by gjwatts**
Reverts OpenLiberty/open-liberty#22461

I should have merged the customer's PR #22360 to fix this issue, not my own.

### CODE REVIEW

**Review by tjwatson — APPROVED** [review]

**Comment by gjwatts** [comment]
#build

**Comment by gjwatts** [comment]
#build

**Comment by gjwatts** [comment]
#build

**Comment by gjwatts** [comment]
Unrelated failure in:
```
com.ibm.ws.collective.repository.fat.common.CommonCollectiveRegistrationTest.hostRegister(CommonCollectiveRegistrationTest.java)
```

**Pull request merged**
