### PR TITLE
Servlet61 Add Test for Empty URL Patterns Mapping

### LINKED ISSUE #26488: Servlet 6.1: Correct the wording in section 12.2 since the context path is not always the empty string when a servlet is mapped using context root mapping. Also clarify that context root mapping occurs for URIs with or without the trailing /.
`https://github.com/jakartaee/servlet/issues/300`

### PR DESCRIPTION
**Pull request by pmd1nh**
fixes https://github.com/OpenLiberty/open-liberty/issues/26488

### CODE REVIEW

**Comment by pmd1nh** [comment]
Server has been compliant with this requirement but there is no trivial tests for them.
Add tests to make it clear for this work item.

**Comment by pmd1nh** [comment]
#build      #spawn.fullfat.buckets=io.openliberty.webcontainer.servlet.6.1.internal_fat,io.openliberty.webcontainer.servlet.6.0.internal_fat,com.ibm.ws.webcontainer.servlet.6.0_fat_toleration.lWAS,com.ibm.ws.webcontainer_fat,com.ibm.ws.webcontainer.servlet.3.1_fat,com.ibm.ws.webcontainer.servlet.4.0_fat,com.ibm.ws.webcontainer_fat_part2,com.ibm.ws.webcontainer_fat_servlet31toleration,com.ibm.ws.webcontainer_fat_servlet31toleration_part2,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0_part2,com.ibm.ws.webcontainer_fat_lWAS,com.ibm.ws.webcontainer_fat_servlet31_webcontainerlWAS,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0.lWAS

**Comment by pmd1nh** [comment]
#build 
#spawn.fullfat.buckets=io.openliberty.webcontainer.servlet.6.1.internal_fat

**Comment by pmd1nh** [comment]
#build
#spawn.fullfat.buckets=io.openliberty.webcontainer.servlet.6.1.internal_fat

**Comment by pmd1nh** [comment]
#build

**Comment by pmd1nh** [comment]
#libby

**Review by pnicolucci — APPROVED** [review]

**Comment by pnicolucci** [comment]
#libby

**Pull request merged**
