### PR TITLE
JAX-WS: Negative test was having different exception due to JDK differences

### LINKED ISSUE #24698: Different exception than expected one in negative tests
For negative tests, while waiting to have a `java.security.cert.CertPathBuilderException`, test was getting `sun.security.provider.certpath.SunCertPathBuilderException` due to differences in JDKs. Tests needs to be modified accordingly.

### PR DESCRIPTION
**Pull request by BerksanAtes**
Fixes #24698

### CODE REVIEW

**Comment by BerksanAtes** [comment]
#build

**Comment by BerksanAtes** [comment]
#build

**Comment by BerksanAtes** [comment]
Not a valid solution

**Comment by BerksanAtes** [comment]
#build

**Review by neuwerk — APPROVED** [review]
Looks good to me, thanks @BerksanAtes

**Comment by BerksanAtes** [comment]
#run-libby-bot

**Pull request merged**
