### PR TITLE
Update to Equinox Framework version 3.21.0

### PR DESCRIPTION
**Pull request by tjwatson**
Remove overlays from previous releases

- [x] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [x] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [x] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

### CODE REVIEW

**Comment by tjwatson** [comment]
#build

**Comment by contbld** [comment]
Your personal pipeline request is at https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=bf432809-ff18-4182-bf99-b56228ba802e

Target locations of links might be accessible only to IBM employees.

**Comment by contbld** [comment]
<h3>Code analysis and actions</h3>
DO NOT DELETE THIS COMMENT.

- 6 product code files were changed.- **Please describe in a separate comment how you tested your changes.**
- 1 messages files were changed and need an L2 review.

- @OpenLiberty/message-reviewer Please review.
  - --nlsFiles

**Comment by tjwatson** [comment]
#build

**Comment by tjwatson** [comment]
#build

**Comment by tjwatson** [comment]
#build

**Review by dazavala — APPROVED** [review]
Pulled in the CDS diagnostics and removed the overlay; looks good.  Not sure why the change to classloader parallel registration was necessary, but also looks good.  Approved.

**Comment by tjwatson** [comment]
> Pulled in the CDS diagnostics and removed the overlay; looks good. Not sure why the change to classloader parallel registration was necessary, but also looks good. Approved.

I took the opportunity to bring the overlay of the class loading implementations to be in sync with the Equinox PR.

**Pull request merged**
