### PR TITLE
ignore hnv warnings for hnv disabled in checkpoint fat

### PR DESCRIPTION
**Pull request by karel-harjono**

### CODE REVIEW

**Comment by karel-harjono** [comment]
#build

**Review by tjwatson — DISMISSED** [review]
LGTM,

The change allows the test to pass locally on my InstantOn enabled environment.

**Comment by karel-harjono** [comment]
#build

**Comment by karel-harjono** [comment]
#libby

**Review by tjwatson — DISMISSED** [review]
LGTM

**Comment by karel-harjono** [comment]
#libby

**Review by tjwatson — APPROVED** [review]

**Pull request merged**
