### PR TITLE
Add test for cookie setAttribute SameSite that has precedence over server setting

### PR DESCRIPTION
**Pull request by pmd1nh**
https://github.com/OpenLiberty/open-liberty/issues/24150

### CODE REVIEW

**Comment by pmd1nh** [comment]
#build
#spawn.fullfat.buckets=io.openliberty.webcontainer.servlet.6.0.internal_fat

**Comment by pmd1nh** [comment]
#build
#spawn.fullfat.buckets=io.openliberty.webcontainer.servlet.6.0.internal_fat

**Comment by pmd1nh** [comment]
#build
#spawn.fullfat.buckets=io.openliberty.webcontainer.servlet.6.0.internal_fat

**Review by pnicolucci — APPROVED** [review]

**Comment by pmd1nh** [comment]
#build
#spawn.fullfat.buckets=io.openliberty.webcontainer.servlet.6.0.internal_fat

**Comment by pmd1nh** [comment]
io.openliberty.webcontainer.servlet.6.0.internal_fat FAT tests | 89 | 0 | 0 |   |  
-- | -- | -- | -- | -- | --
io.openliberty.webcontainer.servlet60.fat.tests.Servlet60CookieSetAttributeTest | 4 | 0 | 0 | 1 s | 4
test_cookiePredefinedSetterAndSetAttribute | 1 | 0 | 0 | 1 s | 1
test_cookieOverrideSetterWithSetAttribute | 1 | 0 | 0 | 0 s | 2
test_cookieAddAndSetHeader | 1 | 0 | 0 | 0 s | 3
test_setAttributeSameSitePrecedence | 1 | 0 | 0 | 0 s | 4

**Comment by pmd1nh** [comment]
#libby

**Pull request merged**
