### PR TITLE
Fix Equinox error on Windows with Java 17

### LINKED ISSUE #18753: Fix Equinox error on Windows with Java 17 for single JVM execution with SelfExtractRun
**Describe the bug**
When executing Open Liberty via the SelfExtractRun class in single JVM mode (ie no jvm.options file present) on the Windows platform with Java 17, the server hangs after the kernel starts and no applications load.  There is an error in the workarea/equinox log as shown:

!ENTRY org.eclipse.osgi 4 0 2021-09-21 09:48:47.554
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Cannot support framework extension bundles without a public addURL(URL) or appendToClassPathForInstrumentation(String) method on the framework class loader: com.ibm.ws.org.eclipse.equinox.region_1.0.57.202108311120 [8]
	at org.eclipse.osgi.storage.FrameworkExtensionInstaller.addExtensionContent0(FrameworkExtensionInstaller.java:142)
	at org.eclipse.osgi.storage.FrameworkExtensionInstaller.addExtensionContent(FrameworkExtensionInstaller.java:116)
	at org.eclipse.osgi.internal.loader.SystemBundleLoader$SystemModuleClassLoader.loadFragments(SystemBundleLoader.java:140)
	at org.eclipse.osgi.internal.loader.SystemBundleLoader.loadClassLoaderFragments(SystemBundleLoader.java:122)
	at org.eclipse.osgi.internal.loader.BundleLoader.loadFragments(BundleLoader.java:315)
	at org.eclipse.osgi.container.ModuleWiring.loadFragments(ModuleWiring.java:276)
	at org.eclipse.osgi.container.ModuleContainer.applyDelta(ModuleContainer.java:843)
	at org.eclipse.osgi.container.ModuleContainer.resolveAndApply(ModuleContainer.java:559)
	at org.eclipse.osgi.container.ModuleContainer.resolve(ModuleContainer.java:502)
	at org.eclipse.osgi.container.ModuleContainer.resolve(ModuleContainer.java:491)
	at org.eclipse.osgi.container.ModuleContainer$ContainerWiring.resolveBundles(ModuleContainer.java:1449)
	at com.ibm.ws.kernel.launch.internal.ProvisionerImpl.installKernelBundle(ProvisionerImpl.java:315)
	at com.ibm.ws.kernel.launch.internal.ProvisionerImpl.installBundles(ProvisionerImpl.java:241)
	at com.ibm.ws.kernel.launch.internal.ProvisionerImpl.initialProvisioning(ProvisionerImpl.java:94)
	at com.ibm.ws.kernel.launch.internal.FrameworkManager.innerLaunchFramework(FrameworkManager.java:448)
	at com.ibm.ws.kernel.launch.internal.FrameworkManager.launchFramework(FrameworkManager.java:284)
	at com.ibm.ws.kernel.launch.internal.LauncherDelegateImpl.doFrameworkLaunch(LauncherDelegateImpl.java:114)
	at com.ibm.ws.kernel.launch.internal.LauncherDelegateImpl.launchFramework(LauncherDelegateImpl.java:100)
	at com.ibm.ws.kernel.boot.internal.KernelBootstrap.go(KernelBootstrap.java:214)
	at com.ibm.ws.kernel.boot.Launcher.handleActions(Launcher.java:241)
	at com.ibm.ws.kernel.boot.Launcher.createPlatform(Launcher.java:117)
	at com.ibm.ws.kernel.boot.cmdline.EnvCheck.main(EnvCheck.java:59)
	at com.ibm.ws.kernel.boot.cmdline.EnvCheck.main(EnvCheck.java:35)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at wlp.lib.extract.SelfExtractRun.runServerInline(SelfExtractRun.java:366)
	at wlp.lib.extract.SelfExtractRun.main(SelfExtractRun.java:302)

**Steps to Reproduce**
1. On Windows with Java 17 package up your server with server package myServer --include=minify,runnable.
2. Ensure there is no jvm.options file within the server, and execute the server via the SelfExtractRun class:  java -cp <path to to /wlp root> wlp.lib.extract.SelfExtractRun
3. The kernel should start but applications will not load.

**Expected behavior**
Server should load applications and run as normal

**Diagnostic information:**
 - OpenLiberty Version: 20.0.0.10
 - Java Version: openjdk version "17" 2021-09-14 OpenJDK Runtime Environment (build 17+35-2724) OpenJDK 64-Bit Server VM (build 17+35-2724, mixed mode, sharing)
 - server.xml configuration  N/A

**Additional context**

### PR DESCRIPTION
**Pull request by hlhoots**
Fix for #18753 
#build 
fixes #18753

### CODE REVIEW

**Comment by hlhoots** [comment]
build machine error 'no space left on device'...

#build

**Review by jimblye — APPROVED** [review]

**Comment by hlhoots** [comment]
One known error in Java 17 hotspot build here: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_MfohYB-fEeypAeRm-z7vIA

**Comment by hlhoots** [comment]
maven errors in logs.. infrastructure issue.  rebuild again.

#build

**Comment by hlhoots** [comment]
build hlhoots-18755-20210929-0705 was a successful windows with java 17 build.

**Pull request merged**
