### PR TITLE
MP OpenAPI log improvements and minor fixes

### PR DESCRIPTION
**Pull request by arturdzm**
PR for #2309 #2096 #2125

- Improve toString method of models for logging
- Minor Fixes

### CODE REVIEW

**Comment by arturdzm** [comment]
#build`

**Comment by leochr** [comment]
#build

**Comment by leochr** [comment]
Kicked off another build since the first one hasn't started FAT tests yet (afraid it may time out).

**Comment by arturdzm** [comment]
#build

**Comment by leochr** [comment]
Personal build is good:
https://wasrtc.hursley.ibm.com:9443/jazz/resource/itemOid/com.ibm.team.build.BuildResult/_pOzyABftEeiANdIhjNYPnw

All of the MicroProfile OpenAPI tests passed:
com.ibm.ws.microprofile.openapi unittests
com.ibm.ws.microprofile.openapi_fat FAT tests
com.ibm.ws.microprofile.openapi_fat_tck FAT tests

Failures are in unrelated components and could not have been caused by the changes from this PR.

Please merge. Thanks.

**Comment by leochr** [comment]
@arturdzm this is not needed anymore I guess, please close if so. thanks

**Comment by leochr** [comment]
Closing since it's showing up the 1Q PR list. Reopen if necessary.

**Pull request closed without merging**
