### PR TITLE
mpOpenAPI: Repeat ShutdownTest

### LINKED ISSUE #29976: MP OpenAPI ShutdownTest does not repeat
MP OpenAPI ShutdownTest is not repeated for each feature version.

This is an additional issue because the server is shared with `DeploymentTest` which does repeat, so `ShutdownTest` ends up running with whatever configuration was run last for `DeploymentTest`.

### PR DESCRIPTION
**Pull request by Azquelt**
This test was not repeated over all feature versions.

We also need to fix the test setup so that it passes on mpOpenAPI 4.0

- [x] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [x] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [x] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

Resolves #29976

### CODE REVIEW

**Comment by Azquelt** [comment]
#build

**Review by abutch3r — APPROVED** [review]
LGTM

**Comment by Azquelt** [comment]
Build failed with an infrastructure issue.
#build

**Comment by Azquelt** [comment]
Failures in the build are in unrelated areas and can be linked to infrastructure problems.

**Pull request merged**
