### PR TITLE
Pkce fat 1

### PR DESCRIPTION
**Pull request by c00crane**
Create FAT for PKCE.  I've created PKCE tests for the OIDC client (openidConnectClient) and social client (oidcLogin).
The new tests will set the pkceCodeChallengeMethod value in the client config to S256 or plain, or omit that config attribute with and without setting proofKeyForCodeExchange to true in the OP.  Tests will run with both RS256 and HS256 and all combinations of settings of these PKCE config attributes.
All combinations should work except for cases where proofKeyForCodeExchange=true and pkceCodeChallengeMethod is NOT set.  
The authorize and token endpoints have already been tested separately - we're just focusing on the behavior with different client settings.

### CODE REVIEW

**Comment by c00crane** [comment]
https://github.com/OpenLiberty/open-liberty/issues/19029

**Comment by c00crane** [comment]
(expecting a couple tests will fail until issue https://github.com/OpenLiberty/open-liberty/issues/25137 is resolved or we decide that we should expect different behavior)
#build 
#spawn.fullfat.buckets= com.ibm.ws.security.oidc.client_fat.1,com.ibm.ws.security.social_fat.LibertyOP.1

**Comment by c00crane** [comment]
Pushed out changes and requested a personal build - was expecting *_proofKeyTrue_HS256_na_* tests to fail due to issue https://github.com/OpenLiberty/open-liberty/issues/25137 - those did fail, but several other tests hit the java BigInteger problem - which is unrelated to these changes.

**Comment by c00crane** [comment]
#libby
#build
#spawn.fullfat.buckets= com.ibm.ws.security.oidc.client_fat.1,com.ibm.ws.security.social_fat.LibertyOP.1

**Comment by c00crane** [comment]
#libby
#build
#spawn.fullfat.buckets= com.ibm.ws.security.oidc.client_fat.3,com.ibm.ws.security.social_fat.LibertyOP.3

**Review by arunavemulapalli — APPROVED** [review]
lgtm

**Pull request merged**
