### PR TITLE
Revert "Allow the creation of the KafkaConsumer to be retried"

### PR DESCRIPTION
**Pull request by Azquelt**
Reverts OpenLiberty/open-liberty#11800

Based on @ianpartridge's comments in #11800, it sounds like this small fix may not actually help with their use case, so I'd like to back this change out until we have a better understanding of their requirements.

### CODE REVIEW

**Comment by andrea-pichler** [comment]
Hi @Azquelt I'm confused about the updates to the dev/com.ibm.ws.microprofile.reactive.messaging.kafka/resources/com/ibm/ws/microprofile/reactive/messaging/kafka/resources/ReactiveMessaging.nlsprops
Why was messages.log file changed to message.log? Is this really correct? Thank you

**Comment by Azquelt** [comment]
Hi @andrea-pichler sorry for the confusion, this is a revert.

Unfortunately, as well as reverting the new function, it reverts some fixes which were made to the nlsprops. This is why you see a correct message being replaced by an incorrect one as well as messages being removed.

If we end up merging this revert, I'll reapply those fixes.

**Comment by Azquelt** [comment]
#build

**Comment by Azquelt** [comment]
Ended up not reverting this.

**Pull request closed without merging**
