### PR TITLE
Condition datasource at checkpoint

### PR DESCRIPTION
**Pull request by sebratton**

### CODE REVIEW

**Comment by sebratton** [comment]
#build

**Comment by sebratton** [comment]
#build

**Comment by sebratton** [comment]
#libbybot

**Review by tjwatson — APPROVED** [review]

**Comment by tjwatson** [comment]
#build

**Comment by sebratton** [comment]
All tests passed in the personal build. There was a pagkaging verifcation log failure but that was an infrastructure releated failure doing an scp:
`     [java] Caused by: org.apache.http.conn.ConnectTimeoutException: Connect to wasrtc.hursley.ibm.com:9443 [wasrtc.hursley.ibm.com/9.20.59.55] failed: Connection timed out
     [java] 	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:149)`

**Pull request merged**
