### PR TITLE
Faces 4.0 API update to 4.0.0-RC1

### LINKED ISSUE #21846: Jakarta Faces 4.0 initial implementation and API - MyFaces 4.0.0-RC1
The goal here is to enable the `faces-4.0` feature to actually leverage the MyFaces 4.0-RC1 release.  The `faces-4.0` feature is still a `noship` feature. During initial integration efforts, I've identified a couple of issues relating to classloading as well as an issue with a method that we depend on in an SPI being removed.

The `faces-4.0` feature will not be usable until we address these issues or have limited usability. However, getting an initial implementation and API delivered is going to help speed up development / debugging efforts and aid with getting any necessary issues opened in the MyFaces open source community to resolve issues we identify.

### PR DESCRIPTION
**Pull request by pnicolucci**
fixes #21846

### CODE REVIEW

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
#libby #build

**Review by volosied — APPROVED** [review]
Thanks for getting this up. Since we're taking an iterative approach and this is a no ship feature, I don't have many comments.   And from the webex review, all your comments made sense. 

Another thing I realized -- we should automatically enable cdi with faces 4.0?

**Comment by pnicolucci** [comment]
> Thanks for getting this up. Since we're taking an iterative approach and this is a no ship feature, I don't have many comments. And from the webex review, all your comments made sense.
> 
> Another thing I realized -- we should automatically enable cdi with faces 4.0?

Good call: https://github.com/OpenLiberty/open-liberty/issues/22187

**Pull request merged**
