### PR TITLE
Fix cos naming fats

### PR DESCRIPTION
**Pull request by joe-chacko**

### CODE REVIEW

**Comment by joe-chacko** [comment]
#build

**Comment by joe-chacko** [comment]
#build

**Comment by joe-chacko** [comment]
#build
#run-libby-bot

**Comment by joe-chacko** [comment]
#build and #run-libby-bot

**Review by ngmr — COMMENTED** [review]
Needs more cowbell

**Review by ngmr — APPROVED** [review]
Looks good to me

**Comment by joe-chacko** [comment]
#build #run-libby-bot

**Comment by joe-chacko** [comment]
#build and #run-libby-bot

**Pull request merged**
