### PR TITLE
Port MYFACES-4477 (Programmatic Facelets)

### LINKED ISSUE #22997: MYFACES-4477: TCK: Spec1581IT: Fix Programmatic Views in Faces 4.0 (Views Rendered via Java)
https://issues.apache.org/jira/browse/MYFACES-4477

### PR DESCRIPTION
**Pull request by volosied**
fixes #22997

### CODE REVIEW

**Comment by volosied** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jsp.2.3_fat,com.ibm.ws.jsf.2.2_fat

**Comment by volosied** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jsf.2.3_fat,com.ibm.ws.jsf.2.2_fat

**Comment by wraschke** [comment]
Hello, please ignore this.

**Comment by volosied** [comment]
Closing and this will be pulled into Faces via 4.0.0-RC2 (sometime next week?)

**Pull request closed without merging**
