### PR TITLE
25997: Remove websocket close delay

### PR DESCRIPTION
**Pull request by loriadi**
Remove the close delay in Websocket.

### CODE REVIEW

**Comment by loriadi** [comment]
fixes #25997

**Comment by loriadi** [comment]
#build

**Comment by loriadi** [comment]
#libbybot

**Comment by loriadi** [comment]
Fixes #PH56266

**Comment by loriadi** [comment]
Fixes #PH56266

**Review by mrsaldana — APPROVED** [review]
LGTM

**Pull request merged**
