### PR TITLE
Redo 14605 where ds injection fails

### LINKED ISSUE #14605: Re-introduce change reverted from 14434
Re-introduce change reverted from https://github.com/OpenLiberty/open-liberty/pull/14434

### PR DESCRIPTION
**Pull request by neilgsyoung**
fixes #14605

### CODE REVIEW

**Comment by neilgsyoung** [comment]
#build

**Comment by neilgsyoung** [comment]
#run-libby-bot

**Comment by neilgsyoung** [comment]
#build

**Comment by neilgsyoung** [comment]
#build

**Comment by neilgsyoung** [comment]
#run-libby-bot

**Comment by neilgsyoung** [comment]
#build

**Comment by neilgsyoung** [comment]
#run-libby-bot

**Comment by neilgsyoung** [comment]
#build

**Comment by neilgsyoung** [comment]
#run-libby-bot

**Comment by neilgsyoung** [comment]
#build

**Comment by neilgsyoung** [comment]
#run-libby-bot

**Comment by neilgsyoung** [comment]
#build

**Comment by neilgsyoung** [comment]
#run-libby-bot

**Comment by neilgsyoung** [comment]
#build

**Review by jonhawkes — APPROVED** [review]

**Comment by neilgsyoung** [comment]
#run-libby-bot

**Pull request merged**
