### PR TITLE
Issue #16797: Remove SharedServer from CDINoInjectionTests

### LINKED ISSUE #16797: Remove SharedServer from servlet 3.1 FAT: CDINoInjectionTest

### PR DESCRIPTION
**Pull request by pnicolucci**
fixes #16797

### CODE REVIEW

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Review by isaacrivriv — APPROVED** [review]
Looks good thanks!

**Comment by pnicolucci** [comment]
#run-libby-bot

**Pull request merged**
