### PR TITLE
Expose BuildServicesImpl to the CDI API bundle

### LINKED ISSUE #20570: Provide the `BuildServices` service (for BCE)
We need to provide the `BuildServices` service to allow `AnnotationBuilder` to work in the build compatible extensions SPI.

### PR DESCRIPTION
**Pull request by Azquelt**
This is needed for the `AnnotationBuilder`, added for Build Compatible Extensions, to work.

The `BuildServicesImpl` is provided by weld, but we need to make it service loadable by the CDI API bundle. To avoid having the  API bundle depend on the implementation we use a fragment to do this.

Fixes TCK failures:
```
org.jboss.cdi.tck.tests.build.compatible.extensions.changeInjectionPoint.ChangeInjectionPointTest
org.jboss.cdi.tck.tests.build.compatible.extensions.customInterceptorBinding.CustomInterceptorBindingTest
org.jboss.cdi.tck.tests.build.compatible.extensions.syntheticBean.SyntheticBeanTest
```

Fixes #20570
Fixes RTC289922

### CODE REVIEW

**Comment by Azquelt** [comment]
#build

**Comment by brideck** [comment]
New personal build: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_cKZSUKxCEeyJdcarUSDuUg

First one crashed and burned.

**Comment by Azquelt** [comment]
Second one also failed. Another? https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_PkRo4KxOEeyJdcarUSDuUg

**Review by Emily-Jiang — APPROVED** [review]
LGTM

**Pull request merged**
