### PR TITLE
Return a consistent status code 404 for non-existing static resources

### LINKED ISSUE #29262: 404 / 403 Status code for URLs ending in `/`
Hi Team, I need assistance with a DAST vulnerability scan issue `Hidden Directory Detected: /index.html/`

- WebSphere Liberty 24.0.0.7 is returning 403 when a forward slash is added to the end of the name of a valid non-directory file, instead of 404.
  - icr.io/appcafe/websphere-liberty:24.0.0.7-kernel-java17-openj9-ubi
- For example: 
  - these URIs return expected 200 response codes:
    - / --> http 200
    - /index.html --> http 200
  - these URIs return expected 404 response codes: 
    - /test.html --> http 404
    - /test.html/ --> http 404
  - this URI returns 403 instead of the expected 404 
    - /index.html/ --> http 403 - expected to be http 404

- application web.xml

```
<?xml version="1.0" encoding="UTF-8"?>
<web-app xmlns="http://xmlns.jcp.org/xml/ns/javaee" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/javaee http://xmlns.jcp.org/xml/ns/javaee/web-app_3_1.xsd"
    version="3.1">
    <display-name>REMOVED</display-name>

    <welcome-file-list>
        <welcome-file>index.html</welcome-file>
    </welcome-file-list>

    <servlet>  
        <servlet-name>REMOVED</servlet-name>  
        <servlet-class>REMOVED</servlet-class>  
        <load-on-startup>REMOVED</load-on-startup>  
    </servlet>  

</web-app>
```

- application uses custom index.html file, and not the default hidden welcome page

- Is this a bug?   Is there a configuration that can force /index.html/ to return 404?

### PR DESCRIPTION
**Pull request by pmd1nh**
- [X] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [X] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [X] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

Fixes https://github.com/OpenLiberty/open-liberty/issues/29262

### CODE REVIEW

**Comment by pmd1nh** [comment]
There are 2 lines change at

https://github.com/OpenLiberty/open-liberty/pull/29296/files#diff-5c19b75700d7dafcffa4d1913567cdf0e57966e1b440551ecd358c456d729338R505

and 

https://github.com/OpenLiberty/open-liberty/pull/29296/files#diff-5c19b75700d7dafcffa4d1913567cdf0e57966e1b440551ecd358c456d729338R857

The rest are auto reformat/alignment.

**Comment by pmd1nh** [comment]
#build
     #spawn.fullfat.buckets=io.openliberty.webcontainer.servlet.6.1.internal_fat,io.openliberty.webcontainer.servlet.6.0.internal_fat,com.ibm.ws.webcontainer.servlet.6.1_fat_toleration.lWAS,com.ibm.ws.webcontainer.servlet.6.0_fat_toleration.lWAS,com.ibm.ws.webcontainer_fat,com.ibm.ws.webcontainer.servlet.3.1_fat,com.ibm.ws.webcontainer.servlet.3.1_fat.2,com.ibm.ws.webcontainer.servlet.4.0_fat,com.ibm.ws.webcontainer_fat_part2,com.ibm.ws.webcontainer_fat_servlet31toleration,com.ibm.ws.webcontainer_fat_servlet31toleration_part2,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0_part2,com.ibm.ws.webcontainer_fat_lWAS,com.ibm.ws.webcontainer_fat_servlet31_webcontainerlWAS,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0.lWAS

**Comment by pmd1nh** [comment]
Need to update current FAT tests for the new 404 

image

**Comment by pmd1nh** [comment]
Also

image

**Comment by pmd1nh** [comment]
Disable CL tests in these area 
https://github.ibm.com/websphere/WS-CD-Open/pull/32563

After this is merged, update those tests and reactive them.

**Comment by pmd1nh** [comment]
attempt to PB then modify to run all possible FULL FAT

```
fat.buckets.to.run = auto
fat.test.mode = full
```

#build

**Comment by pmd1nh** [comment]
Cancelled previous PB, resubmitted with `fat.test.mode = full`

https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_GjbRMFsMEe-nla_L9rYqvA

**Comment by pmd1nh** [comment]
Ran FULL fat for auto buckets selection.
There are some failures in SIP.  Checked these with Tibor to make sure these tests are not expecting 403 status code.  All are good.

**Comment by pmd1nh** [comment]
#libby

**Review by pnicolucci — APPROVED** [review]

**Pull request merged**
