### PR TITLE
Concurrent-3.1 Update Deployment Descriptors

### PR DESCRIPTION
**Pull request by KyleAure**
Cherry-picked from #27148

### CODE REVIEW

**Review by njr-11 — DISMISSED** [review]
Already reviewed & approved under the pull that it was cherry picked from.

**Comment by KyleAure** [comment]
#build

**Comment by KyleAure** [comment]
#build - personal build
#libby - re-check headers

**Comment by KyleAure** [comment]
Combined personal build is at https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_LadtMKTkEe6yLMTOMov9vA

Target locations of links might be accessible only to IBM employees.

**Comment by KyleAure** [comment]
#libby - recheck headers

**Comment by KyleAure** [comment]
Resubmitted

- Personal Build: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_sSXqMKWbEe6yLMTOMov9vA
- Combined Build: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_pPGtgKWbEe6yLMTOMov9vA

Target locations of links might be accessible only to IBM employees.

**Comment by KyleAure** [comment]
Both builds failed with known defects.
Ready for re-review and merge

**Review by njr-11 — APPROVED** [review]

**Pull request merged**
