### PR TITLE
Port com.ibm.ws.webserver.plugin.utility FAT bucket and unit tests

### PR DESCRIPTION
**Pull request by wtlucy**

### CODE REVIEW

**Comment by wtlucy** [comment]
build pointing to this PR and the closed repo's PR to remove these buckets: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_r7x_IHvFEeiesbDn1b1SdQ

**Comment by wtlucy** [comment]
#build

**Comment by wtlucy** [comment]
The normal personal build (which didn't point to the closed repo changes) passed fine, but the build that did had issues.  I've made a change to the test server configurations, trying again: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_okfYYH4kEeiACNpEFzHAag

**Comment by wtlucy** [comment]
#build

**Comment by wtlucy** [comment]
A good manual build pointing to this PR and the closed repo:
https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_58mBMIUKEeiADe06pEGqdQ&tab=com.ibm.team.build.web.ui.internal.editors.result.test.TestProvider

The manual build and the most recent personal build look good.. @pnicolucci can you look over this again?

**Comment by pnicolucci** [comment]
fixes #4259

**Pull request merged**
