### PR TITLE
Log first entry for ignored messages after logging is fully restored

### PR DESCRIPTION
**Pull request by tjwatson**

### CODE REVIEW

**Comment by tjwatson** [comment]
#build

**Comment by tjwatson** [comment]
Fixes #23606

**Review by anjumfatima90 — DISMISSED** [review]

**Comment by tjwatson** [comment]
#build

**Comment by tjwatson** [comment]
#build

**Review by anjumfatima90 — APPROVED** [review]

**Comment by tjwatson** [comment]
#libby

**Pull request merged**
