### PR TITLE
Port classloading.bells_fat to OL

### PR DESCRIPTION
**Pull request by dazavala**
For issue #16317

Port the Classloading Bells FAT to open-liberty in preparation for feature enhancements.

* Update or add copyrights
* Fix syntax problems with ImplClassNotConstructible test
* Create gradle file to export user feature bundle(s)
* Add shrinkwrap utility method to build JAR files w/ filtered content
* Build and export Bell library JARs using shrinkwrap; obviates copy commands in gradle file
* Remove CL-specific Server and Class rule annotations from BellFatTest; refactor the abstractions using simple junit annotated behaviors
* Create bnd file for Bell fat bundle
* Move bnd file for user feature dependency bundle to root dir, reconfigure to build in OL
* Configure bnd.bnd file to build test artifacts
* Reconfigure eclipse project settings -- .classpath, .project, etc.
* Remove vestigial build.xml and .gitignore files
* Copy CL project files to OL

### CODE REVIEW

**Comment by dazavala** [comment]
#build

**Comment by dazavala** [comment]
#build
@tjwatson I made a few changes: 
- Removed commented-out elements in `.classpath`
- Removed file `publish/servers/bell_FAT_Server/.gitignore`, which ignored the sharedLib subdirectory.  This FAT builds Bell library jars directly into `build/libs/autoFVT/publish/servers/bell_FAT_Server/sharedLib`
- Fixed a copyright and some other comments.

**Review by tjwatson — APPROVED** [review]

**Comment by dazavala** [comment]
#libby

**Comment by dazavala** [comment]
#libby

**Comment by dazavala** [comment]
Merging now.  The combined build `EBC dazavala-17628-cl24224-20210624-0812` passed with two breaks unrelated to these changes.

**Pull request merged**
