### PR TITLE
Delete SingleJson.json file after automated build

### PR DESCRIPTION
**Pull request by hlhoots**
- [x] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [x] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [x] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

################################################################################################

### CODE REVIEW

**Comment by hlhoots** [comment]
#build

**Comment by hlhoots** [comment]
cog build was clean; rtc build had 1 failure which is a known issue.

**Comment by hlhoots** [comment]
release build that should run with automated build set to true: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_bPi0UE9uEe-5AYCytDSmRg

**Comment by hlhoots** [comment]
Release build failed with expected error since this was against a personal branch but tests passed.

**Review by cbridgha — APPROVED** [review]
looks good - Fixes issues when trying to rerun tasks....

**Comment by hlhoots** [comment]
fixes [#29237](https://github.com/OpenLiberty/open-liberty/issues/29237)

**Pull request merged**
