### PR TITLE
Add classloading trace to MetricsClassLoaderTest_10

### PR DESCRIPTION
**Pull request by dazavala**
Add trace to diagnose RTC-298694.

### CODE REVIEW

**Comment by dazavala** [comment]
#build

**Review by fmhwong — DISMISSED** [review]
LGTM

**Comment by dazavala** [comment]
Builds failed.  Test result archives exist, but are empty.  Updated the trace spec to generate less volume.  Retry to get a clean build (merge PR), or if lucky, to reproduce the problem and capture the classloading trace.

#build

**Review by fmhwong — APPROVED** [review]
LGTM

**Comment by dazavala** [comment]
#libby

**Pull request merged**
