### PR TITLE
Remove beta fencing for HTTP request tracing

### LINKED ISSUE #26293: Remove beta fencing for HTTP tracing

### PR DESCRIPTION
**Pull request by fmhwong**
Fixes #26293

### CODE REVIEW

**Comment by fmhwong** [comment]
#build
#spawn.fullfat.buckets=io.openliberty.microprofile.telemetry.1.0.internal_fat,io.openliberty.microprofile.telemetry.1.0.internal_fat_tck,io.openliberty.microprofile.telemetry.1.0.internal.jaeger_fat,io.openliberty.microprofile.telemetry.1.1.internal_fat_tck

**Comment by fmhwong** [comment]
#build
#spawn.fullfat.buckets=io.openliberty.microprofile.telemetry.1.0.internal_fat,io.openliberty.microprofile.telemetry.1.0.internal_fat_tck,io.openliberty.microprofile.telemetry.1.0.internal.jaeger_fat,io.openliberty.microprofile.telemetry.1.1.internal_fat_tck

**Comment by fmhwong** [comment]
#build
#spawn.fullfat.buckets=io.openliberty.microprofile.telemetry.1.0.internal_fat,io.openliberty.microprofile.telemetry.1.0.internal_fat_tck,io.openliberty.microprofile.telemetry.1.0.internal.jaeger_fat,io.openliberty.microprofile.telemetry.1.1.internal_fat_tck

**Review by Channyboy — APPROVED** [review]
lgtm

**Comment by fmhwong** [comment]
#libby

**Pull request merged**
