### PR TITLE
Make message/console source values case insensitive

### LINKED ISSUE #22251: Console source and message source logging server property values are not case insensitive
The `com.ibm.ws.logging.console.source` and `com.ibm.wslogging.message.source` server logging configuration property values are not case insensitive, as the other logging configuration property values. 

Configuring with upper case values does not work.
**bootstrap.properties file:**
com.ibm.ws.logging.console.source=MESSAGE,TRACE
com.ibm.wslogging.message.source=MESSAGE,trace

Only lower case values work.
**bootstrap.properties file:**
com.ibm.ws.logging.console.source=message,trace
com.ibm.wslogging.message.source=message,trace

### PR DESCRIPTION
**Pull request by pgunapal**
fixes #22251

### CODE REVIEW

**Comment by pgunapal** [comment]
#build

**Comment by pgunapal** [comment]
#build

**Comment by pgunapal** [comment]
#build

**Review by fmhwong — APPROVED** [review]
LGTM

**Comment by pgunapal** [comment]
Failures in build are known test failures with associated opened defects.

**Pull request merged**
