### PR TITLE
nonship concurrent-3.0 feature

### PR DESCRIPTION
**Pull request by njr-11**
Create a non-ship concurrent-3.0 feature where we can start experimenting with ideas for the Jakarta EE 10 Concurrency 3.0 spec.

### CODE REVIEW

**Review by nmittles — APPROVED** [review]

**Comment by njr-11** [comment]
#build

**Comment by njr-11** [comment]
ID review is unnecessary because the message was copied from the 2.0 feature without any changes.

**Comment by njr-11** [comment]
#run-libby-bot
#build

**Comment by njr-11** [comment]
#run-libby-bot
#build

**Comment by njr-11** [comment]
#build

**Comment by njr-11** [comment]
#build

**Comment by njr-11** [comment]
Build has 2 test failures, which are duplicates of pre-existing issues in unrelated test buckets.

**Pull request merged**
