### PR TITLE
Tolerate Java 9 multi-release JARs

### PR DESCRIPTION
**Pull request by jimblye**
Issue #1635 Unable to package JSONB-1.0 API in applications

### CODE REVIEW

**Comment by jimblye** [comment]
#build

**Comment by jimblye** [comment]
#build

**Comment by jimblye** [comment]
#build

**Comment by jimblye** [comment]
#build

**Comment by ewhoch** [comment]
Jim, double check that you have the "release bug" label on the right thing. In theory they always go on the Issue, never a pull request.

**Pull request merged**
