### PR TITLE
PH52095 - CXF-8706: CXF MTOM handler allow content injection

### LINKED ISSUE #24277: Backport CXF-8706: CXF MTOM handler allow content injection
We need to backport https://github.com/apache/cxf/pull/960 into Open Liberty.

### PR DESCRIPTION
**Pull request by WhiteCat22**
CXF-8706: CXF MTOM handler allow content injection

Backporting [this](https://issues.apache.org/jira/browse/CXF-8706) fix.

Fixes: https://github.com/OpenLiberty/open-liberty/issues/24277

### CODE REVIEW

**Comment by WhiteCat22** [comment]
#build

**Comment by WhiteCat22** [comment]
#libby

**Review by jim-krueger — APPROVED** [review]

**Review by jim-krueger — COMMENTED** [review]
LGTM

**Comment by WhiteCat22** [comment]
Fixes: #PH52095

**Comment by covener** [comment]
Fixes #PH52095

**Pull request merged**
