### PR TITLE
Fixed incorrect bootstrap property values in logging config metatype …

### LINKED ISSUE #14735: Fix the Logging metatype description message for hideMessage
hide.messages=Messages to be hidden
hide.messages.desc=The list of messages, which are separated by a comma, that are configured to be hidden from the console.log and messages.log files. If the messages are configured to be hidden, then they are redirected to the trace.log file. Avoid trouble: Use the com.ibm.ws.logging.hide.messages property, except in cases where you are trying to change the configuration dynamically after startup.

The Description should be fixed to state `com.ibm.ws.logging.hideMessage`, instead of `com.ibm.ws.logging.hide.messages`

### PR DESCRIPTION
**Pull request by pgunapal**
…description

fixes #14735

### CODE REVIEW

**Comment by pgunapal** [comment]
#build

**Comment by skasund** [comment]
L2 message review completed

**Review by fmhwong — APPROVED** [review]
LGTM

Please inform Phil Nickoll for the translation.

**Comment by pgunapal** [comment]
Informed Phil Nickoll, next translation shipment is at end of December.

**Pull request merged**
