### PR TITLE
Remove all unnecessary test-framework references from JPA FAT

### PR DESCRIPTION
**Pull request by dazey3**
Cleanup all the test-framework references that JPA FAT projects are still using

Signed-off-by: Will Dazey <dazeydev.3@gmail.com>

### CODE REVIEW

**Comment by dazey3** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jpa_22_fat,com.ibm.ws.jpa_30_fat,com.ibm.ws.jpa_eclipselink_fat,com.ibm.ws.jpa_ol_fat,com.ibm.ws.jpa_spec10_injection_fat,com.ibm.ws.jpa_spec10_part01_fat,com.ibm.ws.jpa_spec10_part02_fat,com.ibm.ws.jpa_spec10_query_fat,com.ibm.ws.jpa_spec20_fat,com.ibm.ws.jpa_spec21_fat

**Review by jgrassel — APPROVED** [review]
LGTM

**Comment by dazey3** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jpa_22_fat,com.ibm.ws.jpa_30_fat,com.ibm.ws.jpa_eclipselink_fat,com.ibm.ws.jpa_ol_fat,com.ibm.ws.jpa_spec10_injection_fat,com.ibm.ws.jpa_spec10_part01_fat,com.ibm.ws.jpa_spec10_part02_fat,com.ibm.ws.jpa_spec10_query_fat,com.ibm.ws.jpa_spec20_fat,com.ibm.ws.jpa_spec21_fat

**Comment by dazey3** [comment]
#run-libby-bot

**Pull request merged**
