### PR TITLE
Update JPA 3.1 FAT, fix incorrect column types on DB2 and Oracle DDL …

### PR DESCRIPTION
**Pull request by jgrassel**
Updating the JPA 3.1 FAT, correcting the DDL files for DB2 and Oracle, as they contained VARCHAR instead of DATE/TIME/TIMESTAMP types as they should have.  This corrected the remainder of outstanding issues associated with this FAT.

### CODE REVIEW

**Comment by jgrassel** [comment]
#build

**Comment by jgrassel** [comment]
#run-libby-bot

**Comment by jgrassel** [comment]
#build

**Review by tkburroughs — APPROVED** [review]

**Review by dazey3 — APPROVED** [review]
LGTM

**Pull request merged**
