### PR TITLE
Cleanup ol, locking, & injection JPA FAT

### PR DESCRIPTION
**Pull request by dazey3**
Signed-off-by: Will Dazey <dazeydev.3@gmail.com>

### CODE REVIEW

**Comment by dazey3** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jpa_locking_fat,com.ibm.ws.jpa_ol_fat,com.ibm.ws.jpa_spec10_injection_fat

**Comment by dazey3** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jpa_locking_fat,com.ibm.ws.jpa_ol_fat,com.ibm.ws.jpa_spec10_injection_fat

**Review by tkburroughs — APPROVED** [review]
It appears the spec the com.ibm.ws.jpa_spec10_injection_fat bucket has been modified to support multiple databases, but all but the Derby DDL have been removed.  I'm fine with this being limited to Derby only, but make sure it doesn't try to run with other databases and fail.  Will approve assuming you verify that behavior.

**Comment by dazey3** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jpa_locking_fat,com.ibm.ws.jpa_ol_fat,com.ibm.ws.jpa_spec10_injection_fat

**Comment by dazey3** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jpa_locking_fat,com.ibm.ws.jpa_ol_fat,com.ibm.ws.jpa_spec10_injection_fat

**Comment by dazey3** [comment]
#run-libby-bot

**Pull request merged**
