### PR TITLE
Jakartaee work

### PR DESCRIPTION
**Pull request by cbridgha**

### CODE REVIEW

**Comment by cbridgha** [comment]
#build

**Comment by volosied** [comment]
#build

**Comment by volosied** [comment]
#build

**Comment by volosied** [comment]
#build

**Comment by cbridgha** [comment]
https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_AN7iwHmQEeqVMooXUPL4-g

**Comment by skasund** [comment]
L2 message review not required

**Comment by cbridgha** [comment]
#run-libby-bot

**Pull request merged**
