### PR TITLE
Ignore FFDC CloneNotSupportedException

### PR DESCRIPTION
**Pull request by utle**
Ignore the FFDC and we get the new isntance.

### CODE REVIEW

**Comment by utle** [comment]
#build

**Comment by Zech-Hein** [comment]
For Issue: https://github.com/OpenLiberty/open-liberty/issues/16945

**Review by Zech-Hein — CHANGES_REQUESTED** [review]
update copyright to 2021

**Comment by utle** [comment]
#build

**Comment by utle** [comment]
> update copyright to 2021

done.

**Comment by utle** [comment]
#build

**Comment by utle** [comment]
#build

**Review by Zech-Hein — APPROVED** [review]

**Comment by utle** [comment]
#build

**Comment by utle** [comment]
#run-libby-bot

**Pull request merged**
