### PR TITLE
Changes needed to avoid Java2 security exceptions and quiesce warnings

### PR DESCRIPTION
**Pull request by jim-krueger**

### CODE REVIEW

**Comment by jim-krueger** [comment]
#libby #build

**Review by jgrassel — DISMISSED** [review]
lgtm!

**Review by WhiteCat22 — DISMISSED** [review]

**Comment by jim-krueger** [comment]
#libby #build

**Review by WhiteCat22 — APPROVED** [review]

**Comment by jim-krueger** [comment]
#run-libby-bot

**Comment by jim-krueger** [comment]
#build

**Comment by jim-krueger** [comment]
#build

**Comment by jim-krueger** [comment]
#build

**Review by jgrassel — APPROVED** [review]

**Pull request merged**
