### PR TITLE
allow shibboleth to run with Java 16

### PR DESCRIPTION
**Pull request by c00crane**
Add --add-opens=java.xml/com.sun.org.apache.xerces.internal.util=ALL-UNNAMED to the com.ibm.ws.security.saml.sso-2.0_fat.shibboleth/jvm.options file.
We're investigating upgrading the shibboleth server that we embed for testing - in the meantine this jvm.options file update will allow us to run with Java16.

### CODE REVIEW

**Comment by c00crane** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.security.saml.sso_fat,com.ibm.ws.security.saml.sso_fat.2,com.ibm.ws.security.saml.sso_fat.3,com.ibm.ws.security.saml.sso_fat.config,com.ibm.ws.security.saml.sso_fat.config.mapToUserRegistry,com.ibm.ws.security.saml.sso_fat.endpoint.samlmetadata,com.ibm.ws.security.saml.sso_fat.jaxrs,com.ibm.ws.security.saml.sso_fat.jaxrs.config,com.ibm.ws.security.saml.sso_fat.logout,com.ibm.ws.security.saml.sso_fat.logout.IDP_initiated,com.ibm.ws.security.saml.sso_fat.logout.httpServletRequest,com.ibm.ws.security.saml.sso_fat.logout.ibm_security_logout,com.ibm.ws.wssecurity_fat.wsscxf.saml,com.ibm.ws.wssecurity_fat.wsscxf.saml.2

**Comment by c00crane** [comment]
Kicked off build and requested fats be run with Java16: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_Pj6AQIHWEeu8SN1zElUVXg

**Comment by c00crane** [comment]
#run-libby-bot

**Comment by c00crane** [comment]
The changes in this pull will fix OL Fats - we'll need an equivalent update elsewhere - this means that the following projects will fail until that update is made:
com.ibm.ws.security.oidc.client_fat.saml
com.ibm.ws.security.oidc.server_fat.saml

**Review by ayoho — APPROVED** [review]

**Review by ayoho — APPROVED** [review]

**Comment by c00crane** [comment]
#run-libby-bot

**Pull request merged**
