### PR TITLE
Add connectors to Jakartaee beta

### LINKED ISSUE #14118: Add Connectors-2.0 to Jakartaee-9.0 feature

### PR DESCRIPTION
**Pull request by KyleAure**
Fixes #14118

### CODE REVIEW

**Review by njr-11 — APPROVED** [review]

**Comment by KyleAure** [comment]
#build

**Comment by KyleAure** [comment]
Build failed to complete due to a known issue within our build infrastructure.  Will attempt to re-build.

**Comment by KyleAure** [comment]
#build

**Comment by KyleAure** [comment]
#build

**Pull request merged**
