### PR TITLE
IdClass as a named parameter

### PR DESCRIPTION
**Pull request by njr-11**
Scenarios where an IdClass can be a named parameter to a repository query.

### CODE REVIEW

**Comment by njr-11** [comment]
#build

**Review by nmittles — APPROVED** [review]

**Comment by njr-11** [comment]
#build

**Comment by njr-11** [comment]
#libby

**Comment by njr-11** [comment]
#build

**Comment by njr-11** [comment]
Build was successful apart from the BVT tests which ran into the infrastructure issue "no space left on device". The BVT build has been resubmitted as https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_oSU_Ea38Ee2FnaZGnlWrhQ

**Comment by njr-11** [comment]
The resubmit of the BVT build was successful.

**Pull request merged**
