### PR TITLE
Make sure flat configuration is merged appropriately

### PR DESCRIPTION
**Pull request by brenthdaniel**
merge elements by id during flat config processing

### CODE REVIEW

**Comment by brenthdaniel** [comment]
#build

**Comment by brenthdaniel** [comment]
checked in the wrong version of code... 
#build again

**Comment by brenthdaniel** [comment]
#build

**Review by hlhoots — APPROVED** [review]
looks okay to me.

**Comment by brenthdaniel** [comment]
#run-libby-bot

**Comment by brenthdaniel** [comment]
PR for #15363

**Pull request merged**
