### PR TITLE
Issue #17807 - Split buildFeatureStart_fat

### LINKED ISSUE #17807: Split the build.featureStart_fat bucket
Problem:
We now have a large number of features, and the build.featureStart_fat times out after 2 hours on some platforms.  

Resolution:
Split the build.featureStart_fat such that one bucket runs featues with name A to L and the other M to Z.

### PR DESCRIPTION
**Pull request by hlhoots**
#build
fixes #17807

### CODE REVIEW

**Comment by hlhoots** [comment]
#build

**Comment by hlhoots** [comment]
#build

**Comment by hlhoots** [comment]
#build

**Comment by hlhoots** [comment]
#build

**Comment by hlhoots** [comment]
#build

**Comment by hlhoots** [comment]
#build

**Comment by hlhoots** [comment]
#build

**Review by tbitonti — APPROVED** [review]

**Review by brenthdaniel — APPROVED** [review]

**Comment by hlhoots** [comment]
#run-libby-bot

**Pull request merged**
