### PR TITLE
Repeat tests for MP70_EE11

### PR DESCRIPTION
**Pull request by anjumfatima90**
- [x] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [ ] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [ ] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

### CODE REVIEW

**Comment by anjumfatima90** [comment]
#build

**Comment by anjumfatima90** [comment]
#build

**Review by SmithaSubbarao — APPROVED** [review]
/lgtm

**Comment by anjumfatima90** [comment]
#libby

**Comment by anjumfatima90** [comment]
#libby

**Pull request merged**
