### PR TITLE
Issue #12304: Update servlet 5.0 feature description and other minor …

### LINKED ISSUE #12304: Update the servlet-5.0 feature description Subsystem-Name
1) `Subsystem-Category: JavaEE8Application` -> `Subsystem-Category: JakartaEE9Application`

2) `Subsystem-Name: Java Servlets 5.0` -> `Subsystem-Name: Jakarta Servlets 5.0`

3) 
**Started with:**

> description=This feature enables support for HTTP Servlets written to the Java Servlet 5.0 specification. \
>  You can package servlets in Java EE specified WAR or EAR files.  If servlet security is required, you \
>  should also configure an appSecurity feature. Without a security feature, any security \
>  constraints for the application are ignored.

**Changed to:**

> description=This feature enables support for HTTP Servlets written to the Jakarta Servlet 5.0 specification. \
>  You can package servlets in Jakarta EE specified WAR or EAR files.  If servlet security is required, you \
>  should also configure an appSecurity feature. Without a security feature, any security \
>  constraints for the application are ignored.

4) Delete the translations that were copied over incorrectly.

### PR DESCRIPTION
**Pull request by pnicolucci**
fixes #12304 

`Subsystem-Category: JavaEE8Application` -> `Subsystem-Category: JakartaEE9Application`

`Subsystem-Name: Java Servlets 5.0` -> `Subsystem-Name: Jakarta Servlets 5.0`

Feature description changes of Java Servlet and Java EE to Jakarta Servlet and Jakarta EE

### CODE REVIEW

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Comment by andrea-pichler** [comment]
No message review requested from L2

**Comment by pnicolucci** [comment]
#run-libby-bot

**Pull request merged**
