### PR TITLE
Remove test on parent overlay container.

### LINKED ISSUE #19937: context-root for web-ext is no longer honored with WLP 22.0.0.1
Specifying the the `context-root` in a `web-ext` element, e.g:
```
<web-ext id="namehere" moduleName="namehere" context-root="/" />
```

is now ignored starting with WLP 22.0.0.1. This works with WLP 21.0.0.12 as expected.

The context root for the app in the above example becomes `/namehere` instead of `/`.

### PR DESCRIPTION
**Pull request by tbitonti**
Fixes #19937.

Tests are added by pull request #20055.

### CODE REVIEW

**Comment by tbitonti** [comment]
Verified locally.  FAT tests to cover the failing case are being added with issue #19764.

**Comment by tbitonti** [comment]
#build

**Review by brenthdaniel — APPROVED** [review]

**Review by cbridgha — APPROVED** [review]
Looks good

**Comment by tbitonti** [comment]
First build has too many errors.  They look unrelated, but there are too many to tell with confidence.  Respinning.

**Comment by tbitonti** [comment]
#build

**Comment by tbitonti** [comment]
#libby

**Comment by tbitonti** [comment]
#build

**Comment by tbitonti** [comment]
Test failures were reviewed and are unrelated:
no component | 82586 | 1 | 1 |   |  
com.ibm.ws.security.oidc.server_fat.jaxrs.config FAT tests | 1 | 0 | 1 |   |  
com.ibm.ws.security.openidconnect.server.fat.jaxrs.config.FATSuite | 1 | 0 | 1 | 0 s | 1
MapToUserRegistryNoRegUserinfo2ServerTests_NoRegistry_MinimalCfgTest | 1 | 0 | 1 | 0 s | 1
com.ibm.ws.security.oidc.server_fat.jaxrs.config javacores | 1 | 1 | 0 |   |  
com.ibm.ws.security.oidc.server_fat.jaxrs.config javacores

**Pull request merged**
