### PR TITLE
Add -Xdump option to determine intermittent classloading breaks

### PR DESCRIPTION
**Pull request by dazavala**
Add -Xdump options to help determine intermittent classloading failures, specifically NoClassDefFoundError's and NoSuchMethodError's that occur while loading dependent classes from a system bundle.

### CODE REVIEW

**Comment by dazavala** [comment]
#build

**Review by sebratton — APPROVED** [review]
Maybe consider instrumenting the JPA fats on NoSuchMethodException

**Comment by dazavala** [comment]
#build

**Comment by dazavala** [comment]
#libby

**Pull request merged**
