### PR TITLE
Return 400 for invalid encoded request URI

### LINKED ISSUE #27620: Invalid encoded request URI should return 400 instead of 500
**Describe the bug**  
500 status code returns for an invalid encoded URI.  It also creates a FFDC log.  It can cause a false alarm for the server administrator.  A `400 Bad Request` should be returned.

**Steps to Reproduce**  
Send a bad encoded URI to an existing application (i.e context root).  For example:

`http://host:port/%5%20C..`

**Expected behavior**  
Return `400 Bad Request` response without any FFDC.

**Diagnostic information:**  
 - OpenLiberty Version: all version until this is fixed.
 - Affected feature(s) [servlet]
 - Java Version: [11]
 - server.xml configuration (WITHOUT sensitive information like passwords)
 - If it would be useful, upload the messages.log file found in `$WLP_OUTPUT_DIR/messages.log`

**Additional context**  
None

### PR DESCRIPTION
**Pull request by pmd1nh**
fixes https://github.com/OpenLiberty/open-liberty/issues/27620

### CODE REVIEW

**Comment by pmd1nh** [comment]
#build
        #spawn.fullfat.buckets=io.openliberty.webcontainer.servlet.6.1.internal_fat,io.openliberty.webcontainer.servlet.6.0.internal_fat,com.ibm.ws.webcontainer.servlet.6.0_fat_toleration.lWAS,com.ibm.ws.webcontainer_fat,com.ibm.ws.webcontainer.servlet.3.1_fat,com.ibm.ws.webcontainer.servlet.4.0_fat,com.ibm.ws.webcontainer_fat_part2,com.ibm.ws.webcontainer_fat_servlet31toleration,com.ibm.ws.webcontainer_fat_servlet31toleration_part2,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0_part2,com.ibm.ws.webcontainer_fat_lWAS,com.ibm.ws.webcontainer_fat_servlet31_webcontainerlWAS,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0.lWAS

**Comment by pmd1nh** [comment]
Need to update base test case which has been expected 500 but now returning 400

```
com.ibm.ws.webcontainer_fat_lWAS FAT tests 92 2 0
 com.ibm.ws.fat.lwas.PI67093_PI68061Tests 2 2 0 19 s 11
  test_PI67093_WebContainerException_default_behavior 1 1 0 9 s 1
  test_PI68061_WebContainerException_Customized_Text 1 1 0 9 s 2


junit.framework.AssertionFailedError: 2024-02-21-22:46:23:218 Results: Checking Response Code: Expected [500], actual [400]. WRONG response code. FAIL
```

**Comment by pmd1nh** [comment]
If requests have gone passing the Canonicalization process, the URI is encoded before calling into the 
WebContainer.sendBadRequestResponse(req,res)

 ```
curl -v "http://localhost:9242/test_module61/test61%2F<script>something(Parentheses)+Plus'SingleQuote&Ampersand</script>"

Error 400: java.io.IOException: CWWWC0005I: The request URI has invalid or improperly encoded characters: [/test_module61/test61&#37;2F&lt;script&gt;something&#40;Parentheses&#41;&#43;Plus&#39;SingleQuote&amp;Ampersand&lt;/script&gt;] . URI has encoded forward slash [&#37;2F] character.
```

If requests are checked and rejected before the canonicalization process, it calls into the WebContainer.sendBadRequestResponse(req,res) directly.  The error message is NOT encoded the original URI in the response.


```
NOTE the %Ampersand is illegal and will be rejected by this fix

curl -v "http://localhost:9242/test_module61/test61%2F<script>something(Parentheses)+Plus'SingleQuote&%Ampersand</script>"

CWWWC0005I: The request URI has invalid or improperly encoded characters: [/test_module61/test61%2F<script>something(Parentheses)+Plus'SingleQuote&%Ampersand</script>]
```

We will need to encodeDataString in the sendBadRequestResponse in case it is called directly

**Comment by pmd1nh** [comment]
Updated lWAS tests to assert on the 400 instead of 500.
Also update that test to verify the encoded URI in the response data.

https://github.ibm.com/websphere/WS-CD-Open/pull/31571

Manually request PB with both OL and CD-Open PR

https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_pmFAAO--Ee6Y5NNrWk9AvQ

**Comment by pmd1nh** [comment]
4 or 5 FAT buckets were invalid, not sure why.
re spin a new build

https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_LHa_YPAlEe6Y5NNrWk9AvQ

**Review by pnicolucci — APPROVED** [review]

**Comment by pmd1nh** [comment]
Cancelled previous PB.  Update CD-Open to disable the tests for now.  Reactivate after this PR is merged

new PB
https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_upjLYPA2Ee6Y5NNrWk9AvQ

**Comment by pmd1nh** [comment]
#libby

**Comment by pmd1nh** [comment]
wait til https://github.ibm.com/websphere/WS-CD-Open/pull/31571 is in release, then merge this one.

**Comment by pmd1nh** [comment]
```
pmdinh> ~/1_WAS/ASLiberty/2024_FEB/WS-CD-Open/dev (release) $ git log --oneline | grep pmdinh
17:1777c68ecf Merge pull request #31571 from pmdinh/27620-Update_Tests_To_Check_for_400_insteadof_500
```

**Comment by pmd1nh** [comment]
#build
#spawn.fullfat.buckets=io.openliberty.webcontainer.servlet.6.1.internal_fat,io.openliberty.webcontainer.servlet.6.0.internal_fat,com.ibm.ws.webcontainer.servlet.6.0_fat_toleration.lWAS,com.ibm.ws.webcontainer_fat,com.ibm.ws.webcontainer.servlet.3.1_fat,com.ibm.ws.webcontainer.servlet.4.0_fat,com.ibm.ws.webcontainer_fat_part2,com.ibm.ws.webcontainer_fat_servlet31toleration,com.ibm.ws.webcontainer_fat_servlet31toleration_part2,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0_part2,com.ibm.ws.webcontainer_fat_lWAS,com.ibm.ws.webcontainer_fat_servlet31_webcontainerlWAS,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0.lWAS

**Pull request merged**
