### PR TITLE
Improve build performance

### PR DESCRIPTION
**Pull request by fritze2**
This PR includes changes to improve the performance of clean and incremental builds.
- incremental builds would re-run `jakartaeeTransform` and `instrument` tasks. Fixed the tasks input/output configurations.
- enable parallel for local builds and fixed `copyFeatureBundles` to depend on `assemble`.

Still some more work to do here...
Clean build duration is 12:57.
First incremental build duration is 3:08 with 69 tasks executed.
Second incremental build duration is 2:48 with 30 tasks executed.

### CODE REVIEW

**Comment by fritze2** [comment]
#build

**Comment by fritze2** [comment]
#build

**Review by crpotter — APPROVED** [review]
LGTM

**Comment by fritze2** [comment]
I ran `.\gradlew.bat assemble` on a clean workspace Windows machine that took 15:03. The first incremental build took 2:03 with 69 tasks executed. The second incremental build took 1:53 with 28 tasks executed.

The projects that get re-built on incremental builds and need more investigation are:
```
com.ibm.ws.wssecurity.3.4.1
com.ibm.ws.springboot.support.version20.test.webanno.app
com.ibm.ws.springboot.support.version20.test.war.app
com.ibm.ws.springboot.support.version20.test.websocket.app
com.ibm.ws.security.saml.sso_fat.common
com.ibm.ws.springboot.support.version20.test.webflux.wrong.version.app
com.ibm.ws.wssecurity
com.ibm.ws.springboot.support.version20.test.webflux.app
com.ibm.ws.springboot.support.version20.test.actuator.app
com.ibm.ws.springboot.support.version20.test.multi.context.app
com.ibm.ws.springboot.support.version21.test.app
com.ibm.ws.springboot.support.version15.test.app
com.ibm.ws.springboot.support.version20.test.app
com.ibm.ws.springboot.support.version22.test.app
com.ibm.ws.springboot.support.version20.test.java.app
com.ibm.ws.org.apache.cxf.ws.security.2.6.2
com.ibm.ws.org.apache.cxf.rt.ws.security.3.4.1
com.ibm.ws.springboot.support.version23.test.app
```

**Pull request merged**
