### PR TITLE
Remove auditCollector-2.0

### PR DESCRIPTION
**Pull request by wrodrig**
We noticed that the `features`, enabled by this feature could also be enabled inside the `audit-2.0` feature. Doing this will help us to simplify our code.  Also products can still use auditCollector-1.0 as it is.

### CODE REVIEW

**Comment by wrodrig** [comment]
#build

**Comment by wrodrig** [comment]
#build

#libby

**Review by jhanders34 — DISMISSED** [review]

**Comment by wrodrig** [comment]
#build
#libby

**Review by jhanders34 — APPROVED** [review]

**Comment by jhanders34** [comment]
#build

**Pull request merged**
