### PR TITLE
Fixed ClassCastException in Computed Metrics code for MP Metrics

### LINKED ISSUE #26648: ClassCastException with new per_request code in mpMetrics.
It looks like when calculating the REST.elapsedTime per REST request, the elapsedTime returned by the MpMetrics feature is not monotonically increasing, which returns a negative value, causing the error.

```
Stack Dump = java.lang.ClassCastException: class java.lang.Double cannot be cast to class io.openliberty.microprofile.metrics.internal.monitor.computed.internal.EWMA (java.lang.Double is in module java.base of loader 'bootstrap'; io.openliberty.microprofile.metrics.internal.monitor.computed.internal.EWMA is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @71cfe741)
        at io.openliberty.microprofile.metrics.internal.monitor.computed.internal.ComputedMonitorMetricsHandler.calculateEWMAValue(ComputedMonitorMetricsHandler.java:575)
        at io.openliberty.microprofile.metrics.internal.monitor.computed.internal.ComputedMonitorMetricsHandler.calculateMetricValue(ComputedMonitorMetricsHandler.java:458)
        at io.openliberty.microprofile.metrics.internal.monitor.computed.internal.ComputedMonitorMetricsHandler.getComputedValue(ComputedMonitorMetricsHandler.java:400)
        at io.openliberty.microprofile.metrics.internal.monitor.computed.internal.ComputedMonitorGauge.getValue(ComputedMonitorGauge.java:36)
        at io.openliberty.microprofile.metrics.internal.monitor.computed.internal.ComputedMonitorMetricsHandler.lambda$registerNewComputedMetricWithExistingMetricTag$1(ComputedMonitorMetricsHandler.java:292)
        at io.smallrye.metrics.legacyapi.GaugeAdapter$FunctionGauge.lambda$register$0(GaugeAdapter.java:98)Z
  ```

### PR DESCRIPTION
**Pull request by pgunapal**
fixes #26648

### CODE REVIEW

**Comment by pgunapal** [comment]
#build

**Comment by pgunapal** [comment]
#build

**Comment by pgunapal** [comment]
#build
#spawn.fullfat.buckets=io.openliberty.microprofile.metrics.internal.3.x.monitor_fat,io.openliberty.microprofile.metrics.internal.4.x.monitor_fat,io.openliberty.microprofile.metrics.internal.5.x.monitor_fat

**Review by Channyboy — APPROVED** [review]
lgtm

**Comment by pgunapal** [comment]
#libby

**Pull request merged**
