### PR TITLE
Fix log marks on windows servlet31 fat

### LINKED ISSUE #25235: Reset log marks in Servlet 3.1 FAT after trace is configured for Windows
https://github.com/OpenLiberty/open-liberty/pull/25143 sets trace dynamically when the FAT bucket is executed on the Windows platform. Log marks are set so that the configuration can complete before moving on to the tests. However, if a test is using `waitForStringInLog` and the message being looked for occurs before these marks are set the tests will now fail as the `waitForStringInLog` method will start looking from the mark onward.

### PR DESCRIPTION
**Pull request by pnicolucci**
fixes #25235

### CODE REVIEW

**Comment by pnicolucci** [comment]
#libby #build #spawn.fullfat.buckets=com.ibm.ws.webcontainer.servlet.3.1_fat

**Comment by pnicolucci** [comment]
Windows build: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_MfLa0O5_Ee2D8Kk7c5d7Ig&tab=com.ibm.team.build.web.ui.internal.editors.result.properties.PropertiesProvider

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
Windows build: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_OOwe0O8_Ee2D8Kk7c5d7Ig

**Review by pmd1nh — APPROVED** [review]

**Pull request merged**
