### PR TITLE
Feature file updates for various issues

### LINKED ISSUE #16127: ID: authFilter element is missing from generated feature docs and has incorrect descriptions
**Describe the bug**
The Open LIberty autogenerated docs for the `authFilter` element, which is generated from [this metatype.properties file](https://github.com/OpenLiberty/open-liberty/blob/integration/dev/com.ibm.ws.security.authentication.filter/resources/OSGI-INF/l10n/metatype.properties) (and other files in the [com.ibm.ws.security.authentication.filter directory](https://github.com/OpenLiberty/open-liberty/tree/integration/dev/com.ibm.ws.security.authentication.filter)), has two issues:

1. The autogen is not pulling in the attribute descriptions from [com.ibm.ws.security.authentication.filter/resources/OSGI-INF/l10n/metatype.properties](https://github.com/OpenLiberty/open-liberty/blob/integration/dev/com.ibm.ws.security.authentication.filter/resources/OSGI-INF/l10n/metatype.properties). Instead, it pulls in a single description for all the attributes, "A unique configuration ID.". See [the authFilter autogen page](https://www.openliberty.io/docs/21.0.0.2/reference/config/authFilter.html) for example.
2. The `authFilter` configuration element has disappeared from all generated feature doc pages which previously included the element in the "Feature configuration elements". This bug occurred sometime between the 20.0.0.11 and 20.0.0.12 Ga releases. For example, see the [20.0.0.11 version of the MpJWT feature page](https://www.openliberty.io/docs/20.0.0.11/reference/feature/mpJwt-1.1.html), which displays the element, and any later version of the feature page, [for example 21.0.0.2](https://www.openliberty.io/docs/21.0.0.2/reference/feature/mpJwt-1.1.html), which do not. This is the case for all liberty features that use `authFilter` .

This information is not maintained by the docs team and is pulled in automatically from properties files in the Open Liberty repo.

**Steps to Reproduce**
See doc links above

**Expected behavior**
1. The authFilter autogen page should pull in the appropriate attribute descriptions that are specified in [com.ibm.ws.security.authentication.filter/resources/OSGI-INF/l10n/metatype.properties](https://github.com/OpenLiberty/open-liberty/blob/integration/dev/com.ibm.ws.security.authentication.filter/resources/OSGI-INF/l10n/metatype.properties).
2. all version of feature pages for feaures that use authFilter should display the authFilter element in the "Feature configuration elements" list.

**Diagnostic information:**
 - OpenLiberty DOCS Versions 20.0.0.12 and later (currently through 21.0.0.2)

**Additional context**
https://github.com/OpenLiberty/open-liberty/pull/14099 may be relevant @jvanhill @utle

### PR DESCRIPTION
**Pull request by jhanders34**
- Update non auto features to not have the when satisfied install policy
- Fix up so that distributedInternal and builtinAuthentication are not needed by features that depend on the features that tolerate those
- Change javaee / jakarta auto features to private singleton features
- Add eeCompatible to appSecurity-1.0 and 2.0 features
- Fix oauth internal bundle to export openidconnect token package and move the api jar to the -jars section instead of also being a bundle.
- Update tested.features for FATs that add JakartaEE9Action.  With using private features instead of auto features the dependencies are detected differently.
- Update org.opensaml.opensaml bundle to not export org.opensaml.xml, but to import it from the org.opensaml.xmltooling bundle instead.  Without the import if bundles loaded in a different order the opensaml xml would not be found and the saml feature would fail to start.

Fixes #16127

### CODE REVIEW

**Comment by jhanders34** [comment]
#build

**Review by kristip17 — APPROVED** [review]

**Review by cbridgha — APPROVED** [review]
Thanks - Looks good

**Review by jvanhill — APPROVED** [review]

**Review by njr-11 — APPROVED** [review]

**Review by anjumfatima90 — APPROVED** [review]

**Review by arunavemulapalli — APPROVED** [review]
I just focused on samlWeb feature changes and they look good.

**Comment by jhanders34** [comment]
#libby

**Pull request merged**
