### PR TITLE
Enable Spec Issue 1404 and 1423 tests for EE10

### PR DESCRIPTION
**Pull request by pnicolucci**
for #22368

### CODE REVIEW

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
Java 17 build: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_fOZ3oKNgEe23HdxJAjh3dw

**Comment by pnicolucci** [comment]
Java 17 tests were successful!

**Comment by pnicolucci** [comment]
rebasing on RC4 to make sure we're still all good

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
new java17 build https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_jEsKQKPwEe23HdxJAjh3dw

**Comment by pnicolucci** [comment]
Java 17 tests were successful

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
latest Java 17 build: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_KsaLAKSkEe24er7gxU0d3Q

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
Java 17 build: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_zN91wKZzEe24er7gxU0d3Q

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
Java 17 builds: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_gCKa4KcFEe24er7gxU0d3Q

**Comment by pnicolucci** [comment]
Java 17 tests were successful

**Comment by pnicolucci** [comment]
#libby #build

**Review by isaacrivriv — APPROVED** [review]

**Pull request merged**
