### PR TITLE
change repo path for featureUtility fat

### PR DESCRIPTION
**Pull request by jjiwooLim**
Reintroducing FAT tests for #14677

### CODE REVIEW

**Comment by jjiwooLim** [comment]
#build

**Comment by jjiwooLim** [comment]
External build sanity check: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_gd9qEAB8EeyB1uNHimT5CA&tab=com.ibm.team.build.web.ui.internal.editors.result.properties.PropertiesProvider

**Comment by jjiwooLim** [comment]
#libbybot

**Comment by jjiwooLim** [comment]
#libby-bot

**Review by bensonlatibm — APPROVED** [review]
lgtm!

**Pull request merged**
