### PR TITLE
Correct isWsoc21rHigher method name to isWsoc21OrHigher

### LINKED ISSUE #22257: Fix spelling of isWsoc21orHigher
Please open an issue so we don't forget to fix this misspelling: `isWsoc21orHigher`

_Originally posted by @pnicolucci in https://github.com/OpenLiberty/open-liberty/pull/21984#discussion_r954431408_

### PR DESCRIPTION
**Pull request by pnicolucci**
fixes #22257

### CODE REVIEW

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
#libby #build

**Review by pmd1nh — APPROVED** [review]

**Pull request merged**
