### PR TITLE
Use com.ibm.fips.mode

### PR DESCRIPTION
**Pull request by rlcundiff**
For https://github.com/OpenLiberty/open-liberty/issues/27649

### CODE REVIEW

**Comment by rlcundiff** [comment]
#build

**Review by Zech-Hein — APPROVED** [review]
LGTM

**Comment by rlcundiff** [comment]
Since this is a new and as yet unused project, the single build failure in a Springbok FAT is unrelated.

**Comment by rlcundiff** [comment]
#libby

**Pull request merged**
