### PR TITLE
Test checkpoint/restore with managedBeans

### PR DESCRIPTION
**Pull request by anjumfatima90**
#21336

### CODE REVIEW

**Comment by anjumfatima90** [comment]
#build

**Review by dazavala — DISMISSED** [review]
Nice work @anjumfatima90 .  I wasn't able to determine what exactly triggers the container to invoke the preDestroy method on the managed bean instance.  When you have a few minute, please let me know.

**Comment by anjumfatima90** [comment]
Thanks @dazavala. When we lookup the bean and doesn't hold any references it would eventally call @preDestroy signaling the managed bean instance is being removed.

**Comment by anjumfatima90** [comment]
#build

**Review by dazavala — APPROVED** [review]
LGTM!

**Comment by anjumfatima90** [comment]
#libby

**Pull request merged**
