### PR TITLE
Remove default ID from appProperties

### PR DESCRIPTION
**Pull request by brenthdaniel**
Remove the default ID from the appProperties metatype

### CODE REVIEW

**Comment by brenthdaniel** [comment]
#build

**Comment by Joseph-Cass** [comment]
I think the #build tool was and still is poorly. I'll try starting a PB manually

**Comment by Joseph-Cass** [comment]
No idea if this will work, but I've tried requesting a re-build of a recent PB and changed the related PR number to 15491 (this one), here: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_j8t3gFSnEeuFI6_BZVYvOw

**Comment by tevans78** [comment]
@Joseph-Cass sorry, close by no cigar, you needed to update the branch name as well. I'll start a new build.

**Comment by tevans78** [comment]
New personal build: https://wasrtc.hursley.ibm.com:9443/jazz/resource/itemOid/com.ibm.team.build.BuildResult/_avIIwFS2EeuFI6_BZVYvOw

**Comment by Joseph-Cass** [comment]
> @Joseph-Cass sorry, close by no cigar, you needed to update the branch name as well. I'll start a new build.

Oooo close! Thanks Tom :)

**Comment by tevans78** [comment]
#link 280912

**Review by tevans78 — APPROVED** [review]

**Comment by tevans78** [comment]
Out of time to wait for the PB to finish. Merging anyway so that we can get this into the GM tomorrow.

**Comment by brenthdaniel** [comment]
Heh, I started a manual one yesterday as well.. https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_vwMLwFSKEeuFI6_BZVYvOw&tab=com.ibm.team.build.web.ui.internal.editors.result.overview.OverviewPage .. It's still running, but green at 60k tests (including mp config)

**Comment by brenthdaniel** [comment]
The build finished green

**Pull request merged**
