### PR TITLE
GA all MicroProfile 4.0 features

### LINKED ISSUE #15651: GA MicroProfile 4.0 features
Need to update all MP 4.0 features from beta to ga

### PR DESCRIPTION
**Pull request by tevans78**
Move all MicroProfile 4.0 (and those they depend on) to GA.
Do not merge until all epics have been fully approved.
fixes #15651 
#build

### CODE REVIEW

**Review by Emily-Jiang — COMMENTED** [review]
What about the mpCompatible-0.0 feature?

**Comment by tevans78** [comment]
> What about the mpCompatible-0.0 feature?

@Emily-Jiang it is already GA because GA features depend on it

**Comment by tevans78** [comment]
#build

**Comment by tevans78** [comment]
This PR has been replaced by https://github.com/OpenLiberty/open-liberty/pull/15687

**Pull request closed without merging**
