### PR TITLE
Rerun runtime trace injection if problem byte codes are detected.

### PR DESCRIPTION
**Pull request by tbitonti**
For issue #16007.

### CODE REVIEW

**Comment by tbitonti** [comment]
#build

**Review by cbridgha — DISMISSED** [review]
Overriding these adapters to catch the exception, and then allowing ASM to recompute the frames.

**Comment by tbitonti** [comment]
Tested by RAS test bucket com.ibm.ws.ras.instrument_test.  Also verified by customer test of IFIX.

**Comment by tbitonti** [comment]
#build

**Review by hlhoots — APPROVED** [review]
LGTM

**Comment by tbitonti** [comment]
#libby

**Pull request merged**
