### PR TITLE
Bring in eclipselink performance fix removing getStackTrace calls

### LINKED ISSUE #19087: Throughput performance degradation in eclipselink due to Thread.getStackTrace calls
Describe the bug
I have a simple REST/JPA application running on open liberty that performs jpa queries. A change to the org.eclipse.persistence.internal.helper.ConcurrencyManager class is causing a 75% throughput performance degradation for that particular application (~26k req/sec down to ~6k req/sec). See eclipselink issue: https://github.com/eclipse-ee4j/eclipselink/issues/1343 for more details.

Steps to Reproduce
Take any simple jpa application that uses the jpa-2.2 feature and compare throughput application between 21.0.0.7 and 21.0.0.11

Expected behavior
No throughput degradation between liberty releases.

Diagnostic information:
OpenLiberty Version: 21.0.0.8, 21.0.0.9, 21.0.0.10, 21.0.0.11
Affected feature(s): jpa-2.2
Java Version:
server.xml: <feature>jpa-2.2</feature>
Additional context

### PR DESCRIPTION
**Pull request by dettmoney**
This fix will address the problem associated with Issue #19087 . These are fixes that have been integrated into the eclipselink github repositories.

Fixes #19087

### CODE REVIEW

**Comment by dettmoney** [comment]
#build

**Comment by dettmoney** [comment]
I tested the personal build and verified fix works for both jakarta9 and ee8.

**Comment by dettmoney** [comment]
#build

**Review by jhanders34 — APPROVED** [review]

**Review by dazey3 — APPROVED** [review]
lgtm

**Pull request merged**
