### PR TITLE
Issue #17647: Remove SharedServer from WCAddJspFileTest

### LINKED ISSUE #17647: Remove SharedServer from WCAddJspFileTest in the Servlet 4.0 FAT

### PR DESCRIPTION
**Pull request by pnicolucci**
fixes #17647

### CODE REVIEW

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#run-libby-bot

**Comment by pnicolucci** [comment]
#build

**Review by volosied — APPROVED** [review]
looks good to me

**Review by isaacrivriv — APPROVED** [review]
Looks good to me. Thanks!

**Comment by pnicolucci** [comment]
#run-libby-bot

**Pull request merged**
