### PR TITLE
Verify the transaction log datasource configures at restore

### PR DESCRIPTION
**Pull request by dazavala**
For issue #21198

Modify `TransactionLogTest.testTransactionDbLogBasicConnection()` to further verify the transaction log datasource configuration updates, during restore, with config attribute(s) declared in the server.env file. The test now logs transactions to an in-memory database running in a separate process, rather than an embedded database, to more closely emulate usage within container environments.

### CODE REVIEW

**Comment by dazavala** [comment]
#build 
@tjwatson PR is ready for review.  InstantOn build request submitted.

**Comment by dazavala** [comment]
@tjwatson Review changes are uploaded.

**Comment by dazavala** [comment]
#build

**Review by tjwatson — DISMISSED** [review]

**Comment by dazavala** [comment]
InstantOn: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_K37hMOB-Ee2OBOiL2tO6zA

**Comment by dazavala** [comment]
Had a conflict with integration.  Rebuilding...
#build

**Comment by dazavala** [comment]
#build
InstantOn: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_tquREOCGEe2OBOiL2tO6zA

**Comment by dazavala** [comment]
The InstantOn and Liberty personal builds passed.  WIll merge pending copyright and review approvals (attn @tjwatson: I resolved a merge confict with integration after Friday's review).

**Comment by dazavala** [comment]
#libby

**Review by tjwatson — APPROVED** [review]

**Pull request merged**
