### PR TITLE
Use Set for child elements

### PR DESCRIPTION
**Pull request by brenthdaniel**
PR for #17562

### CODE REVIEW

**Comment by brenthdaniel** [comment]
#build

**Comment by brenthdaniel** [comment]
#build

**Comment by brenthdaniel** [comment]
#build

**Comment by brenthdaniel** [comment]
Things are mostly fine in the last build, but there was a GPF in one bucket and some UI failures.. Building again to make sure things are clean. 

#build

**Review by hlhoots — APPROVED** [review]
LGTM

**Comment by brenthdaniel** [comment]
#run-libby-bot

**Pull request merged**
