### PR TITLE
Deliver EclipseLink Issue #1823 overlay

### PR DESCRIPTION
**Pull request by dazey3**
for #24599

Delivering this fix as an overlay to be removed when the next EclipseLink 3.0.4 releases.

### CODE REVIEW

**Comment by dazey3** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jpa.tests.eclipselink_jpa_3.0_fat

**Comment by dazey3** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jpa.tests.eclipselink_jpa_3.0_fat

**Review by jgrassel — APPROVED** [review]
lgtm

**Comment by dazey3** [comment]
#run-libby-bot

**Pull request merged**
