### PR TITLE
Update to RC3/2 of JSONP/B respectively

### PR DESCRIPTION
**Pull request by aguibert**

### CODE REVIEW

**Comment by aguibert** [comment]
#build

**Comment by aguibert** [comment]
Closes #13744 #13747 #13749

**Review by dazavala — APPROVED** [review]
Looks good.  Thanks for handling the json updates.

**Comment by aguibert** [comment]
#build

**Comment by aguibert** [comment]
#run-libby

**Comment by dazavala** [comment]
Fixes #11633

**Pull request merged**
