### PR TITLE
remove versionless features from the productInfo featureInfo command

### PR DESCRIPTION
**Pull request by rsherget**
- [x] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [x] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [x] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

#29705

### CODE REVIEW

**Comment by rsherget** [comment]
#build

**Review by cbridgha — APPROVED** [review]
looks good

**Comment by rsherget** [comment]
#build

**Comment by rsherget** [comment]
#build

**Comment by rsherget** [comment]
#libby

**Pull request merged**
