### PR TITLE
feat: Enable use of verified docker images from public.aws.ecr

### PR DESCRIPTION
**Pull request by KyleAure**
- [x] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [x] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [x] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

Allow us to construct a new docker image name in steps depending on which registry the original image originates.
This will allow us to use images from alternative registries such as AWS, ICR, and GHCR.

### CODE REVIEW

**Comment by KyleAure** [comment]
#build ([view Open Liberty Personal Build](https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?pipelineId=de0cc73c-3c68-472b-badf-873ff07b7608) - :x: completed with errors/failures.)

_Note: Target locations of links might be accessible only to IBM employees._

**Review by mswatosh — DISMISSED** [review]

**Comment by KyleAure** [comment]
#build ([view Open Liberty Personal Build](https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?pipelineId=c57eadf9-ac5e-4e74-8354-5c71e8365ba0) - :x: completed with errors/failures.)

_Note: Target locations of links might be accessible only to IBM employees._

**Review by mswatosh — APPROVED** [review]

**Comment by KyleAure** [comment]
FYI - Not running a PostgreSQL Database rotation test because I only updated the build.example bucket.

**Comment by KyleAure** [comment]
Pipeline: failed with two known defects
RTC Build: (In progress)

**Pull request merged**
