### PR TITLE
DHE server check for PRs changing cnf/oss_ibm.maven

### PR DESCRIPTION
**Pull request by wraschke**
- [ ] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [ ] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [ ] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

For comparable validation of "DHE check" whenever a PR changes file `dev/cnf/oss_ibm.maven`. See 
https://github.com/OpenLiberty/open-liberty/pull/28338 as an example.

If a GAV entry is added or modified, then the corresponding prereq binaries in https://public.dhe.ibm.com/ibmdl/export/pub/software/olrepo/ must be present; otherwise, external contributors will not be able to build Open Liberty themselves.

### CODE REVIEW

**Comment by wraschke** [comment]
!libby@dev ([view Open Liberty Delivery Requirements Verification](https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?pipelineId=c98e4c01-03d3-4224-83b1-9ea410cd1866) - :x: completed with errors/failures.)

_Note: Target locations of links might be accessible only to IBM employees._

**Comment by wraschke** [comment]
!libby@dev ([view Open Liberty Delivery Requirements Verification](https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?pipelineId=7f625861-d3c9-46dd-b1ad-f456822c80fc) - :x: completed with errors/failures.)

_Note: Target locations of links might be accessible only to IBM employees._

**Comment by wraschke** [comment]
!libby@dev ([view Open Liberty Delivery Requirements Verification](https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?pipelineId=c65758c4-cbfb-475d-9a74-a791ac9e4c2c) - :white_check_mark: completed successfully!)

_Note: Target locations of links might be accessible only to IBM employees._

**Comment by wraschke** [comment]
!libby@dev ([view Open Liberty Delivery Requirements Verification](https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?pipelineId=a6f646cc-190a-4557-91ad-942a24d1799d) - :white_check_mark: completed successfully!)

_Note: Target locations of links might be accessible only to IBM employees._

**Comment by wraschke** [comment]
!libby@dev ([view Open Liberty Delivery Requirements Verification](https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?pipelineId=be00a6f3-66ca-4f6b-9f73-5a168f80d9ff) - :x: completed with errors/failures.)

_Note: Target locations of links might be accessible only to IBM employees._

**Comment by wraschke** [comment]
!libby@dev

**Comment by wraschke** [comment]
!build@dev

**Comment by wraschke** [comment]
!libby@dev ([view Open Liberty Delivery Requirements Verification](https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?pipelineId=53c7aa88-b377-465c-b950-9db0ddddbf3d) - :white_check_mark: completed successfully!)

_Note: Target locations of links might be accessible only to IBM employees._

**Comment by wraschke** [comment]
!build@dev ([view Open Liberty Personal Build](https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?pipelineId=d70a2f5d-cb90-4787-b7d9-eeaf9b604de7) - :x: completed with errors/failures.)

_Note: Target locations of links might be accessible only to IBM employees._

**Comment by wraschke** [comment]
!libby@dev ([view Open Liberty Delivery Requirements Verification](https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?pipelineId=b2fc34ab-f32b-4eb8-8cfd-bdc522df4829) - :white_check_mark: completed successfully!)

_Note: Target locations of links might be accessible only to IBM employees._

**Comment by wraschke** [comment]
!libby@dev ([view Open Liberty Delivery Requirements Verification](https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?pipelineId=901575c2-83ec-49bd-a9c4-a20888580c8c) - :white_check_mark: completed successfully!)

_Note: Target locations of links might be accessible only to IBM employees._

**Comment by wraschke** [comment]
!libby@dev ([view Open Liberty Delivery Requirements Verification](https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?pipelineId=dac61d47-055c-4340-82ac-23d51631a538) - :white_check_mark: completed successfully!)

_Note: Target locations of links might be accessible only to IBM employees._

**Comment by wraschke** [comment]
!libby@dev ([view Open Liberty Delivery Requirements Verification](https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?pipelineId=0385698b-c47d-498c-a681-0c0ba5b4b887) - :white_check_mark: completed successfully!)

_Note: Target locations of links might be accessible only to IBM employees._

**Comment by wraschke** [comment]
!pb@dev ([view Open Liberty Personal Build](https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?pipelineId=33c88c90-772d-4dfc-8e33-ba2af36f75e8) - :x: completed with errors/failures.)

_Note: Target locations of links might be accessible only to IBM employees._

**Comment by wraschke** [comment]
!build@dev

**Comment by wraschke** [comment]
!build

**Comment by wraschke** [comment]
!build

**Comment by wraschke** [comment]
!build@dev

**Comment by wraschke** [comment]
#build ([view Open Liberty Personal Build](https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?pipelineId=6ea17f44-eb27-404a-b44b-5dd0ae8e726c) - :x: completed with errors/failures.)

_Note: Target locations of links might be accessible only to IBM employees._

**Comment by wraschke** [comment]
!libby ([view Open Liberty Delivery Requirements Verification](https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?pipelineId=e9277d72-64f7-48f7-85e8-f03aa6cc8c7a) - :white_check_mark: completed successfully!)

_Note: Target locations of links might be accessible only to IBM employees._

**Comment by wraschke** [comment]
!build ([view Open Liberty Personal Build](https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?pipelineId=02523697-0afd-494a-860b-bcb9b5c0a6c1) - :x: completed with errors/failures.)

_Note: Target locations of links might be accessible only to IBM employees._

**Comment by wraschke** [comment]
!libby ([view Open Liberty Delivery Requirements Verification](https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?pipelineId=0e7ed07c-169b-47ad-8a39-b00b35dac0a7) - :white_check_mark: completed successfully!)

_Note: Target locations of links might be accessible only to IBM employees._

**Review by rickettmwork — APPROVED** [review]

**Comment by wraschke** [comment]
The [Open Liberty personal pipeline 02523697-0afd-494a-860b-bcb9b5c0a6c1](https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?pipelineId=02523697-0afd-494a-860b-bcb9b5c0a6c1) failed due to the images creation build failing with

```
/home/jazz_build/Build/jbe/build/WS-CD-Open/dev/ant_build/public_imports/internal_imports/standard_macros.xml:400: The following error occurred while executing this line:
/home/jazz_build/Build/jbe/build/WS-CD-Open/dev/ant_build/public_imports/internal_imports/standard_macros.xml:1650: Task [parallel] failed after [2] attempts; giving up.
Error messages:
com.jcraft.jsch.JSchException: Auth fail for methods 'publickey,password'
com.jcraft.jsch.JSchException: Auth fail for methods 'publickey,password'
com.jcraft.jsch.JSchException: Auth fail for methods 'publickey,password'
```

And that was due to libertyfs hardware problem that has been resolved and Mike posted about at https://ibm-cloud.slack.com/archives/C30NGUQ9E/p1734336811019709,

The DHE server check, which is the step added by this PR, is unaffected by that and behaved per expectation (no dev/cnf/oss_ibm.maven file changed so no DHE server artifacts status check created).

The multiple code checklist comments created in this PR are due to the multiple build directive comments I created trying to get the poller to respond (the config YML was not correct at the time), then the additional LibbyBot pipeline run, then the OL personal pipeline run, then the legacy LibbyBot automation running.

So I am merging this PR.

**Pull request merged**
