### PR TITLE
Make ApplicationPrereqs satisfied before BatchJMS messageEndpoints

### PR DESCRIPTION
**Pull request by AndrewDJBanks**

### CODE REVIEW

**Comment by AndrewDJBanks** [comment]
fixes #19878

**Comment by AndrewDJBanks** [comment]
#build

**Review by joe-chacko — APPROVED** [review]
This might just work.

**Review by joe-chacko — CHANGES_REQUESTED** [review]
Actually, I'm not so sure…

**Review by joe-chacko — CHANGES_REQUESTED** [review]
I am not convinced this will fix the issue, because there is nothing to stop `setServerStartedPhase2()` or any other bind method from being called *before* `setApplicationStartBarrier()`.

**Comment by AndrewDJBanks** [comment]
#build

**Comment by joe-chacko** [comment]
Made a few improvements to the new BatchJmsExecutor, and fixed a bug to tie the optional connection factory in with meta type.
#build should produce fewer failures this time

**Pull request closed without merging**
