### PR TITLE
15724 kernel.boot fat

### PR DESCRIPTION
**Pull request by tbitonti**
FAT only update:
This rewrites the loose packaging tests, and adds a new loose configuration with excludes test (PackageLooseFilterTest).
The new test recreates issue #15724, and is disabled until the fix for that issue is merged.

This update is *not* a fix for issue #15724.  An additional update will provide the fix, and will enable the currently disabled filter test.

The rewrite removes the test classes PackageLooseConfigTest, PackageLooseConfigDropinsTest, and PackageLooseConfigParameterizedTest.  Those are replaced with PackageLooseRunnableTest and 
PackageLooseContentsTest.

The rewrite was substantially to shift reusable code to "AbstractLooseConfigTest".  This implacted  "PackageCommandTest".

Numerous test problems were fixed, including resource management, and including handling blocking IO when retrieving log messages from server processes.

The tests were updated to more fully use the repeatable test pattern, and have new cases not run by the original tests.

### CODE REVIEW

**Comment by tbitonti** [comment]
#build

**Comment by tbitonti** [comment]
#build

**Comment by tbitonti** [comment]
#build

**Comment by tbitonti** [comment]
#build

**Review by cbridgha — APPROVED** [review]
Changes look good to me - thanks

**Comment by tbitonti** [comment]
#libby

**Pull request merged**
