### PR TITLE
7056: Allow all HTTP methods with Http/2

### PR DESCRIPTION
**Pull request by loriadi**
Http/2 and Http/1.1 are behaving differently with regards to non-standard http methods.

Http/1.1 allows the PATCH method to go through while Http/2 gives a 501 unimplemented error.

Change this so that any method will be accepted at this layer for both protocols.

### CODE REVIEW

**Comment by loriadi** [comment]
fixes #7056

**Comment by loriadi** [comment]
#run-libby-bot

**Comment by loriadi** [comment]
#build

**Comment by loriadi** [comment]
Both test failures appear to be unrelated to this change.  The grpc failure has a defect, the jpa failure seems unrelated.

**Review by wtlucy — APPROVED** [review]
Looks good to me - a FAT case will be added in a follow-on PR.

**Pull request merged**
