### PR TITLE
Migrate JPA EJB Passivation Tests to Open Liberty.

### PR DESCRIPTION
**Pull request by jgrassel**
Signed-off-by: Joe Grassel <jgrassel@us.ibm.com>

Migrate EJB Passivation test for JPA to Open Liberty.

### CODE REVIEW

**Comment by jgrassel** [comment]
Fixed the headers.

**Comment by jgrassel** [comment]
#build

**Comment by jgrassel** [comment]
#build

**Comment by dazey3** [comment]
LGTM

**Pull request merged**
