### PR TITLE
Clean up some more unnecessary transformations

### PR DESCRIPTION
**Pull request by jhanders34**
- Do not transform com.ibm.ws.micrprofile.metrics.common, com.ibm.ws.security.mp.jwt.propagation or com.ibm.ws.transaction.fat.util

### CODE REVIEW

**Comment by jhanders34** [comment]
#build

**Comment by jhanders34** [comment]
#libby #build

**Comment by jhanders34** [comment]
#build

**Comment by ayoho** [comment]
@jhanders34 The mp.jwt.propagation package needed to be transformed for that aspect of functionality to work with MP JWT 2.0. We have FATs that ensure we can use some JAX-RS (now restfulWS-3.0) client properties to automatically propagate JWTs. The mp.jwt.propagation package provides the implementation for those particular services. Without that package being transformed, our propagation scenarios fail with MP JWT 2.0.

**Comment by jhanders34** [comment]
#build

**Comment by jhanders34** [comment]
> @jhanders34 The mp.jwt.propagation package needed to be transformed for that aspect of functionality to work with MP JWT 2.0. We have FATs that ensure we can use some JAX-RS (now restfulWS-3.0) client properties to automatically propagate JWTs. The mp.jwt.propagation package provides the implementation for those particular services. Without that package being transformed, our propagation scenarios fail with MP JWT 2.0.

Nothing is transformed though.  There is nothing in the bundle that references javax packages.  So why do you think it needs to be transformed?  The transformed bundles are identical.  The import of the mp jwt APIs already has a range that works for all versions of MP JWT.

**Review by jonhawkes — APPROVED** [review]

**Comment by ayoho** [comment]
That's true - I probably mistakenly thought we needed the bundle to be transformed but really it was just the missing autofeature that we had needed. I'd think the changes that you have should be fine, in that case.

**Review by ayoho — APPROVED** [review]

**Pull request merged**
