### PR TITLE
fix ltpa keys resource resolving

### LINKED ISSUE #26341: 23.0.0.9 CWWKE0701E: bundle com.ibm.ws.security.token.ltpa failure at server startup
**Describe the bug**  
After upgrading Liberty to 23.0.0.9 the following failure occurs at server startup.

```
9/20/23, 11:21:44:530 GMT] 0000001f LogService-134-com.ibm.ws.security.token.ltpa                E CWWKE0701E: bundle com.ibm.ws.security.token.ltpa:1.0.81.cl230920230904-115
8 (134)[com.ibm.ws.security.token.ltpa.internal.LTPAConfigurationImpl(432)] : The activate method has thrown an exception java.lang.NullPointerException
        at com.ibm.ws.security.token.ltpa.internal.LTPAConfigurationImpl.resolveActualPrimaryKeysFileLocation(LTPAConfigurationImpl.java:254)
        at com.ibm.ws.security.token.ltpa.internal.LTPAConfigurationImpl.loadConfig(LTPAConfigurationImpl.java:152)
        at com.ibm.ws.security.token.ltpa.internal.LTPAConfigurationImpl.activate(LTPAConfigurationImpl.java:134)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
```

**Steps to Reproduce**  
Specify an absolute path for the ltpa keys file:
`<ltpa keysFileName="/opt/path/to/ltpa.keys" />`

**Expected behavior**  
The server should be able to startup without failure and use a `keysFileName` with an absolute path value specified.

**Diagnostic information:**  
 - OpenLiberty Version: 23.0.0.9
 - Affected feature(s): appSecurity-*
 - Java Version: any
 - server.xml configuration: 
 `<ltpa keysFileName="/opt/path/to/ltpa.keys" />`

**Workaround**  
A workaround is to use the `default` (i.e. not specified or `${server.config.dir}/resources/security/ltpa.keys`) location/value for `keysFileName` or any path relative to the Liberty server like `${server.config.dir}/ltpa.keys`

**Console Output**
```
[ERROR   ] CWWKE0701E: bundle com.ibm.ws.security.token.ltpa:1.0.81.cl230920230904-115
8 (134)[com.ibm.ws.security.token.ltpa.internal.LTPAConfigurationImpl(432)] : -
The activate method has thrown an exception java.lang.NullPointerException: -
Cannot invoke "com.ibm.wsspi.kernel.service.location.WsResource.toRepositoryPath()" -
because the return value of "com.ibm.wsspi.kernel.service.location.WsResource.getParent()" is null
        at com.ibm.ws.security.token.ltpa.internal.LTPAConfigurationImpl.resolveActualPrimaryKeysFileLocation(LTPAConfigurationImpl.java:254)
        at [internal classes]
```

### PR DESCRIPTION
**Pull request by Zech-Hein**
fixes #26341

### CODE REVIEW

**Comment by Zech-Hein** [comment]
#libby
#build
#spawn.fullfat.buckets=com.ibm.ws.security.token.ltpa_fat

**Review by utle — COMMENTED** [review]
We should return after line 226

**Comment by Zech-Hein** [comment]
#libby
#build
#spawn.fullfat.buckets=com.ibm.ws.security.token.ltpa_fat

**Review by utle — APPROVED** [review]

**Comment by Zech-Hein** [comment]
The last PB is hanging, starting another one
#build
#spawn.fullfat.buckets=com.ibm.ws.security.token.ltpa_fat

**Comment by Zech-Hein** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.security.token.ltpa_fat

**Comment by Zech-Hein** [comment]
Fixes #PH57076

**Pull request merged**
