### PR TITLE
Organize Faces/JSF impl exports

### LINKED ISSUE #24452: Organize Faces exports to thread-context

### PR DESCRIPTION
**Pull request by pnicolucci**
fixes #24452

### CODE REVIEW

**Comment by pnicolucci** [comment]
#libby #build

**Comment by wraschke** [comment]
#libby

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
#libby #build

**Review by volosied — APPROVED** [review]
Looks good. I'm assuming 4.0 was organized already?

**Comment by pnicolucci** [comment]
> Looks good. I'm assuming 4.0 was organized already?

@volosied there are changes for 4.0 in this PR :)

**Pull request merged**
