### PR TITLE
Fix OL FATs that fail on IBM i due to incorrect shell usage

### LINKED ISSUE #24258: Some OL FATs fail on IBM i due to incorrect shell usage
On IBM i, some FATs hit untranslated EBCDIC characters that cause the test to fail.  This is because they are calling the `/bin/sh` shell by default, which is an ILE program (EBCDIC) and should be avoided since FATs run in PASE (ASCII).  

Using the non-ILE shell `/QOpenSys/usr/bin/sh` was the only shell I could find where we did not run into the untranslated EBCDIC characters in our FAT testing.

### PR DESCRIPTION
**Pull request by gjwatts**
Fixes: #24258

### CODE REVIEW

**Comment by gjwatts** [comment]
#build

**Comment by gjwatts** [comment]
Last force push was just to update the copyright date, no code was changed.

**Comment by gjwatts** [comment]
#build

**Review by sebratton — DISMISSED** [review]

**Review by jim-krueger — DISMISSED** [review]
Thanks a lot Greg.  Looks good!

**Comment by gjwatts** [comment]
Had to rebase to pick up Jared's changes to `io.openliberty.ws.jaxws.tools_fat/fat/src/com/ibm/ws/jaxws/tools/test/FATTest.java` in PR https://github.com/OpenLiberty/open-liberty/pull/24261

**Comment by gjwatts** [comment]
#build

**Comment by gjwatts** [comment]
#build

**Review by sebratton — DISMISSED** [review]

**Comment by gjwatts** [comment]
#build

**Comment by gjwatts** [comment]
Force push was to update copyright date in comments, no code changed.

**Review by jim-krueger — APPROVED** [review]

**Review by sebratton — APPROVED** [review]

**Review by neuwerk — APPROVED** [review]
LGTM!

**Comment by gjwatts** [comment]
Waiting for IBM i build to start to verify this fixes the problem on that platform.

**Comment by gjwatts** [comment]
#libbybot

**Comment by gjwatts** [comment]
IBM i build completed successfully.  Merging.

**Pull request merged**
