### PR TITLE
Support added for SameSite cookie attribute

### LINKED ISSUE #10384: Support for SameSite attribute in Set-Cookie header is needed
With the upcoming stable version of Chrome 80, Chrome will treat cookies as SameSite=Lax by default if no SameSite attribute is specified.
More information can be found here:
https://www.chromestatus.com/feature/5088147346030592

Setting the cookie's SameSite option in application code by adding the "set-cookie" header can result in two separate cookies, instead of the SameSite attribute reconized as an attribute to the current cookie.

For instance, an expected HTTP header in the response using SameSite should read as:

Set-Cookie: sid=noS6xWtH3tdF6eLjQVngvqk; HttpOnly; Secure; SameSite=None

However, it could be split as: 

Set-Cookie: sid=noS6xWtH3tdF6eLjQVngvqk; Secure; HttpOnly
Set-Cookie: SameSite=None

### PR DESCRIPTION
**Pull request by mrsaldana**
fixes #10384

### CODE REVIEW

**Comment by mrsaldana** [comment]
#build

**Comment by pnicolucci** [comment]
#run-libby-bot

**Comment by mrsaldana** [comment]
#build

**Comment by mrsaldana** [comment]
Last build has one test failure, not associated to these changes.

**Pull request merged**
