### PR TITLE
Set uri value as part of the vendorProperties

### PR DESCRIPTION
**Pull request by zhang-ca**
The uri attribute directly on the httpSessionCache following JCache API:
javax.cache.spi.CachingProvider.getCacheManager(uri, classLoader, vendorProperties)
The getCacheManager API states, "Multiple calls to this method with the same URI and ClassLoader must return the same CacheManager instance". The URI is different in the some scenarios, since ${server.config.dir} is different for the two Liberty servers. This results in two separate cache managers --> different JCaches --> unshared sessions.

Therefore pass the uri value as part of the vendorProperties to ensure the uri attribute method works with latest Hazelcast versions.

### CODE REVIEW

**Comment by zhang-ca** [comment]
fixes #14594

**Comment by zhang-ca** [comment]
for #14594

**Comment by zhang-ca** [comment]
#build

**Review by bensonlatibm — APPROVED** [review]
lgtm!

**Comment by zhang-ca** [comment]
#build

**Pull request merged**
