### PR TITLE
Upgrade jose4j to 0.9.3

### LINKED ISSUE #23876: Upgrade usage of jose4j
We currently use version 0.6.5 of jose4j, but the latest version is 0.9.2. We should attempt to upgrade to a newer version of the project. Aside from the updated code benefits, we'll also benefit from the removal of prohibited words from the code base.

### LINKED ISSUE #25270: Upgrade jose4j library
Upgrade our usage of the jose4j library to the latest version available.

### PR DESCRIPTION
**Pull request by ayoho**
Upgrades the jose4j library.

Resolves #25270
Resolves #23876

### CODE REVIEW

**Comment by ayoho** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.security.jwt_fat.builder,com.ibm.ws.security.jwt_fat.consumer,com.ibm.ws.security.jwtsso_fat.mpJwt-1.1,com.ibm.ws.security.jwtsso_fat.mpJwt-1.2,com.ibm.ws.security.jwtsso_fat.mpJwt-2.0,com.ibm.ws.security.jwtsso_fat.mpJwt-2.1,com.ibm.ws.security.jwtsso_fat.noMpJwt,com.ibm.ws.security.mp.jwt.1.1_fat.mpJwt-1.1,com.ibm.ws.security.mp.jwt.1.1_fat.mpJwt-1.1.envVars,com.ibm.ws.security.mp.jwt.1.1_fat.mpJwt-1.1.sysProps,com.ibm.ws.security.mp.jwt.1.1_fat.mpJwt-1.2,com.ibm.ws.security.mp.jwt.1.1_fat.mpJwt-1.2.envVars,com.ibm.ws.security.mp.jwt.1.1_fat.mpJwt-1.2.sysProps,com.ibm.ws.security.mp.jwt.1.1_fat.mpJwt-2.0,com.ibm.ws.security.mp.jwt.1.1_fat.mpJwt-2.0.envVars,com.ibm.ws.security.mp.jwt.1.1_fat.mpJwt-2.0.sysProps,com.ibm.ws.security.mp.jwt.1.1_fat.mpJwt-2.1,com.ibm.ws.security.mp.jwt.1.1_fat.mpJwt-2.1.envVars,com.ibm.ws.security.mp.jwt.1.1_fat.mpJwt-2.1.sysProps,com.ibm.ws.security.mp.jwt.1.2_fat.mpJwt-1.2,com.ibm.ws.security.mp.jwt.1.2_fat.mpJwt-2.0,com.ibm.ws.security.mp.jwt.1.2_fat.mpJwt-2.1,com.ibm.ws.security.mp.jwt.2.1_fat.mpJwt-1.1,com.ibm.ws.security.mp.jwt.2.1_fat.mpJwt-1.2,com.ibm.ws.security.mp.jwt.2.1_fat.mpJwt-2.0,com.ibm.ws.security.mp.jwt.2.1_fat.mpJwt-2.1,com.ibm.ws.security.oauth_fat,com.ibm.ws.security.oidc.client_fat.1,com.ibm.ws.security.oidc.client_fat.2,com.ibm.ws.security.oidc.client_fat.backchannelLogout,com.ibm.ws.security.oidc.client_fat.backchannelLogout.saml,com.ibm.ws.security.oidc.client_fat.claimPropagation,com.ibm.ws.security.oidc.client_fat.jaxrs,com.ibm.ws.security.oidc.client_fat.spnego,com.ibm.ws.security.oidc.server_fat,com.ibm.ws.security.oidc.server_fat.backchannelLogout,com.ibm.ws.security.oidc.server_fat.jaxrs.config.commonTest,com.ibm.ws.security.oidc.server_fat.jaxrs.config.noOP,com.ibm.ws.security.oidc.server_fat.jaxrs.config.oauth,com.ibm.ws.security.oidc.server_fat.jaxrs.config.oidc,com.ibm.ws.security.oidc.server_fat.oidc,com.ibm.ws.security.social_fat,com.ibm.ws.security.social_fat.LibertyOP.1,com.ibm.ws.security.social_fat.LibertyOP.2,com.ibm.ws.security.social_fat.LibertyOP.backchannelLogout,com.ibm.ws.security.social_fat.LibertyOP.claimPropagation,com.ibm.ws.security.social_fat.OpenShift,com.ibm.ws.security.social_fat.delegated,com.ibm.ws.security.social_fat.multiProvider,com.ibm.ws.security.social_fat.okdServiceLogin,io.openliberty.security.jakartasec.3.0.internal_fat,io.openliberty.security.jakartasec.3.0.internal_fat.config.1,io.openliberty.security.jakartasec.3.0.internal_fat.config.2,io.openliberty.security.jakartasec.3.0.internal_fat.logout,io.openliberty.security.jakartasec.3.0.internal_fat.refresh

**Comment by ayoho** [comment]
Personal build https://wasrtc.hursley.ibm.com:9443/jazz/resource/itemOid/com.ibm.team.build.BuildResult/_3fmMEO6KEe2D8Kk7c5d7Ig passed with only one failure in security FATs for an already existing defect.

**Review by arunavemulapalli — APPROVED** [review]
do we need to remove this 
org.bitbucket.b_c:jose4j:0.6.5
from
oss_source_dependencies.maven?

**Comment by ayoho** [comment]
#libby

**Pull request merged**
