### PR TITLE
Refactor testcontainer projects

### PR DESCRIPTION
**Pull request by KyleAure**
Refactoring testcontainer projects to ensure setupTestContainers is called.

This issue is due to the fact that we now have FAT Suites in the Websphere Liberty project that run against testcontainers. 
Part of that workflow involves setting the docker.client.stategy property within the ~/.testcontainers.properties file on the underlying filesystem.
In OL our custom client strategy was moved to componenttest.containers.ExternalTestServiceDockerClientStrategy whereas in WL our custom client strategy is in componenttest.topology.utils.ExternalTestServiceDockerClientStrategy.
So the following events would take place on some build systems:
1. WL fat runs and sets docker.client.stategy=componenttest.topology.utils.ExternalTestServiceDockerClientStrategy
2. OL fat runs and never resets config
3. Testcontainers tries to find componenttest.topology.utils.ExternalTestServiceDockerClientStrategy
4. Finds it, but it is a deprecated version of what it used to be and no longer extends org.testcontainers.dockerclient.DockerClientProviderStrategy
5. Throws ClassCastException

Later I will go back and sync the OL and WL fattest projects to match.

### CODE REVIEW

**Comment by KyleAure** [comment]
#build

**Review by Azquelt — APPROVED** [review]

**Comment by KyleAure** [comment]
#build last build had failures

**Comment by KyleAure** [comment]
Build failed with two known defects.
#libbybot

**Comment by KyleAure** [comment]
#libbybot review my copyright headers

**Pull request merged**
