### PR TITLE
Delete old commons logging and codec projects

### PR DESCRIPTION
**Pull request by tevans78**
#build

### CODE REVIEW

**Comment by tevans78** [comment]
Appear to still be some references to the old projects in WS-CD-Open. Will need to fix them first

**Review by benjamin-confino — APPROVED** [review]

**Comment by tevans78** [comment]
#build

**Comment by tevans78** [comment]
#build

**Comment by tevans78** [comment]
#build

**Comment by tevans78** [comment]
One more go!
#build

**Comment by tevans78** [comment]
None of the failures in the PB look related to this.

**Pull request merged**
