### PR TITLE
add reset() to JSAdminService

### PR DESCRIPTION
**Pull request by AndrewDJBanks**

### CODE REVIEW

**Comment by AndrewDJBanks** [comment]
fixes #21901

**Comment by AndrewDJBanks** [comment]
#build

**Comment by wraschke** [comment]
#libby

**Comment by posmith** [comment]
L2 message review completed

**Comment by AndrewDJBanks** [comment]
#build

**Review by sakerl — APPROVED** [review]
Ideally, we might want to localize the IllegalStateException message, but that's something that could be done later if needed. The actual changes look good.

**Comment by AndrewDJBanks** [comment]
#build

**Comment by AndrewDJBanks** [comment]
#build

**Comment by AndrewDJBanks** [comment]
#libbybot

**Pull request merged**
