### PR TITLE
Do not associate vendor connection pool metrics with an application for MP Metrics 1.1

### PR DESCRIPTION
**Pull request by Channyboy**
- [x] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [x] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [x] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

################################################################################################

### CODE REVIEW

**Comment by Channyboy** [comment]
#build ([view Open Liberty Personal Build](https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?pipelineId=62bc9def-5b37-49bc-b908-ea77ac84abcb) - :x: completed with errors/failures.)

_Note: Target locations of links might be accessible only to IBM employees._

**Comment by Channyboy** [comment]
#build #libby ([view Open Liberty Delivery Requirements Verification](https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?pipelineId=01959a0a-62e9-442b-bb8e-446f04fc136a) - :white_check_mark: completed successfully!) ([view Open Liberty Personal Build](https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?pipelineId=d2243d4d-a12b-4b2d-89f0-e89a3f09c704) - :white_check_mark: completed successfully!)

_Note: Target locations of links might be accessible only to IBM employees._

_Note: Target locations of links might be accessible only to IBM employees._

**Review by pgunapal — APPROVED** [review]
LGTM

**Comment by Channyboy** [comment]
Part of #30383

**Pull request merged**
