### PR TITLE
Make mpOpenAPI-3.1 bundles + tests require Java 11

### PR DESCRIPTION
**Pull request by Azquelt**
mpOpenAPI-3.1 already won't start with Java <11 due to a transitive dependency on eeCompatible-10.0, but we need to mark the bundles and tests as well.

For #22284

### CODE REVIEW

**Comment by Azquelt** [comment]
#build

**Review by tevans78 — CHANGES_REQUESTED** [review]
Would like to see the eclipse java versions changed as well

**Comment by Azquelt** [comment]
I updated the execution environment on the project build path in eclipse and delivered the resulting changes to the .classpath and settings files.

I've also added the `Require-Capability` header to the API jar.

**Comment by Azquelt** [comment]
#libby
#build

**Review by jhanders34 — APPROVED** [review]

**Review by tevans78 — APPROVED** [review]

**Pull request merged**
