### PR TITLE
Switch MP7 to GA ... including MP Open API

### PR DESCRIPTION
**Pull request by tevans78**
- [x] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [x] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [x] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

This PR will replace https://github.com/OpenLiberty/open-liberty/pull/29825

### CODE REVIEW

**Comment by Azquelt** [comment]
~~Some of the commits currently on this PR are not directly related to removing the beta guards. They'll be delivered separately in #29990 and #29977 and removed from this PR.~~

Update: these changes have been delivered.

**Comment by Azquelt** [comment]
#build

**Comment by contbld** [comment]
Your personal pipeline request is at https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=9490dc0e-7e51-4951-b74d-1cea219401e2

Target locations of links might be accessible only to IBM employees.

**Comment by contbld** [comment]
<h3>Code analysis and actions</h3>
DO NOT DELETE THIS COMMENT.

- 3 FAT files were changed, added, or removed.
 - Check that the build did not break the affected FAT suite(s).

- 22 product code files were changed.

**Comment by contbld** [comment]
https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=9490dc0e-7e51-4951-b74d-1cea219401e2 has errors/failures.

**Review by Azquelt — APPROVED** [review]

**Pull request merged**
