### PR TITLE
MYFACES-4611

### LINKED ISSUE #25693: MYFACES-4611
**Describe the bug**  

If a ViewExpiredException is handled by a custom ExceptionHandler which performs some implicit navigation the following NullPointerException can occur:

> java.lang.NullPointerException
> at org.apache.myfaces.view.facelets.ViewPoolProcessor.isViewPoolEnabledForThisView(ViewPoolProcessor.java:236)
> at org.apache.myfaces.application.NavigationHandlerImpl.handleNavigation(NavigationHandlerImpl.java:324)
> at org.apache.myfaces.application.NavigationHandlerImpl.handleNavigation(NavigationHandlerImpl.java:117)
> at ....CustomExceptionHandler.handle(CustomExceptionHandler.java:45)

**Steps to Reproduce**  
Use a custom ExceptionHandler to handle ViewExpiredExceptions.

**Expected behavior**  
No NullPointerException is expected.

**Diagnostic information:**  
 - Affected feature(s): jsf-2.2, jsf-2.3, faces-3.0, faces-4.0

**Additional context**  
https://issues.apache.org/jira/browse/MYFACES-4611

### PR DESCRIPTION
**Pull request by pnicolucci**
fixes #25693

### CODE REVIEW

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Review by volosied — APPROVED** [review]
Looks good. This would also be verfied via a test in WS-CD-Open?

**Comment by pnicolucci** [comment]
#libby

**Pull request merged**
