### PR TITLE
Global Handler FAT tests and pass them in EE9

### PR DESCRIPTION
**Pull request by andymc12**
This is part of the EE9 effort, specifically covered by RESTful WS 3.0 epic issue #11803.

This PR ports the FAT tests from WS-CD-Open and upgrades them to run under EE7 and EE8.

Since global handlers are an SPI and require user features, this PR also adds new util methods to the ShrinkHelper class to facilitate the creation of user features in Open Liberty tests.

While testing there changes, I discovered a NPE in StaxUtils which is resolved by a small null check.

This PR also tests EE9 support with the new opt-in model for Jakarta RESTful WS 3.0.

### CODE REVIEW

**Review by WhiteCat22 — APPROVED** [review]

**Comment by andymc12** [comment]
#build

**Review by neuwerk — APPROVED** [review]
Change looks good!

**Comment by andymc12** [comment]
Updated to include Jakarta RESTful WS 3.0 opt-in support. Need new #build and new #libby check for corrected copyright headers.

**Comment by andymc12** [comment]
Tweaks to tested.feature and full vs core edition - new #build

**Comment by andymc12** [comment]
#build

**Review by jim-krueger — APPROVED** [review]
I don't see anything wrong here... but this is a very big change.

**Comment by andymc12** [comment]
> I don't see anything wrong here... but this is a very big change.

Fair enough.  If it regresses anything, we'll be sure to lower the temperature a few degrees when we burn you at the stake for allowing this in.  :-) just kidding!

I mean, it's only 20,000 new/changed lines - what could go wrong?! :-)

**Comment by andymc12** [comment]
#libby

Failures are in unrelated buckets, and are unrelated to these changes.

**Pull request merged**
