### PR TITLE
Update versionless features in packages to be right

### PR DESCRIPTION
**Pull request by jhanders34**
- Add appropriate features for the packages.  This includes adding in data to webproflie / platform 11, concurrent to webprofile 10 and 11, ejbHome and ejbPersistentTimer to platform packages.
- Remove concurrent from web profile 8 package
- Remove managedBeans from EE 11 packages
- Switch to validation for EE 11 packages instead of beanValidation
- Remove MP features from web profile 11 package since not in the platform 11 package.
- Remove versionless features for non required features for MP 4 package
- Order the versionless features to be in alphabetical order so they are easier to find and validate everything is the package.
- Add mpMetrics-5.1 to the MP 7 package.  This may be changed later to remove it and the mpMetrics versionless feature before we ship MP 7 if that is what is decided.

- [x] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [x] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [x] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

### CODE REVIEW

**Comment by jhanders34** [comment]
#build

**Review by cbridgha — DISMISSED** [review]
Looks good

**Comment by cbridgha** [comment]
#build

**Comment by jhanders34** [comment]
#build

**Review by cbridgha — APPROVED** [review]
Looks good

**Comment by cbridgha** [comment]
#libby

**Pull request merged**
