### PR TITLE
Overlay el j2sec property issue

### LINKED ISSUE #23543: Investigate Access Control Exception in EL-5.0
While working on enabling EE10 on FAT buckets, two AccessControlExceptions were discovered (thanks for discovering and notifying @jhanders34!). This is due to the tomcat changes [here](https://bz.apache.org/bugzilla/show_bug.cgi?id=66294). Need to start discussion with the tomcat community on adding a security check for the change [here](https://github.com/apache/tomcat/commit/28ea2b9b2e781d20e0651cb5e0b65bacd464150c#diff-b5962d24af20591547a4804838aa91c84b0151645b2121ac4f244a1b9c1213e8R46-R47) and start a discussion on the new property org.apache.el.GET_CLASSLOADER_USE_PRIVILEGED and how it affects the security manager check [here](https://github.com/apache/tomcat/commit/28ea2b9b2e781d20e0651cb5e0b65bacd464150c#diff-b5962d24af20591547a4804838aa91c84b0151645b2121ac4f244a1b9c1213e8R661)

Exception 1

> java.security.AccessControlException: Access denied ("java.util.PropertyPermission" "org.apache.el.GET_CLASSLOADER_USE_PRIVILEGED" "read")
>         at java.base/java.security.AccessController.throwACE(AccessController.java:176)
>         at java.base/java.security.AccessController.checkPermissionHelper(AccessController.java:238)
>         at java.base/java.security.AccessController.checkPermission(AccessController.java:385)
>         at java.base/java.lang.SecurityManager.checkPermission(SecurityManager.java:322)
>         at com.ibm.ws.kernel.launch.internal.MissingDoPrivDetectionSecurityManager.checkPermission(MissingDoPrivDetectionSecurityManager.java:45)
>         at java.base/java.lang.SecurityManager.checkPropertyAccess(SecurityManager.java:1066)
>         at java.base/java.lang.System.getProperty(System.java:581)
>         at java.base/java.lang.System.getProperty(System.java:564)
>         at java.base/java.lang.Boolean.getBoolean(Boolean.java:265)
>         at jakarta.el.Util.<clinit>(Util.java:47)
>         at jakarta.el.ExpressionFactory.newInstance(ExpressionFactory.java:92)
>         at jakarta.el.ExpressionFactory.newInstance(ExpressionFactory.java:79)
>         at org.apache.jasper.runtime.JspApplicationContextImpl.<clinit>(JspApplicationContextImpl.java:59)
>         at org.apache.jasper.runtime.JspFactoryImpl.getJspApplicationContext(JspFactoryImpl.java:265)
>         at com.ibm._jsp._login._jspInit(_login.java:66)
>         at com.ibm.ws.jsp.runtime.HttpJspBase.init(HttpJspBase.java:77)
>         at com.ibm.ws.webcontainer.servlet.ServletWrapper.init(ServletWrapper.java:299)

Exception 2

> java.security.AccessControlException: Access denied ("java.lang.RuntimePermission" "getClassLoader")
>         at java.base/java.security.AccessController.throwACE(AccessController.java:176)
>         at java.base/java.security.AccessController.checkPermissionHelper(AccessController.java:238)
>         at java.base/java.security.AccessController.checkPermission(AccessController.java:385)
>         at java.base/java.lang.SecurityManager.checkPermission(SecurityManager.java:322)
>         at com.ibm.ws.kernel.launch.internal.MissingDoPrivDetectionSecurityManager.checkPermission(MissingDoPrivDetectionSecurityManager.java:45)
>         at java.base/java.lang.Thread.getContextClassLoader(Thread.java:578)
>         at jakarta.el.Util.getContextClassLoader(Util.java:665)
>         at jakarta.el.ExpressionFactory.newInstance(ExpressionFactory.java:92)
>         at jakarta.el.ExpressionFactory.newInstance(ExpressionFactory.java:79)
>         at org.apache.jasper.runtime.JspApplicationContextImpl.<clinit>(JspApplicationContextImpl.java:59)
>         at org.apache.jasper.runtime.JspFactoryImpl.getJspApplicationContext(JspFactoryImpl.java:265)
>         at com.ibm._jsp._login._jspInit(_login.java:72)
>         at com.ibm.ws.jsp.runtime.HttpJspBase.init(HttpJspBase.java:77)
>         at com.ibm.ws.webcontainer.servlet.ServletWrapper.init(ServletWrapper.java:299)

### PR DESCRIPTION
**Pull request by isaacrivriv**
fixes #23543 

Functional changes needed were added in Tomcat commit [5817d48bde1ae36e05bb03ea6aacc28640603058](https://github.com/apache/tomcat/commit/5817d48bde1ae36e05bb03ea6aacc28640603058)

### CODE REVIEW

**Comment by isaacrivriv** [comment]
#build

**Comment by isaacrivriv** [comment]
J2Sec build https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_Njcc0HYxEe2ux-fzqy0jNQ

**Comment by isaacrivriv** [comment]
J2Sec enabled build with full fat WebContainer buckets https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_WI2qMHczEe2ux-fzqy0jNQ

**Comment by isaacrivriv** [comment]
J2Sec enabled build with full fat WebContainer buckets https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_pK8PQHpNEe2gZbZD5Lij6g

**Comment by isaacrivriv** [comment]
#build

**Comment by isaacrivriv** [comment]
Latest build results enabled Java 2 Security and ran WebContainer and other buckets like JPA with bean validation that also hit the error. The errors that occurred in the build are unrelated to the changes and the failing buckets passed.

**Review by pnicolucci — APPROVED** [review]

**Comment by isaacrivriv** [comment]
#libby

**Pull request merged**
