### PR TITLE
JSFHtmlUnittests ee10

### PR DESCRIPTION
**Pull request by pnicolucci**
for https://github.com/OpenLiberty/open-liberty/issues/22369

Also found https://issues.apache.org/jira/browse/MYFACES-4547 while enabling this test and I've pulled in the fix.

### CODE REVIEW

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
Java 17 build: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_qgxRtJi1Ee2YL83b0ePHDw

**Comment by pnicolucci** [comment]
Java 17 build was successful

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
#libby #build

**Review by isaacrivriv — APPROVED** [review]
Tests look okay and FacesELContext matches changes in upstream. Everything looks good to me, thanks!

**Pull request merged**
