### PR TITLE
Resubmit with further updates to feature checker

### PR DESCRIPTION
**Pull request by benjamin-confino**
Reverts OpenLiberty/open-liberty#25530

### CODE REVIEW

**Comment by benjamin-confino** [comment]
#build

**Review by Yas-Franco — APPROVED** [review]

**Comment by benjamin-confino** [comment]
#build

**Comment by benjamin-confino** [comment]
Looks like the previous build didn't have the WS-CD commit in it.

**Comment by benjamin-confino** [comment]
#build

**Pull request merged**
