### PR TITLE
Update TRAS3012W wording as per ID review

### PR DESCRIPTION
**Pull request by jennifer-c**
Addressing comment from https://github.com/OpenLiberty/open-liberty/pull/12598#pullrequestreview-432516325

#build

### CODE REVIEW

**Comment by andrea-pichler** [comment]
Completed the requested L2 message review

**Comment by jennifer-c** [comment]
#build

**Comment by jennifer-c** [comment]
Test failures are unrelated to message change and are a known problem with many other builds encountering the same errors.

**Comment by jennifer-c** [comment]
@helyarp Could you take a look at these changes, since you were the original reviewer? Thanks!

**Pull request merged**
