### PR TITLE
Fix several SOE failures in JPA FAT

### PR DESCRIPTION
**Pull request by dazey3**
1) SQL SERVER failures:
```
java.lang.NullPointerException
at com.ibm.ws.jpa.injection.jndi.JPA10Injection_JNDI.setUp(JPA10Injection_JNDI.java:154)
```
The issue here is in the DatabaseVendor implementation that is used for DDL generation. For SQL Server, `dbproduct_name = Microsoft SQL Server`. The default returns NULL and eventually fails with this exception.

2) Postgres failures:
Several FAT failures in Postgres because there are still uses of schema in the DDL. Some Drops or Delete DDLs fail and create various test failure (duplicate key exceptions, foreign key violation, missing object, ect)

3) DB2 failures:
```
CREATE TABLE db2inst1.OOBiCardEntA (id INTEGER NOT NULL, name VARCHAR(254), B_ID INTEGER, PRIMARY KEY (id), UNIQUE(B_ID))
com.ibm.db2.jcc.am.SqlSyntaxErrorException: DB2 SQL Error: SQLCODE=-542, SQLSTATE=42831, SQLERRMC=B_ID, DRIVER=4.25.13
```
It looks like `B_ID` should have `NOT NULL` for DB2. 

```
[1/8/21 20:02:21:879 UTC] 00000037 com.ibm.tx.jta.embeddable.impl.EmbeddableTimeoutManager      I WTRN0006W: Transaction 00000176E395EB73000000010E57A2B8B1081CBD3C04CD27667855E6DB2EF41DDB09301500000176E395EB73000000010E57A2B8B1081CBD3C04CD27667855E6DB2EF41DDB09301500000001 has timed out after 120 seconds.
...
[1/8/21 20:03:46:963 UTC] 00000028 SystemErr                                                    R java.lang.IllegalStateException: No Global Transaction exists to commit.
[1/8/21 20:03:46:966 UTC] 00000028 SystemErr                                                    R 	at com.ibm.tx.jta.embeddable.impl.EmbeddableUserTransactionImpl.rollback(EmbeddableUserTransactionImpl.java:131)
```
It appears that the DDL is taking too long to complete and the transaction is timing out. Then the transaction rolls back the DDL on transaction commit when no transaction is found. All subsequent tests then fail. 
The reason for this failure MIGHT be all the extra tracing that this particular FAT had added to the DDL methods. I'll remove that tracing, to match all the other FAT and to try to help improve the timing. 

Signed-off-by: Will Dazey <dazeydev.3@gmail.com>

### CODE REVIEW

**Comment by dazey3** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jpa_22_fat,com.ibm.ws.jpa_30_fat,com.ibm.ws.jpa_eclipselink_fat,com.ibm.ws.jpa_locking_fat,com.ibm.ws.jpa_ol_fat,com.ibm.ws.jpa_spec10_injection_fat,com.ibm.ws.jpa_spec10_part01_fat,com.ibm.ws.jpa_spec10_part02_fat,com.ibm.ws.jpa_spec10_query_fat,com.ibm.ws.jpa_spec20_fat,com.ibm.ws.jpa_spec21_fat,com.ibm.ws.jpa.container.ormdiagnostics_fat

**Review by jgrassel — APPROVED** [review]
LGTM

**Comment by dazey3** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jpa_22_fat,com.ibm.ws.jpa_30_fat,com.ibm.ws.jpa_eclipselink_fat,com.ibm.ws.jpa_locking_fat,com.ibm.ws.jpa_ol_fat,com.ibm.ws.jpa_spec10_injection_fat,com.ibm.ws.jpa_spec10_part01_fat,com.ibm.ws.jpa_spec10_part02_fat,com.ibm.ws.jpa_spec10_query_fat,com.ibm.ws.jpa_spec20_fat,com.ibm.ws.jpa_spec21_fat,com.ibm.ws.jpa.container.ormdiagnostics_fat

**Comment by dazey3** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jpa_22_fat,com.ibm.ws.jpa_30_fat,com.ibm.ws.jpa_eclipselink_fat,com.ibm.ws.jpa_locking_fat,com.ibm.ws.jpa_ol_fat,com.ibm.ws.jpa_spec10_injection_fat,com.ibm.ws.jpa_spec10_part01_fat,com.ibm.ws.jpa_spec10_part02_fat,com.ibm.ws.jpa_spec10_query_fat,com.ibm.ws.jpa_spec20_fat,com.ibm.ws.jpa_spec21_fat,com.ibm.ws.jpa.container.ormdiagnostics_fat

**Comment by dazey3** [comment]
#run-libby-bot

**Pull request merged**
