### PR TITLE
Port MYFACES-4494 to Fix TCK Spec1574IT in Faces 4.0

### LINKED ISSUE #23313: MYFACES-4494
https://issues.apache.org/jira/browse/MYFACES-4494

### PR DESCRIPTION
**Pull request by volosied**
fixes #23313

### CODE REVIEW

**Comment by volosied** [comment]
#build

**Comment by volosied** [comment]
This needs a bit more work -- test still fails.

**Comment by volosied** [comment]
#build

**Comment by volosied** [comment]
#build

**Review by pnicolucci — APPROVED** [review]

**Comment by volosied** [comment]
#libby

**Pull request merged**
