### PR TITLE
JAX-WS: Increase timeouts in config fat buckets.

### PR DESCRIPTION
**Pull request by neuwerk**
This PR does the following:

- Increases timeouts in almost all the tests in the bucket
- Fixes a repeat action test failure by using static application name in  `EnableSchemaValidationTest`
- Cleans up the bucket by remove unnecessary files in the `testWebServiceClient` application

- [x] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [ ] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [ ] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

### CODE REVIEW

**Comment by neuwerk** [comment]
#build

**Review by BerksanAtes — DISMISSED** [review]
Looks good to me!

**Comment by neuwerk** [comment]
#build

**Comment by contbld** [comment]
We could not perform your request. We allow builds for authorized users and trusted code only.

**Review by BerksanAtes — APPROVED** [review]
LGTM!

**Comment by neuwerk** [comment]
#libby

**Comment by contbld** [comment]
We could not perform your request. We allow builds for authorized users and trusted code only.

**Pull request merged**
