### PR TITLE
EJB Singleton Lifecycle Deadlock

### PR DESCRIPTION
**Pull request by olendvcook**
#17593

### CODE REVIEW

**Comment by olendvcook** [comment]
#build

**Review by tkburroughs — APPROVED** [review]

**Comment by olendvcook** [comment]
#build

**Comment by olendvcook** [comment]
#build

**Comment by olendvcook** [comment]
#build

**Review by tkburroughs — APPROVED** [review]

**Comment by olendvcook** [comment]
#build

**Comment by olendvcook** [comment]
#build

**Comment by olendvcook** [comment]
#build

**Comment by olendvcook** [comment]
#build

**Comment by olendvcook** [comment]
Last 2 builds are good enough to deliver

#run-libby-bot

**Pull request merged**
