### PR TITLE
Fix test failure in RTC 291270. It appears that even though Infinispa…

### PR DESCRIPTION
**Pull request by jvanhill**
…n said that the cache existed, when we tried to delete it Infinispan now says it does NOT exist and returns a 404 from the REST endpoint.

### CODE REVIEW

**Comment by jvanhill** [comment]
#build

**Comment by jvanhill** [comment]
The build was still pending when I did the latest push.

**Review by kristip17 — APPROVED** [review]

**Comment by jvanhill** [comment]
#build

**Comment by jvanhill** [comment]
#build

**Comment by jvanhill** [comment]
#libby

**Comment by jvanhill** [comment]
#build
#libby

**Pull request merged**
