### PR TITLE
Change io.openliberty.mpTelemetry-2.0.feature to beta

### LINKED ISSUE #28591: Release mpTelemetry-2.0 as beta

### PR DESCRIPTION
**Pull request by Yas-Franco**
Removes the noship flag for the mpTelemetry 2.0 feature and changes it to beta. 

Fixes #28591

### CODE REVIEW

**Comment by Yas-Franco** [comment]
#libby
#build
#spawn.fullfat.buckets=io.openliberty.microprofile.telemetry.1.0.internal_fat,io.openliberty.microprofile.telemetry.1.0.internal.container_fat,io.openliberty.microprofile.telemetry.1.0.internal_fat_tck,io.openliberty.microprofile.telemetry.1.1.internal_fat_tck

**Comment by Yas-Franco** [comment]
#build

**Review by benjamin-confino — DISMISSED** [review]

**Comment by Yas-Franco** [comment]
#libby

**Comment by Yas-Franco** [comment]
#libby

#build

**Review by benjamin-confino — APPROVED** [review]

**Comment by Yas-Franco** [comment]
The build failed because of a unrelated existing defect. Merging the code

**Pull request merged**
