### PR TITLE
Adding properties' files for OT-3.0

### PR DESCRIPTION
**Pull request by tonyreigns**
Adding properties files for the new feature mpOpenTracing-3.0 feature. They're a direct copy from mpOT-2.0 and are just being readded.

### CODE REVIEW

**Comment by tonyreigns** [comment]
#build

**Comment by ramkumar-k-9286** [comment]
It seems like there are no English messages to review in this issue.

Adding the `ID Review not needed` label. If this is not correct please let me know.

Regards,
Ramkumar

**Comment by skasund** [comment]
L2 message review not required

**Review by fmhwong — APPROVED** [review]
LGTM

**Comment by tonyreigns** [comment]
#run-libby-bot

**Pull request merged**
