### PR TITLE
Update feature file names to match their symbolicNames

### PR DESCRIPTION
**Pull request by jhanders34**
- During externals review it was noted that file name and symbolic name need to match for the externals review tool to work properly.  In reality the feature generator tool uses the symbolic name to create the mf file, but it can be confusing that the mf file and feature file names match.
- This change either updates the the file names of the feature files to match the symbolicName

### CODE REVIEW

**Comment by jhanders34** [comment]
For those on review, I updated the symbolic name for most of them to match the file, but one I updated the file name to match the symbolic name since that is what made sense.  If you want me to switch it to change the symbolic name instead of file name or vice versa please let me know.

**Comment by jhanders34** [comment]
#build

**Comment by jhanders34** [comment]
#build
#libby

**Review by andymc12 — APPROVED** [review]
Reviewed MP GraphQL/Metrics auto feature and restfulWS/reactivestreams rename.  LGTM, thanks!

**Review by sebratton — APPROVED** [review]

**Comment by jhanders34** [comment]
#build
#libby

**Comment by jhanders34** [comment]
The feature checker makes sure that the private and auto features are also still around.  As such to avoid having to update things for the feature checker, I am just renaming the files to match the symbolic names.

**Comment by jhanders34** [comment]
#build

**Comment by jhanders34** [comment]
#libby

**Comment by jhanders34** [comment]
#libby

**Comment by jhanders34** [comment]
#libby

**Comment by jhanders34** [comment]
#libby

**Review by hutchig — COMMENTED** [review]
Don't see anything wrong about this!

**Pull request merged**
