### PR TITLE
Ported the configupdate test bucket to open liberty

### PR DESCRIPTION
**Pull request by KyleAure**
All tests passed locally, and open liberty successfully built locally.

### CODE REVIEW

**Comment by KyleAure** [comment]
#build

**Comment by KyleAure** [comment]
#build double check to make sure this build succeeds now that the bucket is removed from CL.

**Comment by wraschke** [comment]
This must be reverted due to hard build break https://wasrtc.hursley.ibm.com:9443/jazz/resource/itemName/com.ibm.team.workitem.WorkItem/264348 that's failing LAOS continuous builds regularly and preventing pushes to master.

**Comment by KyleAure** [comment]
Continuing work on this test bucket here: 7972

**Pull request merged**
