### PR TITLE
Handle defaultValues in default instance variables

### PR DESCRIPTION
**Pull request by brenthdaniel**
PR for #17830

### CODE REVIEW

**Comment by brenthdaniel** [comment]
#build

**Comment by brenthdaniel** [comment]
#build

**Comment by brenthdaniel** [comment]
Still getting unusual and seemingly unrelated build errors.. rebasing on the release branch and building again. 
#build

**Comment by brenthdaniel** [comment]
#build

**Comment by brenthdaniel** [comment]
#run-libby-bot

**Review by cbridgha — APPROVED** [review]
LGTM

**Pull request merged**
