### PR TITLE
upgrade netty libraries to 4.1.100

### PR DESCRIPTION
**Pull request by hutchig**
This pull request upgrades all the netty jars used by Liberty to 4.1.100.Final

### CODE REVIEW

**Comment by hutchig** [comment]
#build

**Comment by hutchig** [comment]
#build

**Comment by hutchig** [comment]
#build

**Comment by hutchig** [comment]
#build

**Review by pnicolucci — APPROVED** [review]

**Comment by hutchig** [comment]
[Not all] 4 grpc_fats were 100% successful - merging.
Correction - actually there was an error in one of the builds in grpc_fat relating to a  logged error for a closed stream - that is a known issue that is being looked at in the grpc_layer - including https://github.com/OpenLiberty/open-liberty/pull/26533

**Comment by hutchig** [comment]
#libbybot

**Pull request merged**
