### PR TITLE
removed dead code, fixed some test case errors

### PR DESCRIPTION
**Pull request by bensonlatibm**
Removed dead code in test case.
Added 2 second wait between running service commands.

### CODE REVIEW

**Comment by bensonlatibm** [comment]
#build

**Comment by bensonlatibm** [comment]
#run-libby-bot

**Comment by bensonlatibm** [comment]
Changes were tested via PB with build.os.native.packages set to true.

**Review by tiwarim — APPROVED** [review]
Changes look good!

**Pull request merged**
