### PR TITLE
Install tools update feature product match logic

### PR DESCRIPTION
**Pull request by jjiwooLim**
Fixes an error message when users try to install a feature that is available on all Liberty editions except Core to Core edition.

### CODE REVIEW

**Comment by jjiwooLim** [comment]
#build

**Comment by jjiwooLim** [comment]
#build

**Comment by jjiwooLim** [comment]
#build

**Comment by jjiwooLim** [comment]
Build successful

**Comment by jjiwooLim** [comment]
IM build
https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_lziQ0PtWEe6Ztu3nF7SgoA

**Comment by jjiwooLim** [comment]
#build

**Comment by jjiwooLim** [comment]
Lost the previous IM build. Kicked off another one: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_J2omAADFEe-LkpmtVFSl9A

**Comment by jjiwooLim** [comment]
IM build looks good, test failure not related to my changes

**Comment by jjiwooLim** [comment]
#libby-bot

**Comment by jjiwooLim** [comment]
#build

**Review by jacobwdv — APPROVED** [review]
LGTM

**Review by pnickoll — APPROVED** [review]

**Pull request merged**
