### PR TITLE
Issue #24916: Update ddlgen for future EntityManager builders

### PR DESCRIPTION
**Pull request by tkburroughs**
- Jakarta Data EMBuilders are created asynchonously, so may not exist if ddlgen invoked to soon
  - resolve by registering the futures with DDL MBean rather than the EMBuilders
- Jakarta Data does not determine if using persistence service until Builder created, so all futures must be registered, not just the ones that will participate
- Updated ddlgen MBean to skip DDLGenerationParticpants if they return null for file name
- Updated ddlgen MBean to handle exceptions that occur obtaining file name, as this is most likely when Jakarta Data would see an error
- Improved exception handling for Jakarta Data DDL gen; identified where errors should be logged

- [x] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [x] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [x] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

for #24916

### CODE REVIEW

**Comment by tkburroughs** [comment]
#build

**Review by njr-11 — DISMISSED** [review]
There is still some work to do with messages, but that will be done in subsequent PRs by other developers.

**Comment by tkburroughs** [comment]
#libby

**Comment by tkburroughs** [comment]
#build

**Comment by tkburroughs** [comment]
This PR is in an odd state due to merge conflicts; so delivered change with a different PR #29663

**Pull request closed without merging**
