### PR TITLE
Add `com.ibm.ws.jpa.tests.eclipselink.query_jpa_2.2_fat` FAT

### PR DESCRIPTION
**Pull request by dazey3**
When merging https://github.com/OpenLiberty/open-liberty/pull/22011, I forgot to add `com.ibm.ws.jpa.tests.eclipselink.query_jpa_2.2_fat`

Signed-off-by: Will Dazey <dazeydev.3@gmail.com>

### CODE REVIEW

**Comment by dazey3** [comment]
#build

**Comment by dazey3** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jpa.tests.eclipselink.query_jpa_2.2_fat

**Comment by dazey3** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jpa.tests.eclipselink.query_jpa_2.2_fat

**Comment by dazey3** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jpa.tests.eclipselink.query_jpa_2.1_fat,com.ibm.ws.jpa.tests.eclipselink.query_jpa_2.2_fat,com.ibm.ws.jpa.tests.eclipselink.query_jpa_3.1_fat

**Comment by dazey3** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jpa.tests.eclipselink.query_jpa_2.1_fat,com.ibm.ws.jpa.tests.eclipselink.query_jpa_2.2_fat,com.ibm.ws.jpa.tests.eclipselink.query_jpa_3.1_fat

**Review by jgrassel — APPROVED** [review]

**Review by tkburroughs — APPROVED** [review]

**Comment by tkburroughs** [comment]
#libby

**Pull request merged**
