### PR TITLE
empty list of entities redelivery

### LINKED ISSUE #30215: Re-introduce change reverted from 30145
Re-introduce change reverted from https://github.com/OpenLiberty/open-liberty/pull/30145

### PR DESCRIPTION
**Pull request by njr-11**
fixes #30215

This is a redelivery of #30145 which had to be [reverted](https://github.com/OpenLiberty/open-liberty/pull/30213) because code used the wrong message id in one place, causing a test failure, which went unnoticed because I mistook a different build result that said "completed successfully!" for the personal build, which had actually failed.

- [x] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [x] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [x] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

### CODE REVIEW

**Comment by njr-11** [comment]
#build

**Comment by contbld** [comment]
Your personal pipeline request is at https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=8b75f108-bc61-4fdc-880f-51f306fc3b31

Target locations of links might be accessible only to IBM employees.

**Comment by njr-11** [comment]
Note to the ID team: There is no need to review this PR because you already did so under #30145 which this redelivers without changing the NLS messages.

**Comment by contbld** [comment]
<h3>Code analysis and actions</h3>
DO NOT DELETE THIS COMMENT.

- 4 FAT files were changed, added, or removed.
 - Check that the build did not break the affected FAT suite(s).

- 4 product code files were changed.

**Comment by contbld** [comment]
https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=8b75f108-bc61-4fdc-880f-51f306fc3b31 completed successfully!

**Comment by njr-11** [comment]
> https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=8b75f108-bc61-4fdc-880f-51f306fc3b31 completed successfully!

All tests are passing (including those in the io.openliberty.data.internal_fat_errorpaths bucket).

**Review by gjwatts — APPROVED** [review]

**Pull request merged**
