### PR TITLE
Issue #15197: Initial Jakarta EE9 transformation for Oauth and Saml

### LINKED ISSUE #15197: Initial Jakarta EE9 changes for Oauth and Saml

### PR DESCRIPTION
**Pull request by jvanhill**
fixes #15197

### CODE REVIEW

**Comment by jvanhill** [comment]
#libby

**Comment by jvanhill** [comment]
#libby
#build

**Comment by jvanhill** [comment]
@jhanders34 - Mind reviewing the feature files? They should be the same as I sent you earlier, only I made the updates you suggested and removed the changes to the wsSecuritySaml-1.1 feature file.

**Review by ayoho — APPROVED** [review]

**Comment by jvanhill** [comment]
#build
#libby

**Comment by jvanhill** [comment]
#build

**Comment by jvanhill** [comment]
Hitting some build connection issues. Respinning.

#build

**Comment by jvanhill** [comment]
Artifactory was saving the Shibboleth IDP WAR artifact as a JAR instead of a WAR. Respinning.

#build

**Comment by jvanhill** [comment]
Updated POM for same dependency to have WAR packaging.

#build

**Comment by jvanhill** [comment]
#libby

**Comment by jvanhill** [comment]
Respinning as we were missing httpunit:1.6.2 in artifactory.

#build

**Comment by jvanhill** [comment]
#libby

**Comment by jvanhill** [comment]
#build
#libby

**Pull request merged**
