### PR TITLE
Test tracing between opentracing and mpTelemetry

### LINKED ISSUE #24139: Test mpTelemetry with mpOpenTracing and Jaeger
We should be able to have one server running `mpOpenTracing` and another running `mpTelemetry`, tracing to the same server and having trace IDs propagate between them.

We have guides for running `mpOpenTracing` with both [Jaeger][jaeger-guide] and [Zipkin][zipkin-guide] and we should be able to test both of those scenarios.

We also already have tests which set up and use Zipkin and Jaeger trace servers.

[jaeger-guide]: https://openliberty.io/guides/microprofile-opentracing-jaeger.html
[zipkin-guide]: https://openliberty.io/guides/microprofile-opentracing.html

### PR DESCRIPTION
**Pull request by Azquelt**
Test tracing calls between a server using mpTelemetry and a server using mpOpenTracing.

Fixes #24139

### CODE REVIEW

**Comment by Azquelt** [comment]
#build

**Review by Yas-Franco — DISMISSED** [review]
Looks good!

**Comment by Azquelt** [comment]
The new tests passed locally but failed in the build, need to investigate why.

**Comment by Azquelt** [comment]
The OpenTracing server is failing with `java.lang.ClassNotFoundException: okhttp3.Interceptor`

I suspect this is due to maven artifacts in the internal artifactory not having the full dependency metadata. We will need to work out the full list of dependencies required and list them explicitly in the build.gradle.

**Comment by Azquelt** [comment]
Added the missing libraries for the jaeger library.

#build
#libby

**Review by Yas-Franco — APPROVED** [review]
Looks good

**Pull request merged**
