### PR TITLE
Avoid isDirectory check when we know it is a parent File

### PR DESCRIPTION
**Pull request by jhanders34**
- Avoid isDirectory checks when we got the File from a File.getParentFile() call.

### CODE REVIEW

**Comment by jhanders34** [comment]
#build

**Comment by jhanders34** [comment]
Tom and Gary I have simplified this PR to remove the caching function to just focus on the reducing calls to isDirectory.

**Comment by jhanders34** [comment]
#libby #build

**Comment by jhanders34** [comment]
#libby #build

**Comment by jhanders34** [comment]
#libby #build

**Review by tbitonti — APPROVED** [review]

**Comment by jhanders34** [comment]
#libby #build

**Comment by jhanders34** [comment]
#libby #build

**Pull request merged**
