### PR TITLE
Initial FAT test project for XML-WS

### PR DESCRIPTION
**Pull request by tjwatson**

### CODE REVIEW

**Comment by tjwatson** [comment]
#build

**Comment by tjwatson** [comment]
Part of #26381

**Review by anjumfatima90 — DISMISSED** [review]

**Comment by tjwatson** [comment]
#build

**Comment by wraschke** [comment]
#build

**Comment by tjwatson** [comment]
#libby

**Review by anjumfatima90 — APPROVED** [review]

**Pull request merged**
