### PR TITLE
H2: ensure that http connection count gets decremented once

### PR DESCRIPTION
**Pull request by billw1024**

### CODE REVIEW

**Comment by billw1024** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.transport.http2_fat

**Comment by billw1024** [comment]
fixes #14825

**Comment by billw1024** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.transport.http2_fat

**Comment by loriadi** [comment]
Since some of the tests of other components failed with quiesce error, I'll hold off on my review.

**Comment by billw1024** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.transport.http2_fat

**Comment by billw1024** [comment]
70000+ tests passed with just one failure that was unrelated to this change.

**Comment by billw1024** [comment]
#run-libby-bot

**Review by loriadi — APPROVED** [review]
Looks good!

**Pull request merged**
