### PR TITLE
change mpjwt TAI to call util directly

### PR DESCRIPTION
**Pull request by chunlongliang-ibm**
#build 
#spawn.fullfat.buckets=com.ibm.ws.security.mp.jwt_fat_tck,com.ibm.ws.security.mp.jwt,com.ibm.ws.security.jwt_fat.mpjwt,com.ibm.ws.security.mp.jwt.propagation,com.ibm.ws.security.mp.jwt.proxy

### CODE REVIEW

**Comment by chunlongliang-ibm** [comment]
#build  #spawn.fullfat.buckets=com.ibm.ws.security.mp.jwt_fat_tck,com.ibm.ws.security.mp.jwt,com.ibm.ws.security.jwt_fat.mpjwt,com.ibm.ws.security.mp.jwt.propagation,com.ibm.ws.security.mp.jwt.proxy

**Comment by chunlongliang-ibm** [comment]
#build 
#spawn.fullfat.buckets=com.ibm.ws.security.jwtsso_fat,com.ibm.ws.security.jwt_fat.mpjwt,com.ibm.ws.security.mp.jwt_fat_tck

**Comment by chunlongliang-ibm** [comment]
#build 
#spawn.fullfat.buckets=com.ibm.ws.security.jwtsso_fat,com.ibm.ws.security.jwt_fat.mpjwt,com.ibm.ws.security.mp.jwt_fat_tck

**Comment by ayoho** [comment]
Is this pull request still needed?

**Comment by ayoho** [comment]
@chunlongliang-ibm Is this pull request needed?

**Comment by chunlongliang-ibm** [comment]
PR is not required

**Pull request closed without merging**
