### PR TITLE
Tck results certification

### PR DESCRIPTION
**Pull request by Yas-Franco**
https://github.com/OpenLiberty/open-liberty/issues/19795

Changed the hardcoded template wording which is specific to MicroProfile. That part is now configurable so that it can be used by things other than MicroProfile.

### CODE REVIEW

**Comment by Yas-Franco** [comment]
#build

**Comment by yasmin-aumeeruddy** [comment]
#build

**Comment by yasmin-aumeeruddy** [comment]
#build

**Comment by Yas-Franco** [comment]
#build

**Pull request closed without merging**
