### PR TITLE
fix 19832 discovery jvmprops

### PR DESCRIPTION
**Pull request by meiaus**
To resolve 19832:

- com.ibm.ws.security.oidc.client_fat.1/fat/src/com/ibm/ws/security/openidconnect/client/fat/CommonTests/GenericOidcClientTests.java
- com.ibm.ws.security.oidc.client_fat.1/fat/src/com/ibm/ws/security/openidconnect/client/fat/IBM/OidcClientDiscoveryErrorTests.java
- com.ibm.ws.security.oidc.client_fat.1/publish/servers/com.ibm.ws.security.openidconnect.client-1.0_fat.rpd/configs/rp_server_orig.xml
- com.ibm.ws.security.openidconnect.client/src/com/ibm/ws/security/openidconnect/client/internal/OidcClientConfigImpl.java
- com.ibm.ws.security.oidc.client_fat.1/publish/files/serversettings/oidcClientDiscoveryJvmProxyProps.xml
- com.ibm.ws.security.oidc.client_fat.1/publish/servers/com.ibm.ws.security.openidconnect.client-1.0_fat.rpd/jvm.options

Please note due to new method added in `OidcClientDiscoveryErrorTests.java` requiring `@AllowedFFDC({ "org.apache.http.conn.HttpHostConnectException" })`, which also caused other non-related test methods with same requirement within same class and other class (such as GenericOidcClientTests.java).

### CODE REVIEW

**Comment by meiaus** [comment]
#run-libby-bot

**Comment by meiaus** [comment]
#build

**Comment by meiaus** [comment]
#run-libby-bot

**Comment by meiaus** [comment]
#run-libby-bot

**Review by c00crane — APPROVED** [review]
FAT changes look good

**Review by teddyjtorres — APPROVED** [review]

**Review by ayoho — APPROVED** [review]

**Comment by meiaus** [comment]
The work is moved to new PR https://github.com/OpenLiberty/open-liberty/pull/21270/

**Pull request closed without merging**
