### PR TITLE
Add peerRecoveryPrecedence to get correct behavior for test

### PR DESCRIPTION
**Pull request by tjwatson**
This is to adjust for the changes in PR #26843

### CODE REVIEW

**Comment by tjwatson** [comment]
#build

**Comment by tjwatson** [comment]
InstsantOn build running the FAT https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_Fq3QwLR0Ee6cj5m6UcXbGA

**Review by neilgsyoung — APPROVED** [review]
Looks good

**Review by neilgsyoung — CHANGES_REQUESTED** [review]
Thanks Tom - though I see that only the test that has been run is the "testThatWillAlwaysPass"

**Comment by tjwatson** [comment]
> Thanks Tom - though I see that only the test that has been run is the "testThatWillAlwaysPass"

That is because the normal `#build` does not run the test on an InstantOn enabled machine.  See https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_Fq3QwLR0Ee6cj5m6UcXbGA for the run against our InstantOn queue which did run the full transaction FAT and the test passed there now.

**Review by neilgsyoung — APPROVED** [review]
Thanks - InstantOn build looks good.

**Review by dazavala — COMMENTED** [review]
Missed your review request, but did review the change.

**Pull request merged**
