### PR TITLE
Move opentracing mock tracker to FAT project; attempt #2

### PR DESCRIPTION
**Pull request by kgibm**
Trying to fix https://github.com/OpenLiberty/open-liberty/pull/521 while Steve's out

### CODE REVIEW

**Comment by kgibm** [comment]
#build

**Comment by sishida** [comment]
Greetings! ID writer here! If this issue requires ID review, could you please add the "ID Required" label? If it does not need ID review, could you please add the "ID review not needed" label? Thanks a bunch!

**Comment by kgibm** [comment]
@sishida The only ID-related change is that an NLS file was removed, so I'll add "ID review not needed."

**Comment by kgibm** [comment]
#build

**Comment by kgibm** [comment]
#build

**Comment by kgibm** [comment]
#build

**Comment by kgibm** [comment]
#build

**Comment by kgibm** [comment]
#build

**Comment by kgibm** [comment]
#build

**Comment by kgibm** [comment]
#build

**Comment by kgibm** [comment]
Deleted lots of old failed builds. Rebasing on integration and trying a new build...

**Comment by kgibm** [comment]
#build

**Pull request merged**
