### PR TITLE
Update Expression Langague 5.0 to 10.1.1 release

### LINKED ISSUE #22739: Updates Expression Language 5.0 to latest stable version
API : https://repo1.maven.org/maven2/org/apache/tomcat/tomcat-el-api/10.1.1/
IMPL:  https://repo1.maven.org/maven2/org/apache/tomcat/tomcat-jasper-el/10.1.1/

### PR DESCRIPTION
**Pull request by pnicolucci**
fixes #22739

### CODE REVIEW

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
#libby #build

**Review by isaacrivriv — APPROVED** [review]
Looks good to me, thanks!

**Review by volosied — APPROVED** [review]

**Pull request merged**
