### PR TITLE
Disable filter processing for opentracing

### PR DESCRIPTION
**Pull request by Steve-Fontes**
Signed-off-by: Steve Fontes <steve.m.fontes@gmail.com>

### CODE REVIEW

**Comment by Steve-Fontes** [comment]
Disabled one feature that will not be delivered. Modified the FAT tests to stop testing that feature. All other FAT tests remain to make sure base features still work.

**Comment by Steve-Fontes** [comment]
#build

**Comment by lzdanski** [comment]
All files for ID review are to be removed. Adding "ID Reviewed label."

**Comment by Steve-Fontes** [comment]
PB failed due to what looks like a slow network issue in an unrelated test, where the code/feature to be merged would not even have been loaded.

**Pull request merged**
