### PR TITLE
Issue #12278: Update to final 2.0.0 WebSocket API JAR

### LINKED ISSUE #12278: Pull in latest WebSocket API JARs when available

### PR DESCRIPTION
**Pull request by pnicolucci**
fixes #12278

### CODE REVIEW

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Review by jhanders34 — APPROVED** [review]

**Review by cbridgha — APPROVED** [review]
LGTM

**Review by tevans78 — APPROVED** [review]

**Comment by pnicolucci** [comment]
#run-libby-bot

**Pull request merged**
