### PR TITLE
Fix the broken ClientBuilder.keyStore() and ClientBuilder.trustStore() methods in EE9, EE10 & EE11

### LINKED ISSUE #30194: RestfulWS ClientBuilder.keyStore() and ClientBuilder.trustStore() methods are ignored in EE9+
**Describe the bug**  
RESTful Web Services `ClientBuilder.keyStore()` and `ClientBuilder.trustStore()` methods are ignored in EE9+

**Steps to Reproduce**  
Create a RESTFul Web Service `Client` and programmatically pass a `TrustStore` to the `ClientBuilder` in order to set up a SSL connection. 
The SSL connection will fail because the `ClientBuilder` method is ignored by our SSL integration layer.

**Expected behavior**  
A SSL connection should be created using the supplied KeyStore/TrustStore.

**Diagnostic information:**  
 - OpenLiberty Version: 21.0.0.12 - 24.0.0.12
 - Affected feature(s) `restfulws-3.0`, `restfulws-3.1`
 - Java Version: n/a
 - server.xml configuration (WITHOUT sensitive information like passwords): n/a
 - If it would be useful, upload the messages.log file found in `$WLP_OUTPUT_DIR/messages.log`

**Additional context**

### PR DESCRIPTION
**Pull request by WhiteCat22**
- [x] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [x] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [x] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

Fixes #30194
Fixes #PH64154

### CODE REVIEW

**Comment by WhiteCat22** [comment]
#libby #build #spawn.fullfat.buckets=com.ibm.ws.jaxrs.2.0.client_fat

**Comment by contbld** [comment]
Your personal pipeline request is at https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=efe505a6-24b8-405a-8aa9-d1b8bb5231c2

Target locations of links might be accessible only to IBM employees.

**Comment by contbld** [comment]
Your personal pipeline request is at https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=e0286f32-0ede-4cfa-8ed0-5c5bc36fde69

Target locations of links might be accessible only to IBM employees.

**Comment by contbld** [comment]
<h3>Code analysis and actions</h3>
DO NOT DELETE THIS COMMENT.

- 12 FAT files were changed, added, or removed.
 - Check that the build did not break the affected FAT suite(s).

- 7 infrastructure code files were changed.

- 8 product code files were changed.

**Comment by contbld** [comment]
<h3>Code analysis and actions</h3>
DO NOT DELETE THIS COMMENT.

- 12 FAT files were changed, added, or removed.
 - Check that the build did not break the affected FAT suite(s).

- 7 infrastructure code files were changed.

- 8 product code files were changed.

**Comment by contbld** [comment]
https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=e0286f32-0ede-4cfa-8ed0-5c5bc36fde69 has errors/failures.

**Comment by contbld** [comment]
https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=efe505a6-24b8-405a-8aa9-d1b8bb5231c2 has errors/failures.

**Comment by WhiteCat22** [comment]
#libby #build #spawn.fullfat.buckets=com.ibm.ws.jaxrs.2.0.client_fat

**Comment by contbld** [comment]
Your personal pipeline request is at https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=47d36e56-5450-4026-a5a9-528576dd43ab

Target locations of links might be accessible only to IBM employees.

**Comment by contbld** [comment]
Your personal pipeline request is at https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=4cc36ef1-d187-4be0-b5c7-e42e53913ded

Target locations of links might be accessible only to IBM employees.

**Comment by contbld** [comment]
<h3>Code analysis and actions</h3>
DO NOT DELETE THIS COMMENT.

- 12 FAT files were changed, added, or removed.
 - Check that the build did not break the affected FAT suite(s).

- 7 infrastructure code files were changed.

- 8 product code files were changed.

**Comment by contbld** [comment]
<h3>Code analysis and actions</h3>
DO NOT DELETE THIS COMMENT.

- 12 FAT files were changed, added, or removed.
 - Check that the build did not break the affected FAT suite(s).

- 7 infrastructure code files were changed.

- 8 product code files were changed.

**Comment by contbld** [comment]
https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=47d36e56-5450-4026-a5a9-528576dd43ab has errors/failures.

**Comment by contbld** [comment]
https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=4cc36ef1-d187-4be0-b5c7-e42e53913ded has errors/failures.

**Review by jim-krueger — APPROVED** [review]

**Pull request merged**
