### PR TITLE
Fix StackOverflowError in Resteasy code augmented with Liberty Trace

### LINKED ISSUE #29037: StackOverflowError when tracing restfulWs-3.1
**Describe the bug**  
Enabling trace for `org.jboss.resteasy` classes in Open Liberty running with the restfulWs-3.0 or restfulWs-3.1 features can trigger the following StackOverflowError:

> 

```
java.lang.StackOverflowError
> 	at com.ibm.ws.logging.internal.impl.BaseTraceFormatter.formatObj(BaseTraceFormatter.java:1072)
> 	at com.ibm.ws.logging.internal.impl.BaseTraceFormatter.formatMessage(BaseTraceFormatter.java:311)
> 	at com.ibm.ws.logging.internal.impl.BaseTraceFormatter.formatVerboseMessage(BaseTraceFormatter.java:381)
> 	at com.ibm.ws.logging.internal.impl.BaseTraceService.publishTraceLogRecord0(BaseTraceService.java:1241)
> 	at com.ibm.ws.logging.internal.impl.BaseTraceService.publishTraceLogRecord(BaseTraceService.java:1221)
> 	at com.ibm.ws.logging.internal.impl.BaseTraceService.entry(BaseTraceService.java:893)
> 	at com.ibm.websphere.ras.Tr.entry(Tr.java:610)
> 	at org.jboss.resteasy.plugins.delegates.LinkDelegate.toString(LinkDelegate.java:138)
> 	at org.jboss.resteasy.plugins.delegates.LinkDelegate.toString(LinkDelegate.java:18)
> 	at org.jboss.resteasy.specimpl.LinkImpl.toString(LinkImpl.java:98)
> 	at com.ibm.ws.logging.internal.impl.BaseTraceFormatter$3.run(BaseTraceFormatter.java:1151)
> 	at com.ibm.ws.logging.internal.impl.BaseTraceFormatter$3.run(BaseTraceFormatter.java:1148)
> 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:692)
> 	at com.ibm.ws.logging.internal.impl.BaseTraceFormatter.formatObject(BaseTraceFormatter.java:1148)
> 	at com.ibm.ws.logging.internal.impl.BaseTraceFormatter.formatObj(BaseTraceFormatter.java:1087)
> 	at com.ibm.ws.logging.internal.impl.BaseTraceFormatter.formatObj(BaseTraceFormatter.java:1072)
> 	at com.ibm.ws.logging.internal.impl.BaseTraceFormatter.formatMessage(BaseTraceFormatter.java:311)
> 	at com.ibm.ws.logging.internal.impl.BaseTraceFormatter.formatVerboseMessage(BaseTraceFormatter.java:381)
> 	at com.ibm.ws.logging.internal.impl.BaseTraceService.publishTraceLogRecord0(BaseTraceService.java:1241)
> 	at com.ibm.ws.logging.internal.impl.BaseTraceService.publishTraceLogRecord(BaseTraceService.java:1221)
> 	at com.ibm.ws.logging.internal.impl.BaseTraceService.entry(BaseTraceService.java:893)
> 	at com.ibm.websphere.ras.Tr.entry(Tr.java:610)
> 	at org.jboss.resteasy.plugins.delegates.LinkDelegate.toString(LinkDelegate.java:138)
> 	at org.jboss.resteasy.plugins.delegates.LinkDelegate.toString(LinkDelegate.java:18)
> 	at org.jboss.resteasy.specimpl.LinkImpl.toString(LinkImpl.java:98)
> 	at com.ibm.ws.logging.internal.impl.BaseTraceFormatter$3.run(BaseTraceFormatter.java:1151)
> 	at com.ibm.ws.logging.internal.impl.BaseTraceFormatter$3.run(BaseTraceFormatter.java:1148)
> 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:692)
> 	at com.ibm.ws.logging.internal.impl.BaseTraceFormatter.formatObject(BaseTraceFormatter.java:1148)
> 	at com.ibm.ws.logging.internal.impl.BaseTraceFormatter.formatObj(BaseTraceFormatter.java:1087)
> 	at com.ibm.ws.logging.internal.impl.BaseTraceFormatter.formatObj(BaseTraceFormatter.java:1072)
> 	at com.ibm.ws.logging.internal.impl.BaseTraceFormatter.formatMessage(BaseTraceFormatter.java:311)
> 	at com.ibm.ws.logging.internal.impl.BaseTraceFormatter.formatVerboseMessage(BaseTraceFormatter.java:381)
> 	at com.ibm.ws.logging.internal.impl.BaseTraceService.publishTraceLogRecord0(BaseTraceService.java:1241)
> 	at com.ibm.ws.logging.internal.impl.BaseTraceService.publishTraceLogRecord(BaseTraceService.java:1221)
> 	at com.ibm.ws.logging.internal.impl.BaseTraceService.entry(BaseTraceService.java:893)
```

and

```
java.lang.StackOverflowError

	at java.base/java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:228)

	at java.base/java.lang.ThreadLocal.get(ThreadLocal.java:194)

	at java.base/java.lang.ThreadLocal.get(ThreadLocal.java:172)

	at com.ibm.websphere.logging.hpel.LogRecordContext.getExtensions(LogRecordContext.java:297)

	at com.ibm.ws.logging.internal.WsLogRecord.createWsLogRecord(WsLogRecord.java:533)

	at com.ibm.ws.logging.internal.impl.BaseTraceService.entry(BaseTraceService.java:891)

	at com.ibm.websphere.ras.Tr.entry(Tr.java:610)

	at org.jboss.resteasy.plugins.delegates.CacheControlDelegate.toString(CacheControlDelegate.java:85)

	at org.jboss.resteasy.plugins.delegates.CacheControlDelegate.toString(CacheControlDelegate.java:15)

	at jakarta.ws.rs.core.CacheControl.toString(CacheControl.java:333)
```
This also includes a StackOverflowError originating from
```
 org/jboss/resteasy/plugins/delegates/NewCookieHeaderDelegate
```

**Steps to Reproduce**  
Run a RESTful Web Services application in Open Liberty that utilizes `org.jboss.resteasy.specimpl.LinkBuilderImpl` with trace enabled to trace `org.jboss.resteasy` classes.

**Expected behavior**  
No StackOverflowError should occur.

**Diagnostic information:**  
 - OpenLiberty Version: EE9 or EE10
 - Affected feature(s): restfulWs-3.0 and restfulWs-3.1

### PR DESCRIPTION
**Pull request by jim-krueger**
- [x] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [x] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [x] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

Fixes #29037

### CODE REVIEW

**Comment by jim-krueger** [comment]
#libby #build #spawn.fullfat.buckets=com.ibm.ws.jaxrs.2.0_fat,com.ibm.ws.jaxrs.2.0.cdi.1.2_fat,com.ibm.ws.jaxrs.2.0.client_fat,com.ibm.ws.jaxrs.2.1_fat,com.ibm.ws.jaxrs.2.1_fat_executor,com.ibm.ws.jaxrs.2.1_fat_extended,com.ibm.ws.jaxrs.2.1.cdi.2.0_fat,com.ibm.ws.jaxrs.2.1.client_fat,com.ibm.ws.jaxrs.2.1.sse_fat,com.ibm.ws.jaxrs.2.x_fat_clientProps,io.openliberty.restfulWS.3.0_fat,io.openliberty.restfulWS.3.0.cdi.3.0_fat,io.openliberty.restfulWS.3.0.client_fat,io.openliberty.restfulWS.3.1_fat

**Review by WhiteCat22 — DISMISSED** [review]

**Comment by jim-krueger** [comment]
#libby #build #spawn.fullfat.buckets=com.ibm.ws.jaxrs.2.0_fat,com.ibm.ws.jaxrs.2.0.cdi.1.2_fat,com.ibm.ws.jaxrs.2.0.client_fat,com.ibm.ws.jaxrs.2.1_fat,com.ibm.ws.jaxrs.2.1_fat_executor,com.ibm.ws.jaxrs.2.1_fat_extended,com.ibm.ws.jaxrs.2.1.cdi.2.0_fat,com.ibm.ws.jaxrs.2.1.client_fat,com.ibm.ws.jaxrs.2.1.sse_fat,com.ibm.ws.jaxrs.2.x_fat_clientProps,io.openliberty.restfulWS.3.0_fat,io.openliberty.restfulWS.3.0.cdi.3.0_fat,io.openliberty.restfulWS.3.0.client_fat,io.openliberty.restfulWS.3.1_fat

**Comment by jim-krueger** [comment]
#libby #build #spawn.fullfat.buckets=com.ibm.ws.jaxrs.2.0_fat,com.ibm.ws.jaxrs.2.0.cdi.1.2_fat,com.ibm.ws.jaxrs.2.0.client_fat,com.ibm.ws.jaxrs.2.1_fat,com.ibm.ws.jaxrs.2.1_fat_executor,com.ibm.ws.jaxrs.2.1_fat_extended,com.ibm.ws.jaxrs.2.1.cdi.2.0_fat,com.ibm.ws.jaxrs.2.1.client_fat,com.ibm.ws.jaxrs.2.1.sse_fat,com.ibm.ws.jaxrs.2.x_fat_clientProps,io.openliberty.restfulWS.3.0_fat,io.openliberty.restfulWS.3.0.cdi.3.0_fat,io.openliberty.restfulWS.3.0.client_fat,io.openliberty.restfulWS.3.1_fat

**Comment by jim-krueger** [comment]
#libby #build #spawn.fullfat.buckets=com.ibm.ws.jaxrs.2.0_fat,com.ibm.ws.jaxrs.2.0.cdi.1.2_fat,com.ibm.ws.jaxrs.2.0.client_fat,com.ibm.ws.jaxrs.2.1_fat,com.ibm.ws.jaxrs.2.1_fat_executor,com.ibm.ws.jaxrs.2.1_fat_extended,com.ibm.ws.jaxrs.2.1.cdi.2.0_fat,com.ibm.ws.jaxrs.2.1.client_fat,com.ibm.ws.jaxrs.2.1.sse_fat,com.ibm.ws.jaxrs.2.x_fat_clientProps,io.openliberty.restfulWS.3.0_fat,io.openliberty.restfulWS.3.0.cdi.3.0_fat,io.openliberty.restfulWS.3.0.client_fat,io.openliberty.restfulWS.3.1_fat

**Review by WhiteCat22 — APPROVED** [review]

**Pull request merged**
