### PR TITLE
Update SpringBootThinUtil for Spring Boot 3.1.x

### LINKED ISSUE #27242: Update SpringBootThinUtil for Spring Boot 3.1.x
Update the thin app utility to remove 3.1.x libraries from a spring boot app.

### PR DESCRIPTION
**Pull request by jimblye**
Fixes #27242

### CODE REVIEW

**Comment by jimblye** [comment]
#build

**Review by cbridgha — APPROVED** [review]
looks good

**Review by hlhoots — APPROVED** [review]
LGTM.

**Comment by jimblye** [comment]
#libby

**Pull request merged**
