### PR TITLE
JAX-WS: Ensure SOAPFaults are marshalled to the JAX-WS Specification

### PR DESCRIPTION
**Pull request by neuwerk**
This PR addresses #26636 by doing the the following: 

Adds the following classes from CXF 3.5.5: 
```
dev/com.ibm.ws.org.apache.cxf.cxf.rt.databinding.jaxb.3.2/src/org/apache/cxf/jaxb/JAXBEncoderDecoder.java
dev/com.ibm.ws.org.apache.cxf.cxf.rt.databinding.jaxb.3.2/src/org/apache/cxf/jaxb/Utils.java
```
Makes Liberty Specific changes to those classes to ensure that the `Throwable.getMessage()` is marshalled when a fault is thrown. CXF 3.5.5 does not conform to the JAX-WS specification, as it does not marshall the message element from Throwable. 

This PR also adds a new test suite `WebFaultTest` to the `com.ibm.ws.jaxws.2.2.webcontainer_fat_extended` bucket to test a handful of scenarios to make sure that the spec is being honored for `@WebFault` annotated exceptions.

### CODE REVIEW

**Comment by neuwerk** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.jaxrs.2.0_fat, com.ibm.ws.jaxws.X.wsat_fat, com.ibm.ws.jaxws.ejb_fat, com.ibm.ws.jaxws.2.2.webcontainer_fat, com.ibm.ws.jaxws.2.2.webcontainer_fat_extended, com.ibm.ws.jaxws.cdi_fat, com.ibm.ws.jaxws.clientcontainer_fat, com.ibm.ws.wsat_fat.db, com.ibm.ws.wsat.common_fat, com.ibm.ws.wssecurity_fat.wsscxf.1, com.ibm.ws.wssecurity_fat.wsscxf.1, com.ibm.ws.wssecurity_fat.wsscxf.2, com.ibm.ws.wssecurity_fat.wsscxf.3, com.ibm.ws.wssecurity_fat.wsscxf.saml.1, com.ibm.ws.wssecurity_fat.wsscxf.saml.2, com.ibm.ws.wssecurity_fat.wsscxf.saml.3, com.ibm.ws.wssecurity_fat.wsscxf.saml.5, com.ibm.ws.wssecurity_fat.wsscxf.saml.6

**Comment by neuwerk** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.jaxrs.2.0_fat, com.ibm.ws.jaxws.X.wsat_fat, com.ibm.ws.jaxws.ejb_fat, com.ibm.ws.jaxws.2.2.webcontainer_fat, com.ibm.ws.jaxws.2.2.webcontainer_fat_extended, com.ibm.ws.jaxws.cdi_fat, com.ibm.ws.jaxws.clientcontainer_fat, com.ibm.ws.wsat_fat.db, com.ibm.ws.wsat.common_fat, com.ibm.ws.wssecurity_fat.wsscxf.1, com.ibm.ws.wssecurity_fat.wsscxf.1, com.ibm.ws.wssecurity_fat.wsscxf.2, com.ibm.ws.wssecurity_fat.wsscxf.3, com.ibm.ws.wssecurity_fat.wsscxf.saml.1, com.ibm.ws.wssecurity_fat.wsscxf.saml.2, com.ibm.ws.wssecurity_fat.wsscxf.saml.3, com.ibm.ws.wssecurity_fat.wsscxf.saml.5, com.ibm.ws.wssecurity_fat.wsscxf.saml.6

**Review by BerksanAtes — APPROVED** [review]
Looks good to me!

**Comment by neuwerk** [comment]
#build

**Comment by neuwerk** [comment]
#libby

**Comment by neuwerk** [comment]
Failure is unrelated.

**Pull request merged**
