### PR TITLE
add saml slo support

### PR DESCRIPTION
**Pull request by brutif**

### CODE REVIEW

**Comment by brutif** [comment]
#build

**Comment by brutif** [comment]
#build

**Comment by brutif** [comment]
pb is good.  The rest of this change is in CL.

**Comment by ayoho** [comment]
FYI:  I re-spun the personal build since there was an issue running a subset of the FATs. The new build is https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_-WoXED2OEeiEV_f6YBuvGg

**Comment by brutif** [comment]
pb is good, merging

**Pull request merged**
