### PR TITLE
Add postgreSQL tests

### PR DESCRIPTION
**Pull request by jonhawkes**
#build

### CODE REVIEW

**Comment by jonhawkes** [comment]
#build 
#run-libby-bot

**Comment by jonhawkes** [comment]
#build

**Comment by jonhawkes** [comment]
#build

**Comment by jonhawkes** [comment]
#build 
#run-libby-bot

**Review by neilgsyoung — APPROVED** [review]
Looks good.

**Comment by jonhawkes** [comment]
fixes #13817

**Pull request merged**
