### PR TITLE
Add additional tests to VisibilityTest

### PR DESCRIPTION
**Pull request by jhanders34**
- Add test to make sure edition is set correctly in features.  ga and beta features should be core or base and noship features should be full
- Add test to make sure that features visibility matches the directory that they are in.

### CODE REVIEW

**Comment by jhanders34** [comment]
#build

**Comment by jhanders34** [comment]
#build

**Review by cbridgha — APPROVED** [review]
Thanks this is great looks good

**Comment by jhanders34** [comment]
#libby

**Pull request merged**
