### PR TITLE
Remove additional guard for MpOpenAPI custom endpoint.

### PR DESCRIPTION
**Pull request by abutch3r**
Remove additional guard for MicroProfile OpenAPI endpoint customization

Beta guard still in place

### CODE REVIEW

**Comment by abutch3r** [comment]
#build

**Comment by abutch3r** [comment]
#build

**Comment by Azquelt** [comment]
Previous build looks sick. #build

**Comment by tevans78** [comment]
#libby

**Comment by tevans78** [comment]
Libby did not respond. Merging anyway.

**Pull request merged**
