### PR TITLE
Update product and bundle version for release 23.0.0.1

### PR DESCRIPTION
**Pull request by wraschke**
#build

### CODE REVIEW

**Comment by wraschke** [comment]
#libby

**Comment by wraschke** [comment]
#build

**Comment by wraschke** [comment]
Build with UUID _CrnbwHbuEe2ux-fzqy0jNQ is red due to [FAT child build f2](https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_eWMooHc_Ee2ux-fzqy0jNQ&tab=com.ibm.team.build.web.ui.internal.editors.result.log.LogsProvider) having connection problems with wasrtc:

```
CRRTC3524W: Communication with the repository failed due to this error: CRJAZ1372E The following URL cannot be reached: /jazz/service/com.ibm.team.repository.common.internal.IRepositoryRemoteService. The connection timed out. The server returned this error: Connect to wasrtc.hursley.ibm.com:9443 [wasrtc.hursley.ibm.com/9.20.59.55] failed: Connection timed out.
```

This problem is not related at all to this PR's change. All tests and other activities are green so I'm merging.

**Review by crpotter — APPROVED** [review]

**Comment by wraschke** [comment]
#libby

**Pull request merged**
