### PR TITLE
test case with concurrency 3.0 resource definition annotions in an EJB

### PR DESCRIPTION
**Pull request by njr-11**
Add an EJB module to the Concurrency 3.0 tests for the new resource definition annotations.  Include a test for ContextServiceDefinition, but not yet for the other types, which will be tested under other pulls.

### CODE REVIEW

**Comment by njr-11** [comment]
#build

**Comment by njr-11** [comment]
#run-libby-bot
#build

**Review by jmstephensgit — APPROVED** [review]

**Comment by njr-11** [comment]
Build has lots of pre-existing FindBugs errors in unrelated components.  There is one additional error in `com.ibm.ws.health.analyzer.fat.FATSuite` which is a pre-existing issue in that test bucket.

**Comment by njr-11** [comment]
#run-libby-bot

**Pull request merged**
