### PR TITLE
Refresh resolved host when fragment cannot attach

### PR DESCRIPTION
**Pull request by tjwatson**

### CODE REVIEW

**Comment by tjwatson** [comment]
#build

**Comment by tjwatson** [comment]
#build

**Comment by tjwatson** [comment]
#build

**Comment by tjwatson** [comment]
#build

**Comment by tjwatson** [comment]
#libby
#build

**Comment by tjwatson** [comment]
#build

**Review by dazavala — APPROVED** [review]
Approved.  Took an extra look for potential NPE involving references for the refresh report and refresh list.  LGTM.  Felix SCR changes make sense.

**Comment by tjwatson** [comment]
#libby

**Pull request merged**
