### PR TITLE
Update cdi config properties

### LINKED ISSUE #20644: Update cdi emptyBeansXMLExplicitArchive config property name
The new cdi property is currently `emptyBeansXMLExplicitArchive` but we want it to be `emptyBeansXMLExplicitBeanArchive`. There are some NLS messages that will need updating as well.

### LINKED ISSUE #20647: Update enableImplicitBeanArchives config property description
Since we removed the default value for `enableImplicitBeanArchives` in both the `cdi` and `cdi12` config metatypes, we need to specify what the default value is ("true") in the property description.

### PR DESCRIPTION
**Pull request by tevans78**
This PR makes two changes to the CDI config
1. Change the name of the (noship) `emptyBeansXMLExplicitArchive` property to `emptyBeansXMLExplicitBeanArchive`
2. Update the config property descriptions to say what the default values are since they are no longer included in the metatype.

### CODE REVIEW

**Comment by tevans78** [comment]
#build

**Review by Emily-Jiang — APPROVED** [review]
LGTM

**Comment by skasund** [comment]
L2 message review completed

**Review by dmuelle — APPROVED** [review]
LGTM, thanks

**Pull request merged**
