### PR TITLE
Create the MP 6 convenience feature

### PR DESCRIPTION
**Pull request by tevans78**
The current contents of this feature are incomplete. More features will be added as they are ready ... and hopefully servlet-6.0 will be removed.

Part of
https://github.com/OpenLiberty/open-liberty/issues/21968

Tests will be added under
https://github.com/OpenLiberty/open-liberty/issues/22201

This PR is a pre-req of
https://github.com/OpenLiberty/open-liberty/issues/22122

### CODE REVIEW

**Comment by tevans78** [comment]
#build

**Comment by tevans78** [comment]
#build

**Comment by tevans78** [comment]
#build

**Comment by tevans78** [comment]
#build

**Comment by posmith** [comment]
L2 message review not required

**Review by Azquelt — APPROVED** [review]

**Comment by tevans78** [comment]
#libby

**Pull request merged**
