### PR TITLE
273841-remove-jsession-cookie-in-loginjsp-and-toolboxjsp: changes por…

### PR DESCRIPTION
**Pull request by sarinjacobsunny**
Defect 273841: (Fix in next release before next pen test in 2022) Liberty v20.0.0.3 pen test issue: 63105: Sensitive Data stored on HTML5 Local Storage (Medium)

https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.workitem.viewWorkItem&id=273841

### CODE REVIEW

**Comment by sarinjacobsunny** [comment]
Migrated code changes from a PR in WS-CD-Open to open-liberty
Old PR: https://github.ibm.com/websphere/WS-CD-Open/pull/19816

**Comment by sarinjacobsunny** [comment]
#build

**Review by k8vance88 — APPROVED** [review]

**Comment by k8vance88** [comment]
#build

**Comment by sarinjacobsunny** [comment]
I have created a new PR, hence this one can be removed.

Below is the url to new PR,
https://github.com/OpenLiberty/open-liberty/pull/19527

**Pull request closed without merging**
