### PR TITLE
Port  MYFACES-4681 to Faces 4.1

### PR DESCRIPTION
**Pull request by volosied**
- [x] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [x] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [x] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

################################################################################################

fixes part of #29624

The skipped tests relates to:
This relates to `https://github.com/jakartaee/faces/issues/1565` : `Faces 4.0: OutputScript/OutputStyleSheet Remove 'type' attribute if HTML5`

### CODE REVIEW

**Comment by volosied** [comment]
#build

**Comment by pnicolucci** [comment]
upstream PR `https://github.com/apache/myfaces/pull/750`

**Review by pnicolucci — DISMISSED** [review]

**Comment by volosied** [comment]
CTS Run: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_0ICwcHEDEe-0ZL4JeBVc2g

**Comment by volosied** [comment]
CTS was good 

image

**Comment by volosied** [comment]
#libby

**Comment by volosied** [comment]
two tests need to be changed / skipped: 
testOutputStylesheet_PreHtml5_EE11_FEATURES
testOutputScript_PreHtml5_EE11_FEATURES

**Comment by volosied** [comment]
#build

**Comment by volosied** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jsf_fat_lWAS_faces4.1,io.openliberty.org.apache.myfaces.4.0_fat,io.openliberty.org.apache.myfaces.4.1_fat,com.ibm.ws.jsf.2.2_fat,com.ibm.ws.jsf.2.2_fat.2,com.ibm.ws.jsf.2.3_fat

**Review by pnicolucci — DISMISSED** [review]

**Comment by volosied** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jsf_fat_lWAS_faces4.1,io.openliberty.org.apache.myfaces.4.0_fat,io.openliberty.org.apache.myfaces.4.1_fat,com.ibm.ws.jsf.2.2_fat,com.ibm.ws.jsf.2.2_fat.2,com.ibm.ws.jsf.2.3_fat

**Review by pnicolucci — APPROVED** [review]

**Comment by pnicolucci** [comment]
> https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=94a8cd06-5ddf-4136-ac73-fcaac9827ac5 has errors/failures.

@volosied  can you look at the JSF 2.3 websocket failure and see if that is related to this change ?

**Comment by volosied** [comment]
It seems like a network fluke as far as I can tell. 

The same test passes here: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_Hx78cH-PEe-TieZHY4j0Qw&tab=com.ibm.team.build.web.ui.internal.editors.result.test.TestProvider

**Comment by volosied** [comment]
#libby

**Review by pnicolucci — APPROVED** [review]

**Comment by volosied** [comment]
#libby

**Pull request merged**
