### PR TITLE
featureUtility proxy without auth 

### PR DESCRIPTION
**Pull request by jjiwooLim**
Issue: If the proxy is set up without basic auth, it doesn't connect to the proxy.

### CODE REVIEW

**Comment by jjiwooLim** [comment]
#build

**Comment by jjiwooLim** [comment]
com.ibm.ws.messaging.jms_fat failure is not related to this changes.

**Comment by jjiwooLim** [comment]
IM build: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_J4uJ8Ih5Ee2iX8vFQv1q7A

**Review by jacobwdv — APPROVED** [review]
Looks good to me

**Pull request merged**
