### PR TITLE
Deal with servlet 6 slash behaviour in FileHandler

### PR DESCRIPTION
**Pull request by idlewis**
Only for download and delete at the moment.

This is a further follow up on the issues raised by #23570

### CODE REVIEW

**Comment by idlewis** [comment]
#build

**Comment by idlewis** [comment]
another build:
https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_FnYOcDT9Ee6Sc76HvVsCaw

**Comment by wraschke** [comment]
#libby

**Review by yongja79 — DISMISSED** [review]
LGTM

**Comment by idlewis** [comment]
Rebuilding after squashing commits
#build

**Comment by idlewis** [comment]
#libby-bot

**Comment by idlewis** [comment]
fixes #25932

**Review by yongja79 — APPROVED** [review]

**Pull request merged**
