### PR TITLE
Update transformer dependency from 0.2.0 to .0.3.0.20211005.

### LINKED ISSUE #18900: JakartaEE: Transformer: Update dependency to version 0.3.0.20211005
Obtained from:
https://oss.sonatype.org/content/repositories/snapshots/org/eclipse/transformer/

https://oss.sonatype.org/content/repositories/snapshots/org/eclipse/transformer/org.eclipse.transformer.cli/0.3.0-SNAPSHOT/org.eclipse.transformer.cli-0.3.0-20211005.203813-23.jar
https://oss.sonatype.org/content/repositories/snapshots/org/eclipse/transformer/org.eclipse.transformer/0.3.0-SNAPSHOT/org.eclipse.transformer-0.3.0-20211005.203813-22.jar

### PR DESCRIPTION
**Pull request by tbitonti**

### CODE REVIEW

**Comment by tbitonti** [comment]
#build

**Review by cbridgha — APPROVED** [review]
LGTM

**Comment by tbitonti** [comment]
#build

**Comment by tbitonti** [comment]
#build

**Comment by jhanders34** [comment]
#build

**Comment by tbitonti** [comment]
Merged by #18945

**Pull request closed without merging**
