### PR TITLE
Test sessionDatabase-1.0 with InstantOn

### PR DESCRIPTION
**Pull request by tjwatson**

### CODE REVIEW

**Comment by tjwatson** [comment]
#build

**Comment by tjwatson** [comment]
#libby

**Comment by tjwatson** [comment]
#build

**Review by dazavala — DISMISSED** [review]
Hello.  The solution and FAT look great.  Some copyrights need updating.  And one question: Is it necessary to verify the session store db table does not initialize during checkpoint?  This is a specific case of a more general question, actually.

**Comment by tjwatson** [comment]
> Hello. The solution and FAT look great. Some copyrights need updating. And one question: Is it necessary to verify the session store db table does not initialize during checkpoint? This is a specific case of a more general question, actually.

I didn't change anything WRT to db table initialization.  My rational was that each and every server startup would go through the same path as this as far as DB access is concerned.  So here I am just make that so as well.  Only it is ensured to happen on the restore side.  But if you consider a containerized liberty application without InstantOn each time you launch such an application the same path in the code would be run each time you launch that container.  This change makes that also happen for InstantOn.

**Comment by tjwatson** [comment]
#build

**Comment by tjwatson** [comment]
#build

**Review by dazavala — APPROVED** [review]
Improvements to thread safety and field simplification in the session invalidator look good.

**Comment by tjwatson** [comment]
#libby

**Comment by tjwatson** [comment]
Fixes #23704

**Pull request merged**
