### PR TITLE
Fix JSP's getSpecificationVersion

### LINKED ISSUE #23146: JspFactory.getDefaultFactory().getEngineInfo().getSpecificationVersion() return incorrect version
**Describe the bug**  
If a Pages, formerly known as JSP,  application calls `JspFactory.getDefaultFactory().getEngineInfo().getSpecificationVersion()` then a wrong version is returned. The value is coded to return `2.1` rather than the correct specification version.  

**Steps to Reproduce**  
Call getSpecificationVersion() as described above.

**Expected behavior**  
The correct specification version should be returned. 
- jsp-2.2 - > 2.2
- jsp-2.3 - > 2.3
- pages-3.0 -> 3.0 
- and so forth

**Diagnostic information:**  
 - OpenLiberty Version: ALL
 - Affected feature(s) jsp-2.2, jsp-2.3, and pages-3.0
 - Java Version: N/A

**Additional context**

### PR DESCRIPTION
**Pull request by volosied**
fixes #23146

### CODE REVIEW

**Comment by volosied** [comment]
#build

**Comment by volosied** [comment]
#build

**Review by epj — APPROVED** [review]
approved

**Comment by volosied** [comment]
#build

**Comment by volosied** [comment]
#libby

**Pull request merged**
