### PR TITLE
refactor: convert JmsBodyType to enum

### PR DESCRIPTION
**Pull request by ngmr**
- [x] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [x] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [x] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

### CODE REVIEW

**Comment by ngmr** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.messaging.open_31_fat,com.ibm.ws.messaging.open_clientcontainer_fat,com.ibm.ws.messaging.open_comms_fat,com.ibm.ws.messaging.open_fat,com.ibm.ws.messaging.open_jms20AutoCloseable_fat,com.ibm.ws.messaging.open_jms20context_fat,com.ibm.ws.messaging.open_jms20contextSecurity2_fat,com.ibm.ws.messaging.open_jms20contextSecurity_fat,com.ibm.ws.messaging.open_jms20deliverydelay_fat,com.ibm.ws.messaging.open_jms20_fat,com.ibm.ws.messaging.open_jms20security_fat,com.ibm.ws.microprofile.reactive.messaging_fat,io.openliberty.microprofile.reactive.messaging.internal_fat

**Comment by contbld** [comment]
Your personal pipeline request is at https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=2c38e955-b43a-44bd-9ac8-b12c338ac181

Target locations of links might be accessible only to IBM employees.

**Comment by contbld** [comment]
https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=2c38e955-b43a-44bd-9ac8-b12c338ac181 has errors/failures.

**Comment by contbld** [comment]
<h3>Code analysis and actions</h3>
DO NOT DELETE THIS COMMENT.

- 2 product code files were changed.

**Comment by ngmr** [comment]
!build
spawn.fullfat.buckets=com.ibm.ws.messaging.open_31_fat,com.ibm.ws.messaging.open_clientcontainer_fat,com.ibm.ws.messaging.open_comms_fat,com.ibm.ws.messaging.open_fat,com.ibm.ws.messaging.open_jms20AutoCloseable_fat,com.ibm.ws.messaging.open_jms20context_fat,com.ibm.ws.messaging.open_jms20contextSecurity2_fat,com.ibm.ws.messaging.open_jms20contextSecurity_fat,com.ibm.ws.messaging.open_jms20deliverydelay_fat,com.ibm.ws.messaging.open_jms20_fat,com.ibm.ws.messaging.open_jms20security_fat,com.ibm.ws.microprofile.reactive.messaging_fat,io.openliberty.microprofile.reactive.messaging.internal_fat

**Comment by contbld** [comment]
Your personal pipeline request is at https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=a1bdcb0f-7b53-4d42-9447-b47d36bec7cd

Target locations of links might be accessible only to IBM employees.

**Comment by contbld** [comment]
Your personal pipeline request is at https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=3a31ce3c-cf47-42c7-bb01-07e2bad478fe

Target locations of links might be accessible only to IBM employees.

**Comment by contbld** [comment]
<h3>Code analysis and actions</h3>
DO NOT DELETE THIS COMMENT.

- 5 product code files were changed.

**Comment by contbld** [comment]
https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=3a31ce3c-cf47-42c7-bb01-07e2bad478fe has errors/failures.

**Comment by ngmr** [comment]
!build
spawn.fullfat.buckets=com.ibm.ws.messaging.open_31_fat,com.ibm.ws.messaging.open_clientcontainer_fat,com.ibm.ws.messaging.open_comms_fat,com.ibm.ws.messaging.open_fat,com.ibm.ws.messaging.open_jms20AutoCloseable_fat,com.ibm.ws.messaging.open_jms20context_fat,com.ibm.ws.messaging.open_jms20contextSecurity2_fat,com.ibm.ws.messaging.open_jms20contextSecurity_fat,com.ibm.ws.messaging.open_jms20deliverydelay_fat,com.ibm.ws.messaging.open_jms20_fat,com.ibm.ws.messaging.open_jms20security_fat,com.ibm.ws.microprofile.reactive.messaging_fat,io.openliberty.microprofile.reactive.messaging.internal_fat

**Comment by contbld** [comment]
Your personal pipeline request is at https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=9b748f56-3cbe-4c0a-bb07-b2e5f558d705

Target locations of links might be accessible only to IBM employees.

**Comment by contbld** [comment]
Your personal pipeline request is at https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=37980bae-90de-4b6b-9aea-43b01c47da80

Target locations of links might be accessible only to IBM employees.

**Comment by contbld** [comment]
<h3>Code analysis and actions</h3>
DO NOT DELETE THIS COMMENT.

- 5 product code files were changed.- **Please describe in a separate comment how you tested your changes.**
- 1 messages files were changed and need an L2 review.

- @OpenLiberty/message-reviewer Please review.
  - --nlsFiles

**Comment by contbld** [comment]
<h3>Code analysis and actions</h3>
DO NOT DELETE THIS COMMENT.

- 5 product code files were changed.- **Please describe in a separate comment how you tested your changes.**
- 1 messages files were changed and need an L2 review.

- @OpenLiberty/message-reviewer Please review.
  - --nlsFiles

**Comment by contbld** [comment]
https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=a1bdcb0f-7b53-4d42-9447-b47d36bec7cd has errors/failures.

**Comment by ngmr** [comment]
The removal of the static constant ints needs to be hook and eyed with other code, so leaving them in for now.

**Comment by ngmr** [comment]
!build
spawn.fullfat.buckets=com.ibm.ws.messaging.open_31_fat,com.ibm.ws.messaging.open_clientcontainer_fat,com.ibm.ws.messaging.open_comms_fat,com.ibm.ws.messaging.open_fat,com.ibm.ws.messaging.open_jms20AutoCloseable_fat,com.ibm.ws.messaging.open_jms20context_fat,com.ibm.ws.messaging.open_jms20contextSecurity2_fat,com.ibm.ws.messaging.open_jms20contextSecurity_fat,com.ibm.ws.messaging.open_jms20deliverydelay_fat,com.ibm.ws.messaging.open_jms20_fat,com.ibm.ws.messaging.open_jms20security_fat,com.ibm.ws.microprofile.reactive.messaging_fat,io.openliberty.microprofile.reactive.messaging.internal_fat

**Review by sakerl — APPROVED** [review]

**Pull request merged**
