### PR TITLE
Adding NoSQL DB Features

### PR DESCRIPTION
**Pull request by cbridgha**
Adding cloudant DB, couchDB and Mongo DB

### CODE REVIEW

**Comment by cbridgha** [comment]
@sishida Hi - Yes I'm moving some additional features to OL from Commercial Liberty - no new content to be reviewed.

**Comment by sishida** [comment]
Thanks for letting me know! I'm adding the "ID review not needed" label. :)

**Comment by cbridgha** [comment]
Please #build again with all features in place

**Comment by cbridgha** [comment]
Merging - failing tests all are known unrelated problems

**Pull request merged**
