### PR TITLE
22688: AccessLog should log header multiples

### LINKED ISSUE #22688: HTTP Access logging need to log multiple X-Forwarded-For headers
**Describe the bug**  
When HTTP Access Logging is enabled to log specific headers, if that header is repeatable in a single HTTP request, such as X-Fowarded-For headers, only the first header with that name is logged.

**Steps to Reproduce**  
Send a single HTTP request to WebSphere Liberty which contains multiple same named valid headers and have Liberty configured to log that header in the HTTP Access Log. 

**Expected behavior**  
HTTP Access Logging should log a comma separated list of the multiple values of that header.
If HTTP Access Logging is configured no changes need to be made the current configuration.  The output that gets logged will now show a comma separated list of values rather than a single value for repeatable headers.

**Diagnostic information:**  
 - OpenLiberty Version: All
 - Affected feature(s): All if HTTP Access Logging is configured
 - Java Version: n/a
 - server.xml configuration
      The configuration may have something similar to the following, with My-Request-Header as the repeatable header name which may appear multiple times in the same HTTP request.
      
     <httpAccessLogging logFormat=' "%{My-Request-Header}i" '/>

**Additional context**  
n/a

### PR DESCRIPTION
**Pull request by loriadi**
fixes #22688 
fixes #PH49305

### CODE REVIEW

**Comment by loriadi** [comment]
#build

**Comment by loriadi** [comment]
#libbybot

**Comment by loriadi** [comment]
Test failures are unrelated to this PR.

**Comment by loriadi** [comment]
#libbybot

**Comment by loriadi** [comment]
#build

**Comment by loriadi** [comment]
#build

**Comment by loriadi** [comment]
#libbybot

**Comment by loriadi** [comment]
Build failures unrelated to this change.

**Comment by loriadi** [comment]
A new FAT test was added to test that multiple same named headers on both the request and response are logged properly.

**Review by mrsaldana — APPROVED** [review]
Thanks for the work, lgtm!

**Pull request merged**
