### PR TITLE
JAXRSClientSSLTest ignore expected CWWKO0801E message in logs

### PR DESCRIPTION
**Pull request by WhiteCat22**
Servers log CWWKO0801E for expected error on the build machines but not locally

### CODE REVIEW

**Comment by WhiteCat22** [comment]
#build

**Comment by WhiteCat22** [comment]
#build

**Comment by WhiteCat22** [comment]
#build

**Comment by WhiteCat22** [comment]
#build

**Comment by wraschke** [comment]
#link 259130

**Pull request merged**
