### PR TITLE
Improve JPA spec20 FAT

### PR DESCRIPTION
**Pull request by dazey3**
Running `com.ibm.ws.jpa.tests.spec20_jpa_2.0_fat` and `com.ibm.ws.jpa.tests.spec20_jpa_2.1_fat` shows that these FAT projects are running against the `jpa-2.2` feature instead of their namesake features. 

It looks like the config swapping feature of these FAT was not fully implemented. In order to add implementation, I needed to create new DDL files and rename existing ones to include the provider name.

Additionally, I created a new `ValidateJPAFeatureTest` test that makes sure the intended feature is running with the correct JPA feature set.

Signed-off-by: Will Dazey <wadazey@us.ibm.com>

### CODE REVIEW

**Comment by dazey3** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jpa.tests.beanvalidation_jpa_2.0_fat,com.ibm.ws.jpa.tests.beanvalidation_jpa_2.1_fat,com.ibm.ws.jpa.tests.beanvalidation_jpa_2.2_fat,com.ibm.ws.jpa.tests.beanvalidation_jpa_3.0_fat,com.ibm.ws.jpa.tests.beanvalidation_jpa_3.1_fat,com.ibm.ws.jpa.tests.spec20_jpa_2.0_fat,com.ibm.ws.jpa.tests.spec20_jpa_2.1_fat,com.ibm.ws.jpa.tests.spec20_jpa_2.2_fat,com.ibm.ws.jpa.tests.spec20_jpa_3.0_fat,com.ibm.ws.jpa.tests.spec20_jpa_3.1_fat

**Comment by dazey3** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jpa.tests.beanvalidation_jpa_2.0_fat,com.ibm.ws.jpa.tests.beanvalidation_jpa_2.1_fat,com.ibm.ws.jpa.tests.beanvalidation_jpa_2.2_fat,com.ibm.ws.jpa.tests.beanvalidation_jpa_3.0_fat,com.ibm.ws.jpa.tests.beanvalidation_jpa_3.1_fat,com.ibm.ws.jpa.tests.spec20_jpa_2.0_fat,com.ibm.ws.jpa.tests.spec20_jpa_2.1_fat,com.ibm.ws.jpa.tests.spec20_jpa_2.2_fat,com.ibm.ws.jpa.tests.spec20_jpa_3.0_fat,com.ibm.ws.jpa.tests.spec20_jpa_3.1_fat

**Comment by dazey3** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jpa.tests.beanvalidation_jpa_2.0_fat,com.ibm.ws.jpa.tests.beanvalidation_jpa_2.1_fat,com.ibm.ws.jpa.tests.beanvalidation_jpa_2.2_fat,com.ibm.ws.jpa.tests.beanvalidation_jpa_3.0_fat,com.ibm.ws.jpa.tests.beanvalidation_jpa_3.1_fat,com.ibm.ws.jpa.tests.spec20_jpa_2.0_fat,com.ibm.ws.jpa.tests.spec20_jpa_2.1_fat,com.ibm.ws.jpa.tests.spec20_jpa_2.2_fat,com.ibm.ws.jpa.tests.spec20_jpa_3.0_fat,com.ibm.ws.jpa.tests.spec20_jpa_3.1_fat

**Comment by dazey3** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jpa.tests.beanvalidation_jpa_2.0_fat,com.ibm.ws.jpa.tests.beanvalidation_jpa_2.1_fat,com.ibm.ws.jpa.tests.beanvalidation_jpa_2.2_fat,com.ibm.ws.jpa.tests.beanvalidation_jpa_3.0_fat,com.ibm.ws.jpa.tests.beanvalidation_jpa_3.1_fat,com.ibm.ws.jpa.tests.spec20_jpa_2.0_fat,com.ibm.ws.jpa.tests.spec20_jpa_2.1_fat,com.ibm.ws.jpa.tests.spec20_jpa_2.2_fat,com.ibm.ws.jpa.tests.spec20_jpa_3.0_fat,com.ibm.ws.jpa.tests.spec20_jpa_3.1_fat

**Review by jgrassel — APPROVED** [review]
lgtm, good to have a check on the jpa feature used.  Thanks!

**Comment by dazey3** [comment]
#run-libby-bot

**Pull request merged**
