### PR TITLE
Update EE11 schema for web-jsptaglibrary

### PR DESCRIPTION
**Pull request by pmd1nh**
- [X] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [X] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [X] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

### CODE REVIEW

**Comment by pmd1nh** [comment]
fixes #30007

**Comment by pmd1nh** [comment]
Schema from `https://jakarta.ee/xml/ns/jakartaee/#11`

**Comment by pmd1nh** [comment]
#build

**Comment by pmd1nh** [comment]
#build

**Review by jimblye — APPROVED** [review]

**Pull request merged**
