### PR TITLE
Add mpTelemetry fat bucket

### PR DESCRIPTION
**Pull request by Yas-Franco**
For issue #19172

### CODE REVIEW

**Comment by Yas-Franco** [comment]
#build

**Comment by Yas-Franco** [comment]
#libby

**Comment by Yas-Franco** [comment]
Manually started personal build here: 

https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_vFDgkBSwEe2JSL2ccGwYRA

**Review by benjamin-confino — APPROVED** [review]

**Comment by Yas-Franco** [comment]
#libby

**Comment by Yas-Franco** [comment]
#build

**Pull request merged**
