### PR TITLE
Update cnf oss maven files

### PR DESCRIPTION
**Pull request by jhanders34**
- Remove duplicates from the oss_dependencies.maven file
- Remove artifacts that are pulled from maven instead of dhe and are
already in oss_dependencies.maven
- Remove OSS artifacts that should not have been added to open liberty in PR #8185

Each build has the following output when doing cnf:initialize when doing external contributor type build:

Download http://public.dhe.ibm.com/ibmdl/export/pub/software/olrepo/com/googlecode/json-simple/json-simple/1.1.1/json-simple-1.1.1.jar
Download http://public.dhe.ibm.com/ibmdl/export/pub/software/olrepo/commons-fileupload/commons-fileupload/1.3.3/commons-fileupload-1.3.3.jar
Download http://public.dhe.ibm.com/ibmdl/export/pub/software/olrepo/org/apache/felix/org.osgi.service.obr/1.0.2/org.osgi.service.obr-1.0.2.jar
Download http://public.dhe.ibm.com/ibmdl/export/pub/software/olrepo/org/apache/cxf/cxf-rt-ws-security/2.6.2-ibm-p20151002-2341/cxf-rt-ws-security-2.6.2-ibm-p20151002-2341.jar
Download http://public.dhe.ibm.com/ibmdl/export/pub/software/olrepo/net/sf/ehcache/ehcache-core/2.5.2/ehcache-core-2.5.2.jar

The second change fixes those messages coming since they are pulled from maven instead of dhe.

### CODE REVIEW

**Comment by jhanders34** [comment]
#build

**Comment by jhanders34** [comment]
#build

**Comment by jhanders34** [comment]
#build

**Comment by fritze2** [comment]
Thanks. Looks good.

**Pull request merged**
