### PR TITLE
Coordinate server shutdown and peer recovery

### LINKED ISSUE #16613: Synchronize server shutdown and Transaction Peer Recovery
If Transaction Peer Recovery coincides with server shutdown - ie the server determines that it should recover another server's transaction logs at the same moment that it is shutdown, then peer recovery can fail. Data will not be corrupted but FFDCs may be generated. For example,

[4/8/21 16:59:25:539 PDT] 00000035 com.ibm.ws.recoverylog.spi.RecoveryDirectorImpl              I CWRLS0011I: Performing recovery processing for a peer WebSphere server (cloud001).
[4/8/21 16:59:25:541 PDT] 00000035 com.ibm.tx.jta.impl.TxRecoveryAgentImpl                      A WTRN0108I: Recovery initiated for server cloud001
[4/8/21 16:59:25:726 PDT] 00000038 ibm.ws.recoverylog.custom.jdbc.impl.SQLMultiScopeRecoveryLog A CWRLS0008_RECOVERY_LOG_FAILED 
                                                                                                               2
                                                                                                               transaction
[4/8/21 16:59:25:730 PDT] 00000038 ibm.ws.recoverylog.custom.jdbc.impl.SQLMultiScopeRecoveryLog I CWRLS0009_RECOVERY_LOG_FAILED_DETAIL 
                                                                                                               com.ibm.ws.recoverylog.spi.InternalLogException
	at com.ibm.ws.recoverylog.custom.jdbc.impl.SQLMultiScopeRecoveryLog.closeLog(SQLMultiScopeRecoveryLog.java:1213)
	at com.ibm.tx.jta.impl.RecoveryManager.postShutdown(RecoveryManager.java:652)
	at com.ibm.tx.jta.impl.RecoveryManager.cleanupRemoteFailureScope(RecoveryManager.java:1650)
	at com.ibm.tx.jta.impl.FailureScopeController.shutdown(FailureScopeController.java:244)
	at com.ibm.tx.jta.impl.TxRecoveryAgentImpl.stop(TxRecoveryAgentImpl.java:620)

This cross-thread processing could be better coordinated.

### PR DESCRIPTION
**Pull request by neilgsyoung**
fixes #16613

### CODE REVIEW

**Comment by neilgsyoung** [comment]
#build

**Comment by neilgsyoung** [comment]
#run-libby-bot

**Comment by neilgsyoung** [comment]
#build

**Review by jonhawkes — APPROVED** [review]

**Comment by neilgsyoung** [comment]
#run-libby-bot

**Comment by neilgsyoung** [comment]
#build

**Pull request merged**
