### PR TITLE
Remove com.ibm.ws.runtime.update traces as it is no longer needed

### LINKED ISSUE #16688: Undo PR  #16687 -- Remove Tracing
Reminder to remove the runtime trace string from PR #16687 after the defect is resolved.

### PR DESCRIPTION
**Pull request by pnicolucci**
fixes #16688

### CODE REVIEW

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#libby #build

**Review by volosied — APPROVED** [review]
Better late than never!

**Pull request merged**
