### PR TITLE
Make mpHealth-4.0 tolerate MP 6 and EE 10

### PR DESCRIPTION
**Pull request by Azquelt**
mpHealth-4.0 will be part of both MP 5 and MP 6

For #21968

### CODE REVIEW

**Comment by Azquelt** [comment]
#build

**Comment by Azquelt** [comment]
Some tests failed because the right features weren't listed in `tested.features` in the bnd.bnd, should now be fixed.

#libby
#build

**Review by pgunapal — APPROVED** [review]
LGTM

**Comment by Azquelt** [comment]
Ready to merge once #22126 is in

**Pull request merged**
