### PR TITLE
Fixed ConncurrentModException when HEALTH trace is turned on

### LINKED ISSUE #14003: Test Failure: com.ibm.ws.microprofile.health20.fat.ApplicationStateHealthCheckTest.testPreLoadedApplicationsHealthCheckTest_mpHealth-3.0
RTC 277529

```
testPreLoadedApplicationsHealthCheckTest_mpHealth-3.0:junit.framework.AssertionFailedError: 2020-09-03-00:29:40:081 [Unexpected FFDC reporting java.util.ConcurrentModificationException was found (count = 1): /home/jazz_build/_PIPRIO1bEeq6BMGcHg9CTA-EBC.PROD.WASRTC-6BT-001-00-00/jbe/build/dev/image/output/wlp/usr/servers/ApplicationStateHealthCheck/logs/ffdc/ffdc_20.09.03_00.29.37.0.log
>------Start of DE processing------ = [9/3/20 0:29:37:685 UTC]
>Exception = java.util.ConcurrentModificationException
>Source = com.ibm.ws.container.service.state.internal.ApplicationStateManager
>probeid = 145
>Stack Dump = java.util.ConcurrentModificationException
>at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1493)
>at java.base/java.util.HashMap$EntryIterator.next(HashMap.java:1526)
>at java.base/java.util.HashMap$EntryIterator.next(HashMap.java:1524)
>at java.base/java.util.AbstractMap.toString(AbstractMap.java:551)
>at com.ibm.ws.microprofile.health.internal.AppTrackerImpl.applicationStopped(AppTrackerImpl.java:352)
>at com.ibm.ws.container.service.state.internal.ApplicationStateManager.fireStopped(ApplicationStateManager.java:144)
>at com.ibm.ws.container.service.state.internal.StateChangeServiceImpl.fireApplicationStopped(StateChangeServiceImpl.java:65)
>at com.ibm.ws.app.manager.module.internal.SimpleDeployedAppInfoBase.uninstallApp(SimpleDeployedAppInfoBase.java:676)
>at com.ibm.ws.app.manager.war.internal.WARApplicationHandlerImpl.uninstall(WARApplicationHandlerImpl.java:81)
>at com.ibm.ws.app.manager.internal.statemachine.StopAction.execute(StopAction.java:83)
>at com.ibm.ws.app.manager.internal.statemachine.ApplicationStateMachineImpl.enterState(ApplicationStateMachineImpl.java:1342)
>at com.ibm.ws.app.manager.internal.statemachine.ApplicationStateMachineImpl.performAction(ApplicationStateMachineImpl.java:1182)
>at com.ibm.ws.app.manager.internal.statemachine.ApplicationStateMachineImpl.run(ApplicationStateMachineImpl.java:905)
>at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker
```

### PR DESCRIPTION
**Pull request by pgunapal**
fixes #14003

### CODE REVIEW

**Comment by pgunapal** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.microprofile.health.2.0_fat,com.ibm.ws.microprofile.health.2.0_fat_tck,io.openliberty.microprofile.health.3.0.internal_fat_tck,io.openliberty.microprofile.health.3.0.internal_fat

**Review by fmhwong — COMMENTED** [review]
Do we need to move line 158 up to the try block?

**Comment by pgunapal** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.microprofile.health.2.0_fat,com.ibm.ws.microprofile.health.2.0_fat_tck,io.openliberty.microprofile.health.3.0.internal_fat_tck,io.openliberty.microprofile.health.3.0.internal_fat

**Comment by pgunapal** [comment]
@fmhwong Yes good catch! It would be safer to move it as well. I updated the PR with the changes.

**Review by fmhwong — APPROVED** [review]
LGTM

**Comment by pgunapal** [comment]
#libby

**Pull request merged**
