### PR TITLE
CNF in Spring Thin Utility

### PR DESCRIPTION
**Pull request by hlhoots**
#build

### CODE REVIEW

**Review by jimblye — APPROVED** [review]

**Comment by hlhoots** [comment]
Associated with #26357

**Comment by hlhoots** [comment]
Full FAT build: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_n8HjIF1DEe6Bm9_pzDpErg

**Comment by hlhoots** [comment]
Note to self, check both builds before merging...

**Review by cbridgha — APPROVED** [review]
Looks good

**Comment by hlhoots** [comment]
Builds looked good.  Had 1 known failure.  Merging.

**Comment by cbridgha** [comment]
Fixes #PH57263

**Pull request merged**
