### PR TITLE
upgrade protobuf to 3.23.4

### PR DESCRIPTION
**Pull request by hutchig**
As above. Should test jaeger_fat too.

### CODE REVIEW

**Comment by hutchig** [comment]
fixes #25748

**Comment by hutchig** [comment]
#build

**Comment by hutchig** [comment]
#build 
#spawn.fullfat.buckets=io.openliberty.microprofile.telemetry.1.0.internal.jaeger_fat

**Comment by hutchig** [comment]
#build

**Comment by hutchig** [comment]
#build

**Comment by hutchig** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.grpc_fat

**Comment by hutchig** [comment]
./gradlew com.ibm.ws.grpc_fat:buildAndRun  -Dfat.test.mode=Full also passes locally

**Review by isaacrivriv — APPROVED** [review]
Changes look good, thanks for updating!!

**Comment by BryanCutler** [comment]
Thank you @hutchig !

**Pull request merged**
