### PR TITLE
For defect in RTC 283686 make updates that were made in WS-CD-Open af…

### PR DESCRIPTION
**Pull request by jvanhill**
…ter I had moved com.ibm.ws.security.social_fat.LibertyOP to Open Liberty.

### CODE REVIEW

**Comment by jvanhill** [comment]
#build

**Comment by jvanhill** [comment]
#build

**Comment by jvanhill** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.security.social_fat.LibertyOP,com.ibm.ws.security.social_fat

**Comment by jvanhill** [comment]
#libby

**Review by ryanesch — APPROVED** [review]

**Pull request merged**
