### PR TITLE
12095: Add catch around HttpEndpointInfo initalization

### LINKED ISSUE #12095: PluginGenerator: BundleContext is no longer valid
Rare timing issue that occurs when a bundle is uninstalled, but plugin generator is still running.

```
Exception = java.lang.IllegalStateException
Source = com.ibm.ws.webcontainer.osgi.mbeans.PluginGenerator
probeid = generateXML
Stack Dump = java.lang.IllegalStateException: BundleContext is no longer valid
    at org.eclipse.osgi.internal.framework.BundleContextImpl.checkValid(BundleContextImpl.java:1055)
    at org.eclipse.osgi.internal.framework.BundleContextImpl.getAllServiceReferences(BundleContextImpl.java:598)
    at com.ibm.ws.webcontainer.osgi.mbeans.PluginGenerator$HttpEndpointInfo.getService(PluginGenerator.java:2357)
    at com.ibm.ws.webcontainer.osgi.mbeans.PluginGenerator$HttpEndpointInfo.<init>(PluginGenerator.java:2282)
    at com.ibm.ws.webcontainer.osgi.mbeans.PluginGenerator.generateXML(PluginGenerator.java:367)
    at com.ibm.ws.webcontainer.osgi.mbeans.GeneratePluginConfigMBean.generatePluginConfig(GeneratePluginConfigMBean.java:160)
```

### PR DESCRIPTION
**Pull request by volosied**
fixes #12095

View Change: https://github.com/OpenLiberty/open-liberty/pull/12514/files#diff-f549c95906c88490c5df8a2c0f75c76a84450e1de18d547c96ada035e695d0e2R366-R374

### CODE REVIEW

**Comment by volosied** [comment]
#build

**Comment by volosied** [comment]
#build

**Comment by volosied** [comment]
#build

**Comment by volosied** [comment]
#build

**Review by pnicolucci — APPROVED** [review]
Looks good

**Comment by volosied** [comment]
#run-libby-bot

**Pull request merged**
