### PR TITLE
Messaging singletons

### PR DESCRIPTION
**Pull request by joe-chacko**
This will take a while

### CODE REVIEW

**Comment by joe-chacko** [comment]
Additional testing in this separate build: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_EIYOAD2xEe23scQ7k9ObvQ

**Comment by joe-chacko** [comment]
#build

**Comment by joe-chacko** [comment]
#build

**Review by AndrewDJBanks — DISMISSED** [review]

**Comment by joe-chacko** [comment]
#build #run-libby-bot after making `CommsOutboundChain`s `ApplicationPrereq`s

**Comment by joe-chacko** [comment]
#libby-build

**Comment by joe-chacko** [comment]
#build

**Comment by joe-chacko** [comment]
#build

**Comment by joe-chacko** [comment]
#build

**Comment by joe-chacko** [comment]
#build

**Comment by joe-chacko** [comment]
#build

**Comment by joe-chacko** [comment]
#libby-build

**Review by AndrewDJBanks — APPROVED** [review]

**Pull request merged**
