### PR TITLE
28881 copy features ga

### PR DESCRIPTION
**Pull request by tbitonti**
FAT test corrections, merged with GA / beta update, plus FAT beta update.

### CODE REVIEW

**Comment by tbitonti** [comment]
#build

**Comment by tbitonti** [comment]
#build

**Comment by wraschke** [comment]
#libby

**Review by rsherget — DISMISSED** [review]
LGTM

**Comment by tbitonti** [comment]
#build

**Review by rsherget — DISMISSED** [review]
LGTM

**Comment by tbitonti** [comment]
#build

**Review by cbridgha — DISMISSED** [review]
Looks good

**Comment by tbitonti** [comment]
#build

**Comment by tbitonti** [comment]
Successful build with the WL beta-flip pull request:
https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_ZQYl4EhQEe-Hn-AxXEWsJg&tab=com.ibm.team.build.web.ui.internal.editors.result.test.TestProvider

**Review by cbridgha — APPROVED** [review]
Looks good

**Pull request merged**
