### PR TITLE
Add the LDAP IdentityStore

### PR DESCRIPTION
**Pull request by ryanesch**

### CODE REVIEW

**Comment by sishida** [comment]
Hello! ID writer here! Does this message require ID review? If so, please add the "ID Required" label. If it does not need ID review, please add the "ID review not needed" label. Thank you!

**Comment by ryanesch** [comment]
#build

**Comment by ryanesch** [comment]
#build

**Comment by toshiyamamoto** [comment]
There is a build error. 
:com.ibm.ws.security.javaeesec.cdi:compileTestJava/home/jazz_build/_1MiFQLZmEeet8On9YyOAhA-EBC.PROD.WASRTC-7BN-000-00-00/jbe/build/open-liberty/dev/com.ibm.ws.security.javaeesec.cdi/test/com/ibm/ws/security/javaeesec/cdi/extensions/TestIdentityStoreBean.java:31: error: cannot find symbol
import com.ibm.ws.security.javaeesec.identitystore.DummyLdapIdentityStore;
                                                  ^
  symbol:   class DummyLdapIdentityStore
  location: package com.ibm.ws.security.javaeesec.identitystore
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error
 FAILED

**Comment by ryanesch** [comment]
Fixed the missing import.

**Comment by ryanesch** [comment]
#build

**Comment by ryanesch** [comment]
#build

**Comment by ryanesch** [comment]
#build

**Comment by ryanesch** [comment]
#build

**Pull request merged**
