### PR TITLE
Update Faces Projects to use Version  3.0.0

### LINKED ISSUE #13889: Remove Version Variable From MyFaces 3.0 Impl bnd.bnd
dev/io.openliberty.org.apache.myfaces.3.0/bnd.bnd 

Implementation-Version: 3.0.0
Impl-Jar-Version: 3.0.0.RC1

Once MyFaces 3.0.0 is officially released, we can remove Impl-Jar-Version.

### LINKED ISSUE #15747: Update to MyFaces Core 3.0
Once the community creates the release, liberty should pull in the latest impl and api.

Sources should also be added as a follow up.

### PR DESCRIPTION
**Pull request by volosied**
fixes #15747 
fixes #13889

Changes include:

- Update to 3.0.0 from 3.0.0-RC1
- Deleted overlays
- Remove `Impl-Jar-Version` variable from bnd
- Update sources & javadoc (commented  out until they are uploaded by Chuck/Wendy)

No Changes Made:
- io.openliberty.thirdparty.faces-3.0  (Bnd did not need RC1 specificed, so it's already set to 3.0.0)
- io.openliberty.faces.internal (transformed -- uses latest 2.3 jar on build path)

### CODE REVIEW

**Comment by volosied** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jsfContainer_fat_2.3,com.ibm.ws.jsf_fat,com.ibm.ws.jsf.2.2_fat,com.ibm.ws.jsf.2.3_fat

**Comment by pnicolucci** [comment]
@volosied changes look good here. I'll give my final approval once the source is uploaded and uncommented in this PR and we have a good green build with those changes.

**Comment by volosied** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jsfContainer_fat_2.3,com.ibm.ws.jsf_fat,com.ibm.ws.jsf.2.2_fat,com.ibm.ws.jsf.2.3_fat

**Review by pnicolucci — APPROVED** [review]
Looks good Vlad!

**Comment by volosied** [comment]
#run-libby-bot

**Pull request merged**
