### PR TITLE
add isNewAuthentication checking for caller-initiated authentication 

### PR DESCRIPTION
**Pull request by arunavemulapalli**
Address - 
how we check for caller-initiated in OidcHttpAuthenticationMechanism
Check for isNewAuthentication in the AuthenticationParameters

### CODE REVIEW

**Comment by arunavemulapalli** [comment]
#build

**Comment by arunavemulapalli** [comment]
#libby

**Comment by arunavemulapalli** [comment]
#libby

**Comment by arunavemulapalli** [comment]
#build

**Review by teddyjtorres — APPROVED** [review]

**Pull request merged**
