### PR TITLE
MYFACES-4492: Select item label fix

### LINKED ISSUE #23214: Port MYFACES-4492 to Open Liberty
https://issues.apache.org/jira/browse/MYFACES-4492

### PR DESCRIPTION
**Pull request by pnicolucci**
fixes #23214

### CODE REVIEW

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
#libby #build

**Review by volosied — DISMISSED** [review]

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
#libby #build

**Review by volosied — APPROVED** [review]

**Pull request merged**
