### PR TITLE
Update MP Config 3.1 Dependencies

### LINKED ISSUE #26663: Update MP Config 3.1 API, TCK & SmallRye jars
Update to final version of API and TCK jars.
Update to latest applicable version of SmallRye Config.

### PR DESCRIPTION
**Pull request by tevans78**
This only partially resolves https://github.com/OpenLiberty/open-liberty/issues/26663
The SmallRye jars could not be updated because of a TCK failure on Java 21. That will have to be investigated and updated separately.

### CODE REVIEW

**Comment by tevans78** [comment]
#pbbeta

**Comment by tevans78** [comment]
#build

**Comment by tevans78** [comment]
The PB for this showed a failure in the MP Config 3.1 TCK. However, I do not see that locally. I'm going to re-run the PB and see if it happens again.
#build

**Comment by tevans78** [comment]
The previous TCK failure was caused by the updated SmallRye jars (3.4.1) when running on Java 21. Rolling the SmallRye changes back (to 3.3.0) meant that the TCK passed on Java 21. Will have to investigate that further.

**Comment by tevans78** [comment]
#build

**Comment by tevans78** [comment]
Note that the last build started did complete green but ended fast than the one before it (which still had the updated SmallRye jar in).

**Review by benjamin-confino — APPROVED** [review]

**Comment by tevans78** [comment]
#libby

**Pull request merged**
