### PR TITLE
fix gvt failure in some locales by overriding to utf8

### LINKED ISSUE #29665: Fix GVT failure for non-English locales
Currently GVT UI tests fails in some non-English locales (e.g. GVT in JMX REST Connector APIs). This is due to the server logs are read in ISO format instead of UTF-8

For RTC 301296

```
testUnicodeForNotification:junit.framework.AssertionFailedError: 2024-08-13-01:29:16:852 The SSL TCP Channel for default HTTPS endpoint did not start in time.
    at com.ibm.ws.gvt.rest.fat.BaseTestCase.waitForDefaultHttpsEndpoint(BaseTestCase.java:78)
    at com.ibm.ws.gvt.rest.fat.GvtTest.before(GvtTest.java:44)
...
```

### PR DESCRIPTION
**Pull request by nijoj**
- [x] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [x] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [x] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

Fixes #29665

### CODE REVIEW

**Comment by nijoj** [comment]
#build

**Comment by nijoj** [comment]
!GVT
artifact_execution_id=_vKvx4XTmEe-ZBdXWdK7Miw
bucket_image_artifact_execution_id=_vFVGYHTmEe-ZBdXWdK7Miw

**Comment by nijoj** [comment]
!GVT
artifact_execution_id=_vKvx4XTmEe-ZBdXWdK7Miw

**Comment by seethalm** [comment]
!GVT
artifact_execution_id=_pQxRUHTnEe-ZBdXWdK7Miw
bucket_image_artifact_execution_id=_vFVGYHTmEe-ZBdXWdK7Miw

**Comment by nijoj** [comment]
#build

**Comment by nijoj** [comment]
!build
git.clone.repository.username=nijo
git.clone.repository.branch=32727-fixGvtUiTest
fat.buckets.to.run=all

**Comment by nijoj** [comment]
!build
git.clone.repository.username=nijo
git.clone.checkout.branch=32727-fixGvtUiTest
fat.buckets.to.run=all

**Review by websterc87 — APPROVED** [review]
LGTM. Passing in GVT and PB.
This should work across the board but Iseries and ZOS failures are worth looking out for.

**Comment by seethalm** [comment]
#run-libby-bot

**Comment by wraschke** [comment]
@nijoj this is causing hard break 302151.

**Pull request merged**
