### PR TITLE
Reintroduce removal of unset of LOG_DIR

### LINKED ISSUE #26068: Re-introduce change reverted from 25993
Re-introduce change reverted from https://github.com/OpenLiberty/open-liberty/pull/25993

### PR DESCRIPTION
**Pull request by jimblye**
Fixes #26068

### CODE REVIEW

**Comment by jimblye** [comment]
#build

**Review by hlhoots — APPROVED** [review]
LGTM

**Comment by jimblye** [comment]
#build

**Comment by jimblye** [comment]
#build

**Pull request merged**
