### PR TITLE
Move logstash-5.5.0 to artifactory

### LINKED ISSUE #12923: Move logstash-5.5.0.zip to DHE
Need to also upload logstash-5.5.0.zip to DHE

### PR DESCRIPTION
**Pull request by Yushan-Lin**
Fixes #12923 
Regarding #12942

### CODE REVIEW

**Comment by Yushan-Lin** [comment]
#build

**Comment by Yushan-Lin** [comment]
https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_MvTF0MFTEeq9OZzIliLkpg

**Comment by Yushan-Lin** [comment]
https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_S9yBUMFTEeq9OZzIliLkpg

**Comment by Yushan-Lin** [comment]
#bulid

**Comment by Yushan-Lin** [comment]
https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_0sHcUMUFEeq1S7zZzzGuaA

**Comment by Yushan-Lin** [comment]
https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_I0L90MUGEeq1S7zZzzGuaA

**Comment by fmhwong** [comment]
@Yushan-Lin Which personal build show the tests are 100% passed?

**Comment by Yushan-Lin** [comment]
@fmhwong 
https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_S9yBUMFTEeq9OZzIliLkpg&tab=com.ibm.team.build.web.ui.internal.editors.result.test.TestProvider

**Comment by Yushan-Lin** [comment]
#run-libby-bot

**Pull request merged**
