### PR TITLE
testCancelRunningTask transaction timeout from test infrastructure slowness

### LINKED ISSUE #14266: Test Failure: PersistentExecutorTest.testCancelRunningTask
Test Failure: com.ibm.ws.concurrent.persistent.fat.PersistentExecutorTest.testCancelRunningTask

```
testCancelRunningTask:junit.framework.AssertionFailedError: 2020-09-16-16:56:47:942 [Unexpected FFDC reporting javax.resource.ResourceException was found (count = 2): /home/jazz_build/_YLG1kPgsEeqwgKOHPUEi3Q-EBC.PROD.WASRTC-EW8-000-00-00/jbe/build/dev/image/output/wlp/usr/servers/com.ibm.ws.concurrent.persistent.fat/logs/ffdc/ffdc_20.09.16_16.55.50.0.log
>------Start of DE processing------ = [9/16/20 16:55:50:056 UTC]
>Exception = javax.resource.ResourceException
>Source = com.ibm.ejs.j2c.ConnectionManager.initializeForUOW
>probeid = 730
>Stack Dump = javax.resource.ResourceException: addSync: caught Exception
>at com.ibm.ejs.j2c.LocalTransactionWrapper.addSync(LocalTransactionWrapper.java:877)
>at com.ibm.ejs.j2c.ConnectionManager.initializeForUOW(ConnectionManager.java:986)
>at com.ibm.ejs.j2c.ConnectionManager.involveMCInTran(ConnectionManager.java:705)
>at com.ibm.ejs.j2c.ConnectionManager.allocateConnection(ConnectionManager.java:322)
>at com.ibm.ws.rsadapter.jdbc.WSJdbcDataSource.getConnection(WSJdbcDataSource.java:137)
>at com.ibm.ws.rsadapter.jdbc.WSJdbcDataSource.getConnection(WSJdbcDataSource.java:111)
>at com.ibm.wsspi.persistence.internal.DatabaseStoreImpl.getDatabaseProductName(DatabaseStoreImpl.java:719)
>at com.ibm.wsspi.persistence.internal.DatabaseStoreImpl.createPersistenceServiceUnit(DatabaseStoreImpl.java:223)
>at com.ibm.ws.concurrent.persistent.db.DatabaseTaskStore.getPersistenceServiceUnit(DatabaseTaskStore.java:930)
>at com.ibm.ws.concurrent.persistent.db.DatabaseTaskStore.findOrCreate(DatabaseTaskStore.java:529)
>at com.ibm.ws.concurrent.persistent.internal.PersistentExecutorImpl.getPartitionId(PersistentExecutorImpl.java:827)
>at com.ibm.ws.concurrent.persistent.internal.PersistentExecutorImpl.newTask(PersistentExecutorImpl.java:1240)
>at com.ibm.ws.concurrent.persistent.internal.PersistentExecutorImpl.submit(PersistentExecutorImpl.java:1925)
>at web.SchedulerFATServlet.testCancelRunningTask(SchedulerFATServlet.java:1377)
>at java.base/jdk.intern
```

This is caused by poor test infrastructure.  It took over 2 minutes to connect to Derby, exceeding the transaction timeout.  In this particular case, persistent executor code is actually doing a retry, but the original error still ends up reported in the logs, which the test case flags as an error.  We could add these error messages as ones the test should tolerate to help work around when the tests run unreasonably slow.

```
[9/16/20, 16:53:32:024 UTC] 0000002b id=6fe31879 com.ibm.wsspi.persistence.internal.DatabaseStoreImpl         > getDatabaseProductName Entry  
                                                                                                               com.ibm.ws.rsadapter.jdbc.WSJdbcDataSource@c871fa1

[9/16/20, 16:55:32:024 UTC] 0000003b id=00000000 com.ibm.tx.jta.embeddable.impl.EmbeddableTimeoutManager      I WTRN0006W: Transaction 0000017497D5E6E6000000015F579B9CCB82400BBCA01980D7DCB28306DE40106C4292240000017497D5E6E6000000015F579B9CCB82400BBCA01980D7DCB28306DE40106C42922400000001 has timed out after 120 seconds.
[9/16/20, 16:55:32:026 UTC] 0000003c id=00000000 com.ibm.tx.jta.embeddable.impl.EmbeddableTimeoutManager      I WTRN0006W: Transaction 0000017497D5E6F8000000015F579BA4CB82400BBCA01980D7DCB28306DE40106C4292240000017497D5E6F8000000015F579BA4CB82400BBCA01980D7DCB28306DE40106C42922400000001 has timed out after 120 seconds.
[9/16/20, 16:55:32:033 UTC] 0000003b id=00000000 com.ibm.tx.jta.embeddable.impl.EmbeddableTimeoutManager      I WTRN0124I: When the timeout occurred the thread with which the transaction is, or was most recently, associated was Thread[Default Executor-thread-4,5,Default Executor Thread Group]. The stack trace of this thread when the timeout occurred was: 
	java.base/java.io.FileDescriptor.sync(Native Method)
	org.apache.derby.impl.io.DirRandomAccessFile.sync(Unknown Source)
	org.apache.derby.impl.store.raw.data.RAFContainer.writeRAFHeader(Unknown Source)
	org.apache.derby.impl.store.raw.data.RAFContainer.clean(Unknown Source)
	org.apache.derby.impl.services.cache.ConcurrentCache.cleanAndUnkeepEntry(Unknown Source)
	org.apache.derby.impl.services.cache.ConcurrentCache.cleanCache(Unknown Source)
	org.apache.derby.impl.services.cache.ConcurrentCache.cleanAll(Unknown Source)
	org.apache.derby.impl.store.raw.data.BaseDataFileFactory.checkpoint(Unknown Source)
	org.apache.derby.impl.store.raw.data.BaseDataFileFactory.createFinished(Unknown Source)
	org.apache.derby.impl.store.raw.RawStore.createFinished(Unknown Source)
	org.apache.derby.impl.store.access.RAMAccessManager.createFinished(Unknown Source)
	org.apache.derby.impl.db.BasicDatabase.createFinished(Unknown Source)
	org.apache.derby.impl.db.BasicDatabase.boot(Unknown Source)
	org.apache.derby.impl.services.monitor.BaseMonitor.boot(Unknown Source)
	org.apache.derby.impl.services.monitor.TopService.bootModule(Unknown Source)
	org.apache.derby.impl.services.monitor.BaseMonitor.bootService(Unknown Source)
	org.apache.derby.impl.services.monitor.BaseMonitor.createPersistentService(Unknown Source)
	org.apache.derby.impl.services.monitor.FileMonitor.createPersistentService(Unknown Source)
	org.apache.derby.iapi.services.monitor.Monitor.createPersistentService(Unknown Source)
	org.apache.derby.impl.jdbc.EmbedConnection.createDatabase(Unknown Source)
	org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	org.apache.derby.jdbc.InternalDriver.getNewEmbedConnection(Unknown Source)
	org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	org.apache.derby.jdbc.BasicEmbeddedDataSource40.getConnection(Unknown Source)
	org.apache.derby.jdbc.EmbedPooledConnection.openRealConnection(Unknown Source)
	org.apache.derby.jdbc.EmbedPooledConnection.<init>(Unknown Source)
	org.apache.derby.jdbc.InternalDriver.getNewPooledConnection(Unknown Source)
	org.apache.derby.jdbc.EmbeddedConnectionPoolDataSource.createPooledConnection(Unknown Source)
	org.apache.derby.jdbc.EmbeddedConnectionPoolDataSource.getPooledConnection(Unknown Source)
	com.ibm.ws.rsadapter.impl.DatabaseHelper$1.run(DatabaseHelper.java:967)
	com.ibm.ws.rsadapter.impl.DatabaseHelper$1.run(DatabaseHelper.java:953)
	java.base/java.security.AccessController.doPrivileged(AccessController.java:770)
	java.base/java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:826)
	com.ibm.ws.rsadapter.impl.DatabaseHelper.getPooledConnection(DatabaseHelper.java:953)
	com.ibm.ws.rsadapter.impl.WSManagedConnectionFactoryImpl.getConnection(WSManagedConnectionFactoryImpl.java:828)
	com.ibm.ws.rsadapter.impl.WSManagedConnectionFactoryImpl.createManagedConnection(WSManagedConnectionFactoryImpl.java:669)
	com.ibm.ejs.j2c.FreePool.createManagedConnectionWithMCWrapper(FreePool.java:1372)
	com.ibm.ejs.j2c.FreePool.createOrWaitForConnection(FreePool.java:1246)
	com.ibm.ejs.j2c.PoolManager.reserve(PoolManager.java:1465)
	com.ibm.ejs.j2c.ConnectionManager.allocateMCWrapper(ConnectionManager.java:587)com.ibm.ejs.j2c.ConnectionManager.allocateConnection(ConnectionManager.java:320)
	com.ibm.ws.rsadapter.jdbc.WSJdbcDataSource.getConnection(WSJdbcDataSource.java:137)
	com.ibm.ws.rsadapter.jdbc.WSJdbcDataSource.getConnection(WSJdbcDataSource.java:111)
	com.ibm.wsspi.persistence.internal.DatabaseStoreImpl.getDatabaseProductName(DatabaseStoreImpl.java:719)
	com.ibm.wsspi.persistence.internal.DatabaseStoreImpl.createPersistenceServiceUnit(DatabaseStoreImpl.java:223)
	com.ibm.ws.concurrent.persistent.db.DatabaseTaskStore.getPersistenceServiceUnit(DatabaseTaskStore.java:930)
	com.ibm.ws.concurrent.persistent.db.DatabaseTaskStore.findOrCreate(DatabaseTaskStore.java:529)
	com.ibm.ws.concurrent.persistent.internal.PersistentExecutorImpl.getPartitionId(PersistentExecutorImpl.java:827)
	com.ibm.ws.concurrent.persistent.internal.PersistentExecutorImpl.newTask(PersistentExecutorImpl.java:1240)
	com.ibm.ws.concurrent.persistent.internal.PersistentExecutorImpl.submit(PersistentExecutorImpl.java:1925)
	web.SchedulerFATServlet.testCancelRunningTask(SchedulerFATServlet.java:1377)
	java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	java.base/java.lang.reflect.Method.invoke(Method.java:566)
	web.SchedulerFATServlet.doGet(SchedulerFATServlet.java:147)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1230)
	com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:729)
	com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:426)
	com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1226)
	com.ibm.ws.webcontainer.webapp.WebApp.handleRequest(WebApp.java:5057)
	com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.handleRequest(DynamicVirtualHost.java:314)
	com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:1005)
	com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.run(DynamicVirtualHost.java:279)
	com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink$TaskWrapper.run(HttpDispatcherLink.java:1134)
	com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.wrapHandlerAndExecute(HttpDispatcherLink.java:415)
	com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.ready(HttpDispatcherLink.java:374)
	com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:577)
	com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleNewRequest(HttpInboundLink.java:511)
	com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.processRequest(HttpInboundLink.java:359)
	com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.ready(HttpInboundLink.java:326)
	com.ibm.ws.tcpchannel.internal.NewConnectionInitialReadCallback.sendToDiscriminators(NewConnectionInitialReadCallback.java:167)
	com.ibm.ws.tcpchannel.internal.NewConnectionInitialReadCallback.complete(NewConnectionInitialReadCallback.java:75)
	com.ibm.ws.tcpchannel.internal.WorkQueueManager.requestComplete(WorkQueueManager.java:504)
	com.ibm.ws.tcpchannel.internal.WorkQueueManager.attemptIO(WorkQueueManager.java:574)
	com.ibm.ws.tcpchannel.internal.WorkQueueManager.workerRun(WorkQueueManager.java:958)
	com.ibm.ws.tcpchannel.internal.WorkQueueManager$Worker.run(WorkQueueManager.java:1047)
	com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:239)
	java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	java.base/java.lang.Thread.run(Thread.java:834)
```

### PR DESCRIPTION
**Pull request by njr-11**
fixes #14266

### CODE REVIEW

**Review by nmittles — APPROVED** [review]

**Comment by njr-11** [comment]
#build

**Comment by njr-11** [comment]
#build

**Comment by njr-11** [comment]
#build
#run-libby-bot

**Comment by njr-11** [comment]
#build

**Comment by njr-11** [comment]
Although the result was not automatically posted by LibbyBot, the most recent build has passed with all tests successful,
https://wasrtc.hursley.ibm.com:9443/jazz/resource/itemOid/com.ibm.team.build.BuildResult/_oFLY0AfTEeuIgpJAZoWiKQ

**Pull request merged**
