### PR TITLE
Add DHE repository to allow internal tck to run locally.

### PR DESCRIPTION
**Pull request by jim-krueger**

### CODE REVIEW

**Comment by jim-krueger** [comment]
Some of the internal TCK projects for MPRestClient use a special back-ported TCK repository (see [PR 15937](https://github.com/OpenLiberty/open-liberty/pull/15937).  While these test buckets will run fine during a build, which pulled in these repositories from artifactory, they will not run locally (since the repositories do not exist in maven central).   The PR changes the pom.xmls for these projects to use the DHE repository, which fixes the problem.

**Comment by jim-krueger** [comment]
#build

**Review by WhiteCat22 — APPROVED** [review]

**Review by Azquelt — APPROVED** [review]

**Comment by jim-krueger** [comment]
#build

**Review by jhanders34 — APPROVED** [review]

**Comment by jim-krueger** [comment]
#run-libby-bot

**Pull request merged**
