### PR TITLE
create nonship jdbc-4.3 feature

### PR DESCRIPTION
**Pull request by njr-11**
Create a jdbc-4.3 feature as non-ship so that we can start experimenting with an implementation.

### CODE REVIEW

**Comment by njr-11** [comment]
#build

**Comment by njr-11** [comment]
#build

**Comment by lzdanski** [comment]
@njr-11 Looks good! Adding ID Reviewed label

**Comment by njr-11** [comment]
build has 10 test failures, but all are pre-existing issues in unrelated test buckets.

**Pull request merged**
