### PR TITLE
Ltpa fat key replacement tests

### PR DESCRIPTION
**Pull request by mshah0722**
Adding 3 new FAT Tests:

1. testLTPAFileReplacement_invalid3DESKey_monitorValidationKeysDir_true_monitorInterval_10
2. testLTPAFileReplacement_invalidPrivateKey_monitorValidationKeysDir_true_monitorInterval_10
3. testLTPAFileReplacement_invalidPublicKey_monitorValidationKeysDir_true_monitorInterval_10

### CODE REVIEW

**Comment by mshah0722** [comment]
#libby
#build
#spawn.fullfat.buckets=com.ibm.ws.security.token.ltpa_fat

**Comment by mshah0722** [comment]
#libby
#build
#spawn.fullfat.buckets=com.ibm.ws.security.token.ltpa_fat

**Review by Zech-Hein — APPROVED** [review]
LGTM

**Comment by mshah0722** [comment]
Build error is unrelated.

**Pull request merged**
