### PR TITLE
Remove unnecessary attribute as per UFO review and gate keep logic wh…

### PR DESCRIPTION
**Pull request by Channyboy**
…en monitor-1.0 filter does not have HTTP present

- [x] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [x] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [x] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

################################################################################################

#build

### CODE REVIEW

**Review by tonyreigns — DISMISSED** [review]
LGTM

**Comment by Channyboy** [comment]
#build #libby

**Comment by Channyboy** [comment]
#build #libby

**Comment by Channyboy** [comment]
Errors encountered in build were test infra related (and for other tests).

**Review by tonyreigns — DISMISSED** [review]
LGTM

**Comment by Channyboy** [comment]
#build

**Comment by Channyboy** [comment]
#build #libby

**Review by tonyreigns — APPROVED** [review]

**Comment by Channyboy** [comment]
Pipeline is good. Only failures are GUI related.
RTC is still running (and no failures) but the relevant `io.openliberty.http.monitor_fat` tests have executed successfully.
merging.

**Pull request merged**
