### PR TITLE
First drop of mpConfig-3.0

### PR DESCRIPTION
**Pull request by tevans78**
#build

### CODE REVIEW

**Comment by tevans78** [comment]
#build

**Comment by tevans78** [comment]
#build

**Comment by tevans78** [comment]
depends on https://github.com/OpenLiberty/open-liberty/pull/18354

**Comment by tevans78** [comment]
#build

**Review by Emily-Jiang — APPROVED** [review]
LGTM!

**Comment by tevans78** [comment]
#build

**Comment by tevans78** [comment]
#build

**Comment by tevans78** [comment]
#build

**Comment by tevans78** [comment]
#build

**Comment by tevans78** [comment]
#build

**Review by helyarp — COMMENTED** [review]
Looks good!

**Comment by tevans78** [comment]
#run-libby-bot

**Comment by tevans78** [comment]
https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_xutO0AwREeygdL3FgLlrXw

This PB was good enough

**Pull request merged**
