### PR TITLE
change the metadata structure.

### PR DESCRIPTION
**Pull request by toshiyamamoto**
The format of the metadata of serialFilter needs to be changed. Instead of using multiple element to specify multiple filter mode and permission, use serialFilter as an enclosure and introduce filterMode and policy element to specify filter mode and permission respectively.

### CODE REVIEW

**Comment by toshiyamamoto** [comment]
#build

**Comment by toshiyamamoto** [comment]
#build

**Comment by toshiyamamoto** [comment]
#build

**Comment by toshiyamamoto** [comment]
The previous PR had one error which I believe unrelated. But let me run a PR again.
#build

**Comment by skasund** [comment]
Message review complete for L2

**Comment by bsbyrd1** [comment]
Properties file strings look good. Thanks!

**Comment by toshiyamamoto** [comment]
#build

**Comment by toshiyamamoto** [comment]
#build

**Comment by toshiyamamoto** [comment]
#build

**Comment by toshiyamamoto** [comment]
#build

**Comment by toshiyamamoto** [comment]
#build

**Comment by toshiyamamoto** [comment]
#build

**Pull request merged**
