### PR TITLE
Ph59682

### PR DESCRIPTION
**Pull request by WhiteCat22**

### CODE REVIEW

**Review by volosied — DISMISSED** [review]

**Comment by WhiteCat22** [comment]
Fixes https://github.com/OpenLiberty/open-liberty/issues/28176

**Comment by WhiteCat22** [comment]
Fixes #PH59682

**Comment by WhiteCat22** [comment]
#build

**Comment by WhiteCat22** [comment]
#libby

**Comment by WhiteCat22** [comment]
#libby #build

**Comment by WhiteCat22** [comment]
#libby #build

**Comment by volosied** [comment]
#build #fat.buckets.to.run=com.ibm.ws.jsp.2.3_fat,com.ibm.ws.jsp_fat_lWAS.toleration.ee9

**Comment by volosied** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jsp.2.3_fat,com.ibm.ws.jsp_fat_lWAS.toleration.ee9

**Review by volosied — DISMISSED** [review]
Merge if the build is good

**Comment by WhiteCat22** [comment]
Fixes #PH61042

**Comment by WhiteCat22** [comment]
#libby #build

**Review by neuwerk — DISMISSED** [review]
LGTM!

**Review by volosied — DISMISSED** [review]

**Comment by WhiteCat22** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jsp.2.3_fat,com.ibm.ws.jsp_fat_lWAS.toleration.ee9

**Comment by WhiteCat22** [comment]
#libby #build

**Review by volosied — APPROVED** [review]

**Pull request merged**
