### PR TITLE
add gRPC monitoring services

### PR DESCRIPTION
**Pull request by wtlucy**
- create proper osgi services for the monitoring autofeature
- remove dynamic imports for monitoring packages
- remove direct classloads of grpc monitoring classes

for #10093

### CODE REVIEW

**Comment by wtlucy** [comment]
#build

**Review by Azquelt — APPROVED** [review]
All looks good to me :+1:

**Review by annaguri — APPROVED** [review]
Looks good to me.

**Comment by wtlucy** [comment]
#run-libby-bot

**Pull request merged**
