### PR TITLE
Reset version for Faces 4.0

### LINKED ISSUE #22207: Faces 4.0: use package-info.java at 1.0.0 version for com.ibm.ws.jsf.ee export in io.openliberty.org.apache.myfaces.4.0 impl bundle
Currently, it is set at 1.0.44 from MyFaces 3.0 which doesn't really make sense here.

This was initially done in faces-3.0 here: https://github.com/OpenLiberty/open-liberty/pull/13839/files and https://github.com/OpenLiberty/open-liberty/commit/a98df4a96af6a5815a69d78a39c96fdca433d32b

### PR DESCRIPTION
**Pull request by pnicolucci**
fixes #22207

### CODE REVIEW

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
If version is removed: `error  : Used bundle version 1.0.70 for exported package com.ibm.ws.jsf.ee` need to use package-info.java

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
#libby #build

**Review by volosied — APPROVED** [review]
I agree. We should start with 1.0.0

**Pull request merged**
