### PR TITLE
Delete com.ibm.ws.org.apache.commons.discovery Bundle

### PR DESCRIPTION
**Pull request by volosied**
Not needed by JSF, so we're removing it. 

For #26946

### CODE REVIEW

**Comment by volosied** [comment]
#build

**Review by pnicolucci — DISMISSED** [review]

**Comment by volosied** [comment]
#build

**Review by pnicolucci — APPROVED** [review]

**Comment by volosied** [comment]
#libby

**Comment by volosied** [comment]
#build

**Pull request merged**
