### PR TITLE
Issue #21635: Rename Servlet 6.0 Factories bundle

### LINKED ISSUE #21635: Rename `io.openliberty.servlet.6.0.internal.factories` to `io.openliberty.webcontainer.servlet.6.0.internal.factories`
Rename for consistency.

### PR DESCRIPTION
**Pull request by pnicolucci**
fixes #21635

### CODE REVIEW

**Comment by pnicolucci** [comment]
#build

**Comment by wraschke** [comment]
One fish two fish red fish blue fish.

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
I'm going to start a fresh PR as there have been a number of changes to the structure of the webcontainer projects/features.

**Pull request closed without merging**
