### PR TITLE
fix mp-jwt spec violation

### LINKED ISSUE #4712: release bug: mpjwt JsonWebToken.getAudience() return type noncompliant with spec when no audiences present.
spec says when no audiences, it should return null, but we return an empty set

### PR DESCRIPTION
**Pull request by brutif**
resolves #4712

### CODE REVIEW

**Comment by brutif** [comment]
the mpjwt1.1 version of the tck has added a new test that detects the problem.

**Comment by brutif** [comment]
this has to wait for fat updates on 12964 before it can be submitted.

**Comment by brutif** [comment]
I will go ahead and submit a build to smoke out anything -else- it might have broken, but failures in the CL mpjwt fats are expected.

#build

**Comment by arunavemulapalli** [comment]
mpjwt fat failures are addressed in this PR - https://github.ibm.com/was-liberty/WS-CD-Open/pull/12935

**Comment by arunavemulapalli** [comment]
If PB looks good, please goahead and merge the change.
Your changes are not the cause for mpjwt test MPJwtAPIConfigTests_JwksUri_JWTHasJWK_mpJwtMisMatchJWK failure. This is introduced when we updated the jwk code

**Comment by brutif** [comment]
oh let's run the jwtsso full fat since it uses mpjwt
#build 
#spawn.fullfat.buckets=com.ibm.ws.security.jwtsso_fat

**Comment by brutif** [comment]
pb is good, failures in com.ibm.ws.security.jwt_fat.mpjwt are expected until 12964 goes into master.  Will wait to merge until that happens.

**Comment by brutif** [comment]
``` code ```

**Pull request merged**
