### PR TITLE
RESTful WS 3.0 TCK: Handle case where App subclass is specified as servlet-name

### PR DESCRIPTION
**Pull request by andymc12**
Addresses failures in jaxrs_platform/*servlet* buckets.

Refactors FAT test code for re-using with test were web.xml specifies "jakarta.ws.rs.core.Application" for servlet-name (see PR #15339).

### CODE REVIEW

**Comment by andymc12** [comment]
#build

**Review by WhiteCat22 — APPROVED** [review]

**Comment by andymc12** [comment]
Fixed bad merge - new #build

**Comment by andymc12** [comment]
#libby

**Comment by andymc12** [comment]
#run-libby-bot testcases in this PR...

**Pull request merged**
