### PR TITLE
Put faces-4.1 in Beta

### LINKED ISSUE #28387: Faces 4.1: Move to beta
We're only moving the `faces-4.1` feature to beta not the `facesContainer-4.1`feature. The facesContainer-4.1 feature will beta at the same time as `websocket-2.2`

### PR DESCRIPTION
**Pull request by pnicolucci**
fixes #28387

### CODE REVIEW

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
> java.lang.AssertionError: Found features violating visibility conditions: 
> Found issues with Feature: [io.openliberty.faces-4.1]   Edition: [core]   Kind: [beta]
>      It provisions less visible features: 
>      Feature: [io.openliberty.jakarta.websocket-2.2]   Edition: [full]   Kind: [noship]
>      Feature: [io.openliberty.noShip-1.0]   Edition: [full]   Kind: [noship]
> Found issues with Feature: [io.openliberty.jakarta.faces-4.1]   Edition: [core]   Kind: [beta]
>      It provisions less visible features: 
>      Feature: [io.openliberty.noShip-1.0]   Edition: [full]   Kind: [noship]
> Found issues with Feature: [io.openliberty.facesContainer-4.1]   Edition: [core]   Kind: [beta]
>      It provisions less visible features: 
>      Feature: [io.openliberty.jakarta.websocket-2.2]   Edition: [full]   Kind: [noship]
>      Feature: [io.openliberty.noShip-1.0]   Edition: [full]   Kind: [noship]
>      Feature: [io.openliberty.websocket-2.2]   Edition: [full]   Kind: [noship]

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
> 	
> 
> java.lang.AssertionError: Found features violating visibility conditions: 
> Found issues with Feature: [io.openliberty.facesContainer-4.1]   Edition: [core]   Kind: [beta]
>      It provisions less visible features: 
>      Feature: [io.openliberty.websocket-2.2]   Edition: [full]   Kind: [noship]

We're working on WebSockets 2.2 dev, once ready I'll add to beta as well!

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
Websockets won't be ready for beta, so we can't beta the facescontainer.

**Comment by pnicolucci** [comment]
> ava.lang.AssertionError: Found features violating visibility conditions: 
> Found issues with Feature: [io.openliberty.faces-4.1]   Edition: [core]   Kind: [beta]
>      It provisions less visible features: 
>      Feature: [io.openliberty.facesProvider-4.1.0.MyFaces]   Edition: [full]   Kind: [noship]
>

**Comment by pnicolucci** [comment]
> java.lang.AssertionError: Found features that are marked noship, but contain only beta/ga features without a noship feature dependency: 
> If you recently marked a feature beta, you may need to update the feature to depend on noShip-1.0 feature, add or remove from the expected failures list in this test, or have something to fix.
> Found issues with io.openliberty.websocket-2.2
>      The feature is marked noship, but all dependencies are beta or ga
> 
> 	at org.junit.Assert.fail(Assert.java:93)

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
> org.junit.ComparisonFailure: There are versionless features that need to be created. Templates for the needed features have been created in the 'build/versionless' directory.
> Keep in mind the templates are not guarenteed to be correct and are solely meant to act as a helpful starting point for creating a versionless feature.
> Verify the data inside the feature files are correct, then copy the features from 'build/versionless' into 'visibility'.
> Versionless feature files were created for feature(s): jsf, faces expected:<[]> but was:<[Versionless feature files were created for feature(s): jsf, faces]>
> 	at org.junit.Assert.assertEquals(Assert.java:125)
> 	at com.ibm.ws.feature.tests.VersionlessTest.listSelectorDetails(VersionlessTest.java:366)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

**Comment by pnicolucci** [comment]
> junit.framework.AssertionFailedError: Feature resolution [ Singleton [ io.openliberty.faces-4.1 ] [ SERVER ] ] failed with [ 1 ] errors: Missing [ noShip-1.0 ]
> 	at com.ibm.ws.feature.tests.FeatureResolutionUnitTestBase.doTestResolve(FeatureResolutionUnitTestBase.java:384)
> 	at com.ibm.ws.feature.tests.BaselineSingletonUnitTest.testResolve_singleton_baseline(BaselineSingletonUnitTest.java:117)
> 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)

> junit.framework.AssertionFailedError: Feature resolution [ Singleton [ io.openliberty.websocket-2.2 ] [ SERVER ] ] failed with [ 1 ] errors: Missing [ noShip-1.0 ]
> 	at com.ibm.ws.feature.tests.FeatureResolutionUnitTestBase.doTestResolve(FeatureResolutionUnitTestBase.java:384)
> 	at com.ibm.ws.feature.tests.BaselineSingletonUnitTest.testResolve_singleton_baseline(BaselineSingletonUnitTest.java:117)
> 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)

> junit.framework.AssertionFailedError: Feature resolution [ Singleton [ io.openliberty.facesContainer-4.1 ] [ SERVER ] ] failed with [ 1 ] errors: Missing [ noShip-1.0 ]
> 	at com.ibm.ws.feature.tests.FeatureResolutionUnitTestBase.doTestResolve(FeatureResolutionUnitTestBase.java:384)
> 	at com.ibm.ws.feature.tests.BaselineSingletonUnitTest.testResolve_singleton_baseline(BaselineSingletonUnitTest.java:117)
> 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)

**Comment by pnicolucci** [comment]
#build

**Review by jhanders34 — DISMISSED** [review]

**Comment by pnicolucci** [comment]
#build

**Review by jhanders34 — DISMISSED** [review]

**Comment by jhanders34** [comment]
#libby

**Review by jhanders34 — DISMISSED** [review]

**Comment by jhanders34** [comment]
#libby #build

**Comment by jhanders34** [comment]
#libby #build

**Review by jhanders34 — APPROVED** [review]

**Pull request merged**
