### PR TITLE
Enable jsfContainer_fat_2.3 web socket test for  ee10

### PR DESCRIPTION
**Pull request by pnicolucci**
for #22202

I'm also removing the use of JSFApplication to fix a build issue.

### CODE REVIEW

**Comment by pnicolucci** [comment]
#libby #build

**Comment by wraschke** [comment]
#pbbeta

**Comment by wraschke** [comment]
#pbbeta@dev

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
> The build pnicolucci-24249-20230213-0902 https://wasrtc.hursley.ibm.com:9443/jazz/resource/itemOid/com.ibm.team.build.BuildResult/_rTMggKu2Ee2FnaZGnlWrhQ completed and has errors or failures.
> 
> For help analyzing your personal build, go to https://cognitive.hursley.ibm.com/buildAnalysis.html?uuid=_rTMggKu2Ee2FnaZGnlWrhQ

I executed the failed child build again and it was successful: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_OaOe8KxXEe2FnaZGnlWrhQ

**Review by isaacrivriv — APPROVED** [review]
Looks good to me!

**Pull request merged**
