### PR TITLE
Reinstate transaction summary trace

### LINKED ISSUE #21148: Transactions summary trace is missing
The TransactionSummary trace group which is used to provide ultra minimal trace for transaction creation and setRollbackOnly no longer works.

Set TransactionSummary=all trace and notice that regular Transaction=all trace is emitted.

Trace is emitted only for transaction creation and setRollbackOnly

This trace group is used when identifying what started a transaction or what rolled back a transaction in very high throughput systems where regular trace would be too big.

### PR DESCRIPTION
**Pull request by jonhawkes**
fixes #21148

#build

### CODE REVIEW

**Review by neilgsyoung — APPROVED** [review]
Looks good

**Comment by jonhawkes** [comment]
#build

**Comment by jonhawkes** [comment]
#build

**Comment by jonhawkes** [comment]
#build

**Pull request merged**
