### PR TITLE
Create decrementNeeded flag for wsoc quiese error

### LINKED ISSUE #17599: HTTP upgrade to WebSocket can cause quiesce errors
**Describe the bug**  
When a websocket connection is started, it starts as an HTTP connection. If an error occurs during the transition between an HTTP and a websocket connection, which is known to be a websocket upgrade, the error processing neglects to decrement a connection counter, which then causes the server to believe there is an open connection during server stop.

There are two scenarios we are aware of when these quiesce errors occur. As an HTTP upgrade connection request is sent to the server.

1) When a read error occurs during the transition between an HTTP and a websocket connection, the error processing neglects to decrement a connection counter, which then causes the server to believe there is an open connection during server stop.

2) If a client immediately closes the websocket connection after it is opened, the original upgrade request handling may not have had enough time to close properly on the server. Once again, the connection counter fails to decrement leading the server to believe there is an open connection during the server stop.

**Steps to Reproduce**  
This problem is not manually reproduceable and is intermittent.

**Expected behavior**  
The connection counter should be decremented properly when an error occurs during the websocket upgrade process.

**Diagnostic information:**  
 - OpenLiberty Version: all
 - Affected feature(s): websocket-1.0, websocket-1.1

**Additional context**  
None

====================
Summary:

The problem is intermittent.

The triggering factor is when an unexpected read error occurs, like this one:
```
[6/14/21 8:37:03:735 PDT] 0000001e id=207ec47a com.ibm.ws.tcpchannel.internal.SocketIOChannel 1 Read -1(-1) bytes, 1 requested on local: localhost/127.0.0.1:8010 remote: localhost/127.0.0.1:57364
[6/14/21 8:37:03:735 PDT] 0000001e id=00000000 com.ibm.ws.tcpchannel.internal.WorkQueueManager > requestComplete Entry
[6/14/21 8:37:03:735 PDT] 0000001e id=00000000 com.ibm.ws.tcpchannel.internal.WorkQueueManager 3 calling cc.error callback
```

In this case, the wsoc connection has received an initial request with an upgrade header. The 101 response has been sent back. Then a read on a new thread is issued, which immediately returned with a read error.

When this error happens, a CLOSE frame is sent out which is successful, then some clean up work is done.

Then we get to this cleanup where the httpdispatcher link isn't closed, it's just destroyed. This is all being done on the read thread.

```
[6/14/21 8:37:03:738 PDT] 0000001e id=00000000 com.ibm.ws.tcpchannel.internal.TCPConnLink > close(), com.ibm.ws.tcpchannel.internal.TCPConnLink@4da115f4 Entry
[6/14/21 8:37:03:738 PDT] 0000001e id=00000000 com.ibm.ws.tcpchannel.internal.TCPConnLink 3 Closing the connection: remote host name: localhost remote host address: 127.0.0.1 local host name: localhost local host address: 127.0.0.1
[6/14/21 8:37:03:738 PDT] 0000001e id=00000000 com.ibm.ws.tcpchannel.internal.TCPConnLink > destroy(null) Entry
[6/14/21 8:37:03:738 PDT] 0000001e id=00000000 com.ibm.ws.tcpchannel.internal.TCPConnLink 3 Destroying the connection: remote host name: localhost remote host address: 127.0.0.1 local host name: localhost local host address: 127.0.0.1
[6/14/21 8:37:03:738 PDT] 0000001e id=207ec47a com.ibm.ws.tcpchannel.internal.NioSocketIOChannel > close Entry
[6/14/21 8:37:03:738 PDT] 0000001e id=207ec47a com.ibm.ws.tcpchannel.internal.NioSocketIOChannel 1 SocketChannel closing, local: localhost/127.0.0.1:8010 remote: localhost/127.0.0.1:57364
[6/14/21 8:37:03:738 PDT] 0000001e id=207ec47a com.ibm.ws.tcpchannel.internal.NioSocketIOChannel < close Exit
[6/14/21 8:37:03:738 PDT] 0000001e id=00000000 com.ibm.ws.http.channel.internal.inbound.HttpInboundLink 3 Destroying inbound link: com.ibm.ws.http.channel.internal.inbound.HttpInboundLink@4f98915a com.ibm.ws.channelfw.internal.InboundVirtualConnectionImpl@6253b74
[6/14/21 8:37:03:738 PDT] 0000001e id=0f7505cd m.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink > destroy Entry
null
[6/14/21 8:37:03:738 PDT] 0000001e id=00000000 m.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink 3 Destroy with exc=null
[6/14/21 8:37:03:738 PDT] 0000001e id=0f7505cd m.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink > getVC Entry
[6/14/21 8:37:03:738 PDT] 0000001e id=0f7505cd m.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink < getVC Exit
com.ibm.ws.channelfw.internal.InboundVirtualConnectionImpl@6253b74
[6/14/21 8:37:03:738 PDT] 0000001e id=55abae00 com.ibm.ws.wsoc.WsocUpgradeHandler > destroy Entry
```

Later the original thread comes back in and tries to clean up, but the vc is null, so the close on httpdispatcherlink is called with a null value. It just exits when called with a null value. That's where the counter should have been decremented.

```
[6/14/21 8:37:03:752 PDT] 0000001f id=0f7505cd m.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink > finish Entry
null
[6/14/21 8:37:03:752 PDT] 0000001f id=00000000 m.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink 1 Finishing conn; null error=null
[6/14/21 8:37:03:752 PDT] 0000001f id=0f7505cd m.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink > closeStreams Entry
[6/14/21 8:37:03:752 PDT] 0000001f id=0f7505cd m.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink < closeStreams Exit
null
[6/14/21 8:37:03:752 PDT] 0000001f id=0f7505cd m.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink > close Entry
null
null
[6/14/21 8:37:03:752 PDT] 0000001f id=00000000 m.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink 3 Close called , vc ->null hc: 259327437
[6/14/21 8:37:03:752 PDT] 0000001f id=00000000 m.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink 3 Connection must be already closed since vc is null
```

### PR DESCRIPTION
**Pull request by volosied**
fixes #17599 without any timeouts. 

As mentioned in the issue description, the problem is that HttpDispatcherLink.destroy is called before the wsoc upgrade HttpDispatcherLink.close is called.  This causes vc to become null, which causes the thread to exit the close early. This means the connection count isn't properly decremented. 

Avoiding this quiesce has been troublesome, too. We need to decrement the connection count exactly down to zero. Unfortunately, there have been many previous attempts for this fix that causes the connection count to be negative or not decrement to 0.

The current working solution uses an AtomicBoolean `destroyCalledForWsocUpgrade` that is set to true when destroy is called. There's a check in the close that will then decrement the count since we know destroy was called during a wsoc upgrade.

The only special consideration is the HTTP2 upgrade process also has a similar flow, so we added the `!getHttpInboundLink2().isDirectHttp2Link(vc)` check to ensure connection count isn't decremented in that case since we could encounter a different quiesce error in http2.

### CODE REVIEW

**Comment by volosied** [comment]
#build #spawn.fullfat.buckets=io.openliberty.wsoc.internal_fat,com.ibm.ws.webcontainer.servlet.4.0_fat,com.ibm.ws.webcontainer.servlet.3.1_fat

**Review by loriadi — APPROVED** [review]
I like this one better!

**Comment by volosied** [comment]
#build #spawn.fullfat.buckets=io.openliberty.wsoc.internal_fat,com.ibm.ws.webcontainer.servlet.4.0_fat,com.ibm.ws.webcontainer.servlet.3.1_fat

**Review by wtlucy — APPROVED** [review]
discussed on slack, looks good to me

**Comment by volosied** [comment]
#build #spawn.fullfat.buckets=io.openliberty.wsoc.internal_fat,com.ibm.ws.webcontainer.servlet.4.0_fat,com.ibm.ws.webcontainer.servlet.3.1_fat

**Comment by volosied** [comment]
#build #spawn.fullfat.buckets=io.openliberty.wsoc.internal_fat,com.ibm.ws.webcontainer.servlet.4.0_fat,com.ibm.ws.webcontainer.servlet.3.1_fat

**Comment by volosied** [comment]
#build #spawn.fullfat.buckets=io.openliberty.wsoc.internal_fat,com.ibm.ws.webcontainer.servlet.4.0_fat,com.ibm.ws.webcontainer.servlet.3.1_fat

**Comment by volosied** [comment]
#build

**Comment by volosied** [comment]
#build

**Comment by volosied** [comment]
#build #spawn.fullfat.buckets=io.openliberty.wsoc.internal_fat,com.ibm.ws.transport.http2_fat,com.ibm.ws.webcontainer.servlet.4.0_fat,com.ibm.ws.webcontainer.servlet.3.1_fat

**Comment by volosied** [comment]
#build #spawn.fullfat.buckets=io.openliberty.wsoc.internal_fat,com.ibm.ws.transport.http2_fat,com.ibm.ws.webcontainer.servlet.4.0_fat,com.ibm.ws.webcontainer.servlet.3.1_fat

**Review by mrsaldana — APPROVED** [review]
This looks good to me, thanks for working on this!

**Review by loriadi — APPROVED** [review]
Thanks for tackling this complex issue.

**Comment by volosied** [comment]
#build #spawn.fullfat.buckets=io.openliberty.wsoc.internal_fat,com.ibm.ws.transport.http2_fat,com.ibm.ws.webcontainer.servlet.4.0_fat,com.ibm.ws.webcontainer.servlet.3.1_fat

**Comment by volosied** [comment]
Seeing errors in the logs:

[10/5/21, 19:47:24:230 PDT] 00000027 com.ibm.ws.logging.internal.impl.IncidentImpl                I FFDC1015I: An FFDC Incident has been created: "java.lang.NullPointerException com.ibm.ws.tcpchannel.internal.WorkQueueManager workerRun(req)" at ffdc_21.10.05_19.47.24.1.log

I've changed back the if condition statement to see if it reoccurs.

**Comment by volosied** [comment]
#build #spawn.fullfat.buckets=io.openliberty.wsoc.internal_fat,com.ibm.ws.transport.http2_fat,com.ibm.ws.webcontainer.servlet.4.0_fat,com.ibm.ws.webcontainer.servlet.3.1_fat

**Comment by volosied** [comment]
#build #spawn.fullfat.buckets=io.openliberty.wsoc.internal_fat,com.ibm.ws.transport.http2_fat,com.ibm.ws.webcontainer.servlet.4.0_fat,com.ibm.ws.webcontainer.servlet.3.1_fat

**Comment by volosied** [comment]
#build #spawn.fullfat.buckets=io.openliberty.wsoc.internal_fat,com.ibm.ws.transport.http2_fat,com.ibm.ws.webcontainer.servlet.4.0_fat,com.ibm.ws.webcontainer.servlet.3.1_fat

**Comment by volosied** [comment]
#build #spawn.fullfat.buckets=io.openliberty.wsoc.internal_fat,com.ibm.ws.transport.http2_fat,com.ibm.ws.webcontainer.servlet.4.0_fat,com.ibm.ws.webcontainer.servlet.3.1_fat

**Review by wtlucy — APPROVED** [review]
LGTM, thanks for working this out

**Comment by volosied** [comment]
Full FATs looked good.  Unrelated GUI defects did occur though. Defect 286243 occurred and it's also a quiesce error( for a different reason)

PR looks very promising given the recent 2 builds. Merging code. :)

**Comment by volosied** [comment]
#run-libby-bot

**Comment by volosied** [comment]
fixes #17599

**Pull request merged**
