### PR TITLE
DiscoveryHandler fetches discovery doc and returns a parsed JSONObject

### PR DESCRIPTION
**Pull request by tmooretcm**
DiscoveryHandler now successfully creates an HTTP Request based on the common HttpUtils class, and returns a parsed JSONString.

### CODE REVIEW

**Comment by tmooretcm** [comment]
#libby

**Comment by tmooretcm** [comment]
#build

**Review by ayoho — APPROVED** [review]

**Comment by tmooretcm** [comment]
#build

**Comment by tmooretcm** [comment]
#libby

**Review by ayoho — APPROVED** [review]

**Comment by tmooretcm** [comment]
#build

**Comment by tmooretcm** [comment]
#libby

**Review by teddyjtorres — APPROVED** [review]

**Comment by tmooretcm** [comment]
#build
#libby

**Pull request merged**
