### PR TITLE
Revert "empty list of entities"

### PR DESCRIPTION
**Pull request by Zech-Hein**
Reverts OpenLiberty/open-liberty#30145

### CODE REVIEW

**Comment by Zech-Hein** [comment]
#libby

**Comment by contbld** [comment]
Your personal pipeline request is at https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=545af472-9852-4f30-bdd5-1d7c9f0d87ac

Target locations of links might be accessible only to IBM employees.

**Review by njr-11 — APPROVED** [review]

**Comment by contbld** [comment]
<h3>Code analysis and actions</h3>
DO NOT DELETE THIS COMMENT.

- 4 FAT files were changed, added, or removed.
 - Check that the build did not break the affected FAT suite(s).

- 4 product code files were changed.

**Comment by contbld** [comment]
https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=545af472-9852-4f30-bdd5-1d7c9f0d87ac completed successfully!

**Pull request merged**
