### PR TITLE
In the case of remote repo install, handle beta platform features

### PR DESCRIPTION
**Pull request by cbridgha**
- [x ] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [x ] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [x] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

################################################################################################

### CODE REVIEW

**Comment by cbridgha** [comment]
#build

**Review by rsherget — DISMISSED** [review]
LGTM

**Comment by cbridgha** [comment]
#build

**Review by rsherget — APPROVED** [review]
LGTM

**Comment by cbridgha** [comment]
New Build: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_-1QwoXWvEe-ZBdXWdK7Miw

**Comment by cbridgha** [comment]
#libby

**Pull request merged**
