### PR TITLE
Update server dump to not wait indefinitely to complete

### PR DESCRIPTION
**Pull request by jhanders34**
- [x] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [x] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [x] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

### CODE REVIEW

**Comment by jhanders34** [comment]
#build

**Comment by contbld** [comment]
Your personal pipeline request is at https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=e8bca208-5bc6-4358-bb78-bdfb8931890e

Target locations of links might be accessible only to IBM employees.

**Comment by contbld** [comment]
<h3>Code analysis and actions</h3>
DO NOT DELETE THIS COMMENT.

- 1 test infrastructure code files were changed.
 - Test failures/errors in the build could be due to these changes.

**Comment by contbld** [comment]
https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=e8bca208-5bc6-4358-bb78-bdfb8931890e has errors/failures.

**Review by barbj — APPROVED** [review]

**Comment by jhanders34** [comment]
!libby

**Comment by contbld** [comment]
Your personal pipeline request is at https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=9bbb1268-b285-4ec6-b65c-48bcc06c72fe

Target locations of links might be accessible only to IBM employees.

**Comment by contbld** [comment]
<h3>Code analysis and actions</h3>
DO NOT DELETE THIS COMMENT.

- 1 test infrastructure code files were changed.
 - Test failures/errors in the build could be due to these changes.

**Comment by contbld** [comment]
https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=9bbb1268-b285-4ec6-b65c-48bcc06c72fe completed successfully!

**Pull request merged**
