### PR TITLE
Add check for OL product

### PR DESCRIPTION
**Pull request by cbridgha**
Open Liberty should not be logging to use the install Utility - as it is not included.

I'm now checking if using Open Liberty to log appropriate error message for unknown feature.

### CODE REVIEW

**Comment by cbridgha** [comment]
please #build - Thanks!

**Comment by cbridgha** [comment]
#build again

**Comment by cbridgha** [comment]
#build

**Comment by cbridgha** [comment]
#build again

**Comment by cbridgha** [comment]
This is a pretty common re-occurring build break  (245428)

**Comment by ewhoch** [comment]
fixes #154

**Pull request merged**
