### PR TITLE
Pipeline configuration for required copyright header checking

### PR DESCRIPTION
**Pull request by wraschke**
- [x] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [x] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [x] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

This pull request introduces configuration that allows user to trigger a CI Orchestrator-managed Jenkins job, using a LibbyBot directive comment, that will create the required copyright header status check.

Subsequent pull requests will enable prohibited terms, DHE server, and CLA status validations. Those are not required for PR delivery; hence why I am rolling this functionality in stages.

### CODE REVIEW

**Comment by wraschke** [comment]
#libby

**Comment by wraschke** [comment]
!libby

**Comment by wraschke** [comment]
!libby@dev

**Comment by wraschke** [comment]
!libby@dev

**Review by fritze2 — DISMISSED** [review]

**Comment by wraschke** [comment]
!build

**Comment by wraschke** [comment]
!build@dev

**Comment by wraschke** [comment]
!libby@dev

**Comment by wraschke** [comment]
#libby@dev

**Comment by wraschke** [comment]
!libby@dev

**Comment by wraschke** [comment]
!libby

**Review by fritze2 — APPROVED** [review]
LG!

**Comment by wraschke** [comment]
!libby

**Comment by wraschke** [comment]
The above check is proof that this configuration and the required Jenkins code works to achieve the objective.

To test with other PRs that don't have this PR's configuration, I've used https://github.com/OpenLiberty/open-liberty/pull/26558 and https://github.com/OpenLiberty/open-liberty/pull/29668 to exercise the code.

Obviously, commenting in those PRs with the LibbyBot directive won't trigger any pipelines I ran tests with standalone Jenkins jobs to use their data.

**Pull request merged**
