### PR TITLE
third party context providers

### PR DESCRIPTION
**Pull request by njr-11**
Add some initial code to experiment with third-party context providers and a couple of test cases.

### CODE REVIEW

**Comment by njr-11** [comment]
#build

**Comment by njr-11** [comment]
#build
#run-libby-bot

**Comment by njr-11** [comment]
#build

**Comment by njr-11** [comment]
#build

**Comment by njr-11** [comment]
The first 3 builds all failed with the "No more space on device" error, but after applying the workaround to remove the `.im.` build properties, it gets a green build with all tests passing:

https://wasrtc.hursley.ibm.com:9443/jazz/resource/itemOid/com.ibm.team.build.BuildResult/_o2vfwDmcEeygsrM6ShizkA

**Review by jmstephensgit — APPROVED** [review]

**Pull request merged**
