### PR TITLE
fix issue with security re-auth/restore and GRPC

### LINKED ISSUE #28459: GRPC connections hang with security enabled
**Describe the bug**  
With security enabled, GRPC connections intermittently hang and never respond back. This happens due to the mechanism of restore that Security has for re-authenticating a connection which in GRPC is not covered.

**Steps to Reproduce**  
Kick off GRPC connections and wait for a re-authentication to trigger.

**Expected behavior**  
Expect GRPC to not hang with security enabled.

**Diagnostic information:**  
 - OpenLiberty Version: Since GRPC was enabled I believe?
 - Affected feature(s): grpc
 - Java Version: Any
 - server.xml configuration (WITHOUT sensitive information like passwords): grpc enabled xml with ssl
 - If it would be useful, upload the messages.log file found in `$WLP_OUTPUT_DIR/messages.log`

### PR DESCRIPTION
**Pull request by isaacrivriv**
Added change to fix issue with security re-auth/restore and GRPC
fixes #28459

### CODE REVIEW

**Comment by isaacrivriv** [comment]
!build

**Comment by isaacrivriv** [comment]
!build
#spawn.fullfat.buckets=com.ibm.ws.grpc_fat

**Comment by isaacrivriv** [comment]
!build
#spawn.fullfat.buckets=com.ibm.ws.grpc_fat

**Comment by isaacrivriv** [comment]
Good news is that the changes seem to work addressing the issue. It seems related to accumulating data when using oidc for a relogin and continue. Kicking off another build to verify but since all the buckets failed the same way last time I'm confident about this fix

**Comment by isaacrivriv** [comment]
!build
#spawn.fullfat.buckets=com.ibm.ws.grpc_fat

**Review by fritze2 — DISMISSED** [review]
Hi @isaacrivriv, you may want someone who has expertise in this area to review the changes too, but since you need at least one reviewer, I'll approve since it passed in a pipeline.

**Comment by fritze2** [comment]
Would this also address the timeouts in the other two buckets we've seen? I'll run a pipeline to find out tomorrow.
!build
#spawn.fullfat.buckets=com.ibm.ws.grpc_fat,io.openliberty.springboot.fat30_fat,com.ibm.ws.springboot.fat20_fat

**Comment by isaacrivriv** [comment]
Thanks @fritze2! We're working on a review this week with the GRPC experts. Hoping to get this merged in ASAP!

As for the other timeouts, I'm not sure. I haven't looked into the other defects associated with those buckets. This fix is very GRPC specific, so I would not think the springboot buckets use the feature and therefore would probably not be affected by this change.

**Comment by fritze2** [comment]
The pipeline confirmed it has no change in the springboot buckets, and I've found the pause in those buckets that leads to a timeout is tracing to `java.nio.channels.Selector`, so I will try updating to the latest JDK in hopes a bug was patched, and if that doesn't help, then I'll open a defect that we can get help from the springboot devs on.

**Comment by isaacrivriv** [comment]
!build
#spawn.fullfat.buckets=com.ibm.ws.grpc_fat

**Comment by isaacrivriv** [comment]
#libby

**Review by pnicolucci — CHANGES_REQUESTED** [review]
Please update the copyright date range to include 2024. Thanks!

**Comment by pnicolucci** [comment]
@isaacrivriv  we should probably have a release bug issue for this as well.

**Review by pnicolucci — APPROVED** [review]

**Comment by pnicolucci** [comment]
#libby

**Review by mrsaldana — APPROVED** [review]
LGTM

**Comment by isaacrivriv** [comment]
Last change was an update to copyrights and latest build contained all GRPC FATs passing at 100%. Should be safe to merge in

**Pull request merged**
