### PR TITLE
fix error where VirtualThreadOps is intermittently null

### PR DESCRIPTION
**Pull request by njr-11**
Ensure VirtualThreadOps is always available and add a method that can be used to determine whether virtual threads are supported.

### CODE REVIEW

**Comment by njr-11** [comment]
fixes #27339

**Review by KyleAure — DISMISSED** [review]

**Comment by njr-11** [comment]
#build

**Comment by njr-11** [comment]
#build

**Review by KyleAure — APPROVED** [review]

**Comment by njr-11** [comment]
#libby

**Comment by KyleAure** [comment]
Closing duplicate of #28365

**Pull request closed without merging**
