### PR TITLE
Update restfulWS-3.1 to not depend on the servlet-6.0 public feature

### PR DESCRIPTION
**Pull request by jhanders34**
- Change to use an internal feature for servlet function instead of the public one.
- Update auto features that should be enabled still with the private servlet feature enabled.
- Removed dependent features that are brought in already by other features in the dependency tree.
- Add servlet feature to server.xml for JAXRS tests if the test deploys an application that has a servlet in it, so that when repeat is added for EE10, it will still be able to run.

### CODE REVIEW

**Comment by jhanders34** [comment]
#libby #build

**Comment by jhanders34** [comment]
#libby #build

**Comment by jhanders34** [comment]
#libby

**Review by jim-krueger — APPROVED** [review]

**Comment by jhanders34** [comment]
#libby #build

**Review by pmd1nh — APPROVED** [review]

**Pull request merged**
