### PR TITLE
Update package versions for API / SPIs that use Java / Jakarta EE APIs

### LINKED ISSUE #11497: What do to about Liberty API/SPI built on Java EE interfaces/classes
It needs to be determined what the expectations are for the JavaEE/Jakarta transformation tool around IBM API that includes Java EE classes.

For example, a security feature has this API package,
```
IBM-API-Package: com.ibm.wsspi.security.auth.callback; type=“ibm-api”, \
```

A couple of the classes in this package declare interface methods that use JCA spec types as parameters and results types.  For example:
```
/com.ibm.ws.security.jaas.common/src/com/ibm/wsspi/security/auth/callback/WSManagedConnectionFactoryCallback.java
```

and here is some of the content of the class,
```
import javax.resource.spi.ManagedConnectionFactory;
import javax.security.auth.callback.Callback;
...
    public void setManagedConnectionFactory(ManagedConnectionFactory managedConnectionFactory) {
    …
    public ManagedConnectionFactory getManagedConnectionFacotry() {
    …
```

Here’s the public JavaDoc for the above,
https://www.ibm.com/support/knowledgecenter/SS7K4U_liberty/com.ibm.websphere.javadoc.liberty.doc/com.ibm.websphere.appserver.api.security_1.2-javadoc/com/ibm/wsspi/security/auth/callback/WSManagedConnectionFactoryCallback.html

The transformation tool would naturally create two versions of the same API/SPI interface, one in terms of Jakarta EE packages and the other in terms of Java EE packages.  That means there would be two different, conflicting JavaDocs for these two versions of the external API/SPI.  Can processes for externalizing JavaDoc cope with that?  Will it confuse users?  And is it the approach we want to take?

Or, do we need to define new packages or interface names and build in that awareness for all such cases to the transformation tool such that it can convert usage of these API/SPI within customer apps as well as what is strictly Java EE spec usage?  If so, where will we put it /what will we call it so that it does not confuse users? If we did put it in a different package, would we move all of the other classes within that API package as well even if some of them don't have dependencies on Java EE?

What could this look like using the example above?
Java EE:
```
com.ibm.wsspi.security.auth.callback.Constants 	 
com.ibm.wsspi.security.auth.callback.WSAppContextCallback 	
com.ibm.wsspi.security.auth.callback.WSCallbackHandlerFactory 	
com.ibm.wsspi.security.auth.callback.WSManagedConnectionFactoryCallback
com.ibm.wsspi.security.auth.callback.WSMappingCallbackHandler 
com.ibm.wsspi.security.auth.callback.WSMappingPropertiesCallback 
com.ibm.wsspi.security.auth.callback.WSServletRequestCallback 	
com.ibm.wsspi.security.auth.callback.WSServletResponseCallback 	
com.ibm.wsspi.security.auth.callback.WSX509CertificateChainCallback
```
Jakarta if same package:
```
com.ibm.wsspi.security.auth.callback.Constants // has no Java EE dependency
com.ibm.wsspi.security.auth.callback.JakartaAppContextCallback 	
com.ibm.wsspi.security.auth.callback.JakartaCallbackHandlerFactory 	
com.ibm.wsspi.security.auth.callback.JakartaManagedConnectionFactoryCallback
com.ibm.wsspi.security.auth.callback.JakartaMappingCallbackHandler 
com.ibm.wsspi.security.auth.callback.JakartaMappingPropertiesCallback 
com.ibm.wsspi.security.auth.callback.JakartaServletRequestCallback 	
com.ibm.wsspi.security.auth.callback.JakartaServletResponseCallback 	
com.ibm.wsspi.security.auth.callback.JakartaX509CertificateChainCallback
```
* many API/SPI don't use the WS prefix, so that above won't always be so natural
Jakarta if different package:
```
com.ibm.wsspi.security.auth.callback.jakarta.Constants  
com.ibm.wsspi.security.auth.callback.jakarta.WSAppContextCallback 	
com.ibm.wsspi.security.auth.callback.jakarta.WSCallbackHandlerFactory 	
com.ibm.wsspi.security.auth.callback.jakarta.WSManagedConnectionFactoryCallback
com.ibm.wsspi.security.auth.callback.jakarta.WSMappingCallbackHandler 
com.ibm.wsspi.security.auth.callback.jakarta.WSMappingPropertiesCallback 
com.ibm.wsspi.security.auth.callback.jakarta.WSServletRequestCallback 	
com.ibm.wsspi.security.auth.callback.jakarta.WSServletResponseCallback 	
com.ibm.wsspi.security.auth.callback.jakarta.WSX509CertificateChainCallback
```
* should Constants class get copied due to being in the same package? It has no Java EE dependencies of its own

### LINKED ISSUE #18536: JakartaEE: Transformer: Improve package version updates (1 linked issue)
_Output rules for Export/Import package_ https://github.com/eclipse/transformer/issues/20
* **Per tjwatson, defer to post JakartaEE9.**
* Issue #18982

Allow different version updates for different manifest attributes https://github.com/eclipse/transformer/issues/174

_Add class update case for updating package versions_ https://github.com/eclipse/transformer/issues/175
* **Per tjwatson, defer to post JakartaEE9.**
* Issue #18982

Part of Part of: JakartaEE: Deliver Jakarta EE 9
https://github.com/OpenLiberty/open-liberty/issues/9876

### LINKED ISSUE #18900: JakartaEE: Transformer: Update dependency to version 0.3.0.20211005
Obtained from:
https://oss.sonatype.org/content/repositories/snapshots/org/eclipse/transformer/

https://oss.sonatype.org/content/repositories/snapshots/org/eclipse/transformer/org.eclipse.transformer.cli/0.3.0-SNAPSHOT/org.eclipse.transformer.cli-0.3.0-20211005.203813-23.jar
https://oss.sonatype.org/content/repositories/snapshots/org/eclipse/transformer/org.eclipse.transformer/0.3.0-SNAPSHOT/org.eclipse.transformer-0.3.0-20211005.203813-22.jar

### PR DESCRIPTION
**Pull request by jhanders34**
- For APIs and SPIs that include Java EE / Jakarta EE APIs, update package versions to 10.0.

Fixes #18900 
Fixes #11497

### CODE REVIEW

**Comment by jhanders34** [comment]
#build

**Comment by jhanders34** [comment]
#libby #build

**Comment by jhanders34** [comment]
#libby #build

**Review by jgrassel — APPROVED** [review]

**Review by tbitonti — COMMENTED** [review]
Looks good to me.

**Pull request merged**
