### PR TITLE
Create a UDP connection using the selected outbound interface

### LINKED ISSUE #15975: Create a UDP connection using the selected outbound interface

### PR DESCRIPTION
**Pull request by annaguri**
fixes #15975

### CODE REVIEW

**Comment by annaguri** [comment]
#run-libby-bot

**Comment by annaguri** [comment]
#build

**Comment by annaguri** [comment]
#build

**Comment by annaguri** [comment]
#build

**Comment by annaguri** [comment]
#run-libby-bot

**Comment by annaguri** [comment]
#build

**Review by TiborBeres — APPROVED** [review]
Looks good

**Pull request merged**
