### PR TITLE
4455 product utility refactor

### PR DESCRIPTION
**Pull request by mswatosh**
Removing JAXB usage

### CODE REVIEW

**Comment by mswatosh** [comment]
#build

**Comment by mswatosh** [comment]
#build

**Comment by mswatosh** [comment]
#build

**Comment by alvinso** [comment]
@mswatosh are you planning to remove JAXB from other projects?

**Comment by aguibert** [comment]
@alvinso yes, we want to minimize our dependency on JAX-B where we can, since it will no longer be provided by the JDK and it's a rather heavy dependency to pull in on its own (3.4MB).
I've already taken a pass at other components in this PR: https://github.com/OpenLiberty/open-liberty/pull/4482
I'm not planning to do any further removal beyond this PR and #4482 though.

**Pull request merged**
