### PR TITLE
Move Manifest processing to container instead of entry

### PR DESCRIPTION
**Pull request by jhanders34**
- Update to move the MANIFEST.MF file processing and caching from the class level of the container level.
- This change reduces the amount of times we read the same MANIFEST file for the same container in the application classloader.

### CODE REVIEW

**Comment by jhanders34** [comment]
#libby #build

**Comment by jhanders34** [comment]
#libby #build

**Review by andymc12 — APPROVED** [review]
Changes LGTM, though it might be good to have a unit test to ensure that the manifest is only processed once.

**Comment by jhanders34** [comment]
#libby #build

**Comment by jhanders34** [comment]
#build

**Review by jaridk — APPROVED** [review]

**Comment by jhanders34** [comment]
#build

**Comment by jhanders34** [comment]
I reran the failing test with a rebuild of the child build with just the one test bucket in it and it passed.  As such I am merging this PR.

**Pull request merged**
