### PR TITLE
Add remaining websocket tests

### LINKED ISSUE #12870: Port over remaining Websocket tests from CL to OL
Take a look at the tests that weren't moved over to OL and compare to see which are tied to CL specific classes and can't be moved over to leave as they are. Figure out which tests to move over and which to leave

### PR DESCRIPTION
**Pull request by isaacrivriv**
fixes #12870

### CODE REVIEW

**Comment by isaacrivriv** [comment]
#build

**Comment by isaacrivriv** [comment]
#build

**Comment by isaacrivriv** [comment]
#run-libby-bot

**Review by billw1024 — APPROVED** [review]
awesome job, thanks for doing it.

**Review by pnicolucci — APPROVED** [review]

**Pull request merged**
