### PR TITLE
Integrate JPA 3.1 FAT

### PR DESCRIPTION
**Pull request by jgrassel**
Integrate the JPA 3.1 FAT, update Eclipselink 4.0 (for JPA 3.1) to 202d992, in order to pass many of the new tests.

Several tests have been disabled due to ongoing issues in Eclipselink 4.0, these issues are:

https://github.com/eclipse-ee4j/eclipselink/issues/1535
https://github.com/eclipse-ee4j/eclipselink/issues/1539
https://github.com/eclipse-ee4j/eclipselink/issues/1540
https://github.com/eclipse-ee4j/eclipselink/issues/1544
https://github.com/eclipse-ee4j/eclipselink/issues/1572
https://github.com/eclipse-ee4j/eclipselink/issues/1573
https://github.com/eclipse-ee4j/eclipselink/issues/1574
https://github.com/eclipse-ee4j/eclipselink/issues/1575

for #18738

### CODE REVIEW

**Comment by jgrassel** [comment]
#build

**Comment by jgrassel** [comment]
#build

**Comment by jgrassel** [comment]
#build

**Comment by jgrassel** [comment]
#build

**Comment by jgrassel** [comment]
#build

**Comment by jgrassel** [comment]
@jhanders34 I had to add jsonp-2.1 to the jpa-3.1 and persistence service features, because Eclipselink now has a hard dependency on jakarta.json, due to the addition of a new (non-spec) feature which supports JSON types as first-class persistent capable types (vs generic serializable objects).  Looking to see if there's any room to further reduce the added dependency as adding it as a feature feels quite heavy.

**Comment by jgrassel** [comment]
#run-libby-bot
#build

**Comment by jgrassel** [comment]
#build kicking off a new build, build system ran out of space.

**Comment by jgrassel** [comment]
#build

**Comment by jgrassel** [comment]
#build

**Review by tkburroughs — APPROVED** [review]
Since you are using the JakartaEE10Action repeat action, that already sets the minimum java level to 11.... approving.

**Comment by jgrassel** [comment]
#run-libby-bot

**Review by tkburroughs — APPROVED** [review]

**Comment by jgrassel** [comment]
#run-libby-bot  DHE files published

**Pull request merged**
