### PR TITLE
Fix memory leak in CXF caused by large number of PidInfo objects: Issue  27294

### PR DESCRIPTION
**Pull request by sawadood**
Fixes issue #27294

### CODE REVIEW

**Comment by sawadood** [comment]
#build Let's start a PB

**Review by neuwerk — DISMISSED** [review]
LGTM! Thanks Syed.

**Comment by sawadood** [comment]
#build run PB after Copyright update

**Review by BerksanAtes — APPROVED** [review]
Looks good to me!

**Comment by BerksanAtes** [comment]
#run-libby-bot

**Pull request merged**
