### PR TITLE
Discoverable embedded pom's

### PR DESCRIPTION
**Pull request by cbridgha**
Work to embed oss dependencies in our runtime jars - easier to scan our individual packaged images for full inventory.

### CODE REVIEW

**Comment by cbridgha** [comment]
#build

**Comment by cbridgha** [comment]
#build

**Comment by cbridgha** [comment]
#pbbeta

**Comment by cbridgha** [comment]
#pbbeta

**Comment by cbridgha** [comment]
@pb

**Comment by cbridgha** [comment]
#pb

**Comment by cbridgha** [comment]
#build

**Comment by cbridgha** [comment]
#pb

**Comment by cbridgha** [comment]
#build

**Comment by cbridgha** [comment]
#pb

**Comment by cbridgha** [comment]
Latest good build: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_WFjPoLj_Ee2r6re_Zvbagg

**Comment by cbridgha** [comment]
#libby

**Review by hlhoots — APPROVED** [review]
LGTM

**Review by fritze2 — APPROVED** [review]

**Pull request merged**
