### PR TITLE
get status from HttpServletRequest when not an instance of IExtendedResponse

### LINKED ISSUE #24691: wrong status code returned from JASPI when response not an instance of IExtendedResponse
wrong status code returned from `JASPI` when response not an instance of `IExtendedResponse`.
this situation occurs when using `restfulWS-3.1` and a default status code of 500 is returned.

instead of returning 500 when it is not an instance of `IExtendedResponse`, we should just return the status from `HttpServletResponse#getStatus`:
https://github.com/OpenLiberty/open-liberty/blob/7e0db08687847952649d33a5bea24a0586663fc0/dev/com.ibm.ws.security.jaspic/src/com/ibm/ws/security/jaspi/JaspiServiceImpl.java#L689-L694

### PR DESCRIPTION
**Pull request by jimmy1wu**
fixes #24691

### CODE REVIEW

**Comment by jimmy1wu** [comment]
#build

**Comment by jimmy1wu** [comment]
#build

**Comment by jimmy1wu** [comment]
#build

**Review by teddyjtorres — DISMISSED** [review]

**Comment by jimmy1wu** [comment]
#libby
#build

**Review by teddyjtorres — APPROVED** [review]

**Comment by jimmy1wu** [comment]
#spawn.fullfat.buckets=io.openliberty.security.jakartasec.3.0.internal_fat,io.openliberty.security.jakartasec.3.0.internal_fat.config,io.openliberty.security.jakartasec.3.0.internal_fat.config.1,io.openliberty.security.jakartasec.3.0.internal_fat.config.2,io.openliberty.security.jakartasec.3.0.internal_fat.logout,io.openliberty.security.jakartasec.3.0.internal_fat.refresh

**Comment by jimmy1wu** [comment]
#build
#spawn.fullfat.buckets=io.openliberty.security.jakartasec.3.0.internal_fat,io.openliberty.security.jakartasec.3.0.internal_fat.config,io.openliberty.security.jakartasec.3.0.internal_fat.config.1,io.openliberty.security.jakartasec.3.0.internal_fat.config.2,io.openliberty.security.jakartasec.3.0.internal_fat.logout,io.openliberty.security.jakartasec.3.0.internal_fat.refresh

**Pull request merged**
