### PR TITLE
Add multi-provider testing to JPA com.ibm.ws.jpa.tests.spec10.entity_fat

### PR DESCRIPTION
**Pull request by dazey3**
for #19616

Signed-off-by: Will Dazey <dazeydev.3@gmail.com>

### CODE REVIEW

**Comment by dazey3** [comment]
#run-libby-bot

**Comment by dazey3** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jpa.tests.spec10.entity_jpa_2.0_fat,com.ibm.ws.jpa.tests.spec10.entity_jpa_2.1_fat,com.ibm.ws.jpa.tests.spec10.entity_jpa_2.2_fat,com.ibm.ws.jpa.tests.spec10.entity_jpa_3.0_fat

**Review by jgrassel — APPROVED** [review]
lgtm

**Comment by dazey3** [comment]
#run-libby-bot

**Pull request merged**
