### PR TITLE
Additional updates to gradle files for Gradle 8 possible removes

### PR DESCRIPTION
**Pull request by jhanders34**
- Update dependencies to remove warnings about dependencies not being specified.
- Add ignoreEmptyDirectories() calls with skipWhenEmpty() for change of behavior in gradle 8.
- Update dependencies between wlp.lib.extract and build.image to remove dependency warnings

This PR addresses gradle deprecation warning that were not addressed in #25882

### CODE REVIEW

**Comment by jhanders34** [comment]
#build

**Comment by jhanders34** [comment]
#libby #build

**Comment by jhanders34** [comment]
#libby

**Review by njr-11 — APPROVED** [review]

**Review by neuwerk — APPROVED** [review]
LGTM! Thanks!

**Review by pnicolucci — APPROVED** [review]

**Review by fritze2 — APPROVED** [review]

**Review by cbridgha — APPROVED** [review]
Looks good

**Pull request merged**
