### PR TITLE
fix featureManager classpath bug

### PR DESCRIPTION
**Pull request by jjiwooLim**
Issue

featureManager classpath --features=jpaContainer-2.2
should include  `com.ibm.websphere.javaee.persistence.2.2_1.0.62.jar` classpath which is a dependent jar for "cdi-2.0" and "jpaContainer-2.2".

The resolver returned some dependent features (ex. jpaContainer-2.2) with IBM short name, but classpath map only contained symbolic names. (line 268 `FeatureInfo childFeatureInfo = allowedFeatures.get(name);`) 

Adding symbolic name to the map fixes this issue.

### CODE REVIEW

**Comment by jjiwooLim** [comment]
#build

**Review by bensonlatibm — APPROVED** [review]
lgtm!

**Comment by jjiwooLim** [comment]
#libby-bot

**Comment by jjiwooLim** [comment]
updated copyright header

**Pull request merged**
