### PR TITLE
enforce limits on configured duration values

### PR DESCRIPTION
**Pull request by njr-11**
Enforce upper/lower limits on various configured duration values (missedTaskThreshold, pollInterval, retryInterval) when fail over is enabled to help ensure the user is running with reasonable values.  Translatable message will be added in a separate pull, once this part is reviewed and working.

### CODE REVIEW

**Comment by njr-11** [comment]
An id review is not needed because that was done under 10284.  This pull has a couple of the same commits because 10284 hasn't been able to deliver yet.

**Comment by njr-11** [comment]
#build

**Comment by njr-11** [comment]
#build
#run-libby-bot

**Comment by skasund** [comment]
L2 message review not required

**Pull request merged**
