### PR TITLE
update Netty dependencies to 4.1.66

### LINKED ISSUE #17912: Bump netty dependencies to 4.1.66.Final
Pull in the new Netty 4.1.66 release (updating from 4.1.62) which has many bug fixes and improvements: https://netty.io/news/2021/07/16/4-1-66-Final.html

### PR DESCRIPTION
**Pull request by wtlucy**
Fixes #17912

Note: this new version [1] adds support for new compression algorithms, `zstd` and `Brotli`. For our purposes we don't currently need this new functionality, so I'll exclude the new packages that were added from our Netty bundles. 

[1] https://netty.io/news/2021/07/16/4-1-66-Final.html

### CODE REVIEW

**Comment by wtlucy** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.grpc_fat

**Review by annaguri — APPROVED** [review]
Looks good to me

**Review by hutchig — APPROVED** [review]
Looks fine to me.

**Comment by wtlucy** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.grpc_fat

**Comment by wtlucy** [comment]
unrelated build problems, trying again after a rebase: #build #spawn.fullfat.buckets=com.ibm.ws.grpc_fat

**Comment by wtlucy** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.grpc_fat

**Comment by wtlucy** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.grpc_fat

**Comment by wtlucy** [comment]
more build timeouts!? #build #spawn.fullfat.buckets=com.ibm.ws.grpc_fat

**Comment by wtlucy** [comment]
#run-libby-bot

**Pull request merged**
