### PR TITLE
Enable client configuration via server.xml for Jakarta REST 3.0 clients

### PR DESCRIPTION
**Pull request by andymc12**
Includes runtime code, new 3.0-specific messages, and FAT tests.

Part of Epic issue #11803.

### CODE REVIEW

**Comment by andymc12** [comment]
#build

**Comment by skasund** [comment]
L2 message review completed

**Comment by andymc12** [comment]
2 JAX-RS tests failed due to these changes.  I've resolved them (locally, at least) - new #build

**Review by helyarp — COMMENTED** [review]
Looks good!

**Comment by andymc12** [comment]
#build

**Comment by andymc12** [comment]
rebased... new #build

**Review by WhiteCat22 — APPROVED** [review]

**Comment by andymc12** [comment]
Failure occurs in over 1400 builds and is not related to these changes. #libby

**Pull request merged**
