### PR TITLE
Ol versionless flip to ga

### PR DESCRIPTION
**Pull request by cbridgha**

### CODE REVIEW

**Comment by cbridgha** [comment]
#build

**Comment by cbridgha** [comment]
#build

**Comment by cbridgha** [comment]
#build

**Comment by cbridgha** [comment]
https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_trwlIEdkEe-Hn-AxXEWsJg

**Review by tbitonti — DISMISSED** [review]
Not sure about the change from java8 to java11.
Also, with these changes, can beta features be tested?  Should the GA restriction include a beta check?
Otherwise, looks fine.

**Comment by cbridgha** [comment]
Flipped test compile back to Java 8

**Comment by cbridgha** [comment]
New build: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_8dEEAEdpEe-Hn-AxXEWsJg

**Review by rsherget — APPROVED** [review]
LGTM

**Comment by cbridgha** [comment]
This build has two buckets that are known intermittent errors....  not related to versionless as far as I can see...   https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_8dEEAEdpEe-Hn-AxXEWsJg&tab=com.ibm.team.build.web.ui.internal.editors.result.properties.PropertiesProvider

**Comment by cbridgha** [comment]
#libby

**Pull request merged**
