### PR TITLE
Updated tracing for netty unittests

### PR DESCRIPTION
**Pull request by isaacrivriv**
for #25809
Adding a way to be able to view traces in builds by pushing all output tracing to the console

### CODE REVIEW

**Comment by isaacrivriv** [comment]
#build

**Review by websterc87 — CHANGES_REQUESTED** [review]
Would recommend the gradle portion of this is not delivered as the logs are already available in open-liberty.unitTest.results.zip. See Discussion in LibertyOps

**Comment by isaacrivriv** [comment]
#build

**Comment by isaacrivriv** [comment]
#build

**Comment by isaacrivriv** [comment]
#libby

**Review by hutchig — APPROVED** [review]
LGTM!

**Review by websterc87 — APPROVED** [review]
LGTM

**Pull request merged**
