### PR TITLE
Resubmit update to Weld 5.1.1 but use SP1 instead of Final

### PR DESCRIPTION
**Pull request by benjamin-confino**
A test failure was burred behind ant going into an infinite recursive loop. Fortunately someone else had a problem from the same weld change, submitted a bug report, and weld SP1 was released to revert that change. Therefore we will update to 5.1.1.SP1 instead of final.

### CODE REVIEW

**Comment by benjamin-confino** [comment]
#build

**Comment by benjamin-confino** [comment]
Build has not yet started

**Comment by Azquelt** [comment]
Includes the reverted changes from #25572 and #25676

**Comment by benjamin-confino** [comment]
#libby

**Review by Azquelt — APPROVED** [review]

**Comment by benjamin-confino** [comment]
Previous build failed because artifacts needed uploading.

**Comment by benjamin-confino** [comment]
#build

**Pull request merged**
