### PR TITLE
update bcprov lib to 1.78.1

### PR DESCRIPTION
**Pull request by jjiwooLim**
Update bc prov for featureUtility.
bcpg package now has dependency on bcutil package and had to be added.

### CODE REVIEW

**Comment by jjiwooLim** [comment]
#build

**Comment by jjiwooLim** [comment]
#build

**Comment by jjiwooLim** [comment]
#build

**Comment by jjiwooLim** [comment]
https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_AnNGkBIfEe-GLt3IcvbSMw&tab=com.ibm.team.build.web.ui.internal.editors.result.overview.OverviewPage

**Comment by jjiwooLim** [comment]
Test failures are unrelated to my changes.

**Comment by jjiwooLim** [comment]
#libbybot

**Review by bensonlatibm — APPROVED** [review]
LGTM!

**Pull request merged**
