### PR TITLE
check only public features when running baseline tests

### PR DESCRIPTION
**Pull request by rsherget**
- [x] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [x] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [x] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

filter feature sets to only contain public features. Remove any code checking specifically for non-public features

### CODE REVIEW

**Comment by rsherget** [comment]
#29289

**Review by hlhoots — APPROVED** [review]
LGTM

**Comment by rsherget** [comment]
#build

**Comment by rsherget** [comment]
build has 1 failure, its a known error. Merging

**Pull request merged**
