### PR TITLE
Add Expression Language 6.0 Array length FAT

### LINKED ISSUE #25602: Expression Language 6.0: Add support for a new property, `length`, for arrays.
Spec issue: `https://github.com/jakartaee/expression-language/issues/175`

### PR DESCRIPTION
**Pull request by pnicolucci**
fixes #25602

### CODE REVIEW

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Review by volosied — APPROVED** [review]
Looks straightforward.

**Comment by pnicolucci** [comment]
#libby

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#libby

**Pull request merged**
