### PR TITLE
preventing NPE when uninstalling iFixes on Windows

### LINKED ISSUE #21593: NPE hit on Windows Liberty updates
Salesforce case:TS009680209 

Liberty update from 21.0.0.12 to 22.0.0.6 causes an NPE. Workaround is to uninstall all ifixes first before update. Need to fix install.jar logic to prevent NPE. 

**Steps to Reproduce**  
Install 21.0.0.12 with all suggested ifixes then attempt a IM update to 22.0.0.6. Update will fail. 

**Expected behavior**  
Update should complete successfully. 

**Diagnostic information:**  
 - OpenLiberty Version: [e.g. 21.0.0.12 - 22.0.0.6]
 - Liberty IM installations

### PR DESCRIPTION
**Pull request by jacobwdv**
fixes https://github.com/OpenLiberty/open-liberty/issues/21593

### CODE REVIEW

**Comment by jacobwdv** [comment]
#build

**Comment by jacobwdv** [comment]
#build

**Comment by jacobwdv** [comment]
#build

**Review by bensonlatibm — APPROVED** [review]
lgtm!

**Comment by jacobwdv** [comment]
As per https://cognitive.hursley.ibm.com/buildAnalysis.html?uuid=_u2bO4PxrEey3m9ea3wJj4A , the only failures have already been accounted for and should not be related to my changes. 

image

**Comment by jacobwdv** [comment]
#libby-bot

**Pull request merged**
