### PR TITLE
Jakarta EE 10 features with EE 9 content

### PR DESCRIPTION
**Pull request by jhanders34**
- Creates Jakarta EE 10 features with the same content as the Jakarta EE 9 previous version
- Updates EE 9 features that are not changed for EE 10 to work with the EE10 features as a tolerated feature version
- Update auto features to include the EE10 features in addition to the EE 9 ones
- Update value add features to tolerate EE10
- Change eeCompatible-1.0 feature to depend on a bundle that requires Java 11 to force all features used with EE10 to require Java 11
- Update JakartaEE10Action to include the new feature versions and require a minimum of Java 11
- Update FeatureManager to recognize Jakarta EE 10

### CODE REVIEW

**Comment by jhanders34** [comment]
#build

**Review by tevans78 — APPROVED** [review]
I checked CDI, convienience features and Java 11 commits ... all look good

**Review by helyarp — COMMENTED** [review]
English properties files look fine. Adding ID reviewed label.

**Review by mbroz2 — APPROVED** [review]

**Comment by jhanders34** [comment]
#build

**Comment by jhanders34** [comment]
#libby #build

**Comment by jhanders34** [comment]
#build

**Comment by jhanders34** [comment]
#build

**Comment by jhanders34** [comment]
#libby

**Comment by jhanders34** [comment]
#libby

**Pull request merged**
