### PR TITLE
Revert "#1441 Merge JTS into BTS and format events at handlers"

### PR DESCRIPTION
**Pull request by ewhoch**
Reverts OpenLiberty/open-liberty#2167

Under analysis, there is a 3x increase in the time it takes to run a logstash test. In combination with that, that's very close to when we have had some significant performance problems. I see the increase first on a PB, and I have strong suspicion it's this change in what looks like a frequently called method:

https://github.com/Yushan-Lin/open-liberty/commit/61af83f398d44620dde852525c4e1a0c62cec921#diff-473301b347975121e93d7d564e6abaf7

### CODE REVIEW

**Comment by ewhoch** [comment]
#build

**Comment by ewhoch** [comment]
Confirmed this causes a 3x increase in logstash.collector FATs, mainly due to timeouts looking for "TRAS0218I"

In isolation, this would be OK, but seeing how it's coincident with seeing some significant performance instability, i'm moving this PR out of the stream until we can do some more analysis on it. I'm very concerned with the new object create during array copy for what I think may be every logging event.

**Comment by ewhoch** [comment]
reopens #1441 and #1449

**Comment by fmhwong** [comment]
@ewhoch Do you have links to the builds that it was timed out looking for "TRAS0218I"?

**Comment by ewhoch** [comment]
look at any build where it ran for 30+ minutes, literally any of them.

**Pull request merged**
