### PR TITLE
Update swagger UI to latest 3.x

### PR DESCRIPTION
**Pull request by Azquelt**

### CODE REVIEW

**Comment by Azquelt** [comment]
#build

**Comment by Azquelt** [comment]
#libby
#build

**Comment by Azquelt** [comment]
#build

**Comment by Azquelt** [comment]
#build

**Comment by Azquelt** [comment]
#build

**Comment by Azquelt** [comment]
#libby

**Review by tevans78 — APPROVED** [review]

**Comment by Azquelt** [comment]
Testing was conducted manually using the following test plan:

# Test Procedure
 - deploy the test application and configuration
## Check our Customizations
### For the MicroProfile UI
 - Open in your browser: https://localhost:9443/openapi/ui/
 - Hold Shift and click the reload button to ensure that all resources are reloaded
 - Check the liberty logo is at the top
 - Check there is no filter bar
 - Check the top of the page has the title and description but not any links
 - Check the colour for the OAS badge next to the title
   - This is subtle, it should be #5d8203 (original is #89bf04)
 - Check the footer is present and has links for TOS, author website, author e-mail, license
 - Check there is no validation button in the footer
 - Check the colours for GET, POST, PUT and DELETE operations
### For the openapi-3.x UI
 - Open in your browser: https://localhost:9443/api/explorer/
 - Hold Shift and click the reload button to ensure that all resources are reloaded
 - Check the liberty logo is at the top
 - Check the filter bar is present
   - Check that filtering for openapi-test-app (or any prefix) works
   - Check that filtering for anything else gives no operations
 - Check that the top of the page has "Liberty REST APIs"
 - Check the OAS badge colour
 - Check there is no validation button in the footer
 - Check the colours for GET, POST, PUT and DELETE operations
## Check basic functionality
 - Repeat this for both the MicroProfile UI and the openapi-3.x UI
 - In the severs drop-down, select the https server
   - Your browser may not let you make requests to an http server from an https page
 - Open `GET /{id}` operation
   - Check that there are two responses (200 and 404)
   - Check that there are two media types for a 200 response
   - Check that when you change the media type drop down, the example below changes
   - Check that you can switch between the Example Value and Schema
   - Click "Try it out" and retrieve id 1
   - Retrieve id 0 and check that you get a 404
 - Open `POST /private` operation
   - Check that the bar has an unlocked padlock icon on the right
   - Execute the method using Try it out
   - Check that you get a 401 or 403 response
 - Click Authorize at the top of the page and login with oauth
   - For the oauth login, it's important that you use https is used to access the UI and that the hostname is "localhost"
   - For the openapi-3.x UI, use clientid: openapi-ui, secret: abc
   - For the MicroProfile UI, use clientid: mp-ui, secret: abc
   - Select the "test" scope
   - Click "authorize" (this should open a new page with a login box)
   - log in with testuser/testpassword
   - click "allow once"
   - you should now be logged in 
     - an Auth Warning message may be displayed saying that "Authorization may be unsafe", this is an existing issue
   - Click close
 - Check that `POST /private` now has a locked padlock icon
   - Execute the method using Try it out
   - This time it should succeed with a 200 response
 - Open the `GET /apiKeyNeeded` operation
   - Check that the bar has an unlocked padlock icon on the right
   - Check that the description for the operation is "Get a random record"
   - Execute the method using Try it out
   - Check that you get a 403 response code
 - Click Authorize at the top of the page
   - Under apikey enter "12345"
   - you should now be logged in
   - Click close
 - Check that `GET /apiKeyNeeded` now has a locked padlock icon
   - Execute the method using Try it out
   - This time it should succeed with a 200 response

**Pull request merged**
