### PR TITLE
Clear the queue under a separate transaction.

### PR DESCRIPTION
**Pull request by AndrewDJBanks**

### CODE REVIEW

**Comment by AndrewDJBanks** [comment]
#fixes 16599

**Comment by AndrewDJBanks** [comment]
#build

**Comment by AndrewDJBanks** [comment]
#build

**Comment by AndrewDJBanks** [comment]
#libbybot

**Comment by AndrewDJBanks** [comment]
#build

**Review by sakerl — APPROVED** [review]

**Pull request merged**
