### PR TITLE
Re-delivery of the Viewer role

### PR DESCRIPTION
**Pull request by barecode**
After resolving some underlying test issues which were not caught in the initial delivery with of this change  #5102, re-introducing this change with the corresponding test fix.

### CODE REVIEW

**Comment by barecode** [comment]
#build

**Comment by bsbyrd1** [comment]
No comments. .nlsprops updates look good!

**Comment by barecode** [comment]
#build 
New build, rebased to master after the weekend of build problems (caused by me!)

**Comment by barecode** [comment]
Build with all tests enabled (UI on)

**Comment by barecode** [comment]
This should be good to merge, as multiple builds have no overlapping failures (therefore no hard failures introduced by this).

**Pull request merged**
