### PR TITLE
Create prototype MP Config 2.0 based on SmallRye

### PR DESCRIPTION
**Pull request by tevans78**
#build 
This is just a prototype, an experiment

### CODE REVIEW

**Comment by dmuelle** [comment]
Hi @tevans78 - does this prototype require ID review?

**Comment by tevans78** [comment]
> Hi @tevans78 - does this prototype require ID review?

@dmuelle not yet... at some point there will be a proper MP Config 2.0 feature that will need ID

**Comment by dmuelle** [comment]
@tevans78 ok thanks- adding the ID review not needed label so others will know, feel free to remove if needed

**Comment by skasund** [comment]
L2 message review not required

**Comment by tevans78** [comment]
#build

**Pull request closed without merging**
