### PR TITLE
OIDC: Remove possible space from ID of buttons on clientManagement table.

### PR DESCRIPTION
**Pull request by dmorgant**
Since the customer can create their own client IDs when registering an OAuth Client on the Client Management application then the ID may include a space.   The ID is used in assigning a unique ID to the buttons in the table of the clientManagement application.   Change the spaces to '__' so spaces do not appear in the ID.  Blanks are not valid in IDs for html elements.

Also updated the 'Delete' button name on the users token management application from 'Edit_*' to 'Delete_*'.

### CODE REVIEW

**Comment by dmorgant** [comment]
fixes #8705

**Comment by dmorgant** [comment]
#build

**Comment by dmorgant** [comment]
#build

**Comment by dmorgant** [comment]
#build

**Comment by amyreit** [comment]
This build used this branch from OL and the CL branch for 18314-buttonID - we are ready for a combined build.

https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_4KECUNC_Eemo7shcvMe-cQ&tab=com.ibm.team.build.web.ui.internal.editors.result.test.TestProvider

**Pull request merged**
