### PR TITLE
Rename webprofile to io.openliberty

### PR DESCRIPTION
**Pull request by cbridgha**

### CODE REVIEW

**Comment by cbridgha** [comment]
#build

**Comment by dmuelle** [comment]
File flagged for ID review is a file name change only- added the `ID review not needed` label. Let me know if that's incorrect. Thanks

**Comment by andrea-pichler** [comment]
No message review requested from L2

**Review by jimblye — APPROVED** [review]

**Comment by cbridgha** [comment]
#libby

**Pull request merged**
