### PR TITLE
Jakarta Security Identity Store FAT 

### LINKED ISSUE #21170: Security 3.0: FAT: When OidcHttpAuthenticationMechanism uses Liberty's IdentityStoreHandler, application provided IdentityStore(s) will also get invoked
Task: Create FATs to ensure that when OidcHttpAuthenticationMechanism uses Liberty's IdentityStoreHandler, application provided IdentityStore(s) will also get invoked.

Spec section: https://github.com/jakartaee/security/blob/master/spec/src/main/asciidoc/authenticationMechanism.adoc#caller-name-and-groups

> A public OpenID Connect Provider generally has no knowledge about roles or groups an end-user (caller) has in a client application (relying party), but a (private) OpenID Connect Provider operated by the same organisation may have. Therefore this specification allows groups to be provided by the client application or by the OpenID Connect Provider (or both).

> Groups can be provided by the client application by means of an extra identity store with the validationTypes method returning PROVIDE_GROUPS. Groups can be provided by the OpenID Connect Provider by means of additional claims.

### PR DESCRIPTION
**Pull request by c00crane**
Add a few tests to validate security behavior with an App provided Identity Store 

Resolves #21170

### CODE REVIEW

**Comment by c00crane** [comment]
#build

**Comment by c00crane** [comment]
#build

**Comment by c00crane** [comment]
#libby
#build

**Comment by c00crane** [comment]
#libby
#build

**Comment by c00crane** [comment]
#libby
#build

**Review by teddyjtorres — APPROVED** [review]

**Pull request merged**
