### PR TITLE
Add mp 7 repeats to Checkpoint  FATS

### PR DESCRIPTION
**Pull request by Yas-Franco**
- [x] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [x] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [x] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

################################################################################################

As part of https://github.com/OpenLiberty/open-liberty/issues/29005

### CODE REVIEW

**Comment by Yas-Franco** [comment]
#build 
#libby

**Comment by Yas-Franco** [comment]
#build

**Comment by Yas-Franco** [comment]
#build

**Comment by Yas-Franco** [comment]
#build

**Comment by anjumfatima90** [comment]
Instant On build was green: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_H_R7YHHaEe-0ZL4JeBVc2g&tab=com.ibm.team.build.web.ui.internal.editors.result.test.TestProvider

Pipeline build fails intermittently with timeout errors with servers being LEAKED and not being restored properly. @yasmin-aumeeruddy suggested this could be because the FAT is too big and would need to split the FAT.

Merging the PR for now. Splitting the FAT can be done in a separate PR.

#libby

**Review by anjumfatima90 — APPROVED** [review]

**Pull request merged**
