### PR TITLE
Replace @-char in cached lib container path

### PR DESCRIPTION
**Pull request by dazavala**
- [x] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [x] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [x] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

################################################################################################

Replace the `@`-char in cached library container paths to obviate any question of security vulnerability.

### CODE REVIEW

**Comment by dazavala** [comment]
#build

**Comment by dazavala** [comment]
@tjwatson Testing looks good at this point.  My only concern is whether `_` is the best choice for this path delimiter.  Cached library container paths will now appear as, e.g. `.../libcont/DB2JCC4Lib_3_db2jcc4.jar` rather than `.../libcont/DB2JCC4Lib_3@db2jcc4.jar`.

**Review by tjwatson — APPROVED** [review]
> My only concern is whether _ is the best choice

I'm sure we can debate the character choice for a while.  But we already know `_` is "safe" and this file name is completely internal so I don't think we need to worry too much about what the file name looks like.  I am fine with `_` as the character.

**Comment by dazavala** [comment]
@tjwatson Thanks.  Let's see how this works out.

**Pull request merged**
