### PR TITLE
19764 ee10 alt

### PR DESCRIPTION
**Pull request by tbitonti**
Alternate pull request for issue #19764.  This PR uses the original model APIs, and adjusts the implementation and tests accordingly.

### CODE REVIEW

**Comment by tbitonti** [comment]
#build

**Comment by tbitonti** [comment]
#build

**Comment by tbitonti** [comment]
#build

**Comment by tbitonti** [comment]
#build

**Review by jhanders34 — APPROVED** [review]

**Comment by jhanders34** [comment]
#libby

**Comment by tbitonti** [comment]
Unit test updates:

open-liberty/dev/com.ibm.ws.javaee.ddmodel/test/

* com.ibm.ws.javaee.ddmodel.app.AppTest
  * testApp()
* com.ibm.ws.javaee.ddmodel.app.AppHeaderTest
  * testApp90VersionOnly()
  * testApp90NamespaceOnlyAt90()
  * testApp90NamespaceOnlyAt100()
  * testApp100VersionOnly()
* com.ibm.ws.javaee.ddmodel.client.AppClientTest
  * testAppClient()
* com.ibm.ws.javaee.ddmodel.client.AppClientHeaderTest
  * testAppClient90VersionOnlyAt90()
  * testAppClient90VersionOnlyAt100()
  * testAppClient90NamespaceOnlyAt90()
  * testAppClient90NamespaceOnlyAt100()
  * testAppClient100VersionOnlyAt100()
* com.ibm.ws.javaee.ddmodel.ejb.EJBJarInterceptorTest
  * testEE10InterceptorsEJB32()
  * testEE10InterceptorsEJB40()
  * testEE10InterceptorsEJB50()
* com.ibm.ws.javaee.ddmodel.ejb.EJBJarTest
  * testGetVersionID()
* com.ibm.ws.javaee.ddmodel.web.WebAppTest 
  * testWebApp()
  * testEE10ContextServiceWeb31()
  * testEE10ManagedExecutorWeb31()
  * testEE10ManagedScheduledExecutorWeb31()
  * testEE10ManagedThreadFactoryWeb31()
  * testEE10ContextServiceWeb50()
  * testEE10ManagedExecutorWeb50()
  * testEE10ManagedScheduledExecutorWeb50()
  * testEE10ManagedThreadFactoryWeb50()
  * testEE10ContextServiceWeb60()
  * testEE10ManagedExecutorWeb60()
  * testEE10ManagedScheduledExecutorWeb60()
  * testEE10ManagedThreadFactoryWeb60()
* WebFragmentTest
  * testWebFragment()
  * testEE10ContextServiceWebFragment31()
  * testEE10ManagedExecutorWebFragment31()
  * testEE10ManagedScheduledExecutorWebFragment31()
  * testEE10ManagedThreadFactoryWebFragment31()
  * testEE10ContextServiceWebFragment50()
  * testEE10ManagedExecutorWebFragment50()
  * testEE10ManagedScheduledExecutorWebFragment50()
  * testEE10ManagedThreadFactoryWebFragment50()
  * testEE10ContextServiceWeb60()
  * testEE10ManagedExecutorWebFragment60()
  * testEE10ManagedScheduledExecutorWebFragment60()
  * testEE10ManagedThreadFactoryWebFragment60()

FAT test updates (not fully enabled):

open-liberty/dev/com.ibm.ws.javaee.ddmodel_fat/fat

* com.ibm.ws.javaee.ddmodel.suite.FATSuite
  * DDValidAppTests_J9
     * testAutoInstall_Application_J9()
     * testConfig_Application_J9()
     * testBindingsConfig_Application_J9()
     * testSecurityRoleOverrides_Application_J9()
     * testWebExtension_Application_J9()
     * testWebExtensionNoBindings_Application_J9()
     * testWebBindings_Application_J9()
     * testWebBindingsNoBindings_Application_J9()
     * testEJBBindings_Application_J9()
     * testEJBExtension_Application_J9()
     * testEJBBindingsNoBindings_Application_J9()
     * testEJBExtensionNoBindings_Application_J9()
     * testApplicationExtension_Application_J9()
     * testManagedBeanBindings_Application_J9()
     * testWebserviceBindings_Application_J9()
     * testWebserviceBindingsNoBindings_Application_J9()
   * DDValidAppTests_J10
     * testAutoInstall_Application_J10()
     * testConfig_Application_J10()
     * testBindingsConfig_Application_J10()
     * testSecurityRoleOverrides_Application_J10()
     * testWebExtension_Application_J10()
     * testWebExtensionNoBindings_Application_J10()
     * testWebBindings_Application_J10()
     * testWebBindingsNoBindings_Application_J10()
     * testEJBBindings_Application_J10()
     * testEJBExtension_Application_J10()
     * testEJBBindingsNoBindings_Application_J10()
     * testEJBExtensionNoBindings_Application_J10()
     * testApplicationExtension_Application_J10()
     * testManagedBeanBindings_Application_J10()
     * testWebserviceBindings_Application_J10()
     * testWebserviceBindingsNoBindings_Application_J10()
   * DDValidModTests_J9
     * testAutoInstall_Module_J9()
     * testBindingsConfig_Module_J9()
     * testWebExtension_Module_J9()
     * testWebExtensionNoBindings_Module_J9()
     * testWebBindings_Module_J9()
     * testWebBindingsNoBindings_Module_J9()
     * testEJBBindings_Module_J9()
     * testEJBExtension_Module_J9()
     * testEJBBindingsNoBindings_Module_J9()
     * testEJBExtensionNoBindings_Module_J9()
     * testApplicationExtensionFromWebApp_Module_J9()
     * testSecurityRoleOverridesFromWebApp_Module_J9()
     * testManagedBeanBindings_Module_J9()
   * DDValidModTests_J10
     * testAutoInstall_Module_J10()
     * testBindingsConfig_Module_J10()
     * testWebExtension_Module_J10()
     * testWebExtensionNoBindings_Module_J10()
     * testWebBindings_Module_J10()
     * testWebBindingsNoBindings_Module_J10()
     * testEJBBindings_Module_J10()
     * testEJBExtension_Module_J10()
     * testEJBBindingsNoBindings_Module_J10()
     * testEJBExtensionNoBindings_Module_J10()
     * testApplicationExtensionFromWebApp_Module_J10()
     * testSecurityRoleOverridesFromWebApp_Module_J10()
     * testManagedBeanBindings_Module_J10()

**Pull request merged**
