### PR TITLE
Add websocket tests for CDI @Transactional annotations

### LINKED ISSUE #16203: IllegalStateException when calling CDI bean with @Transactional(Transactional.TxType.NEVER) from websocketEndpoint
A customer reported this on groups.io, it looks like a defect and requires investigation.

The customer said...

I have a simple JEE Websocket Endpoint:

```
import javax.enterprise.context.ApplicationScoped;
import javax.enterprise.context.Dependent;
import javax.inject.Inject;
import javax.websocket.*;
import javax.websocket.server.ServerEndpoint;

@ServerEndpoint("/events")
public class WebsocketEndpoint {

@Inject
HealthService service;

@OnOpen
public void onOpen(Session session) {
System.out.println("onOpen!!!!");
}

@OnClose
public void onClose(Session session) {
System.out.println("onClose!!!!");
}

@OnError
public void onError(Session session, Throwable throwable) {
System.out.println("onError!!!!");
throwable.printStackTrace();
}

@OnMessage
public void onMessage(String message) {
System.out.println("Received message from client: " + message + " | " + service.isHealthy());
}
}
```

and a service with @Transactional=Never that is called when a websocket message arrives:

```
@ApplicationScoped
@Transactional(Transactional.TxType.NEVER)
public class HealthService {

public boolean isHealthy() {
return true;
}
}
```

When i connect to the websocket and send a message, instead of @OnMessage, it calls @OnError and throws the following exception:

```
java.lang.IllegalStateException
at com.ibm.ws.uow.embeddable.EmbeddableUOWManagerImpl.getUOWType(EmbeddableUOWManagerImpl.java:598)
at [internal classes]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.jboss.weld.interceptor.reader.SimpleInterceptorInvocation$SimpleMethodInvocation.invoke(SimpleInterceptorInvocation.java:73)
at [internal classes]
at org.acme.weldapp.business.health.boundary.HealthService$Proxy$_$$_WeldSubclass.isHealthy(Unknown Source)
at org.acme.weldapp.business.health.boundary.HealthService$Proxy$_$$_WeldClientProxy.isHealthy(Unknown Source)
at org.acme.weldapp.business.health.boundary.WebsocketEndpoint.onMessage(WebsocketEndpoint.java:33)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at com.ibm.ws.wsoc.LinkRead.callOnMessage(LinkRead.java:1127)
at [internal classes]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:823)
```

This happens on websphere-liberty and open-liberty on older and newer version. I just tested it with Open Liberty 21.0.0.2/wlp-1.0.49.cl210220210209-1100.

Any idea why this is happening? I dont understand why @Transactional=Never should not be working in this context. There is no problem when i call the service from a rest endoint. There also is no problem with the websocket when i remove the @Transactional=Never.

### PR DESCRIPTION
**Pull request by neilgsyoung**
fixes #16203

### CODE REVIEW

**Comment by neilgsyoung** [comment]
#build

**Comment by neilgsyoung** [comment]
#build

**Comment by neilgsyoung** [comment]
#run-libby-bot

**Review by jonhawkes — APPROVED** [review]

**Review by loriadi — APPROVED** [review]
I concentrated on changes to the original wsoc test bucket - those look good!

**Review by mrsaldana — APPROVED** [review]
The added wsoc tests look fine, thanks for your work on this!

**Pull request merged**
