### PR TITLE
Perf improvements in webcontainer and JSF functions

### PR DESCRIPTION
**Pull request by jhanders34**
Several updates are being made to web container and JSF functions for performance reasons.

Avoid calling String.toCharArray() in favor of using String.getChars().  This reduces the creation of multiple char[]s during a request that goes through the web container. 
Turn off trace injection of org.apache.myfaces classes.  It appears that it wasn't working with the previous values in the bnd file.
Add @Trivial to a hot get method in the JSF code.

### CODE REVIEW

**Comment by jhanders34** [comment]
#build

**Comment by jhanders34** [comment]
#build

**Comment by pnicolucci** [comment]
@billw1024  can you review the http changes here?

@pmd1nh  any concerns with the Webcontainer changes?

**Comment by pnicolucci** [comment]
JSF changes look fine.

**Pull request merged**
