### PR TITLE
Issue #18677: Fix copyright header formatting.

### LINKED ISSUE #18677: Fix ResponseHeadersServlet copyright header
Currently, it is formatted as: 

> /*******************************************************************************
> * Copyright (c) 2021 IBM Corporation and others.
> * All rights reserved. This program and the accompanying materials
> * are made available under the terms of the Eclipse Public License v1.0n * which accompanies this distribution, and is available at 
> * http://www.eclipse.org/legal/epl-v10.htmln *n * Contributors: 
> *     IBM Corporation - initial API and implementation
> *******************************************************************************/

It should be:

> /*******************************************************************************
>  * Copyright (c) 2021 IBM Corporation and others.
>  * All rights reserved. This program and the accompanying materials
>  * are made available under the terms of the Eclipse Public License v1.0
>  * which accompanies this distribution, and is available at
>  * http://www.eclipse.org/legal/epl-v10.html
>  *
>  * Contributors:
>  *     IBM Corporation - initial API and implementation
>  *******************************************************************************/

### PR DESCRIPTION
**Pull request by pnicolucci**
fixes #18677

### CODE REVIEW

**Comment by pnicolucci** [comment]
#libby #build

**Review by mrsaldana — APPROVED** [review]

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
@mrsaldana  I gave you another review of this one as eclipse had removed `import javax.servlet.http.Cookie;` and I didn't notice it so we were getting personal build failures. I've updated that and I'll start another build. If that one is successful and you give another review I'll merge this.

**Comment by pnicolucci** [comment]
#libby #build

**Review by mrsaldana — APPROVED** [review]

**Pull request merged**
