### PR TITLE
Ensure com.ibm.ws.request.timing.monitor_fat is repeated with correct features.

### LINKED ISSUE #30073: Test Failure: junit.framework.TestSuite.com.ibm.ws.request.timing.monitor.fat.RequestTimingMetricsTest
RTC 302667
```
com.ibm.ws.request.timing.monitor.fat.RequestTimingMetricsTest:java.lang.Exception: Runtime features were not of the expected version for repeat action (Server: RequestTimingFeatureWithMetrics, Action: EE8_FEATURES_MicroProfile_33).
Expected: servlet-4.0, Actual: servlet-3.1.
Expected: cdi-2.0, Actual: cdi-1.2.
This is usually caused by a feature not being explicitly set in the FAT's server.xml such that FeatureReplacementAction does not replace it properly.
    at componenttest.topology.impl.LibertyServer.checkServerRepeatFeatures(LibertyServer.java:3640)
    at componenttest.topology.impl.LibertyServer.stopServer(LibertyServer.java:3301)
    at componenttest.topology.impl.LibertyServer.stopServer(LibertyServer.java:3143)
    at componenttest.topology.impl.LibertyServer.stopServer(LibertyServer.java:3137)
    at componenttest.topology.impl.LibertyServer.stopServer(LibertyServer.java:3113)
    at componenttest.topology.impl.LibertyServer.stopServer(LibertyServer.java:3022)
    at com.ibm.ws.request.timing.monitor.fat.RequestTimingMetricsTest.classTearDown(RequestTimingMetricsTest.java:144)
    at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
    at componenttest.rules.repeater.RepeatTests$CompositeRepeatTestActionStatement.evaluate(RepeatTests.java:149)
    at componenttest.custom.junit.runner.FATRunner$2.evaluate(FATRunner.java:374)
    at componenttest.custom.junit.runner.FATRunner.run(FATRunner.java:178)
```

RTC 302665
```
testVendorMetricsPresent_EE11_FEATURES_MicroProfile_70:java.lang.Exception: 2024-11-04-14:28:04:159 Runtime features were not of the expected version for repeat action (Server: MetricsMonitorServer, Action: EE11_FEATURES_MicroProfile_70).
Expected: servlet-6.1, Actual: servlet-6.0.
This is usually caused by a feature not being explicitly set in the FAT's server.xml such that FeatureReplacementAction does not replace it properly.
    at componenttest.topology.impl.LibertyServer.checkServerRepeatFeatures(LibertyServer.java:3640)
    at componenttest.topology.impl.LibertyServer.stopServer(LibertyServer.java:3301)
    at componenttest.topology.impl.LibertyServer.stopServer(LibertyServer.java:3143)
    at componenttest.topology.impl.LibertyServer.stopServer(LibertyServer.java:3137)
    at componenttest.topology.impl.LibertyServer.stopServer(LibertyServer.java:3113)
    at componenttest.topology.impl.LibertyServer.stopServer(LibertyServer.java:3022)
    at componenttest.topology.impl.LibertyServer.stopServer(LibertyServer.java:2997)
    at io.openliberty.microprofile.metrics.internal.monitor_fat.MetricsMonitorTest.tearDown(MetricsMonitorTest.java:94)
    at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
    at componenttest.custom.junit.runner.FATRunner$1.evaluate(FATRunner.java:209)
    at componenttest.rules.repeater.RepeatTests$CompositeRepeatTestActionStatement.evaluate(RepeatTests.java:149)
    at componenttest.custom.junit.runner.FATRunner$2.evaluate(FATRunner.java:374)
    at componenttest.custom.junit.runner.FATRunner.run(FATRunner.java:178)
```

### PR DESCRIPTION
**Pull request by pgunapal**
- [x] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [x] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [x] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

fixes #30073

### CODE REVIEW

**Comment by pgunapal** [comment]
#build

**Comment by contbld** [comment]
Your personal pipeline request is at https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=5bf43022-9960-47fe-b224-9d3600077f85

Target locations of links might be accessible only to IBM employees.

**Comment by contbld** [comment]
<h3>Code analysis and actions</h3>
DO NOT DELETE THIS COMMENT.

- 2 FAT files were changed, added, or removed.
 - Check that the build did not break the affected FAT suite(s).

- 1 test infrastructure code files were changed.
 - Test failures/errors in the build could be due to these changes.

**Comment by contbld** [comment]
https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=5bf43022-9960-47fe-b224-9d3600077f85 has errors/failures.

**Comment by contbld** [comment]
The build pgunapal-30103-20241108-0737
https://wasrtc.hursley.ibm.com:9443/jazz/resource/itemOid/com.ibm.team.build.BuildResult/_FMeS0Z2bEe-M9e5esDPP_g
completed and has errors or failures.

For help analyzing your personal build, go to https://libh-proxy1.fyre.ibm.com/cognitive/buildAnalysis.html?uuid=_FMeS0Z2bEe-M9e5esDPP_g

**Comment by pgunapal** [comment]
Failed tests are not related and are known test failures, associated with an existing defect.

**Review by fmhwong — APPROVED** [review]
LGTM

**Pull request merged**
