### PR TITLE
remove synchronized block when invalidating sip application session to prevent deadlock

### PR DESCRIPTION
**Pull request by TiborBeres**
pull request for issue #27282

### CODE REVIEW

**Comment by TiborBeres** [comment]
fixes #27282

**Comment by TiborBeres** [comment]
#build #fat.buckets.to.run="com.ibm.ws.sipcontainer_fat,com.ibm.ws.sipcontainer_fat_1,com.ibm.ws.sipcontainer_fat_2,com.ibm.ws.sipcontainer_fat_3,com.ibm.ws.sipcontainer_fat_4,com.ibm.ws.sipcontainer_fat_5,com.ibm.ws.sipcontainer_fat_6,com.ibm.ws.sipcontainer_fat_7" #spawn.fullfat.buckets="com.ibm.ws.sipcontainer_fat,com.ibm.ws.sipcontainer_fat_1,com.ibm.ws.sipcontainer_fat_2,com.ibm.ws.sipcontainer_fat_3,com.ibm.ws.sipcontainer_fat_4,com.ibm.ws.sipcontainer_fat_5,com.ibm.ws.sipcontainer_fat_6,com.ibm.ws.sipcontainer_fat_7"

**Comment by TiborBeres** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.sipcontainer_fat,com.ibm.ws.sipcontainer_fat_1,com.ibm.ws.sipcontainer_fat_2,com.ibm.ws.sipcontainer_fat_3,com.ibm.ws.sipcontainer_fat_4,com.ibm.ws.sipcontainer_fat_5,com.ibm.ws.sipcontainer_fat_6,com.ibm.ws.sipcontainer_fat_7

**Comment by TiborBeres** [comment]
#build, #fat.buckets.to.run="com.ibm.ws.sipcontainer_fat,com.ibm.ws.sipcontainer_fat_1,com.ibm.ws.sipcontainer_fat_2,com.ibm.ws.sipcontainer_fat_3,com.ibm.ws.sipcontainer_fat_4,com.ibm.ws.sipcontainer_fat_5,com.ibm.ws.sipcontainer_fat_6,com.ibm.ws.sipcontainer_fat_7" , #spawn.fullfat.buckets="com.ibm.ws.sipcontainer_fat,com.ibm.ws.sipcontainer_fat_1,com.ibm.ws.sipcontainer_fat_2,com.ibm.ws.sipcontainer_fat_3,com.ibm.ws.sipcontainer_fat_4,com.ibm.ws.sipcontainer_fat_5,com.ibm.ws.sipcontainer_fat_6,com.ibm.ws.sipcontainer_fat_7"

**Comment by TiborBeres** [comment]
#build, #fat.buckets.to.run=com.ibm.ws.sipcontainer_fat,com.ibm.ws.sipcontainer_fat_1,com.ibm.ws.sipcontainer_fat_2,com.ibm.ws.sipcontainer_fat_3,com.ibm.ws.sipcontainer_fat_4,com.ibm.ws.sipcontainer_fat_5,com.ibm.ws.sipcontainer_fat_6,com.ibm.ws.sipcontainer_fat_7, #spawn.fullfat.buckets=com.ibm.ws.sipcontainer_fat,com.ibm.ws.sipcontainer_fat_1,com.ibm.ws.sipcontainer_fat_2,com.ibm.ws.sipcontainer_fat_3,com.ibm.ws.sipcontainer_fat_4,com.ibm.ws.sipcontainer_fat_5,com.ibm.ws.sipcontainer_fat_6,com.ibm.ws.sipcontainer_fat_7

**Comment by TiborBeres** [comment]
#build, #fat.buckets.to.run=com.ibm.ws.sipcontainer_fat,com.ibm.ws.sipcontainer_fat_1,com.ibm.ws.sipcontainer_fat_2,com.ibm.ws.sipcontainer_fat_3,com.ibm.ws.sipcontainer_fat_4,com.ibm.ws.sipcontainer_fat_5,com.ibm.ws.sipcontainer_fat_6,com.ibm.ws.sipcontainer_fat_7, #spawn.fullfat.buckets=com.ibm.ws.sipcontainer_fat,com.ibm.ws.sipcontainer_fat_1,com.ibm.ws.sipcontainer_fat_2,com.ibm.ws.sipcontainer_fat_3,com.ibm.ws.sipcontainer_fat_4,com.ibm.ws.sipcontainer_fat_5,com.ibm.ws.sipcontainer_fat_6,com.ibm.ws.sipcontainer_fat_7

**Comment by epj** [comment]
I saved fatoutput-com.ibm.ws.sipcontainer_fat_3.zip in case you need it (Friday's pb)

**Comment by TiborBeres** [comment]
All sipcontainer_fat tests were executed in the personal build. There was one known intermittent test failure, not caused by the changes.

**Review by epj — APPROVED** [review]
okay

**Comment by TiborBeres** [comment]
#rosie

**Comment by TiborBeres** [comment]
#libby

**Pull request merged**
