### PR TITLE
Additional properties needed to complete checklist

### PR DESCRIPTION
**Pull request by wraschke**
- [ ] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [ ] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [ ] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

Once the prerequisite PRs for dependency microservice and Jenkins code are merged, I'll

- [ ] Run a production Libby pipeline
- [ ] Remove the commits of test changes to the messages, NLS, and feature files that are there only for testing.
- [ ] Run another production Libby pipeline

### CODE REVIEW

**Comment by wraschke** [comment]
!libby@dev

**Comment by contbld** [comment]
Your personal pipeline request is at https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=75de88a4-ab97-4663-adf2-7b6465e118af

Target locations of links might be accessible only to IBM employees.

**Comment by contbld** [comment]
https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=75de88a4-ab97-4663-adf2-7b6465e118af has errors/failures.

**Comment by wraschke** [comment]
!libby

**Comment by contbld** [comment]
Your personal pipeline request is at https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=c21539ee-8946-4771-9ce4-a8dd30d88a74

Target locations of links might be accessible only to IBM employees.

**Comment by contbld** [comment]
https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=c21539ee-8946-4771-9ce4-a8dd30d88a74 has errors/failures.

**Comment by wraschke** [comment]
!libby@dev

**Comment by contbld** [comment]
Your personal pipeline request is at https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=ff7ba6bf-3e78-429f-b8a7-36e7ed9ac055

Target locations of links might be accessible only to IBM employees.

**Comment by contbld** [comment]
<h3>Code analysis and actions</h3>
DO NOT DELETE THIS COMMENT.

- 1 infrastructure code files were changed.

- 4 product code files were changed.

**Comment by contbld** [comment]
https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=ff7ba6bf-3e78-429f-b8a7-36e7ed9ac055 completed successfully!

**Comment by contbld** [comment]
<h3>Code analysis and actions</h3>
DO NOT DELETE THIS COMMENT.

- 1 infrastructure code files were changed.

- 4 product code files were changed.

**Comment by wraschke** [comment]
<h3>Code analysis and actions</h3>
DO NOT DELETE THIS COMMENT.

- 3 product code files were changed.
- **Please describe in a separate comment how you tested your changes.**

- 1 NLS files were changed and need an ID review.

- @OpenLiberty/madeup-team Please review.
  - dev/com.ibm.ws.security.openidconnect.server/resources/OSGI-INF/l10n/metatype.properties

**Comment by wraschke** [comment]
!libby@dev

**Comment by contbld** [comment]
Your personal pipeline request is at https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=16875415-9595-4c4e-a6a7-3cff2eca4feb

Target locations of links might be accessible only to IBM employees.

**Comment by contbld** [comment]
https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=16875415-9595-4c4e-a6a7-3cff2eca4feb has errors/failures.

**Comment by contbld** [comment]
<h3>Code analysis and actions</h3>
DO NOT DELETE THIS COMMENT.

- 1 infrastructure code files were changed.

- 4 product code files were changed.- **Please describe in a separate comment how you tested your changes.**
- 2 messages files were changed and need an L2 review.

- @OpenLiberty/message-reviewer Please review.
  - dev/com.ibm.websphere.rest.handler/resources/com/ibm/wsspi/rest/config/resources/CWWKOMessages.nlsprops
  - dev/com.ibm.jbatch.container/resources/com/ibm/jbatch/container/internal/resources/JBatchMessages.nlsprops


- 3 NLS files were changed and need an ID review.

- @OpenLiberty/message-reviewer Please review.
  - dev/com.ibm.websphere.rest.handler/resources/com/ibm/wsspi/rest/config/resources/CWWKOMessages.nlsprops
  - dev/com.ibm.jbatch.container/resources/com/ibm/jbatch/container/internal/resources/JBatchMessages.nlsprops
  - dev/com.ibm.websphere.appserver.features/visibility/public/xmlWS-4.0/resources/l10n/io.openliberty.xmlWS-4.0.properties

**Comment by contbld** [comment]
Please code review feature-related files, @OpenLiberty/delivery-approvers

**Comment by wraschke** [comment]
!build@dev

**Comment by contbld** [comment]
Your personal pipeline request is at https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=0c0cafdb-9214-4ef7-946e-175bae193a3e

Target locations of links might be accessible only to IBM employees.

**Comment by contbld** [comment]
Your personal pipeline request is at https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=3ca9229a-bfe9-43e0-aa9d-a50695832284

Target locations of links might be accessible only to IBM employees.

**Comment by contbld** [comment]
<h3>Code analysis and actions</h3>
DO NOT DELETE THIS COMMENT.

- 3 infrastructure code files were changed.

- 4 product code files were changed.- **Please describe in a separate comment how you tested your changes.**
- 2 messages files were changed and need an L2 review.

- @OpenLiberty/message-reviewer Please review.
  - dev/com.ibm.websphere.rest.handler/resources/com/ibm/wsspi/rest/config/resources/CWWKOMessages.nlsprops
  - dev/com.ibm.jbatch.container/resources/com/ibm/jbatch/container/internal/resources/JBatchMessages.nlsprops


- 3 NLS files were changed and need an ID review.

- @OpenLiberty/message-reviewer Please review.
  - dev/com.ibm.websphere.rest.handler/resources/com/ibm/wsspi/rest/config/resources/CWWKOMessages.nlsprops
  - dev/com.ibm.jbatch.container/resources/com/ibm/jbatch/container/internal/resources/JBatchMessages.nlsprops
  - dev/com.ibm.websphere.appserver.features/visibility/public/xmlWS-4.0/resources/l10n/io.openliberty.xmlWS-4.0.properties

**Comment by contbld** [comment]
Please code review feature-related files, @OpenLiberty/delivery-approvers

**Comment by contbld** [comment]
<h3>Code analysis and actions</h3>
DO NOT DELETE THIS COMMENT.

- 3 infrastructure code files were changed.

- 4 product code files were changed.- **Please describe in a separate comment how you tested your changes.**
- 2 messages files were changed and need an L2 review.

- @OpenLiberty/message-reviewer Please review.
  - dev/com.ibm.websphere.rest.handler/resources/com/ibm/wsspi/rest/config/resources/CWWKOMessages.nlsprops
  - dev/com.ibm.jbatch.container/resources/com/ibm/jbatch/container/internal/resources/JBatchMessages.nlsprops


- 3 NLS files were changed and need an ID review.

- @OpenLiberty/message-reviewer Please review.
  - dev/com.ibm.websphere.rest.handler/resources/com/ibm/wsspi/rest/config/resources/CWWKOMessages.nlsprops
  - dev/com.ibm.jbatch.container/resources/com/ibm/jbatch/container/internal/resources/JBatchMessages.nlsprops
  - dev/com.ibm.websphere.appserver.features/visibility/public/xmlWS-4.0/resources/l10n/io.openliberty.xmlWS-4.0.properties

**Comment by contbld** [comment]
Please code review feature-related files, @OpenLiberty/delivery-approvers

**Comment by contbld** [comment]
https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=0c0cafdb-9214-4ef7-946e-175bae193a3e has errors/failures.

**Comment by contbld** [comment]
https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=3ca9229a-bfe9-43e0-aa9d-a50695832284 has errors/failures.

**Comment by wraschke** [comment]
!libby !build

**Comment by contbld** [comment]
Your personal pipeline request is at https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=3b274854-3793-450f-9d62-32077bdc8c11

Target locations of links might be accessible only to IBM employees.

**Comment by contbld** [comment]
Your personal pipeline request is at https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=72b88376-5fba-4f49-ba4f-ba7050544896

Target locations of links might be accessible only to IBM employees.

**Comment by contbld** [comment]
Your personal pipeline request is at https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=adce8f00-ff38-4782-a840-eb0104ec5789

Target locations of links might be accessible only to IBM employees.

**Review by fritze2 — DISMISSED** [review]
Looks good.

**Comment by contbld** [comment]
<h3>Code analysis and actions</h3>
DO NOT DELETE THIS COMMENT.

- 3 infrastructure code files were changed.
- **Please describe in a separate comment how you tested your changes.**
- 1 messages files were changed and need an L2 review.

- @OpenLiberty/message-reviewer Please review.
  - --nlsFiles

**Comment by contbld** [comment]
<h3>Code analysis and actions</h3>
DO NOT DELETE THIS COMMENT.

- 3 infrastructure code files were changed.
- **Please describe in a separate comment how you tested your changes.**
- 1 messages files were changed and need an L2 review.

- @OpenLiberty/message-reviewer Please review.
  - --nlsFiles

**Comment by contbld** [comment]
<h3>Code analysis and actions</h3>
DO NOT DELETE THIS COMMENT.

- 3 infrastructure code files were changed.
- **Please describe in a separate comment how you tested your changes.**
- 1 messages files were changed and need an L2 review.

- @OpenLiberty/message-reviewer Please review.
  - --nlsFiles

**Comment by contbld** [comment]
https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=72b88376-5fba-4f49-ba4f-ba7050544896 has errors/failures.

**Comment by contbld** [comment]
https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=3b274854-3793-450f-9d62-32077bdc8c11 has errors/failures.

**Comment by wraschke** [comment]
!libby !pbbeta

**Comment by contbld** [comment]
Your personal pipeline request is at https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=c0a4cc99-7ae0-40da-84bc-b64dc3671aaa

Target locations of links might be accessible only to IBM employees.

**Comment by contbld** [comment]
Your personal pipeline request is at https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=139da2d9-bab0-4620-a516-6907b68b7258

Target locations of links might be accessible only to IBM employees.

**Comment by contbld** [comment]
<h3>Code analysis and actions</h3>
DO NOT DELETE THIS COMMENT.

- 3 infrastructure code files were changed.
- **Please describe in a separate comment how you tested your changes.**
- 1 messages files were changed and need an L2 review.

- @OpenLiberty/message-reviewer Please review.
  - --nlsFiles

**Comment by contbld** [comment]
<h3>Code analysis and actions</h3>
DO NOT DELETE THIS COMMENT.

- 3 infrastructure code files were changed.
- **Please describe in a separate comment how you tested your changes.**
- 1 messages files were changed and need an L2 review.

- @OpenLiberty/message-reviewer Please review.
  - --nlsFiles

**Comment by contbld** [comment]
https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=c0a4cc99-7ae0-40da-84bc-b64dc3671aaa completed successfully!

**Comment by wraschke** [comment]
!libby

**Comment by contbld** [comment]
Your personal pipeline request is at https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=84b98cf1-cd33-4067-a2ab-44151f03b2f5

Target locations of links might be accessible only to IBM employees.

**Comment by contbld** [comment]
<h3>Code analysis and actions</h3>
DO NOT DELETE THIS COMMENT.

- 3 infrastructure code files were changed.

**Comment by contbld** [comment]
https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=84b98cf1-cd33-4067-a2ab-44151f03b2f5 completed successfully!

**Comment by wraschke** [comment]
!libby

**Comment by wraschke** [comment]
!libby@dev

**Comment by wraschke** [comment]
!libby@dev

**Comment by wraschke** [comment]
!libby@dev

**Comment by wraschke** [comment]
!libby@dev

**Comment by wraschke** [comment]
!libby@dev

**Comment by wraschke** [comment]
!libby@dev

**Comment by wraschke** [comment]
!libby

**Comment by wraschke** [comment]
!build

**Review by fritze2 — APPROVED** [review]

**Comment by wraschke** [comment]
The [Open Liberty Personal Build RTC](https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=4ee8664b-35a4-4890-9234-c8a9167aae58&tab=Steps) is still running as of this writing; specifically, it's waiting for some RTC FAT child builds to coplete. But the beta pipeline completed a while ago and most significantly, the affected step, "Code Checklist Creation", has long completed with expected outcomes in each of the three production pipelines. After checking with Ethan that this is okay, I am merging this PR.

**Pull request merged**
