### PR TITLE
XML Binding 4.0: Add Jakarta XML Binding 4.0 specification API bundle

### PR DESCRIPTION
**Pull request by neuwerk**
This pull request adds the Jakarta XML Binding 4.0 APIs as a new bundle `io.openliberty.xmlBinding.4.0`

### CODE REVIEW

**Comment by neuwerk** [comment]
#build

**Comment by neuwerk** [comment]
#21011

**Review by BerksanAtes — APPROVED** [review]
Looks good!

**Comment by neuwerk** [comment]
#build

**Pull request merged**
