### PR TITLE
Improve JPA DB2ZOS FAT integration

### PR DESCRIPTION
**Pull request by dazey3**
Adding to the JPA FAT testframework for DB2ZOS detection and improving JPA FAT test applications to have new DB2ZOS ddls

### CODE REVIEW

**Comment by dazey3** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jpa.tests.eclipselink.query_jpa_2.2_fat, com.ibm.ws.jpa.tests.eclipselink.query_jpa_3.1_fat, com.ibm.ws.jpa.tests.eclipselink_jpa_2.2_fat, com.ibm.ws.jpa.tests.eclipselink_jpa_3.1_fat, com.ibm.ws.jpa.tests.spec10.query_jpa_2.1_fat, com.ibm.ws.jpa.tests.spec10.query_jpa_3.1_fat

**Review by jgrassel — DISMISSED** [review]
lgtm

**Comment by dazey3** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jpa.tests.eclipselink.query_jpa_2.2_fat, com.ibm.ws.jpa.tests.eclipselink.query_jpa_3.1_fat, com.ibm.ws.jpa.tests.eclipselink_jpa_2.2_fat, com.ibm.ws.jpa.tests.eclipselink_jpa_3.1_fat, com.ibm.ws.jpa.tests.spec10.query_jpa_2.1_fat, com.ibm.ws.jpa.tests.spec10.query_jpa_3.1_fat

**Comment by dazey3** [comment]
#run-libby-bot

**Review by jgrassel — CHANGES_REQUESTED** [review]
Get rid of the bootstrap.jar otherwise looks good.

**Comment by dazey3** [comment]
#run-libby-bot

**Review by jgrassel — APPROVED** [review]
lgtm

**Pull request merged**
