### PR TITLE
test with simulated z/OS context

### PR DESCRIPTION
**Pull request by njr-11**
Create a test bucket that simulates the z/OS context provider configuration (but not behavior) that we can use to test if these types of context can be specified via an application-defined ContextService.

### CODE REVIEW

**Comment by njr-11** [comment]
#build

**Comment by njr-11** [comment]
#build

**Comment by njr-11** [comment]
#build

**Comment by njr-11** [comment]
#run-libby-bot

**Review by nmittles — APPROVED** [review]

**Comment by njr-11** [comment]
#build

**Comment by njr-11** [comment]
Build has 3 test failures, which are duplicates of pre-existing issues in unrelated components.

**Pull request merged**
