### PR TITLE
add jakartaee8 platform for versionless

### LINKED ISSUE #30009: Support Jakartaee-8.0 as a Platform for Versionless
Currently, only javaee-8.0 works as a platform for versionless features. We want to create a way for jakartaee-8.0 to exist as a platform as well.

We want to be able to specify the below config when specifying platforms+versionless features
`<platform>jakartaee-8.0</platform>`

### PR DESCRIPTION
**Pull request by rsherget**
- [x] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [x] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [x] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

Fixes #30009

### CODE REVIEW

**Comment by rsherget** [comment]
#build

**Comment by rsherget** [comment]
#build

**Comment by rsherget** [comment]
#build

**Comment by rsherget** [comment]
Build to test doc creation https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_e3wyQJ0MEe-M9e5esDPP_g

**Comment by cbridgha** [comment]
I looked at the docs build - nothing is broken - so I'm good merging...   The docs don't mention "jakartaee-8.0" at all..  maybe talke to @hlhoots or @dmuelle about a one time change to mention this synonym?

**Comment by dmuelle** [comment]
@cbridgha @rsherget - we've never documented anything about Jakarta EE 8 platform so I think it makes sense have something in the docs saying it's equivalent to Java EE 8. Ricky, would you please open a doc ticket for this at https://github.com/OpenLiberty/docs/issues? We'll get it sorted for 240012 (if thats when we expect it to GA). Thanks!

**Comment by dmuelle** [comment]
I think we might want to add a note to https://openliberty.io/docs/latest/reference/platform/JakartaEE.html, which is an atuogenerated page so would need edits on the dev side. But I'll sort all that out from the doc ticket

**Comment by rsherget** [comment]
> @cbridgha @rsherget - we've never documented anything about Jakarta EE 8 platform so I think it makes sense have something in the docs saying it's equivalent to Java EE 8. Ricky, would you please open a doc ticket for this at https://github.com/OpenLiberty/docs/issues? We'll get it sorted for 240012 (if thats when we expect it to GA). Thanks!

Doc issue opened https://github.com/OpenLiberty/docs/issues/7691

**Comment by hlhoots** [comment]
@dmuelle let me know the wording and location for the new text on that link above, and I can update that page in the code this week.

**Review by hlhoots — APPROVED** [review]
LGTM

**Pull request merged**
