### PR TITLE
Fix failure in RTC 291613. Test was deleting caches between test meth…

### PR DESCRIPTION
**Pull request by jvanhill**
…ods while not restarting the server. This left the JCache cache pointing to a cache that no longer existed and upon the next configuration update, the server would try to close a cache that no longer existed.

### CODE REVIEW

**Comment by jvanhill** [comment]
#build

**Comment by jvanhill** [comment]
#build

**Comment by jvanhill** [comment]
#build

**Comment by jvanhill** [comment]
The last test did not fail in the way I hoped, trying again.

#build

**Comment by jvanhill** [comment]
Issuing yet another build in the hopes it captures the failure.

#build

**Comment by jvanhill** [comment]
#build

**Comment by jvanhill** [comment]
#build

**Comment by jvanhill** [comment]
I was trying to reproduce the error from Infinispan, but I think at this time it is better if I merge the changes and wait for it to recur in the continuous builds.

**Review by ryanesch — APPROVED** [review]

**Comment by ryanesch** [comment]
#run-libby-bot

**Pull request merged**
