### PR TITLE
Issue 1411: Update the EclipseLink 2.6 and 2.7 binaries

### PR DESCRIPTION
**Pull request by daliasheasha**
Updated the 2.6 binaries and scripts to accommodate the changes that were made to Liberty recently that did not allow us to take advantage of properties that were global before and now aren't anymore. 

Updated the 2.7 binaries and scripts likewise. Also, updated the 2.7 binaries to use the EclipseLink 2.7 service branch instead of the 2.7_WAS branch. 

After spending some time looking at the EclipseLink messages, I noticed that we were detecting a lot more messages than expected between EclipseLink 2.6 and 2.7. It turned out that a change went into EclipseLink a while back that combined logging messages and trace messages into one file which were previously separated. The separation allowed us to exclude trace messages from translation since there is no need to translate trace. So, I went back to the EclipseLink community and asked if we could revert that change since we still need the message separation to easily distinguish between messages that need translation and messages that don't. After getting their approval, I went ahead and reverted the change in EclipseLink. Currently, the EclipseLink 2.7 and master branch have their trace and logging messages separated. I also committed changes to the messages according to the ID review.
All these updates are currently in the EclipseLink repository. I am pulling that change into Liberty now with the suggested changes to the translation messages.

### CODE REVIEW

**Comment by daliasheasha** [comment]
#build

**Comment by dazey3** [comment]
fixes #1411

**Comment by daliasheasha** [comment]
The build failed due to a known unrelated failure. 

The updatebinaries.gradle scripts should run successfully as long as this change exists in the environment:
https://github.com/OpenLiberty/open-liberty/pull/1452/files#diff-687e8540545104f724086f8031c5d601

**Comment by bsbyrd1** [comment]
Thanks, @daliasheasha. It looks like you have made trace/logging message updates based on the ID Review, and this issue (1461) does not require ID.

**Comment by daliasheasha** [comment]
#build

**Comment by daliasheasha** [comment]
@dazey3 @jgrassel I tested my original change for DHE and it failed since coordinates in oss_maven do not get mapped to DHE. So, I made a second commit that moves the eclipselink 2.7 coordinates back to oss_ibm.maven since only coordinates in that file are mapped to DHE.

**Comment by daliasheasha** [comment]
fixes #332

**Pull request merged**
