### PR TITLE
update test keys, key and trust stores

### PR DESCRIPTION
**Pull request by c00crane**
Update the keys, keystore and truststores to remove use of secp256k1.  Regenerated all of the mpjwt test keys while I was at it...

### CODE REVIEW

**Comment by c00crane** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.security.mp.jwt.1.1_fat

**Comment by c00crane** [comment]
New personal build submitted (builds overnight failed due to infrastructure issues): https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_b54D0PggEeqwgKOHPUEi3Q

**Comment by c00crane** [comment]
New build with remove ps keys
https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_AIfp8PhUEeqwgKOHPUEi3Q

**Comment by c00crane** [comment]
New build with tests disabled (disabled tests that were using PS certs in a mismatch case - we have other mismatch tests using RS, ES and HS)
https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_g-ymwPjyEeqwgKOHPUEi3Q

**Review by ayoho — APPROVED** [review]

**Comment by c00crane** [comment]
#run-libby-bot

**Pull request merged**
