### PR TITLE
increase timeout again

### PR DESCRIPTION
**Pull request by benjamin-confino**
Hopefully fixes https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.workitem.viewWorkItem&id=283911

### CODE REVIEW

**Comment by benjamin-confino** [comment]
#build

**Comment by benjamin-confino** [comment]
#build

**Review by Azquelt — APPROVED** [review]
This is fine (and the log statements are better :+1:) but we're still only waiting 0.6s.

If it fails again, using a much longer timeout would make this test clearer and more reliable. Could also use `Future` to simplify it a bit.

**Comment by benjamin-confino** [comment]
#run-libby-bot

**Pull request merged**
