### PR TITLE
WSDataSource legacy API

### PR DESCRIPTION
**Pull request by njr-11**
Add the following legacy codepath:
WSDataSource
WSConnectionSpec
JDBCConnectionSpec

Add a test for the isXADataSource method and for now, just one test for requesting a connection with custom attributes (isolation level). More will be added in separate pulls.

### CODE REVIEW

**Comment by njr-11** [comment]
#build

**Comment by njr-11** [comment]
The build failed to compile because some of the files weren't included. Trying again,
#run-libby-bot
#build

**Comment by njr-11** [comment]
#build

**Comment by njr-11** [comment]
Build has 1 test failure and it is a duplicate of a pre-existing failure.

**Review by nmittles — APPROVED** [review]

**Pull request merged**
