### PR TITLE
Tckresults

### PR DESCRIPTION
**Pull request by Yas-Franco**
Generates the content required for the summary of the TCK results for releases of MicroProfile specs. 

https://github.com/OpenLiberty/certifications/tree/prod/microprofile/5.0

### CODE REVIEW

**Comment by Yas-Franco** [comment]
#build

**Comment by Yas-Franco** [comment]
#build

**Comment by Yas-Franco** [comment]
#build

**Comment by Yas-Franco** [comment]
#build

**Review by benjamin-confino — APPROVED** [review]

**Comment by Yas-Franco** [comment]
#run-libby-bot

**Pull request merged**
