### PR TITLE
Remove acronyms from feature descriptionsfor Jakarta

### LINKED ISSUE #12978: As part of Jakarta EE9 we should avoid acronyms in our feature descriptions

### PR DESCRIPTION
**Pull request by pnicolucci**
fixes #12978

### CODE REVIEW

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#run-libby-bot

**Comment by andrea-pichler** [comment]
No message review requested from L2

**Pull request merged**
