### PR TITLE
Eclipse and bnd updates from recent changes

### PR DESCRIPTION
**Pull request by jhanders34**
- Add missing .project, .classpath, org.eclipse.jdt.core.pref and bndtools.prefs files for new projects
- Remove non existent source directories and add new source directory where it was missing.
- Update Java settings to be correct for Java 8 vs Java 11
- Remove gradle buildship build from .project files
- Switch to only produce the transformed version of grpc netty shaded bundle since the non transformed one isn't used.
- Add new FATs to the git hub action test categories
- Switch to use group:artifact format for jandex project.

### CODE REVIEW

**Comment by jhanders34** [comment]
#build

**Review by Yas-Franco — APPROVED** [review]
LGTM

**Review by Azquelt — APPROVED** [review]

**Comment by jhanders34** [comment]
#build

**Comment by jhanders34** [comment]
#build

**Comment by jhanders34** [comment]
#libby

**Pull request merged**
