### PR TITLE
Pull in Jakarta Annotations 2.1

### LINKED ISSUE #20624: Update to Jakarta Annotations 2.1
Final 2.1.0 version is available on maven central
https://repo1.maven.org/maven2/jakarta/annotation/jakarta.annotation-api/2.1.0/jakarta.annotation-api-2.1.0.jar

### PR DESCRIPTION
**Pull request by tevans78**
Update JEE10 features to use Jakarta Annotations 2.1

### CODE REVIEW

**Comment by tevans78** [comment]
#build

**Review by tkburroughs — APPROVED** [review]
LGTM

**Comment by tkburroughs** [comment]
#libby

**Comment by tevans78** [comment]
#build

**Pull request merged**
