### PR TITLE
Clean up existing web tier copyright templates

### LINKED ISSUE #26713: WebTier component copyright template updates
1) Fix the existing copyright template in eclipse preferences.

### PR DESCRIPTION
**Pull request by pnicolucci**
fixes #26713

### CODE REVIEW

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
#build

**Review by pmd1nh — APPROVED** [review]

**Review by volosied — APPROVED** [review]

**Comment by pnicolucci** [comment]
#libby

**Pull request merged**
