### PR TITLE
Added local transformation additions to EE9 and EE10 repeat

### LINKED ISSUE #18532: Local transformation additions for FAT
Add local transformation additions for FAT project to append additional transformation rules for EE9 and EE10 transformations

### PR DESCRIPTION
**Pull request by isaacrivriv**
fixes #18532

### CODE REVIEW

**Comment by isaacrivriv** [comment]
#build

**Comment by isaacrivriv** [comment]
#build

**Comment by isaacrivriv** [comment]
#build

**Comment by isaacrivriv** [comment]
#build

**Comment by isaacrivriv** [comment]
#build

**Comment by isaacrivriv** [comment]
#libby

**Review by jhanders34 — APPROVED** [review]

**Review by pnicolucci — APPROVED** [review]

**Pull request merged**
