### PR TITLE
Add scr tracing

### LINKED ISSUE #18423: Add SCR tracing to com.ibm.ws.webcontainer.servlet.4.0_fat samesite server
We've had a few occurrences of the following error happening in our tests:

> [7/6/21, 12:06:53:208 PDT] 000000cb LogService-121-com.ibm.ws.channel.ssl                        W CWWKE0700W: bundle com.ibm.ws.channel.ssl:1.0.55.202107060915 (121)[com.ibm.ws.channel.ssl.internal.SSLChannelProvider(299)] : Component deactivation threw an exception java.lang.IllegalStateException: Could not obtain lock
    at org.apache.felix.scr.impl.manager.AbstractComponentManager.obtainLock(AbstractComponentManager.java:242)
    at org.apache.felix.scr.impl.manager.AbstractComponentManager.obtainStateLock(AbstractComponentManager.java:289)
    at org.apache.felix.scr.impl.manager.AbstractComponentManager.doDeactivate(AbstractComponentManager.java:849)
    at org.apache.felix.scr.impl.manager.AbstractComponentManager.deactivateInternal(AbstractComponentManager.java:825)
    at org.apache.felix.scr.impl.manager.DependencyManager.deactivateComponentManager(DependencyManager.java:2580)
    at org.apache.felix.scr.impl.manager.DependencyManager.access$400(DependencyManager.java:59)

All of the tests pass successfully in the samesite test suite but we want to determine if there is a deadlock someplace outside of osgi/scr here and ensure that we can capture a thread dump if this happens again.

In addition I'll use this issue to remove the tracing configuration from the `server.xml` and place it in the `bootstrap.property` as well as removing additional trace configuration in the samesite test class that is not necessary.

### PR DESCRIPTION
**Pull request by pnicolucci**
fixes #18423

### CODE REVIEW

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Review by isaacrivriv — APPROVED** [review]
Looks good to me, thanks!

**Comment by pnicolucci** [comment]
#run-libby-bot

**Pull request merged**
