### PR TITLE
Reduce Page Size on Search Paging Test

### LINKED ISSUE #6332: Reduce number of users for SearchPagingTest
SearchPagingTest creates 100 users/groups and it seems to take awhile (like 40 seconds). We can test the same thing with fewer users. Running with 20 users has been working.

### PR DESCRIPTION
**Pull request by kristip17**
Fixes #6332

### CODE REVIEW

**Comment by kristip17** [comment]
#build

**Comment by kristip17** [comment]
SearchPagingTest passed with reduced user/group size.  Failing test is an remote Ldap issue.

User/group creation appears to have gone from ~45 seconds to ~10 seconds.

**Comment by jvanhill** [comment]
> SearchPagingTest passed with reduced user/group size. Failing test is an remote Ldap issue.
> 
> User/group creation appears to have gone from ~45 seconds to ~10 seconds.

Do you mean it is an embedded LDAP issue?

**Comment by kristip17** [comment]
In 4/10 runs of ldap_fat on the PB, a different test that uses remote AD Ldap is hitting the out of space issue.

**Pull request merged**
