### PR TITLE
Check for GC events during server startup

### LINKED ISSUE #14481: Test Failure: com.ibm.ws.logstash.collector.tests.LogstashSSLTest.testLogstashForGCEvent
RTC 278730

```
testLogstashForGCEvent:junit.framework.AssertionFailedError: 2020-10-13-06:23:11:778 liberty_gc not found
at com.ibm.ws.logstash.collector.tests.LogstashSSLTest.testLogstashForGCEvent(LogstashSSLTest.java:186)
at componenttest.custom.junit.runner.FATRunner$1.evaluate(FATRunner.java:197)
at org.testcontainers.containers.FailureDetectingExternalResource$1.evaluate(FailureDetectingExternalResource.java:30)
at componenttest.custom.junit.runner.FATRunner$2.evaluate(FATRunner.java:318)
at componenttest.custom.junit.runner.FATRunner.run(FATRunner.java:171)
```

### LINKED ISSUE #14504: Test Failure: com.ibm.ws.logstash.collector.tests.LogstashSSLTest.testLogstashDefaultConfig
RTC 278770

```
testLogstashDefaultConfig:junit.framework.AssertionFailedError: 2020-09-23-16:19:47:975 Did not get all messages from Logstash container. Missing 1
at com.ibm.ws.logstash.collector.tests.LogstashSSLTest.testLogstashDefaultConfig(LogstashSSLTest.java:116)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at componenttest.custom.junit.runner.FATRunner$1.evaluate(FATRunner.java:197)
at org.testcontainers.containers.FailureDetectingExternalResource$1.evaluate(FailureDetectingExternalResource.java:30)
at componenttest.custom.junit.runner.FATRunner$2.evaluate(FATRunner.java:318)
at componenttest.custom.junit.runner.FATRunner.run(FATRunner.java:171)
```

### PR DESCRIPTION
**Pull request by fmhwong**
Current GC generation is not reliable.  Usually there are GC events generated during server startup.  Will check both server startup GC and test case generated events.  
Fixes #14481 

Added a wait for TRAS0218I during server startup and clear the container log.
Fixes #14504

### CODE REVIEW

**Comment by fmhwong** [comment]
#build

**Comment by fmhwong** [comment]
#build 
#libby

**Review by Yushan-Lin — APPROVED** [review]
LGTM

**Comment by fmhwong** [comment]
#build 
#libby

**Comment by fmhwong** [comment]
#build 
#libby

**Review by Yushan-Lin — APPROVED** [review]
LGTM

**Pull request merged**
