### PR TITLE
Modify forbidden class support

### PR DESCRIPTION
**Pull request by dazavala**
Modify forbidden classes support

### CODE REVIEW

**Comment by dazavala** [comment]
#build
TBD: Launch another build for this PR w/ WSCDO PR 30688.

**Review by jaridk — DISMISSED** [review]
I'm good with it unless you want to change the property name. It's clunky but also this is not going to be a widely-disseminated option so clunky is fine, and I don't really have a better suggestion.

**Comment by dazavala** [comment]
#build

**Comment by dazavala** [comment]
@jaridk This PR and WL 30688 are ready for your review.  Build results are as expected: The combined [WL-OL build](https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_67zdwIM2Ee6tffXfLjKGSA) passed, the [OL build](https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_NfxFAIMzEe6tffXfLjKGSA) passed, and the [WL build](url) failed due to the new test.

**Review by jaridk — APPROVED** [review]

**Comment by dazavala** [comment]
#libby

**Pull request merged**
