### PR TITLE
Git, bnd and eclipse settings updates

### PR DESCRIPTION
**Pull request by jhanders34**
- Add bin_test to the global .gitignore file
- Remove left over eclipse files from a recent component deletion
- Add javac.source, javac.target and Require-Capability to new jdt projects
- Update to use group:artifact:version format instead of group.artifact:version for buildpath dependencies
- Update to reference the built bundle in the fat gradle dependencies for grpc instead of the artifact so you only have to update one place.

### CODE REVIEW

**Comment by jhanders34** [comment]
#build

**Review by njr-11 — DISMISSED** [review]

**Comment by jhanders34** [comment]
#libby #build

**Comment by jhanders34** [comment]
#build

**Review by volosied — DISMISSED** [review]

**Review by hutchig — DISMISSED** [review]
Looks fine to me.

**Review by jim-krueger — DISMISSED** [review]

**Comment by jhanders34** [comment]
#libby #build

**Comment by jhanders34** [comment]
#libby #build

**Review by jim-krueger — APPROVED** [review]

**Pull request merged**
