### PR TITLE
Enhance CheckpointRule to be more general for other FATs

### PR DESCRIPTION
**Pull request by tjwatson**
- [x] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [x] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [x] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

### CODE REVIEW

**Comment by tjwatson** [comment]
#build

**Comment by contbld** [comment]
Your personal pipeline request is at https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=2541e0c3-9b11-4da3-a9b9-361f17204f1f

Target locations of links might be accessible only to IBM employees.

**Comment by contbld** [comment]
<h3>Code analysis and actions</h3>
DO NOT DELETE THIS COMMENT.

- 2 FAT files were changed, added, or removed.
 - Check that the build did not break the affected FAT suite(s).

- 2 test infrastructure code files were changed.
 - Test failures/errors in the build could be due to these changes.

**Comment by contbld** [comment]
https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=2541e0c3-9b11-4da3-a9b9-361f17204f1f has errors/failures.

**Review by anjumfatima90 — APPROVED** [review]
LGTM! Thanks.

**Comment by tjwatson** [comment]
#build

**Comment by contbld** [comment]
Your personal pipeline request is at https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=92f54a7b-2135-4f01-b9d1-247681dfc16e

Target locations of links might be accessible only to IBM employees.

**Comment by contbld** [comment]
<h3>Code analysis and actions</h3>
DO NOT DELETE THIS COMMENT.

- 2 FAT files were changed, added, or removed.
 - Check that the build did not break the affected FAT suite(s).

- 3 test infrastructure code files were changed.
 - Test failures/errors in the build could be due to these changes.

**Comment by contbld** [comment]
https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=92f54a7b-2135-4f01-b9d1-247681dfc16e has errors/failures.

**Comment by contbld** [comment]
The build tjwatson-30105-20241108-1138
https://wasrtc.hursley.ibm.com:9443/jazz/resource/itemOid/com.ibm.team.build.BuildResult/_v3SlgJ28Ee-M9e5esDPP_g
completed and has errors or failures.

For help analyzing your personal build, go to https://libh-proxy1.fyre.ibm.com/cognitive/buildAnalysis.html?uuid=_v3SlgJ28Ee-M9e5esDPP_g

**Comment by contbld** [comment]
The build tjwatson-30105-20241109-0035
https://wasrtc.hursley.ibm.com:9443/jazz/resource/itemOid/com.ibm.team.build.BuildResult/_EhkBoJ5sEe-M9e5esDPP_g
completed and has errors or failures.

For help analyzing your personal build, go to https://libh-proxy1.fyre.ibm.com/cognitive/buildAnalysis.html?uuid=_EhkBoJ5sEe-M9e5esDPP_g

**Pull request merged**
