### PR TITLE
Verify a channel is closed before starting a new test

### LINKED ISSUE #14156: grpc: Ensure that a channel was closed before starting a new test

### PR DESCRIPTION
**Pull request by annaguri**
fixes #14156

### CODE REVIEW

**Comment by annaguri** [comment]
#build

**Review by wtlucy — APPROVED** [review]
LGTM

**Comment by annaguri** [comment]
#build

**Comment by annaguri** [comment]
#run-libby-bot

**Comment by annaguri** [comment]
the build failure is not related to the changes in this PR.

**Pull request merged**
