### PR TITLE
Rename new FT 3.0 projects to io.openliberty convention

### LINKED ISSUE #12568: FT 3.0: Rename projects to use io.openliberty prefix

### PR DESCRIPTION
**Pull request by Joseph-Cass**
Resolves #12568

### CODE REVIEW

**Comment by Joseph-Cass** [comment]
#build

**Comment by Joseph-Cass** [comment]
#build

**Comment by Joseph-Cass** [comment]
#build

**Comment by Joseph-Cass** [comment]
#build

**Comment by Joseph-Cass** [comment]
The tests that failed were unrelated to the changes made.

#run-libby-bot

**Comment by andrea-pichler** [comment]
No message review requested from L2

**Comment by Joseph-Cass** [comment]
#build

**Comment by Joseph-Cass** [comment]
#run-libby-bot

**Pull request merged**
