### PR TITLE
Make FT tests more reliable

### PR DESCRIPTION
**Pull request by Azquelt**
Improve reliability of two Fault Tolerance tests which have been failing in the build. Details in the commit messages.

Relates to RTC266894, RTC277266

### CODE REVIEW

**Comment by Azquelt** [comment]
#build

**Comment by Azquelt** [comment]
Hmm, The 2.0 TCK version of `AsynchronousTest` doesn't test `CompletionStage` behaviour (which was new in 2.0) but some of the test beans are shared between different tests and do have asynchronous methods which return `CompletionStage` so we can't use these tests to test FT 1.1

**Comment by Azquelt** [comment]
#build
#run-libby-bot

**Review by Emily-Jiang — APPROVED** [review]
LGTM!

**Review by benjamin-confino — APPROVED** [review]

**Pull request merged**
