### PR TITLE
Update to ASM 9.7 for Java 23

### PR DESCRIPTION
**Pull request by gjwatts**
This PR updates the current level of ASM from 9.6 (Java 22 support) to 9.7 (Java 23 support) for us to begin Java 23 testing.

### CODE REVIEW

**Comment by gjwatts** [comment]
#build

**Comment by gjwatts** [comment]
#build

**Comment by gjwatts** [comment]
#build

**Comment by gjwatts** [comment]
#build

**Review by tbitonti — APPROVED** [review]
I looked at just the second commit.

**Review by tbitonti — APPROVED** [review]
Reviewed the entire update.
I verified that anno (dev/com.ibm.ws.anno/src/com/ibm/ws/annocache/info/internal/ClassVisitorImpl_Info.java, for example), is coded to use the helper, so that usage is covered by this update.

**Review by jhanders34 — APPROVED** [review]

**Comment by jhanders34** [comment]
#libby

**Pull request merged**
