### PR TITLE
Issue 1186:Exclude the persistence and jpa FAT from running with Java 2 Security

### PR DESCRIPTION
**Pull request by daliasheasha**
Added some security permissions in the FATs server configuration. Some of the security permissions were already in the server.xml but they weren't being picked up because the derby jar was called derby-version.jar instead of just derby.jar so the config didn't apply. I changed the gradle script to rename the derby jar that was found to derby.jar. However after I tried merging my change, it turned out that Glenn Marcy already committed a change similar to mine so I took out my change to the gradle scripts.

### CODE REVIEW

**Comment by daliasheasha** [comment]
#build

**Comment by daliasheasha** [comment]
Fixes #1186

**Comment by daliasheasha** [comment]
I agree with Joe's comment. The java 2 security issues need to be investigated further. However, since the java 2 security builds are failing pretty badly, I will exclude the tests from running with java 2 security for now and open a tech debt work item to address the java 2 security issues.

**Comment by daliasheasha** [comment]
#build

**Comment by jgrassel** [comment]
Looks good to me, thanks!

**Comment by jgrassel** [comment]
A change I made in #1213 should fix the jpa_22_fat bucket running with java 2 sec on.  Can you change this pull request so it only prevents running the persistence service fat with java 2 security enabled?

**Comment by daliasheasha** [comment]
@jgrassel I removed the exclusion from the change set and updated the pull request as suggested.

**Comment by daliasheasha** [comment]
#build

**Comment by daliasheasha** [comment]
I submitted a separate personal build with java 2 security turned on: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_1EZl0NwqEeeC09PBLf7wmg

**Pull request merged**
