### PR TITLE
remove unused gRPC httpEndpoint config prop

### LINKED ISSUE #19348: gRPC server property "httpEndpoints" is invalid
**Describe the bug**  
The [gRPC Server Properties (grpc)](https://openliberty.io/docs/21.0.0.10/reference/config/grpc.html) reference a configuration property named `httpEndpoints`. This property has no effect.

**Steps to Reproduce**  
Configure a server.xml with `<grpc httpEndpoints="<valid_http_endpoint_ids>"/>` - gRPC requests will *not* be restricted to the specified endpoints, as described in the documentation.

**Expected behavior**  
The `httpEndpoints` property is invalid - and should not have been included in the Liberty metatype and documentation. The desired behavior of restricting a gRPC service to a particular endpoint(s) can be attained via [virtual hosts](https://openliberty.io/docs/21.0.0.10/virtual-hosts.html).

**Diagnostic information:**  
 - OpenLiberty Version: 20.0.0.12+
 - Affected feature(s) `grpc-1.0`
 - Java Version: N/A
 - server.xml configuration `<grpc httpEndpoints="<valid_http_endpoint_ids>"/>`

**Additional context**

### PR DESCRIPTION
**Pull request by wtlucy**
Fixes #19348

### CODE REVIEW

**Comment by wtlucy** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.grpc_fat

**Comment by wtlucy** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.grpc_fat

**Comment by wtlucy** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.grpc_fat

**Comment by wtlucy** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.grpc_fat

**Comment by wtlucy** [comment]
Combined build: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_vK0_gFaREeyWaZwSyDrk3A

**Comment by wtlucy** [comment]
#build

**Review by pnicolucci — APPROVED** [review]

**Comment by wtlucy** [comment]
OK, the metatype-validator-test-ignore in CL has been promoted to release, so this PR shouldn't cause any test failures now: #build

**Comment by wtlucy** [comment]
The last build had a (seemingly) unrelated BVT failure, trying again #build

**Comment by wtlucy** [comment]
#run-libby-bot

**Pull request merged**
