### PR TITLE
Add repeats on tests for mpTelemetry 2.0

### PR DESCRIPTION
**Pull request by Yas-Franco**
For issue #28090

- Zipkin dependencies have been updated
- The JaxRs Integration tests, TelemetryWithSpanErrorTest and TelemetryMultiAppTest are yet to be repeated for MpTelemetry-2.0 as there have been breaking changes to `io.opentelemetry.semconv.*` which is used in `io.openliberty.microprofile.telemetry.internal_fat.common/src/io/openliberty/microprofile/telemetry/internal_fat/shared/spans/AbstractSpanMatcher.java` [See here](https://github.com/OpenLiberty/open-liberty/blob/integration/dev/io.openliberty.microprofile.telemetry.internal_fat.common/src/io/openliberty/microprofile/telemetry/internal_fat/shared/spans/AbstractSpanMatcher.java#L21)

### CODE REVIEW

**Review by benjamin-confino — DISMISSED** [review]

**Comment by Yas-Franco** [comment]
#build
#spawn.fullfat.buckets=io.openliberty.microprofile.telemetry.1.0.internal_fat,io.openliberty.microprofile.telemetry.1.0.internal.container_fat,io.openliberty.microprofile.telemetry.1.0.internal_fat_tck,io.openliberty.microprofile.telemetry.1.1.internal_fat_tck

**Comment by Yas-Franco** [comment]
Building again after uploading the Zipin packages

#build
#spawn.fullfat.buckets=io.openliberty.microprofile.telemetry.1.0.internal_fat,io.openliberty.microprofile.telemetry.1.0.internal.container_fat,io.openliberty.microprofile.telemetry.1.0.internal_fat_tck,io.openliberty.microprofile.telemetry.1.1.internal_fat_tck

**Comment by Yas-Franco** [comment]
#build
#spawn.fullfat.buckets=io.openliberty.microprofile.telemetry.1.0.internal_fat,io.openliberty.microprofile.telemetry.1.0.internal.container_fat,io.openliberty.microprofile.telemetry.1.0.internal_fat_tck,io.openliberty.microprofile.telemetry.1.1.internal_fat_tck
#libby

**Comment by Yas-Franco** [comment]
#build
#spawn.fullfat.buckets=io.openliberty.microprofile.telemetry.1.0.internal_fat,io.openliberty.microprofile.telemetry.1.0.internal.container_fat,io.openliberty.microprofile.telemetry.1.0.internal_fat_tck,io.openliberty.microprofile.telemetry.1.1.internal_fat_tck
#libby

**Comment by Yas-Franco** [comment]
#build
#spawn.fullfat.buckets=io.openliberty.microprofile.telemetry.1.0.internal_fat,io.openliberty.microprofile.telemetry.1.0.internal.container_fat,io.openliberty.microprofile.telemetry.1.0.internal_fat_tck,io.openliberty.microprofile.telemetry.1.1.internal_fat_tck
#libby

**Review by benjamin-confino — APPROVED** [review]

**Comment by Yas-Franco** [comment]
#build

**Comment by Yas-Franco** [comment]
#libby

**Comment by Yas-Franco** [comment]
#libby
#build

**Comment by Yas-Franco** [comment]
#build

**Comment by Yas-Franco** [comment]
#libby

**Comment by Yas-Franco** [comment]
There is an unrelated test failure in the build

**Pull request merged**
