### PR TITLE
Update product and bundle version for release 19.0.0.10

### PR DESCRIPTION
**Pull request by tevans78**
This PR takes only the version update from https://github.com/OpenLiberty/open-liberty/pull/8868
The original PR also includes a revert that I don't know if we want or not.

### CODE REVIEW

**Comment by tevans78** [comment]
#build

**Comment by wraschke** [comment]
#build

**Comment by wraschke** [comment]
#build

**Comment by wraschke** [comment]
#build

**Comment by wraschke** [comment]
Hallelujah! The only test failure that occured in the latest and last PB is an existing one (defect 266843). It has nothing to do with this PR's changes. When the branch is unlocked, I will merge this PR.

**Pull request merged**
