### PR TITLE
Beta mpOpenAPI-4.0 and update API and TCK to RC3

### PR DESCRIPTION
**Pull request by Azquelt**

### CODE REVIEW

**Comment by Azquelt** [comment]
#build

**Comment by Azquelt** [comment]
Build failed because `io.openliberty.internal.versionless.mpOpenAPI-4.0` was not set to beta.

It looks like versionless as a whole has been moved to beta in #28674, so I think it's correct to move this one to beta as well.

**Comment by Azquelt** [comment]
#libby
#build

**Review by tevans78 — APPROVED** [review]
LGTM

**Comment by tevans78** [comment]
PB was green, 4.0 TCK was run and passed. Merging.

**Pull request merged**
