### PR TITLE
support old format of start-info

### LINKED ISSUE #23976: Add option to support old format of start-info in multipart/related SOAP messages
In Liberty versions prior to 22.0.0.8, the start-info in multipart-related was formatted as follows:
           start-info="application/soap+xml"; action="sendAttachment"
In new Liberty versions, the start-info attribute is formatted as follows:
           start-info="application/soap+xml; action=\"sendAttachment\""

Some existing Web services applications that rely on the old format of start-info are failing with exceptions like this:
javax.xml.ws.soap.SOAPFaultException: The given SOAPAction \"sendAttachment\"" does not match an operation.

Need an option to support old format of start-info attribute in multipart/related SOAP messages.

### PR DESCRIPTION
**Pull request by sawadood**
fixes #23976

### CODE REVIEW

**Comment by sawadood** [comment]
#build

**Review by neuwerk — APPROVED** [review]
LGTM

**Comment by sawadood** [comment]
The changes were tested by sending a test fix to customer and by running a personal build with these changes.

**Comment by sawadood** [comment]
#run-libby-bot

**Pull request merged**
