### PR TITLE
JSR375:delete unused messages.

### PR DESCRIPTION
**Pull request by toshiyamamoto**
There are a couple of message which are no longer used. This PR removes these messages to avoid some confusion that these messages would be logged some certain conditions.

### CODE REVIEW

**Comment by toshiyamamoto** [comment]
#build

**Comment by toshiyamamoto** [comment]
#build

**Comment by sishida** [comment]
Hello! Could you please confirm if this issue needs ID review or not? If it needs review, please add the "ID Required" label. If it does not need review, please add the "ID review not needed" label.

I am guessing that since this is a removal, ID review is not needed. However, I just wanted to ask to make sure. Thank you! :)

**Comment by toshiyamamoto** [comment]
Since the message file modification is removing a few messages, no ID review is required.

**Comment by toshiyamamoto** [comment]
this issue will be addressed by PR #1982

**Pull request closed without merging**
