### PR TITLE
Fix build issue with jsonb/jsonp tck using tmp directory

### PR DESCRIPTION
**Pull request by KyleAure**
#build

### CODE REVIEW

**Comment by KyleAure** [comment]
Need to re-build once build failures are resolved.

**Comment by KyleAure** [comment]
#build

**Comment by KyleAure** [comment]
SOE build on AIX: https://libh-proxy1.fyre.ibm.com/cognitive-dev/pipelineAnalysis.html?pipelineId=82d42b18-7a25-4626-a3c3-10b2196d6171

Target locations of links might be accessible only to IBM employees.

**Comment by KyleAure** [comment]
```
CI build 	: Had a post build failure, and test failure unrelated to change
RTC Build	: Had a post build failure, but all tests ran and passed
AIX Build	: Passed
```

**Review by tkburroughs — APPROVED** [review]

**Comment by KyleAure** [comment]
Ready to merge once our builds stabilize.

**Pull request merged**
