### PR TITLE
Enable testCDIManagedProperty for EE10

### PR DESCRIPTION
**Pull request by pnicolucci**
for #22368
for #22202

### CODE REVIEW

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
#libby

**Comment by pnicolucci** [comment]
#libby #build #spawn.fullfat.buckets=com.ibm.ws.jsf.2.3_fat,com.ibm.ws.jsfContainer_fat_2.3

**Review by volosied — APPROVED** [review]

**Pull request merged**
