### PR TITLE
Introduce personal build configuration and other needed properties files

### PR DESCRIPTION
**Pull request by wraschke**
#ol-pbbeta@dev

### CODE REVIEW

**Comment by wraschke** [comment]
#ol-pbbeta@dev

**Comment by wasbrdge** [comment]
I'm a sweet widdle boy!

#ol-pbbeta@dev

**Comment by wraschke** [comment]
#ol-pbbeta@dev

**Comment by wraschke** [comment]
#ol-pbbeta@dev

**Review by fritze2 — APPROVED** [review]
LGTM!

**Comment by wraschke** [comment]
#libby

**Comment by wraschke** [comment]
Ethan needs to merge this so he can gather his metrics and data. Thank you!

**Pull request merged**
