### PR TITLE
Clean up common warnings that come out of gradle and eclipse builds for most / all projects.

### PR DESCRIPTION
**Pull request by jhanders34**
- Use macros to remove warning message about artifactory properties
- Use version=! instead of version=0 to avoid warning messages.
- Remove bundle name warning messages related to transformed projects and fat test bundle names
- Remove privatepackage warning when a nlsprops file is marked as a private package when the package name includes .resources in it.
- Use def macro for variables that are not defined when running in an Eclipse environment.

### CODE REVIEW

**Comment by jhanders34** [comment]
#build

**Review by cbridgha — APPROVED** [review]
LGTM

**Comment by jhanders34** [comment]
#libby

**Comment by jhanders34** [comment]
#libby

**Pull request merged**
