### PR TITLE
mpTelemetry end to end test with Jaeger

### LINKED ISSUE #22032: MP Telemetry end to end test with Jaeger
- Run Jaeger in a test container
- Run a JAX-RS application in Liberty with mpTelemetry-1.0
- Check spans in Jaeger

### PR DESCRIPTION
**Pull request by fmhwong**
Fixes https://github.com/OpenLiberty/open-liberty/issues/22032

#build

### CODE REVIEW

**Review by Yas-Franco — APPROVED** [review]
LGTM

**Comment by fmhwong** [comment]
#build

**Comment by fmhwong** [comment]
#build

**Comment by fmhwong** [comment]
#build

**Comment by fmhwong** [comment]
#build

**Comment by fmhwong** [comment]
#build

**Comment by fmhwong** [comment]
#libby

**Comment by fmhwong** [comment]
#libby

**Comment by fmhwong** [comment]
#build

**Comment by fmhwong** [comment]
#libby

**Comment by fmhwong** [comment]
Tests passed.  Build failed for other reasons.

**Pull request merged**
