### PR TITLE
Jms fat cleanup

### PR DESCRIPTION
**Pull request by tbitonti**
FAT test update, only.  This Pull Requests does cleanups to recently delivered open messaging FAT tests:

* Missing FATRunner annotations were added.
* Missing ExpectedFFDC annotations were added.
* Removed ExpectedFFDC in one case.
* Small cleanups were made to the test source.

### CODE REVIEW

**Comment by tbitonti** [comment]
#build

**Comment by tbitonti** [comment]
#libby

**Comment by tbitonti** [comment]
#libby

**Comment by tbitonti** [comment]
#build

**Comment by tbitonti** [comment]
#libby

**Comment by tbitonti** [comment]
#build

**Review by AndrewDJBanks — APPROVED** [review]

**Review by ngmr — APPROVED** [review]
Looks good to me

**Comment by tbitonti** [comment]
#build

**Comment by tbitonti** [comment]
#libby

**Comment by tbitonti** [comment]
#build
#libby

**Comment by tbitonti** [comment]
#build
#libby

**Pull request merged**
