### PR TITLE
Servlet4FAT : expect server.xml apps to cause W messages during first…

### PR DESCRIPTION
**Pull request by mmulholl**
see issue text for a description.

### CODE REVIEW

**Comment by mmulholl** [comment]
link #697

**Comment by mmulholl** [comment]
Build running also with a CDOpen branch to remove Servlet4 FAT from CDOPen. This ensures that the open liberty versionsof the FAT bucket runs as part of the build.
Note: the only code change in the pull request is to the Servlet.4.0_fat bucket so if that buckets passes the fix is good.
https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_dXJWoLpaEeeqpdQxFPkl8Q

**Comment by pnicolucci** [comment]
Latest build here: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_8ue6ALpnEeeqpdQxFPkl8Q&tab=com.ibm.team.build.web.ui.internal.editors.result.properties.PropertiesProvider

**Comment by aguibert** [comment]
hi @pnicolucci and @mmulholl, we've reverted this PR since it seemed to have caused a hard break in the servlet 4.0 FAT.

I don't see how this PR could have caused the failures, but since this alteres the same FAT which is now failing and and pbuild links on this PR do not point to valid personal builds I'm considering that to be sufficient evidence for backout.

**Comment by aguibert** [comment]
this PR was reverted for a moment, and then we realized that a different PR (PR #649) was the real culrpit, so we've un-reverted this PR.

**Pull request merged**
