### PR TITLE
start after stop fails with localConnector feature on Windows

### LINKED ISSUE #25781: Liberty cannot be immediately restarted after stopping with localConnector-1.0 feature on Windows with hotspot
**Describe the bug**  
From version 23.0.0.1 onwards, when calling `server start <name>` immediately after `server stop <name>` completes on a running instance, the script wrongly responds that the server is already running. This worked fine in all previous releases but now fails every time, though it only appears to affect Windows and only when using the `localConnector-1.0` feature.
The server's termination appears to be delayed, as a subsequent call to start will succeed, or waiting ~1-2 seconds before calling start will also succeed.

```
Liberty\wlp\bin>server version
Open Liberty 23.0.0.1 (1.0.73.cl230120230123-2118) on OpenJDK 64-Bit Server VM, version 11.0.11+9 (en_GB)

Liberty\wlp\bin>server stop demo && server start demo
Stopping server demo.
Server demo stopped.
Server demo is already running. ### This shouldn't happen
```

```
Liberty\wlp_13\bin>server version
Open Liberty 22.0.0.13 (1.0.72.cl221320221205-1900) on OpenJDK 64-Bit Server VM, version 11.0.11+9 (en_GB)

Liberty\wlp_13\bin>server stop demo && server start demo
Stopping server demo.
Server demo stopped.
Starting server demo.
Server demo started.
```

**Steps to Reproduce**  
On Windows, create a server with a server.xml containing the `localConnector-1.0` feature:
```
<server description="demo server">
  <featureManager>
    <feature>localConnector-1.0</feature>
  </featureManager>
</server>
```
Call `server stop demo && server start demo`

**Expected behavior**  
The server stop command should only return once the process has terminated, the server start command should succeed when called immediately after server stop completes.

**Diagnostic information:**  
 - OpenLiberty Version: 23.0.0.1 to 23.0.0.6
 - Java Version: ```openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)```
 - Windows 10 22H2

**Additional context**  
Can't reproduce it on Ubuntu. The behaviour changed in 23.0.0.1 and it is still the same in 23.0.0.6, I've tested it with 22.0.0.12 and .13, which are both fine.

### PR DESCRIPTION
**Pull request by jimblye**
Fixes #25781

### CODE REVIEW

**Review by hlhoots — DISMISSED** [review]
LGTM

**Comment by jimblye** [comment]
#build

**Review by hlhoots — DISMISSED** [review]
These changes look okay to me.  Approved pending a FULL build to make sure this change doesnt effect other test cases.

**Review by tbitonti — APPROVED** [review]

**Comment by jimblye** [comment]
#build

**Comment by jimblye** [comment]
#libby

**Comment by jimblye** [comment]
#build

**Pull request merged**
