### PR TITLE
Fix app security test rule

### PR DESCRIPTION
**Pull request by tjwatson**

### CODE REVIEW

**Comment by tjwatson** [comment]
#build

**Comment by tjwatson** [comment]
@volosied you only need to review 79198193532f4ad6e717d1a3ac82ac6c0a04a0a1

**Review by anjumfatima90 — APPROVED** [review]

**Review by volosied — APPROVED** [review]
Looks fine to me. Where / how was this discovered?

**Comment by tjwatson** [comment]
> 

It was discovered when running our `org.openliberty.checkpoint_fat` bucket in FULL mode which includes a websocket test.  This is not something you can run locally unless you use RHEL Linux and have the necessary OpenJ9 Early Access build as well as the necessary CRIU installation.  We have a build queue setup that has the necessary prereqs and runs this: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewDefinition&id=_driBwMB2EeyMPMLKUarGFg

Currently the tests are failing because of the fix needed in the other commit in this PR.  But once that commit was done I started seeing exceptions from security manager in Liberty that reports missing doPrivs during the test run.

**Pull request merged**
