### PR TITLE
19783 serverconfig validation

### PR DESCRIPTION
**Pull request by aknguyen7**
Pull in Sarin's work for config server validation: Provide UI interface to Integrate validation api into admincenter.

### CODE REVIEW

**Comment by aknguyen7** [comment]
#build

**Comment by aknguyen7** [comment]
#build

**Comment by aknguyen7** [comment]
#build

**Comment by aknguyen7** [comment]
#build

**Comment by aknguyen7** [comment]
#build

**Comment by aknguyen7** [comment]
#build

**Comment by aknguyen7** [comment]
#build

**Comment by aknguyen7** [comment]
build for 11/15 completed with all ui tests passed
image

**Review by k8vance88 — APPROVED** [review]

**Comment by aknguyen7** [comment]
#run-libby-bot

**Pull request merged**
