### PR TITLE
add fallback to get oidc config from id token iss for bcl

### PR DESCRIPTION
**Pull request by jimmy1wu**
for https://github.com/OpenLiberty/open-liberty/issues/26615

### CODE REVIEW

**Comment by jimmy1wu** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.security.oidc.client_fat.backchannelLogout,com.ibm.ws.security.oidc.client_fat.backchannelLogout.saml,com.ibm.ws.security.oidc.server_fat.backchannelLogout,com.ibm.ws.security.social_fat.LibertyOP.backchannelLogout

**Comment by jimmy1wu** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.security.oidc.client_fat.backchannelLogout,com.ibm.ws.security.oidc.client_fat.backchannelLogout.saml,com.ibm.ws.security.oidc.server_fat.backchannelLogout,com.ibm.ws.security.social_fat.LibertyOP.backchannelLogout

**Comment by jimmy1wu** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.security.oidc.client_fat.backchannelLogout.1,com.ibm.ws.security.oidc.client_fat.backchannelLogout.2,com.ibm.ws.security.oidc.client_fat.backchannelLogout.saml.1,com.ibm.ws.security.oidc.client_fat.backchannelLogout.saml.2,com.ibm.ws.security.oidc.server_fat.backchannelLogout,com.ibm.ws.security.social_fat.LibertyOP.backchannelLogout.1,com.ibm.ws.security.social_fat.LibertyOP.backchannelLogout.2

**Comment by jimmy1wu** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.security.oidc.client_fat.backchannelLogout.1,com.ibm.ws.security.oidc.client_fat.backchannelLogout.2,com.ibm.ws.security.oidc.client_fat.backchannelLogout.saml.1,com.ibm.ws.security.oidc.client_fat.backchannelLogout.saml.2,com.ibm.ws.security.oidc.server_fat.backchannelLogout,com.ibm.ws.security.social_fat.LibertyOP.backchannelLogout.1,com.ibm.ws.security.social_fat.LibertyOP.backchannelLogout.2

**Review by ayoho — APPROVED** [review]

**Pull request merged**
