### PR TITLE
Add useSeparateSessionInvalidatorThreadPool httpSession property to false

### LINKED ISSUE #26805: Test Failure: com.ibm.ws.request.timing.hung.fat.HungRequestTiming.testHungRequestTiming_EE10_FEATURES
RTC 297153
Similar to https://github.com/OpenLiberty/open-liberty/issues/24590

```
testHungRequestTiming_EE10_FEATURES:java.lang.Throwable: 2023-09-05-13:36:06:170 There were 2 errors:
  java.io.IOException(Server returned HTTP response code: 500 for URL: http://localhost:8010/TestWebApp/TestServlet?sleepTime=290000)
  java.lang.Exception(Errors/warnings were found in server HungRequestTimingServer logs:
<br>[2023-09-05T13:36:01.489-0700] 0000002d com.ibm.ws.webcontainer.util.ApplicationErrorUtils           E SRVE0777E: Exception thrown by application class 'com.ibm.ws.session.http.AbstractHttpSession.isNew:218'
<br>[2023-09-05T13:36:01.921-0700] 0000002d com.ibm.ws.webcontainer.webapp                               E SRVE0315E: An exception occurred: java.lang.Throwable: java.lang.IllegalStateException: The method is called on an invalidated session: XkFY4vs3x-E-2PqK2BIBKpy)
at componenttest.custom.junit.runner.FATRunner.newThrowableWithTimeStamp(FATRunner.java:338)
at componenttest.custom.junit.runner.FATRunner.access$700(FATRunner.java:70)
at componenttest.custom.junit.runner.FATRunner$1.evaluate(FATRunner.java:304)
at componenttest.custom.junit.runner.FATRunner$2.evaluate(FATRunner.java:364)
at componenttest.custom.junit.runner.FATRunner.run(FATRunner.java:178)
at componenttest.rules.repeater.RepeatTests$CompositeRepeatTestActionStatement.evaluate(RepeatTests.java:145)
  java.io.IOException(Server returned HTTP response code: 500 for URL: http://localhost:8010/TestWebApp/TestServlet?sleepTime=290000)
  java.lang.Exception(Errors/warnings were found in server HungRequestTimingServer logs:
<br>[2023-09-05T13:36:01.489-0700] 0000002d com.ibm.ws.webcontainer.util.ApplicationErrorUtils           E SRVE0777E: Exception thrown by application class 'com.ibm.ws.session.http.AbstractHttpSession.isNew:218'
<br>[2023-09-05T13:36:01.921-0700] 0000002d com.ibm.ws.webcontainer.webapp                               E SRVE0315E: An exception occurred: java.lang.Throwable: java.lang.IllegalStateException: The method is called on an invalidated session: XkFY4vs3x-E-2PqK2BIBKpy)
at componenttest.custom.junit.runner.FATRunner$1.evaluate(FATRunner.java:204)
```

### PR DESCRIPTION
**Pull request by Channyboy**
#build
fixes #26805

### CODE REVIEW

**Comment by Channyboy** [comment]
#build

**Comment by Channyboy** [comment]
#build

**Review by pgunapal — APPROVED** [review]
LGTM

**Comment by Channyboy** [comment]
#libby

**Pull request merged**
