### PR TITLE
19878 improve batch jms executor startup sequencing

### PR DESCRIPTION
**Pull request by joe-chacko**

### CODE REVIEW

**Comment by joe-chacko** [comment]
#build

**Comment by joe-chacko** [comment]
#build again after further code changes

**Comment by joe-chacko** [comment]
A few minor tweaks, and some repository tidying.
#build #run-libby-bot

**Review by dmbelina — APPROVED** [review]
Approving based on what I understand that is going on with these DS changes at a high level, and how it resolves the issue.  Some of the nuances I don't grasp at the moment, but can chase that down later.  Noted that all the jms lite and full buckets passed also.

**Pull request merged**
