### PR TITLE
Fix java.security.egd JVM Property used by FATs

### PR DESCRIPTION
**Pull request by wtlucy**
for #16093

### CODE REVIEW

**Comment by wtlucy** [comment]
#build

**Comment by wtlucy** [comment]
personal build with a few different SOE platforms set: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_KxYTYHxaEeu8SN1zElUVXg

**Comment by wtlucy** [comment]
#build

**Comment by wtlucy** [comment]
#build

**Comment by wtlucy** [comment]
Windows and Java 8 tests: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_g8ipMN5eEeuED-bEVHmljA

**Comment by wtlucy** [comment]
z/OS build: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_vP4hEN5gEeuED-bEVHmljA

**Comment by wtlucy** [comment]
#build

**Comment by wtlucy** [comment]
Windows and Java 8 tests: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_BWgaAN_nEeuED-bEVHmljA

z/OS tests: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_GiFuEN_nEeuED-bEVHmljA

**Comment by wtlucy** [comment]
new windows / java 8 build: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_Tl3YcOM_EeuCcLcxc13g-w

**Comment by wtlucy** [comment]
new z/OS build: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_cveTIOQBEeuCcLcxc13g-w

**Comment by kristip17** [comment]
This appears to resolve the server startup issues I'm seeing in RTC 282634

**Comment by wtlucy** [comment]
rebase #build

**Comment by wtlucy** [comment]
rebase #build

**Comment by wtlucy** [comment]
#build

**Review by mhldr — APPROVED** [review]

**Comment by wtlucy** [comment]
#build

**Comment by wtlucy** [comment]
#run-libby-bot

**Pull request merged**
