### PR TITLE
jakarta security 3.0 fat cleanup

### PR DESCRIPTION
**Pull request by jimmy1wu**
various enhancements and cleanups to `io.openliberty.security.jakartasec.3.0.internal_fat.config` fat tests
- create expectation helpers for response status codes and msg's
- reduce redundancy in BaseCallbackServlet
- update jakarta oidc useNonce fat tests to have their own server config
- update jakarta oidc scope fat tests to have their own server config

### CODE REVIEW

**Comment by jimmy1wu** [comment]
#build
#spawn.fullfat.buckets=io.openliberty.security.jakartasec.3.0.internal_fat,
io.openliberty.security.jakartasec.3.0.internal_fat.config,
io.openliberty.security.jakartasec.3.0.internal_fat.logout,
io.openliberty.security.jakartasec.3.0.internal_fat.refresh

**Comment by jimmy1wu** [comment]
#build
#spawn.fullfat.buckets=io.openliberty.security.jakartasec.3.0.internal_fat,
io.openliberty.security.jakartasec.3.0.internal_fat.config,
io.openliberty.security.jakartasec.3.0.internal_fat.logout,
io.openliberty.security.jakartasec.3.0.internal_fat.refresh

**Comment by jimmy1wu** [comment]
#build
#spawn.fullfat.buckets=io.openliberty.security.jakartasec.3.0.internal_fat,
io.openliberty.security.jakartasec.3.0.internal_fat.config,
io.openliberty.security.jakartasec.3.0.internal_fat.logout,
io.openliberty.security.jakartasec.3.0.internal_fat.refresh

**Comment by jimmy1wu** [comment]
#libby
#build
#spawn.fullfat.buckets=io.openliberty.security.jakartasec.3.0.internal_fat,
io.openliberty.security.jakartasec.3.0.internal_fat.config,
io.openliberty.security.jakartasec.3.0.internal_fat.logout,
io.openliberty.security.jakartasec.3.0.internal_fat.refresh

**Review by c00crane — APPROVED** [review]

**Pull request merged**
