### PR TITLE
fix kdc fail-over logic

### PR DESCRIPTION
**Pull request by Zech-Hein**
updated to test the kdc connection getting a new ssh session. 
and also reduce the number of retries from 6 to 3 and reduce the wait time in-between retries from 10 seconds to 5.

### CODE REVIEW

**Comment by Zech-Hein** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.security.spnego_fat.1

**Comment by Zech-Hein** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.security.spnego_fat.1

**Review by utle — APPROVED** [review]

**Comment by Zech-Hein** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.security.spnego_fat.1

**Comment by Zech-Hein** [comment]
#libby

**Comment by Zech-Hein** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.security.spnego_fat.1

**Comment by wraschke** [comment]
#run-libby

**Comment by Zech-Hein** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.security.spnego_fat.1

**Comment by Zech-Hein** [comment]
java batch gui fat failure is unrelated to this change. all other tests passed.

**Pull request merged**
