### PR TITLE
Post archive to save logs on checkpoint fail tests

### PR DESCRIPTION
**Pull request by tjwatson**
- [x] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [x] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [x] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

### CODE REVIEW

**Comment by tjwatson** [comment]
#build

**Comment by contbld** [comment]
Your personal pipeline request is at https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=65182ea2-b20f-4d46-a094-b49697de8947

Target locations of links might be accessible only to IBM employees.

**Review by dazavala — APPROVED** [review]
Looks good.

**Comment by contbld** [comment]
<h3>Code analysis and actions</h3>
DO NOT DELETE THIS COMMENT.

- 1 FAT files were changed, added, or removed.
 - Check that the build did not break the affected FAT suite(s).

**Comment by contbld** [comment]
https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=65182ea2-b20f-4d46-a094-b49697de8947 completed successfully!

**Pull request merged**
