### PR TITLE
Make SSO FATs handle infrastructure issues better wrt junit reporting

### PR DESCRIPTION
**Pull request by c00crane**
When the SSO FATs run into problems obtaining LDAP servers they don't report junit results.  This yeilds no logs when the results are reported.  That makes it hard to debug.
Recently, there were issues with artifactory and there were no logs to pin down the issue.
The FATSuite sets up LDAP server references for the tests to use - this was failing causing the FATSuite to exit without running tests.
I'm adding a catch around "LocalLDAPServerSuite.setUpUsingServers".  We'll log the error and continue running tests.  Some FATs will be able to run some of the test classes that use a BasicRegistry and others will all fail.  But, we'll get results.
I'm also adding AlwaysPassesTest to FATSuites that do not already have it.  This will always produce junit results.

### CODE REVIEW

**Comment by c00crane** [comment]
#24505

**Comment by c00crane** [comment]
I also replaced use of AlwaysRunAndPassTest (from the common security fat project) with AlwaysPassesTest which is available to all FATs from fattest.simplicity

**Comment by c00crane** [comment]
#libby
#build

**Comment by c00crane** [comment]
Retry build - first attempt failed due to infrastructure issues
#build

**Review by ayoho — APPROVED** [review]

**Comment by c00crane** [comment]
#libby
#build

**Pull request merged**
