### PR TITLE
Added fault tolerance 2.1 TCK timeout multiplier for Liberty test builds

### PR DESCRIPTION
**Pull request by Joseph-Cass**
This in in FT2.0 and should be in FT2.1 too.

### CODE REVIEW

**Comment by Joseph-Cass** [comment]
#build

**Comment by Azquelt** [comment]
As best as I can tell, the failure in the build wasn't related to this change. However, the logs from the build are now gone.

The change looks good and non-controversial, so let's rebuild it and if we get another failure we can investigate further.

#build

**Comment by Joseph-Cass** [comment]
The build seemed to fail for 2 different reasons:
1. A known OpenJ9 issue causing a JIT compiler error. This seems to be occurring more frequently with the TCK timeout multiplier in however (from what we've sampled roughly 1 in 10 builds).

2. A one-off failure where the server seemed to stop responding for 5 minutes causing some some project build failures and hence some test failures.

For now whilst we're not having many issues from not having the multiplier included we're not going to merge this change. If not having the multiplier starts creating more frequent issues then we will choose the lesser of the two evils and merge this change.

**Comment by Joseph-Cass** [comment]
The Java version which the tests builds run against has been updated. Hopefully this will resolve our issue. Sending off another build:

#build

**Comment by Azquelt** [comment]
The change to the Java version has unfortunately been reverted.

**Comment by Joseph-Cass** [comment]
The change to the Java version has been re-implemented.

#build

**Comment by Joseph-Cass** [comment]
Build was abandoned. 

Trying another #build

**Comment by Azquelt** [comment]
#run-libby-bot

**Pull request merged**
