### PR TITLE
Issue #14289: Move WebSocket 2.0/CDI 3.0 autofeature to  beta

### LINKED ISSUE #14289: Set auto feature io.openliberty.cdi3.0-websocket2.0 to beta
Set /auto/io.openliberty.cdi3.0-websocket2.0.feature to beta 

Can you open an issue to get this put into beta once we get it delivered and into some builds? Assign it to me and I'll take care of getting it completed.

_Originally posted by @pnicolucci in https://github.com/OpenLiberty/open-liberty/pull/13092#r498379155_

### PR DESCRIPTION
**Pull request by pnicolucci**
fixes #14289

### CODE REVIEW

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Review by cbridgha — APPROVED** [review]
Looks good

**Comment by pnicolucci** [comment]
#run-libby-bot

**Pull request merged**
