### PR TITLE
Fix to missing class exception when using lambdas

### LINKED ISSUE #23610: Investigate java.lang.ClassNotFoundException in Faces-4.0
Enabling EE10 in tests, found an exception using faces-4.0 with an xhtml with the line `application implicit object test: <h:outputText id="out1" value="#{application.servletContextName}"/> ` . When accessing **application.servletContextName** hit the following exception.

> Exception thrown by application class 'jakarta.faces.webapp.FacesServlet.service:255'
> jakarta.servlet.ServletException: com.ibm.wsspi.webcontainer.facade.ServletContextFacade
> at jakarta.faces.webapp.FacesServlet.service(FacesServlet.java:255)
> at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1258)
> at [internal classes]
> Caused by: java.lang.NoClassDefFoundError: com.ibm.wsspi.webcontainer.facade.ServletContextFacade
> at .apply(Unknown Source)
> at org.apache.myfaces.el.resolver.LambdaBeanELResolver.getValue(LambdaBeanELResolver.java:75)
> at [internal classes]
> at jakarta.faces.component._DeltaStateHelper.eval(_DeltaStateHelper.java:339)
> at jakarta.faces.component.UIOutput.getValue(UIOutput.java:69)
> at org.apache.myfaces.renderkit.RendererUtils.getValue(RendererUtils.java:331)
> at org.apache.myfaces.renderkit.RendererUtils.getStringValue(RendererUtils.java:173)
> at org.apache.myfaces.renderkit.html.base.HtmlTextRendererBase.renderOutput(HtmlTextRendererBase.java:132)
> at org.apache.myfaces.renderkit.html.base.HtmlTextRendererBase.encodeEnd(HtmlTextRendererBase.java:122)
> at jakarta.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:634)
> at jakarta.faces.component.UIComponentBase.encodeAll(UIComponentBase.java:523)
> at jakarta.faces.component.UIComponentBase.encodeAll(UIComponentBase.java:519)
> at jakarta.faces.component.UIComponentBase.encodeAll(UIComponentBase.java:519)
> at jakarta.faces.component.UIComponentBase.encodeAll(UIComponentBase.java:519)
> at org.apache.myfaces.view.facelets.FaceletViewDeclarationLanguage.renderView(FaceletViewDeclarationLanguage.java:1778)
> ... 1 more
> Caused by: java.lang.ClassNotFoundException: com.ibm.wsspi.webcontainer.facade.ServletContextFacade cannot be found by com.ibm.ws.webcontainer.servlet.4.0.jakarta_1.0.72.202212020909
> ... 20 more

### PR DESCRIPTION
**Pull request by isaacrivriv**
fixes #23610

### CODE REVIEW

**Comment by isaacrivriv** [comment]
#build

**Review by volosied — DISMISSED** [review]
Per my update in the main issue, I think this is good.  
- 1)  I don't see how this can affect customers / produce regressions (It's implied that com.ibm.wsspi.webcontainer.facade should be accessible in this bundle ) 
- 2) Fixes the CNFE so things start to work again :) 

If we see similar problems again like this in future scenarios, we'll just need to evaluate whether new imports like this make sense on a case by case basis.

**Comment by isaacrivriv** [comment]
#build

**Review by volosied — APPROVED** [review]

**Comment by isaacrivriv** [comment]
#libby

**Review by pnicolucci — APPROVED** [review]

**Pull request merged**
