### PR TITLE
Port additional Social Fats

### PR DESCRIPTION
**Pull request by c00crane**
Port additional Fats to Open Liberty

### CODE REVIEW

**Comment by c00crane** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.security.social_fat,com.ibm.ws.security.social_fat.LibertyOP.1,com.ibm.ws.security.social_fat.LibertyOP.2,com.ibm.ws.security.social_fat.OpenShift,com.ibm.ws.security.social_fat.commonTest.LibertyOP,com.ibm.ws.security.social_fat.delegated,com.ibm.ws.security.social_fat.multiProvider,com.ibm.ws.security.social_fat.okdServiceLogin

**Comment by c00crane** [comment]
#run-libby-bot

**Comment by c00crane** [comment]
Updated terms in config

#run-libby-bot

Kicked off a new build: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_bqzOcJjJEeyylMvVD7B-oA

**Comment by c00crane** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.security.social_fat,com.ibm.ws.security.social_fat.delegated,com.ibm.ws.security.social_fat.LibertyOP.1,com.ibm.ws.security.social_fat.multiProvider,com.ibm.ws.security.social_fat.LibertyOP.2,com.ibm.ws.security.social_fat.OpenShift,com.ibm.ws.security.social_fat.okdServiceLogin
#run-libby-bot

**Comment by c00crane** [comment]
#run-libby-bot
#build
#spawn.fullfat.buckets=com.ibm.ws.security.social_fat,com.ibm.ws.security.social_fat.LibertyOP.1,com.ibm.ws.security.social_fat.LibertyOP.2,com.ibm.ws.security.social_fat.OpenShift,com.ibm.ws.security.social_fat.commonTest.LibertyOP,com.ibm.ws.security.social_fat.delegated,com.ibm.ws.security.social_fat.multiProvider,com.ibm.ws.security.social_fat.okdServiceLogin

**Review by ayoho — APPROVED** [review]

**Pull request merged**
