### PR TITLE
Read-write WLP-Platforms from feature manifests - take 2

### LINKED ISSUE #28570: Part2 of Versionless Support for WLP-Platform feature header for assigning platform to feature
This is the "internal API" part of #28203

### PR DESCRIPTION
**Pull request by jimblye**
Second try at fixes #28570

### CODE REVIEW

**Comment by jimblye** [comment]
#build

**Comment by jimblye** [comment]
#libby

**Review by hlhoots — APPROVED** [review]
LGTM to me pending a build

**Comment by jimblye** [comment]
#build

**Comment by jimblye** [comment]
#libby

**Comment by jimblye** [comment]
#build

**Comment by hlhoots** [comment]
#build

**Comment by hlhoots** [comment]
Good build. Merging.

**Pull request merged**
