### PR TITLE
Refactoring the tests to fix intermittent issue

### PR DESCRIPTION
**Pull request by tonyreigns**
- [x] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [x] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [x] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

Fixes: RTC 301311

### CODE REVIEW

**Review by pgunapal — APPROVED** [review]
LGTM

**Comment by tonyreigns** [comment]
#build

**Comment by tonyreigns** [comment]
#build
#spawn.fullfat.buckets=io.openliberty.microprofile.telemetry.2.0.logging.internal.container_fat,io.openliberty.microprofile.telemetry.2.0.logging.internal_fat

**Comment by tonyreigns** [comment]
Libby is a bit slow this morning or might be down.

Manually started a build: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_-0hvAFsPEe-nla_L9rYqvA

Manual pipeline build: https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?pipelineId=bffefe64-b9fd-4c24-ace8-b4f5126891de

SOE build with checkpoint: https://libh-proxy1.fyre.ibm.com/cognitive-dev/pipelineAnalysis.html?pipelineId=3fa7b7a5-a3b5-44bd-8549-e3d3ba4ac446

**Comment by pgunapal** [comment]
#build

**Pull request merged**
