### PR TITLE
Update swagger UI to 5.10.3

### LINKED ISSUE #24487: Update the swagger-ui dependency update action
The [last run](https://github.com/OpenLiberty/open-liberty/actions/runs/4295300293) of the action to update our swagger-ui dependency and rebuild the OpenAPI UI had several warnings about use of deprecated features which will be removed.

We should fix those.

It also looks like we should now be able to [output a nice summary](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#adding-a-job-summary).

### LINKED ISSUE #26948: Update Swagger-ui to latest version
Update Swagger-ui dependency to v5.

If this however is completely broken on IE 11, then attempt to use 4.19.2

We are now quite back level on Swagger-ui, including by a Major version.

As a pre-req for accessibility fixes we need to be on v5

### PR DESCRIPTION
**Pull request by abutch3r**
Update swagger UI 5.10.3 and update associated dependencies.

Update openapi-ui github action to work with Swagger-ui v5 and resolves node12 deprecations

Fixes [#26948](https://github.com/OpenLiberty/open-liberty/issues/26948)
Fixes [#24487](https://github.com/OpenLiberty/open-liberty/issues/24487)

### CODE REVIEW

**Comment by abutch3r** [comment]
#build
#spawn.fullfat.buckets=io.openliberty.microprofile.openapi.ui.internal_fat,com.ibm.ws.openapi.ui_fat

**Comment by Azquelt** [comment]
From the build results it looks like they have changed the way the lock icons are rendered such that the `button` element no longer gets the `locked` or `unlocked` class - instead the child svg element has this class. There's no obvious change in the way it appears so I think the test just needs updated to match.

From manual testing, the OAS version has disappeared. This looks to be due to it [having been moved to a separate component](https://github.com/swagger-api/swagger-ui/pull/9167). Our `simple-info.jsx` will need updating to include the new component as well. Also those elements [are in a `<span>` now](https://github.com/swagger-api/swagger-ui/pull/9264) in the upstream code.

**Comment by Azquelt** [comment]
#libby
#build
#spawn.fullfat.buckets=io.openliberty.microprofile.openapi.ui.internal_fat,com.ibm.ws.openapi.ui_fat

**Comment by abutch3r** [comment]
#libby
#build

**Comment by abutch3r** [comment]
## Open Liberty UI Manual Testing

Browser and version tested: Firefox 119.01

### MicroProfile UI
- [x] UI Loads on https://localhost:9443/openapi/ui/
- [x] Forced reload causes all resources to be reloaded
- [x] OpenLiberty logo is at the top of the page
- [x] Top of the page has the title and description for the application but no links
- [x] `OAS3` icon surrounding colour is `#5d8203` via element inspection
- [x] Footer is present
- [x] Footer contains links for `Terms of service`, `Test Author - Website`, `Contact Test Author` and `Example license`
- [x] No `Valid` button in footer
- Operation Block colours:
  - [x] POST background is `rgba(32,128,80,.1)` (div class = `opblock opblock-post`)
  - [x] POST border is `#208050` (div class = `opblock opblock-post`)
  - [x] POST Icon background colour is `#208050` (div class = `opblock-summary-method`)
  - [x] PUT background is `rgba(177,99,3,.1)` (div class = `opblock  opblock-put`)
  - [x] PUT border colour is `#b16303` (div class=`opblock-summary-method`)
  - [x] PUT Icon background colour is `#b16303` (div class=`opblock-summary-method`)
  - [x] DELETE background is `rgba(224,7,7,.1)` (div class = `opblock  opblock-delete`)
  - [x] DELETE border colour is `#e00707` (div class=`opblock-summary-method`)
  - [x] DELETE Icon background colour is `#e00707` (div class=`opblock-summary-method`)
  - [x] GET background is `rgba(31,111,240,.1)` (div class = `opblock  opblock-get`)
  - [x] GET border colour is `#1f6ff0` (div class=`opblock-summary-method`)
  - [x] GET Icon background colour is `#1f6ff0` (div class=`opblock-summary-method`)

### Openapi 3.x UI
Public UI
- [x] UI loads https://localhost:9443/api/explorer/
- [x] Forced reload causes all resources to be reloaded
- [x] OpenLiberty logo is at the top of the page
- [x] The Filter box is present at the top of the page
- [x] Filter using `openapi-ui-test-app`  of prefixes of returns the operations
- [x] Filter using anything other value returns no operations
- [x] Top of the Page has `Liberty REST APIs`
- [x] `OAS3` icon surrounding colour is `#5d8203` via element inspection
- [x] No `Valid` button in page footer
- Operation Block colours:
  - [x] POST background is `rgba(32,128,80,.1)` (div class = `opblock opblock-post`)
  - [x] POST border is #208050` (div class = `opblock opblock-post`)
  - [x] POST Icon background colour is `#208050` (div class = `opblock-summary-method`)
  - [x] PUT background is `rgba(177,99,3,.1)` (div class = `opblock  opblock-put`)
  - [x] PUT border colour is `#b16303` (div class=`opblock-summary-method`)
  - [x] PUT Icon background colour is `#b16303` (div class=`opblock-summary-method`)
  - [x] DELETE background is `rgba(224,7,7,.1)` (div class = `opblock  opblock-delete`)
  - [x] DELETE border colour is `#e00707` (div class=`opblock-summary-method`)
  - [x] DELETE Icon background colour is `#e00707` (div class=`opblock-summary-method`)
  - [x] GET background is `rgba(31,111,240,.1)` (div class = `opblock  opblock-get`)
  - [x] GET border colour is `#1f6ff0` (div class=`opblock-summary-method`)
  - [x] GET Icon background colour is `#1f6ff0` (div class=`opblock-summary-method`)

Private UI
- [x] UI load on https://localhost:9443/ibm/api/explorer/ having provided credentials outlined in README
- [x] Forced reload causes all resources to be reloaded
- [x] OpenLiberty logo is at the top of the page
- [x] The Filter box is present at the top of the page
- [x] Filter using `openapi-ui-test-app`  of prefixes of returns the operations
- [x] Filter using anything other value returns no operations
- [x] Top of the Page has `Liberty REST APIs`
- [x] `OAS3` icon surrounding colour is `#5d8203` via element inspection
- [x] No `Valid` button in page footer
- [x] Operation Block colours:
  - [x] POST background is `rgba(32,128,80,.1)` (div class = `opblock opblock-post`)
  - [x] POST border is #208050` (div class = `opblock opblock-post`)
  - [x] POST Icon background colour is `#208050` (div class = `opblock-summary-method`)
  - [x] PUT background is `rgba(177,99,3,.1)` (div class = `opblock  opblock-put`)
  - [x] PUT border colour is `#b16303` (div class=`opblock-summary-method`)
  - [x] PUT Icon background colour is `#b16303` (div class=`opblock-summary-method`)
  - [x] DELETE background is `rgba(224,7,7,.1)` (div class = `opblock  opblock-delete`)
  - [x] DELETE border colour is `#e00707` (div class=`opblock-summary-method`)
  - [x] DELETE Icon background colour is `#e00707` (div class=`opblock-summary-method`)
  - [x] GET background is `rgba(31,111,240,.1)` (div class = `opblock  opblock-get`)
  - [x] GET border colour is `#1f6ff0` (div class=`opblock-summary-method`)
  - [x] GET Icon background colour is `#1f6ff0` (div class=`opblock-summary-method`)

## Functionality Testing

### MicroProfile UI
Access https://localhost:9443/openapi/ui
- [x] Two Server values in Server dropdown
- Select `HTTPS` server url
- Expand `GET /{id}` operation
  - [x] Two responses - `200` and `404` displayed
  - Change `media type` in drop down
    - [x] Example changes from either JSON -> XML or XML->JSON
  - [x]  Can switch between `Example Value` and `Schema`
  - [x] Attempt to provide an ID value and should be prohibited from doing so
  - Click `Try Out`
    -  Provide an ID value of `1`
    - Click `Execute` and get a 
      -  [x] `200` response
    - Change ID value to `0`
    - Click `Execute`
     - [x] `404` response
- Expand `POST /private`
  - [x] Padlock Icon is `Unlocked`
  - Click `Try Out`
    - Click execute 
    - [x] `401` response
-  Click `Authorize` and go to `oauth` section
  - Provide `Client_id` provided in README
  - Provide `Client_secret` provided in README
  - Select Test Scope
  - Click `authorize`
    - Login with user credentials provided in README
    - click `allow once`
    - [x] returned to the OpenAPI UI
  - Close modal
- [x] All `/private*` operations now have a locked padlock
- Expand `POST /private` 
  - Click `Try Out`
  - [x] Click `Execute` and get a `200` response
- [x] Expand `GET /apiKeyNeeded`
  - [x] Padlock is `unlocked`
  - [x] Description is `Get a random record`
  - [x] Click Try Out
    - [x] Click Execute and get a `403` response
- Click `Authorize`
  - Enter apikey from README
  - Click `Authorize`
  - Close modal

### OpenAPI 3.x UI
Access https://localhost:9443/api/explorer
- [x] Two Server values in Server dropdown
- Select `HTTPS` server url
- Expand `GET /{id}` operation
  - [x] Two responses - `200` and `404` displayed
  - Change `media type` in drop down
    - [x] Example changes from either JSON -> XML or XML->JSON
  - [x]  Can switch between `Example Value` and `Schema`
  - [x] Attempt to provide an ID value and should be prohibited from doing so
  - Click `Try Out`
    -  Provide an ID value of `1`
    - Click `Execute` and get a 
      -  [x] `200` response
    - Change ID value to `0`
    - Click `Execute`
     - [x] `404` response
- Expand `POST /private`
  - [x] Padlock Icon is `Unlocked`
  - Click `Try Out`
    - Click execute 
    - [x] `401` response
-  Click `Authorize` and go to `oauth` section
  - Provide `Client_id` provided in README
  - Provide `Client_secret` provided in README
  - Select Test Scope
  - Click `authorize`
    - Login with user credentials provided in README
    - click `allow once`
    - [x] returned to the OpenAPI UI
  - Close modal
- [x] All `/private*` operations now have a locked padlock
- Expand `POST /private` 
  - Click `Try Out`
  - [x] Click `Execute` and get a `200` response
- [x] Expand `GET /apiKeyNeeded`
  - [x] Padlock is `unlocked`
  - [x] Description is `Get a random record`
  - [x] Click Try Out
    - [x] Click Execute and get a `403` response
- Click `Authorize`
  - Enter apikey from README
  - Click `Authorize`
  - Close modal
- Expand `/apiKeyNeeded`
  - [x] Operation has a locked padlock
  - Click `Try Out`
    - Click `Execute`
    -  [x] `200` response

## Customer provided customization

MicroProfile UI
- If the server is running, stop the server
- Rename the folder ` example-customization` in `src/main/liberty/config` to `mpopenapi`
- Start the server
- Access https://localhost:9443/openapi/ui/ 
  - Perform a forced page refresh
  - [x] Header bar colour has changed
  - [x] Logo has changed 

OpenAPI-3.x UI
- If the server is running, stop the server
- Rename the folder ` example-customization` (or mpopenapi if renamed for MicroProfile testing) in `src/main/liberty/config` to `openapi-3.1` 
- Start the server
- Access https://localhost:9443/api/explorer 
  - Perform a forced page refresh
  - [x] Header bar colour has changed
  - [x] Logo has changed 

## Endpoint customization
(Microprofile only)

- Update mpOpenAPI config with new `docPath`
- Start server
- Access https://localhost:9443/<docpath>/ui
- [x] Able to see page
- [x] Page shows api operations
- [x] Default UI customizations are in place
- Update mpOpenAPI config with different `uiPath`
- Update Oauth Provider config redirect path with uiPath value
- Start server
- Access https://localhost:9443/<uiPath>
- [x] Able to see page
- [x] Page shows api operations
-  Click `Authorize` and go to `oauth` section
  - Provide `Client_id` provided in README
  - Provide `Client_secret` provided in README
  - Select Test Scope
  - Click `authorize`
    - Login with user credentials provided in README
    - click `allow once`
    - [x] returned to the OpenAPI UI
  - Close modal

**Comment by abutch3r** [comment]
#libby
#build
#spawn.fullfat.buckets=io.openliberty.microprofile.openapi.ui.internal_fat,com.ibm.ws.openapi.ui_fat

**Comment by abutch3r** [comment]
> From the build results it looks like they have changed the way the lock icons are rendered such that the `button` element no longer gets the `locked` or `unlocked` class - instead the child svg element has this class. There's no obvious change in the way it appears so I think the test just needs updated to match.
> 
> From manual testing, the OAS version has disappeared. This looks to be due to it [having been moved to a separate component](https://github.com/swagger-api/swagger-ui/pull/9167). Our `simple-info.jsx` will need updating to include the new component as well. Also those elements [are in a `<span>` now](https://github.com/swagger-api/swagger-ui/pull/9264) in the upstream code.

Inspecting the behavior of the page, the issue is due to an initial load issue within Swagger-UI no longer adding the respective classes to the button element. If you cycle through a login and logout cycle you can see the `unlocked` and `locked` classes are assigned to the button, but only after that initial auth event. The SVG class is the most consistent element to now determine locked and unlocked behavior

**Comment by Azquelt** [comment]
1. We need to squash out all the irrelevant commits. There should be several commits for each of the code changes and then one commit to rebuild the UI.
2. I believe that we couldn't get the latest version of Swagger UI to work with IE 11? If so, we should remove all of the existing CSS rules and module transpilations which are only there to support IE 11.

**Comment by abutch3r** [comment]
#libby
#build
#spawn.fullfat.buckets=io.openliberty.microprofile.openapi.ui.internal_fat,com.ibm.ws.openapi.ui_fat

**Comment by abutch3r** [comment]
#libby
#build
#spawn.fullfat.buckets=io.openliberty.microprofile.openapi.ui.internal_fat,com.ibm.ws.openapi.ui_fat

**Comment by abutch3r** [comment]
CI failures relate solely to springboot tests, all the openapi tests and in particular the full fat selenium tests passed

**Review by Azquelt — APPROVED** [review]
This looks good, though in future I'd prefer to see the manual changes in separate commits from the code being rebuilt at the end.

Particularly in this case, we've committed two versions of the built JS in the repository history.

Still needs the manual test runs on the output of the personal build.

**Comment by abutch3r** [comment]
#build

**Comment by abutch3r** [comment]
> This looks good, though in future I'd prefer to see the manual changes in separate commits from the code being rebuilt at the end.
> 
> Particularly in this case, we've committed two versions of the built JS in the repository history.
> 
> Still needs the manual test runs on the output of the personal build.

The second set of changes to the JS relate to the changes allowed by the removal of packages for IE11. so was a result of those changes. but we shouldn't see the need to commit two versions of the js again

**Comment by abutch3r** [comment]
Manual testing of build image

Browser and version tested on: Firefox 120.0

### MicroProfile UI
- [x] UI Loads on https://localhost:9443/openapi/ui/
- [x] Forced reload causes all resources to be reloaded
- [x] OpenLiberty logo is at the top of the page
- [x] Top of the page has the title and description for the application but no links
- [x] `OAS3` icon surrounding colour is `#5d8203` via element inspection
- [x] Footer is present
- [x] Footer contains links for `Terms of service`, `Test Author - Website`, `Contact Test Author` and `Example license`
- [x] No `Valid` button in footer
- Operation Block colours:
    - [x] POST background is `rgba(32,128,80,.1)` (div class = `opblock opblock-post`)
    - [x] POST border is `#208050` (div class = `opblock opblock-post`)
    - [x] POST Icon background colour is `#208050` (div class = `opblock-summary-method`)
    - [x] PUT background is `rgba(177,99,3,.1)` (div class = `opblock  opblock-put`)
    - [x] PUT border colour is `#b16303` (div class=`opblock-summary-method`)
    - [x] PUT Icon background colour is `#b16303` (div class=`opblock-summary-method`)
    - [x] DELETE background is `rgba(224,7,7,.1)` (div class = `opblock  opblock-delete`)
    - [x] DELETE border colour is `#e00707` (div class=`opblock-summary-method`)
    - [x] DELETE Icon background colour is `#e00707` (div class=`opblock-summary-method`)
    - [x] GET background is `rgba(31,111,240,.1)` (div class = `opblock  opblock-get`)
    - [x] GET border colour is `#1f6ff0` (div class=`opblock-summary-method`)
    - [x] GET Icon background colour is `#1f6ff0` (div class=`opblock-summary-method`)
- Operation Details
    - Expand `GET /{id}
      - [x] `id` file is marked `* required`


### Openapi 3.x UI
Public UI
- [x] UI loads https://localhost:9443/api/explorer/
- [x] Forced reload causes all resources to be reloaded
- [x] OpenLiberty logo is at the top of the page
- [x] The Filter box is present at the top of the page
- [x] Filter using `openapi-ui-test-app`  of prefixes of returns the operations
- [x] Filter using any other value returns no operations
- [x] Top of the Page has `Liberty REST APIs`
- [x] `OAS3` icon surrounding colour is `#5d8203` via element inspection
- [x] No `Valid` button in page footer
- Operation Block colours:
    - [x] POST background is `rgba(32,128,80,.1)` (div class = `opblock opblock-post`)
    - [x] POST border is `#208050` (div class = `opblock opblock-post`)
    - [x] POST Icon background colour is `#208050` (div class = `opblock-summary-method`)
    - [x] PUT background is `rgba(177,99,3,.1)` (div class = `opblock  opblock-put`)
    - [x] PUT border colour is `#b16303` (div class=`opblock-summary-method`)
    - [x] PUT Icon background colour is `#b16303` (div class=`opblock-summary-method`)
    - [x] DELETE background is `rgba(224,7,7,.1)` (div class = `opblock  opblock-delete`)
    - [x] DELETE border colour is `#e00707` (div class=`opblock-summary-method`)
    - [x] DELETE Icon background colour is `#e00707` (div class=`opblock-summary-method`)
    - [x] GET background is `rgba(31,111,240,.1)` (div class = `opblock  opblock-get`)
    - [x] GET border colour is `#1f6ff0` (div class=`opblock-summary-method`)
    - [x] GET Icon background colour is `#1f6ff0` (div class=`opblock-summary-method`)

Private UI
- [x] UI load on https://localhost:9443/ibm/api/explorer/ having provided credentials outlined in README
- [x] Forced reload causes all resources to be reloaded
- [x] OpenLiberty logo is at the top of the page
- [x] The Filter box is present at the top of the page
- [x] Filter using `openapi-ui-test-app`  of prefixes of returns the operations
- [x] Filter using any other value returns no operations
- [x] Top of the Page has `Liberty REST APIs`
- [x] `OAS3` icon surrounding colour is `#5d8203` via element inspection
- [x] No `Valid` button in page footer
- Operation Block colours:
    - [x] POST background is `rgba(32,128,80,.1)` (div class = `opblock opblock-post`)
    - [x] POST border is #208050` (div class = `opblock opblock-post`)
    - [x] POST Icon background colour is `#208050` (div class = `opblock-summary-method`)
    - [x] PUT background is `rgba(177,99,3,.1)` (div class = `opblock  opblock-put`)
    - [x] PUT border colour is `#b16303` (div class=`opblock-summary-method`)
    - [x] PUT Icon background colour is `#b16303` (div class=`opblock-summary-method`)
    - [x] DELETE background is `rgba(224,7,7,.1)` (div class = `opblock  opblock-delete`)
    - [x] DELETE border colour is `#e00707` (div class=`opblock-summary-method`)
    - [x] DELETE Icon background colour is `#e00707` (div class=`opblock-summary-method`)
    - [x] GET background is `rgba(31,111,240,.1)` (div class = `opblock  opblock-get`)
    - [x] GET border colour is `#1f6ff0` (div class=`opblock-summary-method`)
    - [x] GET Icon background colour is `#1f6ff0` (div class=`opblock-summary-method`)

## Functionality Testing

### MicroProfile UI
Access https://localhost:9443/openapi/ui
- [x] Two Server values in Server dropdown
- Select `HTTPS` server url
- Expand `GET /{id}` operation
    - [x] Two responses - `200` and `404` displayed
    - Change `media type` in drop down
        - [x] Example changes from either JSON -> XML or XML->JSON
    - [x]  Can switch between `Example Value` and `Schema`
    - [x] Attempt to provide an ID value and should be prohibited from doing so
    - Click `Try Out`
        -  Provide an ID value of `1`
        - Click `Execute` and get a
          -  [x] `200` response
        - Change ID value to `0`
        - Click `Execute`
          - [x] `404` response
- Expand `POST /private`
    - [x] Padlock Icon is `Unlocked`
    - Click `Try Out`
      - Click execute
        - [x] `401` response
- Click `Authorize` and go to `oauth` section
- Provide `Client_id` provided in README
- Provide `Client_secret` provided in README
- Select Test Scope
- Click `authorize`
    - Login with user credentials provided in README
    - click `allow once`
    - [x] returned to the OpenAPI UI
- Close modal
- [x] All `/private*` operations now have a locked padlock
- Expand `POST /private`
    - Click `Try Out`
    - [x] Click `Execute` and get a `200` response
- [x] Expand `GET /apiKeyNeeded`
    - [x] Padlock is `unlocked`
    - [x] Description is `Get a random record`
    - [x] Click Try Out
        - [x] Click Execute and get a `403` response
- Click `Authorize`
    - Enter apikey from README
    - Click `Authorize`
    - Close modal
- Expand /apiKeyNeeded
    - [x]  Operation has a locked padlock
    - Click Try Out
    - Click Execute
      - [x] 200 response


### OpenAPI 3.x UI
Access https://localhost:9443/api/explorer
- [x] Two Server values in Server dropdown
- Select `HTTPS` server url
- Expand `GET /{id}` operation
    - [x] Two responses - `200` and `404` displayed
    - Change `media type` in drop down
        - [x] Example changes from either JSON -> XML or XML->JSON
    - [x]  Can switch between `Example Value` and `Schema`
    - [x] Attempt to provide an ID value and should be prohibited from doing so
    - Click `Try Out`
        -  Provide an ID value of `1`
        - Click `Execute` and get a
            -  [x] `200` response
        - Change ID value to `0`
        - Click `Execute`
        - [x] `404` response
- Expand `POST /private`
    - [x] Padlock Icon is `Unlocked`
    - Click `Try Out`
        - Click execute
        - [x] `401` response
-  Click `Authorize` and go to `oauth` section
- Provide `Client_id` provided in README
- Provide `Client_secret` provided in README
- Select Test Scope
- Click `authorize`
    - Login with user credentials provided in README
    - click `allow once`
    - [x] returned to the OpenAPI UI
- Close modal
- [x] All `/private*` operations now have a locked padlock
- Expand `POST /private`
    - Click `Try Out`
    - [x] Click `Execute` and get a `200` response
- [x] Expand `GET /apiKeyNeeded`
    - [x] Padlock is `unlocked`
    - [x] Description is `Get a random record`
    - [x] Click Try Out
        - [x] Click Execute and get a `403` response
- Click `Authorize`
    - Enter apikey from README
    - Click `Authorize`
    - Close modal
- Expand `/apiKeyNeeded`
    - [x] Operation has a locked padlock
    - Click `Try Out`
        - Click `Execute`
        -  [x] `200` response

## Customer provided customization

MicroProfile UI
- If the server is running, stop the server
- Rename the folder ` example-customization` in `src/main/liberty/config` to `mpopenapi`
- Start the server
- Access https://localhost:9443/openapi/ui/
    - Perform a forced page refresh
    - [x] Header bar colour has changed
    - [x] Logo has changed

OpenAPI-3.x UI
- If the server is running, stop the server
- Rename the folder ` example-customization` (or mpopenapi if renamed for MicroProfile testing) in `src/main/liberty/config` to `openapi-3.1`
- Start the server
- Access https://localhost:9443/api/explorer
    - Perform a forced page refresh
    - [x] Header bar colour has changed
    - [x] Logo has changed

## Endpoint customization
(Microprofile only)

- Update mpOpenAPI config with new `docPath`
- Start server
- Access https://localhost:9443/<docpath>/ui
- [x] Able to see page
- [x] Page shows api operations
- [x] Default UI customizations are in place
- Update mpOpenAPI config with different `uiPath`
- Update Oauth Provider config redirect path with uiPath value
- Start server
- Access https://localhost:9443/<uiPath>
- [x] Able to see page
- [x] Page shows api operations
-  Click `Authorize` and go to `oauth` section
- Provide `Client_id` provided in README
- Provide `Client_secret` provided in README
- Select Test Scope
- Click `authorize`
    - Login with user credentials provided in README
    - click `allow once`
    - [x] returned to the OpenAPI UI
- Close modal

**Comment by abutch3r** [comment]
RTC and CI build failures do not relate at all to openapi and in particular the UI

**Pull request merged**
