### PR TITLE
Add MP 7 repeats to Health FATs

### PR DESCRIPTION
**Pull request by tevans78**
Repeat MP Health tests with MP 7 on EE10 and 11

### CODE REVIEW

**Comment by tevans78** [comment]
#build

**Review by tonyreigns — DISMISSED** [review]
LGTM

**Comment by tevans78** [comment]
#build

**Review by tonyreigns — DISMISSED** [review]
LGTM

**Comment by tevans78** [comment]
#build
Forgot to investigate the failure here so running a new PB

**Comment by tevans78** [comment]
#build

**Review by tonyreigns — APPROVED** [review]
LGTM

**Comment by tevans78** [comment]
#libby

**Pull request merged**
