### PR TITLE
Wait for SSL initialization to complete before running tests

### PR DESCRIPTION
**Pull request by andymc12**
Fixes MP Rest Client tests that use SSL - on some build machines the SSL components do not initialize until after the server has declared that it is ready to serve requests. This results in tests starting too soon resulting in SSL errors.

UPDATE: Adding related changes that add a more lenient hostname verifier to avoid JDK behavior differences wrt cert hostname ("localhost" vs "cn=localhost", etc.).

### CODE REVIEW

**Comment by andymc12** [comment]
#build

**Comment by andymc12** [comment]
#build

**Comment by andymc12** [comment]
#build

**Review by jkoehler22 — APPROVED** [review]

**Comment by andymc12** [comment]
#libby

**Pull request merged**
