### PR TITLE
Increase trace for artifact FATs.

### PR DESCRIPTION
**Pull request by tbitonti**
Trace update for RTC 296004.

The trace which is currently generated is not sufficient to diagnose the problem.

This update is an attempt to gather sufficient trace.  This may be a temporary update.

### CODE REVIEW

**Comment by tbitonti** [comment]
#build

**Review by cbridgha — APPROVED** [review]
Looks good

**Comment by tbitonti** [comment]
#build

**Comment by tbitonti** [comment]
Closing; included in:
https://github.com/OpenLiberty/open-liberty/pull/25945

**Pull request closed without merging**
