### PR TITLE
Allow expired token during short token prep method call

### PR DESCRIPTION
**Pull request by c00crane**
Update method shortTokenLifetimePrep to allow message, CWWKS1617E. This method is used in test classes that use short lived tokens - the first token issued is a little slow, so, the call in this method will encounter the issue and not a test case. So, we need to account for this method getting a token that is expired before we try to use it - if the token is expired, we can get message CWWKS1617E.

### CODE REVIEW

**Comment by c00crane** [comment]
#build
#spawn.fullfat.buckets=io.openliberty.security.jakartasec.3.0.internal_fat,io.openliberty.security.jakartasec.3.0.internal_fat.config.1,io.openliberty.security.jakartasec.3.0.internal_fat.config.2,io.openliberty.security.jakartasec.3.0.internal_fat.logout,io.openliberty.security.jakartasec.3.0.internal_fat.refresh

**Comment by c00crane** [comment]
#libby

**Review by teddyjtorres — APPROVED** [review]

**Comment by c00crane** [comment]
#build
#spawn.fullfat.buckets=io.openliberty.security.jakartasec.3.0.internal_fat,io.openliberty.security.jakartasec.3.0.internal_fat.config.1,io.openliberty.security.jakartasec.3.0.internal_fat.config.2,io.openliberty.security.jakartasec.3.0.internal_fat.logout,io.openliberty.security.jakartasec.3.0.internal_fat.refresh

**Comment by c00crane** [comment]
#build
#spawn.fullfat.buckets=io.openliberty.security.jakartasec.3.0.internal_fat,io.openliberty.security.jakartasec.3.0.internal_fat.config.1,io.openliberty.security.jakartasec.3.0.internal_fat.config.2,io.openliberty.security.jakartasec.3.0.internal_fat.logout,io.openliberty.security.jakartasec.3.0.internal_fat.refresh
#libby

**Review by teddyjtorres — APPROVED** [review]

**Pull request merged**
