### PR TITLE
add WebSphere Liberty swidtag

### PR DESCRIPTION
**Pull request by bensonlatibm**
Add ilmt tags for tracking open liberty deployments

### CODE REVIEW

**Comment by bensonlatibm** [comment]
#build

**Comment by bensonlatibm** [comment]
#run-libby-bot

**Comment by bensonlatibm** [comment]
failures in build are unrelated to these changes.

**Review by hermankailey — APPROVED** [review]

**Comment by bensonlatibm** [comment]
tested via running pb and manually verified tag was laid down.

**Pull request merged**
