### PR TITLE
Update container images (database)

### PR DESCRIPTION
**Pull request by KyleAure**
- [x] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [x] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [x] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

321a05b0b4 chore: update postgre container from 14.1 -> 17.0
52a601b8f0 chore: update db2 container from kyleaure/db2 -> icr.io/db2_community/db2
d074e8854c chore: update sqlserver container from 2019-CU18-ubuntu-20.04 -> 2019-CU28-ubuntu-20.04
94efa5d574 doc: add property to check if running on AWS network

### CODE REVIEW

**Comment by KyleAure** [comment]
#build - personal build
#libby - header check

**Comment by KyleAure** [comment]
Database pipeline is at https://libh-proxy1.fyre.ibm.com/cognitive-dev/pipelineAnalysis.html?pipelineId=c01baee7-3cdb-4767-9fcc-cf10d50ce393

Target locations of links might be accessible only to IBM employees.

**Comment by KyleAure** [comment]
AWS SOE pipeline (without changes): https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=b3e66973-27b3-4992-b219-431000f53b5e

AWS SOE pipeline (with changes): https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?pipelineId=6c562daa-8e5a-4c62-93de-5e21ffbfe9c8

Target locations of links might be accessible only to IBM employees.

**Comment by KyleAure** [comment]
## Build results

Personal pipeline: 1 known defect, and one timing defect in unrelated bucket.
Personal RTC Build: [In progress]
Database rotation: Failed with expected defects, DB2 timeout insufficient for new version, increase to 25 minutes.
AWS SOE (unchanged): Failed to start SQLServer database as expected.
AWS SOE (with changes): IMPOSSIBLE

**Review by mswatosh — DISMISSED** [review]

**Review by jmstephensgit — DISMISSED** [review]

**Comment by KyleAure** [comment]
#build - re-do personal build
#libby - check headers

The AWS SOE build is impossible due to our current test infrastructure.  If this personal build passes, merge, and verify during the next SOE that the fix worked.

**Comment by KyleAure** [comment]
#build - personal build
#libby - re-check headers

**Comment by KyleAure** [comment]
Pipeline: Failed with 1 intermittent defect
RTC: Failed with 1 existing defect

Ready to merge on re-review

**Review by mswatosh — APPROVED** [review]

**Pull request merged**
