### PR TITLE
identifyException as StaleStatement/AuthenticationError/Unsupported

### PR DESCRIPTION
**Pull request by njr-11**
Add StaleStatement, AuthenticationError, and Unsupported as a types of exceptions that can be identified via the identifyException configuration element.

### CODE REVIEW

**Comment by njr-11** [comment]
#build

**Comment by njr-11** [comment]
#build

**Comment by njr-11** [comment]
#build

**Comment by njr-11** [comment]
#build

**Review by nmittles — APPROVED** [review]

**Comment by njr-11** [comment]
The previous build was perfectly good (no failures at all). However, due to changes to Liberty builds, we have been asked to rebase all changes and submit new builds:
#build
#run-libby-bot

**Comment by njr-11** [comment]
All tests passed in the latest run.  One did not start due to an infrastructure issue, however, the commits were also under #16319 where all tests passed and when that was merged it implicitly merged this pull too.

**Pull request merged**
