### PR TITLE
Changes to deliver EclipseLink 5.0.0-B04

### PR DESCRIPTION
**Pull request by anija-anil**
Changes to deliver EclipseLink 5.0.0-B04

### CODE REVIEW

**Comment by anija-anil** [comment]
#build

**Review by ajaypaul-ibm — DISMISSED** [review]

**Comment by anija-anil** [comment]
#build

**Comment by anija-anil** [comment]
#libby
#build

**Comment by anija-anil** [comment]
#build

**Comment by anija-anil** [comment]
#build

**Comment by anija-anil** [comment]
#libby
#build

**Comment by anija-anil** [comment]
#build

**Comment by anija-anil** [comment]
#build ([view Open Liberty Personal Build](https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?pipelineId=b60150df-71f2-417b-b139-41974c524d65) - :white_check_mark: completed successfully!)

**Review by ajaypaul-ibm — APPROVED** [review]

**Pull request merged**
