### PR TITLE
Remove legacy JET logging code

### PR DESCRIPTION
**Pull request by jonhawkes**
#build

### CODE REVIEW

**Comment by jonhawkes** [comment]
#build
#run-libby-bot

**Comment by jonhawkes** [comment]
#build
#run-libby-bot

**Comment by jonhawkes** [comment]
#build

**Comment by jonhawkes** [comment]
#build
#run-libby-bot

**Comment by jonhawkes** [comment]
#build

**Comment by jonhawkes** [comment]
#build

**Comment by jonhawkes** [comment]
fixes #17437

**Comment by jonhawkes** [comment]
#build

**Review by neilgsyoung — APPROVED** [review]
Looks good

**Comment by jonhawkes** [comment]
#run-libby-bot
#build

**Comment by jonhawkes** [comment]
#build

**Comment by jonhawkes** [comment]
#run-libby-bot
#build

**Pull request merged**
