### PR TITLE
Issue #14316: Add WLP-AlsoKnownAs to faces-3.0 feature

### LINKED ISSUE #14316: Add WLP-AlsoKnownAs: jsf-3.0 to the faces-3.0 feature
Add WLP-AlsoKnownAs: jsf-3.0 to the faces-3.0 feature

Adding this shows the following in the logs:

> [AUDIT   ] CWWKE0001I: The server test has been launched.
> [ERROR   ] CWWKF0001E: A feature definition could not be found for jsf-3.0
> [ERROR   ] CWWKF0045E: An existing feature definition, faces-3.0, is a possible match for the jsf-3.0 feature that was not found.

### PR DESCRIPTION
**Pull request by pnicolucci**
fixes #14316

### CODE REVIEW

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
PB:https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_1BXKkAdTEeuIgpJAZoWiKQ

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#run-libby-bot

**Review by volosied — APPROVED** [review]
Approved.  I also didn't know this attribute existed. That's really nice!

**Pull request merged**
