### PR TITLE
Enable ajax tests with myfaces 4.0-rc4

### LINKED ISSUE #20812: Faces 4.0: <f:ajax> execute="@this" and render="@this" does not behave as expected when nested in composite component
User story:
As a user of Open Liberty and the faces-4.0 feature, I want to be able to create asynchronously execute and render nested composite components that work as expected by the specification.  That means that the entire component should be re-rendered, not just the individual form element that was interacted with.  

Known issue: https://issues.apache.org/jira/projects/MYFACES/issues/MYFACES-4505?filter=allopenissues
MyFaces is still executing only individual components within the composite component, due to a known bug.

Spec issue: `https://github.com/jakartaee/faces/issues/1567`

See: https://balusc.omnifaces.org/2021/11/whats-new-in-faces-40.html

### PR DESCRIPTION
**Pull request by KyleAure**
Fixes #20812

### CODE REVIEW

**Comment by KyleAure** [comment]
#build

**Comment by KyleAure** [comment]
#build

**Comment by KyleAure** [comment]
#libby - recheck headers

**Comment by KyleAure** [comment]
#build - rebuild hit filesystem error

**Review by volosied — APPROVED** [review]
Looks good to me

**Comment by pnicolucci** [comment]
#build

**Review by pnicolucci — APPROVED** [review]

**Pull request merged**
