### PR TITLE
Telemetry fat repeats

### PR DESCRIPTION
**Pull request by tonyreigns**
- [x] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [x] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [x] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

Previous PR: #29378

### CODE REVIEW

**Comment by tonyreigns** [comment]
#build

**Comment by tonyreigns** [comment]
Doesn't look like a pipeline was started, starting another build in case.

#build

**Comment by tonyreigns** [comment]
The original build didn't start a pipeline build, possibly due to Git slowdown yesterday.

The RTC build passed but didn't run the tests in FULL mode. I started an [SOE pipeline](https://libh-proxy1.fyre.ibm.com/cognitive-dev/pipelineAnalysis.html?pipelineId=bc723e95-0258-488e-b69c-d6a3884b7d75&tab=Tests) to test the checkpoint repeats and that build ran both buckets in FULL mode and passed however there were 3 errors in checkpoint. These errors are likely stemming from the the SkipForRepeats as there's one repeat we need to skip but the test format may have caused issues. Investigating this now.

The second build I started isn't complete but the pipeline build ran all our tests in lite and full mode and everything's passing successfully. There was one test that failed intermittently in 2/60 bucket runs which we'll investigate now. Aside from these two minor issues, the builds were successful.

**Comment by tonyreigns** [comment]
I've identified the issue causing the intermittent failure, looking for a fix now, it's only a test bug.

**Review by pgunapal — DISMISSED** [review]
Looks good

**Review by pgunapal — APPROVED** [review]

**Pull request merged**
