### PR TITLE
Port MYFACES-4505, & MYFACES-4532

### LINKED ISSUE #23958: Port MYFACES-4505 & MYFACES-4532
https://issues.apache.org/jira/browse/MYFACES-4505
https://issues.apache.org/jira/browse/MYFACES-4532

### PR DESCRIPTION
**Pull request by volosied**
fixes #23958

### CODE REVIEW

**Comment by volosied** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jsf.2.2_fat,com.ibm.ws.jsf.2.3_fat,com.ibm.ws.jsf_fat,io.openliberty.org.apache.myfaces.4.0_fat

**Comment by volosied** [comment]
removed MYFACES-4550 from the PR as the community is asking for further updates to it

**Comment by volosied** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jsf.2.2_fat,com.ibm.ws.jsf.2.3_fat,com.ibm.ws.jsf_fat,io.openliberty.org.apache.myfaces.4.0_fat

**Review by pnicolucci — APPROVED** [review]

**Comment by pnicolucci** [comment]
#libby

**Pull request merged**
