### PR TITLE
no longer get invocation subject

### PR DESCRIPTION
**Pull request by acdemyers**
Remove code that gets the invocation subject, leaving it to just get the caller subject.

### CODE REVIEW

**Comment by acdemyers** [comment]
#build

**Comment by acdemyers** [comment]
#build

**Comment by teddyjtorres** [comment]
Hi Alaine. The classpath you have is specific to your machine. Any dependency should be specified in the bnd.bnd file instead.

**Comment by acdemyers** [comment]
#build

**Comment by acdemyers** [comment]
#fixes 1736

**Pull request merged**
