### PR TITLE
Check cache instance is closed due to shutting down

### PR DESCRIPTION
**Pull request by zhang-ca**
Protect any calls to sessionMetaCache methods in CacheHashMap.performInvalidation()

//Process the non-listener sessions first
doInvalidations();

//Read in all the sessions with listeners that need to be invalidated
processInvalidListeners();

### CODE REVIEW

**Comment by zhang-ca** [comment]
fixes #22221

**Comment by zhang-ca** [comment]
for #22221

**Comment by zhang-ca** [comment]
#build

**Review by bensonlatibm — APPROVED** [review]
lgtm!

**Pull request merged**
