### PR TITLE
Switch EE 11 features, bundles and tests to Java 17

### PR DESCRIPTION
**Pull request by jhanders34**

### CODE REVIEW

**Comment by jhanders34** [comment]
#build

**Comment by jhanders34** [comment]
#libby #build

**Review by volosied — COMMENTED** [review]
Confirming you used 11.0.0-M14 for EL?

**Comment by jhanders34** [comment]
> Confirming you used 11.0.0-M14 for EL?

I believe so.  I took the build/source zip file and unzipped it and then cleaned up the properties files and commented out the bnd annotation similar to what was done previously.

**Review by volosied — DISMISSED** [review]
EL changes look good to me

**Comment by jhanders34** [comment]
#libby #build

**Comment by jhanders34** [comment]
#libby #build

**Comment by jhanders34** [comment]
#libby

**Comment by jhanders34** [comment]
#libby

**Comment by fritze2** [comment]
Hope you don't mind that I use your PR as a guinea pig. I'm running a #pbbeta to compare the results against your RTC build before opening the flood gate by turning it on for all devs.

**Review by njr-11 — APPROVED** [review]
Changes related to the Concurrency component look good.

**Review by volosied — APPROVED** [review]
I verified the EL changes locally -- looks good

**Review by pnicolucci — APPROVED** [review]

**Comment by fritze2** [comment]
Re-requesting #pbbeta because PR merge causes CI Orchestrator to cancel pipelines.

**Pull request merged**
