### PR TITLE
timer expiration can cause deadlock in proxy mode

### PR DESCRIPTION
**Pull request by TiborBeres**
In proxy mode expiration timer can cause a deadlock

### CODE REVIEW

**Comment by TiborBeres** [comment]
fixes #23938

**Comment by TiborBeres** [comment]
#build

**Comment by TiborBeres** [comment]
The personal build failure is not cause by the sipcontainer changes. It seems that the allocated time has run out before one of the unit tests could have finished. There were no other errors before the configured test execution timeout has ran out.

```
Task :com.ibm.ws.security.utility:test
Requesting stop of task ':com.ibm.ws.security.utility:test' as it has exceeded its configured timeout of 15m.
Test counts so far:
13696 total tests
13546 total passing
0 total failing
150 total skipped

> Task :com.ibm.ws.security.utility:test FAILED
```

**Review by epj — APPROVED** [review]
okay

**Pull request merged**
