### PR TITLE
Throw correct exceptions from @Transactional interceptors

### LINKED ISSUE #26937: JTA: Transactional-Interceptor wraps RuntimeExceptions
**Describe the bug**  
The  @Transactional-Interceptor wrapps the runtime exception into an jakarta.transaction.TransactionalException

In my opinion this behaviour got introduced with https://github.com/OpenLiberty/open-liberty/commit/d80a04896fcf586db04c65f1bbc50a61514309dd#diff-77d43d7ddfdc7a9365b3a1dea77c78ca603a4cd8bfffa68edbecfaa922c72c55

This may influence other featues like restfulWS (see steps to reproduce).

**Steps to Reproduce**  
```
@RequestScoped
@Path("/sample")
public class SampleSource {

    @GET
    @Transactional
    public String sample(){
        throw new WebApplicationException("not in my house", Response.Status.BAD_REQUEST);
    }

}
```
Server returns status code 500

**Expected behavior**  
In this case I would expect the runtime exception being passed to jaxws and a status code of 400 presented to the caller

**Diagnostic information:**  
 - OpenLiberty Version: 23.0.0.10
- Affected feature(s): JTA
- Java Version: 17.0.8+7

**Additional context**

### PR DESCRIPTION
**Pull request by jonhawkes**
#build

### CODE REVIEW

**Comment by jonhawkes** [comment]
#libby #build

**Comment by jonhawkes** [comment]
#build

**Comment by jonhawkes** [comment]
#libby #build

**Review by neilgsyoung — APPROVED** [review]
Looks good

**Pull request merged**
