### PR TITLE
Issue #25010: Fixed getEntityByIdentifier to not call the WIM GET met…

### LINKED ISSUE #25010: EntryNotFoundException thrown in federated registries when using custom input/output configuration
**Describe the bug**  
When running with `federatedRegistries-1.0`, it is possible to get an EntryNotFoundException when defining a non-identifier type property for the federated registries input/output mapping. This exception can occur in any of the `com.ibm.ws.security.wim.registry.util.*Bridge` classes, but the key is it originates from a `BridgeUtils.getEntityByIdentifier` call.

Below is an example stack:

```
com.ibm.websphere.security.EntryNotFoundException: CWIML1010E: The user registry operation could not be completed. The uniqueId = null and uniqueName = null attributes of the identifier object are either not valid or not defined in the back-end repository.
	at com.ibm.ws.security.registry.internal.UserRegistryWrapper.getGroupsForUser(UserRegistryWrapper.java:248)
	at web.UserRegistryServlet.handleMethodRequest(UserRegistryServlet.java:140)
	at web.UserRegistryServlet.doGet(UserRegistryServlet.java:174)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1258)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:746)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:443)
	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1227)
	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1011)
	at com.ibm.ws.webcontainer.servlet.CacheServletWrapper.handleRequest(CacheServletWrapper.java:75)
	at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:938)
	at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.run(DynamicVirtualHost.java:281)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink$TaskWrapper.run(HttpDispatcherLink.java:1246)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.wrapHandlerAndExecute(HttpDispatcherLink.java:468)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.ready(HttpDispatcherLink.java:427)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:567)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleNewRequest(HttpInboundLink.java:501)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.processRequest(HttpInboundLink.java:361)
	at com.ibm.ws.http.channel.internal.inbound.HttpICLReadCallback.complete(HttpICLReadCallback.java:70)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.requestComplete(WorkQueueManager.java:514)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.attemptIO(WorkQueueManager.java:584)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.workerRun(WorkQueueManager.java:968)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager$Worker.run(WorkQueueManager.java:1057)
	at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:245)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:836)
Caused by: com.ibm.ws.security.registry.EntryNotFoundException: CWIML1010E: The user registry operation could not be completed. The uniqueId = null and uniqueName = null attributes of the identifier object are either not valid or not defined in the back-end repository.
	at com.ibm.ws.security.wim.registry.util.BridgeUtils.handleExceptions(BridgeUtils.java:587)
	at com.ibm.ws.security.wim.registry.util.MembershipBridge.getGroupsForUser(MembershipBridge.java:260)
	at com.ibm.ws.security.wim.registry.WIMUserRegistry.getGroupsForUser(WIMUserRegistry.java:484)
	at com.ibm.ws.security.registry.internal.UserRegistryWrapper.getGroupsForUser(UserRegistryWrapper.java:244)
	... 27 more
Caused by: com.ibm.wsspi.security.wim.exception.InvalidIdentifierException: CWIML1010E: The user registry operation could not be completed. The uniqueId = null and uniqueName = null attributes of the identifier object are either not valid or not defined in the back-end repository.
	at com.ibm.ws.security.wim.ProfileManager.getImpl(ProfileManager.java:421)
	at com.ibm.ws.security.wim.ProfileManager.genericProfileManagerMethod(ProfileManager.java:263)
	at com.ibm.ws.security.wim.ProfileManager.get(ProfileManager.java:207)
	at com.ibm.ws.security.wim.VMMService.get(VMMService.java:211)
	at com.ibm.ws.security.wim.registry.util.BridgeUtils.getEntityByIdentifier(BridgeUtils.java:468)
	at com.ibm.ws.security.wim.registry.util.MembershipBridge.getGroupsForUser(MembershipBridge.java:124)
	... 29 more
```

**Steps to Reproduce**  
Configure an LDAP registry. Configure the userSecurityNameMapping input property to a non-identifier type property, such as mail below.

```
    <ldapRegistry realm="LdapRealm"... >
        ...
    </ldapRegistry>

    <federatedRepository>
      <primaryRealm name="FederatedRealm">
	<participatingBaseEntry name="dc=example,dc=com"/>
	<userSecurityNameMapping inputProperty="mail" outputProperty="mail"/>
      </primaryRealm>
    </federatedRepository>
```

Call the getGroupsForUsers UserRegistry method and you will receive the EntryNotFoundException. Again, this would apply to all of the `com.ibm.ws.security.wim.registry.util.*Bridge` classes. The key to reproducing is setting the input mapping for the returned value for that specific method to one that is not an identifier type property (uniqueName, uniqueId, externalName, externalId).

**Expected behavior**  
The method should not throw an EntryNotFoundException. The bridge class should NOT call the WIM GET method, but should instead call the SEARCH method. The GET method can only be utilized using an identifier property (uniqueName, uniqueId, externalName, externalId).

**Diagnostic information:**  
 - OpenLiberty Version: ALL
 - Affected feature(s): federatedRegistry-1.0
 - Java Version: Any
 - server.xml configuration: see above

**Additional context**  
None.

### PR DESCRIPTION
**Pull request by jvanhill**
…hod when the input mapping property is NOT an identifier attribute. When this is the case, the WIM SEARCH method should be called instead.

fixes #25010

### CODE REVIEW

**Comment by jvanhill** [comment]
#build

**Comment by jvanhill** [comment]
#build

**Comment by jvanhill** [comment]
#build

**Review by ryanesch — APPROVED** [review]

**Comment by jvanhill** [comment]
#libby

**Pull request merged**
