### PR TITLE
Add WLP-Activate-Type: parallel to faces-3.0 auto features

### LINKED ISSUE #14165: Add `WLP-Activation-Type: parallel` to faces-3.0
Please add `WLP-Activation-Type: parallel`

_Originally posted by @tevans78 in https://github.com/OpenLiberty/open-liberty/pull/13839#discussion_r495017142_

### PR DESCRIPTION
**Pull request by pnicolucci**
fixes #14165

### CODE REVIEW

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
PB:https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_4j4QMAXAEeuIgpJAZoWiKQ

**Comment by pnicolucci** [comment]
PB:https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_p0QBgAZZEeuIgpJAZoWiKQ

**Comment by pnicolucci** [comment]
PB: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_b-6XMAb6EeuIgpJAZoWiKQ

**Comment by pnicolucci** [comment]
PB: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_eRYcYAc3EeuIgpJAZoWiKQ

**Comment by pnicolucci** [comment]
#build

**Review by cbridgha — APPROVED** [review]
LGTM

**Comment by pnicolucci** [comment]
#run-libby-bot

**Pull request merged**
