### PR TITLE
Refactoring and processing of Jakarta Security 3.0 annotations for issue #21155

### PR DESCRIPTION
**Pull request by teddyjtorres**
For issue #21155

- Refactors JavaEESecCDIExtension to use a new HttpAuthenticationMechanismsTracker to keep track of authentication mechanisms per application.
- Creates new dev/io.openliberty.security.jakartasec.3.0.internal.cdi project with JakartaSecurity30CDIExtension and supporting classes for processing the OpenIdAuthenticationMechanismDefinition annotation and creating the OidcHttpAuthenticationMechanism.
- Adds shell FAT project to start a server with appSecurity-5.0 (Uncomment test to exercise the OidcHttpAuthenticationMechanism. Uncommented test will fail at the moment until more implementation is added.)

### CODE REVIEW

**Comment by teddyjtorres** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.security.javaeesec_fat,com.ibm.ws.security.javaeesec_fat.2,com.ibm.ws.security.javaeesec_fat.3,com.ibm.ws.security.javaeesec_fat.4

**Review by utle — APPROVED** [review]

**Review by ayoho — APPROVED** [review]

**Comment by teddyjtorres** [comment]
Last commit fixes errors found in the Personal Build. It is a very small change to fix an NPE .

**Comment by teddyjtorres** [comment]
#build

**Comment by teddyjtorres** [comment]
#libby

**Comment by posmith** [comment]
L2 message review completed

**Comment by teddyjtorres** [comment]
Reviewed failure for com.ibm.ws.wssecurity_fat.wsscxf.saml.1's testSAMLCxfSvcClient_TransportEnabled_EE9_FEATURES test failure. It appears to be a connectivity issue not related to the code being delivered in this PR.

**Pull request merged**
