### PR TITLE
Barebones classes for Jakarta Security 3.0 Discovery

### PR DESCRIPTION
**Pull request by tmooretcm**
- Created two classes: DiscoveryHandler and Client
- Updated buildpaths and imports for DiscoveryHandler
- Basic method headers and outline for DiscoveryHeader
- Adjusted OidcClientConfigImpl to have a DiscoveryHandler object taking an SSLSocketFactory instance

### CODE REVIEW

**Comment by tmooretcm** [comment]
#build

**Review by ayoho — APPROVED** [review]

**Comment by tmooretcm** [comment]
#libby

**Comment by tmooretcm** [comment]
#build
#libby

**Comment by tmooretcm** [comment]
#build

**Comment by tmooretcm** [comment]
#libby

**Review by ayoho — APPROVED** [review]

**Pull request merged**
