### PR TITLE
Fix Defect 300579

### PR DESCRIPTION
**Pull request by tssmith04**
Fixes Defect 300579. It was timing out because the test was waiting for the incorrect message.

### CODE REVIEW

**Comment by tssmith04** [comment]
#link 300579

**Comment by volosied** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jsfContainer_fat_2.3

**Review by volosied — APPROVED** [review]
Running a build just in case.  Looks good.

**Comment by tssmith04** [comment]
#libby

**Pull request merged**
