### PR TITLE
Rename existing MP features in MP 4.0 back to com.ibm.websphere.appserver

### LINKED ISSUE #14641: How to handle singleton/toleration of "io.openliberty" vs "com.ibm" features - particularly in MicroProfile features
This design issue comes from issue #14611.  The net of that issue is that the `mpGraphQL-1.0` feature cannot currently tolerate `mpConfig-2.0` (part of MP 4.0) because: (1) it depends on the `mpConfig-1.4` feature (both API and impl) and (2) the `mpConfig-1.4` feature starts with "com.ibm.websphere.appserver" and `mpConfig-2.0` feature starts with "io.openliberty" - therefore they are not the singletons - and `mpGraphQL-1.0` cannot tolerate `mpConfig-2.0`.

First decision: do we care?  I think it would be very limiting for GraphQL users to be locked in to MP 3.3 technologies, but maybe we can live with that... 

Assuming we care, second decision: How do we make this work?  Here are a few options:
(1) MP 4.0 has not shipped - it's not too late to rename the new features to start with "com.ibm.websphere.appserver"

(2) Update the feature manager to match "com.ibm.websphere.xyz" with "io.openliberty.xyz" so that 
```
-features=com.ibm.websphere.appserver.mpConfig-1.4;ibm.tolerates=2.0,\
```
just works as if `mpConfig-2.0`'s symbolic name started with "com.ibm.websphere.appserver".

(3) The hard way... create `mpCompatible-3.3`, `mpCompatible-4.0`, etc. features as described in issue #14219. Then features like `mpGraphQL-1.0` must drop its dependency on `mpConfig-1.4` and instead depend on `mpCompatible-3.3;ibm.tolerates=4.0`.  Then create two new auto-features for `mpGraphQL-1.0+mpCompatible-3.3` and `mpGraphQL-1.0+mpCompatible-4.0` that provide features `mpConfig-1.4` and `mpConfig-2.0`, respectively.

I prefer option 1 or 2 due to the simplicity.  Option 3 will likely work, but it adds a lot of overhead - and will likely require this same sort of approach for future changes - i.e. `mpLRA` might have to do the same thing to work with MP 4.1, 4.2, 4.3, etc. `mpGraphQL-1.0` would have to add or update auto-features with MP 4.1, 4.2, etc.

### PR DESCRIPTION
**Pull request by jhanders34**
- In order to allow for toleration between different MP features, it was decided to not use io.openliberty as a prefix.

The mpLRA features were left as io.openliberty since they are version 1.0

fixes #14641

### CODE REVIEW

**Comment by jhanders34** [comment]
I did a PB for this branch already, but one of the child builds failed with a connectivity issue.  All tests that did run were green as expected.  Building again.

#build

**Comment by jhanders34** [comment]
#build

**Comment by jhanders34** [comment]
#libby

**Review by tevans78 — APPROVED** [review]

**Review by andymc12 — APPROVED** [review]
LGTM - thanks!

**Pull request merged**
