### PR TITLE
Fixes for DS issues identified by testing with Bnd 4.1

### PR DESCRIPTION
**Pull request by bjhargrave**
Testing with the development versions of Bnd 4.1 identified some issues with DS usage in the code base which must be corrected before the project can upgrade to Bnd 4.1 when it is released.

### CODE REVIEW

**Comment by bjhargrave** [comment]
@aguibert, Given that I am an IBM employee, am I not already covered under a CCLA from IBM? Or do you need an Individual CLA from me as well?

**Comment by aguibert** [comment]
@bjhargrave I confirmed with @cbridgha that all IBMers are covered in the CLA automatically, so no need for you to explicitly fill it out

**Comment by aguibert** [comment]
#build

**Comment by aguibert** [comment]
#build

**Comment by aguibert** [comment]
build looks good, just 1 unrelated failure out of 64424 tests -- merging

**Pull request merged**
