### PR TITLE
Fix issues #14, #17 in 17.0.0.3_RC stabilization branch

### PR DESCRIPTION
**Pull request by scottkurz**
Fix for issue #14 and issue #17 in 17.0.0.3_RC stabilization branch.    Similar content to pull #20 and pull #42.

### CODE REVIEW

**Comment by scottkurz** [comment]
#build

**Comment by scottkurz** [comment]
@vishavs can you please mark this message approved?  It's the exact one you just approved in PR #42 (for the 17003 stream, this time).  Thanks!

**Comment by vishavs** [comment]
L2 approves the messsage

**Comment by amylin1** [comment]
Erik, thanks for merging.

**Pull request merged**
