### PR TITLE
Jakarta testing for jca and beanval

### PR DESCRIPTION
**Pull request by KyleAure**

### CODE REVIEW

**Comment by KyleAure** [comment]
Currently not working.  Facing an error with bean validation compatibility:

```
E CWWKE0701E: bundle com.ibm.ws.jca.jakarta:1.0.45.202008241442 (85)[com.ibm.ws.jca.resourceAdapter.properties(278)] : The activate method has thrown an exception jakarta.validation.ValidationException: HV000099: Unable to instantiate validation provider class org.apache.bval.jsr303.ApacheValidationProvider.
``` 

Looks to be an issue between Connectors-2.0 and beanValidation-3.0.  `org.apache.bval.jsr303.ApacheValidationProvider` is listed as the default provider in the validation.xml file.  Perhaps a different provider should be used for beanValidation-3.0? 
@nmittles?

**Comment by nmittles** [comment]
@KyleAure 
Bean Validation in Liberty uses Apache for 1.0 and 1.1.  The provider listed in the test's validation.xml is `org.apache.bval.jsr303.ApacheValidationProvider` which is for Apache Bean Validation 1.0.  Since you're testing using Bean Validation 3.0, it's running Hibernate Validator, and therefore can't use the Apache class.  Try removing the `<default-provider>` tag from the validation.xml and let the bval feature use its default provider class. The test is hardcoded to use the bval 1.0 default provider.

**Comment by KyleAure** [comment]
#build 
#libbybot

**Review by nmittles — APPROVED** [review]

**Comment by KyleAure** [comment]
#build

**Comment by KyleAure** [comment]
#build 
#libbybot

**Pull request merged**
