### PR TITLE
Remove web.xml files that are not needed.

### LINKED ISSUE #25873: Expression Language 6.0: Update io.openliberty.org.apache.jasper.expressionLanguage.60_fat test artifacts to use latest web.xml schema
If a new Servlet 6.1 schema is available we should update the `web.xml` to use it.

### PR DESCRIPTION
**Pull request by pnicolucci**
fixes #25873

### CODE REVIEW

**Comment by pnicolucci** [comment]
#build #spawn.fullfat.buckets=io.openliberty.org.apache.jasper.expressionLanguage.6.0_fat

**Comment by pnicolucci** [comment]
#build #spawn.fullfat.buckets=io.openliberty.org.apache.jasper.expressionLanguage.6.0_fat

**Comment by pnicolucci** [comment]
#build #spawn.fullfat.buckets=io.openliberty.org.apache.jasper.expressionLanguage.6.0_fat

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#libby

**Comment by pnicolucci** [comment]
#build #spawn.fullfat.buckets=io.openliberty.org.apache.jasper.expressionLanguage.6.0_fat

**Review by pmd1nh — APPROVED** [review]

**Comment by pnicolucci** [comment]
The personal build didn't run any builds, the fat.buckets.to.run was set to none even though I specified the spawn.fullfat.buckets, so rerunning with an update to fat.buckets.to.run: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_2htG0OK2Ee62Qc2Tit17uw

**Pull request merged**
