### PR TITLE
Correct the DHE maven repo location

### PR DESCRIPTION
**Pull request by cbridgha**
Fixing up the url of the DHE maven repo for the BND workspace

### CODE REVIEW

**Comment by tevans78** [comment]
I agree with Jared ... possibly a couple of others too;
https://github.com/OpenLiberty/open-liberty/search?q=http%3A%2F%2Fpublic.dhe.ibm.com%2Fibmdl%2Fexport%2Fpub%2Fsoftware%2Fopenliberty%2Fwasliberty-open-liberty&unscoped_q=http%3A%2F%2Fpublic.dhe.ibm.com%2Fibmdl%2Fexport%2Fpub%2Fsoftware%2Fopenliberty%2Fwasliberty-open-liberty

**Comment by cbridgha** [comment]
yep - I'll add those too

**Comment by jhanders34** [comment]
The other two you referenced are different URLs that I assume don't need to be updated.  I thought on the wasliberty.... longer URL was the one that needed to be updated.

**Comment by Azquelt** [comment]
I agree, the search results from `dev/build.image/build.gradle` and `dev/settings.gradle` look correct.

**Pull request merged**
