### PR TITLE
Remove most of the tests for testing purposes

### PR DESCRIPTION
**Pull request by rickettmwork**
Reduce number of tests in order to deubg which ones are causing problems on windows.

DO NOT MERGE THIS UNDER ANY CIRCUMSTANCE

### CODE REVIEW

**Comment by rickettmwork** [comment]
#pb

**Comment by rickettmwork** [comment]
#pbbeta

**Comment by rickettmwork** [comment]
#pb

**Comment by fritze2** [comment]
#pb

**Comment by wraschke** [comment]
#libby

**Comment by rickettmwork** [comment]
#pbbeta

**Pull request closed without merging**
