### PR TITLE
Update transformer to version 0.5.0

### PR DESCRIPTION
**Pull request by jhanders34**
- Move to 0.5.0 version of the transformer
- Remove rules that are no longer needed with the new transformer behavior
- Add new rules for behavior differences with the new version.

### CODE REVIEW

**Comment by jhanders34** [comment]
#build

**Comment by jhanders34** [comment]
#libby #build

**Review by tbitonti — APPROVED** [review]
I'm curious as to the omission of "org.eclipse.transformer:org.eclipse.transformer.bnd.analyzer", which appears in "dev/wlp-gradle/subprojects/fat.gradle" but not in "tasks.gradle" in the same folder.

**Comment by jhanders34** [comment]
> I'm curious as to the omission of "org.eclipse.transformer:org.eclipse.transformer.bnd.analyzer", which appears in "dev/wlp-gradle/subprojects/fat.gradle" but not in "tasks.gradle" in the same folder.

Something to consider to fix possibly, but it probably should not need to be there in the fat.gradle, but that can be done in a follow-on PR since is isn't changed from the previous code.

**Comment by jhanders34** [comment]
#libby #build

**Comment by jhanders34** [comment]
#libby #build

**Comment by jhanders34** [comment]
#libby #build

**Pull request merged**
