### PR TITLE
Tolerate JMSContext.CLIENT_ACKNOWLEDGE on create session.

### PR DESCRIPTION
**Pull request by AndrewDJBanks**

### CODE REVIEW

**Comment by AndrewDJBanks** [comment]
fixes #15279

**Comment by AndrewDJBanks** [comment]
#build

**Comment by AndrewDJBanks** [comment]
#build

**Review by sakerl — APPROVED** [review]
Code changes look good to me.

**Comment by AndrewDJBanks** [comment]
#libbybot

**Comment by AndrewDJBanks** [comment]
See coreq change https://github.ibm.com/websphere/WS-CD-Open/pull/22875.

**Pull request merged**
