### PR TITLE
When TAI is configured with invokeForUnprotectedTAI flag, unnecessary authentication may run 

### PR DESCRIPTION
**Pull request by una-tapa**
This PR is to address  Issue 1338. 
https://github.com/OpenLiberty/open-liberty/issues/1338.

### CODE REVIEW

**Comment by una-tapa** [comment]
#build

**Comment by una-tapa** [comment]
https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=__gDk0IlfEeiN-KJL-9czGg&tab=com.ibm.team.build.web.ui.internal.editors.result.test.TestProvider

**Comment by mhldr** [comment]
issues discussed in #was-liberty-ops caused the build to fail so I'm respinning this incase it's needed (you ***may*** already have the results you need but if not hopefully this respin will help)
#build

**Comment by una-tapa** [comment]
Redoing in other PR.

**Pull request closed without merging**
