### PR TITLE
Clear application metadata on init failure

### PR DESCRIPTION
**Pull request by brenthdaniel**

### CODE REVIEW

**Comment by brenthdaniel** [comment]
#build

**Comment by brenthdaniel** [comment]
@hutchig I think you maintain grpc? The changes here were needed because we are now fully uninstalling applications that fail to start. In the case where a GRPC service fails to start because of a duplicate service name it was removing the legitimate service with the same name from the grpc runtime. I fixed that by scoping the services by the j2eeName, but if you prefer another solution let me know.

**Review by hlhoots — APPROVED** [review]
LGTM

**Comment by brenthdaniel** [comment]
#build

**Review by hutchig — APPROVED** [review]
Looks good to me, and thank you for the test material too.

**Comment by brenthdaniel** [comment]
#run-libby-bot

**Comment by brenthdaniel** [comment]
Fix for #24578

**Pull request merged**
