### PR TITLE
Reenable previously failing DB2 tests

### PR DESCRIPTION
**Pull request by KyleAure**
- [x] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [x] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [x] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

Re-enable tests that fail due to https://github.com/OpenLiberty/open-liberty/issues/29443
@ajaypaul-ibm - requested we retest the failures due to recent fixes in eclipselink

### CODE REVIEW

**Comment by KyleAure** [comment]
#libby - check headers
#build - personal build

**Comment by contbld** [comment]
Your personal pipeline request is at https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=1b9e9d6e-4c6b-4ab6-b3f1-5119b3231a37

Target locations of links might be accessible only to IBM employees.

**Comment by contbld** [comment]
Your personal pipeline request is at https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=abc10c29-3632-498f-b233-b8d890e92e6e

Target locations of links might be accessible only to IBM employees.

**Comment by KyleAure** [comment]
Database rotation personal build: https://libh-proxy1.fyre.ibm.com/cognitive-dev/pipelineAnalysis.html?pipelineId=b5888165-3c2d-4486-b70b-6cb81c6d4588

Target locations of links might be accessible only to IBM employees.

**Comment by contbld** [comment]
<h3>Code analysis and actions</h3>
DO NOT DELETE THIS COMMENT.

- 2 FAT files were changed, added, or removed.
 - Check that the build did not break the affected FAT suite(s).

**Comment by contbld** [comment]
https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=abc10c29-3632-498f-b233-b8d890e92e6e completed successfully!

**Comment by contbld** [comment]
<h3>Code analysis and actions</h3>
DO NOT DELETE THIS COMMENT.

- 2 FAT files were changed, added, or removed.
 - Check that the build did not break the affected FAT suite(s).

**Review by ajaypaul-ibm — APPROVED** [review]

**Comment by contbld** [comment]
https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=1b9e9d6e-4c6b-4ab6-b3f1-5119b3231a37 completed successfully!

**Review by KyleAure — COMMENTED** [review]
@ajaypaul-ibm 
It looks like these tests are still failing on DB2.
See the following failure output groups:

- [JakartaDataRecreateServlet.testOLGH29443](https://libh-proxy1.fyre.ibm.com/cognitive-dev/failureGroupDetails.html?failureGroupId=failure_group-4708650a-b360-42a3-b912-27e5ce66c519)
- [DataJPATestServlet.testConvertBigIntegerValue](https://libh-proxy1.fyre.ibm.com/cognitive-dev/failureGroupDetails.html?failureGroupId=failure_group-ea5eb7fc-8e0a-4060-9099-6f0926cfd83f)

**Pull request closed without merging**
