### PR TITLE
Update JakartaEEAction strings

### PR DESCRIPTION
**Pull request by Yas-Franco**
- [x] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [x] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [x] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

################################################################################################
This changes the repeat action strings so that the output.txt shows the exact repeat

```Running ...  with action: JakartaEE11 FAT repeat action (EE11_FEATURES_MicroProfile_70)```

instead of 

```Running ... with action: JakartaEE11 FAT repeat action ```

### CODE REVIEW

**Review by benjamin-confino — APPROVED** [review]

**Comment by Yas-Franco** [comment]
#libby
#build

**Comment by contbld** [comment]
Your personal pipeline request is at https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=72192c5c-ab73-462b-82eb-0fccee628f26

Target locations of links might be accessible only to IBM employees.

**Comment by contbld** [comment]
Your personal pipeline request is at https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=85315b62-c473-4bd9-9d33-f17dffb20ff5

Target locations of links might be accessible only to IBM employees.

**Comment by contbld** [comment]
<h3>Code analysis and actions</h3>
DO NOT DELETE THIS COMMENT.

- 2 test infrastructure code files were changed.
 - Test failures/errors in the build could be due to these changes.

**Comment by contbld** [comment]
<h3>Code analysis and actions</h3>
DO NOT DELETE THIS COMMENT.

- 2 test infrastructure code files were changed.
 - Test failures/errors in the build could be due to these changes.

**Comment by contbld** [comment]
https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=72192c5c-ab73-462b-82eb-0fccee628f26 completed successfully!

**Comment by contbld** [comment]
https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=85315b62-c473-4bd9-9d33-f17dffb20ff5 has errors/failures.

**Pull request merged**
