### PR TITLE
Remove SharedServer from WC5JakartaServletTest

### LINKED ISSUE #13825: Remove SharedServer from WC5JakartaServletTest in servlet 4.0 FAT bucket

### PR DESCRIPTION
**Pull request by pnicolucci**
fixes #13825

### CODE REVIEW

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#run-libby-bot

**Review by isaacrivriv — APPROVED** [review]
Looks good. Thanks!

**Pull request merged**
