### PR TITLE
Oidc JWE FAT delivery #1

### PR DESCRIPTION
**Pull request by c00crane**
Deliver FAT tests to verify support for additional signature algorithms by the OIDC RP

### CODE REVIEW

**Review by ayoho — COMMENTED** [review]
Changes look good

**Comment by c00crane** [comment]
#build

**Review by ayoho — APPROVED** [review]

**Comment by ayoho** [comment]
#libby

**Comment by skasund** [comment]
L2 message review not required

**Comment by c00crane** [comment]
Tried, but just can't link to issue:
https://github.com/OpenLiberty/open-liberty/issues/12213

**Pull request merged**
