### PR TITLE
Skip testEnvironmentConfigSource() on Windows machines

### PR DESCRIPTION
**Pull request by Joseph-Cass**
#build

### CODE REVIEW

**Comment by Azquelt** [comment]
Looks good but can you add a link to the TCK issue? Thanks.

**Comment by Joseph-Cass** [comment]
> Looks good but can you add a link to the TCK issue? Thanks.

Relates to: https://github.com/eclipse/microprofile-config/issues/664

**Review by Azquelt — APPROVED** [review]

**Comment by Joseph-Cass** [comment]
The FAT bucket which failed is unrelated to the changes made, and was only run due to a bug in the build code. I have messaged the appropriate person about this. The Windows test which has been skipped in this change showed up as one less test in the `external links` tab.

**Comment by Joseph-Cass** [comment]
run-libby-bot

**Comment by Azquelt** [comment]
#run-libby-bot

**Pull request merged**
