### PR TITLE
Update bndtools to 6.3.0-RC2

### PR DESCRIPTION
**Pull request by jhanders34**
- With this new version we can reference transformed bundles with a symbolic name that was drastically changed like what we have done to have transformed bundles start with io.openliberty instead of com.ibm.

### CODE REVIEW

**Comment by tjwatson** [comment]
LGTM, are you waiting to start a build on this one?

**Comment by jhanders34** [comment]
> LGTM, are you waiting to start a build on this one?

I haven't uploaded to artifactory yet.  When I have that done, I will start a build.

**Comment by jhanders34** [comment]
#build

**Review by tjwatson — APPROVED** [review]

**Review by fritze2 — APPROVED** [review]
LGTM

**Pull request merged**
