### PR TITLE
wsscxf.saml.4 fat remoe split

### PR DESCRIPTION
**Pull request by meiaus**
Update com.ibm.ws.wssecurity_fat.wsscxf.saml.4 to remove the split (EE7Only/EE8Only)

### CODE REVIEW

**Comment by meiaus** [comment]
#run-libby-bot

**Comment by meiaus** [comment]
#run-libby-bot

**Comment by meiaus** [comment]
#build

**Comment by arunavemulapalli** [comment]
#build

**Review by arunavemulapalli — APPROVED** [review]

**Pull request merged**
