### PR TITLE
Update infra-buildtasks-core from 4.0.0 to 6.0.6

### PR DESCRIPTION
**Pull request by fritze2**
#build

### CODE REVIEW

**Comment by fritze2** [comment]
#build

**Review by rickettmwork — APPROVED** [review]
Approved pending successful build

**Comment by fritze2** [comment]
Re- #build because the artifactId is `infra.buildtasks-core`, not `infra-buildtasks-core`.

**Comment by rickettmwork** [comment]
All failures in the personal build are existing defects unrelated to these changes

**Comment by fritze2** [comment]
#libby

**Pull request merged**
