### PR TITLE
Issue #3467: Ensure proper handling of factory wrappers implementing the purge method

### PR DESCRIPTION
**Pull request by andymc12**
This resolves issue #3467 by ensuring that we invoke the purge method only on the instance of the class that actually defines the purge method - whether it be a wrapper or a wrapped instance.

### CODE REVIEW

**Comment by andymc12** [comment]
#build

**Comment by andymc12** [comment]
Build issues last week prevented completion of the previous build requests.  Trying again:
#build #spawn.fullfat.buckets=com.ibm.ws.jsf.2.2_fat,com.ibm.ws.jsf_fat_jsf2.2

**Comment by andymc12** [comment]
The build issues from last week are persisting, and continue to prevent completion of the previous build requests. Trying again:
#build #spawn.fullfat.buckets=com.ibm.ws.jsf.2.2_fat,com.ibm.ws.jsf_fat_jsf2.2

**Comment by andymc12** [comment]
Rebased - new #build

**Comment by andymc12** [comment]
The three failures in this latest build are not related to these changes, and I have seen the same failures in other builds that do not have these changes included.

**Comment by wtlucy** [comment]
The changes here do look to fix a concrete problem, however the original problem this change intends to resolve is not completely fixed.  We want to avoid having a partial fix in the upcoming release, so I'll revert this PR re-integrate it when we have a complete fix for the original problem.

**Pull request merged**
