### PR TITLE
Revert "Revert "Update to Felix SCR 2.2.2""

### LINKED ISSUE #23460: Re-introduce change reverted from 22004
Re-introduce change reverted from https://github.com/OpenLiberty/open-liberty/pull/22004

### PR DESCRIPTION
**Pull request by tevans78**
Reverts OpenLiberty/open-liberty#23459

fixes https://github.com/OpenLiberty/open-liberty/issues/23460

#build

### CODE REVIEW

**Comment by tevans78** [comment]
#build

**Comment by dazavala** [comment]
The feature verification (FV) changes necessary to tolerate this SCR update (WSCDO PR 28314) are now in WS-CD-Open integration. **Once the FV changes merge into WS-CD-Open release, we can merge this PR pending approval and personal build.**

**Comment by dazavala** [comment]
#build

**Comment by dazavala** [comment]
@tjwatson or @sebratton - Please review these changes.
#build

**Comment by tjwatson** [comment]
We only have a week until the next GM build is finalized for `22.0.0.13`.  I think we should hold off merging this until after the GM candidate build is done.

**Comment by dazavala** [comment]
FYI, the most recent build shows no breaks.

**Comment by dazavala** [comment]
#build

**Comment by dazavala** [comment]
Close. Changes where instead delivered via #23596.

**Pull request closed without merging**
