### PR TITLE
Debug wab install

### PR DESCRIPTION
**Pull request by sebratton**

### CODE REVIEW

**Comment by sebratton** [comment]
#build

**Comment by sebratton** [comment]
#build

**Comment by sebratton** [comment]
#build

**Review by dazavala — APPROVED** [review]

**Comment by sebratton** [comment]
#build

**Comment by sebratton** [comment]
#build

**Review by tjwatson — APPROVED** [review]
LGTM

**Comment by sebratton** [comment]
#run-libby-bot

**Comment by sebratton** [comment]
#build

**Comment by sebratton** [comment]
#build

**Comment by sebratton** [comment]
#link 255696

**Comment by sebratton** [comment]
#link 275542

**Comment by sebratton** [comment]
#run-libby-bot

**Pull request merged**
