### PR TITLE
19783 update server config validation

### PR DESCRIPTION
**Pull request by sarinjacobsunny**
Provide UI interface to Integrate validation api into admincenter.

Testcases: https://github.ibm.com/websphere/WS-CD-Open/pull/24744/commits/9ce176ec12a7d1bae820b366d3a8ccbf32e76a52

### CODE REVIEW

**Comment by sarinjacobsunny** [comment]
Please review,
@k8vance88 @lavenal @kinueng @amyreit @sreejith-websphere

**Comment by sarinjacobsunny** [comment]
#build

**Comment by sarinjacobsunny** [comment]
#build

**Comment by lavenal** [comment]
#build

**Comment by sarinjacobsunny** [comment]
#build

**Comment by sarinjacobsunny** [comment]
#build

**Comment by sarinjacobsunny** [comment]
#build

**Comment by sarinjacobsunny** [comment]
#build

**Comment by Sreejith-Websphere** [comment]
#build

**Comment by sarinjacobsunny** [comment]
#build

**Comment by k8vance88** [comment]
#build

**Comment by sarinjacobsunny** [comment]
#build

**Comment by sarinjacobsunny** [comment]
#build

**Comment by sarinjacobsunny** [comment]
#build

**Comment by sarinjacobsunny** [comment]
#build

**Comment by sarinjacobsunny** [comment]
#build

**Comment by sarinjacobsunny** [comment]
#build

**Comment by sarinjacobsunny** [comment]
#build

**Comment by sarinjacobsunny** [comment]
#build

**Comment by sarinjacobsunny** [comment]
#build

**Comment by sarinjacobsunny** [comment]
Squashed 63 commits into single commit.

**Comment by sarinjacobsunny** [comment]
New PR is raised for the same, and this one can be ignored.

URL to new PR is,
https://github.com/OpenLiberty/open-liberty/pull/19581

**Pull request closed without merging**
