### PR TITLE
Initial common crypto utils project

### PR DESCRIPTION
**Pull request by rlcundiff**
For https://github.com/OpenLiberty/open-liberty/pull/27649

### CODE REVIEW

**Comment by rlcundiff** [comment]
#build

**Comment by rlcundiff** [comment]
#build

**Comment by rlcundiff** [comment]
#build

**Comment by rlcundiff** [comment]
#build

**Comment by rlcundiff** [comment]
#build

**Comment by rlcundiff** [comment]
#build

**Comment by rlcundiff** [comment]
#build

**Comment by rlcundiff** [comment]
#build

**Comment by rlcundiff** [comment]
#build

**Comment by rlcundiff** [comment]
#libby

**Comment by rlcundiff** [comment]
This is a new project that is not yet used by any other projects.  The test failures in other components must be unrelated to this PR.

**Review by utle — APPROVED** [review]

**Pull request merged**
