### PR TITLE
Use mvn wrapper2

### PR DESCRIPTION
**Pull request by tevans78**
Redelivery of https://github.com/OpenLiberty/open-liberty/pull/24754

Plus some fixes for zos and Windows

### CODE REVIEW

**Comment by tevans78** [comment]
#build

**Comment by tevans78** [comment]
#build

**Review by abutch3r — DISMISSED** [review]
LGTM

**Comment by tevans78** [comment]
TCKs only, on Linux, Windows and zos: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_pyBwYOJ3Ee2xRt1mHVwGHw

**Comment by tevans78** [comment]
#build

**Comment by tevans78** [comment]
replaced by https://github.com/OpenLiberty/open-liberty/pull/25191

**Pull request closed without merging**
