### PR TITLE
HTTP/2 window update improvements

### LINKED ISSUE #12399: HTTP/2 read window not updated
In a limited scenario, Liberty's HTTP/2 implementation does not send HTTP/2 window updates quickly enough - causing its read flow control window to stall and preventing clients from sending more data.

### PR DESCRIPTION
**Pull request by wtlucy**
fixes #12399

### CODE REVIEW

**Comment by wtlucy** [comment]
#build

**Comment by wtlucy** [comment]
#build

**Comment by pnicolucci** [comment]
Hey @wtlucy this should probably be linked to an issue and tagged as a `release bug`. What do you think?

**Comment by wtlucy** [comment]
@pnicolucci Yeah, it will be (both linked and tagged) - I'd wanted to get some feedback first

**Comment by wtlucy** [comment]
#build

**Comment by wtlucy** [comment]
#build

**Comment by wtlucy** [comment]
#build

**Comment by wtlucy** [comment]
#run-libby-bot

**Pull request merged**
