### PR TITLE
update ehcache initialization

### PR DESCRIPTION
**Pull request by arunavemulapalli**
ehcache updates

### CODE REVIEW

**Comment by arunavemulapalli** [comment]
#build

**Comment by arunavemulapalli** [comment]
#build

**Comment by arunavemulapalli** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.wssecurity_fat.wsscxf,com.ibm.ws.wssecurity_fat.wsscxf.1
#spawn.zos=true

**Comment by arunavemulapalli** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.wssecurity_fat.wsscxf,com.ibm.ws.wssecurity_fat.wsscxf.1
#spawn.zos=true

**Comment by arunavemulapalli** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.wssecurity_fat.wsscxf,com.ibm.ws.wssecurity_fat.wsscxf.1
#spawn.zos=true
#spawn.zos.tests=true
#spawn.common.fats.on.zos = true

**Comment by arunavemulapalli** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.wssecurity_fat.wsscxf,com.ibm.ws.wssecurity_fat.wsscxf.1
#spawn.zos=true
#spawn.zos.tests=true
#spawn.common.fats.on.zos=true

**Comment by arunavemulapalli** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.wssecurity_fat.wsscxf,com.ibm.ws.wssecurity_fat.wsscxf.1

**Comment by arunavemulapalli** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.wssecurity_fat.wsscxf,com.ibm.ws.wssecurity_fat.wsscxf.1

**Comment by arunavemulapalli** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.wssecurity_fat.wsscxf,com.ibm.ws.wssecurity_fat.wsscxf.1

**Comment by arunavemulapalli** [comment]
#libby
#build

**Review by neuwerk — APPROVED** [review]
The changes look good to me!

**Comment by arunavemulapalli** [comment]
here is a pb link to zOS test build (all ws-security tests are running successfully) - https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_hoFBgCwmEeyF1bm_xnmrjA&tab=com.ibm.team.build.web.ui.internal.editors.result.overview.OverviewPage

**Pull request merged**
