### PR TITLE
Update EclipseLink 2.6_WAS for JPA 2.1

### PR DESCRIPTION
**Pull request by dazey3**
for #19185
for #19182 
for #19179 
for #19176 
for #19327 
for #19342

### CODE REVIEW

**Comment by dazey3** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jpa_eclipselink_fat,com.ibm.ws.jpa.tests.spec10.entitymanager_jpa_2.0_fat,com.ibm.ws.jpa.tests.spec10.entitymanager_jpa_2.1_fat,com.ibm.ws.jpa.tests.spec10.entitymanager_jpa_2.2_fat,com.ibm.ws.jpa.tests.spec10.entitymanager_jpa_3.0_fat,com.ibm.ws.jpa.tests.spec10.query_jpa_2.0_fat,com.ibm.ws.jpa.tests.spec10.query_jpa_2.1_fat,com.ibm.ws.jpa.tests.spec10.query_jpa_2.2_fat,com.ibm.ws.jpa.tests.spec10.query_jpa_3.0_fat

**Comment by dazey3** [comment]
I ran a build with both this EclipseLink update and a Feature Checker update: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_K2a3oFakEeyWaZwSyDrk3A

**Review by jgrassel — APPROVED** [review]

**Comment by dazey3** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jpa_eclipselink_fat,com.ibm.ws.jpa.tests.spec10.entitymanager_jpa_2.0_fat,com.ibm.ws.jpa.tests.spec10.entitymanager_jpa_2.1_fat,com.ibm.ws.jpa.tests.spec10.entitymanager_jpa_2.2_fat,com.ibm.ws.jpa.tests.spec10.entitymanager_jpa_3.0_fat,com.ibm.ws.jpa.tests.spec10.query_jpa_2.0_fat,com.ibm.ws.jpa.tests.spec10.query_jpa_2.1_fat,com.ibm.ws.jpa.tests.spec10.query_jpa_2.2_fat,com.ibm.ws.jpa.tests.spec10.query_jpa_3.0_fat

**Comment by dazey3** [comment]
#run-libby-bot

**Pull request merged**
