### PR TITLE
Move io.openliberty.checkpoint bundle to kernel

### PR DESCRIPTION
**Pull request by tjwatson**

### CODE REVIEW

**Comment by tjwatson** [comment]
#build

**Review by dazavala — APPROVED** [review]
Looks good!  No nits.

**Comment by tjwatson** [comment]
#build

Needed to fix up the unit tests.

**Comment by dmuelle** [comment]
It looks like there are no new messages that need ID review here. I've add the `ID review not needed` label.

**Comment by tjwatson** [comment]
#build

**Comment by posmith** [comment]
L2 message review completed

**Comment by tjwatson** [comment]
#build

**Comment by tjwatson** [comment]
#libby

**Pull request merged**
