### PR TITLE
Update to Smallrye OpenAPI 3.1.1 and add Jandex 3

### LINKED ISSUE #23687: Consume latest Smallrye OpenAPI
Currently we're using a release candidate version of Smallrye OpenAPI. We should update to the final version now that it's available.

### PR DESCRIPTION
**Pull request by Azquelt**
Additionally the 3.1 spec API artifact is now on maven central so we can reference it there.

SmallRye OpenAPI 3.1.1 depends on Jandex 3, so we also need to add that. Jandex 3 has breaking changes compared to Jandex 2 so Jandex 2 also needs to remain to support older features which use it. I have created a private feature for Jandex 3 since I anticipate that other features will also depend on it.

For the moment, there's one class which is overlaid, I have raised an issue which would allow us to remove that here: smallrye/smallrye-open-api#1333

Fixes #23687

### CODE REVIEW

**Comment by Azquelt** [comment]
#build

**Comment by Azquelt** [comment]
#build
#libby
#spawn.fullfat.buckets=com.ibm.ws.microprofile.openapi_fat,io.openliberty.microprofile.openapi.2.0.internal_fat,io.openliberty.microprofile.openapi.3.0.internal_fat_tck,io.openliberty.microprofile.openapi.3.1.internal_fat_tck

**Comment by Azquelt** [comment]
Rebuild: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_lXr80JEGEe2FQJgc_COkyw

**Comment by Azquelt** [comment]
#build
#libby
#spawn.fullfat.buckets=com.ibm.ws.microprofile.openapi_fat,io.openliberty.microprofile.openapi.2.0.internal_fat,io.openliberty.microprofile.openapi.3.0.internal_fat_tck,io.openliberty.microprofile.openapi.3.1.internal_fat_tck

**Comment by Azquelt** [comment]
During code review, we noticed that although the new bundles are correct, the old smallrye-open-api bundles don't list jandex on their classpath which results in a manifest with no version. This would break if it was used with a feature which included jandex since it would be wired to the wrong bundle.

When rebundling a third-party dependency, it's possible to depend on a package without any reference to it in the bnd file so I think it's necessary for me to search through the built version of all bundle manifests to see if there are any references to jandex packages which don't have a version.

**Comment by Azquelt** [comment]
I did a search of the manifest files of all bundles from a recent release build and found a few that import jandex without version ranges. I've updated the bnd files to include the relevant version of jandex on the build path so that bnd will generate an appropriate version range.

It looks like the Narayana bundle has some other unversioned imports which may need to be fixed in the future but I haven't tried to fix those here.

@idlewis please review [b8fc06c](https://github.com/OpenLiberty/open-liberty/pull/23686/commits/b8fc06c384c1d5dd1b089524a0475625178eb9c9)
@jim-krueger or @WhiteCat22 please review [16c68a5](https://github.com/OpenLiberty/open-liberty/pull/23686/commits/16c68a5c05ca6a502d45ce389225e3196821f7ee)

**Comment by Azquelt** [comment]
#build
#libby
#spawn.fullfat.buckets=com.ibm.ws.microprofile.openapi_fat,io.openliberty.microprofile.openapi.2.0.internal_fat,io.openliberty.microprofile.openapi.3.0.internal_fat_tck,io.openliberty.microprofile.openapi.3.1.internal_fat_tck

**Review by idlewis — DISMISSED** [review]

**Review by tevans78 — DISMISSED** [review]

**Comment by Azquelt** [comment]
Previous build has not started so it will include the latest changes.

#libby

**Comment by Azquelt** [comment]
Added a manual version range for org.eclipse.microprofile.config to `io.openliberty.io.smallrye.openapi.core` to allow it to work with either MP Config 2.0 or 3.0.

**Comment by Azquelt** [comment]
#libby

**Comment by Azquelt** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.microprofile.openapi_fat,io.openliberty.microprofile.openapi.2.0.internal_fat,io.openliberty.microprofile.openapi.3.0.internal_fat_tck,io.openliberty.microprofile.openapi.3.1.internal_fat_tck

**Review by tevans78 — APPROVED** [review]

**Pull request merged**
