### PR TITLE
Issue #20522: Update ExpressionLanguage 4.0 to 10.0.18

### LINKED ISSUE #20522: Update ExpressionLanguage 4.0 API/Impl to 10.0.18
**Describe the bug**  
A new version of the Tomcat Expression Language API / Implementation is available. Update from the current 10.0.14 version to the latest 10.0.18 version.

**Steps to Reproduce**  
N/A

**Expected behavior**  
N/A

**Diagnostic information:**  
N/A

**Additional context**  
[API](https://search.maven.org/artifact/org.apache.tomcat/tomcat-el-api/10.0.18/jar)
[Implementation](https://search.maven.org/artifact/org.apache.tomcat/tomcat-jasper-el/10.0.18/jar)

### PR DESCRIPTION
**Pull request by pnicolucci**
fixes #20522

### CODE REVIEW

**Comment by pnicolucci** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.el.3.0_fat,com.ibm.ws.jsp.2.3_fat

**Comment by pnicolucci** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.el.3.0_fat,com.ibm.ws.jsp.2.3_fat

**Comment by pnicolucci** [comment]
As part of this PR we need to check look at the overlays we have in the el 40 projects and determine if any updates are necessary from the source we're pulling in.

**Comment by pnicolucci** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.el.3.0_fat,com.ibm.ws.jsp.2.3_fat

**Comment by pnicolucci** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.el.3.0_fat,com.ibm.ws.jsp.2.3_fat

**Comment by pnicolucci** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.el.3.0_fat,com.ibm.ws.jsp.2.3_fat

**Comment by pnicolucci** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.el.3.0_fat,com.ibm.ws.jsp.2.3_fat

**Comment by pnicolucci** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.el.3.0_fat,com.ibm.ws.jsp.2.3_fat

**Review by isaacrivriv — APPROVED** [review]
Looks good, thanks!

**Comment by pnicolucci** [comment]
#libby

**Review by volosied — APPROVED** [review]
LGTM

**Pull request merged**
