### PR TITLE
Transient Exception handling

### PR DESCRIPTION
**Pull request by jonhawkes**
#build

### CODE REVIEW

**Comment by jonhawkes** [comment]
#build

**Comment by jonhawkes** [comment]
#build 
#run-libby-bot

**Comment by jonhawkes** [comment]
#build 
#run-libby-bot

**Comment by jonhawkes** [comment]
#build

**Comment by jonhawkes** [comment]
#build

**Review by neilgsyoung — APPROVED** [review]
Looks good.

**Comment by jonhawkes** [comment]
#build

**Pull request merged**
