### PR TITLE
use long instead of integer in SipApplicationSession

### PR DESCRIPTION
**Pull request by TiborBeres**
We are replacing int with long to allow more sip application sessions

### CODE REVIEW

**Comment by TiborBeres** [comment]
#build, #spawn.fullfat.buckets=com.ibm.ws.sipcontainer_fat,com.ibm.ws.sipcontainer_fat_1,com.ibm.ws.sipcontainer_fat_2,com.ibm.ws.sipcontainer_fat_3,com.ibm.ws.sipcontainer_fat_4,com.ibm.ws.sipcontainer_fat_5,com.ibm.ws.sipcontainer_fat_6,com.ibm.ws.sipcontainer_fat_7

**Comment by TiborBeres** [comment]
test failures in the personal build are known intermittent issues, not related to the code change

**Comment by TiborBeres** [comment]
pull request for issue #27712

**Comment by TiborBeres** [comment]
Fixes #27712

**Review by epj — APPROVED** [review]
OK

**Pull request merged**
