### PR TITLE
JAX-WS: Refactor configuration fats for clearer repeat rules

### PR DESCRIPTION
**Pull request by neuwerk**
This PR refactors `io.openliberty.jaxws.config_fat` to add additional fat repeats for EE 8.

### CODE REVIEW

**Comment by neuwerk** [comment]
#build

**Comment by neuwerk** [comment]
#build

**Review by BerksanAtes — APPROVED** [review]
Looks good to me!

**Comment by neuwerk** [comment]
#build

**Comment by wraschke** [comment]
#libby

**Pull request merged**
