### PR TITLE
More feature updates for Jakarta 9 enablement

### LINKED ISSUE #16127: ID: authFilter element is missing from generated feature docs and has incorrect descriptions
**Describe the bug**
The Open LIberty autogenerated docs for the `authFilter` element, which is generated from [this metatype.properties file](https://github.com/OpenLiberty/open-liberty/blob/integration/dev/com.ibm.ws.security.authentication.filter/resources/OSGI-INF/l10n/metatype.properties) (and other files in the [com.ibm.ws.security.authentication.filter directory](https://github.com/OpenLiberty/open-liberty/tree/integration/dev/com.ibm.ws.security.authentication.filter)), has two issues:

1. The autogen is not pulling in the attribute descriptions from [com.ibm.ws.security.authentication.filter/resources/OSGI-INF/l10n/metatype.properties](https://github.com/OpenLiberty/open-liberty/blob/integration/dev/com.ibm.ws.security.authentication.filter/resources/OSGI-INF/l10n/metatype.properties). Instead, it pulls in a single description for all the attributes, "A unique configuration ID.". See [the authFilter autogen page](https://www.openliberty.io/docs/21.0.0.2/reference/config/authFilter.html) for example.
2. The `authFilter` configuration element has disappeared from all generated feature doc pages which previously included the element in the "Feature configuration elements". This bug occurred sometime between the 20.0.0.11 and 20.0.0.12 Ga releases. For example, see the [20.0.0.11 version of the MpJWT feature page](https://www.openliberty.io/docs/20.0.0.11/reference/feature/mpJwt-1.1.html), which displays the element, and any later version of the feature page, [for example 21.0.0.2](https://www.openliberty.io/docs/21.0.0.2/reference/feature/mpJwt-1.1.html), which do not. This is the case for all liberty features that use `authFilter` .

This information is not maintained by the docs team and is pulled in automatically from properties files in the Open Liberty repo.

**Steps to Reproduce**
See doc links above

**Expected behavior**
1. The authFilter autogen page should pull in the appropriate attribute descriptions that are specified in [com.ibm.ws.security.authentication.filter/resources/OSGI-INF/l10n/metatype.properties](https://github.com/OpenLiberty/open-liberty/blob/integration/dev/com.ibm.ws.security.authentication.filter/resources/OSGI-INF/l10n/metatype.properties).
2. all version of feature pages for feaures that use authFilter should display the authFilter element in the "Feature configuration elements" list.

**Diagnostic information:**
 - OpenLiberty DOCS Versions 20.0.0.12 and later (currently through 21.0.0.2)

**Additional context**
https://github.com/OpenLiberty/open-liberty/pull/14099 may be relevant @jvanhill @utle

### PR DESCRIPTION
**Pull request by jhanders34**
- Consolidate to only having persistentExecutor-1.0 and use private features to pick the right Jakarta features to enable
- Switch remaining Java EE vs Jakarta EE 9 auto features to private features
- Don't jakartaeeMe the jpa.container.v22 bundle since it does not need to be transformed
- Remove adminSecurity private feature from jakartaee-9.0 since it isn't needed any longer
- Remove empty build.gradle file
- Add new FAT to a github action test category

### CODE REVIEW

**Comment by jhanders34** [comment]
#build

**Comment by jhanders34** [comment]
#build

**Comment by jhanders34** [comment]
#libby
#build

**Review by KyleAure — APPROVED** [review]

**Review by jgrassel — APPROVED** [review]
LGTM

**Review by tjwatson — APPROVED** [review]

**Review by njr-11 — APPROVED** [review]
If the persistentExecutor feature is ever GA'ed, I expect it would be against a future level of Jakarta EE only, and not Java EE. But not being GA at all yet, I suppose it's fine to consolidate the current use of it.

**Review by sebratton — APPROVED** [review]

**Comment by jhanders34** [comment]
#libby

**Pull request merged**
