### PR TITLE
SpringBoot 3.0: Initial features

### PR DESCRIPTION
**Pull request by cbridgha**

### CODE REVIEW

**Comment by cbridgha** [comment]
#build

**Review by helyarp — COMMENTED** [review]
Looks good!

**Comment by posmith** [comment]
L2 message review completed

**Comment by cbridgha** [comment]
#build

**Comment by cbridgha** [comment]
Latest build looks good - we are close!

https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_CXIwMAAMEe6LLo57pmOrBg

**Review by tbitonti — APPROVED** [review]

**Comment by cbridgha** [comment]
#libby

**Pull request merged**
