### PR TITLE
Issue #21212: Update Infinispan client configuration in FAT so that i…

### LINKED ISSUE #21212: SEC 380: Fix JCache Infinispan configuration for security cache FATs
The Infinispan configuration for the security cache FATs is for embedded and not for a client so the caches are not being configured correctly on the Infinispan server.

Update the configuration so that we are using the correct configuration.

### PR DESCRIPTION
**Pull request by jvanhill**
…t is not using embedded configuration.

fixes #21212

### CODE REVIEW

**Comment by jvanhill** [comment]
#build

**Review by ryanesch — APPROVED** [review]

**Comment by jvanhill** [comment]
#build

**Comment by jvanhill** [comment]
#build
#libby

**Comment by jvanhill** [comment]
#build
#libby

**Comment by jvanhill** [comment]
#build
#libby

**Pull request merged**
