### PR TITLE
Remove extendedHandshake from plugin autogen

### PR DESCRIPTION
**Pull request by pmd1nh**
https://github.com/OpenLiberty/open-liberty/issues/25209

reapply PR 24529

### CODE REVIEW

**Comment by pmd1nh** [comment]
Dynamic Routing has disabled extendedHandshake tests from its FAT

https://github.ibm.com/websphere/WS-CD-Open/pull/29611

**Comment by pmd1nh** [comment]
#build

**Comment by pmd1nh** [comment]
bad-overall-build-progress.txt | rtc-merged.xml: No space left on device
-- | --

resubmit

#build

**Comment by posmith** [comment]
L2 message review not required

**Comment by pmd1nh** [comment]
based
#build

**Comment by pmd1nh** [comment]
#libby

**Review by volosied — APPROVED** [review]

**Pull request merged**
