### PR TITLE
Issue#20854: Re-enable CDI, Transaction, Servlet31 tests for EE10

### PR DESCRIPTION
**Pull request by pmd1nh**
Enable CDI tests from #20854

### CODE REVIEW

**Comment by pmd1nh** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.cdi.api_fat,com.ibm.ws.cdi.jee_fat,com.ibm.ws.cdi.ejb_fat

**Comment by pmd1nh** [comment]
only one failure now


com.ibm.ws.cdi.jee.jaxrs.inject.InjectIntoPathTest | 3 | 1 | 0 | 6 s | 2
-- | -- | -- | -- | -- | --
testInjectionIntoPath_EE10_FEATURES | 1 | 1 | 0 | 5 s | 3
 

However, Tom Evan is going to Skip this test 

https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.workitem.viewWorkItem&id=291264

**Comment by pmd1nh** [comment]
Also enabled TransactionalTestServlet EE10 tests. @jonhawkes

**Comment by pmd1nh** [comment]
Enable Servlet 31 [FormLoginReadListenerTest]
Enable TransactionalTestServlet

#build
#spawn.fullfat.buckets=com.ibm.ws.webcontainer.servlet.3.1_fat,com.ibm.ws.transaction.core_fat.cdi

**Review by jonhawkes — APPROVED** [review]

**Review by pnicolucci — APPROVED** [review]

**Comment by pnicolucci** [comment]
#libby

**Comment by pmd1nh** [comment]
One failing test in above PB has an associated defect 
https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.workitem.viewWorkItem&id=291264

PR https://github.com/OpenLiberty/open-liberty/pull/21706 has merged to disable that test in EE10.

**Pull request merged**
