### PR TITLE
Synchronize lease delete and act on server stopping

### LINKED ISSUE #16540: Transaction Peer Recovery: lease heartbeat collides with server shutdown
It is possible that the thread that has been spawned to update the lease on a server's recovery logs may attempt to update the lease as the server is shutting down and the infrastructure it needs to do the update is itself shutting down.

### PR DESCRIPTION
**Pull request by neilgsyoung**
fixes #16540

### CODE REVIEW

**Comment by neilgsyoung** [comment]
#build

**Comment by neilgsyoung** [comment]
#build

**Comment by neilgsyoung** [comment]
#build

**Comment by neilgsyoung** [comment]
#build

**Review by jonhawkes — APPROVED** [review]

**Pull request merged**
