### PR TITLE
Add write permission to javapermission

### LINKED ISSUE #22456: Test Failure: io.openliberty.microprofile.telemetry.internal.tests.AutoInstrumentationTest.systemSpanTest_EE10_FEATURES_MicroProfile_60
RTC 292476

```
systemSpanTest_EE10_FEATURES_MicroProfile_60:junit.framework.AssertionFailedError: 2022-09-08-04:34:10:679 result is null
    at io.openliberty.microprofile.telemetry.internal.tests.AutoInstrumentationTest.systemSpanTest(AutoInstrumentationTest.java:115)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at componenttest.custom.junit.runner.FATRunner$1.evaluate(FATRunner.java:199)
    at org.testcontainers.containers.FailureDetectingExternalResource$1.evaluate(FailureDetectingExternalResource.java:30)
    at componenttest.custom.junit.runner.FATRunner$2.evaluate(FATRunner.java:352)
    at componenttest.custom.junit.runner.FATRunner.run(FATRunner.java:173)
    at componenttest.rules.repeater.RepeatTests$CompositeRepeatTestActionStatement.evaluate(RepeatTests.java:143)
```

### PR DESCRIPTION
**Pull request by fmhwong**
Fix #22456

- Add write permission to javapermission

### CODE REVIEW

**Comment by fmhwong** [comment]
#build

**Comment by fmhwong** [comment]
https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_2GX6QDLYEe2Kc-z_2q9Pqw

**Comment by fmhwong** [comment]
Test passed on Build Liberty Full Fat Java 2 Security 20220912-1453

https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_2GX6QDLYEe2Kc-z_2q9Pqw

**Review by Yas-Franco — APPROVED** [review]
Looks good!

**Pull request merged**
