### PR TITLE
Upgrade testcontainers to 1.20.2

### PR DESCRIPTION
**Pull request by KyleAure**
- [x] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [x] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [x] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

Upgrading to latest version of testcontainers

### CODE REVIEW

**Comment by KyleAure** [comment]
#build - personal build

**Comment by KyleAure** [comment]
Personal database rotation pipeline: https://libh-proxy1.fyre.ibm.com/cognitive-dev/pipelineAnalysis.html?pipelineId=b2531627-4b94-49e1-820d-ee00ccc61862

Target locations of links might be accessible only to IBM employees.

**Comment by KyleAure** [comment]
#libby - check headers
#build - personal build

**Comment by KyleAure** [comment]
Personal database rotation pipeline: https://libh-proxy1.fyre.ibm.com/cognitive-dev/pipelineAnalysis.html?pipelineId=db9d897b-c6bc-4167-a92e-0e00a7ad2f9d

Target locations of links might be accessible only to IBM employees.

**Comment by KyleAure** [comment]
Pipeline: Failed, known defects and one infrastructure issue
Pipeline DBRotation: Passed
RTC Build: Still running

**Comment by KyleAure** [comment]
#libby - re-check headers
#build - re-run personal build with improvements and unit tests

**Review by mswatosh — APPROVED** [review]

**Comment by KyleAure** [comment]
Pipeline - failed will all known defects
RTC build - took 10 hours for the bot to respond. 😞 
I'll take the passing Pipeline build as enough to merge.

**Pull request merged**
