### PR TITLE
Reintroduce 21891 - Testcontainer project and image tracking

### LINKED ISSUE #22186: Re-introduce change reverted from 21891
Re-introduce change reverted from https://github.com/OpenLiberty/open-liberty/pull/21891

### PR DESCRIPTION
**Pull request by KyleAure**
Fixes #22186

### CODE REVIEW

**Comment by KyleAure** [comment]
#build

**Review by mswatosh — APPROVED** [review]

**Comment by KyleAure** [comment]
#build

**Comment by KyleAure** [comment]
#libby

**Comment by KyleAure** [comment]
Personal build failed with two known defects, and a child build failed to start. 
I re-ran the child build here: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_ylAEwCCOEe2b2O1gXXKb4w
(Target locations of links might be accessible only to IBM employees.)

**Review by Azquelt — COMMENTED** [review]
Header on the cached files is helpful, thanks

**Pull request merged**
