### PR TITLE
Add missing DDL for JPA Locking FAT

### PR DESCRIPTION
**Pull request by dazey3**
Some missing DDL from https://github.com/OpenLiberty/open-liberty/pull/14235

Signed-off-by: Will Dazey <dazeydev.3@gmail.com>

### CODE REVIEW

**Comment by dazey3** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jpa_locking_fat

**Review by tkburroughs — APPROVED** [review]

**Comment by dazey3** [comment]
Postgres build: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_U3XoMCjlEeugFadUkByo4Q

SQLServer build: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_dNpZ0CjpEeugFadUkByo4Q

**Comment by dazey3** [comment]
SQLServer: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_p-eHsSk7EeugFadUkByo4Q
Postgres: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_vYBmUCk7EeugFadUkByo4Q
Oracle: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_18L3cCmqEeugFadUkByo4Q

**Review by tkburroughs — APPROVED** [review]

**Comment by dazey3** [comment]
#run-libby-bot

**Pull request merged**
