### PR TITLE
Create xerces impl bundle

### PR DESCRIPTION
**Pull request by tevans78**
Following on from https://github.com/OpenLiberty/open-liberty/pull/19429 this PR is to move xercesImpl to a common bundle.

### CODE REVIEW

**Comment by tevans78** [comment]
#build

**Comment by tevans78** [comment]
#build

**Review by benjamin-confino — APPROVED** [review]

**Comment by tevans78** [comment]
#build

**Review by benjamin-confino — APPROVED** [review]

**Comment by tevans78** [comment]
Forced push was only to rebase after https://github.com/OpenLiberty/open-liberty/pull/19472 was merged. No actual code changes.

**Comment by tevans78** [comment]
#libby

**Pull request merged**
