### PR TITLE
Move adminCenter-1.0 to OL

### PR DESCRIPTION
**Pull request by fritze2**
- Add com.ibm.websphere.appserver.features/visibility/public/adminCenter-1.0
- Add ant_build.js
- Add com.ibm.ws.ui
- Add com.ibm.ws.ui.example.tool
- Add com.ibm.ws.ui.shared
- Add com.ibm.ws.ui.tool.collectivemanagement
- Add com.ibm.ws.ui.tool.deploy
- Add com.ibm.ws.ui.tool.explore
- Add com.ibm.ws.ui.tool.javaBatch
- Add com.ibm.ws.ui.tool.serverConfig

### CODE REVIEW

**Comment by fritze2** [comment]
#run-libby-bot

**Comment by fritze2** [comment]
#run-libby-bot

**Comment by fritze2** [comment]
#build

**Comment by fritze2** [comment]
#build

**Comment by fritze2** [comment]
#build

**Comment by fritze2** [comment]
#build

**Comment by wraschke** [comment]
#build

**Comment by fritze2** [comment]
#run-libby-bot

**Comment by fritze2** [comment]
The personal build doesn't have UI related failures, however the UI projects in WAS override the projects being built in OL so it's masking whether the projects in this commit have failures. If removing the UI projects from WAS causes failures, I'll commit patches to these projects in OL before removing them from WAS.

**Pull request merged**
