### PR TITLE
Issue #13934: Update faces-3.0 beans.xml namespace

### LINKED ISSUE #13934: Update beans.xml namespace in beans.xml for myfaces 3.0 implementation
See: #13925 we'll want to update our namespace once a fix has been delivered in CDI.

### PR DESCRIPTION
**Pull request by pnicolucci**
fixes #13934

### CODE REVIEW

**Comment by pnicolucci** [comment]
#build

**Review by volosied — APPROVED** [review]

**Comment by pnicolucci** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jsf.2.3_fat

**Comment by pnicolucci** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jsf.2.3_fat

**Comment by pnicolucci** [comment]
#run-libby-bot

**Pull request merged**
