### PR TITLE
Add JakartaEEAction.setSkipTransformation() method and use it

### PR DESCRIPTION
**Pull request by jhanders34**
- Instead of using special IDs when doing EE9, EE10 and EE11 repeats to not do transformation, add state to JakartaEEAction to indicate that the application are already jakarta-ized.
- Update other repeat functions to have an option to say that applications are already jakarta-ized and pass that state onto JakartaEEAction subclass instance.
- Update some FAT projects that are testing Jakarta function, to not use javax classes and not require transformation.
- Update jaxrs restfulWS tests to use mpRestClient-4.0 for EE 11 repeat now that the feature supports EE 11
- Remove dependency on addJakartaTransformer from build.gradle now that the projects don't require transformation
- Add some repeats for appAuthentication FAT and update user features used for security to support EE 11 tolerates

### CODE REVIEW

**Comment by jhanders34** [comment]
#libby #build

**Comment by jhanders34** [comment]
#build

**Comment by jhanders34** [comment]
#build

**Comment by jhanders34** [comment]
#libby

**Review by njr-11 — APPROVED** [review]

**Review by c00crane — APPROVED** [review]
Reviewed SSO changes and added Ut for core security.

**Review by c00crane — APPROVED** [review]

**Review by jim-krueger — APPROVED** [review]
Checked RestfulWS changes.   Looks good.

**Review by jim-krueger — APPROVED** [review]

**Pull request merged**
