### PR TITLE
Opentracing FAT

### PR DESCRIPTION
**Pull request by tbitonti**
Personal build (all green):
https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_0OSTop8VEeew8ISV5CV8GQ&tab=com.ibm.team.build.web.ui.internal.editors.result.test.TestProvider
Note new FAT:
com.ibm.ws.opentracing_fat
This is the FAT component for the open tracing feature.

### CODE REVIEW

**Comment by tbitonti** [comment]
This update adds FATs.  As such, it does not have tests, rather, the content of the update is a new set of tests for function already present.
The added FATs were tested by running a personal build and verifying that the tests all ran and all passed.

**Comment by aguibert** [comment]
@tbitonti you will need to get one of the admins to add you to the OpenLiberty organization so that you get the [CLA not needed] tag on your PR.  Here is the admin list:
https://github.com/orgs/OpenLiberty/teams/admin/members

**Comment by tbitonti** [comment]
Updated with changes per review by Steve Fontes.
New personal build is green: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_x-tygKLrEeee-IeTp-fxEQ

**Comment by tbitonti** [comment]
#build

**Pull request closed without merging**
