### PR TITLE
Restore MP JWT 1.2 and 2.0 TCK except failing test on Java 19

### LINKED ISSUE #22933: MP JWT 1.2 and 2.0 TCKs won't run at 22.0.0.11
**Describe the bug**  
The entire MP JWT 1.2 and 2.0 TCKs were disabled in https://github.com/OpenLiberty/open-liberty/pull/22745 for Java 19+

The preferred way to handle this is to just disable the individual TCK test that fails in Java 19+.

**Steps to Reproduce**  
Try to run the MP JWT 1.2 or 2.0 TCKs at 22.0.0.11 using Java 19+.

**Expected behavior**  
The MP JWT 1.2 or 2.0 TCK would run all but the failing test.

**Diagnostic information:**  
 - OpenLiberty Version: 22.0.0.11
 - Affected feature(s): MP JWT 1.2 or 2.0 TCK
 - Java Version: Java 19

### PR DESCRIPTION
**Pull request by gjwatts**
Fixes https://github.com/OpenLiberty/open-liberty/issues/22933

### CODE REVIEW

**Comment by gjwatts** [comment]
#build

**Review by teddyjtorres — APPROVED** [review]

**Comment by gjwatts** [comment]
#build

**Comment by gjwatts** [comment]
Java 19 personal build passed with these changes in it.

**Comment by wraschke** [comment]
Test

**Comment by gjwatts** [comment]
#build

**Comment by gjwatts** [comment]
Ran into conflicts with [Tom's recent changes](https://github.com/OpenLiberty/open-liberty/pull/22785).  Had to combine them and push those changes out again.  Rebuilding.

**Comment by gjwatts** [comment]
#libbybot

**Review by tevans78 — APPROVED** [review]

**Pull request merged**
