### PR TITLE
Split the Jakarta Mail API bundle into a separate feature

### PR DESCRIPTION
**Pull request by andymc12**
This change allows features like `restfulWSClient-3.0` that need the Jakarta Mail APIs to depend on a Mail 2.0 API feature that does not include the full implementation classes - and does not expose the `jakarta.mail.*` packages to user applications.

This change includes:
- creates new io.openliberty.jakarta.mail-2.0 feature for the API bundles
- puts `jakarta.mail.*` classes into _bundle_ in dev/api/spec, and removes them from io.openliberty.com.sun.mail.jakarta.mail.2.0 bundle
- includes `mail-2.0` feature in the `jakartaee-9.0` convenience feature
- replaces `mail-2.0` (full) feature with new io.openliberty.jakarta.mail-2.0 feature for `restfulWSClient-3.0`

### CODE REVIEW

**Comment by andymc12** [comment]
#build

**Review by dazavala — APPROVED** [review]
Feature naming conventions and API factorization look correct.  Approved.

**Review by uberskigeek — APPROVED** [review]

**Comment by andymc12** [comment]
Left a reference in to a deleted feature... should be fixed now - new #build

**Comment by andymc12** [comment]
#libby

**Pull request merged**
