### PR TITLE
Return the correct HttpServletMapping from HttpServletRequest.getHttp…

### PR DESCRIPTION
**Pull request by zaroman**
…ServletMapping() during include, async, and when using a named dispatcher.

Also, avoid a potential NPE when getHttpServletMapping() is called from a filter and there is no target servlet.

### CODE REVIEW

**Comment by zaroman** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.webcontainer.servlet.4.0_fat

**Comment by zaroman** [comment]
fixes #2044

**Comment by pnicolucci** [comment]
add some traces to pushServletReference and we should be good.

**Comment by zaroman** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.webcontainer.servlet.4.0_fat

**Pull request merged**
