### PR TITLE
update weld to 3.1.8.Final

### LINKED ISSUE #18835: Update weld 3 to 3.1.8.Final
Weld has released an update to Weld3 and so we must re-consume it.

### PR DESCRIPTION
**Pull request by benjamin-confino**
fixes #18835 and #18836

### CODE REVIEW

**Comment by benjamin-confino** [comment]
#build

**Comment by benjamin-confino** [comment]
#build

**Comment by benjamin-confino** [comment]
#build

**Comment by benjamin-confino** [comment]
#build

**Comment by benjamin-confino** [comment]
#run-libby-bot

**Comment by Azquelt** [comment]
I see a reference to `weld-osgi-bundle` in `com.ibm.websphere.appserver.cdi-2.0.feature` - should that also be updated?

**Review by Azquelt — APPROVED** [review]

**Pull request merged**
