### PR TITLE
Added typo fix for API constant

### LINKED ISSUE #13922: Typo in rename Webcontainer Constant
During discovery of javax references that were not transformed, found a typo in the [javax.servlet.forward.query_string](https://github.com/OpenLiberty/open-liberty/blob/integration/dev/wlp-jakartaee-transform/rules/jakarta-direct.properties#L19) rename rule. Should be renamed to *jakarta.servlet.forward.query_string* to follow what's stated on the [API](https://jakarta.ee/specifications/servlet/5.0/apidocs/constant-values.html)

### PR DESCRIPTION
**Pull request by isaacrivriv**
fixes #13922

### CODE REVIEW

**Comment by isaacrivriv** [comment]
Added the rule and built the project. Then built the com.ibm.ws.webcontainer project and decompiled the jakarta jar and verified that the string was corrected

**Comment by isaacrivriv** [comment]
#build

**Comment by volosied** [comment]
oops. good catch.

**Comment by isaacrivriv** [comment]
#build

**Comment by isaacrivriv** [comment]
#run-libby-bot

**Review by pnicolucci — APPROVED** [review]
LGTM

**Comment by isaacrivriv** [comment]
Merging due to buildcon being 3

**Pull request merged**
