### PR TITLE
Phase 4 EE 10 repeats of existing functions

### PR DESCRIPTION
**Pull request by jhanders34**
- Add EE 10 repeats to FATs that test features that are value-add features or EE features that do not have a version change in EE 10.
- Update com.ibm.ws.jbatch.misc_fat to repeat for EE 10.

For #18722

### CODE REVIEW

**Comment by jhanders34** [comment]
#build

**Comment by jhanders34** [comment]
#build

**Comment by jhanders34** [comment]
#build

**Comment by jhanders34** [comment]
#build

**Review by njr-11 — COMMENTED** [review]
It looks like this is repeating coverage on Jakarta EE 10 across the remaining Concurrency, JCA, and JDBC buckets.  I remember a decision that was made several years ago (Andy from my team had raised the issue) that repeats should not be done on every test and every bucket to avoid overburdening build infrastructure, but only strategically where the coverage makes the most sense. Accordingly, these components have gone through and made some of the buckets to run against different Jakarta EE levels, some with repeats, and others without.  But this looks like with this change now a bunch of others are being repeated. Has the direction on this changed or are there more specific reasons why these buckets ought to be repeated?

**Comment by jhanders34** [comment]
> It looks like this is repeating coverage on Jakarta EE 10 across the remaining Concurrency, JCA, and JDBC buckets. I remember a decision that was made several years ago (Andy from my team had raised the issue) that repeats should not be done on every test and every bucket to avoid overburdening build infrastructure, but only strategically where the coverage makes the most sense. Accordingly, these components have gone through and made some of the buckets to run against different Jakarta EE levels, some with repeats, and others without. But this looks like with this change now a bunch of others are being repeated. Has the direction on this changed or are there more specific reasons why these buckets ought to be repeated?

If you want me to remove the repeats for concurrency, jca and jdbc, I can, but I don't think they take a lot of resources to run.

**Review by njr-11 — APPROVED** [review]
> I don't think they take a lot of resources to run.

Back when the issue was raised, the concern was not about individual buckets taking up a lot of resources to repeat, but with the conglomerate of all test buckets repeating unnecessarily.  However, if these components are the only ones that are still trying to avoid repeats, there is no point in that, and it makes to make them like all the others.  I'll go ahead and approve the review so you can choose how to best handle.

**Review by cgianfra — APPROVED** [review]

**Review by tkburroughs — APPROVED** [review]

**Comment by jhanders34** [comment]
#libby

**Pull request merged**
