### PR TITLE
Misc Jakartasec FAT cleanup

### PR DESCRIPTION
**Pull request by c00crane**
Do a little cleanup before we say we're done with Jakartasec FATs.

1. Add some more comments to the AuthenticationTests
2. Update the test classes to replace random selection on repeat.  Many of the test classes were randomly selecting the type of token that the OP would create (opaque or jwt).  For now, we can have each test class repeat with each token type (we may reduce that in the future)
3. Update the order of the test classes listed in the FAT project .classpath files.  This will reorder how the apps appear in Eclipse.  For projects with a lot of test applications, putting them in alphabetical order makes it easier to find an app.

### CODE REVIEW

**Comment by c00crane** [comment]
I modified the repeat logic - each test class will now be run with both token types in FULL mode and each test class will choose one of these to use for LITE mode.
I also updated the test classes choosing a subset of test cases to run in LITE mode.  For a few test classes with few test cases, I marked the class to run in LITE mode (all test cases in the class will run).

**Comment by c00crane** [comment]
#libby
#build
#spawn.fullfat.buckets=io.openliberty.security.jakartasec.3.0.internal_fat,io.openliberty.security.jakartasec.3.0.internal_fat.common,io.openliberty.security.jakartasec.3.0.internal_fat.config,io.openliberty.security.jakartasec.3.0.internal_fat.logout,io.openliberty.security.jakartasec.3.0.internal_fat.refresh

**Comment by c00crane** [comment]
#libby
#build
#spawn.fullfat.buckets=io.openliberty.security.jakartasec.3.0.internal_fat,io.openliberty.security.jakartasec.3.0.internal_fat.config.1,io.openliberty.security.jakartasec.3.0.internal_fat.config.2,io.openliberty.security.jakartasec.3.0.internal_fat.config.commonTest,io.openliberty.security.jakartasec.3.0.internal_fat.logout,io.openliberty.security.jakartasec.3.0.internal_fat.refresh

**Comment by c00crane** [comment]
#build
#spawn.fullfat.buckets=io.openliberty.security.jakartasec.3.0.internal_fat,io.openliberty.security.jakartasec.3.0.internal_fat.config.1,io.openliberty.security.jakartasec.3.0.internal_fat.config.2,io.openliberty.security.jakartasec.3.0.internal_fat.config.commonTest,io.openliberty.security.jakartasec.3.0.internal_fat.logout,io.openliberty.security.jakartasec.3.0.internal_fat.refresh

**Review by teddyjtorres — APPROVED** [review]

**Pull request merged**
