### PR TITLE
Issue #2905: update WebsocketEvent.getUser signature

### PR DESCRIPTION
**Pull request by pnicolucci**

### CODE REVIEW

**Comment by pnicolucci** [comment]
fixes #2905

**Comment by pnicolucci** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jsf.2.3_fat,com.ibm.ws.jsf_fat_jsf2.3,com.ibm.ws.jsf_fat_lWAS_jsf2.3,com.ibm.ws.jsf.2.2_fat_jsf2.3

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_qqneADRPEein-4zb_x5ocw&tab=com.ibm.team.build.web.ui.internal.editors.result.overview.OverviewPage

**Comment by wraschke** [comment]
#build

**Comment by pnicolucci** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jsf.2.3_fat,com.ibm.ws.jsf_fat_jsf2.3,com.ibm.ws.jsf_fat_lWAS_jsf2.3,com.ibm.ws.jsf.2.2_fat_jsf2.3

**Pull request merged**
