### PR TITLE
Remove noShip-1.0 from wsoc FATs

### LINKED ISSUE #27644: WebSocket 2.2: Remove noship-1.0 from FATs once we beta
bnd.bnd contains `tested.features:\` which references `noship-1.0`

### PR DESCRIPTION
**Pull request by pnicolucci**
fixes #27644

### CODE REVIEW

**Comment by pnicolucci** [comment]
#build

**Review by volosied — APPROVED** [review]

**Comment by pnicolucci** [comment]
#libby

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#libby

**Pull request merged**
