### PR TITLE
correct intermittant issue affecting plus sign test 

### LINKED ISSUE #13234: correct intermittant issue affecting decodeurlplussign test
The PR for this issue does the following:
1) Remove decodeUrlPlusSign_false.server.xml  and set the decodeUrlPlusSign property directly in the server configuration.
2) Minor formatting changes to servlet31_wcServer/server.xml
3) Ensure that the testServletMapping test case actually waits for the configuration update to complete after restoring the saved server.xml.
4) Update the testDecodeUrlPlusSign test case to directly set the property value in the server.xml rather than using a new server.xml. Also add a finally block to ensure that the configuration is restored to the saved configuration from the start of the test even if the test fails.

### PR DESCRIPTION
**Pull request by epj**
fixes #13234

### CODE REVIEW

**Comment by epj** [comment]
#libbybot

**Comment by epj** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.webcontainer_fat,com.ibm.ws.webcontainer_fat_lWAS,com.ibm.ws.webcontainer_fat_servlet31_webcontainerlWAS,com.ibm.ws.webcontainer.servlet.3.1_fat,com.ibm.ws.webcontainer.servlet.4.0_fat

**Comment by epj** [comment]
We've now seen this same issue under EE8_FEATURES (servlet 4.0) so its not servlet-5.0 specific.  So we need to rethink this fix, just disabling the test for a particular feature set isn't the answer.

**Comment by pnicolucci** [comment]
Closing this as disabling the tests is not valid in this instance. Tests will be fixed with PR: https://github.com/OpenLiberty/open-liberty/issues/13234

**Pull request closed without merging**
