### PR TITLE
11772 Set EE platform dependencies for transaction features

### PR DESCRIPTION
**Pull request by dazavala**
#11772 

Establish the EE platform affinity and tolerance for all the transaction-x.y features to ensure the feature manager rejects (i.e. prevents from resolving) invalid combinations of features dependent on transaction-x.y, and to enable the feature manager to resolve the appropriate transaction-x.y feature dependency for non-public features.

The feature manager may resolve transaction-1.x for dependent javaee features, and must resolve transaction-2.0 for dependent jakarta features, and must reject any combination of features dependent on both transaction-1.x and transaction-2.0.

### CODE REVIEW

**Comment by dazavala** [comment]
#build

**Comment by dazavala** [comment]
#build

**Comment by dazavala** [comment]
The one test failure in the personal build does not involve transaction features.  Merging now.

**Comment by dazavala** [comment]
#libbybot

**Comment by dazavala** [comment]
#run-libby-bot

**Comment by wraschke** [comment]
#libbybot

**Pull request merged**
