### PR TITLE
Add appName to LogRecordContext in JSON logs

### LINKED ISSUE #20919: Add the appName to the LogRecordContext for JSON logs.
Register the application name as a LogRecordContext extension at server startup. Whenever log messages are sent and the application name is known, the application name will be added to the LogRecordContext, with the key `appName` and the value being the application name that the message was logged from. If JSON logging is enabled, a new field called `ext_appName` will be added with the application name.

Add test cases as well, to the above functionality.

### PR DESCRIPTION
**Pull request by pgunapal**
fixes #20919

- Registers the application name to the LogRecordContext and adds the following JSON field: `ext_appName`
- Added test cases to test different scenarios for the above functionality.

### CODE REVIEW

**Comment by pgunapal** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.logging.json_fat,com.ibm.ws.logging_fat

**Comment by pgunapal** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.logging_fat

**Comment by pgunapal** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.logging_fat

**Comment by pgunapal** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.logging_fat

**Comment by pgunapal** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.logging_fat

**Comment by pgunapal** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.logging_fat

**Comment by pgunapal** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.logging_fat

**Comment by pgunapal** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.logging_fat

**Review by fmhwong — APPROVED** [review]
LGTM

**Comment by pgunapal** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.logging_fat

**Comment by pgunapal** [comment]
#libby

**Pull request merged**
