### PR TITLE
Add headers to scim-2.0 responses

### PR DESCRIPTION
**Pull request by wrodrig**
Add response headers to the SCIM-2.0 api requests.

### CODE REVIEW

**Comment by wrodrig** [comment]
#build

**Review by arkarkala — DISMISSED** [review]

**Comment by wrodrig** [comment]
#build
#Libby

**Comment by wrodrig** [comment]
#build
#Libby

**Comment by wrodrig** [comment]
#build
#Libby

**Review by utle — APPROVED** [review]

**Pull request merged**
