### PR TITLE
Fix test failure in RTC 289509. No longer check definitely that we cr…

### PR DESCRIPTION
**Pull request by jvanhill**
…eated the cache for the first server. Some of the JCache providers are not consistent on whether they say a cache already exists.

### CODE REVIEW

**Comment by jvanhill** [comment]
#build

**Review by kristip17 — APPROVED** [review]

**Comment by jvanhill** [comment]
#build

**Comment by jvanhill** [comment]
#libby

**Comment by jvanhill** [comment]
#build

**Comment by jvanhill** [comment]
#build
#libby

**Comment by jvanhill** [comment]
#build
#libby

**Comment by jvanhill** [comment]
The last build had child build fail due to connectivity issues between the build and RTC. However; it was only running the infinispan and hazelcast buckets, which ran 10 times successfully anyway.

**Pull request merged**
