### PR TITLE
check if ran by featureUtility

### LINKED ISSUE #21672: featureUtility modify debug trace
Modify debug trace to show better messages

### PR DESCRIPTION
**Pull request by jjiwooLim**
Fixes #21672

### CODE REVIEW

**Comment by jjiwooLim** [comment]
#build

**Review by bensonlatibm — APPROVED** [review]
lgtm!

**Comment by jjiwooLim** [comment]
#libby-bot

**Comment by jjiwooLim** [comment]
#libby-bot

**Pull request merged**
