### PR TITLE
Do not register monitor metrics when MetricRegistry is null

### LINKED ISSUE #23823: MP Metrics 5.0: Monitor metrics bundle attempts registers metric when metric runtime initialization fails.
When initialization the MP Metrics runtime (i.e. underlying SR and Micrometer implementation), failures can occur which stops the Metrics runtime from being initialized properly. The related monitor metrics bundle `io.openliberty.microprofile.metrics.5.0.monitor.internal` which will start as part of the feature set will continue to initialize and attempt to register vendor (and certain base) metrics. If the MP Metrics runtime fails to initialize, a `null` MetricRegistry is provided to the monitor metrics bundle. Currently, it does not check for a `null` value and proceeds to attempt a registration which leads to a `NullPointerException`.

### PR DESCRIPTION
**Pull request by Channyboy**
#build
fixes #23823

### CODE REVIEW

**Comment by Channyboy** [comment]
#build

**Comment by Channyboy** [comment]
#libby

**Comment by fmhwong** [comment]
Are there anything the user can do when `metricRegistry` is `null`?

**Comment by Channyboy** [comment]
@fmhwong Nope. If the MetricRegistry retrieved from `SharedMetricRegistries` is null then the initiliazation of the SmallRye Metrics (or Micrometer related libraries) failed and the feature is in-operable.

**Comment by fmhwong** [comment]
> @fmhwong Nope. If the MetricRegistry retrieved from `SharedMetricRegistries` is null then the initiliazation of the SmallRye Metrics (or Micrometer related libraries) failed and the feature is in-operable.

Since you just write a debug message only, should we write an info or warning message telling customer how to fix the configuration?

**Comment by Channyboy** [comment]
Yup, that was part of : https://github.com/OpenLiberty/open-liberty/pull/23830

**Review by fmhwong — APPROVED** [review]
LGTM

**Pull request merged**
