### PR TITLE
Eclipse and Java setting updates

### PR DESCRIPTION
**Pull request by jhanders34**
- Remove nonexistent src directory from .classpath files
- Add missing .project and .classpath files for new project
- Add missing test-application source directory
- Update bnd files to have javac and Require-Capability to be Java 11
- Update eclipse jdt core prefs files to have Java 11 settings for Java 11 projects that were not set correctly
- Add missing bndtools.core.prefs file
- Add new FATs to the Github Action build test categories

### CODE REVIEW

**Comment by jhanders34** [comment]
#build

**Review by Yas-Franco — APPROVED** [review]
LGTM - Thanks

**Comment by Azquelt** [comment]
> Add missing .project and .classpath files for new project

I was also adding the project files for `io.openliberty.microprofile.telemetry.1.0.internal_fat` in #22190

**Comment by tevans78** [comment]
#libby

**Review by tevans78 — APPROVED** [review]

**Review by pnicolucci — APPROVED** [review]
Thanks, the Faces 4.0 changes look good!

**Pull request merged**
