### PR TITLE
Update JSF Feature Conflict Tests

### LINKED ISSUE #13890: Investigate testEnsureJSF23FeatureAndJSF22FeatureAreSingletonFeatures_EE9_FEATURES Failure
com.ibm.ws.jsf.2.3_fat/fat/src/com/ibm/ws/jsf23/fat/tests/JSF23JSF22SingletonFeatureTest.java

testEnsureJSF23FeatureAndJSF22FeatureAreSingletonFeatures -- Test Skipped for now

Expected:
`[ERROR   ] CWWKF0033E: The singleton features jsf-2.2 and faces-3.0 cannot be loaded at the same time.  The configured features jsf-2.2 and jsf-2.3 include one or more features that cause the conflict. Your configuration is not supported; update server.xml to remove incompatible features.`

Actual:
```
[ERROR   ] CWWKF0044E: The features jsf-2.2 and el-4.0 cannot be loaded at the same time.  The feature jsf-2.2 of Java EE 7 is incompatible with the feature el-4.0 of Jakarta EE 9.  The configured features jsf-2.2 and faces-3.0 include an incompatible combination of features.  Your configuration is not supported.  Update the configuration to use features that support either the Jakarta EE or Java EE programming models, but not both.
[ERROR   ] CWWKF0029E: Could not resolve module: com.ibm.ws.jsp.jstl.facade.jakarta [67]
  Unresolved requirement: Import-Package: org.apache.taglibs.standard.extra.commons.collections.iterators; version="[2.2.0,3.0.0)"
    -> Export-Package: org.apache.taglibs.standard.extra.commons.collections.iterators; bundle-symbolic-name="com.ibm.ws.jsp"; bundle-version="1.0.45.202009082229"; version="2.2.0"; uses:="org.apache.taglibs.standard.extra.commons.collections"
       com.ibm.ws.jsp [30]
         Unresolved requirement: Import-Package: junit.framework; resolution:="optional"
         Unresolved requirement: Import-Package: junit.textui; resolution:="optional"
         Unresolved requirement: Import-Package: org.apache.xml.serialize; resolution:="optional"
         Unresolved requirement: Import-Package: org.apache.xml.serializer; resolution:="optional"
         Unresolved requirement: Import-Package: com.ibm.websphere.servlet.error; version="0.0.0"
  Unresolved requirement: Import-Package: org.apache.taglibs.standard.extra.commons.collections; version="[2.2.0,3.0.0)"
    -> Export-Package: org.apache.taglibs.standard.extra.commons.collections; bundle-symbolic-name="com.ibm.ws.jsp"; bundle-version="1.0.45.202009082229"; version="2.2.0" 
```

### PR DESCRIPTION
**Pull request by pnicolucci**
fixes #13890

### CODE REVIEW

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#run-libby-bot

**Review by volosied — APPROVED** [review]
Looks great :)

**Pull request merged**
