### PR TITLE
extended document root for jsp fix

### LINKED ISSUE #17482: JSP with trackDependencies should check for updates of included JSP in the extended document root
JSP with trackDependencies=true does not always check for updates of included JSP in the extended document root.  This is inconsistent with tWAS behavior.

### PR DESCRIPTION
**Pull request by epj**
fixes #17482

### CODE REVIEW

**Comment by epj** [comment]
JSP with trackDependencies=true does not always check for updates of included JSP in the extended document root. This is inconsistent with tWAS behavior.

**Comment by epj** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.jsp.2.3_fat

**Review by wtlucy — APPROVED** [review]
LGTM

**Comment by epj** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.jsp.2.3_fat

**Comment by epj** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.jsp.2.3_fat

**Comment by epj** [comment]
#libby-bot

**Comment by epj** [comment]
#Libby-Bot

**Comment by epj** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.jsp.2.3_fat

**Comment by epj** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.jsp.2.3_fat

**Comment by epj** [comment]
The most recent build had a single test failure, in the UI area, unrelated to this change.

**Comment by epj** [comment]
#libby

**Comment by epj** [comment]
fixes #17445

**Pull request merged**
