### PR TITLE
Issue #16557: Remove SharedServer from UpgradeWrite/ReadListenerHttpUnit test

### LINKED ISSUE #16557: Remove SharedServer from UpgradeWrite/ReadListenerHttpUnit for Servlet 3.1 FAT

### PR DESCRIPTION
**Pull request by pnicolucci**
fixes #16557

### CODE REVIEW

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Review by isaacrivriv — APPROVED** [review]
Looks good thanks!

**Comment by pnicolucci** [comment]
#run-libby-bot

**Pull request merged**
