### PR TITLE
Break apart JPA Injection and Spec 2.1 FAT

### PR DESCRIPTION
**Pull request by jgrassel**
Broke apart the Injection (and now 2.1 spec) FAT buckets into smaller pieces, and renamed them to follow the `com.ibm.ws.jpa.tests.` root name to make the JPA FAT directories/projects easier to spot.

### CODE REVIEW

**Comment by jgrassel** [comment]
#build

**Comment by jgrassel** [comment]
Added a commit for breaking apart jpa 2.1 spec bucket.

#run-libby-bot
#build

**Review by dazey3 — APPROVED** [review]
LGTM

**Comment by jgrassel** [comment]
Looks like it thought the spec10 commons project was a runnable test, and failed trying to consume it.  Setting the bnd file to `test.project: false`.

#build
#run-libby-bot

**Comment by jgrassel** [comment]
Forgot to update test-categories, so pushed a new commit for that.

#build
#run-libby-bot

**Comment by jgrassel** [comment]
#build

**Comment by jgrassel** [comment]
Build failed early.  Rebasing and trying again.
#build
#run-libby-bot

**Comment by jgrassel** [comment]
#build
#run-libby-bot

**Comment by jgrassel** [comment]
Looks like libby bot added `com.ibm.ws.jpa.tests.spec10.injection.common` as a fat to test in the build properties, removing it got rid of the problem.

**Pull request merged**
