### PR TITLE
CL22148 shutdown callback with running task notification

### PR DESCRIPTION
**Pull request by njr-11**
step 1 of #17703

### CODE REVIEW

**Comment by njr-11** [comment]
#run-libby-bot

**Comment by njr-11** [comment]
#build

**Review by KyleAure — APPROVED** [review]

**Comment by njr-11** [comment]
The test failed intermittently because it didn't wait for the task to start running, and having a running task is an expectation of the test.  This has been fixed, so I'm trying the build again:
#build
#run-libby-bot

**Comment by njr-11** [comment]
Build has 1 test failure, which is a preexisting issue in an unrelated test bucket

**Pull request merged**
