### PR TITLE
Add overlay for JAXB Marshaller/Unmarshaller pooling in CXF

### PR DESCRIPTION
**Pull request by neuwerk**
CXF 3.4 is missing a performance improvement that has been a part of the IBM's fork of CXF 2.6.2. It was never pulled in to CXF, but can be viewed here: https://issues.apache.org/jira/browse/CXF-4650.

### CODE REVIEW

**Comment by neuwerk** [comment]
#build

**Comment by neuwerk** [comment]
#build

**Comment by neuwerk** [comment]
#build

**Comment by neuwerk** [comment]
#build

**Comment by neuwerk** [comment]
#build

**Comment by neuwerk** [comment]
#build

**Review by jhanders34 — APPROVED** [review]

**Comment by jhanders34** [comment]
#libby

**Pull request merged**
