### PR TITLE
com.ibm.ws.wssecurity_fat.wsscxf.saml.4 update per new jaxws-2.2

### PR DESCRIPTION
**Pull request by meiaus**
Parent issue: https://github.com/OpenLiberty/open-liberty/issues/23060

### CODE REVIEW

**Comment by meiaus** [comment]
#run-libby-bot

**Comment by meiaus** [comment]
#build

**Comment by meiaus** [comment]
1. The personal build with `auto` passed:

image

image

The error in the build is out of scope from the PR:

image


2. The personal build with SOE platforms passed:

image

image

**Comment by meiaus** [comment]
@arunavemulapalli the PR is ready for review/approval.  Thanks.

**Comment by meiaus** [comment]
#run-libby-bot

**Comment by meiaus** [comment]
#build

**Comment by meiaus** [comment]
#build

**Comment by meiaus** [comment]
Personal Build result:
1. with the updated project only: passed
image

**Comment by meiaus** [comment]
#run-libby-bot

**Comment by meiaus** [comment]
#build

**Comment by meiaus** [comment]
#run-libby-bot

**Comment by meiaus** [comment]
#build

**Comment by meiaus** [comment]
Personal build result:
1. with default `build`: passed

image

2. With soe.platform.requests RHEL9_X86_REDHAT_8_64,WIN2022_ORACLEJDK11_64_EBC: passed

image

**Comment by meiaus** [comment]
@arunavemulapalli the PR is ready to review/approval (after the latest update).  Thanks.

**Review by arunavemulapalli — APPROVED** [review]

**Pull request merged**
