### PR TITLE
modify float test to include new values for Java 19

### LINKED ISSUE #22220: Java 19: Failed com.ibm.ws.logging_fat: printFloatTest
RTC 291091

```

junit.framework.AssertionFailedError: 2022-06-19-11:53:01:017 222222222 NOT FOUND
at com.ibm.ws.logging.fat.RealFlushTest.printFloatTest(RealFlushTest.java:219)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at componenttest.custom.junit.runner.FATRunner$1.evaluate(FATRunner.java:199)
at componenttest.custom.junit.runner.FATRunner$2.evaluate(FATRunner.java:349)
at componenttest.custom.junit.runner.FATRunner.run(FATRunner.java:173)
```

### PR DESCRIPTION
**Pull request by ellen-lau**
#build

### CODE REVIEW

**Comment by ellen-lau** [comment]
#build

**Comment by ellen-lau** [comment]
fixes: #22220

**Comment by ellen-lau** [comment]
Test passed in Java 19 build here: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_3ahLsDnIEe23g5vzbKf2xA&tab=com.ibm.team.build.web.ui.internal.editors.result.test.TestProvider

**Review by tonyreigns — APPROVED** [review]
LGTM

**Comment by ellen-lau** [comment]
#run-libby-bot

**Pull request merged**
