### PR TITLE
Add quotes around button values so multiple words don't get separated

### PR DESCRIPTION
**Pull request by dmorgant**
For the Input elements representing the buttons in the html for the tables on the OIDC applications set the value attribute to the translated string.  The value attribute value was not being quoted and therefore was not being added to the input element correctly.  So, added quotes to the value elements in the DOM.

### CODE REVIEW

**Comment by dmorgant** [comment]
fixes CL issue: 18247

**Comment by dmorgant** [comment]
#build

**Comment by dmorgant** [comment]
Test:
Bringing up the OIDC applications in Spanish, we can see that the 'Regenerate' button which is translated to a phrase of multiple words correctly shows ALL the words in the column where the button is located instead of just the first one.

**Comment by lavenal** [comment]
Denise, since you take care of the "delete" button value in usersTokenManagement, wondering whether you want to take care of the "delete" and "edit" button value in clientManagement.

**Comment by dmorgant** [comment]
Great news......In the client management app we use \<button> elements, instead of \<input type=button> elements.   So the problem with the space does not exist.   Here's a picture....

image

**Pull request merged**
