### PR TITLE
Add Jakarta-ee API pom deps

### PR DESCRIPTION
**Pull request by cbridgha**
The major part of these changes is to compensate for the bnd subprojects that are used for our API spec jar's.
We don't use a bnd buildpath - but directly "include" the libraries in our bundles...    For these jar's we will start setting direct maven dependency properties.

Also included perf improvement to only grab the specific jar entry for the pom.xml, and stop traversing the entire contents...

### CODE REVIEW

**Comment by cbridgha** [comment]
#build

**Comment by cbridgha** [comment]
#build

**Comment by cbridgha** [comment]
#build

**Review by hlhoots — APPROVED** [review]
Seems good to me.

**Comment by cbridgha** [comment]
#libby

**Pull request merged**
