### PR TITLE
collapse concurrency bundles now that java 7 support is unnecessary

### PR DESCRIPTION
**Pull request by njr-11**
It will be easier to refactor the concurrency projects for Jakarta EE if we collapse them, which is possible now the Java 7 support has ended. The only reason for separating them was to temporarily keep a few methods that return Java 8 CompletableFuture/CompletionStage out of the way that weren't available on Java 7, which is no longer necessary.

### CODE REVIEW

**Comment by njr-11** [comment]
An ID review is unnecessary because there are no actual changes to messages.  One message was moved to a different bundle, but with no changes.

**Comment by njr-11** [comment]
#build

**Comment by njr-11** [comment]
#build
#run-libby-bot

**Comment by njr-11** [comment]
#build

**Comment by njr-11** [comment]
#build

**Comment by andrea-pichler** [comment]
Completed the requested L2 message review

**Comment by njr-11** [comment]
#build

**Comment by njr-11** [comment]
#build

**Comment by njr-11** [comment]
#build

**Comment by njr-11** [comment]
#build

**Comment by njr-11** [comment]
#build

**Comment by njr-11** [comment]
Rebased onto integration given how long this has been held out.
#run-libby-bot

**Comment by njr-11** [comment]
#build

**Comment by njr-11** [comment]
Build has 3 test failures which are duplicates of pre-existing issues.

**Pull request merged**
