### PR TITLE
Cleanup multiple things

### PR DESCRIPTION
**Pull request by jhanders34**
- Update .classpath to include src directory for overlay file.
- Update bnd files for some errors in the file with use of backslash
- Update github actions test categories for recent FAT updates.
- Add missing javadoc zip file to feature file
- Remove transforming bundles that do not have their transformed bundle included in any feature files.
- Update FAT tests where we were setting a minimum Java level of Java 8 or lower.  The lowest Java level we test with is Java 8.

### CODE REVIEW

**Comment by jhanders34** [comment]
#build

**Comment by jhanders34** [comment]
#libby

**Comment by jhanders34** [comment]
#libby #build

**Comment by jhanders34** [comment]
#libby #build

**Comment by jhanders34** [comment]
#build

**Review by tevans78 — APPROVED** [review]

**Comment by tevans78** [comment]
#libby

**Pull request merged**
