### PR TITLE
Do not associate vendor connection pool metrics with an application for mpMerics-2.x

### PR DESCRIPTION
**Pull request by Channyboy**
- [x] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [x] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [x] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

### CODE REVIEW

**Comment by Channyboy** [comment]
#build ([view Open Liberty Personal Build](https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?pipelineId=5175a841-f184-4f6b-b656-b18047a072a3) - :white_check_mark: completed successfully!)

_Note: Target locations of links might be accessible only to IBM employees._

**Review by pgunapal — APPROVED** [review]
LGTM

**Comment by pgunapal** [comment]
Should have `release bug` issue created for this.

**Comment by Channyboy** [comment]
Part of #30383

**Pull request merged**
