### PR TITLE
Add mpTelemetry TCK

### PR DESCRIPTION
**Pull request by Yas-Franco**
For issue #19172

### CODE REVIEW

**Comment by Yas-Franco** [comment]
#build

**Comment by Yas-Franco** [comment]
#build

**Comment by Yas-Franco** [comment]
#build

**Comment by Yas-Franco** [comment]
Looks like references to Jetty were causing null pointer exceptions previously

**Comment by Yas-Franco** [comment]
#build

**Review by benjamin-confino — APPROVED** [review]

**Comment by Yas-Franco** [comment]
#libby

**Pull request merged**
