### PR TITLE
Add keystore to Java EE v8 FAT

### PR DESCRIPTION
**Pull request by tkburroughs**
Precreate the keystore for a Java EE v8 FAT to avoid CWPKI0804E that occurs when automatic creation intermittently fails.

- [x] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [x] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [x] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

### CODE REVIEW

**Comment by tkburroughs** [comment]
#build

**Comment by contbld** [comment]
Your personal pipeline request is at https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=86adbb26-f70d-4d8c-ae4f-a3515d4587fc

Target locations of links might be accessible only to IBM employees.

**Comment by contbld** [comment]
<h3>Code analysis and actions</h3>
DO NOT DELETE THIS COMMENT.

- 2 FAT files were changed, added, or removed.
 - Check that the build did not break the affected FAT suite(s).

**Comment by contbld** [comment]
https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=86adbb26-f70d-4d8c-ae4f-a3515d4587fc has errors/failures.

**Review by brideck — APPROVED** [review]

**Comment by tkburroughs** [comment]
RTC build results have not been reported here... but they were 100% passing.  Merging.

**Pull request merged**
