### PR TITLE
2646 fix duplicate wto message print

### LINKED ISSUE #2646: Messages in MessageRouter.properties are issued twice when creating a log handler that filters on '*'
In some configurations, a message may be issued twice to a log handler.  For example given this configuration in the commercial Liberty product:
`<zosLogging wtoMessage="*"/>`
The message CWWKB0001I is printed twice.  Message CWWKB0001I is present in the OSGi bundle's MessageRouter.properties file, and is also covered by the "*" in the wtoMessage attribute.

In the `com.ibm.ws.logging.osgi` project, in file `WsMessageRouterImp.java` method `route()` there is a check for log handlers that are registered for "*".  If there are any, we route the message to those log handlers, since it wants to see everything.  Then, just below that, we check for the specific message ID.  If the specific message ID is requested by a log handler, we route there.

It's possible for a log handler to specify "*" and a specific ID as well, and in this case the message is routed twice.  This can happen when a message is specified in a MessageRouter.properties file for an OSGi bundle.  The messages in the MessageRouter.properties file is explicitly added to the list of messages that the log handler wants routed to itself.  However if the user then specifies additional configuration on the log handler, that is added to what as in MessageRouter.properties.  It is easy to end up with duplicates since the user may not be aware that MessageRouter.properties exists in a given bundle.

The code should not route for a specific message ID if it has already routed for "*".

### PR DESCRIPTION
**Pull request by viane**
Fixes #2646

### CODE REVIEW

**Comment by viane** [comment]
#build

**Comment by viane** [comment]
#build

**Comment by viane** [comment]
From both builds, the BVT failures occurred on the first build didn't happen on the 2 build, and 2nd build's FAT failures didn't fail on the first build. The stack trace also indicates the failure was caused by timing reasons, so most likely the problems are "intermittent".

Fat test failure report:

|                             Test Bucke                            | Defect ID | Match Rate |
|:-----------------------------------------------------------------:|:---------:|:----------:|
|   com.ibm.ws.app.manager.wab.configure.fat.ConfigurableWABTests   |   230248  |     99%    |
|                             launchTck                             |   252495  |     98%    |
| com.ibm.ws.microprofile.metrics11.tck.launcher.MetricsTCKLauncher |   252495  |     90%    |
|        io.astefanutti.metrics.cdi.se.MeterInjectionBeanTest       |   209446  |     93%    |

**Comment by viane** [comment]
#build

**Comment by viane** [comment]
#build

**Comment by viane** [comment]
#build

**Comment by viane** [comment]
#build

**Comment by viane** [comment]
#build

**Comment by viane** [comment]
#build

**Comment by viane** [comment]
#build

**Comment by gkwan-ibm** [comment]
- please update the second line to change the copyright year from 2016 to 2017
- it is up to you to update or not that
    - the line 178, continue is not necessary
    - or lines 176 to 181, one single if should be enough instead of if and else if

**Comment by viane** [comment]
#build

**Pull request merged**
