### PR TITLE
Update copyright header date range to include 2023

### PR DESCRIPTION
**Pull request by pnicolucci**
related to pull request #23784

Update a missed copyright date range update

### CODE REVIEW

**Comment by pnicolucci** [comment]
#libby #build

**Review by isaacrivriv — APPROVED** [review]
Looks good, thanks for updating this!

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
The failure in the personal build is being addressed by https://github.com/OpenLiberty/open-liberty/pull/23864 and is not related to this PR

**Pull request merged**
