### PR TITLE
Add to bnd buildpath to address an eclipse compile issue.

### PR DESCRIPTION
**Pull request by sebratton**
Fix an eclipse red compile flag on a FAT.

### CODE REVIEW

**Review by tjwatson — APPROVED** [review]
LGTM

**Comment by sebratton** [comment]
#build

**Comment by sebratton** [comment]
#build

**Comment by sebratton** [comment]
#build

**Comment by sebratton** [comment]
#build

**Comment by sebratton** [comment]
#build

**Comment by sebratton** [comment]
#libby

**Pull request merged**
