### PR TITLE
Add FAT for Servlet 6.1 ServletResponse no-op clarification

### LINKED ISSUE #26484: Servlet 6.1: Clarify Javadoc for ServletResponse and HttpServletResponse methods that are NO-OPs once the response has been committed.
`https://github.com/jakartaee/servlet/issues/164`

### PR DESCRIPTION
**Pull request by pnicolucci**
fixes #26484

### CODE REVIEW

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#libby #build

**Comment by fritze2** [comment]
Hi Paul, both of the builds you requested failed to clone from github.ibm.com. I've seen this in other PBs as well. Hoping that by re-requesting your builds it will progress further.
#build

**Review by volosied — APPROVED** [review]
Tests look good to me

**Pull request merged**
