### PR TITLE
testTLD assert msg fix

### LINKED ISSUE #20307: fix file update timing issue in FAT testTLD for JSP
**Describe the bug**  
Jsp.2.3 fat gets this error intermittently:
testTLD:junit.framework.AssertionFailedError: 2021-10-08-06:35:44:939 Log should not contain SRVE0253I: Destroy successful.

**Steps to Reproduce**  
This error only happens on Windows, running the com.ibm.ws.jsp.2.3 fat in FULL mode.

**Expected behavior**  
FAT should run clean.

### PR DESCRIPTION
**Pull request by epj**
fixes #20307

### CODE REVIEW

**Comment by epj** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.jsp_fat,com.ibm.ws.jsp.2.3_fat

**Comment by epj** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.jsp_fat,com.ibm.ws.jsp.2.3_fat

**Comment by epj** [comment]
Yesterday's build has been stuck at 98% done for a while, but it did finish the tests and they are clean.

**Review by volosied — APPROVED** [review]
Good idea to reuse "ShrinkHelper.defaultDropinApp(server, TestEDR_APP_NAME + ".war");" 

Approved

**Comment by epj** [comment]
#libbybot

**Comment by epj** [comment]
#libby

**Pull request merged**
