### PR TITLE
Create new OL zips

### PR DESCRIPTION
**Pull request by tevans78**
This PR creates OL profile zips for
jakartaee10
webProfile10
microProfile6

This PR depends on https://github.com/OpenLiberty/open-liberty/pull/22216

#build

### CODE REVIEW

**Comment by tevans78** [comment]
#build

**Review by cbridgha — APPROVED** [review]
Looks good

**Comment by tevans78** [comment]
Rebased to remove commit that was already merged under https://github.com/OpenLiberty/open-liberty/pull/22216

**Comment by tevans78** [comment]
#libby

**Pull request merged**
