### PR TITLE
Add eeCompatible-6.0 and tolerate 7.0,8.0 in el-3.0 public feature

### LINKED ISSUE #13306: The public el-3.0 feature needs to specify a eeCompatible feature
The public `el-3.0` feature needs to specify a eeCompatible feature , if it does not then it is possible to load the following features together and it should not be possible:

```
<feature>el-3.0</feature>
<feature>el-4.0</feature>
```

and

```
<feature>jsp-3.0</feature>
<feature> el-3.0</feature>
```

The `jsp-3.0` feature and the `el-4.0` feature both specify the following eeCompatible feature:

`com.ibm.websphere.appserver.eeCompatible-9.0`

The `el-3.0` feature should specify the following eeCompatible feature:

`com.ibm.websphere.appserver.eeCompatible-7.0; ibm.tolerates:="6.0,8.0"`

We need to tolerate the `8.0` version of `eeCompatible` because EL 3.0 was created for Java EE7 and there was no update for Java EE8 and features such as `jsf-2.3` are `eeCompatible-8.0` and need to enable the `el-3.0` feature by pulling in the `jsp-2.3` feature which pulls in  `el-3.0`.

We need the `6.0` version of `eeCompatible` because currently you can load the `el-3.0` feature along side EE6 features such as `beanValidation-1.0` which is `eeCompatible-6.0`.

With this change we'll now see the following when both the `el-3.0` and `el-4.0` features are enabled:

>CWWKF0044E: The features el-4.0 and el-3.0 cannot be loaded at the same time.  The feature el-4.0 of Jakarta EE 9 is incompatible with the feature el-3.0 of Java EE 7.  The configured features el-4.0 and el-3.0 include an incompatible combination of features.  Your configuration is not supported.  Update the configuration to use features that support either the Jakarta EE or Java EE programming models, but not both.

### PR DESCRIPTION
**Pull request by pnicolucci**
fixes #13306

### CODE REVIEW

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#run-libby-bot

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#run-libby-bot

**Review by tevans78 — APPROVED** [review]

**Pull request merged**
