### PR TITLE
Merge MP OpenTracing message files into a common bundle

### LINKED ISSUE #17430: Moved MP Open Tracing NLS messages into common bundle
To avoid duplicate messages showing up in documentation

### PR DESCRIPTION
**Pull request by fmhwong**
Fixes #17430

### CODE REVIEW

**Comment by fmhwong** [comment]
#build

**Comment by fmhwong** [comment]
#build

**Comment by dmuelle** [comment]
Hi @fmhwong - looks like there aren't any new English messages here that need review. I'll add the` ID review not needed` label. If that's not correct, just let me know. Thanks!

**Review by tonyreigns — APPROVED** [review]
LGTM

**Comment by fmhwong** [comment]
#libby

**Pull request merged**
