### PR TITLE
Add step for creating code checklist

### PR DESCRIPTION
**Pull request by wraschke**
- [x] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [x] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [x] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

This PR's changes are for introducing a new step that will create the required code checklists on Open Liberty PRs.

### CODE REVIEW

**Comment by wraschke** [comment]
!libby

**Comment by wraschke** [comment]
!libby@dev

**Comment by wraschke** [comment]
!libby@dev

**Comment by wraschke** [comment]
!libby@dev

**Comment by wraschke** [comment]
!libby@dev

**Review by fritze2 — DISMISSED** [review]

**Comment by wraschke** [comment]
!build

**Comment by wraschke** [comment]
!build@dev

**Comment by wraschke** [comment]
!build@dev

**Comment by wraschke** [comment]
!build

**Review by fritze2 — DISMISSED** [review]

**Comment by wraschke** [comment]
!pbbeta

**Comment by wraschke** [comment]
!pbbeta

**Comment by wraschke** [comment]
The RTC pipeline's "Code Checklist Creation" Jenkins job starts without any issues.

The beta pipeline, however, has a problem when requesting the Jenkins job. Since that is a more complicated issue to pick through, we decided that these two pipeline types with new step was okay for now. I'll introduce the new step in a follow-up PR.

**Comment by wraschke** [comment]
!libby

**Review by fritze2 — DISMISSED** [review]

**Comment by wraschke** [comment]
!build !libby

**Comment by wraschke** [comment]
!libby

**Comment by wraschke** [comment]
!pbbeta !pb

**Review by fritze2 — APPROVED** [review]

**Comment by wraschke** [comment]
The TCK FAT failures are unrelated to this PR's change.

**Pull request merged**
