### PR TITLE
Ship Liberty public key to build image

### PR DESCRIPTION
**Pull request by jjiwooLim**
Ship liberty public key for featureUtility signature verification.

### CODE REVIEW

**Comment by jjiwooLim** [comment]
#build

**Review by cbridgha — DISMISSED** [review]
looks good

**Comment by jjiwooLim** [comment]
Forgot to add the public key file.
#build

**Comment by jjiwooLim** [comment]
#build

**Comment by jjiwooLim** [comment]
Added keyID property in [CL](https://github.ibm.com/websphere/WS-CD-Open/pull/29793) as well.
#build

**Review by bensonlatibm — APPROVED** [review]
LGTM!

**Comment by jjiwooLim** [comment]
#libby-bot

**Pull request merged**
