### PR TITLE
upgrade dojo for Admin Center

### PR DESCRIPTION
**Pull request by lavenal**

### CODE REVIEW

**Comment by lavenal** [comment]
#build

**Comment by lavenal** [comment]
All UI FAT tests passed in the PB.

**Review by k8vance88 — APPROVED** [review]

**Comment by lavenal** [comment]
#build

**Comment by lavenal** [comment]
#build

**Comment by lavenal** [comment]
All UI tests passed in the PB.

**Comment by lavenal** [comment]
fixed #20232

**Pull request merged**
