### PR TITLE
upgrade dojo from 1.12.9 to 1.12.11 version

### PR DESCRIPTION
**Pull request by aknguyen7**

### CODE REVIEW

**Comment by aknguyen7** [comment]
#build

**Comment by aknguyen7** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.ui_rest_fat,com.ibm.ws.ui.collective_fat,com.ibm.ws.ui_fat.gui

**Review by k8vance88 — APPROVED** [review]

**Comment by aknguyen7** [comment]
#build

**Comment by aknguyen7** [comment]
build that use WS-CD-Open upgradeDojo1.12.11 branch https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_NqH4oLHyEe2syNb0fJgimw

**Review by jhanders34 — APPROVED** [review]

**Comment by aknguyen7** [comment]
#libby

**Pull request merged**
