### PR TITLE
Use MicroProfile Opentracing 2.0 GM version

### LINKED ISSUE #15397: Switch MicroProfile OpenTracing spec to 2.0 GM version
Switch MicroProfile OpenTracing spec to 2.0 GM version

### PR DESCRIPTION
**Pull request by fmhwong**
Fixes #15397

### CODE REVIEW

**Comment by fmhwong** [comment]
#build

**Comment by fmhwong** [comment]
#build

**Comment by fmhwong** [comment]
#build

**Comment by fmhwong** [comment]
#build

**Review by Channyboy — APPROVED** [review]
lgtm

**Comment by fmhwong** [comment]
#libby

**Pull request merged**
