### PR TITLE
Synchronize Testcontainer Logic

### PR DESCRIPTION
**Pull request by KyleAure**
Synching up logic and testing for testcontainers between WL and OL.
This PR accomplishes the following:

- Introduce OnlyIfSysProp annotation
- Enable DatabaseRotation to modify authData in server config
- Remove extra PostgreSQL driver in favor of newer version
- Update testcontainers to 1.17.4
- When SQLServer is used for DB rotation make sure the database table used is "TEST"
- Fix io.openliberty.org.testcontainers/build.gradle:assembleTestContainerData task so it only runs when a test suite that uses test containers is run. 
- Ensure tests enlisted in DB Rotation have some sort of auth data set up, otherwise, we cannot use heuristics to determine where the auth data should be modified.
- Remote `fat.modify="true"` from test suites that do not use DB rotation. It just makes the server configuration more confusing.

### CODE REVIEW

**Comment by KyleAure** [comment]
#build

**Comment by KyleAure** [comment]
#build

**Comment by KyleAure** [comment]
Abandoned previous build and trying again: #build

**Comment by KyleAure** [comment]
#build

**Comment by KyleAure** [comment]
#build

**Comment by KyleAure** [comment]
#build

**Comment by KyleAure** [comment]
#build

**Review by tabishop — APPROVED** [review]

**Comment by KyleAure** [comment]
#build

**Comment by KyleAure** [comment]
#build

**Comment by KyleAure** [comment]
Personal build results: 

| Database | Results |
| --- | --- |
| Derby | 1 failure - known defect | 
| DB2  | 1 failure - network issue | 
| Oracle | 1 failure - known defect |
| PostgreSQL | 1 failure - known defect |
| SQLServer | 0 failures |

**Comment by KyleAure** [comment]
#libbybot

**Pull request merged**
