### PR TITLE
Issue 19027: Add NLS messages for OIDC UserInfo JWT response checks

### LINKED ISSUE #19027: More descriptive messages needed when userinfo content-type does not match the content type returned
When the response from userinfo comes with a contentType of "application/json", but the content is JWS, I get:
FFDC1015I: An FFDC Incident has been created: “java.io.IOException: Unexpected character ‘e’ on line 1, column 1
CWWKS1749E: The User Info data [eyJraWQiOiJsWVF4Q2dMNi1uN3Vzbl94bTVqdFlfRHNONFYyRDByMGxxcWhjRTZxYVZFIiwidHlwIjoiSldUIiwiYWxnIjoiUlMyNTYifQ.eyJ0b2tlbl90eXBlIjoiQmVhcmVyIiwiYXVkIjoiY2xpZW50MDEiLCJzdWIiOiJ0ZXN0dXNlciIsImRlZmF1bHRFeHRyYUNsYWltIjoic29tZVZhbHVlIiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4OTEwL1Rva2VuRW5kcG9pbnRTZXJ2bGV0IiwiZXhwIjoxNjM0MzMyODEwLCJpYXQiOjE2MzQzMjU2MTB9.Dsuly2KiBR3pUtutnHVw5M3wdFRdy4hKkyYhjw22LdVgYAJ6B_T3BHiHFrvUrKJyYToibCCQGecsFKSNZqRx5SYmcafd5im2q-2MGKVwCkGFsNTo5Zt9nR2CiPjw4ppQ9zJSPhic8rmzG4f8Ph-IdIVms-D8axn_6M8vAxVU7DSqmRKhf83PQGjMnT_5BUhSi56mDHU2m1aBiW2kzDTilfrigKgFAxs8qjbvuctyGw7TkougozhAu-tNXkiZkFVo8J1nJ2QY4ev7P2ii7yTmSvraCxvGNjobaAF8I4-ZwZ3tLxTRhfLig5wBC18vJ0ik3tNjrwHA0n229yJWpo3DLpFYNwuEnP5an1nuSZZr9QLEmwW6wDOLmt-i_NtivNnPMZbcynrkKi6jy7xcCNLIbvxJApAxBe04nGkMeewfiTJVf0NlXgOyeaj5EGfZRpLgtdCX33rYMNW8Gm4AzaGRGspItQAB7RZijHupCF5WtLel45Oit9fZKcKUWQYAumfptMsUiGEJADOu201UZLPmAnfGpKkGkupL51RVRRX42NVdv7fgjfpiXUSEVG0axw-_fCX_tAOk3vEw7dd6OWE-YX5y5qkuI2jVhRhJcPygBxIyA33yBKOJM3tkUT4VJEZFrdXOHpFgLcAC8cU7eUbc8IWBO3tUt-eJLKVMPrVf798] is invalid because the sub claim does not match the sub claim of the ID Token [testuser].

Should we get a more informational message indicating that the response content is of the wrong type.

Whe the response contains a JWE (instead of the JWS), I'm not seeing the FFDC, but get the generic sub claim mis-match message

### PR DESCRIPTION
**Pull request by ayoho**
Resolves #19027

### CODE REVIEW

**Comment by ayoho** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.security.oidc.client_fat.1,com.ibm.ws.security.oidc.client_fat.2,com.ibm.ws.security.oidc.client_fat.config,com.ibm.ws.security.oidc.client_fat.e2e,com.ibm.ws.security.oidc.client_fat.jaxrs,com.ibm.ws.security.oidc.client_fat.saml,com.ibm.ws.security.oidc.client_fat.spnego,com.ibm.ws.security.oidc.server_fat,com.ibm.ws.security.oidc.server_fat.app-passwords,com.ibm.ws.security.oidc.server_fat.app-passwords.DerbyDB.jwt,com.ibm.ws.security.oidc.server_fat.app-passwords.DerbyDB.opaque,com.ibm.ws.security.oidc.server_fat.app-passwords.LocalStore.jwt,com.ibm.ws.security.oidc.server_fat.app-passwords.LocalStore.opaque,com.ibm.ws.security.oidc.server_fat.app-tokens,com.ibm.ws.security.oidc.server_fat.app-tokens.DerbyDB.jwt,com.ibm.ws.security.oidc.server_fat.app-tokens.DerbyDB.opaque,com.ibm.ws.security.oidc.server_fat.app-tokens.LocalStore.jwt,com.ibm.ws.security.oidc.server_fat.app-tokens.LocalStore.opaque,com.ibm.ws.security.oidc.server_fat.clientregistration,com.ibm.ws.security.oidc.server_fat.config,com.ibm.ws.security.oidc.server_fat.config.oauth,com.ibm.ws.security.oidc.server_fat.config.oidc,com.ibm.ws.security.oidc.server_fat.endpoint.authorize,com.ibm.ws.security.oidc.server_fat.endpoint.coveragemap,com.ibm.ws.security.oidc.server_fat.endpoint.discovery,com.ibm.ws.security.oidc.server_fat.endpoint.end_session,com.ibm.ws.security.oidc.server_fat.endpoint.introspect,com.ibm.ws.security.oidc.server_fat.endpoint.revoke,com.ibm.ws.security.oidc.server_fat.endpoint.token,com.ibm.ws.security.oidc.server_fat.endpoint.userinfo,com.ibm.ws.security.oidc.server_fat.feature,com.ibm.ws.security.oidc.server_fat.granttype.jwt,com.ibm.ws.security.oidc.server_fat.gui.tokenMgmt,com.ibm.ws.security.oidc.server_fat.jaxrs,com.ibm.ws.security.oidc.server_fat.jaxrs.config,com.ibm.ws.security.oidc.server_fat.oauth,com.ibm.ws.security.oidc.server_fat.oidc,com.ibm.ws.security.oidc.server_fat.saml,com.ibm.ws.security.social_fat,com.ibm.ws.security.social_fat.LibertyOP,com.ibm.ws.security.social_fat.OpenShift,com.ibm.ws.security.social_fat.delegated,com.ibm.ws.security.social_fat.multiProvider

**Review by helyarp — COMMENTED** [review]
Looks good!

**Comment by skasund** [comment]
L2 message review completed

**Comment by ayoho** [comment]
#libby

**Comment by ayoho** [comment]
These changes were included in https://github.com/OpenLiberty/open-liberty/pull/19143, which was merged a while ago.

**Pull request closed without merging**
