### PR TITLE
Enable parallel activation of jaxrs-2.1 and cdi-2.0 features

### PR DESCRIPTION
**Pull request by anjumfatima90**

### CODE REVIEW

**Comment by anjumfatima90** [comment]
#build

**Comment by wraschke** [comment]
#build

**Comment by wraschke** [comment]
#build

**Comment by wraschke** [comment]
Testing.

**Comment by wraschke** [comment]
#build

**Comment by wraschke** [comment]
#run-libby-bot

**Comment by anjumfatima90** [comment]
#build

**Comment by tjwatson** [comment]
#build

**Pull request merged**
