### PR TITLE
Myfaces 4550

### LINKED ISSUE #24131: MYFACES-4550
https://issues.apache.org/jira/browse/MYFACES-4550

Also cleanup commit: https://github.com/apache/myfaces/commit/c1a48630b6a85ae0a2099d0eeac43b3503b0b839

### PR DESCRIPTION
**Pull request by pnicolucci**
fixes #24131

### CODE REVIEW

**Comment by pnicolucci** [comment]
#libby #build #spawn.fullfat.buckets=io.openliberty.org.apache.myfaces.4.0_fat,com.ibm.ws.jsf.2.2_fat,com.ibm.ws.jsf.2.3_fat

**Comment by pnicolucci** [comment]
#libby #build #spawn.fullfat.buckets=io.openliberty.org.apache.myfaces.4.0_fat,com.ibm.ws.jsf.2.2_fat,com.ibm.ws.jsf.2.3_fat

**Comment by pnicolucci** [comment]
#libby #build #spawn.fullfat.buckets=io.openliberty.org.apache.myfaces.4.0_fat,com.ibm.ws.jsf.2.2_fat,com.ibm.ws.jsf.2.3_fat

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
#libby #build #spawn.fullfat.buckets=com.ibm.ws.jsf.2.2_fat,com.ibm.ws.jsf.2.3_fat,io.openliberty.org.apache.myfaces.4.0_fat

**Comment by pnicolucci** [comment]
#libby #build #spawn.fullfat.buckets=com.ibm.ws.jsf.2.2_fat,com.ibm.ws.jsf.2.3_fat,io.openliberty.org.apache.myfaces.4.0_fat

**Review by volosied — APPROVED** [review]

**Comment by pnicolucci** [comment]
#libby #build #spawn.fullfat.buckets=com.ibm.ws.jsf.2.2_fat,com.ibm.ws.jsf.2.3_fat,io.openliberty.org.apache.myfaces.4.0_fat

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
#libby #build #spawn.fullfat.buckets=com.ibm.ws.jsf.2.2_fat,com.ibm.ws.jsf.2.3_fat,io.openliberty.org.apache.myfaces.4.0_fat

**Pull request merged**
