### PR TITLE
Retry requests if slow requests are not found in RequestTiming FAT

### LINKED ISSUE #13564: Test Failure: com.ibm.ws.request.timing.fat.TimingRequestTiming.testTimingLocalEnableSlowRequest
RTC 276422

```
testTimingLocalEnableSlowRequest:junit.framework.AssertionFailedError: 2020-07-23-18:40:29:814 Expected > 0 slow request warning but found : 0
at com.ibm.ws.request.timing.fat.TimingRequestTiming.testTimingLocalEnableSlowRequest(TimingRequestTiming.java:131)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at componenttest.custom.junit.runner.FATRunner$1.evaluate(FATRunner.java:197)
at componenttest.custom.junit.runner.FATRunner$2.evaluate(FATRunner.java:318)
at componenttest.custom.junit.runner.FATRunner.run(FATRunner.java:171)
at componenttest.rules.repeater.RepeatTests$CompositeRepeatTestActionStatement.evaluate(RepeatTests.java:115)


```

### LINKED ISSUE #13620: Test Failure: com.ibm.ws.request.timing.fat.SlowRequestTiming.testSlowReqDynamicPatternUpdate_EE8_FEATURES
RTC 277077

```
testSlowReqDynamicPatternUpdate_EE8_FEATURES:junit.framework.AssertionFailedError: 2020-08-14-19:21:05:519 No Slow request timing records found! :
at com.ibm.ws.request.timing.fat.SlowRequestTiming.testSlowReqDynamicPatternUpdate(SlowRequestTiming.java:536)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at componenttest.custom.junit.runner.FATRunner$1.evaluate(FATRunner.java:197)
at componenttest.custom.junit.runner.FATRunner$2.evaluate(FATRunner.java:318)
at componenttest.custom.junit.runner.FATRunner.run(FATRunner.java:171)
at componenttest.rules.repeater.RepeatTests$CompositeRepeatTestActionStatement.evaluate(RepeatTests.java:115)
```

### PR DESCRIPTION
**Pull request by Yushan-Lin**
Fixes #13564 and Fixes #13620
Exceptions are not printed sometimes in TestJDBC which causes FAT tests to fail. It looks for slow warning messages `TRAS0112W` which is not found sometimes as the exception is not printed.

### CODE REVIEW

**Comment by Yushan-Lin** [comment]
https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_FL-S4OlWEeql06cgdrhuYw

**Comment by Yushan-Lin** [comment]
https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_ojw5YOsjEeq6BMGcHg9CTA

**Comment by Yushan-Lin** [comment]
https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewDefinition&id=_JWdEUD7dEemKFI0xRbWJ_w

**Comment by Yushan-Lin** [comment]
https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_pVePge1aEeq6BMGcHg9CTA

**Review by pgunapal — APPROVED** [review]
LGTM

**Comment by Yushan-Lin** [comment]
#run-libby-bot

**Pull request merged**
