### PR TITLE
Initial drop of a second Logging FAT due to 3h time limit being reached

### LINKED ISSUE #24970: Speed up com.ibm.ws.logging_fat
RTC 295561

The com.ibm.ws.logging_fat runs more than 3 hours in SOE builds and it failed with a timeout.

We either need to speed this up or split this into 2 buckets.

### PR DESCRIPTION
**Pull request by tonyreigns**
Resolves: #24970 

Created a new Logging FAT and moved over some tests over. All newly created logging tests will be added to this bucket.

### CODE REVIEW

**Comment by tonyreigns** [comment]
#build

**Comment by tonyreigns** [comment]
#build

**Review by fmhwong — APPROVED** [review]
LGTM

**Comment by tonyreigns** [comment]
#libby

**Pull request merged**
