### PR TITLE
Faces 4.1 Update Schemas

### LINKED ISSUE #29070: Faces 4.1: Refresh with official schemas for Faces
https://jakarta.ee/xml/ns/jakartaee/#11

1) [web-facesconfig_4_1.xsd](https://jakarta.ee/xml/ns/jakartaee/web-facesconfig_4_1.xsd)
2) [web-facelettaglibrary_4_1.xsd](https://jakarta.ee/xml/ns/jakartaee/web-facelettaglibrary_4_1.xsd)
3) [web-partialresponse_4_1.xsd](https://jakarta.ee/xml/ns/jakartaee/web-partialresponse_4_1.xsd)

I don't think anything is done with 2/3 outside of the implementation but certainly, we'll need updates for 1.

### PR DESCRIPTION
**Pull request by pmd1nh**
Fixes https://github.com/OpenLiberty/open-liberty/issues/29070

### CODE REVIEW

**Review by tbitonti — DISMISSED** [review]

**Comment by pmd1nh** [comment]
#build

**Comment by pmd1nh** [comment]
PB unittests fail

```
com.ibm.ws.javaee.ddmodel unittests 896 8 0
	
    com.ibm.ws.javaee.ddmodel.DDParserSpecList 2 2 0 0 s 1
        testSummary 1 1 0 0 s 1
        testDetail 1 1 0 0 s 2
    com.ibm.ws.javaee.ddmodel.jsf.JSFAppHeaderTest 9 5 0 0 s 37
        testJSF_NoNamespace 1 1 0 0 s 1
        testJSF_NoSchemaLocation 1 1 0 0 s 3
        testJSF_NoXSI 1 1 0 0 s 4
        testJSF_NoVersion 1 1 0 0 s 5
        testJSF_NamespaceOnly 1 1 0 0 s 6
    com.ibm.ws.javaee.ddmodel.jsf.JSFAppTest 19 1 0 0 s 38
        testGetVersion 1 1 0 0 s 1
```

all have the same root cause

```
java.lang.IllegalArgumentException: Unknown schema version [ 41 ]
	at com.ibm.ws.javaee.dd.PlatformVersion.getDottedVersionText(PlatformVersion.java:90)
```

Need to update com.ibm.ws.javaee.dd.PlatformVersion with version 41

**Comment by pmd1nh** [comment]
#build

**Comment by pmd1nh** [comment]
```
com.ibm.ws.javaee.ddmodel unittests 896 2 0
    com.ibm.ws.javaee.ddmodel.jsf.JSFAppHeaderTest 9 2 0 0 s 37

(1)
testJSF_NoVersion
org.junit.ComparisonFailure: expected:<4.[0]> but was:<4.[1]>
	at org.junit.Assert.assertEquals(Assert.java:125)
	at org.junit.Assert.assertEquals(Assert.java:147)
	at com.ibm.ws.javaee.ddmodel.jsf.JSFAppHeaderTest.testJSF_NamespaceOnly(JSFAppHeaderTest.java:211)

(2)
testJSF_NamespaceOnly
org.junit.ComparisonFailure: expected:<4.[0]> but was:<4.[1]>
	at org.junit.Assert.assertEquals(Assert.java:125)
	at org.junit.Assert.assertEquals(Assert.java:147)
	at com.ibm.ws.javaee.ddmodel.jsf.JSFAppHeaderTest.testJSF_NamespaceOnly(JSFAppHeaderTest.java:211)
```

**Comment by pmd1nh** [comment]
Update com.ibm.ws.javaee.ddmodel/test/com/ibm/ws/javaee/ddmodel/jsf/JSFAppHeaderTest.java
to adjustVersion() for 4.1 accordingly.

#build

**Comment by pmd1nh** [comment]
All ddmodel tests passed

```
com.ibm.ws.javaee.ddmodel unittests 896 0 0
com.ibm.ws.javaee.ddmodel_bvt bvt tests 4 0 0
com.ibm.ws.javaee.ddmodel_fat FAT tests 180 0 0
com.ibm.ws.javaee.ddmodel.ws unittests 42 0 0
com.ibm.ws.javaee.ddmodel.wsbnd unittests 0 0 0
com.ibm.ws.javaee.metadata.context_test unittests 2 0 0
com.ibm.ws.javaee.platform_fat FAT tests 1 0 0
com.ibm.ws.javaee.platform.feature_fat FAT tests 2 0 0
```
	
One failed test 

wlp.lib.extract_fat FAT tests 15 1 0
 wlp.lib.extract.PackageRunnableTest 4 1 0 3 m 10 s 2
  testRunnableDeleteServerMinusLogsFolder 1 1 0 59 s 3

**Review by tbitonti — APPROVED** [review]

**Pull request merged**
