### PR TITLE
Add Non-TCK related FATS for MP Metrics 5.1

### PR DESCRIPTION
**Pull request by Channyboy**
#build

- Remove beta flag from existing FATS
- Add io.openliberty.microprofile.metrics.internal.5.1_fat_tck with new FATS for optional MP Config for MP Metrics 5.1
- Add feature replacement for mpMetrics-5.1 for io.openliberty.microprofile.metrics.internal.5.x.monitor_fat

### CODE REVIEW

**Comment by Channyboy** [comment]
#build

**Comment by Channyboy** [comment]
#build

**Comment by Channyboy** [comment]
#build

**Comment by Channyboy** [comment]
#libby

**Comment by Channyboy** [comment]
#build

**Comment by Channyboy** [comment]
#libby

**Review by pgunapal — APPROVED** [review]
LGTM

**Pull request merged**
