### PR TITLE
Upload retranslated files

### LINKED ISSUE #10867: German translation for 'Logout' incorrect for OIDC applications
The UI message files for the OIDC applications, 
.../oidc/endpoint/OP/personalTokenManagement
.../oidc/endpoint/OP/usersTokenManagement
.../oidc/endpoint/OP/clientManagement
incorrectly translated 'Logout' to be 'Login' in the German files.

To view, login to the applications and view the 'Logout' button at the top right of panel.  When your browser is set to German, you will see 'Anmeldon' instead 'Abmeldon'.

### PR DESCRIPTION
**Pull request by dmorgant**
Update the German (de) message files for the OIDC applications to have the correct translation for 'Logout'.

fixes #10867

### CODE REVIEW

**Comment by dmorgant** [comment]
#build

**Comment by dmorgant** [comment]
Testing:
Set the browser to the German locale (de) and logged into the 3 OIDC applications.  The 'Logout' button at the top of the pane should show 'Abmeldon' instead of 'Anmeldon'.

**Comment by skasund** [comment]
L2 message review not required

**Comment by dmorgant** [comment]
#run-libby-bot

**Pull request merged**
