### PR TITLE
Generate SHA256 of TCK Jar

### PR DESCRIPTION
**Pull request by tevans78**
Find out the exact tck jar that was run
Generate a SHA256 hash
Publish in the result page
Use the exact version string from maven rather than passing it in

#build

For #22749

### CODE REVIEW

**Comment by tevans78** [comment]
#build

**Comment by tevans78** [comment]
#build

**Review by benjamin-confino — APPROVED** [review]

**Comment by tevans78** [comment]
#libby

**Comment by tevans78** [comment]
The MP JWT failures in the PB are a known defect (292993: Test Failure: org.eclipse.microprofile.jwt.tck.container.jaxrs.ClaimValueInjectionTest.verifyInjectedIssuedAtStandard)

**Pull request merged**
