### PR TITLE
mpOpentracing-1.1 Initial Code

### PR DESCRIPTION
**Pull request by fmhwong**
This is a retry from PR #4427 which caused build breaks.

- Upgraded io.opentracing APIs from 0.30 to 0.31
- Upgraded org.eclipse.microprofile.opentracing API from 1.0 to 1.1
- Removed ActiveSpan

Fixes: #4286

### CODE REVIEW

**Comment by fmhwong** [comment]
Per #442, ID review is not required as we copied the same message files from mpOpentracing-1.0.

**Comment by fmhwong** [comment]
#build

**Comment by fmhwong** [comment]
The above build failed with `io.opentracing.noop` not found in `allowedOSSPackages.txt` in WS-CD-Open master branch, but the file in integration has been updated. 

#build again as the file is in master now.
`

**Comment by tonyreigns** [comment]
Failed tests are unrelated and already have existing work items.

**Pull request merged**
