### PR TITLE
new lite test with cbh

### PR DESCRIPTION
**Pull request by meiaus**
https://github.com/OpenLiberty/open-liberty/issues/24471

The test exists already on Full bucket, and now added to Lite for capturing issue earlier when the pre-loaded CBH jar needs to recompile due to runtime changes.

### CODE REVIEW

**Comment by meiaus** [comment]
#run-libby-bot

**Comment by meiaus** [comment]
#build

**Comment by meiaus** [comment]
#build

**Comment by meiaus** [comment]
PB result:
1. With build all: 


image

The error in the build was from other FAT which is out of scope of the PR:

image

**Review by arunavemulapalli — DISMISSED** [review]
we maybe able to use just use one reapeatwithee7 class to cover both cbh versions. We can do this in another update

**Comment by meiaus** [comment]
#run-libby-bot

**Comment by meiaus** [comment]
#build

**Comment by meiaus** [comment]
#run-libby-bot

**Comment by meiaus** [comment]
#run-libby-bot

**Comment by meiaus** [comment]
#build

**Review by arunavemulapalli — APPROVED** [review]

**Comment by meiaus** [comment]
PB result with build all: passed

image

The error from other FAT is out of scope for the PR:

image

**Pull request merged**
