### PR TITLE
Add debug information for MpHealth Semeru JDK CDI TCK failure

### PR DESCRIPTION
**Pull request by pgunapal**
- Enables CDI debug trace to gather more information on MpHealth 3.1/4.0 TCK failing on Semeru JDK 17.

### CODE REVIEW

**Comment by pgunapal** [comment]
#build

**Comment by pgunapal** [comment]
#build

**Comment by pgunapal** [comment]
#build

**Comment by pgunapal** [comment]
#build

**Comment by pgunapal** [comment]
#build

**Comment by pgunapal** [comment]
#build

**Review by Channyboy — APPROVED** [review]

**Comment by pgunapal** [comment]
#libby

**Pull request merged**
