### PR TITLE
Validate visitor cts fix

### LINKED ISSUE #14111: JSP ValidateVisitor.ELCheckType triggers NoSuchMethodError
A handful of tests in the JSP TCK triggers the following error:
java.lang.NoSuchMethodError: org.apache.el.lang.ELSupport.coerceToNumber(Ljava/lang/Object;Ljava/lang/Class;)Ljava/lang/Number;
	at com.ibm.ws.jsp.translator.visitor.validator.ValidateVisitor.ELCheckType(ValidateVisitor.java:1777)
	at com.ibm.ws.jsp.translator.visitor.validator.ValidateVisitor.validateCustomTagAttribute(ValidateVisitor.java:1720)
	at com.ibm.ws.jsp.translator.visitor.validator.ValidateVisitor.validateCustomTagAttributeValues(ValidateVisitor.java:1401)
	at com.ibm.ws.jsp.translator.visitor.validator.ValidateVisitor.visitCustomTagStart(ValidateVisitor.java:284)
	at com.ibm.ws.jsp.translator.visitor.JspVisitor.processJspElement(JspVisitor.java:370)
	at com.ibm.ws.jsp.translator.visitor.JspVisitor.processChildren(JspVisitor.java:423)
	at com.ibm.ws.jsp.translator.visitor.JspVisitor.processJspElement(JspVisitor.java:238)
	at com.ibm.ws.jsp.translator.visitor.JspVisitor.visit(JspVisitor.java:220)
	at com.ibm.ws.jsp.translator.JspTranslator.processVisitors(JspTranslator.java:130)
	at com.ibm.ws.jsp.translator.utils.JspTranslatorUtil.translateJsp(JspTranslatorUtil.java:266)
	at com.ibm.ws.jsp.translator.utils.JspTranslatorUtil.translateJspAndCompile(JspTranslatorUtil.java:113)
	at com.ibm.ws.jsp.webcontainerext.AbstractJSPExtensionServletWrapper.translateJsp(AbstractJSPExtensionServletWrapper.java:540)
	at com.ibm.ws.jsp.webcontainerext.AbstractJSPExtensionServletWrapper._checkForTranslation(AbstractJSPExtensionServletWrapper.java:457)
	at com.ibm.ws.jsp.webcontainerext.AbstractJSPExtensionServletWrapper.checkForTranslation(AbstractJSPExtensionServletWrapper.java:247)
	at com.ibm.ws.jsp.webcontainerext.AbstractJSPExtensionProcessor.findWrapper(AbstractJSPExtensionProcessor.java:508)
	at com.ibm.ws.jsp.webcontainerext.AbstractJSPExtensionProcessor.getServletWrapper(AbstractJSPExtensionProcessor.java:351)
	...

### PR DESCRIPTION
**Pull request by pnicolucci**
fixes #14111

### CODE REVIEW

**Comment by pnicolucci** [comment]
#build

**Comment by brideck** [comment]
I have verified that this fix works for the affected TCK tests.

**Comment by pnicolucci** [comment]
#run-libby-bot

**Review by volosied — APPROVED** [review]
Method was added back in. Build passes, and Brian's tests pass. Change looks good.

**Pull request merged**
