### PR TITLE
Add test for aggressive log takeover

### LINKED ISSUE #13743: Add new tests for aggressive revovery log takeover
Introduce new tests to mimic the process of an aggressive takeover of recovery logs by the home server, while a peer is attempting to recover those logs.

### PR DESCRIPTION
**Pull request by neilgsyoung**
fixes #13743

### CODE REVIEW

**Comment by neilgsyoung** [comment]
#build

**Comment by neilgsyoung** [comment]
#build

**Comment by neilgsyoung** [comment]
#build

**Comment by neilgsyoung** [comment]
#build

**Comment by neilgsyoung** [comment]
#build

**Comment by neilgsyoung** [comment]
#build

**Comment by neilgsyoung** [comment]
#run-libby-bot

**Comment by neilgsyoung** [comment]
#run-libby-bot

**Comment by neilgsyoung** [comment]
#build

**Comment by neilgsyoung** [comment]
#build

**Review by jonhawkes — APPROVED** [review]

**Pull request merged**
