### PR TITLE
Fix incorrect post fat kill usage

### PR DESCRIPTION
**Pull request by dave-waddling**
OpenLiberty Pull Requester,

ATTENTION, READ THIS: Updated 4/11/2018 - Read and understand this completely,
then delete this entire template. If a reviewer or merger sees this template,
they should fail the review or merge.

If this code change is fixing a user-visible bug in previously released code, it MUST
have an associated issue mentioned in the PR text or description. That Issue also
MUST be labelled “release bug”

This directs automation to scrape this fix for inclusion in the next release's
list of bugs fixed.

If this code is NOT for fixing a released bug, for example new function, fixing
a bug in unreleased function, or other improvements that do not affect the
user-space, no label is needed. An issue could or could not be used based
on the developer’s discretion, but do still delete this text block.

For full details, please see this wiki page:

https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions

### CODE REVIEW

**Comment by dave-waddling** [comment]
PB: https://wasrtc.hursley.ibm.com:9443/jazz/resource/itemOid/com.ibm.team.build.BuildResult/_cshWMKu7Ee6mAvAMVOSgKw

**Comment by dave-waddling** [comment]
Missed a few invocations of kill -9, fixed them. New build: https://wasrtc.hursley.ibm.com:9443/jazz/resource/itemOid/com.ibm.team.build.BuildResult/_WzTJ8K41Ee6cy7FiSuuNuQ

**Comment by dave-waddling** [comment]
Latest build linked finished with a single known test failure that is unrelated to my change; I've triaged it accordingly.
Looking at the individual build logs for async child builds there are no longer any messages printing the usage of `kill` due to running `kill -9` without an argument as we were doing.

As the test failure is understood and the build behaviour is correct the [build](https://wasrtc.hursley.ibm.com:9443/jazz/resource/itemOid/com.ibm.team.build.BuildResult/_WzTJ8K41Ee6cy7FiSuuNuQ) can be considered as green and validating my changes.

**Review by fritze2 — APPROVED** [review]
LGTM

**Comment by dave-waddling** [comment]
#libby

**Pull request merged**
