### PR TITLE
Allow two different error messages

### PR DESCRIPTION
**Pull request by benjamin-confino**
fixes https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.workitem.viewWorkItem&id=297817

### CODE REVIEW

**Comment by benjamin-confino** [comment]
#build

**Comment by benjamin-confino** [comment]
#build

**Comment by benjamin-confino** [comment]
#build

**Review by Azquelt — APPROVED** [review]

**Comment by benjamin-confino** [comment]
#libby

**Pull request merged**
