### PR TITLE
added NPE checks to SessionGet and SessionPut

### PR DESCRIPTION
**Pull request by randyclee**
Fixes: RTC 281747 and 282404

#build

### CODE REVIEW

**Comment by randyclee** [comment]
#build

**Comment by randyclee** [comment]
#build

**Comment by randyclee** [comment]
#build

**Comment by randyclee** [comment]
#build

**Comment by randyclee** [comment]
#build

**Review by zhang-ca — APPROVED** [review]

**Comment by randyclee** [comment]
#run-libby-bot

**Pull request merged**
