### PR TITLE
Enable jsf22 bean validation tests for faces40

### PR DESCRIPTION
**Pull request by pnicolucci**
for #22369

### CODE REVIEW

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
Java 17 build: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_k9TTkFTREe2P_cwgExA7aA

**Comment by pnicolucci** [comment]
Java 17 tests were successful

**Review by isaacrivriv — APPROVED** [review]
Changes look good to me, thanks!

**Pull request merged**
