### PR TITLE
Include Mbean testing for HTTP Stats

### PR DESCRIPTION
**Pull request by Channyboy**
- [x] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [x] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [x] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

################################################################################################

#build

### CODE REVIEW

**Review by tonyreigns — DISMISSED** [review]
LGTM

**Comment by Channyboy** [comment]
Errors encountered in build were test infra related (and for other tests).

**Comment by Channyboy** [comment]
#build #libby

**Review by tonyreigns — DISMISSED** [review]
LGTM

**Comment by Channyboy** [comment]
#build #libby

**Comment by Channyboy** [comment]
#build #libby

**Review by tonyreigns — DISMISSED** [review]

**Comment by Channyboy** [comment]
#build #libby

**Comment by Channyboy** [comment]
#build #libby

**Review by tonyreigns — APPROVED** [review]
LGTM

**Comment by Channyboy** [comment]
This PR adds new tests to `io.openliberty.http.monitor_fat`. The RTC build is still running but the bucket has passed.
The pipeline has finished and has passed this bucket as well. Error encountered there are related to zos buckets and would not be impacted by this PR. Merging.

**Pull request merged**
