### PR TITLE
Issue #15744: Update JSF 2.3 to 2.3.8

### LINKED ISSUE #15744: Pull in MyFaces 2.3.8
Pull in MyFaces 2.3.8

### PR DESCRIPTION
**Pull request by pnicolucci**
fixes #15744

### CODE REVIEW

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Review by volosied — APPROVED** [review]
Looks correct to me.

**Review by wtlucy — APPROVED** [review]
LGTM

**Comment by pnicolucci** [comment]
#run-libby-bot

**Pull request merged**
