### PR TITLE
(Restore) Revert "Revert "Update Persistence Service to tollerate JPA 2.2""

### PR DESCRIPTION
**Pull request by jgrassel**
Reverts OpenLiberty/open-liberty#878

### CODE REVIEW

**Comment by jgrassel** [comment]
#build

**Comment by aguibert** [comment]
#build

**Comment by aguibert** [comment]
#build

**Comment by aguibert** [comment]
Had to spin manual builds.

Reg build: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_WCqv8sYtEeeBHLpwjQKQLg

IM build: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_dg8fYMYtEeeBHLpwjQKQLg

**Pull request merged**
