### PR TITLE
refactor: convert SubscriptionMessageType to enum

### PR DESCRIPTION
**Pull request by ngmr**
- [x] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [x] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [x] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

### CODE REVIEW

**Comment by ngmr** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.messaging.open_31_fat,com.ibm.ws.messaging.open_clientcontainer_fat,com.ibm.ws.messaging.open_comms_fat,com.ibm.ws.messaging.open_fat,com.ibm.ws.messaging.open_jms20AutoCloseable_fat,com.ibm.ws.messaging.open_jms20context_fat,com.ibm.ws.messaging.open_jms20contextSecurity2_fat,com.ibm.ws.messaging.open_jms20contextSecurity_fat,com.ibm.ws.messaging.open_jms20deliverydelay_fat,com.ibm.ws.messaging.open_jms20_fat,com.ibm.ws.messaging.open_jms20security_fat,com.ibm.ws.microprofile.reactive.messaging_fat,io.openliberty.microprofile.reactive.messaging.internal_fat

**Comment by contbld** [comment]
Your personal pipeline request is at https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=21152c90-4195-4cf0-887e-6d03e1e6beb0

Target locations of links might be accessible only to IBM employees.

**Comment by contbld** [comment]
https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=21152c90-4195-4cf0-887e-6d03e1e6beb0 has errors/failures.

**Comment by contbld** [comment]
<h3>Code analysis and actions</h3>
DO NOT DELETE THIS COMMENT.

- 1 product code files were changed.

**Comment by ngmr** [comment]
!build
spawn.fullfat.buckets=com.ibm.ws.messaging.open_31_fat,com.ibm.ws.messaging.open_clientcontainer_fat,com.ibm.ws.messaging.open_comms_fat,com.ibm.ws.messaging.open_fat,com.ibm.ws.messaging.open_jms20AutoCloseable_fat,com.ibm.ws.messaging.open_jms20context_fat,com.ibm.ws.messaging.open_jms20contextSecurity2_fat,com.ibm.ws.messaging.open_jms20contextSecurity_fat,com.ibm.ws.messaging.open_jms20deliverydelay_fat,com.ibm.ws.messaging.open_jms20_fat,com.ibm.ws.messaging.open_jms20security_fat,com.ibm.ws.microprofile.reactive.messaging_fat,io.openliberty.microprofile.reactive.messaging.internal_fat

**Comment by contbld** [comment]
Your personal pipeline request is at https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=81b23482-d34a-4ae7-8c13-596a5f44e656

Target locations of links might be accessible only to IBM employees.

**Comment by contbld** [comment]
Your personal pipeline request is at https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=ef6f216e-4e90-4501-a3c5-8d819ed9454d

Target locations of links might be accessible only to IBM employees.

**Comment by contbld** [comment]
<h3>Code analysis and actions</h3>
DO NOT DELETE THIS COMMENT.

- 3 product code files were changed.

**Comment by contbld** [comment]
<h3>Code analysis and actions</h3>
DO NOT DELETE THIS COMMENT.

- 3 product code files were changed.

**Comment by contbld** [comment]
https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=81b23482-d34a-4ae7-8c13-596a5f44e656 has errors/failures.

**Review by sakerl — APPROVED** [review]

**Pull request merged**
