### PR TITLE
Add more versionless packaging test function

### PR DESCRIPTION
**Pull request by hlhoots**
#build

### CODE REVIEW

**Review by jimblye — DISMISSED** [review]

**Comment by hlhoots** [comment]
#build

**Comment by hlhoots** [comment]
#build

**Comment by hlhoots** [comment]
#libby

**Review by tbitonti — DISMISSED** [review]
See issue #29047 as a followup.  Not necessary at this time, and don't want to slow us down.

**Comment by hlhoots** [comment]
RTC build: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_49WdMkEZEe-Hn95lLM_tGQ

multiple builds overnight failed with download / unzip liberty failures

**Comment by hlhoots** [comment]
next build: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_ZDD3gEHtEe-F88sHKWQ5jw

**Review by rsherget — APPROVED** [review]
LGTM

**Comment by hlhoots** [comment]
1 build error. known issue.  merging.

**Pull request merged**
