### PR TITLE
perform jwe id token verification in FATs

### PR DESCRIPTION
**Pull request by jimmy1wu**
for issue https://github.com/OpenLiberty/open-liberty/issues/17652

### CODE REVIEW

**Comment by jimmy1wu** [comment]
#build

**Comment by jimmy1wu** [comment]
#libby

**Comment by jimmy1wu** [comment]
#build

**Comment by jimmy1wu** [comment]
#libby
#build

**Comment by jimmy1wu** [comment]
#libby
#build

**Review by c00crane — APPROVED** [review]

**Comment by jimmy1wu** [comment]
the build errors are unrelated

**Pull request merged**
