### PR TITLE
add fat tests for OpenIdAuthenticationMechanismDefinition prompt and promptExpression

### PR DESCRIPTION
**Pull request by jimmy1wu**
add fat tests for OpenIdAuthenticationMechanismDefinition `prompt` and `promptExpression`

added tests to validate that the prompt param is correctly added to the auth endpoint request. tests are included for no prompts, a single prompt, and multiple prompts. additionally, tests are included to test cases where an error is return from the OP and that promptExpression takes precedence over prompt. also, fixed the use of prompt in the logout and refresh tests, since it was not being properly passed into the openid config before this.

additionally, updated runtime to not add the optional params, such as prompt, if they are empty.

### CODE REVIEW

**Comment by jimmy1wu** [comment]
#build
#spawn.fullfat.buckets=io.openliberty.security.jakartasec.3.0.internal_fat,
io.openliberty.security.jakartasec.3.0.internal_fat.config,
io.openliberty.security.jakartasec.3.0.internal_fat.logout,
io.openliberty.security.jakartasec.3.0.internal_fat.refresh

**Comment by jimmy1wu** [comment]
#build
#spawn.fullfat.buckets=io.openliberty.security.jakartasec.3.0.internal_fat,
io.openliberty.security.jakartasec.3.0.internal_fat.config,
io.openliberty.security.jakartasec.3.0.internal_fat.logout,
io.openliberty.security.jakartasec.3.0.internal_fat.refresh

**Comment by jimmy1wu** [comment]
#libby
#build
#spawn.fullfat.buckets=io.openliberty.security.jakartasec.3.0.internal_fat,
io.openliberty.security.jakartasec.3.0.internal_fat.config,
io.openliberty.security.jakartasec.3.0.internal_fat.logout,
io.openliberty.security.jakartasec.3.0.internal_fat.refresh

**Review by c00crane — APPROVED** [review]

**Review by ayoho — APPROVED** [review]

**Comment by jimmy1wu** [comment]
for https://github.com/OpenLiberty/open-liberty/issues/21161

**Pull request merged**
