### PR TITLE
Update messageID for log rollover warning

### LINKED ISSUE #23390: Two messages use the same message ID in LoggingMessages.nlsprops
`TRAS3012W` is used twice in 2 different messages.

https://github.com/OpenLiberty/open-liberty/blob/08201219d6c6484d7b39e28f804cc47aefcdb6f3/dev/com.ibm.ws.logging/resources/com/ibm/ws/logging/internal/resources/LoggingMessages.nlsprops#L159

https://github.com/OpenLiberty/open-liberty/blob/08201219d6c6484d7b39e28f804cc47aefcdb6f3/dev/com.ibm.ws.logging/resources/com/ibm/ws/logging/internal/resources/LoggingMessages.nlsprops#L167

Message ID "TRAS3013W" is not needed in the explanation and useraction.

### PR DESCRIPTION
**Pull request by ellen-lau**
#build

Updating messageID for `LOG_ROLLOVER_START_TIME_FORMAT_WARNING` to `TRAS3015W`. Removing `TRAS3013W` from the `explanation` and `useraction` for `LOG_ROLLOVER_INTERVAL_TOO_SHORT_WARNING`.

### CODE REVIEW

**Comment by posmith** [comment]
L2 message review completed.

**Comment by ellen-lau** [comment]
#build

**Review by helyarp — COMMENTED** [review]
EN message changes look good!

**Comment by ellen-lau** [comment]
#run-libby-bot

**Comment by ellen-lau** [comment]
Build failures are not related to the changes.

**Review by Channyboy — APPROVED** [review]

**Comment by Channyboy** [comment]
lgtm

**Comment by Channyboy** [comment]
lgtm

**Pull request merged**
