### PR TITLE
Issue #21975: fix spelling of listener

### LINKED ISSUE #21975: Fix incorrect spelling of "Listener" (listner) in webcontainer and jsf(FAT)

### PR DESCRIPTION
**Pull request by pnicolucci**
fixes #21975

### CODE REVIEW

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
#liberty #build

**Review by pmd1nh — APPROVED** [review]

**Comment by pnicolucci** [comment]
#libby

**Pull request merged**
