### PR TITLE
9602 - H2 Synchronization

### LINKED ISSUE #9602: H2 Synchronization problem with tests that are sending duplicate frames
Scenario:

1) The H2 test sends two identical Headers frames, both with eos set
2) The server starts to process the first frame on stream 3, and gets interrupted part way through processing.  At this point the stream is in HALF_CLOSED_REMOTE state.  We have read in the headers but have not sent the request on to be processed.
3) The second identical frame comes in for stream 3 with eos set.
4) The server recognizes that the stream is closing, can't accept a new read frame and sends a goaway frame saying the stream is already closed.
5) The server cleans up all things stream 3 related.
6) The server then gets back to processing the original valid HEADERS frame, but the resources have been deleted, and we get the NPE.

### PR DESCRIPTION
**Pull request by loriadi**
fixes #9602

### CODE REVIEW

**Comment by loriadi** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.transport.http2_fat

**Comment by loriadi** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.transport.http2_fat

**Comment by loriadi** [comment]
#build

**Comment by loriadi** [comment]
#build

**Comment by loriadi** [comment]
#build

**Comment by pnicolucci** [comment]
#run-libby-bot

**Comment by loriadi** [comment]
#run-libby-bot

**Comment by loriadi** [comment]
#build

**Comment by loriadi** [comment]
#build

**Comment by loriadi** [comment]
The two failed tests are covered by an existing defect.

**Comment by loriadi** [comment]
testHeaderFrameAfterHeaderFrameWithEndOfStream
junit.framework.AssertionFailedError: 2019-04-02-18:16:50:190 [Unexpected FFDC reporting java.lang.NullPointerException was found (count = 1): /home/jazz_build/_IIwVwFUQEem8NdNdaSGUMw-EBC.PROD.WASRTC-6CX-001-00-00/jbe/build/dev/image/output/wlp/usr/servers/com.ibm.ws.transport.http2.fat/logs/ffdc/ffdc_19.04.02_18.16.49.0.log
>------Start of DE processing------ = [4/2/19 18:16:49:679 UTC]
>Exception = java.lang.NullPointerException
>Source = com.ibm.ws.http.channel.internal.inbound.HttpInboundServiceContextImpl.init
>probeid = 1
>Stack Dump = java.lang.NullPointerException
>at com.ibm.ws.tcpchannel.internal.TCPConnLink.getRemoteAddress(TCPConnLink.java:367)
>at com.ibm.ws.http.channel.h2internal.H2TCPConnectionContext.getRemoteAddress(H2TCPConnectionContext.java:58)
>at com.ibm.ws.http.channel.internal.HttpServiceContextImpl.init(HttpServiceContextImpl.java:916)
>at com.ibm.ws.http.channel.internal.inbound.HttpInboundServiceContextImpl.init(HttpInboundServiceContextImpl.java:119)
>at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.ready(HttpInboundLink.java:298)
>at com.ibm.ws.http.channel.h2internal.H2StreamProcessor$Http2Ready.run(H2StreamProcessor.java:1597)
>at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:239)
>at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
>at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
>at java.base/java.lang.Thread.run(Thread.java:825)
]
at componenttest.custom.junit.runner.FATRunner.blowup(FATRunner.java:296)
at componenttest.custom.junit.runner.FATRunner.access$500(FATRunner.java:64)
at componenttest.custom.junit.runner.FATRunner$1.evaluate(FATRunner.java:246)
at componenttest.custom.junit.runner.FATRunner$2.evaluate(FATRunner.java:314)
at componenttest.custom.junit.runner.FATRunner.run(FATRunner.java:167)

Occurred on the following Platforms:
Liberty Full Fat - Java 2 security -  EBC - 20190402-0415

**Comment by loriadi** [comment]
#build

**Comment by loriadi** [comment]
#build

**Comment by loriadi** [comment]
#libby-bot

**Comment by loriadi** [comment]
#build

**Comment by loriadi** [comment]
4 test failures unrelated to this change.

**Pull request merged**
