### PR TITLE
JCA annotations not processed for v2.0

### LINKED ISSUE #15461: TCK: whitebox-mixedmode and whitebox-permissiondd adapters start but cannot be looked up
36 Connector TCK EE9 tests fail due to two adapters (whitebox-mixedmode & whitebox-permissiondd) that appear to start, but cannot be injected or looked up in the server.

```
11-18-2020 12:57:19:  SVR-ERROR: javax.naming.NamingException: CWNEN1001E: The object referenced by the java:comp/env/eis/whitebox-mixedmode JNDI name could not be instantiated. If the reference name maps to a JNDI name in the deployment descriptor bindings for the application performing the JNDI lookup, make sure that the JNDI name mapping in the deployment descriptor binding is correct. If the JNDI name mapping is correct, make sure the target resource can be resolved with the specified name relative to the default initial context. [Root exception is com.ibm.wsspi.injectionengine.InjectionException: CWNEN0030E: The server was unable to obtain an object instance for the java:comp/env/eis/whitebox-mixedmode reference.  The exception message was: CWNEN1004E: The server was unable to find the eis/whitebox-mixedmode default binding with the com.sun.ts.tests.common.connector.whitebox.TSConnectionFactory type for the java:comp/env/eis/whitebox-mixedmode reference.]
	at com.ibm.ws.injectionengine.osgi.internal.naming.InjectionJavaColonHelper.newCannotInstantiateObjectException(InjectionJavaColonHelper.java:183)
	at com.ibm.ws.injectionengine.osgi.internal.naming.InjectionJavaColonHelper.getObjectInstance(InjectionJavaColonHelper.java:118)
	at com.ibm.ws.jndi.url.contexts.javacolon.internal.JavaURLContext.lookup(JavaURLContext.java:332)
	at com.ibm.ws.jndi.url.contexts.javacolon.internal.JavaURLContext.lookup(JavaURLContext.java:370)
	at org.apache.aries.jndi.DelegateContext.lookup(DelegateContext.java:149)
	at javax.naming.InitialContext.lookup(InitialContext.java:417)
	at com.sun.ts.lib.util.TSNamingContext.lookup(TSNamingContext.java:69)
	at com.sun.ts.tests.connector.annotations.partialanno.paClient.setup(paClient.java:92)
        ...
Caused by: com.ibm.wsspi.injectionengine.InjectionException: CWNEN0030E: The server was unable to obtain an object instance for the java:comp/env/eis/whitebox-mixedmode reference.  The exception message was: CWNEN1004E: The server was unable to find the eis/whitebox-mixedmode default binding with the com.sun.ts.tests.common.connector.whitebox.TSConnectionFactory type for the java:comp/env/eis/whitebox-mixedmode reference.
	at com.ibm.wsspi.injectionengine.InjectionBinding.getInjectionObject(InjectionBinding.java:1454)
	at com.ibm.wsspi.injectionengine.InjectionBinding.getInjectionObject(InjectionBinding.java:1384)
	at com.ibm.ws.injectionengine.osgi.internal.naming.InjectionJavaColonHelper.getObjectInstance(InjectionJavaColonHelper.java:116)
	... 50 more
Caused by: com.ibm.wsspi.injectionengine.InjectionException: CWNEN1004E: The server was unable to find the eis/whitebox-mixedmode default binding with the com.sun.ts.tests.common.connector.whitebox.TSConnectionFactory type for the java:comp/env/eis/whitebox-mixedmode reference.
	at com.ibm.ws.injectionengine.osgi.internal.IndirectJndiLookupObjectFactory.getObjectInstance(IndirectJndiLookupObjectFactory.java:194)
	at com.ibm.ws.injectionengine.osgi.internal.IndirectJndiLookupObjectFactory.getObjectInstance(IndirectJndiLookupObjectFactory.java:100)
	at com.ibm.wsspi.injectionengine.InjectionBinding.getInjectionObjectInstance(InjectionBinding.java:1552)
	at com.ibm.wsspi.injectionengine.InjectionBinding.getInjectionObject(InjectionBinding.java:1428)
	... 52 more
```

### PR DESCRIPTION
**Pull request by njr-11**
fixes #15461

### CODE REVIEW

**Review by KyleAure — APPROVED** [review]

**Comment by njr-11** [comment]
#build

**Comment by njr-11** [comment]
#build

**Comment by wraschke** [comment]
#help

**Comment by wraschke** [comment]
#help

**Comment by wraschke** [comment]
Hello, Nathan, this is only a test message.

**Comment by wraschke** [comment]
#help

**Comment by wraschke** [comment]
#run-libby

**Comment by wraschke** [comment]
#build

**Pull request merged**
