### PR TITLE
Remove Servlet 5.0 duplicate resource overlays

### LINKED ISSUE #14796: Remove servlet 5.0 duplicate resource overlays
`io.openliberty.jakarta.servlet.5.0` contains the following `src/jakarta/servlet/resources` within this directory are the following files:

image

This is because the M1 version of the API jar did not have anything in `src/jakarta/servlet/resources` directory. The Servlet 4.0 API jar which is shipped as part of open liberty contains:

image

There are three files in the overlays that are currently not in the Servlet 5.0 final API jar from Eclipse for Jakarta EE9:

```
	datatypes.dtd
	xml.xsd
	XMLSchema.dtd
```
The remaining three will be looked at in the following issue: https://github.com/OpenLiberty/open-liberty/issues/14799

The following shows what files are in the Servlet 5.0 API jar's `jakarta/servlet/resources` directory: https://github.com/eclipse-ee4j/servlet-api/tree/master/api/src/main/resources/jakarta/servlet/resources

### PR DESCRIPTION
**Pull request by pnicolucci**
fixes #14796

### CODE REVIEW

**Comment by pnicolucci** [comment]
#build

**Review by volosied — APPROVED** [review]
Looks good!

**Comment by pnicolucci** [comment]
#run-libby-bot

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#run-libby-bot

**Pull request merged**
