### PR TITLE
OL fattest.simplicity update to enable FIPS 140-3

### PR DESCRIPTION
**Pull request by meiaus**
Work items:
https://github.ibm.com/websphere/WS-CD-Open/issues/30272
https://github.ibm.com/websphere/WS-CD-Open/issues/30273

Replace https://github.com/OpenLiberty/open-liberty/pull/26228

### CODE REVIEW

**Comment by meiaus** [comment]
#run-libby-bot

**Comment by meiaus** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.security.saml.sso_fat, com.ibm.ws.security.saml.sso_fat.2,com.ibm.ws.security.saml.sso_fat.3, com.ibm.ws.security.saml.sso_fat.config,com.ibm.ws.security.saml.sso_fat.config.mapToUserRegistry,com.ibm.ws.security.saml.sso_fat.endpoint.samlmetadata,com.ibm.ws.security.saml.sso_fat.jaxrs,com.ibm.ws.security.saml.sso_fat.jaxrs.config,com.ibm.ws.security.saml.sso_fat.logout,com.ibm.ws.security.oidc.client_fat.config.1,com.ibm.ws.security.oidc.client_fat.config.2,com.ibm.ws.security.oidc.client_fat.backchannelLogout,com.ibm.ws.security.oidc.client_fat.backchannelLogout.saml,com.ibm.ws.security.oidc.client_fat.claimPropagation,com.ibm.ws.security.oidc.client_fat.e2e,com.ibm.ws.security.oidc.client_fat.jaxrs,com.ibm.ws.security.oidc.client_fat.saml,com.ibm.ws.security.oidc.client_fat.spnego, com.ibm.ws.security.oidc.server_fat.app-passwords,com.ibm.ws.security.oidc.server_fat.app-passwords.DerbyDB.jwt,com.ibm.ws.security.oidc.server_fat.app-passwords.DerbyDB.opaque,com.ibm.ws.security.oidc.server_fat.app-passwords.LocalStore.jwt,com.ibm.ws.security.oidc.server_fat.app-passwords.LocalStore.opaque,com.ibm.ws.security.oidc.server_fat.app-tokens,com.ibm.ws.security.oidc.server_fat.app-tokens.DerbyDB.jwt,com.ibm.ws.security.oidc.server_fat.app-tokens.DerbyDB.opaque,com.ibm.ws.security.oidc.server_fat.app-tokens.LocalStore.jwt,com.ibm.ws.security.oidc.server_fat.app-tokens.LocalStore.opaque,com.ibm.ws.security.oidc.server_fat.backchannelLogout,com.ibm.ws.security.oidc.server_fat.clientregistration,com.ibm.ws.security.oidc.server_fat.config,com.ibm.ws.security.oidc.server_fat.config.oauth,com.ibm.ws.security.oidc.server_fat.config.oidc,com.ibm.ws.security.oidc.server_fat.endpoint.authorize,com.ibm.ws.security.oidc.server_fat.endpoint.coveragemap,com.ibm.ws.security.oidc.server_fat.endpoint.discovery,com.ibm.ws.security.oidc.server_fat.endpoint.end_session,com.ibm.ws.security.oidc.server_fat.endpoint.introspect,com.ibm.ws.security.oidc.server_fat.endpoint.revoke,com.ibm.ws.security.oidc.server_fat.endpoint.token,com.ibm.ws.security.oidc.server_fat.endpoint.userinfo,com.ibm.ws.security.oidc.server_fat.feature,com.ibm.ws.security.oidc.server_fat.granttype.jwt,com.ibm.ws.security.oidc.server_fat.jaxrs,com.ibm.ws.security.oidc.server_fat.jaxrs.config,com.ibm.ws.security.oidc.server_fat.oauth,com.ibm.ws.security.oidc.server_fat.oidc,com.ibm.ws.security.oidc.server_fat.saml,com.ibm.ws.security.oidc.server_fat.spnego,com.ibm.ws.security.social_fat.LibertyOP.1,com.ibm.ws.security.social_fat.LibertyOP.2,com.ibm.ws.security.social_fat.LibertyOP.backchannelLogout,com.ibm.ws.security.social_fat.LibertyOP.claimPropagation,com.ibm.ws.security.social_fat.OpenShift,com.ibm.ws.security.social_fat.delegated,com.ibm.ws.security.social_fat.multiProvider,com.ibm.ws.security.social_fat.okdServiceLogin,com.ibm.ws.wssecurity_fat.wsscxf.1,com.ibm.ws.wssecurity_fat.wsscxf.2,com.ibm.ws.wssecurity_fat.wsscxf.3,com.ibm.ws.wssecurity_fat.wsscxf.4,com.ibm.ws.wssecurity_fat.wsscxf.saml.1,com.ibm.ws.wssecurity_fat.wsscxf.saml.2,com.ibm.ws.wssecurity_fat.wsscxf.saml.3,com.ibm.ws.wssecurity_fat.wsscxf.saml.6,com.ibm.ws.wssecurity_fat.wsscxf.saml.5,com.ibm.ws.security.saml.sso_fat,com.ibm.ws.security.saml.sso_fat.2,com.ibm.ws.security.saml.sso_fat.3,com.ibm.ws.security.saml.sso_fat.config,com.ibm.ws.security.saml.sso_fat.config.mapToUserRegistry,com.ibm.ws.security.saml.sso_fat.endpoint.samlmetadata,com.ibm.ws.security.saml.sso_fat.jaxrs,com.ibm.ws.security.saml.sso_fat.jaxrs.config,com.ibm.ws.security.saml.sso_fat.logout,com.ibm.ws.security.saml.sso_fat.logout.IDP_initiated,com.ibm.ws.security.saml.sso_fat.logout.httpServletRequest,com.ibm.ws.security.saml.sso_fat.logout.ibm_security_logout,com.ibm.ws.webcontainer.security.feature_fat,com.ibm.ws.webcontainer.security.jacc.1.5_fat,com.ibm.ws.webcontainer.security_fat,com.ibm.ws.webcontainer.security_fat.features,com.ibm.ws.webcontainer.security_fat.passwordutil,
com.ibm.ws.security.jwt_fat.builder,com.ibm.ws.security.jwt_fat.consumer,com.ibm.ws.security.jwt_fat.mpjwt,com.ibm.ws.security.jwtsso_fat,com.ibm.ws.security.social_fat,com.ibm.ws.security.social_fat.LibertyOP,com.ibm.ws.security.social_fat.delegated,com.ibm.ws.security.social_fat.multiProvider,com.ibm.ws.jaxws.clientcontainer_fat,com.ibm.ws.jaxws.2.2.webcontainer_fat,com.ibm.ws.jaxrs.2.x.webcontainer_fat,com.ibm.ws.jaxrs.2.1_fat,com.ibm.ws.jaxrs.2.0_fat,com.ibm.ws.jaxrs.2.0.client_fat, com.ibm.ws.jaxrs.2.1.client_fat, com.ibm.websphere.ssl_fat, com.ibm.ws.ssl_fat

**Comment by meiaus** [comment]
The PB result from `#build`:

Properties setting indicating OL PR branch and CL release:
image

Test result all passed except 2 failure out of scope:

image

**Comment by meiaus** [comment]
The SOE build result:

- platforms set as:
`soe.platform.requests` `UBUNTU22_ARM_SEMERU_OPEN_17,OSX_13_VENTURA_IBMJDK8,AIX73_POWER10_PPC_TEMURIN_11`


- tests passed except the following invalid (due to FAT buckets name no longer available)

image

- but `Activities` tab showing pending:

image

- as well as `Logs` showing timed out:
image

bad-overall-build-progress.txt:
```
The following error occurred while executing this line:
/home/jazz_build/Build/jbe/build/WS-CD-Open/dev/ant_build/resources/build_imports/liberty-macros.xml:992: Parallel execution timed out
	at org.apache.tools.ant.ProjectHelper.addLocationToBuildException(ProjectHelper.java:551)
```

**Comment by meiaus** [comment]
The resulted invalid buckets from the above PB/SOE result have been expanded as follows:
```
com.ibm.ws.security.mp.jwt.1.1_fat.mpJwt-1.1, com.ibm.ws.security.mp.jwt.1.1_fat.mpJwt-1.1.envVars, com.ibm.ws.security.mp.jwt.1.1_fat.mpJwt-1.1.sysProps, com.ibm.ws.security.mp.jwt.1.1_fat.mpJwt-1.2, com.ibm.ws.security.mp.jwt.1.1_fat.mpJwt-1.2.envVars, com.ibm.ws.security.mp.jwt.1.1_fat.mpJwt-1.2.sysProps, com.ibm.ws.security.mp.jwt.1.1_fat.mpJwt-2.0, com.ibm.ws.security.mp.jwt.1.1_fat.mpJwt-2.0.envVars, com.ibm.ws.security.mp.jwt.1.1_fat.mpJwt-2.0.sysProps, com.ibm.ws.security.mp.jwt.1.1_fat.mpJwt-2.1, com.ibm.ws.security.mp.jwt.1.1_fat.mpJwt-2.1.envVars, om.ibm.ws.security.mp.jwt.1.1_fat.mpJwt-2.1.sysProps,com.ibm.ws.security.jwtsso_fat.mpJwt-1.1, com.ibm.ws.security.jwtsso_fat.mpJwt-1.2, com.ibm.ws.security.jwtsso_fat.mpJwt-2.0, com.ibm.ws.security.jwtsso_fat.mpJwt-2.1, com.ibm.ws.security.jwtsso_fat.noMpJwt,

com.ibm.ws.security.social_fat.LibertyOP.1, com.ibm.ws.security.social_fat.LibertyOP.1, com.ibm.ws.security.social_fat.LibertyOP.1, com.ibm.ws.security.social_fat.LibertyOP.backchannelLogout, com.ibm.ws.security.social_fat.LibertyOP.claimPropagation
```

The next SOE build is submitted with the updated full buckets, and set only one platform `AIX73_POWER10_PPC_TEMURIN_11` for retesting:

```
#spawn.fullfat.buckets=com.ibm.ws.security.saml.sso_fat, com.ibm.ws.security.saml.sso_fat.2,com.ibm.ws.security.saml.sso_fat.3, com.ibm.ws.security.saml.sso_fat.config,com.ibm.ws.security.saml.sso_fat.config.mapToUserRegistry,com.ibm.ws.security.saml.sso_fat.endpoint.samlmetadata,com.ibm.ws.security.saml.sso_fat.jaxrs,com.ibm.ws.security.saml.sso_fat.jaxrs.config,com.ibm.ws.security.saml.sso_fat.logout,com.ibm.ws.security.oidc.client_fat.config.1,com.ibm.ws.security.oidc.client_fat.config.2,com.ibm.ws.security.oidc.client_fat.backchannelLogout,com.ibm.ws.security.oidc.client_fat.claimPropagation,com.ibm.ws.security.oidc.client_fat.e2e,com.ibm.ws.security.oidc.client_fat.jaxrs,com.ibm.ws.security.oidc.client_fat.saml,com.ibm.ws.security.oidc.client_fat.spnego, com.ibm.ws.security.oidc.server_fat.app-passwords,com.ibm.ws.security.oidc.server_fat.app-passwords.DerbyDB.jwt,com.ibm.ws.security.oidc.server_fat.app-passwords.DerbyDB.opaque,com.ibm.ws.security.oidc.server_fat.app-passwords.LocalStore.jwt,com.ibm.ws.security.oidc.server_fat.app-passwords.LocalStore.opaque,com.ibm.ws.security.oidc.server_fat.app-tokens,com.ibm.ws.security.oidc.server_fat.app-tokens.DerbyDB.jwt,com.ibm.ws.security.oidc.server_fat.app-tokens.DerbyDB.opaque,com.ibm.ws.security.oidc.server_fat.app-tokens.LocalStore.jwt,com.ibm.ws.security.oidc.server_fat.app-tokens.LocalStore.opaque,com.ibm.ws.security.oidc.server_fat.backchannelLogout,com.ibm.ws.security.oidc.server_fat.clientregistration,com.ibm.ws.security.oidc.server_fat.config,com.ibm.ws.security.oidc.server_fat.config.oauth,com.ibm.ws.security.oidc.server_fat.config.oidc,com.ibm.ws.security.oidc.server_fat.endpoint.authorize,com.ibm.ws.security.oidc.server_fat.endpoint.coveragemap,com.ibm.ws.security.oidc.server_fat.endpoint.discovery,com.ibm.ws.security.oidc.server_fat.endpoint.end_session,com.ibm.ws.security.oidc.server_fat.endpoint.introspect,com.ibm.ws.security.oidc.server_fat.endpoint.revoke,com.ibm.ws.security.oidc.server_fat.endpoint.token,com.ibm.ws.security.oidc.server_fat.endpoint.userinfo,com.ibm.ws.security.oidc.server_fat.feature,com.ibm.ws.security.oidc.server_fat.granttype.jwt,com.ibm.ws.security.oidc.server_fat.jaxrs,com.ibm.ws.security.oidc.server_fat.jaxrs.config.noOP, com.ibm.ws.security.oidc.server_fat.jaxrs.config.oauth,com.ibm.ws.security.oidc.server_fat.jaxrs.config.oidc,com.ibm.ws.security.oidc.server_fat.oauth,com.ibm.ws.security.oidc.server_fat.oidc,com.ibm.ws.security.oidc.server_fat.saml,com.ibm.ws.security.oidc.server_fat.spnego,com.ibm.ws.security.social_fat.LibertyOP.1,com.ibm.ws.security.social_fat.LibertyOP.2,com.ibm.ws.security.social_fat.LibertyOP.backchannelLogout,com.ibm.ws.security.social_fat.LibertyOP.claimPropagation,com.ibm.ws.security.social_fat.OpenShift,com.ibm.ws.security.social_fat.delegated,com.ibm.ws.security.social_fat.multiProvider,com.ibm.ws.security.social_fat.okdServiceLogin,com.ibm.ws.wssecurity_fat.wsscxf.1,com.ibm.ws.wssecurity_fat.wsscxf.2,com.ibm.ws.wssecurity_fat.wsscxf.3,com.ibm.ws.wssecurity_fat.wsscxf.4,com.ibm.ws.wssecurity_fat.wsscxf.saml.1,com.ibm.ws.wssecurity_fat.wsscxf.saml.2,com.ibm.ws.wssecurity_fat.wsscxf.saml.3,com.ibm.ws.wssecurity_fat.wsscxf.saml.6,com.ibm.ws.wssecurity_fat.wsscxf.saml.5,com.ibm.ws.security.saml.sso_fat,com.ibm.ws.security.saml.sso_fat.2,com.ibm.ws.security.saml.sso_fat.3,com.ibm.ws.security.saml.sso_fat.config,com.ibm.ws.security.saml.sso_fat.config.mapToUserRegistry,com.ibm.ws.security.saml.sso_fat.endpoint.samlmetadata,com.ibm.ws.security.saml.sso_fat.jaxrs,com.ibm.ws.security.saml.sso_fat.jaxrs.config,com.ibm.ws.security.saml.sso_fat.logout,com.ibm.ws.security.saml.sso_fat.logout.IDP_initiated,com.ibm.ws.security.saml.sso_fat.logout.httpServletRequest,com.ibm.ws.security.saml.sso_fat.logout.ibm_security_logout,com.ibm.ws.webcontainer.security.feature_fat,com.ibm.ws.webcontainer.security.jacc.1.5_fat,com.ibm.ws.webcontainer.security_fat,com.ibm.ws.webcontainer.security_fat.features,com.ibm.ws.webcontainer.security_fat.passwordutil,
com.ibm.ws.security.jwt_fat.builder,com.ibm.ws.security.jwt_fat.consumer, com.ibm.ws.security.mp.jwt.1.1_fat.mpJwt-1.1, com.ibm.ws.security.mp.jwt.1.1_fat.mpJwt-1.1.envVars, com.ibm.ws.security.mp.jwt.1.1_fat.mpJwt-1.1.sysProps, com.ibm.ws.security.mp.jwt.1.1_fat.mpJwt-1.2, com.ibm.ws.security.mp.jwt.1.1_fat.mpJwt-1.2.envVars, com.ibm.ws.security.mp.jwt.1.1_fat.mpJwt-1.2.sysProps, com.ibm.ws.security.mp.jwt.1.1_fat.mpJwt-2.0, com.ibm.ws.security.mp.jwt.1.1_fat.mpJwt-2.0.envVars, com.ibm.ws.security.mp.jwt.1.1_fat.mpJwt-2.0.sysProps, com.ibm.ws.security.mp.jwt.1.1_fat.mpJwt-2.1, com.ibm.ws.security.mp.jwt.1.1_fat.mpJwt-2.1.envVars, om.ibm.ws.security.mp.jwt.1.1_fat.mpJwt-2.1.sysProps,com.ibm.ws.security.jwtsso_fat.mpJwt-1.1, com.ibm.ws.security.jwtsso_fat.mpJwt-1.2, com.ibm.ws.security.jwtsso_fat.mpJwt-2.0, com.ibm.ws.security.jwtsso_fat.mpJwt-2.1, com.ibm.ws.security.jwtsso_fat.noMpJwt,com.ibm.ws.security.social_fat, com.ibm.ws.security.social_fat.LibertyOP.1, com.ibm.ws.security.social_fat.LibertyOP.1, com.ibm.ws.security.social_fat.LibertyOP.1, com.ibm.ws.security.social_fat.LibertyOP.backchannelLogout,com.ibm.ws.security.social_fat.LibertyOP.claimPropagation,com.ibm.ws.security.social_fat.delegated,com.ibm.ws.security.social_fat.multiProvider,com.ibm.ws.jaxws.clientcontainer_fat,com.ibm.ws.jaxws.2.2.webcontainer_fat,com.ibm.ws.jaxrs.2.x.webcontainer_fat,com.ibm.ws.jaxrs.2.1_fat,com.ibm.ws.jaxrs.2.0_fat,com.ibm.ws.jaxrs.2.0.client_fat, com.ibm.ws.jaxrs.2.1.client_fat, com.ibm.websphere.ssl_fat, com.ibm.ws.ssl_fat
```

**Comment by meiaus** [comment]
Due to above legacy SOE builds' result with pending situation, re-submit SOE by using the instruction `CI Orchestrator SOE Platform against a PB` in 
https://github.ibm.com/websphere/WS-CD-Open/wiki/SOE-(Supported-Operating-Environments)-build#requesting-a-run-as-part-of-a-personal-build: 


image

**Comment by meiaus** [comment]
To try with new the instruction `CI Orchestrator SOE Platform against a PB` in 
https://github.ibm.com/websphere/WS-CD-Open/wiki/SOE-(Supported-Operating-Environments)-build#requesting-a-run-as-part-of-a-personal-build: 
submit a fresh PB (without spawn full buckets) and then will use this PB to submit for CI SOE afterwards.

#build

**Comment by meiaus** [comment]
Submitted the request for `CI Orchestrator SOE Platform against a PB`:

image

**Comment by meiaus** [comment]
The pipeline analysis:
https://libh-proxy1.fyre.ibm.com/cognitive-dev/pipelineAnalysis.html?uuid=ca1a364a-5dc7-467b-9944-1fda9a53127b&tab=Steps

**Comment by meiaus** [comment]
Re-submit for windows only:

image


https://libh-proxy1.fyre.ibm.com/cognitive-dev/pipelineAnalysis.html?uuid=451757d2-7de4-4d60-afda-b405c14d4829

Somehow the initial pipelineruns didn't show the specified windows under `Steps`:

image

image

**Comment by meiaus** [comment]
#run-libby-bot

**Comment by meiaus** [comment]
#run-libby-bot

**Comment by meiaus** [comment]
#build

**Comment by meiaus** [comment]
#run-libby-bot

**Comment by meiaus** [comment]
#build

**Comment by meiaus** [comment]
Submitted pipeline run SOE build against the PB:
image


image

**Comment by meiaus** [comment]
Pipeline analysis:
https://libh-proxy1.fyre.ibm.com/cognitive-dev/pipelineAnalysis.html?uuid=325d7665-9cba-435f-8efe-dfca2c305375

**Review by arunavemulapalli — APPROVED** [review]

**Comment by meiaus** [comment]
Pipeline analysis showed some buckets didn't complete (with `Impossible`, which is usually caused by the infrastructure and is out of PR scope):


image


SOE analysis showed some failures within the executed buckets, which are already tracked with known defects.  For those not tracked with defects yet are also out of PR scope:

https://libh-proxy1.fyre.ibm.com/cognitive-dev/soeAnalysis.html?uuid=_de714HkLEe6p7N33NVgeoQ&tab=All+Failures&maxRows=40000

image


From validating the changes per regression perspective, the goal is achieved.  The PR will be merged.

**Pull request merged**
