### PR TITLE
Increase async timetout in WC test application for large data

### LINKED ISSUE #18624: Increase async timeout to accommodate network latency
Set async timeout to 300 sec to accommodate slow network when testing large data.

It was previously increased to 75 sec in [17014](https://github.com/OpenLiberty/open-liberty/pull/17014) but apparently that may not totally fix the problem.

### PR DESCRIPTION
**Pull request by pmd1nh**
fixed #18624

### CODE REVIEW

**Comment by pmd1nh** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.webcontainer_fat,com.ibm.ws.webcontainer.servlet.3.1_fat,com.ibm.ws.webcontainer.servlet.4.0_fat,com.ibm.ws.webcontainer_fat_part2,com.ibm.ws.webcontainer_fat_servlet31toleration,com.ibm.ws.webcontainer_fat_servlet31toleration_part2,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0_part2,com.ibm.ws.webcontainer_fat_lWAS,com.ibm.ws.webcontainer_fat_servlet31_webcontainerlWAS,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0.lWAS

**Comment by pmd1nh** [comment]
#run-libby-bot

**Review by pnicolucci — APPROVED** [review]
Looks good!

**Review by epj — APPROVED** [review]
looks good

**Pull request merged**
