### PR TITLE
Issue24387

### LINKED ISSUE #24387: Skipped Faces Tests (Caused by JavaScript Changes in 4.0.0-RC5)
See 4.0.0-RC5 PR:  https://github.com/OpenLiberty/open-liberty/pull/24370 

**79** Tests Skipped. 26 are being enabled

Applications: 
[applications.zip](https://github.com/OpenLiberty/open-liberty/files/10865518/applications.zip)
[23apps.zip](https://github.com/OpenLiberty/open-liberty/files/10905012/23apps.zip)

## com.ibm.ws.jsf_fat_lWAS_faces4.0 
- JSF20AJAXTag
  - testDisabledFalse
  - testEventDefault
  - testEventSpecified
  - testExecuteAll
  - testExecuteDefault
  - testExecuteForm
  - testExecuteMultiple
  - testExecuteSingle
  - testExecuteThis
  - testListener
  - testOnError
  - testOnEvent
  - testRenderAll
  - testRenderForm
  - testRenderMultipleComponents
  - testRenderSingleComponent
  - testRenderThis
  - testImmediateFalse
  - testImmediateTrue
  - testImmediateDefault
- ~JSF20BeanValidation~ -> Merged: WS-CD-Open/pull/28935
  - ~testSizeConstraint~
  - ~testNotNullConstraint~
  - ~testMinConstraint~
  - ~testMaxConstraint~
  - ~testNullConstraint~
  - ~testAssertTrueConstraint~
  - ~testAssertFalseConstraint~
  - ~testFutureConstraint~
  - ~testPastConstraint~
  - ~testDigitsConstraint~
  - ~testDecimalMaxConstraint~
  - ~testDecimalMinConstraint~
  - ~testPatternConstraint~
  - ~testPatternConstraintOnMethod~
  - ~testValidateBeanTagDefault~
  - ~testValidateBeanTagDisabledTrue~
  - ~testValidationBeanTagGroups~
  - ~testValidationBeanTagWrapMultiple~
  - ~testCustomConstraint~
- JSF20Behaviors
  - ~testAnnotated~ -> enabled WS-CD-Open/pull/28943
  - ~testDefined~ -> enabled WS-CD-Open/pull/28943
  - testAjax
- JSF20JavaScriptAPI
  - testExecuteAll
  - testExecuteDefault
  - testExecuteForm
  - testExecuteMultiple
  - testExecuteNone
  - testExecuteSingle
  - testExecuteThis
  - testOnError
  - testOnEvent
  - testRenderDefault
  - testRenderForm
  - testRenderMultipleComponents
  - testRenderNone
  - testRenderSingleComponent
  - testRenderThis
  - testOnEventCall
  - testOnErrorCall
- JSF20Navigation
  - testConditional
 - JSF20AJAX (recently ported from old testsuite bucket) 
   - testJSF
   - testDojo
   

## com.ibm.ws.jsf.2.2_fat
Failures: 
- [JSF22ComponentTester_TestCommandLinkOrder](https://github.com/OpenLiberty/open-liberty/blob/382c0bac1dbf3e85ed565eb603829255723a08ee/dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/JSF22ComponentTesterTests.java#L230)
  - JSF22ComponentTester_TestCommandLinkOrder: test output is not correct: Not called 
- [testResetValues](https://github.com/OpenLiberty/open-liberty/blob/c567d068ed5b9d878138d7d22ed6d09d2bc03930/dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/JSF22MiscellaneousTests.java#L194) (JSF22MiscellaneousTests)
  - expected:<[1]> but was:<[0]> 

Errors ( "missing formal parameter "):
- [JSF22ClientWindowTests](https://github.com/OpenLiberty/open-liberty/blob/7fad9e794d71ef64b1d8cec461b2f50b1094e28a/dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/JSF22ClientWindowTests.java#L48)  
[jsfTestServer2.zip](https://github.com/OpenLiberty/open-liberty/files/10905261/jsfTestServer2.zip)

  - JSF22ClientWindow_TestAjax
  - JSF22ClientWindow_TestSimpleLink
  - JSF22ClientWindow_TestSimpleLinkNewWindow	JSF22ClientWindow_TestDisabledLink
  - JSF22ClientWindow_TestCommandButton
  - JSF22ClientWindow_TestCommandLink
  - JSF22ClientWindow_TestButton
  - JSF22ClientWindow_TestButtonDisabled
  - JSF22ClientWindow_TestMultipleBasePages
- JSFCompELTests.java
  - testAjaxEvent
- JSF22ResetValuesAndAjaxDelayTests.java
  - testResetValues
  - [testAjaxZeroDelay](https://github.com/OpenLiberty/open-liberty/blob/9185922ddd82d1b5a4f9300d7f71ecd6d32b1f81/dev/com.ibm.ws.jsf.2.2_fat/fat/src/com/ibm/ws/jsf22/fat/tests/JSF22ResetValuesAndAjaxDelayTests.java#L179)
- JSF22AppConfigPopTests.java
  - testACPNavigationRule -> https://github.com/OpenLiberty/open-liberty/pull/24572
- JSF22AparTests.java
  - testViewScopedJSFManagedBeanPreDestroy -> Enabled with :https://github.com/OpenLiberty/open-liberty/pull/24547

## com.ibm.ws.jsf.2.3_fat

Failures: 
- ~~testFaceletRefreshPeriodProduction~~ [FIXED via context parameter]
  - ~~The correct value of the jakarta.faces.FACELETS_REFRESH_PERIOD context parameter was not found~~
- testPushWebsocket
  -   Expected to find 'Called onopen listener' in response, but response was: JSF 2.3 WebSocket test JSF 2.3 WebSocket - Test message pushed from server to client Click here to send message 
- testOpenAndCloseWebsocket
  - null 
  
Errors ( "syntax error"):
- JSF23CDIGeneralTests.java
  - testInjectableELImplicitObjects
  - testFacesConverterBeanInjection
  - testFacesValidatorBeanInjection
  - testFacesBehaviorBeanInjection
- JSF23ExternalContextStartupShutdownTests.java
  - testExternalContextGetRealPath_Startup_Shutdown -> https://github.com/OpenLiberty/open-liberty/pull/24549
- JSF23CommandScriptTests.java
  - testCommandScriptAutorunDefaultExecute
  - testCommandScriptActionListener
  - testCommandScriptActionListenerAttr
  - testCommandScriptAutorun
  - testCommandScriptParam
  - testCommandScriptButton
- JSF23EvalScriptsTests.java
    - testEvalScriptsSimple
    - testEvalScriptsList
    - testEvalScriptsFunction
    - testEvalScriptsMultiField
- JSF23SpecIssueTests.java
  - testSpecIssue790Test2
- JSF23SelectOneRadioGroupTests.java
  -  testSelectOneRadioGroup_AjaxRequest

## io.openliberty.org.apache.myfaces.4.0_fat

- AjaxRenderExecuteThisTest
  - testAjaxRender
  - testAjaxExecuteThis
  - testAjaxRenderThis
- AnnotationLiteralsTest
  - testFlowMap -> enabled here: https://github.com/OpenLiberty/open-liberty/pull/24551/files
- MultipleInputFileTest
  - testNoMultiple_WithAjax_SingleFile
  - testNoMultiple_WithAjax_MultipleFiles
  - testWithMultiple_WithAjax_SingleFile
  - testWithMultiple_WithAjax_MultipleFiles
- ClientWindowScopedTest
  - testClientWindowReuseInFlow -> https://github.com/OpenLiberty/open-liberty/pull/24574

### PR DESCRIPTION
**Pull request by tssmith04**
fixes Ajax tests in #24387 : 
- testAjaxRender
- testAjaxExecuteThis
- testAjaxRenderThis

### CODE REVIEW

**Comment by tssmith04** [comment]
#libby

**Comment by tssmith04** [comment]
#build

**Comment by tssmith04** [comment]
#build

**Review by pnicolucci — APPROVED** [review]
This looks good! Would be good to have @volosied  take a quick look as well. Thanks!

**Review by volosied — APPROVED** [review]

**Pull request merged**
