### PR TITLE
Update build-text.xml for com.ibm.ws.kernel.feature_fat

### PR DESCRIPTION
**Pull request by garretmoon**

### CODE REVIEW

**Comment by andymc12** [comment]
#build

**Comment by garretmoon** [comment]
There are two build I requested for this change: 
https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_E5a0MJWrEeiA46HHn3eUcA&tab=com.ibm.team.build.web.ui.internal.editors.result.properties.PropertiesProvider

https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_BcDeMJXnEeiA46HHn3eUcA

The failures in test doesn't related to my change.

**Comment by garretmoon** [comment]
#build

**Comment by tevans78** [comment]
Please read the bit at the top which starts `ATTENTION, READ THIS: Updated 4/11/2018 - Read and understand this completely, then delete this entire template.`

**Comment by garretmoon** [comment]
#build

**Comment by garretmoon** [comment]
#build

**Comment by garretmoon** [comment]
#build

**Pull request merged**
