### PR TITLE
Issue #19455: Store to local authentication cache when unable to stor…

### LINKED ISSUE #19455: SEC 380: Support local cache backup for JCache authentication cache
When using authentication cache, the JCache should support using the existing local cache when objects can not be serialized. This will prevent a drop in performance for object instances that cannot be serialized and stored in the JCache.

### PR DESCRIPTION
**Pull request by jvanhill**
…e to JCache.

fixes #19455

### CODE REVIEW

**Comment by jvanhill** [comment]
#build

**Review by ryanesch — APPROVED** [review]

**Comment by jvanhill** [comment]
#build
#libby

**Comment by jvanhill** [comment]
#build

**Comment by jvanhill** [comment]
Abandoned the build as it was built on top of a PR in integration that was reverted.

**Comment by jvanhill** [comment]
#libby
#build

**Pull request merged**
