### PR TITLE
issue warning message when it is determined security not present

### PR DESCRIPTION
**Pull request by ajm01**

### CODE REVIEW

**Comment by ajm01** [comment]
#build

**Comment by scottkurz** [comment]
This build had a relevant build failure that I'm not familiar with.  More like the compile/package stage than test, I mean, and related to batch.

**Comment by scottkurz** [comment]
I recreated the same problem locally:

* What went wrong:
Execution failed for task ':com.ibm.jbatch.container:compileJava'.
> java.lang.RuntimeException: com.sun.tools.javac.code.Symbol$CompletionFailure: class file for com.ibm.ws.logging.internal.TraceSpecification not found

by doing: `./gradlew com.ibm.jbatch.container:assemble`

**Comment by ajm01** [comment]
#build

**Pull request merged**
