### PR TITLE
Issue #27775: Upgrade commons compress to 1.26

### LINKED ISSUE #27775: Upgrade org.apache.commons.compress to 1.26
Need to upgrade commons.compress from the current version to the latest version 1.26.

### PR DESCRIPTION
**Pull request by hlhoots**
#build 

fixes #27775

### CODE REVIEW

**Comment by idlewis** [comment]
I've been looking at this from a JMX archive expander POV.
It looks as though compress 1.26 has introduced a dependency on commons-io. I've been playing around in pr https://github.com/OpenLiberty/open-liberty/pull/27720
Although I haven't got very far as my build env is very out of date, and causing me issues.

**Comment by hlhoots** [comment]
#build

**Comment by hlhoots** [comment]
#build

**Comment by hlhoots** [comment]
#build

**Comment by hlhoots** [comment]
#build

**Review by cbridgha — DISMISSED** [review]
Looks good

**Comment by hlhoots** [comment]
errors and timeouts. rebuild for hopeful clarity.

#build

**Comment by hlhoots** [comment]
#build

**Comment by hlhoots** [comment]
Added another missing commons-io class.

#build

**Comment by hlhoots** [comment]
#build

**Comment by hlhoots** [comment]
#build

**Comment by hlhoots** [comment]
#build 

fix for testcontainers

**Comment by hlhoots** [comment]
#build

**Comment by hlhoots** [comment]
The latest builds had some errors, but nothing  seems to be related to the commons-compress upgrade.  A majority of the failures were in UI related buckets with `java.net.ConnectException: 2024-03-14-11:15:45:087 Connection` refused failures.

**Review by cbridgha — DISMISSED** [review]
Looks good

**Comment by hlhoots** [comment]
#build

**Comment by hlhoots** [comment]
#build 

The commons.io upgrade seems to now return a NoSuchFileException instead of the previous FileNotFoundException for the FileUtils.readFileToString(file, "UTF-8") method called in FilePersistenceProvider.java.  Thus updated 2 com.ibm.ws.ui product files to handle that accordingly based on talks with ui team.

**Comment by hlhoots** [comment]
RTC build had an failure related to the changes in com.ibm.ws.ui as it tried to run a FAT bucket called com.ibm.ws.ui_fat which doesnt exist.  The cog build had 4 buckets that had errors, however there were corresponding existing defects for those errors.  Should be good to merge after review.

**Review by jimblye — APPROVED** [review]

**Review by tbitonti — APPROVED** [review]

**Review by aknguyen7 — APPROVED** [review]
I reviewed the changes in `FilePersistenceProvider.java` and `PlainTextLoaderService.java` , they LGTM

**Comment by hlhoots** [comment]
#libby

**Pull request merged**
