### PR TITLE
refactor: convert TrmMessageType to enum

### PR DESCRIPTION
**Pull request by ngmr**
- [x] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [x] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [x] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

### CODE REVIEW

**Comment by ngmr** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.messaging.open_31_fat,com.ibm.ws.messaging.open_clientcontainer_fat,com.ibm.ws.messaging.open_comms_fat,com.ibm.ws.messaging.open_fat,com.ibm.ws.messaging.open_jms20AutoCloseable_fat,com.ibm.ws.messaging.open_jms20context_fat,com.ibm.ws.messaging.open_jms20contextSecurity2_fat,com.ibm.ws.messaging.open_jms20contextSecurity_fat,com.ibm.ws.messaging.open_jms20deliverydelay_fat,com.ibm.ws.messaging.open_jms20_fat,com.ibm.ws.messaging.open_jms20security_fat,com.ibm.ws.microprofile.reactive.messaging_fat,io.openliberty.microprofile.reactive.messaging.internal_fat

**Comment by contbld** [comment]
Your personal pipeline request is at https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=9336076e-9b9c-4df1-b82a-3129d38093a4

Target locations of links might be accessible only to IBM employees.

**Comment by contbld** [comment]
https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=9336076e-9b9c-4df1-b82a-3129d38093a4 has errors/failures.

**Comment by contbld** [comment]
<h3>Code analysis and actions</h3>
DO NOT DELETE THIS COMMENT.

- 1 product code files were changed.

**Comment by ngmr** [comment]
!build
spawn.fullfat.buckets=com.ibm.ws.messaging.open_31_fat,com.ibm.ws.messaging.open_clientcontainer_fat,com.ibm.ws.messaging.open_comms_fat,com.ibm.ws.messaging.open_fat,com.ibm.ws.messaging.open_jms20AutoCloseable_fat,com.ibm.ws.messaging.open_jms20context_fat,com.ibm.ws.messaging.open_jms20contextSecurity2_fat,com.ibm.ws.messaging.open_jms20contextSecurity_fat,com.ibm.ws.messaging.open_jms20deliverydelay_fat,com.ibm.ws.messaging.open_jms20_fat,com.ibm.ws.messaging.open_jms20security_fat,com.ibm.ws.microprofile.reactive.messaging_fat,io.openliberty.microprofile.reactive.messaging.internal_fat

**Comment by contbld** [comment]
Your personal pipeline request is at https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=c8b0152d-905d-4da9-aa9e-a6d0f9980c30

Target locations of links might be accessible only to IBM employees.

**Comment by contbld** [comment]
Your personal pipeline request is at https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=6f32112c-fa5b-4450-b3ea-db2b699683d5

Target locations of links might be accessible only to IBM employees.

**Comment by contbld** [comment]
<h3>Code analysis and actions</h3>
DO NOT DELETE THIS COMMENT.

- 3 product code files were changed.

**Comment by contbld** [comment]
<h3>Code analysis and actions</h3>
DO NOT DELETE THIS COMMENT.

- 3 product code files were changed.

**Comment by contbld** [comment]
https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=6f32112c-fa5b-4450-b3ea-db2b699683d5 has errors/failures.

**Review by sakerl — APPROVED** [review]

**Pull request merged**
