### PR TITLE
Invoke Security web collaborator within the right CDI scopes

### PR DESCRIPTION
**Pull request by teddyjtorres**
For issue #1868

### CODE REVIEW

**Comment by teddyjtorres** [comment]
#build

**Comment by teddyjtorres** [comment]
#build

**Comment by teddyjtorres** [comment]
#build

**Comment by pnicolucci** [comment]
I also think you should run the following test buckets in full mode:

spawn.fullfat.buckets=com.ibm.ws.webcontainer.servlet.4.0_fat,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0.lWAS,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration31

Of course any security tests you feel should be run as well.

**Comment by teddyjtorres** [comment]
#build

**Comment by teddyjtorres** [comment]
Hi @pnicolucci,
The latest commit checks for appSecurity-3.0 also.  We need to invoke postInvokeForSecureResponse even if CDI is not needed because JASPIC processing is done there for the response.  We just needed to split it into postInvokeForSecureResponse and postInvoke so that it could be done before the notification of the SRLs if CDI was needed.

**Comment by teddyjtorres** [comment]
Before moving on with this fix, a new private feature in open-liberty that includes the spi and its javadoc is needed to decouple the dependency that servlet-3.0 in closed liberty has to those artifacts.  Then, the servlet-3.0 feature in closed liberty will need to be updated to use that private feature.  Finally, the com.ibm.websphere.appserver.spi.servlet bundle version can be safely updated in open-liberty as in being done in this pull request.

**Comment by teddyjtorres** [comment]
#build

**Comment by teddyjtorres** [comment]
The failure in testSecurityContext_hasAccessToWebResource_nullMethods_custom appears intermittent.  The same bucket was run twice and the same test passed the first time,

com.ibm.ws.security.javaeesec_fat FAT tests | 168 | 0 | 0
-- | -- | -- | --
...
testSecurityContext_hasAccessToWebResource_nullMethods_custom | 1 | 0 | 0
-- | -- | -- | --

**Comment by pnicolucci** [comment]
Changes look good sorry for the delayed review. Thanks!

**Pull request merged**
