### PR TITLE
GA autoCloseConnections and enable by default

### LINKED ISSUE #15158: Beta and later GA the HandleList function
For Beta and/or GA of HandleList
- [x] remove dependency on noShip feature from
  /com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.emptyHandleListContext-1.0.feature
- [x] remove usage of noShip feature from
  /com.ibm.ws.concurrent_fat_db/publish/servers/concurrent_fat_db/server.xml
- [x] metatype
   autoCloseConnections switch from internal --> beta --> ga
   autoCloseConnections specify default value (upon ga, not beta)
- [x] ConnectionManagerServiceImpl
   interpret null autoCloseConnections (possible for DataSourceDefintion/ConnectionFactoryDefinition) as default value
- [x] check test buckets for TODO comments that might have been missed
   /com.ibm.ws.jca_fat
   /com.ibm.ws.jca_fat_derbyra
   /com.ibm.ws.jdbc_fat_loadfromapp
   /com.ibm.ws.jdbc_fat_v43
   /com.ibm.ws.concurrent_fat_db

### PR DESCRIPTION
**Pull request by njr-11**
fixes #15158 

This pull includes the approved behavior change of autoCloseConnections from false to true, along with GA of this configuration attribute.

### CODE REVIEW

**Comment by njr-11** [comment]
#build

**Comment by njr-11** [comment]
#run-libby-bot

**Comment by njr-11** [comment]
The previous build uncovered a breaking change due to a bug in the WMQ resource adapter. That was worked around in a separate pull which has been merged now.
The current pull is now rebased onto latest, and retrying the build:
#build
#run-libby-bot

**Comment by njr-11** [comment]
#build

**Review by tevans78 — APPROVED** [review]

**Pull request merged**
