### PR TITLE
Disable Logstash Collector tests for z/OS machines

### LINKED ISSUE #17137: Test Failure: com.ibm.ws.logstash.collector.tests.LogstashSSLTest.testLogstashDynamicDisableFeature
RTC 283700

```
testLogstashDynamicDisableFeature:junit.framework.AssertionFailedError: 2021-01-18-22:39:54:241 [Unexpected FFDC reporting com.ibm.java.diagnostics.healthcenter.api.HealthCenterException was found (count = 1): /WebSphere/Misc/jazz_build/jbe_zrock111/jazz/buildsystem/buildengine/eclipse/build/dev/image/output/wlp/usr/servers/LogstashServer/logs/ffdc/ffdc_21.01.18_22.35.32.0.log
>------Start of DE processing------ = [1/18/21 22:35:32:680 GMT]
>Exception = com.ibm.java.diagnostics.healthcenter.api.HealthCenterException
>Source = com.ibm.ws.health.center.classloader.HCClassLoader
>probeid> at com.ibm.ws.health.center.classloader.HCClassLoader.activate(HCClassLoader.java:165)
> at org.apache.felix.scr.impl.inject.methods.BaseMethod.invokeMethod(BaseMethod.java:244)
> at org.apache.felix.scr.impl.inject.methods.BaseMethod.access$500(BaseMethod.java:41)
> at org.apache.felix.scr.impl.inject.methods.BaseMethod$Resolved.invoke(BaseMethod.java:685)
> at org.apache.felix.scr.impl.inject.methods.BaseMethod.invoke(BaseMethod.java:529)
> at org.apache.felix.scr.impl.inject.methods.ActivateMethod.invoke(ActivateMethod.java:318)
> at org.apache.felix.scr.impl.inject.methods.ActivateMethod.invoke(ActivateMethod.java:308)
> at org.apache.felix.scr.impl.manager.SingleComponentManager.createImplementationObject(SingleComponentManager.java:354)
> at org.apache.felix.scr.impl.manager.SingleComponentManager.createComponent(SingleComponentManager.java:115)
> at org.apache.felix.scr.impl.manager.SingleComponentManager.getService(SingleComponentManager.java:1000)
> at org.apache.felix.scr.impl.manager.SingleComponentManager.getServiceInternal(SingleComponentManager.java:973)
> at org.apache.felix.scr.impl.manager.AbstractComponentManager.activateInternal(AbstractComponentManager.java:776)
> at org.apache.felix.scr.impl.manager.AbstractComponentManager.enableInternal(AbstractComponentManager.java:674)
> at org.apache.felix.scr.impl.manager.AbstractComponentManager.enable(AbstractComponentManager.java:437)
> at org.apache.felix.scr.impl.manager.ConfigurableComponentHolder.enableComponents(ConfigurableComponentHolder.java:667)
> at org.apache.felix.scr.impl.BundleComponentActivator.initialEnable(BundleComponentActivator.java:305)
> at org.apache.felix.scr.impl.Activator.loadComponents(Activator.java:554)
> at org.apache.felix.scr.impl.Activator.access$200(Activator.java:70)
> at org.apache.felix.scr.impl.Activator$ScrExtension.start(Activator.java:421)
> at org.apache.felix.scr.impl.AbstractExtender.createExtension(AbstractExtender.java:196)
> at org.apache.felix.scr.impl.AbstractExtender.modifiedBundle(AbstractExtender.java:169)
> at org.apache.felix.scr.impl.AbstractExtender.modifiedBundle(AbstractExtender.java:49)
> at org.osgi.util.tracker.BundleTracker$Tracked.customizerModified(BundleTracker.java:488)
> at org.osgi.util.tracker.BundleTracker$Tracked.customizerModified(BundleTracker.java:1)
> at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:232)
> at org.osgi.util.tracker.BundleTracker$Tracked.bundleChanged(BundleTracker.java:450)
> at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:973)
> at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
> at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151)
> at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEventPrivileged(EquinoxEventPublisher.java:235)
> at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:141)
> at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:133)
> at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor.publishModuleEvent(EquinoxContainerAdaptor.java:217)
> at org.eclipse.osgi.container.Module.publishEvent(Module.java:498)
> at org.eclipse.osgi.container.Module.start(Module.java:485)
> at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:1844)
> at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$1.execute(ModuleContainer.java:1832)
> at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1837)
> at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1781)
> at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1742)
> at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1664)
> at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
> at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
> at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)
]
at componenttest.custom.junit.runner.FATRunner.blowup(FATRunner.java:300)
at componenttest.custom.junit.runner.FATRunner.access$600(FATRunner.java:66)
at componenttest.custom.junit.runner.FATRunner$1.evaluate(FATRunner.java:250)
at org.testcontainers.containers.FailureDetectingExternalResource$1.evaluate(FailureDetectingExternalResource.java:30)
at componenttest.custom.junit.runner.FATRunner$2.evaluate(FATRunner.java:318)
at componenttest.custom.junit.runner.FATRunner.run(FATRunner.java:171) = 187
>Stack Dump = com.ibm.java.diagnostics.healthcenter.api.HealthCenterException: Unable to connect to in process agent. Check the agent is loaded and running.
> at com.ibm.java.diagnostics.healthcenter.api.factory.HealthCenterFactory.localConnect(Unknown Source)
> at com.ibm.java.diagnostics.healthcenter.api.factory.HealthCenterFactory.connect(Unknown Source)
> at com.ibm.ws.health.center.proxy.HCConnectorImpl.connect(HCConnectorImpl.java:53)
```

### PR DESCRIPTION
**Pull request by adriankalafut**
Fixes [#17137](https://github.com/OpenLiberty/open-liberty/issues/17137).

### CODE REVIEW

**Comment by adriankalafut** [comment]
#build

**Comment by adriankalafut** [comment]
#build

**Comment by adriankalafut** [comment]
z/OS build: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_yVfpYN2rEeuED-bEVHmljA&tab=com.ibm.team.build.web.ui.internal.editors.result.overview.OverviewPage

**Comment by adriankalafut** [comment]
#build

**Comment by adriankalafut** [comment]
#build

**Comment by adriankalafut** [comment]
#build

**Review by tonyreigns — APPROVED** [review]
LGTM

**Comment by adriankalafut** [comment]
#run-libby-bot

**Pull request merged**
