### PR TITLE
Issue 16000: Social login: Add session affinity config for oidcLogin

### LINKED ISSUE #16000: OIDC in the socal login feature socialLogin-1.0 does maintain session affinity TS004966274
**Describe the bug**
With the social login feature, socialLogin-1.0, the OIDC function, oidcLogin, cannot maintain session affinity.  It never invokes HttpServletRequest.getSession() .

The createSession attribute from the OIDC RP needs to be exposed through to the oidcLogin config.

### PR DESCRIPTION
**Pull request by ayoho**
Fixes #16000

### CODE REVIEW

**Comment by ayoho** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.security.social_fat,com.ibm.ws.security.social_fat.delegated,com.ibm.ws.security.social_fat.LibertyOP,com.ibm.ws.security.social_fat.multiProvider

**Comment by skasund** [comment]
L2 message review not required

**Review by ManasiGandhi — APPROVED** [review]
Looks good to me.

**Comment by ayoho** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.security.social_fat,com.ibm.ws.security.social_fat.delegated,com.ibm.ws.security.social_fat.LibertyOP,com.ibm.ws.security.social_fat.multiProvider

**Comment by ayoho** [comment]
#libby
#build
#spawn.fullfat.buckets=com.ibm.ws.security.social_fat,com.ibm.ws.security.social_fat.delegated,com.ibm.ws.security.social_fat.LibertyOP,com.ibm.ws.security.social_fat.multiProvider

**Comment by ayoho** [comment]
#libby
#build
#spawn.fullfat.buckets=com.ibm.ws.security.social_fat,com.ibm.ws.security.social_fat.delegated,com.ibm.ws.security.social_fat.LibertyOP,com.ibm.ws.security.social_fat.multiProvider

**Review by teddyjtorres — APPROVED** [review]

**Pull request merged**
