### PR TITLE
Run jax integration tests without Concurrency-3.0 feature

### LINKED ISSUE #24225: Test mpTelemetry with/without concurrent-3.0
The async functionality in restfulWS-3.1 works slightly differently when concurrent-3.0 is enabled and this has caused bugs.

Ensure we are testing both configurations, particularly JAX-RS and MP Rest Client async functionality.

### PR DESCRIPTION
**Pull request by benjamin-confino**
fixes #24225

### CODE REVIEW

**Comment by benjamin-confino** [comment]
JAX-RS and MP Rest Client async functionality are both tested in JaxRsEndpoints.java

**Comment by benjamin-confino** [comment]
#build

**Review by Yas-Franco — APPROVED** [review]
Looks good!

**Comment by benjamin-confino** [comment]
#build

**Comment by benjamin-confino** [comment]
#libby

**Comment by benjamin-confino** [comment]
#run-libby-bot

**Pull request merged**
