### PR TITLE
Add new VisibilityTest for tolerated public / protected features

### LINKED ISSUE #15061: Enabling Openapi-3.1 and Reactive Messaging 1.0 fails
**Describe the bug**
Hello, I'm trying since few days to enable both features mentionned in the title together. However, it keeps failing on a feature conflict.

**Steps to Reproduce**
Enable the following features in a freshly created app server:

```xml
<feature>jpa-2.2</feature>
        <feature>jsonb-1.0</feature>
        <feature>cdi-2.0</feature>
        <feature>jaxrs-2.1</feature>
        <feature>mpconfig-1.3</feature>
        <feature>openapi-3.1</feature>
        <feature>mpReactiveMessaging-1.0</feature>
```

**Expected behavior**
Both features should be loadable at the same time.

**Diagnostic information:**
 - OpenLiberty Version: 20.0.0.11
 - Java Version: Java 14
 - server.xml configuration (WITHOUT sensitive information like passwords)
```xml
<server description="ZeroAuthDB">
    <featureManager>
        <feature>jpa-2.2</feature>
        <feature>jsonb-1.0</feature>
        <feature>cdi-2.0</feature>
        <feature>jaxrs-2.1</feature>
        <feature>mpconfig-1.3</feature>
        <feature>openapi-3.1</feature>
        <feature>mpReactiveMessaging-1.0</feature>
    </featureManager>

    <variable name="default.http.port" defaultValue="8080"/>
    <variable name="version.mariadb" defaultValue="2.7.0"/>
    <variable name="mariadb.lib" defaultValue="${shared.resource.dir}/mariadb-java-client-${version.mariadb}.jar"/>

    <httpEndpoint httpPort="${default.http.port}" id="defaultHttpEndpoint" hosts="*" />

    <jpa defaultJtaDataSourceJndiName="jdbc/<sensitive info>" entityManagerPoolCapacity="5"/>
    <library id="MARIADBLIB" name="Library for Maria DB">
        <file name="${mariadb.lib}"/>
    </library>
    <dataSource id="AuthDBDS" jndiName="jdbc/AuthDBDS">
    	<jdbcDriver javax.sql.DataSource="org.mariadb.jdbc.Driver" libraryRef="MARIADBLIB"/>
<!-- sensitive info here -->
    </dataSource>
    <webAppSecurity singleSignonEnabled="false"/>
    <basicRegistry id="basic" realm="dummyRealm">
    </basicRegistry>
</server>
```

### PR DESCRIPTION
**Pull request by jhanders34**
- Add test to make sure that if a feature depends on another feature and that dependent feature has tolerated public or protected features, that the depending feature references that tolerated feature.
- Update features that were found to be missing features for tolerated public / protected features in their dependent features.
- A new commented out test is also added that will be enabled later with additional feature changes for the redundancy it finds with dependent features.

fixes #15061

### CODE REVIEW

**Comment by jhanders34** [comment]
#build

**Comment by jhanders34** [comment]
@fmhwong can you look at the mpOpenTracing-1.2 feature change?  The change is the current behavior that only mpConfig-1.3 will be used with mpOpenTracing-1.2.  openTracing-1.2 has mpConfig-1.3 tolerates 1.4.  Not sure why it tolerates 1.4, but I don't think we can change that.  It is accurate for mpOpenTracing-1.2 to only do mpConfig-1.3 I believe since that is what goes with mpOpenTracing-1.2 for that MP level.

@Azquelt can you look at the openapi-3.1 feature change?  This is a change in behavior, but I think it is correct because I don't see why openapi would limit to mpConfig-1.2 when mpOpenAPI 1.0 that it depends on supports all 3.  I think this was just a miss when updating mpOpenAPI 1.0 to add mpConfig 1.3 and 1.4 support and really the reason that this new test exists.  If you agree with the change I think I can update this PR to also say that it fixes issue #15061.

@tevans78 and @cbridgha  please review this PR generally.

**Comment by Azquelt** [comment]
@jhanders34 The older OpenAPI features are owned by @arturdzm. I can't see any reason why the change to `openapi-3.1` shouldn't be made, unless it was a deliberate choice not to support newer versions of mpConfig, but I would defer to @arturdzm on that. I would also look to him to say whether any we should be running any tests if we support this.

**Comment by arturdzm** [comment]
It should be able to work with any version of mpConfig feature. 
It does only work currently with mpOpenAPI-1.0 because there were some API updates to MP OpenAPI spec so different bundles are loaded for those. To support that it most likely would require creating multiple bundles to be loaded in depending on which MP OpenAPI is enabled.

**Comment by jhanders34** [comment]
We are not going to expand openapi 3.1 to support mpOpenAPI level newer than 1.0.  openapi 3.1 is now stabilized.  The only issue is if mpConfig support should be expanded to match that of mpOpenAPI 1.0 and you answered that it should and was a missed change when mpOpenAPI supported new versions of mpConfig which is what I put into the PR.

**Review by fmhwong — APPROVED** [review]
LGTM

**Review by arturdzm — APPROVED** [review]
LGTM

**Pull request merged**
