### PR TITLE
Fix ejbcontainer.session.async_fat AsyncWarnTest Order Dependency

### PR DESCRIPTION
**Pull request by brideck**
Correct initial value of the state variable for the default server.xml.

### CODE REVIEW

**Comment by brideck** [comment]
fixes #13412

**Comment by brideck** [comment]
Personal build + SOE:
https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_ysUzYNtBEeqigNlDxrUK9A

**Comment by olendvcook** [comment]
Personal Build + SOE Attempt 2: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_0ls0wNvOEeqigNlDxrUK9A&tab=com.ibm.team.build.web.ui.internal.editors.result.properties.PropertiesProvider

**Comment by brideck** [comment]
Resubmitted Personal Build + SOE Full:
https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_JsR5pNuSEeqigNlDxrUK9A

**Comment by brideck** [comment]
Tests passed at 100%, merging.

**Pull request merged**
