### PR TITLE
Remove beta guard ssl cert url encoded string

### LINKED ISSUE #19420: Remove beta guard for Support new change in the SSL certificate with urlencoded string
Code changed: dev/com.ibm.ws.webcontainer/src/com/ibm/ws/webcontainer/osgi/request/IRequestImpl.java  and  dev/com.ibm.ws.webcontainer/bnd.bnd 

PR that delivered beta guard: https://github.com/OpenLiberty/open-liberty/pull/19168/files

### PR DESCRIPTION
**Pull request by pnicolucci**
fixes #19420

### CODE REVIEW

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.webcontainer.servlet.4.0_fat

**Comment by pnicolucci** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.webcontainer.servlet.4.0_fat

**Review by pmd1nh — APPROVED** [review]

**Review by tevans78 — APPROVED** [review]

**Comment by pnicolucci** [comment]
#libby

**Comment by pnicolucci** [comment]
The latest personal build has three failures that are accounted for with an existing build break defect. Personal build is good enough for validation for this pull request the tests specific to this functionality executed successfully.

**Pull request merged**
