### PR TITLE
only get primaryKeyImportDir when needed

### PR DESCRIPTION
**Pull request by Zech-Hein**
1. only get primaryKeyImportDir when needed
2. stop using configured validation keys after they have been removed from configuration. (they were still being used even after removal before).

### CODE REVIEW

**Comment by Zech-Hein** [comment]
#libby
#build
#spawn.fullfat.buckets=com.ibm.ws.security.token.ltpa_fat

**Comment by mshah0722** [comment]
#libby
#build
#spawn.fullfat.buckets=com.ibm.ws.security.token.ltpa_fat

**Comment by mshah0722** [comment]
#libby
#build
#spawn.fullfat.buckets=com.ibm.ws.security.token.ltpa_fat

**Comment by mshah0722** [comment]
#libby
#build
#spawn.fullfat.buckets=com.ibm.ws.security.token.ltpa_fat

**Review by mshah0722 — APPROVED** [review]
LGTM!

**Pull request merged**
