### PR TITLE
Update netty dependencies from 4.1.100.Final to 4.1.109.Final

### LINKED ISSUE #28421: Bump netty dependencies to 4.1.109.Final
**Describe the bug**  
Current Netty components in Open Liberty are of the version 4.1.100.Final released in October 2023. The latest version 4.1.109.Final contains various bug fixes and improvements over the current version.

**Steps to Reproduce**  
No steps to reproduce

**Expected behavior**  
Open Liberty stays up to date with upstream fixes and improvements.

**Diagnostic information:**  
N/A

**Additional context**  
Pull in the new Netty 4.1.109 release (updating from 4.1.100) which has many bug fixes and improvements: https://netty.io/news/2024/04/15/4-1-109-Final.html

### PR DESCRIPTION
**Pull request by isaacrivriv**
fixes #28421

### CODE REVIEW

**Comment by isaacrivriv** [comment]
#build

**Comment by isaacrivriv** [comment]
#libby

**Comment by isaacrivriv** [comment]
#build

**Review by pnicolucci — CHANGES_REQUESTED** [review]
Please update the copyright date ranges in the bnd.bnds.

**Review by pnicolucci — APPROVED** [review]

**Comment by pnicolucci** [comment]
#libby

**Review by mrsaldana — APPROVED** [review]
LGTM

**Comment by isaacrivriv** [comment]
Latest changes were updating copyrights and before that the build came back successful. Should be okay to merge in

**Pull request merged**
