### PR TITLE
Cleanup faces30and40 bnd

### LINKED ISSUE #22212: Faces 3.0 and Faces 4.0: buildpath in bnd.bnd for io.openliberty.jakarta.faces.3.0/4.0 needs to be cleaned up as much of it is not necessary

### PR DESCRIPTION
**Pull request by pnicolucci**
fixes #22212

### CODE REVIEW

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
#build

**Review by isaacrivriv — DISMISSED** [review]

**Comment by pnicolucci** [comment]
#libby #build

**Review by volosied — DISMISSED** [review]
Looks good.  I think I would prefer to comment them out  (if possible) in case we make overlays and need to hunt for the right bundles.

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Review by volosied — APPROVED** [review]
LGTM

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#libby

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#libby

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#libby

**Pull request merged**
