### PR TITLE
Obtain EJB module ComponentMetaData from MetaDataService

### PR DESCRIPTION
**Pull request by tkburroughs**
- update EJB runtime to provide a generic CMD for an EJB module
- remove EJB module tracker from Data and obtain EJB module CMD from MetaDataService

- [x] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [x] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [x] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

for #24858

### CODE REVIEW

**Comment by tkburroughs** [comment]
#build

**Review by njr-11 — APPROVED** [review]

**Comment by wraschke** [comment]
#build

**Comment by tkburroughs** [comment]
#libby

**Comment by tkburroughs** [comment]
All failures associated with known issues; ready to merge.

**Pull request merged**
