### PR TITLE
GRPC: recognise appSecurity-5.0

### PR DESCRIPTION
**Pull request by Azquelt**
Add appSecurity-5.0 to grpc's list of security features

Noted this while working on #20947

### CODE REVIEW

**Review by hutchig — APPROVED** [review]
LGTM

**Review by volosied — APPROVED** [review]
We really need a better solution here, but, this looks good for now.

Thanks!

**Comment by Azquelt** [comment]
#build

**Comment by jhanders34** [comment]
> We really need a better solution here, but, this looks good for now.
> 
> Thanks!

Usually it would be an auto feature and possibly registering a service or something like that.  Hopefully a solution can be made that can be similarly used for the use case in https://github.com/OpenLiberty/open-liberty/pull/20947.

**Pull request merged**
