### PR TITLE
fix possible out of bounds in WC WebApp

### LINKED ISSUE #28652: FFDC for index out of bounds in web container, WebApp.handleRequest()
**Describe the bug**  
An Async Servlet test has hit this error (only once so far).
Stack Dump = java.lang.StringIndexOutOfBoundsException: Range [13, 1) out of bounds for length 1
	at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:55)
	at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:52)
	at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:213)
	at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:210)
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:98)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckFromToIndex(Preconditions.java:112)
	at java.base/jdk.internal.util.Preconditions.checkFromToIndex(Preconditions.java:349)
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4861)
	at java.base/java.lang.String.substring(String.java:2830)
	at java.base/java.lang.String.substring(String.java:2803)
	at com.ibm.ws.webcontainer.webapp.WebApp.handleRequest(WebApp.java:4878)
	at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.handleRequest(DynamicVirtualHost.java:328)
	at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:1047)
	at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.run(DynamicVirtualHost.java:293)
...

**Steps to Reproduce**  
Async Servlet test suite has hit this once.

**Expected behavior**  
No FFDC errors in Async Servlet tests.

**Diagnostic information:**  
 - OpenLiberty Version: 24.0.0.6
 - Affected feature(s) servlet-3.1
 - Java Version: 21

### PR DESCRIPTION
**Pull request by epj**
fixes #28652

### CODE REVIEW

**Comment by epj** [comment]
#build

**Comment by epj** [comment]
#build
#spawn.fullfat.buckets=io.openliberty.webcontainer.servlet.6.1.internal_fat,io.openliberty.webcontainer.servlet.6.0.internal_fat,com.ibm.ws.webcontainer.servlet.6.1_fat_toleration.lWAS,com.ibm.ws.webcontainer.servlet.6.0_fat_toleration.lWAS,com.ibm.ws.webcontainer_fat,com.ibm.ws.webcontainer.servlet.3.1_fat,com.ibm.ws.webcontainer.servlet.3.1_fat.2,com.ibm.ws.webcontainer.servlet.4.0_fat,com.ibm.ws.webcontainer_fat_part2,com.ibm.ws.webcontainer_fat_servlet31toleration,com.ibm.ws.webcontainer_fat_servlet31toleration_part2,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0_part2,com.ibm.ws.webcontainer_fat_lWAS,com.ibm.ws.webcontainer_fat_servlet31_webcontainerlWAS,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0.lWAS

**Comment by epj** [comment]
#libby

**Review by volosied — APPROVED** [review]
Looks reasonable to me.

**Pull request merged**
