### PR TITLE
Reduce BC jars size for install

### PR DESCRIPTION
**Pull request by jjiwooLim**
Reduce BC v.1.75 libs 
Reduced from 9.2MB to 3.7MB

### CODE REVIEW

**Comment by jjiwooLim** [comment]
#build

**Comment by jjiwooLim** [comment]
Package Verification Ignore files merged to release branch #build

**Comment by jjiwooLim** [comment]
No Package Verification failure in the latest build.

**Review by bensonlatibm — APPROVED** [review]
LGTM!

**Pull request merged**
