### PR TITLE
Reduce frequency of scheduled test pipelines and revert unittest step

### PR DESCRIPTION
**Pull request by fritze2**
- Lowering frequency of scheduled pipelines from daily to weekly.
- Revert parallel unittest step until we fix a defect with the new compile step target.

### CODE REVIEW

**Comment by fritze2** [comment]
#build

**Comment by fritze2** [comment]
#pbbeta

**Review by wraschke — APPROVED** [review]

**Comment by wraschke** [comment]
The conventional RTC build kicked off from pound sign build is still running (groan) but that should not be affected by this PR's change.

The two beta pipelines have the appropriate number of tests: 88988 in one and 90072 in the other. The separate unittest is indeed gone. (Two pipelines requested for one comment is known problem that I've [raised in channel](https://ibm-cloud.slack.com/archives/C02488C45B5/p1678738602121619); new issue forthcoming from me.

So, approved.

**Comment by fritze2** [comment]
#libby

**Comment by fritze2** [comment]
#libby-bot

**Pull request merged**
