### PR TITLE
Jaxws22 feature update

### PR DESCRIPTION
**Pull request by WhiteCat22**
This is it. The big one. Deleting the existing CXF 2.6.2 projects and replacing them with the 2.6 projects that we've been working on to bring the source code into OpenLiberty. Also updating all references to the old jars to point at the new projects.

### CODE REVIEW

**Comment by WhiteCat22** [comment]
#build

**Comment by WhiteCat22** [comment]
#build

**Comment by andrea-pichler** [comment]
Requested message review completed by L2

**Comment by WhiteCat22** [comment]
thanks @dmuelle 

#build

**Comment by WhiteCat22** [comment]
```com.ibm.ws.jaxws22.fat.dispatch.SimpleDispatchTests``` in ```com.ibm.ws.jaxws.2.2_fat``` are failing with some sort of infinite loop with log files reaching > 1.5 million lines.

these tests are a copy of ```CXFNoWssecTests``` in ```com.ibm.ws.wssecurity_fat.cxf``` which are also failing

**Comment by WhiteCat22** [comment]
```CWWKZ0002E: An exception occurred while starting the application simpleservice. The exception message was: com.ibm.ws.container.service.metadata.MetaDataException: java.lang.IllegalArgumentException: The headRegion must not be null.```

**Comment by WhiteCat22** [comment]
#build

**Comment by WhiteCat22** [comment]
addressed the last failing test, running a new build with the ```com.ibm.ws.jaxws.cdi_fat,com.ibm.ws.jaxws.clientcontainer_fat_IWAS,com.ibm.ws.jaxws.ejb_fat_lWAS,com.ibm.ws.jaxws.security_fat_lWAS,com.ibm.ws.jaxws.wab_fat,com.ibm.ws.jaxws.webcontainer_fat_lWAS,com.ibm.ws.jaxws.wsat_fat,com.ibm.ws.wssecurity_fat.cxf,com.ibm.ws.wssecurity_fat.saml,com.ibm.ws.wssecurity_fat.saml.2,com.ibm.ws.wssecurity_fat.twas``` fat buckets

https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_OQ_PoObZEemM--BPo4KzaA

**Comment by WhiteCat22** [comment]
build with updated test buckets

https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_M_aD4OkGEemoq4hjSBupzg

**Comment by WhiteCat22** [comment]
https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_uB9IoOnTEemoq4hjSBupzg

**Comment by WhiteCat22** [comment]
final #build, this should be good to merge, but just double checking

**Comment by WhiteCat22** [comment]
green build

**Pull request merged**
