### PR TITLE
re-introduce and add test for new swidtag

### PR DESCRIPTION
**Pull request by bensonlatibm**
This PR adds in an swidtag to allow ILMT to recognize Open Liberty.
This PR also adds in a test case to check for the tag's existence in Open Liberty.

### CODE REVIEW

**Comment by bensonlatibm** [comment]
#build

**Comment by bensonlatibm** [comment]
#build

**Comment by bensonlatibm** [comment]
#build

**Comment by bensonlatibm** [comment]
#build

**Comment by bensonlatibm** [comment]
#build

**Comment by bensonlatibm** [comment]
#build

**Comment by bensonlatibm** [comment]
The last PB had failures in: 	
io.openliberty.microprofile.rest.client.2.0.internal_fat_tck FAT tests
which are unrelated to this PR.

**Comment by bensonlatibm** [comment]
#run-libby-bot

**Comment by bensonlatibm** [comment]
#build

**Comment by bensonlatibm** [comment]
#run-libby-bot

**Review by tiwarim — APPROVED** [review]
Change looks good!

**Comment by bensonlatibm** [comment]
tested by Running PB, and PB building os.native packages
verified checktags test ran
manually verified openliberty kernel zip only contained open liberty tags
manually verified wlp kernel zip only contained websphere liberty tags

**Pull request merged**
