### PR TITLE
Re-introduce "Fix errors during Database Rotation"

### LINKED ISSUE #28584: Re-introduce change reverted from 28416
Re-introduce change reverted from https://github.com/OpenLiberty/open-liberty/pull/28416

### PR DESCRIPTION
**Pull request by KyleAure**
Fixes #28584
Reintroduces #28416

### CODE REVIEW

**Comment by KyleAure** [comment]
#libby - check headers
#build
#spawn.fullfat.buckets=com.ibm.ws.jpa.tests.beanvalidation_jpa_2.0_fat,com.ibm.ws.jpa.tests.beanvalidation_jpa_2.1_fat,com.ibm.ws.jpa.tests.beanvalidation_jpa_2.2_fat,com.ibm.ws.jpa.tests.beanvalidation_jpa_3.0_fat,com.ibm.ws.jpa.tests.beanvalidation_jpa_3.1_fat,com.ibm.ws.jpa.tests.beanvalidation_jpa_3.2_fat,com.ibm.ws.jpa.tests.jpaconfig_jpa_2.1_fat,com.ibm.ws.jpa.tests.jpaconfig_jpa_2.2_fat,com.ibm.ws.jpa.tests.jpaconfig_jpa_3.0_fat,com.ibm.ws.jpa.tests.jpaconfig_jpa_3.1_fat,com.ibm.ws.jpa.tests.jpaconfig_jpa_3.2_fat

**Review by Riva-Tholoor-Philip — APPROVED** [review]

**Review by tkburroughs — APPROVED** [review]

**Comment by KyleAure** [comment]
PostgreSQL Pipeline: https://libh-proxy1.fyre.ibm.com/cognitive-dev/pipelineAnalysis.html?pipelineId=df8fbd4a-793b-4378-81a3-d474d17e9c66

Target locations of links might be accessible only to IBM employees.

**Comment by KyleAure** [comment]
RTC Build: Failed with unrelated errors in other test buckets
Pipeline: Failed during compilation, seems unrelated.
```txt
* What went wrong:
Execution failed for task ':com.ibm.websphere.appserver.features:publishFeatureResources'.
> /home/jazz_build/Build/jbe/build/open-liberty/dev/build.image/wlp/lib/com.ibm.ws.microprofile.config.1.2.cdi_1.0.90.jar (No such file or directory)
```
Looks like many of the other personal builds around this time have also failed during compilation. Perhaps due to gradle parallel builds?
PostgreSQL: Passed

**Comment by KyleAure** [comment]
Merging now that the SOE with the revert has completed successfully.

**Pull request merged**
