### PR TITLE
Issue #15092: Verify that RestEasy ReactiveClient works by enabling com.ibm.ws.jaxrs.2.1.client_fat to be transformed

### PR DESCRIPTION
**Pull request by jkoehler22**

### CODE REVIEW

**Comment by jkoehler22** [comment]
#build

**Comment by jkoehler22** [comment]
For issue https://github.com/OpenLiberty/open-liberty/issues/15092

**Comment by jkoehler22** [comment]
#build

**Review by jim-krueger — APPROVED** [review]

**Comment by jkoehler22** [comment]
#build

**Pull request merged**
