### PR TITLE
Update netty components

### LINKED ISSUE #18751: Bump netty dependencies to 4.1.68.Final
**Describe the bug**  
Current Netty components in Open Liberty are of the version `4.1.66.Final` released on July 2021. Dependabot found security issues with the netty-codec component which was fixed on the `4.1.68.Final` version release on September 2021. Currently the codebase has no security issues since the affected components of the artifact are not used in Open Liberty or its dependencies. The changes should be made to update to the latest version since version `4.1.68.Final` does contain various bug fixes and improvements over the current version.

**Steps to Reproduce**  
No steps to reproduce.

**Expected behavior**  
Open Liberty maintains up to date with security and vulnerability issues.

**Additional context**  

Pull in the new Netty 4.1.68 release (updating from 4.1.66) which has many bug fixes and improvements: https://netty.io/news/2021/09/09/4-1-68-Final.html

This issue will resolve #18714

### PR DESCRIPTION
**Pull request by isaacrivriv**
fixes #18751

### CODE REVIEW

**Comment by isaacrivriv** [comment]
#build

**Comment by isaacrivriv** [comment]
#build

**Comment by mbroz2** [comment]
https://github.com/OpenLiberty/open-liberty/pull/18714

**Review by wtlucy — APPROVED** [review]
looks good!

**Pull request merged**
