### PR TITLE
Include MP 6.1 in OL zips

### LINKED ISSUE #25643: Update OL zips to include microProfile-6.1
Update all OL packaging to include microProfile-6.1

openliberty-microProfile6-23.0.0.8-cl230820230807-0401.zip
openliberty-webProfile10-23.0.0.8-cl230820230807-0401.zip
openliberty-jakartaee10-23.0.0.8-cl230820230807-0401.zip

### PR DESCRIPTION
**Pull request by tevans78**
fixes https://github.com/OpenLiberty/open-liberty/issues/25643

### CODE REVIEW

**Comment by tevans78** [comment]
#build

**Review by Yas-Franco — DISMISSED** [review]
Telemetry parts seem good to me

**Comment by tevans78** [comment]
#build

**Comment by tevans78** [comment]
#build

**Comment by tevans78** [comment]
#build

**Review by jhanders34 — COMMENTED** [review]
I think the changes look good.  I expect you will have conflicts with the forthcoming mpTelemetry 1.1 changes so no reason to approve it since you will need to rebase and resolve conflicts when that happens likely.  The only question I had is are there any test updates that need to be made to no longer set beta in the test now that the features are GA?

**Comment by tevans78** [comment]
> I think the changes look good. I expect you will have conflicts with the forthcoming mpTelemetry 1.1 changes so no reason to approve it since you will need to rebase and resolve conflicts when that happens likely. The only question I had is are there any test updates that need to be made to no longer set beta in the test now that the features are GA?

There are some beta flags in the Telemetry buckets (including one in the 1.0 TCK which probably should not be there). However, I don't want to mess with the Telemetry buckets just yet, I'll talk to @yasmin-aumeeruddy about removing those beta flags/repeats etc

**Comment by tevans78** [comment]
#build

**Comment by tevans78** [comment]
#build

**Review by jhanders34 — APPROVED** [review]

**Review by Yas-Franco — APPROVED** [review]

**Comment by jhanders34** [comment]
#libby

**Review by cbridgha — APPROVED** [review]
looks good

**Comment by ayoho** [comment]
#libby

**Pull request merged**
