### PR TITLE
27547-RemovingFont.

### PR DESCRIPTION
**Pull request by sarinjacobsunny**
Replace font with plex.

### CODE REVIEW

**Comment by sarinjacobsunny** [comment]
#build

**Comment by sarinjacobsunny** [comment]
- Left side is with old font
- Right side is IBM plex font.

image

image

**Review by k8vance88 — APPROVED** [review]

**Comment by sarinjacobsunny** [comment]
#run-libby-bot

**Review by k8vance88 — APPROVED** [review]
LGTM

**Comment by sarinjacobsunny** [comment]
#run-libby-bot

**Pull request merged**
