### PR TITLE
grow threadpool less eagerly when system CPU info is NA

### PR DESCRIPTION
**Pull request by gjdeval**
In z-space, CPU info for the system is not available, generally. Lack of this info can lead to slightly sub-optimal Liberty threadpool sizing, by being a bit too willing to experiment with larger pool sizes, when the available throughput history does not provide clear guidance about whether growing the pool is likely to help.
This change improves behavior in that corner case by treating "system CPU not available" the same as "cpuHigh" has been handled for some time - either condition will bias the autonomics away from growing the pool based on a coinflip.

### CODE REVIEW

**Comment by gjdeval** [comment]
Equivalent behavior to this change has been tested by the CICS performance team, by testing with the cpuHigh threshold set so that the processCpu reading (available in z-space) would trigger cpuHigh behavior. That manual setting caused fewer threads to be added to the pool, leading to improved efficiency (cpu/transaction) in the CICS transaction manager test.

**Comment by gjdeval** [comment]
#run-libby-bot

**Comment by gjdeval** [comment]
#build

**Comment by jhanders34** [comment]
#build

**Pull request merged**
