### PR TITLE
Remove bad references

### PR DESCRIPTION
**Pull request by cbridgha**
Removing dependency entries that are not used - or that the test project downloads from the MC mirror repo.

This will prevent all builds from seeing the dozen or so error messages from not finding these entries.
(adding the -i flag to any gradle command will show them)

All of the removed entries are only used during test/fat - and are already downloaded using the MC mirror repo.

### CODE REVIEW

**Comment by cbridgha** [comment]
#build

**Comment by cbridgha** [comment]
#build

**Comment by cbridgha** [comment]
#build

**Review by brenthdaniel — APPROVED** [review]

**Comment by cbridgha** [comment]
#libby

**Pull request merged**
