### PR TITLE
rename io.openliberty.io.opentelemetry.internal

### LINKED ISSUE #23489: Rename the bundle which packages OpenTelemetry
`io.openliberty.io.opentelemetry.internal` should be called `io.openliberty.io.opentelemetry` because it is just a rebundling of the external OSS.

See the [naming guidelines](https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-naming-guidelines#third-party-projects--rebundles)

### PR DESCRIPTION
**Pull request by benjamin-confino**
fixes #23489

### CODE REVIEW

**Comment by benjamin-confino** [comment]
#build

**Comment by benjamin-confino** [comment]
#build

**Comment by benjamin-confino** [comment]
#build

**Review by Yas-Franco — APPROVED** [review]
Looks good!

**Comment by benjamin-confino** [comment]
#run-libby-bot

**Comment by benjamin-confino** [comment]
#libby

**Pull request merged**
