### PR TITLE
Issue7046-Migrate kernel feature FAT

### PR DESCRIPTION
**Pull request by anjumfatima90**
for issue #7046

### CODE REVIEW

**Comment by anjumfatima90** [comment]
#build

**Comment by cbridgha** [comment]
@anjumfatima90   Please fix up the copyrights to use EPL!

**Comment by anjumfatima90** [comment]
#build

**Comment by anjumfatima90** [comment]
A build with CL branch which deletes com.ibm.ws.kernel.feature_fat and the OL pull request branch
https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_X5q8oF-LEemP6vsjGLPPfg

**Comment by anjumfatima90** [comment]
https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_9ivjwGBcEemP6vsjGLPPfg

**Pull request merged**
