### PR TITLE
[18849] - limit JAXRS21ClientSSLProxyAuthTest.testTunnelThroughProxyToHTTPSEndpoint_ClientBuilder() to run on Java 11+

### PR DESCRIPTION
**Pull request by WhiteCat22**
https://github.com/OpenLiberty/open-liberty/issues/18849

### CODE REVIEW

**Review by andymc12 — APPROVED** [review]
Thanks @WhiteCat22

**Comment by WhiteCat22** [comment]
#build #run-libby-bot

**Comment by WhiteCat22** [comment]
#build

**Comment by WhiteCat22** [comment]
#build #run-libby-bot

**Comment by WhiteCat22** [comment]
been hitting an intermittent timing related bug, so disabled the https tests completely.
#build #run-libby-bot

**Comment by WhiteCat22** [comment]
Green build

**Pull request merged**
