### PR TITLE
Improve core test performance

### PR DESCRIPTION
**Pull request by jonhawkes**
#libby-build

### CODE REVIEW

**Comment by jonhawkes** [comment]
#build

**Comment by jonhawkes** [comment]
#libby

**Comment by jonhawkes** [comment]
#libby #build

**Comment by jonhawkes** [comment]
#libby #build

**Comment by jonhawkes** [comment]
#build

**Comment by jonhawkes** [comment]
#build

**Comment by jonhawkes** [comment]
#build

**Comment by jonhawkes** [comment]
#build

**Comment by jonhawkes** [comment]
#libby #build

**Comment by jonhawkes** [comment]
#libby #build

**Review by neilgsyoung — DISMISSED** [review]
Looks good

**Comment by jonhawkes** [comment]
#libby #build

**Review by neilgsyoung — APPROVED** [review]
Looks good

**Pull request merged**
