### PR TITLE
JVM Working Dir skip on non jcmd.exe environments

### PR DESCRIPTION
**Pull request by hlhoots**
#build 

#15128 related

### CODE REVIEW

**Comment by hlhoots** [comment]
Tests passed in build, but build did not complete. Rerun for sanity purposes.
#build

**Comment by hlhoots** [comment]
#build

**Comment by hlhoots** [comment]
Previous build hung up after gradle assembly.  Assuming infrastructure, rebuilding.

**Review by jimblye — APPROVED** [review]

**Review by cbridgha — APPROVED** [review]
Looks good

**Comment by hlhoots** [comment]
#run-libby-bot

**Pull request merged**
