### PR TITLE
add a doPrivs to org.jboss.resteasy.spi.config.DefaultConfiguration

### PR DESCRIPTION
**Pull request by WhiteCat22**
to fix Java 2 Security errors

I'll be making a PR against RestEasy to contribute these changes back to the source.

We will be able to remove this overlay file when we upgrade to a version of RestEasy that includes these changes.

### CODE REVIEW

**Review by jim-krueger — APPROVED** [review]

**Comment by WhiteCat22** [comment]
#build

**Comment by WhiteCat22** [comment]
#run-libby-bot

**Comment by WhiteCat22** [comment]
Java 2 Security PB https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_E5nXAK6oEeuW8upL6bdo9A

**Comment by WhiteCat22** [comment]
Updated PR with feedback from RestEasy. #run-libby-bot
new PB: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_QNMg0K9oEeuW8upL6bdo9A

**Review by andymc12 — APPROVED** [review]
LGTM - thanks @WhiteCat22!

**Comment by WhiteCat22** [comment]
rebase on `release` after the branches are open again
#build
#run-libby-bot

**Comment by WhiteCat22** [comment]
failing test is not related to jaxrs

**Pull request merged**
