### PR TITLE
Update SmallRye OpenAPI to 4.0.2

### LINKED ISSUE #30111: mpOpenAPI-4.0 fails to parse a static openapi.json file containing tabs
Found during SVT:

Test with build  [openliberty-25.0.0.1-beta-cl241220241107-1102.zip](https://rtpgsa.ibm.com/projects/l/liberty.build/liberty/WASX.LIBERTY/daily/cl241220241107-1102.30.linux/linux/zipper/externals/installables/openliberty-25.0.0.1-beta-cl241220241107-1102.zip)

I see the following error in the log

> [ERROR   ] CWWKO1661E: An error occurred when processing application SocialSphere-mp and an OpenAPI document was not produced. The error was: io.smallrye.openapi.runtime.OpenApiRuntimeException: Failed to read YAML stream.

_Originally posted by @tam512 in https://github.com/OpenLiberty/open-liberty/issues/29035#issuecomment-2463714620_

When looking in the FFDC files, the full error is revealed to be:

```
io.smallrye.openapi.runtime.OpenApiRuntimeException: Failed to read YAML stream
	at io.smallrye.openapi.runtime.io.JacksonJsonIO.fromReader(JacksonJsonIO.java:385)
	at io.smallrye.openapi.runtime.io.JacksonJsonIO.fromReader(JacksonJsonIO.java:33)
	at io.smallrye.openapi.runtime.io.JsonIO.fromReader(JsonIO.java:473)
	at io.smallrye.openapi.api.SmallRyeOpenAPI$Builder.addStaticModel(SmallRyeOpenAPI.java:588)
	at io.smallrye.openapi.api.SmallRyeOpenAPI$Builder.lambda$buildStaticModel$5(SmallRyeOpenAPI.java:570)
	at io.smallrye.common.classloader.ClassPathUtils.lambda$consumeStream$1(ClassPathUtils.java:170)
	at io.smallrye.common.classloader.ClassPathUtils.readStream(ClassPathUtils.java:197)
	at io.smallrye.common.classloader.ClassPathUtils.consumeStream(ClassPathUtils.java:169)
	at io.smallrye.openapi.api.SmallRyeOpenAPI$Builder.buildStaticModel(SmallRyeOpenAPI.java:570)
	at io.smallrye.openapi.api.SmallRyeOpenAPI$Builder.build(SmallRyeOpenAPI.java:700)
	at io.openliberty.microprofile.openapi40.internal.services.impl.ModelGenerator40Impl.generateModel(ModelGenerator40Impl.java:47)
	at io.openliberty.microprofile.openapi20.internal.ApplicationProcessor.generateModel(ApplicationProcessor.java:323)
	at io.openliberty.microprofile.openapi20.internal.ApplicationProcessor.processWebModule(ApplicationProcessor.java:263)
	at io.openliberty.microprofile.openapi20.internal.ApplicationProcessor.processApplication(ApplicationProcessor.java:145)
	at io.openliberty.microprofile.openapi20.internal.ApplicationRegistryImpl.addApplication(ApplicationRegistryImpl.java:113)
	at io.openliberty.microprofile.openapi20.internal.ApplicationListener.applicationStarting(ApplicationListener.java:48)
	at com.ibm.ws.container.service.state.internal.ApplicationStateManager.fireStarting(ApplicationStateManager.java:53)
	at com.ibm.ws.container.service.state.internal.StateChangeServiceImpl.fireApplicationStarting(StateChangeServiceImpl.java:52)
	at com.ibm.ws.app.manager.module.internal.SimpleDeployedAppInfoBase.preDeployApp(SimpleDeployedAppInfoBase.java:623)
	at com.ibm.ws.app.manager.module.internal.SimpleDeployedAppInfoBase.installApp(SimpleDeployedAppInfoBase.java:584)
	at com.ibm.ws.app.manager.module.internal.DeployedAppInfoBase.deployApp(DeployedAppInfoBase.java:625)
	at com.ibm.ws.app.manager.war.internal.WARApplicationHandlerImpl.install(WARApplicationHandlerImpl.java:67)
	at com.ibm.ws.app.manager.internal.statemachine.StartAction.execute(StartAction.java:199)
	at com.ibm.ws.app.manager.internal.statemachine.ApplicationStateMachineImpl.enterState(ApplicationStateMachineImpl.java:1369)
	at com.ibm.ws.app.manager.internal.statemachine.ApplicationStateMachineImpl.run(ApplicationStateMachineImpl.java:912)
	at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:298)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:839)
Caused by: com.fasterxml.jackson.dataformat.yaml.snakeyaml.error.MarkedYAMLException: while scanning for the next token
found character '\t(TAB)' that cannot start any token. (Do not use \t(TAB) for indentation)
 in 'reader', line 2, column 1:
    	"openapi": "3.0.0",
    ^

 at [Source: (InputStreamReader); line: 1, column: 1]
	at com.fasterxml.jackson.dataformat.yaml.snakeyaml.error.MarkedYAMLException.from(MarkedYAMLException.java:28)
	at com.fasterxml.jackson.dataformat.yaml.YAMLParser.nextToken(YAMLParser.java:433)
	at com.fasterxml.jackson.databind.ObjectMapper._readTreeAndClose(ObjectMapper.java:4854)
	at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:3208)
	at io.smallrye.openapi.runtime.io.JacksonJsonIO.fromReader(JacksonJsonIO.java:382)
	... 28 more
Caused by: while scanning for the next token
found character '\t(TAB)' that cannot start any token. (Do not use \t(TAB) for indentation)
 in 'reader', line 2, column 1:
    	"openapi": "3.0.0",
    ^

	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:445)
	at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:238)
	at org.yaml.snakeyaml.parser.ParserImpl$ParseImplicitDocumentStart.produce(ParserImpl.java:212)
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:162)
	at org.yaml.snakeyaml.parser.ParserImpl.getEvent(ParserImpl.java:172)
	at com.fasterxml.jackson.dataformat.yaml.YAMLParser.nextToken(YAMLParser.java:429)
	... 31 more
```

The file being parsed in this case starts:

```json
{
	"openapi": "3.0.0",
```

The file uses a mix of spaces and tabs for indentation.

This should parse correctly as JSON because the whitespace in this location is not meaningful.

### PR DESCRIPTION
**Pull request by Azquelt**
Includes fix for parsing JSON static OpenAPI files, so also add a FAT test for that.

- [x] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [x] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [x] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

Fixes #30111

### CODE REVIEW

**Comment by Azquelt** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.microprofile.openapi.1.1_fat_tck,com.ibm.ws.microprofile.openapi_fat,com.ibm.ws.microprofile.openapi_fat_tck,com.ibm.ws.openapi.ui_fat,io.openliberty.microprofile.openapi.2.0.internal_fat,io.openliberty.microprofile.openapi.2.0.internal_fat_tck,io.openliberty.microprofile.openapi.3.0.internal_fat_tck,io.openliberty.microprofile.openapi.3.1.internal_fat_tck,io.openliberty.microprofile.openapi.4.0.internal_fat,io.openliberty.microprofile.openapi.4.0.internal_fat_tck,io.openliberty.microprofile.openapi.ui.internal_fat

**Comment by contbld** [comment]
Your personal pipeline request is at https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=d1690860-46fb-4eeb-9291-6a8dca0b10f5

Target locations of links might be accessible only to IBM employees.

**Comment by contbld** [comment]
https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=d1690860-46fb-4eeb-9291-6a8dca0b10f5 has errors/failures.

**Comment by Azquelt** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.microprofile.openapi.1.1_fat_tck,com.ibm.ws.microprofile.openapi_fat,com.ibm.ws.microprofile.openapi_fat_tck,com.ibm.ws.openapi.ui_fat,io.openliberty.microprofile.openapi.2.0.internal_fat,io.openliberty.microprofile.openapi.2.0.internal_fat_tck,io.openliberty.microprofile.openapi.3.0.internal_fat_tck,io.openliberty.microprofile.openapi.3.1.internal_fat_tck,io.openliberty.microprofile.openapi.4.0.internal_fat,io.openliberty.microprofile.openapi.4.0.internal_fat_tck,io.openliberty.microprofile.openapi.ui.internal_fat

**Comment by contbld** [comment]
Your personal pipeline request is at https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=10afeafb-a634-4c24-b570-068e57726394

Target locations of links might be accessible only to IBM employees.

**Comment by contbld** [comment]
<h3>Code analysis and actions</h3>
DO NOT DELETE THIS COMMENT.

- 2 FAT files were changed, added, or removed.
 - Check that the build did not break the affected FAT suite(s).

- 4 product code files were changed.

**Comment by contbld** [comment]
<h3>Code analysis and actions</h3>
DO NOT DELETE THIS COMMENT.

- 2 FAT files were changed, added, or removed.
 - Check that the build did not break the affected FAT suite(s).

- 4 product code files were changed.

**Review by ayoho — APPROVED** [review]

**Review by Emily-Jiang — APPROVED** [review]
LGTM

**Comment by contbld** [comment]
https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=10afeafb-a634-4c24-b570-068e57726394 has errors/failures.

**Comment by contbld** [comment]
The build Azquelt-30114-20241108-2303
https://wasrtc.hursley.ibm.com:9443/jazz/resource/itemOid/com.ibm.team.build.BuildResult/_N9Ga4Z5fEe-M9e5esDPP_g
completed successfully!

**Comment by contbld** [comment]
The build Azquelt-30114-20241108-2310
https://wasrtc.hursley.ibm.com:9443/jazz/resource/itemOid/com.ibm.team.build.BuildResult/_M9F58Z5gEe-M9e5esDPP_g
completed successfully!

**Pull request merged**
