### PR TITLE
Add wsoc tracing to basicTestServer

### PR DESCRIPTION
**Pull request by volosied**
Adding wsoc tracing for [rtc defect 278472](https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.workitem.viewWorkItem&id=278472)

### CODE REVIEW

**Comment by volosied** [comment]
#build

**Review by isaacrivriv — APPROVED** [review]
Looks good thanks!

**Review by loriadi — APPROVED** [review]
Looks good!

**Comment by volosied** [comment]
#run-libby-bot

**Pull request merged**
