### PR TITLE
update ui package.json files

### PR DESCRIPTION
**Pull request by aknguyen7**

### CODE REVIEW

**Comment by aknguyen7** [comment]
#build

**Comment by aknguyen7** [comment]
#build

**Comment by aknguyen7** [comment]
#build

**Review by k8vance88 — APPROVED** [review]

**Comment by aknguyen7** [comment]
image
image
image
image

known problem [27984](https://github.ibm.com/websphere/WS-CD-Open/issues/27984)
image

**Comment by aknguyen7** [comment]
#libby

**Pull request merged**
