### PR TITLE
Update Data TCK to version 1.0.1

### PR DESCRIPTION
**Pull request by KyleAure**
Related: https://github.com/jakartaee/data/issues/762

### CODE REVIEW

**Comment by KyleAure** [comment]
#build

**Comment by KyleAure** [comment]
Personal build failed as expected since the 1.0.1 artifact is not in Artifactory

**Comment by KyleAure** [comment]
TCK is passing locally.  Need to wait until TCK is published to review/build/merge this PR

**Comment by KyleAure** [comment]
#libby - check headers
#build - personal build

**Review by njr-11 — APPROVED** [review]

**Pull request merged**
