### PR TITLE
move code inside if block for null safety

### LINKED ISSUE #18663: NullPointerException in JaxRsFactoryImplicitBeanCDICustomizer
There currently is a potential for the following NPE in the 21.0.0.9 service release:
java.lang.NullPointerException at com.ibm.ws.jaxrs20.cdi.component.JaxRsFactoryImplicitBeanCDICustomizer.getClassFromCDI(JaxRsFactoryImplicitBeanCDICustomizer.java:241)

### PR DESCRIPTION
**Pull request by benjamin-confino**

### CODE REVIEW

**Comment by benjamin-confino** [comment]
#build

**Review by andymc12 — APPROVED** [review]
LGTM - thanks @benjamin-confino!

**Comment by benjamin-confino** [comment]
And build was green. Merging

**Comment by benjamin-confino** [comment]
#run-libby-bot

**Comment by jim-krueger** [comment]
Fixes #18663

**Pull request merged**
