### PR TITLE
Ejb custom bindings remote-home-binding, interface binding-name, and component-id

### PR DESCRIPTION
**Pull request by olendvcook**
#8780 
#8783 
#8778

### CODE REVIEW

**Comment by olendvcook** [comment]
#build

**Comment by olendvcook** [comment]
#build

**Comment by tkburroughs** [comment]
#run-libby-bot

**Comment by tkburroughs** [comment]
The second build, submitted after the last commit failed badly after 8 minutes; submitting another...
#build

**Comment by tkburroughs** [comment]
@olendvcook Merged

**Pull request merged**
