### PR TITLE
query language returning boolean and untested partial queries

### PR DESCRIPTION
**Pull request by njr-11**
Add coverage for
* Query method that returns boolean
* Query method with only FROM/WHERE/ORDER clauses, and test page count
* Query method with only FROM/ORDER clauses, and test page count
* Find method returning various types with wildcard type parameter
* Find method returning type with Object type parameter

- [x] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [x] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [x] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

### CODE REVIEW

**Comment by njr-11** [comment]
#build ([view Open Liberty Personal Build](https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?pipelineId=57c42178-036c-4f21-b491-81501c212b2d) - :x: completed with errors/failures.)

_Note: Target locations of links might be accessible only to IBM employees._

**Comment by njr-11** [comment]
#build ([view Open Liberty Personal Build](https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?pipelineId=74d1f28e-6289-40f5-9480-9c6777087967) - :x: completed with errors/failures.)

_Note: Target locations of links might be accessible only to IBM employees._

**Review by KyleAure — APPROVED** [review]

**Comment by njr-11** [comment]
#build ([view Open Liberty Personal Build](https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?pipelineId=146a59b0-2fa3-4d14-839f-ae48c732f2bc) - :x: completed with errors/failures.)

_Note: Target locations of links might be accessible only to IBM employees._

**Comment by njr-11** [comment]
> #build ([view Open Liberty Personal Build](https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?pipelineId=146a59b0-2fa3-4d14-839f-ae48c732f2bc) - ❌ completed with errors/failures.)
 ([view Open Liberty Personal Build](https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?pipelineId=9998dc53-2ce6-4e1e-8036-cf97776a057e) - :white_check_mark: completed successfully!)
> 
> _Note: Target locations of links might be accessible only to IBM employees._

Build has 1 intermittent test failure in an unrelated test bucket.

> Your personal build request is at https://wasrtc.hursley.ibm.com:9443/jazz/resource/itemOid/com.ibm.team.build.BuildResult/_EmyJELzaEe-V7IPhyP5jiw
> 
> Target locations of links might be accessible only to IBM employees.

Build is successful with no failures.

_Note: Target locations of links might be accessible only to IBM employees._

**Pull request merged**
