### PR TITLE
Added testcase for JSP with WebProfile and checkpoint

### PR DESCRIPTION
**Pull request by KeenanMcCarthy**
Created a test application with a JSP file that prints to server upon request, tesclass then searches logs for the output after checkpoint restore
for issue #21334

### CODE REVIEW

**Comment by KeenanMcCarthy** [comment]
#build
#libby

**Comment by KeenanMcCarthy** [comment]
#build

**Comment by KeenanMcCarthy** [comment]
#build

**Review by anjumfatima90 — APPROVED** [review]

**Comment by KeenanMcCarthy** [comment]
#libby

**Pull request merged**
