### PR TITLE
Add test for running with a custom UserRegistry loaded from a BELL.

### PR DESCRIPTION
**Pull request by jvanhill**
There is a lack of testing when loading a custom UserRegistry (CUR) from a BELL. Test both with and without federation.

### CODE REVIEW

**Comment by jvanhill** [comment]
#build

**Review by kristip17 — DISMISSED** [review]

**Comment by jvanhill** [comment]
#build

**Comment by jvanhill** [comment]
#build

**Review by kristip17 — APPROVED** [review]

**Comment by jvanhill** [comment]
#libby

**Comment by jvanhill** [comment]
#libby

**Pull request merged**
