### PR TITLE
Fix JPA FAT latest build break issues

### PR DESCRIPTION
**Pull request by dazey3**
1. In `com.ibm.ws.jpa.tests.eclipselink.query_jpa_3.1_fat`, it was missed that we should restrict to a minimum Java level of 11. Allowing this FAT to run against JDK8 produces failures indicating that no tests were run.

2. In `com.ibm.ws.jpa.tests.spec20_fat.common`, during the CREATE DDL execution, a table "CDM_Entity00" already exists failure occurs against Postgres:
```
SQL Execution failed: org.postgresql.util.PSQLException: ERROR: relation "cdm_entity00" already exists
[9/23/22 10:20:42:397 PDT] 0000002c id=00000000 SystemErr                                                    R org.postgresql.util.PSQLException: ERROR: relation "cdm_entity00" already exists
```

The reason for this failure is because the DROP DDL does not contain a DROP statement for "CDM_Entity00". However, this entity table "CDM_Entity00" is not even needed for the EntityManager test that was creating it, so the fix is to remove the CREATE statement from the DDL.

However, that isn't the last issue when running against Postgres... There was another issue that both the Cache and EntityManager test applications CREATE INDEX DDL statements that use the same INDEX names. For PostgreSQL, this appears to be a large issue. The Cache tests, running first, do not fail, however then the EntityManager tests run next, they fail to CREATE INDEXES that already exist.
I tried making sure that the Cache tests properly clean up and DROP INDEX, however that didn't resolve the issue. Instead, renaming the INDEXES to new names was the only way to resolve the issue against Postgres.

3. In all of the JPA FAT 3.1, I am seeing this failure:
```
    [9/27/22, 1:53:18:676 PDT] 00000029 eclipselink                                                  E CWWJP9992E: [eclipselink] Missing PostgreSQL10JsonPlatform from org.eclipse.persistence.pgsql module. JSON extension will not work properly.
```
Until the EclipseLink 4.0 binaries are updated, the current implementation throws a harsh error for the missing "org.eclipse.persistence.pgsql module" when running against PostgreSQL. That error has been lessened to trace, but we have not picked up that change yet in the new binaries.

### CODE REVIEW

**Comment by dazey3** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jpa.tests.spec20_jpa_2.1_fat,com.ibm.ws.jpa.tests.spec20_jpa_2.2_fat,com.ibm.ws.jpa.tests.spec20_jpa_3.0_fat,com.ibm.ws.jpa.tests.spec20_jpa_3.1_fat,com.ibm.ws.jpa.tests.eclipselink.query_jpa_3.1_fat

**Comment by dazey3** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jpa.tests.spec20_jpa_2.1_fat,com.ibm.ws.jpa.tests.spec20_jpa_2.2_fat,com.ibm.ws.jpa.tests.spec20_jpa_3.0_fat,com.ibm.ws.jpa.tests.spec20_jpa_3.1_fat,com.ibm.ws.jpa.tests.eclipselink.query_jpa_3.1_fat

**Review by jgrassel — APPROVED** [review]
lgtm

**Comment by dazey3** [comment]
#run-libby-bot

**Pull request merged**
