### PR TITLE
Zip reaper test

### PR DESCRIPTION
**Pull request by tbitonti**
Zip reaper main update:
Contains both the zip reaper updates and the updated artifact tests (artifact_fat, artifact_fat_bvt, and artifact_test).  "artifact_fat_bvt" is a port of "artifact_bvt" from WS-CD-Open, converted to being a FAT test instead of as a BVT test.

### CODE REVIEW

**Comment by tbitonti** [comment]
#build

**Comment by tbitonti** [comment]
#build

**Comment by tbitonti** [comment]
#build

**Comment by tbitonti** [comment]
#build

**Comment by gmarcy** [comment]
Looks like the latest build is finding a problem in the classloading_fat in the archive.zip code

**Comment by tbitonti** [comment]
Hi,

That's a known problem with this update.  The good news is that all of the
other tests are now passing (well, except for com.ibm.ws.jbatch.jms_fat
batch.jms.fat.junit.BatchMultiExecAndDynamicMSTest
testMultipleExecutorsInOneEndpoint, which I'm hoping is unrelated).

I think the ZIP open is expected to fail (based on the test name), and the
problem being the FFDC output is unexpected.  It's not clear to my why the
updated code emits an FFDC differently than the prior code.  Is there maybe
something in the classloading test which is confused by the new method
name?

Here is the current code:

/com.ibm.ws.artifact.zip/src/com/ibm/ws/artifact/zip/cache/internal/ZipFileUtils.java

    public static ZipFile openZipFile(final String path) throws
ZipException, IOException {
        return openZipFile( new File(path) );
    }

    @FFDCIgnore({PrivilegedActionException.class})
    public static ZipFile openZipFile(final File target) throws IOException
{
        Object token = ThreadIdentityManager.runAsServer();

        try {
            return AccessController.doPrivileged(new
PrivilegedExceptionAction<ZipFile>() {
                @Override
                public ZipFile run() throws IOException {
                    return new ZipFile(target);
                }
            });
        } catch (PrivilegedActionException e) {
            Exception e2 = e.getException();
            if (e2 instanceof IOException) {
                throw (IOException) e2;
            } else if (e2 instanceof RuntimeException) {
                throw (RuntimeException) e2;
            } else {
                throw new UndeclaredThrowableException(e);
            }

        } finally {
            ThreadIdentityManager.reset(token);
        }
    }

The prior code had this:

https://github.com/OpenLiberty/open-liberty/blob/integration/dev/com.ibm.ws.artifact.zip/src/com/ibm/ws/artifact/zip/internal/Utils.java


    @FFDCIgnore(PrivilegedActionException.class)
    public static ZipFile newZipFile(final File target) throws IOException
{
        try {
            return AccessController.doPrivileged(new
PrivilegedExceptionAction<ZipFile>() {
                @Override
                public ZipFile run() throws IOException {
                    return new ZipFile(target);
                }
            });
        } catch (PrivilegedActionException e) {
            Exception e2 = e.getException();
            if (e2 instanceof IOException)
                throw (IOException) e2;
            if (e2 instanceof RuntimeException)
                throw (RuntimeException) e2;
            throw new UndeclaredThrowableException(e);
        }
    }

The failing test:

com.ibm.ws.classloading_fat
com.ibm.ws.classloading.SharedLibFatTest
testClassloaderErrorArchive

junit.framework.AssertionFailedError: 2017-12-12-00:27:38:624 [Unexpected
FFDC reporting java.util.zip.ZipException was found (count =
1): /home/jazz_build/_xuirMd7FEeeJvLD-oValiA-EBC.PROD.WASRTC-4S9-000-00-00/jbe/build/dev/image/output/wlp/usr/servers/classloader_FAT_Server/logs/ffdc/ffdc_17.12.12_00.27.36.0.log

>------Start of DE processing------ = [12/12/17 0:27:36:867 UTC]
>Exception = java.util.zip.ZipException
>Source = com.ibm.ws.artifact.zip.internal.ZipFileContainer
>probeid = 659
>Stack Dump = java.util.zip.ZipException: error in opening zip file
>		 at java.util.zip.ZipFile.open(Native Method)
>		 at java.util.zip.ZipFile.<init>(ZipFile.java:235)
>		 at java.util.zip.ZipFile.<init>(ZipFile.java:165)
>		 at java.util.zip.ZipFile.<init>(ZipFile.java:179)
>		 at com.ibm.ws.artifact.zip.cache.internal.ZipFileUtils$1.run
(ZipFileUtils.java:39)
>		 at com.ibm.ws.artifact.zip.cache.internal.ZipFileUtils$1.run
(ZipFileUtils.java:36)
>		 at java.security.AccessController.doPrivileged
(AccessController.java:650)
>		 at
com.ibm.ws.artifact.zip.cache.internal.ZipFileUtils.openZipFile
(ZipFileUtils.java:36)
>		 at
com.ibm.ws.artifact.zip.cache.internal.ZipFileUtils.openZipFile
(ZipFileUtils.java:28)
>		 at com.ibm.ws.artifact.zip.cache.internal.ZipFileReaper.open
(ZipFileReaper.java:1394)
>		 at com.ibm.ws.artifact.zip.cache.internal.ZipFileReaper.open
(ZipFileReaper.java:1347)
>		 at
com.ibm.ws.artifact.zip.cache.internal.ZipFileHandleImpl.open
(ZipFileHandleImpl.java:131)
>		 at
com.ibm.ws.artifact.zip.internal.ZipFileContainer.openZipFileHandle
(ZipFileContainer.java:658)
>		 at
com.ibm.ws.artifact.zip.internal.ZipFileContainer.createZipEntries
(ZipFileContainer.java:802)
>		 at
com.ibm.ws.artifact.zip.internal.ZipFileContainer.getZipEntries
(ZipFileContainer.java:729)
>		 at com.ibm.ws.artifact.zip.internal.ZipFileContainer.iterator
(ZipFileContainer.java:919)
>		 at com.ibm.ws.classloading.internal.ContainerClassLoader
$ArtifactContainerUniversalContainer.processContainer
(ContainerClassLoader.java:504)
>		 at com.ibm.ws.classloading.internal.ContainerClassLoader
$ArtifactContainerUniversalContainer.updatePackageMap
(ContainerClassLoader.java:531)
>		 at com.ibm.ws.classloading.internal.ContainerClassLoader
$SmartClassPathImpl$1.run(ContainerClassLoader.java:731)
>		 at java.util.concurrent.Executors$RunnableAdapter.call
(Executors.java:522)
>		 at java.util.concurrent.FutureTask.run(FutureTask.java:277)
>		 at java.util.concurrent.ThreadPoolExecutor.runWorker
(ThreadPoolExecutor.java:1153)
>		 at java.util.concurrent.ThreadPoolExecutor$Worker.run
(ThreadPoolExecutor.java:628)
>		 at java.lang.Thread.run(Thread.java:785)
]
		 at componenttest.custom.junit.runner.FATRunner.blowup
(FATRunner.java:277)
		 at componenttest.custom.junit.runner.FATRunner.access$500
(FATRunner.java:63)
		 at componenttest.custom.junit.runner.FATRunner$1.evaluate
(FATRunner.java:227)
		 at componenttest.custom.junit.runner.FATRunner$2.evaluate
(FATRunner.java:314)
		 at componenttest.custom.junit.runner.FATRunner.run
(FATRunner.java:153)

Thomas F. Bitonti
WebSphere Application Server Group / WCCM
(919) 486-0867

**Comment by tbitonti** [comment]
#build

**Comment by tbitonti** [comment]
#build

**Comment by tbitonti** [comment]
#build

**Comment by tbitonti** [comment]
Most recent build failure is a duplicate of known defect 250407.

**Comment by tbitonti** [comment]
#build

**Comment by tbitonti** [comment]
Test failure testCustomizeCollectiveSwaggerUI covered by defect 249005:

https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.workitem.viewWorkItem&id=249005

**Pull request merged**
