### PR TITLE
[14039] Add `restfulWS-3.0` to beta and as part of `webProfile-9.0`

### LINKED ISSUE #14039: Add `restfulWS-3.0` to Jakarta Web/Full Profile 9.0 and Beta images
Need to set kind=beta, edition=core, and put restfulWS-3.0 in the webprofile-9.0 feature (which is already included in the jakartaee-9.0 feature).

Part of Epic Issue #11803

### PR DESCRIPTION
**Pull request by andymc12**
Fixes #14039

### CODE REVIEW

**Comment by andymc12** [comment]
#build

**Comment by andymc12** [comment]
#build

**Comment by andymc12** [comment]
#build

**Review by cbridgha — APPROVED** [review]
LGTM

**Comment by andymc12** [comment]
One failure in an unrelated JMS bucket (that occurs in other builds without this change).
#run-libby-bot

**Comment by andymc12** [comment]
#run-libby-bot

**Pull request merged**
