### PR TITLE
[14611] Tolerate mpConfig-2.0

### LINKED ISSUE #14611: mpGraphQL-1.0 should tolerate mpConfig-2.0
Currently, the `mpGraphQL-1.0` feature depends on `mpConfig-1.4`, but it should be able to tolerate `mpConfig-2.0` (part of MP 4.0). 

Ideally, we would just need to add the `ibm.tolerates:=2.0` directive to the mpGraphQL-1.0 feature, and either add some new tests (or use repeat actions for existing tests) to verify that it works, but it seems like we might be blocked on #14219 or a similar solution.

mpGraphQL-1.0 depends on mpConfig-1.4 (the API and impl), but the mpConfig-1.4 feature has a symbolic name that starts with "com.ibm" while mpConfig-2.0's symbolic name starts with "io.openliberty".  This means that they cannot be mutually exclusive as a singleton feature.  So a config like:
```
<featureManager>
  <feature>mpGraphQL-1.0</feature> <!-- includes mpConfig-1.4 -->
  <feature>mpConfig-2.0</feature>
</featureManager>
```
results in both `mpConfig-1.4` and `mpConfig-2.0` getting installed, wreaking havoc on OSGi's package wirings.  

Once #14219 is resolved, we may be able to use that solution to tolerate mpConfig-2.0 in mpGraphQL-1.0.

### PR DESCRIPTION
**Pull request by andymc12**
Be able to tolerate mpConfig-2.0 (MP 4.0) in mpGraphQL-1.0.

Fixes #14611 

Do not merge until solution is found for multiple mpConfig features installed at the same time.

### CODE REVIEW

**Comment by andymc12** [comment]
Rebased to pull in latest changes (including #14641). New #build

**Comment by andymc12** [comment]
#build

**Comment by andymc12** [comment]
#build

**Comment by andymc12** [comment]
#build

**Comment by andymc12** [comment]
Last build failed due to zOS issue. I manually kicked off another build with spawn.zos=false at https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_nKTigB9tEeuPC7nYV-RLig (only accessible to IBMers)

**Review by WhiteCat22 — APPROVED** [review]

**Comment by andymc12** [comment]
Made a few tweaks for handling comma-separated config properties->Lists and handling MP Metrics in MP 4.0.   New #build

**Comment by andymc12** [comment]
Another tweak... new #build

**Comment by andymc12** [comment]
#libby

**Pull request merged**
