### PR TITLE
Add JPA 31 testing EclipseLink Query FAT

### PR DESCRIPTION
**Pull request by dazey3**
Signed-off-by: Will Dazey <wadazey@us.ibm.com>

### CODE REVIEW

**Comment by dazey3** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jpa.tests.eclipselink.query_jpa_3.1_fat

**Comment by dazey3** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jpa.tests.eclipselink.query_jpa_3.1_fat

**Comment by dazey3** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jpa.tests.eclipselink.query_jpa_3.1_fat

**Comment by dazey3** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jpa.tests.eclipselink.query_jpa_3.1_fat

**Review by jgrassel — APPROVED** [review]
lgtm

**Comment by dazey3** [comment]
#run-libby-bot

**Pull request merged**
