### PR TITLE
preventing NPE by checking if the String returned by getMessageKey() …

### PR DESCRIPTION
**Pull request by jacobwdv**
…is null before doing .equals() comparisons.

maintenance of code to prevent NPE as seen in https://github.com/OpenLiberty/open-liberty/issues/19787

The NPE only happened because of an odd behaviour in the repository code. In any case, preventing an NPE would have resulted in better error output and user experience. This code change adds safeguards to check for null from the `getMessageKey()` API before using the value.

### CODE REVIEW

**Comment by jacobwdv** [comment]
#build

**Review by bensonlatibm — APPROVED** [review]
lgtm!

**Comment by jacobwdv** [comment]
#build

**Comment by jacobwdv** [comment]
all failures in build analysis show they are existing defects. Therefore my changes should be fit to merge.

**Comment by jacobwdv** [comment]
#libby-bot

**Pull request merged**
