### PR TITLE
Perf improvement in WC filter trace

### PR DESCRIPTION
**Pull request by pmd1nh**
https://github.com/OpenLiberty/open-liberty/issues/23405

### CODE REVIEW

**Comment by pmd1nh** [comment]
#build
        #spawn.fullfat.buckets=io.openliberty.webcontainer.servlet.6.0.internal_fat,com.ibm.ws.webcontainer_fat,com.ibm.ws.webcontainer.servlet.3.1_fat,com.ibm.ws.webcontainer.servlet.4.0_fat,com.ibm.ws.webcontainer_fat_part2,com.ibm.ws.webcontainer_fat_servlet31toleration,com.ibm.ws.webcontainer_fat_servlet31toleration_part2,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0_part2,com.ibm.ws.webcontainer_fat_lWAS,com.ibm.ws.webcontainer_fat_servlet31_webcontainerlWAS,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0.lWAS

**Review by loriadi — APPROVED** [review]
LGTM

**Comment by pmd1nh** [comment]
unrelated failure

com.ibm.ws.ui.tool.explore_fat.gui.nd.rw.ws FAT tests | 26 | 3 | 0 |   |  
-- | -- | -- | -- | -- | --
com.ibm.ws.ui.tool.explore.fat.gui.nd.rw.tests.ServerPortsTest | 5 | 3 | 0 | 3 m 55 s | 9
testCustomHttpAndHttpsPortsForOneServer_withWebSocket | 1 | 1 | 0 | 1 m 15 s | 3
testCustomHttpPortsOnlyForOneServer_withWebSocket | 1 | 1 | 0 | 1 m 14 s | 4
testCustomHttpsPortsOnlyForOneServer_withWebSocket | 1 | 1 | 0 | 1 m 14 s | 5

**Comment by pmd1nh** [comment]
#libby

**Pull request merged**
