### PR TITLE
Anno beta 3

### PR DESCRIPTION
**Pull request by tbitonti**

### CODE REVIEW

**Comment by tbitonti** [comment]
#build

**Comment by tbitonti** [comment]
#build

**Comment by skasund** [comment]
L2 message review completed

**Comment by tbitonti** [comment]
#build

**Comment by tbitonti** [comment]
#build

**Comment by tbitonti** [comment]
#build

**Comment by tbitonti** [comment]
#build

**Comment by tbitonti** [comment]
#build

**Comment by cbridgha** [comment]
@tbitonti I looked at the over 13MB of tests data for the unit tests, and the anno fat project is only 200K.    Shouldn't the majority of your tests be moved to the Fat Project?  

I know we also talked in the past about using artifactory to store tests data - I quickly talked to @ayoho about this, and he may be able to give some advice.

**Comment by tbitonti** [comment]
Errors in the personal build:

no component | 64366 | 1 | 5 |   |  
com.ibm.ws.eba.wab_fat FAT tests | 138 | 0 | 2 |   |  
com.ibm.ws.eba.wab.componenttest.WABClassPathOrderingFATEE7Test | 2 | 0 | 2 | 0 s | 4
testOrder | 1 | 0 | 1 | 0 s | 1
testNonLoadable | 1 | 0 | 1 | 0 s | 2
com.ibm.ws.microprofile.reactive.messaging_fat FAT tests | 4 | 0 | 3 |   |  
junit.framework.TestSuite | 3 | 0 | 3 | 0 s | 1
com.ibm.ws.microprofile.reactive.messaging.fat.suite.PlaintextTests | 1 | 0 | 1 | 0 s | 1
com.ibm.ws.microprofile.reactive.messaging.fat.suite.TlsTests | 1 | 0 | 1 | 0 s | 2
com.ibm.ws.microprofile.reactive.messaging.fat.suite.SaslPlainTests | 1 | 0 | 1 | 0 s | 3
com.ibm.ws.security.client_fat_java7 FAT tests | 17 | 1 | 0 |   |  
com.ibm.ws.security.client.fat.java7.BasicTest | 3 | 1 | 0 | 2 m 04 s | 2
testNoDefaultKeyTest | 1 | 1 | 0 | 1 m 02 s | 3

The two WAB tests may be related; I'm investigating.  The others look unrelated.

**Comment by tbitonti** [comment]
#build

**Comment by tbitonti** [comment]
Build failures are unrelated or covered by known issues.

**Pull request merged**
