### PR TITLE
Add --illegal-access=permit for JDBC Kerberos FAT for Java 16

### PR DESCRIPTION
**Pull request by gjwatts**
Fixes Java 16 permission errors by adding `--illegal-access=permit` to the needed package.

### CODE REVIEW

**Comment by gjwatts** [comment]
#build

**Review by mswatosh — APPROVED** [review]

**Comment by gjwatts** [comment]
#build

**Comment by gjwatts** [comment]
Added that exact same logic for DB2KerberosTest.java, PostgresKerberosTest.java and ErrorPathTest.java since they could all have the same problem.

**Comment by gjwatts** [comment]
#build

**Comment by gjwatts** [comment]
Also, internally running tests on Java 16 against the platforms that reported the Java 16 error in the first place.

**Comment by gjwatts** [comment]
Java 16 testing complete and successful, merging.

**Comment by gjwatts** [comment]
#libbybot

**Pull request merged**
