### PR TITLE
Issue #19707: RunnableJarHangsOnCtrlC

### PR DESCRIPTION
**Pull request by hlhoots**
Fixes issue in #19707

### CODE REVIEW

**Comment by hlhoots** [comment]
#build

**Comment by hlhoots** [comment]
windows build
https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_MTeGgG40EeywTM1lnhUXVw

**Comment by hlhoots** [comment]
windows build was good.  linux build had 1 un-related error.

**Review by cbridgha — APPROVED** [review]
Looks good

**Pull request merged**
