### PR TITLE
merge saml.4 to saml.3

### PR DESCRIPTION
**Pull request by meiaus**
https://github.com/OpenLiberty/open-liberty/issues/25015

### CODE REVIEW

**Comment by meiaus** [comment]
#run-libby-bot

**Comment by meiaus** [comment]
#run-libby-bot

**Comment by meiaus** [comment]
#build

**Comment by meiaus** [comment]
PB result:
1. With specified FAT: passed

image

2. With `soe.platform.requests` `AIX73_POWER10_PPC_IBM_SEMERUJDK17_OPENJ9_64_EBC,RHEL9_PPC64LE_IBM_SEMERUJDK18_OPENJ9_64,WIN2022_ORACLEJDK11_64_EBC`: passed

image


image

**Review by arunavemulapalli — APPROVED** [review]

**Pull request merged**
