### PR TITLE
Update JPA Spec 1.0 part 1 FAT to be multi-db supportive

### PR DESCRIPTION
**Pull request by olendvcook**
for #11840

created #12913 for Oracle Issue, can easily revert the 2nd commit later to re-enable oracle tests.

### CODE REVIEW

**Comment by olendvcook** [comment]
#build

**Comment by olendvcook** [comment]
#build

**Comment by olendvcook** [comment]
#build

**Comment by olendvcook** [comment]
#build

**Comment by olendvcook** [comment]
Postgres run = https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_G5MAkI_bEeqSW5h8Zr6pSw

**Comment by olendvcook** [comment]
postgres attempt 2: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_f5a2sJCSEeqSW5h8Zr6pSw

**Comment by olendvcook** [comment]
Postgres 3: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_xGeNwJEwEeqSW5h8Zr6pSw

**Comment by olendvcook** [comment]
Oracle: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_lZ744JFWEeqSW5h8Zr6pSw

**Comment by olendvcook** [comment]
SQLServer: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_rFBMYJFWEeqSW5h8Zr6pSw

**Comment by olendvcook** [comment]
SQLServer try 2: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_SlcsgJOCEeqgbanVBKj5-g

**Comment by olendvcook** [comment]
oracle with trace: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_w2MNsJOvEeqgbanVBKj5-g

**Comment by olendvcook** [comment]
oracle2 with trace: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_0DQbApR9EeqgbanVBKj5-g

**Comment by olendvcook** [comment]
oracle3 https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_ZgQnwJUdEeqgbanVBKj5-g

**Comment by olendvcook** [comment]
#build

**Comment by olendvcook** [comment]
Oracle: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_MrcC8LuUEeqsDL_UN9umug

**Comment by olendvcook** [comment]
#build

**Comment by olendvcook** [comment]
oracle 2: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_4SYAkLxuEeqsDL_UN9umug

**Comment by olendvcook** [comment]
oracle 3: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_upL1gL-fEeq9OZzIliLkpg

**Comment by olendvcook** [comment]
#build

**Comment by olendvcook** [comment]
#run-libby-bot
#build

**Comment by olendvcook** [comment]
#build

**Comment by olendvcook** [comment]
#build

**Comment by olendvcook** [comment]
#build

**Comment by dazey3** [comment]
#run-libby-bot

**Pull request merged**
