### PR TITLE
Decouple cxf projects from the jaxrs.2.0.client project

### PR DESCRIPTION
**Pull request by WhiteCat22**
Decouple org.apache.cxf.cxf.rt.transports.http.3.2 and org.apache.cxf.cxf.rt.transports.http.hc.3.2 from com.ibm.ws.jaxrs.2.0.client

### CODE REVIEW

**Comment by WhiteCat22** [comment]
#build

**Comment by WhiteCat22** [comment]
updated the com.ibm.ws.jaxrs.2.x.concurrent/bnd.bnd to import com.ibm.ws.cxf.client package

**Comment by WhiteCat22** [comment]
#build

**Comment by WhiteCat22** [comment]
#build

**Comment by WhiteCat22** [comment]
#build

**Comment by WhiteCat22** [comment]
builds died so rebuilding #build

**Comment by WhiteCat22** [comment]
com.ibm.ws.jaxrs.2.1_fat_executor->com.ibm.ws.jaxrs.executor.fat.JAXRSExecutorTest->testClientBuilderSubmitInvocationCallbackViaManagedExecutor is failing with:

```
java.lang.Exception: Unexpected failure for InvocationCallback lookup attempt. See cause.
	at web.jaxrstest.JAXRSExecutorTestServlet.testClientBuilderSubmitInvocationCallbackViaManagedExecutor(JAXRSExecutorTestServlet.java:117)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at componenttest.app.FATServlet.doGet(FATServlet.java:67)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:686)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:791)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1255)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:743)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:440)
	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1221)
	at com.ibm.ws.webcontainer.webapp.WebApp.handleRequest(WebApp.java:4968)
	at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.handleRequest(DynamicVirtualHost.java:314)
	at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:992)
	at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.run(DynamicVirtualHost.java:279)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink$TaskWrapper.run(HttpDispatcherLink.java:1047)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.wrapHandlerAndExecute(HttpDispatcherLink.java:417)
	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.ready(HttpDispatcherLink.java:376)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:532)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleNewRequest(HttpInboundLink.java:466)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.processRequest(HttpInboundLink.java:331)
	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.ready(HttpInboundLink.java:302)
	at com.ibm.ws.tcpchannel.internal.NewConnectionInitialReadCallback.sendToDiscriminators(NewConnectionInitialReadCallback.java:165)
	at com.ibm.ws.tcpchannel.internal.NewConnectionInitialReadCallback.complete(NewConnectionInitialReadCallback.java:74)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.requestComplete(WorkQueueManager.java:501)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.attemptIO(WorkQueueManager.java:571)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.workerRun(WorkQueueManager.java:926)
	at com.ibm.ws.tcpchannel.internal.WorkQueueManager$Worker.run(WorkQueueManager.java:1015)
	at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:239)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.naming.NamingException: CWNEN1000E: A JNDI operation on a java:comp/env name cannot be completed because the current thread is not associated with a Java Enterprise Edition application component. This condition can occur when the JNDI client using the java:comp/env name does not occur on the thread of a server application request. Make sure that a Java EE application does not run JNDI operations on java:comp/env names within static code blocks or in threads created by that application. Such code does not necessarily run on the thread of a server application request and therefore is not supported by JNDI operations on java:comp/env names.
	at com.ibm.ws.injectionengine.osgi.internal.naming.InjectionJavaColonHelper.getInjectionScopeData(InjectionJavaColonHelper.java:158)
	at com.ibm.ws.injectionengine.osgi.internal.naming.InjectionJavaColonHelper.getInjectionBinding(InjectionJavaColonHelper.java:132)
	at com.ibm.ws.injectionengine.osgi.internal.naming.InjectionJavaColonHelper.getObjectInstance(InjectionJavaColonHelper.java:112)
	at com.ibm.ws.jndi.url.contexts.javacolon.internal.JavaURLContext.lookup(JavaURLContext.java:332)
	at com.ibm.ws.jndi.url.contexts.javacolon.internal.JavaURLContext.lookup(JavaURLContext.java:370)
	at org.apache.aries.jndi.DelegateContext.lookup(DelegateContext.java:161)
	at javax.naming.InitialContext.lookup(InitialContext.java:417)
	at web.jaxrstest.JAXRSExecutorTestServlet$1.completed(JAXRSExecutorTestServlet.java:89)
	at web.jaxrstest.JAXRSExecutorTestServlet$1.completed(JAXRSExecutorTestServlet.java:80)
	at org.apache.cxf.jaxrs.client.JaxrsClientCallback.handleResponse(JaxrsClientCallback.java:76)
	at org.apache.cxf.jaxrs.client.WebClient$ClientAsyncResponseInterceptor.doHandleAsyncResponse(WebClient.java:1002)
	at org.apache.cxf.jaxrs.client.AbstractClient$AbstractClientAsyncResponseInterceptor.handleAsyncResponse(AbstractClient.java:1332)
	at org.apache.cxf.jaxrs.client.AbstractClient$AbstractClientAsyncResponseInterceptor.handleMessage(AbstractClient.java:1301)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
	at org.apache.cxf.jaxrs.client.ClientMessageObserver.onMessage(ClientMessageObserver.java:56)
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.handleResponseInternal(HTTPConduit.java:1747)
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream$1.run(HTTPConduit.java:1235)
	at com.ibm.ws.threading.internal.PolicyTaskFutureImpl.run(PolicyTaskFutureImpl.java:721)
	at com.ibm.ws.threading.internal.PolicyExecutorImpl.runTask(PolicyExecutorImpl.java:1133)
	at com.ibm.ws.threading.internal.PolicyExecutorImpl$GlobalPoolTask.run(PolicyExecutorImpl.java:188)
	... 3 more
```

Failing:
```
ws.context.service.serializable.ThreadContextDescriptorImpl 3 taskStopping JEEMetadataContextImpl@2fa4e2a1 default
```

Passing:
```
.ws.context.service.serializable.ThreadContextDescriptorImpl 3 taskStopping JEEMetadataContextImpl@63dcb305 jaxrsapp#jaxrsapp.war#web.jaxrstest.JAXRSExecutorTestServlet
```

**Comment by WhiteCat22** [comment]
I have no idea why this JNDI lookup is failing now, how it's related to my changes, nor why JEEMetadataContextImpl changes.

**Comment by WhiteCat22** [comment]
```
[2/14/19 12:23:24:279 CST] 00000014 id=496491ee LogService-104-com.ibm.ws.jaxrs.2.0.client                   3 BundleComponentActivator : Bundle [104] descriptor locations OSGI-INF/com.ibm.ws.jaxrs20.client.support.BundleRuntimeProviderFactoryServiceGateway.xml,OSGI-INF/com.ibm.ws.cxf.client.component.AsyncClientRunnableWrapperManager.xml,OSGI-INF/OAuthPropagationHelper.xml 
```

looks like we are loading AsyncClientRunnableWrapperManager from com.ibm.ws.jaxrs.2.0.client instead of com.ibm.ws.org.apache.cxf.cxf.rt.transports.http.3.2.

I'll move AsyncClientRunnableWrapperManager and AsyncClientRunnableWrapper out of com.ibm.ws.jaxrs.2.0.client and into com.ibm.ws.jaxrs.2.0.common since jaxrs-2.1 has a feature dependency on com.ibm.ws.jaxrs.2.0.client but not com.ibm.ws.jaxrs.2.0.common.

**Comment by neuwerk** [comment]
#6984

**Pull request closed without merging**
