### PR TITLE
Update message

### LINKED ISSUE #25097: Update adminCenter
Fixes #PH54050

### PR DESCRIPTION
**Pull request by pmd1nh**
Fixes #25097

### CODE REVIEW

**Comment by pmd1nh** [comment]
#build

**Comment by covener** [comment]
Fixes #PH54050

**Review by covener — APPROVED** [review]

**Comment by pmd1nh** [comment]
#libby

**Comment by pmd1nh** [comment]
whitespace correction can't cause failed test

no component 84793 1 0
 Feature verification (23003config76) 1 1 0

**Pull request merged**
