### PR TITLE
Re-enable FT Metrics test with MP6

### LINKED ISSUE #24013: Re-enable Fault Tolerance Metrics FAT test for MP 6.0
We disabled testing [`MetricRemovalTest`](https://github.com/OpenLiberty/open-liberty/blob/integration/dev/com.ibm.ws.microprofile.faulttolerance.cdi_fat_metrics/fat/src/com/ibm/websphere/microprofile/faulttolerance/metrics/fat/tests/MetricRemovalTest.java) on MP 6.0 while `mpMetrics-5.0` was being integrated but didn't re-enable it after that work was done.

I believe it should now pass without changes.

### PR DESCRIPTION
**Pull request by tevans78**
fixes https://github.com/OpenLiberty/open-liberty/issues/24013

### CODE REVIEW

**Comment by tevans78** [comment]
#build

**Comment by jhanders34** [comment]
Starting a new build now that Small Rye Metrics 5.0.0 Final is in the build.

#build

**Comment by tevans78** [comment]
#build

**Review by Azquelt — APPROVED** [review]

**Comment by tevans78** [comment]
PB is not yet complete but the FT Metrics FATs have passed. Merging now so that there is a chance this PR makes it in time for the next SOE.

**Pull request merged**
