### PR TITLE
Overlay equinox PR 698

### PR DESCRIPTION
**Pull request by tjwatson**
- [x] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [x] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [x] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

### CODE REVIEW

**Comment by tjwatson** [comment]
#build

**Comment by contbld** [comment]
Your personal pipeline request is at https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=e5ea28c5-74c0-4414-b3ae-562cbe30b42e

Target locations of links might be accessible only to IBM employees.

**Comment by contbld** [comment]
<h3>Code analysis and actions</h3>
DO NOT DELETE THIS COMMENT.

- 3 product code files were changed.

**Comment by contbld** [comment]
https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=e5ea28c5-74c0-4414-b3ae-562cbe30b42e has errors/failures.

**Comment by tjwatson** [comment]
#build

**Comment by contbld** [comment]
Your personal pipeline request is at https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=925de358-ab09-48b4-a8af-8e0583bbe579

Target locations of links might be accessible only to IBM employees.

**Comment by contbld** [comment]
<h3>Code analysis and actions</h3>
DO NOT DELETE THIS COMMENT.

- 3 product code files were changed.- **Please describe in a separate comment how you tested your changes.**
- 1 messages files were changed and need an L2 review.

- @OpenLiberty/message-reviewer Please review.
  - --nlsFiles

**Review by dazavala — APPROVED** [review]
`KeyBasedLockStore` looks correct; I see the slight difference in the functional interface.  All calls to `findLoadedClass()` in class `EquinoxClassLoader` are protected by the `classNameLock`.  I believe this is what the solution intends.  Approved.

**Comment by tjwatson** [comment]
> `KeyBasedLockStore` looks correct; I see the slight difference in the functional interface. All calls to `findLoadedClass()` in class `EquinoxClassLoader` are protected by the `classNameLock`. I believe this is what the solution intends. Approved.

I did change the function for the `lockCreator` from the version in open-liberty to take the key (class name) as a parameter.  I did this to allow `toString` to show the class name for the lock.  This way if we get a javacore with the lock it can show us what class it was for.

**Review by jhanders34 — APPROVED** [review]

**Pull request merged**
