### PR TITLE
Issue #17777: Remove SharedServer

### LINKED ISSUE #17777: Remove SharedServer from WCServletClarificationTest in the Servlet 4.0 FAT

### PR DESCRIPTION
**Pull request by pnicolucci**
fixes #17777

### CODE REVIEW

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Review by isaacrivriv — APPROVED** [review]
Looks good, thanks!

**Comment by pnicolucci** [comment]
#run-libby-bot

**Pull request merged**
