### PR TITLE
Automatic validation per Jakarta Data 1.0 beta 3, and tests

### PR DESCRIPTION
**Pull request by njr-11**
Enable tests for validation on insert and add new tests for validation on update, covering both save and saveAll for records and unannotated entity classes.

### CODE REVIEW

**Comment by njr-11** [comment]
#build

**Comment by njr-11** [comment]
#build

**Review by mswatosh — APPROVED** [review]

**Comment by njr-11** [comment]
#build

**Comment by njr-11** [comment]
#build

**Comment by njr-11** [comment]
#build

**Pull request merged**
