### PR TITLE
Fix session-timeout configuration not read

### LINKED ISSUE #23114: Servlet 6 configures session-timeout
The following web.xml configuration is failed to set in Servlet 6.0

```
<session-config>
        <session-timeout>60</session-timeout>
</session-config>
```
Reason - Servlet 6.0 didn't call the parent to process the <session-config> if the sub-element `<cookie-config>` not presented.

### PR DESCRIPTION
**Pull request by pmd1nh**
fixes #23114

### CODE REVIEW

**Comment by pmd1nh** [comment]
Address a TCK test.

**Comment by pmd1nh** [comment]
#build
#spawn.fullfat.buckets=io.openliberty.webcontainer.servlet.6.0.internal_fat,com.ibm.ws.webcontainer.servlet.3.1_fat,com.ibm.ws.webcontainer.servlet.4.0_fat,com.ibm.ws.session_fat,com.ibm.ws.session_fat_lWAS_servlet.3.1.toleration,com.ibm.ws.session.cache_fat,com.ibm.ws.session.cache_fat_config,com.ibm.ws.session.cache_fat_config_infinispan,com.ibm.ws.session.cache_fat_infinispan,com.ibm.ws.session.cache_fat_infinispan_container,com.ibm.ws.session.cache_provider_fat

**Comment by pmd1nh** [comment]
2 failed tests in session.cache_fat.

Resubmitted a build for this particular bucket.  All passed

com.ibm.ws.session.cache_fat FAT tests | 177 | 1 | 1 |   |  
-- | -- | -- | -- | -- | --
com.ibm.ws.session.cache_fat FAT tests | 182 | 0 | 0 |   |

**Comment by pmd1nh** [comment]
#libby

**Review by pnicolucci — APPROVED** [review]

**Pull request merged**
