### PR TITLE
Issue #16184: Minor EJB timer DST unit test adjustment

### PR DESCRIPTION
**Pull request by tkburroughs**
Corrected a couple UT scenarios to make them more realistic

for #16184

### CODE REVIEW

**Comment by tkburroughs** [comment]
#build

**Comment by tkburroughs** [comment]
One FAT failure is unrelated to changes

**Comment by tkburroughs** [comment]
#run-libby-bot

**Comment by tkburroughs** [comment]
#build 

Another build after recent changes to overall build

**Review by olendvcook — APPROVED** [review]

**Pull request merged**
