### PR TITLE
add debugging to apacheDSandKDC

### PR DESCRIPTION
**Pull request by Zech-Hein**
debugging the ApacheDS failures on z/OS

### CODE REVIEW

**Comment by Zech-Hein** [comment]
#build

**Comment by Zech-Hein** [comment]
z/os PB: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_iD_1gHIFEe6LyICjST0JEw

**Comment by utle** [comment]
#build

**Comment by utle** [comment]
zOS PB: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_-Kv2sHQnEe6LyICjST0JEw

**Comment by utle** [comment]
zOS PB:https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_3xNaIHTJEe6LyICjST0JEw

**Pull request closed without merging**
