### PR TITLE
Update CHIPS - Session Options + Other Fixes

### PR DESCRIPTION
**Pull request by volosied**
for https://github.com/OpenLiberty/open-liberty/issues/27405

### CODE REVIEW

**Comment by volosied** [comment]
#build #spawn.fullfat.buckets=io.openliberty.webcontainer.servlet.6.0.internal_fat,com.ibm.ws.webcontainer.servlet.4.0_fat

**Comment by volosied** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Review by pnicolucci — DISMISSED** [review]

**Comment by pnicolucci** [comment]
#libby

**Comment by volosied** [comment]
#build #spawn.fullfat.buckets=io.openliberty.webcontainer.servlet.6.0.internal_fat,com.ibm.ws.webcontainer.servlet.4.0_fat

**Comment by volosied** [comment]
#build #spawn.fullfat.buckets=io.openliberty.webcontainer.servlet.6.0.internal_fat,com.ibm.ws.webcontainer.servlet.4.0_fat

**Review by pnicolucci — APPROVED** [review]

**Comment by pnicolucci** [comment]
#libby

**Pull request merged**
