### PR TITLE
Added button role for cancelFilterHref and deleteSearchInputHref

### PR DESCRIPTION
**Pull request by FrankJYang**
added role="button"
Issue reference: https://github.ibm.com/websphere/WS-CD-Open/issues/28199
not release bug - no label included.

### CODE REVIEW

**Comment by FrankJYang** [comment]
#build

**Comment by FrankJYang** [comment]
#build

**Comment by FrankJYang** [comment]
#pb

**Review by aknguyen7 — APPROVED** [review]

**Comment by aknguyen7** [comment]
#link [28199](https://github.ibm.com/websphere/WS-CD-Open/issues/28199)

**Comment by FrankJYang** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.ui_rest_fat,com.ibm.ws.ui_fat.gui

**Comment by FrankJYang** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.ui_rest_fat,[com.ibm.ws](http://com.ibm.ws/).ui.collective_fat,com.ibm.ws.ui_fat.gui

**Comment by FrankJYang** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.ui_rest_fat,com.ibm.ws.ui_fat.gui

**Comment by FrankJYang** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.ui_rest_fat,com.ibm.ws.ui.collective_fat,com.ibm.ws.ui_fat.gui

**Pull request merged**
