### PR TITLE
MYFACES-4512

### LINKED ISSUE #25632: MYFACES-4512
**Describe the bug**  
A NullPointerException can occur when an application defines a custom ViewHandler that does not override the default implementation of `getViewDeclarationLanguage()` which returns null.

**Steps to Reproduce**  
Define a custom ViewHandler in an application that does not override the default implementation of `getViewDeclarationLanguage()`.

**Expected behavior**  
A NullPointerException would not be expected.

**Diagnostic information:**  
 - Affected feature(s): jsf-2.2, jsf-2.3, faces-3.0

**Additional context**  
https://issues.apache.org/jira/browse/MYFACES-4512

### PR DESCRIPTION
**Pull request by pnicolucci**
fixes #25632

### CODE REVIEW

**Comment by pnicolucci** [comment]
#build

**Review by volosied — DISMISSED** [review]
Looks good!

**Comment by pnicolucci** [comment]
#libby

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
child build failed but rerunning: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_-XhrkCIvEe6_w9kYCbJDeQ&tab=com.ibm.team.build.web.ui.internal.editors.result.overview.OverviewPage

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
#libby #build

**Review by volosied — APPROVED** [review]

**Pull request merged**
