### PR TITLE
Remove beta guard for crac-1.4 and InstantOn support for springBoot-3.0

### PR DESCRIPTION
**Pull request by tjwatson**

### CODE REVIEW

**Comment by tjwatson** [comment]
#build

**Comment by tjwatson** [comment]
#build

**Comment by tjwatson** [comment]
#build

**Review by dazavala — APPROVED** [review]
Looks good.  Changes are complete, and you implemented the minor optimization we discussed earlier.  IDR why `LibertyCheckpoint.checkpointRestore()` called `registerHookService()`. The call is unnecessary as the hook service was registered earlier, yes?

**Comment by tjwatson** [comment]
> Looks good. Changes are complete, and you implemented the minor optimization we discussed earlier. IDR why `LibertyCheckpoint.checkpointRestore()` called `registerHookService()`. The call is unnecessary as the hook service was registered earlier, yes?

I agree.  I think you may have misread the changes in the PR.  It does contain that optimization in `register` to not call `registerHookService` if the phase is `INACTIVE`.  But the other change is to remove the call to `registerHookService` from `LibertyCheckpoint.checkpointRestore`

**Comment by tjwatson** [comment]
#libby

**Review by anjumfatima90 — APPROVED** [review]

**Pull request merged**
