### PR TITLE
Batch Beta Removal PR

### PR DESCRIPTION
**Pull request by SmithaSubbarao**
This is for the issue: https://github.com/OpenLiberty/open-liberty/issues/27747
- [x] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [x] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [x] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

### CODE REVIEW

**Review by anjumfatima90 — APPROVED** [review]

**Review by anjumfatima90 — CHANGES_REQUESTED** [review]
I think we would need to update checkpointbatchFAT server as well in the FAT.

**Comment by SmithaSubbarao** [comment]
Test info:

1. JdbcConfigTestCheckpoint:
```
    [mkdir] Created dir: /root/open-liberty-instanton-setup/ub2204/open-liberty/dev/com.ibm.ws.jbatch.open_fat/build/libs/autoFVT/build/tmp
     [echo] framework.maxheap=-Xmx1024m
    [junit] Running batch.fat.junit.FATSuite
    [junit] Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 277.858 sec
     [echo] Finished running batch.fat.junit.FATSuite
     [echo] XML report is available at /root/open-liberty-instanton-setup/ub2204/open-liberty/dev/com.ibm.ws.jbatch.open_fat/build/libs/autoFVT/results/junit

generateReports:
 [startAnt] Buildfile: /root/open-liberty-instanton-setup/ub2204/open-liberty/dev/com.ibm.ws.jbatch.open_fat/build/libs/autoFVT/src/ant/launch.xml
 [startAnt] 
 [startAnt] reallyGenerateReports:
 [startAnt]      [echo] Generating an HTML report based on the existing XML report
 [startAnt]     [mkdir] Created dir: /root/open-liberty-instanton-setup/ub2204/open-liberty/dev/com.ibm.ws.jbatch.open_fat/build/libs/autoFVT/results/junit.html
 [startAnt] [junitreport] Processing /root/open-liberty-instanton-setup/ub2204/open-liberty/dev/com.ibm.ws.jbatch.open_fat/build/libs/autoFVT/results/junit/TESTS-TestSuites.xml to /tmp/null686574028
 [startAnt] [junitreport] Loading stylesheet jar:file:/usr/share/java/ant-junit-1.10.12.jar!/org/apache/tools/ant/taskdefs/optional/junit/xsl/junit-frames.xsl
 [startAnt] [junitreport] Transform time: 915ms
 [startAnt] [junitreport] Deleting: /tmp/null686574028
 [startAnt]      [echo] HTML report is available at /root/open-liberty-instanton-setup/ub2204/open-liberty/dev/com.ibm.ws.jbatch.open_fat/build/libs/autoFVT/results/junit.html/index.html
 [startAnt] 
 [startAnt] BUILD SUCCESSFUL
 [startAnt] Total time: 1 second

archiveReports:

execute:

BUILD SUCCESSFUL
Total time: 4 minutes 45 seconds

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.10.1/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD SUCCESSFUL in 6m
```

2. CDITestCheckpoint:
```
    [mkdir] Created dir: /root/open-liberty-instanton-setup/ub2204/open-liberty/dev/com.ibm.ws.jbatch.open_fat/build/libs/autoFVT/results/junit
    [mkdir] Created dir: /root/open-liberty-instanton-setup/ub2204/open-liberty/dev/com.ibm.ws.jbatch.open_fat/build/libs/autoFVT/results/tmp
     [copy] Copying 1 file to /root/open-liberty-instanton-setup/ub2204/open-liberty/dev/com.ibm.ws.jbatch.open_fat/build/libs/autoFVT/results
[propertyfile] Updating property file: /root/open-liberty-instanton-setup/ub2204/open-liberty/dev/com.ibm.ws.jbatch.open_fat/build/libs/autoFVT/results/logging.properties
     [echo] Running batch.fat.junit.FATSuite
     [echo] Timeout: 10800000
     [echo] Launching FAT with extra vmargs: 
     [echo] Launching FAT with zos extra vmargs: 
     [echo] Coverage settings:
     [echo] test.coverage: ${test.coverage}
     [echo] exec.data.file: /root/open-liberty-instanton-setup/ub2204/open-liberty/dev/com.ibm.ws.jbatch.open_fat/build/libs/autoFVT/results/coverage/jacoco.exec
     [echo] jacocoant.file: /root/open-liberty-instanton-setup/ub2204/open-liberty/dev/com.ibm.ws.jbatch.open_fat/build/libs/autoFVT/${junit_jar}/jacoco-0.7.6.201602180812/lib/jacocoant.jar
     [echo] jacocoagent.file: /root/open-liberty-instanton-setup/ub2204/open-liberty/dev/com.ibm.ws.jbatch.open_fat/build/libs/autoFVT/${junit_jar}/jacoco-0.7.6.201602180812/lib/jacocoagent.jar
    [mkdir] Created dir: /root/open-liberty-instanton-setup/ub2204/open-liberty/dev/com.ibm.ws.jbatch.open_fat/build/libs/autoFVT/build/tmp
     [echo] framework.maxheap=-Xmx1024m
    [junit] Running batch.fat.junit.FATSuite
    [junit] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 70.57 sec
     [echo] Finished running batch.fat.junit.FATSuite
     [echo] XML report is available at /root/open-liberty-instanton-setup/ub2204/open-liberty/dev/com.ibm.ws.jbatch.open_fat/build/libs/autoFVT/results/junit

generateReports:
 [startAnt] Buildfile: /root/open-liberty-instanton-setup/ub2204/open-liberty/dev/com.ibm.ws.jbatch.open_fat/build/libs/autoFVT/src/ant/launch.xml
 [startAnt] 
 [startAnt] reallyGenerateReports:
 [startAnt]      [echo] Generating an HTML report based on the existing XML report
 [startAnt]     [mkdir] Created dir: /root/open-liberty-instanton-setup/ub2204/open-liberty/dev/com.ibm.ws.jbatch.open_fat/build/libs/autoFVT/results/junit.html
 [startAnt] [junitreport] Processing /root/open-liberty-instanton-setup/ub2204/open-liberty/dev/com.ibm.ws.jbatch.open_fat/build/libs/autoFVT/results/junit/TESTS-TestSuites.xml to /tmp/null1465493357
 [startAnt] [junitreport] Loading stylesheet jar:file:/usr/share/java/ant-junit-1.10.12.jar!/org/apache/tools/ant/taskdefs/optional/junit/xsl/junit-frames.xsl
 [startAnt] [junitreport] Transform time: 880ms
 [startAnt] [junitreport] Deleting: /tmp/null1465493357
 [startAnt]      [echo] HTML report is available at /root/open-liberty-instanton-setup/ub2204/open-liberty/dev/com.ibm.ws.jbatch.open_fat/build/libs/autoFVT/results/junit.html/index.html
 [startAnt] 
 [startAnt] BUILD SUCCESSFUL
 [startAnt] Total time: 1 second

archiveReports:

execute:

BUILD SUCCESSFUL
Total time: 1 minute 18 seconds

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.10.1/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD SUCCESSFUL in 2m 58s
358 actionable tasks: 107 executed, 251 up-to-date
```

3. Full Fat Test: ```./gradlew com.ibm.ws.jbatch.open_fat:buildandrun -Dfat.test.class.name=JdbcConfigTestCheckpoint -Dfat.test.mode=FULL```
```
     [echo] Launching FAT with zos extra vmargs: 
     [echo] Coverage settings:
     [echo] test.coverage: ${test.coverage}
     [echo] exec.data.file: /root/open-liberty-instanton-setup/ub2204/open-liberty/dev/com.ibm.ws.jbatch.open_fat/build/libs/autoFVT/results/coverage/jacoco.exec
     [echo] jacocoant.file: /root/open-liberty-instanton-setup/ub2204/open-liberty/dev/com.ibm.ws.jbatch.open_fat/build/libs/autoFVT/${junit_jar}/jacoco-0.7.6.201602180812/lib/jacocoant.jar
     [echo] jacocoagent.file: /root/open-liberty-instanton-setup/ub2204/open-liberty/dev/com.ibm.ws.jbatch.open_fat/build/libs/autoFVT/${junit_jar}/jacoco-0.7.6.201602180812/lib/jacocoagent.jar
    [mkdir] Created dir: /root/open-liberty-instanton-setup/ub2204/open-liberty/dev/com.ibm.ws.jbatch.open_fat/build/libs/autoFVT/build/tmp
     [echo] framework.maxheap=-Xmx1024m
    [junit] Running batch.fat.junit.FATSuite
    [junit] Tests run: 24, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 836.691 sec
     [echo] Finished running batch.fat.junit.FATSuite
     [echo] XML report is available at /root/open-liberty-instanton-setup/ub2204/open-liberty/dev/com.ibm.ws.jbatch.open_fat/build/libs/autoFVT/results/junit

generateReports:
 [startAnt] Buildfile: /root/open-liberty-instanton-setup/ub2204/open-liberty/dev/com.ibm.ws.jbatch.open_fat/build/libs/autoFVT/src/ant/launch.xml
 [startAnt] 
 [startAnt] reallyGenerateReports:
 [startAnt]      [echo] Generating an HTML report based on the existing XML report
 [startAnt]     [mkdir] Created dir: /root/open-liberty-instanton-setup/ub2204/open-liberty/dev/com.ibm.ws.jbatch.open_fat/build/libs/autoFVT/results/junit.html
 [startAnt] [junitreport] Processing /root/open-liberty-instanton-setup/ub2204/open-liberty/dev/com.ibm.ws.jbatch.open_fat/build/libs/autoFVT/results/junit/TESTS-TestSuites.xml to /tmp/null366643589
 [startAnt] [junitreport] Loading stylesheet jar:file:/usr/share/java/ant-junit-1.10.12.jar!/org/apache/tools/ant/taskdefs/optional/junit/xsl/junit-frames.xsl
 [startAnt] [junitreport] Transform time: 873ms
 [startAnt] [junitreport] Deleting: /tmp/null366643589
 [startAnt]      [echo] HTML report is available at /root/open-liberty-instanton-setup/ub2204/open-liberty/dev/com.ibm.ws.jbatch.open_fat/build/libs/autoFVT/results/junit.html/index.html
 [startAnt] 
 [startAnt] BUILD SUCCESSFUL
 [startAnt] Total time: 1 second

archiveReports:

execute:

BUILD SUCCESSFUL
Total time: 14 minutes 4 seconds

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.10.1/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD SUCCESSFUL in 16m 22s
```

4. .Full batch bucket for Checkpoint only tests: ```./gradlew com.ibm.ws.jbatch.open_fat:buildandrun -Dfat.test.mode=FULL -Dfat.test.run.checkpoint.only=true```


```
    [mkdir] Created dir: /root/open-liberty-instanton-setup/ub2204/open-liberty/dev/com.ibm.ws.jbatch.open_fat/build/libs/autoFVT/build/tmp
     [echo] framework.maxheap=-Xmx1024m
    [junit] Running batch.fat.junit.FATSuite
    [junit] Tests run: 27, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1,027.009 sec
     [echo] Finished running batch.fat.junit.FATSuite
     [echo] XML report is available at /root/open-liberty-instanton-setup/ub2204/open-liberty/dev/com.ibm.ws.jbatch.open_fat/build/libs/autoFVT/results/junit

generateReports:
 [startAnt] Buildfile: /root/open-liberty-instanton-setup/ub2204/open-liberty/dev/com.ibm.ws.jbatch.open_fat/build/libs/autoFVT/src/ant/launch.xml
 [startAnt] 
 [startAnt] reallyGenerateReports:
 [startAnt]      [echo] Generating an HTML report based on the existing XML report
 [startAnt]     [mkdir] Created dir: /root/open-liberty-instanton-setup/ub2204/open-liberty/dev/com.ibm.ws.jbatch.open_fat/build/libs/autoFVT/results/junit.html
 [startAnt] [junitreport] Processing /root/open-liberty-instanton-setup/ub2204/open-liberty/dev/com.ibm.ws.jbatch.open_fat/build/libs/autoFVT/results/junit/TESTS-TestSuites.xml to /tmp/null1884557349
 [startAnt] [junitreport] Loading stylesheet jar:file:/usr/share/java/ant-junit-1.10.12.jar!/org/apache/tools/ant/taskdefs/optional/junit/xsl/junit-frames.xsl
 [startAnt] [junitreport] Transform time: 1011ms
 [startAnt] [junitreport] Deleting: /tmp/null1884557349
 [startAnt]      [echo] HTML report is available at /root/open-liberty-instanton-setup/ub2204/open-liberty/dev/com.ibm.ws.jbatch.open_fat/build/libs/autoFVT/results/junit.html/index.html
 [startAnt] 
 [startAnt] BUILD SUCCESSFUL
 [startAnt] Total time: 2 seconds

archiveReports:

execute:

BUILD SUCCESSFUL
Total time: 17 minutes 14 seconds

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.10.1/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD SUCCESSFUL in 18m 31s
358 actionable tasks: 66 executed, 292 up-to-date
```

**Comment by SmithaSubbarao** [comment]
#build ([view Open Liberty Personal Build](https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?pipelineId=9ddddd36-e68d-4dec-b571-ed3074da525b) - :white_check_mark: completed successfully!)

_Note: Target locations of links might be accessible only to IBM employees._

**Review by anjumfatima90 — CHANGES_REQUESTED** [review]
I think you would have to remove jvm.options file from `checkpointbatchFAT` server.

**Review by anjumfatima90 — APPROVED** [review]
LGTM, Thanks!

**Comment by SmithaSubbarao** [comment]
#build  ([view Open Liberty Personal Build](https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?pipelineId=614491fd-a4b5-44f3-92f9-7b164dae123c) - :white_check_mark: completed successfully!)

_Note: Target locations of links might be accessible only to IBM employees._

**Review by tjwatson — APPROVED** [review]

**Pull request merged**
