### PR TITLE
Refactoring health tests

### LINKED ISSUE #27935: Test Failure: io.openliberty.microprofile.health31.fat.ConfigAdminHealthCheckTest.testReadinessEndpointOnServerStart
RTC 299432

```
testReadinessEndpointOnServerStart:junit.framework.AssertionFailedError: 2024-03-15-16:06:34:618 App was not detected by ConfigAdmin.
    at io.openliberty.microprofile.health31.fat.ConfigAdminHealthCheckTest.testReadinessEndpointOnServerStart(ConfigAdminHealthCheckTest.java:404)
    at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
    at componenttest.custom.junit.runner.FATRunner$1.evaluate(FATRunner.java:203)
    at componenttest.rules.repeater.RepeatTests$CompositeRepeatTestActionStatement.evaluate(RepeatTests.java:145)
    at componenttest.custom.junit.runner.FATRunner$2.evaluate(FATRunner.java:363)
    at componenttest.custom.junit.runner.FATRunner.run(FATRunner.java:177)

```

### PR DESCRIPTION
**Pull request by tonyreigns**
Fixes: #27935 
#27908

### CODE REVIEW

**Comment by tonyreigns** [comment]
#build

**Comment by tonyreigns** [comment]
#build

**Comment by tonyreigns** [comment]
#build

**Review by pgunapal — APPROVED** [review]
LGTM

**Comment by tonyreigns** [comment]
#build

**Comment by tonyreigns** [comment]
#libby

**Pull request merged**
