### PR TITLE
Read-write WLP-Platforms from feature manifests

### LINKED ISSUE #28570: Part2 of Versionless Support for WLP-Platform feature header for assigning platform to feature
This is the "internal API" part of #28203

### PR DESCRIPTION
**Pull request by jimblye**
fixes #28570

### CODE REVIEW

**Review by tbitonti — DISMISSED** [review]

**Comment by jimblye** [comment]
#build

**Comment by jimblye** [comment]
#build

**Review by tbitonti — DISMISSED** [review]

**Comment by jimblye** [comment]
#build

**Review by cbridgha — APPROVED** [review]
Good to merge after WSCD test change makes it to release.... (a day)

**Comment by jimblye** [comment]
#libby

**Review by hlhoots — APPROVED** [review]
LGTM as well.  See Chuck's comments on merge order / timing.

**Review by tbitonti — APPROVED** [review]

**Pull request merged**
