### PR TITLE
Update MyFaces 2.3 to 2.3.7

### LINKED ISSUE #14950: Pull MyFaces 2.3.7 into Open Liberty
The latest version of Apache MyFaces that is released for 2.3 is 2.3.7. This issue pulls in the latest API / Implementation for Apache MyFaces 2.3. This is used by the `jsf-2.3` feature in Open Liberty.

### PR DESCRIPTION
**Pull request by pnicolucci**
fixes #14950

### CODE REVIEW

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jsfContainer_fat_2.3,com.ibm.ws.jsf_fat_lWAS_jsf2.3,com.ibm.ws.jsf_fat_jsf2.3,com.ibm.ws.jsf.2.3._fat

**Comment by pnicolucci** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jsfContainer_fat_2.3,com.ibm.ws.jsf_fat_lWAS_jsf2.3,com.ibm.ws.jsf_fat_jsf2.3,com.ibm.ws.jsf.2.3._fat,com.ibm.ws.jsf.2.2_fat

**Comment by pnicolucci** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jsfContainer_fat_2.3,com.ibm.ws.jsf_fat_lWAS_jsf2.3,com.ibm.ws.jsf_fat_jsf2.3,com.ibm.ws.jsf.2.3_fat,com.ibm.ws.jsf.2.2_fat

**Comment by pnicolucci** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jsfContainer_fat_2.3,com.ibm.ws.jsf_fat_lWAS_jsf2.3,com.ibm.ws.jsf_fat_jsf2.3,com.ibm.ws.jsf.2.3_fat,com.ibm.ws.jsf.2.2_fat

**Comment by pnicolucci** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jsfContainer_fat_2.3,com.ibm.ws.jsf_fat_lWAS_jsf2.3,com.ibm.ws.jsf_fat_jsf2.3,com.ibm.ws.jsf.2.3_fat,com.ibm.ws.jsf.2.2_fat

**Review by volosied — APPROVED** [review]
Thank you for working on this!

**Review by wtlucy — APPROVED** [review]

**Review by isaacrivriv — APPROVED** [review]
Looks good to me. Thanks!

**Comment by pnicolucci** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jsfContainer_fat_2.3,com.ibm.ws.jsf_fat_lWAS_jsf2.3,com.ibm.ws.jsf_fat_jsf2.3,com.ibm.ws.jsf.2.3_fat,com.ibm.ws.jsf.2.2_fat

**Comment by pnicolucci** [comment]
#run-libby-bot

**Pull request merged**
