### PR TITLE
jaasLoginContextEntryRef for connection factories

### PR DESCRIPTION
**Pull request by njr-11**
Add the jaasLoginContextEntryRef attribute to connectionFactory as beta and test it using the validator.

### CODE REVIEW

**Comment by njr-11** [comment]
#build

**Comment by njr-11** [comment]
#build

**Comment by njr-11** [comment]
ID review is not necessary because the attribute name/description was copied from an existing messages file (for the exact same attribute on a different configuration element), which would have already been reviewed.

**Comment by skasund** [comment]
L2 message review not required

**Comment by njr-11** [comment]
#build

**Comment by njr-11** [comment]
#build

**Comment by njr-11** [comment]
Build completed with all tests passing after removing a line of code that had been inadvertently copied to the ConnectionFactoryResourceBuilder from the JMSConnectionFactoryResourceBuilder

**Pull request merged**
