### PR TITLE
Move repeat fault tolerance

### LINKED ISSUE #10691: Impacted projects detection when RepeatFaultTolerance.java is updated
**The bug**
Running `#build` after updating `faulttolerance_fat/suite/RepeatFaultTolerance.java` did not detect impacts to the correct projects, and hence not all the required buckets ran.

**To reproduce**
Run `#build` after updating `RepeatFaultTolerance.java`

**Expected behavior**
Running `#build` should generate buckets for the impacted projects when `RepeatFaultTolerance.java` is updated. At the time of writting, these are:
```
com.ibm.ws.microprofile.faulttolerance.cdi_fat,
com.ibm.ws.microprofile.faulttolerance.cdi_fat_metrics,
com.ibm.ws.microprofile.faulttolerance.2.0_fat_tck
com.ibm.ws.microprofile.faulttolerance.2.1_fat_tck
```

### PR DESCRIPTION
**Pull request by Joseph-Cass**
Fixes #10691

### CODE REVIEW

**Comment by Joseph-Cass** [comment]
#build

**Comment by Joseph-Cass** [comment]
#build
#run-libby-bot

**Comment by Azquelt** [comment]
build did not complete which needs investigation

**Comment by Joseph-Cass** [comment]
#build
#run-libby-bot

**Comment by Joseph-Cass** [comment]
#build
#run-libby-bot

**Pull request merged**
