### PR TITLE
Run CpuInfo thread as a daemon

### LINKED ISSUE #20206: Servers stop can fail in products that embed Liberty
**Describe the bug**  
A long running thread was added in 22.0.0.1 to gather CPU statistics. It currently is created as a non-daemon thread. This causes problems with stopping the server in products that embed Liberty and prevent the JVM from stopping until all non-daemon threads have exited. 

**Expected behavior**  
The server should stop cleanly. 

**Diagnostic information:**  
 - Products that embed OpenLiberty Version: 22.0.0.1

### PR DESCRIPTION
**Pull request by brenthdaniel**
Fixes https://github.com/OpenLiberty/open-liberty/issues/20206

### CODE REVIEW

**Comment by brenthdaniel** [comment]
#build

**Comment by brenthdaniel** [comment]
Fixes #20206

**Review by tjwatson — APPROVED** [review]

**Comment by tjwatson** [comment]
#build

**Comment by tjwatson** [comment]
FYI @jhanders34 @dettmoney

**Comment by jhanders34** [comment]
Also adding @gjdeval to your FYI list.

**Comment by tjwatson** [comment]
I'm going to go ahead and merge this.  Thanks for fixing this Brent.

**Pull request merged**
