### PR TITLE
Create microProfile-3.1 feature

### LINKED ISSUE #9195: Create microProfile-3.1 convenience feature
Create the super-feature that enables all MicroProfile 3.1 sub features

### PR DESCRIPTION
**Pull request by tevans78**
Create microProfile-3.1 feature ... as beta to start with
fixes #9195

### CODE REVIEW

**Comment by tevans78** [comment]
#build

**Comment by ManasiGandhi** [comment]
@tevans78 Does this issue need a message review from the ID team?

**Comment by tevans78** [comment]
@ManasiGandhi No, it's a copy from microProfile-3.0 but with the version changed to 3.1. Thank you.

**Comment by ManasiGandhi** [comment]
@tevans78 Thanks.

**Pull request merged**
