### PR TITLE
Add code to retry SQL operations on tx recovery logs

### LINKED ISSUE #18893: Allow option to retry SQL operations on transaction recovery logs
Currently SQL operations on transaction recovery logs, where the logs are stored in a database, are only retried if a SQLTransientException is encountered. Optionally, this issue will allow more general SQLExceptions to be retried.

### PR DESCRIPTION
**Pull request by neilgsyoung**
fixes #18893

### CODE REVIEW

**Comment by neilgsyoung** [comment]
#build

**Comment by neilgsyoung** [comment]
#run-libby-bot

**Comment by neilgsyoung** [comment]
#build

**Comment by neilgsyoung** [comment]
#run-libby-bot

**Comment by neilgsyoung** [comment]
#build

**Review by jonhawkes — APPROVED** [review]

**Comment by neilgsyoung** [comment]
#run-libby-bot

**Comment by neilgsyoung** [comment]
#build

**Comment by neilgsyoung** [comment]
#run-libby-bot

**Comment by neilgsyoung** [comment]
#run-libby-bot

**Comment by neilgsyoung** [comment]
#build

**Comment by neilgsyoung** [comment]
#run-libby-bot

**Pull request merged**
