### PR TITLE
Update slf4j-simple to the latest version

### LINKED ISSUE #13184: Consolidate multiple versions of slf4j-simple
```
org.slf4j:slf4j-simple:1.7.25
org.slf4j:slf4j-simple:1.7.26
org.slf4j:slf4j-simple:1.7.28
```

Tom suggested to move all references to the latest level here per the review of PR #13169

### PR DESCRIPTION
**Pull request by Yushan-Lin**
Fixes #13184

### CODE REVIEW

**Comment by Yushan-Lin** [comment]
#build

**Comment by Yushan-Lin** [comment]
https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_bLJ7ANZSEeqBAvt2Ajbd0w

**Comment by Yushan-Lin** [comment]
https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_50TwYNcoEeqBAvt2Ajbd0w

**Comment by fmhwong** [comment]
#build

**Comment by fmhwong** [comment]
#build

**Comment by fmhwong** [comment]
#build

**Comment by Yushan-Lin** [comment]
#build

**Comment by Yushan-Lin** [comment]
#run-libby-bot

**Comment by Yushan-Lin** [comment]
FAT failure in personal build is not related to the change

**Pull request merged**
