### PR TITLE
Fix test application bug

### PR DESCRIPTION
**Pull request by pmd1nh**
Fix test application.

One line fix is around line 513

### CODE REVIEW

**Comment by pmd1nh** [comment]
https://github.com/OpenLiberty/open-liberty/issues/18516

**Comment by pmd1nh** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.webcontainer_fat,com.ibm.ws.webcontainer.servlet.3.1_fat,com.ibm.ws.webcontainer.servlet.4.0_fat,com.ibm.ws.webcontainer_fat_lWAS,com.ibm.ws.webcontainer_fat_servlet31_webcontainerlWAS,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0.lWAS

**Review by epj — APPROVED** [review]
looks good to me

**Comment by pmd1nh** [comment]
Brief summary:

In the test application, TestHttpUpgradeHandler, there is a 

static String TestSet 

which track the testing scenario.  In the normal condition, the client sends over some data, the channel read in those data, and the TestHttpUpgradeHandler handles those data and close out the input before the test complete.

However, during the reading data at the channel, there is intermittent delay (for whatever reasons), test A is pending for those data to be read.  At the same time, another request B (for different test case of the same suite) comes in and sets the above static String TestSet to its own test.  When test A completes its operation, it closes the web connection and interferes with the operation of test B.  

Trace here show two different tests during the clean up (close webConnection of one test) and also showing another test is being worked on ON THE SAME THREAD

=================

[5/9/21 1:09:34:185 PDT] 00000028 UpgradedWebCo 3   call Handler destroy com.ibm.ws.webcontainer31.upgrade.HttpUpgradeHandlerWrapper@44b7ec9a
[5/9/21 1:09:34:189 PDT] 00000028 UpgradedWebCo 3   Handler destroy successfulcom.ibm.ws.webcontainer31.upgrade.HttpUpgradeHandlerWrapper@44b7ec9a
[5/9/21 1:09:34:189 PDT] 00000028 SRTUpgradeInp 3   Calling close on the util class
[5/9/21 1:09:34:189 PDT] 00000028 UpgradeInputB 3   close, Initial read outstanding : false
[5/9/21 1:09:34:189 PDT] 00000028 UpgradeInputB 3   close, No read outstanding, no reason to call cancel
[5/9/21 1:09:34:189 PDT] 00000028 SRTUpgradeInp 3   Calling close on parent
[5/9/21 1:09:34:189 PDT] 00000028 UpgradeOutput 3   close upgrade output
[5/9/21 1:09:34:189 PDT] 00000028 UpgradeOutput 3   flushUpgraded: Flushing buffers for Upgraded output: com.ibm.ws.webcontainer31.util.UpgradeOutputByteBufferUtil@38dfdc94
[5/9/21 1:09:34:189 PDT] 00000028 UpgradeOutput 3   flushUpgraded: No more data to flush 
[5/9/21 1:09:34:189 PDT] 00000028 UpgradeOutput 3   flushUpgraded: disconnect write buffers in TCP when done
[5/9/21 1:09:34:189 PDT] 00000028 UpgradedWebCo 3    no callbacks, don't close here... 
[5/9/21 1:09:34:189 PDT] 00000028 UpgradedWebCo 3    webConnection_closeComplete--> true
``[5/9/21 1:09:34:189 PDT] 00000028 TestHttpUpgra I   closed webConnection in **testUpgradeReadSmallDataInHandler** `in TestUpgradeReadListener `
```
[5/9/21 1:09:34:189 PDT] 00000028 TestHttpUpgra I   
 [RUNNING TEST | **testUpgrade_WriteListener_From_ReadListener** | In init method of TestHttpUpgradeHandler
```
[5/9/21 1:09:34:189 PDT] 00000028 UpgradeInputB 3   UpgradeInputByteBufferUtil:: constructor
[5/9/21 1:09:34:189 PDT] 00000028 SRTUpgradeInp 3   init upgrade input
[5/9/21 1:09:34:189 PDT] 00000028 ThreadContext 3   ThreadContextManager created, getting the initial data
[5/9/21 1:09:34:189 PDT] 00000028 ThreadContext 3   ThreadContextManager saving the original thread's context data

===========

This is caused by a bug in the   TestHttpUpgradeHandler.setReadListenerTests().  The static TestSet is checked and only one test set should be allowed.  However, around line 513, it had been used "if" instead of an "else if"; thus two tests could have been running at the same time and messing up the later request's data state.

**Comment by pmd1nh** [comment]
#run-libby-bot

**Pull request merged**
