### PR TITLE
Update FFDCIgnore Javadoc

### PR DESCRIPTION
**Pull request by Azquelt**
For #22396

During the discussion of `@FFDCIgnore` and try-with-resources, an update to the Javadoc was requested.

However, I noted while writing it that `@FFDCIgnore` is part of the logging SPI so I'm not sure if that changes anything about how we can change its behaviour or whether I should include a link back to the issue about the limitation with using try-with-resources.

### CODE REVIEW

**Comment by Azquelt** [comment]
I couldn't find a test for FFDC instrumentation. There's [SimpleTryCatchTest](https://github.com/OpenLiberty/open-liberty/blob/integration/dev/com.ibm.ws.logging_test/test/com/ibm/ws/ras/instrumentation/test/SimpleTryCatchTest.java) which looks like it should be testing this, but when I tried running it the class isn't actually instrumented and no FFDCs are produced.

I manually tested the scenarios added to the Javadoc by inspecting the instrumented class file with `javap -c`.

**Comment by wraschke** [comment]
#libby

**Review by jhanders34 — APPROVED** [review]

**Review by frowe — APPROVED** [review]
Probably should add a reminder to issue 22396 to update this javadoc when/if the issue is resolved

**Comment by Azquelt** [comment]
#build

**Comment by Azquelt** [comment]
#build

**Comment by Azquelt** [comment]
Unusual failure in `com.ibm.ws.jmx.connector.bvt.JMXConnectorBVTTest` - don't think it's related to this PR but will run the build again to check.

#build

**Pull request merged**
