### PR TITLE
Issue #20095: update Mojarra to 2.3.9 for jsfContainer FAT

### LINKED ISSUE #20095: Update the mojarra test artifacts for the com.ibm.ws.jsfContainer_fat_2.3 FAT bucket
Currently, an old `2.3.3` version is used. Updating to the latest `2.3.9` version.

### PR DESCRIPTION
**Pull request by pnicolucci**
fixes #20095

### CODE REVIEW

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
#build

**Review by isaacrivriv — APPROVED** [review]
Looks good, thanks!

**Comment by pnicolucci** [comment]
#libby

**Pull request merged**
