### PR TITLE
versionless mpMetrics resolves with mp70

### LINKED ISSUE #30363: Failed to install versionless features with JEE10 and MP7 plafforms
**Describe the bug**  

Failed to install features by server.xml with versionless features

```
[INFO] Launching defaultServer (Open Liberty 24.0.0.12/wlp-1.0.96.cl241220241119-0657) on Eclipse OpenJ9 VM, version 11.0.18+10 (en_CA)
[INFO] [AUDIT   ] CWWKE0001I: The server defaultServer has been launched.
[INFO] [AUDIT   ] CWWKG0093A: Processing configuration drop-ins resource: /Users/gkwan/tasks/CNAI/guides/working/getting-started/versionless/guide-getting-started/finish/target/liberty/wlp/usr/servers/defaultServer/configDropins/overrides/liberty-plugin-variable-config.xml
[INFO] [ERROR   ] CWWKF0001E: A feature definition could not be found for mphealth
[INFO] [ERROR   ] CWWKF0001E: A feature definition could not be found for jsonb
[INFO] [ERROR   ] CWWKF0001E: A feature definition could not be found for jsonp
[INFO] [ERROR   ] CWWKF0001E: A feature definition could not be found for restfulws
[INFO] [ERROR   ] CWWKF0001E: A feature definition could not be found for cdi
[INFO] [ERROR   ] CWWKF0001E: A feature definition could not be found for mpconfig
[INFO] [ERROR   ] CWWKF0001E: A feature definition could not be found for mpmetrics
[INFO] [AUDIT   ] CWWKF0012I: The server installed the following features: [].
```

**Steps to Reproduce**  
- use Java 11+
- `git clone https://github.com/OpenLiberty/guide-getting-started.git -b versionless`
- `cd guide-getting-started/finish`
- `mvn liberty:run`
- got above errors

**Expected behavior**  
Liberty runtime should be started successfully with the required features from server.xml

**Diagnostic information:**  
 - OpenLiberty Version: 24.0.0.12
 - Affected feature(s): MP7
 - Java Version: Java 11, 17, 21
 - server.xml configuration (WITHOUT sensitive information like passwords)
   - https://github.com/OpenLiberty/guide-getting-started/blob/versionless/finish/src/main/liberty/config/server.xml 
 - If it would be useful, upload the messages.log file found in `$WLP_OUTPUT_DIR/messages.log`
   - the messages.log has no exception stack traces 

**Additional context**  
- there is no problem if switch to use MP 6.1

### PR DESCRIPTION
**Pull request by rsherget**
- [x] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [x] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [x] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

Fixes #30363

### CODE REVIEW

**Comment by rsherget** [comment]
#build ([view Open Liberty Personal Build](https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?pipelineId=3e3cadc2-181b-4031-ab49-7f6a42a9689b) - :x: completed with errors/failures.)

_Note: Target locations of links might be accessible only to IBM employees._

**Review by hlhoots — DISMISSED** [review]
LGTM

**Review by cbridgha — DISMISSED** [review]
looks good

**Comment by rsherget** [comment]
#build ([view Open Liberty Personal Build](https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?pipelineId=3169706a-bbbf-483d-beb3-3f91c5ce35e0) - :x: completed with errors/failures.)

_Note: Target locations of links might be accessible only to IBM employees._

**Review by hlhoots — APPROVED** [review]
LGTM

**Pull request merged**
