### PR TITLE
Add automated TX Lease Log SQL Retry tests

### LINKED ISSUE #20009: Add automated TX tests for lease log SQL Retries
Automate the manual tests.

### PR DESCRIPTION
**Pull request by neilgsyoung**
fixes #20009

### CODE REVIEW

**Comment by neilgsyoung** [comment]
#build

**Comment by neilgsyoung** [comment]
#build

**Comment by skasund** [comment]
L2 message review not required

**Comment by neilgsyoung** [comment]
#run-libby-bot

**Comment by neilgsyoung** [comment]
#build

**Comment by neilgsyoung** [comment]
#run-libby-bot

**Comment by neilgsyoung** [comment]
#build

**Comment by neilgsyoung** [comment]
#build

**Comment by neilgsyoung** [comment]
#run-libby-bot

**Comment by neilgsyoung** [comment]
#build

**Comment by neilgsyoung** [comment]
#run-libby-bot

**Comment by neilgsyoung** [comment]
#build

**Comment by neilgsyoung** [comment]
#run-libby-bot

**Comment by neilgsyoung** [comment]
#build

**Comment by neilgsyoung** [comment]
#build

**Comment by neilgsyoung** [comment]
#run-libby-bot

**Comment by neilgsyoung** [comment]
#build

**Comment by neilgsyoung** [comment]
#run-libby-bot

**Comment by neilgsyoung** [comment]
#build

**Comment by neilgsyoung** [comment]
#build

**Comment by neilgsyoung** [comment]
#build

**Comment by neilgsyoung** [comment]
#build

**Review by jonhawkes — APPROVED** [review]

**Pull request merged**
