### PR TITLE
Issue 4587: Update EclipseLink from 2.7.1 to 2.7.3 for JPA 2.2

### LINKED ISSUE #4587: Update EclipseLink 2.7.1 to 2.7.3 for JPA 2.2
There was a regression in 2.7.2, so we skipped that version. The regression should be fixed for 2.7.3

EclipseLink 2.7.3 has been released [here](http://www.eclipse.org/downloads/download.php?file=/rt/eclipselink/releases/2.7.3/eclipselink-plugins-2.7.3.v20180807-4be1041.zip)

### PR DESCRIPTION
**Pull request by dazey3**
fixes #4587

Signed-off-by: Will Dazey <dazeydev.3@gmail.com>

### CODE REVIEW

**Comment by dazey3** [comment]
The messages update in this PR only contains spaces changes. I don't think a messages code review is needed.

**Comment by dazey3** [comment]
#build

**Comment by lzdanski** [comment]
@dazey3 Confirmed that changes are only to whitespace in message files. In future, you can add the "ID review not needed" label when changes are made to the message files, but not to the message content. Adding ID reviewed label

**Comment by dazey3** [comment]
Failures in the build do not appear to be related.

**Pull request merged**
