### PR TITLE
Fix build break 281668 by waiting for exit status signal instead of c…

### PR DESCRIPTION
**Pull request by jvanhill**
…hannel close signal.

### CODE REVIEW

**Comment by jvanhill** [comment]
#build

**Review by Zech-Hein — APPROVED** [review]

**Comment by jvanhill** [comment]
The build seems frozen. Respinning.

#build

**Comment by jvanhill** [comment]
#build

**Comment by jvanhill** [comment]
#build

**Comment by jvanhill** [comment]
#libby

**Pull request merged**
