### PR TITLE
server config update SHA to SHA256 cipher for FIPS

### PR DESCRIPTION
**Pull request by meiaus**
To resolve: https://github.ibm.com/websphere/WS-CD-Open/issues/30276
Background FIPS 140-3 evaluation information: https://www.ibm.com/docs/en/sdk-java-technology/8?topic=guide-fips-140-3-evaluation-technology

### CODE REVIEW

**Comment by meiaus** [comment]
#run-libby-bot

**Comment by meiaus** [comment]
#build

**Comment by meiaus** [comment]
PB result:
From `#build`: The updated FAT passed:

image

**Comment by meiaus** [comment]
re-submit SOE by using the instruction CI Orchestrator SOE Platform against a PB in
https://github.ibm.com/websphere/WS-CD-Open/wiki/SOE-(Supported-Operating-Environments)-build#requesting-a-run-as-part-of-a-personal-build:

image

**Comment by meiaus** [comment]
The SOE PB build is complete without failure:

image


image


image

**Review by arunavemulapalli — APPROVED** [review]
lgtm

thanks.

**Review by WhiteCat22 — APPROVED** [review]

**Comment by meiaus** [comment]
Thanks @arunavemulapalli @WhiteCat22 for reviewing.

**Pull request merged**
