### PR TITLE
JAX-WS: Remove CXF 2.6.2 from jaxwsClient-2.2

### PR DESCRIPTION
**Pull request by neuwerk**
This pull request replaces the jaxwsClient-2.2 features use of 2.6.2 with 3.2

### CODE REVIEW

**Comment by neuwerk** [comment]
#build

**Comment by neuwerk** [comment]
#build

**Review by BerksanAtes — APPROVED** [review]
Looks good!

**Comment by neuwerk** [comment]
#run-libby-bot

**Pull request merged**
