### PR TITLE
JAXB: Upgrade JAXB to 2.3.9

### PR DESCRIPTION
**Pull request by neuwerk**
This PR does the following:

- Reverts [The revert of https://github.com/OpenLiberty/open-liberty/pull/26129](https://github.com/OpenLiberty/open-liberty/pull/27472)
- Reverts [the revert of: #27451](https://github.com/OpenLiberty/open-liberty/pull/27470)
- Fixes the failure in `io.openliberty.jaxws.tools_fat` by adding an `--adds-open` to the fat buckets command processor.

### CODE REVIEW

**Comment by neuwerk** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.javamail.1.6_fat, com.ibm.ws.anno_fat, com.ibm.ws.jaxb_fat, com.ibm.ws.jaxrs.2.0_fat, com.ibm.ws.jaxws.X.wsat_fat, com.ibm.ws.jaxws.ejb_fat, com.ibm.ws.jaxws.2.2.webcontainer_fat, com.ibm.ws.jaxws.2.2.webcontainer_fat_extended, com.ibm.ws.jaxws.cdi_fat, com.ibm.ws.jaxws.clientcontainer_fat, com.ibm.ws.jbatch.cdi_fat, com.ibm.ws.jbatch.misc_fat, com.ibm.ws.jbatch.open_fat, com.ibm.ws.kernel.feature_fat, com.ibm.ws.microprofile.config.1.1_fat, com.ibm.ws.microprofile.config.1.2_fat, com.ibm.ws.microprofile.config.1.3_fat, com.ibm.ws.microprofile.config.1.4_fat, com.ibm.ws.security.wim.adapter.file_fat, com.ibm.ws.tx.jta_fat_hibernate, io.openliberty.mail.2.0.internal_fat, com.ibm.ws.wsat_fat.db, com.ibm.ws.wsat.common_fat, com.ibm.ws.wssecurity_fat.wsscxf.1, com.ibm.ws.wssecurity_fat.wsscxf.1, com.ibm.ws.wssecurity_fat.wsscxf.2, com.ibm.ws.wssecurity_fat.wsscxf.3, com.ibm.ws.wssecurity_fat.wsscxf.saml.1, com.ibm.ws.wssecurity_fat.wsscxf.saml.2, com.ibm.ws.wssecurity_fat.wsscxf.saml.3, com.ibm.ws.wssecurity_fat.wsscxf.saml.5, com.ibm.ws.wssecurity_fat.wsscxf.saml.6, io.openliberty.jaxws.tools_fat

**Comment by neuwerk** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.javamail.1.6_fat, com.ibm.ws.anno_fat, com.ibm.ws.jaxb_fat, com.ibm.ws.jaxrs.2.0_fat, com.ibm.ws.jaxws.X.wsat_fat, com.ibm.ws.jaxws.ejb_fat, com.ibm.ws.jaxws.2.2.webcontainer_fat, com.ibm.ws.jaxws.2.2.webcontainer_fat_extended, com.ibm.ws.jaxws.cdi_fat, com.ibm.ws.jaxws.clientcontainer_fat, com.ibm.ws.jbatch.cdi_fat, com.ibm.ws.jbatch.misc_fat, com.ibm.ws.jbatch.open_fat, com.ibm.ws.kernel.feature_fat, com.ibm.ws.microprofile.config.1.1_fat, com.ibm.ws.microprofile.config.1.2_fat, com.ibm.ws.microprofile.config.1.3_fat, com.ibm.ws.microprofile.config.1.4_fat, com.ibm.ws.security.wim.adapter.file_fat, com.ibm.ws.tx.jta_fat_hibernate, io.openliberty.mail.2.0.internal_fat, com.ibm.ws.wsat_fat.db, com.ibm.ws.wsat.common_fat, com.ibm.ws.wssecurity_fat.wsscxf.1, com.ibm.ws.wssecurity_fat.wsscxf.1, com.ibm.ws.wssecurity_fat.wsscxf.2, com.ibm.ws.wssecurity_fat.wsscxf.3, com.ibm.ws.wssecurity_fat.wsscxf.saml.1, com.ibm.ws.wssecurity_fat.wsscxf.saml.2, com.ibm.ws.wssecurity_fat.wsscxf.saml.3, com.ibm.ws.wssecurity_fat.wsscxf.saml.5, com.ibm.ws.wssecurity_fat.wsscxf.saml.6, io.openliberty.jaxws.tools_fat

**Review by sawadood — APPROVED** [review]
Changes look good

**Comment by neuwerk** [comment]
#libby

**Pull request merged**
