### PR TITLE
H2 FVT: more orderly test servers shutdown

### PR DESCRIPTION
**Pull request by billw1024**

### CODE REVIEW

**Comment by billw1024** [comment]
fixes #14774

**Comment by billw1024** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.transport.http2_fat

**Review by loriadi — APPROVED** [review]
Hopefully this will help!

**Comment by billw1024** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.transport.http2_fat

**Pull request merged**
