### PR TITLE
Add JPA 3.0 enum to JPAVersion, properly report JPA 2.2 with JPA22 Ru…

### PR DESCRIPTION
**Pull request by jgrassel**
Add JPA 3.0 enum to JPAVersion, properly report JPA 2.2 with JPA22 Runtime, and add JPA30 Runtime.  Also, with JPA 3.0, the JPA runtime integration should not add the "eclipselink.allow-null-max-min" property.

### CODE REVIEW

**Comment by jgrassel** [comment]
#build

**Comment by jgrassel** [comment]
#build #run-libby-bot

**Comment by jgrassel** [comment]
`com.ibm.ws.jpa.container.ormdiagnostics_3.0_fat` needed to be updated to look for keyword "com.ibm.ws.jpa.container.v30.internal.JPA30Runtime" instead of "com.ibm.ws.jpa.container.v22.internal.JPA22Runtime"

**Review by dazey3 — APPROVED** [review]
LGTM

**Pull request merged**
