### PR TITLE
Update commons-io to 2.8.0

### LINKED ISSUE #16788: Update commons-io to 2.8.0 in /dev/wlp-mavenRepoTasks
Related to https://github.com/OpenLiberty/open-liberty/pull/16771 but use the latest version of commons-io which is 2.8.0 at this time.

### PR DESCRIPTION
**Pull request by ericglau**
Fixes https://github.com/OpenLiberty/open-liberty/issues/16788

### CODE REVIEW

**Comment by ericglau** [comment]
#build

**Comment by ericglau** [comment]
#build

**Comment by ericglau** [comment]
#build

**Comment by ericglau** [comment]
Tested by manually running the ant task locally to ensure its invocation of `IOUtils.toString(is, (Charset) null);` still returns a proper string when reading the features json.

**Comment by ericglau** [comment]
Tested by running the following gradle task locally: https://github.com/OpenLiberty/open-liberty/blob/ead2684fc97ab665ae4b9fd6e02d7319213c116d/dev/com.ibm.websphere.appserver.features/build.gradle#L396
and verified the Maven repo with features was generated under `dev/com.ibm.websphere.appserver.features/build/temp/mavenArtifact`

**Review by TrevCraw — APPROVED** [review]

**Comment by ericglau** [comment]
#run-libby-bot

**Pull request merged**
