### PR TITLE
Correctly sequence createJFAPChain

### PR DESCRIPTION
**Pull request by AndrewDJBanks**

### CODE REVIEW

**Comment by AndrewDJBanks** [comment]
fixes #8225

**Comment by AndrewDJBanks** [comment]
#build

**Comment by AndrewDJBanks** [comment]
#build

**Comment by AndrewDJBanks** [comment]
#build

**Comment by wraschke** [comment]
See my comments at https://ibm-cloud.slack.com/archives/C30NGUQ9E/p1563547913214200 regarding why I reverted this pull request.

**Pull request merged**
