### PR TITLE
Transactional annotation for Jakarta Data

### PR DESCRIPTION
**Pull request by njr-11**
Experiment with the Transactional annotation on a repository interface and its methods.
If Jakarta Data includes these on the bean, then repository methods will be intercepted and exhibit the specified transactional behavior.

### CODE REVIEW

**Comment by njr-11** [comment]
#build

**Comment by njr-11** [comment]
#libby

**Comment by njr-11** [comment]
#build

**Review by jmstephensgit — DISMISSED** [review]

**Comment by njr-11** [comment]
#libby

**Comment by njr-11** [comment]
#build

**Comment by njr-11** [comment]
#build
#libby

**Comment by njr-11** [comment]
#build
#libby

**Comment by njr-11** [comment]
#build

**Comment by njr-11** [comment]
#build

**Comment by njr-11** [comment]
#build

**Review by jmstephensgit — APPROVED** [review]

**Comment by njr-11** [comment]
build has 7 failures, which are preexisting issues in unrelated components

**Pull request merged**
