### PR TITLE
add SCR traces

### LINKED ISSUE #18608: Additional tracing for Error CWWKE0701E
Adding additional tracing for an error about loading the `com.ibm.ws.transport.http` bundle with the following trace

```
java.lang.Exception: 2021-08-17-19:44:37:810 Errors/warnings were found in server TestServer logs:
<br>[8/17/21, 19:43:03:419 PDT] 0000007c LogService-50-com.ibm.ws.transport.http                      E CWWKE0701E: bundle com.ibm.ws.transport.http:1.0.56.202108171920 (50)[com.ibm.ws.http.internal.HttpEndpointImpl(174)] : Timeout waiting for reg change to complete registered  
at componenttest.topology.impl.LibertyServer.checkLogsForErrorsAndWarnings(LibertyServer.java:2626)
at componenttest.topology.impl.LibertyServer.stopServer(LibertyServer.java:2485)
at componenttest.topology.impl.LibertyServer.stopServer(LibertyServer.java:2300)
at componenttest.topology.impl.LibertyServer.stopServer(LibertyServer.java:2275)
at com.ibm.ws.messaging.JMS20security.fat.JMSConsumerTest.JMSConsumerTest.testCreateSharedDurableWithMsgSel_TCP_SecOn(JMSConsumerTest.java:611)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at componenttest.custom.junit.runner.FATRunner$1.evaluate(FATRunner.java:197)
at componenttest.custom.junit.runner.FATRunner$2.evaluate(FATRunner.java:318)
at componenttest.custom.junit.runner.FATRunner.run(FATRunner.java:171)
at componenttest.rules.repeater.RepeatTests$CompositeRepeatTestActionStatement.evaluate(RepeatTests.java:143)
```

### PR DESCRIPTION
**Pull request by isaacrivriv**
fixes #18608

### CODE REVIEW

**Comment by isaacrivriv** [comment]
#build

**Comment by isaacrivriv** [comment]
#build

**Comment by isaacrivriv** [comment]
#build

**Comment by isaacrivriv** [comment]
#build

**Comment by isaacrivriv** [comment]
#build

**Review by pnicolucci — APPROVED** [review]

**Comment by isaacrivriv** [comment]
#libby

**Pull request merged**
