### PR TITLE
Expression Language 6.0: Update to the M13 version

### LINKED ISSUE #26674: Expression Language 6.0: Update to version M13 of the API and Implementation
Latest version:

API: https://repo1.maven.org/maven2/org/apache/tomcat/tomcat-el-api/11.0.0-M13/
Impl: https://repo1.maven.org/maven2/org/apache/tomcat/tomcat-jasper-el/11.0.0-M13/

### PR DESCRIPTION
**Pull request by pnicolucci**
fixes #26674

### CODE REVIEW

**Comment by pnicolucci** [comment]
#build #spawn.fullfat.buckets=io.openliberty.org.apache.jasper.expressionLanguage.6.0_fat,io.openliberty.org.apache.jasper.expressionLanguage.5.0_fat,com.ibm.ws.el.3.0_fat

**Comment by pnicolucci** [comment]
Java 2 Security build: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_a9u4kI4AEe6gttl9kBC4bw

**Comment by pnicolucci** [comment]
Java 2 security build as 100% green. The Expression Language 6.0 test just ran the AlwaysPassing test I think because the FAT requires Java 21. We can perhaps remove the bootstrap.properties updates in our Expression Language buckets to not run on J2Sec builds now that it looks like the build defs are updated. I can do this on a follow on PR.

**Comment by pnicolucci** [comment]
#libby #build

**Review by volosied — APPROVED** [review]
Look good

**Pull request merged**
