### PR TITLE
Upgrade Oracle container and driver to 21c

### LINKED ISSUE #23977: Upgrade Oracle container and driver to 21c
Ensure our tests are running against the latest version of Oracle so that we can more easily replicate customer environments. 

Oracle 21c Images: https://hub.docker.com/r/gvenzl/oracle-xe/tags?page=1&name=21.3.0
Oracle 21c JDBC Drivers: https://mvnrepository.com/artifact/com.oracle.database.jdbc/ojdbc8/21.8.0.0

### PR DESCRIPTION
**Pull request by KyleAure**
Fixes #23977

### CODE REVIEW

**Comment by KyleAure** [comment]
#build

**Comment by KyleAure** [comment]
Database Rotation personal build for oracle is at https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_pB2-8JhNEe2YL83b0ePHDw

Target locations of links might be accessible only to IBM employees.

**Review by nmittles — DISMISSED** [review]

**Comment by KyleAure** [comment]
Personal Build: failed the Krb5 test suite because the new image wasn't pulled before the timeout. 
re-running that child build here: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_5DTaUZjyEe2YL83b0ePHDw

Personal Build, with database rotation, was successful. 
Wait on the child build to pass successfully before merging.

**Comment by KyleAure** [comment]
#libby - recheck headers
#build - after resolving merge conflicts
@nmittles - need re-review

**Review by nmittles — APPROVED** [review]
Reviewed changes from Jan 23rd.

**Comment by KyleAure** [comment]
Personal build failed due to existing unrelated defects.

**Pull request merged**
