### PR TITLE
Issue #19935: Remove SharedServer

### LINKED ISSUE #19935: Remove SharedServer from NBMultiReadTest in Servlet 3.1 FAT bucket

### PR DESCRIPTION
**Pull request by pnicolucci**
fixes #19935

### CODE REVIEW

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Review by isaacrivriv — APPROVED** [review]
Looks good, thanks!

**Comment by pnicolucci** [comment]
#libby

**Pull request merged**
