### PR TITLE
Update to Felix SCR 2.2.2

### PR DESCRIPTION
**Pull request by tjwatson**
This is an update to OSGi R8 implementation of SCR

### CODE REVIEW

**Comment by tjwatson** [comment]
#build

**Comment by tjwatson** [comment]
#build

**Comment by tjwatson** [comment]
#build

**Comment by tjwatson** [comment]
#build

**Comment by tjwatson** [comment]
#build

**Review by dazavala — COMMENTED** [review]
LGTM according to issue 22057.

**Comment by tjwatson** [comment]
#build

**Comment by tjwatson** [comment]
#libby

**Review by dazavala — APPROVED** [review]
Looks good.

**Pull request merged**
