### PR TITLE
Zip reaper fix.

### PR DESCRIPTION
**Pull request by tbitonti**
Candidate fix for #258010.

### CODE REVIEW

**Comment by tbitonti** [comment]
#build

**Comment by tbitonti** [comment]
On background: During testing of zip introspector additions, it was noticed in the zip introspector dump information that the zip reaper was in an indefinite wait even though closes were pending.  A review of the reaper code found a bug in the selection of zip files which were to be reaped, causing some zip files to never be closed.

This change should remove cases of files being locked.  All cases may not be resolved.  Correct practice is to put in a small pause to allow the server to quiesce before attempting to update (rename, delete, or overwrite) archives which may have been in use by the server.

**Comment by tbitonti** [comment]
#build

**Comment by Azquelt** [comment]
#build

**Comment by tbitonti** [comment]
Build failures:

> com.ibm.ws.event.logging_fat FAT tests 7 1 0
>   com.ibm.ws.event.logging.FATTest 7 1 0
>     testEventLoggingRemoveFeature 1 1 0
> com.ibm.ws.kernel.metatype.helper_fat FAT tests 7 1 0
>   com.ibm.ws.kernel.metatype.helper.fat.FATTest 7 1 0
>     testFilesetFilesMonitorReenabled 1 1 0
> com.ibm.ws.security.authentication.builtin_fat FAT tests 39 0 1
>   com.ibm.ws.security.authentication.fat.CustomLoginModuleTest 11 0 1
>     testCustomLoginModule_DynamicUpdate_NestedToNestedLibrary 1 0 1
> com.ibm.ws.ui.tool.explore_fat.gui.nd.rw FAT tests 26 4 0
>   com.ibm.ws.ui.tool.explore.fat.gui.nd.rw.tests.ListViewTest 4 4 0
>     testSearchByTypeAndName 1 1 0
>     testSortingSearchResults 1 1 0
>     testAddingRemovingColumns 1 1 0
>     testAddRemoveColumnsPersistence 1 1 0
These don't seem to be related to the change.

**Comment by Azquelt** [comment]
I agree, all the failures in the build match existing defects.

**Pull request merged**
