### PR TITLE
MP Rest Client 2.0 impl, FATs, and TCK

### PR DESCRIPTION
**Pull request by andymc12**
Implements epic issue #10786

### CODE REVIEW

**Comment by andymc12** [comment]
#build

**Comment by andymc12** [comment]
Tweaks - new #build

**Review by jim-krueger — APPROVED** [review]

**Comment by andymc12** [comment]
#run-libby-bot

**Comment by andymc12** [comment]
Only one failure, and it is not related to these changes - and I've seen the same failure in multiple other builds that don't have these changes.

**Pull request merged**
