### PR TITLE
Adding feature translation files for OpenTracing.1.1

### LINKED ISSUE #4611: OpenTracing.1.1 Adding Translations to Features
Add translations for opentracing.1.1. Identical to OpenTracing.1.0 but are renamed to 1.1

### PR DESCRIPTION
**Pull request by tonyreigns**
Add translations for opentracing.1.1. Identical to OpenTracing.1.0 but are renamed to 1.1

Fixes #4611 

#build

### CODE REVIEW

**Comment by tonyreigns** [comment]
#build

**Comment by lzdanski** [comment]
@tonyreigns It looks like these are just translation file updates and don't need ID Review. Can you please add the "ID Review not needed" label?

**Comment by tonyreigns** [comment]
@lzdanski Hi Laura, yes we were told that we could just copy the translations over from the previous version as no changes were made to them. The label has been added.

**Comment by tonyreigns** [comment]
A work item already exists for the only error in this build. Unrelated to my changes.

**Pull request merged**
