### PR TITLE
Fix simplicity auto-feature dependency validation

### PR DESCRIPTION
**Pull request by tkburroughs**
Simplicity Feature code has a bug and is not reading auto-feature
provisioning correctly, so assumes all auto-features are enabled.

Fix auto-feature dependency validation and update FAT to properly
report tested features.

### CODE REVIEW

**Comment by tkburroughs** [comment]
#build

**Comment by tkburroughs** [comment]
#run_libby_bot

**Comment by tkburroughs** [comment]
#run-libby-bot

**Comment by tkburroughs** [comment]
#build

**Comment by tkburroughs** [comment]
#run-libby-bot

**Comment by tkburroughs** [comment]
#run-libby-bot

**Comment by tkburroughs** [comment]
#run-libby-bot

**Comment by tkburroughs** [comment]
#build

**Comment by tkburroughs** [comment]
#run-libby-bot
#build

**Comment by tkburroughs** [comment]
#run-libby-bot
#build

**Comment by tkburroughs** [comment]
#run-libby-bot
#build

**Review by olendvcook — APPROVED** [review]

**Comment by tkburroughs** [comment]
Failures in last 2 builds are known intermittent issues; ready to merge.

**Comment by tkburroughs** [comment]
#help

**Pull request merged**
