### PR TITLE
Update push request query string

### PR DESCRIPTION
**Pull request by wtlucy**

### CODE REVIEW

**Comment by wtlucy** [comment]
#build spawn.fullfat.buckets=com.ibm.ws.webcontainer.servlet.4.0_fat,com.ibm.ws.transport.http2_fat

**Comment by wtlucy** [comment]
#build spawn.fullfat.buckets=com.ibm.ws.webcontainer.servlet.4.0_fat,com.ibm.ws.transport.http2_fat

**Comment by wtlucy** [comment]
#build spawn.fullfat.buckets=com.ibm.ws.webcontainer.servlet.4.0_fat,com.ibm.ws.transport.http2_fat

**Comment by wtlucy** [comment]
fixes #3151

**Comment by wtlucy** [comment]
#build spawn.fullfat.buckets=com.ibm.ws.webcontainer.servlet.4.0_fat,com.ibm.ws.transport.http2_fat

**Comment by wtlucy** [comment]
My changes in the closed branch to allow these changes to get past the feature checker have been promoted to master, so the feature checker errors flagged by this PR should go away.
#build spawn.fullfat.buckets=com.ibm.ws.webcontainer.servlet.4.0_fat,com.ibm.ws.transport.http2_fat

**Comment by pnicolucci** [comment]
#build spawn.fullfat.buckets=com.ibm.ws.webcontainer.servlet.4.0_fat,com.ibm.ws.transport.http2_fat

**Comment by pnicolucci** [comment]
#build spawn.fullfat.buckets=com.ibm.ws.webcontainer.servlet.4.0_fat,com.ibm.ws.transport.http2_fat

**Pull request merged**
