### PR TITLE
Myfaces 4559

### LINKED ISSUE #24250: MYFACES-4559
https://issues.apache.org/jira/browse/MYFACES-4559

### PR DESCRIPTION
**Pull request by pnicolucci**
fixes #24250

### CODE REVIEW

**Comment by pnicolucci** [comment]
#libby #build #spawn.fullfat.buckets=com.ibm.ws.jsf.2.2_fat,com.ibm.ws.jsf.2.3_fat,io.openliberty.org.apache.myfaces.4.0_fat

**Comment by volosied** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jsf.2.2_fat,com.ibm.ws.jsf.2.3_fat,io.openliberty.org.apache.myfaces.4.0_fat

**Review by volosied — DISMISSED** [review]

**Comment by pnicolucci** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jsf.2.2_fat,com.ibm.ws.jsf.2.3_fat,io.openliberty.org.apache.myfaces.4.0_fat

**Comment by pnicolucci** [comment]
#libby #build

**Review by volosied — APPROVED** [review]

**Pull request merged**
