### PR TITLE
Coerce config values between metatype and JDBC driver types

### LINKED ISSUE #13867: With properties.postgresql, socketTimeout and connectTimeout cannot be parsed
**Describe the bug**
when declaring `<properties.postgresql connectTimeout="30s" socketTimeout="30s" ... />`
For both of these fields, I get the following exception:
```
[9/10/20 7:53:59:298 PDT] 00000022 com.ibm.ws.logging.internal.impl.IncidentImpl                I FFDC1015I: An FFDC Incident has been created: "java.lang.IllegalArgumentException: argument type mismatch com.ibm.ws.jdbc.internal.JDBCDriverService$1 217" at ffdc_20.09.10_07.53.59.0.log
[9/10/20 7:53:59:314 PDT] 00000022 com.ibm.ws.jdbc.internal.JDBCDriverService                   W DSRA8021W: Warning: error setting 'connectTimeout'=30: java.lang.IllegalArgumentException: argument type mismatch
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at com.ibm.ws.jdbc.internal.JDBCDriverService$1.run(JDBCDriverService.java:305)
	at com.ibm.ws.jdbc.internal.JDBCDriverService$1.run(JDBCDriverService.java:261)
	at java.security.AccessController.doPrivileged(AccessController.java:734)
	at com.ibm.ws.jdbc.internal.JDBCDriverService.create(JDBCDriverService.java:261)
	at com.ibm.ws.jdbc.internal.JDBCDriverService.createXADataSource(JDBCDriverService.java:662)
	at com.ibm.ws.jdbc.DataSourceService.init(DataSourceService.java:620)
```

**Steps to Reproduce**
Declare a PostgreSQL datasource, and try to set:  `<properties.postgresql connectTimeout="30s" socketTimeout="30s" ... />

**Expected behavior**
The values should be parsed

**Diagnostic information:**
 - Liberty 20.0.0.6
 - IBM Java 8.0_5.41

### PR DESCRIPTION
**Pull request by aguibert**
Closes #13867 

#build

### CODE REVIEW

**Review by njr-11 — COMMENTED** [review]
I spoke with Andy about this offline and he will check on whether this solution can replace the duration property lists (such as DURATION_MS_INT_PROPS) that are in PropertyService.  Otherwise, if it cannot be replaced, then it would be preferable to just add the postgresql duration properties to those lists.

**Comment by aguibert** [comment]
#build

**Comment by aguibert** [comment]
#build

**Review by njr-11 — APPROVED** [review]

**Comment by aguibert** [comment]
#run-libby

**Pull request merged**
