### PR TITLE
Bruce jwtsso config issues

### PR DESCRIPTION
**Pull request by brutif**

### CODE REVIEW

**Comment by brutif** [comment]
#build

**Comment by lzdanski** [comment]
Messages look good to me. Adding ID reviewed label.

**Comment by brutif** [comment]
build died mysteriously with threading unit test failure, so rebase to integration and try again.
#build

**Comment by brutif** [comment]
#build

**Comment by brutif** [comment]
#build

**Comment by brutif** [comment]
#build

**Pull request merged**
