### PR TITLE
modified:   com.ibm.ws.messaging.open_jms20security_fat/fat/src/com/i…

### PR DESCRIPTION
**Pull request by AndrewDJBanks**

### CODE REVIEW

**Comment by AndrewDJBanks** [comment]
fixes #23394

**Comment by AndrewDJBanks** [comment]
#build

**Comment by AndrewDJBanks** [comment]
#build

**Review by sakerl — APPROVED** [review]

**Comment by AndrewDJBanks** [comment]
#libbybot

**Pull request merged**
