### PR TITLE
Remove SharedServer from WCServerTest

### LINKED ISSUE #13911: Remove SharedServer from servlet.4.0_fat WCServerTest

### PR DESCRIPTION
**Pull request by pnicolucci**
fixes #13911

### CODE REVIEW

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Review by isaacrivriv — APPROVED** [review]
Looks good. Thanks!

**Comment by pnicolucci** [comment]
#run-libby-bot

**Pull request merged**
