### PR TITLE
Improve getting all stack traces for Slow RequestTiming 

### LINKED ISSUE #16174: Slow requests from the RequestTiming-1.0 feature causing huge bottleneck from multiple threads
**Describe the bug**
Many threads (~196) were detected as slow by the Request Timing feature, hence when the Request Timing feature was trying to log the warning, it tries to get all the stack trace for each thread, by calling `java/lang/Thread.getAllStackTraces`, which is causing a huge bottleneck and slowness, as several threads are waiting on this to complete.

**Stack Trace:**
```
      Java callstack:
          at java/lang/Thread.isAlive(Thread.java:632(Compiled Code))
          at java/lang/ThreadGroup.enumerateGeneric(ThreadGroup.java:418(Compiled Code))
             (entered lock: java/lang/ThreadGroup$ChildrenThreadsLock@0x0000000082074208, entry count: 1)
          at java/lang/ThreadGroup.enumerateGeneric(ThreadGroup.java:430(Compiled Code))
             (entered lock: java/lang/ThreadGroup$ChildrenGroupsLock@0x0000000081435240, entry count: 1)
          at java/lang/ThreadGroup.enumerateGeneric(ThreadGroup.java:430(Compiled Code))
             (entered lock: java/lang/ThreadGroup$ChildrenGroupsLock@0x0000000081435208, entry count: 1)
          at java/lang/ThreadGroup.enumerate(ThreadGroup.java:360(Compiled Code))
          at java/lang/ThreadGroup.enumerate(ThreadGroup.java:342(Compiled Code))
          at java/lang/Thread.getAllStackTraces(Thread.java:1187(Compiled Code))
          at **com/ibm/wsspi/requestContext/RequestContext.getStackTrace(RequestContext.java:179(Compiled Code))**
          at com/ibm/ws/request/timing/manager/SlowRequestManager$2$1.run(SlowRequestManager.java:127(Compiled Code))
          at com/ibm/ws/threading/internal/ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:239(Compiled Code))
          at java/util/concurrent/Executors$RunnableAdapter.call(Executors.java:522(Compiled Code))
          at java/util/concurrent/FutureTask.run(FutureTask.java:277(Compiled Code))
          at java/util/concurrent/ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160(Compiled Code))
          at java/util/concurrent/ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635(Compiled Code))
          at java/lang/Thread.run(Thread.java:820(Compiled Code))
```
**Steps to Reproduce**
Enable the `requestTiming-1.0` feature with 100+ threads that are really slow, ensure the `slowRequestThreshold` is low.

**Expected behavior**
There should not be a bottleneck when trying to get stack traces for the slow request warning.

**Diagnostic information:**
 - OpenLiberty Version: 20.0.0.x
 - Java Version: JRE 1.8.0 Linux amd64-64 (build 8.0.6.10 - pxa6480sr6fp10-20200408_01(SR6 FP10))

**Additional context**
(Analysis by Kevin G):
Looks like the code in `dev/com.ibm.ws.request.probes/src/com/ibm/wsspi/requestContext/RequestContext.java` in the method `getStackTrace` is not very efficient. It calls `Thread.getAllStackTraces` and calculating stack traces is expensive and the expense of this call will be proportional to the number of threads which in this case is a lot of threads. Instead the code could use `Thread.enumerate` which doesn't pre-calculate the stacks and then you can find the thread by ID. If you only need to check the Default Executor thread group, then the static method call should be sufficient; otherwise, you could get the root thread group and then call enumerate on that (be careful with creating a large enough array)

### PR DESCRIPTION
**Pull request by pgunapal**
Using `Thread.enumerate` to get all the stack traces, instead of using Thread.getAllStackTraces, which may have a performance impact if there are too many threads.

fixes #16174

### CODE REVIEW

**Comment by pgunapal** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.request.probe.jdbc_fat,com.ibm.ws.request.probe.servlet_fat,com.ibm.ws.request.probes_fat,com.ibm.ws.request.timing_fat

**Comment by pgunapal** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.request.probe.jdbc_fat,com.ibm.ws.request.probe.servlet_fat,com.ibm.ws.request.probes_fat,com.ibm.ws.request.timing_fat

**Comment by pgunapal** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.request.probe.jdbc_fat,com.ibm.ws.request.probe.servlet_fat,com.ibm.ws.request.probes_fat,com.ibm.ws.request.timing_fat

**Comment by pgunapal** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.request.probe.jdbc_fat,com.ibm.ws.request.probe.servlet_fat,com.ibm.ws.request.probes_fat,com.ibm.ws.request.timing_fat

**Review by fmhwong — APPROVED** [review]
LGTM.  Minor indentation problems due to mixed use of tabs and spaces.
Do we have an existing test case which can make sure we don't regress?

**Comment by pgunapal** [comment]
> LGTM. Minor indentation problems due to mixed use of tabs and spaces.
> Do we have an existing test case which can make sure we don't regress?

@fmhwong Fixed the indentation problem. We do have existing test cases that tests for the Slow RequestTiming stack traces. In both `com.ibm.ws.request.probes_fat` and `com.ibm.ws.request.timing_fat` FATs.

**Comment by pgunapal** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.request.probe.jdbc_fat,com.ibm.ws.request.probe.servlet_fat,com.ibm.ws.request.probes_fat,com.ibm.ws.request.timing_fat

**Comment by pgunapal** [comment]
#libby

**Pull request merged**
