### PR TITLE
initial steps for query by method parameters

### PR DESCRIPTION
**Pull request by njr-11**
This pull includes some initial steps for query by parameters.
Some method names in tests are renamed to become consistent with either query-by-method name or query-by-parameters.
Basic updates are included to identify whether query-by-method vs query-by-parameters is wanted, with the query-by-parameters processing set up to the point of identifying if parameters are present and allowing some basic operations.

### CODE REVIEW

**Comment by njr-11** [comment]
#build

**Comment by njr-11** [comment]
#build
#libby

**Comment by njr-11** [comment]
#build
#libby

**Review by jmstephensgit — APPROVED** [review]

**Comment by wraschke** [comment]
#build
#libby

**Pull request merged**
