### PR TITLE
Copy the input stream sent to providers to avoid premature close

### PR DESCRIPTION
**Pull request by andymc12**

### CODE REVIEW

**Comment by andymc12** [comment]
#build

**Comment by wraschke** [comment]
Test comment; please ignore.

**Comment by andymc12** [comment]
Added a new commit (doing the same thing in a different place) - new #build

**Comment by andymc12** [comment]
Rebasing and new #build now that the streams are open

**Comment by andymc12** [comment]
There was a failure in the com.ibm.ws.jaxrs.2.1.webcontainer_fat bucket in the most recent build, but I was not able to reproduce that in my own local build.  Submitting a new #build since the previous failure may have been another problem with the build/test infrastructure.

**Comment by andymc12** [comment]
#build

**Comment by andymc12** [comment]
#build

**Comment by andymc12** [comment]
Just rebased to pull in recent changes in similar space.  New #build

**Pull request merged**
