### PR TITLE
Publish schemaGen script with rc=0 when no arguments

### PR DESCRIPTION
**Pull request by jimblye**
Fixes issue  #20695, re-publishes the script.   The script now returns rc=0 when invoked with no arguments.
This is hopefully the last step for the original issue #18191

### CODE REVIEW

**Comment by jimblye** [comment]
#build
#libby

**Comment by jimblye** [comment]
#build

**Comment by jimblye** [comment]
#build

**Review by hlhoots — APPROVED** [review]
LGTM

**Comment by jimblye** [comment]
#libby

**Comment by jimblye** [comment]
#libby

**Comment by hlhoots** [comment]
#run-libby-bot

**Pull request merged**
