### PR TITLE
Issue16524-FixAuditRecordSpanningLogs

### PR DESCRIPTION
**Pull request by emilytee**

### CODE REVIEW

**Comment by emilytee** [comment]
Fixes #16524

**Comment by emilytee** [comment]
#build

**Review by acdemyers — APPROVED** [review]

**Comment by emilytee** [comment]
#build

**Comment by emilytee** [comment]
#build

**Comment by emilytee** [comment]
#build

**Comment by emilytee** [comment]
#build

**Comment by emilytee** [comment]
#run-libby-bot

**Pull request merged**
