### PR TITLE
Various fixes for Logstash Testcontainer FAT

### LINKED ISSUE #14348: Test Failure (20200923-0443): com.ibm.ws.logstash.collector.tests.LogstashSSLTest.testLogstashDefaultConfig
RTC 278134

```
junit.framework.AssertionFailedError: 2020-10-03-00:23:17:450 Did not get all messages from Logstash container. Missing 1
	at com.ibm.ws.logstash.collector.tests.LogstashSSLTest.testLogstashDefaultConfig(LogstashSSLTest.java:116)
	at componenttest.custom.junit.runner.FATRunner$1.evaluate(FATRunner.java:197)
	at org.testcontainers.containers.FailureDetectingExternalResource$1.evaluate(FailureDetectingExternalResource.java:30)
	at componenttest.custom.junit.runner.FATRunner$2.evaluate(FATRunner.java:318)
	at componenttest.custom.junit.runner.FATRunner.run(FATRunner.java:171)

```

### PR DESCRIPTION
**Pull request by fmhwong**
Fixes #14348 
- Update testcontainer to 1.14.0
- Wait for TRAS0218I to show up in container log before clearing it

- Updated the testLogstashForGCEvent test

### CODE REVIEW

**Comment by fmhwong** [comment]
#build

**Comment by fmhwong** [comment]
#build

**Comment by fmhwong** [comment]
#libby

**Review by Yushan-Lin — APPROVED** [review]
LGTM

**Pull request merged**
