### PR TITLE
Eclipse file clean up and other small changes.

### PR DESCRIPTION
**Pull request by jhanders34**
- Update auto feature to not include the feature that is part of the filter.
- Remove log flie that should not have been added to the repo
- Remove non existent source directory from com.ibm.ws.concurrent_fat_jakarta .classpath file
- Update version=0 to be version="0" to remove errors when using the transformer
- Update com.ibm.ws.logging method names that have an invisible character causing compile failure on eclipse.
- Do not ship the source for com.ibm.ws.kernel.feature.core in the bundle.
- Add missing buildpath dependency that cause eclipse build error due to indirectly referenced class.
- Add new FATs to the test-categories for Github builds
- Remove non existent src for servlet 6.0 and make sure it is marked to Java 11 requirement.

### CODE REVIEW

**Comment by jhanders34** [comment]
#build

**Review by tabishop — APPROVED** [review]
Approved for jsonp related changes

**Review by cbridgha — APPROVED** [review]
Looks good

**Review by tevans78 — APPROVED** [review]

**Review by ellen-lau — APPROVED** [review]
LGTM for logging related changes

**Review by pmd1nh — APPROVED** [review]
Reviewed for servlet and jsp.  Thanks!

**Pull request merged**
