### PR TITLE
oidc client update to make sure that we can access post params

### LINKED ISSUE #28235: Enabling openidConnectClient feature causes the body request not to be forwarded to the application's servlet (starting from WLP 24.0.0.3)
It seems that something has changed with the OpenID implementation in WLP 24.0.0.3, causing the body/payload of the POST request to no longer be included in the request input stream. 

In cases when OpenID is not used (i.e., ‘openidConnectClient-1.0’ is not added to the feature list and openidConnectClient is not defined in server.xml), the request body is always available via:

 ```
      public void service(ServletRequest request, ServletResponse response) {
           request.getInputStream();
       }
```
in the servlet. However, when OpenID is used (and this change started from 24.0.0.3) the request.getInputStream() returns an empty stream for some of the POST request. Instead, the value of the request payload is included in one of the request attributes. To be more exact, it is an "ServletRequestWrapperHashMap" attribute (request.getAttribute("ServletRequestWrapperHashMap")) that contains a HashMap<String, Object> with three values: ContentDataLength (Long), ContentType (e.g., string ‘application/x-www-form-urlencoded; charset=UTF-8”), and ContentData – the byte array (byte[]) with the request body.

The problem was observed in case of POST requests which include in body/payload following content: "_method=GET ...."

E.g.:

```
curl 'https://ba5d95c1-us-south.lb.appdomain.cloud/sam/computers.json' \
  -H 'accept: application/json, text/javascript, */*; q=0.01' \
  -H 'accept-language: en,pl;q=0.9,zh-TW;q=0.8,zh;q=0.7,ko;q=0.6,en-US;q=0.5,it;q=0.4' \
  -H 'content-type: application/x-www-form-urlencoded; charset=UTF-8' \
  -H 'cookie: WASReqURLOidcn631693810=https://ba5d95c1-us-south.lb.appdomain.cloud/; JSESSIONID=0000WkdXQBo28JRwDJ_gI2YNse3:e2caf162-b7c5-45c1-a51e-37a618eb5bd6; WASOidcSession=VVRYU2daMjF6V1ZoU2poVlU1ejBaN2tZSzliYVBZYi93UGMrVEN2NTVnMD0=:T25iUGprY2dlRnowZ2ZPVzY1M2NiQ09BaXQ3VmVES0dIRmhwR1Bhc2NGYz0=:bEF1VUQ0QjJUZW54Nk1MSGdGc0Y5KzFWZmRxL0ZMVkcvaGJuZ29xZ2Jiaz0=::MTcxMzQ0NDY1ODAwMA==_SfVqOdbgfofAAg9GsFtRpUjnr41nYthNUZuCOmnTpsw=; WAS_p143393543=kSkySdj0PMwessE3XJkfdzTXZuaH92J1jcuBxcd4V3dNcyfd/vcH9OGvlZCEkdPmqRuHw/z1OSBZKUoxLqZWA+Xb99PcKJ41i/+Mi7VIXJYbhU0y5cIYE2l3Zy06Hmm3qPWf35rERTIkJKe/2q6YR4ARQbSEF7hf/E/Zw0eqKiP4woaYlyxAivBMywFg4PSqxRM3w9fcv6KF8v1fKBuV1un8M+C7hwlxZ8pO0+oCT/Wi9RGIaWYqtzMcFkoQtAY+OyQ21zSe59+JS5L2x0NC0IBGnrTPQGZ7ygQZp4vfKYti5TxygOOufRRgCIqXjdHmAZvt1xMihFoaU0NxKz5uM0iqVplvVcRdhTtANzzW5MQQMCmDlMlcPZZApy/XgTYYHZpP0imFLk4MVYPPUUS0lLlIUqCB4Ca5FXa6AtV9NcO850A0urxnVuLyAhh03u7XlZnWKci8kfK2hbC68JU+uCEIillT/vHEr0yfxiEzqd97tu2JoiDMg34V/AzXPWITw3CuaQ9TzrWq0ivuqvoeR02nHoZK4IzgDnHcU68GKuR1OFRssDyrFnC7ekTnkr93PF7I4o/3ng9kxHMUI3E5Rw==; _DSS_session=bXZVT2lVaEQyY1hxUFdWSjFNdTNpK01tcnptN1Q1Yms4TURVaEdDVnhrTVJIeldsYTJabHY1U1NXazNCVlNuT1RRZUF5cGNFcFE3YnNtak1JUjZlUCttRGpLSlVKN3RQTi96WGRaS0s0NTNTUmRlUGJ3aFRneHpIdmtmL3crQWhCY3IrNGVkVnQ3cjRvQmdxNVAvNHhLZllkaTMyZUVvYytQZmc3eEt0MWk5c2tVd2NFVGVYK0JpdlNRQVducDZ0dlFya3JUNklVV2o1cHlOcmhhMGo4aGZLeTUwZWR1ZmhaYVJYV1NRMGZCYXIvczkxeFliekc1U2R6bmV2R1VNL2xMVVdKNlpSckRiLzhZNlJ3RDVyQnc9PS0tWHpWYWRiUU12RmNUMzdBOEdhTTdqQT09--5eeda042b110104d7891e369e7f92558fe7672a1' \
  -H 'origin: https://ba5d95c1-us-south.lb.appdomain.cloud/' \
  -H 'priority: u=1, i' \
  -H 'referer: https://ba5d95c1-us-south.lb.appdomain.cloud/sam/computers' \
  -H 'sec-ch-ua: "Chromium";v="124", "Google Chrome";v="124", "Not-A.Brand";v="99"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "Windows"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-origin' \
  -H 'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36' \
  -H 'x-csrf-token: gOQYtHjSWefYBNtMPahZWXiIILxiWdcl4Wx+KzzHFxrx5P87dBhqMPINonPs+gbpndvvVxcrvAOsoAP7FKU+Wg==' \
  -H 'x-requested-with: XMLHttpRequest' \
  --data-raw '_method=GET&gridUID=11a47529-5bfa-416f-b7b2-d9e1287f5e08&seq=0&limit=500&offset=0&countSwitch=1&columns%5B%5D=id&columns%5B%5D=processor.computer_type&columns%5B%5D=name&columns%5B%5D=last_seen&columns%5B%5D=os&columns%5B%5D=ip_address&columns%5B%5D=rollup.latest_scan&columns%5B%5D=computer_counts.installation_software_facts&time%5B%5D=2024-04-02T22%3A00%3A00Z&time%5B%5D=2024-04-03T22%3A00%3A00Z&criteria=%7B%22and%22%3A+%5B%5D%7D&_import_id=564' \
  --insecure

```

The import log attached in WLP log from only this single problematic request processing with following logging settings:

`<logging        traceSpecification="com.ibm.ws.security.openidconnect*=all=enabled:com.ibm.ws.security.oauth*=all=enabled:com.ibm.ws.webcontainer.security.*=all=enabled:org.apache.http.client.*=all=enabled:io.openliberty.security.oidcclientcore.*=all=enabled" maxFileSize="0" traceFormat="BASIC" />`
[problematic_request.log](https://github.com/OpenLiberty/open-liberty/files/15081367/problematic_request.log)

### PR DESCRIPTION
**Pull request by arunavemulapalli**
- oidc client updates
- for #28235 

Fixes #28235

### CODE REVIEW

**Comment by arunavemulapalli** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.security.oidc.client_fat.1,com.ibm.ws.security.oidc.client_fat.2,com.ibm.ws.security.oidc.client_fat.e2e,com.ibm.ws.security.oidc.client_fat.jaxrs,com.ibm.ws.security.oidc.client_fat.saml,com.ibm.ws.security.oidc.client_fat.spnego,com.ibm.ws.security.oidc.server_fat.app-passwords,com.ibm.ws.security.oidc.server_fat.app-passwords.DerbyDB.jwt,com.ibm.ws.security.oidc.server_fat.app-passwords.DerbyDB.opaque,com.ibm.ws.security.oidc.server_fat.app-passwords.LocalStore.jwt,com.ibm.ws.security.oidc.server_fat.app-passwords.LocalStore.opaque,com.ibm.ws.security.oidc.server_fat.app-tokens,com.ibm.ws.security.oidc.server_fat.app-tokens.DerbyDB.jwt,com.ibm.ws.security.oidc.server_fat.app-tokens.DerbyDB.opaque,com.ibm.ws.security.oidc.server_fat.app-tokens.LocalStore.jwt,com.ibm.ws.security.oidc.server_fat.app-tokens.LocalStore.opaque,com.ibm.ws.security.oidc.server_fat.clientregistration,com.ibm.ws.security.oidc.server_fat.config,com.ibm.ws.security.oidc.server_fat.config.oauth,com.ibm.ws.security.oidc.server_fat.config.oidc,com.ibm.ws.security.oidc.server_fat.endpoint.authorize,com.ibm.ws.security.oidc.server_fat.endpoint.coveragemap,com.ibm.ws.security.oidc.server_fat.endpoint.discovery,com.ibm.ws.security.oidc.server_fat.endpoint.end_session,com.ibm.ws.security.oidc.server_fat.endpoint.introspect,com.ibm.ws.security.oidc.server_fat.endpoint.revoke,com.ibm.ws.security.oidc.server_fat.endpoint.token,com.ibm.ws.security.oidc.server_fat.endpoint.userinfo,com.ibm.ws.security.oidc.server_fat.feature,com.ibm.ws.security.oidc.server_fat.granttype.jwt,com.ibm.ws.security.oidc.server_fat.gui.tokenMgmt,com.ibm.ws.security.oidc.server_fat.jaxrs,com.ibm.ws.security.oidc.server_fat.oidc,com.ibm.ws.security.oidc.server_fat.saml,com.ibm.ws.security.social_fat,com.ibm.ws.security.social_fat.LibertyOP.1,com.ibm.ws.security.social_fat.LibertyOP.2,com.ibm.ws.security.social_fat.OpenShift,com.ibm.ws.security.social_fat.delegated,com.ibm.ws.security.social_fat.multiProvider,com.ibm.ws.security.oidc.client_fat.backchannelLogout.1,com.ibm.ws.security.oidc.client_fat.backchannelLogout.2,com.ibm.ws.security.oidc.client_fat.backchannelLogout.saml.1,com.ibm.ws.security.oidc.client_fat.backchannelLogout.saml.2,com.ibm.ws.security.oidc.server_fat.backchannelLogout,com.ibm.ws.security.social_fat.LibertyOP.backchannelLogout.1,com.ibm.ws.security.social_fat.LibertyOP.backchannelLogout.2

**Comment by arunavemulapalli** [comment]
#libby
#build
#spawn.fullfat.buckets=com.ibm.ws.security.oidc.client_fat.1,com.ibm.ws.security.oidc.client_fat.2,com.ibm.ws.security.oidc.client_fat.e2e,com.ibm.ws.security.oidc.client_fat.jaxrs,com.ibm.ws.security.oidc.client_fat.saml,com.ibm.ws.security.oidc.client_fat.spnego,com.ibm.ws.security.oidc.server_fat.app-passwords,com.ibm.ws.security.oidc.server_fat.app-passwords.DerbyDB.jwt,com.ibm.ws.security.oidc.server_fat.app-passwords.DerbyDB.opaque,com.ibm.ws.security.oidc.server_fat.app-passwords.LocalStore.jwt,com.ibm.ws.security.oidc.server_fat.app-passwords.LocalStore.opaque,com.ibm.ws.security.oidc.server_fat.app-tokens,com.ibm.ws.security.oidc.server_fat.app-tokens.DerbyDB.jwt,com.ibm.ws.security.oidc.server_fat.app-tokens.DerbyDB.opaque,com.ibm.ws.security.oidc.server_fat.app-tokens.LocalStore.jwt,com.ibm.ws.security.oidc.server_fat.app-tokens.LocalStore.opaque,com.ibm.ws.security.oidc.server_fat.clientregistration,com.ibm.ws.security.oidc.server_fat.config,com.ibm.ws.security.oidc.server_fat.config.oauth,com.ibm.ws.security.oidc.server_fat.config.oidc,com.ibm.ws.security.oidc.server_fat.endpoint.authorize,com.ibm.ws.security.oidc.server_fat.endpoint.coveragemap,com.ibm.ws.security.oidc.server_fat.endpoint.discovery,com.ibm.ws.security.oidc.server_fat.endpoint.end_session,com.ibm.ws.security.oidc.server_fat.endpoint.introspect,com.ibm.ws.security.oidc.server_fat.endpoint.revoke,com.ibm.ws.security.oidc.server_fat.endpoint.token,com.ibm.ws.security.oidc.server_fat.endpoint.userinfo,com.ibm.ws.security.oidc.server_fat.feature,com.ibm.ws.security.oidc.server_fat.granttype.jwt,com.ibm.ws.security.oidc.server_fat.gui.tokenMgmt,com.ibm.ws.security.oidc.server_fat.jaxrs,com.ibm.ws.security.oidc.server_fat.oidc,com.ibm.ws.security.oidc.server_fat.saml,com.ibm.ws.security.social_fat,com.ibm.ws.security.social_fat.LibertyOP.1,com.ibm.ws.security.social_fat.LibertyOP.2,com.ibm.ws.security.social_fat.OpenShift,com.ibm.ws.security.social_fat.delegated,com.ibm.ws.security.social_fat.multiProvider,com.ibm.ws.security.oidc.client_fat.backchannelLogout.1,com.ibm.ws.security.oidc.client_fat.backchannelLogout.2,com.ibm.ws.security.oidc.client_fat.backchannelLogout.saml.1,com.ibm.ws.security.oidc.client_fat.backchannelLogout.saml.2,com.ibm.ws.security.oidc.server_fat.backchannelLogout,com.ibm.ws.security.social_fat.LibertyOP.backchannelLogout.1,com.ibm.ws.security.social_fat.LibertyOP.backchannelLogout.2

**Comment by arunavemulapalli** [comment]
#build

**Comment by arunavemulapalli** [comment]
#build

**Review by ayoho — APPROVED** [review]

**Pull request merged**
