### PR TITLE
Jms port fat 4

### PR DESCRIPTION
**Pull request by tbitonti**
Re-introduce initial changes, plus fixes for the case problem.

### CODE REVIEW

**Comment by tbitonti** [comment]
#build

**Review by Zech-Hein — COMMENTED** [review]
It looks like the PB is still failing with com.ibm.ws.messaging.open_jms20_fat:compileJava FAILED

**Comment by tbitonti** [comment]
#build

**Comment by tbitonti** [comment]
#build

**Comment by tbitonti** [comment]
#libby

**Review by Zech-Hein — APPROVED** [review]
Results look good on the last PB

**Pull request merged**
