### PR TITLE
New tack singletons

### PR DESCRIPTION
**Pull request by joe-chacko**

### CODE REVIEW

**Comment by joe-chacko** [comment]
#build

**Comment by joe-chacko** [comment]
#build

**Comment by joe-chacko** [comment]
#build

**Comment by joe-chacko** [comment]
#build

**Comment by joe-chacko** [comment]
#build

**Comment by joe-chacko** [comment]
#build

**Comment by joe-chacko** [comment]
#build

**Comment by joe-chacko** [comment]
#build

**Review by AndrewDJBanks — APPROVED** [review]

**Comment by joe-chacko** [comment]
#build

**Comment by AndrewDJBanks** [comment]
#build

**Comment by joe-chacko** [comment]
#build

**Pull request closed without merging**
