### PR TITLE
MYFACES-4594

### LINKED ISSUE #24683: Port MYFACES-4594
**Describe the bug**  
MYFACES-4594 was opened because by default `org.apache.myfaces.LOG_WEB_CONTEXT_PARAMS` defaults to `dev-only` which is defined here: https://myfaces.apache.org/#/core40

> Indicate if info logging all web config params should be done before initializing the webapp. With 4.0.0, the default changed from auto to dev-only. where logging no longer occurs in the production project stage (new default behavior). True enables logging in the production and development project stages. False disables logging.

If there are multiple applications deployed on a server and not all of them have the [ProjectStage](https://jakarta.ee/specifications/faces/4.0/apidocs/jakarta/faces/application/projectstage#PROJECT_STAGE_PARAM_NAME) set to `Development` the Context Parameters may not work correctly for all the applications deployed in the way that it should.  The first application to start would define the logging that would or wouldn't take place.

**Expected behavior**  
Each application should be able to define if context parameters are logged or not. 

**Diagnostic information:**  
 - OpenLiberty Version: 23.0.0.3
 - Affected feature(s): faces-4.0
 - Java Version: N/A

**Additional context**  
https://issues.apache.org/jira/browse/MYFACES-4594

### PR DESCRIPTION
**Pull request by pnicolucci**
fixes #24683

### CODE REVIEW

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
#libby #build

**Review by volosied — DISMISSED** [review]
Looks good to me.

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
#libby #build

**Review by volosied — APPROVED** [review]

**Pull request merged**
