### PR TITLE
update wsscxf saml.5 fat for java2sec

### PR DESCRIPTION
**Pull request by meiaus**
update com.ibm.ws.wssecurity_fat.wsscxf.saml.5 with java2sec

### CODE REVIEW

**Comment by meiaus** [comment]
#run-libby-bot

**Comment by meiaus** [comment]
#build

**Comment by meiaus** [comment]
#run-libby-bot

**Comment by meiaus** [comment]
Note:
Initial PB were submitted with the properties `global.debug.java2.sec`, which didn't enable java2 sec (per server messages.log).
The latest PB with `global.java2.sec` enabled java2 security as expected.

**Review by arunavemulapalli — APPROVED** [review]

**Pull request merged**
