### PR TITLE
Read in monitor-1.0 configuration to disable or enable the registered…

### LINKED ISSUE #27833: JAX-rs and RestfulWS monitor bundles' filters are still creating objects when REST is filtered out of monitor-1.0
**Describe the bug**  
When using `monitor-1.0` with `jaxrs-*` and the `monitor-1.0`'s filter attribute has filtered out the REST stat module, REST stat objects are still created, but are discarded and will be garbage collected. However, during high loads this can increase the memory consumption as it may take awhile for GC to occur.

**Steps to Reproduce**  

1. "Disable" REST stat component from monitor-1.0 and have jaxrs (or restful-ws) features enabled.
2. High load of REST requests

**Expected behavior**  

**Diagnostic information:**  
 - OpenLiberty Version: 20.0.0.4-...
 - Affected feature(s) [e.g. monitor-1.0]
 - Java Version: any java
 - server.xml configuration (WITHOUT sensitive information like passwords)
 - If it would be useful, upload the messages.log file found in `$WLP_OUTPUT_DIR/messages.log`

**Additional context**  

The JAX-RS/Restful-WS filters which are registered to the JAX-RS/RestfulWS runtime still executes during the runtime and attempts to register a stat object to the `MeterCollection<?>` even if `REST` is not listed explicitly as part of the monitor-1.0 `filter` attribute.  _(For context, when the monitor-1.0 filter attribute is used, only the monitoring components listed will be enabled and Mbeans created for those runtime components)_. 

In the scenario where REST it not listed in the monitor-1.0 filter attribute, these REST stat objects created by the JAX-RS/restful-WS filter are discarded and not registered to the `MeterCollection` and are subject to the Garbage Collection. However, if there is a high request load per second, these objects may linger and consume memory whilst the GC calculates which objects will be GCed.

Solution is to consult the monitor-1.0 configuration and stop the JAX-RS/Restful-WS filter from executing if the `REST` component is not specified in the monitor-1.0 filter attribute.

### PR DESCRIPTION
**Pull request by Channyboy**
… jax-rs/restful-ws filters to reduce memory usage

fixes #27833 
#build

### CODE REVIEW

**Comment by Channyboy** [comment]
#build
#libby

**Comment by Channyboy** [comment]
#build #libby

**Comment by Channyboy** [comment]
#build

**Review by fmhwong — APPROVED** [review]
LGTM

**Comment by Channyboy** [comment]
#libby

**Pull request merged**
