### PR TITLE
Servlet6.1 - Retain Quotes in Request Cookie Value

### LINKED ISSUE #29410: Servlet 6.1 - Quotes are part of the request cookie value
In request `Cookie` header, the quotes are part of cookie value.

Example: Request header
`Cookie: name1=\"value1\";  Path=/test`
 
Cookie getName() >  `name1`
Cookie getValue() > `"value1"`

### PR DESCRIPTION
**Pull request by pmd1nh**
fixes https://github.com/OpenLiberty/open-liberty/issues/29410

### CODE REVIEW

**Comment by pmd1nh** [comment]
#build
        #spawn.fullfat.buckets=io.openliberty.webcontainer.servlet.6.1.internal_fat,io.openliberty.webcontainer.servlet.6.0.internal_fat,com.ibm.ws.webcontainer.servlet.6.1_fat_toleration.lWAS,com.ibm.ws.webcontainer.servlet.6.0_fat_toleration.lWAS,com.ibm.ws.webcontainer_fat,com.ibm.ws.webcontainer.servlet.3.1_fat,com.ibm.ws.webcontainer.servlet.3.1_fat.2,com.ibm.ws.webcontainer.servlet.4.0_fat,com.ibm.ws.webcontainer_fat_part2,com.ibm.ws.webcontainer_fat_servlet31toleration,com.ibm.ws.webcontainer_fat_servlet31toleration_part2,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0_part2,com.ibm.ws.webcontainer_fat_lWAS,com.ibm.ws.webcontainer_fat_servlet31_webcontainerlWAS,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0.lWAS

**Comment by pmd1nh** [comment]
#build
#spawn.fullfat.buckets=io.openliberty.webcontainer.servlet.6.1.internal_fat,io.openliberty.webcontainer.servlet.6.0.internal_fat,com.ibm.ws.webcontainer.servlet.6.1_fat_toleration.lWAS,com.ibm.ws.webcontainer.servlet.6.0_fat_toleration.lWAS,com.ibm.ws.webcontainer_fat,com.ibm.ws.webcontainer.servlet.3.1_fat,com.ibm.ws.webcontainer.servlet.3.1_fat.2,com.ibm.ws.webcontainer.servlet.4.0_fat,com.ibm.ws.webcontainer_fat_part2,com.ibm.ws.webcontainer_fat_servlet31toleration,com.ibm.ws.webcontainer_fat_servlet31toleration_part2,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0_part2,com.ibm.ws.webcontainer_fat_lWAS,com.ibm.ws.webcontainer_fat_servlet31_webcontainerlWAS,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0.lWAS

**Comment by pmd1nh** [comment]
#build
#spawn.fullfat.buckets=io.openliberty.webcontainer.servlet.6.1.internal_fat,io.openliberty.webcontainer.servlet.6.0.internal_fat,com.ibm.ws.webcontainer.servlet.6.1_fat_toleration.lWAS,com.ibm.ws.webcontainer.servlet.6.0_fat_toleration.lWAS,com.ibm.ws.webcontainer_fat,com.ibm.ws.webcontainer.servlet.3.1_fat,com.ibm.ws.webcontainer.servlet.3.1_fat.2,com.ibm.ws.webcontainer.servlet.4.0_fat,com.ibm.ws.webcontainer_fat_part2,com.ibm.ws.webcontainer_fat_servlet31toleration,com.ibm.ws.webcontainer_fat_servlet31toleration_part2,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0_part2,com.ibm.ws.webcontainer_fat_lWAS,com.ibm.ws.webcontainer_fat_servlet31_webcontainerlWAS,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0.lWAS

**Comment by pmd1nh** [comment]
2 failed but unrelated tests
```
no component 107110 2 0
 com.ibm.ws.ui.tool.deploy_fat.gui.nd.rw.liberty FAT tests 3 2 0
  com.ibm.ws.ui.tool.deploy.fat.gui.nd.rw.liberty.tests.DeployLibertyServerTest 1 1 0 7 m 53 s 3
    verifyLibertyServerDeploy 1 1 0 7 m 53 s 1
  com.ibm.ws.ui.tool.deploy.fat.gui.nd.rw.liberty.tests.DirectURLDeployTest 1 1 0 7 m 56 s 2
    testDirectDeployURL 1 1 0 7 m 56 s 1
```

**Comment by pmd1nh** [comment]
#libby

**Comment by pmd1nh** [comment]
#build
#spawn.fullfat.buckets=io.openliberty.webcontainer.servlet.6.1.internal_fat,io.openliberty.webcontainer.servlet.6.0.internal_fat,com.ibm.ws.webcontainer.servlet.6.1_fat_toleration.lWAS,com.ibm.ws.webcontainer.servlet.6.0_fat_toleration.lWAS,com.ibm.ws.webcontainer_fat,com.ibm.ws.webcontainer.servlet.3.1_fat,com.ibm.ws.webcontainer.servlet.3.1_fat.2,com.ibm.ws.webcontainer.servlet.4.0_fat,com.ibm.ws.webcontainer_fat_part2,com.ibm.ws.webcontainer_fat_servlet31toleration,com.ibm.ws.webcontainer_fat_servlet31toleration_part2,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0_part2,com.ibm.ws.webcontainer_fat_lWAS,com.ibm.ws.webcontainer_fat_servlet31_webcontainerlWAS,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0.lWAS

**Comment by pmd1nh** [comment]
#build

**Comment by pmd1nh** [comment]
all WC passed.

one failed test  which I don't think it is related to this PR, but request build again

```
com.ibm.ws.jaxrs.2.0_fat FAT tests 415 0 1
 junit.framework.TestSuite 1 0 1 0 s 18
  com.ibm.ws.jaxrs20.fat.JAXRS20CallBackTest 1 0 1 0 s 1

java.lang.Exception: Errors/warnings were found in server com.ibm.ws.jaxrs.fat.callback-_EE11_FEATURES logs:
 <br>[10/4/24, 1:25:43:250 UTC] 0000002f com.ibm.ws.webcontainer31.osgi.response.WCOutputStream31     E SRVE9017E: An attempt to read or write failed because the stream has been closed.
	at componenttest.topology.impl.LibertyServer.checkLogsForErrorsAndWarnings(LibertyServer.java:3485)
```

**Review by pnicolucci — APPROVED** [review]

**Comment by pnicolucci** [comment]
#libby

**Comment by pmd1nh** [comment]
one failed but unrelated

```
java.lang.Exception: Errors/warnings were found in server com.ibm.ws.concurrent.fat.ejb logs:
 <br>[10/5/24, 4:05:19:275 UTC] 00000020 LogService-67-com.ibm.ws.app.manager                         E CWWKE0701E: bundle com.ibm.ws.app.manager:1.1.95.202410041253 (67)[com.ibm.ws.app.manager.internal.ApplicationConfigurator(182)] : The unsetAppRecycleComponent method has thrown an exception java.lang.NullPointerException: Cannot invoke "com.ibm.ws.runtime.update.RuntimeUpdateManager.createNotification(String)" because the return value of "com.ibm.ws.app.manager.internal.ApplicationConfigurator.access$400(com.ibm.ws.app.manager.internal.ApplicationConfigurator)" is null
	at componenttest.topology.impl.LibertyServer.checkLogsForErrorsAndWarnings(LibertyServer.java:3485)
	at com
```

**Pull request merged**
