### PR TITLE
update bcel

### PR DESCRIPTION
**Pull request by ngmr**

### CODE REVIEW

**Comment by ngmr** [comment]
#build

**Comment by ngmr** [comment]
#build

**Comment by clarkek123** [comment]
@joe-chacko @ngmr Did this make it into the GM driver of 22.0.0.13?

**Review by joe-chacko — DISMISSED** [review]

**Comment by joe-chacko** [comment]
#run-libby-bot

**Comment by clarkek123** [comment]
@ngmr and @joe-chacko We have exec approval to defer this until Liberty 23.0.0.1. The Liberty 2023 dates are at https://github.ibm.com/websphere/WS-CD-Open/wiki/2023-Liberty-Release-Schedule. To have the best chance of making 23.0.0.1 please have the PR delivered by DCUT of January 11, 2023.  Thanks

**Comment by joe-chacko** [comment]
#build again after updating one more feature to use the newer bcel

**Review by joe-chacko — DISMISSED** [review]

**Comment by joe-chacko** [comment]
#run-libby-bot

**Comment by joe-chacko** [comment]
#build again

**Comment by ngmr** [comment]
#build again, this now includes and uses the latest version of bcel without removing the prior version - a follow-on change (#23639) will remove that version once it's no longer in use.

**Comment by ngmr** [comment]
#build

**Review by joe-chacko — DISMISSED** [review]

**Comment by ngmr** [comment]
#build **again** (sigh)

**Comment by joe-chacko** [comment]
#build yet again

**Comment by joe-chacko** [comment]
#run-libby-bot

**Review by joe-chacko — APPROVED** [review]

**Pull request merged**
