### PR TITLE
Update Pages 4.0 API to M2

### LINKED ISSUE #27128: Pages 4.0: Update ErrorData to add support for the new attribute jakarta.servlet.error.method
`https://github.com/jakartaee/pages/pull/255`

### LINKED ISSUE #27756: Pages 4.0: Pull in the M2 version of the Pages API
https://repo1.maven.org/maven2/jakarta/servlet/jsp/jakarta.servlet.jsp-api/4.0.0-M2/

### PR DESCRIPTION
**Pull request by pnicolucci**
fixes #27756
fixes #27128

### CODE REVIEW

**Comment by pnicolucci** [comment]
#build

**Review by volosied — DISMISSED** [review]

**Comment by pnicolucci** [comment]
#build

**Review by volosied — APPROVED** [review]
Looks good

**Comment by pnicolucci** [comment]
#libby

**Pull request merged**
