### PR TITLE
Repeat MP41 test against MP60

### LINKED ISSUE #22201: Repeat existing tests against the microProfile-6.0 feature
These test buckets need to be repeated against the new microProfile-6.0 feature

https://github.com/OpenLiberty/open-liberty/tree/integration/dev/io.openliberty.microprofile.internal_fat
https://github.com/OpenLiberty/open-liberty/tree/integration/dev/io.openliberty.microprofile41.internal_fat
https://github.com/OpenLiberty/open-liberty/tree/integration/dev/io.openliberty.microprofile5.internal_fat

### PR DESCRIPTION
**Pull request by tevans78**
Add an extra MP60 repeat to io.openliberty.microprofile41.internal_fat
fixes https://github.com/OpenLiberty/open-liberty/issues/22201

### CODE REVIEW

**Comment by tevans78** [comment]
#pb

**Comment by tevans78** [comment]
#build

**Comment by tevans78** [comment]
#build

**Review by benjamin-confino — DISMISSED** [review]

**Comment by tevans78** [comment]
#libby

**Review by benjamin-confino — APPROVED** [review]

**Comment by tevans78** [comment]
#libby

**Pull request merged**
