### PR TITLE
Improve reading of MP Config properties in MP JWT

### PR DESCRIPTION
**Pull request by ayoho**
For issue #13879

### CODE REVIEW

**Comment by ayoho** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.security.jwt_fat.builder,com.ibm.ws.security.jwt_fat.consumer,com.ibm.ws.security.jwtsso_fat,com.ibm.ws.security.mp.jwt_fat_tck,com.ibm.ws.security.mp.jwt.1.1_fat

**Comment by ayoho** [comment]
#run-libby-bot
#build
#spawn.fullfat.buckets=com.ibm.ws.security.jwt_fat.builder,com.ibm.ws.security.jwt_fat.consumer,com.ibm.ws.security.jwtsso_fat,com.ibm.ws.security.mp.jwt_fat_tck,com.ibm.ws.security.mp.jwt.1.1_fat

**Comment by ayoho** [comment]
#run-libby-bot
#build
#spawn.fullfat.buckets=com.ibm.ws.security.jwt_fat.builder,com.ibm.ws.security.jwt_fat.consumer,com.ibm.ws.security.jwtsso_fat,com.ibm.ws.security.mp.jwt_fat_tck,com.ibm.ws.security.mp.jwt.1.1_fat

**Comment by ayoho** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.security.jwt_fat.builder,com.ibm.ws.security.jwt_fat.consumer,com.ibm.ws.security.jwtsso_fat,com.ibm.ws.security.mp.jwt_fat_tck,com.ibm.ws.security.mp.jwt.1.1_fat

**Review by teddyjtorres — APPROVED** [review]

**Pull request merged**
