### PR TITLE
Call secureRandom in LTPACrypto

### PR DESCRIPTION
**Pull request by acdemyers**
Change LTPA key to use use secureRandom during key generation.

### CODE REVIEW

**Comment by acdemyers** [comment]
#build

**Comment by acdemyers** [comment]
#build

**Comment by acdemyers** [comment]
#build

**Comment by acdemyers** [comment]
#build

**Comment by acdemyers** [comment]
#libby

**Comment by acdemyers** [comment]
#build

**Comment by acdemyers** [comment]
#build

**Review by arkarkala — APPROVED** [review]

**Comment by acdemyers** [comment]
#libby

**Comment by acdemyers** [comment]
#libby

**Pull request merged**
