### PR TITLE
Fix test failure caused by changing exception message text

### PR DESCRIPTION
**Pull request by scottkurz**

### CODE REVIEW

**Comment by scottkurz** [comment]
#build

**Comment by kinueng** [comment]
#link 251418

**Comment by kinueng** [comment]
Related to #2062

**Comment by scottkurz** [comment]
#build

**Comment by kinueng** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jbatch.rest_fat,com.ibm.ws.jbatch_fat,com.ibm.ws.ui.tool.javaBatch_fat.gui

**Comment by scottkurz** [comment]
Since Kin's build too has the ui excluded, I kicked off yet another build:
https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_nByMsBL-EeiStsw2He7iFw

**Comment by scottkurz** [comment]
The build at: https://wasrtc.hursley.ibm.com:9443/jazz/resource/itemOid/com.ibm.team.build.BuildResult/_xR_cYBKqEeiStsw2He7iFw  was good enough to verify.

It ran the batch FATs (incl. a couple in 'full' mode) 100% and also  com.ibm.ws.ui.tool.javaBatch_fat.gui FAT tests including the one with the previous failure (testInMemoryUnsupportedErrorPopup).

I didn't look at the CDI FAT failures since they couldn't have been caused by my change.  Also looks like there is a separate issue w/ the packaging build.

**Pull request merged**
