### PR TITLE
Add code to create manifest in PackageRunnable test

### PR DESCRIPTION
**Pull request by hlhoots**

### CODE REVIEW

**Comment by hlhoots** [comment]
#build

**Comment by hlhoots** [comment]
#build

**Review by cbridgha — COMMENTED** [review]
LGTM

**Comment by hlhoots** [comment]
#build

**Comment by hlhoots** [comment]
#build

**Comment by hlhoots** [comment]
last build failed with a gradle error on com.ibm.ws.jaxws.2.2.webcontainer_fat.  rebuilding with a rebase.

**Comment by hlhoots** [comment]
#run-libby-bot

**Review by cbridgha — APPROVED** [review]
Still looks good. :)

**Pull request merged**
