### PR TITLE
Rename the private servlet features to io.openliberty.servlet.api-XX

### PR DESCRIPTION
**Pull request by anjumfatima90**
for issue #13242

### CODE REVIEW

**Comment by anjumfatima90** [comment]
#build

**Comment by anjumfatima90** [comment]
#build

**Comment by anjumfatima90** [comment]
#build

**Comment by anjumfatima90** [comment]
#build

**Comment by anjumfatima90** [comment]
#build

**Comment by anjumfatima90** [comment]
#build

**Comment by anjumfatima90** [comment]
#build

**Comment by anjumfatima90** [comment]
#build

**Comment by anjumfatima90** [comment]
#build

**Comment by cbridgha** [comment]
#libby

**Pull request merged**
