### PR TITLE
Cleanup WebContainer bnd.bnd

### LINKED ISSUE #24888: Clean up com.ibm.ws.webcontainer/bnd.bnd

### PR DESCRIPTION
**Pull request by pnicolucci**
fixes #24888

### CODE REVIEW

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
One test failed due to an existing defect.

**Comment by pmd1nh** [comment]
look like only Contributors line and whitespaces cleanup?

**Review by pmd1nh — APPROVED** [review]

**Comment by pnicolucci** [comment]
> look like only Contributors line and whitespaces cleanup?

@pmd1nh  thanks for the review, mainly formatting. I did fix one spelling mistake `indepndent` -> `independent`

**Pull request merged**
