### PR TITLE
Update build tasks

### PR DESCRIPTION
**Pull request by rickettmwork**

### CODE REVIEW

**Comment by rickettmwork** [comment]
#build

**Comment by rickettmwork** [comment]
#build

**Comment by rickettmwork** [comment]
#build

**Comment by rickettmwork** [comment]
#build

**Comment by rickettmwork** [comment]
None of the PB failures were caused by changes in this PR.
The failing DHE check is fixed (but I'm not sure if there's a way to rerun it)

**Review by dave-waddling — DISMISSED** [review]

**Review by dave-waddling — APPROVED** [review]

**Comment by tevans78** [comment]
#libby

**Pull request merged**
