### PR TITLE
Remove usage and references to com.ibm.ws.timer

### PR DESCRIPTION
**Pull request by tjwatson**
- [ ] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [ ] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [ ] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

### CODE REVIEW

**Comment by tjwatson** [comment]
#build

**Comment by dazavala** [comment]
@tjwatson Can you remove the dependency on bundle `com.ibm.ws.timer` from `channelfw-1.0`?
 
`com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.channelfw-1.0.feature`

**Comment by dazavala** [comment]
@tjwatson Except for copyright changes I didn't see any issues while reviewing yesterday.

**Review by dazavala — APPROVED** [review]
Looks good.  Thanks, @tjwatson.

**Comment by tjwatson** [comment]
#build

**Comment by tjwatson** [comment]
#libby

**Pull request merged**
