### PR TITLE
Use the coordinator feature for tck tests

### PR DESCRIPTION
**Pull request by idlewis**
Enable a subset of TckTests.java in the main build.
Just enabling a subset of known working/good tests to start with to ensure some level of testing is being done

### CODE REVIEW

**Review by hutchig — APPROVED** [review]
LGTM

**Comment by idlewis** [comment]
#build

**Comment by idlewis** [comment]
#build

**Review by yongja79 — APPROVED** [review]
LGTM

**Comment by idlewis** [comment]
#build

**Comment by idlewis** [comment]
#run-libby-bot

**Pull request merged**
