### PR TITLE
Issue #17596: Use impl version in faces api bnd.bnd

### LINKED ISSUE #17596: Use ${Implementation-Version} in myfaces 2.3 and 3.0 API  bnd.bnd

### PR DESCRIPTION
**Pull request by pnicolucci**
fixes #17596

### CODE REVIEW

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Review by wtlucy — APPROVED** [review]
LGTM

**Comment by pnicolucci** [comment]
#run-libby-bot

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#run-libby-bot

**Review by volosied — APPROVED** [review]
Looks good to me as well.

**Pull request merged**
