### PR TITLE
Fix connection manager deadlock when purgePolicy=FailingConnectionOnly

### LINKED ISSUE #14657: Fix connection manager deadlock for purgePolicy=FailingConnectionOnly
**Describe the bug**
Need to rework the `com.ibm.ejs.j2c.PoolManager.validateConnections(ManagedConnectionFactory, boolean)` method to prevent connection validation from occurring on a different thread which can lead to a deadlock when purgePolicy=FailingConnectionOnly.

```
javacore
---
MTHREADINFO      "Default Executor-thread-36,serviceName=executor" J9VMThread:0x0000000004633600, omrthread_t:0x00007FD95863A210, java/lang/Thread:0x000000004F28D520, state:B, prio=5
.....
3XMTHREADBLOCK     Blocked on: com/ibm/db2/jcc/am/dt@0x00000000D00BFC78 Owned by: "Default Executor-thread-14,serviceName=executor" (J9VMThread:0x00000000023D7600, java/lang/Thread:0x0000000040FE5148)
3XMHEAPALLOC             Heap bytes allocated since last GC cycle=0 (0x0)
3XMTHREADINFO3           Java callstack:
4XESTACKTRACE                at com/ibm/db2/jcc/am/dt.close(dt.java:71)
4XESTACKTRACE                at com/ibm/ws/rsadapter/impl/WSRdbManagedConnectionImpl.destroy(WSRdbManagedConnectionImpl.java:2592)
4XESTACKTRACE                at com/ibm/ejs/j2c/MCWrapper.destroy(MCWrapper.java:1751)
4XESTACKTRACE                at com/ibm/ejs/j2c/FreePool.cleanupAndDestroyMCWrapper(FreePool.java:473)
4XESTACKTRACE                at com/ibm/ejs/j2c/FreePool.returnToFreePool(FreePool.java:273(Compiled Code))
4XESTACKTRACE                at com/ibm/ejs/j2c/PoolManager.release(PoolManager.java:951(Compiled Code))
4XESTACKTRACE                at com/ibm/db2/jcc/am/SqlSyntaxErrorException.getMessage(SqlSyntaxErrorException.java:54)
4XESTACKTRACE                at com/ibm/ws/rsadapter/AdapterUtil.translateSQLException(AdapterUtil.java:774)
4XESTACKTRACE                at com/ibm/ws/rsadapter/impl/WSRdbManagedConnectionImpl.validate(WSRdbManagedConnectionImpl.java:4286)
4XESTACKTRACE                at com/ibm/ws/rsadapter/impl/WSManagedConnectionFactoryImpl.getInvalidConnections(WSManagedConnectionFactoryImpl.java:1066)
4XESTACKTRACE                at com/ibm/ejs/j2c/PoolManager.validateConnections(PoolManager.java:473)
---
3XMTHREADINFO      "Default Executor-thread-14,serviceName=executor" J9VMThread:0x00000000023D7600, omrthread_t:0x00007FD9280C97A0, java/lang/Thread:0x0000000040FE5148, state:B, prio=5
.....
3XMTHREADBLOCK     Blocked on: com/ibm/db2/jcc/t4/T4XAConnection@0x00000000D00BF5A0 Owned by: "Default Executor-thread-36,serviceName=executor" (J9VMThread:0x0000000004633600, java/lang/Thread:0x000000004F28D520)
3XMHEAPALLOC             Heap bytes allocated since last GC cycle=0 (0x0)
3XMTHREADINFO3           Java callstack:
4XESTACKTRACE                at com/ibm/db2/jcc/am/Connection.clearWarnings(Connection.java:1871(Compiled Code))
5XESTACKTRACE                   (entered lock: com/ibm/db2/jcc/t4/T4XAConnection@0x00000000D00BF5A0, entry count: 1)
4XESTACKTRACE                at com/ibm/db2/jcc/am/dt.clearWarnings(dt.java:204(Compiled Code))
5XESTACKTRACE                   (entered lock: com/ibm/db2/jcc/am/dt@0x00000000D00BFC78, entry count: 1)
4XESTACKTRACE                at com/ibm/ws/rsadapter/jdbc/WSJdbcConnection.initialize(WSJdbcConnection.java:242(Compiled Code))
4XESTACKTRACE                at com/ibm/ws/rsadapter/jdbc/WSJdbcDataSource.getConnection(WSJdbcDataSource.java:154(Compiled Code))
4XESTACKTRACE                at com/ibm/ws/rsadapter/jdbc/WSJdbcDataSource.getConnection(WSJdbcDataSource.java:112(Compiled Code))
```

**Steps to Reproduce**
Only happens for purgePolicy=FailingConnectionOnly on fast systems

**Expected behavior**
Prevent validation from occurring on a connection that may be used on another thread, potentially causing deadlock.

**Diagnostic information:**
WAS Liberty core 19.0.0.12
JAVA SDK 8.0.6
@RHEL 7.4

### PR DESCRIPTION
**Pull request by gjwatts**
Modify the com.ibm.ejs.j2c.PoolManager.validateConnections method to prevent a potential deadlock from occurring on a connection that may be used on another thread when purgePolicy=FailingConnectionOnly.

Fixes #14657

### CODE REVIEW

**Comment by gjwatts** [comment]
#build

**Comment by gjwatts** [comment]
#build

**Comment by gjwatts** [comment]
#libbybot

**Review by jmstephensgit — APPROVED** [review]

**Comment by gjwatts** [comment]
#libbybot

**Comment by gjwatts** [comment]
#build

**Comment by gjwatts** [comment]
I had made a couple of changes that Kyle recommended and then rebuilt.  The testing passed, so merging changes.

**Pull request merged**
