### PR TITLE
fix: testEscapeCharacters on PostgreSQL

### PR DESCRIPTION
**Pull request by KyleAure**
- [x] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [x] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [x] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

refactor: swap to new DatabaseContainerUtil methods
refactor: simplify custom postgresql class for database rotation
fix: skip testEscapeCharacters on postgresql as impossible

### CODE REVIEW

**Review by njr-11 — DISMISSED** [review]
Approving the disablement of the test to avoid build breaks on PostgreSQL.  However, please open an issue for the JPA team to look into whether this is actually an EclipseLink bug and note the issue # around `@SkipIfSysProp(DB_Postgres)` to help with reenablement if they fix it.

**Comment by KyleAure** [comment]
#build ([view Open Liberty Personal Build](https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?pipelineId=af0a93f6-f244-4f6b-a174-c8e1c7a80a60) - :x: completed with errors/failures.)

_Note: Target locations of links might be accessible only to IBM employees._

**Comment by KyleAure** [comment]
#build - redo personal build after failure due to network issue. ([view Open Liberty Personal Build](https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?pipelineId=feee977c-58a6-4196-9173-7db808c30aac) - :x: completed with errors/failures.)

_Note: Target locations of links might be accessible only to IBM employees._

**Comment by KyleAure** [comment]
#build - redo personal build.  Soft merge conflict with the change made to the PostgreSQL Container.  I'll make that change later. ([view Open Liberty Personal Build](https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?pipelineId=febccc26-d17b-431b-9df9-d264d791635f) - :x: completed with errors/failures.)

_Note: Target locations of links might be accessible only to IBM employees._

**Comment by KyleAure** [comment]
#build - personal build fixed error ([view Open Liberty Personal Build](https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?pipelineId=32ca4dea-0501-46d7-a935-4cc958de8e06) - :white_check_mark: completed successfully!)

_Note: Target locations of links might be accessible only to IBM employees._

**Review by njr-11 — APPROVED** [review]

**Pull request merged**
