### PR TITLE
variable in include location can be empty

### PR DESCRIPTION
**Pull request by rsherget**
If include tag has a location of a variable and that variable is empty, it should display a warning but not fail

### CODE REVIEW

**Comment by rsherget** [comment]
#build

**Comment by rsherget** [comment]
#build

**Comment by rsherget** [comment]
#build

**Review by cbridgha — DISMISSED** [review]
Looks good - only comment is to add 2024 on the copyrights

**Review by hlhoots — DISMISSED** [review]
LGTM

**Comment by rsherget** [comment]
#build

**Comment by rsherget** [comment]
#libby

**Comment by rsherget** [comment]
The build's errors/failures were not related to the code changes.

**Review by tbitonti — APPROVED** [review]

**Comment by rsherget** [comment]
#libby

**Pull request merged**
