### PR TITLE
Do not associate vendor connection pool metrics with an application for mpMerics-3.0 and mpMetrics-4.0

### PR DESCRIPTION
**Pull request by Channyboy**
- [x] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [x] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [x] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

################################################################################################

### CODE REVIEW

**Comment by Channyboy** [comment]
#build #libby ([view Open Liberty Delivery Requirements Verification](https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?pipelineId=6726f11d-cdb4-4d41-a388-c9bea698501d) - :white_check_mark: completed successfully!) ([view Open Liberty Personal Build](https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?pipelineId=181824a8-6133-4d50-8003-e712625ce529) - :x: completed with errors/failures.)

_Note: Target locations of links might be accessible only to IBM employees._

_Note: Target locations of links might be accessible only to IBM employees._

**Review by pgunapal — APPROVED** [review]
LGTM

**Comment by Channyboy** [comment]
#build ([view Open Liberty Personal Build](https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?pipelineId=65e7d636-ed7f-429d-b901-5bf46aa880a8) - :white_check_mark: completed successfully!)

_Note: Target locations of links might be accessible only to IBM employees._

**Comment by Channyboy** [comment]
Part of #30383

**Pull request merged**
