### PR TITLE
Issue #20720: Test distributed authentication cache for OIDC and OAuth2.

### LINKED ISSUE #20720: SEC 380: Test OAUTH with distributed authentication cache
Perform distributed authentication cache testing with the oauth-2.0 feature.

### LINKED ISSUE #20721: SEC 380: Test OIDC with distributed authentication cache
Perform distributed authentication cache testing with the openidConnectClient-1.0 feature.

### PR DESCRIPTION
**Pull request by jvanhill**
fixes #20720 
fixes #20721

### CODE REVIEW

**Comment by jvanhill** [comment]
#build

**Comment by jvanhill** [comment]
#build

**Comment by jvanhill** [comment]
#build

**Comment by jvanhill** [comment]
#build

**Comment by jvanhill** [comment]
#libby

**Review by kristip17 — APPROVED** [review]

**Pull request merged**
