### PR TITLE
Refactor different delay tests

### PR DESCRIPTION
**Pull request by sakerl**
- [x] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [ ] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [ ] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

################################################################################################

################################################################################################

### CODE REVIEW

**Comment by sakerl** [comment]
for #28009

**Comment by sakerl** [comment]
#build

**Comment by sakerl** [comment]
!build

**Review by ngmr — APPROVED** [review]

**Comment by sakerl** [comment]
!libby

**Comment by sakerl** [comment]
#build

**Comment by sakerl** [comment]
#libby

**Comment by ngmr** [comment]
!build

**Comment by ngmr** [comment]
!libby

**Comment by sakerl** [comment]
#build

**Comment by sakerl** [comment]
!libby

**Pull request merged**
