### PR TITLE
update quartz

### PR DESCRIPTION
**Pull request by benjamin-confino**
Missed a file when updating to an newer version of quartz

The other changes were due to dependnecy conflicts.

### CODE REVIEW

**Comment by benjamin-confino** [comment]
#build

**Comment by benjamin-confino** [comment]
#build

**Review by tevans78 — APPROVED** [review]

**Comment by benjamin-confino** [comment]
#libby

**Comment by benjamin-confino** [comment]
#libby

**Comment by benjamin-confino** [comment]
#build

**Review by tevans78 — APPROVED** [review]

**Comment by benjamin-confino** [comment]
#build

**Comment by benjamin-confino** [comment]
#libby

**Pull request merged**
