### PR TITLE
Update SmallRye Config for ConfigProperties bug fixes

### PR DESCRIPTION
**Pull request by Joseph-Cass**
Consumes and tests the fixes for the following SmallRye Config issues:
- https://github.com/smallrye/smallrye-config/issues/475
- https://github.com/smallrye/smallrye-config/issues/477
- https://github.com/smallrye/smallrye-config/issues/476

### CODE REVIEW

**Comment by Joseph-Cass** [comment]
#build
#spawn.fullfat.buckets=io.openliberty.microprofile.config.2.0.internal_fat_tck,io.openliberty.microprofile.config.2.0.internal_fat,com.ibm.ws.microprofile.config.1.1_fat,com.ibm.ws.microprofile.config.1.2_fat,com.ibm.ws.microprofile.config.1.3_fat,com.ibm.ws.microprofile.config.1.4_fat

**Review by Emily-Jiang — APPROVED** [review]
LGTM!

**Comment by Joseph-Cass** [comment]
The build failure seems unrelated, but I'm not sure. Going to try again just to be sure:

#build
#spawn.fullfat.buckets=io.openliberty.microprofile.config.2.0.internal_fat_tck,io.openliberty.microprofile.config.2.0.internal_fat,com.ibm.ws.microprofile.config.1.1_fat,com.ibm.ws.microprofile.config.1.2_fat,com.ibm.ws.microprofile.config.1.3_fat,com.ibm.ws.microprofile.config.1.4_fat

**Comment by Joseph-Cass** [comment]
Both PB's each failed from 2 different OAuth20 unit tests:

- `OAuth20EndpointServicesTest.testRevokeWrongClient`

- `OAuth20EndpointServicesTest.testHandleOAuthRequestNoOAuth20Provider`

I've checked the defects list and couldn't find anything similar. I don't think these code changes could cause this, but then again, I know nothing about OAuth.

I'm going to try a rebase and see if that helps things...

**Comment by Joseph-Cass** [comment]
#build
#spawn.fullfat.buckets=io.openliberty.microprofile.config.2.0.internal_fat_tck,io.openliberty.microprofile.config.2.0.internal_fat,com.ibm.ws.microprofile.config.1.1_fat,com.ibm.ws.microprofile.config.1.2_fat,com.ibm.ws.microprofile.config.1.3_fat,com.ibm.ws.microprofile.config.1.4_fat

**Comment by ayoho** [comment]
#build

**Pull request closed without merging**
