### PR TITLE
Changing service name

### PR DESCRIPTION
**Pull request by tonyreigns**
Fixes: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.workitem.viewWorkItem&id=300670

### CODE REVIEW

**Comment by tonyreigns** [comment]
#build

**Review by donbourne — APPROVED** [review]

**Comment by Yas-Franco** [comment]
The build did not run the affected test for MPTelemetry-2.0. Running it in FULL now

**Comment by Yas-Franco** [comment]
#build
#spawn.fullfat.buckets=io.openliberty.microprofile.telemetry.1.0.internal_fat,io.openliberty.microprofile.telemetry.1.0.internal.container_fat,io.openliberty.microprofile.telemetry.1.0.internal_fat_tck,io.openliberty.microprofile.telemetry.1.1.internal_fat_tck,io.openliberty.microprofile.telemetry.2.0.internal_fat_tck

**Review by Yas-Franco — APPROVED** [review]
Good spot! Thank you Anthony

**Pull request merged**
