### PR TITLE
Make jwtSso-1.0 work with Jakarta EE 9

### LINKED ISSUE #19150: Update jwtSso-1.0 feature to work with Jakarta EE 9 and MP 5.0
jwtSso-1.0 feature depends on MP and Jakarta APIs.  As such it will not work until it is updated to work with EE9 and MP 5.0 APIs.

### PR DESCRIPTION
**Pull request by jhanders34**
- Create private features for Jakarta EE 9 and for previous versions
- Remove jwtSsoToken auto feature and roll its contents into jwtSso-1.0 since it is always enabled when jwtSso-1.0 is enabled.
- Add jwt-1.2 API feature dependency to support JWT 1.2 with jwtSso-1.0
- Make auto feature to bring in jsonp-1.0 or 1.1 if not using Jakarta EE 9.
-  Update FATs that test jwtSso-1.0 to run with Jakarta EE 9 and mpJwt-2.0

### CODE REVIEW

**Comment by jhanders34** [comment]
#build

**Comment by jhanders34** [comment]
#libby #build

**Comment by jhanders34** [comment]
#libby #build

**Comment by jhanders34** [comment]
#libby #build

**Review by jvanhill — APPROVED** [review]

**Comment by jhanders34** [comment]
#libby #build

**Comment by jhanders34** [comment]
#libby

**Pull request merged**
