### PR TITLE
Simplify logic to not use lambdas and method handles

### PR DESCRIPTION
**Pull request by jhanders34**
- Instead of using stream() on a Collection, just use a formal for loop with if statement instead of filter.

- [x] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [x] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [x] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

### CODE REVIEW

**Comment by jhanders34** [comment]
#build

**Comment by contbld** [comment]
Your personal pipeline request is at https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=2878f6b4-f1eb-4b25-bb0b-07c42fdcefce

Target locations of links might be accessible only to IBM employees.

**Comment by contbld** [comment]
<h3>Code analysis and actions</h3>
DO NOT DELETE THIS COMMENT.

- 1 product code files were changed.

**Comment by tjwatson** [comment]
I am surprised this code is a hot code path that would show slowdown with lambdas.

**Comment by jhanders34** [comment]
> I am surprised this code is a hot code path that would show slowdown with lambdas.

I haven't profiled it at all, I just saw it when inspecting the code for the feature I gave you performance focal approval.

**Review by tjwatson — APPROVED** [review]

**Comment by contbld** [comment]
https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=2878f6b4-f1eb-4b25-bb0b-07c42fdcefce completed successfully!

**Pull request merged**
