### PR TITLE
Add ClockProviderTest to the checkpoint beanvalidation fat

### PR DESCRIPTION
**Pull request by dazavala**
For issue #21321

The ClockProviderTest provides the following coverage to the checkpoint bean validation fat:

- Verify a basic temporal constraint for a java bean within checkpoint and restore. The test ensures the clock provided by the default validation configuration tracks time as expected within checkpoint and restore, and that during checkpoint, the clock must does not "fix" within the default clock provider nor the temporal constraint validators.
- Verify the system time zone and bval time zone ID do not change between checkpoint and restore. Java CRIU support does not adjust the system time zone in restored JVMs at this time.
- [Extra] Verify JNDI lookup of bean validation resources. JNDI lookup is implicitly verified by resource injection, but has not been formally verified by any checkpoint bean validation test.

### CODE REVIEW

**Comment by dazavala** [comment]
#build

**Comment by dazavala** [comment]
#build

**Comment by dazavala** [comment]
An InstantOn build is submitted.  This PR is ready for review.

**Comment by dazavala** [comment]
#build

**Comment by dazavala** [comment]
#libby

**Comment by dazavala** [comment]
#build

**Comment by dazavala** [comment]
#build
Previous build failed to pull `jakarta.websocket:jakarta.websocket-client-api:2.1.0` from Artifactory.

**Review by sebratton — APPROVED** [review]
LGTM. My only suggestion is if you have any other changes to make, then clean up validation checks in bval.v20.web.FieldValidatedBean that aren't explictly being tested for with this addition. It looks like many are already covered in MethodReturnValidatedBean. Also, if you need to make any other changes unrelated to this review,t hen there is an eclipse warning about accessing static method in ebval.v20.web.BeanVal20TestServlet that can be cleaned up.

**Comment by dazavala** [comment]
#libby

**Comment by dazavala** [comment]
#libby

**Pull request merged**
