### PR TITLE
JakartaEE 10: Remove handling of new reference elements from EJB descriptor parsing.

### LINKED ISSUE #20386: JakartaEE 10: Revert EJB 4.0 Schema and DD Parser Changes
A new version of the EJB specification will not be provided for Jakarta EE 10.  The EJB 4.0 must not be updated for EJB 10, as the spec has not been updated to support it.

The following PR updated the EJB 4.,0 schema to incorrectly reference a Jakarta EE 10 schema.  Also multiple EJB DD perser files were incorrectly updated to introduce a version 5.0; as well as tests, etc.

https://github.com/OpenLiberty/open-liberty/pull/20318

All of the changes for EJB 4.0 need to be reverted.  The EJB 4.0 schema should not support any new Jakarta EE 10 elements; that would require a new version of the EJB specification. This is consistent with EJB 3.2, which was not updated for Java EE 8.

### PR DESCRIPTION
**Pull request by tbitonti**
Removed test cases:

* com.ibm.ws.javaee.ddmodel.ejb.EJBJarTest
  - testGetVersionID()
    - Removed pseudo ejb-5.0 case
* com.ibm.ws.javaee.ddmodel.ejb.EJBJarEnterpriseBeanTest
  - testEE10MessageDrivenEJB50()
  - testEE10EntityEJB50()
  - testEE10SessionEJB50()
* com.ibm.ws.javaee.ddmodel.ejb.EJBJarInterceptorTest
  - testEE10InterceptorsEJB50()
  
fixes #20386

### CODE REVIEW

**Comment by tbitonti** [comment]
#libby
#build

**Comment by tbitonti** [comment]
These tests already verify that the new elements are not accepted when the EJB schema version is 4.0 and the platform version is pre-EE10:

- com.ibm.ws.javaee.ddmodel.ejb.EJBJarEnterpriseBeanTest
  - testEE10MessageDrivenEJB40()
  - testEE10EntityEJB40()
  - testEE10SessionEJB40()

- com.ibm.ws.javaee.ddmodel.ejb.EJBJarInterceptorTest
  - testEE10InterceptorsEJB40()

These missing tests were added:

- com.ibm.ws.javaee.ddmodel.app.AppTest
  - testEE10ContextServiceApp90()
  - testEE10ManagedExecutorApp90()
  - testEE10ManagedScheduledExecutorApp90()
  - testEE10ManagedThreadFactoryApp90()
  - testEE10ContextServiceApp100()
  - testEE10ManagedExecutorApp100()
  - testEE10ManagedScheduledExecutorApp100()
  - testEE10ManagedThreadFactoryApp100()
  -

**Review by tkburroughs — CHANGES_REQUESTED** [review]
PR 20318 Also changed the following file; not sure what it is for, but it seems incorrect for ejb-jar_4_0.xsd

 dev/com.ibm.ws.javaee.dd/resources/com/ibm/ws/javaee/dd/schemas/diff_jakartaee_10-9.txt

It seems to be showing differences between EE 10 and EE 9, and ejb-jar_4_0.xsd should have no differences.  Perhaps this file is unimportant though?

Also, the ejb-jar_4_0.xsd file still contains an incorrect reference to EE 10:

```
<xsd:include schemaLocation="jakartaee_10.xsd"/>
```

This should be jakartaee_9.xsd, as updated here: https://github.com/eclipse-ee4j/jakartaee-schemas/commit/f0bc0a790065b379172fc1c8a07431c221f79b94

**Comment by tbitonti** [comment]
#libby
#build

**Review by tkburroughs — APPROVED** [review]

**Pull request merged**
