### PR TITLE
update retryInterval description per fail over

### PR DESCRIPTION
**Pull request by njr-11**
retryInterval description needs an update because it only applies to the server where the failure happened.

### CODE REVIEW

**Comment by andrea-pichler** [comment]
No L2 message review requested

**Comment by njr-11** [comment]
@dmuelle I have mostly update the message as requested 
https://github.com/OpenLiberty/open-liberty/pull/10485/commits/100f4461a5b57ac5d8e355849983314ad17d710c
except for the portion, "servers that did not see the failure initially are configured to retry at their next poll", which didn't make sense anymore, so I updated that portion differently.  Let me know if you have any issues with that. Otherwise, please complete the review.

**Comment by njr-11** [comment]
#build

**Comment by njr-11** [comment]
#run-libby-bot

**Pull request merged**
