### PR TITLE
Add support for session interfaces in javaee ddmodels

### PR DESCRIPTION
**Pull request by brenthdaniel**
Removing LibertyNotInUse annotation and adding support for session.getInterfaces() in the javaee ddmodel overrides.

### CODE REVIEW

**Comment by brenthdaniel** [comment]
#build

**Comment by brenthdaniel** [comment]
#13921

**Review by ManasiGandhi — COMMENTED** [review]
No changes needed

**Comment by brenthdaniel** [comment]
#build

**Review by tbitonti — CHANGES_REQUESTED** [review]
There seems to be a typo in metatype/v1.0.0: "inteface" instead of "interface".

<OCD id="com.ibm.ws.javaee.dd.commonbnd.Interceptor" name="%SessionMetatype.**inteface**.name" description="%SessionMetatype.interface.desc" ibm:extends="com.ibm.ws.javaee.dd.commonbnd.RefBindingsGroup">

Minor nit: In a number of places, the code fully qualifies types, e.g., "java.lang.String bindingName" in InterfaceComponentImpl.java.

**Review by tbitonti — APPROVED** [review]

**Comment by brenthdaniel** [comment]
#build

**Comment by olendvcook** [comment]
#build

**Comment by brenthdaniel** [comment]
#run-libby-bot

**Pull request merged**
