### PR TITLE
Switch MicroProfile 5.0 and MP Context Propagation 1.3 to GA

### PR DESCRIPTION
**Pull request by tevans78**
This PR switches 10 public features to GA and changes the MP packaging for OL to be GA
#build

### CODE REVIEW

**Review by njr-11 — APPROVED** [review]
mpContextPropagation-1.3 updates look good

**Review by mbroz2 — APPROVED** [review]

**Comment by tevans78** [comment]
Forced-push was only to rebase on integration after final API updates were made. No actual changes to this PR.
#build

**Review by jhanders34 — COMMENTED** [review]
Were you planning on undoing part of https://github.com/OpenLiberty/open-liberty/pull/19017/commits/f65a4054c78f5e34de46f401c19fb287d3718d3f with this PR so that the mpContextPropagation API jar is in the dev directory instead of the lib directory?

**Review by jhanders34 — COMMENTED** [review]
Should revert of #18454 be part of this PR as well, or it should be a separate PR?  Reverting that PR resolves #18476.  FYI @andymc12 to see as well.

**Comment by tevans78** [comment]
@jhanders34 Well remembered, good questions!

**Comment by tevans78** [comment]
> Were you planning on undoing part of [f65a405](https://github.com/OpenLiberty/open-liberty/commit/f65a4054c78f5e34de46f401c19fb287d3718d3f) with this PR so that the mpContextPropagation API jar is in the dev directory instead of the lib directory?

Fixed this one

**Comment by tevans78** [comment]
> Should revert of #18454 be part of this PR as well, or it should be a separate PR? Reverting that PR resolves #18476. FYI @andymc12 to see as well.

We agreed that this issue should not hold up the release of MP 5.0... but there is an issue open to add the integration back in properly.

**Comment by tevans78** [comment]
#build

**Comment by tevans78** [comment]
#libby

**Pull request merged**
