### PR TITLE
WI#1296: Rename JPA 2.2 Container + CDI 2.0 Autofeature and remove ve…

### PR DESCRIPTION
**Pull request by jgrassel**
…rsion numbers

Signed-off-by: Joe Grassel <jgrassel@us.ibm.com>

### CODE REVIEW

**Comment by jgrassel** [comment]
#build

**Comment by jgrassel** [comment]
#build

**Comment by jgrassel** [comment]
Kicked off https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_vP0hswdkEeiIX6lO4t6XVQ

**Comment by jgrassel** [comment]
https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_jqBcgBDWEeiStsw2He7iFw&tab=com.ibm.team.build.web.ui.internal.editors.result.test.TestProvider

No longer has feature checker failures.  Looks like the failures that are there are just a sign of the state of master right now.

**Comment by Jay-A-W** [comment]
PR 10187 in commercial liberty needs to be in master before this PR can be merged. 
It has caused a hard build break in LAOS Continuous as of build (https://wasrtc.hursley.ibm.com:9443/jazz/resource/itemOid/com.ibm.team.build.BuildResult/_xyrAEBHEEeiStsw2He7iFw).
Reverting PR.

**Pull request merged**
