### PR TITLE
Fix issue #4414 for feature resolver false conflicts

### PR DESCRIPTION
**Pull request by tjwatson**

### CODE REVIEW

**Comment by tjwatson** [comment]
Libby please try an initial test #build for this PR

**Comment by tjwatson** [comment]
This is for issue #4414.

**Comment by dazavala** [comment]
Tom, I completed my review and would approve these changes if/when you're ready to merge.  I expect we'll follow-up on the new unittest case and the personal build result.

**Comment by tjwatson** [comment]
#build

**Comment by tjwatson** [comment]
#build

**Pull request merged**
