### PR TITLE
Fix Faces 4.1 API to Pass Signature Tests

### LINKED ISSUE #30217: MYFACES-4692 - Fix 4.1 Signature Tests
ActionSource and ActionSource2 need some rework, but otherwise, the rest of the API is good. 

Note: This needs to be merged upstream.

```
Missing Methods
---------------

jakarta.faces.component.ActionSource2:  method public abstract jakarta.el.MethodExpression jakarta.faces.component.ActionSource2.getActionExpression()
jakarta.faces.component.ActionSource2:  method public abstract void jakarta.faces.component.ActionSource2.setActionExpression(jakarta.el.MethodExpression)

Added Methods
-------------

jakarta.faces.component.ActionSource2:  method public jakarta.el.MethodExpression jakarta.faces.component.ActionSource.getActionExpression()
jakarta.faces.component.ActionSource2:  method public void jakarta.faces.component.ActionSource.setActionExpression(jakarta.el.MethodExpression)


Missing Methods
---------------

jakarta.faces.component.ActionSource2:  method public abstract jakarta.el.MethodExpression jakarta.faces.component.ActionSource2.getActionExpression()
jakarta.faces.component.ActionSource2:  method public abstract void jakarta.faces.component.ActionSource2.setActionExpression(jakarta.el.MethodExpression)

Added Methods
-------------

jakarta.faces.component.ActionSource2:  method public jakarta.el.MethodExpression jakarta.faces.component.ActionSource.getActionExpression()
jakarta.faces.component.ActionSource2:  method public void jakarta.faces.component.ActionSource.setActionExpression(jakarta.el.MethodExpression)
```

### PR DESCRIPTION
**Pull request by volosied**
- [x] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [x] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [x] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

fixes #30217

### CODE REVIEW

**Comment by volosied** [comment]
#build

**Comment by contbld** [comment]
Your personal pipeline request is at https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=4a18e3a9-676b-4d12-88a0-2a76e1803de3

Target locations of links might be accessible only to IBM employees.

**Comment by contbld** [comment]
<h3>Code analysis and actions</h3>
DO NOT DELETE THIS COMMENT.

- 1 infrastructure code files were changed.

- 2 product code files were changed.

**Comment by contbld** [comment]
https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=4a18e3a9-676b-4d12-88a0-2a76e1803de3 completed successfully!

**Comment by volosied** [comment]
#build

**Comment by contbld** [comment]
Your personal pipeline request is at https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=abcc4163-0946-488f-b752-278227c716d4

Target locations of links might be accessible only to IBM employees.

**Comment by volosied** [comment]
#build

**Comment by contbld** [comment]
Your personal pipeline request is at https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=425cfc72-5bb5-427d-8a16-e2298796f2e7

Target locations of links might be accessible only to IBM employees.

**Comment by contbld** [comment]
<h3>Code analysis and actions</h3>
DO NOT DELETE THIS COMMENT.

- 1 infrastructure code files were changed.

- 3 product code files were changed.

**Comment by contbld** [comment]
<h3>Code analysis and actions</h3>
DO NOT DELETE THIS COMMENT.

- 1 infrastructure code files were changed.

- 3 product code files were changed.

**Comment by contbld** [comment]
https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=abcc4163-0946-488f-b752-278227c716d4 has errors/failures.

**Comment by contbld** [comment]
https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=425cfc72-5bb5-427d-8a16-e2298796f2e7 has errors/failures.

**Review by jhanders34 — APPROVED** [review]

**Pull request merged**
