### PR TITLE
retry deserialization with jakarta classes

### LINKED ISSUE #14324: Can EJB timers persisted in Java EE still be used in Jakarta EE?
When customers move from Java EE to Jakarta EE, many of them will have EJB persistent timers stored in a database, which are scheduled to continue running.  Liberty will see these timers and try to run them.  Some might work. But if we don't take any action, many timers will fail to deserialize due to meeting any of the following conditions:

- `javax.ejb.ScheduleExpression` is used to schedule the timer
- timer raises an EE spec exception such as `javax.ejb.EJBException` (EJB Container itself raises this)
- info object that is supplied upon scheduling is a Java EE spec class instance

When customers have multiple servers that share the same database location for timers (which is the solution for failover) and they move their servers from Java EE to Jakarta EE without taking everything down at once, there will inevitably be a temporary mixture of servers using Java EE and Jakarta EE at the same time.  During this time, the scenario could also exist in reverse, where a timer is persisted in Jakarta EE and is read by a server that is still running in Java EE.

A. The easy answer for us (Make customers cancel and recreate timers) is at best inconvenient and at worst completely impractical for customers.  For customers with applications that programmatically schedule timers based upon the input of their users, there is no way to recreate the timer because the scheduling information exists only within the persisted timer entry.

B. It might be possible to write a tool to read timers from the database, deserialize them, transform classes to Jakarta, and reserialize them.  Is there a way to run the transformer from within Liberty against a stream of bytes?  As far as I am aware, we are not shipping the transformer as part of Liberty.  This likely wouldn't work anyway because we don't have a separate byte stream for the timer info or ScheduleExpression. We have a byte stream for an EJB container class, which in turn deserializes the timer info and SchedulExpression instances directly without the intermediate step of having a byte stream in between.

C. The Liberty serialization service could intercept failures to load Jakarta EE (or Java EE) classes, and upon failure, attempt to load the matching class from the other spec instead.  I prototyped this and demonstrated it to work in at least one scenario.  But is it safe/desirable to do in all cases, or even if we limit it to during timer deserialization?

Temporary edits to com.ibm.ws.serialization.DeserializationObjectInputStream.loadClass(String):

```
    protected Class<?> loadClass(String name) throws ClassNotFoundException {
        try {
            ...
            return classLoader.loadClass(name);
        } catch (ClassNotFoundException e) {
            if (name != null) {
                String retryName;
                if (name.startsWith("javax."))
                    retryName = "jakarta." + name.substring(6);
                else if (name.startsWith("jakarta."))
                    retryName = "javax." + name.substring(8);
                else
                    retryName = null;
                if (retryName != null)
                    try {
                        return classLoader.loadClass(retryName);
                    } catch (ClassNotFoundException x) {
                        // alternative spec name not found either, let the original error be raised
                    }
            }
            ...
            throw e;
        }
    }
```

Also check with @scottkurz if Batch will have any similar troubles because they also persist to the database.

Error that occurs when Timer that was scheduled with a javax.ejb.ScheduleExpression attempts to deserialize in Jakarta:
```
com.ibm.ejs.container.TimerServiceException: An error occurred accessing the persistent EJB timer with the 250 task identifier : javax.ejb.ScheduleExpression; nested exception is: java.lang.ClassNotFoundException: javax.ejb.ScheduleExpression
at com.ibm.ws.ejbcontainer.timer.persistent.osgi.internal.PersistentTimerImpl.newTimerServiceException(PersistentTimerImpl.java:263)
at com.ibm.ws.ejbcontainer.timer.persistent.osgi.internal.PersistentTimerImpl.getTimerStatus(PersistentTimerImpl.java:215)
at com.ibm.ws.ejbcontainer.timer.persistent.osgi.internal.PersistentTimerImpl.getTimerTaskHandler(PersistentTimerImpl.java:227)
at com.ibm.ejs.container.PersistentTimer.getInfo(PersistentTimer.java:181)
at ejb.MyTimerEJBInWAR.getTimer(MyTimerEJBInWAR.java:41)
at ejb.EJSLocalNSLMyTimerEJBInWAR_331e99bf.getTimer(EJSLocalNSLMyTimerEJBInWAR_331e99bf.java)
at web.PersistentExecCompatibilityTestServlet.testFindEJBTimerWithScheduleExpressionFromJavaEE_20_0_0_10(PersistentExecCompatibilityTestServlet.java:520)
...
Caused by: java.lang.ClassNotFoundException: javax.ejb.ScheduleExpression
at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:753)
at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1032)
at com.ibm.ws.serialization.DeserializationObjectInputStream.loadClass(DeserializationObjectInputStream.java:62)
at com.ibm.ws.serialization.internal.DeserializationObjectInputStreamImpl.loadClass(DeserializationObjectInputStreamImpl.java:48)
at com.ibm.ws.serialization.DeserializationObjectInputStream.resolveClass(DeserializationObjectInputStream.java:131)
at com.ibm.ws.serialization.DeserializationObjectInputStream.resolveClass(DeserializationObjectInputStream.java:169)
at java.base/java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1992)
at java.base/java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1878)
at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2166)
at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1700)
at java.base/java.io.ObjectInputStream.readObjectImpl(ObjectInputStream.java:517)
at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:455)
at com.ibm.ws.ejbcontainer.util.ParsedScheduleExpression.readObject(ParsedScheduleExpression.java:998)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1160)
at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2322)
at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2193)
at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1700)
at java.base/java.io.ObjectInputStream.readObjectImpl(ObjectInputStream.java:517)
at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:455)
at com.ibm.ejs.container.PersistentTimerTaskHandler.readObject(PersistentTimerTaskHandler.java:686)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1160)
at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2322)
at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2193)
at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1700)
at java.base/java.io.ObjectInputStream.readObjectImpl(ObjectInputStream.java:517)
at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:455)
at com.ibm.ws.concurrent.persistent.internal.PersistentExecutorImpl.deserialize(PersistentExecutorImpl.java:503)
at com.ibm.ws.concurrent.persistent.internal.TaskStatusImpl.getTimer(TaskStatusImpl.java:333)
at com.ibm.ws.ejbcontainer.timer.persistent.osgi.internal.PersistentTimerImpl.getTimerStatus(PersistentTimerImpl.java:211)
```

Error that occurs when timer that was scheduled with timer info that is a Java EE instance, in this case,  javax.servlet.http.Cookie, attempts to deserialize in Jakarta:
```
CNTR0020E: EJB threw an unexpected (non-declared) exception during invocation of method "runTimer" on bean "BeanId(persistentcompattest#persistentcompattest.war#MyTimerEJBInWAR, null)". Exception data: com.ibm.ejs.container.TimerServiceException: Failure deserializing timer info object.; nested exception is: java.lang.ClassNotFoundException: javax.servlet.http.Cookie
	at com.ibm.ejs.container.PersistentTimerTaskHandler.getUserInfo(PersistentTimerTaskHandler.java:518)
	at com.ibm.ejs.container.PersistentTimer.getInfo(PersistentTimer.java:182)
	at ejb.MyTimerEJBInWAR.runTimer(MyTimerEJBInWAR.java:54)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.ibm.ejs.container.TimedObjectWrapper.invokeCallback(TimedObjectWrapper.java:102)
	at com.ibm.ejs.container.PersistentTimerTaskHandler.run(PersistentTimerTaskHandler.java:289)
	at com.ibm.ws.concurrent.persistent.internal.InvokerTask.run(InvokerTask.java:449)
        ...
Caused by: java.lang.ClassNotFoundException: javax.servlet.http.Cookie
	at com.ibm.ws.classloading.internal.AppClassLoader.findClassCommonLibraryClassLoaders(AppClassLoader.java:569)
	at com.ibm.ws.classloading.internal.AppClassLoader.findClass(AppClassLoader.java:291)
	at java.base/java.lang.ClassLoader.loadClassHelper(ClassLoader.java:1134)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1049)
	at com.ibm.ws.classloading.internal.AppClassLoader.findOrDelegateLoadClass(AppClassLoader.java:547)
	at com.ibm.ws.classloading.internal.AppClassLoader.loadClass(AppClassLoader.java:505)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1032)
	at com.ibm.ws.serialization.DeserializationObjectInputStream.loadClass(DeserializationObjectInputStream.java:62)
	at com.ibm.ws.serialization.internal.DeserializationObjectInputStreamImpl.loadClass(DeserializationObjectInputStreamImpl.java:48)
	at com.ibm.ws.serialization.DeserializationObjectInputStream.resolveClass(DeserializationObjectInputStream.java:131)
	at com.ibm.ws.serialization.DeserializationObjectInputStream.resolveClass(DeserializationObjectInputStream.java:169)
	at java.base/java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1992)
	at java.base/java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1878)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2166)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1700)
	at java.base/java.io.ObjectInputStream.readObjectImpl(ObjectInputStream.java:517)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:455)
	at com.ibm.ejs.container.PersistentTimerTaskHandler$1.run(PersistentTimerTaskHandler.java:510)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:703)
	at com.ibm.ejs.container.PersistentTimerTaskHandler.getUserInfo(PersistentTimerTaskHandler.java:507)
	... 15 more
```

### PR DESCRIPTION
**Pull request by njr-11**
fixes #14324

### CODE REVIEW

**Comment by njr-11** [comment]
#build

**Review by tkburroughs — APPROVED** [review]

**Comment by njr-11** [comment]
#build
#run-libby-bot
For now, 3 of the tests will be disabled because we need to find a solution for why ClassLoader.getSystemClassLoader can load Java EE classes but not Jakarta.  It wasn't valid to work around this by switching to the class loader for the EJB because (as identified by the failing EJB tests), it's a supported scenario to query persistent timers for an app that is gone (which is so that the old timers can be canceled).

**Comment by njr-11** [comment]
#build
#run-libby-bot
Found a solution that doesn't require disabling the 3 tests.  The retry handling can be moved to the other loadClass method, in which case it covers those scenarios as well because it will be searching the deserialization class providers for other spec name as well.

**Comment by tkburroughs** [comment]
FAT failures match a known intermittent issue and are unrelated to the changes in this pull request; merging.

**Comment by tkburroughs** [comment]
@njr-11 Merged.

**Pull request merged**
