### PR TITLE
Add recovery log deletion for peer recovery

### LINKED ISSUE #16787: On successful Peer Transaction Recover remove the recovered server's logs
In the current implementation, logs will live forever even if the server for which they were created is long gone, never to return.

### PR DESCRIPTION
**Pull request by neilgsyoung**
fixes #16787

### CODE REVIEW

**Comment by neilgsyoung** [comment]
#run-libby-bot

**Comment by neilgsyoung** [comment]
#build

**Review by jonhawkes — APPROVED** [review]

**Comment by neilgsyoung** [comment]
#run-libby-bot

**Comment by neilgsyoung** [comment]
#build

**Comment by neilgsyoung** [comment]
#run-libby-bot

**Comment by neilgsyoung** [comment]
#run-libby-bot

**Comment by neilgsyoung** [comment]
#build

**Comment by neilgsyoung** [comment]
#run-libby-bot

**Comment by neilgsyoung** [comment]
#build

**Comment by neilgsyoung** [comment]
#run-libby-bot

**Comment by neilgsyoung** [comment]
#build

**Pull request merged**
