### PR TITLE
Change the productId for OpenLiberty features

### PR DESCRIPTION
**Pull request by Azquelt**

### CODE REVIEW

**Comment by Azquelt** [comment]
#build

**Comment by Azquelt** [comment]
IM offering build against WS-CD integration: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_KKF4oBJOEeiStsw2He7iFw

**Comment by Azquelt** [comment]
We now won't deliver this until after 18.0.0.1

**Comment by Azquelt** [comment]
Rebased on master

#build

**Comment by Azquelt** [comment]
Personal IM Offering build: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_8qFGlBirEeiANdIhjNYPnw

**Comment by Azquelt** [comment]
IM Offering build has no errors. Personal build hit an infrastructure issue.

#build

**Comment by Azquelt** [comment]
Rebased to include #2346

**Comment by Azquelt** [comment]
#build

**Comment by Azquelt** [comment]
Personal IM Offering build: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewDefinition&id=_91uEoLsbEeaIGPtXEYJxbg

**Comment by Azquelt** [comment]
Last build failed because some projects had not been removed from WS-CD. That has been merged this morning.

IM build against integration: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_nJn9oCHyEeiwitX0Zm6mOA

**Comment by idlewis** [comment]
@Azquelt This can be closed now I think? as it was addressed under #3215

**Pull request closed without merging**
