### PR TITLE
H2: Add code that allows for an inactivity to be set to close a

### PR DESCRIPTION
**Pull request by billw1024**
connection

### CODE REVIEW

**Comment by billw1024** [comment]
#build

**Comment by mrsaldana** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.transport.http2_fat

**Comment by mrsaldana** [comment]
#build

**Comment by mrsaldana** [comment]
#build

**Comment by billw1024** [comment]
#build

**Comment by billw1024** [comment]
latest build was "good",  62000+ tests passed, 4 failures were unrelated to this change.

**Pull request merged**
