### PR TITLE
Jakarta Mail 2.1.0 feature and bundles

### LINKED ISSUE #22112: Jakarta Mail 2.1: Add implementation
First step to supporting Jakarta Mail 2.1 will be to add the implementation to the public `mail-2.1` feature. The RI is now a part of the Angus Mail Eclipse Project and can be found here: https://github.com/eclipse-ee4j/angus-mail. 

- [ ]  The RI available from MC needs to be uploaded: https://mvnrepository.com/artifact/org.eclipse.angus/angus-mail/1.0.0.
- [ ]  A new bundle `io.openliberty.org.eclipse.angus.mail.2.1` needs to be added that bundles and exports the contents of the RI jar you've uploaded. 
- [ ]  Due to the implementation and spec split, any of the RI resources exported the `io.openliberty.mail.2.0.internal` bundle will need to be exported instead by this new ri bundle. These include:

```
Include-Resource: \
  @${repo;<CHANGE THIS TO ANGUS COORDINATES IN ARTIFACTORY>}!/META-INF/mailcap, \
  @${repo;<CHANGE THIS TO ANGUS COORDINATES IN ARTIFACTORY>}!/META-INF/gfprobe-provider.xml, \
  @${repo;<CHANGE THIS TO ANGUS COORDINATES IN ARTIFACTORY>}!/META-INF/javamail.charset.map, \
  @${repo;<CHANGE THIS TO ANGUS COORDINATES IN ARTIFACTORY>}!/META-INF/javamail.default.address.map, \
  @${repo;<CHANGE THIS TO ANGUS COORDINATES IN ARTIFACTORY>}!/META-INF/javamail.default.providers  
```

and 

```
app-resources= \
  META-INF/javamail.default.address.map | \
  META-INF/javamail.default.providers | \
  META-INF/javamail.charset.map | \
  META-INF/mailcap | \
  META-INF/jakarta.mail.Provider | \
  META-INF/jakarta.mail.util.StreamProvider
```

- [ ]  The RI bundle needs to be added to the public `javaMail-2.1` feature
- [ ] A new `io.openliberty.mail.2.1.internal` project and bundle should be created, which adds the `io.openliberty.mail.2.0.internal` bundle to it's classpath so it can then, import all it's `io.openliberty.mail.2.1.internal` packages from `io.openliberty.mail.*` and denotes them as

```
Private-Package: \
	io.openliberty.mail.internal.injection,\
	io.openliberty.mail.internal,\
	io.openliberty.mail.resources
```

This allows us to reuse the same source code without having to duplicate code. 

- [ ] Add this new `io.openliberty.mail.2.1.internal` bundle to the public javaMail-2.1 feature
- [ ] You should test locally that a server can start with `javaMail-2.1` enabled 
- [ ]  And finally you should run this bucket locally `build.featureJavaLevel.mToZ_fat`

### PR DESCRIPTION
**Pull request by BerksanAtes**
Fixes #22112

### CODE REVIEW

**Comment by BerksanAtes** [comment]
#build

**Review by neuwerk — APPROVED** [review]
Changes look good to me! Thanks @BerksanAtes

**Comment by neuwerk** [comment]
#libby

**Comment by neuwerk** [comment]
#run-libby-bot

**Comment by neuwerk** [comment]
#libby

**Pull request merged**
