### PR TITLE
Update Faces 4.0 to 4.0.0-RC4

### LINKED ISSUE #24115: Update Faces 4.0 to RC4
Release Notes - MyFaces Core - Version 4.0.0-RC4 can be found in the following link:
https://issues.apache.org/jira/secure/ReleaseNote.jspa?projectId=10600&version=12352692

### PR DESCRIPTION
**Pull request by volosied**
Only overlay I kept was [MYFACES-4552](https://github.com/OpenLiberty/open-liberty/commit/0e57ed97f415a0bcbda0dcebdb52d402d4b8aa15)

 Fixes #24115

### CODE REVIEW

**Comment by volosied** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jsf.2.3_fat,com.ibm.ws.jsf.2.2_fat,io.openliberty.org.apache.myfaces.4.0_fat

**Comment by volosied** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jsf.2.3_fat,com.ibm.ws.jsf.2.2_fat,io.openliberty.org.apache.myfaces.4.0_fat

**Comment by pnicolucci** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jsf.2.3_fat,com.ibm.ws.jsf.2.2_fat,io.openliberty.org.apache.myfaces.4.0_fat

**Review by pnicolucci — APPROVED** [review]

**Comment by pnicolucci** [comment]
#libby

**Pull request merged**
