### PR TITLE
Issue #28996: default ppv env var for sermeru instantOn

### PR DESCRIPTION
**Pull request by hlhoots**
#build

### CODE REVIEW

**Comment by hlhoots** [comment]
fixes #28996

**Review by tbitonti — APPROVED** [review]

**Comment by wraschke** [comment]
#libby

**Comment by hlhoots** [comment]
RTC build had one test failure, that seems unrelated.  Rerunning a build for sanity purposes.

#build

**Comment by hlhoots** [comment]
Several errors in the build, but none look related to the change made. Merging.

**Pull request merged**
