### PR TITLE
get the server object on the injection path

### PR DESCRIPTION
**Pull request by benjamin-confino**
part of #https://github.com/OpenLiberty/open-liberty/issues/27711

Now https://github.com/OpenLiberty/open-liberty/pull/28732 has been delivered this uses the new server scoped OpenTelemetry object in the old codepath if available.

### CODE REVIEW

**Comment by benjamin-confino** [comment]
#build

**Review by tonyreigns — APPROVED** [review]
LGTM

**Comment by tonyreigns** [comment]
#build

**Comment by benjamin-confino** [comment]
delivered under #28828

**Pull request closed without merging**
