### PR TITLE
Repeat Infinispan tests for Jakarta EE10

### PR DESCRIPTION
**Pull request by zhang-ca**
Repeat Infinispan container Session FATs for Jakarta EE10

### CODE REVIEW

**Comment by zhang-ca** [comment]
fixes #21200

**Comment by zhang-ca** [comment]
Changes depends on #21076

**Comment by zhang-ca** [comment]
#build

**Comment by zhang-ca** [comment]
#build

**Review by bensonlatibm — APPROVED** [review]
lgtm!

**Pull request merged**
