### PR TITLE
Fix the host name when it changes on restore

### LINKED ISSUE #23651: InstantOn and resolvedHostName on restore
The InstantOn target use-case is restoring in-container.  With that in mind the checkpoint of a process will be done in an environment that will always have a different resolved host name than the hostname that would be used when launching in-container (the hostname is generally a generated name when a container is launched).

During checkpoint it seems the variable `com.ibm.ws.http.internal.HttpEndpointImpl.resolvedHostName` gets set early before a checkpoint of the process is done.  This value currently does not get updated on restore when the hostname of the restore environment will be different than the hostname during checkpoint.

It is unclear what side-effects this has.  The `com.ibm.ws.http.internal.VirtualHostMap` class uses the `com.ibm.ws.http.internal.HttpEndpointImpl.getResolvedHostName()` method.  This also gets called very early during checkpoint before the process can be saved for a checkpoint.  Do we need to adjust this value that gets cached in the virtual host for the new hostname on restore?

### PR DESCRIPTION
**Pull request by tjwatson**

### CODE REVIEW

**Comment by tjwatson** [comment]
#build

**Comment by tjwatson** [comment]
Fixes #23651

**Comment by tjwatson** [comment]
#build

**Comment by tjwatson** [comment]
#build

**Comment by tjwatson** [comment]
#build

**Comment by tjwatson** [comment]
#build

**Comment by tjwatson** [comment]
#build

**Comment by tjwatson** [comment]
@mrsaldana please review 6580654c7f30d80397d94fb1359d3fa07aa85616
@neuwerk please review 4836b83481d88e8d2aba6c77a2b05e775e8efaaa

**Comment by tjwatson** [comment]
#build

**Comment by tjwatson** [comment]
#build

**Comment by tjwatson** [comment]
#build

**Review by anjumfatima90 — DISMISSED** [review]

**Comment by tjwatson** [comment]
#build

**Comment by tjwatson** [comment]
#build

**Comment by tjwatson** [comment]
#build

**Comment by tjwatson** [comment]
#build

**Review by neuwerk — APPROVED** [review]
https://github.com/OpenLiberty/open-liberty/commit/4836b83481d88e8d2aba6c77a2b05e775e8efaaa changes LGTM!

**Comment by tjwatson** [comment]
#libby

**Review by anjumfatima90 — APPROVED** [review]
LGTM, Thanks!

**Review by mrsaldana — APPROVED** [review]
https://github.com/OpenLiberty/open-liberty/commit/6580654c7f30d80397d94fb1359d3fa07aa85616 looks good, thanks for the work here!

**Pull request merged**
