### PR TITLE
Myfaces 4456

### LINKED ISSUE #22653: Pull in MYFACES-4456
https://issues.apache.org/jira/browse/MYFACES-4456

### PR DESCRIPTION
**Pull request by pnicolucci**
fixes #22653
for #20839

### CODE REVIEW

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
Java17 build: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_4guAIEPLEe2gRt1V5m8KOw

**Review by volosied — APPROVED** [review]
looks good to me

**Pull request merged**
