### PR TITLE
Add BATCH GitHub Actions test category; Fix comments explaining invalid vs. valid XML

### PR DESCRIPTION
**Pull request by scottkurz**
Signed-off-by: Scott Kurz <skurz@us.ibm.com>

### CODE REVIEW

**Comment by scottkurz** [comment]
#build

**Comment by scottkurz** [comment]
@KyleAure I haven't used the GH actions much... can you please review this change breaking out the batch FATs into their own category?  Thank you !

**Review by KyleAure — APPROVED** [review]
Looks good.  Thanks 👍

**Comment by scottkurz** [comment]
#run-libby-bot

**Comment by scottkurz** [comment]
RTC build failures - 1 unrelated, 1 matching known defect.  Merging.

**Pull request merged**
