### PR TITLE
Add additional mpConfig-2.0 FAT tests

### PR DESCRIPTION
**Pull request by Joseph-Cass**
#build

### CODE REVIEW

**Comment by Joseph-Cass** [comment]
#build

**Comment by Joseph-Cass** [comment]
Build failed since it didn't include the changes from this PR: https://github.com/OpenLiberty/open-liberty/pull/15568. 

Will do a rebase and retry.

**Comment by Joseph-Cass** [comment]
#build

**Review by ayoho — APPROVED** [review]

**Comment by Joseph-Cass** [comment]
#run-libby-bot

**Comment by Joseph-Cass** [comment]
#run-libby-bot

**Pull request merged**
