### PR TITLE
Fix hardcoded realm from expectations

### PR DESCRIPTION
**Pull request by Zech-Hein**

### CODE REVIEW

**Comment by Zech-Hein** [comment]
#build

**Comment by Zech-Hein** [comment]
#build

**Comment by Zech-Hein** [comment]
#build

**Comment by Zech-Hein** [comment]
`CWWKE0701E: bundle com.ibm.ws.transport.iiop:1.0.61.202201191112` failure is unrelated to the changes

**Review by wrodrig — APPROVED** [review]
Looks Good!

**Comment by Zech-Hein** [comment]
#libby

**Pull request merged**
