### PR TITLE
Update EclipseLink 2.7.7 -> 2.7.8

### PR DESCRIPTION
**Pull request by dazey3**
Updating EclipseLink from 2.7.7 to 2.7.8. 

for #14457
for #14425
for #14137
for #13433
for #12694

Also, several fixes were included in this update by the EclipseLink community.

Signed-off-by: Will Dazey <dazeydev.3@gmail.com>

### CODE REVIEW

**Comment by dazey3** [comment]
#run-libby-bot

**Comment by dazey3** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jpa_22_fat,com.ibm.ws.jpa_30_fat,com.ibm.ws.jpa_eclipselink_fat,com.ibm.ws.jpa_ol_fat,com.ibm.ws.jpa_spec10_injection_fat,com.ibm.ws.jpa_spec10_part01_fat,com.ibm.ws.jpa_spec10_part02_fat,com.ibm.ws.jpa_spec10_query_fat,com.ibm.ws.jpa_spec20_fat,com.ibm.ws.jpa_spec21_fat

**Comment by dazey3** [comment]
#run-libby-bot

**Comment by dazey3** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jpa_22_fat,com.ibm.ws.jpa_30_fat,com.ibm.ws.jpa_eclipselink_fat,com.ibm.ws.jpa_ol_fat,com.ibm.ws.jpa_spec10_injection_fat,com.ibm.ws.jpa_spec10_part01_fat,com.ibm.ws.jpa_spec10_part02_fat,com.ibm.ws.jpa_spec10_query_fat,com.ibm.ws.jpa_spec20_fat,com.ibm.ws.jpa_spec21_fat

**Review by jgrassel — APPROVED** [review]
LGTM

**Comment by dazey3** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jpa_22_fat,com.ibm.ws.jpa_30_fat,com.ibm.ws.jpa_eclipselink_fat,com.ibm.ws.jpa_ol_fat,com.ibm.ws.jpa_spec10_injection_fat,com.ibm.ws.jpa_spec10_part01_fat,com.ibm.ws.jpa_spec10_part02_fat,com.ibm.ws.jpa_spec10_query_fat,com.ibm.ws.jpa_spec20_fat,com.ibm.ws.jpa_spec21_fat

**Comment by dazey3** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jpa_22_fat,com.ibm.ws.jpa_30_fat,com.ibm.ws.jpa_eclipselink_fat,com.ibm.ws.jpa_ol_fat,com.ibm.ws.jpa_spec10_injection_fat,com.ibm.ws.jpa_spec10_part01_fat,com.ibm.ws.jpa_spec10_part02_fat,com.ibm.ws.jpa_spec10_query_fat,com.ibm.ws.jpa_spec20_fat,com.ibm.ws.jpa_spec21_fat

**Comment by dazey3** [comment]
#run-libby-bot

**Pull request merged**
