### PR TITLE
Myfaces 4452

### PR DESCRIPTION
**Pull request by pnicolucci**
for https://github.com/OpenLiberty/open-liberty/issues/22198

https://issues.apache.org/jira/browse/MYFACES-4452

### CODE REVIEW

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
#libby #build

**Review by volosied — APPROVED** [review]

**Pull request merged**
