### PR TITLE
Add detect secrets files

### PR DESCRIPTION
**Pull request by fritze2**

### CODE REVIEW

**Comment by fritze2** [comment]
#build

**Review by websterc87 — APPROVED** [review]
looks good to me. Hopefully the hooks is built in such a way that it doesnt slow down on a big repo like this. Im guessing thats the reason behind the baseline.

**Comment by fritze2** [comment]
#libby

**Comment by fritze2** [comment]
> **The following files contain a string indicating discriminating content:**
> 
> * .pre-commit-config.yaml

Wording was copied directly from IBM Detect Secrets files.

**Pull request merged**
