### PR TITLE
Clean up Faces 4.0 bundle, remove remaining taglibconfig references

### LINKED ISSUE #23778: Faces 4.0: clean up io.openliberty.org.apache.myfaces.4.0 bnd.bnd and beans.xml (com.ibm.ws.faces)
1) The bnd.bnd contains the following export: `  com.ibm.ws.faces.taglibconfig, \`
2) The beans.xml contains the following exclude: `<exclude name="com.ibm.ws.faces.**" />`

This package was removed as part of : https://github.com/OpenLiberty/open-liberty/pull/23078/files#diff-356d41702904ac6fb3802d3fe983437cf1b50d2438dadb8dc31b1e5536975023

### PR DESCRIPTION
**Pull request by pnicolucci**
fixes #23778

### CODE REVIEW

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
#build

**Review by volosied — APPROVED** [review]
LTGM

**Comment by pnicolucci** [comment]
#libby

**Pull request merged**
