### PR TITLE
Split `com.ibm.ws.jpa.tests.spec20_fat` FAT

### PR DESCRIPTION
**Pull request by dazey3**
Splitting the `com.ibm.ws.jpa.tests.spec20_fat` into individual EE FAT:
```
com.ibm.ws.jpa.tests.spec20_fat.common
com.ibm.ws.jpa.tests.spec20_jpa_2.0_fat
com.ibm.ws.jpa.tests.spec20_jpa_2.1_fat
com.ibm.ws.jpa.tests.spec20_jpa_2.2_fat
com.ibm.ws.jpa.tests.spec20_jpa_3.0_fat
com.ibm.ws.jpa.tests.spec20_jpa_3.1_fat
```

### CODE REVIEW

**Comment by dazey3** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jpa.tests.spec20_jpa_2.0_fat,com.ibm.ws.jpa.tests.spec20_jpa_2.1_fat,com.ibm.ws.jpa.tests.spec20_jpa_2.2_fat,com.ibm.ws.jpa.tests.spec20_jpa_3.0_fat,com.ibm.ws.jpa.tests.spec20_jpa_3.1_fat

**Comment by dazey3** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jpa.tests.spec20_jpa_2.0_fat,com.ibm.ws.jpa.tests.spec20_jpa_2.1_fat,com.ibm.ws.jpa.tests.spec20_jpa_2.2_fat,com.ibm.ws.jpa.tests.spec20_jpa_3.0_fat,com.ibm.ws.jpa.tests.spec20_jpa_3.1_fat

**Comment by dazey3** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jpa.tests.spec20_jpa_2.0_fat,com.ibm.ws.jpa.tests.spec20_jpa_2.1_fat,com.ibm.ws.jpa.tests.spec20_jpa_2.2_fat,com.ibm.ws.jpa.tests.spec20_jpa_3.0_fat,com.ibm.ws.jpa.tests.spec20_jpa_3.1_fat

**Review by jgrassel — APPROVED** [review]

**Comment by dazey3** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jpa.tests.spec20_jpa_2.0_fat,com.ibm.ws.jpa.tests.spec20_jpa_2.1_fat,com.ibm.ws.jpa.tests.spec20_jpa_2.2_fat,com.ibm.ws.jpa.tests.spec20_jpa_3.0_fat,com.ibm.ws.jpa.tests.spec20_jpa_3.1_fat

**Comment by dazey3** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jpa.tests.spec20_jpa_2.0_fat,com.ibm.ws.jpa.tests.spec20_jpa_2.1_fat,com.ibm.ws.jpa.tests.spec20_jpa_2.2_fat,com.ibm.ws.jpa.tests.spec20_jpa_3.0_fat,com.ibm.ws.jpa.tests.spec20_jpa_3.1_fat

**Comment by dazey3** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jpa.tests.spec20_jpa_2.0_fat,com.ibm.ws.jpa.tests.spec20_jpa_2.1_fat,com.ibm.ws.jpa.tests.spec20_jpa_2.2_fat,com.ibm.ws.jpa.tests.spec20_jpa_3.0_fat,com.ibm.ws.jpa.tests.spec20_jpa_3.1_fat

**Comment by dazey3** [comment]
#run-libby-bot

**Pull request merged**
