### PR TITLE
update ssl metatype key.jks to key.p12

### PR DESCRIPTION
**Pull request by Zech-Hein**
For issue #12120 

The location description needs to be updated from key.jks to key.p12

### CODE REVIEW

**Review by utle — APPROVED** [review]

**Comment by skasund** [comment]
L2 message review not required

**Comment by Zech-Hein** [comment]
#run-libby-bot

**Comment by Zech-Hein** [comment]
#build

**Comment by Zech-Hein** [comment]
The failure on the PB is unrelated to the change. All other tests ran look good.

**Pull request merged**
