### PR TITLE
24157: Validate header names

### LINKED ISSUE #24157: Validate HTTP header names
Describe the bug
Http header names should be validated

Steps to Reproduce
Send an http request that contains a header where the header name contains an invalid character.

Expected behavior
The http response to an http request that contains an invalid character should contain a response code of 400.

Diagnostic information:

OpenLiberty Version: [e.g. first release - 23.0.0.1]
Affected feature(s): servlet-4.0, servlet-3.1, servlet-3.0
Java Version: n/a
server.xml configuration
n/a

### PR DESCRIPTION
**Pull request by loriadi**
fixes #24157

### CODE REVIEW

**Comment by loriadi** [comment]
#build

**Comment by loriadi** [comment]
#build

**Comment by loriadi** [comment]
#build

**Comment by loriadi** [comment]
#build

**Comment by loriadi** [comment]
#libbybot

**Comment by loriadi** [comment]
#build

**Comment by loriadi** [comment]
#libbybot

**Comment by loriadi** [comment]
All the errors from the build are this:
java.lang.IllegalStateException: Could not find a valid Docker environment. Please see logs and check configuration

and other builds surrounding my build have these same errors.  My changes did not cause this error.

I've added a couple of unit tests and also tested this change manually with a trace logging enabled.

**Comment by loriadi** [comment]
#build

**Comment by loriadi** [comment]
#libbybot

**Comment by loriadi** [comment]
fixes #PH52074

**Review by mrsaldana — APPROVED** [review]
thanks for the work !

**Pull request merged**
