### PR TITLE
update grpc dependencies to 1.35.0

### PR DESCRIPTION
**Pull request by wtlucy**
* Update grpc-java libs to 1.35.0, netty to 4.1.52.Final, and all other dependencies to grpc 1.35.0 required levels
* Update servlet adapter builder to work with the changes made in grpc-java issue 7211
* Remove the backported fix from #14080
* minor test updates

for #14109

### CODE REVIEW

**Comment by wtlucy** [comment]
#build

**Review by billw1024 — APPROVED** [review]
looks good

**Review by loriadi — APPROVED** [review]
Looks good

**Comment by wtlucy** [comment]
#build

**Comment by wtlucy** [comment]
#run-libby-bot

**Pull request merged**
