### PR TITLE
remove beta fencing for featureUtility 

### PR DESCRIPTION
**Pull request by jjiwooLim**
#18388

### CODE REVIEW

**Comment by jjiwooLim** [comment]
#build

**Comment by jjiwooLim** [comment]
#build

**Comment by bensonlatibm** [comment]
#run-libby-bot

**Comment by bensonlatibm** [comment]
#build

**Comment by bensonlatibm** [comment]
RTC failure was in com.ibm.ws.ui.tool.javaBatch_fat.gui.FATSuite and is unrelated to these changes.

**Review by bensonlatibm — APPROVED** [review]
lgtm!

**Pull request merged**
