### PR TITLE
Update ExpressionLanguage-4.0 api/impl to 10.0.7

### LINKED ISSUE #17659: Update ExpressionLanguage 4.0 API/Impl to 10.0.7

### PR DESCRIPTION
**Pull request by volosied**
fixes #17659

### CODE REVIEW

**Comment by volosied** [comment]
#build

**Review by pnicolucci — APPROVED** [review]

**Comment by pnicolucci** [comment]
#run-libby-bot

**Comment by volosied** [comment]
#build

**Comment by volosied** [comment]
Build showed unrelated errors & CTS Tests passed -- merging

**Pull request merged**
