### PR TITLE
Remove config signing function

### PR DESCRIPTION
**Pull request by brenthdaniel**

### CODE REVIEW

**Comment by brenthdaniel** [comment]
#build

**Comment by brenthdaniel** [comment]
#build

**Comment by brenthdaniel** [comment]
#build

**Comment by brenthdaniel** [comment]
#build

**Comment by brenthdaniel** [comment]
#build

**Comment by brenthdaniel** [comment]
#build

**Comment by brenthdaniel** [comment]
#build

**Review by cbridgha — APPROVED** [review]
LGTM

**Comment by brenthdaniel** [comment]
#run-libby-bot

**Pull request merged**
