### PR TITLE
Repeat el fats with el60 feature

### LINKED ISSUE #25598: Expression Language 6.0: Repeat existing Expression Lanauge FATs with the `expressionLanguage-6.0` feature

### PR DESCRIPTION
**Pull request by pnicolucci**
fixes #25598

### CODE REVIEW

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Review by volosied — APPROVED** [review]
Looks fine to me

**Comment by pnicolucci** [comment]
#libby

**Comment by pnicolucci** [comment]
#libby

**Pull request merged**
