### PR TITLE
Fix regex to match json tck jar

### PR DESCRIPTION
**Pull request by tevans78**
Pattern matcher was expecting TCK jars to end in `-tck.x.x.jar` but the Jakarta JSON TCK jar ends in `-tck-tests.x.x.jar`
#build

### CODE REVIEW

**Comment by tevans78** [comment]
Appears that the pattern matching does not work properly on windows either :-(

**Comment by tevans78** [comment]
#build
#pb

**Comment by tevans78** [comment]
#pb

**Comment by tevans78** [comment]
#build

**Review by Yas-Franco — APPROVED** [review]
Looks good to me!

**Comment by tevans78** [comment]
#libby

**Pull request merged**
