### PR TITLE
Update copyright year ending in manifest files to be 2022

### PR DESCRIPTION
**Pull request by jhanders34**
- Update copyright year ending in manifest files to be 2022

### CODE REVIEW

**Comment by tjwatson** [comment]
Can you explain why you need to remove the `Private-Package` header?  I've used this header in the past for experiments with running Liberty on the flat classpath or with GraalVM Substrate Native.

**Comment by jhanders34** [comment]
> Can you explain why you need to remove the `Private-Package` header? I've used this header in the past for experiments with running Liberty on the flat classpath or with GraalVM Substrate Native.

Interesting use of Private-Package.  -privatepackage is the instruction way of specifying private packages similar to Include-Resource vs -includeresource.  In OSGi Private-Package is not used.  Private-Package is not used in all bnd files for all the packages in a bundle that are not exported.  I guess we should talk outside of the PR about this on Monday.

**Comment by jhanders34** [comment]
#build

**Comment by tjwatson** [comment]
> Interesting use of Private-Package. -privatepackage is the instruction way of specifying private packages similar to Include-Resource vs -includeresource. In OSGi Private-Package is not used. Private-Package is not used in all bnd files for all the packages in a bundle that are not exported. I guess we should talk outside of the PR about this on Monday.

I am still not sure the motivation for removing the header though.  It is true that the `Private-Package` header is not used by the framework.  On the other hand the framework tries hard to not load the bundle manifest when loading from a cached state.  So the extra header there should not impact memory footprint.  If we see the manifest headers being kept in memory then we should look find out what is causing the headers to be parsed on a cached restart.  Several areas in Liberty I had to update to cache things the runtime needs so on restart they do not cause the manifests to be loaded.  For example, the headers for iFix information.

My usecase is not a priority.  But the reason I came to depend on `Private-Package` was so that I could easily determine what classes come from what bundles when the framework does not control the class loader (e.g. loading from the flat classpath, the module path, or from a native GraalVM image).  This is how Atomos can do the package-to-content mapping when dealing with native image content; otherwise Atomos has to do an exhaustive search of the content archive to discover all the packages which is expensive:
https://github.com/apache/felix-atomos/blob/atomos-distribution-1.0.0/atomos/src/main/java/org/apache/felix/atomos/impl/base/AtomosBase.java#L1637-L1681

For modules it is not as bad because JPMS has Class.getModule to figure out what module/bundle a class is from.  For flat classpath we depend on there being a ProtectionDomain so we can map the location to the bundle JAR when we search the classpath.

As I said, this is not an important usecase, but I wanted to point out that I've found the header useful in the past.  I would prefer we keep it, unless there is some performance reason to get rid of it.

**Comment by jhanders34** [comment]
#build

**Review by tjwatson — APPROVED** [review]

**Comment by jhanders34** [comment]
This was done as part of #21238, so I am going to close out this PR.

**Pull request closed without merging**
