### PR TITLE
296004 fat rewrite

### PR DESCRIPTION
**Pull request by tbitonti**
Update for build break defect 296004.

Rewrote the zip cache introspector cache tests:
* Removed unnecessary delays;
* Changed the servlet resource hold/release strategy to remove a lengthy sleep;
* Corrected resource usage to minimize open times and to ensure resource closure.
* Recategorized slow tests as FULL mode tests.

These test classes / methods were impacted:
* /com.ibm.ws.artifact_fat/fat/src/com/ibm/ws/artifact/fat/FATReaperIntrospectionTest.java
  * testZipHandles()
  * testNotWaitingWithNonEmptyQueue()
  * testOpenCounts()
* /com.ibm.ws.artifact_fat/fat/src/com/ibm/ws/artifact/fat/FATReaperMultipleIntrospectionTest.java
  * testManyApps()
  * testMoveToOpen()

This does not directly address the original build break.  This update is intended to remove LEAKED test results, so to provide better test logging in case of subsequent failures.

This also reduces test time by about 50% (from 10m to 5m on a local windows environment), when running LITE mode tests.

### CODE REVIEW

**Comment by tbitonti** [comment]
#build

**Comment by tbitonti** [comment]
The target FAT tests ran green.

The time to run FATReaperMultipleIntrospectionTest was reduced from about 4.5m to about 2m:

### **Final:**
```
com.ibm.ws.artifact.fat.FATReaperIntrospectionTest 3 0 0 0s 2
  testZipHandles 1 0 0 0s 1
  testNotWaitingWithNonEmptyQueue 1 0 0 0s 2
  testOpenCounts 1 0 0 0s 3

com.ibm.ws.artifact.fat.FATReaperMultipleIntrospectionTest 2 0 0 1m 54s 3
  testManyApps 1 0 0 29s 1
  testMoveToOpen 1 0 0 1m 24s 2

com.ibm.ws.artifact.fat.FATResourceProtocol 2 0 0 55s 1
  testResourceProtocolConfiguration 1 0 0 41s 1
  testResourceProtocolUpdate 1 0 0 13s 2
```

### **Initial:**
```
com.ibm.ws.artifact.fat.FATReaperIntrospectionTest 4 0 0 0s 2
  testServerDumpIncludesZipReader 1 0 0 0s 1
  testZipReaperDumpContainsAllZips 1 0 0 0s 2
  testNotWaitingWithNonEmptyQueue 1 0 0 0s 3
  testZipFileToOpenCorrect 1 0 0 0s 4

com.ibm.ws.artifact.fat.FATReaperMultipleIntrospectionTest 2 0 0 4m 27s 3
  checkManyApps 1 0 0 32s 1
  testMoveToOpen 1 0 0 3m 55s 2

com.ibm.ws.artifact.fat.FATResourceProtocol 2 0 0 42s 1
  testResourceProtocolConfiguration 1 0 0 30s 1
  testResourceProtocolUpdate 1 0 0 11s 2
```

**Review by jimblye — DISMISSED** [review]

**Comment by tbitonti** [comment]
Rebuilding with correct file sets.  Had three file changes from an unrelated update accidentally included.

**Comment by tbitonti** [comment]
#build

**Review by jimblye — APPROVED** [review]

**Comment by tbitonti** [comment]
The test impacts *ONLY* FAT tests.  No product code was updated.

The update was tested by rerunning the updated FAT tests.

**Comment by tbitonti** [comment]
#libby

**Pull request merged**
