### PR TITLE
Eclipse setting cleanup

### PR DESCRIPTION
**Pull request by jhanders34**
- Update output to be bin_test for unit test in security.audit.source
component.
- Update cxf.api.2.6 component to filter on 1.7 instead of 1.8 since it
compiles everywhere else as 1.7.
- Remove unneeded build.gradle file for reactive.messaging_fat_tck
component.
- Update eclipse compiler settings to 1.8 to match the settings in the
bnd.bnd file and .classpath for persistence_fat_configupdate component..

### CODE REVIEW

**Comment by jhanders34** [comment]
#build

**Comment by jhanders34** [comment]
I am on vacation next week.  If one of you can review and merge while I am out I would appreciate it.

**Comment by toshiyamamoto** [comment]
I accidentally merged thhe code before a PB was completed. However, the PB is good, there is a known problem in it though.

**Comment by jhanders34** [comment]
> I accidentally merged thhe code before a PB was completed. However, the PB is good, there is a known problem in it though.

That is ok.  It was not touching code, but settings files for eclipse and java settings.  The build had gotten far enough to show that compile worked.

**Pull request merged**
