### PR TITLE
Remove beta guards for new computed metrics for MP Metrics 3.0, 4.0, and 5.0

### LINKED ISSUE #26616: Remove beta guards for providing new computed metrics for MP Metrics feature
- As part of the https://github.com/OpenLiberty/open-liberty/issues/25813 feature.
- Need to remove the beta guards that were added as part of https://github.com/OpenLiberty/open-liberty/pull/26320 and https://github.com/OpenLiberty/open-liberty/pull/26603

### PR DESCRIPTION
**Pull request by pgunapal**
fixes #26616

### CODE REVIEW

**Comment by pgunapal** [comment]
#build

**Comment by pgunapal** [comment]
#build

**Review by Channyboy — APPROVED** [review]
lgtm when all approvals acquired

**Comment by pgunapal** [comment]
Received all the focal point approvals: https://github.com/OpenLiberty/open-liberty/issues/25813

**Pull request merged**
