### PR TITLE
Revert "Increase logging level in JMSAsyncSendTests"

### PR DESCRIPTION
**Pull request by jhanders34**
Reverts OpenLiberty/open-liberty#30126

### CODE REVIEW

**Review by tkburroughs — APPROVED** [review]

**Comment by jhanders34** [comment]
!libby

**Comment by contbld** [comment]
Your personal pipeline request is at https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=f5f0248d-4462-4d42-94cf-e369b6aa4155

Target locations of links might be accessible only to IBM employees.

**Comment by contbld** [comment]
<h3>Code analysis and actions</h3>
DO NOT DELETE THIS COMMENT.

- 1 FAT files were changed, added, or removed.
 - Check that the build did not break the affected FAT suite(s).

**Comment by contbld** [comment]
https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=f5f0248d-4462-4d42-94cf-e369b6aa4155 completed successfully!

**Pull request merged**
