### PR TITLE
Don't put processed file paths into errors

### LINKED ISSUE #19410: JMX file transfer errors shouldn't expose resolved file paths
This is a follow up to issue #19366
The code review showed that the same error exists in 2 other places which also should be fixed.

### PR DESCRIPTION
**Pull request by idlewis**
As this leaks internal server information, which is against
good security practices
fixes #19410

### CODE REVIEW

**Comment by idlewis** [comment]
#build

**Comment by idlewis** [comment]
#build

**Comment by idlewis** [comment]
#run-libby-bot

**Review by leochr — APPROVED** [review]
@idlewis Looks good. Thanks

**Pull request merged**
