### PR TITLE
Update testng

### LINKED ISSUE #23781: Update to TestNG 7.5.x
https://repo1.maven.org/maven2/org/testng/testng/7.7.1/

### PR DESCRIPTION
**Pull request by abutch3r**
Update TestNG to 7.5.0 custom release

Update Arquillian testng to last known good release
Update Arquillian Jarkata to latest
Update Arquillian Liberty Container to latest

Simplyify Arquillian Logging extensions

fixes https://github.com/OpenLiberty/open-liberty/issues/23781

### CODE REVIEW

**Comment by abutch3r** [comment]
#pb

**Comment by abutch3r** [comment]
#pb

**Comment by benjamin-confino** [comment]
#pb

**Comment by benjamin-confino** [comment]
#build

**Comment by benjamin-confino** [comment]
#build

**Comment by tevans78** [comment]
#build

**Pull request closed without merging**
