### PR TITLE
Added retry for JPQL Syntax Error parsing (Persistence Exception)

### PR DESCRIPTION
**Pull request by ajaypaul-ibm**
Added retry for JPQL Syntax Error . This is workaround for the issue which is reported by some customers.
for #28285

### CODE REVIEW

**Comment by ajaypaul-ibm** [comment]
#build

**Comment by ajaypaul-ibm** [comment]
#libby

**Comment by ajaypaul-ibm** [comment]
#build

**Review by tkburroughs — APPROVED** [review]

**Comment by tkburroughs** [comment]
Looks good

**Comment by tkburroughs** [comment]
Note: waiting on this build to complete:
- https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_ZDFaEAX_Ee-9IeXbkm35aA

**Pull request merged**
