### PR TITLE
Better key generation for SSL tests

### PR DESCRIPTION
**Pull request by jonhawkes**
#build

### CODE REVIEW

**Review by neilgsyoung — DISMISSED** [review]
Looks good

**Comment by jonhawkes** [comment]
#build

**Comment by jonhawkes** [comment]
#build

**Comment by jonhawkes** [comment]
#build

**Review by neilgsyoung — APPROVED** [review]
LGTM

**Comment by jonhawkes** [comment]
#libby

**Comment by jonhawkes** [comment]
#build

**Comment by jonhawkes** [comment]
#build

**Pull request merged**
