### PR TITLE
20676: Websocket hang

### LINKED ISSUE #20676: WEBCONTAINER THREADS HUNG WHILE CLOSING WEBSOCKETS
**Describe the bug**  
While closing a WebSocket in an error condition, a WebContainer thread may hang.

ThreadMonitor W WSVR0605W:
Thread "WebContainer : 1" (0000020d) has been active for 17823
milliseconds and may be hung. There is/are 1 thread(s) in total
in the server that may be hung.
at java.lang.Object.wait(Native Method)
at java.lang.Object.wait(Object.java:189)
at com.ibm.ws.wsoc.WsocConnLink.finishReadBeforeClose(WsocConnL
ink.java:812)
at com.ibm.ws.wsoc.SessionImpl.close(SessionImpl.java:394)
at com.ibm.ws.wsoc.EndpointManager.httpSessionExpired(EndpointM
anager.java:166)
at com.ibm.ws.wsoc.WsocHttpSessionListener.sessionDestroyed(Wso
cHttpSessionListener.java:63)
at com.ibm.ws.webcontainer.managedobject.ManagedObjectListenerW
rapper.sessionDestroyed(ManagedObjectListenerWrapper.java:90)
at com.ibm.ws.session.http.HttpSessionObserver.sessionDestroyed
(HttpSessionObserver.java:202)
at com.ibm.ws.session.SessionEventDispatcher.sessionDestroyed(S
essionEventDispatcher.java:160)
at com.ibm.ws.session.StoreCallback.sessionInvalidated(StoreCal
lback.java:126)
at com.ibm.ws.session.store.memory.MemorySession.invalidate(Mem
orySession.java:226)
at com.ibm.ws.session.http.HttpSessionImpl.invalidate(HttpSessi
onImpl.java:303)
at
com.ibm.ws.session.SessionData.invalidate(SessionData.java:247)
at com.ibm.ws.session.HttpSessionFacade.invalidate(HttpSessionF
acade.java:200)

**Steps to Reproduce**  
In some instances, closing a secure WebSocket connection that has timed out may hang a WebContainer thread..

**Expected behavior**  

The WebSocket should close the connection and the WebContainer thread should exit.

**Diagnostic information:**  
 - OpenLiberty Version: 16.0.0.2 - 22.0.0.4
 - Affected feature(s): WebSocket

**Additional context**  
n/a

### PR DESCRIPTION
**Pull request by loriadi**
fixes #20676

### CODE REVIEW

**Comment by loriadi** [comment]
#build

**Comment by loriadi** [comment]
#build

**Comment by loriadi** [comment]
The build failure is not related to this change.

**Comment by loriadi** [comment]
#run-libbybot

**Review by mrsaldana — APPROVED** [review]
LGTM, thanks for your work debugging this one!

**Comment by covener** [comment]
Hi all, sorry for the spam but we will randomly be using this old closed PR/issue combo to do some testing of the `#fixes PH12345` stuff.  We will remove/edit out any confusing comments.

**Comment by rsherget** [comment]
#fixes PH00000
#fixes PH99999

**Pull request merged**
