### PR TITLE
Tighten coordination of peer recoveryComplete processing

### LINKED ISSUE #20495: More coordination of peer recoveryComplete processing with home server shutdown
Testing found another window where threads driving peer recovery and shutdown can interfere.

### PR DESCRIPTION
**Pull request by neilgsyoung**
fixes #20495

### CODE REVIEW

**Comment by neilgsyoung** [comment]
#build

**Comment by neilgsyoung** [comment]
#build

**Comment by neilgsyoung** [comment]
#run-libby-bot

**Comment by neilgsyoung** [comment]
#build

**Comment by neilgsyoung** [comment]
#build

**Review by jonhawkes — APPROVED** [review]

**Pull request merged**
