### PR TITLE
Fix ClassCastException in WebContainer session

### LINKED ISSUE #23111: ClassCastException from com.ibm.ws.webcontainer.session.impl.HttpSessionContextImpl.getSessionUserName
I'm running a jakarta sso security test that sets a short lifetime to access and/or id_tokens created by the Openid Connect provider.  When the user tries to use the now expired token the RP/client makes a request of the OP and I end up with the following ClassCastExpetion.

```
10/21/22, 18:14:23:373 CDT] 00000038 com.ibm.ws.webcontainer.util.ApplicationErrorUtils           E SRVE0777E: Exception thrown by application class 'com.ibm.ws.webcontainer.session.impl.HttpSessionContextImpl.getSessionUserName:695'
java.lang.ClassCastException: io.openliberty.webcontainer60.session.impl.WCHttpSessionImpl60 incompatible with com.ibm.ws.session.SessionData
	at com.ibm.ws.webcontainer.session.impl.HttpSessionContextImpl.getSessionUserName(HttpSessionContextImpl.java:695)
	at com.ibm.ws.webcontainer.security.AuthenticateApi.getSessionUserName(AuthenticateApi.java:294)
	at com.ibm.ws.webcontainer.security.AuthenticateApi.logoutUnprotectedResourceServiceRef(AuthenticateApi.java:243)
	at com.ibm.ws.webcontainer.security.AuthenticateApi.logout(AuthenticateApi.java:191)
	at com.ibm.ws.webcontainer.security.AuthenticateApi.logoutServlet30(AuthenticateApi.java:647)
	at com.ibm.ws.webcontainer.security.WebAppSecurityCollaboratorImpl.logout(WebAppSecurityCollaboratorImpl.java:1199)
	at com.ibm.ws.webcontainer.srt.SRTServletRequest.logout(SRTServletRequest.java:4010)
	at com.ibm.ws.security.openidconnect.web.OidcEndpointServices.processEndSession(OidcEndpointServices.java:528)
	at com.ibm.ws.security.openidconnect.web.OidcEndpointServices.handleOidcRequest(OidcEndpointServices.java:283)
	at com.ibm.ws.security.openidconnect.web.OidcEndpointServlet.handleRequest(OidcEndpointServlet.java:109)
	at com.ibm.ws.security.openidconnect.web.OidcEndpointServlet.doGet(OidcEndpointServlet.java:59)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:527)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:614)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1258)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:746)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:443)
	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.invokeTarget(WebAppFilterChain.java:193)
	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:98)
	at com.ibm.ws.security.openidconnect.web.OidcRequestFilter.setEndpointRequest(OidcRequestFilter.java:41)
```

[sessionData.zip](https://github.com/OpenLiberty/open-liberty/files/9862912/sessionData.zip)

### PR DESCRIPTION
**Pull request by pmd1nh**
fixes #23111

### CODE REVIEW

**Comment by pmd1nh** [comment]
#build
#spawn.fullfat.buckets=io.openliberty.webcontainer.servlet.6.0.internal_fat,com.ibm.ws.webcontainer.servlet.3.1_fat,com.ibm.ws.webcontainer.servlet.4.0_fat,com.ibm.ws.session_fat,com.ibm.ws.session_fat_lWAS_servlet.3.1.toleration,com.ibm.ws.session.cache_fat,com.ibm.ws.session.cache_fat_config,com.ibm.ws.session.cache_fat_config_infinispan,com.ibm.ws.session.cache_fat_infinispan,com.ibm.ws.session.cache_fat_infinispan_container,com.ibm.ws.session.cache_provider_fat

**Review by pnicolucci — APPROVED** [review]

**Comment by pmd1nh** [comment]
#build
#spawn.fullfat.buckets=io.openliberty.webcontainer.servlet.6.0.internal_fat,com.ibm.ws.webcontainer.servlet.3.1_fat,com.ibm.ws.webcontainer.servlet.4.0_fat,com.ibm.ws.session_fat,com.ibm.ws.session_fat_lWAS_servlet.3.1.toleration,com.ibm.ws.session.cache_fat,com.ibm.ws.session.cache_fat_config,com.ibm.ws.session.cache_fat_config_infinispan,com.ibm.ws.session.cache_fat_infinispan,com.ibm.ws.session.cache_fat_infinispan_container,com.ibm.ws.session.cache_provider_fat

**Comment by pmd1nh** [comment]
resubmitted session.cache_fat.  all passed

com.ibm.ws.session.cache_fat FAT tests | 174 | 0 | 3 |   |  
-- | -- | -- | -- | -- | --
com.ibm.ws.session.cache_fat FAT tests | 182 | 0 | 0 |   |

**Comment by pmd1nh** [comment]
#libby

**Pull request merged**
