### PR TITLE
Java level and Eclipse setting updates

### PR DESCRIPTION
**Pull request by jhanders34**
- Mark telemetry tck FAT project to compile with Java 11 so that it doesn't run with Java 8 since it is using EE10 features.
- Update pages.3.1.internal.factories project to compile to Java 11 byte code
- Add missing and remove extra source directory to .classpath files where it was missing or extra.
- Remove gradle buildship build from .project file.

### CODE REVIEW

**Comment by jhanders34** [comment]
#build

**Comment by jhanders34** [comment]
#build

**Comment by jhanders34** [comment]
#libby #build

**Review by volosied — APPROVED** [review]

**Comment by jhanders34** [comment]
#libby

**Pull request merged**
