### PR TITLE
Moved the RequestTiming enableThreadDumps attribute from beta to GA

### LINKED ISSUE #16255: Move RequestTiming-1.0 enableThreadDumps from beta to GA

### PR DESCRIPTION
**Pull request by pgunapal**
fixes #16255 
- Moved the enableThreadDumps attribute from beta to GA in the metatype.xml
- Added enableThreadDumps to the HungRequestTimingConfig/HungRequest debug trace.

### CODE REVIEW

**Comment by pgunapal** [comment]
#build

**Comment by pgunapal** [comment]
#build

**Comment by pgunapal** [comment]
#build

**Review by fmhwong — APPROVED** [review]
LGTM

**Comment by pgunapal** [comment]
#libby

**Pull request merged**
