### PR TITLE
Issue #17486: Cleanup removeAttribute/getAttribute

### LINKED ISSUE #17486: Clean up WebContainerRequestState.removeAttribute/getAttribute
There is no need to store the value returned from `_attributes.remove(arg0);`
Also minor cleanup of `getAttribute`

### PR DESCRIPTION
**Pull request by pnicolucci**
fixes #17486

### CODE REVIEW

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Review by wtlucy — APPROVED** [review]
LGTM

**Comment by pnicolucci** [comment]
#run-libby-bot

**Pull request merged**
