### PR TITLE
Issue #15037: Add JACC proxy provider sample project.

### LINKED ISSUE #15037: Jakarta Authorization: Add JACC proxy provider sample project.

### PR DESCRIPTION
**Pull request by jvanhill**
closes #15037

### CODE REVIEW

**Comment by jvanhill** [comment]
#build

**Comment by jvanhill** [comment]
#build
#libby

**Comment by andrea-pichler** [comment]
No message review requested from L2

**Comment by jvanhill** [comment]
#build
#libby

**Review by helyarp — COMMENTED** [review]
Looks good!

**Review by Zech-Hein — APPROVED** [review]

**Comment by jvanhill** [comment]
#build

**Comment by jvanhill** [comment]
#libby

**Comment by jvanhill** [comment]
This PR is good to go once the streams are unlocked.

**Pull request merged**
