### PR TITLE
create nonship configValidator feature, porting over the Config REST API handler first

### PR DESCRIPTION
**Pull request by njr-11**
Create a nonship feature under which we can port the config/validator REST APIs that have been in beta for a while, and further experiment with them without making any of the function GA.  This nonship feature might end up being used for a beta in open liberty, or might eventually be removed in favor of an approach using autofeatures.

### CODE REVIEW

**Comment by njr-11** [comment]
#build

**Comment by njr-11** [comment]
The ID review should be unnecessary at this time given that the feature created under this pull is a nonship feature with the sole purpose of keeping the function out of GA as we experiment with it.

**Comment by skasund** [comment]
L2 message review not required

**Comment by njr-11** [comment]
#build

**Pull request merged**
