### PR TITLE
FAT for Faces 4.0 ExternalContext addResponseCookie API

### LINKED ISSUE #20811: Faces 4.0: add support for SameSite attribute in ExternalContext#addResponseCookie() properties
Spec issue: `https://github.com/jakartaee/faces/issues/1570`

See: https://balusc.omnifaces.org/2021/11/whats-new-in-faces-40.html
https://jakarta.ee/specifications/faces/4.0/apidocs/jakarta/faces/context/externalcontext#addResponseCookie(java.lang.String,java.lang.String,java.util.Map)

### PR DESCRIPTION
**Pull request by pnicolucci**
fixes #20811

### CODE REVIEW

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
#libby #build

**Review by volosied — APPROVED** [review]
Looks good!

**Pull request merged**
