### PR TITLE
Issue #2370: set _sessionCreated only when a session is actually created

### PR DESCRIPTION
**Pull request by pnicolucci**

### CODE REVIEW

**Comment by pnicolucci** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.webcontainer.servlet.4.0_fat

**Comment by pnicolucci** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.webcontainer.servlet.4.0_fat

**Comment by pnicolucci** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.webcontainer.servlet.4.0_fat

**Comment by wraschke** [comment]
Test.

**Comment by wraschke** [comment]
Test.

**Comment by wraschke** [comment]
#build

**Comment by wraschke** [comment]
#build

**Comment by wraschke** [comment]
#run-libby-bot

**Comment by pnicolucci** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.webcontainer.servlet.4.0_fat

**Comment by pnicolucci** [comment]
between the last couple of builds everything has passed. The failures are not looking to be related to any of these changes in this PR.

**Pull request merged**
