### PR TITLE
refactoring to QueryInfo

### PR DESCRIPTION
**Pull request by njr-11**
Refactoring mainly to QueryInfo and RepositoryImpl that involves renaming a misleading field, moving methods to where they make more sense, and moving some constants and utility methods to a utility class. While doing this, I spotted an exception that was being raised with its NLS message id missing, which would cause its message to appear wrongly in the exception and for its message not to be logged. After fixing that, we also needed excludes of those messagse for tests that were causing the error on purpose to test it.

- [x] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [x] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [x] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

### CODE REVIEW

**Comment by njr-11** [comment]
#build

**Comment by contbld** [comment]
Your personal pipeline request is at https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=62f017ce-bda6-4a95-842e-26fc001ad17f

Target locations of links might be accessible only to IBM employees.

**Comment by contbld** [comment]
<h3>Code analysis and actions</h3>
DO NOT DELETE THIS COMMENT.

- 8 FAT files were changed, added, or removed.
 - Check that the build did not break the affected FAT suite(s).

- 5 product code files were changed.

**Comment by contbld** [comment]
https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=62f017ce-bda6-4a95-842e-26fc001ad17f has errors/failures.

**Comment by njr-11** [comment]
#build

**Comment by contbld** [comment]
Your personal pipeline request is at https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=60986413-1f74-44ce-affc-b55bb5e6bbdf

Target locations of links might be accessible only to IBM employees.

**Review by mswatosh — APPROVED** [review]

**Comment by contbld** [comment]
<h3>Code analysis and actions</h3>
DO NOT DELETE THIS COMMENT.

- 8 FAT files were changed, added, or removed.
 - Check that the build did not break the affected FAT suite(s).

- 5 product code files were changed.

**Comment by njr-11** [comment]
> https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=62f017ce-bda6-4a95-842e-26fc001ad17f has errors/failures.

Both of the intermittent test failures are preexisting issues. Unfortunately one of those intermittent errors showed up in the Jakarta Data TCK bucket. However, it did not stop any tests from running and was only the `CWWKD1080E` that is known to appear in the server logs when the TCK uninstalls the test application while Liberty is still doing some work related to that application. That preexisting issues is unrelated to these changes and did not stop any of the tests from running.

**Comment by contbld** [comment]
https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=60986413-1f74-44ce-affc-b55bb5e6bbdf has errors/failures.

**Comment by contbld** [comment]
The build njr-11-30107-20241108-0423
https://wasrtc.hursley.ibm.com:9443/jazz/resource/itemOid/com.ibm.team.build.BuildResult/_ndLRMJ3CEe-M9e5esDPP_g
completed successfully!

**Comment by contbld** [comment]
The build njr-11-30107-20241109-0348
https://wasrtc.hursley.ibm.com:9443/jazz/resource/itemOid/com.ibm.team.build.BuildResult/_QuTLcJ5EEe-M9e5esDPP_g
completed successfully!

**Pull request merged**
