### PR TITLE
Login integration latest changes

### PR DESCRIPTION
**Pull request by ezhou365**

### CODE REVIEW

**Comment by ezhou365** [comment]
#build

**Comment by ezhou365** [comment]
#build
#spawn.fullfat.buckets= com.ibm.ws.security.social_fat,
com.ibm.ws.security.social_fat.GitHub,
com.ibm.ws.security.social_fat.LibertyOP,
com.ibm.ws.security.social_fat.delegated,
com.ibm.ws.security.social_fat.facebook,
com.ibm.ws.security.social_fat.linkedin,
com.ibm.ws.security.social_fat.multiProvider,
com.ibm.ws.security.social_fat.oidcCertification,
com.ibm.ws.security.social_fat.twitter

**Comment by ezhou365** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.security.social_fat,
com.ibm.ws.security.social_fat.LibertyOP,
com.ibm.ws.security.social_fat.delegated,
com.ibm.ws.security.social_fat.multiProvider,
com.ibm.ws.security.social_fat.oidcCertification

**Comment by jantley-ibm** [comment]
ID review not needed, deletions only

**Comment by ezhou365** [comment]
#run-libby-bot

**Pull request merged**
