### PR TITLE
make up front trace instrumentation property enabled

### PR DESCRIPTION
**Pull request by ewhoch**
for issue #226, this is the same fix that went into 17003 rolled up to the integration stream.

### CODE REVIEW

**Comment by ewhoch** [comment]
#build

**Comment by wraschke** [comment]
#run-libby

**Comment by wraschke** [comment]
#liberty-for-life

**Comment by wraschke** [comment]
#build

**Comment by ewhoch** [comment]
#build

**Comment by ewhoch** [comment]
#build

**Pull request closed without merging**
