### PR TITLE
Plugin generator should better handle bad bundle states

### PR DESCRIPTION
**Pull request by wtlucy**
For #17047

### CODE REVIEW

**Comment by wtlucy** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.webcontainer_fat,com.ibm.ws.webserver.plugin.runtime_fat,com.ibm.ws.webserver.plugin.runtime_fat_servlet31,com.ibm.ws.webserver.plugin.utility_fat

**Review by volosied — APPROVED** [review]
LGTM

**Comment by wtlucy** [comment]
#build

**Comment by wtlucy** [comment]
#run-libby-bot

**Pull request merged**
