### PR TITLE
Migrate jpa injection ejb in war fat

### PR DESCRIPTION
**Pull request by jgrassel**
Migrate the JPA EJB-In-WAR fat bucket to OpenLiberty, as well as refactor the JPA Injection bucket to rely on fewer app server starts.  The change reduced my local sandbox execution of com.ibm.ws.jpa_spec10_injection_fat by 50%.

### CODE REVIEW

**Comment by jgrassel** [comment]
#build

**Comment by jgrassel** [comment]
Updated as per review comments.

#build
#run-libby-bot

**Review by dazey3 — APPROVED** [review]
LGTM

**Comment by jgrassel** [comment]
#run-libby-bot

**Pull request merged**
