### PR TITLE
JAX-WS: Refactor LibertyCXFPositivePropertiesTest

### PR DESCRIPTION
**Pull request by neuwerk**
This PR refactors the `LIbertyCXFPositivePropertiesTest` suite in order to address repeated timeout failures. 

The test methods have been moved to the `LIbertyCXFPositivePropertiesTestServlet.java` class

1. `LIbertyCXFPositivePropertiesTestServlet` now  contains  the `WebServiceRef` clients to prevent connection issues
2. The test application has been moved into a separate test-application directory `libertyCXFProperites` to clean up overlaps with `WebServiceRefFeatureTest`
3. Cleaned up code overlap and reused code from other applications
4. Addressed the cause of the timeouts by fixing the `server.xml` configuration

### CODE REVIEW

**Review by BerksanAtes — DISMISSED** [review]
It's a complete rewrite of the test. Better architecture for sure. I like the comments. Looks good to me as long as It PB passes :)

**Comment by neuwerk** [comment]
#build

**Comment by neuwerk** [comment]
#build

**Comment by neuwerk** [comment]
#build

**Comment by neuwerk** [comment]
#build

**Comment by neuwerk** [comment]
#build

**Comment by neuwerk** [comment]
#build

**Comment by neuwerk** [comment]
#build

**Comment by neuwerk** [comment]
#build

**Comment by neuwerk** [comment]
#libby

**Review by sawadood — APPROVED** [review]
Changes look good.

**Pull request merged**
