### PR TITLE
add tlsprofiler securityutility command

### PR DESCRIPTION
**Pull request by ryanesch**

### CODE REVIEW

**Comment by andrea-pichler** [comment]
Completed the requested L2 message review

**Comment by ryanesch** [comment]
#build

**Comment by ryanesch** [comment]
#build

**Comment by ryanesch** [comment]
#build

**Review by una-tapa — APPROVED** [review]
The change looks good.  Thanks!

**Comment by ryanesch** [comment]
#build

**Comment by ryanesch** [comment]
#run-libby-bot

**Pull request merged**
