### PR TITLE
Update oracle jdbc driver to 23c

### PR DESCRIPTION
**Pull request by KyleAure**
Follow up to: https://github.com/OpenLiberty/open-liberty/pull/28997

### CODE REVIEW

**Comment by KyleAure** [comment]
#libby - check headers
#build - personal build

**Comment by KyleAure** [comment]
#libby - check headers
#build - personal build (expect failures)

**Comment by KyleAure** [comment]
#libby - check headers
#build - personal build

**Comment by KyleAure** [comment]
RTC Build: Failed with 2 known defects 
Pipeline Build: Failed with 2 known defects

**Review by mswatosh — APPROVED** [review]

**Pull request merged**
