### PR TITLE
com.ibm.ws.wssecurity_fat.wsscxf.2/.3 (renamed and split from old wsscxf.1) update per new jaxws-2.2

### PR DESCRIPTION
**Pull request by meiaus**
Parent issue: https://github.com/OpenLiberty/open-liberty/issues/23060

**Note:** com.ibm.ws.wssecurity_fat.wsscxf.1 is split to 2 to balance the execution time/load:

com.ibm.ws.wssecurity_fat.wsscxf.2
com.ibm.ws.wssecurity_fat.wsscxf.3

com.ibm.ws.wssecurity_fat.wsscxf will be renamed to com.ibm.ws.wssecurity_fat.wsscxf.1 via different PR.

### CODE REVIEW

**Comment by meiaus** [comment]
#run-libby-bot

**Comment by meiaus** [comment]
#run-libby-bot

**Comment by meiaus** [comment]
#build

**Comment by meiaus** [comment]
1. The personal build with `auto` passed per the updated FAT:

image

image

The error in this build is out of scope from this PR:
image

2. The personal build with SOE platforms passed:

image

image

image

**Comment by meiaus** [comment]
@arunavemulapalli the PR is ready for review/approval.  Thanks.

**Comment by meiaus** [comment]
#run-libby-bot

**Comment by meiaus** [comment]
#run-libby-bot

**Comment by meiaus** [comment]
#build

**Comment by meiaus** [comment]
#run-libby-bot

**Comment by meiaus** [comment]
#build

**Comment by meiaus** [comment]
#run-libby-bot

**Comment by meiaus** [comment]
#build

**Comment by meiaus** [comment]
#run-libby-bot

**Comment by meiaus** [comment]
#run-libby-bot

**Comment by meiaus** [comment]
#build

**Comment by meiaus** [comment]
3 personal builds' result:
1. With the new projects specified: passed

image

image

2.  (Reran) With `All`: passed
image

image


4. (Reran) With multiple SOE platforms: passed 

image

image

image

**Review by arunavemulapalli — APPROVED** [review]

**Pull request merged**
