### PR TITLE
use ManagedChannelRegistry instead of ServiceLoader to register ManagedChannelProvider

### LINKED ISSUE #17904: grpcClient-1.0 dynamic enablement unexpected behavior
Currently `grpcClient-1.0` relies on the ServiceLoader functionality, to register a ManagedChannelProvider which can be used by user apps. Unfortunately this ManagedChannelProvider ServiceLoader reference is not dynamic in our OSGi context - so if a server is started without `grpcClient-1.0` enabled, then enabling `grpcClient-1.0` at a later time will not actually enable the Liberty `ManagedChannelProvider`.

### PR DESCRIPTION
**Pull request by wtlucy**
Fixes #17904

### CODE REVIEW

**Comment by wtlucy** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.grpc_fat

**Comment by wtlucy** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.grpc_fat

**Comment by wtlucy** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.grpc_fat

**Review by annaguri — APPROVED** [review]
Looks good to me

**Review by loriadi — APPROVED** [review]
Looks good, Bill.

**Comment by wtlucy** [comment]
#run-libby-bot

**Comment by wtlucy** [comment]
#run-libby-bot

**Comment by wtlucy** [comment]
wrong button 😦

**Pull request merged**
