### PR TITLE
FeatureUtility enable no proxy

### PR DESCRIPTION
**Pull request by jjiwooLim**
Implemented no proxy for featureUtility
To set no_proxy using the environment variable, use `no_proxy`.
To set it using `featureUtility.properties`, use `http.nonProxyHosts` (name used by jvm system properties)

### CODE REVIEW

**Review by bensonlatibm — APPROVED** [review]
lgtm!

**Review by bensonlatibm — CHANGES_REQUESTED** [review]
Please update copyright dates to 2024.

**Comment by jjiwooLim** [comment]
#build

**Comment by jjiwooLim** [comment]
#build 
#create.im.repo=true

**Comment by jjiwooLim** [comment]
#build

**Comment by jjiwooLim** [comment]
#build
#create.im.repo=true

**Comment by jjiwooLim** [comment]
#libby-bot

**Comment by jjiwooLim** [comment]
FAT failures not related to this changes

**Comment by jjiwooLim** [comment]
#build

**Comment by jjiwooLim** [comment]
Beta tests ran successfully

**Review by bensonlatibm — APPROVED** [review]
lgtm!

**Pull request merged**
