### PR TITLE
Issue #1689: Set JSF 2.3 WSOC dependency apiJar=false

### PR DESCRIPTION
**Pull request by pnicolucci**

### CODE REVIEW

**Comment by pnicolucci** [comment]
Fixes #1689

**Comment by pnicolucci** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jsf.2.3_fat

**Comment by brutif** [comment]
#build

**Comment by rbtcwt** [comment]
#build

**Comment by pnicolucci** [comment]
#build 
#spawn.fullfat.buckets=com.ibm.ws.jsf.2.3_fat

**Comment by pnicolucci** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.jsf.2.3_fat

**Comment by pnicolucci** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.jsf.2.3_fat

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jsf.2.3_fat

**Comment by pnicolucci** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jsf.2.3_fat

**Pull request merged**
