### PR TITLE
All HAMs to support Decorator and Alternative

### PR DESCRIPTION
**Pull request by utle**
All HAMs to support Decorator and Alternative

### CODE REVIEW

**Comment by utle** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.security.javaeesec_fat,com.ibm.ws.security.javaeesec_fat.2,com.ibm.ws.security.javaeesec_fat.3,com.ibm.ws.security.javaeesec_fat.4,com.ibm.ws.security.jaspic_fat,com.ibm.ws.security.jaspic.jakarta10_fat,io.openliberty.security.jakartasec.3.0.internal_fat, io.openliberty.security.jakartasec.3.0.internal_fat.config, io.openliberty.security.jakartasec.3.0.internal_fat.logout

**Comment by utle** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.security.javaeesec_fat,com.ibm.ws.security.javaeesec_fat.2,com.ibm.ws.security.javaeesec_fat.3,com.ibm.ws.security.javaeesec_fat.4,com.ibm.ws.security.jaspic_fat,com.ibm.ws.security.jaspic.jakarta10_fat,io.openliberty.security.jakartasec.3.0.internal_fat, io.openliberty.security.jakartasec.3.0.internal_fat.config

**Comment by utle** [comment]
https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_JglLAGO_Ee2FXtyvmy2tqA

**Comment by utle** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.security.javaeesec_fat,com.ibm.ws.security.javaeesec_fat.2,com.ibm.ws.security.javaeesec_fat.3,com.ibm.ws.security.javaeesec_fat.4,com.ibm.ws.security.jaspic_fat,com.ibm.ws.security.jaspic.jakarta10_fat,io.openliberty.security.jakartasec.3.0.internal_fat, io.openliberty.security.jakartasec.3.0.internal_fat.config

**Comment by utle** [comment]
#run-libby-bot

**Review by teddyjtorres — APPROVED** [review]

**Pull request merged**
