### PR TITLE
server env expansion var test failure ZOS

### PR DESCRIPTION
**Pull request by jimblye**
fixes issue #23468

### CODE REVIEW

**Comment by jimblye** [comment]
#build #libby

**Review by hlhoots — DISMISSED** [review]
LGTM

**Comment by jimblye** [comment]
#build

**Review by hlhoots — APPROVED** [review]
LGTM

**Comment by jimblye** [comment]
#build 
Will create a z/OS build off of settings for the auto-generated build per [these instructions](https://github.ibm.com/websphere/WS-CD-Open/wiki/Requesting-a-Personal-Build-that-tests-against-zOS).

**Comment by jimblye** [comment]
#libby

**Comment by jimblye** [comment]
The two tests that were disabled showed as passing in the ZOS build.   There were many failures in the ZOS build in the kernel.boot_fat.  They seem to all be "Start Server errors", but not related to the test that is modified by this PR.

**Pull request merged**
