### PR TITLE
Issue #21245-NPE In ServerSTartTest.java

### LINKED ISSUE #21245: Fix NPE in ServerStartTest.java
The following NPE happens whenever the jcmd command cannot find the pid for a java process.

java.lang.NullPointerException
at java.lang.ProcessBuilder.start(ProcessBuilder.java:1012)
at java.lang.Runtime.exec(Runtime.java:621)
at java.lang.Runtime.exec(Runtime.java:486)
at com.ibm.ws.kernel.boot.ServerStartTest.test_SWD_InvalidPath(ServerStartTest.java:767)

### PR DESCRIPTION
**Pull request by hlhoots**
#build 
fixes #21245

### CODE REVIEW

**Comment by hlhoots** [comment]
#build

**Review by cbridgha — APPROVED** [review]
Looks good  - maybe update the copyright

**Comment by hlhoots** [comment]
Builds seemed to run this test correctly.  There were other known issues with the build.  Given this going to merge.

**Comment by hlhoots** [comment]
#run-libby-bot

**Pull request merged**
