### PR TITLE
featureUtility proxy environment variable bug

### LINKED ISSUE #30018: featureUtiliy doesn't connect to proxy when set with environment variable
**Describe the bug**  
featureUtility doesn't connect to proxy when it's set through environment variable.

**Steps to Reproduce**  
Steps to reproduce the bug
```
export http_proxy=http://localhost:3128
./featureUtility installFeature json-1.0

```

**Expected behavior**  
It should connect to Maven repository via proxy. 

**Diagnostic information:**  
 - OpenLiberty Version: [e.g. 23.0.0.9 - 23.0.0.11]

### PR DESCRIPTION
**Pull request by jjiwooLim**
- [ ] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [ ] Fixes #30018

### CODE REVIEW

**Comment by jjiwooLim** [comment]
#build

**Comment by jjiwooLim** [comment]
!pbbeta
create.im.repo=true

**Comment by jjiwooLim** [comment]
Test failures unrelated to my changes

**Review by bensonlatibm — APPROVED** [review]
lgtm!

**Pull request merged**
