### PR TITLE
Change audit code to call secureRandom

### PR DESCRIPTION
**Pull request by acdemyers**
Removing some code from audit that generated it's own random.

### CODE REVIEW

**Comment by acdemyers** [comment]
#build

**Comment by acdemyers** [comment]
#build

**Comment by wraschke** [comment]
#pbbeta@dev

**Comment by wraschke** [comment]
#pbbeta

**Comment by acdemyers** [comment]
#build

**Review by emilytee — APPROVED** [review]

**Comment by acdemyers** [comment]
#pbbeta

**Pull request merged**
