### PR TITLE
Fix policy attachments issue 19334

### LINKED ISSUE #19334: Policy attachments file: policy-attachments-server.xml is not processed
The policy attachments file: policy-attachments-server.xml packaged under META-INF of an EJB module of a Web services provider is not processed.

### PR DESCRIPTION
**Pull request by sawadood**
The policy attachments file: policy-attachments-server.xml packaged with a Web services application is not getting processed. This pull request is opened to fix issue 19334.

fixes #19334

### CODE REVIEW

**Comment by sawadood** [comment]
fixes #19334

**Comment by sawadood** [comment]
#build - Starting a personal build

**Review by neuwerk — APPROVED** [review]
Changes look good to me! Thanks Syed!!

**Comment by sawadood** [comment]
#run-libby-bot

**Pull request merged**
