### PR TITLE
Felix SCR fix for FELIX-6327

### PR DESCRIPTION
**Pull request by tjwatson**
This is to address FELIX-6327 issue
https://issues.apache.org/jira/browse/FELIX-6327

### CODE REVIEW

**Comment by tjwatson** [comment]
#build

**Comment by tjwatson** [comment]
Fixes issue #13895

**Comment by tjwatson** [comment]
#build

**Review by sebratton — APPROVED** [review]
Looks good. Don't forget DHE upload.

**Comment by tjwatson** [comment]
#build

**Comment by tjwatson** [comment]
#build

**Comment by tjwatson** [comment]
> Looks good. Don't forget DHE upload.

Felix SCR has had an official release that includes the necessary fix.  I have updated the PR to use the version available in maven central.  Doing another build to verify.

**Comment by tjwatson** [comment]
#build

**Comment by tjwatson** [comment]
#build

**Comment by tjwatson** [comment]
#run-libby-bot

**Pull request merged**
