### PR TITLE
Orphaned transaction changes

### PR DESCRIPTION
**Pull request by dhaggart**
Initial take on changes to orphan transaction handling including additional diagnostics.

### CODE REVIEW

**Comment by dhaggart** [comment]
#run-libby-bot

**Comment by dhaggart** [comment]
#build

**Comment by dhaggart** [comment]
Andrew, since TransactionReference will still try to complete Inactive transactions, I thought it best to only avoid the FFDC if/when there was no reserved transaction space.  As you say, if we have Inactive with a non-zero reservation we have a more serious issue and probably should bring things down.

**Comment by andrea-pichler** [comment]
No L2 message review required for translations

**Comment by AndrewDJBanks** [comment]
Good point. Yes things are better as they are.

**Pull request merged**
