### PR TITLE
Openjdk 15 platforms are causing NPE.

### PR DESCRIPTION
**Pull request by ismartspace**
Openjdk 15 platforms are causing NPE.
Added if statement to check if the value is null before comparing the value.

### CODE REVIEW

**Comment by ismartspace** [comment]
Pull request for #13926

**Comment by ismartspace** [comment]
#build

**Comment by ismartspace** [comment]
Successfully ran fat bucket 10 times on jdk 15 platfrom:
https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_PFC-0PZREeqwgKOHPUEi3Q

**Comment by ismartspace** [comment]
#build

**Comment by ismartspace** [comment]
https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_Z4TdsPasEeqwgKOHPUEi3Q&tab=com.ibm.team.build.web.ui.internal.editors.result.test.TestProvider

**Review by hermankailey — APPROVED** [review]

**Pull request merged**
