### PR TITLE
Sip netty update

### PR DESCRIPTION
**Pull request by isaacrivriv**
for https://github.com/OpenLiberty/open-liberty/issues/15779

### CODE REVIEW

**Comment by isaacrivriv** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.sipcontainer_fat

**Comment by posmith** [comment]
L2 message review not required

**Comment by isaacrivriv** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.sipcontainer_fat

**Comment by isaacrivriv** [comment]
#build

**Comment by isaacrivriv** [comment]
#build

**Review by hutchig — APPROVED** [review]
I wondered about the useCompactHeaders TODO but other than that had no questions and looks good to me.

**Comment by isaacrivriv** [comment]
#libby

**Comment by isaacrivriv** [comment]
Last build errors unrelated to SIP. Also ran Full FAT Beta [build](https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_R32KUCWCEe6G1PEnFHKlyw&tab=com.ibm.team.build.web.ui.internal.editors.result.test.TestProvider) with channelfw and Netty and both buckets passed without errors. This is ready to merge

**Pull request merged**
