### PR TITLE
Update EclipseLink 2.7.8 -> 2.7.9

### PR DESCRIPTION
**Pull request by dazey3**
Updating EclipseLink from 2.7.8 to 2.7.9.

for #17018
for #17020
for #17022
for #17024
for #17026
for #17028
for #17368
for #17372
for #17375
for #17408

for #15956

### CODE REVIEW

**Comment by dazey3** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jpa_spec20_fat,com.ibm.ws.jpa_eclipselink_fat,com.ibm.ws.jpa.tests.spec10.query_jpa_2.2_fat

**Comment by dazey3** [comment]
#build

**Comment by dazey3** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jpa_spec20_fat,com.ibm.ws.jpa_eclipselink_fat,com.ibm.ws.jpa.tests.spec10.query_jpa_2.2_fat

**Comment by dazey3** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jpa_spec20_fat,com.ibm.ws.jpa_eclipselink_fat,com.ibm.ws.jpa.tests.spec10.query_jpa_2.2_fat

**Comment by dazey3** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jpa_spec20_fat,com.ibm.ws.jpa_eclipselink_fat,com.ibm.ws.jpa.tests.spec10.query_jpa_2.2_fat

**Review by jgrassel — APPROVED** [review]
lgtm

**Comment by dazey3** [comment]
#run-libby-bot

**Comment by FireBurn** [comment]
Hi

I'm seeing the following build failure locally:


```
> Task :com.ibm.websphere.appserver.thirdparty.eclipselink.2.7:processResources NO-SOURCE
> Task :com.ibm.websphere.appserver.thirdparty.eclipselink.2.7:classes
> Task :com.ibm.websphere.appserver.thirdparty.eclipselink.2.7:jar FAILED
warning: Split package, multiple jars provide the same package:org/eclipse/persistence/exceptions/i18n
Use Import/Export Package directive -split-package:=(merge-first|merge-last|error|first) to get rid of this warning
Package found in   [Jar:main, Jar:org.eclipse.persistence.core-2.7.9]
Class path         [Jar:main, Jar:org.eclipse.persistence.core-2.7.9, Jar:org.eclipse.persistence.jpa-2.7.9, Jar:javax.persistence-api-2.2, Jar:com.ibm.websphere.javaee.connector.1.7, Jar:com.ibm.websphere.org.osgi.core, Jar:com.ibm.websphere.javaee.jsonp.1.0, Jar:com.ibm.websphere.javaee.persistence.2.2, Jar:com.ibm.ws.logging.core, Jar:charsets, Jar:jsse, Jar:resources, Jar:jce, Jar:rt, Jar:management-agent]
warning: Split package, multiple jars provide the same package:org/eclipse/persistence/internal/helper
Use Import/Export Package directive -split-package:=(merge-first|merge-last|error|first) to get rid of this warning
Package found in   [Jar:main, Jar:org.eclipse.persistence.core-2.7.9]
Class path         [Jar:main, Jar:org.eclipse.persistence.core-2.7.9, Jar:org.eclipse.persistence.jpa-2.7.9, Jar:javax.persistence-api-2.2, Jar:com.ibm.websphere.javaee.connector.1.7, Jar:com.ibm.websphere.org.osgi.core, Jar:com.ibm.websphere.javaee.jsonp.1.0, Jar:com.ibm.websphere.javaee.persistence.2.2, Jar:com.ibm.ws.logging.core, Jar:charsets, Jar:jsse, Jar:resources, Jar:jce, Jar:rt, Jar:management-agent]
warning: Split package, multiple jars provide the same package:org/eclipse/persistence/internal/localization/i18n
Use Import/Export Package directive -split-package:=(merge-first|merge-last|error|first) to get rid of this warning
Package found in   [Jar:main, Jar:org.eclipse.persistence.core-2.7.9]
Class path         [Jar:main, Jar:org.eclipse.persistence.core-2.7.9, Jar:org.eclipse.persistence.jpa-2.7.9, Jar:javax.persistence-api-2.2, Jar:com.ibm.websphere.javaee.connector.1.7, Jar:com.ibm.websphere.org.osgi.core, Jar:com.ibm.websphere.javaee.jsonp.1.0, Jar:com.ibm.websphere.javaee.persistence.2.2, Jar:com.ibm.ws.logging.core, Jar:charsets, Jar:jsse, Jar:resources, Jar:jce, Jar:rt, Jar:management-agent]
warning: Unused Export-Package instructions: [org.eclipse.persistence.internal.libraries.asm*] 
warning: Imports that lack version ranges: [javax.crypto, javax.crypto.spec, javax.enterprise.context.spi, javax.enterprise.inject.spi, javax.imageio, javax.imageio.stream, javax.jms, javax.management, javax.management.openmbean, javax.mail.internet, javax.naming, javax.rmi, javax.rmi.CORBA, javax.sql, javax.transaction, javax.transaction.xa, javax.validation, javax.validation.groups, javax.validation.metadata, javax.xml.datatype, javax.xml.namespace, javax.xml.parsers, javax.xml.stream, javax.xml.stream.events, javax.xml.transform, javax.xml.transform.dom, javax.xml.transform.sax, javax.xml.transform.stream, javax.xml.validation, javax.xml.xpath, org.omg.CORBA, org.omg.CORBA.portable, org.omg.CORBA_2_3.portable, org.w3c.dom, org.xml.sax, org.xml.sax.ext, org.xml.sax.helpers, com.ibm.tx.jta, com.ibm.ws.Transaction, com.ibm.ws.jpa.container.eclipselink.logging]
warning: Unreferenced class path entries [rt, javax.persistence-api-2.2, com.ibm.websphere.javaee.connector.1.7, org.eclipse.persistence.core-2.7.9, com.ibm.websphere.org.osgi.core, resources, jsse, jce, com.ibm.websphere.javaee.persistence.2.2, org.eclipse.persistence.jpa-2.7.9, com.ibm.websphere.javaee.jsonp.1.0, management-agent, com.ibm.ws.logging.core, charsets]
error  : Can not find JAR file '/apps/was/.m2/repository/org/eclipse/persistence/org.eclipse.persistence.asm/2.7.9/org.eclipse.persistence.asm-2.7.9.jar'
error  : Can not find JAR file '/apps/was/.m2/repository/org/eclipse/persistence/org.eclipse.persistence.jpa.modelgen/2.7.9/org.eclipse.persistence.jpa.modelgen-2.7.9.jar'

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':com.ibm.websphere.appserver.thirdparty.eclipselink.2.7:jar'.
> com.ibm.websphere.appserver.thirdparty.eclipselink.2.7 has errors, 2 errors were reported
```

I can't find asm 2.7.9 or modelgen 2.7.9, am I missing something?

**Comment by FireBurn** [comment]
Ah looks like https://patch-diff.githubusercontent.com/raw/OpenLiberty/open-liberty/pull/17941.patch fixes it

**Pull request merged**
