### PR TITLE
Update Expression Language 6.0 to M21

### LINKED ISSUE #28794: Expression Language 6.0: Update to the M21 version for Expression Language 6.0
API: https://repo1.maven.org/maven2/org/apache/tomcat/tomcat-el-api/11.0.0-M21/
IMPL: https://repo1.maven.org/maven2/org/apache/tomcat/tomcat-jasper-el/11.0.0-M21/

### PR DESCRIPTION
**Pull request by pnicolucci**
fixes #28794

### CODE REVIEW

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#libby

**Review by volosied — APPROVED** [review]

**Pull request merged**
