### PR TITLE
Automate JSONB TCK

### LINKED ISSUE #19401: Automate Liberty FAT bucket to run the JSON-B TCK
User story:
"As the development team, I want an automated test bucket that runs the JSON-B TCK so that we can ensure that we only permit changes to go in which comply with the TCK, to avoid causing regressions to users."

### PR DESCRIPTION
**Pull request by KyleAure**
Fixes #19401 
Automate the Jsonb TCK by pulling in the TCK, and running against our internal bundles.

### CODE REVIEW

**Comment by KyleAure** [comment]
#build

**Review by nmittles — APPROVED** [review]

**Comment by KyleAure** [comment]
#build

**Comment by KyleAure** [comment]
#build

**Comment by KyleAure** [comment]
#build last build never ran :(

**Comment by KyleAure** [comment]
#libbybot

**Pull request merged**
