### PR TITLE
JVM Working Dir url and spaces test cases

### PR DESCRIPTION
**Pull request by hlhoots**
#build

### CODE REVIEW

**Comment by hlhoots** [comment]
#build

**Comment by hlhoots** [comment]
windows build: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_qr2jkFgiEeyWaZwSyDrk3A

**Comment by hlhoots** [comment]
This PR is required for #15128

**Comment by hlhoots** [comment]
windows build also good.  ready to merge once reviewed.

**Review by jimblye — APPROVED** [review]

**Comment by hlhoots** [comment]
#run-libby-bot

**Pull request merged**
