### PR TITLE
Ported JNDI FAT Tests

### PR DESCRIPTION
**Pull request by habiblawal1**

### CODE REVIEW

**Comment by habiblawal1** [comment]
#build

**Comment by habiblawal1** [comment]
#build

**Review by joe-chacko — DISMISSED** [review]
Excellent work!

**Comment by joe-chacko** [comment]
#libbybot #build

**Comment by joe-chacko** [comment]
#build

**Comment by habiblawal1** [comment]
#build

**Comment by joe-chacko** [comment]
#libbybot

**Review by joe-chacko — APPROVED** [review]
lgtm

**Comment by joe-chacko** [comment]
#libbybot

**Pull request merged**
