### PR TITLE
Enable WCPartitionedCookieAttributeSecurityTest

### LINKED ISSUE #28472: Enable WCPartitionedCookieAttributeSecurityTest once Security CHIPs work is delivered
https://github.com/OpenLiberty/open-liberty/blob/24bfb43dc6ba2fdee813c651a373abc0132f2433/dev/com.ibm.ws.webcontainer.servlet.4.0_fat/fat/src/com/ibm/ws/fat/wc/FATSuite.java#L111

### PR DESCRIPTION
**Pull request by pnicolucci**
fixes #28472

### CODE REVIEW

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Review by volosied — DISMISSED** [review]

**Comment by pnicolucci** [comment]
#libby

**Review by volosied — DISMISSED** [review]

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#libby #build

**Review by volosied — APPROVED** [review]
Looks good. Thanks for updating the test!

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#libby

**Pull request merged**
