### PR TITLE
remove allow http config attribute for token requests

### PR DESCRIPTION
**Pull request by brutif**
During externals review it was requested that this attribute be removed.

### CODE REVIEW

**Comment by brutif** [comment]
need to park this until fats are updated.

**Comment by bcpswope** [comment]
Looks like we are only deleting content here... need an ID review?

**Comment by brutif** [comment]
I think we're good, thanks

**Comment by brutif** [comment]
once FAT updates on 10281 are in, this one can proceed.

**Comment by brutif** [comment]
#build

**Comment by brutif** [comment]
argh, I had a bug.
#build

**Comment by brutif** [comment]
10281 is showing up in integration now, so let's try it again and see if that test has now  been deleted.
#build

**Comment by brutif** [comment]
pb is good, FAT updates have finally taken effect.

**Pull request merged**
