### PR TITLE
Update z/os plans to use more machines

### PR DESCRIPTION
**Pull request by rickettmwork**

### CODE REVIEW

**Review by dave-waddling — DISMISSED** [review]

**Comment by rickettmwork** [comment]
!pbbeta@dev
spawn.zos=true

**Comment by rickettmwork** [comment]
#libby

**Comment by rickettmwork** [comment]
!pbbeta@dev
spawn.zos=true

**Comment by rickettmwork** [comment]
!pbbeta@dev
spawn.zos=true

**Comment by rickettmwork** [comment]
#libby

**Review by dave-waddling — APPROVED** [review]

**Pull request merged**
