### PR TITLE
Update Jackson to 2.15.2

### PR DESCRIPTION
**Pull request by Azquelt**
Requires updating snakeyaml 2.0. Previous snakeyaml patch is no longer needed.

### CODE REVIEW

**Comment by Azquelt** [comment]
#libby
#build

**Comment by Azquelt** [comment]
#build
#pbbeta

**Comment by Azquelt** [comment]
#build
#pbbeta
#libby

**Comment by Azquelt** [comment]
#build
#libby
#pbbeta

**Comment by Azquelt** [comment]
A dependant repository needs a change first to stop using the removed no-arg constructor for `SafeConstructor` which is removed in snakeyaml 2.0

**Review by abutch3r — COMMENTED** [review]
Only note would be updating the `.java` copyrights to include 2023. otherwise looks good. given small size of change will approve if deemed insufficient to require date update.

**Comment by Azquelt** [comment]
Yeah, it's a bit close whether or not we should update the copyright dates here. I've made changes so that we do.

#build
#libby

**Review by abutch3r — APPROVED** [review]
LGTM

**Pull request merged**
