### PR TITLE
Move facesContainer-4.1 and websocket-2.2 to beta

### LINKED ISSUE #28747: WebSocket 2.2 / FacesContainer 4.1: Move to beta

### PR DESCRIPTION
**Pull request by pnicolucci**
fixes #28747

### CODE REVIEW

**Comment by pnicolucci** [comment]
#build

**Review by jhanders34 — DISMISSED** [review]

**Comment by pnicolucci** [comment]
build failures:

> java.lang.AssertionError: Found versionless features that are marked noship or beta, but contain only beta/ga features: 
> If you recently marked a feature beta, you may need to update the versionless feature to not depend on the noShip-1.0 feature and update the kind to beta or ga.
> Found issues with io.openliberty.internal.versionless.websocket-2.2
>      The feature is marked noship, but all dependencies are beta or ga
> 
> 	at org.junit.Assert.fail(Assert.java:93)
> 	at com.ibm.ws.feature.tests.VisibilityTest.testMissingBetaOrGAVersionlessFeatures(VisibilityTest.java:695)

**Comment by pnicolucci** [comment]
build failures:

> java.lang.AssertionError: Found features violating visibility conditions: 
> Found issues with Feature: [io.openliberty.facesContainer-4.1]   Edition: [core]   Kind: [beta]
>      It provisions less visible features: 
>      Feature: [io.openliberty.facesProvider-4.1.0.Container]   Edition: [full]   Kind: [noship]
> 
> 	at org.junit.Assert.fail(Assert.java:93)
> 	at org.junit.Assert.assertTrue(Assert.java:43)
> 	at org.junit.Assert.assertFalse(Assert.java:68)
> 	at com.ibm.ws.feature.tests.VisibilityTest.testVisibility(VisibilityTest.java:253)

**Comment by pnicolucci** [comment]
#build

**Review by jhanders34 — APPROVED** [review]

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#libby

**Pull request merged**
