### PR TITLE
Platform tests

### PR DESCRIPTION
**Pull request by rsherget**
- [x] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [x] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [x] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

Creates tests for various platform configurations

### CODE REVIEW

**Comment by rsherget** [comment]
#build

**Review by tbitonti — DISMISSED** [review]

**Comment by rsherget** [comment]
#build

**Comment by rsherget** [comment]
#build

**Review by hlhoots — APPROVED** [review]
Approving, pending a good build.

**Review by tbitonti — APPROVED** [review]

**Pull request merged**
