### PR TITLE
Performance Improvement 

### PR DESCRIPTION
**Pull request by jdmcclur**
If null, set response contentType to the header contentType

### CODE REVIEW

**Comment by jdmcclur** [comment]
#build

**Comment by jhanders34** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.webcontainer.servlet.4.0_fat,com.ibm.ws.webcontainer_fat,
com.ibm.ws.webcontianer_fat_lWAS,com.ibm.ws.webcontainer_fat_servlet31

**Comment by jhanders34** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.webcontainer.servlet.4.0_fat,com.ibm.ws.webcontainer_fat,
com.ibm.ws.webcontianer_fat_lWAS,com.ibm.ws.webcontainer_fat_servlet31

**Comment by pmd1nh** [comment]
Ideally, a getter should only retrieve.  However, I don't see any other way to improve the performance for this.  Also, since it is simple enough, we should be OK with this change.

**Comment by jdmcclur** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.webcontainer.servlet.4.0_fat,com.ibm.ws.webcontainer_fat,
com.ibm.ws.webcontianer_fat_lWAS,com.ibm.ws.webcontainer_fat_servlet31

**Comment by jdmcclur** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.webcontainer.servlet.4.0_fat,com.ibm.ws.webcontainer_fat,
com.ibm.ws.webcontianer_fat_lWAS,com.ibm.ws.webcontainer_fat_servlet31

**Pull request merged**
