### PR TITLE
Fix spelling of length in tests

### LINKED ISSUE #24453: Some JSF tests have the word `length` spelling incorrectly

### PR DESCRIPTION
**Pull request by pnicolucci**
fixes #24453

### CODE REVIEW

**Comment by pnicolucci** [comment]
#libby #build

**Review by isaacrivriv — APPROVED** [review]
Looks good, thanks for cleaning up!

**Comment by pnicolucci** [comment]
#libby

**Comment by pnicolucci** [comment]
#libby

**Comment by wraschke** [comment]
#libby

**Pull request merged**
