### PR TITLE
Removed special characters from comments

### PR DESCRIPTION
**Pull request by Mesbah-Alam**
Resolves https://github.com/OpenLiberty/open-liberty/issues/5092

Signed-off-by: Mesbah <Mesbah_Alam@ca.ibm.com>

### CODE REVIEW

**Comment by Mesbah-Alam** [comment]
@pnicolucci  - please review.

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Comment by Mesbah-Alam** [comment]
I tested this PR using an AdoptOpenJDK 8 SDK on our ci build system, here: https://ci.adoptopenjdk.net/view/work%20in%20progress/job/TestBuild_Sandbox2/377/console

Please ignore the tck test results - as this PR only concerns building of open-liberty -- which happens without error.

**Comment by aguibert** [comment]
#build

**Comment by aguibert** [comment]
Merging this PR without a build because it's just updates to code comments

**Pull request merged**
