### PR TITLE
Enable "LibbyBot" checks to run as part of personal pipeline

### PR DESCRIPTION
**Pull request by wraschke**
- [x] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [x] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [x] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

### CODE REVIEW

**Comment by wraschke** [comment]
#pb #pbbeta

**Comment by wraschke** [comment]
#pb #pbbeta

**Review by fritze2 — DISMISSED** [review]

**Review by websterc87 — DISMISSED** [review]
30 minute timeout for something that involve the EBC dynamic provisioning seems low. In the case of minor EBC queueing or fyre unavailability it would render it often unstable I would recommend a 2hr timeout as these steps do not need to complete until the PB complete so increasing tolerance will aid stability.

**Review by wraschke — COMMENTED** [review]
Latest commit 3f7ad4b has these requested changes.

**Review by fritze2 — APPROVED** [review]

**Comment by wraschke** [comment]
!libby !pb !pbbeta

**Review by wraschke — COMMENTED** [review]
Latest commit https://github.com/OpenLiberty/open-liberty/commit/3f7ad4b522de6e4cca455a49b7c46322e3c784ca has these requested changes.

**Comment by wraschke** [comment]
"pb" RTC pipeline passed 100% successfully.

beta pipeline has intermittently failed FATs with majority of them being TCKs failed due to connection timeouts or "Bad Gateway (502)" when trying to download from the remote Maven repository. There was a known issue investigated by Tools as a Service team: https://ibm-cloud.slack.com/archives/C56Q2EJ3S/p1729113272008289

This PR has no bearing on the failed FATs.

**Pull request merged**
