### PR TITLE
287571 wait for keystore

### PR DESCRIPTION
**Pull request by c00crane**
Have the builder minimum config tests wait for the keystores to be loaded before running any of the tests.

### CODE REVIEW

**Comment by c00crane** [comment]
#build

**Review by clarkek123 — APPROVED** [review]

**Comment by c00crane** [comment]
#build

**Comment by c00crane** [comment]
#build

**Comment by c00crane** [comment]
#run-libby-bot
#build

**Comment by c00crane** [comment]
#build

**Comment by c00crane** [comment]
#build
#run-libby-bot

**Pull request merged**
