### PR TITLE
Beta fence Request Timing Metrics

### PR DESCRIPTION
**Pull request by Channyboy**
#build

### CODE REVIEW

**Review by fmhwong — CHANGES_REQUESTED** [review]
`-Dcom.ibm.ws.beta.edition=true` is a JVM option.  Should it be put in `jvm.options`?

**Comment by Channyboy** [comment]
> `-Dcom.ibm.ws.beta.edition=true` is a JVM option. Should it be put in `jvm.options`?

Yup! I thought they would be picked up the same in bootstrap.options similar to what we allow it do in logging. But that should be two different mechanisms. Plus I forgot to remove the `-D` from two of the files even if it did.

**Comment by Channyboy** [comment]
#build
#run-libby-bot

**Review by fmhwong — APPROVED** [review]
LGTM

**Pull request merged**
