### PR TITLE
update testcontainers to 1.15.0

### PR DESCRIPTION
**Pull request by KyleAure**

### CODE REVIEW

**Comment by bsideup** [comment]
@KyleAure FYI 1.15.1 is out and is highly recommended as it fixes the compatibility with the latest Docker release :)

**Comment by KyleAure** [comment]
@bsideup Thanks.  Yes, the plan was to do 1.15.1.  Started this last week.  It looks like there were some breaking changes in DockerClientProviderStrategy since the last time we upgraded that I have been working on integrating.  🎉

**Comment by bsideup** [comment]
@KyleAure in 1.15.1 or 1.15.0? Because there shouldn't be any in 1.15.1 (unless we missed something 😅)

P.S. could you please ping me on Testcontainers' Slack and share how you're using `DockerClientProviderStrategy`? We plan to make a few changes to it and I would like to sync upfront :)

**Comment by KyleAure** [comment]
Closing as this update is being handled under #15296

**Pull request closed without merging**
