### PR TITLE
Make DefaultExceptionMapper work with restfulWS-3.0

### LINKED ISSUE #18793: MicroProfile Open Tracing and Metrics - Jakarta EE 9.1
MP OT and Metrics are currently unable to migrate to Jakarta EE 9.1 as they're both blocked by `com.ibm.ws.jaxrs.defaultexceptionmapper`. Until the exception mapper is migrated over to Jakarta, this issue will be completely blocked. It will be several weeks until this issue can be prioritized.

### PR DESCRIPTION
**Pull request by Azquelt**
Fixes #18793

### CODE REVIEW

**Comment by Azquelt** [comment]
#build

**Review by andymc12 — APPROVED** [review]
These changes look great!  Thanks @Azquelt!

**Comment by Azquelt** [comment]
#build

**Comment by Azquelt** [comment]
#run-libby-bot

**Comment by Azquelt** [comment]
Missed a necessary change to the opentracing-1.3 feature file.

**Comment by Azquelt** [comment]
Failures in the build do not appear to be related to this change.

**Pull request merged**
