### PR TITLE
Port Servlet 3.1 fat bucket from Commercial Liberty to Open Liberty

### PR DESCRIPTION
**Pull request by isaacrivriv**
fixes https://github.com/OpenLiberty/open-liberty/issues/8127

### CODE REVIEW

**Comment by isaacrivriv** [comment]
#build

**Comment by isaacrivriv** [comment]
#build

**Comment by isaacrivriv** [comment]
#build

**Comment by isaacrivriv** [comment]
#build

**Comment by pnicolucci** [comment]
#run-libby-bot

**Pull request merged**
