### PR TITLE
Temporary deprecated this API

### PR DESCRIPTION
**Pull request by utle**
Add @Deprecated for now.

### CODE REVIEW

**Comment by utle** [comment]
#build

**Comment by utle** [comment]
#build

**Comment by utle** [comment]
#build

**Comment by tevans78** [comment]
#runlibbybot

**Comment by tevans78** [comment]
#run-libby-bot

**Comment by utle** [comment]
#build 
#spawn.fullfat.buckets=com.ibm.ws.security.token.ltpa_fat

**Comment by tevans78** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.security.token.ltpa_fat

**Comment by tevans78** [comment]
@utle BVT failed again and I don't know why.

**Comment by jhanders34** [comment]
Looks like the BVT is failing because the request is coming in before the ssl channel is fully created . With the change to move opening the port until after the applications are started, I am guessing that we need to update the test case to wait longer or look for a different message in the logs before sending a request.

**Comment by tevans78** [comment]
Combined PB with the BVT fix: https://wasrtc.hursley.ibm.com:9443/jazz/resource/itemOid/com.ibm.team.build.BuildResult/_05utIIlSEeqB0LE2SMkmyg

**Pull request merged**
