### PR TITLE
Fix for Issue #8037: Use MP CompletionStageFactory to enable JAX-RS to run on the Liberty Thread Pool

### PR DESCRIPTION
**Pull request by jkoehler22**

### CODE REVIEW

**Comment by jkoehler22** [comment]
#build

**Comment by jkoehler22** [comment]
#build

**Comment by jkoehler22** [comment]
#build

**Comment by jkoehler22** [comment]
#build

**Comment by jkoehler22** [comment]
#build

**Comment by jkoehler22** [comment]
#build

**Comment by wraschke** [comment]
#build

**Comment by jkoehler22** [comment]
#build

**Comment by jkoehler22** [comment]
The failures in my PB was not related to my change.   Merging

**Pull request merged**
