### PR TITLE
Eclipse updates from recent changes

### PR DESCRIPTION
**Pull request by jhanders34**
- Update output directory for test directory to be bin_test
- Remove nonexistent src directory
- Add missing .settings files.
- Remove leftover files from com.ibm.ws.jpa.tests.beanvalidation
- Add new FATs to their appropraite github action test categories

### CODE REVIEW

**Comment by jhanders34** [comment]
#build

**Review by pgunapal — APPROVED** [review]
MP Health changes look good!

**Review by Azquelt — APPROVED** [review]

**Review by tevans78 — APPROVED** [review]

**Review by hutchig — APPROVED** [review]
LGTM

**Review by KyleAure — APPROVED** [review]

**Review by wtlucy — APPROVED** [review]
LGTM

**Review by jgrassel — APPROVED** [review]
lgtm

**Comment by jhanders34** [comment]
#libby

**Pull request merged**
