### PR TITLE
Pages API: export 3.1.1 package versions

### LINKED ISSUE #24298: Bump pages-3.1 API export to `3.1.1` to reflect the current JAR being used
https://github.com/OpenLiberty/open-liberty/blob/integration/dev/io.openliberty.jakarta/pages.3.1.bnd#L23

Work was done here: https://github.com/OpenLiberty/open-liberty/pull/24015

However, the remaining work is to update API bundle by exporting 3.1.1.

### PR DESCRIPTION
**Pull request by volosied**
fixes #24298

### CODE REVIEW

**Comment by volosied** [comment]
#build #spawn.fullfat.buckets=io.openliberty.pages.3.1.internal_fat,com.ibm.ws.jsp.2.3_fat

**Review by isaacrivriv — APPROVED** [review]
Thanks for updating these!!

**Review by pnicolucci — APPROVED** [review]

**Comment by pnicolucci** [comment]
#libby

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
#build #spawn.fullfat.buckets=io.openliberty.pages.3.1.internal_fat,com.ibm.ws.jsp.2.3_fat

**Comment by volosied** [comment]
#build #spawn.fullfat.buckets=io.openliberty.pages.3.1.internal_fat,com.ibm.ws.jsp.2.3_fat

**Comment by volosied** [comment]
#build #spawn.fullfat.buckets=io.openliberty.pages.3.1.internal_fat,com.ibm.ws.jsp.2.3_fat

**Comment by volosied** [comment]
Build passed, but child failed ( timeout?) I restarted the child build and it was green.

Merging.

**Pull request merged**
