### PR TITLE
Add mpOpentracing-1.0 and change opentracing to support the TCK

### PR DESCRIPTION
**Pull request by kgibm**

### CODE REVIEW

**Comment by kgibm** [comment]
#build

**Comment by kgibm** [comment]
@sishida I need to re-do this PR on a new branch because a rebase isn't working. I'll be opening a new one.

**Comment by kgibm** [comment]
@sishida Opened #1408

**Comment by bcpswope** [comment]
I looked at the properties files entry: 
The MicroProfile Opentracing specification provides a mechanism to access an opentracing.io Tracer

Just looks like it is missing a period at the end of the sentence.

**Pull request closed without merging**
