### PR TITLE
Remove beta guards from BELL enhancements

### PR DESCRIPTION
**Pull request by dazavala**
Remove beta support from the [BELLs 1.0 feature enhancements](https://github.com/OpenLiberty/open-liberty/issues/19368).

- Remove beta fencing from the Bells feature runtime, the classloading service, and the classloading gateway configuration.
- Remove beta attributes from Bell metatypes.
- Remove `#beta` comments from message and metatype resource files.
- Move beta-edition test behaviors to the corresponding ga-edition tests; remove beta-edition tests and FAT utilities.

### CODE REVIEW

**Comment by dazavala** [comment]
#build

**Comment by dazavala** [comment]
@OpenLiberty/message-reviewer - The `#beta` comment was removed from message and metatype resource files.  You should see no other changes.

**Review by tjwatson — APPROVED** [review]

**Comment by dazavala** [comment]
The [Personal Build](https://wasrtc.hursley.ibm.com:9443/jazz/resource/itemOid/com.ibm.team.build.BuildResult/_7iLD4ERYEe2gRt1V5m8KOw) failed schema validation for `bell.properties`. The validator expects an element or attribute in the OCD.  This failure occurs after removing the `ibm:beta="true"` attribute from the` bell.properties` OCD.  Odd.  Found examples of OCD definitions for properties identical to the BELL design and discovered they all have attributes `ibmui:extraProperties` and `ibmui:localization`, where the BELL properties OCD does not.  Attempting another #build with updated OCD for bells propertiies.
```
junit.framework.AssertionFailedError: The type com.ibm.ws.classloading.bell.properties should have either attributes or elements.
	at com.ibm.ws.config.internal.schemaChecker.MetaTypeValidator$FailureRecord.<init>(MetaTypeValidator.java:102)
	at com.ibm.ws.config.internal.schemaChecker.MetaTypeValidator$FailureRecord.<init>(MetaTypeValidator.java:94)
	at com.ibm.ws.config.internal.schemaChecker.MetaTypeValidator.validateType(MetaTypeValidator.java:401)

```

**Comment by dazavala** [comment]
#build

**Comment by dazavala** [comment]
#build

**Comment by dazavala** [comment]
#build

**Comment by dazavala** [comment]
#build
Experiment `ibm:beta="false"`

**Comment by dazavala** [comment]
#build
Attempting bell properties metatype changes derived from example `com.ibm.ws.jndi.referenceEntry.properties`, which adds ibmui attributes and adds a localized metatype property (label). See commit [Add ibmui attrs to bell.xml and bell.properties](https://github.com/OpenLiberty/open-liberty/pull/22824/commits/203416dd07f903a58469f69b00ea9f11f687ae66)

**Comment by dazavala** [comment]
#build 
Build potential solution containing ibmui attributes and all updated metatype l10n resources.  No new translations were introduced by this [change](https://github.com/OpenLiberty/open-liberty/pull/22824/commits/d873767f263c1abb23483ec3b640a850b6714b4f).  

Looking into improving this solution by using short property names (labels) for attribute `ibmui:extraProperties`

**Comment by dazavala** [comment]
#build
Build proposed final solution containing ibmui attributes and all updated metatype l10n resources containing short property names (labels) for attribute `ibmui:extraProperties`. No new translations were introduced by [commit f638b9](https://github.com/OpenLiberty/open-liberty/pull/22824/commits/f638b9163ef502e582d3cc4651df4ca8615865b1)

**Comment by dazavala** [comment]
#build

**Review by tjwatson — APPROVED** [review]
LGTM

I would use `%extraProperties.name` and `%extraProperties.description` in the `bells.xml` file and avoid the need for duplicate messages.  That can be cleaned up in a follow on PR.

**Comment by dazavala** [comment]
Builds dazavala-22824-20221007-0825 and dazavala-22824-20221007-0736 shows the solution passes schema validation and the impacted FATs: bells, classloading, session cache w/ infinispan, and jcache w/ infinispan.  The builds respectively verify short- and long-format l10n property labels for the `ibmui:extraProperties` attribute in the approved solution. This PR is ready to merge pending copyright header check.

**Comment by dazavala** [comment]
#libbybot

**Pull request merged**
