### PR TITLE
Add introspection to ApplicationPrereqMonitor

### PR DESCRIPTION
**Pull request by AndrewDJBanks**

### CODE REVIEW

**Comment by AndrewDJBanks** [comment]
fixes #18036

**Comment by AndrewDJBanks** [comment]
#build

**Review by joe-chacko — APPROVED** [review]
lgtm

**Comment by AndrewDJBanks** [comment]
#build

**Comment by AndrewDJBanks** [comment]
#build

**Comment by AndrewDJBanks** [comment]
#build

**Comment by AndrewDJBanks** [comment]
#libbybot

**Pull request merged**
