### PR TITLE
Stop building EE9 and MP5 zips

### PR DESCRIPTION
**Pull request by tevans78**
We will no longer be publishing EE9 and MP5 zips as they are being replaced by EE10 and MP6. No point building them.

#build

### CODE REVIEW

**Review by mbroz2 — APPROVED** [review]

**Comment by tevans78** [comment]
#build

**Comment by jhanders34** [comment]
#libby

**Comment by tevans78** [comment]
#build

**Comment by mbroz2** [comment]
The single failure in com.ibm.ws.ui.tool.deploy.fat.gui.nd.tests.RuleSelectionTest is unrelated to this change.

**Pull request merged**
