### PR TITLE
Issue #17609: Remove SharedServer

### LINKED ISSUE #17609: Remove SharedServer from WCSendRedirectRelativeURLTrue servlet 4.0 tests

### PR DESCRIPTION
**Pull request by pnicolucci**
fixes #17609

### CODE REVIEW

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Review by isaacrivriv — APPROVED** [review]
Looks good to me, thanks!

**Comment by pnicolucci** [comment]
#run-libby-bot

**Pull request merged**
