### PR TITLE
Use constructor injection for mandatory references

### PR DESCRIPTION
**Pull request by tjwatson**
This allows a large portion of fields to become final to avoid possible NPE when fields are used by other inject methods.

- [x] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [x] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [x] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

### CODE REVIEW

**Comment by tjwatson** [comment]
#build

**Review by dazavala — APPROVED** [review]
Looks good.  This user doc informed my review.

- @Reference.name - Annotated constructor parameter - **The name of the reference is the parameter name.**
- @Reference.service - Annotated constructor parameter - The type of the service is based upon the type of the parameter being annotated and the cardinality of the reference. If the cardinality is either 0..n or 1..n, the type of the parameter must be one of java.util.Collection, java.util.List, or a subtype of java.util.Collection so the type of the service is the generic type of the collection. **Otherwise, the type of the service is the type of the parameter.**
- @Reference.cardinality - Annotated constructor parameter - The cardinality is based on the type of the parameter. If the type is either java.util.Collection, java.util.List, or a subtype of java.util.Collection, the cardinality is 0..n. **Otherwise, the cardinality is 1..1**.
- @Reference.policy - Annotated constructor parameter - **The policy is STATIC**. STATIC policy must be used for constructor parameters.

**Comment by tjwatson** [comment]
This is to address NPEs like this:

```
[9/30/24, 7:45:49:505 PDT] 00000021 LogService-94-com.ibm.ws.app.manager                         E CWWKE0701E: bundle com.ibm.ws.app.manager:1.1.95.202409292134 (94)[com.ibm.ws.app.manager.internal.ApplicationConfigurator(208)] : The unsetAppRecycleComponent method has thrown an exception java.lang.NullPointerException: Cannot invoke "com.ibm.ws.runtime.update.RuntimeUpdateManager.createNotification(String)" because the return value of "com.ibm.ws.app.manager.internal.ApplicationConfigurator.access$400(com.ibm.ws.app.manager.internal.ApplicationConfigurator)" is null
        at com.ibm.ws.app.manager.internal.ApplicationConfigurator$UpdateEpisodeState.<init>(ApplicationConfigurator.java:1461)
        at com.ibm.ws.app.manager.internal.ApplicationConfigurator.joinEpisode(ApplicationConfigurator.java:1425)
        at com.ibm.ws.app.manager.internal.ApplicationConfigurator.unsetAppRecycleComponent(ApplicationConfigurator.java:785)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at org.apache.felix.scr.impl.inject.methods.BaseMethod.invokeMethod(BaseMethod.java:257)
        at org.apache.felix.scr.impl.inject.methods.BaseMethod.access$500(BaseMethod.java:41)
        at org.apache.felix.scr.impl.inject.methods.BaseMethod$Resolved.invoke(BaseMethod.java:701)
        at org.apache.felix.scr.impl.inject.methods.BaseMethod$NotResolved.invoke(BaseMethod.java:655)
        at org.apache.felix.scr.impl.inject.methods.BaseMethod.invoke(BaseMethod.java:544)
        at org.apache.felix.scr.impl.inject.methods.BindMethod.invoke(BindMethod.java:42)
        at org.apache.felix.scr.impl.manager.DependencyManager.invokeUnbindMethod(DependencyManager.java:2225)
        at org.apache.felix.scr.impl.manager.SingleComponentManager.invokeUnbindMethod(SingleComponentManager.java:466)
        at org.apache.felix.scr.impl.manager.DependencyManager$MultipleDynamicCustomizer.removedService(DependencyManager.java:400)
        at org.apache.felix.scr.impl.manager.DependencyManager$MultipleDynamicCustomizer.removedService(DependencyManager.java:304)
        at org.apache.felix.scr.impl.manager.ServiceTracker$Tracked.customizerRemoved(ServiceTracker.java:1258)
        at org.apache.felix.scr.impl.manager.ServiceTracker$Tracked.customizerRemoved(ServiceTracker.java:1152)
        at org.apache.felix.scr.impl.manager.ServiceTracker$AbstractTracked.untrack(ServiceTracker.java:1012)
        at org.apache.felix.scr.impl.manager.ServiceTracker$Tracked.serviceChanged(ServiceTracker.java:1192)
        at org.apache.felix.scr.impl.BundleComponentActivator$ListenerInfo.serviceChanged(BundleComponentActivator.java:116)
        at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:123)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:961)
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
        at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151)
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:945)
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:882)
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.unregister(ServiceRegistrationImpl.java:244)
        at org.apache.felix.scr.impl.manager.AbstractComponentManager$3.unregister(AbstractComponentManager.java:952)
        at org.apache.felix.scr.impl.manager.AbstractComponentManager$3.unregister(AbstractComponentManager.java:915)
        at org.apache.felix.scr.impl.manager.RegistrationManager.changeRegistration(RegistrationManager.java:140)
        at org.apache.felix.scr.impl.manager.AbstractComponentManager.unregisterService(AbstractComponentManager.java:994)
        at org.apache.felix.scr.impl.manager.AbstractComponentManager.doDeactivate(AbstractComponentManager.java:844)
        at org.apache.felix.scr.impl.manager.AbstractComponentManager.deactivateInternal(AbstractComponentManager.java:825)
        at org.apache.felix.scr.impl.manager.DependencyManager.deactivateComponentManager(DependencyManager.java:2649)
        at org.apache.felix.scr.impl.manager.DependencyManager.access$400(DependencyManager.java:59)
        at org.apache.felix.scr.impl.manager.DependencyManager$SingleStaticCustomizer.addedService(DependencyManager.java:1272)
        at org.apache.felix.scr.impl.manager.DependencyManager$SingleStaticCustomizer.addedService(DependencyManager.java:1238)
        at org.apache.felix.scr.impl.manager.ServiceTracker$Tracked.customizerAdded(ServiceTracker.java:1232)
        at org.apache.felix.scr.impl.manager.ServiceTracker$Tracked.customizerAdded(ServiceTracker.java:1152)
        at org.apache.felix.scr.impl.manager.ServiceTracker$AbstractTracked.trackAdding(ServiceTracker.java:959)
        at org.apache.felix.scr.impl.manager.ServiceTracker$AbstractTracked.track(ServiceTracker.java:895)
        at org.apache.felix.scr.impl.manager.ServiceTracker$Tracked.serviceChanged(ServiceTracker.java:1184)
        at org.apache.felix.scr.impl.BundleComponentActivator$ListenerInfo.serviceChanged(BundleComponentActivator.java:116)
        at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:123)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:961)

```

**Comment by tjwatson** [comment]
This is possible if the dynamic greedy reference is set/unset while trying to construct the component because some other threads are changing service registrations on parallel bundle startup.  Here the NPE was caused by `_runtimeUpdateManager` being null.  The strange `access$400` reference there is because an inner class needs a synthetic method to access the private field `_runtimeUpdateManager` in the top-level class.  When NPEs like this happen for fields holding mandatory references, it is best to convert them to final fields and use constructor injection instead to avoid any possibility of the component instance being used before the field is set.

**Pull request merged**
