### PR TITLE
WSOC FVT: change timing for the connectToClass test

### PR DESCRIPTION
**Pull request by billw1024**

### CODE REVIEW

**Comment by billw1024** [comment]
#build #spawn.fullfat.buckets=io.openliberty.wsoc.internal_fat

**Comment by billw1024** [comment]
#build #spawn.fullfat.buckets=io.openliberty.wsoc.internal_fat

**Review by isaacrivriv — APPROVED** [review]
LGTM Thanks!

**Comment by billw1024** [comment]
fixes #15064

**Pull request merged**
