### PR TITLE
Environment variable LOG_DIR not respected in server.xml

### LINKED ISSUE #7461: Environment variable LOG_DIR not respected in server.xml
@msmigiel commented on [Wed May 08 2019](https://github.com/OpenLiberty/openliberty.io/issues/1184)

I'm running Open Liberty 19.0.0.4 on Windows 10 and am seeing an odd issue. 

In my server.xml, I have a section for logging as follows:

`<logging hideMessage="SRVE9967W, CWWKO0221E" maxFileSize="64" consoleLogLevel="INFO" logDirectory="${env.LOG_DIR}" messageFileName="${env.MESSAGE_FILE}" traceFileName="${env.TRACE_FILE}" traceSpecification="" />`

In my batch script to start Liberty, I define the variables as:
`set LOG_DIR=%USER_HOME%\logs`
`set LOG_FILE=%JVM%_%COMPUTERNAME%_%CURRENT_DATE%.log`
`set MESSAGE_FILE=%JVM%_%COMPUTERNAME%_%CURRENT_DATE%.log`
`set TRACE_FILE=%JVM%_trace_%COMPUTERNAME%_%CURRENT_DATE%.log`

I am not using a bootstrap.properties. When I start Liberty with the above, I see that a folder called "${env.LOG_DIR}" is created in my Liberty server's folder (usr\servers\defaultServer) and has the properly named message and trace files. The problem is that logDirectory is not using the variable I pass to it as a variable but rather a file name. As a workaround, if I add the following to my script:

`set LOG_PATH=%LOG_DIR%`

and change to the following in server.xml:

`logDirectory="${env.LOG_PATH}" `

it works. I can't figure out why LOG_DIR doesn't work but LOG_PATH does. According to what I've read, this is the proper way to use environment variables and LOG_DIR is one used by the Liberty script itself.

### PR DESCRIPTION
**Pull request by jimblye**
Fixes #7461

### CODE REVIEW

**Comment by jimblye** [comment]
#build

**Review by cbridgha — APPROVED** [review]
Looks good

**Comment by jimblye** [comment]
#build

**Comment by jimblye** [comment]
There is one test failure in the build:

```
v2.io.swagger.models.SwaggerException: CWWKO1254E: Unable to load the file https://petstore.swagger.io/v2/swagger.json with the reference format: URL. 
	at v2.io.swagger.parser.util.RefUtils.readExternalRef(RefUtils.java:163)
	at v2.io.swagger.parser.ResolverCache.loadRef(ResolverCache.java:171)
	at v2.io.swagger.parser.ResolverCache.loadRef(ResolverCache.java:128)
	at v2.io.swagger.parser.processors.ExternalRefProcessor.processRefToExternalDefinition(ExternalRefProcessor.java:46)
	at v2.io.swagger.parser.processors.ModelProcessor.processRefModel(ModelProcessor.java:136)
	at v2.io.swagger.parser.processors.ModelProcessor.processModel(ModelProcessor.java:52)
	at v2.io.swagger.parser.processors.ParameterProcessor.processParameters(ParameterProcessor.java:95)
	at v2.io.swagger.parser.processors.OperationProcessor.processOperation(OperationProcessor.java:31)
	at v2.io.swagger.parser.processors.PathsProcessor.processPaths(PathsProcessor.java:190)
	at v2.io.swagger.parser.processors.PathsProcessor.processPaths(PathsProcessor.java:55)
	at v2.io.swagger.parser.SwaggerResolver.resolve(SwaggerResolver.java:77)
	at v2.io.swagger.parser.SwaggerResolver.resolve(SwaggerResolver.java:43)
	at v2.io.swagger.parser.SwaggerResolver.resolve(SwaggerResolver.java:39)
	at v2.io.swagger.parser.SwaggerResolverTest.testOperationBodyparamRemoteRefs(SwaggerResolverTest.java:156)
	at v2.io.swagger.parser.SwaggerResolverTest.testJsonOperationBodyparamRemoteRefs(SwaggerResolverTest.java:165)
Caused by: java.io.IOException: Server returned HTTP response code: 502 for URL: https://petstore.swagger.io/v2/swagger.json
	at v2.io.swagger.parser.util.RemoteUrl.urlToString(RemoteUrl.java:147)
	at v2.io.swagger.parser.util.RefUtils.readExternalRef(RefUtils.java:150)
```

This does not seem to be related to the LOG_DIR environment variable.   Merging.

**Review by amyreit — COMMENTED** [review]
LGTM

**Pull request merged**
