### PR TITLE
Issue 8590: Add cert for new AD server

### LINKED ISSUE #8590: Update truststore for new AD server for AD SSL WIM fat tests
Update the truststore for our new backup AD server.

### PR DESCRIPTION
**Pull request by kristip17**
Fixes #8590

### CODE REVIEW

**Comment by kristip17** [comment]
#build

**Comment by kristip17** [comment]
Spawned an additional build with local ldap set to false -- https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewDefinition&id=_JWdEUD7dEemKFI0xRbWJ_w  . The build kicked off by `#build` may have SSL errors trying to talk to the local LDAP.

**Comment by jvanhill** [comment]
#build

**Comment by jvanhill** [comment]
The failing tests were all SSL timeouts and were unrelated to this certificate update.

**Pull request merged**
