### PR TITLE
Fix test failure in RTC 291613.

### PR DESCRIPTION
**Pull request by jvanhill**

### CODE REVIEW

**Comment by jvanhill** [comment]
#build

**Review by ryanesch — APPROVED** [review]

**Comment by jvanhill** [comment]
Build was still pending during the latest push.

**Comment by jvanhill** [comment]
The test failures in the build were completely unrelated to this change.

**Comment by jvanhill** [comment]
#libby

**Comment by posmith** [comment]
L2 message review completed

**Pull request merged**
