### PR TITLE
Added server alternate

### PR DESCRIPTION
**Pull request by BerksanAtes**
Fixes #24039
Alternating server to prevent deregistration of incomingObserver from next EE repetition

### CODE REVIEW

**Review by neuwerk — APPROVED** [review]
Change looks good to me, I don't see a PB in the PR, I'll kick one off. Just make sure it's green before you merge.

**Comment by neuwerk** [comment]
#build

**Comment by BerksanAtes** [comment]
#run-libby-bot

**Comment by BerksanAtes** [comment]
Build has failures, however, the test that I ran without a problem.

**Pull request merged**
