### PR TITLE
jwk updates

### PR DESCRIPTION
**Pull request by arunavemulapalli**
Update jwk to include kid even if it is created using the keys from the configuration.

### CODE REVIEW

**Comment by arunavemulapalli** [comment]
#build

**Comment by ayoho** [comment]
@arunavemulapalli Is this something that will need to be included in 18.0.0.4?

**Comment by ayoho** [comment]
Aruna says this is not required for 18.0.0.4.

**Comment by arunavemulapalli** [comment]
merged already using another pr. Closing this one.

**Pull request closed without merging**
