### PR TITLE
Issue #12178: Remove Thread.sleep that is not necssary

### LINKED ISSUE #12178: Remove Thread.sleep(1000) from test_HttpServletRequestGetMapping_ContextRootMapping_Forward
```
    @Test
    @Mode(TestMode.FULL)
    public void test_HttpServletRequestGetMapping_ContextRootMapping_Forward() throws Exception {
        Thread.sleep(1000);
        SHARED_SERVER.verifyResponse(createWebBrowserForTestCase(), "/TestGetMapping/pathFwdMatch?dispatchPath=/",
                                     "Mapping values: mappingMatch: CONTEXT_ROOT matchValue:  pattern:  servletName: GetMappingTestServlet");
    }
```
The thread.sleep(1000); has no documentation as to why it might be necessary, I don't see any of the other tests in this suite with a sleep.

I've removed it and it runs fine without this locally.

### PR DESCRIPTION
**Pull request by pnicolucci**
fixes #12178

### CODE REVIEW

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Comment by isaacrivriv** [comment]
#run-libby-bot

**Pull request merged**
