### PR TITLE
set headers on REST response

### PR DESCRIPTION
**Pull request by aknguyen7**
fixed [294757](https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.workitem.viewWorkItem&id=294757)

### CODE REVIEW

**Comment by aknguyen7** [comment]
#link 294757

**Comment by aknguyen7** [comment]
#build

**Review by k8vance88 — APPROVED** [review]

**Comment by aknguyen7** [comment]
#build

**Comment by aknguyen7** [comment]
#build

**Comment by aknguyen7** [comment]
UI passed with 1 failures for a known defect 288136 org.openqa.selenium.WebDriverException: Expected to read a START_MAP but instead have: END. Last 0 characters read:

**Pull request merged**
