### PR TITLE
Updates for WebContainer monitor logic and updates to Request timing fat

### PR DESCRIPTION
**Pull request by jhanders34**
- Update transformation rules to correctly transform arguments for WebContainer monitor code
- Update request timing to do repeat for Jakarta EE 9
- Remove --add-exports jvm options file for the test since it is now in java9.options for the server.

### CODE REVIEW

**Comment by jhanders34** [comment]
#build

**Review by gjwatts — APPROVED** [review]

**Review by pgunapal — APPROVED** [review]
LGTM

**Review by isaacrivriv — APPROVED** [review]
Changes look good to me. Thanks for the work!

**Review by Channyboy — APPROVED** [review]
lgtm

**Comment by jhanders34** [comment]
#libby

**Pull request merged**
