### PR TITLE
Enable JSF22ViewPoolingTests for EE10

### PR DESCRIPTION
**Pull request by pnicolucci**
for #22369

### CODE REVIEW

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
Java 17 build: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_UgbAoESaEe2gRt1V5m8KOw

**Comment by pnicolucci** [comment]
Java 17 build: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_BvJUgET-Ee2gRt1V5m8KOw

**Comment by pnicolucci** [comment]
Java 17 build: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_X9Ev0EVtEe2gRt1V5m8KOw&tab=com.ibm.team.build.web.ui.internal.editors.result.overview.OverviewPage

**Comment by pnicolucci** [comment]
Java 17 build was successful

**Review by volosied — APPROVED** [review]
Builds were deleted  before I could view them, but Libby said they were successful :)  Approved

**Pull request merged**
