### PR TITLE
Consolidate CDI auto features

### LINKED ISSUE #1515: CDI: Consolidate auto features
We currently have a bunch of cdi auto-features which are badly named and potentially duplicates. Extra auto-features slow down server startup time.
```
com.ibm.websphere.appserver.cdi1.2-appSecurity1.0
com.ibm.websphere.appserver.cdi1.2-appSecurityClient1.0
com.ibm.websphere.appserver.cdi1.2-ejb3.2
com.ibm.websphere.appserver.cdi1.2-jms-2.0
com.ibm.websphere.appserver.cdi1.2-jndi1.0
com.ibm.websphere.appserver.cdi1.2-jsf2.2
com.ibm.websphere.appserver.cdi1.2-servlet3.1
com.ibm.websphere.appserver.cdi1.2-transaction1.2
com.ibm.websphere.appserver.cdi2.0-appSecurity1.0
com.ibm.websphere.appserver.cdi2.0-appSecurityClient1.0
com.ibm.websphere.appserver.cdi2.0-ejb3.2
com.ibm.websphere.appserver.cdi2.0-jms2.0
com.ibm.websphere.appserver.cdi2.0-jndi1.0
com.ibm.websphere.appserver.cdi2.0-jsf2.3
com.ibm.websphere.appserver.cdi2.0-servlet4.0
com.ibm.websphere.appserver.cdi2.0-transaction1.2
```

For example, `cdi1.2-appSecurity1.0` and `cdi2.0-appSecurity1.0` have nothing to do with appSecurity1.0 (only 2.0 and 3.0) and both add in the same bundle. We could probably get away with just one auto-feature called `com.ibm.websphere.appserver.cdi-appSecurity`.

Each once needs to be checked to see if it is really needed. If (as in the cdi-1.2 cases) the feature is GA then changing the name will required an exemption in the WS-CD feature checker code. The exemption will need to be added to WS-CD before any changes can be made in OL.

### PR DESCRIPTION
**Pull request by tevans78**
#build 
fixes #1515

### CODE REVIEW

**Comment by tevans78** [comment]
build above is still pending so will pick up the second commit

**Comment by Azquelt** [comment]
Summary of changes:
* consolidate cdi-appSecurity autofeatures (only one needed for CDI 1.2/2.0 + appSec 2.0/3.0)
* consolidate cdi-appSecurityClient autofeatures (only one needed for CDI 1.2/2.0 + appSecClient 1.0)
* consolidate cdi-jndi autofeatures (only one needed for CDI 1.2/2.0 + jndi 1.0)
* consolidate cdi-jaxrs autofeatures (only one needed for CDI 1.2/2.0 + jaxrs 2.0/2.1)
  * this would be a slight change as previously we would only activate an autofeature for (CDI 1.2 + jaxrs 2.0) or (CDI 2.0 + jaxrs 2.1) whereas now we would also activate an autofeature for e.g. (CDI 1.2 + jaxrs 2.1). However, this shouldn't result in any actual change since (CDI 1.2 + jaxrs 2.1) and (CDI 2.0 + jaxrs 2.0) are not compatible combinations so these new scenarios cannot occur.
* consolidate jms2-cdi autofeatures (only one needed for CDI 1.2/2.0 + jms 2.0)
* rename the CDI autofeatures for batch-1.0, beanValidation-1.1/2.0 and jcacheContainer for consistency with other features
* remove the cdi-transactions autofeatures since CDI depends directly on transactions so we can include the transactions integration bundle in the CDI feature itself
* reformat a few other CDI autofeature feature files

**Comment by Azquelt** [comment]
#run-libby-bot

**Comment by tevans78** [comment]
#build

**Comment by tevans78** [comment]
#build

**Comment by tevans78** [comment]
I was way too slow, build is gone!
#build

**Pull request closed without merging**
