### PR TITLE
Update Faces 4.0 to 4.0.0-RC5

### LINKED ISSUE #24369: Update Faces 4.0 to RC5
Release Notes - MyFaces Core - Version 4.0.0-RC5 can be found in the following link:
https://issues.apache.org/jira/secure/ReleaseNote.jspa?projectId=10600&version=12352858

### PR DESCRIPTION
**Pull request by volosied**
fixes #24369

### CODE REVIEW

**Comment by volosied** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jsf.2.3_fat,com.ibm.ws.jsf.2.2_fat,io.openliberty.org.apache.myfaces.4.0_fat,com.ibm.ws.jsf_fat_lWAS_faces4.0

**Comment by volosied** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jsf.2.3_fat,com.ibm.ws.jsf.2.2_fat,io.openliberty.org.apache.myfaces.4.0_fat,com.ibm.ws.jsf_fat_lWAS_faces4.0

**Comment by volosied** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jsf.2.3_fat,com.ibm.ws.jsf.2.2_fat,io.openliberty.org.apache.myfaces.4.0_fat

**Comment by volosied** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jsf.2.3_fat,com.ibm.ws.jsf.2.2_fat,io.openliberty.org.apache.myfaces.4.0_fat

**Comment by pnicolucci** [comment]
latest build against ws-cd-open integration: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_znavILhcEe2r6re_Zvbagg

**Review by pnicolucci — APPROVED** [review]

**Comment by pnicolucci** [comment]
#libby

**Review by isaacrivriv — APPROVED** [review]
Thanks for getting RC5 in!

**Pull request merged**
