### PR TITLE
Static Trace Injection Performance improvements

### PR DESCRIPTION
**Pull request by cbridgha**
During buildtime - we activate ASM instrumentation to inject bytecode level Trace calls.

We are changing the default static initializer for the Trace Object to pass in the Class, message bundle, and trace group - because we used to calculate these values at startup time.

In addition to changing our default injected code, we are also detecting "existing" calls in source to the "Tr.register(Class)" if the classes are instrumented at build time, and replace these calls in favor of the qualified initializer passing the bundle name and trace group strings.

### CODE REVIEW

**Comment by cbridgha** [comment]
#build

**Comment by cbridgha** [comment]
#build

**Comment by cbridgha** [comment]
#build

**Comment by cbridgha** [comment]
#build

**Comment by cbridgha** [comment]
#build

**Comment by cbridgha** [comment]
#build

**Comment by cbridgha** [comment]
#build

**Comment by cbridgha** [comment]
#build

**Comment by jhanders34** [comment]
I notice you updated some non instrumented classes manually with your changes.  Could we update the instrumentation code to honor disable instrumentation, but still do the conversion of Tr.register to the other form?  Otherwise it will be an endless effort to update them manually, or we just update them manually now but that also leaves maintaining it more difficult which is why we want to do it with the transformer logic.

**Comment by cbridgha** [comment]
#build

**Comment by dettmoney** [comment]
There are several instances of:
new String[] { "applications", com.ibm.ws.app.manager.internal.AppManagerConstants.TRACE_GROUP },
                                                          com.ibm.ws.app.manager.internal.AppManagerConstants.TRACE_MESSAGES);

Should this be a public static in a utility class, and have each register use the same String array?

**Comment by cbridgha** [comment]
#build

**Comment by cbridgha** [comment]
#build

**Comment by cbridgha** [comment]
#build

**Comment by cbridgha** [comment]
please #build AGAIN

**Comment by cbridgha** [comment]
#build

**Pull request merged**
