### PR TITLE
13301: Make JsonBuilderFactory static

### LINKED ISSUE #13301: Microprofile GraphQL Performance Regression
We have a MPGraphQL regression in 20.0.0.9. I see a new builder factory being created.
```
  Parent      0   0.00  17.10           0         430    J:io/smallrye/graphql/execution/context/SmallRyeContext.<init>(Ljavax/json/JsonObject;)V
    Self      0   0.00  17.10           0         430    J:javax/json/Json.createBuilderFactory(Ljava/util/Map;)Ljavax/json/JsonBuilderFactory;
   Child      0   0.00  17.10           0         430    J:javax/json/spi/JsonProvider.provider()Ljavax/json/spi/JsonProvider;
 ```

This looks to be a new class: https://github.com/smallrye/smallrye-graphql/blob/master/server/implementation/src/main/java/io/smallrye/graphql/execution/context/SmallRyeContext.java 

Need a cache fix like:  https://github.com/smallrye/smallrye-graphql/pull/186

### PR DESCRIPTION
**Pull request by andymc12**
This fixes an unreleased performance regression (fixes #13301 ). I would prefer to pull in a SmallRye GraphQL release with this fix, but it looks like a GraphQL release might not occur before we need to build our next release, so this fix overlays the source code.  It can be removed in a future iteration when we pull in 1.0.7.

### CODE REVIEW

**Comment by andymc12** [comment]
#build

**Comment by andymc12** [comment]
#build after code review comment change to remove redundant graphql-java dependency from bnd file.

**Comment by jhanders34** [comment]
#libby

**Comment by andymc12** [comment]
This change is overridden by #13321 which includes the same changes but in the SmallRye GraphQL source tree directly.

**Pull request closed without merging**
