### PR TITLE
Issue #12305: Update jsp-3.0 description and subsystem name

### LINKED ISSUE #12305: Update the jsp-3.0 feature description and Subsystem-Name
1) `Subsystem-Name: JavaServer Pages 3.0` -> `Subsystem-Name: Jakarta Server Pages 3.0`

2) 
**Starting with:**

> description=This feature enables support for Java Server Pages (JSPs) that are written to the JSP \
>  3.0 specification. This framework simplifies the construction of user interfaces. \
>  Enabling this feature also enables the Expression Language (EL) version 3.0 feature.  

**Changed to:**
> description=This feature enables support for Jakarta Server Pages (JSPs) that are written to the JSP \
>  3.0 specification. This framework simplifies the construction of user interfaces. \
>  Enabling this feature also enables the Jakarta Expression Language (EL) version 4.0 feature.  

3) Delete the translations that were copied over incorrectly.

### PR DESCRIPTION
**Pull request by pnicolucci**
fixes #12305

### CODE REVIEW

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Comment by andrea-pichler** [comment]
No message review requested from L2

**Comment by pnicolucci** [comment]
#run-libby-bot

**Pull request merged**
