### PR TITLE
A few JavaMail-1.5 and JAX-WS FAT fixes. 

### PR DESCRIPTION
**Pull request by neuwerk**
This PR addresses three issues: 

One - Moves a JavaMail-1.5 test into the shared JavaMail FAT bucket. 
Two - Fixes a timing issue in the WSAT fat buckets
Three - Cleans up a potential classpath conflict in the PureCXF tests.

### CODE REVIEW

**Comment by neuwerk** [comment]
#build

**Comment by neuwerk** [comment]
#build

**Comment by neuwerk** [comment]
#build

**Review by WhiteCat22 — APPROVED** [review]

**Comment by neuwerk** [comment]
#run-libby-bot

**Pull request merged**
