### PR TITLE
Increate supported version from 6 to 9.

### PR DESCRIPTION
**Pull request by tbitonti**
For issue #11653

### CODE REVIEW

**Comment by tbitonti** [comment]
#build

**Comment by tbitonti** [comment]
#build

**Comment by tbitonti** [comment]
#build

**Comment by tbitonti** [comment]
#build

**Comment by tbitonti** [comment]
#build

**Comment by andymc12** [comment]
The last build failed due to an intermittent infrastructure issue.  New #build

**Comment by andymc12** [comment]
All failures occur in other unrelated builds, and appear to be unrelated to these changes.

**Comment by andymc12** [comment]
#run-libby-bot

**Comment by tbitonti** [comment]
Changes were tested by the addition of new unit test cases which verify reads of indexes at the new index format versions (7, 8, and 9).  See:
dev/com.ibm.ws.anno/test/com/ibm/ws/annocache/test/jandex/JandexSparseReadTest.java

**Pull request merged**
