### PR TITLE
Telemetry fat repeats

### PR DESCRIPTION
**Pull request by tonyreigns**
- [x] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [x] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [x] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

- Supporting Java 8 for the telemetry logging FAT buckets. 
- Adding TelemetryRepeats for both buckets
- Minor cleanup
Related to #27711

### CODE REVIEW

**Comment by tonyreigns** [comment]
#build

**Review by pgunapal — DISMISSED** [review]
Looks good!

**Comment by tonyreigns** [comment]
I've already ran builds for these changes in a different PR but a new PR was required unfortunately.

Previous passing build: https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=df95bfa5-5404-478f-9324-34ed57b75bce

**Review by pgunapal — APPROVED** [review]
Looks good

**Pull request merged**
