### PR TITLE
Update to not include fattest.simplicity.jar in autoFVT.zip files

### PR DESCRIPTION
**Pull request by jhanders34**
- Update to have fattest.simplicity.jar and com.ibm.ws.componenttest.jar in fattest.simplicity/build/libs/lib and not in the autoFVT.zip files.

### CODE REVIEW

**Comment by jhanders34** [comment]
!pbbeta
git.clone.checkout.branch=branch3
git.clone.repository.sshUrl=git@github.ibm.com:jhanders/WS-CD-Open.git
git.clone.repository.username=jhanders

**Comment by jhanders34** [comment]
#build

**Comment by jhanders34** [comment]
!pbbeta
git.clone.checkout.branch=branch3
git.clone.repository.sshUrl=git@github.ibm.com:jhanders/WS-CD-Open.git
git.clone.repository.username=jhanders

**Comment by jhanders34** [comment]
!pbbeta
git.clone.checkout.branch=branch3
git.clone.repository.sshUrl=git@github.ibm.com:jhanders/WS-CD-Open.git
git.clone.repository.username=jhanders

**Comment by jhanders34** [comment]
!pbbeta
git.clone.checkout.branch=branch3
git.clone.repository.sshUrl=git@github.ibm.com:jhanders/WS-CD-Open.git
git.clone.repository.username=jhanders

**Review by gjwatts — APPROVED** [review]

**Comment by gjwatts** [comment]
#libby

**Pull request merged**
