### PR TITLE
2234 update mp config version

### LINKED ISSUE #2234: MP Config 1.2: The API jar says version 1.2 but it is actually 1.2.1
The api bundle we produce looks like this...
`/build.image/wlp/dev/api/stable/com.ibm.websphere.org.eclipse.microprofile.config.1.2_1.0.20.jar`
The numbers at the end are
api version = 1.2
bundle version = 1.0
liberty version = 20

The api version should be 1.2.1 so the file name should end up as
`/build.image/wlp/dev/api/stable/com.ibm.websphere.org.eclipse.microprofile.config.1.2.1_1.0.20.jar`

So the way to fix that is to change the name of the api bundle from
`com.ibm.websphere.org.eclipse.microprofile.config.1.2`
to
`com.ibm.websphere.org.eclipse.microprofile.config.1.2.1`

### PR DESCRIPTION
**Pull request by jonhawkes**
fixes #2234

#build

### CODE REVIEW

**Comment by jonhawkes** [comment]
#build

**Comment by jonhawkes** [comment]
#build

**Comment by jonhawkes** [comment]
#build

**Comment by Azquelt** [comment]
Rebased to remove a rogue commit which shouldn't have been included and a merge. Code is identical, no additional personal build needed.

**Pull request merged**
