### PR TITLE
Add pluginGeneratorLock to GeneratePluginConfigMBean

### LINKED ISSUE #18404: Create PluginGenerator Lock to to Address FileNotFoundExceptions
**Describe the bug**  

During the generation of the `plugin-cfg.xml` file the following exception may occur:

>Stack Dump = java.io.FileNotFoundException: C:\Users\jazz_build\Build\jazz-build-engines\wasrtc\EBCPROD\build\dev\image\output\wlp\usr\servers\com.ibm.ws.security.openidconnect.server-1.0_fat.feature\logs\state\\.plugin-cfg.xml (The process cannot access the file because it is being used by another process)

**Steps to Reproduce**  
The `plugin-cfg-.xml` is generated automatically upon server start in addition to the following actions:

1. When an application is deployed to the server
2. When an application is undeployed from the server
3. When an application programmatically modifies the session cookie configuration name during application initialization
4. When server configuration is updated

When multiple threads attempt to work on the plugin-cfg.xml, it can lead to the FileNotFoundException exception above. 

**Expected behavior**  
The `plugin-cfg.xml` file is generated without error.

**Additional context**  
N/A

### PR DESCRIPTION
**Pull request by volosied**
fixes #18404

### CODE REVIEW

**Comment by volosied** [comment]
#build

**Review by wtlucy — APPROVED** [review]
LGTM. This should better enforce the intention of the existing method synchronization.

**Comment by volosied** [comment]
#build

**Comment by volosied** [comment]
#run-libby-bot

**Comment by volosied** [comment]
Relevant tests for this change passed, but build had trouble related to "Downloading IM from LibertyFS". 

Merging

**Pull request merged**
