### PR TITLE
Issue #1249 Update JSF 2.3 to latest snapshot

### PR DESCRIPTION
**Pull request by jsartoris**
pull request for Issue #1249

### CODE REVIEW

**Comment by jsartoris** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jsf.2.3_fat,com.ibm.ws.jsf.2.2_fat_jsf2.3,com.ibm.ws.jsf_fat_jsf2.3,com.ibm.ws.jsf_fat_lWAS_jsf2.3

**Comment by jsartoris** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jsf.2.3_fat,com.ibm.ws.jsf.2.2_fat_jsf2.3,com.ibm.ws.jsf_fat_jsf2.3,com.ibm.ws.jsf_fat_lWAS_jsf2.3

**Comment by samolisov** [comment]
Because OpenLiberty is an open project, please let me share my personal opinion, just a couple of words.  @jsartoris drops ~11 thousand lines and put 4. This is amazing!

**Comment by jsartoris** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jsf.2.3_fat,com.ibm.ws.jsf.2.2_fat_jsf2.3,com.ibm.ws.jsf_fat_jsf2.3,com.ibm.ws.jsf_fat_lWAS_jsf2.3

**Comment by jsartoris** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jsf.2.3_fat,com.ibm.ws.jsf.2.2_fat_jsf2.3,com.ibm.ws.jsf_fat_jsf2.3,com.ibm.ws.jsf_fat_lWAS_jsf2.3

**Comment by jsartoris** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jsf.2.3_fat,com.ibm.ws.jsf.2.2_fat_jsf2.3,com.ibm.ws.jsf_fat_jsf2.3,com.ibm.ws.jsf_fat_lWAS_jsf2.3

**Comment by jsartoris** [comment]
The one failure in the com.ibm.ws.jsf.2.2_fat_2.3 test bucket is an existing defect and is being worked separately.  The failure is not caused by the changes in this pull request.

**Pull request merged**
