### PR TITLE
update java2sec for wsscxf.saml.1

### PR DESCRIPTION
**Pull request by meiaus**
update com.ibm.ws.wssecurity_fat.wsscxf.saml.1 with java2sec

### CODE REVIEW

**Comment by meiaus** [comment]
#run-libby-bot

**Comment by meiaus** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.wssecurity_fat.wsscxf.saml.1

**Comment by meiaus** [comment]
The above PB https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_dx4qsPGcEeu3WKcyevrZqg&tab=com.ibm.team.build.web.ui.internal.editors.result.overview.OverviewPage is complete with errors from other FAT:

wsscxf.saml.1 fat passed:

image


and other FAT failed, which is out of concern from this PR:

image

But a new PB will be submitted to only specify the updated FAT to run.

**Comment by meiaus** [comment]
#run-libby-bot

**Comment by meiaus** [comment]
Note:
Initial PB were submitted with the properties `global.debug.java2.sec`, which didn't enable java2 sec (per server messages.log).
The latest PB with `global.java2.sec` enabled java2 security as expected.

**Review by jimmy1wu — APPROVED** [review]

**Pull request merged**
