### PR TITLE
Do request in a thread to avoid blocking forever

### PR DESCRIPTION
**Pull request by tjwatson**

### CODE REVIEW

**Comment by tjwatson** [comment]
#build

**Comment by tjwatson** [comment]
#build

**Comment by tjwatson** [comment]
#build

**Review by hlhoots — DISMISSED** [review]
Looks good to me.

**Comment by tjwatson** [comment]
#build

**Comment by tjwatson** [comment]
#build

**Comment by tjwatson** [comment]
#build

**Review by dazavala — APPROVED** [review]
Looks good.  Vestigial code is gone.  Approving now, though merge is pending build results.

**Comment by tjwatson** [comment]
#libby

**Pull request merged**
