### PR TITLE
Initial InstantOn tests for Bean Validation

### PR DESCRIPTION
**Pull request by dazavala**
For issue #21321

A retrofit of the Bean Validation managed bean test that verifies CDI support for Bean Validation API and constraints.

- Verify a restored server validates basic (built-in) Bean Validation constraints within a web application that uses a CDI managed bean.
- Temporal constraint validation uses a custom `ClockProvider` implementation. The impl class is provided by the test and configured in `validation.xml`. Otherwise, the `ValidationFactory` has the default configuration.

### CODE REVIEW

**Comment by dazavala** [comment]
#build

**Comment by dazavala** [comment]
#build
Removed `autoFVT-template/bootstrapping.properties`.  @sebratton Ready for review, please; starting an InstantOn build now.

**Comment by dazavala** [comment]
#build
Had a little trouble with tested features support causing tests to fail.  Changed the bnd.bnd file to declare every tested feature rather than the `webProfile-x.0` features.

**Review by sebratton — APPROVED** [review]
LGTM

**Comment by dazavala** [comment]
#libby

**Comment by dazavala** [comment]
The InstantOn build passed as well.  Merge pending copyright header check.

**Comment by dazavala** [comment]
#libby

**Pull request merged**
