### PR TITLE
Update MP Metrics 5.0 TCK to use final release

### PR DESCRIPTION
**Pull request by Channyboy**
#build

### CODE REVIEW

**Comment by Channyboy** [comment]
#build

**Comment by Channyboy** [comment]
#run-libby-bot

**Comment by Channyboy** [comment]
#libby

**Review by fmhwong — APPROVED** [review]
LGTM

**Comment by Channyboy** [comment]
Failure occured during one of the FAT bucket executions due to a rare issue where the OL server fails to unload an application and results in an unresponsive server for the rest of the FAT test. (Not MP Metrics related).

**Pull request merged**
