### PR TITLE
update netty to 4.1.94 and reduce duplicate bundle including of it in grpc client

### PR DESCRIPTION
**Pull request by hutchig**
Refresh netty to 4.1.94.Final
Align version to 4.1.94 name (not using the 'Final' bit to match artifactory)
Reduce repo reference and multiple repackaging rather than bundle reuse in grpc client.

### CODE REVIEW

**Comment by hutchig** [comment]
#build

**Comment by hutchig** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.grpc_fat

**Comment by hutchig** [comment]
#build

**Comment by hutchig** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.grpc_fat

**Comment by hutchig** [comment]
#build

**Comment by hutchig** [comment]
#libbybot

**Review by websterc87 — APPROVED** [review]
Changes make sense to me and testing proves this changes doesnt break our tests.

**Comment by hutchig** [comment]
fixes #19246

**Pull request merged**
