### PR TITLE
Update Nester and Base64Coder to not be in internal packages 

### PR DESCRIPTION
**Pull request by jhanders34**
- Update Nester and Base64Coder to not be in internal packages
- Export Nester's package and update everyone to import it instead of having a private package to it and including it in lots of bundles for no reason
- Still keep the internal package version that just calls the non internal one so that WebSphere Liberty code and tests can be updated.  When done will remove the internal package version.
- Keep com.ibm.ws.common.encoder around as a test project to be used for FATs until it can be reworked.

### CODE REVIEW

**Comment by dmuelle** [comment]
asa far as I can tell, no new messages that need ID review here. I'll add the` ID Review not needed` label. If that's incorrect just let me know. Thanks

**Comment by jhanders34** [comment]
#libby #build

**Comment by jhanders34** [comment]
#build

**Comment by skasund** [comment]
L2 message review completed

**Comment by jhanders34** [comment]
#build

**Comment by jhanders34** [comment]
#build

**Comment by jhanders34** [comment]
#libby

**Review by tbitonti — COMMENTED** [review]
Looks good.

This is missing a new-line at the end-of-file.  I don't know if that is a problem or not:
dev/com.ibm.ws.security.openidconnect.server/bnd.bnd

There are a lot of files which are missing copyright updates, or which do not have a copyright section.

**Review by brenthdaniel — APPROVED** [review]
Why are the internal versions maintained? I would prefer to see them removed

**Comment by jhanders34** [comment]
> Why are the internal versions maintained? I would prefer to see them removed

I will be removing the internal versions after the WebSphere Liberty PR you approved is merged in.  I did it this way to do 4 PRs across the two products to avoid requiring a combined build.

**Review by tbitonti — APPROVED** [review]

**Pull request merged**
