### PR TITLE
For RTC294574, make sure min java limits are in place for com.ibm.ws.…

### PR DESCRIPTION
**Pull request by jgrassel**
Make sure that there are min java versions set for each subbucket in com.ibm.ws.jpa.tests.javasupport_fat

### CODE REVIEW

**Comment by jgrassel** [comment]
#build

**Comment by jgrassel** [comment]
#run-libby-bot

**Review by dazey3 — APPROVED** [review]
lgtm

**Comment by jgrassel** [comment]
#build

**Comment by jgrassel** [comment]
Tests passed on rerun of failed child build (failure due to infra issues).  Waiting for the rebuild to finish.

**Comment by jgrassel** [comment]
#build

**Comment by jgrassel** [comment]
#build

**Comment by jgrassel** [comment]
Failed child build reran on pass, so considering this good.

**Pull request merged**
