### PR TITLE
Clean up some feature files

### PR DESCRIPTION
**Pull request by jhanders34**
- Remove auto features that only depend on one feature and move the contents to those features.
- Change to not have a feature depend on an auto feature
- Remove jakartaMail-1.6
- Update a few simple API features to have parallel activation enabled
- Add new test cases to find some of the issues that were resolved.

### CODE REVIEW

**Comment by jhanders34** [comment]
#build

**Review by jvanhill — APPROVED** [review]
The only real comment I have is that a bunch of copyrights probably need to be updated.

**Review by uberskigeek — APPROVED** [review]

**Review by pgunapal — APPROVED** [review]
LGTM - mpHealth-related changes

**Comment by jhanders34** [comment]
#libby

**Comment by jhanders34** [comment]
I updated the Copyright years.

**Review by cbridgha — APPROVED** [review]
LGTM

**Review by neuwerk — APPROVED** [review]
The jaxws-2.2 changes look good!

**Review by andymc12 — APPROVED** [review]

**Review by andymc12 — APPROVED** [review]
LGTM

**Pull request merged**
