### PR TITLE
Issue #21282: Execute EE9 tests for Java less than 11 for lite mode.

### LINKED ISSUE #21282: com.ibm.ws.webcontainer.servlet.4.0_fat does not run any tests when executed with Java 8
Since Jakarta EE10 requires Java 11 no tests are run on Java 8 builds since Jakarta EE10 is specified for `lite` mode.

This FAT bucket should execute the EE9 tests in `lite` mode for Java < 11.

### PR DESCRIPTION
**Pull request by pnicolucci**
fixes #21282

### CODE REVIEW

**Comment by pnicolucci** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.webcontainer.servlet.4.0_fat

**Comment by pnicolucci** [comment]
Java 8 build: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_eF9KsOE1EeymtZSUeIeeVA&tab=com.ibm.team.build.web.ui.internal.editors.result.properties.PropertiesProvider

**Review by volosied — APPROVED** [review]
This looks good to me. 

Run EE10 or  Java 11 or higher. Else run EE9.

**Comment by pnicolucci** [comment]
#libby

**Pull request merged**
