### PR TITLE
Featureutility fat add test for updated resolver 

### PR DESCRIPTION
**Pull request by jjiwooLim**
Removed resolveAutoFeatue() method which calls resolve() api again after the first resolve() or resolveAsSet() call. It's not needed anymore.  #21992
Added test case for #24315 and updated archive-1.0.zip in artifactory/dhe

### CODE REVIEW

**Comment by jjiwooLim** [comment]
#build

**Comment by jjiwooLim** [comment]
#build

**Comment by jjiwooLim** [comment]
#libby-bot

**Review by bensonlatibm — DISMISSED** [review]
lgtm!

**Comment by Azquelt** [comment]
Thanks, these changes look good to me too and the tests look sensible as well.

I've added the `DO NOT MERGE` label until we've got the epic approved, I'll chase that up tomorrow.

**Comment by jjiwooLim** [comment]
#build

**Comment by Azquelt** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.install.utility_fat,com.ibm.ws.install.featureUtility_fat

**Comment by Azquelt** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.install.utility_fat,com.ibm.ws.install.featureUtility_fat

**Comment by Azquelt** [comment]
These optimisations should fix the performance regression which was causing the test run to take much longer than expected.

**Comment by Azquelt** [comment]
Failures in the build are not related to this change

**Comment by Azquelt** [comment]
#libby

**Review by pnickoll — APPROVED** [review]

**Pull request merged**
