### PR TITLE
9786 updates

### PR DESCRIPTION
**Pull request by brenthdaniel**

### CODE REVIEW

**Comment by brenthdaniel** [comment]
#build

**Comment by brenthdaniel** [comment]
#build

**Comment by brenthdaniel** [comment]
#build

**Comment by brenthdaniel** [comment]
#run-libby-bot

**Review by cbridgha — APPROVED** [review]
LGTM - Can you update copyright dates?

**Comment by brenthdaniel** [comment]
Windows build here: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_bmONAPqzEeuB1uNHimT5CA&tab=com.ibm.team.build.web.ui.internal.editors.result.overview.OverviewPage

It has a ton of failures, but they all appear to be unrelated.

**Pull request merged**
