### PR TITLE
Add onRestore method

### PR DESCRIPTION
**Pull request by tjwatson**

### CODE REVIEW

**Comment by tjwatson** [comment]
#build

**Review by dazavala — CHANGES_REQUESTED** [review]
Need to update copyrights on GeneratePluginConfigListerner and SessionContext.  Otherwise, ready to approve this helpful change.

**Review by dazavala — DISMISSED** [review]

**Review by anjumfatima90 — DISMISSED** [review]

**Comment by tjwatson** [comment]
#build

**Review by dazavala — APPROVED** [review]
Both changes look good.  Obvious whiff on last review regarding missing return stmt and wrong debug message on restore().

**Comment by tjwatson** [comment]
#libby

**Pull request merged**
