### PR TITLE
Issue #1963: Java 2 Security error package minify

### PR DESCRIPTION
**Pull request by hlhoots**
IOException when java 2 security enabled and running the package minify
comand.

### CODE REVIEW

**Comment by hlhoots** [comment]
Please #build this Libby :)

PR for #1963

**Comment by hlhoots** [comment]
#build

**Comment by hlhoots** [comment]
#build

**Comment by ewhoch** [comment]
took a 2nd look since this changed significantly. Looks OK, this is just rolling a previously java7 only project into the kernel core, which is proper since we don't support java6 anymore.

**Pull request merged**
