### PR TITLE
featureUtility and featureManager returns RC=20 when an unknown action is specified. 

### LINKED ISSUE #17235: Improve featureUtility return code when invalid action name is specified
Users currently see an erroneous return code `0` when an invalid action is specified. This should be changed to BAD_ARGUMENT (20) so that any scripted invocations of featureUtility can detect this.

Reproduction steps: 
```
./featureUtility install; echo $?
Unknown action: install
Usage: featureUtility {installFeature|installServerFeatures|viewSettings|find|help} [options]
0
```
The RC in this case should be 20 (BAD_ARGUMENT).

### PR DESCRIPTION
**Pull request by jacobwdv**
Proper RC=20 is returned when featureUtility is executed with an unknown action in the syntax.

Fixes #17235

### CODE REVIEW

**Comment by jacobwdv** [comment]
#build

**Comment by jacobwdv** [comment]
> Please describe in a separate comment how you tested your changes.

I manually testing featureUtility and featureManager after making these changes in my own build. I also wrote a test case to ensure featureUtility continues to return RC=20 when an unknown action is specified.

**Comment by jacobwdv** [comment]
> 
> 
> The build jacobwdv-17297-20210525-1043
> https://wasrtc.hursley.ibm.com:9443/jazz/resource/itemOid/com.ibm.team.build.BuildResult/_Fmw0QL13Eeu5V8GZL3dwAw
> completed and has errors or failures.
> 
> For help analyzing your personal build, go to https://cognitive.hursley.ibm.com/buildAnalysis.html?uuid=_Fmw0QL13Eeu5V8GZL3dwAw

@bensonlatibm All of these failures are due to timeouts, what are the next steps to get this build passing. Can I rerun the test or the build to move forward?

**Comment by jacobwdv** [comment]
#build

**Review by jjiwooLim — APPROVED** [review]
LGTM

**Review by bensonlatibm — APPROVED** [review]
looks good!

**Comment by jacobwdv** [comment]
#build

**Comment by jacobwdv** [comment]
rebuilding once more, it seems these test timed out again, with one exception that one test failed with an EOF exception which seems unrelated to my changes:
`com.ibm.ws.collective.routing.controller.fat.RoutingInfoManagerTest`
```
java.rmi.UnmarshalException: error unmarshalling return; nested exception is: 
	java.io.EOFException
	at java.rmi/sun.rmi.server.UnicastRef.invoke(UnicastRef.java:197)
	at jdk.remoteref/jdk.jmx.remote.internal.rmi.PRef.invoke(Unknown Source)
	at java.management.rmi/javax.management.remote.rmi.RMIConnectionImpl_Stub.invoke(Unknown Source)
	at java.management.rmi/javax.management.remote.rmi.RMIConnector$RemoteMBeanServerConnection.invoke(RMIConnector.java:1021)
	at com.ibm.ws.collective.routing.controller.fat.RoutingInfoManagerTest.setup(RoutingInfoManagerTest.java:116)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at componenttest.custom.junit.runner.FATRunner$2.evaluate(FATRunner.java:343)
	at componenttest.custom.junit.runner.FATRunner.run(FATRunner.java:177)
Caused by: java.io.EOFException
	at java.base/java.io.ObjectInputStream$BlockDataInputStream.peekByte(ObjectInputStream.java:3248)
	at java.base/java.io.ObjectInputStream.skipCustomData(ObjectInputStream.java:2484)
	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2443)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2266)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1768)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:548)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:458)
	at java.base/java.util.HashMap.readObject(HashMap.java:1460)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1175)
	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2400)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2266)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1768)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:548)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:458)
	at java.base/java.util.concurrent.ConcurrentHashMap.readObject(ConcurrentHashMap.java:1455)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1175)
	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2400)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2266)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1768)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:548)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:458)
	at java.rmi/sun.rmi.server.UnicastRef.unmarshalValue(UnicastRef.java:327)
	at java.rmi/sun.rmi.server.UnicastRef.invoke(UnicastRef.java:177)
```

**Comment by jacobwdv** [comment]
#build

**Review by bensonlatibm — APPROVED** [review]
Looks good!

**Comment by jacobwdv** [comment]
#run-libby-bot

**Comment by jacobwdv** [comment]
image
4 tests failed, 4 timeouts. It is very unlikely my changed caused these failures. Do we move forward with the code change or should we alert whoever owns these buckets? @bensonlatibm

**Comment by bensonlatibm** [comment]
The wlp.lib.extract_fat failures are unlrelated to these changes.  They will be fixed via
 https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.workitem.viewWorkItem&id=276597

**Pull request merged**
