### PR TITLE
Issue #16568: Remove SharedServer from UpgradeReadWriteTimeout tests

### LINKED ISSUE #16568: Remove SharedServer from UpgradeReadWriteTimeoutHttpUnit for Servlet 3.1 FAT

### PR DESCRIPTION
**Pull request by pnicolucci**
fixes #16568

### CODE REVIEW

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#run-libby-bot

**Review by isaacrivriv — APPROVED** [review]
Looks good thanks!

**Comment by pnicolucci** [comment]
#run-libby-bot

**Pull request merged**
