### PR TITLE
Remove beta fence for timed log rollover

### PR DESCRIPTION
**Pull request by ellen-lau**
#build

### CODE REVIEW

**Comment by ellen-lau** [comment]
#build

**Comment by ellen-lau** [comment]
#build

**Comment by ellen-lau** [comment]
#libby #build

**Review by tonyreigns — APPROVED** [review]
LGTM

**Comment by ellen-lau** [comment]
#run-libby-bot

**Comment by ellen-lau** [comment]
#build

**Comment by ellen-lau** [comment]
Build failed with unrelated test failure -- all test cases for logging are passing.

**Pull request merged**
