### PR TITLE
Remove beta flag server config val

### PR DESCRIPTION
**Pull request by aknguyen7**
1. Include changes to revert the commit 6f94b84f08f0dc5762a9d0cb17ab7709e186da4a "Issue 21120: gate new function on beta edition" , this revert removes the beta gates in place for the new rest handler validor/config endpoints.

2. Include changes to remove the beta gate in server config admin center

### CODE REVIEW

**Comment by aknguyen7** [comment]
#build

**Comment by aknguyen7** [comment]
#build

**Review by nmittles — DISMISSED** [review]
Reviewed commit:
[Revert "Issue 21120: gate new function on beta edition"](https://github.com/OpenLiberty/open-liberty/pull/24051/commits/07c5895fe4fa02b4553dd2b5790fb02a6996ef52)

**Comment by aknguyen7** [comment]
#build

**Comment by aknguyen7** [comment]
#build

**Review by k8vance88 — APPROVED** [review]

**Comment by aknguyen7** [comment]
#build

**Comment by aknguyen7** [comment]
green build, ui tests ran successfully

image

**Comment by aknguyen7** [comment]
#libby

**Pull request merged**
