### PR TITLE
18380 wire libs for shared libraries.

### LINKED ISSUE #18380: CDI does not cross wire two jars if they are part of the same library ref
If you have a server.xml with a <library> tag with multiple jars they cannot cross inject even though they will share a classloader (CDI uses classloading to determine what can see what for injecting)

### PR DESCRIPTION
**Pull request by benjamin-confino**
This fixes #18380

### CODE REVIEW

**Comment by benjamin-confino** [comment]
#build

**Review by Azquelt — APPROVED** [review]

**Comment by benjamin-confino** [comment]
#build

**Comment by benjamin-confino** [comment]
#run-libby-bot

**Comment by benjamin-confino** [comment]
Build on https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_BAYQYAyGEeygdL3FgLlrXw is green

**Pull request merged**
