### PR TITLE
Update EE 11 FATs to use Java 21

### PR DESCRIPTION
**Pull request by jhanders34**

### CODE REVIEW

**Comment by jhanders34** [comment]
#build

**Review by KyleAure — COMMENTED** [review]
Looks good, you can also update `io.openliberty.jakarta.data.1.0_fat_tck` as it has been approved for EE 11.

**Comment by jhanders34** [comment]
> Looks good, you can also update `io.openliberty.jakarta.data.1.0_fat_tck` as it has been approved for EE 11.

The tests still use EE 10 features and we are leaving the rest of data to be Java 17 until we can upgrade it to Jakarta EE 11 by default.

**Comment by jhanders34** [comment]
#libby #build

**Review by KyleAure — APPROVED** [review]

**Review by pnicolucci — COMMENTED** [review]
Can you update Faces 5.0 as well?

io.openliberty.org.apache.myfaces.5.0_fat

**Comment by jhanders34** [comment]
> Can you update Faces 5.0 as well?
> 
> io.openliberty.org.apache.myfaces.5.0_fat

I merged before I saw your comment.  Yeah that one should be updated as well.  I missed in when searching.

**Comment by pnicolucci** [comment]
> > Can you update Faces 5.0 as well?
> > io.openliberty.org.apache.myfaces.5.0_fat
> 
> I merged before I saw your comment. Yeah that one should be updated as well. I missed in when searching.

@jhanders34 I'll do that this morning.

**Comment by pnicolucci** [comment]
You beat me to it: https://github.com/OpenLiberty/open-liberty/pull/26661

**Pull request merged**
