### PR TITLE
Allow disabling individual annotations

### PR DESCRIPTION
**Pull request by benjamin-confino**

### CODE REVIEW

**Comment by benjamin-confino** [comment]
#build

**Comment by Azquelt** [comment]
The checks in `FaultToleranceCDIExtension` also need to be added to `FaultToleranceInterceptor` where we create the policies.

Otherwise it won't work if there are multiple annotations on one method and only some of them are disabled.

**Comment by Azquelt** [comment]
Also, as it's written the cache will grow and grow because nothing is removed from it.

**Comment by Azquelt** [comment]
@benjamin-confino looks good, there was one fix needed which was that the target class is usually a Weld proxy and we need to find the real class name to look up the correct config properties.

I also took the opportunity to do a little cleaning up. Could you review my changes when you have a moment?

**Comment by Azquelt** [comment]
#build

**Comment by benjamin-confino** [comment]
#build

**Comment by benjamin-confino** [comment]
#build

**Pull request merged**
