### PR TITLE
Add code to create /lib/extract/ folder if not installed

### LINKED ISSUE #16823: Test Failure: wlp.lib.extract.PackageRunnableTest.testRunnableJar
Error:

testRunnableJar:junit.framework.AssertionFailedError: Server did not start successfully in time.
at wlp.lib.extract.PackageRunnableTest.executeTheJar(PackageRunnableTest.java:297)
at wlp.lib.extract.PackageRunnableTest.testRunnableJar(PackageRunnableTest.java:121)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

Resolution:

It seems that the /lib/extract folder is not installed in certain builds.  These changes will auto generate that folder if it does not exist.

### PR DESCRIPTION
**Pull request by hlhoots**
#build 
fixes #16823

### CODE REVIEW

**Review by cbridgha — APPROVED** [review]
LGTM

**Comment by hlhoots** [comment]
#build

**Comment by hlhoots** [comment]
latest build here:  https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_aeHhsKj_EeuKcr1KwnmtXw&tab=com.ibm.team.build.web.ui.internal.editors.result.overview.OverviewPage

**Comment by hlhoots** [comment]
#build

**Comment by hlhoots** [comment]
Last build was good.  Merging.

**Comment by hlhoots** [comment]
#run-libby-bot

**Pull request merged**
