### PR TITLE
wsscxf fat remove split

### PR DESCRIPTION
**Pull request by meiaus**
Update com.ibm.ws.wssecurity_fat.wsscxf to remove the split (EE7Only/EE8Only) and use the feature version as conditional check.

### CODE REVIEW

**Comment by meiaus** [comment]
#run-libby-bot

**Comment by meiaus** [comment]
#run-libby-bot

**Comment by meiaus** [comment]
#run-libby-bot

**Comment by meiaus** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.wssecurity_fat.wsscxf

**Comment by meiaus** [comment]
The `#build` is successful:
 Build Liberty Personal Build - EBC meiaus-18416-20210904-0533

**Comment by meiaus** [comment]
#build

**Comment by arunavemulapalli** [comment]
#build

**Review by arunavemulapalli — APPROVED** [review]

**Pull request merged**
