### PR TITLE
step 1 dd.common interfaces

### PR DESCRIPTION
**Pull request by njr-11**
Add the interfaces first as part of a 3 step process.

### CODE REVIEW

**Comment by njr-11** [comment]
#build

**Comment by njr-11** [comment]
#build
#run-libby-bot

**Review by mswatosh — APPROVED** [review]

**Comment by njr-11** [comment]
#build
#run-libby-bot

**Comment by njr-11** [comment]
#build

**Comment by njr-11** [comment]
#build

**Comment by njr-11** [comment]
#build

**Comment by njr-11** [comment]
#build

**Comment by njr-11** [comment]
Personal build https://wasrtc.hursley.ibm.com:9443/jazz/resource/itemOid/com.ibm.team.build.BuildResult/_GVPmoDNyEeyF1bm_xnmrjA has 5 test failures, all of which are duplicates of pre-existing issues in unrelated test buckets.

The other 4 most recent builds hit an infrastructure issue during the feature checker and terminated prematurely.

**Pull request merged**
