### PR TITLE
Fix various timing problems in the new Logstash collector FAT

### LINKED ISSUE #14128: Test Failure (20200923-0443): com.ibm.ws.logstash.collector.tests.LogstashSSLTest.testLogstashDefaultConfig
RTC 278134

```
junit.framework.AssertionFailedError: 2020-09-23-16:19:47:975 Did not get all messages from Logstash container. Missing 1
at com.ibm.ws.logstash.collector.tests.LogstashSSLTest.testLogstashDefaultConfig(LogstashSSLTest.java:116)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at componenttest.custom.junit.runner.FATRunner$1.evaluate(FATRunner.java:197)
at org.testcontainers.containers.FailureDetectingExternalResource$1.evaluate(FailureDetectingExternalResource.java:30)
at componenttest.custom.junit.runner.FATRunner$2.evaluate(FATRunner.java:318)
at componenttest.custom.junit.runner.FATRunner.run(FATRunner.java:171)
```

### LINKED ISSUE #14142: Test Failure (20200923-0443): com.ibm.ws.logstash.collector.tests.CustomizedTagTest.testTags
RTC 278135

```
junit.framework.AssertionFailedError: 2020-09-23-19:09:23:286 liberty_accesslog not found
at com.ibm.ws.logstash.collector.tests.CustomizedTagTest.testTags(CustomizedTagTest.java:180)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at componenttest.custom.junit.runner.FATRunner$1.evaluate(FATRunner.java:197)
at org.testcontainers.containers.FailureDetectingExternalResource$1.evaluate(FailureDetectingExternalResource.java:30)
at componenttest.custom.junit.runner.FATRunner$2.evaluate(FATRunner.java:318)
at componenttest.custom.junit.runner.FATRunner.run(FATRunner.java:171)
```

### LINKED ISSUE #14143: Test Failure: com.ibm.ws.logstash.collector.tests.LogstashSSLTest.testLogstashEvents
RTC 278147

```
testLogstashEvents:junit.framework.AssertionFailedError: 2020-09-23-22:24:12:917 liberty_gc not found
at com.ibm.ws.logstash.collector.tests.LogstashSSLTest.testLogstashEvents(LogstashSSLTest.java:148)
at componenttest.custom.junit.runner.FATRunner$1.evaluate(FATRunner.java:197)
at org.testcontainers.containers.FailureDetectingExternalResource$1.evaluate(FailureDetectingExternalResource.java:30)
at componenttest.custom.junit.runner.FATRunner$2.evaluate(FATRunner.java:318)
at componenttest.custom.junit.runner.FATRunner.run(FATRunner.java:171)
```

### PR DESCRIPTION
**Pull request by fmhwong**
- Moved up wait for TRAS0218I so that the container output will only contain the 10 messages.
fixes #14128 

- Added more wait for the events
fixes #14142 

- Added a createGCEvent() method to create GC events
fixes #14143

### CODE REVIEW

**Comment by fmhwong** [comment]
#build

**Comment by fmhwong** [comment]
#build

**Comment by fmhwong** [comment]
#libby 
#build

**Review by Yushan-Lin — APPROVED** [review]
LGTM

**Pull request merged**
