### PR TITLE
Init Commit: adding tcpOptions documentation for acceptThread and wai…

### PR DESCRIPTION
**Pull request by mrsaldana**
…tToAccept options

### CODE REVIEW

**Comment by mrsaldana** [comment]
#build

**Comment by micgibso** [comment]
ID: Changes reviewed, all look good.

**Comment by mrsaldana** [comment]
#build

**Comment by mrsaldana** [comment]
#build

**Comment by mrsaldana** [comment]
#build

**Comment by mrsaldana** [comment]
#build

**Comment by mrsaldana** [comment]
#build

**Comment by mrsaldana** [comment]
Resolved by #4977

**Pull request closed without merging**
