### PR TITLE
clean up JSF 2.3 FAT test classes

### LINKED ISSUE #24856: Clean up JSF 2.3 FAT Test classes
Reuse Class variable already defined in each class when starting up the server.
    Ensure Class variable is correct in each class.
    Clean up copyright headers

### PR DESCRIPTION
**Pull request by pnicolucci**
fixes #24856

### CODE REVIEW

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
#libby #build

**Review by isaacrivriv — APPROVED** [review]
Looks good!

**Comment by pnicolucci** [comment]
#libby

**Pull request merged**
