### PR TITLE
21.0.0.4 PII NLS Returns

### PR DESCRIPTION
**Pull request by pnickoll**

### CODE REVIEW

**Comment by pnickoll** [comment]
#build

**Comment by pnickoll** [comment]
#build

**Review by crpotter — APPROVED** [review]

**Comment by pnickoll** [comment]
#build

**Comment by pnickoll** [comment]
#build

**Comment by pnickoll** [comment]
#build

**Comment by pnickoll** [comment]
#build

**Comment by pnickoll** [comment]
#libbybot

**Pull request merged**
