### PR TITLE
partial refactor to avoid including experimental annotatations in data-1.0

### PR DESCRIPTION
**Pull request by njr-11**
Partial refactoring to avoid including experimental annotations in data-1.0 under api.
More work should be done after this PR to remove references/hacks in the code that still refer to the partial annotations, but this was enough to decouple them at the feature level, so it seemed like a good place to break up the work.

### CODE REVIEW

**Comment by njr-11** [comment]
#build

**Review by KyleAure — CHANGES_REQUESTED** [review]
The changes themselves look good. 
I just wonder about the names of the packages and bundles. 
Based on the [naming guidelines](https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-naming-guidelines) 

Internal projects and bundles should be named: 
- io.openliberty.data.1.0.internal
- io.openliberty.data.1.1.internal

Internal packages should be named: 
- io/openliberty/data/internal
^^ Would the package names need to include the version?  I don't think they would since the bundles should never be activated together.  That one I'm not as sure about.

**Review by KyleAure — APPROVED** [review]
Looks good 👍🏼

**Comment by njr-11** [comment]
#build
#libby

**Pull request merged**
