### PR TITLE
mpOpenAPI 1.0 Fixes and fat test improvements

### PR DESCRIPTION
**Pull request by arturdzm**

### CODE REVIEW

**Comment by arturdzm** [comment]
#build

**Comment by arturdzm** [comment]
#build

**Comment by arturdzm** [comment]
Build still running, but microprofile openapi tests finished green. Should be good to merge

**Comment by leochr** [comment]
Personal build completed and the failures are unrelated. Please merge these commits - needed for 1Q18 feature mpOpenAPI-1.0

**Comment by ewhoch** [comment]
Something seems wrong with this PR. there are 109 commits listed for 151 file changes. I wouldn't expect that and it would make the commit history significantly messy.

**Comment by leochr** [comment]
(Including the justifications given in the email here for record):

What's in the commits?
There is some portion of development code, but the changes are mostly unit tests, FATs and automated TCKs for our 1Q feature mpOpenAPI-1.0 along with some serviceability improvements. Kevin Smith reviewed the test coverage and was quite happy with what we have. But he can't approve until the tests run as part of an official build.
 
All changes are for the new feature and it's isolated from other components. The personal builds passed and there were no failures in anything related to our components. So we believe the risk of accepting is minimal.
 
Reason for lots of commits:
We haven't been able to deliver into the integration branch due to the buildcon. The team members needed each others' commits to continue the work. So we were working on our team branch. We were trying to deliver incrementally and earlier had another pull request, but since it wasn't merged, we closed that one (#2240).
 
Also wanted to point out that we had taken this 'team branch' approach from 1Q17, since waiting for dependent commits to make into master took so long and were blocking us. We never caused any build issues because all of the related commits coming from our team were built together and tested together before delivering into integration branch.
 
Please help to unblock us and to ship our feature.

**Pull request merged**
