### PR TITLE
Port MYFACES-4500 and MYFACES-4501

### LINKED ISSUE #23351: Port MYFACES-4500, MYFACES-4501
https://issues.apache.org/jira/browse/MYFACES-4500
https://issues.apache.org/jira/browse/MYFACES-4501

### PR DESCRIPTION
**Pull request by volosied**
fixes #23351

Addreses xml preamble and throws an ISE if multiple redirects occur in ajax requests.

### CODE REVIEW

**Comment by volosied** [comment]
#build

**Comment by volosied** [comment]
#build

**Comment by volosied** [comment]
#build

**Review by pnicolucci — DISMISSED** [review]

**Comment by volosied** [comment]
#libby

**Review by pnicolucci — APPROVED** [review]

**Comment by volosied** [comment]
#libby

**Comment by volosied** [comment]
#build

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
#libby-build

**Pull request merged**
