### PR TITLE
Add selenium testcontainer and cleanup testcontainer projects

### PR DESCRIPTION
**Pull request by KyleAure**
Add selenium test container to `io.openliberty.org.testcontainers` bundle. 
Change test container projects to have runtime dependency on said bundle.
Add `generate.replacement: true` to bundle so the bundle is accessible in the WL repo.

### CODE REVIEW

**Comment by KyleAure** [comment]
#build

**Review by jmstephensgit — APPROVED** [review]

**Comment by KyleAure** [comment]
Doing one extra #build to make sure any intermittent defects aren't hiding any issues with this PR.

**Comment by KyleAure** [comment]
#build after resolving merge conflicts

**Comment by KyleAure** [comment]
#build

**Comment by KyleAure** [comment]
#build again after resolving merge conflicts

**Comment by KyleAure** [comment]
#libbybot

**Pull request merged**
