### PR TITLE
New JPA 3.1 testing

### PR DESCRIPTION
**Pull request by dazey3**
1. Enable existing tests for JPA 3.1 that were disabled with `com.ibm.ws.testtooling.testlogic.AbstractTestLogic.isUsingJPA31Feature()` check
2. Create new `com.ibm.ws.jpa.tests.eclipselink.query_jpa_3.1_fat` FAT
3. Move tests for the JPA Spec 3.1's new `Adds support for Expressions as conditions in Criteria CASE expressions` feature to `com.ibm.ws.jpa.tests.jpa_31_fat`

### CODE REVIEW

**Comment by dazey3** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jpa.tests.spec10.query_jpa_3.1_fat,com.ibm.ws.jpa.tests.spec10.entitymanager_jpa_3.1_fat,com.ibm.ws.jpa.tests.spec10.entity_jpa_3.1_fat,com.ibm.ws.jpa.tests.eclipselink_jpa_3.1_fat,com.ibm.ws.jpa.tests.eclipselink.query_jpa_3.1_fat

**Comment by dazey3** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jpa.tests.spec10.query_jpa_3.1_fat,com.ibm.ws.jpa.tests.spec10.entitymanager_jpa_3.1_fat,com.ibm.ws.jpa.tests.spec10.entity_jpa_3.1_fat,com.ibm.ws.jpa.tests.eclipselink_jpa_3.1_fat,com.ibm.ws.jpa.tests.eclipselink.query_jpa_3.1_fat

**Comment by dazey3** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jpa.tests.spec10.query_jpa_3.1_fat,com.ibm.ws.jpa.tests.spec10.entitymanager_jpa_3.1_fat,com.ibm.ws.jpa.tests.spec10.entity_jpa_3.1_fat,com.ibm.ws.jpa.tests.eclipselink_jpa_3.1_fat,com.ibm.ws.jpa.tests.eclipselink.query_jpa_3.1_fat

**Comment by dazey3** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jpa.tests.spec10.query_jpa_3.1_fat,com.ibm.ws.jpa.tests.spec10.entitymanager_jpa_3.1_fat,com.ibm.ws.jpa.tests.spec10.entity_jpa_3.1_fat,com.ibm.ws.jpa.tests.eclipselink_jpa_3.1_fat,com.ibm.ws.jpa.tests.eclipselink.query_jpa_3.1_fat

**Comment by dazey3** [comment]
https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_Iydg5jPUEe2Kc-z_2q9Pqw

**Review by tkburroughs — APPROVED** [review]

**Comment by tkburroughs** [comment]
#libby

**Pull request merged**
