### PR TITLE
build: use valid environment variable names

### PR DESCRIPTION
**Pull request by joe-chacko**
- [x] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [x] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [x] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

### CODE REVIEW

**Comment by joe-chacko** [comment]
!build

**Comment by joe-chacko** [comment]
#build

**Comment by jonhawkes** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.transaction.hadb_fat.postgresql.lease

**Review by jonhawkes — APPROVED** [review]
wfm

**Review by KyleAure — APPROVED** [review]

**Pull request merged**
