### PR TITLE
Updates to personalbuild.yml and rtcbuild.yml

### PR DESCRIPTION
**Pull request by fritze2**
- Increase dependencyMapper's timeoutInMinutes from 30 to 120. The dependencyMapper step should take up to 30 minutes to execute and queue times may vary from 10 minutes to an hour. Since timeoutInMinutes includes queue time, setting it to 2 hours will allow for 1.5h queue times and 30 minutes executing the step.
- Add keywords that respond to ! instead of #.

### CODE REVIEW

**Comment by fritze2** [comment]
!pbbeta

**Comment by fritze2** [comment]
!fullpbbeta

**Comment by fritze2** [comment]
!pb

**Comment by fritze2** [comment]
!fullpb

**Comment by fritze2** [comment]
!build

**Comment by fritze2** [comment]
Cancelling the last 5 pipelines because I only need to test that they launch successfully.

**Comment by fritze2** [comment]
Test using #build and #pbbeta to verify this can be merged.

**Comment by fritze2** [comment]
Also run #pb to compare against.

**Review by crpotter — APPROVED** [review]

**Comment by fritze2** [comment]
#libby

**Pull request merged**
