### PR TITLE
Ignore AppForceRestart on quiesce

### PR DESCRIPTION
**Pull request by brenthdaniel**
In rare situations, if a configuration update that includes a feature update is started as the server is shut down, the server quiesce will fail because it is waiting on applications to restart.

### CODE REVIEW

**Comment by brenthdaniel** [comment]
#build

**Comment by brenthdaniel** [comment]
#build

**Review by jimblye — APPROVED** [review]

**Review by hlhoots — APPROVED** [review]
looks good to me.

**Comment by brenthdaniel** [comment]
#run-libby-bot

**Pull request merged**
