### PR TITLE
Generate FAT help file and minor cleanup

### LINKED ISSUE #26710: Minor WebTier FAT bucket cleanup
1) Ensure we generate the FAT help file.
2) Remove unused imports and variables

### PR DESCRIPTION
**Pull request by pnicolucci**
fixes #26710

### CODE REVIEW

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
#libby #build

**Review by volosied — DISMISSED** [review]
Looks fine to me.

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
#libby #build

**Review by volosied — APPROVED** [review]
Looks good 
Edit: Not sure what the `CI Orchestrator Pipeline` failure means.

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#libby

**Pull request merged**
