### PR TITLE
fixing windows unit tests and updating exclusion list for the windows…

### PR DESCRIPTION
**Pull request by jacobwdv**
… uninstall performance changes

Another attempt at windows uninstall performance. It seems we missed one directory from the exclusion list. 

Found also that unit tests weren't passing on Windows, updated the tests and added some improved logic for file deletion in ESAAsset.java

### CODE REVIEW

**Comment by jacobwdv** [comment]
#libby-bot

**Comment by jacobwdv** [comment]
#build

**Comment by jacobwdv** [comment]
#libby-bot

**Comment by jacobwdv** [comment]
#build

**Comment by jacobwdv** [comment]
#build

**Comment by jacobwdv** [comment]
#build

**Review by bensonlatibm — APPROVED** [review]
lgtm!

**Comment by jacobwdv** [comment]
#build

**Comment by jacobwdv** [comment]
#build

**Pull request merged**
