### PR TITLE
Repeat Hazelcast tests for Jakarta EE10

### PR DESCRIPTION
**Pull request by zhang-ca**
Repeat Hazelcast Session FATs for Jakarta EE10

com.ibm.ws.session.cache_fat
com.ibm.ws.session.cache_fat_config

### CODE REVIEW

**Comment by zhang-ca** [comment]
fixes #21200

**Comment by zhang-ca** [comment]
Changes depends on #21076

**Comment by zhang-ca** [comment]
#build

**Comment by zhang-ca** [comment]
#build

**Review by bensonlatibm — APPROVED** [review]
lgtm!

**Pull request merged**
