### PR TITLE
Upgrade ASM to 9.2

### LINKED ISSUE #18650: Upgrade ASM to 9.2
Open Liberty relies on [ASM](https://asm.ow2.io/index.html).  We are currently running ASM 9.1, but to support Java 18, we need to upgrade to [ASM 9.2](https://asm.ow2.io/versions.html).

ASM related changes also need to be made to Eclipselink and covered in issue #18653.

These 2 changes are completely isolated from each other and can be delivered separately.

### PR DESCRIPTION
**Pull request by gjwatts**

### CODE REVIEW

**Comment by gjwatts** [comment]
#build

**Review by KyleAure — APPROVED** [review]

**Comment by gjwatts** [comment]
Libby bot did not post the PB results, but the unit test `com.ibm.ws.anno` failed at
```
com.ibm.ws.anno.test.cases.AnnotationTest_Error_InfoFailures > testAnnotationTest_Error_InfoFailures
    java.lang.ArrayIndexOutOfBoundsException at AnnotationTest_Error_InfoFailures.java:82
```
in
```
java.lang.ArrayIndexOutOfBoundsException
	at org.objectweb.asm.ClassReader.readStringish(ClassReader.java:3726)
	at org.objectweb.asm.ClassReader.readClass(ClassReader.java:3741)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:454)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:424)
	at com.ibm.ws.anno.info.internal.InfoStoreImpl.scanNewClass(InfoStoreImpl.java:258)
	at com.ibm.ws.anno.info.internal.InfoStoreImpl.scanNewClass(InfoStoreImpl.java:190)
	at com.ibm.ws.anno.info.internal.InfoStoreImpl.scanClass(InfoStoreImpl.java:145)
	at com.ibm.ws.anno.info.internal.ClassInfoCache.scanClass(ClassInfoCache.java:158)
	at com.ibm.ws.anno.info.internal.ClassInfoCache.resolveClassInfo(ClassInfoCache.java:1077)
	at com.ibm.ws.anno.info.internal.InfoStoreImpl.resolveClassInfo(InfoStoreImpl.java:367)
	at com.ibm.ws.anno.info.internal.DelayedClassInfo.getClassInfo(DelayedClassInfo.java:130)
	at com.ibm.ws.anno.info.internal.DelayedClassInfo.isArtificial(DelayedClassInfo.java:200)
	at com.ibm.ws.anno.test.cases.AnnotationTest_Error_InfoFailures.verifyClassInfo(AnnotationTest_Error_InfoFailures.java:82)
	at com.ibm.ws.anno.test.cases.AnnotationTest_Error_InfoFailures.verifyInfoStore(AnnotationTest_Error_InfoFailures.java:179)
	at com.ibm.ws.anno.test.cases.AnnotationTest_BaseClass.verifyInfoStore(AnnotationTest_BaseClass.java:448)
	at com.ibm.ws.anno.test.cases.AnnotationTest_BaseClass.runScanTest(AnnotationTest_BaseClass.java:317)
	at com.ibm.ws.anno.test.cases.AnnotationTest_BaseClass.runScanTest(AnnotationTest_BaseClass.java:274)
	at com.ibm.ws.anno.test.cases.AnnotationTest_BaseClass.runScanTest(AnnotationTest_BaseClass.java:257)
	at com.ibm.ws.anno.test.cases.AnnotationTest_Error_InfoFailures.testAnnotationTest_Error_InfoFailures(AnnotationTest_Error_InfoFailures.java:35)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at test.common.SharedOutputManager$1.evaluate(SharedOutputManager.java:620)
	at org.junit.rules.RunRules.evaluate(RunRules.java:18)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at jdk.internal.reflect.GeneratedMethodAccessor7.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:119)
	at jdk.internal.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:414)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
and
```
com.ibm.ws.annocache.test.scan.errors.AnnotationTargets_InfoFailures_ErrorTest > validateInfoStore
    java.lang.ArrayIndexOutOfBoundsException at AnnotationTargets_InfoFailures_ErrorTest.java:76
```
in
```
java.lang.ArrayIndexOutOfBoundsException
	at org.objectweb.asm.ClassReader.readStringish(ClassReader.java:3726)
	at org.objectweb.asm.ClassReader.readClass(ClassReader.java:3741)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:454)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:424)
	at com.ibm.ws.annocache.info.internal.InfoStoreImpl.scanNewClass(InfoStoreImpl.java:266)
	at com.ibm.ws.annocache.info.internal.InfoStoreImpl.scanNewClass(InfoStoreImpl.java:197)
	at com.ibm.ws.annocache.info.internal.InfoStoreImpl.scanClass(InfoStoreImpl.java:153)
	at com.ibm.ws.annocache.info.internal.ClassInfoCacheImpl.scanClass(ClassInfoCacheImpl.java:156)
	at com.ibm.ws.annocache.info.internal.ClassInfoCacheImpl.resolveClassInfo(ClassInfoCacheImpl.java:1137)
	at com.ibm.ws.annocache.info.internal.InfoStoreImpl.resolveClassInfo(InfoStoreImpl.java:375)
	at com.ibm.ws.annocache.info.internal.DelayedClassInfoImpl.getClassInfo(DelayedClassInfoImpl.java:128)
	at com.ibm.ws.annocache.info.internal.DelayedClassInfoImpl.isArtificial(DelayedClassInfoImpl.java:196)
	at com.ibm.ws.annocache.test.scan.errors.AnnotationTargets_InfoFailures_ErrorTest.validateClassInfo(AnnotationTargets_InfoFailures_ErrorTest.java:76)
	at com.ibm.ws.annocache.test.scan.errors.AnnotationTargets_InfoFailures_ErrorTest.validateInfoStore(AnnotationTargets_InfoFailures_ErrorTest.java:188)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:30)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at jdk.internal.reflect.GeneratedMethodAccessor7.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:119)
	at jdk.internal.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:414)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	at java.base/java.lang.Thread.run(Thread.java:836)
```

**Comment by gjwatts** [comment]
But the same branch built on Java 17 (Hotspot) passed just fine with the new ASM 9.2.

**Comment by gjwatts** [comment]
Had to modify the anno [InfoStoreImpl.java](https://github.com/OpenLiberty/open-liberty/blob/integration/dev/com.ibm.ws.anno/src/com/ibm/ws/anno/info/internal/InfoStoreImpl.java) and annocache [InfoStoreImpl.java](https://github.com/OpenLiberty/open-liberty/blob/integration/dev/com.ibm.ws.anno/src/com/ibm/ws/annocache/info/internal/InfoStoreImpl.java) files to handle an `ArrayIndexOutOfBoundsException` being thrown due to changes in ClassReader.java between ASM 9.1 and ASM 9.2 when we test with invalid classes.

**Comment by gjwatts** [comment]
#build

**Comment by gjwatts** [comment]
#build

**Review by KyleAure — APPROVED** [review]
Approved dependency updates.  Please have the teams responsible for the product code updates review this as well.

**Review by tbitonti — APPROVED** [review]
Do we know what about the class causes the exception?  How likely will the exception be caused by existing applications?

**Comment by gjwatts** [comment]
#build

**Comment by tbitonti** [comment]
We aren't the only folks to have noticed this:
https://gitlab.ow2.org/asm/asm/-/issues/317955

**Comment by gjwatts** [comment]
Failure was a known defect and unrelated to the changes in this PR.

**Comment by gjwatts** [comment]
Waiting until after 17-Nov-2021 to merge per Tom's request.

**Comment by tbitonti** [comment]
Created this:
https://gitlab.ow2.org/asm/asm/-/issues/317957
I think we should go ahead with the change as-is.
We might want to change the 'catch' clause to catch more parse failures.

**Comment by gjwatts** [comment]
@tbitonti What other exceptions would you recommend we catch?

**Comment by tbitonti** [comment]
Ah, missed something.  There is an addition class which needs the same update:

https://github.com/OpenLiberty/open-liberty/blob/integration/dev/com.ibm.ws.anno/src/com/ibm/ws/annocache/info/internal/InfoStoreImpl.java

**Comment by gjwatts** [comment]
#build

**Review by tbitonti — APPROVED** [review]

**Comment by gjwatts** [comment]
Last FAT did not complete.  Running again.  #build

**Comment by gjwatts** [comment]
There were 3 FAT buckets that failed in this last run.  Two of them were known defects.  The last one (com.ibm.ws.jbatch.open_fat) I ran separate testing against 10 times and they all passed -> https://wasrtc.hursley.ibm.com:9443/jazz/resource/itemOid/com.ibm.team.build.BuildResult/_QWHRTkGtEeyda8UYcX_yfQ (FYI, IBM internal link only).

**Comment by gjwatts** [comment]
#build

**Comment by gjwatts** [comment]
#libbybot

**Comment by gjwatts** [comment]
The only failure in the last test was for an unrelated UI FAT.  Merging.

**Pull request merged**
