### PR TITLE
Update EclipseLink 2.6_WAS for JPA 2.1

### PR DESCRIPTION
**Pull request by dazey3**
for #16588
for #16685
for #16686
for #16772

### CODE REVIEW

**Comment by dazey3** [comment]
#run-libby-bot

**Comment by dazey3** [comment]
#run-libby-bot

**Comment by dazey3** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jpa.tests.spec10.embeddable_fat,com.ibm.ws.jpa_22_fat,com.ibm.ws.jpa_30_fat,com.ibm.ws.jpa_eclipselink_fat,com.ibm.ws.jpa_ol_fat,com.ibm.ws.jpa_spec10_query_fat,com.ibm.ws.jpa_spec20_fat,com.ibm.ws.jpa.tests.spec10.callback_fat,com.ibm.ws.jpa.tests.spec10.entitymanager_fat,com.ibm.ws.jpa.tests.spec10.inheritance_fat,com.ibm.ws.jpa.tests.spec10.issues_fat,com.ibm.ws.jpa.tests.spec10.relationships.manyXmany_fat,com.ibm.ws.jpa.tests.spec10.relationships.manyXone_fat,com.ibm.ws.jpa.tests.spec10.relationships.oneXmany_fat,com.ibm.ws.jpa.tests.spec10.relationships.oneXone_fat

**Comment by dazey3** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jpa.tests.spec10.embeddable_fat,com.ibm.ws.jpa_22_fat,com.ibm.ws.jpa_30_fat,com.ibm.ws.jpa_eclipselink_fat,com.ibm.ws.jpa_ol_fat,com.ibm.ws.jpa_spec10_query_fat,com.ibm.ws.jpa_spec20_fat,com.ibm.ws.jpa.tests.spec10.callback_fat,com.ibm.ws.jpa.tests.spec10.entitymanager_fat,com.ibm.ws.jpa.tests.spec10.inheritance_fat,com.ibm.ws.jpa.tests.spec10.issues_fat,com.ibm.ws.jpa.tests.spec10.relationships.manyXmany_fat,com.ibm.ws.jpa.tests.spec10.relationships.manyXone_fat,com.ibm.ws.jpa.tests.spec10.relationships.oneXmany_fat,com.ibm.ws.jpa.tests.spec10.relationships.oneXone_fat

**Comment by dazey3** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jpa.tests.spec10.embeddable_fat,com.ibm.ws.jpa_22_fat,com.ibm.ws.jpa_30_fat,com.ibm.ws.jpa_eclipselink_fat,com.ibm.ws.jpa_ol_fat,com.ibm.ws.jpa_spec10_query_fat,com.ibm.ws.jpa_spec20_fat,com.ibm.ws.jpa.tests.spec10.callback_fat,com.ibm.ws.jpa.tests.spec10.entitymanager_fat,com.ibm.ws.jpa.tests.spec10.inheritance_fat,com.ibm.ws.jpa.tests.spec10.issues_fat,com.ibm.ws.jpa.tests.spec10.relationships.manyXmany_fat,com.ibm.ws.jpa.tests.spec10.relationships.manyXone_fat,com.ibm.ws.jpa.tests.spec10.relationships.oneXmany_fat,com.ibm.ws.jpa.tests.spec10.relationships.oneXone_fat

**Comment by dazey3** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jpa.tests.spec10.embeddable_fat,com.ibm.ws.jpa_22_fat,com.ibm.ws.jpa_30_fat,com.ibm.ws.jpa_eclipselink_fat,com.ibm.ws.jpa_ol_fat,com.ibm.ws.jpa_spec10_query_fat,com.ibm.ws.jpa_spec20_fat,com.ibm.ws.jpa.tests.spec10.callback_fat,com.ibm.ws.jpa.tests.spec10.entitymanager_fat,com.ibm.ws.jpa.tests.spec10.inheritance_fat,com.ibm.ws.jpa.tests.spec10.issues_fat,com.ibm.ws.jpa.tests.spec10.relationships.manyXmany_fat,com.ibm.ws.jpa.tests.spec10.relationships.manyXone_fat,com.ibm.ws.jpa.tests.spec10.relationships.oneXmany_fat,com.ibm.ws.jpa.tests.spec10.relationships.oneXone_fat

**Comment by dazey3** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jpa.tests.spec10.embeddable_fat,com.ibm.ws.jpa_22_fat,com.ibm.ws.jpa_30_fat,com.ibm.ws.jpa_eclipselink_fat,com.ibm.ws.jpa_ol_fat,com.ibm.ws.jpa_spec10_query_fat,com.ibm.ws.jpa_spec20_fat,com.ibm.ws.jpa.tests.spec10.callback_fat,com.ibm.ws.jpa.tests.spec10.entitymanager_fat,com.ibm.ws.jpa.tests.spec10.inheritance_fat,com.ibm.ws.jpa.tests.spec10.issues_fat,com.ibm.ws.jpa.tests.spec10.relationships.manyXmany_fat,com.ibm.ws.jpa.tests.spec10.relationships.manyXone_fat,com.ibm.ws.jpa.tests.spec10.relationships.oneXmany_fat,com.ibm.ws.jpa.tests.spec10.relationships.oneXone_fat

**Comment by dazey3** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jpa_22_fat,com.ibm.ws.jpa_30_fat,com.ibm.ws.jpa_eclipselink_fat,com.ibm.ws.jpa_ol_fat,com.ibm.ws.jpa_spec10_query_fat,com.ibm.ws.jpa_spec20_fat,com.ibm.ws.jpa.tests.spec10.callback_fat,com.ibm.ws.jpa.tests.spec10.entitymanager_fat,com.ibm.ws.jpa.tests.spec10.inheritance_fat,com.ibm.ws.jpa.tests.spec10.issues_fat,com.ibm.ws.jpa.tests.spec10.relationships.manyXmany_fat,com.ibm.ws.jpa.tests.spec10.relationships.manyXone_fat,com.ibm.ws.jpa.tests.spec10.relationships.oneXmany_fat,com.ibm.ws.jpa.tests.spec10.relationships.oneXone_fat

**Comment by dazey3** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jpa_22_fat,com.ibm.ws.jpa_30_fat,com.ibm.ws.jpa_eclipselink_fat,com.ibm.ws.jpa_ol_fat,com.ibm.ws.jpa_spec10_query_fat,com.ibm.ws.jpa_spec20_fat,com.ibm.ws.jpa.tests.spec10.callback_fat,com.ibm.ws.jpa.tests.spec10.entitymanager_fat,com.ibm.ws.jpa.tests.spec10.inheritance_fat,com.ibm.ws.jpa.tests.spec10.issues_fat,com.ibm.ws.jpa.tests.spec10.relationships.manyXmany_fat,com.ibm.ws.jpa.tests.spec10.relationships.manyXone_fat,com.ibm.ws.jpa.tests.spec10.relationships.oneXmany_fat,com.ibm.ws.jpa.tests.spec10.relationships.oneXone_fat

**Review by jgrassel — APPROVED** [review]
LGTM

**Comment by dazey3** [comment]
#run-libby-bot

**Pull request merged**
