### PR TITLE
Test change to recursive find in perm mgr code

### PR DESCRIPTION
**Pull request by hlhoots**
#build

### CODE REVIEW

**Comment by hlhoots** [comment]
build super slow.  rebuilding.
#build

**Comment by hlhoots** [comment]
Build had issues in one bucket which looks to be a known issue.  Rebuilding for sanity check.

#build

**Comment by hlhoots** [comment]
code clean up
#build

**Comment by hlhoots** [comment]
fixes #15958

**Comment by hlhoots** [comment]
#build

**Comment by hlhoots** [comment]
j2sec build here: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_eywpcHFWEeu93_rH8DpK2g

**Comment by hlhoots** [comment]
#build

**Comment by hlhoots** [comment]
#build

**Comment by hlhoots** [comment]
Last build was good with 1 ui failure.

**Comment by hlhoots** [comment]
Java 2 sec build here:  https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_-CYyEHUjEeuM4LMmhYlrDw&tab=com.ibm.team.build.web.ui.internal.editors.result.test.TestProvider

Had some failures, but the app.manager bucket where previous errors happened ran okay.

**Review by cbridgha — APPROVED** [review]
LGTM

**Review by emilytee — APPROVED** [review]

**Comment by hlhoots** [comment]
#run-libby-bot

**Pull request merged**
