### PR TITLE
24077: DoNotAllowDuplicateSetCookie property not working

### LINKED ISSUE #24077: DoNotAllowDuplicateSetCookies http channel config option is not working
**Describe the bug**  
The http channel config property DoNotAllowDuplicateSetCookies=true, when set, still allows duplicate set-cookie cookies in http responses.

**Steps to Reproduce**  
Set the <httpOptions DoNotAllowDuplicateSetCookies="true"/> on the httpEndPoint in server.xml.  Have an application create two Set-Cookie headers with the same cookie name.  When the property is set, the duplicate header should be removed from the response.

**Expected behavior**  
The http response should not be sent with duplicate Set-Cookie cookies.

**Diagnostic information:**  
 - OpenLiberty Version: [e.g. 20.0.0.3 - 23.0.0.1]
 - Affected feature(s): setvlet-4.0, servlet-3.1
 - Java Version: n/a
 - server.xml configuration
 <server>
    <featureManager>
        <feature>servlet-4.0</feature>
    </featureManager>
    <httpEndpoint id="defaultHttpEndpoint"
                  httpPort="9080"
        <httpOptions DoNotAllowDuplicateSetCookies="true"/>
    </httpEndpoint>
</server>

### PR DESCRIPTION
**Pull request by loriadi**
Fix the DoNotAllowDuplicateSetCookies httpchannel property

fixes #24077

### CODE REVIEW

**Comment by loriadi** [comment]
fixes #24077

**Comment by loriadi** [comment]
#build

**Comment by loriadi** [comment]
fixes #PH52167

**Review by mrsaldana — APPROVED** [review]
LGTM

**Pull request merged**
