### PR TITLE
WS-Security SAML FAT:: Update repeat action to match SAML Web SSO repeat actions

### PR DESCRIPTION
**Pull request by neuwerk**
- [x] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [ ] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [ ] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

### CODE REVIEW

**Comment by neuwerk** [comment]
#29989

**Comment by neuwerk** [comment]
#build

**Review by BerksanAtes — APPROVED** [review]
Looks good to me!

**Comment by neuwerk** [comment]
#libby

**Pull request merged**
