### PR TITLE
Wait for server stop process to end

### LINKED ISSUE #15280: Framework Error
In MicroProfile Starter GH Actions and Circle CI build, the following error surfaced regularly. See [here](https://github.com/eclipse/microprofile-starter/actions/runs/415183661) for logs.
```
Extracting files to /home/runner/wlpExtract/liberty_2294323321101/wlp
Successfully extracted all product files.
Launching liberty (Open Liberty 20.0.0.12/wlp-1.0.47.cl201220201111-0736) on OpenJDK 64-Bit Server VM, version 11.0.9.1+1 (en_US)
[AUDIT   ] CWWKE0001I: The server liberty has been launched.
[AUDIT   ] CWWKZ0058I: Monitoring dropins for applications.
[AUDIT   ] CWWKS4104A: LTPA keys created in 1.519 seconds. LTPA key file: /home/runner/wlpExtract/liberty_2294323321101/wlp/usr/servers/liberty/resources/security/ltpa.keys
[AUDIT   ] CWPKI0803A: SSL certificate created in 1.458 seconds. SSL key file: /home/runner/wlpExtract/liberty_2294323321101/wlp/usr/servers/liberty/resources/security/public.jks
[AUDIT   ] CWWKT0016I: Web application available (default_host): http://localhost:9080/metrics/
[AUDIT   ] CWWKT0016I: Web application available (default_host): http://localhost:9080/jwt/
[AUDIT   ] CWWKT0016I: Web application available (default_host): http://localhost:9080/openapi/ui/
[AUDIT   ] CWWKT0016I: Web application available (default_host): http://localhost:9080/health/
[AUDIT   ] CWWKT0016I: Web application available (default_host): http://localhost:9080/openapi/
[AUDIT   ] CWWKT0016I: Web application available (default_host): http://localhost:9080/ibm/api/
[AUDIT   ] CWWKT0016I: Web application available (default_host): http://localhost:9080/
[AUDIT   ] CWWKZ0001I: Application liberty started in 3.020 seconds.
[AUDIT   ] CWWKF0012I: The server installed the following features: [appSecurity-2.0, cdi-2.0, concurrent-1.0, distributedMap-1.0, jaxrs-2.1, jaxrsClient-2.1, jndi-1.0, json-1.0, jsonb-1.0, jsonp-1.1, jwt-1.0, microProfile-3.3, monitor-1.0, mpConfig-1.4, mpFaultTolerance-2.1, mpHealth-2.2, mpJwt-1.1, mpMetrics-2.3, mpOpenAPI-1.1, mpOpenTracing-1.3, mpRestClient-1.4, opentracing-1.3, servlet-4.0, ssl-1.0].
[AUDIT   ] CWWKF0011I: The liberty server is ready to run a smarter planet. The liberty server started in 10.393 seconds.
[AUDIT   ] CWWKE0085I: The server liberty is stopping because the JVM is exiting.
[err] !SESSION 2020-12-11 10:34:50.100 -----------------------------------------------
eclipse.buildId=unknown
java.version=11.0.9.1
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
!ENTRY org.eclipse.osgi 4 0 2020-12-11 10:34:50.101
!MESSAGE FrameworkEvent ERROR
!STACK 0
java.io.IOException: Exception in opening zip file: /home/runner/wlpExtract/liberty_2294323321101/wlp/lib/org.eclipse.osgi_3.15.0.jar
	at org.eclipse.osgi.framework.util.SecureAction.getZipFile(SecureAction.java:340)
	at org.eclipse.osgi.storage.bundlefile.ZipBundleFile.doOpen(ZipBundleFile.java:48)
	at org.eclipse.osgi.storage.bundlefile.CloseableBundleFile.open(CloseableBundleFile.java:128)
	at org.eclipse.osgi.storage.bundlefile.CloseableBundleFile.lockOpen(CloseableBundleFile.java:77)
	at org.eclipse.osgi.storage.bundlefile.CloseableBundleFile.getEntry(CloseableBundleFile.java:261)
	at org.eclipse.osgi.storage.BundleInfo$Generation.getEntry(BundleInfo.java:397)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.getEntry(EquinoxBundle.java:701)
	at com.ibm.ws.artifact.url.internal.NotABundleResourceURLConnection.getManifestKeyForBundle(NotABundleResourceURLConnection.java:48)
	at com.ibm.ws.artifact.url.internal.NotABundleResourceURLConnection.forgetBundle(NotABundleResourceURLConnection.java:96)
	at com.ibm.ws.artifact.url.internal.URLStreamHandlerServiceImpl.addingBundle(URLStreamHandlerServiceImpl.java:56)
	at com.ibm.ws.artifact.url.internal.URLStreamHandlerServiceImpl.addingBundle(URLStreamHandlerServiceImpl.java:29)
	at org.osgi.util.tracker.BundleTracker$Tracked.customizerAdding(BundleTracker.java:475)
	at org.osgi.util.tracker.BundleTracker$Tracked.customizerAdding(BundleTracker.java:1)
	at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256)
	at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:229)
	at org.osgi.util.tracker.BundleTracker$Tracked.bundleChanged(BundleTracker.java:450)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:973)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151)
	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEventPrivileged(EquinoxEventPublisher.java:235)
	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:141)
	at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:133)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor.publishModuleEvent(EquinoxContainerAdaptor.java:217)
	at org.eclipse.osgi.container.Module.publishEvent(Module.java:498)
	at org.eclipse.osgi.container.Module.doStop(Module.java:656)
	at org.eclipse.osgi.container.Module.stop(Module.java:520)
	at org.eclipse.osgi.container.SystemModule.stop(SystemModule.java:207)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$SystemBundle$EquinoxSystemModule$1.run(EquinoxBundle.java:220)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.nio.file.NoSuchFileException: /home/runner/wlpExtract/liberty_2294323321101/wlp/lib/org.eclipse.osgi_3.15.0.jar
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
	at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:149)
	at java.base/sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
	at java.base/java.nio.file.Files.readAttributes(Files.java:1763)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1225)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:727)
	at java.base/java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:844)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:247)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:177)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:191)
	at org.eclipse.osgi.framework.util.SecureAction.getZipFile(SecureAction.java:322)
	... 28 more
[AUDIT   ] quiesce.begin
[AUDIT   ] CWWKT0017I: Web application removed (default_host): http://localhost:9080/
[AUDIT   ] CWWKZ0009I: The application liberty has stopped successfully.
[AUDIT   ] CWWKT0017I: Web application removed (default_host): http://localhost:9080/metrics/
[AUDIT   ] CWWKT0017I: Web application removed (default_host): http://localhost:9080/health/
[AUDIT   ] CWWKT0017I: Web application removed (default_host): http://localhost:9080/openapi/
[AUDIT   ] CWWKT0017I: Web application removed (default_host): http://localhost:9080/openapi/ui/
[AUDIT   ] CWWKT0017I: Web application removed (default_host): http://localhost:9080/jwt/
[AUDIT   ] CWWKT0017I: Web application removed (default_host): http://localhost:9080/ibm/api/
[AUDIT   ] CWWKE0036I: The server liberty stopped after 12.773 seconds.


```

### PR DESCRIPTION
**Pull request by tjwatson**
Need to be sure the server stop process ends before
deleting the wlp extract folder.  A timeout is not used because we need to still support Java 7 for the wlp.lib.extract project

Fixes #15280

### CODE REVIEW

**Comment by tjwatson** [comment]
#build

**Comment by tjwatson** [comment]
#build

**Review by Emily-Jiang — APPROVED** [review]
LGTM!

**Comment by tjwatson** [comment]
> LGTM!

Thanks @Emily-Jiang I'm doing some more cleanup for this code.  But is there some way to test this change in the MicroProfile Starter GH actions?  Perhaps just in another PR to the starter github project?  Or do we basically need to wait for a Liberty release to test if this fixes the starter GH actions build?

**Comment by tjwatson** [comment]
#build

**Review by hlhoots — APPROVED** [review]
looks good to me pending a clean build.

**Comment by Emily-Jiang** [comment]
> > LGTM!
> 
> Thanks @Emily-Jiang I'm doing some more cleanup for this code. But is there some way to test this change in the MicroProfile Starter GH actions? Perhaps just in another PR to the starter github project? Or do we basically need to wait for a Liberty release to test if this fixes the starter GH actions build?

Unfortunately, I can't test this on MP starter unless you get this into a beta driver. I can then do a PR to get build to use the beta driver instead of the GA driver.

**Comment by Emily-Jiang** [comment]
@tjwatson did you see the latest comment I added to the issue, which is different error message. Is that related to this issue or should I open a different one?

**Comment by tjwatson** [comment]
> @tjwatson did you see the [latest comment](https://github.com/OpenLiberty/open-liberty/issues/15280#issuecomment-743464482) I added to the issue, which is different error message. Is that related to this issue or should I open a different one?

@Emily-Jiang I cannot be certain, but I am pretty confident that it is related.  If I read the latest error you posted correctly, it looks to be class loading issues on shutdown.  I can see how there would be issues loading classes on shutdown if the JARs with the classes that need to load while the server is shutting down.

**Comment by tjwatson** [comment]
#build

**Comment by tjwatson** [comment]
#libby

**Pull request merged**
