### PR TITLE
Fix for Issue #10253: Add Reactive client tests to test Injection

### PR DESCRIPTION
**Pull request by jkoehler22**

### CODE REVIEW

**Comment by jkoehler22** [comment]
#build

**Comment by jkoehler22** [comment]
#build

**Comment by jkoehler22** [comment]
#build

**Comment by jkoehler22** [comment]
#run-libby-bot

**Comment by jkoehler22** [comment]
#build 

Looks like my PB did not complete.

**Comment by wraschke** [comment]
This was reverted due to com.ibm.ws.jaxrs.2.1.cdi.2.0_fat com.ibm.ws.jaxrs21.cdi20.fat.ResourceInfoAtStartupTest.testLoadOnStartupResource1() failing in LAOS continuous builds. See https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_IVUykGh3EeqaXeM8BMnlag, for example:

`junit.framework.AssertionFailedError: 2020-03-18-06:01:12:216 [Unexpected FFDC reporting javax.ejb.EJBException was found (count = 100): /home/jazz_build/_uuzv8Gi5EeqaXeM8BMnlag-EBC.PROD.WASRTC-B24-000-00-00/jbe/build/dev/image/output/wlp/usr/servers/jaxrs21.fat.resourceinfoatstartup/logs/ffdc/ffdc_20.03.18_06.01.08.8.log
>------Start of DE processing------ = [3/18/20, 6:01:08:785 UTC]
>Exception = javax.ejb.EJBException
>Source = com.ibm.ejs.container.BusinessExceptionMappingStrategy.setUncheckedException
>probeid = 506
>Stack Dump = javax.ejb.EJBException: CWNEN0030E: The server was unable to obtain an object instance for the java:comp/env/jdbc/TestDataSource reference.  The exception message was: CWNEN1006E: The server was unable to obtain an object for the jdbc/TestDataSource binding with the javax.sql.DataSource type. The exception message was: java.sql.SQLNonTransientException: DSRA4000E: No implementations of org.apache.derby.jdbc.EmbeddedConnectionPoolDataSource40 are found for dataSource[jdbc/TestDataSource] with library DerbyLib. The name or location of JDBC driver JAR files might be incorrect or inaccessible. Searched in: []. Searched under packages: [org.apache.derby.jdbc].; nested exception is: java.sql.SQLNonTransientException: DSRA4000E: No implementations of org.apache.derby.jdbc.EmbeddedConnectionPoolDataSource40 are found for dataSource[jdbc/TestDataSource] with library DerbyLib. The name or location of JDBC driver JAR files might be incorrect or inaccessible. Searched in: []. Searched under packages: [org.apache.derby.jdbc].
>	at com.ibm.ejs.container.util.ExceptionUtil.EJBException(ExceptionUtil.java:399)
>	at com.ibm.ejs.container.ManagedBeanOBase.injectInstance(ManagedBeanOBase.java:160)
>	at com.ibm.ejs.container.StatelessBeanO.injectInstance(StatelessBeanO.java:275)
>	at com.ibm.ejs.container.StatelessBeanO.initialize(StatelessBeanO.java:159)
>	at com.ibm.ejs.container.BeanOFactory.create(BeanOFactory.java:103)
>	at com.ibm.ejs.container.EJSHome.createBeanO(EJSHome.java:975)
>	at com.ibm.ejs.container.EJSHome.createBeanO(EJSHome.java:1077)
>	at com.ibm.ejs.container.activator.UncachedActivationStrategy.atActivate(UncachedActivationStrategy.java:62)
>	at com.ibm.ejs.container.activator.Activator.preInvokeActivateBean(Activator.java:263)
>	at com.ibm.ejs.container.EJSContainer.preInvokeActivate(EJSContainer.java:3001)
>	at com.ibm.ejs.container.EJSContainer.EjbPreInvoke(EJSContainer.java:2390)
>	at jaxrs21.fat.resourceinfoatstartup.EJSLocalNSLApp_bfd67a9c.getSingletons(EJSLocalNSLApp_bfd67a9c.java)
>	at com.ibm.ws.jaxrs20.server.LibertyJaxRsServerFactoryBean.updateEndpointInfo(LibertyJaxRsServerFactoryBean.java:393)
>	at com.ibm.ws.jaxrs20.server.LibertyJaxRsServerFactoryBean.onApplicationInit(LibertyJaxRsServerFactoryBean.java:192)
>	at com.ibm.ws.jaxrs20.server.LibertyJaxRsServerFactoryBean.doInit(LibertyJaxRsServerFactoryBean.java:280)
>	at com.ibm.ws.jaxrs20.server.JaxRsWebEndpointImpl.init(JaxRsWebEndpointImpl.java:66)
>	at com.ibm.websphere.jaxrs.server.IBMRestServlet.init(IBMRestServlet.java:64)
>	at com.ibm.ws.webcontainer.servlet.ServletWrapper.init(ServletWrapper.java:291)
>	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:584)
>	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:426)
>	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1226)
>	at com.ibm.ws.webcontainer.webapp.WebApp.handleRequest(WebApp.java:5021)
>	at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.handleRequest(DynamicVirtualHost.java:314)
>	at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:1007)
>	at com.ibm.ws.webcontainer.osgi.DynamicVirtualHost$2.run(DynamicVirtualHost.java:279)
>	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink$TaskWrapper.run(HttpDispatcherLink.java:1134)
>	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.wrapHandlerAndExecute(HttpDispatcherLink.java:415)
>	at com.ibm.ws.http.dispatcher.internal.channel.HttpDispatcherLink.ready(HttpDispatcherLink.java:374)
>	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:551)
>	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.handleNewRequest(HttpInboundLink.java:484)
>	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.processRequest(HttpInboundLink.java:346)
>	at com.ibm.ws.http.channel.internal.inbound.HttpInboundLink.ready(HttpInboundLink.java:317)
>	at com.ibm.ws.tcpchannel.internal.NewConnectionInitialReadCallback.sendToDiscriminators(NewConnectionInitialReadCallback.java:167)
>	at com.ibm.ws.tcpchannel.internal.NewConnectionInitialReadCallback.complete(NewConnectionInitialReadCallback.java:75)
>	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.requestComplete(WorkQueueManager.java:504)
>	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.attemptIO(WorkQueueManager.java:574)
>	at com.ibm.ws.tcpchannel.internal.WorkQueueManager.workerRun(WorkQueueManager.java:958)
>	at com.ibm.ws.tcpchannel.internal.WorkQueueManager$Worker.run(WorkQueueManager.java:1047)
>	at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:239)
>	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
>	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
>	at java.base/java.lang.Thread.run(Thread.java:825)
>Caused by: java.sql.SQLNonTransientException: DSRA4000E: No implementations of org.apache.derby.jdbc.EmbeddedConnectionPoolDataSource40 are found for dataSource[jdbc/TestDataSource] with library DerbyLib. The name or location of JDBC driver JAR files might be incorrect or inaccessible. Searched in: []. Searched under packages: [org.apache.derby.jdbc].
>	at com.ibm.ws.jdbc.internal.JDBCDriverService.classNotFound(JDBCDriverService.java:223)
>	at com.ibm.ws.jdbc.internal.JDBCDriverService.create(JDBCDriverService.java:345)
>	at com.ibm.ws.jdbc.internal.JDBCDriverService.createAnyPreferLegacyOrder(JDBCDriverService.java:402)
>	at com.ibm.ws.jdbc.DataSourceService.init(DataSourceService.java:610)
>	at com.ibm.ws.jca.cm.AbstractConnectionFactoryService$2.run(AbstractConnectionFactoryService.java:498)
>	at com.ibm.ws.jca.cm.AbstractConnectionFactoryService$2.run(AbstractConnectionFactoryService.java:495)
>	at java.base/java.security.AccessController.doPrivileged(AccessController.java:703)
>	at com.ibm.ws.jca.cm.AbstractConnectionFactoryService.initPrivileged(AbstractConnectionFactoryService.java:495)
>	at com.ibm.ws.jca.cm.AbstractConnectionFactoryService.createResource(AbstractConnectionFactoryService.java:149)
>	at com.ibm.ws.injectionengine.osgi.internal.IndirectJndiLookupObjectFactory.createResourceWithFilterPrivileged(IndirectJndiLookupObjectFactory.java:383)
>	at com.ibm.ws.injectionengine.osgi.internal.IndirectJndiLookupObjectFactory.access$100(IndirectJndiLookupObjectFactory.java:57)
>	at com.ibm.ws.injectionengine.osgi.internal.IndirectJndiLookupObjectFactory$3.run(IndirectJndiLookupObjectFactory.java:365)
>	at java.base/java.security.AccessController.doPrivileged(AccessController.java:703)
>	at com.ibm.ws.injectionengine.osgi.internal.IndirectJndiLookupObjectFactory.createResourceWithFilter(IndirectJndiLookupObjectFactory.java:362)
>	at com.ibm.ws.injectionengine.osgi.internal.IndirectJndiLookupObjectFactory.createResource(IndirectJndiLookupObjectFactory.java:338)
>	at com.ibm.ws.injectionengine.osgi.internal.IndirectJndiLookupObjectFactory.getObjectInstance(IndirectJndiLookupObjectFactory.java:134)
>	at com.ibm.ws.injectionengine.osgi.internal.IndirectJndiLookupObjectFactory.getObjectInstance(IndirectJndiLookupObjectFactory.java:100)
>	at com.ibm.wsspi.injectionengine.InjectionBinding.getInjectionObjectInstance(InjectionBinding.java:1552)
>	at com.ibm.wsspi.injectionengine.InjectionBinding.getInjectionObject(InjectionBinding.java:1428)
>	at com.ibm.wsspi.injectionengine.InjectionBinding.getInjectableObject(InjectionBinding.java:1368)
>	at com.ibm.wsspi.injectionengine.InjectionTarget.inject(InjectionTarget.java:104)
>	at com.ibm.ws.cdi.impl.managedobject.CDIManagedObject.inject(CDIManagedObject.java:182)
>	at com.ibm.ejs.container.ManagedBeanOBase.injectInstance(ManagedBeanOBase.java:142)
>Caused by: java.lang.ClassNotFoundException: org.apache.derby.jdbc.EmbeddedConnectionPoolDataSource40
>	at com.ibm.ws.classloading.internal.AppClassLoader.findClassCommonLibraryClassLoaders(AppClassLoader.java:557)
>	at com.ibm.ws.classloading.internal.AppClassLoader.findClass(AppClassLoader.java:288)
>	at java.base/java.lang.ClassLoader.loadClassHelper(ClassLoader.java:1134)
>	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1049)
>	at com.ibm.ws.classloading.internal.AppClassLoader.findOrDelegateLoadClass(AppClassLoader.java:535)
>	at com.ibm.ws.classloading.internal.AppClassLoader.loadClass(AppClassLoader.java:495)
>	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1032)
>	at com.ibm.ws.jdbc.internal.JDBCDriverService$1.run(JDBCDriverService.java:271)
>	at com.ibm.ws.jdbc.internal.JDBCDriverService$1.run(JDBCDriverService.java:261)
>	at java.base/java.security.AccessController.doPrivileged(AccessController.java:703)
>	at com.ibm.ws.jdbc.internal.JDBCDriverService.create(JDBCDriverService.java:261)
, Unexpected FFDC reporting java.lang.ClassNotFoundException was found (count = 100): /home/jazz_build/_uuzv8Gi5EeqaXeM8BMnlag-EBC.PROD.WASRTC-B24-000-00-00/jbe/build/dev/image/output/wlp/usr/servers/jaxrs21.fat.resourceinfoatstartup/logs/ffdc/ffdc_20.03.18_06.01.08.0.log`

**Pull request merged**
