### PR TITLE
Test mpTelemetry with checkpoint/restore

### PR DESCRIPTION
**Pull request by anjumfatima90**
#21539

### CODE REVIEW

**Comment by anjumfatima90** [comment]
#build

**Review by tjwatson — DISMISSED** [review]
LGTM

**Comment by anjumfatima90** [comment]
#build

**Comment by anjumfatima90** [comment]
#build

**Comment by anjumfatima90** [comment]
#build

**Comment by anjumfatima90** [comment]
#build

**Comment by anjumfatima90** [comment]
#build

**Comment by anjumfatima90** [comment]
#build

**Comment by anjumfatima90** [comment]
#build

**Review by tjwatson — DISMISSED** [review]

**Review by tjwatson — DISMISSED** [review]

**Comment by anjumfatima90** [comment]
#build

**Comment by anjumfatima90** [comment]
#build

**Review by sebratton — APPROVED** [review]

**Comment by anjumfatima90** [comment]
#libby

**Pull request merged**
