### PR TITLE
Disable usr features

### PR DESCRIPTION
**Pull request by TayyabDev**
disable user features from server installations

### CODE REVIEW

**Comment by Charlotte-Holt** [comment]
I discussed with @TayyabDev that ID will not review this PR, as all necessary changes will be made in #9032 .

**Comment by TayyabDev** [comment]
#build

**Comment by alvinso** [comment]
#run-libby-bot

**Comment by TayyabDev** [comment]
#build

**Comment by TayyabDev** [comment]
#run-libby-bot

**Comment by TayyabDev** [comment]
Build failed due to an unrelated FAT. FeatureUtility fat ran and passed

**Pull request merged**
