### PR TITLE
Changes to deliver staged version of Persistence API 3.2 (i.e. M3)

### PR DESCRIPTION
**Pull request by anija-anil**
Changes to deliver staged version of Persistence API 3.2 (i.e. M3)

### CODE REVIEW

**Comment by anija-anil** [comment]
#build

**Comment by jhanders34** [comment]
#libby

**Comment by tkburroughs** [comment]
#libby

**Comment by anija-anil** [comment]
#libby
#build

**Review by tkburroughs — APPROVED** [review]

**Pull request merged**
