### PR TITLE
Update AnnotationScanner to take into consideration excluded packages…

### PR DESCRIPTION
**Pull request by anton-balaniuc**
… and classes

For example when
mp.openapi.scan.exclude.packages=[com.example.excluded]
AnnotationScanner still uses Application classes from that package:
com.ibm.ws.microprofile.openapi.AnnotationScanner            1 Found application classes:
[com.example.demo.DemoRestApplication, com.example.excluded.DemoRestApplication]

However `com.example.excluded.DemoRestApplication` should not be processed by openApiScanner

Signed-off-by: Anton Balaniuc anton.balaniuc@gmail.com

OpenLiberty Pull Requester,

ATTENTION, READ THIS: Updated 4/11/2018 - Read and understand this completely,
then delete this entire template. If a reviewer or merger sees this template,
they should fail the review or merge.

If this code change is fixing a user-visible bug in previously released code, it MUST
have an associated issue mentioned in the PR text or description. That Issue also
MUST be labelled “release bug”

This directs automation to scrape this fix for inclusion in the next release's
list of bugs fixed.

If this code is NOT for fixing a released bug, for example new function, fixing
a bug in unreleased function, or other improvements that do not affect the
user-space, no label is needed. An issue could or could not be used based
on the developer’s discretion, but do still delete this text block.

For full details, please see this wiki page:

https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions

### CODE REVIEW

**Comment by anton-balaniuc** [comment]
related issue: https://github.com/OpenLiberty/open-liberty/issues/9483

**Comment by leochr** [comment]
@anton-balaniuc Following up to see if you had a chance to review my previous comment or if you have any questions. 

Please let me know if you are busy with other items and would like me to make the suggested changes. Thank you!

**Comment by anton-balaniuc** [comment]
@leochr, I am happy to do this change.  If this is not urgent I will submit PR by the end of the week.

**Comment by anton-balaniuc** [comment]
@leochr Can you please review it one more time?

**Comment by leochr** [comment]
@anton-balaniuc Thanks for making the changes. Looks good to me. One minor thing. In ApplicationProcessor.java, please update the copyright header (from `2017, 2018` to `2017, 2019`)

**Comment by leochr** [comment]
@arturdzm Could you please review as well? just want to make sure we didn't miss anything.

**Comment by leochr** [comment]
@anton-balaniuc Please confirm that you've tested the scenario you reported as the issue is now resolved with these changes. Thanks.

**Comment by leochr** [comment]
#build

**Comment by anton-balaniuc** [comment]
@leochr header information has been updated. 

As well I have tested the change:
```
mp.openapi.scan.exclude.packages=io.openliberty.guides.system
```
and output from `trace.log`:
```
Found application classes:
[io.openliberty.guides.inventory.InventoryApplication, io.openliberty.guides.system.SystemApplication]

Application classes after filtering:
[io.openliberty.guides.inventory.InventoryApplication]
```

**Comment by leochr** [comment]
#build

**Comment by anton-balaniuc** [comment]
Hi @leochr, can this be merged, or do I need to add/fix anything else?

**Comment by leochr** [comment]
Thank you @anton-balaniuc 

@arturdzm please review. Thanks.

**Comment by arturdzm** [comment]
#libby-bot

**Pull request merged**
