### PR TITLE
Sebratton/error pages

### PR DESCRIPTION
**Pull request by sebratton**
OpenLiberty Pull Requester,

### CODE REVIEW

**Comment by sebratton** [comment]
#build

**Comment by sebratton** [comment]
#build

**Comment by tjwatson** [comment]
This is for #2483

**Comment by tjwatson** [comment]
#build

**Comment by tjwatson** [comment]
#build

**Comment by sebratton** [comment]
#build

**Comment by tjwatson** [comment]
#build

**Pull request merged**
