### PR TITLE
rename LibertyResteasyEndpointIntrospector

### PR DESCRIPTION
**Pull request by WhiteCat22**
Renaming our Resteasy endpoint dump introspector

### CODE REVIEW

**Review by jim-krueger — APPROVED** [review]

**Comment by WhiteCat22** [comment]
#build #run-libby-bot

**Review by andymc12 — CHANGES_REQUESTED** [review]
I don't think this will actually change the filename of the introspector output.  I think you'll need to make the change to this method:
```
    @Override
    public String getIntrospectorName() {
        return "LibertyResteasyEndpointIntrospector";
    }
```

**Review by jim-krueger — APPROVED** [review]

**Review by andymc12 — APPROVED** [review]
LGTM

**Comment by WhiteCat22** [comment]
#build #run-libby-bot

**Pull request merged**
