### PR TITLE
Port changes from WS-CD-Open that were made between when I moved the …

### PR DESCRIPTION
**Pull request by jvanhill**
…oidc.client_fat project to OL and before I could remove the same project from WS-CD-Open.

### CODE REVIEW

**Comment by jvanhill** [comment]
#build

**Comment by jvanhill** [comment]
#build

**Review by kristip17 — APPROVED** [review]

**Comment by jvanhill** [comment]
The lone test failure is an known issue.

**Comment by jvanhill** [comment]
#libby

**Pull request merged**
