### PR TITLE
Update LDAP used by SAML FATs

### PR DESCRIPTION
**Pull request by c00crane**
I'm updating the in-memory LDAP server used by the SAML tests.  We're having problems with the LDAP server when the tests run on z/OS and we're using Java 17.
The LDAP server starts and runs fine.  The tests run successfully, but, the shutdown is hanging.  It will hang for almost 3 hours and the test framework will shut the tests down.
```
[08/07/2023 21:12:30:986 EDT] 001 LargeProjectRepeatActions      createLargeProjectRepeats      I OS: ZOS
[08/07/2023 21:12:31:028 EDT] 001 JavaInfo                       <init>                         I major=17,  minor=0, service release=0, fixpack=0,  vendor=IBM,  javaHome=/WebSphere/Misc/jazz_build/jbe_flash067/jazz/buildsystem/buildengine/eclipse/jvms/SDK8_64bit_SR5_FP25, criuSupported=Optional.empty
[08/07/2023 21:12:31:030 EDT] 001 TestModeFilter                 <clinit>                       I System property: fat.test.mode is full running in test mode FULL
[08/07/2023 21:12:31:030 EDT] 001 LargeProjectRepeatActions      createLargeProjectRepeats      I Enabling the EE10 test instance (Not on Windows, Java > 8, FULL Mode)
[08/07/2023 21:12:31:078 EDT] 001 FeatureFilter                  <clinit>                       I System property: fat.test.feature.under.test is security.saml.sso
[08/07/2023 21:12:31:078 EDT] 001 JavaLevelFilter                <clinit>                       I System property: fat.test.feature.under.test is security.saml.sso
[08/07/2023 21:12:31:079 EDT] 001 FATRunner                      <clinit>                       I Is this FAT running locally?  fat.test.localrun=false
[08/07/2023 21:12:31:079 EDT] 001 FATRunner                      <clinit>                       I Using filters [componenttest.custom.junit.runner.TestModeFilter@592dabb6, componenttest.custom.junit.runner.TestNameFilter@ba83cab1, componenttest.custom.junit.runner.FeatureFilter@2f1bf696, componenttest.custom.junit.runner.SystemPropertyFilter@1a57091e, componenttest.custom.junit.runner.JavaLevelFilter@30922dec, componenttest.custom.junit.runner.CheckpointSupportFilter@74efcfe4]
[08/07/2023 21:12:31:249 EDT] 001 CompositeRepeatTestActionState evaluate                       I All tests attempt to run 1 times:
[08/07/2023 21:12:31:250 EDT] 001 CompositeRepeatTestActionState evaluate                       I   [0] JakartaEE10 FAT repeat action
[08/07/2023 21:12:31:250 EDT] 001 CompositeRepeatTestActionState evaluate                       I ===================================
[08/07/2023 21:12:31:250 EDT] 001 CompositeRepeatTestActionState evaluate                       I 
[08/07/2023 21:12:31:250 EDT] 001 CompositeRepeatTestActionState evaluate                       I Running tests with action: JakartaEE10 FAT repeat action
[08/07/2023 21:12:31:250 EDT] 001 CompositeRepeatTestActionState evaluate                       I 
[08/07/2023 21:12:31:251 EDT] 001 CompositeRepeatTestActionState evaluate                       I ===================================
...
[08/07/2023 21:19:28:502 EDT] 001 CommonLocalLDAPServerSuite     ldapTearDown                   I Stopping Local LDAP service
```
The tests timeout at 3 hours.

### CODE REVIEW

**Comment by c00crane** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.security.saml.sso_fat,com.ibm.ws.security.saml.sso_fat.jaxrs,com.ibm.ws.security.saml.sso_fat.2,com.ibm.ws.security.saml.sso_fat.jaxrs.config,com.ibm.ws.security.saml.sso_fat.3,com.ibm.ws.security.saml.sso_fat.logout,com.ibm.ws.security.saml.sso_fat.common,com.ibm.ws.security.saml.sso_fat.logout.IDP_initiated,com.ibm.ws.security.saml.sso_fat.config,com.ibm.ws.security.saml.sso_fat.logout.httpServletRequest,com.ibm.ws.security.saml.sso_fat.config.mapToUserRegistry,com.ibm.ws.security.saml.sso_fat.logout.ibm_security_logout,com.ibm.ws.security.saml.sso_fat.endpoint.samlmetadata

**Comment by c00crane** [comment]
#libby
#build
#spawn.fullfat.buckets=com.ibm.ws.security.saml.sso_fat,com.ibm.ws.security.saml.sso_fat.jaxrs,com.ibm.ws.security.saml.sso_fat.2,com.ibm.ws.security.saml.sso_fat.jaxrs.config,com.ibm.ws.security.saml.sso_fat.3,com.ibm.ws.security.saml.sso_fat.logout,com.ibm.ws.security.saml.sso_fat.common,com.ibm.ws.security.saml.sso_fat.logout.IDP_initiated,com.ibm.ws.security.saml.sso_fat.config,com.ibm.ws.security.saml.sso_fat.logout.httpServletRequest,com.ibm.ws.security.saml.sso_fat.config.mapToUserRegistry,com.ibm.ws.security.saml.sso_fat.logout.ibm_security_logout,com.ibm.ws.security.saml.sso_fat.endpoint.samlmetadata

**Comment by c00crane** [comment]
https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_A3UwsEDuEe6Z3JPws1j0ig

**Comment by c00crane** [comment]
#libby
#build
#spawn.fullfat.buckets=com.ibm.ws.security.saml.sso_fat,com.ibm.ws.security.saml.sso_fat.jaxrs,com.ibm.ws.security.saml.sso_fat.2,com.ibm.ws.security.saml.sso_fat.jaxrs.config,com.ibm.ws.security.saml.sso_fat.3,com.ibm.ws.security.saml.sso_fat.logout,com.ibm.ws.security.saml.sso_fat.common,com.ibm.ws.security.saml.sso_fat.logout.IDP_initiated,com.ibm.ws.security.saml.sso_fat.config,com.ibm.ws.security.saml.sso_fat.logout.httpServletRequest,com.ibm.ws.security.saml.sso_fat.config.mapToUserRegistry,com.ibm.ws.security.saml.sso_fat.logout.ibm_security_logout,com.ibm.ws.security.saml.sso_fat.endpoint.samlmetadata,com.ibm.ws.wssecurity_fat.wsscxf.saml.1,com.ibm.ws.wssecurity_fat.wsscxf.saml.2,com.ibm.ws.wssecurity_fat.wsscxf.saml.3,com.ibm.ws.wssecurity_fat.wsscxf.saml.5,com.ibm.ws.wssecurity_fat.wsscxf.saml.6

**Comment by c00crane** [comment]
#libby
#spawn.fullfat.buckets=com.ibm.ws.security.saml.sso_fat.jaxrs,com.ibm.ws.wssecurity_fat.wsscxf.saml.6,com.ibm.ws.wssecurity_fat.wsscxf.saml.3,com.ibm.ws.security.saml.sso_fat.jaxrs.config,com.ibm.ws.security.saml.sso_fat.endpoint.samlmetadata,com.ibm.ws.security.saml.sso_fat.config,com.ibm.ws.wssecurity_fat.wsscxf.saml.1,com.ibm.ws.security.saml.sso_fat.3,com.ibm.ws.security.saml.sso_fat.2,com.ibm.ws.wssecurity_fat.wsscxf.saml.5,com.ibm.ws.security.saml.sso_fat.logout.IDP_initiated,com.ibm.ws.security.saml.sso_fat.logout.httpServletRequest,com.ibm.ws.wssecurity_fat.wsscxf.saml.2,com.ibm.ws.security.saml.sso_fat.logout.ibm_security_logout,com.ibm.ws.security.saml.sso_fat.config.mapToUserRegistry,com.ibm.ws.security.saml.sso_fat.logout,com.ibm.ws.security.saml.sso_fat,com.ibm.ws.security.saml.sso_fat.jaxrs,com.ibm.ws.security.saml.sso_fat.2,com.ibm.ws.security.saml.sso_fat.jaxrs.config,com.ibm.ws.security.saml.sso_fat.3,com.ibm.ws.security.saml.sso_fat.logout,com.ibm.ws.security.saml.sso_fat.logout.IDP_initiated,com.ibm.ws.security.saml.sso_fat.config,com.ibm.ws.security.saml.sso_fat.logout.httpServletRequest,com.ibm.ws.security.saml.sso_fat.config.mapToUserRegistry,com.ibm.ws.security.saml.sso_fat.logout.ibm_security_logout,com.ibm.ws.security.saml.sso_fat.endpoint.samlmetadata,com.ibm.ws.wssecurity_fat.wsscxf.saml.1,com.ibm.ws.wssecurity_fat.wsscxf.saml.2,com.ibm.ws.wssecurity_fat.wsscxf.saml.3,com.ibm.ws.wssecurity_fat.wsscxf.saml.5,com.ibm.ws.wssecurity_fat.wsscxf.saml.6,com.ibm.ws.security.oauth_fat,com.ibm.ws.security.oidc.client_fat.1,com.ibm.ws.security.oidc.client_fat.2,com.ibm.ws.security.oidc.client_fat.claimPropagation,com.ibm.ws.security.social_fat.LibertyOP.claimPropagation

**Comment by c00crane** [comment]
#libby
#build
#spawn.fullfat.buckets=com.ibm.ws.security.saml.sso_fat.jaxrs,com.ibm.ws.wssecurity_fat.wsscxf.saml.6,com.ibm.ws.wssecurity_fat.wsscxf.saml.3,com.ibm.ws.security.saml.sso_fat.jaxrs.config,com.ibm.ws.security.saml.sso_fat.endpoint.samlmetadata,com.ibm.ws.security.saml.sso_fat.config,com.ibm.ws.wssecurity_fat.wsscxf.saml.1,com.ibm.ws.security.saml.sso_fat.3,com.ibm.ws.security.saml.sso_fat.2,com.ibm.ws.wssecurity_fat.wsscxf.saml.5,com.ibm.ws.security.saml.sso_fat.logout.IDP_initiated,com.ibm.ws.security.saml.sso_fat.logout.httpServletRequest,com.ibm.ws.wssecurity_fat.wsscxf.saml.2,com.ibm.ws.security.saml.sso_fat.logout.ibm_security_logout,com.ibm.ws.security.saml.sso_fat.config.mapToUserRegistry,com.ibm.ws.security.saml.sso_fat.logout,com.ibm.ws.security.saml.sso_fat,com.ibm.ws.security.saml.sso_fat.jaxrs,com.ibm.ws.security.saml.sso_fat.2,com.ibm.ws.security.saml.sso_fat.jaxrs.config,com.ibm.ws.security.saml.sso_fat.3,com.ibm.ws.security.saml.sso_fat.logout,com.ibm.ws.security.saml.sso_fat.logout.IDP_initiated,com.ibm.ws.security.saml.sso_fat.config,com.ibm.ws.security.saml.sso_fat.logout.httpServletRequest,com.ibm.ws.security.saml.sso_fat.config.mapToUserRegistry,com.ibm.ws.security.saml.sso_fat.logout.ibm_security_logout,com.ibm.ws.security.saml.sso_fat.endpoint.samlmetadata,com.ibm.ws.wssecurity_fat.wsscxf.saml.1,com.ibm.ws.wssecurity_fat.wsscxf.saml.2,com.ibm.ws.wssecurity_fat.wsscxf.saml.3,com.ibm.ws.wssecurity_fat.wsscxf.saml.5,com.ibm.ws.wssecurity_fat.wsscxf.saml.6,com.ibm.ws.security.oauth_fat,com.ibm.ws.security.oidc.client_fat.1,com.ibm.ws.security.oidc.client_fat.2,com.ibm.ws.security.oidc.client_fat.claimPropagation,com.ibm.ws.security.social_fat.LibertyOP.claimPropagation

**Review by arunavemulapalli — APPROVED** [review]

**Pull request merged**
