### PR TITLE
Update Persistence 3.0.0 to EclipseLink 3.0.2

### LINKED ISSUE #17025: [JPA 3.0] EclipseLink: Deliver Bug #570378
Update JPA 3.0 to fix EclipseLink bug [570378](https://bugs.eclipse.org/bugs/show_bug.cgi?id=570378)

### PR DESCRIPTION
**Pull request by dazey3**
fixes #17025
for #15956
for #17019
for #17021
for #17023
for #17027
for #17029
for #17367
for #17371
for #17374
for #17409

Signed-off-by: Will Dazey <dazeydev.3@gmail.com>

### CODE REVIEW

**Comment by dazey3** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jpa.tests.spec10.embeddable_fat,com.ibm.ws.jpa_22_fat,com.ibm.ws.jpa_30_fat,com.ibm.ws.jpa_eclipselink_fat,com.ibm.ws.jpa_ol_fat,com.ibm.ws.jpa_spec10_query_fat,com.ibm.ws.jpa_spec20_fat,com.ibm.ws.jpa.tests.spec10.callback_fat,com.ibm.ws.jpa.tests.spec10.entitymanager_fat,com.ibm.ws.jpa.tests.spec10.inheritance_fat,com.ibm.ws.jpa.tests.spec10.issues_fat,com.ibm.ws.jpa.tests.spec10.relationships.manyXmany_fat,com.ibm.ws.jpa.tests.spec10.relationships.manyXone_fat,com.ibm.ws.jpa.tests.spec10.relationships.oneXmany_fat,com.ibm.ws.jpa.tests.spec10.relationships.oneXone_fat,com.ibm.ws.jpa.tests.spec20.lock_fat,com.ibm.ws.jpa.tests.spec21.cdi_fat,com.ibm.ws.jpa.tests.spec21.issues_fat,com.ibm.ws.jpa.tests.spec21.txsynchronization_fat

**Review by jgrassel — DISMISSED** [review]

**Comment by dazey3** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jpa.tests.spec10.query,com.ibm.ws.jpa_eclipselink_fat,com.ibm.ws.jpa_spec20_fat

**Comment by dazey3** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jpa.tests.spec10.query,com.ibm.ws.jpa_eclipselink_fat,com.ibm.ws.jpa_spec20_fat

**Comment by dazey3** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jpa.tests.spec10.query,com.ibm.ws.jpa_eclipselink_fat,com.ibm.ws.jpa_spec20_fat

**Review by jgrassel — APPROVED** [review]
lgtm

**Comment by dazey3** [comment]
#run-libby-bot

**Pull request merged**
