### PR TITLE
JWKS containing a JWK with the x5c-attribute is now correctly parsed …

### PR DESCRIPTION
**Pull request by danpfe**
…and no longer fails the initialization of the MP-JWT-feature. See issue https://github.com/OpenLiberty/open-liberty/issues/3921.

### CODE REVIEW

**Comment by danpfe** [comment]
Hi @LibbyBot ( and all others ;) ). Code was tested using a new unit test and by building a release and verifying whether my application using MP-JWT (pointing to a JWKS URL containing amongst others a JWK with the "x5c"-attribute) works.

**Comment by aguibert** [comment]
Hi @danpfe, thanks for the PR!  The code changes look reasonable so I will submit a #build on your behalf that will run the full pipeline of automated functional testing.

I'll defer the official code review to someone on the security team such as @chunlongliang-ibm .

**Comment by aguibert** [comment]
Sorry, guess I can't submit the build yet since the CLA has not been processed yet.  Can you please re-open the PR once your CLA has been processed?

**Comment by danpfe** [comment]
Uhm,... ok, guess so.

**Pull request closed without merging**
