### PR TITLE
Reduce testcontainer starts

### PR DESCRIPTION
**Pull request by jonhawkes**
#build

### CODE REVIEW

**Comment by jonhawkes** [comment]
#libby #build

**Review by neilgsyoung — APPROVED** [review]
Looks good

**Comment by jonhawkes** [comment]
#build

**Comment by jonhawkes** [comment]
#libby

**Comment by jonhawkes** [comment]
#build

**Comment by jonhawkes** [comment]
#pbbeta

**Comment by wraschke** [comment]
#pbbeta@dev

**Comment by wraschke** [comment]
#pbbeta@dev

**Pull request merged**
