### PR TITLE
Use j.u.logging in Yoko for verbose logging

### LINKED ISSUE #14843: JNDI IIOP lookup fails with Yoko error "Release called on unknown client"
[20/10/29 11:40:18:503 JST] 0000a74a id=00000000 org.apache.yoko.orb.CORBA.Delegate                           1 Received unexpected exception for request
org.apache.yoko.orb.OB.AssertionFailed: Yoko encountered an internal error Release called on unknown client
	at org.apache.yoko.orb.OB.Assert.fail(Assert.java:22)
	at org.apache.yoko.orb.OB.ClientManager.releaseClient(ClientManager.java:428)
	at org.apache.yoko.orb.OB.DowncallStub.handleFailureException(DowncallStub.java:369)
	at org.apache.yoko.orb.OB.DowncallStub.invoke(DowncallStub.java:662)
	at org.apache.yoko.orb.CORBA.Delegate.invoke(Delegate.java:462)
	at org.apache.yoko.orb.CORBA.Delegate.is_a(Delegate.java:311)
	at org.omg.CORBA.portable.ObjectImpl._is_a(ObjectImpl.java:56)
	at com.ibm.ws.jndi.iiop.OrbContext.lookup(OrbContext.java:56)
	at org.apache.aries.jndi.DelegateContext.lookup(DelegateContext.java:161)
	at javax.naming.InitialContext.lookup(InitialContext.java:428)
	…

### LINKED ISSUE #14903: NPE from cache in Yoko after connection failure
The stack trace will look something like this:
java.lang.NullPointerException
-	at org.apache.yoko.util.concurrent.ReferenceCountedCache.remove(ReferenceCountedCache.java:107)
-	at org.apache.yoko.orb.OB.GIOPConnection.processException(GIOPConnection.java:691)
-	at org.apache.yoko.orb.OB.GIOPConnectionThreaded.refresh(GIOPConnectionThreaded.java:679)
-	at org.apache.yoko.orb.OB.Connection$State$3.applyTo(Connection.java:56)
-	at org.apache.yoko.orb.OB.Connection.setState(Connection.java:132)
-	at org.apache.yoko.orb.OB.GIOPConnection.destroy(GIOPConnection.java:1021)
-	at org.apache.yoko.orb.OB.ORBInstance$1.clean(ORBInstance.java:39)
-	at org.apache.yoko.orb.OB.ORBInstance$1.clean(ORBInstance.java:36)
-	at org.apache.yoko.util.concurrent.ReferenceCountedCache.clean(ReferenceCountedCache.java:128)
-	at org.apache.yoko.orb.OB.GIOPClient.reuseOrCreateOutboundConnection(GIOPClient.java:152)
-	at org.apache.yoko.orb.OB.GIOPClient.getWorker(GIOPClient.java:127)

### LINKED ISSUE #15153: Use java.util.logging for verbose logging in Yoko
Replaces an obscure properties-based configuration mechanism in Yoko with a standardized system using java.util.logging

### LINKED ISSUE #15310: NullPointerException from Yoko CodeBaseProxy.getCodeBase()
`java.lang.NullPointerException at org.apache.yoko.orb.OB.CodeBaseProxy.getCodeBase(CodeBaseProxy.java:100)`

This can arise when there is a race condition between two threads calling `getCodeBase()` for the first time. The initialization of an instance field is driven lazily. If both threads attempt to initialize the field, one thread may set a (different) field to `null` just before the other thread attempts to dereference the other field.

The fix for this is to make the lazily initialized field `volatile` and to `synchronize` on an internal lock object around the initialization of the field. This ensures that the race condition never arises.

### PR DESCRIPTION
**Pull request by ngmr**
Fixes #14843 
Fixes #14903 
Fixes #15153 
Fixes #15310

### CODE REVIEW

**Comment by ngmr** [comment]
#build

**Comment by ngmr** [comment]
#build

**Comment by ngmr** [comment]
#build

**Comment by ngmr** [comment]
#build

**Review by chackoj — APPROVED** [review]
Superlative work

**Pull request closed without merging**
