### PR TITLE
cleanup customerFormAuth handleFormLogin method

### PR DESCRIPTION
**Pull request by Zech-Hein**
Follow up changes for: https://github.com/OpenLiberty/open-liberty/issues/23310

### CODE REVIEW

**Comment by Zech-Hein** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.security.javaeesec_fat,com.ibm.ws.security.javaeesec_fat.2,com.ibm.ws.security.javaeesec_fat.3,com.ibm.ws.security.javaeesec_fat.4,com.ibm.ws.security.jaspic_fat,com.ibm.ws.security.jaspic.jakarta10_fat,io.openliberty.security.jakartasec.3.0.internal_fat, io.openliberty.security.jakartasec.3.0.internal_fat.config

**Comment by Zech-Hein** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.security.javaeesec_fat,com.ibm.ws.security.javaeesec_fat.2,com.ibm.ws.security.javaeesec_fat.3,com.ibm.ws.security.javaeesec_fat.4,com.ibm.ws.security.jaspic_fat,com.ibm.ws.security.jaspic.jakarta10_fat,io.openliberty.security.jakartasec.3.0.internal_fat, io.openliberty.security.jakartasec.3.0.internal_fat.config

**Comment by Zech-Hein** [comment]
#libby

**Review by utle — APPROVED** [review]

**Comment by Zech-Hein** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.security.javaeesec_fat,com.ibm.ws.security.javaeesec_fat.2,com.ibm.ws.security.javaeesec_fat.3,com.ibm.ws.security.javaeesec_fat.4,com.ibm.ws.security.jaspic_fat,com.ibm.ws.security.jaspic.jakarta10_fat,io.openliberty.security.jakartasec.3.0.internal_fat, io.openliberty.security.jakartasec.3.0.internal_fat.config

**Pull request merged**
