### PR TITLE
Translate noProxyHost list to regex format

### LINKED ISSUE #20403: LibertyRestClientBuilderImpl nonProxyHosts PatternSyntaxException
It seems that in the LibertyRestClientBuilderImpl [here](https://github.com/OpenLiberty/open-liberty/blame/1927e381f0682fc85d02c1cabcf4959af35c3868/dev/io.openliberty.org.jboss.resteasy.mprestclient/src/org/jboss/resteasy/microprofile/client/ot/LibertyRestClientBuilderImpl.java#L325) it is assumed that the nonProxyHosts are a regex patterns, but they are actually not as they can contain * as wildcards. (See doc https://docs.oracle.com/javase/8/docs/technotes/guides/net/proxies.html)
This results in an exception when my nonproxyHosts are parsed there, see example below:

When running with these nonProxyHosts: -Dhttp.nonProxyHosts="*.svc|*.cluster.local|localhost|127.0.0.1"

it results in following exception:

java.util.regex.PatternSyntaxException: Dangling meta character '*' near index 0
*.svc
^
	at java.base/java.util.regex.Pattern.error(Pattern.java:2028)
	at java.base/java.util.regex.Pattern.sequence(Pattern.java:2203)
	at java.base/java.util.regex.Pattern.expr(Pattern.java:2069)
	at java.base/java.util.regex.Pattern.compile(Pattern.java:1783)
	at java.base/java.util.regex.Pattern.<init>(Pattern.java:1430)
	at java.base/java.util.regex.Pattern.compile(Pattern.java:1069)
	at org.jboss.resteasy.microprofile.client.ot.LibertyRestClientBuilderImpl.build(LibertyRestClientBuilderImpl.java:325)
	at org.jboss.resteasy.microprofile.client.RestClientDelegateBean.create(RestClientDelegateBean.java:129)
	at org.jboss.weld.contexts.unbound.DependentContextImpl.get(DependentContextImpl.java:64)
	at org.jboss.weld.bean.ContextualInstanceStrategy$DefaultContextualInstanceStrategy.get(ContextualInstanceStrategy.java:100)
	at org.jboss.weld.bean.ContextualInstance.get(ContextualInstance.java:50)
	at org.jboss.weld.manager.BeanManagerImpl.getReference(BeanManagerImpl.java:694)
	at org.jboss.weld.manager.BeanManagerImpl.getInjectableReference(BeanManagerImpl.java:794)
	at org.jboss.weld.injection.FieldInjectionPoint.inject(FieldInjectionPoint.java:92)
	at org.jboss.weld.util.Beans.injectBoundFields(Beans.java:345)
	at org.jboss.weld.util.Beans.injectFieldsAndInitializers(Beans.java:356)
	at org.jboss.weld.injection.producer.ResourceInjector$1.proceed(ResourceInjector.java:69)
	at com.ibm.ws.cdi.impl.weld.injection.WebSphereInjectionServicesImpl$3.run(WebSphereInjectionServicesImpl.java:323)
	at com.ibm.ws.cdi.impl.weld.injection.WebSphereInjectionServicesImpl$3.run(WebSphereInjectionServicesImpl.java:320)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at com.ibm.ws.cdi.impl.weld.injection.WebSphereInjectionServicesImpl.aroundInject(WebSphereInjectionServicesImpl.java:320)
	at org.jboss.weld.injection.InjectionContextImpl.run(InjectionContextImpl.java:46)

I have experienced same issue in resteasy, which was fixed here:

https://github.com/resteasy/resteasy-microprofile/pull/9/commits/9e9b1524fbb22dfc2a6794672dcc2455e46e81a4

### PR DESCRIPTION
**Pull request by jim-krueger**
Fixes #20403

### CODE REVIEW

**Comment by jim-krueger** [comment]
#build

**Comment by jim-krueger** [comment]
#build

**Comment by jim-krueger** [comment]
This change is a port of a fix included in RestEasy via [https://github.com/resteasy/resteasy-microprofile/pull/9](https://github.com/resteasy/resteasy-microprofile/pull/9)

**Review by WhiteCat22 — APPROVED** [review]

**Comment by jim-krueger** [comment]
This change was tested by adding the jvm.options file to the server for the com.ibm.ws.microprofile.rest.client.fat.BasicTest.    This testcase was chosen relatively at random.   Without this change, the added jvm.options would cause the test to fail in a similar fashion to the failure documented in the #20403.

**Review by jhanders34 — APPROVED** [review]

**Comment by jim-krueger** [comment]
#build

**Comment by jim-krueger** [comment]
#build

**Comment by jim-krueger** [comment]
#run-libby-bot

**Comment by jim-krueger** [comment]
Test failure is unrelated to change.  Merging.

**Pull request merged**
