### PR TITLE
Bruce add jwtsso component take2

### PR DESCRIPTION
**Pull request by brutif**

### CODE REVIEW

**Comment by brutif** [comment]
#build

**Comment by brutif** [comment]
fix schemaval errors and, drumroll, 
#build

**Comment by bsbyrd1** [comment]
Looks like this properties file needs review: dev/com.ibm.ws.security.jwtsso/resources/OSGI-INF/l10n/metatype.properties

**Comment by brutif** [comment]
still weird unrelated failures in build.im.zip.offering.  merge with integration and spin again
#build

**Comment by brutif** [comment]
change feature kind to noship
#build

**Comment by brutif** [comment]
pb is good

**Comment by lzdanski** [comment]
@brutif ID changes look good!

**Pull request merged**
