### PR TITLE
changes to handling LTPAToken2 

### LINKED ISSUE #21973: Expiration fields are not compared in an LTPA Token
**Describe the bug**  
When there are two expiration times present in an LTPA token, the times should be compared to be within an acceptable difference.

**Steps to Reproduce**  
Behavior is always present with LTPA token usage.

**Expected behavior**  
Liberty should reject LTPA tokens when the two expiration times in the token are not within an acceptable difference by throwing an invalidTokenException.

**Diagnostic information:**  
 - OpenLiberty Version: 17.0.0.3 - 22.0.0.8
 - Affected feature(s): appSecurity-2.0, appSecurity-3.0
 - Java Version: all

### PR DESCRIPTION
**Pull request by Zech-Hein**
Fixes https://github.com/OpenLiberty/open-liberty/issues/21973

### CODE REVIEW

**Comment by Zech-Hein** [comment]
#build

**Comment by Zech-Hein** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.security.acme_fat,com.ibm.ws.security.auth.data_fat,com.ibm.ws.security.authentication.filter_fat,com.ibm.ws.security.client_fat,com.ibm.ws.security.jaspic_fat,com.ibm.ws.security.javaeesec_fat,com.ibm.ws.security.javaeesec_fat.2,com.ibm.ws.security.javaeesec_fat.3,com.ibm.ws.security.mp.jwt_fat_tck,com.ibm.ws.security.oauth_fat,com.ibm.ws.security.oidc.client_fat.1,com.ibm.ws.security.oidc.client_fat.2,com.ibm.ws.security.oidc.client_fat.jaxrs

**Comment by Zech-Hein** [comment]
rebuilding with latest updates
#build

**Comment by Zech-Hein** [comment]
#libby

**Comment by Zech-Hein** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.security.acme_fat,com.ibm.ws.security.auth.data_fat,com.ibm.ws.security.authentication.filter_fat,com.ibm.ws.security.client_fat,com.ibm.ws.security.jaspic_fat,com.ibm.ws.security.javaeesec_fat,com.ibm.ws.security.javaeesec_fat.2,com.ibm.ws.security.javaeesec_fat.3,com.ibm.ws.security.mp.jwt_fat_tck,com.ibm.ws.security.oauth_fat,com.ibm.ws.security.oidc.client_fat.1,com.ibm.ws.security.oidc.client_fat.2,com.ibm.ws.security.oidc.client_fat.jaxrs

**Comment by Zech-Hein** [comment]
the failure on the last build is unrelated to the changes in the PR. The test results look good.

**Review by arkarkala — APPROVED** [review]

**Review by utle — APPROVED** [review]

**Pull request merged**
