### PR TITLE
Rename eeCompatible-9.0 feature to javaeeCompatible-9.0

### PR DESCRIPTION
**Pull request by tjwatson**
Temporary change until we rename all javaeeCompatible features.

Also enable JDBC 4.3 FAT for testing with jakarta 9.

### CODE REVIEW

**Comment by tjwatson** [comment]
#build

**Comment by tjwatson** [comment]
#build

**Comment by tjwatson** [comment]
#build

**Comment by tjwatson** [comment]
#run-libby-bot

**Comment by tkburroughs** [comment]
#run-libby-bot

**Comment by wraschke** [comment]
#libby

**Pull request merged**
