### PR TITLE
wsoc fvt: All the buckets need to join the server stop delay party

### PR DESCRIPTION
**Pull request by billw1024**

### CODE REVIEW

**Comment by billw1024** [comment]
fixes #15190

**Comment by billw1024** [comment]
#build #spawn.fullfat.buckets=io.openliberty.wsoc.internal_fat

**Review by isaacrivriv — APPROVED** [review]
Looks good! Thanks for the fixes!

**Comment by billw1024** [comment]
#build #spawn.fullfat.buckets=io.openliberty.wsoc.internal_fat

**Pull request merged**
