### PR TITLE
Update jandex to 2.4.0 and smallrye-open-api to 2.1.15

### LINKED ISSUE #17972: `@Schema(multipleOf = )` can throw `NumberFormatException` in `mpOpenAPI-2.0` feature
I'm trying to use attribue `multipleOf` of `@org.eclipse.microprofile.openapi.annotations.media.Schema` but I've found some minor bugs.

(in all cases the field I'm annotating with `@Schema` is a `BigDecimal` field)

**With `multipleOf = 1`, then upon application deploy the server shows:**

> [INFO] [ERROR   ] CWWKO1650E: Validation of the OpenAPI document produced the following error(s):
> [INFO]
> [INFO]  - Message: The Schema Object must have the "multipleOf" property set to a number strictly greater than zero, Location: #/components/schemas/...

Either the validation is wrong and `multipleOf = 1` should be accepted. Or the message should go "...strictly greater than one".

Even with such an "ERROR", the OpenAPI document is generated, with `multipleOf = 1`. (IMHO this message should then be downgraded to a WARNING).

Edit: a separate issue was opened for this: #18002 

**With `multipleOf = 0.99999d` (or `0.5`) I've got:**

The same as with `multipleOf = 1`: same misleading error message, the generated OpenAPI document is ok, with `multipleOf = 0.99999` (or `0.5`).

**With `multipleOf = 0.1` (or `0.1d`, or `0.2`, or `0.0001d`, or `1.1d`, or `1.1`), I've got:**
> [INFO] [ERROR   ] CWWKO1661E: An error occurred when processing application margem-intraday_service and an OpenAPI document was not produced. The error was: java.lang.NumberFormatException.

The OpenAPI document is mostly empty (as promised by the error message):
```yaml
---
openapi: 3.0.3
info:
  title: Generated API
  version: "1.0"
servers:
- url: http://localhost:9080
- url: https://localhost:9443
paths: {}
```

(in ffdc):

> Exception = java.lang.NumberFormatException
> Source = io.openliberty.microprofile.openapi20.ApplicationProcessor
> probeid = 239
> Stack Dump = java.lang.NumberFormatException
>         at java.math.BigDecimal.<init>(BigDecimal.java:497)
>         at java.math.BigDecimal.<init>(BigDecimal.java:383)
>         at java.math.BigDecimal.<init>(BigDecimal.java:809)
>         at java.math.BigDecimal.valueOf(BigDecimal.java:1277)
>         at io.smallrye.openapi.runtime.io.schema.SchemaFactory.readAttr(SchemaFactory.java:329)
>         at io.smallrye.openapi.runtime.io.schema.SchemaFactory.readSchema(SchemaFactory.java:156)
>         at io.smallrye.openapi.runtime.scanner.dataobject.AnnotationTargetProcessor.readSchemaAnnotatedField(AnnotationTargetProcessor.java:312)
>         at io.smallrye.openapi.runtime.scanner.dataobject.AnnotationTargetProcessor.processField(AnnotationTargetProcessor.java:160)
>         at io.smallrye.openapi.runtime.scanner.dataobject.AnnotationTargetProcessor.process(AnnotationTargetProcessor.java:64)
>         at io.smallrye.openapi.runtime.scanner.OpenApiDataObjectScanner.lambda$depthFirstGraphSearch$1(OpenApiDataObjectScanner.java:262)
>         at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
>         (... many java.util.stream frames ...)
>         at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
>         at io.smallrye.openapi.runtime.scanner.OpenApiDataObjectScanner.depthFirstGraphSearch(OpenApiDataObjectScanner.java:262)
>         at io.smallrye.openapi.runtime.scanner.OpenApiDataObjectScanner.process(OpenApiDataObjectScanner.java:213)
>         at io.smallrye.openapi.runtime.scanner.OpenApiDataObjectScanner.process(OpenApiDataObjectScanner.java:160)
>         at io.smallrye.openapi.runtime.io.schema.SchemaFactory.introspectClassToSchema(SchemaFactory.java:477)
>         at io.smallrye.openapi.runtime.io.schema.SchemaFactory.readClassSchema(SchemaFactory.java:365)
>         at io.smallrye.openapi.runtime.io.schema.SchemaFactory.readSchema(SchemaFactory.java:217)
>         at io.smallrye.openapi.runtime.io.schema.SchemaFactory.readSchema(SchemaFactory.java:80)
>         at io.smallrye.openapi.runtime.io.schema.SchemaFactory.readSchema(SchemaFactory.java:65)
>         at io.smallrye.openapi.runtime.io.mediatype.MediaTypeReader.readMediaType(MediaTypeReader.java:49)
>         at io.smallrye.openapi.runtime.io.content.ContentReader.readContent(ContentReader.java:53)
>         at io.smallrye.openapi.runtime.io.requestbody.RequestBodyReader.readRequestBody(RequestBodyReader.java:124)
>         at io.smallrye.openapi.runtime.scanner.spi.AnnotationScanner.processRequestBody(AnnotationScanner.java:782)
>         at io.smallrye.openapi.jaxrs.JaxRsAnnotationScanner.processResourceMethod(JaxRsAnnotationScanner.java:402)
>         at io.smallrye.openapi.jaxrs.JaxRsAnnotationScanner.lambda$processResourceMethods$0(JaxRsAnnotationScanner.java:252)
>         at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
>         at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
>         at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
>         at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
>         at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1556)
>         at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
>         (... many java.util.stream frames ...)
>         at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
>         at io.smallrye.openapi.jaxrs.JaxRsAnnotationScanner.processResourceMethods(JaxRsAnnotationScanner.java:250)
>         at io.smallrye.openapi.jaxrs.JaxRsAnnotationScanner.processResourceClass(JaxRsAnnotationScanner.java:220)
>         at io.smallrye.openapi.jaxrs.JaxRsAnnotationScanner.processResourceClasses(JaxRsAnnotationScanner.java:196)
>         at io.smallrye.openapi.jaxrs.JaxRsAnnotationScanner.scan(JaxRsAnnotationScanner.java:126)
>         at io.smallrye.openapi.runtime.scanner.OpenApiAnnotationScanner.scan(OpenApiAnnotationScanner.java:118)
>         at io.smallrye.openapi.runtime.OpenApiProcessor.modelFromAnnotations(OpenApiProcessor.java:136)
>         at io.smallrye.openapi.runtime.OpenApiProcessor.modelFromAnnotations(OpenApiProcessor.java:117)
>         at io.openliberty.microprofile.openapi20.ApplicationProcessor.generateModel(ApplicationProcessor.java:263)
>         at io.openliberty.microprofile.openapi20.ApplicationProcessor.processWebModule(ApplicationProcessor.java:200)
>         at io.openliberty.microprofile.openapi20.ApplicationProcessor.processApplication(ApplicationProcessor.java:112)
>         at io.openliberty.microprofile.openapi20.ApplicationRegistry.processApplication(ApplicationRegistry.java:136)
>         at io.openliberty.microprofile.openapi20.ApplicationRegistry.addApplication(ApplicationRegistry.java:70)
>         at io.openliberty.microprofile.openapi20.ApplicationListener.applicationStarting(ApplicationListener.java:45)
>         at com.ibm.ws.container.service.state.internal.ApplicationStateManager.fireStarting(ApplicationStateManager.java:51)
>         at com.ibm.ws.container.service.state.internal.StateChangeServiceImpl.fireApplicationStarting(StateChangeServiceImpl.java:50)
>         at com.ibm.ws.app.manager.module.internal.SimpleDeployedAppInfoBase.preDeployApp(SimpleDeployedAppInfoBase.java:547)
>         at com.ibm.ws.app.manager.module.internal.SimpleDeployedAppInfoBase.installApp(SimpleDeployedAppInfoBase.java:508)
>         at com.ibm.ws.app.manager.module.internal.DeployedAppInfoBase.deployApp(DeployedAppInfoBase.java:349)
>         at com.ibm.ws.app.manager.war.internal.WARApplicationHandlerImpl.install(WARApplicationHandlerImpl.java:65)
>         at com.ibm.ws.app.manager.internal.statemachine.StartAction.execute(StartAction.java:149)
>         at com.ibm.ws.app.manager.internal.statemachine.ApplicationStateMachineImpl.enterState(ApplicationStateMachineImpl.java:1352)
>         at com.ibm.ws.app.manager.internal.statemachine.ApplicationStateMachineImpl.run(ApplicationStateMachineImpl.java:897)
>         at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:238)
>         (...)
> 

Here I don't know if `0.1` (or `0.2` or `0.0001d`) is a valid value for this property (though I could not find any spec strictly forbidding it). Any way the error report should be cleaner. At least it could say in which annotation it choked (the "Location: #/components/schemas/..." part I've got earlier with `multipleOf = 1`).

**With `multipleOf = 1.9` (or `2.5d`), I've got:**

Everything works fine. No error message. OpenAPI document correctly generated.

**Expected behavior**
I was trying to document my endpoint to tell that it accepts decimal values no more precise than `0.0001` (i.e. a `BigDecimal` with scale 4). To this end I've tried `multipleOf = 0.0001d`.

I don't know if the specs allow for fractional `multipleOf`. If not, then I expect a clearer error/warning message stating the fact (actually in this case I'd expect the attribute `multipleOf` to be `int`).

**Diagnostic information:**
 - OpenLiberty Version: 21.0.0.6/wlp-1.0.53.cl210620210527-1900
 - Java Version:  Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_271-b09 (en_BR)
 - server.xml configuration 
   > Installing features: [jsonb-1.0, jndi-1.0, cdi-2.0, passwordutilities-1.0, jdbc-4.2, localconnector-1.0, ejblite-3.2, jaxrs-2.1, concurrent-1.0, appsecurity-3.0, mpopenapi-2.0, beanvalidation-2.0, jpa-2.2, mphealth-3.0]
 and one minor oddity related to `<classloader apiTypeVisibility="+third-party" commonLibraryRef="..."/>`

### PR DESCRIPTION
**Pull request by Azquelt**
Consume the newly released versions of jandex and smallrye-open-api

Also add a test for the `NumberFormatException` which could occur when certain double values were used in annotations.

Fixes #17972

### CODE REVIEW

**Comment by Azquelt** [comment]
#build

**Comment by Azquelt** [comment]
#build

**Review by tbitonti — APPROVED** [review]
Nice update!  The test additions are very much appreciated.

**Comment by Azquelt** [comment]
#run-libby-bot
#build

**Review by tevans78 — APPROVED** [review]

**Comment by Azquelt** [comment]
Accidentally included a stray file from another PR.
#run-libby-bot
#build

**Pull request merged**
