### PR TITLE
Test restConnector-2.0 with checkpoint/restore

### PR DESCRIPTION
**Pull request by anjumfatima90**
#23702

### CODE REVIEW

**Comment by anjumfatima90** [comment]
#build

**Comment by anjumfatima90** [comment]
#build

**Review by tjwatson — DISMISSED** [review]

**Comment by anjumfatima90** [comment]
#build

**Comment by anjumfatima90** [comment]
#build

**Review by tjwatson — APPROVED** [review]

**Comment by anjumfatima90** [comment]
#libby

**Pull request merged**
