### PR TITLE
Transform RESTEasy bundle for JAX-RS 3.0

### LINKED ISSUE #13236: EE9: Transform RESTEasy bundle for JAX-RS 3.0
Perform transformation (via the Eclipse Transformer tool) from `javax.ws.rs.*` to `jakarta.ws.rs.*`.

### PR DESCRIPTION
**Pull request by andymc12**
Fixes #13236 - also includes fix for #13219 (could override #13220)...

### CODE REVIEW

**Comment by andymc12** [comment]
#build

**Comment by andymc12** [comment]
#build

**Comment by ManasiGandhi** [comment]
@andymc12 Do you need a message review for these files?

**Comment by andymc12** [comment]
Need to (temporarily) ignore an FFDC - new #build

**Comment by andymc12** [comment]
@ManasiGandhi sorry - no, these messages have already been approved.  This PR is just moving them.

**Comment by andrea-pichler** [comment]
No message review requested from L2

**Comment by andymc12** [comment]
#run-libby-bot

**Comment by andymc12** [comment]
A bunch of failures, but all of them appear in other builds and are unrelated to these changes.

**Pull request merged**
