### PR TITLE
Issue #16440: Update ExpressionLanguage 4.0 API/Impl to 10.0.6

### LINKED ISSUE #16440: Pull in latest Jakarta EE9 Expression Language API/Impl
Once we resolve the Jakarta issue mentioned here: https://github.com/OpenLiberty/open-liberty/issues/16176 we'll need to pull in the latest tomcat if they need to change.

### PR DESCRIPTION
**Pull request by pnicolucci**
fixes #16440

### CODE REVIEW

**Comment by pnicolucci** [comment]
#build

**Review by volosied — APPROVED** [review]
Looks good as far I can tell.  Hope CTS testing won't have any surprises.

**Review by isaacrivriv — APPROVED** [review]
Looks good to me. Thanks!

**Comment by pnicolucci** [comment]
#run-libby-bot

**Comment by pnicolucci** [comment]
CTS signature tests passed.

**Pull request merged**
