### PR TITLE
PR for Issue 9588: Fix JWKs behavior when JWT includes KID

### LINKED ISSUE #9588: Fix JWKS behavior that returns cached JWK despite the JWK not having right KID
The `JWKSet.getJWKByKidInCollection()` method has a behavior that's probably not what we want. Taking a look [here](https://github.com/OpenLiberty/open-liberty/blob/integration/dev/com.ibm.ws.security.common.jsonwebkey/src/com/ibm/ws/security/common/jwk/impl/JWKSet.java#L92), you'll see the method is implemented to:
1. Return the only cached JWK entry if a `kid` wasn't provided and there's only one JWK in the cache
1. Return the JWK in the cache whose `kid` matches the `kid` provided to the method
1. If the above don't apply, return the only cached JWK entry if there's only one JWK in the cache

That last point - returning the only cached JWK even if the `kid` doesn't match - probably isn't the implementation we want. The method should probably be changed to return `null` in this case, where a `kid` is provided to the method but there are no JWKs in the cache with a matching `kid`. That should be done even if there's only one JWK that's cached. That will force the runtime to do a remote call to attempt to fetch the correct JWK.

### PR DESCRIPTION
**Pull request by ayoho**
Resolves #9588

### CODE REVIEW

**Comment by ayoho** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.security.mp.jwt_fat,com.ibm.ws.security.openidconnect.client_fat,com.ibm.ws.security.openidconnect.client_fat.config,com.ibm.ws.security.openidconnect.client_fat.e2e,com.ibm.ws.security.openidconnect.client_fat.jaxrs,com.ibm.ws.security.openidconnect.client_fat.saml,com.ibm.ws.security.openidconnect.client_fat.spnego,com.ibm.ws.security.openidconnect.server_fat,com.ibm.ws.security.openidconnect.server_fat.config,com.ibm.ws.security.openidconnect.server_fat.endpoint.app-passwords,com.ibm.ws.security.openidconnect.server_fat.endpoint.app-passwords.DerbyDB.jwt,com.ibm.ws.security.openidconnect.server_fat.endpoint.app-passwords.DerbyDB.opaque,com.ibm.ws.security.openidconnect.server_fat.endpoint.app-passwords.LocalStore.jwt,com.ibm.ws.security.openidconnect.server_fat.endpoint.app-passwords.LocalStore.opaque,com.ibm.ws.security.openidconnect.server_fat.endpoint.app-tokens,com.ibm.ws.security.openidconnect.server_fat.endpoint.app-tokens.DerbyDB.jwt,com.ibm.ws.security.openidconnect.server_fat.endpoint.app-tokens.DerbyDB.opaque,com.ibm.ws.security.openidconnect.server_fat.endpoint.app-tokens.LocalStore.jwt,com.ibm.ws.security.openidconnect.server_fat.endpoint.app-tokens.LocalStore.opaque,com.ibm.ws.security.openidconnect.server_fat.endpoint.authorize,com.ibm.ws.security.openidconnect.server_fat.endpoint.clientregistration,com.ibm.ws.security.openidconnect.server_fat.endpoint.coveragemap,com.ibm.ws.security.openidconnect.server_fat.endpoint.discovery,com.ibm.ws.security.openidconnect.server_fat.endpoint.end_session,com.ibm.ws.security.openidconnect.server_fat.endpoint.introspect,com.ibm.ws.security.openidconnect.server_fat.endpoint.revoke,com.ibm.ws.security.openidconnect.server_fat.endpoint.token,com.ibm.ws.security.openidconnect.server_fat.endpoint.userinfo,com.ibm.ws.security.openidconnect.server_fat.feature,com.ibm.ws.security.openidconnect.server_fat.granttype.jwt,com.ibm.ws.security.openidconnect.server_fat.gui.tokenMgmt,com.ibm.ws.security.openidconnect.server_fat.jaxrs,com.ibm.ws.security.openidconnect.server_fat.jaxrs.config,com.ibm.ws.security.openidconnect.server_fat.oauth,com.ibm.ws.security.openidconnect.server_fat.oidc,com.ibm.ws.security.openidconnect.server_fat.saml,com.ibm.ws.security.openidconnect.server_fat.spnego,com.ibm.ws.security.social_fat,com.ibm.ws.security.social_fat.delegated,com.ibm.ws.security.social_fat.LibertyOP,com.ibm.ws.security.social_fat.multiProvider

**Comment by ayoho** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.security.jwtsso_fat,com.ibm.ws.security.mp.jwt_fat,com.ibm.ws.security.mp.jwt_fat_tck,com.ibm.ws.security.social_fat,com.ibm.ws.security.social_fat.oidcCertification,com.ibm.ws.security.jwt_fat.builder,com.ibm.ws.security.jwt_fat.consumer,com.ibm.ws.security.jwt_fat.mpjwt,com.ibm.ws.security.oauth_fat,com.ibm.ws.security.openidconnect.client_fat,com.ibm.ws.security.openidconnect.client_fat.config,com.ibm.ws.security.openidconnect.client_fat.e2e,com.ibm.ws.security.openidconnect.client_fat.jaxrs,com.ibm.ws.security.openidconnect.client_fat.saml,com.ibm.ws.security.openidconnect.server_fat,com.ibm.ws.security.openidconnect.server_fat.config,com.ibm.ws.security.openidconnect.server_fat.endpoint.app-passwords,com.ibm.ws.security.openidconnect.server_fat.endpoint.app-passwords.DerbyDB.jwt,com.ibm.ws.security.openidconnect.server_fat.endpoint.app-passwords.DerbyDB.opaque,com.ibm.ws.security.openidconnect.server_fat.endpoint.app-passwords.LocalStore.jwt,com.ibm.ws.security.openidconnect.server_fat.endpoint.app-passwords.LocalStore.opaque,com.ibm.ws.security.openidconnect.server_fat.endpoint.app-tokens,com.ibm.ws.security.openidconnect.server_fat.endpoint.app-tokens.DerbyDB.jwt,com.ibm.ws.security.openidconnect.server_fat.endpoint.app-tokens.DerbyDB.opaque,com.ibm.ws.security.openidconnect.server_fat.endpoint.app-tokens.LocalStore.jwt,com.ibm.ws.security.openidconnect.server_fat.endpoint.app-tokens.LocalStore.opaque,com.ibm.ws.security.openidconnect.server_fat.endpoint.authorize,com.ibm.ws.security.openidconnect.server_fat.endpoint.clientregistration,com.ibm.ws.security.openidconnect.server_fat.endpoint.coveragemap,com.ibm.ws.security.openidconnect.server_fat.endpoint.discovery,com.ibm.ws.security.openidconnect.server_fat.endpoint.end_session,com.ibm.ws.security.openidconnect.server_fat.endpoint.introspect,com.ibm.ws.security.openidconnect.server_fat.endpoint.revoke,com.ibm.ws.security.openidconnect.server_fat.endpoint.token,com.ibm.ws.security.openidconnect.server_fat.endpoint.userinfo,com.ibm.ws.security.openidconnect.server_fat.feature,com.ibm.ws.security.openidconnect.server_fat.granttype.jwt,com.ibm.ws.security.openidconnect.server_fat.gui.tokenMgmt,com.ibm.ws.security.openidconnect.server_fat.jaxrs,com.ibm.ws.security.openidconnect.server_fat.jaxrs.config,com.ibm.ws.security.openidconnect.server_fat.oauth,com.ibm.ws.security.openidconnect.server_fat.oidc,com.ibm.ws.security.openidconnect.server_fat.saml,com.ibm.ws.security.openidconnect.server_fat.spnego,com.ibm.ws.security.saml.sso_fat,com.ibm.ws.security.saml.sso_fat.2,com.ibm.ws.security.saml.sso_fat.3,com.ibm.ws.security.saml.sso_fat.config,com.ibm.ws.security.saml.sso_fat.config.mapToUserRegistry,com.ibm.ws.security.saml.sso_fat.endpoint.samlmetadata,com.ibm.ws.security.saml.sso_fat.jaxrs,com.ibm.ws.security.saml.sso_fat.jaxrs.config,com.ibm.ws.security.saml.sso_fat.logout,com.ibm.ws.security.saml.sso_fat.logout.httpServletRequest,com.ibm.ws.security.saml.sso_fat.logout.ibm_security_logout,com.ibm.ws.security.saml.sso_fat.logout.IDP_initiated,com.ibm.ws.security.social_fat,com.ibm.ws.security.social_fat.delegated,com.ibm.ws.security.social_fat.LibertyOP,com.ibm.ws.security.social_fat.multiProvider

**Comment by ayoho** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.security.jwtsso_fat,com.ibm.ws.security.mp.jwt_fat,com.ibm.ws.security.mp.jwt_fat_tck,com.ibm.ws.security.social_fat,com.ibm.ws.security.social_fat.oidcCertification,com.ibm.ws.security.jwt_fat.builder,com.ibm.ws.security.jwt_fat.consumer,com.ibm.ws.security.jwt_fat.mpjwt,com.ibm.ws.security.oauth_fat,com.ibm.ws.security.openidconnect.client_fat,com.ibm.ws.security.openidconnect.client_fat.config,com.ibm.ws.security.openidconnect.client_fat.e2e,com.ibm.ws.security.openidconnect.client_fat.jaxrs,com.ibm.ws.security.openidconnect.client_fat.saml,com.ibm.ws.security.openidconnect.server_fat,com.ibm.ws.security.openidconnect.server_fat.config,com.ibm.ws.security.openidconnect.server_fat.endpoint.app-passwords,com.ibm.ws.security.openidconnect.server_fat.endpoint.app-passwords.DerbyDB.jwt,com.ibm.ws.security.openidconnect.server_fat.endpoint.app-passwords.DerbyDB.opaque,com.ibm.ws.security.openidconnect.server_fat.endpoint.app-passwords.LocalStore.jwt,com.ibm.ws.security.openidconnect.server_fat.endpoint.app-passwords.LocalStore.opaque,com.ibm.ws.security.openidconnect.server_fat.endpoint.app-tokens,com.ibm.ws.security.openidconnect.server_fat.endpoint.app-tokens.DerbyDB.jwt,com.ibm.ws.security.openidconnect.server_fat.endpoint.app-tokens.DerbyDB.opaque,com.ibm.ws.security.openidconnect.server_fat.endpoint.app-tokens.LocalStore.jwt,com.ibm.ws.security.openidconnect.server_fat.endpoint.app-tokens.LocalStore.opaque,com.ibm.ws.security.openidconnect.server_fat.endpoint.authorize,com.ibm.ws.security.openidconnect.server_fat.endpoint.clientregistration,com.ibm.ws.security.openidconnect.server_fat.endpoint.coveragemap,com.ibm.ws.security.openidconnect.server_fat.endpoint.discovery,com.ibm.ws.security.openidconnect.server_fat.endpoint.end_session,com.ibm.ws.security.openidconnect.server_fat.endpoint.introspect,com.ibm.ws.security.openidconnect.server_fat.endpoint.revoke,com.ibm.ws.security.openidconnect.server_fat.endpoint.token,com.ibm.ws.security.openidconnect.server_fat.endpoint.userinfo,com.ibm.ws.security.openidconnect.server_fat.feature,com.ibm.ws.security.openidconnect.server_fat.granttype.jwt,com.ibm.ws.security.openidconnect.server_fat.gui.tokenMgmt,com.ibm.ws.security.openidconnect.server_fat.jaxrs,com.ibm.ws.security.openidconnect.server_fat.jaxrs.config,com.ibm.ws.security.openidconnect.server_fat.oauth,com.ibm.ws.security.openidconnect.server_fat.oidc,com.ibm.ws.security.openidconnect.server_fat.saml,com.ibm.ws.security.openidconnect.server_fat.spnego,com.ibm.ws.security.saml.sso_fat,com.ibm.ws.security.saml.sso_fat.2,com.ibm.ws.security.saml.sso_fat.3,com.ibm.ws.security.saml.sso_fat.config,com.ibm.ws.security.saml.sso_fat.config.mapToUserRegistry,com.ibm.ws.security.saml.sso_fat.endpoint.samlmetadata,com.ibm.ws.security.saml.sso_fat.jaxrs,com.ibm.ws.security.saml.sso_fat.jaxrs.config,com.ibm.ws.security.saml.sso_fat.logout,com.ibm.ws.security.saml.sso_fat.logout.httpServletRequest,com.ibm.ws.security.saml.sso_fat.logout.ibm_security_logout,com.ibm.ws.security.saml.sso_fat.logout.IDP_initiated,com.ibm.ws.security.social_fat,com.ibm.ws.security.social_fat.delegated,com.ibm.ws.security.social_fat.LibertyOP,com.ibm.ws.security.social_fat.multiProvider

**Comment by arunavemulapalli** [comment]
#run-libby-bot

**Comment by arunavemulapalli** [comment]
The latest personal build is good except that the build request has an invalid test bucket name.

**Pull request merged**
