### PR TITLE
Issue #23462: Speculative workaround for NPE in DB2Helper.isAuthException

### LINKED ISSUE #23462: NullPointerException in com.ibm.ws.rsadapter.impl.DB2Helper.isAuthException
**Describe the bug**  

FFDC:

```
------Start of DE processing------ = [2022-10-26T11:16:43.852+0000]
Exception = java.lang.NullPointerException
Source = noSourceId
probeid = com.lombardisoftware.utility.spring.ProgrammaticTransactionSupport
Stack Dump = java.lang.NullPointerException
    at com.ibm.ws.rsadapter.impl.DB2Helper.isAuthException(DB2Helper.java:269)
    at com.ibm.ws.rsadapter.impl.DatabaseHelper.isAnAuthorizationException(DatabaseHelper.java:1597)
    at com.ibm.ws.rsadapter.AdapterUtil.mapException(AdapterUtil.java:1265)
    at com.ibm.ws.rsadapter.jdbc.WSJdbcUtil.mapException(WSJdbcUtil.java:108)
    at com.ibm.ws.rsadapter.jdbc.WSJdbcPreparedStatement.executeUpdate(WSJdbcPreparedStatement.java:526)
    at org.springframework.jdbc.core.JdbcTemplate.lambda$update$2(JdbcTemplate.java:965) [...]
```

**Steps to Reproduce**  

Non-reproduceable. Seemingly related to a DB2 transaction log full error.

**Expected behavior**  

NullPointerException unexpected

**Diagnostic information:**  
 - OpenLiberty Version: 22.0.0.3
 - Affected feature(s): jdbc
 - Java Version: IBM Java 8
 - server.xml configuration (WITHOUT sensitive information like passwords)
   ```
     <library id="DB2JCC4Lib">
           <fileset dir="/shared/resources/jdbc/db2" includes="db2jcc4.jar db2jcc_license_cu.jar"/>
     </library>
     <dataSource commitOrRollbackOnCleanup="commit" id="jdbc/TeamWorksDB" isolationLevel="TRANSACTION_READ_COMMITTED" jndiName="jdbc/TeamWorksDB" type="javax.sql.XADataSource">
           <jdbcDriver libraryRef="DB2JCC4Lib"/>
           <connectionManager maxPoolSize="200" minPoolSize="1"/>
           <properties.db2.jcc
               databaseName="${db_name}"
               serverName="${db_host}"
               portNumber="${db_port}"
               user="${db_user}"
               password="${db_password}"
               driverType="4"
           />
     </dataSource>
     <transaction recoverOnStartup="true" waitForRecovery="false" heuristicRetryInterval="10" transactionLogDBTableSuffix="${tran_log_suffix}"
           recoveryGroup="recover-group-icp4adeploy-workflow-authoring-baw" recoveryIdentity="_RI${tran_log_suffix}">
       <dataSource transactional="false">
           <jdbcDriver libraryRef="DB2JCC4Lib"/>
           <properties.db2.jcc
               databaseName="${db_name}"
               serverName="${db_host}"
               portNumber="${db_port}"
               user="${db_user}"
               password="${db_password}"
               driverType="4"
           />
       </dataSource>
   </transaction>
   ```
 - If it would be useful, upload the messages.log file found in `$WLP_OUTPUT_DIR/messages.log`: N/A

**Additional context**

### PR DESCRIPTION
**Pull request by kgibm**
Fixes #23462

### CODE REVIEW

**Comment by kgibm** [comment]
#build

**Comment by kgibm** [comment]
#libby

**Comment by kgibm** [comment]
#build

**Comment by kgibm** [comment]
#build

**Review by njr-11 — APPROVED** [review]
Approving this as a workaround for suspected Java bug.

**Pull request merged**
