### PR TITLE
Issue23894-FixJava2SecurityBuildBreak

### PR DESCRIPTION
**Pull request by emilytee**

### CODE REVIEW

**Comment by emilytee** [comment]
#libby

**Comment by emilytee** [comment]
#build

**Comment by emilytee** [comment]
fixes #23894

**Comment by emilytee** [comment]
#build global.java2.sec

**Comment by emilytee** [comment]
#build global.java2.sec=true

**Review by acdemyers — APPROVED** [review]

**Comment by emilytee** [comment]
#build #global.java2.sec=true

**Pull request merged**
