### PR TITLE
add AES128 to kdc scripts for spnego FAT

### PR DESCRIPTION
**Pull request by Zech-Hein**
This changes the encryption level used for Kerberos in the Spnego.1 FAT to use `aes128-cts-hmac-sha1-96` instead of `rc4-hmac`
this is needed to allow the tests to run successfully on java17 builds as `rc4-hmac` is not sufficient for java17.

To allow this change to work, the krb5.conf needs to be updated in consul first, I have a pull request pending for that in GHE. I will kick off the PB for this PR after that consul change is merged.

fyi: @gjwatts

### CODE REVIEW

**Comment by Zech-Hein** [comment]
#build

**Review by utle — APPROVED** [review]

**Comment by Zech-Hein** [comment]
#build

**Comment by Zech-Hein** [comment]
The changes in this PR affect the spnego tests that use remote KDC machines. Most of our spnego tests no longer use remote KDC machines and instead use a local ApacheDS KDC.

The current spnego tests are split between two buckets as follows:
```
spnego_fat : All tests use local ApacheDS KDC
spnego_fat.1 : All tests use remote KDC machine.
```
The changes in this PR only affect `spnego_fat.1` and not `spnego_fat`. The previous PBs only ran spnego_fat so it needs to be re-run for spnego_fat.1

#build
#spawn.fullfat.buckets=com.ibm.ws.security.spnego_fat.1

**Comment by Zech-Hein** [comment]
the failures from the basicAuthTest class are unrelated to the change and caused by a change in a seperate PR to the JavaInfo class

**Pull request merged**
