### PR TITLE
cleanup Resteasy dependencies in oss_dependencies.maven

### PR DESCRIPTION
**Pull request by WhiteCat22**
We are pulling in the `6.0.0.Final` Resteasy dependencies, but we don't use them.

This change does not affect product code nor tests.

### CODE REVIEW

**Comment by WhiteCat22** [comment]
#Libby #build #spawn.fullfat.buckets=com.ibm.ws.jaxrs.2.0_fat,com.ibm.ws.jaxrs.2.0.cdi.1.2_fat,com.ibm.ws.jaxrs.2.0.client_fat,com.ibm.ws.jaxrs.2.1_fat,com.ibm.ws.jaxrs.2.1_fat_executor,com.ibm.ws.jaxrs.2.1_fat_extended,com.ibm.ws.jaxrs.2.1.cdi.2.0_fat,com.ibm.ws.jaxrs.2.1.client_fat,com.ibm.ws.jaxrs.2.1.sse_fat,com.ibm.ws.jaxrs.2.x_fat_clientProps,io.openliberty.restfulWS.3.0_fat,io.openliberty.restfulWS.3.0.cdi.3.0_fat,io.openliberty.restfulWS.3.0.client_fat,io.openliberty.restfulWS.3.1_fat

**Review by jim-krueger — APPROVED** [review]

**Comment by WhiteCat22** [comment]
#libby

**Comment by WhiteCat22** [comment]
#build

**Comment by WhiteCat22** [comment]
#build

**Pull request merged**
