### PR TITLE
Fixes #24584

### LINKED ISSUE #24584: pluginUtility merge action generates incorrect output for some inputs
Merging of a large heterogeneous mix of plugin-cfg.xmls fails to properly organise all of the routes from all of the input plugin configs.

### PR DESCRIPTION
**Pull request by brianxjx**
Fixes #24584

### CODE REVIEW

**Comment by brianxjx** [comment]
#build

**Comment by twpatter** [comment]
#build

**Comment by brianxjx** [comment]
#build

**Comment by brianxjx** [comment]
#libby-build

**Review by dtadcox — DISMISSED** [review]
LGTM

**Review by twpatter — DISMISSED** [review]

**Comment by brianxjx** [comment]
#build

**Comment by brianxjx** [comment]
#build

**Comment by brianxjx** [comment]
#build

**Review by twpatter — APPROVED** [review]

**Review by dtadcox — APPROVED** [review]

**Comment by brianxjx** [comment]
#build

**Comment by hlhoots** [comment]
copyright header is missing thus no merge button.  see if Libbybot can help us: 

#run-libby-bot

**Pull request merged**
