### PR TITLE
Issue #12355: Rename Jakarta Interceptor and Persistence API

### LINKED ISSUE #12355: Jakarta EE 9: Rename interceptor API bundle
Rename interceptor and persistence API bundles from

  com.ibm.websphere.jakarta.interceptor.2.0
  com.ibm.websphere.jakartaee.persistence.3.0

to

  io.openliberty.jakarta.interceptor.2.0
  io.openliberty.jakarta.persistence.3.0

### PR DESCRIPTION
**Pull request by tkburroughs**
Rename interceptor and persistence API bundles from

com.ibm.websphere.jakarta.interceptor.2.0
com.ibm.websphere.jakartaee.persistence.3.0

to

io.openliberty.jakarta.interceptor.2.0
io.openliberty.jakarta.persistence.3.0

fixes #12355

### CODE REVIEW

**Comment by tkburroughs** [comment]
#build

**Comment by tkburroughs** [comment]
#build

**Comment by tkburroughs** [comment]
#build

**Comment by jhanders34** [comment]
#build

**Comment by tkburroughs** [comment]
Failing FAT in the 2 builds that have completed are known issues; unrelated to jakarta ee 9 and the rename in this pr.  Ready to merge.

**Pull request merged**
