### PR TITLE
Jms20 fat dcf

### PR DESCRIPTION
**Pull request by tbitonti**
FAT enablement change, only.

This pull request enables the test class "JMSDCFTest.java", one of the test classes under FAT project "com.ibm.ws.messaging.open_jms20_fat".

The test is running locally in both javax and jakarta modes, but with questionable configuration settings.

A messaging engine is enabled on both the client server (JMSDCFClient.xml) and on the engine server (JMSDCFEngine.xml).  I was unable to get the tests to run without having both a client server and an engine server, and with a messaging engine on both servers.  I tried but was unable to get the tests running using a single server configuration.

---

Pre-Jakarta, use of client configuration that does not have a server element results in an injection failure of:

```
  @Resource(name = "myJMSCF")

  Stack Dump = com.ibm.wsspi.injectionengine.InjectionException: 
      CWNEN1004E: The server was unable to find the myJMSCF default binding
      with the javax.jms.ConnectionFactory type for the java:comp/env/myJMSCF reference.
          at com.ibm.ws.injectionengine.osgi.internal.IndirectJndiLookupObjectFactory.
          getObjectInstance(IndirectJndiLookupObjectFactory.java:282)
```

Still pre-Jakarta, adding a server element fixes the default injection:

`  <feature>wasJmsServer-1.0</feature>`

But queue lookup fails:

```
  jmsQueue = (Queue) new InitialContext().lookup("java:comp/env/jndi_INPUT_Q");

  Stack Dump = javax.servlet.ServletException: Failed JMS initialization
      at jmsdcf.web.JMSDCFServlet.init(JMSDCFServlet.java
```

A modification to the lookup enables most tests to succeed:

`  jmsQueue = (Queue) new InitialContext().lookup("jndi_INPUT_Q");`

Note the client configuration has this queue binding:

```
  <jmsQueue id="jndi_INPUT_Q" jndiName="jndi_INPUT_Q">
    <properties.wasJms queueName="QUEUE1"/>
  </jmsQueue>
```

One test still fails "testP2P_B_SecOff_inject":

```
  Caused by: com.ibm.ws.sib.processor.exceptions.SIMPNotPossibleInCurrentConfigurationException:
    CWSIK0015E: The destination QUEUE1 was not found on messaging engine defaultME.
    at com.ibm.ws.sib.processor.impl.DestinationManager.checkDestinationHandlerExists(DestinationManager.javva:4146)
```

Adding a queue element to the client configuration messaging engine enables this test to pass:

```
  <messagingEngine id="CLIENT_ME">
    <queue id="QUEUE1" maxRedeliveryCount="2"/>
  </messagingEngine>
```

Note that the element was already present in the engine configuration messaging engine:

```
  <messagingEngine id="ENGINE_ME">
    <queue id="QUEUE1" maxRedeliveryCount="2"/>
  </messagingEngine>
```

### CODE REVIEW

**Comment by tbitonti** [comment]
#build

**Comment by dhaggart** [comment]
OK, so eliminating "java:comp/env/" changes fundamentally the way the resources work, switching from indirect to direct lookups .  The look-ups should all be able to be done indirectly using the resource-ref names specified in the web.xml for the servlet.  This is present for the queue:

```
  <resource-env-ref>
    <resource-env-ref-name>jndi_INPUT_Q1</resource-env-ref-name>
    <resource-env-ref-type>javax.jms.Queue</resource-env-ref-type>
  </resource-env-ref>
```

though it isn't really that important for the queue whereas it is for the connection factory.

It is apparent that the resource ref for "myJMSCF" is absent from the file and should be added, something like:

test-applications/JMSDCF/resources/WEB-INF/web.xml:

```
  <resource-ref>
    <res-ref-name>myJMSCF</res-ref-name>
    <res-type>javax.jms.ConnectionFactory</res-type>
    <lookup-name>myJMSCF</lookup-name>
  </resource-ref>
```

and then @Resource(name = "myJMSCF") should work.

publish/files/JMSDCFClient.xml seems to lack the definition of "myJMSCF" though so not sure how it is working; I think it should have:

```
  <jmsConnectionFactory jndiName="myJMSCF" connectionManagerRef="ConMgr6">
    <properties.wasJms remoteServerAddress="localhost:${bvt.prop.jms.1}:BootstrapBasicMessaging"/> 
  </jmsConnectionFactory>

```
added.

It should also have the wasJmsEndpoint removed as it shouldn't be necessary for the client.

(I would have tested all this before posting the comment but something is up with my build environment continually complaining of a lack of fatTestPorts.xml inclusion even when explicitly/expressly added.)

**Comment by tbitonti** [comment]
#libby

**Review by dazavala — APPROVED** [review]

**Comment by tbitonti** [comment]
#libby

**Pull request merged**
