### PR TITLE
Add Equinox trace to share classes support

### PR DESCRIPTION
**Pull request by tjwatson**

### CODE REVIEW

**Comment by tjwatson** [comment]
#build

**Comment by tjwatson** [comment]
#build

**Comment by tjwatson** [comment]
#build

**Review by dazavala — APPROVED** [review]
LGTM. Changes within the SharedClassCacheHook to replace reflection artifacts with the OTI shared class HelperFactory and URLHelper classes look correct -- i.e. `<ctor>` and method return values, fail conditions that render the hook instance null, arguments passed to HelperFactory and URLHelper methods, and exception handling on calls to URLHelper methods. Nit: SharedClassCacheHook is not an overlay class; its CR needs update.

**Comment by tjwatson** [comment]
#libby

**Review by jhanders34 — APPROVED** [review]

**Pull request merged**
