### PR TITLE
Upgrade postgres test driver

### PR DESCRIPTION
**Pull request by mswatosh**
Updating the postgres driver used in Open Liberty tests.

Removing a few unnecessary postgres drivers in build paths.

### CODE REVIEW

**Comment by mswatosh** [comment]
#build

**Comment by mswatosh** [comment]
#run-libby-bot

**Comment by mswatosh** [comment]
#build

**Comment by mswatosh** [comment]
Failures are all unrelated

**Review by KyleAure — APPROVED** [review]

**Pull request merged**
