### PR TITLE
Implement default mapping for getServletPath

### PR DESCRIPTION
**Pull request by pmd1nh**
test fix getServletPath for default servlet mapping of (/) splash

### CODE REVIEW

**Comment by pmd1nh** [comment]
#build       #spawn.fullfat.buckets=com.ibm.ws.webcontainer_fat,com.ibm.ws.webcontainer_fat_lWAS,com.ibm.ws.webcontainer_fat_servlet31,com.ibm.ws.webcontainer_fat_servlet31_webcontainerlWAS,com.ibm.ws.webcontainer.servlet.4.0_fat,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.1,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0.lWAS

**Comment by pmd1nh** [comment]
Note to self: SERVLET_PATH_FOR_DEFAULT_MAPPING has HIGHEST priority and should be used from 18.0.0.4 onward.  

To ease the migration for customer who may have already SET the old ENABLE_DEFAULT_SERVLET_REQUEST_PATH_ELEMENTS, the SERVLET_PATH_FOR_DEFAULT_MAPPING will be set automatically IFF it has not set.

**Comment by pmd1nh** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.webcontainer_fat,com.ibm.ws.webcontainer_fat_lWAS,com.ibm.ws.webcontainer_fat_servlet31,com.ibm.ws.webcontainer_fat_servlet31_webcontainerlWAS,com.ibm.ws.webcontainer.servlet.4.0_fat,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.1,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0.lWAS

**Comment by pnicolucci** [comment]
#4809

**Comment by pnicolucci** [comment]
Closing this as it will be included in the following PR: https://github.com/OpenLiberty/open-liberty/pull/4852

**Pull request closed without merging**
