### PR TITLE
Wait for ObjectFactory References

### PR DESCRIPTION
**Pull request by tkburroughs**
@Resource injection is intermittently failing because some ObjectFactory OSGi components
have not yet been activated, so update the injection engine to wait for the needed
ObjectFactory rather than just fail.

for #16596

### CODE REVIEW

**Comment by tkburroughs** [comment]
#build

**Comment by tkburroughs** [comment]
Build looks good; failing FAT is unrelated to this change and matches an open issue.

**Comment by tkburroughs** [comment]
Fixed a problem with the wait time calculation; pushed new commit.

**Comment by tkburroughs** [comment]
#build

**Comment by tkburroughs** [comment]
#libby-bot

**Comment by tkburroughs** [comment]
#libby-bot

**Comment by tkburroughs** [comment]
#build

**Comment by tkburroughs** [comment]
#libby-bot
#build

**Review by brideck — APPROVED** [review]

**Comment by tkburroughs** [comment]
#build

**Pull request merged**
