### PR TITLE
Add build-test.xml to fat project zips

### PR DESCRIPTION
**Pull request by rickettmwork**

### CODE REVIEW

**Review by websterc87 — COMMENTED** [review]
Code looks good but I would want a PB to prove this doesnt break existing builds

**Comment by websterc87** [comment]
#build

**Comment by rickettmwork** [comment]
#build

**Comment by rickettmwork** [comment]
!pbbeta

**Comment by rickettmwork** [comment]
PB failures:
1. Caused by: java.lang.OutOfMemoryError: native memory exhausted
2. No errors, just never finished
3. No errors, just never finished.

None of these appear to be related to the code change, but its possible they are somehow, so... trying again.

If this one fails suggest we ditch the change

**Comment by rickettmwork** [comment]
#pb

**Comment by rickettmwork** [comment]
Give up.

**Pull request closed without merging**
