### PR TITLE
fix identifyException to show under dataSource and beta it

### PR DESCRIPTION
**Pull request by njr-11**
The identifyException element is missing from the schema under dataSource.
Fix this and then beta identifyException so that users can try it out.

### CODE REVIEW

**Comment by njr-11** [comment]
#build

**Comment by njr-11** [comment]
When I tried to promote the identifyException nested element under dataSource to beta, I discovered that identifyException had already been accidentally externalized as an unusable top level element as GA function.  I'll need to open a design issue to determine what to do about that.

**Comment by njr-11** [comment]
#build

**Comment by njr-11** [comment]
#run-libby-bot

**Review by jmstephensgit — APPROVED** [review]

**Comment by njr-11** [comment]
Build had 1 test failure, which is a duplicate of a pre-existing issue in an unrelated test bucket.

**Pull request merged**
