### PR TITLE
JAX-RS 3.0 Client to use ManagedExecutorService if available

### PR DESCRIPTION
**Pull request by andymc12**
This is a [spec requirement](https://jakarta.ee/specifications/restful-ws/3.0/jakarta-restful-ws-spec-3.0.html#executor_services) and is blocking the MP OpenTracing team because they depend on contexts being transferred on async JAX-RS client requests.

### CODE REVIEW

**Comment by andymc12** [comment]
#build

**Review by WhiteCat22 — APPROVED** [review]

**Comment by andymc12** [comment]
Addressed a code review issue (mentioned in slack) about not doing anything with the closeActions (whoops!) and a typo that pulled in concurrency 3.0 instead of 2.0. New #build

**Comment by andymc12** [comment]
Last build completed with 2 unrelated failures.  Adam, Jim and I walked through the code changes after yesterday's scrum. Merging.

**Comment by andymc12** [comment]
#libby

**Pull request merged**
