### PR TITLE
refactored ServicesTest

### PR DESCRIPTION
**Pull request by bensonlatibm**
Updated some comments.
added 2s delay between service commands.

### CODE REVIEW

**Comment by bensonlatibm** [comment]
#build

**Comment by bensonlatibm** [comment]
#build

**Comment by bensonlatibm** [comment]
#build

**Comment by bensonlatibm** [comment]
#build

**Comment by bensonlatibm** [comment]
#run-libby-bot

**Comment by bensonlatibm** [comment]
#build

**Review by tiwarim — APPROVED** [review]
Looks good!

**Pull request merged**
