### PR TITLE
Update messaging to return 3.1 for metadata version for EE10

### PR DESCRIPTION
**Pull request by jhanders34**
This is the EE10 version of https://github.com/OpenLiberty/open-liberty/pull/14919

### CODE REVIEW

**Comment by jhanders34** [comment]
#build

**Comment by dazavala** [comment]
Most excellent.  I wondered why the JMSMetaDataImpl class hardcoded the spec major and minor versions rather than pull them from the connection metadata, which is where the spec says the version info is declared.  I believe this is the appropriate solution going forward over the simple solution I added for ee9.

**Review by dazavala — APPROVED** [review]

**Comment by jhanders34** [comment]
#libby

**Comment by jhanders34** [comment]
#libby

**Pull request merged**
