### PR TITLE
Update EclipseLink 2.7.14 -> 2.7.15

### LINKED ISSUE #27541: Update to EclipseLink 2.7.15 for JPA 2.2
When EclipseLink 2.7.15 is released, update `com.ibm.websphere.appserver.thirdparty.eclipselink.2.7` to deliver new release.

- [All EclipseLink Binaries](https://mvnrepository.com/artifact/org.eclipse.persistence/eclipselink)
- [EclipseLink 2.7.15 Binaries](https://mvnrepository.com/artifact/org.eclipse.persistence/eclipselink/2.7.15)
- [EclipseLink 2.7.15 Release Notes](https://github.com/eclipse-ee4j/eclipselink/releases/tag/2.7.15)

Overlays to remove:
- None

Included fixes to document in Liberty
- None

### PR DESCRIPTION
**Pull request by anija-anil**
Updating EclipseLink from 2.7.14 to 2.7.15.

fixes #27541

### CODE REVIEW

**Comment by anija-anil** [comment]
#build

**Review by tkburroughs — APPROVED** [review]
Thanks for spotting that the excludes needed to be removed from `build.gradle`

**Comment by tkburroughs** [comment]
Since many of the JPA FAT is full only; run all in FULL mode to ensure no regressions:
#build #spawn.fullfat.buckets=com.ibm.ws.jpa.tests.beanvalidation_jpa_2.2_fat,com.ibm.ws.jpa.tests.container.checkpoint_jpa_2.2_fat,com.ibm.ws.jpa.tests.container.client_fat,com.ibm.ws.jpa.tests.eclipselink_jpa_2.2_fat,com.ibm.ws.jpa.tests.eclipselink.query_jpa_2.2_fat,com.ibm.ws.jpa.tests.jpa_22_fat,com.ibm.ws.jpa.tests.jpaconfig_jpa_2.2_fat,com.ibm.ws.jpa.tests.spec10.callback_jpa_2.2_fat,com.ibm.ws.jpa.tests.spec10.embeddable_jpa_2.2_fat,com.ibm.ws.jpa.tests.spec10.entity_jpa_2.2_fat,com.ibm.ws.jpa.tests.spec10.entitymanager_jpa_2.2_fat,com.ibm.ws.jpa.tests.spec10.inheritance_jpa_2.2_fat,com.ibm.ws.jpa.tests.spec10.injection.defaultPersistenceUnit_fat,com.ibm.ws.jpa.tests.spec10.injection.dfi_fat,com.ibm.ws.jpa.tests.spec10.injection.dmi_fat,com.ibm.ws.jpa.tests.spec10.injection.ejbinwar_fat,com.ibm.ws.jpa.tests.spec10.injection.jarfile_fat,com.ibm.ws.jpa.tests.spec10.injection.jndi_fat,com.ibm.ws.jpa.tests.spec10.injection.mdb_fat,com.ibm.ws.jpa.tests.spec10.issues_fat,com.ibm.ws.jpa.tests.spec10.packaging_jpa_2.2_fat,com.ibm.ws.jpa.tests.spec10.query_jpa_2.2_fat,com.ibm.ws.jpa.tests.spec10.relationships.manyXmany_jpa_2.2_fat,com.ibm.ws.jpa.tests.spec10.relationships.manyXone_jpa_2.2_fat,com.ibm.ws.jpa.tests.spec10.relationships.oneXmany_jpa_2.2_fat,com.ibm.ws.jpa.tests.spec10.relationships.oneXone_jpa_2.2_fat,com.ibm.ws.jpa.tests.spec20_jpa_2.2_fat,com.ibm.ws.jpa.tests.spec21.cdi_fat,com.ibm.ws.jpa.tests.spec21.issues_fat,com.ibm.ws.jpa.tests.spec21.txsynchronization_fat

**Comment by tkburroughs** [comment]
Good news is that all the JPA tests passed in FULL mode... so once the feature checker failures are addressed, this should build cleanly.

**Comment by anija-anil** [comment]
#build

**Comment by anija-anil** [comment]
#build

**Comment by tkburroughs** [comment]
Since many of the JPA FAT is full only; run all in FULL mode to ensure no regressions:
#build #spawn.fullfat.buckets=com.ibm.ws.jpa.tests.beanvalidation_jpa_2.2_fat,com.ibm.ws.jpa.tests.container.checkpoint_jpa_2.2_fat,com.ibm.ws.jpa.tests.container.client_fat,com.ibm.ws.jpa.tests.eclipselink_jpa_2.2_fat,com.ibm.ws.jpa.tests.eclipselink.query_jpa_2.2_fat,com.ibm.ws.jpa.tests.jpa_22_fat,com.ibm.ws.jpa.tests.jpaconfig_jpa_2.2_fat,com.ibm.ws.jpa.tests.spec10.callback_jpa_2.2_fat,com.ibm.ws.jpa.tests.spec10.embeddable_jpa_2.2_fat,com.ibm.ws.jpa.tests.spec10.entity_jpa_2.2_fat,com.ibm.ws.jpa.tests.spec10.entitymanager_jpa_2.2_fat,com.ibm.ws.jpa.tests.spec10.inheritance_jpa_2.2_fat,com.ibm.ws.jpa.tests.spec10.injection.defaultPersistenceUnit_fat,com.ibm.ws.jpa.tests.spec10.injection.dfi_fat,com.ibm.ws.jpa.tests.spec10.injection.dmi_fat,com.ibm.ws.jpa.tests.spec10.injection.ejbinwar_fat,com.ibm.ws.jpa.tests.spec10.injection.jarfile_fat,com.ibm.ws.jpa.tests.spec10.injection.jndi_fat,com.ibm.ws.jpa.tests.spec10.injection.mdb_fat,com.ibm.ws.jpa.tests.spec10.issues_fat,com.ibm.ws.jpa.tests.spec10.packaging_jpa_2.2_fat,com.ibm.ws.jpa.tests.spec10.query_jpa_2.2_fat,com.ibm.ws.jpa.tests.spec10.relationships.manyXmany_jpa_2.2_fat,com.ibm.ws.jpa.tests.spec10.relationships.manyXone_jpa_2.2_fat,com.ibm.ws.jpa.tests.spec10.relationships.oneXmany_jpa_2.2_fat,com.ibm.ws.jpa.tests.spec10.relationships.oneXone_jpa_2.2_fat,com.ibm.ws.jpa.tests.spec20_jpa_2.2_fat,com.ibm.ws.jpa.tests.spec21.cdi_fat,com.ibm.ws.jpa.tests.spec21.issues_fat,com.ibm.ws.jpa.tests.spec21.txsynchronization_fat

**Pull request merged**
