### PR TITLE
Remove Jsp's packageinfo from org/apache/jasper/runtime/ package

### PR DESCRIPTION
**Pull request by volosied**
Doesn't appear to have any real purpose?   Originally brought up here: https://github.com/OpenLiberty/open-liberty/pull/26346#discussion_r1332289349

The bnd.bnd also export this package. For instance, in the 2.3 bundle: 

```
org.apache.jasper.runtime;thread-context=true;version="2.3"
```

The packageinfo lines were added in WS-CD-Liberty in 17.0.0.2 under commit: `dc93ff3f8adc3939452a857b071cf802bccc22fd` : "updates for gradle open liberty projects ".

### CODE REVIEW

**Comment by volosied** [comment]
I don't see any significant difference between bundles (with / without this change).

Only that the following are missing: 
﻿﻿org.apache.jasper.runtime.package-info.class
org.apache.jasper.runtime.packageinfo

**Comment by volosied** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jsp.2.3_fat,io.openliberty.pages.3.1.internal_fat,io.openliberty.pages.4.0.internal_fat

**Review by pnicolucci — COMMENTED** [review]
We should update the copyright date range header in bnd.bnd to include 2023.

**Review by pnicolucci — APPROVED** [review]

**Comment by volosied** [comment]
#libby

**Pull request merged**
