### PR TITLE
Update Jackson to 2.13.4

### PR DESCRIPTION
**Pull request by Azquelt**
Note that most of the Jackson jars have moved the module-info.class into META-INF/versions and we still don't want to include it in our bundle.

As it's the only class in META-INF/versions, we just exclude the whole directory.

### CODE REVIEW

**Comment by Azquelt** [comment]
#build

**Comment by Azquelt** [comment]
#build
#libby

**Comment by Azquelt** [comment]
#libby
#build

**Comment by Azquelt** [comment]
Needs some build changes as well. Test build to check whether they will work once they're included as well: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_l0aUsFFCEe2fv7PFprXZfA

**Review by jhanders34 — COMMENTED** [review]
Should ant_build.js/build.gradle and cnf/build.gradle also be updated?

**Review by Emily-Jiang — DISMISSED** [review]

**Comment by Azquelt** [comment]
> Should ant_build.js/build.gradle and cnf/build.gradle also be updated?

Thanks, I did mean to update `cnf/build.gradle` but that got lost somewhere.

I hadn't seen `ant_build.js/build.gradle`, I don't know what it's used for there and as that one's far more out of date I think there's a higher risk of breakage so I'll make a separate PR for that.

**Comment by Azquelt** [comment]
Build with latest updates and build changes: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_LJXQ0FMjEe2P_cwgExA7aA

**Review by jhanders34 — APPROVED** [review]

**Comment by Azquelt** [comment]
#build

**Comment by Azquelt** [comment]
#libby

**Comment by Azquelt** [comment]
The failure in the build does not appear to be related to this change.

**Pull request merged**
