### PR TITLE
update keystores for jcache checkpoint tests and disable hnv

### LINKED ISSUE #29412: Fixing Checkpoint Hostname Verification Fat Failures

### PR DESCRIPTION
**Pull request by karel-harjono**

### CODE REVIEW

**Comment by karel-harjono** [comment]
#build

**Comment by karel-harjono** [comment]
#build

**Comment by karel-harjono** [comment]
#build

**Comment by karel-harjono** [comment]
#build

**Review by arkarkala — APPROVED** [review]

**Pull request merged**
