### PR TITLE
Added test class to check webProfile EAR deployment with checkpoint

### PR DESCRIPTION
**Pull request by KeenanMcCarthy**
Created an EAR with two WARs and one EJB JAR, tests deployment endpoints before and after checkpoint

### CODE REVIEW

**Comment by KeenanMcCarthy** [comment]
#build
#libby

**Review by dazavala — DISMISSED** [review]
Everything looks great, including the assembly of the EAR and WAR modules.

**Review by dazavala — APPROVED** [review]
LGTM

**Comment by KeenanMcCarthy** [comment]
#libby

**Pull request merged**
