### PR TITLE
Update to remove duplicate entries in buildpath and duplicate packages in bundles.

### PR DESCRIPTION
**Pull request by jhanders34**
- Update transform for io.openliberty.restfulWS.internal.globalhandler: don't use sub bundles since we don't need more than one bundle. We only need the transformed one.
- Update security audit code to remove duplicate classes in bundles
- Only include one bundle that includes packages in a bundle in the buildpath
- Remove explicit duplicate bundles in buildpath
- Move some classes to other bundles to not have two bundles both having the same package.
- Update test and fat projects that already have bundles added to the buildpath to not include them as well in the bnd.bnd buildpath list.

### CODE REVIEW

**Comment by jhanders34** [comment]
@OpenLiberty/message-reviewer this PR doesn't need review.  It is just deleting duplicate message files.  I am breaking apart the PR #21061.

**Comment by jhanders34** [comment]
#build

**Comment by jhanders34** [comment]
#libby #build

**Review by una-tapa — APPROVED** [review]
The code looks good. Thanks, Jared.  (Focused on security audit area)

**Review by neuwerk — APPROVED** [review]
JAX-WS/JAX-RS Changes look good to me! Thanks!!

**Review by tkburroughs — APPROVED** [review]
EJB changes LGTM

**Comment by una-tapa** [comment]
I had a chance to chat with @emilytee.  She would like to take a look.  Tagging her.

**Review by cbridgha — APPROVED** [review]
Good with changes - but let's discuss the bnd changes you referred to next week.(Just so I understand)

**Review by emilytee — APPROVED** [review]
Please make sure to run FULL audit fats, including those not under audit_fat (webcontainer.security, etc)

**Pull request merged**
