### PR TITLE
Merge multi-homed environment related changes into Liberty

### LINKED ISSUE #15943: Merge multi-homed environment related changes into Liberty

### PR DESCRIPTION
**Pull request by annaguri**
fixes #15943

### CODE REVIEW

**Comment by annaguri** [comment]
#build

**Comment by annaguri** [comment]
#run-libby-bot

**Comment by annaguri** [comment]
#build

**Comment by annaguri** [comment]
The build completed with errors, but they are not related to the changes in this PR. All SIP tests completed successfully.

**Comment by annaguri** [comment]
#run-libby-bot

**Review by TiborBeres — APPROVED** [review]
looks good

**Comment by annaguri** [comment]
#run-libby-bot

**Pull request merged**
