### PR TITLE
Update to bnd 7.0.0

### PR DESCRIPTION
**Pull request by fritze2**
- Update to bnd 7.0.0

### CODE REVIEW

**Comment by fritze2** [comment]
#build #pbbeta

**Comment by fritze2** [comment]
#build

**Comment by fritze2** [comment]
#build

**Comment by fritze2** [comment]
#build #pbbeta

**Comment by fritze2** [comment]
#build

**Comment by fritze2** [comment]
#build

**Comment by fritze2** [comment]
#build #pbbeta

**Comment by fritze2** [comment]
#build

**Comment by fritze2** [comment]
#build

**Comment by fritze2** [comment]
#build

**Comment by fritze2** [comment]
#build

**Comment by fritze2** [comment]
Manual respin of failing tests: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_m2wH8JkXEe6q84kI3KZ5lw

**Comment by jhanders34** [comment]
#libby #build

**Review by jhanders34 — APPROVED** [review]

**Pull request merged**
