### PR TITLE
Issue #4300: Update DefaultExtensionProcessor file.not.found default …

### PR DESCRIPTION
**Pull request by pnicolucci**

### CODE REVIEW

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
fixes #4300

**Comment by pnicolucci** [comment]
#build

**Comment by mhldr** [comment]
issues discussed in #was-liberty-ops caused the build to fail so I'm respinning this incase it's needed (you ***may*** already have the results you need but if not hopefully this respin will help)
#build

**Comment by pnicolucci** [comment]
#build spawn.fullfat.buckets=com.ibm.ws.webcontainer.servlet.4.0_fat,com.ibm.ws.webcontainer_fat,com.ibm.ws.webcontainer_fat_lWAS,com.ibm.ws.webcontainer_fat_servlet31,com.ibm.ws.webcontainer_fat_servlet31_webcontainerlWAS,com.ibm.ws.webcontainer_fat_servlet31toleration,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0.lWAS,com.ibm.ws.webcontainer.servlet.4.0_fat_tolerations.3.1

**Comment by pnicolucci** [comment]
#build spawn.fullfat.buckets=com.ibm.ws.webcontainer.servlet.4.0_fat,com.ibm.ws.webcontainer_fat,com.ibm.ws.webcontainer_fat_lWAS,com.ibm.ws.webcontainer_fat_servlet31,com.ibm.ws.webcontainer_fat_servlet31_webcontainerlWAS,com.ibm.ws.webcontainer_fat_servlet31toleration,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0.lWAS,com.ibm.ws.webcontainer.servlet.4.0_fat_tolerations.3.1

**Comment by pnicolucci** [comment]
#build spawn.fullfat.buckets=com.ibm.ws.webcontainer.servlet.4.0_fat,com.ibm.ws.webcontainer_fat,com.ibm.ws.webcontainer_fat_lWAS,com.ibm.ws.webcontainer_fat_servlet31,com.ibm.ws.webcontainer_fat_servlet31_webcontainerlWAS,com.ibm.ws.webcontainer_fat_servlet31toleration,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0.lWAS,com.ibm.ws.webcontainer.servlet.4.0_fat_tolerations.3.1

**Comment by pnicolucci** [comment]
#build spawn.fullfat.buckets=com.ibm.ws.webcontainer.servlet.4.0_fat,com.ibm.ws.webcontainer_fat,com.ibm.ws.webcontainer_fat_lWAS,com.ibm.ws.webcontainer_fat_servlet31,com.ibm.ws.webcontainer_fat_servlet31_webcontainerlWAS,com.ibm.ws.webcontainer_fat_servlet31toleration,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0.lWAS,com.ibm.ws.webcontainer.servlet.4.0_fat_tolerations.3.1

**Comment by pnicolucci** [comment]
#build spawn.fullfat.buckets=com.ibm.ws.webcontainer.servlet.4.0_fat,com.ibm.ws.webcontainer_fat,com.ibm.ws.webcontainer_fat_lWAS,com.ibm.ws.webcontainer_fat_servlet31,com.ibm.ws.webcontainer_fat_servlet31_webcontainerlWAS,com.ibm.ws.webcontainer_fat_servlet31toleration,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0.lWAS,com.ibm.ws.webcontainer.servlet.4.0_fat_tolerations.3.1

**Comment by pnicolucci** [comment]
#build spawn.fullfat.buckets=com.ibm.ws.webcontainer.servlet.4.0_fat,com.ibm.ws.webcontainer_fat,com.ibm.ws.webcontainer_fat_lWAS,com.ibm.ws.webcontainer_fat_servlet31,com.ibm.ws.webcontainer_fat_servlet31_webcontainerlWAS,com.ibm.ws.webcontainer_fat_servlet31toleration,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0.lWAS,com.ibm.ws.webcontainer.servlet.4.0_fat_tolerations.3.1

**Comment by pnicolucci** [comment]
#build spawn.fullfat.buckets=com.ibm.ws.webcontainer.servlet.4.0_fat,com.ibm.ws.webcontainer_fat,com.ibm.ws.webcontainer_fat_lWAS,com.ibm.ws.webcontainer_fat_servlet31,com.ibm.ws.webcontainer_fat_servlet31_webcontainerlWAS,com.ibm.ws.webcontainer_fat_servlet31toleration,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0.lWAS,com.ibm.ws.webcontainer.servlet.4.0_fat_tolerations.3.1

**Comment by pnicolucci** [comment]
#build spawn.fullfat.buckets=com.ibm.ws.webcontainer.servlet.4.0_fat,com.ibm.ws.webcontainer_fat,com.ibm.ws.webcontainer_fat_lWAS,com.ibm.ws.webcontainer_fat_servlet31,com.ibm.ws.webcontainer_fat_servlet31_webcontainerlWAS,com.ibm.ws.webcontainer_fat_servlet31toleration,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0.lWAS,com.ibm.ws.webcontainer.servlet.4.0_fat_tolerations.3.1

**Comment by pnicolucci** [comment]
#build spawn.fullfat.buckets=com.ibm.ws.webcontainer.servlet.4.0_fat,com.ibm.ws.webcontainer_fat,com.ibm.ws.webcontainer_fat_lWAS,com.ibm.ws.webcontainer_fat_servlet31,com.ibm.ws.webcontainer_fat_servlet31_webcontainerlWAS,com.ibm.ws.webcontainer_fat_servlet31toleration,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0.lWAS,com.ibm.ws.webcontainer.servlet.4.0_fat_tolerations.3.1

**Comment by pnicolucci** [comment]
#build spawn.fullfat.buckets=com.ibm.ws.webcontainer.servlet.4.0_fat,com.ibm.ws.webcontainer_fat,com.ibm.ws.webcontainer_fat_lWAS,com.ibm.ws.webcontainer_fat_servlet31,com.ibm.ws.webcontainer_fat_servlet31_webcontainerlWAS,com.ibm.ws.webcontainer_fat_servlet31toleration,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0.lWAS,com.ibm.ws.webcontainer.servlet.4.0_fat_tolerations.3.1

**Comment by pnicolucci** [comment]
#build spawn.fullfat.buckets=com.ibm.ws.webcontainer.servlet.4.0_fat,com.ibm.ws.webcontainer_fat,com.ibm.ws.webcontainer_fat_lWAS,com.ibm.ws.webcontainer_fat_servlet31,com.ibm.ws.webcontainer_fat_servlet31_webcontainerlWAS,com.ibm.ws.webcontainer_fat_servlet31toleration,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0.lWAS,com.ibm.ws.webcontainer.servlet.4.0_fat_tolerations.3.1

**Comment by pnicolucci** [comment]
#build spawn.fullfat.buckets=com.ibm.ws.webcontainer.servlet.4.0_fat,com.ibm.ws.webcontainer_fat,com.ibm.ws.webcontainer_fat_lWAS,com.ibm.ws.webcontainer_fat_servlet31,com.ibm.ws.webcontainer_fat_servlet31_webcontainerlWAS,com.ibm.ws.webcontainer_fat_servlet31toleration,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0.lWAS,com.ibm.ws.webcontainer.servlet.4.0_fat_tolerations.3.1

**Comment by pnicolucci** [comment]
#build

**Pull request merged**
