### PR TITLE
Fix ace

### PR DESCRIPTION
**Pull request by acdemyers**
Fixing Access control exception seen in csiv2 code.

### CODE REVIEW

**Comment by acdemyers** [comment]
#build

**Comment by acdemyers** [comment]
#build

**Comment by acdemyers** [comment]
#build

**Review by emilytee — APPROVED** [review]

**Comment by acdemyers** [comment]
#build

**Comment by acdemyers** [comment]
#build

**Comment by acdemyers** [comment]
#build

**Comment by tevans78** [comment]
#libby

**Pull request merged**
