### PR TITLE
Fix to set default values when not provided

### PR DESCRIPTION
**Pull request by acdemyers**
Fix PasswordUtil.passwordEncode(password, "hash") to return a hashed string.   The method was returning null due to missing information needed to create the hashed string.  The default values for the missing information was not being used.

### CODE REVIEW

**Comment by acdemyers** [comment]
fixes #18866

**Comment by acdemyers** [comment]
#build

**Comment by acdemyers** [comment]
#build

**Comment by acdemyers** [comment]
#libby

**Review by arkarkala — APPROVED** [review]

**Comment by acdemyers** [comment]
#build

**Pull request merged**
