### PR TITLE
Pause testing infinispan with Java 23 and plus

### PR DESCRIPTION
**Pull request by anjumfatima90**
for issue #29423

- [x] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [x] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [x] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

### CODE REVIEW

**Comment by anjumfatima90** [comment]
#build

**Comment by contbld** [comment]
Your personal pipeline request is at https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=5954ee0e-8cc2-4bf7-9dff-9454e0e34601

Target locations of links might be accessible only to IBM employees.

**Comment by contbld** [comment]
<h3>Code analysis and actions</h3>
DO NOT DELETE THIS COMMENT.

- 4 FAT files were changed, added, or removed.
 - Check that the build did not break the affected FAT suite(s).

**Comment by anjumfatima90** [comment]
#build

**Comment by contbld** [comment]
Your personal pipeline request is at https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=8ee7ee17-0534-4cdd-a5f2-bea2c7676285

Target locations of links might be accessible only to IBM employees.

**Comment by contbld** [comment]
<h3>Code analysis and actions</h3>
DO NOT DELETE THIS COMMENT.

- 7 FAT files were changed, added, or removed.
 - Check that the build did not break the affected FAT suite(s).

**Comment by contbld** [comment]
https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=5954ee0e-8cc2-4bf7-9dff-9454e0e34601 has errors/failures.

**Comment by contbld** [comment]
https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=8ee7ee17-0534-4cdd-a5f2-bea2c7676285 has errors/failures.

**Review by tjwatson — APPROVED** [review]

**Pull request merged**
