### PR TITLE
Use a retry method when querying the values from the Otel collector o…

### PR DESCRIPTION
**Pull request by Channyboy**
…ver the static 5 second wait

- [ ] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [ ] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [ ] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

################################################################################################

### CODE REVIEW

**Comment by Channyboy** [comment]
#build #libby
#spawn.fullfat.buckets=io.openliberty.http.monitor_fat

**Comment by Channyboy** [comment]
#build #libby
#spawn.fullfat.buckets=io.openliberty.http.monitor_fat

**Comment by contbld** [comment]
Your personal pipeline request is at https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=2c3c6af8-d452-47d9-8be2-73769b4b64a7

Target locations of links might be accessible only to IBM employees.

**Comment by contbld** [comment]
Your personal pipeline request is at https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=f6532fe6-5183-4afe-bfd3-f3a870a93a1e

Target locations of links might be accessible only to IBM employees.

**Comment by contbld** [comment]
<h3>Code analysis and actions</h3>
DO NOT DELETE THIS COMMENT.

- 6 FAT files were changed, added, or removed.
 - Check that the build did not break the affected FAT suite(s).

**Comment by contbld** [comment]
https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=2c3c6af8-d452-47d9-8be2-73769b4b64a7 completed successfully!

**Comment by contbld** [comment]
<h3>Code analysis and actions</h3>
DO NOT DELETE THIS COMMENT.

- 6 FAT files were changed, added, or removed.
 - Check that the build did not break the affected FAT suite(s).

**Comment by contbld** [comment]
https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=f6532fe6-5183-4afe-bfd3-f3a870a93a1e has errors/failures.

**Comment by Channyboy** [comment]
#build #libby

**Comment by contbld** [comment]
Your personal pipeline request is at https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=850294b9-f9f7-4ebe-a5a0-f4781d683bd5

Target locations of links might be accessible only to IBM employees.

**Comment by contbld** [comment]
Your personal pipeline request is at https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=942c46a3-0e45-4859-ac6e-dba1f27a2497

Target locations of links might be accessible only to IBM employees.

**Comment by contbld** [comment]
<h3>Code analysis and actions</h3>
DO NOT DELETE THIS COMMENT.

- 6 FAT files were changed, added, or removed.
 - Check that the build did not break the affected FAT suite(s).

**Comment by contbld** [comment]
https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=850294b9-f9f7-4ebe-a5a0-f4781d683bd5 completed successfully!

**Comment by contbld** [comment]
<h3>Code analysis and actions</h3>
DO NOT DELETE THIS COMMENT.

- 6 FAT files were changed, added, or removed.
 - Check that the build did not break the affected FAT suite(s).

**Comment by contbld** [comment]
https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=942c46a3-0e45-4859-ac6e-dba1f27a2497 completed successfully!

**Comment by contbld** [comment]
The build Channyboy-30094-20241107-2256
https://wasrtc.hursley.ibm.com:9443/jazz/resource/itemOid/com.ibm.team.build.BuildResult/_71HJkZ2UEe-M9e5esDPP_g
completed successfully!

**Review by tonyreigns — APPROVED** [review]
LGTM

**Comment by contbld** [comment]
The build Channyboy-30094-20241108-1725
https://wasrtc.hursley.ibm.com:9443/jazz/resource/itemOid/com.ibm.team.build.BuildResult/_OF4qQJ3tEe-M9e5esDPP_g
completed successfully!

**Pull request merged**
