### PR TITLE
Move MicroProfile 4.1 to GA

### PR DESCRIPTION
**Pull request by tevans78**
Move MicroProfile 4.1 and MP Health 3.1 to GA
Include MicroProfile 4.1 in appropriate OL GA packages
Re-instate an open tracing test that was incorrectly commented out

#build

### CODE REVIEW

**Review by pgunapal — APPROVED** [review]
LGTM

**Review by Emily-Jiang — APPROVED** [review]
LGTM!

**Comment by tevans78** [comment]
#build

**Comment by tevans78** [comment]
#run-libby-bot

**Pull request merged**
