### PR TITLE
Log server start failure in PostgreSQL tests

### PR DESCRIPTION
**Pull request by jonhawkes**
#build

### CODE REVIEW

**Review by neilgsyoung — APPROVED** [review]

**Comment by jonhawkes** [comment]
#build 
#run-liberty-bot

**Comment by jonhawkes** [comment]
#build 
#run-liberty-bot

**Comment by jonhawkes** [comment]
#build 
#run-libby-bot

**Comment by jonhawkes** [comment]
#build 
#run-libby-bot

**Comment by jonhawkes** [comment]
#build 
#run-libby-bot

**Comment by jonhawkes** [comment]
#build
#run-libby-bot

**Comment by jonhawkes** [comment]
#build
#run-libby-bot

**Comment by jonhawkes** [comment]
#build
#run-libby-bot

**Comment by jonhawkes** [comment]
#build
#run-libby-bot

**Comment by jonhawkes** [comment]
#build
#run-liberty-bot

**Comment by jonhawkes** [comment]
#build
#run-liberty-bot

**Comment by jonhawkes** [comment]
#build
#run-liberty-bot

**Comment by jonhawkes** [comment]
#run-liberty-bot

**Comment by jonhawkes** [comment]
#build
#run-liberty-bot

**Comment by jonhawkes** [comment]
#build
#run-liberty-bot

**Comment by jonhawkes** [comment]
#build
#run-libby-bot

**Pull request merged**
