### PR TITLE
update wsscxf saml.2 for java2sec

### PR DESCRIPTION
**Pull request by meiaus**
update com.ibm.ws.wssecurity_fat.wsscxf.saml.2 with java2sec

### CODE REVIEW

**Comment by meiaus** [comment]
#run-libby-bot

**Comment by meiaus** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.wssecurity_fat.wsscxf.saml.2

**Comment by meiaus** [comment]
The above PB https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_oxMQ4PGcEeu3WKcyevrZqg  is complete with errors from other FAT:

wsscxf.saml.2 fat passed:

image


and other FAT failed, which is out of concern from this PR:

image

But a new PB will be submitted to only specify the updated FAT to run.

**Review by arunavemulapalli — APPROVED** [review]

**Comment by meiaus** [comment]
Note:
Initial PB were submitted with the properties `global.debug.java2.sec`, which didn't enable java2 sec (per server messages.log).
The latest PB with `global.java2.sec` enabled java2 security as expected.

**Comment by meiaus** [comment]
#run-libby-bot

**Pull request merged**
