### PR TITLE
minor featureUtility improvements

### PR DESCRIPTION
**Pull request by jjiwooLim**
changing strings to constants
InstallConstants.SINGLE_JSON_FILE was repaced to InstallConstants.INSTALL_LOCAL_ESA in #23006

### CODE REVIEW

**Comment by jjiwooLim** [comment]
#build

**Comment by jjiwooLim** [comment]
IM build: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_S2pz0FCKEe2fv7PFprXZfA

**Comment by jjiwooLim** [comment]
[z/os build](https://github.ibm.com/websphere/WS-CD-Open/wiki/Requesting-a-Personal-Build-that-tests-against-zOS) failed becuase `fat.buckets.to.run=auto` when you can only request specific buckets. Otherwise, result looks good.

**Review by bensonlatibm — APPROVED** [review]
lgtm!

**Pull request merged**
