### PR TITLE
Add maximum connections to pmi

### PR DESCRIPTION
**Pull request by jmstephensgit**

### CODE REVIEW

**Comment by jmstephensgit** [comment]
#build

**Review by tabishop — DISMISSED** [review]

**Comment by jmstephensgit** [comment]
#build

**Comment by jmstephensgit** [comment]
#build

**Comment by jmstephensgit** [comment]
#build

**Comment by jmstephensgit** [comment]
#build

**Comment by jmstephensgit** [comment]
#build

**Review by tabishop — DISMISSED** [review]

**Comment by jmstephensgit** [comment]
#build

**Comment by jmstephensgit** [comment]
#build

**Comment by jmstephensgit** [comment]
#build

**Comment by jmstephensgit** [comment]
#build

**Comment by jmstephensgit** [comment]
#build

**Comment by jmstephensgit** [comment]
#build

**Review by tabishop — APPROVED** [review]

**Pull request closed without merging**
