### PR TITLE
Update repeat logic per java version

### PR DESCRIPTION
**Pull request by pnicolucci**
for #21200

### CODE REVIEW

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
Java 8 build: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_BbuRIP5QEey3m9ea3wJj4A

**Comment by zhang-ca** [comment]
Changes looks good, only the infinispan test servers require the feature replace.

**Review by zhang-ca — APPROVED** [review]
Feature replaced 5 servers looks good.

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
@zhang-ca  I'm going to close this PR I need you to try and run these repeats locally and debug a bit:

The rest naming seems pretty odd:

<html><body>


testRefreshInvalidation_EE10_FEATURES_EE9_FEATURES | 1 | 0 | 0 | 9 s | 5
-- | -- | -- | -- | -- | --
testInfinispanClassCastException_EE10_FEATURES_EE9_FEATURES | 1 | 0 | 0 | 0 s | 6
testRefreshInvalidation_EE10_FEATURES_EE9_FEATURES_CacheManager


</body>
</html>

To note there are repeats listed in some of the test classes as well such as: SessionCacheTimeoutTest.java.

**Comment by zhang-ca** [comment]
Thanks, will run the changes locally.

**Pull request closed without merging**
