### PR TITLE
Remove beta guard from JWT SSO FAT for enhanced algorithm usage

### PR DESCRIPTION
**Pull request by ayoho**

### CODE REVIEW

**Comment by ayoho** [comment]
#build

**Review by c00crane — APPROVED** [review]

**Comment by ayoho** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.security.jwtsso_fat

**Comment by ayoho** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.security.jwtsso_fat

**Comment by ayoho** [comment]
#libby
#build
#spawn.fullfat.buckets=com.ibm.ws.security.jwtsso_fat

**Comment by ayoho** [comment]
#libby
#build
#spawn.fullfat.buckets=com.ibm.ws.security.jwtsso_fat

**Pull request merged**
