### PR TITLE
Upgrade to use latest apache fileupload library

### PR DESCRIPTION
**Pull request by cbridgha**
Changes include:

Using open source version of fileupload - latest version.
standardize bnd refs to refer to wrapper bundle name that includes version (This pattern is used for other apache libs).

### CODE REVIEW

**Comment by cbridgha** [comment]
#build

**Comment by cbridgha** [comment]
#build

**Comment by wraschke** [comment]
#build

**Comment by wraschke** [comment]
#build

**Comment by wraschke** [comment]
Random comment.

**Comment by cbridgha** [comment]
#build

**Comment by cbridgha** [comment]
#build

**Comment by cbridgha** [comment]
#build

**Comment by cbridgha** [comment]
Closing this PR - starting over with another....

**Pull request closed without merging**
