### PR TITLE
Ensure restfulWSClient-3.0 works with XML resources with xmlBinding-3.0

### PR DESCRIPTION
**Pull request by andymc12**
We have tests that JAXB-annotated entities work with the JAX-RS _server_ implementation but none for the _client_.  This PR verifies that it works for JAX-RS 2.X and 3.X.  Prior to this change 2.X worked (but had to tests to verify) but 3.X needed a change to the auto-feature to ensure that the client worked with JAXB.

### CODE REVIEW

**Comment by andymc12** [comment]
#build

**Review by jim-krueger — APPROVED** [review]
LGTM

**Comment by andymc12** [comment]
Previous build seems to be hung and ran out of disk space, I'll try a new #build with my fingers crossed that whatever ran out of space has been fixed.

**Comment by andymc12** [comment]
Canceled that build and kicked off manual build https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_XCVh0DnPEeygsrM6ShizkA removing ".im." properties to avoid disk space issue.

**Pull request merged**
