### PR TITLE
Update to jdk-21.0.3

### PR DESCRIPTION
**Pull request by fritze2**

### CODE REVIEW

**Comment by fritze2** [comment]
!pbbeta

**Comment by fritze2** [comment]
!build
#spawn.fullfat.buckets=com.ibm.ws.grpc_fat,io.openliberty.springboot.fat30_fat,com.ibm.ws.springboot.fat20_fat

**Comment by wraschke** [comment]
#libby

**Comment by wraschke** [comment]
Another comment.

**Pull request closed without merging**
