### PR TITLE
Overlay for Oracle 23 Support

### PR DESCRIPTION
**Pull request by ajaypaul-ibm**
This PR contains the overaly for Oracle 23 support.
for #28155

### CODE REVIEW

**Comment by ajaypaul-ibm** [comment]
#build

**Comment by tkburroughs** [comment]
Run the failing FAT:
#build
#spawn.fullfat.buckets = com.ibm.ws.jpa.tests.eclipselink_jpa_3.0_fat, com.ibm.ws.jpa.tests.spec10.embeddable_jpa_3.0_fat

**Review by tkburroughs — DISMISSED** [review]

**Comment by ajaypaul-ibm** [comment]
#build
#spawn.fullfat.buckets = com.ibm.ws.jpa.tests.eclipselink_jpa_3.0_fat, com.ibm.ws.jpa.tests.spec10.embeddable_jpa_3.0_fat

**Comment by ajaypaul-ibm** [comment]
#libby

**Comment by tkburroughs** [comment]
#build
#spawn.fullfat.buckets = com.ibm.ws.jpa.tests.eclipselink_jpa_3.0_fat, com.ibm.ws.jpa.tests.spec10.embeddable_jpa_3.0_fat

**Review by tkburroughs — APPROVED** [review]

**Pull request merged**
