### PR TITLE
Fix FaultToleranceCDIExtension and downgrade warning

### PR DESCRIPTION
**Pull request by Azquelt**
* Fix the logic that determines when to add the FaultToleranceInterceptor
* Add a test to demonstrate the edge case where the interceptor was not added correctly
* Downgrade warnings in FaultToleranceCDIExtension to debug
* Fix default ID for FeatureReplacementAction

### CODE REVIEW

**Comment by Azquelt** [comment]
#build

**Comment by Azquelt** [comment]
#build

**Comment by mhldr** [comment]
issues discussed in #was-liberty-ops caused the build to fail so I'm respinning this incase it's needed (you ***may*** already have the results you need but if not hopefully this respin will help)
#build

**Comment by Azquelt** [comment]
No ID review needed because I've now removed the warning messages

**Comment by Azquelt** [comment]
#build

**Comment by Azquelt** [comment]
#build

**Comment by Azquelt** [comment]
#build

**Comment by Azquelt** [comment]
#build

**Comment by Azquelt** [comment]
#build

**Comment by Azquelt** [comment]
Failures in build appear to be unrelated.

**Pull request merged**
