### PR TITLE
Fix test failure in RTC 278913 (2nd try).

### PR DESCRIPTION
**Pull request by jvanhill**

### CODE REVIEW

**Comment by jvanhill** [comment]
#build

**Comment by jvanhill** [comment]
#libby
#build

**Comment by jvanhill** [comment]
#libby
#build

**Comment by jvanhill** [comment]
#build
#libby

**Comment by jvanhill** [comment]
There was an issue connecting to RTC during the build.

#build
#libby

**Comment by jvanhill** [comment]
#build

**Comment by jvanhill** [comment]
#build

**Comment by jvanhill** [comment]
#build
#libby

**Comment by jvanhill** [comment]
#build
#libby

**Comment by jvanhill** [comment]
#build
#libby

**Review by ayoho — APPROVED** [review]

**Pull request merged**
