### PR TITLE
Servlet 6.0: Remove SingleThreadModel support.

### PR DESCRIPTION
**Pull request by pmd1nh**
https://github.com/openliberty/open-liberty/issues/20643

### CODE REVIEW

**Comment by pmd1nh** [comment]
#build

**Review by pnicolucci — COMMENTED** [review]
Changes look good to me Phu, can you please change the commit message though as it talks about deprecation which isn't what is happening here.

**Comment by pmd1nh** [comment]
Changed commit message

#build

**Comment by pmd1nh** [comment]
one error in 

com.ibm.ws.ui.tool.explore_fat.gui.nd.rw.ws.allresources FAT tests | 12 | 0 | 1 |   |  
-- | -- | -- | -- | -- | --
com.ibm.ws.ui.tool.explore.fat.gui.nd.rw.allresources.tests.AllRuntimesTest | 1 | 0 | 1 | 26 s | 6
testAllRuntimes_withWebSocket | 1 | 0 | 1 | 26 s | 1

does not look relate to this change.

**Comment by pmd1nh** [comment]
#build

**Review by pnicolucci — APPROVED** [review]
Thanks for updating the commit message!

**Comment by pmd1nh** [comment]
#run-libby-bot

**Comment by pmd1nh** [comment]
some infrastructure errors but not relate to this change.  I'm going to merge this.

**Pull request merged**
