### PR TITLE
Added wait for server config update for hideMessage logging tests

### LINKED ISSUE #22518: Test Failure: com.ibm.ws.logging.fat.TestHideMessages.testRemovalHideMessageAttribute
RTC 292288

This seems to be an issue in zOS only.

```
testRemovalHideMessageAttribute:junit.framework.AssertionFailedError: 2022-08-23-10:45:02:725 Hidden Message CWWKF0012I should be seen in console.log
at com.ibm.ws.logging.fat.TestHideMessages.testRemovalHideMessageAttribute(TestHideMessages.java:131)
at componenttest.custom.junit.runner.FATRunner$1.evaluate(FATRunner.java:199)
at componenttest.custom.junit.runner.FATRunner$2.evaluate(FATRunner.java:352)
at componenttest.custom.junit.runner.FATRunner.run(FATRunner.java:173)
```

### PR DESCRIPTION
**Pull request by pgunapal**
fixes #22518
- On z/OS platforms, the server config update is slow to update, hence the test fails. Added a wait for config update.

### CODE REVIEW

**Comment by pgunapal** [comment]
#build

**Comment by pgunapal** [comment]
#build

**Comment by pgunapal** [comment]
z/OS build also passed: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_0_19oTu4Ee23g5vzbKf2xA&tab=com.ibm.team.build.web.ui.internal.editors.result.properties.PropertiesProvider

**Review by fmhwong — APPROVED** [review]
LGTM

**Comment by pgunapal** [comment]
#libby

**Pull request merged**
