### PR TITLE
Improve HTTP/2 server shutdown behavior

### LINKED ISSUE #19547: New HTTP/2 streams still accepted while server is closing
**Describe the bug**  
Due to an oversight in the fix made for https://github.com/OpenLiberty/open-liberty/issues/19193, HTTP/2 streams can still be accepted after the server shutdown process begins.

**Steps to Reproduce**  
During server shutdown, with a quiesce timeout active, have an HTTP/2 connection actively generating new streams. As long as new streams keep the connection open during the quiesce timeout, the quiesce warning message will be invoked. A similar warning will be logged:

```CWWKE1106W: 1 shutdown operations did not complete during the quiesce period.```

**Expected behavior**  
During quiesce, connections should begin closing down. In HTTP/1.1 this implies disabling keep-alive. In HTTP/2, sending a GOAWAY once quiesce begins.

**Diagnostic information:**  
 - OpenLiberty Version: 18.0.0.2+
 - Affected feature(s): servlet-4.0+, or users who have explicitly enabled HTTP/2
 - Java Version: N/A

### PR DESCRIPTION
**Pull request by wtlucy**
Fixes #19547

### CODE REVIEW

**Comment by wtlucy** [comment]
#spawn.fullfat.buckets=com.ibm.ws.ui_fat.gui,com.ibm.ws.ui.tool.javaBatch_fat.gui

**Comment by wtlucy** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.ui_fat.gui,com.ibm.ws.ui.tool.javaBatch_fat.gui

**Comment by wtlucy** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.ui_fat.gui,com.ibm.ws.ui.tool.javaBatch_fat.gui

**Comment by wtlucy** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.ui_fat.gui,com.ibm.ws.ui.tool.javaBatch_fat.gui

**Comment by wtlucy** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.ui_fat.gui,com.ibm.ws.ui.tool.javaBatch_fat.gui

**Comment by wtlucy** [comment]
#build

**Comment by wtlucy** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.ui_fat.gui,com.ibm.ws.ui.tool.javaBatch_fat.gui,com.ibm.ws.http2_fat,com.ibm.ws.grpc_fat

**Comment by wtlucy** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.ui.tool.javaBatch_fat.gui,com.ibm.ws.transport.http2_fat,com.ibm.ws.grpc_fat

**Comment by wtlucy** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.ui.tool.javaBatch_fat.gui,com.ibm.ws.transport.http2_fat,com.ibm.ws.grpc_fat

**Comment by wtlucy** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.ui.tool.javaBatch_fat.gui,com.ibm.ws.transport.http2_fat,com.ibm.ws.grpc_fat

**Comment by wtlucy** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.ui.tool.javaBatch_fat.gui,com.ibm.ws.transport.http2_fat,com.ibm.ws.grpc_fat

**Comment by wtlucy** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.ui.tool.javaBatch_fat.gui,com.ibm.ws.transport.http2_fat,com.ibm.ws.grpc_fat

**Comment by wtlucy** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.ui.tool.javaBatch_fat.gui,com.ibm.ws.transport.http2_fat,com.ibm.ws.grpc_fat

**Comment by wtlucy** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.ui.tool.javaBatch_fat.gui,com.ibm.ws.transport.http2_fat,com.ibm.ws.grpc_fat

**Review by mrsaldana — APPROVED** [review]

**Comment by wtlucy** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.ui.tool.javaBatch_fat.gui,com.ibm.ws.transport.http2_fat,com.ibm.ws.grpc_fat

**Comment by wtlucy** [comment]
#run-libby-bot

**Pull request merged**
