### PR TITLE
Squashed commit of the following:

### PR DESCRIPTION
**Pull request by tbitonti**
commit 5044291a9e6bc6fe319bcb2bd2bcc725a3dc2f9a
Author: Thomas Bitonti <bitonti@us.ibm.com>
Date:   Fri May 24 11:35:15 2019 -0400

    NLS pass

commit b2532b77bbf0423bf974506276c80fe0c5593398
Author: Thomas Bitonti <bitonti@us.ibm.com>
Date:   Fri May 24 09:42:22 2019 -0400

    Update java version for anno javaDoc

commit c79259e275975e0dac04b2394c0de6952773f461
Author: Thomas Bitonti <bitonti@us.ibm.com>
Date:   Thu May 23 12:20:41 2019 -0400

    Fix problem in new merge read code.

commit d7f85ee389c6fd2f04cfc34ff3630a309d803a83
Author: Thomas Bitonti <bitonti@us.ibm.com>
Date:   Wed May 22 12:55:28 2019 -0400

    Merge container data.

commit 4703ec716bbac7a953c7dfff03093a67bf693c37
Author: Thomas Bitonti <bitonti@us.ibm.com>
Date:   Tue May 21 16:07:16 2019 -0400

    Combine container data into a single file.

commit 29de2d371e162a6cb2608fe7d94c7be12a3a1013
Author: Thomas Bitonti <bitonti@us.ibm.com>
Date:   Thu May 16 15:34:43 2019 -0400

    Correct jandex no-write cases.  Record jandex package info.

commit f72bc47eb939394bfb10930c5cc4d58e5ed24202
Author: Thomas Bitonti <bitonti@us.ibm.com>
Date:   Wed May 15 18:50:43 2019 -0400

    Add option to skip writes when data is read from jandex

commit 923e3ab3bfe6acc761310a449fc70615737abb10
Author: Thomas Bitonti <bitonti@us.ibm.com>
Date:   Wed May 15 17:12:47 2019 -0400

    Fix NPE in JAXWS module info builder

commit e1e4c85e6d4f03f9d5d78965263ff5b3b9558f96
Author: Thomas Bitonti <bitonti@us.ibm.com>
Date:   Mon May 13 17:46:15 2019 -0400

    Enable WebSocket injection handler.

commit 09a39855966555524ab1d57fe663beddf3f05cd6
Author: Thomas Bitonti <bitonti@us.ibm.com>
Date:   Mon May 13 17:25:42 2019 -0400

    Enable additional collaborators and module init data.

commit 09ea49238cbf9a837c8f2f15684eed2d8360d901
Author: Thomas Bitonti <bitonti@us.ibm.com>
Date:   Sun May 12 08:38:25 2019 -0400

    Fix test localization.

commit 50de57a2b4c151d0ca1a9288cfbb2a9a424d3bbd
Author: Thomas Bitonti <bitonti@us.ibm.com>
Date:   Sat May 11 22:21:09 2019 -0400

    Fix cache messages.

commit 308b335d2ed39e69dcad99e199c9cc552d90dbed
Author: Thomas Bitonti <bitonti@us.ibm.com>
Date:   Sat May 11 19:55:41 2019 -0400

    Fix unit test comparison code; remove warnings. Adjust to run in eclipse.

commit 80ff66accf9f9f4f3acb1f1153daf327679304bb
Author: Thomas Bitonti <bitonti@us.ibm.com>
Date:   Fri May 10 12:41:40 2019 -0400

    Correct injection collectors.

commit e50812a87edf271e5473952d10b8204342ce73eb
Author: Thomas Bitonti <bitonti@us.ibm.com>
Date:   Wed May 8 13:39:07 2019 -0400

    Remove backup files from commit.

commit 209e0d99ba652040c5004675c7c25a1f0e5fd9a9
Author: Thomas Bitonti <bitonti@us.ibm.com>
Date:   Wed May 8 13:35:46 2019 -0400

    Remove implementation dependency from class source specification types.

commit 78c263b561e61f00081248a0f6e2f10a00a92393
Author: Thomas Bitonti <bitonti@us.ibm.com>
Date:   Tue May 7 05:53:47 2019 -0400

    More SPI fixes.

commit f4e0be1ddd15da5eb1e5f298f76e4c20a656815e
Author: Thomas Bitonti <bitonti@us.ibm.com>
Date:   Mon May 6 21:50:05 2019 -0400

    Add missing class.specification; adjust versions.

commit 2a3b1d5deeb8cb473684ab55d3426da5e2e67989
Author: Thomas Bitonti <bitonti@us.ibm.com>
Date:   Thu May 2 13:46:05 2019 -0400

    Fix injection collaborator NPE; remove deprecation warnings.

commit 8520f5d22606fa8013a01253408e8917a1a43e36
Author: Thomas Bitonti <bitonti@us.ibm.com>
Date:   Wed May 1 11:59:46 2019 -0400

    Put in missing feature package exports to anno and container.service

commit 15294d60ba7a6bf133f19369d11cffab537a6e8e
Author: Thomas Bitonti <bitonti@us.ibm.com>
Date:   Tue Apr 30 16:46:20 2019 -0400

    Fix mocks of annotation adapts.

commit c87d0532eecf161a3062a8f5cc3a00fe36a29e21
Author: Thomas Bitonti <bitonti@us.ibm.com>
Date:   Tue Apr 30 12:47:01 2019 -0400

    Update feature versions

commit f6fb69e76f7e879e72d1b295c7ca424328416b7a
Author: Thomas Bitonti <bitonti@us.ibm.com>
Date:   Tue Apr 30 11:21:17 2019 -0400

    Change cache enablement default to true.

commit a3a0c0fcfe9345313613b2d76165a222166a6be7
Author: Thomas Bitonti <bitonti@us.ibm.com>
Date:   Tue Apr 30 09:42:43 2019 -0400

    Correct container service versions.

commit d740b1cadde39b1bf3b26c2fe3398f6e9b077990
Author: Thomas Bitonti <bitonti@us.ibm.com>
Date:   Mon Apr 29 17:19:39 2019 -0400

    Javadoc and versioning fixes

commit f2efa2fc74342cfb1f79b0d92575cfdb7eed5aa7
Author: Thomas Bitonti <bitonti@us.ibm.com>
Date:   Fri Apr 26 13:04:48 2019 -0400

    Change back webcontainer security mock

commit 419879cb4e438613dbc814fe84066530bd45ed49
Author: Thomas Bitonti <bitonti@us.ibm.com>
Date:   Thu Apr 25 16:45:40 2019 -0400

    Add missing test classes

commit df3cbffe76b23af1399bc35682bab635b5d9520d
Author: Thomas Bitonti <bitonti@us.ibm.com>
Date:   Thu Apr 25 16:03:10 2019 -0400

    Add missing test dependency

commit 9c210934a36cb9400829e25eafc3d7bd0f7be540
Author: Thomas Bitonti <bitonti@us.ibm.com>
Date:   Thu Apr 25 15:48:25 2019 -0400

    Add missing test dependency

commit cbf25548e7c3dbcf59757536e8b4a4098f4d2da1
Author: Thomas Bitonti <bitonti@us.ibm.com>
Date:   Thu Apr 25 15:37:05 2019 -0400

    Add missing test dependency.

commit 5f6a0e843bed8a9316edb2ba3991491751d50640
Author: Thomas Bitonti <bitonti@us.ibm.com>
Date:   Thu Apr 25 14:21:43 2019 -0400

    Correct copyrights

commit 0228430e364e44eae753230f8e23f90d606e5879
Author: Thomas Bitonti <bitonti@us.ibm.com>
Date:   Wed Apr 24 14:39:40 2019 -0400

    Re-enable anno fat suite

commit f6c4e9f459a717da0a3d22060b2822f2774853d8
Author: Thomas Bitonti <bitonti@us.ibm.com>
Date:   Tue Apr 23 18:22:35 2019 -0400

    More anno fat fixes.

commit 00753169904af9f3f6385311225ba1ba1e25dd29
Author: Thomas Bitonti <bitonti@us.ibm.com>
Date:   Mon Apr 22 17:56:58 2019 -0400

    BigApp test fixes

commit 125f010f9e19583c3d57d10a0e310fe91ceb2f14
Author: Thomas Bitonti <bitonti@us.ibm.com>
Date:   Thu Apr 18 15:38:26 2019 -0400

    Working on BigAppTest.

commit 0fd951281423fd59d7cea40cec0d314ccf53e971
Author: Thomas Bitonti <bitonti@us.ibm.com>
Date:   Wed Apr 17 18:39:31 2019 -0400

    More anno caching fat fixes.

commit 572a6233555c74d41ddf465f52a74688187b4a55
Author: Thomas Bitonti <bitonti@us.ibm.com>
Date:   Tue Apr 16 17:30:54 2019 -0400

    Service and FAT corrections

commit f6000ce435cc0923c846b76083b98795c7212650
Author: Thomas Bitonti <bitonti@us.ibm.com>
Date:   Mon Apr 15 16:52:59 2019 -0400

    FAT adjustments

commit cfc40308f273b5f5068000ceacb7d0c5e36bc27e
Author: Thomas Bitonti <bitonti@us.ibm.com>
Date:   Fri Apr 12 17:47:53 2019 -0400

    Recover anno caching fat tests

commit 4c1a679777de86dc0660c9e40c583e3908a37d31
Author: Thomas Bitonti <bitonti@us.ibm.com>
Date:   Thu Apr 11 14:33:59 2019 -0400

    Unit test corrections.

commit 80b0ff614ca38ac1c2cad8769d26666d125b33c0
Author: Thomas Bitonti <bitonti@us.ibm.com>
Date:   Tue Apr 9 13:48:34 2019 -0400

    Merge recent changes to EARDeployedAppInfoFactoryImpl.java.

commit 6377a2007494426389163cf846e4ad1b7ff585f6
Author: Thomas Bitonti <bitonti@us.ibm.com>
Date:   Tue Apr 9 11:29:28 2019 -0400

    Anno consumer update

commit 2dc1aa8cf76f152603cbee5e23b62a4f94616ad1
Author: Thomas Bitonti <bitonti@us.ibm.com>
Date:   Tue Apr 9 10:22:37 2019 -0400

    Anno beta core plus services

Fix jandex property override.  Trim trace.

Jandex index fixes.  More trace tuning.

Coverage trace fixes.  Trace trimming.  Better jandex error catching.

Convert JSF annotations to use the new implementation.

Add option to write jandex indexes.

Add useJandexFormat case to anno FAT tests.

Remove API dependency on Jandex.

Enable binary and jandex format.  Lock in recommended defaults.  Fix unit and FAT tests.  Fix sharing problem with CDI.

Correct bad JaxRs 2.0 merge.

Tune info storage.

More tuning; warning removal.  Fix sparse reader bug.  Fix buffer test locations.  Add jandex index test cases.

Remove temporary coverage logging.  Correct JVM option to override jandex setting.

Add option to read jandex fully.

Read binary format completely.

Read jandex indexes fully.

Correct invalidation processing.  Correct jandex options processing.

Trim out unused options.

Correct overall result cache logic.

Fix defects found by FAT and UNIT testing.

Handle null container files.

### CODE REVIEW

**Comment by tbitonti** [comment]
#build

**Comment by tbitonti** [comment]
#build

**Comment by tbitonti** [comment]
#build

**Comment by tbitonti** [comment]
#build

**Comment by tbitonti** [comment]
#build

**Comment by tbitonti** [comment]
#build

**Comment by skasund** [comment]
L2 message review completed

**Comment by tbitonti** [comment]
#build

**Comment by tbitonti** [comment]
#build

**Pull request closed without merging**
