### PR TITLE
Update CDI API to 4.1.0.RC1, fix weld version refs

### PR DESCRIPTION
**Pull request by Azquelt**
* Update the CDI API jars to the latest version
* Fix some references to the Weld version which were missed in the last update (the correct version of weld was being included, but some manifests listed the wrong version)

### CODE REVIEW

**Comment by Azquelt** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.cdi.2.0_fat,com.ibm.ws.cdi.annotations_fat,com.ibm.ws.cdi.api_fat,com.ibm.ws.cdi.beansxml_fat,com.ibm.ws.cdi.beansxml.implicit_fat,com.ibm.ws.cdi.ejb_fat,com.ibm.ws.cdi.extension_fat,com.ibm.ws.cdi.jee_fat,com.ibm.ws.cdi.jndi_fat,com.ibm.ws.cdi.lifecycle_fat,com.ibm.ws.cdi.noncontextual_fat,com.ibm.ws.cdi.third.party_fat,com.ibm.ws.cdi.visibility_fat,com.ibm.ws.clientcontainer.cdi_fat,com.ibm.ws.ejbcontainer.cdi_fat,com.ibm.ws.jaxrs.2.0.cdi.1.2_fat,com.ibm.ws.jaxrs.2.1.cdi.2.0_fat,com.ibm.ws.jaxws.cdi_fat,com.ibm.ws.jbatch.cdi_fat,com.ibm.ws.jpa.tests.spec21.cdi_fat,com.ibm.ws.microprofile.faulttolerance.cdi_fat,io.openliberty.cdi.3.0.internal_fat,io.openliberty.cdi.4.0.internal_fat,io.openliberty.cdi.core_fat,io.openliberty.restfulWS.3.0.cdi.3.0_fat

**Comment by Azquelt** [comment]
Last push was to update the dependabot pom, it should be quick enough to be picked up by the personal builds that were started beforehand.

**Review by Yas-Franco — APPROVED** [review]

**Comment by Azquelt** [comment]
#libby

**Comment by Azquelt** [comment]
Failures in the build do not appear to be related to this change.

**Pull request merged**
