### PR TITLE
Delete recovery logs on clean shutdown in HA env

### LINKED ISSUE #17741: Delete recovery logs on  clean shutdown when in a peer recovery environment
In the absence of this functionality, log files (or database records) can persist when servers have been scaled-in in a containerized environment.

### PR DESCRIPTION
**Pull request by neilgsyoung**
fixes #17741

### CODE REVIEW

**Comment by neilgsyoung** [comment]
#build

**Comment by neilgsyoung** [comment]
#run-libby-bot

**Comment by neilgsyoung** [comment]
#build

**Comment by neilgsyoung** [comment]
#run-libby-bot

**Comment by neilgsyoung** [comment]
#build

**Comment by jonhawkes** [comment]
fixes #17787

**Comment by neilgsyoung** [comment]
#build

**Comment by neilgsyoung** [comment]
#run-libby-bot

**Comment by neilgsyoung** [comment]
#build

**Comment by neilgsyoung** [comment]
#run-libby-bot

**Comment by neilgsyoung** [comment]
#build

**Review by jonhawkes — APPROVED** [review]

**Pull request merged**
