### PR TITLE
add jakartaee8 wlp-platform values to features

### PR DESCRIPTION
**Pull request by rsherget**
- [x] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [x] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [x] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

For the featurelist and some doc purposes, add jakartaee-8.0 to all features that have javaee-8.0 as part of their wlp-platform value.

### CODE REVIEW

**Comment by rsherget** [comment]
#build

**Review by hlhoots — APPROVED** [review]
LGTM pending a good build.

**Comment by rsherget** [comment]
#build

**Comment by rsherget** [comment]
#build

**Comment by websterc87** [comment]
#build

**Comment by rsherget** [comment]
Build https://wasrtc.hursley.ibm.com:9443/jazz/resource/itemOid/com.ibm.team.build.BuildResult/_59GEkKwlEe-5Tq7vYMk6IA completed with no errors. Merging

**Pull request merged**
