### PR TITLE
Bump libthrift to 0.14.1 in the MP OT bundles

### LINKED ISSUE #16769: Update libthrift to the 0.14.1
MP OT Jaegar FAT is using libthrift 0.13.0.  Security vulnerabilities were reported in this version.  Update to latest 0.14.1.

### PR DESCRIPTION
**Pull request by Channyboy**
#build  
fixes #16769

Two OT fats use it:
- `com.ibm.ws.microprofile.opentracing.jaeger_fat`
- `io.openliberty.microprofile.opentracing.2.0.internal.jaeger_fat`
Updating libthrift to 0.14.1 requires updating the related jaeger-* libraries used there to 1.6.0 due to API changes in libthrift.
The jaeger lib changes to 1.6.0 requires the opentracing API to be a 0.33.0

This is an issue for `com.ibm.ws.microprofile.opentracing.jaeger_fat` as it strictcly depends/uses OT API 0.31.0.
As a result this FAT will not be updated as this is FAT only.

Furthermore, the FAT classes for `io.openliberty.microprofile.opentracing.2.0.internal.jaeger_fat` were modified to ensure proper server shutdown after the FAT has executed.

The sl4j dependency was bumped to the appropriate level as well.

### CODE REVIEW

**Review by fmhwong — CHANGES_REQUESTED** [review]
server.xml has a reference to the jar file and they need to be changed too.

**Comment by Channyboy** [comment]
#build 
#run-libby-bot

**Comment by Channyboy** [comment]
#build

**Review by fmhwong — APPROVED** [review]
LGTM

**Pull request merged**
