### PR TITLE
Download built from source jars from wasliberty-source-built-maven-local

### PR DESCRIPTION
**Pull request by fritze2**

### CODE REVIEW

**Comment by fritze2** [comment]
#build

**Comment by fritze2** [comment]
#build

**Comment by fritze2** [comment]
#build

**Comment by fritze2** [comment]
#build

**Comment by cbridgha** [comment]
Rebuild with all jars uploaded:  https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_C8CHAIoTEeqB0LE2SMkmyg

**Comment by fritze2** [comment]
#build
Testing these dependencies:
```
com.fasterxml:classmate:1.3.4
com.google.code.gson:gson:2.8.2
com.googlecode.json-simple:json-simple:1.1.1
com.sun.mail:javax.mail:1.5.6
com.sun.mail:javax.mail:1.6.2
com.sun.org.apache.xml.internal:resolver:20050927
com.sun.xml.stream.buffer:streambuffer:1.5.3
commons-beanutils:commons-beanutils:1.9.4
commons-codec:commons-codec:1.10
commons-fileupload:commons-fileupload:1.3.3
commons-io:commons-io:2.6
io.reactivex.rxjava2:rxjava:2.2.13
io.smallrye.reactive:smallrye-reactive-converter-api:1.0.10
io.smallrye.reactive:smallrye-reactive-messaging-provider:1.0.8
io.smallrye.reactive:smallrye-reactive-streams-operators:1.0.10
javax.activation:activation:1.1
javax.annotation:javax.annotation-api:1.2
javax.annotation:javax.annotation-api:1.3
javax.annotation:javax.annotation-api:1.3.2
javax.inject:javax.inject:1
javax.interceptor:javax.interceptor-api:1.2
javax.jms:javax.jms-api:2.0
javax.persistence:javax.persistence-api:2.2
javax.resource:javax.resource-api:1.7
javax.security.auth.message:javax.security.auth.message-api:1.1
javax.servlet:javax.servlet-api:4.0.0
javax.validation:validation-api:2.0.1.Final
net.jodah:failsafe:1.0.4
org.apache.aries.jmx:org.apache.aries.jmx.api:1.1.5
org.apache.aries.jmx:org.apache.aries.jmx.core.whiteboard:1.1.5
org.apache.aries.jndi:org.apache.aries.jndi.api:1.1.0
org.apache.aries:org.apache.aries.util:1.1.3
org.apache.commons:commons-weaver-processor:1.1
org.apache.cxf:cxf-rt-bindings-soap:2.6.2
org.apache.cxf:cxf-rt-core:2.6.2
org.apache.cxf:cxf-rt-databinding-jaxb:2.6.2
org.apache.cxf:cxf-rt-frontend-simple:2.6.2
org.apache.cxf:cxf-rt-rs-mp-client:3.2.6
org.apache.cxf:cxf-rt-rs-service-description:3.3.0
org.apache.cxf:cxf-rt-rs-sse:3.3.0
org.apache.cxf:cxf-rt-transports-http-hc:3.3.0
org.apache.cxf:cxf-rt-ws-addr:2.6.2
org.apache.cxf:cxf-tools-common:3.3.0
org.apache.cxf:cxf-tools-validator:2.6.2
org.apache.cxf:cxf-tools-wadlto-jaxrs:3.3.0
org.apache.geronimo.specs:geronimo-osgi-registry:1.1
org.apache.geronimo.specs:geronimo-validation_1.0_spec:1.1
org.apache.httpcomponents:httpasyncclient:4.1.4
org.apache.httpcomponents:httpclient:4.5.10
org.apache.httpcomponents:httpcore-nio:4.4.12
org.apache.httpcomponents:httpcore:4.4.12
org.apache.mina:mina-core:2.1.3
org.apache.myfaces.buildtools:myfaces-builder-annotations:1.0.9
org.apache.neethi:neethi:3.0.2
org.bitbucket.b_c:jose4j:0.5.1
org.bitbucket.b_c:jose4j:0.6.4
org.bitbucket.b_c:jose4j:0.6.5
org.bouncycastle:bcpkix-jdk15on:1.61
org.hibernate.validator:hibernate-validator-cdi:6.1.1.Final
org.jboss.classfilewriter:jboss-classfilewriter:1.1.2.Final
org.jboss.classfilewriter:jboss-classfilewriter:1.2.4.Final
org.jboss.jdeparser:jdeparser:1.0.0.Final
org.jboss.logging:jboss-logging:3.3.2.Final
org.jvnet.mimepull:mimepull:1.9.7
org.osgi:org.osgi.core:4.2.0
org.shredzone.acme4j:acme4j-client:2.7
org.shredzone.acme4j:acme4j-utils:2.7
org.springframework:spring-aop:4.3.13.RELEASE
org.springframework:spring-context:4.3.13.RELEASE
org.springframework:spring-expression:4.3.13.RELEASE
org.springframework:spring-web:4.3.13.RELEASE
```

**Comment by fritze2** [comment]
#build

**Comment by fritze2** [comment]
#help

**Comment by fritze2** [comment]
#build
Testing these dependencies:
```
com.fasterxml:classmate:1.3.4
com.google.code.gson:gson:2.8.2
com.google.guava:guava:27.0.1-android
com.googlecode.json-simple:json-simple:1.1.1
com.sun.org.apache.xml.internal:resolver:20050927
com.sun.xml.stream.buffer:streambuffer:1.5.3
commons-beanutils:commons-beanutils:1.9.4
commons-codec:commons-codec:1.4
commons-digester:commons-digester:1.8
commons-fileupload:commons-fileupload:1.3.3
commons-io:commons-io:2.6
io.reactivex.rxjava2:rxjava:2.2.13
io.smallrye.reactive:smallrye-reactive-converter-api:1.0.10
io.smallrye.reactive:smallrye-reactive-messaging-provider:1.0.8
javax.activation:activation:1.1
javax.annotation:javax.annotation-api:1.2
javax.annotation:javax.annotation-api:1.3.2
javax.enterprise:cdi-api:1.2
javax.enterprise:cdi-api:2.0
javax.inject:javax.inject:1
javax.interceptor:javax.interceptor-api:1.2
javax.jms:javax.jms-api:2.0
javax.resource:javax.resource-api:1.7
javax.security.auth.message:javax.security.auth.message-api:1.1
javax.servlet:javax.servlet-api:4.0.0
javax.validation:validation-api:2.0.1.Final
net.jodah:failsafe:1.0.4
org.apache.aries.jmx:org.apache.aries.jmx.api:1.1.5
org.apache.aries.jmx:org.apache.aries.jmx.core.whiteboard:1.1.5
org.apache.aries.jndi:org.apache.aries.jndi.api:1.1.0
org.apache.aries:org.apache.aries.util:1.1.3
org.apache.commons:commons-weaver-processor:1.1
org.apache.cxf:cxf-rt-bindings-soap:2.6.2
org.apache.cxf:cxf-rt-core:2.6.2
org.apache.cxf:cxf-rt-databinding-jaxb:2.6.2
org.apache.cxf:cxf-rt-frontend-simple:2.6.2
org.apache.cxf:cxf-rt-rs-mp-client:3.2.6
org.apache.cxf:cxf-rt-rs-service-description:3.3.0
org.apache.cxf:cxf-rt-rs-sse:3.3.0
org.apache.cxf:cxf-rt-transports-http-hc:3.3.0
org.apache.cxf:cxf-rt-ws-addr:2.6.2
org.apache.cxf:cxf-tools-common:3.3.0
org.apache.cxf:cxf-tools-validator:3.3.3
org.apache.cxf:cxf-tools-wadlto-jaxrs:3.3.0
org.apache.felix:org.apache.felix.gogo.command:0.16.0
org.apache.geronimo.specs:geronimo-osgi-registry:1.1
org.apache.geronimo.specs:geronimo-validation_1.0_spec:1.1
org.apache.httpcomponents:httpasyncclient:4.1.4
org.apache.httpcomponents:httpclient:4.5.10
org.apache.httpcomponents:httpcore-nio:4.4.12
org.apache.httpcomponents:httpcore:4.4.12
org.apache.mina:mina-core:2.1.3
org.apache.myfaces.buildtools:myfaces-builder-annotations:1.0.9
org.apache.neethi:neethi:3.0.2
org.bitbucket.b_c:jose4j:0.5.1
org.bitbucket.b_c:jose4j:0.6.4
org.bitbucket.b_c:jose4j:0.6.5
org.bouncycastle:bcpkix-jdk15on:1.61
org.jboss.classfilewriter:jboss-classfilewriter:1.2.4.Final
org.jboss.jdeparser:jdeparser:1.0.0.Final
org.jboss.logging:jboss-logging:3.3.2.Final
org.jvnet.mimepull:mimepull:1.9.7
org.osgi:org.osgi.core:4.2.0
org.shredzone.acme4j:acme4j-utils:2.7
org.springframework:spring-expression:4.3.13.RELEASE
org.springframework:spring-web:4.3.13.RELEASE
```

**Comment by cbridgha** [comment]
#build

**Comment by fritze2** [comment]
#build

**Comment by fritze2** [comment]
#build

**Comment by fritze2** [comment]
#run-libby-bot

**Pull request merged**
