### PR TITLE
New pattern for wsat tests

### PR DESCRIPTION
**Pull request by jonhawkes**
#build

### CODE REVIEW

**Comment by jonhawkes** [comment]
#build

**Comment by jonhawkes** [comment]
#build

**Comment by jonhawkes** [comment]
#build

**Comment by jonhawkes** [comment]
#build

**Comment by jonhawkes** [comment]
#libby #build

**Review by neilgsyoung — DISMISSED** [review]
Looks good

**Comment by jonhawkes** [comment]
#libby #build

**Comment by jonhawkes** [comment]
#libby #build

**Comment by jonhawkes** [comment]
#libby #build

**Comment by jonhawkes** [comment]
#build

**Comment by jonhawkes** [comment]
#build

**Comment by jonhawkes** [comment]
#libby #build

**Review by neilgsyoung — APPROVED** [review]
Looks good

**Pull request merged**
