### PR TITLE
Issue #20306: Update netty dependencies to 4.1.75.Final

### LINKED ISSUE #20306: Bump netty dependencies to 4.1.75.Final
Describe the bug
Current Netty components in Open Liberty are of the version 4.1.72.Final released in December 2021. The latest version 4.1.75.Final contains various bug fixes and improvements over the current version.

Steps to Reproduce
No steps to reproduce.

Expected behavior
Open Liberty stays up to date with upstream fixes and improvements.

Additional context

Pull in the new Netty 4.1.75 release (updating from 4.1.72) which has many bug fixes and improvements: https://netty.io/news/2022/03/10/4-1-75-Final.html

### PR DESCRIPTION
**Pull request by pnicolucci**
fixes #20306

### CODE REVIEW

**Comment by pnicolucci** [comment]
#build

**Review by mrsaldana — APPROVED** [review]
LGTM

**Review by isaacrivriv — APPROVED** [review]
Changes look good, thanks!

**Comment by pnicolucci** [comment]
#libby #build

**Review by mrsaldana — APPROVED** [review]

**Review by isaacrivriv — APPROVED** [review]
LGTM thanks!

**Pull request merged**
