### PR TITLE
changed install-to location from core to usr for userfeature

### PR DESCRIPTION
**Pull request by rampras3**

### CODE REVIEW

**Comment by rampras3** [comment]
@OpenLiberty/reviewer

**Comment by ewhoch** [comment]
You're not listed in the org, and your github profile has little or no information. Our labeling bot is having issues at the moment, so if you are an IBMer please make your github profile more complete as right now it is fairly empty, and look to make sure you've accepted the necessary invite into the organization. If not, please wait while we get our labeling figured out with instructions for CLA signing as needed.

**Comment by rampras3** [comment]
issue: #285

**Comment by rampras3** [comment]
personal build: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_QKdQwKOOEeee-IeTp-fxEQ&tab=com.ibm.team.build.web.ui.internal.editors.result.test.TestProvider

**Pull request merged**
