### PR TITLE
XML-Binding fix in CXF 3.2

### PR DESCRIPTION
**Pull request by neuwerk**
This pull request address two issues:
1.) Allows CXF to properly check for jakarta.xml.binding.JAXBElement
2.) Prevents CXF from flooding  messages.log with to much "Create Service ...." trace

### CODE REVIEW

**Comment by neuwerk** [comment]
#build

**Comment by neuwerk** [comment]
#18442

**Comment by neuwerk** [comment]
#build

**Review by BerksanAtes — APPROVED** [review]
Looks good!

**Comment by neuwerk** [comment]
#run-libby-bot

**Pull request merged**
