### PR TITLE
load on startup a wsoc fvt servlet

### PR DESCRIPTION
**Pull request by billw1024**

### CODE REVIEW

**Comment by billw1024** [comment]
fixes #14728

**Comment by billw1024** [comment]
#build #spawn.fullfat.buckets=io.openliberty.wsoc.internal_fat

**Review by isaacrivriv — APPROVED** [review]
Looks good to me! Thanks!

**Comment by billw1024** [comment]
#build #spawn.fullfat.buckets=io.openliberty.wsoc.internal_fat

**Comment by billw1024** [comment]
#build #spawn.fullfat.buckets=io.openliberty.wsoc.internal_fat

**Comment by billw1024** [comment]
#run-libby-bot

**Pull request merged**
