### PR TITLE
Issue #16191 workaround OpenJDK15 build issue

### PR DESCRIPTION
**Pull request by srl295**
- bump biz.aQute.bnd Gradle plugin to version 5.1.2
- per: https://github.com/gradle/gradle/issues/13628#issuecomment-672541910
Fixes: #16191

### CODE REVIEW

**Comment by srl295** [comment]
cla's in the mail…

**Comment by srl295** [comment]
> I think this counts as a trivial change ... no CLA needed for this one.

great… but maybe more to come!

**Comment by gjwatts** [comment]
@srl295 This should be resolved by issue #16217.  Would you like to keep this issue open any longer?

**Comment by srl295** [comment]
Nope let’s close as fixed

**Comment by gjwatts** [comment]
@srl295 Closing request as fixed by PR #16217.  Thank you again for taking the time to make us aware of this problem!

**Pull request closed without merging**
