### PR TITLE
Jsf22 misc tests ee10

### PR DESCRIPTION
**Pull request by pnicolucci**
for https://github.com/OpenLiberty/open-liberty/issues/22369

### CODE REVIEW

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
java 17 build: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_nTt8QJvpEe25i_tSaDMOdg

**Comment by pnicolucci** [comment]
Java 17 tests were successful

**Review by isaacrivriv — APPROVED** [review]
Looks good, thanks for working on this!

**Pull request merged**
