### PR TITLE
grpc refresh guava

### PR DESCRIPTION
**Pull request by hutchig**
Refresh Google guava (Java utils) references' version.

### CODE REVIEW

**Comment by hutchig** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.grpc_fat

**Comment by hutchig** [comment]
#libbybot

**Comment by hutchig** [comment]
#build

**Review by rickettmwork — DISMISSED** [review]
Approved pending successful pb

**Comment by hutchig** [comment]
#build

**Comment by hutchig** [comment]
#build

**Comment by hutchig** [comment]
#build

**Comment by hutchig** [comment]
#build

**Comment by hutchig** [comment]
#build

**Comment by hutchig** [comment]
e

**Comment by hutchig** [comment]
#build

**Comment by hutchig** [comment]
#libbybot

**Comment by hutchig** [comment]
Issue appears to be:
[6/27/23, 21:51:41:402 PDT] 0000001c id=00000000 LogService-80-io.openliberty.grpc.1.0.internal.client        E CWWKE0702E: Could not resolve module: io.openliberty.grpc.1.0.internal.client [80]
  Unresolved requirement: Import-Package: com.google.common.collect; version="[32.0.0,33.0.0)"
    -> Export-Package: com.google.common.collect; bundle-symbolic-name="io.openliberty.grpc.1.0.internal.common"; bundle-version="1.0.79.202306271302"; version="32.0.1"; uses:="com.google.common.base,javax.annotation,org.checkerframework.checker.nullness.qual"                                              
       io.openliberty.grpc.1.0.internal.common [79]
         Unresolved requirement: Import-Package: javax.annotation.meta; version="[3.0.0,4.0.0)"
  Unresolved requirement: Import-Package: com.google.common.base; version="[32.0.0,33.0.0)"
    -> Export-Package: com.google.common.base; bundle-symbolic-name="io.openliberty.grpc.1.0.internal.common"; bundle-version="1.0.79.202306271302"; version="32.0.1"; uses:="javax.annotation,org.checkerframework.checker.nullness.qual"

**Comment by hutchig** [comment]
Also present on Laptop in equinox.log of local servers
image

**Comment by hutchig** [comment]
!SESSION 2023-06-27 15:24:43.439 -----------------------------------------------
eclipse.buildId=unknown
java.fullversion=17.0.7+7
JRE 17 Mac OS X amd64-64-Bit Compressed References 20230418_450 (JIT enabled, AOT enabled)
OpenJ9   - d57d05932
OMR      - 855813495
JCL      - 9d7a231edbc based on jdk-17.0.7+7
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_GB

!ENTRY io.openliberty.grpc.1.0.internal.common.jakarta 4 0 2023-06-27 15:24:43.440
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: io.openliberty.grpc.1.0.internal.common.jakarta [93]
  Unresolved requirement: Import-Package: javax.annotation.meta; version="[3.0.0,4.0.0)"

        at org.eclipse.osgi.container.Module.start(Module.java:463)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:1847)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:857)

!ENTRY io.openliberty.grpc.1.0.internal.client.jakarta 4 0 2023-06-27 15:24:43.454
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: io.openliberty.grpc.1.0.internal.client.jakarta [94]
  Unresolved requirement: Import-Package: com.google.common.collect; version="[32.0.0,33.0.0)"
    -> Export-Package: com.google.common.collect; bundle-symbolic-name="io.openliberty.grpc.1.0.internal.common.jakarta"; bundle-version="1.0.79.202306271034"; version="32.0.1"; uses:="com.google.common.base,jakarta.annotation,org.checkerframework.checker.nullness.qual"
       io.openliberty.grpc.1.0.internal.common.jakarta [93]
         Unresolved requirement: Import-Package: javax.annotation.meta; version="[3.0.0,4.0.0)"
  Unresolved requirement: Import-Package: com.google.common.base; version="[32.0.0,33.0.0)"
    -> Export-Package: com.google.common.base; bundle-symbolic-name="io.openliberty.grpc.1.0.internal.common.jakarta"; bundle-version="1.0.79.202306271034"; version="32.0.1"; uses:="jakarta.annotation,org.checkerframework.checker.nullness.qual"

        at org.eclipse.osgi.container.Module.start(Module.java:463)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:1847)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:857)
~

**Comment by hutchig** [comment]
#build

**Comment by hutchig** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.grpc_fat

**Comment by hutchig** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.grpc_fat

**Comment by hutchig** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.grpc_fat

**Comment by hutchig** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.grpc_fat

**Comment by hutchig** [comment]
#build

**Review by rickettmwork — APPROVED** [review]

**Comment by hutchig** [comment]
#libbybot

**Pull request merged**
