### PR TITLE
Update TCK projects

### PR DESCRIPTION
**Pull request by tevans78**
This PR is an update for clarity, ease of use and consistency ... should not change anything functionally

### CODE REVIEW

**Comment by tevans78** [comment]
#build

**Comment by tevans78** [comment]
#build

**Comment by tevans78** [comment]
#build

**Comment by tevans78** [comment]
#build

**Review by benjamin-confino — APPROVED** [review]

**Comment by tevans78** [comment]
Last commit was not in the PB but I need to get this merged in, getting too many conflicts :-(
#libby

**Comment by tevans78** [comment]
#libby

**Pull request merged**
