### PR TITLE
remove synchronize keyword from serverStopping method

### LINKED ISSUE #10510: Thread fails to complete during the quiesce period
Timeout is occurring when one thread waits for the serverStopping method in GeneratePluginConfigMBean.java as a plugin-cfg.xml is generated. Need to remove unnecessary synchronized keyword from the serverStopping method located in GeneratePluginConfigMBean.

### PR DESCRIPTION
**Pull request by DaBusyB**
fixes #10510 
thread can't enter serverStopping while plugin generation is in process in another thread

### CODE REVIEW

**Comment by DaBusyB** [comment]
#build

**Comment by DaBusyB** [comment]
#build

**Comment by volosied** [comment]
removed comments since they pointed to difference builds.

**Comment by volosied** [comment]
Two errors in the build, but neither one is relevant to our change.

**Comment by volosied** [comment]
#run-libby-bot

**Comment by volosied** [comment]
@pnicolucci  If you don't have any concerns here, can you approve this PR?

**Pull request merged**
