### PR TITLE
Change how web fragment absolute ordering test app is updated

### PR DESCRIPTION
**Pull request by jimblye**

### CODE REVIEW

**Review by tbitonti — APPROVED** [review]

**Comment by jimblye** [comment]
#build

**Comment by jimblye** [comment]
#libby

**Comment by jimblye** [comment]
#libby

**Review by tbitonti — APPROVED** [review]

**Review by cbridgha — APPROVED** [review]
LGTM

**Comment by cbridgha** [comment]
#libby

**Pull request merged**
