### PR TITLE
Jwks timeout tests fail on really slow machines

### PR DESCRIPTION
**Pull request by c00crane**
The test case that tests the default JWKs read and connection timeout is failing on slow Windows machines - we'll skip this test on Windows.

### CODE REVIEW

**Comment by c00crane** [comment]
#build
#spawn.fullfat.buckets=io.openliberty.security.jakartasec.3.0.internal_fat,io.openliberty.security.jakartasec.3.0.internal_fat.config.1,io.openliberty.security.jakartasec.3.0.internal_fat.config.2,io.openliberty.security.jakartasec.3.0.internal_fat.logout,io.openliberty.security.jakartasec.3.0.internal_fat.refresh

**Comment by c00crane** [comment]
#build
#spawn.fullfat.buckets=io.openliberty.security.jakartasec.3.0.internal_fat.config.2
#libby

**Review by teddyjtorres — APPROVED** [review]

**Comment by c00crane** [comment]
#build
#spawn.fullfat.buckets=io.openliberty.security.jakartasec.3.0.internal_fat.config.2

**Comment by c00crane** [comment]
#build
#spawn.fullfat.buckets=io.openliberty.security.jakartasec.3.0.internal_fat.config.2

**Comment by c00crane** [comment]
#build
#spawn.fullfat.buckets=io.openliberty.security.jakartasec.3.0.internal_fat.config.2
#libby

**Review by teddyjtorres — APPROVED** [review]

**Pull request merged**
