### PR TITLE
Update MP Health 3.1 to final API spec release

### LINKED ISSUE #17318: Update MicroProfile Health 3.1 API+TCK to official release spec version
Currently, mpHealth-3.1 is using the RC3 APIs and TCKs, need to update it to the official MicroProfile component spec release version.

### PR DESCRIPTION
**Pull request by pgunapal**
fixes #17318

### CODE REVIEW

**Comment by pgunapal** [comment]
#build

**Review by fmhwong — APPROVED** [review]
LGTM

**Comment by pgunapal** [comment]
#build

**Comment by pgunapal** [comment]
#libby

**Pull request merged**
