### PR TITLE
Check versionRange for null before using it

### LINKED ISSUE #20211: Check for null version passed in when selecting bundles from runtimes
When an ifix is created for the explore and java batch tools, the version is missing in each of the tool feature manifest files.

**Steps to Reproduce**  
With an ifix build, Admin Center would not be able to load any tools in the default settings.

**Expected behavior**  
Expect Admin Center to load the default tools.

**Diagnostic information:**  
 - OpenLiberty Version: since 21.0.0.4
 - Affected feature: adminCenter-1.0

**Additional context** 
This only affects ifix build test result.

### PR DESCRIPTION
**Pull request by lavenal**
fixed #20211

### CODE REVIEW

**Comment by lavenal** [comment]
#build

**Review by cbridgha — APPROVED** [review]
LGTM

**Comment by lavenal** [comment]
The earlier build has run for more than a day and hanging on 99% complete . Will resubmit another build.

**Comment by lavenal** [comment]
#build

**Comment by lavenal** [comment]
#build

**Comment by lavenal** [comment]
All the kernel tests passed.

**Pull request merged**
