### PR TITLE
Remove serverTTLAttribute from ldapRegistry-3.0

### PR DESCRIPTION
**Pull request by agiridharan**
Remove the 'serverTTLAttribute' from ldapRegistry-3.0 feature since it is unused and does not make sense given that the LDAP cache implementation is a 3 level cache where no individual entry has its own TTL.

### CODE REVIEW

**Comment by agiridharan** [comment]
#build

**Comment by agiridharan** [comment]
#build

**Comment by agiridharan** [comment]
fixes #4789

**Comment by jvanhill** [comment]
Closing this PR as @agiridharan has created a new PR.

**Pull request closed without merging**
