### PR TITLE
Issue #13096: Add MDB RA FAT

### PR DESCRIPTION
**Pull request by tkburroughs**
Added message-driven bean FAT using a test resource adapter to
verify various aspects of message delivery.

Also updated the shared library support in Simplicity to handle
shared libraries with multiple filesets.

for #13096

### CODE REVIEW

**Comment by tkburroughs** [comment]
#build

**Comment by tkburroughs** [comment]
#build

**Review by brideck — APPROVED** [review]

**Comment by tkburroughs** [comment]
#run-libby-bot

**Comment by tkburroughs** [comment]
#build

**Comment by tkburroughs** [comment]
#build

**Pull request merged**
