### PR TITLE
Updates: Jandex 2.3.0, SR OpenAPI 2.1.5

### PR DESCRIPTION
**Pull request by Azquelt**
Fixes #17356

Also needed for #17428

### CODE REVIEW

**Comment by Azquelt** [comment]
#build

**Review by tbitonti — CHANGES_REQUESTED** [review]
There is a sparse reader here which will need to be updated, if this Jandex update changes the index format:
https://github.com/OpenLiberty/open-liberty/tree/integration/dev/com.ibm.ws.anno/src/com/ibm/ws/annocache/jandex/internal

If there is an index format change these unit tests would need a new case:
https://github.com/OpenLiberty/open-liberty/tree/integration/dev/com.ibm.ws.anno/test/com/ibm/ws/annocache/test/jandex

**Review by tbitonti — APPROVED** [review]
Version 2.3.0 uses Jandex index format version 9, which we support.

**Comment by Azquelt** [comment]
#build

**Comment by Azquelt** [comment]
#run-libby-bot

**Comment by Azquelt** [comment]
There's one failure in the build which seems to be a known problem not related to this change.

**Pull request merged**
