### PR TITLE
Refactoring and processing of Jakarta Security 3.0 annotations for issue #21155

### PR DESCRIPTION
**Pull request by teddyjtorres**
For issue #21155

### CODE REVIEW

**Comment by teddyjtorres** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.security.javaeesec_fat,com.ibm.ws.security.javaeesec_fat.2,com.ibm.ws.security.javaeesec_fat.3,com.ibm.ws.security.javaeesec_fat.4

**Comment by teddyjtorres** [comment]
> https://wasrtc.hursley.ibm.com:9443/jazz/resource/itemOid/com.ibm.team.build.BuildResult/_n8GEoAL7Ee2_YeU2rrO1jw

The file has references to the git branch where the spec is located, which contains the word "master" triggering the LibbyBot's comment above.

`// TODO: Implement logic per https://github.com/jakartaee/security/blob/master/spec/src/main/asciidoc/authenticationMechanism.adoc#openid-connect-annotation`

References to the repo will be removed.

**Comment by teddyjtorres** [comment]
#libby
#build
#spawn.fullfat.buckets=com.ibm.ws.security.javaeesec_fat,com.ibm.ws.security.javaeesec_fat.2,com.ibm.ws.security.javaeesec_fat.3,com.ibm.ws.security.javaeesec_fat.4

**Review by utle — APPROVED** [review]

**Comment by posmith** [comment]
L2 message review completed

**Review by ayoho — APPROVED** [review]

**Comment by teddyjtorres** [comment]
Created https://github.com/OpenLiberty/open-liberty/pull/22143 to address this refactoring.

**Pull request closed without merging**
