### PR TITLE
Issue 15987: Update OIDC code cookie value calculation

### LINKED ISSUE #15987: OIDC state cookie cannot be read by another JVM in collective w/socal login TS004966274
**Describe the bug**
`[2/15/21 2:32:56:282 CST] 00000072 OIDCClientAut E   CWWKS1745E: The WASOidcCode cookie [ITSASTRING_1xtpZwgG8vF7d0XMeAEvBmeGzPAegfSptO4GP72tObA=] in the request to the OpenID Connect client [xxx] is not valid. Its value might have been modified.`

**Steps to Reproduce**

1. Configure OIDC with the socialLogin-1.0 feature (oidcLogin) in a collective w/o session affinity
2. Initial request goes to JVM1
3. Callback from OP goes to JVM2
4. JVM2 fails to validate the state cookie and the login fails

**Expected behavior**
JVM2 can read and process the state cookie

**Diagnostic information:**
 - OpenLiberty Version: 21.0.0.1
 - Java Version: 
 - server.xml configuration:
 	`<oidcLogin id="w3id_oidc_auth" displayName="w3_OIDC_Login" clientId="xxx" clientSecret="xxx" authorizationEndpoint="https://login.com/oidc/endpoint/default/authorize" tokenEndpoint="https://login.com/oidc/endpoint/default/token" jwksUri="https://login.com/oidc/endpoint/default/jwks" issuer="https://login.com/oidc/endpoint/default" scope="openid profile email" userNameAttribute="email" authFilterRef="w3_oidcAuthFilter"/>`

**Additional information:**
This issue was reported with OIDC configured via social login (oidcLogin).  This does not happen with the OIDC RP configured via the openidConnectClient-1.0 feature (openidConnectClient).

Trace snip:
[2/15/21 2:32:56:282 CST] 00000072 OIDCClientAut >  validateReqParameters Entry  
                                 com.ibm.ws.security.social.internal.OidcLoginConfigImpl@1b36348e
                                 {}
                                 ITSASTRING_1xtpZwgG8vF7d0XMeAEvBmeGzPAegfSptO4GP72tObA=
[2/15/21 2:32:56:282 CST] 00000072 OidcClientUti >  calculateOidcCodeCookieValue Entry  
                                 ITSASTRING
                                 com.ibm.ws.security.social.internal.OidcLoginConfigImpl@1b36348e
[2/15/21 2:32:56:282 CST] 00000072 Oauth2LoginCo >  getClientSecret Entry 
[2/15/21 2:32:56:282 CST] 00000072 Oauth2LoginCo <  getClientSecret Exit  
                                 <sensitive java.lang.String@b184e960>
[2/15/21 2:32:56:282 CST] 00000072 Oauth2LoginCo >  getClientSecret Entry 
[2/15/21 2:32:56:282 CST] 00000072 Oauth2LoginCo <  getClientSecret Exit  
                                 <sensitive java.lang.String@b184e960>
[2/15/21 2:32:56:282 CST] 00000072 OidcClientUti <  calculateOidcCodeCookieValue Exit  
                                 ITSASTRING_aTT7rHRKFKpjpcYIuXS9bk+9AvDUbdWBZxwgfICnDVo=
[2/15/21 2:32:56:282 CST] 00000072 OIDCClientAut 3   The value for the OIDC state cookie [WASOidcCode] failed validation.
[2/15/21 2:32:56:282 CST] 00000072 OIDCClientAut <  validateReqParameters Exit  
                                 false
[2/15/21 2:32:56:282 CST] 00000072 ProviderAuthe >  <init> Entry  
                                 SEND_401
                                 401
[2/15/21 2:32:56:282 CST] 00000072 ProviderAuthe <  <init> Exit  
                                 com.ibm.ws.webcontainer.security.ProviderAuthenticationResult@f775020f
[2/15/21 2:32:56:282 CST] 00000072 Oauth2LoginCo >  getClientId Entry 
[2/15/21 2:32:56:282 CST] 00000072 Oauth2LoginCo <  getClientId Exit  
                                 YmFiYWZhMzQtNzJkMC00
[2/15/21 2:32:56:282 CST] 00000072 OIDCClientAut E   CWWKS1745E: The WASOidcCode cookie [ITSASTRING_1xtpZwgG8vF7d0XMeAEvBmeGzPAegfSptO4GP72tObA=] in the request to the OpenID Connect client [xxx] is not valid. Its value might have been modified.

### PR DESCRIPTION
**Pull request by ayoho**
Fixes #15987

### CODE REVIEW

**Comment by ayoho** [comment]
#libby

**Comment by ayoho** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.security.oidc.client_fat,com.ibm.ws.security.oidc.client_fat.config,com.ibm.ws.security.oidc.client_fat.e2e,com.ibm.ws.security.oidc.client_fat.jaxrs,com.ibm.ws.security.oidc.client_fat.saml,com.ibm.ws.security.oidc.server_fat,com.ibm.ws.security.oidc.server_fat.app-passwords,com.ibm.ws.security.oidc.server_fat.app-passwords.DerbyDB.jwt,com.ibm.ws.security.oidc.server_fat.app-passwords.DerbyDB.opaque,com.ibm.ws.security.oidc.server_fat.app-passwords.LocalStore.jwt,com.ibm.ws.security.oidc.server_fat.app-passwords.LocalStore.opaque,com.ibm.ws.security.oidc.server_fat.app-tokens,com.ibm.ws.security.oidc.server_fat.app-tokens.DerbyDB.jwt,com.ibm.ws.security.oidc.server_fat.app-tokens.DerbyDB.opaque,com.ibm.ws.security.oidc.server_fat.app-tokens.LocalStore.jwt,com.ibm.ws.security.oidc.server_fat.app-tokens.LocalStore.opaque,com.ibm.ws.security.oidc.server_fat.clientregistration,com.ibm.ws.security.oidc.server_fat.config,com.ibm.ws.security.oidc.server_fat.config.oauth,com.ibm.ws.security.oidc.server_fat.config.oidc,com.ibm.ws.security.oidc.server_fat.endpoint.authorize,com.ibm.ws.security.oidc.server_fat.endpoint.coveragemap,com.ibm.ws.security.oidc.server_fat.endpoint.discovery,com.ibm.ws.security.oidc.server_fat.endpoint.end_session,com.ibm.ws.security.oidc.server_fat.endpoint.introspect,com.ibm.ws.security.oidc.server_fat.endpoint.revoke,com.ibm.ws.security.oidc.server_fat.endpoint.token,com.ibm.ws.security.oidc.server_fat.endpoint.userinfo,com.ibm.ws.security.oidc.server_fat.feature,com.ibm.ws.security.oidc.server_fat.granttype.jwt,com.ibm.ws.security.oidc.server_fat.gui.tokenMgmt,com.ibm.ws.security.oidc.server_fat.jaxrs,com.ibm.ws.security.oidc.server_fat.jaxrs.config,com.ibm.ws.security.oidc.server_fat.oauth,com.ibm.ws.security.oidc.server_fat.oidc,com.ibm.ws.security.oidc.server_fat.saml

**Comment by skasund** [comment]
L2 message review not required

**Comment by ayoho** [comment]
First personal build had just a single failure in an OIDC bucket from an LDAP operation timeout. I'm pretty confident it wasn't a result of my change, but I'll run a new build just in case.

#build
#spawn.fullfat.buckets=com.ibm.ws.security.oidc.client_fat,com.ibm.ws.security.oidc.client_fat.config,com.ibm.ws.security.oidc.client_fat.e2e,com.ibm.ws.security.oidc.client_fat.jaxrs,com.ibm.ws.security.oidc.client_fat.saml,com.ibm.ws.security.oidc.server_fat,com.ibm.ws.security.oidc.server_fat.app-passwords,com.ibm.ws.security.oidc.server_fat.app-passwords.DerbyDB.jwt,com.ibm.ws.security.oidc.server_fat.app-passwords.DerbyDB.opaque,com.ibm.ws.security.oidc.server_fat.app-passwords.LocalStore.jwt,com.ibm.ws.security.oidc.server_fat.app-passwords.LocalStore.opaque,com.ibm.ws.security.oidc.server_fat.app-tokens,com.ibm.ws.security.oidc.server_fat.app-tokens.DerbyDB.jwt,com.ibm.ws.security.oidc.server_fat.app-tokens.DerbyDB.opaque,com.ibm.ws.security.oidc.server_fat.app-tokens.LocalStore.jwt,com.ibm.ws.security.oidc.server_fat.app-tokens.LocalStore.opaque,com.ibm.ws.security.oidc.server_fat.clientregistration,com.ibm.ws.security.oidc.server_fat.config,com.ibm.ws.security.oidc.server_fat.config.oauth,com.ibm.ws.security.oidc.server_fat.config.oidc,com.ibm.ws.security.oidc.server_fat.endpoint.authorize,com.ibm.ws.security.oidc.server_fat.endpoint.coveragemap,com.ibm.ws.security.oidc.server_fat.endpoint.discovery,com.ibm.ws.security.oidc.server_fat.endpoint.end_session,com.ibm.ws.security.oidc.server_fat.endpoint.introspect,com.ibm.ws.security.oidc.server_fat.endpoint.revoke,com.ibm.ws.security.oidc.server_fat.endpoint.token,com.ibm.ws.security.oidc.server_fat.endpoint.userinfo,com.ibm.ws.security.oidc.server_fat.feature,com.ibm.ws.security.oidc.server_fat.granttype.jwt,com.ibm.ws.security.oidc.server_fat.gui.tokenMgmt,com.ibm.ws.security.oidc.server_fat.jaxrs,com.ibm.ws.security.oidc.server_fat.jaxrs.config,com.ibm.ws.security.oidc.server_fat.oauth,com.ibm.ws.security.oidc.server_fat.oidc,com.ibm.ws.security.oidc.server_fat.saml

**Comment by ayoho** [comment]
#libby
#build
#spawn.fullfat.buckets=com.ibm.ws.security.oidc.client_fat,com.ibm.ws.security.oidc.client_fat.config,com.ibm.ws.security.oidc.client_fat.e2e,com.ibm.ws.security.oidc.client_fat.jaxrs,com.ibm.ws.security.oidc.client_fat.saml,com.ibm.ws.security.oidc.server_fat,com.ibm.ws.security.oidc.server_fat.app-passwords,com.ibm.ws.security.oidc.server_fat.app-passwords.DerbyDB.jwt,com.ibm.ws.security.oidc.server_fat.app-passwords.DerbyDB.opaque,com.ibm.ws.security.oidc.server_fat.app-passwords.LocalStore.jwt,com.ibm.ws.security.oidc.server_fat.app-passwords.LocalStore.opaque,com.ibm.ws.security.oidc.server_fat.app-tokens,com.ibm.ws.security.oidc.server_fat.app-tokens.DerbyDB.jwt,com.ibm.ws.security.oidc.server_fat.app-tokens.DerbyDB.opaque,com.ibm.ws.security.oidc.server_fat.app-tokens.LocalStore.jwt,com.ibm.ws.security.oidc.server_fat.app-tokens.LocalStore.opaque,com.ibm.ws.security.oidc.server_fat.clientregistration,com.ibm.ws.security.oidc.server_fat.config,com.ibm.ws.security.oidc.server_fat.config.oauth,com.ibm.ws.security.oidc.server_fat.config.oidc,com.ibm.ws.security.oidc.server_fat.endpoint.authorize,com.ibm.ws.security.oidc.server_fat.endpoint.coveragemap,com.ibm.ws.security.oidc.server_fat.endpoint.discovery,com.ibm.ws.security.oidc.server_fat.endpoint.end_session,com.ibm.ws.security.oidc.server_fat.endpoint.introspect,com.ibm.ws.security.oidc.server_fat.endpoint.revoke,com.ibm.ws.security.oidc.server_fat.endpoint.token,com.ibm.ws.security.oidc.server_fat.endpoint.userinfo,com.ibm.ws.security.oidc.server_fat.feature,com.ibm.ws.security.oidc.server_fat.granttype.jwt,com.ibm.ws.security.oidc.server_fat.gui.tokenMgmt,com.ibm.ws.security.oidc.server_fat.jaxrs,com.ibm.ws.security.oidc.server_fat.jaxrs.config,com.ibm.ws.security.oidc.server_fat.oauth,com.ibm.ws.security.oidc.server_fat.oidc,com.ibm.ws.security.oidc.server_fat.saml

**Review by teddyjtorres — APPROVED** [review]

**Pull request merged**
