### PR TITLE
update saml test configurations

### PR DESCRIPTION
**Pull request by arunavemulapalli**
- update tests configs to use sha256 as signature algorithm, so the same tests can run with fips140-3

### CODE REVIEW

**Comment by arunavemulapalli** [comment]
#build

**Review by c00crane — APPROVED** [review]

**Comment by arunavemulapalli** [comment]
#libby

**Comment by arunavemulapalli** [comment]
build results look good

**Comment by arunavemulapalli** [comment]
one soe (centos+ibmjava8) results look good - https://libh-proxy1.fyre.ibm.com/cognitive-dev/soeAnalysis.html?uuid=_WwnD0HTFEe6LyICjST0JEw&tab=Pipelines

**Pull request merged**
