### PR TITLE
Fix xmlws-2.3 and jaxws-2.3 Effective Policy/ATAsserion failures

### PR DESCRIPTION
**Pull request by neuwerk**
This pull requests makes the following changes:
- Fixes an issue in CXF 3.2 which prevents the xmlWS-3.0 and jaxws-2.3 from properly applying an policy attachment
- Fixes in an issue in the integration layer that allows the WS-AT policy to be set to a specific Endpoint URL
- Adds jaxws-2.3 and xmlWS-3.0 as features to run the com.ibm.ws.jaxws.X.wsat_fat bucket against.

### CODE REVIEW

**Comment by neuwerk** [comment]
#build

**Comment by neuwerk** [comment]
#build

**Comment by neuwerk** [comment]
#build

**Comment by neuwerk** [comment]
#build

**Comment by neuwerk** [comment]
#build

**Comment by neuwerk** [comment]
#build

**Comment by neuwerk** [comment]
#build

**Review by arunavemulapalli — APPROVED** [review]

**Comment by neuwerk** [comment]
#run-libby-bot

**Pull request merged**
