### PR TITLE
Jsf22 flash events ee10

### PR DESCRIPTION
**Pull request by pnicolucci**
for #22369

### CODE REVIEW

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
Java 17 build: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_XuVbgEqXEe2vN7J6vLoevQ

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
Java 17 build: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_AlmaMErrEe2vN7J6vLoevQ

**Comment by pnicolucci** [comment]
Java 17 build was good

**Review by isaacrivriv — APPROVED** [review]
Looks good to me, thanks!

**Pull request merged**
