### PR TITLE
29124 jaxrs dynamic outbound fallback

### LINKED ISSUE #29124: jaxrs: Regression by #27782
18857ba42fb853efe3fcdc1c6b6960e82ea7a504  changed jaxrs client to call
`                        return jsseHelper.getSSLContext(null, null, null);`
if no sslAlias is explicitly set. It does not honor eg. any ssl Config Statement, which would match a host.

The old behavoiur would be passing the connectionInfo:
`                        return jsseHelper.getSSLContext(null, connectionInfo, null);`

So for eg. jax-ws, OL still honors
```
<ssl id="x" keyStoreRef="test">
          <outboundConnection host="test.com" port="443"/>
</ssl>
```
For jax-rs. it is not honored and uses only the default SSL statement.

Tested with 24.0.0.6 - the code is still unchanged in master.

### PR DESCRIPTION
**Pull request by WhiteCat22**
Fixes #29124

- [x] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [x] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [x] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

### CODE REVIEW

**Review by neuwerk — DISMISSED** [review]
Looks good to me!

**Comment by WhiteCat22** [comment]
#libby #build #spawn.fullfat.buckets=com.ibm.ws.jaxrs.2.0.client_fat

**Comment by WhiteCat22** [comment]
#libby #build #spawn.fullfat.buckets=com.ibm.ws.jaxrs.2.0.client_fat

**Comment by WhiteCat22** [comment]
Fixes #PH62695

**Review by neuwerk — APPROVED** [review]

**Review by jim-krueger — APPROVED** [review]

**Pull request merged**
