### PR TITLE
17742 jakarta support in yoko

### PR DESCRIPTION
**Pull request by ngmr**

### CODE REVIEW

**Comment by ngmr** [comment]
#build

**Comment by ngmr** [comment]
#run-libby-bot

**Comment by ngmr** [comment]
#build

**Comment by ngmr** [comment]
#run-libby-bot

**Comment by ngmr** [comment]
#build

**Comment by ngmr** [comment]
#run-libby-bot

**Comment by ngmr** [comment]
#build

**Review by tkburroughs — APPROVED** [review]

**Pull request closed without merging**
