### PR TITLE
add HandleList support to EE Concurrency

### PR DESCRIPTION
**Pull request by njr-11**
Create an autofeature to enable integration with HandleList when connection management and the thread context feature for EE Concurrency are enabled.  Add a couple of test cases to verify that, when enabled, the HandleList closes connections that are created within a contextual task and leaked.

### CODE REVIEW

**Comment by njr-11** [comment]
#build

**Comment by njr-11** [comment]
Build failed with this error:
Feature AppliesTo Version Validation Errors
```
 The productVersion in the IBM-AppliesTo line of each feature in:
 wlp-featureRepo-21.0.0.1.zip must be set to productVersion=21.0.0.1
 wlp-beta-featureRepo-21.0.0.1.zip must be set to productVersion=2021.1.0.0
 
 The following features have invalid AppliesTo productVersions:
 features/2021.1.0.0/io.openliberty.emptyHandleListContext-1.0.esa.json in wlp-beta-featureRepo-2021.1.0.0.zip - appliesTo productVersion 21.0.0.1 - does not match required version (2021.1.0.0) 
```
which doesn't make any sense to me. One guess is that it's some sort of attempt to work around the inability of autofeatures to honor kind=noship by rejecting them outright when they depend only on ga/beta features.  I'll attempt to work around this by adding a noShip-1.0 feature to gate the autofeature and see if that helps.

**Comment by njr-11** [comment]
#build
#run-libby-bot

**Review by aguibert — APPROVED** [review]

**Comment by njr-11** [comment]
The update to the test server.xml to enable the noship feature was not included in the commit. Added it now and rebuilding,
#build
#run-libby-bot

**Pull request merged**
