### PR TITLE
More logging for repeat action and test method entry and exit

### PR DESCRIPTION
**Pull request by benjamin-confino**
- [x] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [x] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [x] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

This 
- Prints out the Description when entering a repeat action (usually the test class that will be run at that repeat)
- Makes the message saying which test method we're entering or exiting much more visible

### CODE REVIEW

**Comment by benjamin-confino** [comment]
#build

**Review by jhanders34 — DISMISSED** [review]

**Comment by benjamin-confino** [comment]
#build

**Review by Yas-Franco — APPROVED** [review]

**Comment by benjamin-confino** [comment]
https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=e47ba218-d0f0-4877-b8a9-8af82a4b9fae has one failure (3/4 runs of that test passed), I looked at that test and it does not read the output.txt logs as part of the test.

**Comment by benjamin-confino** [comment]
#libby

**Pull request merged**
