### PR TITLE
tolerate errors in log when FailoverTimersTest forces a failover

### LINKED ISSUE #14148: Test Failure: FailoverTimersTest.testProgrammaticTimerFailsOverWhenTimerFailsOnOneServer
Test Failure: com.ibm.ws.concurrent.persistent.fat.failovertimers.FailoverTimersTest.testProgrammaticTimerFailsOverWhenTimerFailsOnOneServer

```
testProgrammaticTimerFailsOverWhenTimerFailsOnOneServer:java.lang.Exception: 2020-09-13-17:29:15:133 Errors/warnings were found in server com.ibm.ws.concurrent.persistent.fat.failovertimers.serverA logs:
 <br>[9/13/20 17:29:08:183 UTC] 00000028 com.ibm.tx.jta.impl.RegisteredResources                      E WTRN0046E: An attempt by the transaction manager to call prepare on a transactional resource has resulted in an error. The error code was XAER_RMFAIL. The exception stack trace follows: org.apache.derby.client.am.XaException: XAER_RMFAIL : No current connection.
 <br>[9/13/20 17:29:10:757 UTC] 00000028 com.ibm.tx.jta.impl.RegisteredResources                      W WTRN0049W: An attempt by the transaction manager to call rollback on a transactional resource has resulted in an XAER_RMFAIL error. The resource was com.ibm.tx.jta.impl.JTAXAResourceImpl@9820a935#{XidImpl: formatId(57415344) gtrid_length(36) bqual_length(54)
 <br>[9/13/20 17:29:11:435 UTC] 00000028 com.ibm.tx.jta.impl.RegisteredResources                      W WTRN0049W: An attempt by the transaction manager to call rollback on a transactional resource has resulted in an XAER_RMFAIL error. The resource was com.ibm.tx.jta.impl.JTAXAResourceImpl@3dd45c9#{XidImpl: formatId(57415344) gtrid_length(36) bqual_length(54)
 <br>[9/13/20 17:29:11:482 UTC] 00000028 com.ibm.ejs.j2c.MCWrapper                                    E J2CA0081E: Method cleanup failed while trying to execute method cleanup on ManagedConnection WSRdbManagedConnectionImpl@e2db805b from resource dataSource[DefaultDataSource]. Caught exception: com.ibm.ws.rsadapter.exceptions.DataStoreAdapterException: DSRA0080E: An exception was received by the Data Store Adapter. See original exception message: Cannot call 'cleanup' on a ManagedConnection while it is still in a transaction..
at componenttest.topology.impl.LibertyServer.checkLogsForErrorsAndWarnings(LibertyServer.java:2555)
at componenttest.topology.impl.LibertyServer.stopServer(LibertyServer.java:2420)
at componenttest.topology.impl.Li
```

Test case is complaining of errors that show up in the logs when a server is taking down in the middle of execution in order to force a failover. The test case ought to be tolerating errors on the server that is taken down and just requiring that tasks successfully fail over to the other server.

### PR DESCRIPTION
**Pull request by njr-11**
fixes #14148

### CODE REVIEW

**Review by nmittles — APPROVED** [review]

**Comment by njr-11** [comment]
#build

**Comment by njr-11** [comment]
#build

**Comment by njr-11** [comment]
#build

**Comment by njr-11** [comment]
#build

**Comment by njr-11** [comment]
#build

**Comment by njr-11** [comment]
#build

**Pull request merged**
