### PR TITLE
Renamed servlet, jstl, jsp, and el to io openliberty jakarta

### LINKED ISSUE #12316: Jakartaee - > Jakarta Rename for JSP, EL, Servlet & JSTL APIs
The vote to use Jakarta over Jakartaee in the api names has been decided, so the following 4 jars will need to be changed: 

- com.ibm.websphere._jakartaee_.el.4.0
- com.ibm.websphere._jakartaee_.jsp.3.0
- com.ibm.websphere._jakartaee_.jstl.2.0
- com.ibm.websphere._jakartaee_.servlet.5.0

This changes will include folder names, bnd.bnd's _Bundle-SymbolicName_, and the feature files for each of the above. 

Future renames are possible -- such as to ``io.openliberty.jakarta.xxx``

### PR DESCRIPTION
**Pull request by isaacrivriv**
fixes #12316

### CODE REVIEW

**Comment by isaacrivriv** [comment]
#build

**Comment by isaacrivriv** [comment]
When looking at the git changes view, we noticed that git is confusing some of the renamed files saying they came from another renamed project. The files we noticed this happened on were
```
jstl.2.0/.project -> el.4.0/.project
el.4.0/.project -> jsp.3.0/.project
jsp.3.0/.project -> jstl.2.0/.project
jstl.2.0/.classpath -> jsp.3.0/.classpath
jsp.3.0/.classpath -> jstl.2.0/.classpath
```

We verified and concluded that the files are ok and how they should be with their appropriate name changes but git is confusing them as if they came from another renamed project.

**Comment by isaacrivriv** [comment]
#build

**Comment by tevans78** [comment]
#run-libby-bot

**Comment by tevans78** [comment]
Merging without another PB ... previous one was good enough and I want this in the GM.

**Pull request merged**
