### PR TITLE
Fixing SessionCacheConfigUpdateTest cases

### PR DESCRIPTION
**Pull request by zhang-ca**
Between server configuration update and completion, it needs time.

        server.updateServerConfiguration(config);

        server.waitForConfigUpdateInLogUsingMark(APP_NAMES, EMPTY_RECYCLE_LIST);

### CODE REVIEW

**Comment by zhang-ca** [comment]
#build

**Review by randyclee — APPROVED** [review]
LGTM

**Comment by zhang-ca** [comment]
#build

**Comment by zhang-ca** [comment]
#build

**Comment by zhang-ca** [comment]
#run-libby-bot

**Pull request merged**
