### PR TITLE
Fix Missing Trailer Fields in Response

### LINKED ISSUE #29477: Trailer fields are missing in HttpServletResponse after some time.
**Describe the bug**  
The HttpServletResponse [trailer fields](https://jakarta.ee/specifications/servlet/6.0/apidocs/jakarta.servlet/jakarta/servlet/http/httpservletresponse#setTrailerFields(java.util.function.Supplier)) are missing in responses after some successful responses.

There is no error or exception when that happens.  The Chunked encoding response does not contain the ending trailer fields.

**Steps to Reproduce**  
1. Implementing the HttpServlettResponse [setTrailerFields(Supplier<Map<String,String>> supplier)](https://jakarta.ee/specifications/servlet/6.0/apidocs/jakarta.servlet/jakarta/servlet/http/httpservletresponse#setTrailerFields(java.util.function.Supplier))​ 

2. Request and verify that the above setting trailer fields are in the initial response (they are at the end of the chunked response `after` the 0 byte package).
3. Request repeatedly to the same endpoint resource.
4. After some time, observe that the response trailer fields are missing.

**Expected behavior**  
The trailer fields should always be in the responses.

**Diagnostic information:**  
 - OpenLiberty Version: 18.0.0.2 - 24.0.0.9
 - Affected feature(s) [Servlet 4.0, Servlet 5.0, Servlet 6.0]
 - Java Version: any

NOTE: if using `curl` client to send and verify the response, use `--raw` option to show the hidden 0 byte package and the trailer.

### PR DESCRIPTION
**Pull request by pmd1nh**
- [X] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [X] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [ ] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

################################################################################################

Fixes https://github.com/OpenLiberty/open-liberty/issues/29477

### CODE REVIEW

**Comment by pmd1nh** [comment]
#build
        #spawn.fullfat.buckets=io.openliberty.webcontainer.servlet.6.1.internal_fat,io.openliberty.webcontainer.servlet.6.0.internal_fat,com.ibm.ws.webcontainer.servlet.6.1_fat_toleration.lWAS,com.ibm.ws.webcontainer.servlet.6.0_fat_toleration.lWAS,com.ibm.ws.webcontainer_fat,com.ibm.ws.webcontainer.servlet.3.1_fat,com.ibm.ws.webcontainer.servlet.3.1_fat.2,com.ibm.ws.webcontainer.servlet.4.0_fat,com.ibm.ws.webcontainer_fat_part2,com.ibm.ws.webcontainer_fat_servlet31toleration,com.ibm.ws.webcontainer_fat_servlet31toleration_part2,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0_part2,com.ibm.ws.webcontainer_fat_lWAS,com.ibm.ws.webcontainer_fat_servlet31_webcontainerlWAS,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0.lWAS

**Comment by pmd1nh** [comment]
4 failures/errors but do not seem to relate to this change.

```
no component 108046 2 2
    com.ibm.ws.ui.tool.deploy_fat.gui.nd.rw.liberty FAT tests 3 2 0
      com.ibm.ws.ui.tool.deploy.fat.gui.nd.rw.liberty.tests.DeployLibertyServerTest 1 1 0 7 m 22 s 3
        verifyLibertyServerDeploy 1 1 0 7 m 22 s 1
      com.ibm.ws.ui.tool.deploy.fat.gui.nd.rw.liberty.tests.DirectURLDeployTest 1 1 0 7 m 20 s 2
        testDirectDeployURL 1 1 0 7 m 20 s 1
    io.openliberty.jaxws.config_fat FAT tests 1 0 1
      io.openliberty.jaxws.config.fat.FATSuite 1 0 1 0 s 1
        testAddedElementIncorrectServiceNameSchemaValidatinFalse 1 0 1 0 s 1
    io.openliberty.jaxws.executor_fat FAT tests 1 0 1
      io.openliberty.jaxws.executor.FATSuite 1 0 1 0 s 1
        JAXWSExecutorTestServlet.testOneWayClientSubmitCallViaManagedExecutor_EE10_FEATURES 1 0 1 0 s 1 
```

**Comment by pmd1nh** [comment]
#libby

**Review by jhanders34 — APPROVED** [review]

**Comment by pmd1nh** [comment]
There is no FAT for this one as it will require some long run to bring out/verify the problem.

**Comment by pmd1nh** [comment]
#libby

**Pull request merged**
