### PR TITLE
Issue #12154: Jakarta XML DD transform rules

### LINKED ISSUE #12154: Jakarta EE 9: Provide XML deployment descriptor Injection transform rules
Provide the rules for transforming XML deployment descriptors for data types that may be looked up in java:comp or injected.  This includes files like web.xml and ejb-jar.xml.

### PR DESCRIPTION
**Pull request by tkburroughs**
The following XML deployment descriptors will need to be transformed
when transforming test projects from Java EE 8 to Jakarta EE 9:

application.xml
application-client.xml
ejb-jar.xml
permissions.xml
web.xml
web-fragment.xml

The following data types may appear in these files as some type of
resource reference:

javax.ejb.EJBContext
javax.ejb.MessageDrivenContext
javax.ejb.SessionContext
javax.ejb.Timer
javax.ejb.TimerService
javax.enterprise.concurrent.ContextService
javax.enterprise.concurrent.ManagedExecutorService
javax.enterprise.concurrent.ManagedScheduledExecutorService
javax.enterprise.concurrent.ManagedThreadFactory
javax.enterprise.inject.spi.BeanManager
javax.jms.ConnectionFactory
javax.jms.Destination
javax.jms.Queue
javax.jms.QueueConnectionFactory
javax.jms.Topic
javax.jms.TopicConnectionFactory
javax.resource.cci.ConnectionFactory
javax.transaction.UserTransaction
javax.transaction.TransactionSynchronizationRegistry

fixes #12154

### CODE REVIEW

**Comment by tkburroughs** [comment]
#build

**Comment by tkburroughs** [comment]
#libby-bot

**Comment by tkburroughs** [comment]
#run-libby-bot

**Comment by tkburroughs** [comment]
#run-libby-bot

**Comment by tkburroughs** [comment]
#run-libby

**Comment by wraschke** [comment]
#help

**Comment by wraschke** [comment]
#libbybot

**Comment by wraschke** [comment]
#libby

**Comment by tkburroughs** [comment]
FAT failures in build have open issues and are not related to JakartaEE 9 testing.  Merging.

**Pull request merged**
