### PR TITLE
Use Json factories to avoid having to lookup the provider

### LINKED ISSUE #16395: Cache JsonWriterFactory/JsonReaderFactory
In multiple locations in Liberty we create JSON writers/reader like this:

 ```
writer = Json.createWriter(entityStream);
reader = Json.createReader(entityStream);
```

This is fine if you do it once, but if you do it every request it adds a lot of classloading overhead. It is better to create and cache a WriterFactory (or ObjectFactory) like this.

```
private static final  JsonWriterFactory writerFactory = Json.createWriterFactory(null);


<later>
writer = writerFactory.createWriter(entityStream);
```

I plan to fix the first two classes here and look into the rest.

**JAX-RS**
dev/com.ibm.ws.jaxrs.2.0.common/src/com/ibm/ws/jaxrs20/providers/jsonp/JsonPProvider.java
dev/io.openliberty.org.jboss.resteasy.common/src/io/openliberty/restfulWS/providers/JsonPProvider.java

**Batch**
dev/com.ibm.ws.jbatch.jms/src/com/ibm/ws/jbatch/jms/internal/events/impl/BatchEventsPublisherImpl.java
dev/com.ibm.ws.jbatch.rest/src/com/ibm/ws/jbatch/rest/internal/resources/BatchRoot.java
dev/com.ibm.ws.jbatch.rest/src/com/ibm/ws/jbatch/rest/utils/BatchJSONHelper.java
dev/com.ibm.ws.jbatch.utility/src/com/ibm/ws/jbatch/utility/rest/JobExecutionListMessageBodyReader.java
dev/com.ibm.ws.jbatch.utility/src/com/ibm/ws/jbatch/utility/rest/JobExecutionMessageBodyReader.java
dev/com.ibm.ws.jbatch.utility/src/com/ibm/ws/jbatch/utility/rest/JobInstanceListMessageBodyReader.java
dev/com.ibm.ws.jbatch.utility/src/com/ibm/ws/jbatch/utility/rest/JobInstanceMessageBodyReader.java
dev/com.ibm.ws.jbatch.utility/src/com/ibm/ws/jbatch/utility/rest/JobRestartMessageBodyWriter.java
dev/com.ibm.ws.jbatch.utility/src/com/ibm/ws/jbatch/utility/rest/JobSubmissionMessageBodyWriter.java
dev/com.ibm.ws.jbatch.utility/src/com/ibm/ws/jbatch/utility/rest/JsonHelper.java
dev/com.ibm.ws.jbatch.utility/src/com/ibm/ws/jbatch/utility/rest/PurgeResponseMessageBodyReader.java

**Security**
dev/com.ibm.ws.security.mp.jwt.cdi/src/com/ibm/ws/security/mp/jwt/cdi/ClaimBean.java
dev/com.ibm.ws.security.mp.jwt.cdi/src/com/ibm/ws/security/mp/jwt/cdi/ClaimProducer.java
dev/com.ibm.ws.security.mp.jwt/src/com/ibm/ws/security/mp/jwt/impl/utils/ClaimsUtils.java
dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/internal/utils/IntrospectUserApiUtils.java
dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/internal/utils/OpenShiftUserApiUtils.java

**Other**
dev/com.ibm.ws.repository/src/com/ibm/ws/repository/transport/client/SingleFileClient.java
dev/wlp-mavenRepoTasks/src/com/ibm/ws/wlp/mavenFeatures/LibertyFeaturesToMavenRepo.java

### PR DESCRIPTION
**Pull request by jhanders34**
- Update to use JsonBuilderFactory.createObjectBuilder() instead of Json.createObjectBuilder()
- Update to use JsonReaderFactory.createReader() instead of Json.createReader()
- Update to use JsonWriterFactory.createWriter() instead of Json.createWriter()

Fixes #16395

### CODE REVIEW

**Comment by jhanders34** [comment]
#build

**Comment by jhanders34** [comment]
#libby

**Review by scottkurz — APPROVED** [review]
LGTM

**Review by ayoho — APPROVED** [review]

**Review by jdmcclur — APPROVED** [review]

**Comment by jhanders34** [comment]
#libby
#build

**Review by andymc12 — APPROVED** [review]
LGTM - thanks!

**Pull request merged**
