### PR TITLE
Update loginProperty syntax in LDAP FATs

### PR DESCRIPTION
**Pull request by ryanesch**
Update LDAP FATs to use the new loginProperty syntax. Remove loginProperty if uid (default) to keep config minimal.

### CODE REVIEW

**Comment by ryanesch** [comment]
#build

**Comment by ryanesch** [comment]
#build

**Comment by ryanesch** [comment]
The one failing test is an existing/known test bug.

**Review by jvanhill — APPROVED** [review]

**Comment by ryanesch** [comment]
#run-libby-bot

**Pull request merged**
