### PR TITLE
Issue #19781: Fix WIMUserRegistry.isValidGroup and isValidUser to onl…

### LINKED ISSUE #19781: Calling `UserRegistry.isValidGroup` or `UserRegistry.isValidUser` when using `federatedRegistry-1.0` can return `true` when `false` should be returned.
**Describe the bug**  
Calling `UserRegistry.isValidGroup` or `UserRegistry.isValidUser` when using `federatedRegistry-1.0` can return `true` when `false` should be returned.

**Steps to Reproduce**  
- Enable the `federatedRegistry-1.0` feature, as well as another feature that includes a UserRegistry.
- Call `UserRegistry.isValidGroup` with a valid user, or `UserRegistry.isValidUser` with a valid group.
  - This can occur with the basic user registry,  the SAF user registries (WebSphere Liberty only), or with a custom user registry.

**Expected behavior**  
When passing in an valid user to the `UserRegistry.isValidGroup` method and/or a valid group to the `UserRegistry.isValidUser` method, they should return false, but instead they return true.

**Diagnostic information:**  
 - OpenLiberty Version: Any
 - Affected feature(s): federatedRegistry-1.0
 - Java Version: Any

**Additional context**  
None.

### PR DESCRIPTION
**Pull request by jvanhill**
…y return true when the entity type matches the expected entity type for the method.

fixes #19781

### CODE REVIEW

**Comment by jvanhill** [comment]
#build

**Review by ryanesch — APPROVED** [review]

**Comment by jvanhill** [comment]
#build
#libby

**Comment by jvanhill** [comment]
Cancelled previous build and rebuild with spawn.zos=true.

https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_htDdQHk3Eeyxm-wYSNWOrg&tab=com.ibm.team.build.web.ui.internal.editors.result.properties.PropertiesProvider

**Comment by jvanhill** [comment]
#libby

Rebuilt after rebasing with more changes made for zOS build.

https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_jifvkHlxEeyxm-wYSNWOrg

**Comment by jvanhill** [comment]
Respun due to zOS build machine issues.

https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_V20bwHoLEeyxm-wYSNWOrg

**Comment by jvanhill** [comment]
Respun due to zOS and Consul issues.

https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_5hhdQHrSEeyxm-wYSNWOrg

**Comment by jvanhill** [comment]
#build

**Comment by jvanhill** [comment]
#build
#libby

**Pull request merged**
