### PR TITLE
Prolong finish for async requests

### PR DESCRIPTION
**Pull request by jonhawkes**
#build

### CODE REVIEW

**Comment by jonhawkes** [comment]
#build #libby

**Comment by jonhawkes** [comment]
#build #libby

**Comment by jonhawkes** [comment]
#build #libby

**Comment by jonhawkes** [comment]
#build #libby

**Comment by jonhawkes** [comment]
#build #libby

**Review by neilgsyoung — APPROVED** [review]
Looks good

**Comment by jonhawkes** [comment]
#build #libby

**Comment by jonhawkes** [comment]
#build #libby

**Comment by jonhawkes** [comment]
#build #libby

**Pull request merged**
