### PR TITLE
Add Java SE 12 as a support Java level for feature doc

### PR DESCRIPTION
**Pull request by aguibert**

### CODE REVIEW

**Comment by aguibert** [comment]
#build

**Comment by NottyCode** [comment]
This might affect how the Liberty repository displays Java baselines, but it won’t affect the generated feature doc for KC. That is based on the feature list generated data. 

Can the min version ever be 1.6.0? We don’t support it anymore so if it is wouldn’t that suggest our ESAs aren’t quite built correctly?

**Comment by NottyCode** [comment]
You need to update this class for the documentation to list Java SE 12:

https://github.com/OpenLiberty/open-liberty/blob/integration/dev/com.ibm.ws.kernel.feature.cmdline/src/com/ibm/ws/kernel/feature/internal/generator/FeatureList.java

**Comment by aguibert** [comment]
#build

**Comment by aguibert** [comment]
#build

**Pull request merged**
