### PR TITLE
Add multipart spec tests

### LINKED ISSUE #22884: Enable EE10 spec multipart support to work along side the IBM  proprietary multipart support
Currently the EE10 spec version of multipart support has been disabled to allow the IBM proprietary multipart support from JAXRS 2.1 and EE9 to function.   Prior to EE10 GA both alternatives should function.

### PR DESCRIPTION
**Pull request by jim-krueger**
Fixes #22884
Add test to confirm that multi-part function continue to works for the previous IBM-only APIs and the new Spec APIs (ie. EntityPart).

### CODE REVIEW

**Comment by jim-krueger** [comment]
#run-libby-bot

**Comment by jim-krueger** [comment]
#build

**Comment by jim-krueger** [comment]
#run-libby-bot

**Comment by jim-krueger** [comment]
#run-libby-bot

**Comment by jim-krueger** [comment]
#build

**Comment by jim-krueger** [comment]
#build

**Review by WhiteCat22 — DISMISSED** [review]

**Comment by jim-krueger** [comment]
#run-libby-bot

**Comment by jim-krueger** [comment]
#build

**Comment by jim-krueger** [comment]
#run-libby-bot

**Comment by jim-krueger** [comment]
#build

**Comment by jim-krueger** [comment]
#run-libby-bot

**Comment by jim-krueger** [comment]
#run-libby-bot

**Comment by jim-krueger** [comment]
#build

**Review by WhiteCat22 — DISMISSED** [review]

**Comment by jim-krueger** [comment]
#run-libby-bot

**Comment by jim-krueger** [comment]
#build

**Review by WhiteCat22 — APPROVED** [review]

**Pull request merged**
