### PR TITLE
update wsscxf.1 fat for java2sec

### PR DESCRIPTION
**Pull request by meiaus**
update com.ibm.ws.wssecurity_fat.wsscxf.1 with java2sec

### CODE REVIEW

**Comment by meiaus** [comment]
#run-libby-bot

**Comment by meiaus** [comment]
#build

**Comment by meiaus** [comment]
#run-libby-bot

**Comment by meiaus** [comment]
Note:
Initial PB were submitted with the properties `global.debug.java2.sec`, which didn't enable java2 sec (per server messages.log).
The latest PB with `global.java2.sec` enabled java2 security as expected.

**Comment by meiaus** [comment]
Note:
Initial PB were submitted with the properties `global.debug.java2.sec`, which didn't enable java2 sec (per server messages.log).
The latest PB with `global.java2.sec` enabled java2 security as expected.

**Review by jimmy1wu — COMMENTED** [review]
these files look like they were unintentionally moved from `wsscxf` to `wsscxf.saml.3`

1. dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.3/fat/com.ibm.ws.wssecurity_fat.pwdigest/.gitignore

2. dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.3/fat/com.ibm.ws.wssecurity_fat.pwdigest/bootstrap.properties

3. dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.3/fat/com.ibm.ws.wssecurity_fat.pwdigest/server.xml

4. dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.3/fat/com.ibm.ws.wssecurity_fat.pwdigest/server_withClCallback.xml

5. dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.3/fat/com.ibm.ws.wssecurity_fat.pwdigest/server_withClCallback_wss4j.xml

6. dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.3/fat/com.ibm.ws.wssecurity_fat.pwdigest/server_wss4j.xml

**Comment by meiaus** [comment]
#run-libby-bot

**Comment by meiaus** [comment]
> 
> 
> these files look like they were unintentionally moved from `wsscxf` to `wsscxf.saml.3`
> 
>     1. dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.3/fat/com.ibm.ws.wssecurity_fat.pwdigest/.gitignore
> 
>     2. dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.3/fat/com.ibm.ws.wssecurity_fat.pwdigest/bootstrap.properties
> 
>     3. dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.3/fat/com.ibm.ws.wssecurity_fat.pwdigest/server.xml
> 
>     4. dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.3/fat/com.ibm.ws.wssecurity_fat.pwdigest/server_withClCallback.xml
> 
>     5. dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.3/fat/com.ibm.ws.wssecurity_fat.pwdigest/server_withClCallback_wss4j.xml
> 
>     6. dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.3/fat/com.ibm.ws.wssecurity_fat.pwdigest/server_wss4j.xml


Deleted those files from web commits.

**Comment by meiaus** [comment]
#run-libby-bot

**Comment by meiaus** [comment]
> 
> 
> these files look like they were unintentionally moved from `wsscxf` to `wsscxf.saml.3`
> 
>     1. dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.3/fat/com.ibm.ws.wssecurity_fat.pwdigest/.gitignore
> 
>     2. dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.3/fat/com.ibm.ws.wssecurity_fat.pwdigest/bootstrap.properties
> 
>     3. dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.3/fat/com.ibm.ws.wssecurity_fat.pwdigest/server.xml
> 
>     4. dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.3/fat/com.ibm.ws.wssecurity_fat.pwdigest/server_withClCallback.xml
> 
>     5. dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.3/fat/com.ibm.ws.wssecurity_fat.pwdigest/server_withClCallback_wss4j.xml
> 
>     6. dev/com.ibm.ws.wssecurity_fat.wsscxf.saml.3/fat/com.ibm.ws.wssecurity_fat.pwdigest/server_wss4j.xml

Thanks for catching it.  It's fixed.

**Review by jimmy1wu — APPROVED** [review]

**Pull request merged**
