### PR TITLE
MYFACES-4551

### LINKED ISSUE #24111: MYFACES-4551
https://issues.apache.org/jira/browse/MYFACES-4551

Need to also pull in MYFACES PR: `https://github.com/apache/myfaces/pull/513` to fix some of the regressions we found during a personal build.

Included `UISelectOne` changes from https://github.com/volosied/myfaces/commit/80cb2af09e602c748f3f39512c0d4f060fcf16d4#diff-7b90e2ee9a32f1bd3dffb5cfd597a26374a3568ff52ffae993eba3038e6e7a08 as well.

### PR DESCRIPTION
**Pull request by pnicolucci**
fixes #24111

### CODE REVIEW

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
#libby #build #spawn.fullfat.buckets=com.ibm.ws.jsf.2.2_fat,com.ibm.ws.jsf.2.3_fat,io.openliberty.org.apache.myfaces.4.0_fat

**Comment by volosied** [comment]
I see some radio button failures... Looking into them.

**Comment by pnicolucci** [comment]
#libby #build #spawn.fullfat.buckets=com.ibm.ws.jsf.2.2_fat,com.ibm.ws.jsf.2.3_fat,io.openliberty.org.apache.myfaces.4.0_fat

**Review by volosied — APPROVED** [review]
Looks good, thanks for porting this over.

**Pull request merged**
