### PR TITLE
MP OpenAPI: Add CSP header

### PR DESCRIPTION
**Pull request by arturdzm**
Add CSP HTTP header to OpenAPI and MP OpenAPI features

### CODE REVIEW

**Comment by arturdzm** [comment]
#build

**Comment by arturdzm** [comment]
#build

**Comment by Azquelt** [comment]
This looks ok, I want to test it locally before it's merged since there are no automated tests.

**Comment by Azquelt** [comment]
Verified manually that the UI still allows requests to other domains if they're listed in the openapi document.

**Review by Azquelt — APPROVED** [review]

**Comment by Azquelt** [comment]
#libby

**Pull request merged**
