### PR TITLE
Update EclipseLink 2.6_WAS for JPA 2.1

### PR DESCRIPTION
**Pull request by dazey3**
for #16970 
for #16969 
for #15956 
for #17369 
for #16772 
for #17373 
for #17376 
for #17406 
for #17407

### CODE REVIEW

**Comment by dazey3** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jpa.tests.spec10.query_jpa_2.0_fat,com.ibm.ws.jpa.tests.spec10.query_jpa_2.1_fat,com.ibm.ws.jpa.tests.spec10.query_jpa_2.2_fat,com.ibm.ws.jpa.tests.spec10.query_jpa_3.0_fat,com.ibm.ws.jpa_eclipselink_fat

**Comment by jgrassel** [comment]
Is DHE resolved?

**Comment by dazey3** [comment]
#run-libby-bot

**Review by jgrassel — APPROVED** [review]
lgtm now

**Pull request merged**
