### PR TITLE
Issue #18322: Update ExpressionLanguage 4.0 to 10.0.10

### LINKED ISSUE #18322: Update ExpressionLanguage 4.0 API/Impl to 10.0.10

### PR DESCRIPTION
**Pull request by pnicolucci**
fixes #18322

### CODE REVIEW

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Review by volosied — APPROVED** [review]
Looks correct

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#run-libby-bot

**Review by volosied — APPROVED** [review]
Looks perfect, thanks for getting this

**Pull request merged**
