### PR TITLE
Cleanup JSF22StatelessViewTests, share common CDI bean

### PR DESCRIPTION
**Pull request by pnicolucci**
for #22202

### CODE REVIEW

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
> The build pnicolucci-24272-20230214-1131 https://wasrtc.hursley.ibm.com:9443/jazz/resource/itemOid/com.ibm.team.build.BuildResult/_mk4_cKyUEe2FnaZGnlWrhQ completed and has errors or failures.
> 
> For help analyzing your personal build, go to https://cognitive.hursley.ibm.com/buildAnalysis.html?uuid=_mk4_cKyUEe2FnaZGnlWrhQ

executing the failed child build again: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_sdHxIa0jEe2FnaZGnlWrhQ

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
#libby #build

**Review by volosied — APPROVED** [review]
Changes make sense to me. Approved.

**Pull request merged**
