### PR TITLE
updated include tag parsing

### PR DESCRIPTION
**Pull request by hermankailey**
fix for #15388 changed include tag parsing to be more flexible and handle more unique corner cases

### CODE REVIEW

**Comment by hermankailey** [comment]
#build

**Comment by hermankailey** [comment]
#build

**Review by bensonlatibm — APPROVED** [review]
Approved.
It might be helpful to document the corner cases being addressed.

**Comment by hermankailey** [comment]
corner case outlined in #15388 include tag unable to find and replace environment variables in filenames

**Pull request merged**
