### PR TITLE
JAX-WS: Remove Apache CXF 2.6.2 as a dependency. 

### PR DESCRIPTION
**Pull request by neuwerk**
This pull request removes all Open Liberty references to Apache CXF 2.6.2, as well as refactors the jaxws-2.2 bundles to reduce code reuse, and deletes the old 2.6.2 versions of the bundles.

### CODE REVIEW

**Comment by posmith** [comment]
L2 message review completed

**Comment by neuwerk** [comment]
#build

**Comment by neuwerk** [comment]
#build

**Comment by dmuelle** [comment]
I dont think there are new messages here that need ID review- adding the `ID review not needed` label. If that's not correct, let me know.

**Comment by cbridgha** [comment]
Removed target - as the bundle where this is included is not packaged in any shipped images - but cleanup should happen asap.

**Pull request closed without merging**
