### PR TITLE
Make earlyMessageTraceKiller_Timer a daemon thread

### LINKED ISSUE #25580: Non-daemon Liberty Timer threads preventing JVM shutdown in CICS (Java 17)
**Describe the bug**  

With Java 17 and on CICS, JVMs aren't recycling cleanly because non-daemon threads are active after Liberty has been stopped and are interfering with CICS's ability to restart a JVM. 

Specifically with logging, the java.util.Timer objects `earlyMessageTraceKiller_Timer` in `BaseTraceService.java` and `BufferManagerEMQHelper` in `BufferManagerEMQHelper.java` are both created as non-daemon threads, and should be changed to be daemon threads.

From a test fix changing the `earlyMessageTraceKiller_Timer` thread to daemon, the problem was resolved.

**Diagnostic information:**  
 - OpenLiberty Version: current
 - Affected feature(s): logging
 - Java Version: Java 17

### PR DESCRIPTION
**Pull request by ellen-lau**
#build

### CODE REVIEW

**Comment by ellen-lau** [comment]
#build

**Comment by ellen-lau** [comment]
#build

**Comment by ellen-lau** [comment]
#build

**Comment by ellen-lau** [comment]
fixes: #25580

**Comment by ellen-lau** [comment]
#build

**Review by Channyboy — DISMISSED** [review]

**Comment by ellen-lau** [comment]
#run-libby-bot

**Comment by ellen-lau** [comment]
#build

**Review by tonyreigns — APPROVED** [review]
LGTM

**Comment by ellen-lau** [comment]
Test failure in the build is unrelated to the changes.

**Pull request merged**
