### PR TITLE
Handle async case where app shuts down

### PR DESCRIPTION
**Pull request by Azquelt**
If an application shuts down, no more asynchronous operations can be
started for that application. With FT and async, new async operations
can be started at several points for one method call.

This change ensures that in this case, the user gets a sensible error
message, rather than an FFDC and an internal error exception.

### CODE REVIEW

**Comment by skasund** [comment]
Message review completed by L2

**Comment by Azquelt** [comment]
Hi @dmuelle, sorry I hadn't been able to get back to this. I agree with the changes proposed by @jantley-ibm and have added a commit with those changes.

**Comment by Azquelt** [comment]
#build

**Comment by dmuelle** [comment]
@Azquelt looks good! ID reviewed label added

**Comment by Azquelt** [comment]
Build did not complete correctly. Likely an infrastructure issue.

#build

**Pull request merged**
