### PR TITLE
1560 shrinkwrap helper should not default to overwiting when exporting artifacts to the server

### PR DESCRIPTION
**Pull request by benjamin-confino**

### CODE REVIEW

**Comment by benjamin-confino** [comment]
#build

**Comment by benjamin-confino** [comment]
#build

**Comment by benjamin-confino** [comment]
#build

**Comment by benjamin-confino** [comment]
#build

**Comment by benjamin-confino** [comment]
#build

**Comment by benjamin-confino** [comment]
#build

**Comment by benjamin-confino** [comment]
#build

**Comment by benjamin-confino** [comment]
#build

**Comment by benjamin-confino** [comment]
Builds were good, I will deliver when it is unlocked.

**Comment by ewhoch** [comment]
This hit a soft merge and will need to come out- apologies.

**Pull request merged**
