### PR TITLE
refactored build.gradle and buildOsNativePackages.sh

### PR DESCRIPTION
**Pull request by bensonlatibm**
Changelogs will now update timestamp and fix pack version automatically.
deb packages will now be signed if the appropriate GPG key is installed.

### CODE REVIEW

**Comment by bensonlatibm** [comment]
#build

**Comment by bensonlatibm** [comment]
#build

**Comment by bensonlatibm** [comment]
#build

**Comment by bensonlatibm** [comment]
#build

**Comment by pnicolucci** [comment]
#run-libby-bot

**Comment by bensonlatibm** [comment]
In addition to the passing PB above, manual tests were run on the shell scripts changed in this PR.

**Pull request merged**
