### PR TITLE
Update Eclipselink ASM to 9.5.

### PR DESCRIPTION
**Pull request by jgrassel**
Update Eclipselink ASM to 9.5 for Java 21 support.

### CODE REVIEW

**Comment by jgrassel** [comment]
#build

**Review by gjwatts — APPROVED** [review]

**Comment by jgrassel** [comment]
#build

**Review by dazey3 — APPROVED** [review]
LGTM!

**Comment by jgrassel** [comment]
feature modifier files updated on ws-cd, waiting for that to get moved to release before I can merge here.

**Pull request merged**
