### PR TITLE
Introduce a Singleton mechanism for messaging

### PR DESCRIPTION
**Pull request by joe-chacko**
#build

### CODE REVIEW

**Comment by AndrewDJBanks** [comment]
#build

**Comment by joe-chacko** [comment]
#build #run-libby-bot

**Comment by joe-chacko** [comment]
#build #run-libby-bot

**Comment by joe-chacko** [comment]
#build

**Comment by joe-chacko** [comment]
#build

**Comment by joe-chacko** [comment]
#build again after minor improvements
and #run-libby-bot

**Comment by joe-chacko** [comment]
#build again after minor improvements
and #run-libby-bot

**Comment by joe-chacko** [comment]
#build once more for the win

**Review by ngmr — APPROVED** [review]
This is a great functional step forward.

There are some minor code formatting improvements that could be made, and the exception message in MPSelectionCriteriaFactory.getInstance() should be updated to reflect the change in method name (from createFactoryInstance()), but overall I think these can be addressed in a subsequent change, and these changes are worthy enough to be promoted as is.

**Pull request merged**
