### PR TITLE
Remove CXF's org.apache.cxf.jaxrs.client.blueprint.Activator from JAX-RS and JAX-WS

### PR DESCRIPTION
**Pull request by WhiteCat22**
We've meant to remove `org.apache.cxf.jaxrs.client.blueprint.Activator` from our CXF bundles when we released `jaxrs-2.1` however, we missed some and some additional bundles brought more in with the `jaxws-2.2` upgrade to CXF 3.4.3.

This PR removes them from our bundles' `MANIFEST.MF` files so that we don't attempt to load them. (by not bringing the headers in from the original CXF jars in the first place)

I also did some formatting cleanup to the bnd files while I was in there.

### CODE REVIEW

**Comment by WhiteCat22** [comment]
#libby #build #spawn.fullfat.buckets=com.ibm.ws.jaxws.2.2.webcontainer_fat,com.ibm.ws.jaxws.2.2.webcontainer_fat_extended,com.ibm.ws.jaxws.clientcontainer_fat,com.ibm.ws.jaxws.cdi_fat,com.ibm.ws.jaxws.ejb_fat,com.ibm.ws.jaxws.X.wsat_fat,com.ibm.ws.jaxrs.2.0_fat,com.ibm.ws.jaxrs.2.1_fat,com.ibm.ws.jaxrs.2.1_fat_executor,io.openliberty.ws.jaxrs.2.1.jaxws.2.2_fat,io.openliberty.ws.jaxrs.global.handler.internal_fat,io.openliberty.ws.jaxws.global.handler.internal_fat,com.ibm.ws.wsat.common_fat,com.ibm.ws.wsat.concurrent_fat,com.ibm.ws.wsat.migration_fat.1,com.ibm.ws.wsat.migration_fat.2,com.ibm.ws.wsat.migration_fat.3,com.ibm.ws.wsat.migration_fat.4,com.ibm.ws.wsat.migration_fat.5,com.ibm.ws.wsat.recovery_fat.multi.1,com.ibm.ws.wsat.recovery_fat.multi.2,com.ibm.ws.wsat.recovery_fat.multi.3,com.ibm.ws.wsat.recovery_fat.multi.4,com.ibm.ws.wsat.recovery_fat.single,com.ibm.ws.wsat_fat.db,com.ibm.ws.wsat_fat.ssl,com.ibm.ws.wsat_fat.multi,com.ibm.ws.wsat_fat.assertion,com.ibm.ws.wsat_fat.dbs_optional,com.ibm.ws.wsat_fat.dbs,com.ibm.ws.wsat_fat.db_optional,com.ibm.ws.wssecurity_fat.wsscxf.saml.3,com.ibm.ws.wssecurity_fat.wsscxf.1,com.ibm.ws.wssecurity_fat.wsscxf.saml.2,com.ibm.ws.wssecurity_fat.wsscxf.saml.4,com.ibm.ws.wssecurity_fat.wsscxf,com.ibm.ws.wssecurity_fat.wsscxf.saml.1,com.ibm.ws.wssecurity_fat.wsscxf.saml,com.ibm.ws.wssecurity_fat.wsscxf.saml.5,com.ibm.ws.jaxrs.2.0_fat,com.ibm.ws.jaxrs.2.0.cdi.1.2_fat,com.ibm.ws.jaxrs.2.0.client_fat,com.ibm.ws.jaxrs.2.1_fat,com.ibm.ws.jaxrs.2.1_fat_executor,com.ibm.ws.jaxrs.2.1_fat_extended,com.ibm.ws.jaxrs.2.1.cdi.2.0_fat,com.ibm.ws.jaxrs.2.1.client_fat,com.ibm.ws.jaxrs.2.1.sse_fat,com.ibm.ws.jaxrs.2.x_fat_clientProps

**Comment by WhiteCat22** [comment]
I manually compared the `MANIFEST.MF` files before and after my changes to make sure important headers we not lost.

**Review by neuwerk — APPROVED** [review]
Changes look good to me, thanks @WhiteCat22 for doing this for both teams!

**Comment by neuwerk** [comment]
The WS-Security failures in the PB are intermittent issues that are related to already known defects

**Comment by WhiteCat22** [comment]
#libby #build #spawn.fullfat.buckets=com.ibm.ws.jaxws.2.2.webcontainer_fat,com.ibm.ws.jaxws.2.2.webcontainer_fat_extended,com.ibm.ws.jaxws.clientcontainer_fat,com.ibm.ws.jaxws.cdi_fat,com.ibm.ws.jaxws.ejb_fat,com.ibm.ws.jaxws.X.wsat_fat,com.ibm.ws.jaxrs.2.0_fat,com.ibm.ws.jaxrs.2.1_fat,com.ibm.ws.jaxrs.2.1_fat_executor,io.openliberty.ws.jaxrs.2.1.jaxws.2.2_fat,io.openliberty.ws.jaxrs.global.handler.internal_fat,io.openliberty.ws.jaxws.global.handler.internal_fat,com.ibm.ws.wsat.common_fat,com.ibm.ws.wsat.concurrent_fat,com.ibm.ws.wsat.migration_fat.1,com.ibm.ws.wsat.migration_fat.2,com.ibm.ws.wsat.migration_fat.3,com.ibm.ws.wsat.migration_fat.4,com.ibm.ws.wsat.migration_fat.5,com.ibm.ws.wsat.recovery_fat.multi.1,com.ibm.ws.wsat.recovery_fat.multi.2,com.ibm.ws.wsat.recovery_fat.multi.3,com.ibm.ws.wsat.recovery_fat.multi.4,com.ibm.ws.wsat.recovery_fat.single,com.ibm.ws.wsat_fat.db,com.ibm.ws.wsat_fat.ssl,com.ibm.ws.wsat_fat.multi,com.ibm.ws.wsat_fat.assertion,com.ibm.ws.wsat_fat.dbs_optional,com.ibm.ws.wsat_fat.dbs,com.ibm.ws.wsat_fat.db_optional,com.ibm.ws.wssecurity_fat.wsscxf.saml.3,com.ibm.ws.wssecurity_fat.wsscxf.1,com.ibm.ws.wssecurity_fat.wsscxf.saml.2,com.ibm.ws.wssecurity_fat.wsscxf.saml.4,com.ibm.ws.wssecurity_fat.wsscxf,com.ibm.ws.wssecurity_fat.wsscxf.saml.1,com.ibm.ws.wssecurity_fat.wsscxf.saml,com.ibm.ws.wssecurity_fat.wsscxf.saml.5,com.ibm.ws.jaxrs.2.0_fat,com.ibm.ws.jaxrs.2.0.cdi.1.2_fat,com.ibm.ws.jaxrs.2.0.client_fat,com.ibm.ws.jaxrs.2.1_fat,com.ibm.ws.jaxrs.2.1_fat_executor,com.ibm.ws.jaxrs.2.1_fat_extended,com.ibm.ws.jaxrs.2.1.cdi.2.0_fat,com.ibm.ws.jaxrs.2.1.client_fat,com.ibm.ws.jaxrs.2.1.sse_fat,com.ibm.ws.jaxrs.2.x_fat_clientProps

added a second commit for some additional cleanup

**Pull request merged**
