### PR TITLE
Issue 5789 - use jar/wsjar protocol for root dirctory

### PR DESCRIPTION
**Pull request by tjwatson**
For #5789 
#build

Still need to write a testcase.

### CODE REVIEW

**Comment by tjwatson** [comment]
#build

**Comment by anjumfatima90** [comment]
#build

**Comment by anjumfatima90** [comment]
#build

**Comment by anjumfatima90** [comment]
#build

**Comment by tjwatson** [comment]
For the record, @anjumfatima90 picked up my PR and has contributed tests for the update.  I approve of the changes (github won't let me mark myself as a reviewer of my own PR).

**Pull request merged**
