### PR TITLE
Update apache commons to 3.14.0

### PR DESCRIPTION
**Pull request by benjamin-confino**
This updates us to the latest version of apache commons, partly because keeping updated is good but mostly because I want to use the more recent version of LazyInitializer in the open telemetry bundle.

### CODE REVIEW

**Comment by benjamin-confino** [comment]
#build

**Review by jhanders34 — DISMISSED** [review]

**Comment by jhanders34** [comment]
#build

**Comment by benjamin-confino** [comment]
#build

**Review by jhanders34 — APPROVED** [review]

**Comment by benjamin-confino** [comment]
#libby

**Pull request merged**
