### PR TITLE
Wsat serviceability

### PR DESCRIPTION
**Pull request by jonhawkes**

### CODE REVIEW

**Comment by jonhawkes** [comment]
#build
#run-libby-bot

**Comment by jonhawkes** [comment]
#build
#run-libby-bot

**Comment by jonhawkes** [comment]
#build

**Comment by jonhawkes** [comment]
#build
#run-libby-bot

**Comment by jonhawkes** [comment]
#build
#run-libby-bot

**Comment by jonhawkes** [comment]
#build
#run-libby-bot

**Comment by jonhawkes** [comment]
#build
#run-libby-bot

**Comment by jonhawkes** [comment]
#build
#run-libby-bot

**Comment by jonhawkes** [comment]
#build
#run-libby-bot

**Review by neilgsyoung — APPROVED** [review]
Looks good

**Comment by jonhawkes** [comment]
#build
#run-libby-bot

**Pull request merged**
