### PR TITLE
Max Java version is set to 17

### LINKED ISSUE #25848: Set maximum java level
As part of the deprecation of the Java Security Manager, as specified by JEP 411, Liberty does not support the Java Security Manager with Java 18 or later. Test that was using Java Security Manager is set to be skipped for java version 18 and above.

### PR DESCRIPTION
**Pull request by BerksanAtes**
Fixes #25848

### CODE REVIEW

**Comment by BerksanAtes** [comment]
#build

**Comment by BerksanAtes** [comment]
#build

**Comment by BerksanAtes** [comment]
#build

**Review by sawadood — APPROVED** [review]
Changes look good

**Comment by BerksanAtes** [comment]
#run-libby-bot

**Comment by BerksanAtes** [comment]
#run-libby-bot

**Comment by BerksanAtes** [comment]
#run-libby-bot

**Comment by BerksanAtes** [comment]
#run-libby-bot

**Pull request merged**
