### PR TITLE
Less Latching and Better Processing

### PR DESCRIPTION
**Pull request by billw1024**

### CODE REVIEW

**Comment by billw1024** [comment]
fixes #14216

**Comment by billw1024** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.grpc_fat

**Review by wtlucy — APPROVED** [review]
great improvement from my POV

**Comment by billw1024** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.grpc_fat

**Comment by billw1024** [comment]
latest build had just 4 failures, none related to these changes.  will merge

**Comment by billw1024** [comment]
#run-libby-bot

**Comment by wtlucy** [comment]
this generally fixed #13091

**Pull request merged**
