### PR TITLE
Revert "Revert "WI#1296: Rename JPA 2.2 Container + CDI 2.0 Autofeature and remove ve…""

### PR DESCRIPTION
**Pull request by jgrassel**
Reverts OpenLiberty/open-liberty#2231

Needed change is in CD origin/master

commit 60763c865387ac1a3ae4fb300641ad7fe3332583
Author: Joe Grassel <jgrassel@us.ibm.com>
Date:   Thu Feb 1 10:22:40 2018 -0600

    Remove jpa-cdi autofeature from 17004 feature verifyer list to enable OL#1890 delivery.
    
    Signed-off-by: Joe Grassel <jgrassel@us.ibm.com>

### CODE REVIEW

**Comment by jgrassel** [comment]
#build

**Comment by jgrassel** [comment]
#build

**Comment by jgrassel** [comment]
#build

**Comment by jgrassel** [comment]
#build

**Comment by ewhoch** [comment]
@jgrassel is this needed anymore? It's holding a branch open in origin.

**Comment by tevans78** [comment]
Although you might want a new personal build before delivery?

**Comment by jgrassel** [comment]
#build

**Comment by jgrassel** [comment]
#build

**Comment by jgrassel** [comment]
Delivered via another pull request, closing this issue.

**Pull request closed without merging**
