### PR TITLE
mpOpenAPI: fix multipleOf validation check

### LINKED ISSUE #18002: `@Schema(multipleOf = )` validation check is wrong in all versions of the `mpOpenAPI` feature
Split from #17972, reported by @rslemos

**With `multipleOf = 1`, then upon application deploy the server shows:**

> [INFO] [ERROR   ] CWWKO1650E: Validation of the OpenAPI document produced the following error(s):
> [INFO]
> [INFO]  - Message: The Schema Object must have the "multipleOf" property set to a number strictly greater than zero, Location: #/components/schemas/...

Either the validation is wrong and `multipleOf = 1` should be accepted. Or the message should go "...strictly greater than one".

Even with such an "ERROR", the OpenAPI document is generated, with `multipleOf = 1`. (IMHO this message should then be downgraded to a WARNING).

**Expected behavior**
I was trying to document my endpoint to tell that it accepts decimal values no more precise than `0.0001` (i.e. a `BigDecimal` with scale 4). To this end I've tried `multipleOf = 0.0001d`.

I don't know if the specs allow for fractional `multipleOf`. If not, then I expect a clearer error/warning message stating the fact (actually in this case I'd expect the attribute `multipleOf` to be `int`).

**Diagnostic information:**
 - OpenLiberty Version: 21.0.0.6/wlp-1.0.53.cl210620210527-1900
 - Java Version:  Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_271-b09 (en_BR)
 - server.xml configuration 
   > Installing features: [jsonb-1.0, jndi-1.0, cdi-2.0, passwordutilities-1.0, jdbc-4.2, localconnector-1.0, ejblite-3.2, jaxrs-2.1, concurrent-1.0, appsecurity-3.0, mpopenapi-2.0, beanvalidation-2.0, jpa-2.2, mphealth-3.0]
 and one minor oddity related to `<classloader apiTypeVisibility="+third-party" commonLibraryRef="..."/>`

### PR DESCRIPTION
**Pull request by Azquelt**
The validation check was checking that multipleOf is greater than or equal to one, rather than checking that it's greater than zero.

In addition to the fix:
 - enhance unit tests to check for this case
 - fix the message name so that it matches what the message actually says :facepalm: 

Fixes #18002

### CODE REVIEW

**Comment by Azquelt** [comment]
This does not need L2 or ID review because there are no changes to the actual messages. Only the message label (the string used to reference the message from the code) has changed so that it matches the message.

**Comment by Azquelt** [comment]
#build

**Review by Emily-Jiang — APPROVED** [review]
LGTM

**Comment by Azquelt** [comment]
#run-libby-bot

**Comment by Azquelt** [comment]
The failures in the build do not appear to be related to this change.

**Pull request merged**
