### PR TITLE
Issue #417: remove commons.codec and manifest for jsf-2.3

### PR DESCRIPTION
**Pull request by pnicolucci**

### CODE REVIEW

**Comment by pnicolucci** [comment]
Fixes Issue #417

**Comment by pnicolucci** [comment]
#build  spawn.fullfat.buckets=com.ibm.ws.jsf.2.3_fat,com.ibm.ws.jsf.2.2_fat_jsf2.3,com.ibm.ws.jsf_fat_jsf2.3

**Comment by pnicolucci** [comment]
#build spawn.fullfat.buckets=com.ibm.ws.jsf.2.3_fat,com.ibm.ws.jsf.2.2_fat_jsf2.3,com.ibm.ws.jsf_fat_jsf2.3

**Comment by wraschke** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jsf.2.3_fat,com.ibm.ws.jsf.2.2_fat_jsf2.3,com.ibm.ws.jsf_fat_jsf2.3

**Pull request merged**
