### PR TITLE
Refactor MpTelemetry 1.0 and 1.1 common code

### LINKED ISSUE #27666: Refactor mpTelemetry-1.1 and 1.0 code
There is code in `[io.openliberty.microprofile.telemetry.internal.common](https://github.com/OpenLiberty/open-liberty/tree/8dfc96e8d0f06f94de4d8c6172a5f80b2763b131/dev/io.openliberty.microprofile.telemetry.internal.common)` that wouldn't suitable for `mpTelemetry-2.0`, for example, code that disables metrics. This needs to be taken out of common or be version controlled.

### PR DESCRIPTION
**Pull request by Yas-Franco**
Fixes #27666
In preperation for MpTelemetry 2.0 development

### CODE REVIEW

**Review by benjamin-confino — DISMISSED** [review]

**Comment by Yas-Franco** [comment]
#build
#spawn.fullfat.buckets=io.openliberty.microprofile.telemetry.1.0.internal_fat,io.openliberty.microprofile.telemetry.1.0.internal.jaeger_fat,io.openliberty.microprofile.telemetry.1.0.internal_fat_tck,io.openliberty.microprofile.telemetry.1.1.internal_fat_tck

**Comment by Yas-Franco** [comment]
#build
#spawn.fullfat.buckets=io.openliberty.microprofile.telemetry.1.0.internal_fat,io.openliberty.microprofile.telemetry.1.0.internal.jaeger_fat,io.openliberty.microprofile.telemetry.1.0.internal_fat_tck,io.openliberty.microprofile.telemetry.1.1.internal_fat_tck

**Comment by Yas-Franco** [comment]
#build

**Comment by Yas-Franco** [comment]
#build
#spawn.fullfat.buckets=io.openliberty.microprofile.telemetry.1.0.internal_fat,io.openliberty.microprofile.telemetry.1.0.internal.container_fat,io.openliberty.microprofile.telemetry.1.0.internal_fat_tck,io.openliberty.microprofile.telemetry.1.1.internal_fat_tck

**Comment by Yas-Franco** [comment]
#build
#spawn.fullfat.buckets=io.openliberty.microprofile.telemetry.1.0.internal_fat,io.openliberty.microprofile.telemetry.1.0.internal.container_fat,io.openliberty.microprofile.telemetry.1.0.internal_fat_tck,io.openliberty.microprofile.telemetry.1.1.internal_fat_tck

**Comment by Yas-Franco** [comment]
#libby

**Review by benjamin-confino — APPROVED** [review]

**Comment by Yas-Franco** [comment]
#build
#spawn.fullfat.buckets=io.openliberty.microprofile.telemetry.1.0.internal_fat,io.openliberty.microprofile.telemetry.1.0.internal.container_fat,io.openliberty.microprofile.telemetry.1.0.internal_fat_tck,io.openliberty.microprofile.telemetry.1.1.internal_fat_tck

**Pull request merged**
