### PR TITLE
Add TrustedProxyEnable and TrustedProxyGroup as config options in the

### PR DESCRIPTION
**Pull request by zaroman**
pluginConfiguration stanza of the server.xml.

TrustedProxyEnable is a boolean needed to use trusted proxies.
TrustedProxyGroup is a comma-separated list of trusted proxies.

### CODE REVIEW

**Comment by zaroman** [comment]
#build

**Comment by sishida** [comment]
Hello! ID writer here! Does this message require ID review? If so, please add the "ID Required" label. If it does not need ID review, please add the "ID review not needed" label. Thank you!

**Comment by sishida** [comment]
Hello! ID writer here! Does this message require ID review? If so, please add the "ID Required" label. If it does not need ID review, please add the "ID review not needed" label. Thank you!

**Comment by zaroman** [comment]
#build

**Comment by zaroman** [comment]
Fixes #614

**Comment by zaroman** [comment]
#build

**Comment by zaroman** [comment]
#build

**Comment by zaroman** [comment]
#build

**Comment by zaroman** [comment]
#buil

**Comment by zaroman** [comment]
#build

**Comment by zaroman** [comment]
The metatype validator test has been modified to suppress the attribLabelNotSentenceCase error for these two new attributes.

**Pull request merged**
