### PR TITLE
Test change to com.ibm.ws.jca

### PR DESCRIPTION
**Pull request by fritze2**
- One line change to `dev/com.ibm.ws.jca/src/com/ibm/ws/jca/internal/ActivationConfig.java` in order to verify this builds only the required projects and image, and only runs tests specific to this functional area.

### CODE REVIEW

**Comment by wraschke** [comment]
#pbbeta

**Comment by fritze2** [comment]
#build

**Comment by fritze2** [comment]
#build

**Comment by fritze2** [comment]
#build

**Comment by fritze2** [comment]
#build

**Comment by fritze2** [comment]
!pb
!pbbeta

**Comment by fritze2** [comment]
!pb

**Comment by fritze2** [comment]
!pb
!pbbeta

**Comment by fritze2** [comment]
!pb
!pbbeta

**Comment by fritze2** [comment]
!pb
!pbbeta

**Comment by fritze2** [comment]
This test needs to be replaced with a PR that changes another project / functional area in order to test FAT selection. Changes to the com.ibm.ws.jca project cause all FATs to run due to the exception:

```
java.lang.NullPointerException: Cannot invoke "java.util.Collection.addAll(java.util.Collection)" because "rootPlatforms" is null
	at com.ibm.ws.kernel.feature.internal.FeatureResolverImpl.doResolve(FeatureResolverImpl.java:580)
	at com.ibm.ws.kernel.feature.internal.FeatureResolverImpl.resolve(FeatureResolverImpl.java:559)
	at com.ibm.ws.kernel.feature.internal.FeatureResolverImpl.resolveFeatures(FeatureResolverImpl.java:428)
	at com.ibm.ws.infra.depchain.FeatureCollection.getEnabledFeatures(FeatureCollection.java:72)
	at com.ibm.ws.infra.depchain.ChangeDetector.getFATsTestingFeatures(ChangeDetector.java:288)
	at com.ibm.ws.infra.depchain.ChangeDetector.getFatsToRun(ChangeDetector.java:184)
	at com.ibm.ws.infra.depchain.ChangeDetector.main(ChangeDetector.java:79)
ChangeDetector found these FATs to run: [all]
```

**Pull request closed without merging**
