### PR TITLE
inital set of thread local storage tests

### PR DESCRIPTION
**Pull request by tabishop**
Initial set of thread local storage tests. This is just an initial set of tests that will need to be cleaned up.

### CODE REVIEW

**Comment by tabishop** [comment]
#build

**Comment by tabishop** [comment]
#build

**Comment by jmstephensgit** [comment]
Reviewed but waiting until Monday to approve.

**Review by jmstephensgit — APPROVED** [review]

**Comment by tabishop** [comment]
#run-libby-bot

**Comment by tabishop** [comment]
#build

**Pull request merged**
