### PR TITLE
FIX added a check to make sure jax-ws components are not tested with Java version above Java8

### PR DESCRIPTION
**Pull request by Erikkre**
Last PR was not working with all versions of Java but this amended one was tested for all locally. Will see result of personal build for java 8 and manual rtc build for java 11
Issue #5757

### CODE REVIEW

**Comment by Erikkre** [comment]
#build

**Comment by jhanders34** [comment]
This still seems like the wrong solution.  Do you not just need to update the server_monitorFilter1.xml, server_monitorFilter2.xml, server_monitorFilter3.xml and server_monitorFilter4.xml files to add the jaxws-2.2 feature like is done in the server_mpMetric11.xml and server_monitor.xml files?  When that is done I assume this problem will go away and the test will work for Java 8 and Java 11.

**Comment by Erikkre** [comment]
#build

**Comment by Erikkre** [comment]
Build breaks are due to the unrelated timeout errors, not the implemented fixes.

**Pull request merged**
