### PR TITLE
Port JPA 1.0 Query Tests (initial pass)

### PR DESCRIPTION
**Pull request by jgrassel**
Initial port of Query FAT (first of several passes)

### CODE REVIEW

**Comment by jgrassel** [comment]
#build

**Comment by jgrassel** [comment]
#build

**Comment by tkburroughs** [comment]
#build

**Comment by tkburroughs** [comment]
@jgrassel build failed; submitted another one

**Comment by jgrassel** [comment]
#build

**Comment by jgrassel** [comment]
#run-libby-bot

**Pull request merged**
