### PR TITLE
Issue #16468: Remove SharedServer from HttpSessionAttListener test class

### LINKED ISSUE #16468: Remove SharedServer from HttpSessionAttListener Servlet 31 FAT

### PR DESCRIPTION
**Pull request by pnicolucci**
fixes #16468

### CODE REVIEW

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Review by isaacrivriv — APPROVED** [review]
Looks good to me thanks!

**Comment by isaacrivriv** [comment]
#run-libby-bot

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#run-libby-bot

**Pull request merged**
