### PR TITLE
Deliver 21.0.0.10 NLS updates

### PR DESCRIPTION
**Pull request by pnickoll**

### CODE REVIEW

**Comment by pnickoll** [comment]
#build

**Review by dbarfield — APPROVED** [review]

**Comment by pnickoll** [comment]
#build

**Comment by pnickoll** [comment]
#run-libby-bot

**Comment by pnickoll** [comment]
#libby

**Comment by pnickoll** [comment]
#build

**Comment by pnickoll** [comment]
#build

**Pull request merged**
