### PR TITLE
Issue #19906: Ensure WIM config changes are processed by the LDAP reg…

### LINKED ISSUE #19906: Test Failure: com.ibm.ws.security.wim.scim.fat.CreateAndDeleteTest.createAndDeleteExtendedUserNoMapping
This test fails due to a variability in the timing window between when the WIM federated repository configuration is processed, and the LDAP configuration is processed during configuration updates processed during runtime.

The LDAP configuration relies on federated repository configuation, but in this case, the test updates federated repository configuration, but the LDAP configuration is processed first. Since that occurs, the changes to federated repository configuration are not processed when the LDAP configuration is processed.

```
createAndDeleteExtendedUserNoMapping:junit.framework.AssertionFailedError: 2020-08-22-12:09:01:047 Expected response 500, received 201 (Created) while connecting to https://localhost:8020/ibm/api/scim/Users. Unable to reset streamToWrite. Error stream: null
at componenttest.topology.utils.HttpUtils.getHttpConnection(HttpUtils.java:294)
at com.ibm.ws.security.wim.scim.util.SCIMUtils.callURL(SCIMUtils.java:76)
at com.ibm.ws.security.wim.scim.fat.CreateAndDeleteTest.createAndDeleteExtendedUserNoMapping(CreateAndDeleteTest.java:566)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at componenttest.custom.junit.runner.FATRunner$1.evaluate(FATRunner.java:203)
at componenttest.custom.junit.runner.FATRunner$2.evaluate(FATRunner.java:343)
at componenttest.custom.junit.runner.FATRunner.run(FATRunner.java:177)
```

### PR DESCRIPTION
**Pull request by jvanhill**
…istry after they are processed by federated repositories.

fixes #19906

### CODE REVIEW

**Review by kristip17 — APPROVED** [review]

**Comment by jvanhill** [comment]
#build

**Comment by jvanhill** [comment]
@OpenLiberty/message-reviewer - Please ignore all changes to the messages except CWIML4534E (the last message in the file), as the others were just moved to put them more in order.

**Review by helyarp — COMMENTED** [review]
CWIML4534E looks good!

**Comment by jvanhill** [comment]
Corrected a comment, which does not require a rebuild.

**Comment by jvanhill** [comment]
#libby

**Pull request merged**
