### PR TITLE
Jakarta security fat setup

### PR DESCRIPTION
**Pull request by c00crane**
Deliver FAT test setup for Jakarta openidconnect.
Setup junit test in the security FAT framework.
Create a simple client app with annotated config and a simple Callback.

### CODE REVIEW

**Comment by c00crane** [comment]
#build

**Review by ayoho — APPROVED** [review]

**Comment by c00crane** [comment]
#build

**Comment by c00crane** [comment]
#build

**Comment by c00crane** [comment]
#run-libby-bot

**Comment by c00crane** [comment]
#run-libby-bot
#build

**Pull request merged**
