### PR TITLE
Retry Gradle version update

### PR DESCRIPTION
**Pull request by wraschke**
This is retrying the [Gradle version update attempt](https://github.com/OpenLiberty/open-liberty/pull/23350), which I reverted because of problems and because it was too close to 23.0.0.2 GM driver day.

### CODE REVIEW

**Comment by wraschke** [comment]
#build

**Comment by wraschke** [comment]
The one test failure in `com.ibm.ws.eba.app.runtime_fat` in the above PB is a known defect: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.workitem.viewWorkItem&id=294697

**Comment by wraschke** [comment]
#build

**Review by fritze2 — APPROVED** [review]

**Comment by wraschke** [comment]
The PB with UUID _zO0KELgpEe2r6re_Zvbagg has a red child build, f7, due to this failure (in its build.log):

```
     [java] Target 'launchFatTests' failed with message 'The following error occurred while executing this line:
     [java] /home/jazz_build/Build/jbe/build/dev/ant_build/build-liberty-with-controlled-jvm.xml:437: /home/jazz_build/Build/jbe/build/dev/ant_build/build-liberty-with-controlled-jvm.xml:624: The following error occurred while executing this line:
     [java] /home/jazz_build/Build/jbe/build/dev/ant_build/public_imports/internal_imports/standard_macros.xml:440: The following error occurred while executing this line:
     [java] /home/jazz_build/Build/jbe/build/dev/ant_build/public_imports/internal_imports/standard_macros.xml:493: com.ibm.team.repository.common.transport.ConnectionException: CRJAZ1372E The following URL cannot be reached: /jazz/service/com.ibm.team.build.internal.common.ITeamBuildService. The connection timed out. The server returned this error: Connect to wasrtc.hursley.ibm.com:9443 [wasrtc.hursley.ibm.com/9.20.59.55] failed: Connection timed out.'.
```

That is a problem with wasrtc's connection, not anything due to this PR's changes. The build code involved in flow was trying to link files to the build and could not due to wasrtc being flakey.

I verified that all the tests that ran as a part of f7 had their results in the PB.

Additionally, the failed FAT com.ibm.ws.transaction.hadb_fat.oracle.retriablecodes has an error that matches to https://wasrtc.hursley.ibm.com:9443/jazz/resource/itemName/com.ibm.team.workitem.WorkItem/294819 and that appears to be an infrastructure/Fyre problem. The Admin Center FAT failures, like `junit.framework.AssertionFailedError: Unable to get a valid webdriver from the container`, should not be at all related to this PR's changes.

I can confirm through the ivyBuild build.log and the various gradle_* log files that the default Gradle 6.8.3 version is still in use for this PB:

```
[01-Mar-2023 11:39:08:915 PST] 00000032      [exec] To honour the JVM settings for this build a single-use Daemon process will be forked. See https://docs.gradle.org/6.8.3/userguide/gradle_daemon.html#sec:disabling_the_daemon.
```

```
To honour the JVM settings for this build a single-use Daemon process will be forked. See https://docs.gradle.org/6.8.3/userguide/gradle_daemon.html#sec:disabling_the_daemon.
```

That is what I wanted and expected to see out of the # build PB--the existing behavior and defaults should be intact.

The new 7.4.1 version won't take affect until we set `gradle.version` = `7.4.1` and `gradle.wl.version` = `6.8.3` on the build definitions where want the upgrade to take effect.

So I am merging this PR.

**Comment by wraschke** [comment]
#libby

**Pull request merged**
