### PR TITLE
style: spell invoke correctly

### PR DESCRIPTION
**Pull request by joe-chacko**
- [x] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [x] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [x] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

### CODE REVIEW

**Comment by joe-chacko** [comment]
!build

**Comment by contbld** [comment]
Your personal pipeline request is at https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=c7616a9c-81b5-423a-8cd4-be6a412e7e26

Target locations of links might be accessible only to IBM employees.

**Comment by contbld** [comment]
Your personal pipeline request is at https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=0ac865c3-7037-4ec0-8699-032902e17803

Target locations of links might be accessible only to IBM employees.

**Review by ngmr — APPROVED** [review]

**Comment by contbld** [comment]
<h3>Code analysis and actions</h3>
DO NOT DELETE THIS COMMENT.

- 19 FAT files were changed, added, or removed.
 - Check that the build did not break the affected FAT suite(s).

- 3 test infrastructure code files were changed.
 - Test failures/errors in the build could be due to these changes.

- 2 product code files were changed.

**Comment by contbld** [comment]
<h3>Code analysis and actions</h3>
DO NOT DELETE THIS COMMENT.

- 19 FAT files were changed, added, or removed.
 - Check that the build did not break the affected FAT suite(s).

- 3 test infrastructure code files were changed.
 - Test failures/errors in the build could be due to these changes.

- 2 product code files were changed.

**Comment by contbld** [comment]
https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=c7616a9c-81b5-423a-8cd4-be6a412e7e26 completed successfully!

**Comment by contbld** [comment]
https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=0ac865c3-7037-4ec0-8699-032902e17803 has errors/failures.

**Pull request merged**
