### PR TITLE
Wait for tests to completely finish

### PR DESCRIPTION
**Pull request by jonhawkes**
#build
#spawn.fullfat.buckets=com.ibm.ws.wsat_fat.multi,com.ibm.ws.wsat_fat.multi.misroute

### CODE REVIEW

**Review by neilgsyoung — DISMISSED** [review]
Looks good

**Comment by jonhawkes** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.wsat_fat.multi,com.ibm.ws.wsat_fat.multi.misroute

**Comment by jonhawkes** [comment]
#libby
#build
#spawn.fullfat.buckets=com.ibm.ws.wsat_fat.multi,com.ibm.ws.wsat_fat.multi.misroute

**Review by neilgsyoung — APPROVED** [review]
looks peachy!

**Pull request merged**
