### PR TITLE
Servlet 6.1 create initial WebContainer classes

### LINKED ISSUE #27090: Servlet 6.1 Create intial WebContainer classes
Create the essential WebContainer classes: request, response, connection context, webapp context.

### PR DESCRIPTION
**Pull request by pmd1nh**
fixes https://github.com/OpenLiberty/open-liberty/issues/27090

Create the initial classes: request, response, webapp, connection context.
Add a simple FAT test.

### CODE REVIEW

**Comment by pmd1nh** [comment]
#build

**Comment by pmd1nh** [comment]
<html><head></head><body>
io.openliberty.webcontainer.servlet.6.1.internal_fat FAT tests | 1 | 0 | 0 |   |  
-- | -- | -- | -- | -- | --
io.openliberty.webcontainer.servlet61.fat.tests.Servlet61SimpleServletTest | 1 | 0 | 0 | 1 s | 

</body></html>

**Comment by pmd1nh** [comment]
removed FAT.

#build

**Review by pnicolucci — APPROVED** [review]

**Comment by pmd1nh** [comment]
#libby

**Pull request merged**
