### PR TITLE
Update CDI tests for Faces 4.0 that looked for session beans in the session map

### PR DESCRIPTION
**Pull request by pnicolucci**
for #22368

### CODE REVIEW

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
Java 17 build: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_5Ur84IfpEe2iX8vFQv1q7A

**Comment by pnicolucci** [comment]
Java 17 build was successful.

**Comment by pnicolucci** [comment]
#libby #build

**Review by isaacrivriv — APPROVED** [review]
Changes look good to me. Thanks!!

**Pull request merged**
