### PR TITLE
[18794] LibertyAuthFilter for checking RoleMethodAuthUtil

### LINKED ISSUE #18794: JAX-RS 3.0 does not invoke request.authenticate like in 2.1, resulting in 403 errors
The JAX-RS 3.0 rest code in the server side needs to call request.authenticate before it calls isUserInRole. This is affecting the MP JWT 2.0's TCK tests.

2.1 rest client has com.ibm.ws.jaxrs20.security.LibertyAuthFilter, but it appears the 3.0 client does not have one. The rest client appears to just call request.isUserInRole

> [9/27/21, 11:06:51:740 CDT] 0000003d id=767cdbcf .ibm.ws.webcontainer.security.WebAppSecurityCollaboratorImpl < preInvoke Exit  
>                                                                                                                com.ibm.ws.webcontainer.security.WebSecurityContext@41d2d723
> [9/27/21, 11:06:51:740 CDT] 0000003d id=00000000 com.ibm.wsspi.webcontainer.collaborator.CollaboratorHelper   < preInvokeCollaborators RETURN
> [9/27/21, 11:06:51:740 CDT] 0000003d id=00000000 com.ibm.wsspi.webcontainer.WebContainerRequestState          3 getInstance created->true, request state->com.ibm.wsspi.webcontainer.WebContainerRequestState@8768a79
> [9/27/21, 11:06:51:740 CDT] 0000003d id=00000000 com.ibm.wsspi.webcontainer.WebContainerRequestState          1 setInvokedFilters  invokedFilters --> true
> [9/27/21, 11:06:51:740 CDT] 0000003d id=fb32234e com.ibm.ws.security.jaspi.JaspiServletFilter                 > doFilter Entry  
>                                                                                                                com.ibm.ws.webcontainer40.srt.SRTServletRequest40@3ad75eca
>                                                                                                                com.ibm.ws.webcontainer40.srt.SRTServletResponse40@c2d62003
>                                                                                                                com.ibm.ws.webcontainer.filter.WebAppFilterChain@130a11c8
> [9/27/21, 11:06:51:740 CDT] 0000003d id=00000000 com.ibm.wsspi.webcontainer.WebContainerRequestState          3 getInstance created->false, request state->com.ibm.wsspi.webcontainer.WebContainerRequestState@8768a79
> [9/27/21, 11:06:51:740 CDT] 0000003d id=00000000 com.ibm.wsspi.webcontainer.WebContainerRequestState          1 isInvokedFilters  _invokedFilters --> true
> [9/27/21, 11:06:51:740 CDT] 0000003d id=00000000 com.ibm.wsspi.webcontainer.WebContainerRequestState          1 setInvokedFilters  invokedFilters --> false
> [9/27/21, 11:06:51:741 CDT] 0000003d id=767cdbcf .ibm.ws.webcontainer.security.WebAppSecurityCollaboratorImpl > isUserInRole Entry  
>                                                                                                                Echoer
>                                                                                                                com.ibm.ws.webcontainer40.srt.SRTServletRequest40@3ad75eca
> [9/27/21, 11:06:51:741 CDT] 0000003d id=00000000 .ibm.ws.webcontainer.security.WebAppSecurityCollaboratorImpl 3 isUserInRole role = Echoer
> 
>

### PR DESCRIPTION
**Pull request by andymc12**
Fixes #18794 by adding a new filter (enabled by auto feature when the `restfulWS-3.0` and `appSecurity-4.0` features are enabled) that will check JAX-RS resource classes and methods for `@RolesAllowed`, `@PermitAll`, `@DenyAll` annotations and react accordingly.

### CODE REVIEW

**Comment by andymc12** [comment]
#build

**Review by WhiteCat22 — APPROVED** [review]

**Comment by andymc12** [comment]
Minor tweak - new #build

**Comment by andymc12** [comment]
only jax-rs failure is unrelated - and is from an intermittent defect that @WhiteCat22 is resolving in a separate PR.

**Comment by andymc12** [comment]
#libby

**Pull request merged**
