### PR TITLE
Move the faces-3.0 feature to beta

### LINKED ISSUE #12261: Move the jsf-3.0 feature to beta when ready

### PR DESCRIPTION
**Pull request by pnicolucci**
fixes #12261

### CODE REVIEW

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Review by volosied — APPROVED** [review]
Changes look good. Thanks!

**Review by tevans78 — APPROVED** [review]

**Comment by pnicolucci** [comment]
#run-libby-bot

**Comment by pnicolucci** [comment]
I've run multiple builds the latest two have no consistent failures and the JSF tests are passing that are enabled. I'm going to merge this.

**Pull request merged**
