### PR TITLE
Remove module-info class files from bundles

### PR DESCRIPTION
**Pull request by jhanders34**

### CODE REVIEW

**Comment by jhanders34** [comment]
#build

**Comment by jhanders34** [comment]
#libby

**Review by neuwerk — APPROVED** [review]
JAX-WS and JAXB changes look good! Thanks Jared.

**Review by jjiwooLim — APPROVED** [review]
Install change looks good to me!

**Review by ayoho — APPROVED** [review]
Seems fine to me. What's the benefit of doing this, or what is being fixed?

**Comment by jhanders34** [comment]
> Seems fine to me. What's the benefit of doing this, or what is being fixed?

Liberty does not support module-info.class since we do not have jars as JPMS modules -- they are OSGi bundles.  We have done the work to remove module-info.class files in all other bundles and recently these were added back in so I took the task to clean them up again.

**Pull request merged**
