### PR TITLE
Added new features and their dependencies

### PR DESCRIPTION
**Pull request by chitwansharmaa**
Intermittent connection failure to maven central to install features. Added dependency files so that Instead of installing from maven central, features will be installed from the local repository present in the publish folder of FAT.

### CODE REVIEW

**Comment by chitwansharmaa** [comment]
#build

**Comment by chitwansharmaa** [comment]
#build

**Comment by chitwansharmaa** [comment]
#build

**Comment by chitwansharmaa** [comment]
#build

**Review by bensonlatibm — APPROVED** [review]
looks good!

**Comment by chitwansharmaa** [comment]
#run-libby-bot

**Pull request merged**
