### PR TITLE
Fat bucket is split

### LINKED ISSUE #17637: Split jaxws.2.2.webcontainer_fat bucket to 2 bundles
Running this test bucket consumes heavy resources as it is by server.

### PR DESCRIPTION
**Pull request by BerksanAtes**
Fixes #17637
High resource consumption of fat bucket was causing intermittent issues on servers.

### CODE REVIEW

**Comment by BerksanAtes** [comment]
#build

**Comment by BerksanAtes** [comment]
#build

**Comment by BerksanAtes** [comment]
#build

**Comment by BerksanAtes** [comment]
#libbybot

**Review by WhiteCat22 — APPROVED** [review]

**Pull request merged**
