### PR TITLE
Split up the JPA EclipseLink FAT

### PR DESCRIPTION
**Pull request by dazey3**
With the new JPA 3.1 FAT repeat action, the `com.ibm.ws.jpa.tests.eclipselink_fat` is now going over the 3 hour timeout limit for FULL FAT testing. This change will break up the FAT into 4 new buckets:
```
com.ibm.ws.jpa.tests.eclipselink_jpa_2.1_fat
com.ibm.ws.jpa.tests.eclipselink_jpa_2.2_fat
com.ibm.ws.jpa.tests.eclipselink_jpa_3.0_fat
com.ibm.ws.jpa.tests.eclipselink_jpa_3.1_fat
```

### CODE REVIEW

**Comment by dazey3** [comment]
#build

**Comment by dazey3** [comment]
#build

**Comment by dazey3** [comment]
#run-libby-bot

**Review by jgrassel — APPROVED** [review]
lgtm

**Pull request merged**
