### PR TITLE
token validation update

### LINKED ISSUE #24310: aud missing in the response from the token endpoint should result in 401
If the token endpoint returns tokens without the "aud" claim, we should get a 401.  We're not, we're getting access to the protected app.

Test is TokenValidationTests_audMissing_jwt
[audMissing.zip](https://github.com/OpenLiberty/open-liberty/files/10744397/audMissing.zip)

### PR DESCRIPTION
**Pull request by arunavemulapalli**
handle the case of missing "aud" claim

Resolves #24310

### CODE REVIEW

**Comment by arunavemulapalli** [comment]
fixes #24310

**Review by teddyjtorres — DISMISSED** [review]

**Comment by arunavemulapalli** [comment]
#build

**Comment by arunavemulapalli** [comment]
#build

**Comment by arunavemulapalli** [comment]
#libby

**Review by teddyjtorres — APPROVED** [review]

**Pull request merged**
