### PR TITLE
Enable JSF22ComponentRendererTests for Faces 4.0

### PR DESCRIPTION
**Pull request by pnicolucci**
for #22369

### CODE REVIEW

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
Java 17 build: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_feNiAFkhEe2P_cwgExA7aA

**Comment by pnicolucci** [comment]
Java 17 build was successful

**Review by volosied — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
