### PR TITLE
CDI: Update to Weld 6 CR1

### PR DESCRIPTION
**Pull request by Azquelt**
Also requires depending on Jboss logging 3.6.

- [x] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [x] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [x] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

### CODE REVIEW

**Comment by Azquelt** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.cdi.2.0_fat,com.ibm.ws.cdi.annotations_fat,com.ibm.ws.cdi.api_fat,com.ibm.ws.cdi.beansxml_fat,com.ibm.ws.cdi.beansxml.implicit_fat,com.ibm.ws.cdi.ejb_fat,com.ibm.ws.cdi.extension_fat,com.ibm.ws.cdi.jee_fat,com.ibm.ws.cdi.jndi_fat,com.ibm.ws.cdi.lifecycle_fat,com.ibm.ws.cdi.noncontextual_fat,com.ibm.ws.cdi.third.party_fat,com.ibm.ws.cdi.visibility_fat,com.ibm.ws.clientcontainer.cdi_fat,com.ibm.ws.ejbcontainer.cdi_fat,com.ibm.ws.jaxrs.2.0.cdi.1.2_fat,com.ibm.ws.jaxrs.2.1.cdi.2.0_fat,com.ibm.ws.jaxws.cdi_fat,com.ibm.ws.jbatch.cdi_fat,com.ibm.ws.jpa.tests.spec21.cdi_fat,com.ibm.ws.microprofile.faulttolerance.cdi_fat,com.ibm.ws.microprofile.faulttolerance.cdi_fat_metrics,io.openliberty.cdi.3.0.internal_fat,io.openliberty.cdi.4.0.internal_fat,io.openliberty.cdi.4.1.internal_fat,io.openliberty.cdi.core_fat,io.openliberty.restfulWS.3.0.cdi.3.0_fat

**Comment by Azquelt** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.cdi.2.0_fat,com.ibm.ws.cdi.annotations_fat,com.ibm.ws.cdi.api_fat,com.ibm.ws.cdi.beansxml_fat,com.ibm.ws.cdi.beansxml.implicit_fat,com.ibm.ws.cdi.ejb_fat,com.ibm.ws.cdi.extension_fat,com.ibm.ws.cdi.jee_fat,com.ibm.ws.cdi.jndi_fat,com.ibm.ws.cdi.lifecycle_fat,com.ibm.ws.cdi.noncontextual_fat,com.ibm.ws.cdi.third.party_fat,com.ibm.ws.cdi.visibility_fat,com.ibm.ws.clientcontainer.cdi_fat,com.ibm.ws.ejbcontainer.cdi_fat,com.ibm.ws.jaxrs.2.0.cdi.1.2_fat,com.ibm.ws.jaxrs.2.1.cdi.2.0_fat,com.ibm.ws.jaxws.cdi_fat,com.ibm.ws.jbatch.cdi_fat,com.ibm.ws.jpa.tests.spec21.cdi_fat,com.ibm.ws.microprofile.faulttolerance.cdi_fat,com.ibm.ws.microprofile.faulttolerance.cdi_fat_metrics,io.openliberty.cdi.3.0.internal_fat,io.openliberty.cdi.4.0.internal_fat,io.openliberty.cdi.4.1.internal_fat,io.openliberty.cdi.core_fat,io.openliberty.restfulWS.3.0.cdi.3.0_fat

**Comment by contbld** [comment]
Your personal pipeline request is at https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=91003a7a-f182-4ff3-9e23-fab179b9856c

Target locations of links might be accessible only to IBM employees.

**Comment by contbld** [comment]
<h3>Code analysis and actions</h3>
DO NOT DELETE THIS COMMENT.

- 5 product code files were changed.

**Comment by Azquelt** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.cdi.2.0_fat,com.ibm.ws.cdi.annotations_fat,com.ibm.ws.cdi.api_fat,com.ibm.ws.cdi.beansxml_fat,com.ibm.ws.cdi.beansxml.implicit_fat,com.ibm.ws.cdi.ejb_fat,com.ibm.ws.cdi.extension_fat,com.ibm.ws.cdi.jee_fat,com.ibm.ws.cdi.jndi_fat,com.ibm.ws.cdi.lifecycle_fat,com.ibm.ws.cdi.noncontextual_fat,com.ibm.ws.cdi.third.party_fat,com.ibm.ws.cdi.visibility_fat,com.ibm.ws.clientcontainer.cdi_fat,com.ibm.ws.ejbcontainer.cdi_fat,com.ibm.ws.jaxrs.2.0.cdi.1.2_fat,com.ibm.ws.jaxrs.2.1.cdi.2.0_fat,com.ibm.ws.jaxws.cdi_fat,com.ibm.ws.jbatch.cdi_fat,com.ibm.ws.jpa.tests.spec21.cdi_fat,com.ibm.ws.microprofile.faulttolerance.cdi_fat,com.ibm.ws.microprofile.faulttolerance.cdi_fat_metrics,io.openliberty.cdi.3.0.internal_fat,io.openliberty.cdi.4.0.internal_fat,io.openliberty.cdi.4.1.internal_fat,io.openliberty.cdi.core_fat,io.openliberty.restfulWS.3.0.cdi.3.0_fat

**Comment by contbld** [comment]
Your personal pipeline request is at https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=fa02b15b-97bb-4e51-a9fd-298856e65d2c

Target locations of links might be accessible only to IBM employees.

**Comment by contbld** [comment]
<h3>Code analysis and actions</h3>
DO NOT DELETE THIS COMMENT.

- 5 product code files were changed.

**Comment by contbld** [comment]
https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=91003a7a-f182-4ff3-9e23-fab179b9856c has errors/failures.

**Comment by contbld** [comment]
https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=fa02b15b-97bb-4e51-a9fd-298856e65d2c has errors/failures.

**Comment by Azquelt** [comment]
Part of the packaging failed in the build, needs run again.

#build
#spawn.fullfat.buckets=com.ibm.ws.cdi.2.0_fat,com.ibm.ws.cdi.annotations_fat,com.ibm.ws.cdi.api_fat,com.ibm.ws.cdi.beansxml_fat,com.ibm.ws.cdi.beansxml.implicit_fat,com.ibm.ws.cdi.ejb_fat,com.ibm.ws.cdi.extension_fat,com.ibm.ws.cdi.jee_fat,com.ibm.ws.cdi.jndi_fat,com.ibm.ws.cdi.lifecycle_fat,com.ibm.ws.cdi.noncontextual_fat,com.ibm.ws.cdi.third.party_fat,com.ibm.ws.cdi.visibility_fat,com.ibm.ws.clientcontainer.cdi_fat,com.ibm.ws.ejbcontainer.cdi_fat,com.ibm.ws.jaxrs.2.0.cdi.1.2_fat,com.ibm.ws.jaxrs.2.1.cdi.2.0_fat,com.ibm.ws.jaxws.cdi_fat,com.ibm.ws.jbatch.cdi_fat,com.ibm.ws.jpa.tests.spec21.cdi_fat,com.ibm.ws.microprofile.faulttolerance.cdi_fat,com.ibm.ws.microprofile.faulttolerance.cdi_fat_metrics,io.openliberty.cdi.3.0.internal_fat,io.openliberty.cdi.4.0.internal_fat,io.openliberty.cdi.4.1.internal_fat,io.openliberty.cdi.core_fat,io.openliberty.restfulWS.3.0.cdi.3.0_fat

**Comment by contbld** [comment]
Your personal pipeline request is at https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=256f5254-d7e9-49e3-bda1-af0d779e7478

Target locations of links might be accessible only to IBM employees.

**Comment by contbld** [comment]
<h3>Code analysis and actions</h3>
DO NOT DELETE THIS COMMENT.

- 5 product code files were changed.

**Comment by contbld** [comment]
https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=256f5254-d7e9-49e3-bda1-af0d779e7478 has errors/failures.

**Review by Yas-Franco — APPROVED** [review]
Looks good

**Pull request merged**
