### PR TITLE
Updating OpenAPI UI libraries

### PR DESCRIPTION
**Pull request by JusteenR**

### CODE REVIEW

**Comment by JusteenR** [comment]
#build

**Comment by JusteenR** [comment]
#build

**Comment by navidsh** [comment]
#run-libby-bot

**Comment by JusteenR** [comment]
#build

**Comment by arturdzm** [comment]
#build

**Comment by arturdzm** [comment]
#build

**Comment by arturdzm** [comment]
#run-libby-bot

**Pull request merged**
