### PR TITLE
Custom property for cache name

### PR DESCRIPTION
**Pull request by zhang-ca**
Session custom property CacheSeparator to customize the cache naming

### CODE REVIEW

**Comment by zhang-ca** [comment]
#build

**Comment by zhang-ca** [comment]
fixes #20908

**Comment by zhang-ca** [comment]
for #20908

**Comment by zhang-ca** [comment]
#build

**Comment by zhang-ca** [comment]
#run-libby-bot

**Comment by zhang-ca** [comment]
Changes has been tested and verified by the customers (TS009044088).

**Comment by zhang-ca** [comment]
> The build zhang-ca-20921-20220426-0905 https://wasrtc.hursley.ibm.com:9443/jazz/resource/itemOid/com.ibm.team.build.BuildResult/_Qqb2EMVwEeyhmZ5zGPuLaA completed and has errors or failures.
> 
> For help analyzing your personal build, go to https://cognitive.hursley.ibm.com/buildAnalysis.html?uuid=_Qqb2EMVwEeyhmZ5zGPuLaA

Build pass, error came from unrelated UI tests

**Comment by zhang-ca** [comment]
#build

**Review by bensonlatibm — APPROVED** [review]
lgtm!

**Pull request merged**
