### PR TITLE
Telemetry: Use correct @WithSpan binding

### LINKED ISSUE #25467: A better error for the NullPointer we get if WithSpan is on the class level
In order to make the WithSpanInterceptor we had to allow the WithSpan annotation to be put onto a Type.

However in a fat test if you put WithSpan onto an application class you get an NPE from WithSpanInterceptor.MethodRequestSpanNameExtractor.extract - we should either remove Type as a target for WithSpan or put a better error method in.

### PR DESCRIPTION
**Pull request by Azquelt**
Use CDI to look up the actual binding used to bind the interceptor

Fixes #25467

### CODE REVIEW

**Comment by Azquelt** [comment]
I want to check the performance impact of doing the service lookup this way before merging this.

**Comment by Azquelt** [comment]
#build
#spawn.fullfat.buckets=io.openliberty.microprofile.telemetry.1.0.internal_fat,io.openliberty.microprofile.telemetry.1.0.internal.jaeger_fat,io.openliberty.microprofile.telemetry.1.0.internal_fat_tck,io.openliberty.microprofile.telemetry.1.1.internal_fat_tck

**Comment by Azquelt** [comment]
Currently the service lookup takes 64% of the method call time with J2S disabled, or 90% with J2S enabled - which seems a little much.

Using the streams API to find the WithSpan annotation from the list returned also takes longer than I'd expect, given that in most circumstances there will only be one, so a `for` loop there might be worthwhile.

**Comment by Azquelt** [comment]
#libby
#build
#spawn.fullfat.buckets=io.openliberty.microprofile.telemetry.1.0.internal_fat,io.openliberty.microprofile.telemetry.1.0.internal.jaeger_fat,io.openliberty.microprofile.telemetry.1.0.internal_fat_tck,io.openliberty.microprofile.telemetry.1.1.internal_fat_tck

**Review by Yas-Franco — APPROVED** [review]
Looks good

**Comment by Azquelt** [comment]
Failures in the CI Orchestrator Pipeline build do not appear to be related to this change.

**Pull request merged**
