### PR TITLE
Synchronized code in WsLogger cause deadlock with session thread

### PR DESCRIPTION
**Pull request by zhang-ca**
****************************************************************
    * PROBLEM DESCRIPTION: Enable logging for session may cause deadlock with session manager           
    ****************************************************************
    Synchronized code in WsLogger can caused deadlock in concurrent session method calls

### CODE REVIEW

**Comment by zhang-ca** [comment]
fixes #20730

**Comment by zhang-ca** [comment]
for #20730

**Comment by zhang-ca** [comment]
#build

**Review by prova-anika-216474306 — APPROVED** [review]
LGTM!

**Pull request merged**
