### PR TITLE
add validate json to user input data for PUT

### PR DESCRIPTION
**Pull request by aknguyen7**

### CODE REVIEW

**Comment by aknguyen7** [comment]
#build

**Review by k8vance88 — APPROVED** [review]

**Comment by aknguyen7** [comment]
#link 292359

**Comment by aknguyen7** [comment]
#build

**Comment by aknguyen7** [comment]
UI passed with 1 failures for a known defect 288136 org.openqa.selenium.WebDriverException: Expected to read a START_MAP but instead have: END. Last 0 characters read:

image
image
image

**Pull request merged**
