### PR TITLE
Update gRPC package, bundle, and feature names to match new guidelines 

### PR DESCRIPTION
**Pull request by wtlucy**
For #12389

### CODE REVIEW

**Comment by andrea-pichler** [comment]
No message review requested from L2

**Comment by wtlucy** [comment]
#build

**Comment by wtlucy** [comment]
OK, I've needed to make some changes in the closed repo as well to get past some message verification and schema validator errors.  Combined repo build: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_ecgLoKWtEeqCjdhsjSafyw

**Comment by wtlucy** [comment]
#build

**Comment by wtlucy** [comment]
#run-libby-bot

**Pull request merged**
