### PR TITLE
Springboot websocket fat test

### LINKED ISSUE #25765: SpringBoot 3.0: Enable WebSocket FAT
The Spring3 WebSocket FAT class WebSocketTests30 is disabled due to application errors.

### PR DESCRIPTION
**Pull request by rsherget**
Fixes the websocket SpringBoot FAT test

### CODE REVIEW

**Comment by rsherget** [comment]
#build

This fixes the websocket and security FAT tests. Had to create a whole new springboot app as to not break other tests.

**Comment by rsherget** [comment]
#build

**Review by hlhoots — APPROVED** [review]
LGTM

**Review by jimblye — APPROVED** [review]

**Comment by wraschke** [comment]
#libby

**Comment by wraschke** [comment]
I merged this at Harry's request. The PB has run all FATs (except for z/OS FATs) and it looks good.

**Comment by hlhoots** [comment]
Thanks @wraschke !

**Pull request merged**
