### PR TITLE
Remove unused fields in com.ibm.ws.ras.instrument

### PR DESCRIPTION
**Pull request by chackoj**
There were a couple of fields that Eclipse identified as never being read.
I have removed these in such a way that the behaviour stays the same.

#build

### CODE REVIEW

**Comment by chackoj** [comment]
#build attempt 2

**Review by cbridgha — APPROVED** [review]
LGTM

**Comment by chackoj** [comment]
Requested a rebuild with ALL the tests, as recommended by @cbridgha

**Comment by chackoj** [comment]
#run-libby-bot

**Pull request merged**
