### PR TITLE
[19529] - move mpGraphQL-2.0 from noship to beta

### PR DESCRIPTION
**Pull request by WhiteCat22**
We have all approvals needed to beta `mpGraphQL-2.0`
#19529

### CODE REVIEW

**Review by andymc12 — APPROVED** [review]
LGTM - thanks @WhiteCat22!

**Comment by WhiteCat22** [comment]
#build #run-libby-bot

**Comment by tevans78** [comment]
@WhiteCat22 you're missing `io.openliberty.org.eclipse.microprofile.graphql-2.0`

**Comment by WhiteCat22** [comment]
added `io.openliberty.org.eclipse.microprofile.graphql-2.0` #build #run-libby-bot

**Pull request merged**
