### PR TITLE
[TS010666588] skip illegal characters in jvm.options.

### PR DESCRIPTION
**Pull request by cbridgha**
Branch for running PB for #22605

### CODE REVIEW

**Comment by cbridgha** [comment]
#build

**Comment by bmarwell** [comment]
Hi @cbridgha!

Test cases: matrix of:

**Test file jvm.options**

* charset UTF-8 with invalid chars
* charset ASCII with invalid chars
* charset ASCII with all correct chars

**LANG settings**

* LANG=C
* LANG=en_US
* LANG=en_US. ISO8859-1
* LANG=en_US.UTF8
* LANG=en_US.utf8
* LANG=en_US.UTF-8
* LANG=EN_US
* LANG=EN_US.utf8
* LANG=EN_US.UTF8
* LANG=EN_US.UTF-8

**OSes**

* AIX 7.2
* Linux

**Comment by cbridgha** [comment]
#build

**Comment by cbridgha** [comment]
#build

**Review by hlhoots — APPROVED** [review]
LGTM pending a good build.

**Comment by cbridgha** [comment]
#build

**Comment by cbridgha** [comment]
#libby

**Pull request merged**
