### PR TITLE
Rewrite Zip Cache Introspector FAT tests.

### PR DESCRIPTION
**Pull request by tbitonti**
Improved resource management;
removed unnecessary delays;
revised test servlet hold/release strategy
recategorized slow tests as FULL mode tests.

### CODE REVIEW

**Comment by tbitonti** [comment]
#build

**Comment by tbitonti** [comment]
Re-vision of prior PRs 
(initial) https://github.com/OpenLiberty/open-liberty/pull/25929
(reversion) https://github.com/OpenLiberty/open-liberty/pull/25939
(prior PR) https://github.com/OpenLiberty/open-liberty/pull/25319

**Comment by tbitonti** [comment]
#build

**Review by jimblye — APPROVED** [review]

**Comment by tbitonti** [comment]
#libby

**Comment by tbitonti** [comment]
FAT only update.  Tested by rerunning the FATS which were modified.

**Pull request merged**
