### PR TITLE
Add support for OIDC in JCache auth cache.

### LINKED ISSUE #21024: Investigate serialization for OIDC in regards to distributed authentication cache.
Liberty provides two ways to configure a client for OIDC:

1. `openIdConnectClient` via the `openIdConnectClient-1.0` feature
2. `oidcLogin` via the `socialLogin-1.0` feature

When using JCache to store the subject in the (distributed) authentication cache, the Subject needs to be serialized before being stored. This includes any principals and any public or private credentials stored in the Subject.

1. When using `openIdConnectClient`, `com.ibm.ws.security.openidconnect.client.jose4j.OidcTokenImpl` is stored in the Subject as a private credential. This class, along with its parent class `OidcTokenImplBase` are both not serializable. The `OidcTokenImplBase` also contains a class from Jose4J (`org.jose4j.jwt.JwtClaims`) that is not serializable. We need to either make that class serializable or be able to serialize the JSON the JwtClaims object comes from so we can reconstruct it on deserialization.

2. When using `oidcLogin`, `com.ibm.ws.security.jwt.internal.JwtTokenConsumerImpl` is stored in the Subject as a private credential. This class contains another Jose4J class that is not serializable - `org.jose4j.jwx.Headers`. Again, either this class needs to be made serializable, or we need to serialize the JSON string so it can be deserialized and used to construct the `org.jose4j.jwx.Headers`.

If we decide not to make the classes serializable, we will first need to verify that we don't create a large performance impact as the SSO and performance teams have been reducing the amount of marshalling and unmarshalling of JSON in this area to improve performance.

 - Note: I have tested a fix for `oidcLogin` that works that relies on marshalling the JSON into an object at some point to get to the headers, which may have a performance hit.

 - Note: I have NOT tested with anything beyond `oidcLogin` or `oauthLogin` in `socialLogin-1.0`.

 - Note: Ensure that we add version-to-version serialization tests for any OL classes we make Serializable that will fail if someone breaks serialization across versions.

### PR DESCRIPTION
**Pull request by jvanhill**
fixes #21024

### CODE REVIEW

**Comment by jvanhill** [comment]
#build

**Comment by jvanhill** [comment]
Build was still pending when I did my push, no need to restart build.

**Comment by jvanhill** [comment]
#libby

**Review by ryanesch — APPROVED** [review]

**Review by kristip17 — APPROVED** [review]

**Review by teddyjtorres — APPROVED** [review]

**Comment by jvanhill** [comment]
Pushed changes to some comments, nothing that should effect the build, so not respinning.

**Comment by jvanhill** [comment]
#libby

**Comment by jvanhill** [comment]
The failed tests from the latest build were pre-existing issues.

**Pull request merged**
