### PR TITLE
Use http header for authentications

### LINKED ISSUE #27077: FeatureUtility returns 403 if repo pwd is encoded
**Describe the bug**  
When custom repo with basic auth is set with encoded pwd, featureUtility returns 403 when downloading the esa file.
However, it doesn't return 403 when downloading the json file.

**Expected behavior**  
Should download and install esa from custom repository

**Diagnostic information:**  
 - OpenLiberty Version: 23.0.0.9

### PR DESCRIPTION
**Pull request by jjiwooLim**
Instead of using Java authenticator which only accepts one global authenticator (for Java 8) use the header inside the http request.
Fixes #27077

### CODE REVIEW

**Comment by jjiwooLim** [comment]
#build

**Review by jacobwdv — DISMISSED** [review]
LGTM

**Comment by jjiwooLim** [comment]
#libby-bot

**Comment by jjiwooLim** [comment]
#build

**Comment by jjiwooLim** [comment]
#build

**Comment by jjiwooLim** [comment]
#build

**Comment by jjiwooLim** [comment]
Test failure due to Nexus test container start up failed within 5 min duration

**Comment by jjiwooLim** [comment]
#build

**Comment by jjiwooLim** [comment]
#build

**Comment by jjiwooLim** [comment]
#build

**Comment by jjiwooLim** [comment]
`com.ibm.ws.transaction.hadb_fat.derby.1 FAT tests` failure not realted to my changes

**Comment by jjiwooLim** [comment]
#libbybot

**Review by jacobwdv — APPROVED** [review]
I've already reviewed this code up until we disabled the nexus container startup timeout issue. I approve removing the container from the test as it cannot be fixed.

**Pull request merged**
