### PR TITLE
Updates for feature file header WLP-DisableAllFeatures-OnConflict

### PR DESCRIPTION
**Pull request by sebratton**

### CODE REVIEW

**Comment by sebratton** [comment]
#build

**Comment by sebratton** [comment]
#build

**Comment by tjwatson** [comment]
This pull request and #14263 need to be coordinated.  Once all the new features have `WLP-DisableAllFeatures-OnConflict` set to `true` it will likely cause several tests to start failing.

**Comment by sebratton** [comment]
fixes issue #14234

**Comment by sebratton** [comment]
#libbybot

**Comment by sebratton** [comment]
#build

**Review by tjwatson — APPROVED** [review]

**Comment by tjwatson** [comment]
#run-libby-bot

**Pull request merged**
