### PR TITLE
add featureUtility isf tolerate unit test

### PR DESCRIPTION
**Pull request by jjiwooLim**
Adding unit test for #19991

Currently downloading features from Maven Central. Should use artifactory in the future

### CODE REVIEW

**Comment by jjiwooLim** [comment]
#build

**Comment by jjiwooLim** [comment]
#build

**Comment by jjiwooLim** [comment]
#build

**Comment by jjiwooLim** [comment]
#build

**Comment by jjiwooLim** [comment]
#libby-bot

**Review by bensonlatibm — APPROVED** [review]
lgtm!

**Pull request merged**
