### PR TITLE
Update server config before start of each test

### PR DESCRIPTION
**Pull request by lamkavan**
This is in relation to https://github.com/OpenLiberty/open-liberty/issues/10018
This PR fixes the issue.

### CODE REVIEW

**Comment by lamkavan** [comment]
#build

**Comment by lamkavan** [comment]
#build

**Comment by lamkavan** [comment]
#run-libby-bot

**Comment by pgunapal** [comment]
LGTM, the latest personal build is green and passed all the affected FAT tests (com.ibm.ws.request.timing_fat).

**Pull request merged**
