### PR TITLE
jaxws-2.2: Update CXF to account for changes in XLXP and clean up projects

### PR DESCRIPTION
**Pull request by neuwerk**
This pull request does 4 things

1. Addresses change in XLXP that makes CXF 3.x look for old JDK JAX-B RI property: `com/sun/xml/internal/bind/marshaller/namespacePrefixMapper`. CXF will now check if XLXP's namespacePrefixMapper is availible, and fall back to the new RI's prefix if not. 
2. Removes no longer needed `com.ibm.ws.cxf.client` project
3. Adds `com.ibm.ws.org.apache.cxf.rt.security.3.4.1` bnds for Jakarta transforer
4. Removes expected exceptions in WS-AT tests when new version of CXF is used with jaxws-2.2.

### CODE REVIEW

**Comment by neuwerk** [comment]
#build

**Comment by neuwerk** [comment]
#build

**Review by arunavemulapalli — APPROVED** [review]

**Comment by neuwerk** [comment]
#build

**Comment by neuwerk** [comment]
#run-libby-bot

**Pull request merged**
