### PR TITLE
Fix passivation of CDI beans with injected Event

### PR DESCRIPTION
**Pull request by benjamin-confino**
Add two packages to the list of packages to search when deserializing objects from a passivated bean.

`org.jboss.weld.event` contains the implementation for an injected `Event` and after some debugging we found that `org.jboss.weld.annotated.slim.unbacked` was needed in some cases as well, though this isn't shown by the test in this PR.

for #24631

### CODE REVIEW

**Comment by benjamin-confino** [comment]
#build

**Comment by benjamin-confino** [comment]
#build

**Comment by benjamin-confino** [comment]
Previous build didn't fail, but its still running and way overdue.

**Comment by benjamin-confino** [comment]
#libby

**Review by volosied — APPROVED** [review]
Changes are good for MyFaces! Thanks! Please merge when you can :)

**Pull request merged**
