### PR TITLE
close connections in testDurableSubscriberWithoutClientID

### PR DESCRIPTION
**Pull request by AndrewDJBanks**

### CODE REVIEW

**Comment by AndrewDJBanks** [comment]
#build

**Comment by AndrewDJBanks** [comment]
#build

**Comment by AndrewDJBanks** [comment]
#build

**Review by sakerl — APPROVED** [review]
Looks good.

**Comment by dazavala** [comment]
Hi, @AndrewDJBanks.  I received an email request to review these changes.  They look good (and improved).  Test classes in this suite required no changes to support EE9.  You results should indicate the suite executes over the original feature set and the EE9 feature set w/ no problem.  If you still need my formal approval, ping me.  -Regards.

**Comment by AndrewDJBanks** [comment]
#libbybot

**Pull request merged**
