### PR TITLE
Reintroduce jakarta overlay el

### LINKED ISSUE #12492: Re-introduce change reverted from 12288
Re-introduce change reverted from https://github.com/OpenLiberty/open-liberty/pull/12288

### PR DESCRIPTION
**Pull request by volosied**
fixes #12492

Due to https://bz.apache.org/bugzilla/show_bug.cgi?id=64498, the previous PR #12288 was bad.

It was reverted in #12491 

As of now, the the bugzilla issue 64498 has been resolved in tomcat 10.0.0-m7.  Therefore, I am reintroducing my changes. 

Additionally, an osgi contract is provided by the api: 
```
 Provide-Capability: \
   osgi.contract;\
       osgi.contract=JavaEL;\
       version:Version=4.0.0;\
       uses:="jakarta.el"
```

### CODE REVIEW

**Comment by volosied** [comment]
Currently, this PR is waiting for sources jars to be uploaded.

**Comment by volosied** [comment]
#build

**Comment by pnicolucci** [comment]
#run-libby-bot

**Comment by volosied** [comment]
#build

**Comment by volosied** [comment]
#build

**Comment by volosied** [comment]
#build

**Comment by volosied** [comment]
#build

**Comment by pnicolucci** [comment]
#run-libby-bot

**Comment by volosied** [comment]
oss_dependencies.maven is not alphabetical. 
It should be  
```
org.apache.tomcat.embed:tomcat-embed-websocket:8.5.23
org.apache.tomcat:tomcat-el-api:10.0.0-M7
org.apache.tomcat:tomcat-jasper-el:10.0.0-M7
```
Reverting.

**Pull request merged**
