### PR TITLE
Sse holdup server shutdown

### PR DESCRIPTION
**Pull request by andymc12**
Resolves Issue #623 

The SSE implementation was starting an AsyncContext but not completing it - this left the channel framework thinking there was active work still occurring long after the SSE sink had been closed.  This fix ensures that the AsyncContext is closed.

### CODE REVIEW

**Comment by andymc12** [comment]
#build

**Comment by aguibert** [comment]
hi @andymc12 , to confirm this issue is fixed can you also remove `CWWKE1102W` from the `LibertyServer.stopServer()` arguments in the sse_fat?  That will ensure the tests fail in the future if the server ever fails to quiesce normally.

**Comment by andymc12** [comment]
Updated tests - new #build

**Comment by andymc12** [comment]
Merging now since the modified tests have already passed, and the rest of the run has passed previously.

**Pull request merged**
