### PR TITLE
New methods to add hooks directly to the CheckpointPhase

### PR DESCRIPTION
**Pull request by tjwatson**
In order to make it easier for static code to participate in checkpoint new methods are added to CheckpointPhase to allow static hooks to be added instead of requiring hooks to be registered as OSGi services.

### CODE REVIEW

**Comment by tjwatson** [comment]
#build

**Comment by tjwatson** [comment]
@dettmoney please 3bccba34370838d1f151bf9d2992fb103f4b2d9d

**Review by dettmoney — APPROVED** [review]

**Comment by tjwatson** [comment]
#build

**Comment by tjwatson** [comment]
@cbridgha please review 34c28afda0804f2b269ff682670401e63329f9b6

**Review by cbridgha — APPROVED** [review]
I'm ok with this - but can you open an issue to preserve your comments regarding The ServerClasspathTest?

**Comment by tjwatson** [comment]
> I'm ok with this - but can you open an issue to preserve your comments regarding The ServerClasspathTest?

Done with #21353

**Review by sebratton — APPROVED** [review]

**Comment by tjwatson** [comment]
#libby

**Pull request merged**
