### PR TITLE
Issue #13596: URBridge needs to return the security name so that it a…

### LINKED ISSUE #13569: Federated basicRegistry returns inconsistent results for case insensitive direct user lookups in scim-1.0
SCIM returns inconsistent results when the `ignoreCaseForAuthentication` attribute for `basicRegistry` is set to `true`.

For reference, the following basic registry configuration:

```
<basicRegistry realm="BasicRealm" ignoreCaseForAuthentication="true">
  <user name="scimUser" password="password"/>
  <group name="scimGroup">
    <member name="scimUser"/>
  </group>
</basicRegistry>
```

Take two similar requests below, the first searching `scimUser` (matching the case in the configuration) and the second searching for `scimuser`. Both calls return results that match the case sent on the search (i.e. id, userName, displayName, location). Additionally, the second search does not return the groups.

```
bash$ curl -sk -u "scimuser:password" https://localhost:9443/ibm/api/scim/Users/scimUser?attributes=id,userName,displayName,emails,groups | json_reformat 
{
    "id": "scimUser",
    "schemas": [
        "urn:scim:schemas:core:1.0"
    ],
    "userName": "scimUser",
    "displayName": "scimUser",
    "externalId": null,
    "groups": [
        {
            "value": "scimGroup",
            "display": "scimGroup"
        }
    ],
    "meta": {
        "location": "https://localhost:9443/ibm/api/scim/Users/scimUser"
    }
}

bash$ curl -sk -u "scimuser:password" https://localhost:9443/ibm/api/scim/Users/scimuser?attributes=id,userName,displayName,emails,groups | json_reformat 
{
    "id": "scimuser",
    "schemas": [
        "urn:scim:schemas:core:1.0"
    ],
    "userName": "scimuser",
    "displayName": "scimuser",
    "externalId": null,
    "meta": {
        "location": "https://localhost:9443/ibm/api/scim/Users/scimuser"
    }
}
```

The error is due to URBridge logic in federated repositories. It searches for the user in the federated basic registry, and since ignore case is turned on for authentication, the user is found. However; federated repositories URBridge doesn't use the security name passed back by the registry and instead uses the security name passed in to populate the results. It also uses the security name passed in to search for groups, which is not effected by the `ignoreCaseForAuthentication` configuration attribute.

The URBridge logic was updated to populate the entity from the registry. It will also use the security name returned from the registry to perform the group search so that groups will be returned.

### LINKED ISSUE #13612: Re-introduce change reverted from 13570
Re-introduce change reverted from https://github.com/OpenLiberty/open-liberty/pull/13570

### PR DESCRIPTION
**Pull request by jvanhill**
…lways matches the user and group in the registry.

fixes #13569
fixes #13612

### CODE REVIEW

**Comment by jvanhill** [comment]
#build
#spawn.zos=true

**Comment by jvanhill** [comment]
The last build request didn't set the spawn.zos property to true, so I canceled that request, cloned it and set that property. The new build is here:

https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_-KrUEOYYEeql06cgdrhuYw

**Comment by jvanhill** [comment]
Respun the build by cloning the previous build (with spawn.zos) that had failed due to a compile failure.

https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_YJNWwObWEeql06cgdrhuYw

**Comment by jvanhill** [comment]
Another build error, another respin:

https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_s-Cn0OerEeql06cgdrhuYw

**Comment by jvanhill** [comment]
#build
#libby

**Comment by jvanhill** [comment]
The previous build did not run the failing zOS test, though all other FATs and zFATS passed. Running again and specifically running the `com.ibm.ws.zos.request.logging.saf_zfat` bucket.

https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_ktQhUO0lEeq6BMGcHg9CTA

**Review by kristip17 — APPROVED** [review]

**Pull request merged**
