### PR TITLE
Rename Faces 5.0 to 4.1 as Faces 4.1 will be for EE11

### LINKED ISSUE #27184: Jakarta EE11 will now include Faces 4.1 not Faces 5.0
Work to update our features / bundles / test projects to reflect the new Faces version.

### PR DESCRIPTION
**Pull request by pnicolucci**
fixes #27184

### CODE REVIEW

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Comment by posmith** [comment]
Support message review not required.

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#libby

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Review by volosied — APPROVED** [review]
Changes themselves look fine to me. However, I don't know if there are any other files needed to change? Perhaps Jared will let you know.

**Review by jhanders34 — APPROVED** [review]

**Comment by jhanders34** [comment]
#libby

**Pull request merged**
