### PR TITLE
Further testing for 23448

### PR DESCRIPTION
**Pull request by benjamin-confino**
Link to #23448

### CODE REVIEW

**Comment by benjamin-confino** [comment]
#build

**Comment by Azquelt** [comment]
I've rebased this on #23903 to avoid merge conflicts. Only the last four commits relate to this PR.

**Comment by benjamin-confino** [comment]
While I can't review my own PR, what Andrew did looks good to me

**Review by Azquelt — DISMISSED** [review]

**Comment by Azquelt** [comment]
#build
#libby

**Comment by Azquelt** [comment]
Rebased on #23903 again.

**Review by Azquelt — DISMISSED** [review]

**Comment by Azquelt** [comment]
#libby
#build

**Comment by Azquelt** [comment]
Rebased on #23903 again

**Review by Azquelt — DISMISSED** [review]

**Comment by Azquelt** [comment]
Last build request hasn't started yet so we don't need to request a new one.

#libby

**Review by Azquelt — APPROVED** [review]

**Pull request merged**
