### PR TITLE
DataStoreHelperMetaData methods for networktimeout readonly schema typemap

### PR DESCRIPTION
**Pull request by njr-11**
Add methods for indicating support of java.sql.Connection getters for network timeout, read-only, schema, and type map.

### CODE REVIEW

**Comment by njr-11** [comment]
#build

**Comment by njr-11** [comment]
#build

**Review by jmstephensgit — APPROVED** [review]

**Comment by njr-11** [comment]
#build

**Comment by njr-11** [comment]
#run-libby-bot

**Pull request merged**
