### PR TITLE
Use httpMessageContext.redirect() instead of response.sendRedirect for LoginToContinue intercepter

### PR DESCRIPTION
**Pull request by Zech-Hein**
For https://github.com/OpenLiberty/open-liberty/issues/23310

### CODE REVIEW

**Comment by Zech-Hein** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.security.javaeesec_fat,com.ibm.ws.security.javaeesec_fat.2,com.ibm.ws.security.javaeesec_fat.3,com.ibm.ws.security.javaeesec_fat.4,com.ibm.ws.security.jaspic_fat,com.ibm.ws.security.jaspic.jakarta10_fat,io.openliberty.security.jakartasec.3.0.internal_fat, io.openliberty.security.jakartasec.3.0.internal_fat.config

**Comment by Zech-Hein** [comment]
#libby

**Review by utle — APPROVED** [review]

**Comment by Zech-Hein** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.security.javaeesec_fat,com.ibm.ws.security.javaeesec_fat.2,com.ibm.ws.security.javaeesec_fat.3,com.ibm.ws.security.javaeesec_fat.4,com.ibm.ws.security.jaspic_fat,com.ibm.ws.security.jaspic.jakarta10_fat,io.openliberty.security.jakartasec.3.0.internal_fat, io.openliberty.security.jakartasec.3.0.internal_fat.config

**Comment by Zech-Hein** [comment]
FAT tests ran successfully, all passing on the last build.

But the build had a failure waiting for BVT tests. Running one more build to confirm nothing is broken.
#build

**Pull request merged**
