### PR TITLE
22897: Update wsoc test timeout

### PR DESCRIPTION
**Pull request by loriadi**

### CODE REVIEW

**Comment by loriadi** [comment]
#build

**Comment by loriadi** [comment]
#22212

**Comment by loriadi** [comment]
#libbybot

**Review by volosied — APPROVED** [review]

**Comment by loriadi** [comment]
fixes #22897

**Comment by loriadi** [comment]
In my personal build, I verified that the timeout setting is 180 seconds.  If this fails again during soe, I should be able to see the timeout.

**Pull request merged**
