### PR TITLE
catch NPE in isRequestPartOfTransaction

### PR DESCRIPTION
**Pull request by TiborBeres**
Catch NPE thrown in isRequestPartOfTransaction when getBranch returns null.

### CODE REVIEW

**Comment by TiborBeres** [comment]
pull request for issue #27547

**Comment by TiborBeres** [comment]
#build

**Comment by TiborBeres** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.sipcontainer_fat

**Comment by TiborBeres** [comment]
#build #fat.tests.to.run="com.ibm.ws.sipcontainer_fat,com.ibm.ws.sipcontainer_fat_1.com.ibm.ws.sipcontainer_fat_2,com.ibm.ws.sipcontainer_fat_3,com.ibm.ws.sipcontainer_fat_4,com.ibm.ws.sipcontainer_fat_5,com.ibm.ws.sipcontainer_fat_6,com.ibm.ws.sipcontainer_fat_7" #spawn.fullfat.buckets="com.ibm.ws.sipcontainer_fat,com.ibm.ws.sipcontainer_fat_1.com.ibm.ws.sipcontainer_fat_2,com.ibm.ws.sipcontainer_fat_3,com.ibm.ws.sipcontainer_fat_4,com.ibm.ws.sipcontainer_fat_5,com.ibm.ws.sipcontainer_fat_6,com.ibm.ws.sipcontainer_fat_7"

**Comment by TiborBeres** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.sipcontainer_fat,com.ibm.ws.sipcontainer_fat_1,com.ibm.ws.sipcontainer_fat_2,com.ibm.ws.sipcontainer_fat_3,com.ibm.ws.sipcontainer_fat_4,com.ibm.ws.sipcontainer_fat_5,com.ibm.ws.sipcontainer_fat_6,com.ibm.ws.sipcontainer_fat_7

**Comment by TiborBeres** [comment]
#build, #fat.buckets.to.run=com.ibm.ws.sipcontainer_fat,com.ibm.ws.sipcontainer_fat_1,com.ibm.ws.sipcontainer_fat_2,com.ibm.ws.sipcontainer_fat_3,com.ibm.ws.sipcontainer_fat_4,com.ibm.ws.sipcontainer_fat_5,com.ibm.ws.sipcontainer_fat_6,com.ibm.ws.sipcontainer_fat_7, #spawn.fullfat.buckets=com.ibm.ws.sipcontainer_fat,com.ibm.ws.sipcontainer_fat_1,com.ibm.ws.sipcontainer_fat_2,com.ibm.ws.sipcontainer_fat_3,com.ibm.ws.sipcontainer_fat_4,com.ibm.ws.sipcontainer_fat_5,com.ibm.ws.sipcontainer_fat_6,com.ibm.ws.sipcontainer_fat_7

**Comment by TiborBeres** [comment]
#build  #fat.buckets.to.run=com.ibm.ws.sipcontainer_fat,com.ibm.ws.sipcontainer_fat_1,com.ibm.ws.sipcontainer_fat_2,com.ibm.ws.sipcontainer_fat_3,com.ibm.ws.sipcontainer_fat_4,com.ibm.ws.sipcontainer_fat_5,com.ibm.ws.sipcontainer_fat_6,com.ibm.ws.sipcontainer_fat_7  #spawn.fullfat.buckets=com.ibm.ws.sipcontainer_fat,com.ibm.ws.sipcontainer_fat_1,com.ibm.ws.sipcontainer_fat_2,com.ibm.ws.sipcontainer_fat_3,com.ibm.ws.sipcontainer_fat_4,com.ibm.ws.sipcontainer_fat_5,com.ibm.ws.sipcontainer_fat_6,com.ibm.ws.sipcontainer_fat_7

**Comment by TiborBeres** [comment]
#build, #fat.buckets.to.run=com.ibm.ws.sipcontainer_fat,com.ibm.ws.sipcontainer_fat_1,com.ibm.ws.sipcontainer_fat_2,com.ibm.ws.sipcontainer_fat_3,com.ibm.ws.sipcontainer_fat_4,com.ibm.ws.sipcontainer_fat_5,com.ibm.ws.sipcontainer_fat_6,com.ibm.ws.sipcontainer_fat_7, #spawn.fullfat.buckets=com.ibm.ws.sipcontainer_fat,com.ibm.ws.sipcontainer_fat_1,com.ibm.ws.sipcontainer_fat_2,com.ibm.ws.sipcontainer_fat_3,com.ibm.ws.sipcontainer_fat_4,com.ibm.ws.sipcontainer_fat_5,com.ibm.ws.sipcontainer_fat_6,com.ibm.ws.sipcontainer_fat_7

**Comment by TiborBeres** [comment]
the failed tests in the personal build are known intermittent issues, not tied to the changes in this PR

**Review by epj — APPROVED** [review]
okay

**Pull request merged**
