### PR TITLE
Logging for constant pool recreate PR

### PR DESCRIPTION
**Pull request by benjamin-confino**
This will give us extra logging for https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.workitem.viewWorkItem&id=285987

And if we're lucky fix it (we haven't been able to reproduce the error with these changes)

### CODE REVIEW

**Comment by benjamin-confino** [comment]
#build

**Comment by benjamin-confino** [comment]
#build

**Comment by tbitonti** [comment]
* Changes which can be removed if the problem is fixed:

dev/com.ibm.ws.ejbcontainer.security.jacc_fat.2/publish/servers/com.ibm.ws.ejbcontainer.security.jacc_fat.ejbjar.inwar/bootstrap.properties
-- remove "LTI_TRACE_ENABLED=true"

dev/com.ibm.ws.ejbcontainer.security.jacc_fat.2/publish/servers/com.ibm.ws.ejbcontainer.security.jacc_fat.ejbjar.inwar/server.env
-- remove ",org/jboss/weld/resources/HotspotReflectionCache.internalGetAnnotations()"

dev/com.ibm.ws.ejbcontainer.security.jacc_fat/publish/servers/com.ibm.ws.ejbcontainer.security.jacc_fat.ejbjar.inwar/bootstrap.properties
-- remove "-Xtrace:iprint=mt,methods={com/ibm/ws/ras/instrument/internal/main/LibertyRuntimeTransformer.transform},trigger=method{com/ibm/ws/ras/instrument/internal/main/LibertyRuntimeTransformer.transform,jstacktrace}"
-- remove "LTI_TRACE_ENABLED=true"
-- remove "LTI_TRACE_PATTERN=i"

dev/com.ibm.ws.ejbcontainer.security.jacc_fat/publish/servers/com.ibm.ws.ejbcontainer.security.jacc_fat.ejbjar.inwar/server.xml
-- remove 
    <logging traceSpecification="*=info:com.ibm.ws.ras.instrument.internal.main*=all:JCDI=all:com.ibm.ws.webbeans*=all:org.apache.webbeans*=all:org.jboss.weld*=all:com.ibm.ws.cdi*=all" />

dev/com.ibm.ws.org.jboss.weld/bnd.overrides
-- remove "org/jboss/weld/resources=${bin}/org/jboss/weld/resources, \"

* Current changes
 
dev/com.ibm.ws.org.jboss.weld/src/org/jboss/weld/resources/FileLogger.java
-- change to be java system property enabled
dev/com.ibm.ws.org.jboss.weld/src/org/jboss/weld/resources/HotspotReflectionCache.java
-- change to be java system property enabled

dev/com.ibm.ws.ejbcontainer.security.jacc_fat/fat/src/com/ibm/ws/ejbcontainer/security/jacc_fat/FATSuite.java
-- revert; the change was to temporarily remove passing tests from the test bucket

dev/com.ibm.ws.ras.instrument/src/com/ibm/ws/ras/instrument/internal/introspect/TraceConfigClassVisitor.java
-- OK; make sure to use the current ASM version opcode

dev/com.ibm.ws.ras.instrument/src/com/ibm/ws/ras/instrument/internal/main/AbstractInstrumentation.java
-- OK

dev/com.ibm.ws.ras.instrument/src/com/ibm/ws/ras/instrument/internal/main/DynamicTraceInstrumentation.java
-- OK

dev/com.ibm.ws.ras.instrument/src/com/ibm/ws/ras/instrument/internal/main/FileLogger.java
-- OK

dev/com.ibm.ws.ras.instrument/src/com/ibm/ws/ras/instrument/internal/main/FileLoggerTest.java
-- OK; maybe, move to unit tests?

dev/com.ibm.ws.ras.instrument/src/com/ibm/ws/ras/instrument/internal/main/LibertyRuntimeTransformer.java
-- OK

dev/com.ibm.ws.ras.instrument/src/com/ibm/ws/ras/instrument/internal/main/LibertyTracePreprocessInstrumentation.java
-- OK; this change seems unnecessary and probably can be reverted

dev/com.ibm.ws.ras.instrument/src/com/ibm/ws/ras/instrument/internal/main/StaticTraceInstrumentation.java
-- OK;

dev/io.openliberty.org.jboss.weld4/bnd.overrides
-- OK

dev/io.openliberty.org.jboss.weld4/src/org/jboss/weld/resources/FileLogger.java
-- change to be java system property enabled

dev/io.openliberty.org.jboss.weld4/src/org/jboss/weld/resources/HotspotReflectionCache.java
-- change to be java system property enabled

**Comment by tbitonti** [comment]
Current changes:

(+) change made in the branch
(x) no change needed

dev/com.ibm.ws.org.jboss.weld/src/org/jboss/weld/resources/FileLogger.java
+- change to be java system property enabled
dev/com.ibm.ws.org.jboss.weld/src/org/jboss/weld/resources/HotspotReflectionCache.java
+- change to be java system property enabled

dev/com.ibm.ws.ejbcontainer.security.jacc_fat/fat/src/com/ibm/ws/ejbcontainer/security/jacc_fat/FATSuite.java
+-- revert; the change was to temporarily remove passing tests from the test bucket

dev/com.ibm.ws.ras.instrument/src/com/ibm/ws/ras/instrument/internal/introspect/TraceConfigClassVisitor.java
+- OK; make sure to use the current ASM version opcode

dev/com.ibm.ws.ras.instrument/src/com/ibm/ws/ras/instrument/internal/main/AbstractInstrumentation.java
x- OK

dev/com.ibm.ws.ras.instrument/src/com/ibm/ws/ras/instrument/internal/main/DynamicTraceInstrumentation.java
x- OK

dev/com.ibm.ws.ras.instrument/src/com/ibm/ws/ras/instrument/internal/main/FileLogger.java
x- OK

dev/com.ibm.ws.ras.instrument/src/com/ibm/ws/ras/instrument/internal/main/FileLoggerTest.java
x- OK; maybe, move to unit tests?

dev/com.ibm.ws.ras.instrument/src/com/ibm/ws/ras/instrument/internal/main/LibertyRuntimeTransformer.java
x- OK

dev/com.ibm.ws.ras.instrument/src/com/ibm/ws/ras/instrument/internal/main/LibertyTracePreprocessInstrumentation.java
+- OK; this change seems unnecessary and probably can be reverted

dev/com.ibm.ws.ras.instrument/src/com/ibm/ws/ras/instrument/internal/main/StaticTraceInstrumentation.java
x- OK;

dev/io.openliberty.org.jboss.weld4/bnd.overrides
x- OK

dev/io.openliberty.org.jboss.weld4/src/org/jboss/weld/resources/FileLogger.java
+- change to be java system property enabled

dev/io.openliberty.org.jboss.weld4/src/org/jboss/weld/resources/HotspotReflectionCache.java
+- change to be java system property enabled

**Comment by benjamin-confino** [comment]
#build

**Comment by benjamin-confino** [comment]
#build

**Pull request closed without merging**
