### PR TITLE
avoid claiming task when application is unavailable

### LINKED ISSUE #25169: 295651:Concurrent persistent failover timers - server not releasing claim on scheduled task when unable to run it
**Describe the bug**  
The FAT `com.ibm.ws.concurrent.persistent.fat.failovertimers` found a product bug.  In the test `testProgrammaticTimerWithTxSuspendedFailsOverWhenAppStops`, `Server B` kicks off a timed task, then immediately ends the app that handles it, which means `Server B` is unable to run any future tasks and should no longer claim it.  Next `Server A` starts up and it is expected `Server A` will start claiming the task once the last claim from `Server B` expires.  But for some reason, `Server B` continues to claim the task, even though it has no way to run it.

**Steps to Reproduce**  
Run the FAT `testProgrammaticTimerWithTxSuspendedFailsOverWhenAppStops` in `com.ibm.ws.concurrent.persistent.fat.failovertimers`.

**Expected behavior**  
`Server B` should not claim the task if it is unable to run it.

**Diagnostic information:**  
 - OpenLiberty Version: Unknown
 - Affected feature(s) concurrent persistent failover timers
 - Java Version: 1.8.0_331
 - server.xml configuration (WITHOUT sensitive information like passwords)
 - If it would be useful, upload the messages.log file found in `$WLP_OUTPUT_DIR/messages.log`

```
Server A features
  <featureManager>
    <feature>ejbPersistentTimer-3.2</feature>
    <feature>jdbc-4.2</feature>
    <feature>servlet-4.0</feature>
  </featureManager>
```

```
Server B
 <featureManager>
    <feature>enterpriseBeansPersistentTimer-4.0</feature>
    <feature>jdbc-4.2</feature>
    <feature>servlet-5.0</feature>
  </featureManager>
```

**Additional context**  
In the `trace.log` file for `Server B`, we see the `CLAIMTIL` value continually updating, even though the task cannot be run:
```
CLAIMTIL=2023/04/13-21:41:13.803-UTC[1681422073803]
NEXTEXEC=2023/04/13-21:41:10.803-UTC[1681422070803]
ORIGSBMT=2023/04/13-21:41:09.804-UTC[1681422069804]
```
```
CLAIMTIL=2023/04/13-21:41:16.958-UTC[1681422076958]
NEXTEXEC=2023/04/13-21:41:10.803-UTC[1681422070803]
ORIGSBMT=2023/04/13-21:41:09.804-UTC[1681422069804]
```
.
.
.
```
CLAIMTIL=2023/04/13-21:45:14.949-UTC[1681422314949]
NEXTEXEC=2023/04/13-21:41:10.803-UTC[1681422070803]
ORIGSBMT=2023/04/13-21:41:09.804-UTC[1681422069804]
```

### PR DESCRIPTION
**Pull request by njr-11**
fixes #25169

### CODE REVIEW

**Comment by njr-11** [comment]
#build

**Comment by njr-11** [comment]
#build

**Review by gjwatts — APPROVED** [review]

**Comment by njr-11** [comment]
#build

**Comment by njr-11** [comment]
The build has 1 test failure, which is a pre-existing issue in unrelated componentry.

**Pull request merged**
