### PR TITLE
more logging

### PR DESCRIPTION
**Pull request by benjamin-confino**

### CODE REVIEW

**Comment by benjamin-confino** [comment]
#build

**Comment by benjamin-confino** [comment]
#build

**Comment by benjamin-confino** [comment]
Example output (nulls seem to appear only for $X inner classes)
```
[31/10/2022, 10:20:37:480 GMT] 00000038 id=00000000 com.ibm.ws.cdi.impl.weld.BeanDeploymentArchiveImpl           3 scan [ BDA for beanManagerLookupApp#io.openliberty.transaction.internal.cdi20.jakarta_1.additionalClasses(RUNTIME_EXTENSION) ] AFTER SCAN. Bean classes: { com.ibm.tx.jta.cdi.AbstractTransactionContext - com.ibm.tx.jta.cdi.AbstractTransactionContext, com.ibm.tx.jta.cdi.AbstractTransactionContext$1 - null, com.ibm.tx.jta.cdi.AbstractTransactionContext$2 - null, com.ibm.tx.jta.cdi.AbstractTransactionContext$DestroyedQualifier - com.ibm.tx.jta.cdi.AbstractTransactionContext.DestroyedQualifier, com.ibm.tx.jta.cdi.AbstractTransactionContext$InitializedQualifier - com.ibm.tx.jta.cdi.AbstractTransactionContext.InitializedQualifier, com.ibm.tx.jta.cdi.AbstractTransactionContext$InstanceAndContext - com.ibm.tx.jta.cdi.AbstractTransactionContext.InstanceAndContext, com.ibm.tx.jta.cdi.interceptors.Mandatory - com.ibm.tx.jta.cdi.interceptors.Mandatory, com.ibm.tx.jta.cdi.interceptors.Never - com.ibm.tx.jta.cdi.interceptors.Never, com.ibm.tx.jta.cdi.interceptors.NotSupported - com.ibm.tx.jta.cdi.interceptors.NotSupported, com.ibm.tx.jta.cdi.interceptors.Required - com.ibm.tx.jta.cdi.interceptors.Required, com.ibm.tx.jta.cdi.interceptors.RequiresNew - com.ibm.tx.jta.cdi.interceptors.RequiresNew, com.ibm.tx.jta.cdi.interceptors.Supports - com.ibm.tx.jta.cdi.interceptors.Supports, com.ibm.tx.jta.cdi.interceptors.TransactionalInterceptor - com.ibm.tx.jta.cdi.interceptors.TransactionalInterceptor, com.ibm.tx.jta.cdi.interceptors.TransactionalInterceptor$1 - null, com.ibm.tx.jta.cdi.interceptors.TransactionalInterceptor$2 - null, com.ibm.tx.jta.cdi.interceptors.package-info - com.ibm.tx.jta.cdi.interceptors.package-info, com.ibm.tx.jta.cdi.package-info - com.ibm.tx.jta.cdi.package-info, io.openliberty.transaction.internal.cdi20.CDI20TransactionContext - io.openliberty.transaction.internal.cdi20.CDI20TransactionContext, io.openliberty.transaction.internal.cdi20.CDI20TransactionContextExtension - io.openliberty.transaction.internal.cdi20.CDI20TransactionContextExtension, jakarta.transaction.TransactionScoped - jakarta.transaction.TransactionScoped}


[31/10/2022, 10:20:38:083 GMT] 00000038 id=00000000 com.ibm.ws.cdi.impl.weld.BeanDeploymentArchiveImpl           > containsBeanClass. BDA for beanManagerLookupApp#beanManagerLookupApp.war(WEB_MODULE) contains com.ibm.ws.cdi.jndi.lookup.BeanManagerLookupServlet Entry 
[31/10/2022, 10:20:38:083 GMT] 00000038 id=00000000 com.ibm.ws.cdi.impl.weld.BeanDeploymentArchiveImpl           < containsBeanClass false Exit
```

**Review by tevans78 — DISMISSED** [review]

**Comment by benjamin-confino** [comment]
#build

**Comment by benjamin-confino** [comment]
#build

**Review by tevans78 — APPROVED** [review]

**Comment by benjamin-confino** [comment]
#libby

**Pull request merged**
