### PR TITLE
Create additional FAT for Back Channel Logout

### PR DESCRIPTION
**Pull request by c00crane**
Create additional tests for Back Channel Logout
Test with and oidc client, social client and with an OP that using SAML for authentication.
Include tests use multiple client, webClient and server instances

For https://github.com/OpenLiberty/open-liberty/issues/20049

### CODE REVIEW

**Comment by c00crane** [comment]
#libby
#build
#spawn.fullfat.buckets=com.ibm.ws.security.oidc.client_fat.backchannelLogout,com.ibm.ws.security.oidc.client_fat.backchannelLogout.saml,com.ibm.ws.security.oidc.server_fat.backchannelLogout,com.ibm.ws.security.social_fat.LibertyOP.backchannelLogout

**Review by jimmy1wu — DISMISSED** [review]

**Comment by c00crane** [comment]
#libby
#build
#spawn.fullfat.buckets=com.ibm.ws.security.oidc.client_fat.backchannelLogout,com.ibm.ws.security.oidc.client_fat.backchannelLogout.saml,com.ibm.ws.security.oidc.server_fat.backchannelLogout,com.ibm.ws.security.social_fat.LibertyOP.backchannelLogout

**Comment by c00crane** [comment]
#libby
#build
#spawn.fullfat.buckets=com.ibm.ws.security.oidc.client_fat.backchannelLogout,com.ibm.ws.security.oidc.client_fat.backchannelLogout.saml,com.ibm.ws.security.oidc.server_fat.backchannelLogout,com.ibm.ws.security.social_fat.LibertyOP.backchannelLogout

**Comment by c00crane** [comment]
#libby
#build
#spawn.fullfat.buckets=com.ibm.ws.security.oidc.client_fat.backchannelLogout,com.ibm.ws.security.oidc.client_fat.backchannelLogout.saml,com.ibm.ws.security.oidc.server_fat.backchannelLogout,com.ibm.ws.security.social_fat.LibertyOP.backchannelLogout

**Review by jimmy1wu — APPROVED** [review]

**Comment by ayoho** [comment]
Largely resolves https://github.com/OpenLiberty/open-liberty/issues/20651

**Comment by ayoho** [comment]
Also resolves https://github.com/OpenLiberty/open-liberty/issues/20848

**Pull request merged**
