### PR TITLE
Update bnd to overwrite snakeyaml class

### PR DESCRIPTION
**Pull request by Azquelt**
#24307 tried to replace one of the snakeyaml classes but the bnd.bnd was not updated to ensure that the replaced class was packaged correctly in the bundle.

### CODE REVIEW

**Comment by Azquelt** [comment]
#build
#libby

**Comment by Azquelt** [comment]
**Must check that the jar from the build result includes the replaced class before merging.**

I've tested this locally, but must check the build result as well. Make sure that the `io.openliberty.com.fasterxml.jackson` jar contains a version of `org.yaml.snakeyaml.Yaml` which uses `SafeConstructor` rather than `Constructor` (will need to inspect the bytecode to determine this).

**Comment by Azquelt** [comment]
The build looks good, reported failures correspond with existing defects in other components. The `Yaml.class` file from the build result does use `SafeConstructor`.

However, I forgot to request the correct set of full fat tests.

#build
#spawn.fullfat.buckets=com.ibm.ws.microprofile.openapi.1.1_fat_tck,com.ibm.ws.microprofile.openapi_fat,com.ibm.ws.microprofile.openapi_fat_tck,com.ibm.ws.openapi.3.1_fat,com.ibm.ws.openapi_fat,io.openliberty.microprofile.openapi.2.0.internal_fat,io.openliberty.microprofile.openapi.2.0.internal_fat_tck,io.openliberty.microprofile.openapi.3.0.internal_fat_tck,io.openliberty.microprofile.openapi.3.1.internal_fat_tck

**Review by jhanders34 — APPROVED** [review]

**Comment by Azquelt** [comment]
Checked the new build, the Yaml.class file from the build result does use SafeConstructor.

**Pull request merged**
