### PR TITLE
general review of DataProvider

### PR DESCRIPTION
**Pull request by njr-11**
This PR contains updates from a general review of DataProvider, which is the core OSGi service for our Jakarta Data provider.  This includes:
Switching all static dependencies to constructor injection, which is a newer, recommended approach that allows all of the fields to be final, which is safer.
No longer inheriting CDIExensionMetaDataInternal to make application beans visible, because we only did that for some experimental code that was later removed. I left a comment in about how to get the capability back if we ever decide to add the experimental feature to Jakarta Data.
Adding line breaks in a few places so that code can be viewed on a screen without needing to scroll off the page to the right.
Attempting to order the deactivate/applicationStopped tearing down of services according to dependencies.
Adding more comments/JavaDoc to explain things.

- [x] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [x] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [x] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

### CODE REVIEW

**Comment by njr-11** [comment]
#build

**Comment by contbld** [comment]
Your personal pipeline request is at https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=945eb17f-fbff-416e-9a05-fa5d0156fb98

Target locations of links might be accessible only to IBM employees.

**Comment by contbld** [comment]
<h3>Code analysis and actions</h3>
DO NOT DELETE THIS COMMENT.

- 1 product code files were changed.

**Comment by contbld** [comment]
https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=945eb17f-fbff-416e-9a05-fa5d0156fb98 has errors/failures.

**Review by mswatosh — APPROVED** [review]

**Comment by njr-11** [comment]
#build

**Comment by contbld** [comment]
Your personal pipeline request is at https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=bfb81198-0d9d-44a5-8c29-3c5fa2e54040

Target locations of links might be accessible only to IBM employees.

**Comment by contbld** [comment]
<h3>Code analysis and actions</h3>
DO NOT DELETE THIS COMMENT.

- 1 product code files were changed.

**Comment by contbld** [comment]
https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=bfb81198-0d9d-44a5-8c29-3c5fa2e54040 completed successfully!

**Pull request merged**
