### PR TITLE
Update EERepeatAction to behave like MicroProfileActions

### PR DESCRIPTION
**Pull request by jhanders34**
- When telling EERepeatActions to run EE10 in lite, update to switch to a non EE 10 repeat when running in Java 8 just like what is done with MicroProfileActions.

### CODE REVIEW

**Comment by jhanders34** [comment]
#build

**Review by Azquelt — DISMISSED** [review]
There are some references to "MP" in the comments which would ideally be changed to "EE", but otherwise I think this looks good.

Thank you.

**Comment by jhanders34** [comment]
> There are some references to "MP" in the comments which would ideally be changed to "EE", but otherwise I think this looks good.
> 
> Thank you.

Done

**Comment by jhanders34** [comment]
#libby

**Review by Azquelt — APPROVED** [review]

**Pull request merged**
