### PR TITLE
Removing traces for correct deploy

### PR DESCRIPTION
**Pull request by sercheo87**
Resolve [Issue 10267](https://github.com/OpenLiberty/open-liberty/issues/10267)

### CODE REVIEW

**Comment by sercheo87** [comment]
Check code run command `./gradlew build` and compile without errors.

**Comment by pnicolucci** [comment]
@sercheo87  I'm going to close this PR I have one here that was more what I had in mind for this change: https://github.com/OpenLiberty/open-liberty/pull/10292 This removes all of the detailed traces for the test bucket. Thanks for taking a look at this issue.

**Comment by sercheo87** [comment]
@pnicolucci help me, how contribute with Open Liberty project??? Issues is assigned to another persons.

**Comment by pnicolucci** [comment]
@sercheo87  you could look at: https://github.com/OpenLiberty/open-liberty/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22 also see the following on contributing: https://openliberty.io/contribute/

**Pull request closed without merging**
