### PR TITLE
Upgrade Arquillian version to 1.3.0.Final in MP TCKs

### PR DESCRIPTION
**Pull request by andymc12**
Upgrading Arquillian from `1.1.3.Final` to `1.3.0.Final` in MicroProfile TCKs.

### CODE REVIEW

**Comment by andymc12** [comment]
#build

**Comment by andymc12** [comment]
Errors in MP Rest Client and OpenApi buckets - it appears to be due to incompatible changes in `arquillian-testng-container`. Most MP TCK projects use version `1.1.14.Final` for this artifact, while the failing ones are using the same version as the rest of Arquillian (`1.3.0.Final`).  I've changed all MP TCK buckets to use `1.1.14.Final`.  New #build

**Comment by andymc12** [comment]
Tweak to fix openapi 2.0 failures.  #build

**Review by Azquelt — APPROVED** [review]

**Comment by andymc12** [comment]
#libby

**Pull request merged**
