### PR TITLE
Refactor method getSharedLibraryClassLoader()

### PR DESCRIPTION
**Pull request by dazavala**
The definitions for public methods `getSharedLibraryClassLoader()` and `getSharedLibrarySpiClassLoader()` are nearly identical. This PR eliminates the duplication by refactoring their behaviors into a private method, `getSharedLibraryClassLoader()`, that can create shared library class loaders with or without SPI visibility.

### CODE REVIEW

**Comment by dazavala** [comment]
#build

**Review by tjwatson — APPROVED** [review]
LGTM

**Comment by dazavala** [comment]
Taking another look before merge, I deleted some unintended whitespace and revised a redundant comment.

**Comment by dazavala** [comment]
#build

**Comment by dazavala** [comment]
FYI: The following FATs are sensitive to changes in library classloader SPI visibility: `com.ibm.ws.classloading.bells_fat`,  `io.openliberty.jcache.internal_fat.hazelcast`, and `io.openliberty.jcache.internal_fat.infinispan`.

**Comment by dazavala** [comment]
#build

**Comment by dazavala** [comment]
The latest PB shows three breaks in the `io.openliberty.jcache.internal_fat.infinispan_FAT` indicating a "AuthCache" was not found.  This is a known problem with the distributed auth cache FATs.  I see no evidence of failures caused by the library classloader.

**Comment by dazavala** [comment]
#libby

**Pull request merged**
