### PR TITLE
Tolerate a little slow server restart in http_fat: 288001

### PR DESCRIPTION
**Pull request by hutchig**
This patch will attempt to start a test server more than one time when faced with a slow start - for a small number of times.
Fixes #288001

### CODE REVIEW

**Comment by hutchig** [comment]
#build

**Comment by hutchig** [comment]
#build

**Review by wtlucy — APPROVED** [review]
this makes sense to me

**Comment by hutchig** [comment]
Where is my
#build
?

**Comment by hutchig** [comment]
#libbybot

**Comment by hutchig** [comment]
All fat builds seem to be unable to resolve 3rd party libraries at the moment (all three failed builds above). There are 'Hursley Cell B' Fyre outages at the moment. https://ibm-cloud.slack.com/archives/C30NGUQ9E/p1638463862467900?thread_ts=1638462939.467300&cid=C30NGUQ9E

**Comment by hutchig** [comment]
#build

**Pull request merged**
