### PR TITLE
Rename convenience feature

### PR DESCRIPTION
**Pull request by cbridgha**
Explaining the churn in this PR - 

1) This represents renaming the top convenience jakartaee-9.0 feature to use io.openliberty....
1a) Also renamed appclientsupport-2.0 for io.openliberty
2) Also adding the new features ready to be included this release
2a) and removed beta flags until everything is stable (will switch back when all contained features switched)
3) Ran into compatibility issues with injection-1.0, and realized we don't use it with clientContainerRemoteSupport-1.0, so removed.

### CODE REVIEW

**Comment by cbridgha** [comment]
#build

**Comment by skasund** [comment]
L2 message review not required

**Comment by cbridgha** [comment]
#build

**Comment by cbridgha** [comment]
#build

**Comment by cbridgha** [comment]
Latest build with these changes: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_d0zg4PK5Eeq2j8eW2p4naw

**Review by hlhoots — APPROVED** [review]
Seems okay to me pending a good full build testing the change.

**Comment by cbridgha** [comment]
#build

**Comment by cbridgha** [comment]
#libby

**Comment by cbridgha** [comment]
#libby

**Pull request merged**
