### PR TITLE
adding block so windows doesn't run retrieveUninstallFileList twice

### PR DESCRIPTION
**Pull request by jacobwdv**
Check all asset's subdirectories for locked files before uninstalling.

### CODE REVIEW

**Comment by jacobwdv** [comment]
#build

**Comment by jacobwdv** [comment]
#build

**Comment by jacobwdv** [comment]
#build

**Comment by jacobwdv** [comment]
investigating how and why my changes didn't impact performance I believe it is because they are not run!

My steps (on praising1.fyre.ibm.com)

1. use PU to copy both CORE and BASE into their own repo: `C:\repositories\liberty.test2`
2. update the `installbase.bat` file in C:\Program Files\IBM\Installation Manager\eclipse\tools to use the new repository for BOTH packages 
3. run installbase.bat - while it's running it will eventually populate `C:\test\IMDATA_v9\temp` with jars. I copy these jars onto my thinkpad while it's installing core and base. 
4. open jar files, manifest shows ```Manifest-Version: 1.0
Build-Identifier: SNAPSHOT-Mon Nov 29 20:51:48 UTC 2021```
5. This should not be true, the manifest should show the most recent build if I built this correctly, but where did it get this version of the jar?!
6. Looking in the debug logs it appears to be buried in : `C:\Program Files\IBM\Installation Manager\eclipse\configuration\org.eclipse.osgi\964\0\.cp\lib8559\com.ibm.ws.install.jar`
7. How does the osgi cache this file, this file isn't even in the repository? I cleared IMShared and retried, same thing
8. Looking in repos I can see the one repository `C:\repositories\liberty` from way before contains `repo\liberty\plugins\com.ibm.was.liberty.dfp.v85_8.5.5009.20160120_1352.jar\lib\com.ibm.ws.install.jar\META-INF\`
9. note: test2 doesnt even have this file, i think it's because i copied only the CORE and BASE offerings when using PU. Looks like Benson copied every offering when doing it..
10. it appears this dfp file from the original C:\repositories\liberty repository is where it's getting the file from. I don't know why or how it's finding it there when using the C:\repositories\liberty.test2 repo but it seems to have it cached somewhere or looks into the chain

I'm now seeing if i download EVERY offering from my PB if perhaps the dfp file is downloaded and used by eclipse when installing. Will update once this is done, it'll take a while to download all these.

**Comment by jacobwdv** [comment]
Trying to copy all repos resulted in an error: 
```
Copying offering IBM WebSphere Application Server Liberty Network Deployment Trial 16.0.0.2 (Internal Version 16.0.2.20160526_2338).
   Missing artifacts for some installable units of component "com.ibm.websphere.liberty.NDTRIAL_16.0.2.20160526_2338"
      Adding file com.ibm.websphere.liberty.CORE.extras_16.0.2.20160526_2338 to repository C:\repositories\liberty.test3 failed.
         Resumable download failed for: https://rtpgsa.ibm.com/projects/l/liberty.build/liberty/WAS85.LIBERTY/test/cl160220160526-2258.51.linux/linux/zipper/externals/installables/repository/WLP/files/com.ibm.websphere.liberty.CORE.extras_16.0.2.20160526_2338.file.
            Failed to retrieve 'file com.ibm.websphere.liberty.CORE.extras_16.0.2.20160526_2338'.
               An exception is thrown while retrieving the file 'https://rtpgsa.ibm.com/projects/l/liberty.build/liberty/WAS85.LIBERTY/test/cl160220160526-2258.51.linux/linux/zipper/externals/installables/repository/WLP/files/com.ibm.websphere.liberty.CORE.extras_16.0.2.20160526_2338.file' to 'C:\repositories\liberty.test3\tmp\cicdip_Administrator\1639754103465\v\md5\5fe5af5c0a75127001e36dad89f89226_md5~3791999f1206e7501fd029e9d58ed891'.

```

Perhaps these personal builds aren't meant to be used this way? I noticed also that rtpgsa is connected to here even though the repo i specified was from a PB. WHen I added the repo it asked for w3 and for gsa user/pass. 
image

**Comment by jacobwdv** [comment]
#build

**Comment by jacobwdv** [comment]
#build

**Comment by jacobwdv** [comment]
fixes #19807

**Review by bensonlatibm — APPROVED** [review]
lgtm!

**Comment by bensonlatibm** [comment]
#run-libby-bot

**Comment by bensonlatibm** [comment]
failures in RTC build are not due to these changes.

**Pull request merged**
