### PR TITLE
Support new Sig Alg in JWT builer/consumer

### PR DESCRIPTION
**Pull request by c00crane**
Add new FAT tests for additional signature algorithms being added to the builder/consumer.

### CODE REVIEW

**Comment by c00crane** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.security.jwt_fat.builder,com.ibm.ws.security.jwt_fat.consumer,com.ibm.ws.security.mp.jwt.1.1_fat

**Comment by c00crane** [comment]
#run-libby-bot

**Comment by c00crane** [comment]
https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_46SOkNv-EeqigNlDxrUK9A completed with unrelated failures.  
The new tests added for the build and consumer ran 100% successfully.
There were no failures in any of the security FAT projects that share updated tools.

**Comment by teddyjtorres** [comment]
For issues #13578 and #13579

**Pull request merged**
