### PR TITLE
Create atomic dispatcher state - improved

### PR DESCRIPTION
**Pull request by ngmr**
Supercedes #16535 

Fixes an initialization error in the changes being made, to set up the initial value held by SpillDispatcher.stateRef

#build

### CODE REVIEW

**Comment by ngmr** [comment]
#run-libby-bot

**Comment by ngmr** [comment]
#build

**Comment by ngmr** [comment]
#run-libbry-bot

**Comment by ngmr** [comment]
#run-libby-bot

**Comment by ngmr** [comment]
#build

**Comment by ngmr** [comment]
#run-libby-bot

**Review by sakerl — APPROVED** [review]

**Pull request closed without merging**
