### PR TITLE
Run existing MP Rest Client FATs on 3.0 (RESTEasy) implementation

### PR DESCRIPTION
**Pull request by andymc12**
Includes:
* Many FAT updates - mostly to handle updated repeat logic, but also includes some changes to handle legal behavior changes between CXF and RESTEasy.
* Update to runtime code to ensure that MP Rest Client can read SSL config from Liberty's server.xml.
* Update to test framework to allow archives to be preserved after post server-stop processing had completed.
* Adds some diagnostic code to tests and test framework.

### CODE REVIEW

**Comment by andymc12** [comment]
#build

**Comment by andymc12** [comment]
Last build stopped unexpectedly... new #build

**Review by jim-krueger — APPROVED** [review]
LGTM

**Comment by andymc12** [comment]
This should be fine to merge, but due to build infrastructure issues, release mgmt has requested a newer personal #build

**Comment by andymc12** [comment]
The last build failed due to disk space... I manually kicked off another build without the space-consuming install manager stuff in hopes that this might successfully finish.  That build is at: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_NNUV0Ee3Eeyda8UYcX_yfQ (IBM internal only link)

**Comment by andymc12** [comment]
One failure, but seems unrelated.

**Pull request merged**
