### PR TITLE
JAXWS-2.2: Update CXF from 2.6.2 to 3.4

### PR DESCRIPTION
**Pull request by neuwerk**
Changes are a squash, cleanup, and additional tests fixes for:  #21395

### CODE REVIEW

**Comment by neuwerk** [comment]
#build

**Comment by wraschke** [comment]
test

**Comment by wraschke** [comment]
#libby

**Review by sawadood — APPROVED** [review]
Changes look good

**Comment by neuwerk** [comment]
https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_f6bYYPxlEey3m9ea3wJj4A&tab=com.ibm.team.build.web.ui.internal.editors.result.properties.PropertiesProvider

Green build

**Comment by neuwerk** [comment]
#run-libby-bot

**Pull request merged**
