### PR TITLE
Allow multiple version of singleton feature with featureUtility installFeature command

### LINKED ISSUE #17299: Allow multiple version of singleton feature with featureUtility installFeature command
**Describe the bug**
Both scenarios fail:
- /bin/featureUtility installFeature javaee-7.0 javaee-8.0 servlet-3.1
- /bin/featureUtility installFeature baseBundle

Initializing ...
<---------------------> 0.00%
Resolving remote features. This process might take several minutes to complete.
<====-----------------> 15.00%
CWWKF1405E: The javaee-7.0 and javaee-8.0 singleton features are incompatible with each other and they cannot be installed at the same time.

**Steps to Reproduce**
- /bin/featureUtility installFeature javaee-7.0 javaee-8.0 servlet-3.1

**Expected behavior**
When using a installFeature, featureUtility should allow installation of features with multiple versions. 
This will also allow bundle feautres installation for closed liberty.

**Diagnostic information:**
 - OpenLiberty Version: 21.x Liberty

### PR DESCRIPTION
**Pull request by jjiwooLim**
Fixes #17299

### CODE REVIEW

**Review by bensonlatibm — CHANGES_REQUESTED** [review]
Looks good - only need to update all copyright headers to include 2021

**Comment by jjiwooLim** [comment]
#build

**Comment by jjiwooLim** [comment]
The build failed with wlp.lib.extract_fat failures which are unlrelated to these changes

**Comment by jjiwooLim** [comment]
#libbybot

**Review by bensonlatibm — APPROVED** [review]
Looks good!

**Comment by bensonlatibm** [comment]
The wlp.lib.extract_fat failures are unlrelated to these changes. They will be fixed via
https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.workitem.viewWorkItem&id=276597

**Pull request merged**
