### PR TITLE
FeatureManager/FeatureUtility set install directory

### LINKED ISSUE #19303: Product validation fails when iFix is applied
When the iFix is applied, featureManager install command and featureUtility installFeature command will fail at product validation stage. 

Repro steps:
Apply PH39418 (which alters com.ibm.ws.kernel.boot.archive_1.0.56.jar) to 21.0.0.9 liberty
Install any feature using featureManager/featureUtility
```
...
Installing json-1.0 ...
[2021-11-08, 18:16:31:664 EST] Step 4 of 7: Installing json-1.0 ...
[2021-11-08, 18:16:31:685 EST] Successfully installed feature JavaScript Object Notation for Java 1.0.
[2021-11-08, 18:16:31:689 EST] Successfully updated the checksum file /Users/jiwoolim/Downloads/21009Temp/lib/features/checksums/com.ibm.websphere.appserver.json-1.0.cs for exising checksum.
[2021-11-08, 18:16:31:859 EST] Validating installed fixes ...
[2021-11-08, 18:16:31:859 EST] Step 5 of 7: Validating installed fixes ...
[2021-11-08, 18:16:31:859 EST] No fix is required to be reapplied.
[2021-11-08, 18:16:31:859 EST] Cleaning up temporary files ...
[2021-11-08, 18:16:31:859 EST] Step 6 of 7: Cleaning up temporary files ...
[2021-11-08, 18:16:31:861 EST] Successfully completed cleaning up temporary files.
[2021-11-08, 18:16:31:861 EST] Installation completed
[2021-11-08, 18:16:31:861 EST] Step 7 of 7: Installation completed
[2021-11-08, 18:16:31:861 EST] 
[2021-11-08, 18:16:31:862 EST] CWWKF1017I: One or more features installed successfully: [json-1.0].
[2021-11-08, 18:16:31:862 EST] 
[2021-11-08, 18:16:31:863 EST] All features were successfully installed.
[2021-11-08, 18:16:31:863 EST] 
[2021-11-08, 18:16:31:865 EST] Start product validation...
[2021-11-08, 18:16:31:900 EST] Validating feature: com.ibm.websphere.appserver.kernel-1.0... 
[2021-11-08, 18:16:31:900 EST] FAIL!
[2021-11-08, 18:16:31:900 EST]   [ERROR] Content: lib/com.ibm.ws.kernel.boot.archive_1.0.56.jar is either changed or broken.
  [ERROR] Content: lib/com.ibm.ws.kernel.boot_1.0.56.jar is either changed or broken.

[2021-11-08, 18:16:31:927 EST] Product validation was complete, and found 2 error(s).
...
```

### PR DESCRIPTION
**Pull request by jjiwooLim**
fixes #19303

Product validation steps are written [here](https://ibm.ent.box.com/notes/762901110184)

For testing:

- Created new binary called `testIfix.jar`

- For the tool to pick up this new jar, created `testIfix.mf` inside /wlp/lib/platform. Then created the corresponding checksum file `testIfix.cs` inside /wlp/lib/platform/checksums. 
- The checksum inside `testIfix.cs` has wrong checksum so that the first validation check fails. When the first validation fails, it will check if the iFix is applied.
- It will get the correct checksum from the iFix. /wlp/lib/fixes/xml.xml and /wlp/lib/fixes/lpmf.lpmf has the correct checksum.

### CODE REVIEW

**Comment by jjiwooLim** [comment]
#build

**Comment by jjiwooLim** [comment]
Prev build ran out of space. Kicking off another build

**Comment by jjiwooLim** [comment]
#build

**Comment by jjiwooLim** [comment]
FAT failures are not related to this code changes

**Comment by jjiwooLim** [comment]
#libby-bot

**Comment by jjiwooLim** [comment]
#build

**Comment by jjiwooLim** [comment]
#build

**Comment by jjiwooLim** [comment]
#build

**Comment by jjiwooLim** [comment]
Product validation steps are written [here](https://ibm.ent.box.com/notes/762901110184)

**Comment by jjiwooLim** [comment]
#libby-bot

**Review by bensonlatibm — APPROVED** [review]
lgtm!

**Pull request merged**
