### PR TITLE
Issue #18174: Remove SharedServer from WCApplicationMBeanStatusTest

### LINKED ISSUE #18174: Remove SharedServer from WCApplicationMBeanStatusTest

### PR DESCRIPTION
**Pull request by pnicolucci**
fixes #18174

### CODE REVIEW

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#run-libby-bot

**Review by isaacrivriv — APPROVED** [review]
Looks good to me thanks!

**Pull request merged**
