### PR TITLE
Remove checked for support cipher suite

### LINKED ISSUE #18353: Warning CWWKS9590W when strong ciphers are configured
We have configured the Ciphers Suites to the liberty server. In server.xml we have,  

```
<ssl id="defaultSSLConfig"
.....
enabledCiphers="SSL_ECDHE_RSA_WITH_AES_256_CBC_SHA384 TLS_DHE_RSA_WITH_AES_128_CBC_SHA256 TLS_DHE_RSA_WITH_AES_128_GCM_SHA256 TLS_DHE_RSA_WITH_AES_256_CBC_SHA256 TLS_DHE_RSA_WITH_AES_256_GCM_SHA384 TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256 TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 "
....
```

When added this, start getting the below warnings:
```
[WARNING ] CWWKS9590W: The SSL_ECDHE_RSA_WITH_AES_256_CBC_SHA384 requested cipher suite appears to have [integrity, confidentiality, establishTrustInTarget, strong, noexport] association options that do not match the specified [integrity, confidentiality, establishTrustInTarget, noexport, tls] supported options and the [integrity, confidentiality] required options.
[WARNING ] CWWKS9590W: The TLS_DHE_RSA_WITH_AES_128_CBC_SHA256 requested cipher suite appears to have [integrity, confidentiality, establishTrustInTarget, strong, noexport, tls] association options that do not match the specified [integrity, confidentiality, establishTrustInTarget, noexport, tls] supported options and the [integrity, confidentiality] required options.
```

In this case,
Supported Association Options list is [integrity, confidentiality, establishTrustInTarget, noexport, tls]
Required Association Options list is [integrity, confidentiality]

As per our discussion with Liberty team - **"When using the enabledCiphers attribute with strong ciphers, it is not possible to eliminate the CWWKS9590W message without removing the strong ciphers. We need to open an issue to fix this."**

Hence opening this issue to fix this in the Liberty code.

### PR DESCRIPTION
**Pull request by utle**
There is no need to check for support with custom cipher suite

Fixes #18353

### CODE REVIEW

**Comment by utle** [comment]
#build

**Comment by utle** [comment]
#build

**Comment by utle** [comment]
#build

**Comment by utle** [comment]
#build

**Comment by utle** [comment]
#build

**Comment by utle** [comment]
#build

**Review by chirp1 — COMMENTED** [review]
Updates look good.

**Review by arkarkala — APPROVED** [review]

**Comment by utle** [comment]
#build

**Comment by utle** [comment]
#run-libby-bot

**Pull request merged**
