### PR TITLE
Issue #8456: Return required roles for authorization failures in SCIM…

### PR DESCRIPTION
**Pull request by jvanhill**
… 2.0. Also add SCIM 2.0 FAT project as well as SCIM 2.0 unit tests

### CODE REVIEW

**Comment by tevans78** [comment]
Please remove the IBM Confidential template from the settings

**Comment by jvanhill** [comment]
Hey #libby

**Comment by jvanhill** [comment]
#build

**Comment by jvanhill** [comment]
#build

**Comment by jvanhill** [comment]
#build

**Pull request merged**
