### PR TITLE
Issue #21300: Update Servlet 6.0 Resources

### LINKED ISSUE #21300: Review `jakarta.servlet.resources` for Servlet 6.0
Servlet 5.0: https://github.com/OpenLiberty/open-liberty/tree/integration/dev/io.openliberty.jakarta.servlet.5.0/src/jakarta/servlet/resources

Servlet 6.0: https://github.com/OpenLiberty/open-liberty/tree/integration/dev/io.openliberty.jakarta.servlet.6.0

Servlet 6.0 does not include the additional resources that we normally include. There should be a JSP dependency on these that we'll find as we continue to do more testing.

### PR DESCRIPTION
**Pull request by pnicolucci**
fixes #21300

### CODE REVIEW

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
#libby #build

**Review by pmd1nh — APPROVED** [review]

**Pull request merged**
