### PR TITLE
Avoid reactivating when optional CDIJSFInitializer service goes away

### PR DESCRIPTION
**Pull request by tjwatson**
Avoid reactivation of com.ibm.wsspi.webcontainer.extension.ExtensionFactory service implementations to avoid causing the WebContainer to be reactivated during startup.

### CODE REVIEW

**Comment by tjwatson** [comment]
#build

**Review by KyleAure — DISMISSED** [review]

**Review by pnicolucci — COMMENTED** [review]
These changes IMO warrant an update to the copyright date range where 2023 isn't already included. I'm going to pull your changes in locally and run some full buckets.

**Comment by tjwatson** [comment]
> These changes IMO warrant an update to the copyright date range where 2023 isn't already included. I'm going to pull your changes in locally and run some full buckets.

I pushed up a commit to update copyright dates.

**Review by KyleAure — APPROVED** [review]

**Comment by pnicolucci** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jsf.2.3_fat,com.ibm.ws.jsf.2.2_fat,io.openliberty.org.apache.myfaces.4.0_fat,com.ibm.ws.jsfContainer_fat_2.2,com.ibm.ws.jsfContainer_fat_2.3

**Comment by tjwatson** [comment]
#libby

**Review by pnicolucci — APPROVED** [review]

**Comment by tjwatson** [comment]
#libby

**Comment by tjwatson** [comment]
#libby

**Pull request merged**
