### PR TITLE
test updates , fix server configs to have same set of features

### PR DESCRIPTION
**Pull request by arunavemulapalli**
Make sure that the test config files specify only the component specific config (for dynamic updates) and not altering the features.

### CODE REVIEW

**Comment by arunavemulapalli** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.wssecurity_fat.wsscxf

**Comment by arunavemulapalli** [comment]
#build

**Review by meiaus — APPROVED** [review]

**Comment by arunavemulapalli** [comment]
#build

**Comment by arunavemulapalli** [comment]
#build

**Comment by arunavemulapalli** [comment]
completed this change via another pr

**Pull request closed without merging**
