### PR TITLE
Fixes #29802 - The Gitter link in the default page returns 404

### LINKED ISSUE #29802: The Gitter link in the default page returns 404
**Describe the bug**
The Gitter link in the following default page (http://localhost:9080/) returns 404. Also, the Twitter link should be updated because Twitter was renamed to X.

Screenshot 2024-10-08 at 10 07 13 AM

**Steps to Reproduce**  
- Go to https://openliberty.io/start/ to generate a starter project
- unzip the project
- run `./mvnw liberty:dev`
- visit http://localhost:9080

**Expected behavior**  
- Gitter link should return to https://app.gitter.im/#/room/#OpenLiberty_development:gitter.im
- Twitter link should be removed or renamed to X

**Diagnostic information:**  
 - OpenLiberty Version: tried with OL 24.0.0.10
 - Affected feature(s): not sure
 - Java Version: any supported version
 - server.xml configuration (WITHOUT sensitive information like passwords)
   - see it from a starter project 
 - If it would be useful, upload the messages.log file found in `$WLP_OUTPUT_DIR/messages.log`

**Additional context**  
None

### PR DESCRIPTION
**Pull request by rivaldorodrigues**
- [x] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [x] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [x] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

### Description:

Update of the Gitter link and removal of the Twitter icon and link.
Resolves #29802

### Details:

- Updated the Gitter div link from `https://gitter.im/OpenLiberty/`  to `https://app.gitter.im/#/room/#OpenLiberty_development:gitter.im`
- Removed the Twitter icon div
- Removed the Twitter logo image
- Removed the second row in the section to adjust the layout while maintaining responsiveness and spacing between the items.

### Evidences:

CleanShot 2024-10-17 at 12 21 38
CleanShot 2024-10-17 at 12 21 53

### CODE REVIEW

**Comment by gkwan-ibm** [comment]
hi @seshadhri-aswath, @mrsaldana, or @pmd1nh

Would either of you review and follow up this PR?

**Comment by rivaldorodrigues** [comment]
The modification consists of changing an independent HTML file.
To test the changes, I opened the file in different browsers (Chrome, Firefox and Safari) and checked if the Gitter link had been changed and the Twitter icon removed.

**Comment by gkwan-ibm** [comment]
hi @seshadhri-aswath, @mrsaldana, or @pmd1nh

Rivaldo Rodrigues is an IBMer but not from WAS org. He is participating in the Open Source Contributors Coalition. Would either of you review and follow up his contributed PR? Or forward to someone else to do that.

**Comment by pmd1nh** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.transport.http_test

**Comment by gkwan-ibm** [comment]
hi @rivaldorodrigues 

It means you need to sign the CLA even you are IBMer. Follow this [instructions](https://github.com/OpenLiberty/open-liberty/blob/integration/CONTRIBUTING.md#contributor-license-agreement).

**Comment by rivaldorodrigues** [comment]
Thanks for the advice. I will proceed with this.

**Comment by pmd1nh** [comment]
@gkwan-ibm I am trying to review and merge this one. 
@rivaldorodrigues I will handle it from here.  Thanks for PR!

**Comment by rivaldorodrigues** [comment]
Alright. Thank you.

**Comment by pmd1nh** [comment]
@rivaldorodrigues Sorry I messed up the process for the external contributed PR.  

Can you please rebase and correct the code using the change from [29925](https://github.com/OpenLiberty/open-liberty/pull/29925) ?  We need to keep the `<id>` in the `<div>` in order to retain the same behavior.  I will then merge this PR for you.

Thank you!

**Comment by rivaldorodrigues** [comment]
Hi, @pmd1nh. That's ok. Thanks for reopening it.
I proceeded with the rebase, and now it's synced. 

I applied the same CSS adjustments from #29925, but I noticed that the items remain with the wrong spacing between each other.

CleanShot 2024-10-30 at 14 42 41@2x

As you asked to keep the `id` in the `div` I added a new CSS block to ensure even spacing distribution.
What do you think? Is it a possible solution?

Were is the evidence of the fix:

CleanShot 2024-10-30 at 14 48 52@2x

CleanShot 2024-10-30 at 14 49 24@2x

**Comment by pmd1nh** [comment]
@rivaldorodrigues how does it look in iphone or smaller screen in your simulation?

**Comment by rivaldorodrigues** [comment]
Here, the items remain evenly spaced. When the resolution is very small, some items move to the next line.
CleanShot 2024-10-30 at 15 34 04

In the iPhone SE simulator, the icons stay on the same line but with equal spacing.
CleanShot 2024-10-30 at 15 30 29@2x

These blank spaces appear in the Chrome simulation, but I believe this is a separate issue since it also happens in the current branch.

**Comment by pmd1nh** [comment]
@gkwan-ibm Do you think if anyone can rely or look for the  `<div id="first_row" class="row">`  or `<div id="second_row" class="row">` in their script/automation?  That is our main concerns.

**Comment by gkwan-ibm** [comment]
Although I don't know the answer of "anyone can rely or look for the` <div id="first_row" class="row">` or `<div id="second_row" class="row">` in their script/automation?", I doubt to remove/rename `first_row` to `resources_single_row`. 

hi @rivaldorodrigues would you simply remove the Twitter link and update the Gitter link? No need to update any `<div>`.

**Comment by gkwan-ibm** [comment]
Although I don't know the answer of "anyone can rely or look for the` <div id="first_row" class="row">` or `<div id="second_row" class="row">` in their script/automation?", I doubt to remove/rename `first_row` to `resources_single_row`. I got why combine 2 rows to 1 row.

Let think about it.

**Comment by gkwan-ibm** [comment]
I agree to combine 2 rows into 1 row as a simpler solution and I also agree Phu's concern. I suggest
- use `first_row` instead of `resources_single_row`
- no need to add new style for `#resources_single_row`
- just update the `first_row`'s width style to 100%

**Comment by rivaldorodrigues** [comment]
Understood. I just applied your suggestions.

**Comment by pmd1nh** [comment]
cloned and running internal build process to make sure everything is good before approve and close this out.

**Review by pmd1nh — APPROVED** [review]

**Comment by pmd1nh** [comment]
Personal build is good in my own PR

**Comment by pmd1nh** [comment]
thanks @rivaldorodrigues !

**Comment by rivaldorodrigues** [comment]
Many thanks, @pmd1nh and @gkwan-ibm

**Pull request merged**
