### PR TITLE
Myfaces 4555

### LINKED ISSUE #24099: MYFACES-4555
https://issues.apache.org/jira/browse/MYFACES-4555

### PR DESCRIPTION
**Pull request by pnicolucci**
fixes #24099

### CODE REVIEW

**Comment by pnicolucci** [comment]
#libby #build #spawn.fullfat.buckets=io.openliberty.org.apache.myfaces.4.0_fat

**Comment by pnicolucci** [comment]
#libby #buid

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
#libby #build

**Review by volosied — APPROVED** [review]

**Pull request merged**
