### PR TITLE
Issue #20939: Reproduction for NoClassDefFoundError when Hazelcast is…

### PR DESCRIPTION
**Pull request by jvanhill**
… used in an application.

### CODE REVIEW

**Comment by jvanhill** [comment]
#build

**Comment by jvanhill** [comment]
#libby
#build

**Comment by jvanhill** [comment]
#libby
#build

**Comment by jvanhill** [comment]
#libby
#build

**Comment by jvanhill** [comment]
#libby
#build

**Review by ryanesch — APPROVED** [review]

**Pull request merged**
