### PR TITLE
Issue #23615: Fix stop command in wlp.lib.extract_fat

### LINKED ISSUE #23615: Fix javacore issue in wlp.lib.extract_fat
There was a bug in the wlp.lib.extract_fat where the stop command was being called, but not working properly.  This was causing a process to be destroyed, and thus causing a javacore in some cases.  This fix resolves the issue with the stop command.

### PR DESCRIPTION
**Pull request by hlhoots**
#build 
fixes #23615

### CODE REVIEW

**Review by jimblye — DISMISSED** [review]

**Comment by hlhoots** [comment]
Windows build here: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_GCVswHY6Ee2ux-fzqy0jNQ

Target locations of links might be accessible only to IBM employees.

**Comment by hlhoots** [comment]
windows build had file locks.  rebuilding on both platforms.

https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_cSGF4HceEe2ux-fzqy0jNQ

#build 

Target locations of links might be accessible only to IBM employees.

**Comment by hlhoots** [comment]
#build

**Comment by hlhoots** [comment]
new win build https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_MbBk0Hf1Ee2ux-fzqy0jNQ

Target locations of links might be accessible only to IBM employees.

**Comment by hlhoots** [comment]
Last builds were both good. The windows build had a couple of errors but the bucket where my changes are located ran successfully.

**Comment by hlhoots** [comment]
#run-libby-bot

**Review by jimblye — APPROVED** [review]

**Pull request merged**
