### PR TITLE
Issue #23954: Make the authCache->cacheRef and webAppSecurity->logged…

### LINKED ISSUE #23954: The authCache->cacheRef and webAppSecurity->loggedOutCookieCacheRef server configuration elements are not included in the documentation.
The `authCache->cacheRef` and `webAppSecurity->loggedOutCookieCacheRef` attributes mistakenly were not updated to be GA instead of beta and therefore are not showing up in the auto-generated documentation. They should have GA'd in the 22.0.0.11 release.

This results in them not showing up in the documentation on openlibery.io as well as missing from Liberty developer tools.

They need to have the `ibm:beta="true"` attribute removed from the metatype.

### PR DESCRIPTION
**Pull request by jvanhill**
…OutCookieCacheRef configuration elements GA, instead of beta.

fixes #23954

### CODE REVIEW

**Comment by jvanhill** [comment]
#build

**Comment by jvanhill** [comment]
#build

**Comment by jvanhill** [comment]
#build

**Review by ryanesch — APPROVED** [review]

**Comment by jvanhill** [comment]
#build

**Comment by jvanhill** [comment]
#libby

**Comment by jvanhill** [comment]
The single failure was a known test failure.

**Pull request merged**
