### PR TITLE
Issue #13088: Add eeCompatible feature to the jsp-2.3 feature

### LINKED ISSUE #13088: Add eeCompatible-7.0 to the jsp-2.3 public feature
Since the jsp-3.0 feature pulls in the el-4.0 feature and that feature specifies the eeCompatible-9.0 feature already we have this via the transitive property. The el-4.0 feature added this feature in : https://github.com/openliberty/open-liberty/issues/13069

We should look at how the runtime fails when including two features such as `jsp-3.0` and `jsp-2.3` it might be cleaner to actually add eeCompatible to the `jsp-3.0` and `jsp-2.3` features.

Looks like this work was already done in : #13165 for the `jsp-3.0` feature, we should look at the `jsp-2.3` feature to see if we can do something similar to what we've done for `el-3.0`: https://github.com/OpenLiberty/open-liberty/issues/13306

The `jsp-2.3` feature is part of EE7 and therefore should specify `com.ibm.websphere.appserver.eeCompatible-7.0` it must also tolerate the 6.0 version of the feature because currently for example `beanValidation-1.0` specifies the 6.0 version and before adding eeCompatible to jsp-2.3 the features load fine together. We also need to tolerate the 8.0 version because there was no EE8 update for JSP so features such as `jsf-2.3` need to work with `jsp-2.3`.

[https://www.ibm.com/support/knowledgecenter/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/rwlp_prog_model_supported_combos.html](https://www.ibm.com/support/knowledgecenter/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/rwlp_prog_model_supported_combos.html)

> [AUDIT   ] CWWKE0001I: The server test has been launched.
> [AUDIT   ] CWWKZ0058I: Monitoring dropins for applications.
> [AUDIT   ] CWWKF0012I: The server installed the following features: [beanValidation-1.0, el-3.0, jsp-2.3, servlet-3.1].
> [AUDIT   ] CWWKF0011I: The test server is ready to run a smarter planet. The test server started in 4.471 seconds.
> [AUDIT   ] CWWKE0055I: Server shutdown requested on Monday, September 14, 2020 at 2:23 PM. The server test is shutting down.
> [AUDIT   ] CWWKE1100I: Waiting for up to 30 seconds for the server to quiesce.
> [AUDIT   ] CWWKE0036I: The server test stopped after 18.126 seconds.

### PR DESCRIPTION
**Pull request by pnicolucci**
fixes #13088

### CODE REVIEW

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
Personal Build: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_OuuJoP6NEeqZosoAJ-GPIQ

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#run-libby-bot

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Review by cbridgha — APPROVED** [review]
LGTM

**Review by isaacrivriv — APPROVED** [review]
LGTM Thanks!

**Comment by pnicolucci** [comment]
#run-libby-bot

**Pull request merged**
