### PR TITLE
Slim down HA tests

### PR DESCRIPTION
**Pull request by jonhawkes**
#build

### CODE REVIEW

**Comment by jonhawkes** [comment]
#build

**Comment by jonhawkes** [comment]
#build

**Comment by jonhawkes** [comment]
#build

**Comment by jonhawkes** [comment]
#pb

**Comment by jonhawkes** [comment]
#build

**Comment by jonhawkes** [comment]
#build

**Comment by jonhawkes** [comment]
#libby #build

**Comment by jonhawkes** [comment]
#pb

**Comment by jonhawkes** [comment]
#libby #build #pb

**Comment by jonhawkes** [comment]
#build

**Review by neilgsyoung — DISMISSED** [review]
Looks good.

**Comment by jonhawkes** [comment]
#build

**Comment by jonhawkes** [comment]
#libby #build

**Review by neilgsyoung — APPROVED** [review]

**Pull request merged**
