### PR TITLE
Change coordinates for arquillian plugin

### PR DESCRIPTION
**Pull request by andymc12**

### CODE REVIEW

**Comment by andymc12** [comment]
#build

**Comment by andymc12** [comment]
#build

**Comment by andymc12** [comment]
Really need a #build

**Comment by andymc12** [comment]
I heard LibbyBot got restarted - trying to #build again

**Comment by ewhoch** [comment]
This was tested extensively locally by a few devs and its' consistent with other buckets now. seems fine to merge as is.

**Pull request merged**
