### PR TITLE
Fixes the RequestProbe FAT to wait for server config update

### PR DESCRIPTION
**Pull request by pgunapal**

### CODE REVIEW

**Comment by pgunapal** [comment]
fixes #15168

**Comment by pgunapal** [comment]
#build

**Comment by pgunapal** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.request.timing_fat

**Review by fmhwong — APPROVED** [review]
LGTM

**Comment by pgunapal** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.request.timing_fat

**Comment by pgunapal** [comment]
#libby

**Pull request merged**
