### PR TITLE
Changes needed to remove SSE testcase skips for EE9

### PR DESCRIPTION
**Pull request by jim-krueger**

### CODE REVIEW

**Comment by jim-krueger** [comment]
#build

**Review by WhiteCat22 — APPROVED** [review]

**Review by andymc12 — APPROVED** [review]

**Comment by jim-krueger** [comment]
#build

**Comment by jim-krueger** [comment]
#build

**Comment by jim-krueger** [comment]
#buid

**Comment by jim-krueger** [comment]
#build

**Comment by jim-krueger** [comment]
Test failures unrelated to changes.  Merging.

**Pull request merged**
