### PR TITLE
ws-security and ws-security.saml fat updates to run with jaxws-2.2 and jaxws-2.3

### PR DESCRIPTION
**Pull request by meiaus**
Consolidate the prior branches for EE8 update:

mei_cxfsaml_fat_jaxws2.3 (https://github.com/OpenLiberty/open-liberty/pull/15920)
mei_wsscxfsaml_fat_jaxws2.3_0304 (https://github.com/OpenLiberty/open-liberty/pull/16284)
mei_java11_ee8_debug

and the newly split of projects via the current branch:
wssec_all_fat_0522

### CODE REVIEW

**Comment by meiaus** [comment]
#build

**Comment by meiaus** [comment]
Submitted again from selected platform `Liberty Java 8 - EBC`: 

https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=__HU-EMhrEeuzsMpZrObBiQ

**Comment by meiaus** [comment]
#run-libby-bot

**Review by arunavemulapalli — APPROVED** [review]
We may need to do some cleanup of the files.
Approving pending on good personal build results.

**Comment by meiaus** [comment]
#run-libby-bot

**Comment by meiaus** [comment]
#run-libby-bot

**Comment by meiaus** [comment]
#run-libby-bot

**Comment by meiaus** [comment]
#run-libby-bot

**Comment by meiaus** [comment]
#run-libby-bot

**Comment by meiaus** [comment]
#run-libby-bot

**Comment by meiaus** [comment]
All wssec FAT passed in the PB EBC meiaus-17452-20210629-1125, the only log error is

`fat.build.response.for.child-build.featureStart_fat0    waitFor - Open Liberty feature simple start test with Open Liberty image (child build.featureStart_fat0)`
The related build log: 
```
2021-06-30 00:38:51 [Jazz build engine] 
2021-06-30 00:38:51 [Jazz build engine] Substituted the following configuration element property variables:
2021-06-30 00:38:51 [Jazz build engine] 	com.ibm.team.build.ant : com.ibm.team.build.ant.buildFile = ${team.scm.fetchDestination}/BuildLauncher/build-liberty-ghe.xml   -->   com.ibm.team.build.ant.buildFile = build.launch/BuildLauncher/build-liberty-ghe.xml
2021-06-30 00:38:51 [Jazz build engine] 	com.ibm.team.build.ant : com.ibm.team.build.ant.antArgs = -keep-going ${extra.ant.options} -lib BuildLauncher/lib -propertyfile ../build.properties   -->   com.ibm.team.build.ant.antArgs = -keep-going  -lib BuildLauncher/lib -propertyfile ../build.properties
2021-06-30 00:38:51 [Jazz build engine] 	com.ibm.team.build.ant : com.ibm.team.build.ant.workingDir = ${team.scm.fetchDestination}   -->   com.ibm.team.build.ant.workingDir = build.launch
2021-06-30 00:38:51 [Jazz build engine] 
2021-06-30 00:38:51 [Jazz build engine] running on host: ne-7b6c3-088b-41a2-a218-7371e44779d8-ebc-wpspd2jemngl
2021-06-30 00:38:51 [Jazz build engine] Should build occur?
2021-06-30 00:38:51 [Jazz build engine] Yes: Always build a user initiated request.
2021-06-30 00:38:51 [Jazz build engine] Invoking pre-build participant "com.ibm.team.build.jazzscm"
CRRTC3524W: Communication with the repository failed due to this error: CRJAZ1371E The following URL cannot be reached: https://wasrtc.hursley.ibm.com:9443/jazz/service/com.ibm.team.repository.common.internal.IRepositoryRemoteService. The server cannot be reached. The network could not connect to the server. Error details: Connection timed out. 
```

**Comment by meiaus** [comment]
#run-libby-bot

**Comment by meiaus** [comment]
#run-libby-bot

**Comment by meiaus** [comment]
#build

**Comment by meiaus** [comment]
#run-libby-bot

**Comment by meiaus** [comment]
#help

**Comment by meiaus** [comment]
#run-libby-bot

**Comment by meiaus** [comment]
#build

**Comment by meiaus** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.wssecurity_fat.wsscxf,com.ibm.ws.wssecurity_fat.wsscxf.saml.3,com.ibm.ws.wssecurity_fat.wsscxf.saml.5,com.ibm.ws.wssecurity_fat.wsscxf.saml.1,com.ibm.ws.wssecurity_fat.wsscxf.saml.4,com.ibm.ws.wssecurity_fat.wsscxf.saml.2,com.ibm.ws.wssecurity_fat.wsscxf.1,com.ibm.ws.wssecurity_fat.wsscxf.saml

**Comment by meiaus** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.wssecurity_fat.wsscxf,com.ibm.ws.wssecurity_fat.wsscxf.saml.3,com.ibm.ws.wssecurity_fat.wsscxf.saml.5,com.ibm.ws.wssecurity_fat.wsscxf.saml.1,com.ibm.ws.wssecurity_fat.wsscxf.saml.4,com.ibm.ws.wssecurity_fat.wsscxf.saml.2,com.ibm.ws.wssecurity_fat.wsscxf.1,com.ibm.ws.wssecurity_fat.wsscxf.saml

**Comment by meiaus** [comment]
#run-libby-bot

**Comment by meiaus** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.wssecurity_fat.wsscxf,com.ibm.ws.wssecurity_fat.wsscxf.saml.3,com.ibm.ws.wssecurity_fat.wsscxf.saml.5,com.ibm.ws.wssecurity_fat.wsscxf.saml.1,com.ibm.ws.wssecurity_fat.wsscxf.saml.4,com.ibm.ws.wssecurity_fat.wsscxf.saml.2,com.ibm.ws.wssecurity_fat.wsscxf.1,com.ibm.ws.wssecurity_fat.wsscxf.saml

**Comment by meiaus** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.wssecurity_fat.wsscxf,com.ibm.ws.wssecurity_fat.wsscxf.1

**Comment by meiaus** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.wssecurity_fat.wsscxf.saml,com.ibm.ws.wssecurity_fat.wsscxf.saml.1,com.ibm.ws.wssecurity_fat.wsscxf.saml.5

**Comment by meiaus** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.wssecurity_fat.wsscxf.saml.2,com.ibm.ws.wssecurity_fat.wsscxf.saml.3,com.ibm.ws.wssecurity_fat.wsscxf.saml.4

**Comment by meiaus** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.wssecurity_fat.wsscxf,com.ibm.ws.wssecurity_fat.wsscxf.1

**Comment by meiaus** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.wssecurity_fat.wsscxf.saml,com.ibm.ws.wssecurity_fat.wsscxf.saml.1,com.ibm.ws.wssecurity_fat.wsscxf.saml.5

**Comment by meiaus** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.wssecurity_fat.wsscxf.saml.2,com.ibm.ws.wssecurity_fat.wsscxf.saml.3,com.ibm.ws.wssecurity_fat.wsscxf.saml.4

**Comment by meiaus** [comment]
#run-libby-bot

**Comment by meiaus** [comment]
Note: the latest 3 PB with explicit comments for build properties specified are complete, which verified all related wssec FAT are tested/passed.  Although 2 of these PB contained few errors from other FAT, which will be out of concern here before merging this PR.

image

image

Error/failure from other FAT's:

image


image

**Comment by arunavemulapalli** [comment]
for #12449

**Pull request merged**
