### PR TITLE
Remove GH actions

### PR DESCRIPTION
**Pull request by KyleAure**
Remove GH Actions build. 
In its current state, it is unsuitable for continuous integration (CI) testing as our builds are limited to a concurrency limit based on the GH Organization and not a per-project basis. 
We will be searching for an alternative solution for a modern CI platform.

### CODE REVIEW

**Review by websterc87 — APPROVED** [review]
Looks good to me,

**Comment by KyleAure** [comment]
Force pushed to resolve merge conflicts.

**Comment by KyleAure** [comment]
#libbybot

**Comment by KyleAure** [comment]
Only deleting GitHub actions, no product or test code changes.

**Comment by wraschke** [comment]
Content of `.github/workflow-scripts/validate-copyright-headers.sh` doesn't mean actual bad headers and at any rate, file is deleted under this PR. So merging.

**Pull request merged**
