### PR TITLE
Set ZOS encoding

### LINKED ISSUE #30461: ZOS Encoding not set in TCKUtilities.getDetectedShortNames
mf files in zos are encoded in EBCDIC, we need to manually set the charset or we'll get an error.

### PR DESCRIPTION
**Pull request by benjamin-confino**
- [x] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [x] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [x] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

Resolves #30461

### CODE REVIEW

**Comment by benjamin-confino** [comment]
#build
 ([view Open Liberty Personal Build](https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?pipelineId=f2e0ae5f-38be-4f2c-8a4e-956e8fc937cf) - :white_check_mark: completed successfully!)
#spawn.zos=true

_Note: Target locations of links might be accessible only to IBM employees._

**Comment by benjamin-confino** [comment]
#build
 ([view Open Liberty Personal Build](https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?pipelineId=60b879f4-626e-4745-875f-9f5c14cbd500) - :x: completed with errors/failures.)
#spawn.zos=true

_Note: Target locations of links might be accessible only to IBM employees._

**Comment by benjamin-confino** [comment]
#build
 ([view Open Liberty Personal Build](https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?pipelineId=6cffbe12-a435-4cc5-821e-588116a9116c) - :white_check_mark: completed successfully!)
 #spawn.zos=true

_Note: Target locations of links might be accessible only to IBM employees._

**Comment by benjamin-confino** [comment]
#build
 ([view Open Liberty Personal Build](https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?pipelineId=5ce3ee7a-b80a-456c-bdc0-19ad0355ade5) - :white_check_mark: completed successfully!)
#spawn.zos=true

_Note: Target locations of links might be accessible only to IBM employees._

**Comment by benjamin-confino** [comment]
ZOS soe here: https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?pipelineId=9def920d-4f90-4285-aea8-07ebb40bcc96

**Review by sakerl — APPROVED** [review]

**Pull request merged**
