### PR TITLE
add sysout for FAT failures

### PR DESCRIPTION
**Pull request by benjamin-confino**
To help investigate https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.workitem.viewWorkItem&id=283911

### CODE REVIEW

**Comment by benjamin-confino** [comment]
#build

**Comment by benjamin-confino** [comment]
#build

**Comment by benjamin-confino** [comment]
#build

**Review by Azquelt — APPROVED** [review]

**Review by Azquelt — APPROVED** [review]
It would be much better if these had better messages explaining what happened and used the logging framework.

These changes need to come out once you've found and fixed the issue.

**Comment by benjamin-confino** [comment]
#run-libby-bot

**Pull request merged**
