### PR TITLE
Tomcat 66317 port to Open Liberty

### LINKED ISSUE #23040: Fix for missing privileged block
https://bz.apache.org/bugzilla/show_bug.cgi?id=66317

Add fix for missing security manager check and privileged block for accessing classloader of lambda coercion

### PR DESCRIPTION
**Pull request by isaacrivriv**
fixes #23040

### CODE REVIEW

**Comment by isaacrivriv** [comment]
#build

**Comment by isaacrivriv** [comment]
#link 293230

**Review by pnicolucci — APPROVED** [review]
This looks good, it matches the upstream code fix.

**Comment by isaacrivriv** [comment]
Final J2Sec enabled build ran with only one known issue unrelated to the changes. Merging in

**Pull request merged**
