### PR TITLE
Add quotes to server working directory test

### PR DESCRIPTION
**Pull request by tbitonti**
Ref: Issue #21214.

If this code change is fixing a user-visible bug in previously released code, it MUST
have an associated issue mentioned in the PR text or description. That Issue also
MUST be labelled “release bug”.
https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions

### CODE REVIEW

**Review by hlhoots — APPROVED** [review]
LGTM pending a build on Windows.

**Comment by tbitonti** [comment]
#build

**Review by hlhoots — APPROVED** [review]
Updates look good for env var cleanup.

**Comment by tbitonti** [comment]
#build

**Comment by tbitonti** [comment]
#build

**Comment by tbitonti** [comment]
The personal build has all passing tests.

Running a Windows build, since the problem is specific to windows:

https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_TAf4gOcwEeyVkLDPEXw2dw

**Comment by tbitonti** [comment]
Window tests are passing to a "usual" extent.

**Comment by tbitonti** [comment]
#libby

**Comment by tbitonti** [comment]
#libby

**Pull request merged**
