### PR TITLE
pull request for code updates for olgh5667 jwt thread perf issue

### PR DESCRIPTION
**Pull request by barbj**

### CODE REVIEW

**Comment by barbj** [comment]
#5667 
#build 
#spawn.fullfat.buckets=com.ibm.ws.security.openidconnect.client_fat,com.ibm.ws.security.jwt_fat.mpjwt,com.ibm.ws.security.social_fat.LibertyOP

**Comment by barbj** [comment]
#5667

**Comment by ayoho** [comment]
Is this pull request still needed?

**Comment by ayoho** [comment]
@barbj Is this pull request needed?

**Comment by ayoho** [comment]
@barbj Checking again - is this PR needed?

**Comment by barbj** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.security.openidconnect.client_fat,com.ibm.ws.security.jwt_fat.mpjwt,com.ibm.ws.security.social_fat.LibertyOP

**Comment by barbj** [comment]
There are FAT failures and I can't deal with it right now.  I deselected 'deletion allowed' on the PB; hopefully it will stick around long enough for me to investigate.

**Comment by barbj** [comment]
#run-libby-bot

**Pull request merged**
