### PR TITLE
Issue #13717: EE 9 EJB in WAR FAT

### PR DESCRIPTION
**Pull request by tkburroughs**
New EJB FAT that covers EJB in WAR scenarios.
Will run for JAva EE 7 & 8 as well as Jakarta 9.

for #13717

### CODE REVIEW

**Comment by tkburroughs** [comment]
#build

**Review by olendvcook — APPROVED** [review]

**Comment by tkburroughs** [comment]
#build

**Comment by tkburroughs** [comment]
#build

**Comment by tkburroughs** [comment]
Added update for new test in .github/test-categores
#libby
#build

**Comment by tkburroughs** [comment]
Fixed a case sensitivity issue in bnd.bnd
#libby
#build

**Pull request merged**
