### PR TITLE
JAX-WS: SOAP response default is set UTF-8

### LINKED ISSUE #27220: JAX-WS: Default encoding for SOAP Response is set to UTF-8
Default encoding for SOAP Response needs to be UTF-8. Otherwise, if encoding is not set explicitly or not provided by a tool's default setting, Liberty was providing ISO_8859_1. With this issue it's changed to UTF-8 like Traditional WAS.

### PR DESCRIPTION
**Pull request by BerksanAtes**
Fixes #27220

### CODE REVIEW

**Comment by BerksanAtes** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.jaxws.2.2.webcontainer_fat,com.ibm.ws.jaxws.2.2.webcontainer_fat_extended,com.ibm.ws.jaxws.cdi_fat,com.ibm.ws.jaxws.clientcontainer_fat,com.ibm.ws.jaxws.ejb_fat,com.ibm.ws.jaxws.X.wsat_fat,io.openliberty.xmlws.4.0.internal_fat,io.openliberty.jaxrs.2.1.jaxws.2.2_fat,io.openliberty.jaxws.global.handler.internal_fat,io.openliberty.jaxws.security_fat,io.openliberty.jaxws.security_fat.1,io.openliberty.jaxws.security_fat.ssl,io.openliberty.jaxws.tools_fat

**Review by sawadood — COMMENTED** [review]
I would leave the old constant ISO88591 and just change the default to new constant UTF8

**Review by sawadood — APPROVED** [review]
looks good!

**Comment by BerksanAtes** [comment]
#run-libby-bot

**Pull request merged**
