### PR TITLE
Revert "Revert 8465 that reverted 8239 "oauth call jwt's jwtdata class""

### PR DESCRIPTION
**Pull request by brutif**
This reverts commit 3c25c35f72bda585f10243c6d605516fbcaf7d98.
The 3465 reversion occurred because initially on 8239  I didn't run the full jwt fats.  I've fixed the small bug in Jwtdata, and added the full fats.

### CODE REVIEW

**Comment by brutif** [comment]
adding the jwt buckets I missed on 8239

#build
#spawn.fullfat.buckets=com.ibm.ws.security.openidconnect.client_fat,com.ibm.ws.security.openidconnect.client_fat.config,com.ibm.ws.security.openidconnect.client_fat.e2e,com.ibm.ws.security.openidconnect.client_fat.jaxrs,com.ibm.ws.security.openidconnect.client_fat.saml,com.ibm.ws.security.openidconnect.client_fat.spnego,com.ibm.ws.security.openidconnect.server_fat,com.ibm.ws.security.openidconnect.server_fat.config,com.ibm.ws.security.openidconnect.server_fat.endpoint.token,com.ibm.ws.security.openidconnect.server_fat.endpoint.userinfo,com.ibm.ws.security.openidconnect.server_fat.feature,com.ibm.ws.security.openidconnect.server_fat.granttype.jwt,com.ibm.ws.security.openidconnect.server_fat.jaxrs,com.ibm.ws.security.openidconnect.server_fat.jaxrs.config,com.ibm.ws.security.openidconnect.server_fat.oauth,com.ibm.ws.security.openidconnect.server_fat.oidc,com.ibm.ws.security.openidconnect.server_fat.saml,com.ibm.ws.security.openidconnect.server_fat.spnego,com.ibm.ws.security.jwt_fat.builder,com.ibm.ws.security.jwt_fat.consumer

**Comment by brutif** [comment]
Execution failed for task ':com.ibm.websphere.javaee.jsf.2.3:audit'.
> Error trying to get audit results

Unrelated build failure, let's try again...

#build
#spawn.fullfat.buckets=com.ibm.ws.security.openidconnect.client_fat,com.ibm.ws.security.openidconnect.client_fat.config,com.ibm.ws.security.openidconnect.client_fat.e2e,com.ibm.ws.security.openidconnect.client_fat.jaxrs,com.ibm.ws.security.openidconnect.client_fat.saml,com.ibm.ws.security.openidconnect.client_fat.spnego,com.ibm.ws.security.openidconnect.server_fat,com.ibm.ws.security.openidconnect.server_fat.config,com.ibm.ws.security.openidconnect.server_fat.endpoint.token,com.ibm.ws.security.openidconnect.server_fat.endpoint.userinfo,com.ibm.ws.security.openidconnect.server_fat.feature,com.ibm.ws.security.openidconnect.server_fat.granttype.jwt,com.ibm.ws.security.openidconnect.server_fat.jaxrs,com.ibm.ws.security.openidconnect.server_fat.jaxrs.config,com.ibm.ws.security.openidconnect.server_fat.oauth,com.ibm.ws.security.openidconnect.server_fat.oidc,com.ibm.ws.security.openidconnect.server_fat.saml,com.ibm.ws.security.openidconnect.server_fat.spnego,com.ibm.ws.security.jwt_fat.builder,com.ibm.ws.security.jwt_fat.consumer

**Comment by tevans78** [comment]
@brutif you may wish to rebase on integration to pick up the newer version of ossindex, the thing that fails in the audit task

**Comment by brutif** [comment]
@tevans78 Thanks Tom

**Comment by andrea-pichler** [comment]
Requested message review completed by L2

**Comment by brutif** [comment]
build was abandoned after running for over 24 hours.  Let's try again...

#build
#spawn.fullfat.buckets=com.ibm.ws.security.openidconnect.client_fat,com.ibm.ws.security.openidconnect.client_fat.config,com.ibm.ws.security.openidconnect.client_fat.e2e,com.ibm.ws.security.openidconnect.client_fat.jaxrs,com.ibm.ws.security.openidconnect.client_fat.saml,com.ibm.ws.security.openidconnect.client_fat.spnego,com.ibm.ws.security.openidconnect.server_fat,com.ibm.ws.security.openidconnect.server_fat.config,com.ibm.ws.security.openidconnect.server_fat.endpoint.token,com.ibm.ws.security.openidconnect.server_fat.endpoint.userinfo,com.ibm.ws.security.openidconnect.server_fat.feature,com.ibm.ws.security.openidconnect.server_fat.granttype.jwt,com.ibm.ws.security.openidconnect.server_fat.jaxrs,com.ibm.ws.security.openidconnect.server_fat.jaxrs.config,com.ibm.ws.security.openidconnect.server_fat.oauth,com.ibm.ws.security.openidconnect.server_fat.oidc,com.ibm.ws.security.openidconnect.server_fat.saml,com.ibm.ws.security.openidconnect.server_fat.spnego,com.ibm.ws.security.jwt_fat.builder,com.ibm.ws.security.jwt_fat.consumer

**Comment by brutif** [comment]
pb is good

**Pull request merged**
