### PR TITLE
Mark crac-1.3 feature as beta

### PR DESCRIPTION
**Pull request by tjwatson**

### CODE REVIEW

**Comment by tjwatson** [comment]
#build

**Comment by tjwatson** [comment]
@cbridgha could you review commit 7f92c4d

The other two commits in this PR are already merged into integration from PR #26014, not sure why the github UI shows otherwise.

**Review by cbridgha — DISMISSED** [review]
Looks good

**Review by cbridgha — DISMISSED** [review]

**Review by cbridgha — APPROVED** [review]

**Comment by tjwatson** [comment]
#libby

**Pull request merged**
