### PR TITLE
Retriable and non-retriable sqlcode list support

### LINKED ISSUE #19226: Support config of SQLExceptions on which to fail or succeed
Follow on to issue #18893 - allowing an administrator to specify the set of SQLException sqlcodes on which to retry or, alternatively, to fail fast.

### PR DESCRIPTION
**Pull request by neilgsyoung**
fixes #19226

### CODE REVIEW

**Comment by neilgsyoung** [comment]
#run-libby-bot

**Comment by neilgsyoung** [comment]
#build

**Comment by neilgsyoung** [comment]
#run-libby-bot

**Review by jonhawkes — APPROVED** [review]

**Comment by neilgsyoung** [comment]
#build

**Pull request merged**
