### PR TITLE
Port cdi wsoc tests

### LINKED ISSUE #12993: Port CDI-Websocket tests from Websocket FAT
Now that CDI-3.0 feature is enabled we want to move over the CDI test with Websocket to test the integration between them and make sure everything works out

### PR DESCRIPTION
**Pull request by isaacrivriv**
fixes #12993

### CODE REVIEW

**Comment by isaacrivriv** [comment]
#build

**Comment by isaacrivriv** [comment]
#build

**Comment by pnicolucci** [comment]
#run-libby-bot

**Comment by isaacrivriv** [comment]
#build

**Comment by isaacrivriv** [comment]
#build

**Comment by isaacrivriv** [comment]
#run-libby-bot

**Pull request merged**
