### PR TITLE
Beta appSecurity-5.0, appAuthentication-3.0, appAuthorization-3.0, and dependent features for issue #22998

### PR DESCRIPTION
**Pull request by teddyjtorres**
For issue #22998

### CODE REVIEW

**Comment by teddyjtorres** [comment]
#build

**Review by emilytee — DISMISSED** [review]

**Review by jhanders34 — CHANGES_REQUESTED** [review]
io.openliberty.connectorsInboundSecurity-2.1 should also move to beta with edition of base.

**Comment by teddyjtorres** [comment]
@jhanders34  I changed io.openliberty.connectorsInboundSecurity-2.1 to beta with edition of base in latest commit per your request. Thanks!

**Comment by teddyjtorres** [comment]
#build

**Review by emilytee — APPROVED** [review]

**Review by jhanders34 — APPROVED** [review]

**Comment by teddyjtorres** [comment]
#libby

**Pull request merged**
