### PR TITLE
Wait for the restored configuration before stopping the test server

### LINKED ISSUE #19577: Build error: NPE when cleaning up DD parsing tests
This is a test error, which shows up as a build error.

The failure occurs when running "DDNonValidTests".  See below.

java.lang.Exception: Errors/warnings were found in server ddmodel_fat logs:
 <br>[12/7/21, 8:07:55:132 PST] 00000027 com.ibm.ws.app.manager.AppMessageHelper                      E CWWKZ0004E: An exception occurred while starting the application Test. The exception message was: java.lang.NullPointerException
	at componenttest.topology.impl.LibertyServer.checkLogsForErrorsAndWarnings(LibertyServer.java:2698)
	at componenttest.topology.impl.LibertyServer.stopServer(LibertyServer.java:2556)
	at componenttest.topology.impl.LibertyServer.stopServer(LibertyServer.java:2445)
	at componenttest.topology.impl.LibertyServer.stopServer(LibertyServer.java:2354)
	at componenttest.topology.impl.LibertyServer.stopServer(LibertyServer.java:2329)
	at com.ibm.ws.javaee.ddmodel.suite.CommonTests.commonTearDown(CommonTests.java:256)
	at com.ibm.ws.javaee.ddmodel.suite.DDNonValidTests.tearDown(DDNonValidTests.java:35)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

### PR DESCRIPTION
**Pull request by tbitonti**
Fix for #19577.

### CODE REVIEW

**Comment by tbitonti** [comment]
#build

**Comment by tbitonti** [comment]
This update is a correction to a FAT test bucket.  No product shippable code was modified.

The update is tested by running FAT tests, as usual.  No new tests are needed.

**Review by hlhoots — APPROVED** [review]
LGTM

**Comment by tbitonti** [comment]
#build

**Review by hlhoots — APPROVED** [review]
LGTM

**Comment by tbitonti** [comment]
#libby

**Comment by tbitonti** [comment]
This update is to a set of FAT tests which fail occasionally because of bugs in the test implementation. The update is tested by rerunning the failing FATs and observing that the failure no longer occurs.
Because the failures are intermittent, whether the fix is complete won't be known for some time after the update is merged.  So far, local testing both reproduced the original problem and seemed to fix the problem with this update.

**Pull request merged**
