### PR TITLE
Fix Jakarta Data tests for Oracle

### PR DESCRIPTION
**Pull request by KyleAure**
Related #25296

### CODE REVIEW

**Comment by KyleAure** [comment]
#build

**Comment by KyleAure** [comment]
SOE Oracle: https://libh-proxy1.fyre.ibm.com/cognitive-dev/pipelineAnalysis.html?pipelineId=3230103e-4d07-4094-bcdf-937c568ebcf6

**Comment by KyleAure** [comment]
RTC (derby): Passed
Pipeline (derby): Failed with 1 known defect (unrelated)
Pipeline (oracle): Failed during jakarta data checkpoint tests (future investigation)

**Review by jmstephensgit — APPROVED** [review]

**Review by njr-11 — APPROVED** [review]
This looks good, thanks!  One minor comment is that everywhere else in for this component we use TODO rather than FIXME for identifying places that we need to revisit. It would probably be best to remain consistent so that a single search can identify all of these.

**Pull request merged**
