### PR TITLE
Add MpTelemetry 2.0 agents tests

### LINKED ISSUE #29068: Test otel Java agent with MpTelemetry 2.0
We have a test for the agent 1.19 and 1.29. We should test it with 2.1.0 to line up with MpTelemetry 2.0

### PR DESCRIPTION
**Pull request by Yas-Franco**
Fixes #29068

### CODE REVIEW

**Comment by Yas-Franco** [comment]
#libby

#build
#spawn.fullfat.buckets=io.openliberty.microprofile.telemetry.1.0.internal.container_fat

**Comment by Yas-Franco** [comment]
#libby

#build
#spawn.fullfat.buckets=io.openliberty.microprofile.telemetry.1.0.internal.container_fat

**Comment by wraschke** [comment]
#libby

#build
#spawn.fullfat.buckets=io.openliberty.microprofile.telemetry.1.0.internal.container_fat

**Review by benjamin-confino — APPROVED** [review]
Only issue I spotted was a comment which can be updated in a followup. Approving

**Pull request merged**
