### PR TITLE
Update Expression Language 5.0 10.1.31

### LINKED ISSUE #29946: Update Expression Language 5.0 API and IMPL version 10.1.31
**Describe the bug**  
A new version of the Tomcat Expression Language API / Implementation is available. Update from the current 10.1.11 version to the latest 10.1.31 version.

**Steps to Reproduce**  
N/A

**Expected behavior**  
N/A

**Diagnostic information:**  
N/A

**Additional context**  
[API](https://repo1.maven.org/maven2/org/apache/tomcat/tomcat-el-api/10.1.31/)
[IMPL](https://repo1.maven.org/maven2/org/apache/tomcat/tomcat-jasper-el/10.1.31/)

### PR DESCRIPTION
**Pull request by pnicolucci**
- [x] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [x] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [x] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

fixes #29946

### CODE REVIEW

**Comment by pnicolucci** [comment]
#build

**Comment by contbld** [comment]
Your personal pipeline request is at https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=0edcf712-0248-447c-9c72-b52569f5e830

Target locations of links might be accessible only to IBM employees.

**Comment by contbld** [comment]
<h3>Code analysis and actions</h3>
DO NOT DELETE THIS COMMENT.

- 5 product code files were changed.

**Comment by contbld** [comment]
https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=0edcf712-0248-447c-9c72-b52569f5e830 completed successfully!

**Comment by pnicolucci** [comment]
#libby #build

**Comment by contbld** [comment]
Your personal pipeline request is at https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=d129150d-bf99-4a35-9720-466874f65625

Target locations of links might be accessible only to IBM employees.

**Comment by contbld** [comment]
Your personal pipeline request is at https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=0fb80d12-4476-4eda-8620-571dbafbc3d0

Target locations of links might be accessible only to IBM employees.

**Comment by contbld** [comment]
<h3>Code analysis and actions</h3>
DO NOT DELETE THIS COMMENT.

- 5 product code files were changed.

**Comment by contbld** [comment]
<h3>Code analysis and actions</h3>
DO NOT DELETE THIS COMMENT.

- 5 product code files were changed.

**Comment by contbld** [comment]
https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=d129150d-bf99-4a35-9720-466874f65625 completed successfully!

**Comment by contbld** [comment]
https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=0fb80d12-4476-4eda-8620-571dbafbc3d0 has errors/failures.

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build ([view Open Liberty Personal Build](https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?pipelineId=cd8d5392-2ed3-4426-8780-dad7098b5953) - :white_check_mark: completed successfully!)

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#libby ([view Open Liberty Delivery Requirements Verification](https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?pipelineId=5b38a718-40d4-4601-a432-55d773476ee4) - :white_check_mark: completed successfully!)

_Note: Target locations of links might be accessible only to IBM employees._

**Review by volosied — APPROVED** [review]
Looks good to me.  I don't see any breaking changes in the Tomcat change log either, just optimizations / performance improvements.

**Pull request merged**
