### PR TITLE
Gate --illegal-access=permit changes

### PR DESCRIPTION
**Pull request by gjwatts**
The `--illegal-access=permit` parameter I added in #15992 was not introduced until Java9, so any builds done at Java 7 or 8 will fail. Reintroduce this parameter with a gate to only allow the value for Java 15+.

### CODE REVIEW

**Comment by gjwatts** [comment]
#build

**Review by wraschke — APPROVED** [review]

**Comment by gjwatts** [comment]
Force push was to rebase to resolve merge conflicts.  No code was changed, but running another build.

**Comment by gjwatts** [comment]
#build #libbybot

**Comment by gjwatts** [comment]
There were 4 unrelated test failures on the build.  Merging.

**Pull request merged**
