### PR TITLE
Add new SIP Container custom properties to the metadata

### LINKED ISSUE #15996: Add new SIP Container custom properties to the metadata

### PR DESCRIPTION
**Pull request by annaguri**
fixes #15996

### CODE REVIEW

**Comment by annaguri** [comment]
#build

**Review by fritze2 — APPROVED** [review]

**Review by TiborBeres — APPROVED** [review]
Looks good

**Comment by annaguri** [comment]
#build

**Comment by annaguri** [comment]
#run-libby-bot

**Pull request merged**
