### PR TITLE
Scanning improvements: filter InHouse Jars and test projects - upgrade dojo version

### PR DESCRIPTION
**Pull request by cbridgha**

### CODE REVIEW

**Comment by cbridgha** [comment]
#build

**Comment by cbridgha** [comment]
#build

**Comment by cbridgha** [comment]
#build

**Comment by cbridgha** [comment]
#build

**Comment by cbridgha** [comment]
#build

**Comment by cbridgha** [comment]
#build

**Review by fritze2 — APPROVED** [review]

**Comment by cbridgha** [comment]
#libby

**Pull request merged**
