### PR TITLE
Build fat test integration passing

### PR DESCRIPTION
**Pull request by ibrakadabra70**

### CODE REVIEW

**Comment by ibrakadabra70** [comment]
#build

**Comment by ibrakadabra70** [comment]
#build

**Comment by ibrakadabra70** [comment]
#build

**Comment by ibrakadabra70** [comment]
#build

**Comment by ibrakadabra70** [comment]
https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_h1H-sOOZEemM--BPo4KzaA

**Comment by bensonlatibm** [comment]
FAT failure is in the com.ibm.ws.javaee.70_fat which is unrelated to these changes.

**Pull request merged**
