### PR TITLE
refactor: start using postgresql an mongodb from aws

### PR DESCRIPTION
**Pull request by KyleAure**
- [x] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [x] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [x] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

### CODE REVIEW

**Comment by KyleAure** [comment]
#build - personal build check interoperability with WebSphere Liberty prior to review. ([view Open Liberty Personal Build](https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?pipelineId=9f142b5c-1314-42c2-be64-628810dd7fd7) - :x: completed with errors/failures.)

_Note: Target locations of links might be accessible only to IBM employees._

**Comment by KyleAure** [comment]
Hold off on this until updates to WebSphere Liberty have caught up with Open Liberty.

**Comment by KyleAure** [comment]
#build ([view Open Liberty Personal Build](https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?pipelineId=03925f7a-7fec-4a37-994b-8cea7cee7cf2) - :x: completed with errors/failures.)

_Note: Target locations of links might be accessible only to IBM employees._

**Comment by KyleAure** [comment]
PostgreSQL SOE: https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?pipelineId=f7964755-79f5-465d-be05-aae13fb725be

Note: Target locations of links might be accessible only to IBM employees.

**Comment by KyleAure** [comment]
Pipeline: failed with 1 known z/OS defect
PostgreSQL SOE: failed with 2 known JPA defects, and 1 known Data defect

Ready to merge once integration branch is unlocked.

**Review by mswatosh — APPROVED** [review]

**Pull request merged**
