### PR TITLE
Issue #16452: Remove SharedServer from VHServerHttpUnit.java

### LINKED ISSUE #16452: Remove SharedServer from Servlet 31 FAT VHServerHttpUnit.java

### PR DESCRIPTION
**Pull request by pnicolucci**
fixes #16452

### CODE REVIEW

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Review by isaacrivriv — APPROVED** [review]
Looks good to me thanks!

**Comment by pnicolucci** [comment]
#run-libby-bot

**Pull request merged**
