### PR TITLE
Update non Jakarta 9 features to have eeCompatible

### PR DESCRIPTION
**Pull request by jhanders34**
- Update jsonp-1.0, jaxb-2.x, and springBoot-x.y features to have eeCompatible so that they do not try to start with EE 9 features.

### CODE REVIEW

**Comment by jhanders34** [comment]
#build

**Comment by jhanders34** [comment]
The test failures in the personal build indicate that @jvanhill 's PR to fix federatedRegistry for story #16642 needs to be merged in before this PR can be merged in.  The point of this PR was to be able to show that story #16642 was necessary because federatedRegistry was working with Jakarta EE 9 features, but it shouldn't be because xmlBinding-3.0 is the EE9 feature that should be used and not JAXB-2.2.  As part of that work I audited the other Java / Jakarta EE public features to see if there were other ones missing eeCompatible and found the others listed here.  I added SpringBoot features since they will not work with EE9 until Spring Boot supports Jakarta EE 9 with Spring Boot 3.0.

**Review by nmittles — APPROVED** [review]
Reviewed JSON-P-1.0 changes.

**Review by tjwatson — APPROVED** [review]

**Review by tevans78 — APPROVED** [review]

**Review by BerksanAtes — APPROVED** [review]
Looks good

**Comment by jhanders34** [comment]
#libby
#build

**Comment by jhanders34** [comment]
#libby
#build

**Comment by jhanders34** [comment]
#libby #build

**Review by jvanhill — APPROVED** [review]

**Pull request merged**
