### PR TITLE
Add compilePersonalRTC.properties

### PR DESCRIPTION
**Pull request by fritze2**
- Add compilePersonalRTC.properties is used by personal builds launched in RTC and is imported by `.ci-orchestrator/rtcbuild.yml`.

The repository uses these existing properties files:
- compilePersonal.properties is used by personal builds launched via CI Orchestrator and is imported by `.ci-orchestrator/personalbuild.yml`.
- compile.properties is for common properties and is used by all builds launched via CI Orchestrator.

### CODE REVIEW

**Comment by fritze2** [comment]
#pb

**Review by wraschke — DISMISSED** [review]
Approved. But it would be really, really helpful to add documentation at top explaining the particular need for each compile*.properties file. This PR introduces a third one.

And is the plain compile.properties file no longer needed?

**Comment by fritze2** [comment]
#pb

**Comment by fritze2** [comment]
> Approved. But it would be really, really helpful to add documentation at top explaining the particular need for each compile*.properties file. This PR introduces a third one.
> 
> And is the plain compile.properties file no longer needed?

No, compile.properties is still needed by the newer personal builds and other types like release, continuous and platforms. I added to the description that compile.properties is a file containing common properties for builds, compilePersonal.properties is for personal builds that do not run the original RTC build, and compilePersonalRTC.properties is a new file for personal builds that only run the original RTC build.

**Comment by wraschke** [comment]
#pbbeta

**Comment by wraschke** [comment]
I cancelled the PB beta pipeline because the problems are due to the same one that Ethan is fixing in the PR changes detector microservice.

**Comment by fritze2** [comment]
#pb@dev

**Comment by fritze2** [comment]
#pbbeta@dev

**Comment by fritze2** [comment]
#pb Would this do it?

**Comment by fritze2** [comment]
#pb@dev
spawn.fullfat.buckets=com.ibm.ws.jndi.iiop_fat

**Comment by fritze2** [comment]
#pbbeta@dev
spawn.fullfat.buckets=com.ibm.ws.jndi.iiop_fat

**Comment by fritze2** [comment]
Pipelines failed to reach libfsfe06.hursley.ibm.com because that server has an outage, so I switched to using the backup frontend libfsfe04.hursley.ibm.com.

#pb@dev
spawn.fullfat.buckets=com.ibm.ws.jndi.iiop_fat

**Comment by fritze2** [comment]
#pbbeta@dev
spawn.fullfat.buckets=com.ibm.ws.jndi.iiop_fat

**Comment by fritze2** [comment]
#pbbeta@dev
spawn.fullfat.buckets=com.ibm.ws.jndi.iiop_fat

**Comment by fritze2** [comment]
#libby-bot

**Comment by fritze2** [comment]
#libbybot

**Comment by wraschke** [comment]
https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=ece18544-f09f-4109-8060-7185a512a894 has 91236
 tests that ran, which is within the range of other pipelines and regular personal builds. There are failures in FATs that need addressing from an Orchestrator POV probably, but we will work on those separately.

I hope the reference to libfsfe04 will not be a problem long term.

**Review by wraschke — APPROVED** [review]

**Comment by wraschke** [comment]
I'm overriding the copyright header check because the latency problem we're experiencing is not triggering LibbyBot to respond.

**Comment by fritze2** [comment]
#pbbeta

**Pull request merged**
