### PR TITLE
Removed feature files and projects related to mpMetrics-2.1

### LINKED ISSUE #9666: Remove references to mpMetrics-2.1
Remove references to mpMetrics-2.1 as it will never be released

### PR DESCRIPTION
**Pull request by Yushan-Lin**
Fixes #9666

### CODE REVIEW

**Comment by Yushan-Lin** [comment]
#build

**Comment by jantley-ibm** [comment]
@Yushan-Lin no ID review needed; would you like me to go ahead and merge?

**Comment by tevans78** [comment]
@jantley-ibm 

> @Yushan-Lin no ID review needed; would you like me to go ahead and merge?

Looks like the personal build was abandoned. Need a good PB before merging.

**Comment by Channyboy** [comment]
I think it's waiting for https://github.ibm.com/was-liberty/WS-CD-Open/pull/19252 to be Merged.
Which in turn is waiting for the `mpMetrics-2.2` code to still be migrated to master.

**Comment by tevans78** [comment]
#build

**Comment by tevans78** [comment]
Ignore that build just above, it will fail. This one is being run against CL integration and will be good enough as a PB because the combined integration build is currently enabled.
https://wasrtc.hursley.ibm.com:9443/jazz/resource/itemOid/com.ibm.team.build.BuildResult/_72Jk8AU1EeqfUosHDHrRQQ

**Comment by tevans78** [comment]
#build

**Comment by Channyboy** [comment]
The error from the latest build does not reflect the changes made in this PR.

**Pull request merged**
