### PR TITLE
JAX-WS: Issue accessing ibm-ws-bnd.xml file in a test

### LINKED ISSUE #27353: JAX-WS: Issue accessing ibm-ws-bnd.xml file in a test
In one test ibm-ws-bnd.xml file copy operation doesn't finish in time resulting ParseException. 
`ibm-ws-bnd.xml deployment descriptor on line -1. The error message was: java.net.MalformedURLException)`
Suspected server.fileExistsInLibertyServerRoot might be causing more IO operation interfering with OS copy operation. 

To prevent conflicting IO operation test suite is split to two. One is using ibm-ws-bnd.xml file other one does not.

### PR DESCRIPTION
**Pull request by BerksanAtes**
Fixes #27353

### CODE REVIEW

**Comment by BerksanAtes** [comment]
#build

**Comment by BerksanAtes** [comment]
#build

**Review by neuwerk — APPROVED** [review]
LGTM!

**Comment by BerksanAtes** [comment]
#run-libby-bot

**Review by sawadood — APPROVED** [review]
Looks good

**Pull request merged**
