### PR TITLE
Remove MP OpenAPI endpoint customisation beta guards

### LINKED ISSUE #26427: Remove OpenAPI Configuration Beta guards
Remove the beta guards for the OpenAPI endpoint configuration.

building on top of https://github.com/OpenLiberty/open-liberty/pull/26112/files - remove the beta guard segments from the code

### PR DESCRIPTION
**Pull request by ryan-storey**
Fixes https://github.com/OpenLiberty/open-liberty/issues/26427

### CODE REVIEW

**Comment by ryan-storey** [comment]
#build

**Comment by abutch3r** [comment]
#build

**Comment by abutch3r** [comment]
#libby
#build

**Comment by abutch3r** [comment]
#build

**Review by abutch3r — APPROVED** [review]

**Pull request merged**
