### PR TITLE
Issue #81 - Add FATs to test Fault Tolerance configuration

### PR DESCRIPTION
**Pull request by neilgsyoung**
Improve FAT coverage of Fault Tolerance function by adding tests for Fault Tolerance configuration.

With refererence to issue #81, this PR adds test coverage for...

Retry config
CircuitBreaker config
Bulkhead config
Timeout config

### CODE REVIEW

**Comment by neilgsyoung** [comment]
fixes #81

**Comment by neilgsyoung** [comment]
#build

**Comment by neilgsyoung** [comment]
#build

**Comment by Azquelt** [comment]
Please squash the changes before merging

**Comment by Azquelt** [comment]
Failure in first personal build is known problem #214

**Comment by neilgsyoung** [comment]
squashed commits.

**Pull request merged**
