### PR TITLE
update wsscxf fat for java2sec

### PR DESCRIPTION
**Pull request by meiaus**
update com.ibm.ws.wssecurity_fat.wsscxf with java2sec

### CODE REVIEW

**Comment by meiaus** [comment]
#run-libby-bot

**Comment by meiaus** [comment]
#build
#global.debug.java2.sec=true

**Comment by meiaus** [comment]
The above PB https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_sTpyZvGZEeu3WKcyevrZqg&tab=com.ibm.team.build.web.ui.internal.editors.result.overview.OverviewPage is complete with errors from other FAT:

wsscxf fat passed:

image

and other FAT failed,  which is out of concern from this PR:

image

But a new PB will be submitted to only specify the updated FAT to run.

**Comment by meiaus** [comment]
The latest PB (EBC meiaus-18012-20210731-1213): https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_Cw2VwPIqEeuj_9vf1o2UsA&tab=com.ibm.team.build.web.ui.internal.editors.result.overview.OverviewPage is complete with error from other FAT:

image


the specified FAT passed:

image

**Comment by meiaus** [comment]
The PR is ready for review and then to be merged.

**Comment by meiaus** [comment]
Note:
Initial PB were submitted with the properties `global.debug.java2.sec`, which didn't enable java2 sec (per server messages.log).
The latest PB with `global.java2.sec` enabled java2 security as expected.

**Comment by meiaus** [comment]
#run-libby-bot

**Review by jimmy1wu — APPROVED** [review]

**Comment by meiaus** [comment]
The failed result from the latest PB was from other FAT, which is out of concern before merging the PR.

image


image

**Pull request merged**
