### PR TITLE
Issue #28247: Add versionless features to packaging

### PR DESCRIPTION
**Pull request by hlhoots**
#build 

Do not merge!

### CODE REVIEW

**Comment by hlhoots** [comment]
Build was good.  Installable package look to contain the versionless features.  This can't be merged until versionless goes GA.

**Review by cbridgha — DISMISSED** [review]
Looks good

**Comment by hlhoots** [comment]
#build 

jakee10 had a typo. rebuild

**Comment by hlhoots** [comment]
typo.  rebuild.

#build

**Comment by hlhoots** [comment]
Delivered via another PR

**Pull request closed without merging**
