### PR TITLE
Revert "Enable jandex for cdi extenstion archives"

### PR DESCRIPTION
**Pull request by jimblye**

### CODE REVIEW

**Comment by jimblye** [comment]
#build

**Comment by Channyboy** [comment]
Will this be merged soon?

**Comment by jimblye** [comment]
#build

**Comment by jimblye** [comment]
IF it is ok to merge without a green build, then it can be merged now.  The test errors in the build do not look related to the changes.   I have submitted another build, but I think it is safe to merge.

**Comment by jimblye** [comment]
#build

**Comment by jimblye** [comment]
Different errors with the latest build.   It usually takes at least 3 builds to get a clean one.

**Pull request merged**
