### PR TITLE
feat: fully switch artifactory from remote to local repository

### PR DESCRIPTION
**Pull request by KyleAure**
- [x] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [x] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [x] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

### CODE REVIEW

**Comment by KyleAure** [comment]
#build

**Comment by websterc87** [comment]
#build

**Review by rickettmwork — APPROVED** [review]

**Comment by rickettmwork** [comment]
Code looks right, but PB failure looks like it is likely caused by these changes

**Comment by KyleAure** [comment]
Pipeline had 4 failures:
- Two were UI bucket connection failures (intermittent and common)
- Concurrency test failure (intermittent and recently occuring but unrelated)
- One Testcontainer issue in bucket io.openliberty.microprofile.telemetry.1.0.internal.container_fat, but has been occuring for more than 5 days.  I double checked and verified that the issue is unrelated to my change. 

Ready to merge.

**Comment by mhldr** [comment]
After discussion with Mike and Chris this is needed to solve docker issues - particularly JBoss ones and the PBs are fine so I merged despite the streams being locked.

**Pull request merged**
