### PR TITLE
Replace DSA keys

### LINKED ISSUE #16194: com.ibm.ws.security.oauth.oidc_fat.common has keystore using SHA1withDSA certificate
Client certificate tests are failing as JREs no longer consider the SHA1withDSA signing algorithm secure. As a temporary measure, to pass tests I added code in `com.ibm.ws.security.oauth_oidc.fat.commonTest.CommonTest#setupSSLClient(boolean)` to permit certificates with insecure signing algorithms. I believe the errors were seen in either the OIDC client or server FAT tests.

The certificate should be regenerated, the keystore and any truststores should be updated and the temporary workaround should  be removed.

```
keytool -v -list -keystore com.ibm.ws.security.oidc.server_fat.oidc/build/libs/autoFVT/securitykeys/commonLDAPUser1.jks -storepass security
Keystore type: JKS
Keystore provider: SUN

Your keystore contains 1 entry

Alias name: ldapuser1
Creation date: Nov 29, 2011
Entry type: PrivateKeyEntry
Certificate chain length: 1
Certificate[1]:
Owner: CN=LDAPUser1, O=IBM, C=US
Issuer: CN=LDAPUser1, O=IBM, C=US
Serial number: 4ed56454
Valid from: Tue Nov 29 17:01:40 CST 2011 until: Fri Nov 26 17:01:40 CST 2021
Certificate fingerprints:
	 SHA1: C0:11:47:C4:7A:D6:E3:E7:97:E8:CF:6C:82:4C:35:07:CD:E2:72:6B
	 SHA256: 73:DA:F7:BD:5B:57:FD:2C:E2:B5:F5:A5:E8:13:8E:D1:A7:48:46:99:E5:47:30:F5:FE:43:B3:2E:32:F7:29:78
Signature algorithm name: SHA1withDSA
Subject Public Key Algorithm: 1024-bit DSA key
Version: 3
```

### PR DESCRIPTION
**Pull request by c00crane**
Replace dsa keys used by security FATs.

### CODE REVIEW

**Comment by c00crane** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.security.jwt_fat.builder,com.ibm.ws.security.jwt_fat.consumer,com.ibm.ws.security.jwtsso_fat,com.ibm.ws.security.mp.jwt.1.1_fat,com.ibm.ws.security.mp.jwt.1.2_fat,com.ibm.ws.security.mp.jwt_fat_tck,com.ibm.ws.security.oauth_fat,com.ibm.ws.security.oidc.client_fat,com.ibm.ws.security.oidc.server_fat.oidc,com.ibm.ws.security.saml.sso_fat,com.ibm.ws.security.saml.sso_fat.2,com.ibm.ws.security.saml.sso_fat.3,com.ibm.ws.security.saml.sso_fat.config,com.ibm.ws.security.saml.sso_fat.config.mapToUserRegistry,com.ibm.ws.security.saml.sso_fat.endpoint.samlmetadata,com.ibm.ws.security.saml.sso_fat.jaxrs,com.ibm.ws.security.saml.sso_fat.jaxrs.config,com.ibm.ws.security.saml.sso_fat.logout,com.ibm.ws.security.saml.sso_fat.logout.IDP_initiated,com.ibm.ws.security.saml.sso_fat.logout.httpServletRequest,com.ibm.ws.security.saml.sso_fat.logout.ibm_security_logout,com.ibm.ws.security.social_fat,com.ibm.ws.security.social_fat.LibertyOP,com.ibm.ws.security.social_fat.oidcCertification,com.ibm.ws.wssecurity_fat.wsscxf,com.ibm.ws.wssecurity_fat.wsscxf.saml,com.ibm.ws.wssecurity_fat.wsscxf.saml.2

**Comment by c00crane** [comment]
kicked off a build - expecting lots of failures - too many projects to try to run locally (and have it complete in less than a day)

**Review by ayoho — APPROVED** [review]

**Comment by c00crane** [comment]
#run-libby-bot

**Comment by c00crane** [comment]
#run-libby-bot
#build
#spawn.fullfat.buckets=com.ibm.ws.security.jwt_fat.builder,com.ibm.ws.security.jwt_fat.consumer,com.ibm.ws.security.jwtsso_fat,com.ibm.ws.security.mp.jwt.1.1_fat,com.ibm.ws.security.mp.jwt.1.2_fat,com.ibm.ws.security.mp.jwt_fat_tck,com.ibm.ws.security.oauth_fat,com.ibm.ws.security.oidc.client_fat,com.ibm.ws.security.oidc.server_fat.oidc,com.ibm.ws.security.saml.sso_fat,com.ibm.ws.security.saml.sso_fat.2,com.ibm.ws.security.saml.sso_fat.3,com.ibm.ws.security.saml.sso_fat.config,com.ibm.ws.security.saml.sso_fat.config.mapToUserRegistry,com.ibm.ws.security.saml.sso_fat.endpoint.samlmetadata,com.ibm.ws.security.saml.sso_fat.jaxrs,com.ibm.ws.security.saml.sso_fat.jaxrs.config,com.ibm.ws.security.saml.sso_fat.logout,com.ibm.ws.security.saml.sso_fat.logout.IDP_initiated,com.ibm.ws.security.saml.sso_fat.logout.httpServletRequest,com.ibm.ws.security.saml.sso_fat.logout.ibm_security_logout,com.ibm.ws.security.social_fat,com.ibm.ws.security.social_fat.LibertyOP,com.ibm.ws.security.social_fat.oidcCertification,com.ibm.ws.wssecurity_fat.wsscxf,com.ibm.ws.wssecurity_fat.wsscxf.saml,com.ibm.ws.wssecurity_fat.wsscxf.saml.2,com.ibm.ws.security.oidc.client_fat.jaxrs

**Comment by c00crane** [comment]
One more build with Andy's changes included (fixes a problem in bnd.bnd) 
https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_hK0WML4nEeu5V8GZL3dwAw

**Comment by c00crane** [comment]
#run-libby-bot

**Comment by c00crane** [comment]
The overall framework blew up again (downloads) - has nothing to do with the test changes - just need to see good results from the client jaxrs project (due to a collision between these and Andy's changes...)
#build
#spawn.fullfat.buckets=com.ibm.ws.security.oidc.client_fat.jaxrs

**Comment by c00crane** [comment]
#build

**Comment by c00crane** [comment]
#run-libby-bot
#build

**Pull request merged**
