### PR TITLE
Issue #20057: Rename the JCache configuration attributes to remove th…

### LINKED ISSUE #20057: SEC 380: Remove the "J" from distributed cache / JCache configuration elements
Rename the distributed cache / JCache configuration elements so they no longer have "JCache" in them and instead use only "Cache".

- jCachingProvider to cachingProvider
- jCacheManager to cacheManager
- jCacheManager->jCachingProviderRef to cacheManager->cachingProviderRef
- jCache to cache
- jCache->jCacheManagerRef to cache->cacheManagerRef
- authCache->jCacheRef to authCache->cacheRef
- webAppSecurity->loggedOutCookieJCacheRef to webAppSecurity->loggedOutCookieCacheRef

### PR DESCRIPTION
**Pull request by jvanhill**
…e letter J from them.

fixes #20057

### CODE REVIEW

**Comment by jvanhill** [comment]
#build

**Comment by jvanhill** [comment]
#libby
#build

**Comment by jvanhill** [comment]
#build

**Comment by jvanhill** [comment]
The only build failures are known issues that were auto-triaged by the cognitive build systems.

**Comment by jvanhill** [comment]
Waiting for the streams to unlock to merge.

**Review by helyarp — COMMENTED** [review]
Looks good!

**Review by kristip17 — APPROVED** [review]

**Pull request merged**
