### PR TITLE
mapped superclass

### PR DESCRIPTION
**Pull request by njr-11**
Experiment with JNoSQL MappedSuperclass and additional paginated types.

### CODE REVIEW

**Comment by njr-11** [comment]
#build

**Comment by njr-11** [comment]
#build
#run-libby-bot

**Comment by njr-11** [comment]
#build
#run-libby-bot

**Review by mswatosh — APPROVED** [review]

**Comment by njr-11** [comment]
build has 1 failure which is a pre-existing issue reported by an unrelated test bucket

**Pull request merged**
