### PR TITLE
Issue #21817: Use jar for classpath on zos

### PR DESCRIPTION
**Pull request by tspewak**
Use jar for classpath so _fat tests from open-liberty can run on z/OS systems using JAVA 11.

### CODE REVIEW

**Comment by tspewak** [comment]
fixes #21817

#build

**Comment by tspewak** [comment]
I did a rebuid of the child on this build specifying for it to run on build engine chaso022. chaos022 has java 11. the specified tests passed.                 
   https://wasrtc.hursley.ibm.com:9443/jazz/resource/itemOid/com.ibm.team.build.BuildResult/_iMb7MAkyEe2D6LzgSzSNOg

**Comment by tspewak** [comment]
#21408

**Comment by tspewak** [comment]
#build

**Review by ginnick — APPROVED** [review]
Looks fine to me...Couldn't look at any builds that are linked...deleted?

**Comment by tspewak** [comment]
I requested one again last week so they would be there for the review but those got cleaned up as well. The first one was successful the last one had a test that hit a known error.

**Pull request merged**
