### PR TITLE
Add JDBC Checkpoint Batch test

### PR DESCRIPTION
**Pull request by SmithaSubbarao**
- [x] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [x] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [x] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

### CODE REVIEW

**Comment by SmithaSubbarao** [comment]
#build

**Comment by SmithaSubbarao** [comment]
#build

**Comment by SmithaSubbarao** [comment]
> https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=35682db9-b1bc-4836-8676-306b07104a96 has errors/failures.

Need to access the errors before the copyright libby build

**Comment by tjwatson** [comment]
> > https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=35682db9-b1bc-4836-8676-306b07104a96 has errors/failures.
> 
> Need to access the errors before the copyright libby build

This seems to be infrastructure errors and nothing to do with your PR

**Comment by SmithaSubbarao** [comment]
> > > https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=35682db9-b1bc-4836-8676-306b07104a96 has errors/failures.
> > 
> > 
> > Need to access the errors before the copyright libby build
> 
> This seems to be infrastructure errors and nothing to do with your PR

Sounds good, I'll proceed with a libby build now. Thank you Tom!

**Comment by SmithaSubbarao** [comment]
#libby

**Comment by tjwatson** [comment]
> Sounds good, I'll proceed with a libby build now. Thank you Tom!

That is fine, but you need to do another build to get the tests to run.  I'll do that here:

#build

**Comment by SmithaSubbarao** [comment]
#build

**Comment by SmithaSubbarao** [comment]
> Your personal pipeline request is at https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=39e326c9-ae39-41df-9246-f9a7ade25762
> 
> Target locations of links might be accessible only to IBM employees.

The pipeline analysis link here is inaccessible due to an issue with the pipelines: https://ibm-cloud.slack.com/archives/C30NGUQ9E/p1729190468239069. This might be holding the build tests until it's fixed... ^

**Comment by SmithaSubbarao** [comment]
#build

**Comment by tjwatson** [comment]
#build

**Review by tjwatson — APPROVED** [review]
LGTM

**Pull request merged**
