### PR TITLE
Update xercesImpl to 2.12.1

### PR DESCRIPTION
**Pull request by tevans78**
At the moment xercesImpl is only used in tests but want to be consistent about which version we use so switching to a bundle.

### CODE REVIEW

**Comment by tevans78** [comment]
#build

**Review by cbridgha — APPROVED** [review]
Assuming build goes well - looks good

**Comment by tevans78** [comment]
#build

**Comment by tevans78** [comment]
#build

**Comment by tevans78** [comment]
#build

**Comment by tevans78** [comment]
One failure in CollectiveRegistrationMBeanTest was caused by a javacore in com.ibm.ws.collective.repository.fat.controller ... very unlikely to be related to this change

**Comment by tevans78** [comment]
#run-libby-bot

**Review by cbridgha — CHANGES_REQUESTED** [review]
Need to add these lines to new test bundles in bnd...   test.project: true
publish.wlp.jar.disabled: true

**Comment by tevans78** [comment]
#build

**Review by cbridgha — APPROVED** [review]
LGTM

**Comment by tevans78** [comment]
#run-libby-bot

**Comment by wraschke** [comment]
This PR must be reverted.

This causes build break in com.ibm.ws.security.fat.common unittests with NoClassDefFoundErrors like

```
java.lang.NoClassDefFoundError: org.apache.xml.utils.PrefixResolver
	at java.base/java.lang.J9VMInternals.prepareClassImpl(Native Method)
	at java.base/java.lang.J9VMInternals.prepare(J9VMInternals.java:340)
	at java.base/java.lang.Class.getMethodHelper(Class.java:1452)
	at java.base/java.lang.Class.getMethod(Class.java:1395)
	at org.jmock.lib.legacy.ClassImposteriser.toStringMethodIsFinal(ClassImposteriser.java:75)
	at org.jmock.lib.legacy.ClassImposteriser.imposterise(ClassImposteriser.java:59)
	at org.jmock.Mockery.mock(Mockery.java:139)
	at org.jmock.Mockery.mock(Mockery.java:120)
	at com.ibm.ws.security.fat.common.expectations.CommonSpecificExpectationTest.<init>(CommonSpecificExpectationTest.java:30)

```

Please see https://ibm-cloud.slack.com/archives/C30NGUQ9E/p1633380106417400 for more details.

**Pull request merged**
