### PR TITLE
installUtility/featureUtility remove resolveAutoFeatures

### LINKED ISSUE #21644: installUtility/featureUtility installs more features than it should
Installing `webProfile-8.0` feature installs both `websocket-1.0` and `websocket-1.1`, when only `websocket-1.1` should be installed. 

Also installing `audit-1.0` feature installs `cdi-2.0` when it shouldn't according to the IBM doc. 

This happened because we called resolve() api again with the resolved features including the auto-features. I believe there was a bug in the resolver where it didn't return the auto-features way back then, but it looks like the resolver is fixed now and we are resolving too much.

### PR DESCRIPTION
**Pull request by jjiwooLim**
Fixes  #21644

### CODE REVIEW

**Comment by jjiwooLim** [comment]
#build

**Comment by jjiwooLim** [comment]
#build

**Review by bensonlatibm — APPROVED** [review]
lgtm!

**Comment by jjiwooLim** [comment]
#libby-bot

**Pull request merged**
