### PR TITLE
Retain lease on recovery failure paths

### LINKED ISSUE #16784: Delete lease for Tx recovery logs when recovery is clean
The current implementation will delete the lease in circumstances where tx recovery processing has failed. This disallows any future attempt to peer recover the logs.

### PR DESCRIPTION
**Pull request by neilgsyoung**
fixes #16784

### CODE REVIEW

**Review by jonhawkes — APPROVED** [review]

**Comment by neilgsyoung** [comment]
#build

**Comment by neilgsyoung** [comment]
#run-libby-bot

**Comment by neilgsyoung** [comment]
#build

**Comment by neilgsyoung** [comment]
#build

**Comment by neilgsyoung** [comment]
#run-libby-bot

**Comment by neilgsyoung** [comment]
#build

**Pull request merged**
