### PR TITLE
Issue 15237: Clear WIM Info from the Audit Manager thread

### LINKED ISSUE #15237: Clear federated repository specific information from AuditManager thread
During automated testing, some (negative) test requests came in on threads already populated with audit info and picked up stale realm and repositoryID information. This information is only for logging the Audit record (for example, in audit.log) and is not used for authentication or authorization. This would affect the realm or repository ID listed in the audit record for cases where the user or group was not found in an repository and the previous realm or repository ID could be used in the audit record (for example, EntityNotFound type scenarios).

Example audit log attributes:
```
"realm": "LDAPRealmFed"
"repositoryId": "com.ibm.ws.security.registry.ldap.config[ldap1]"
```
versus
```
"realm":"realm not matched"
"repositoryId": "repository not matched"
```

The fix is to clear the federated repository specific information from the AuditManager's threadLocal when leaving ProfileManager.

### PR DESCRIPTION
**Pull request by kristip17**
Fixes #15237 

Did not add a new test for this given the randomness of the occurrence.

### CODE REVIEW

**Comment by kristip17** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.security.wim.audit_fat

**Comment by kristip17** [comment]
Unit test in OpenLiberty CI is known issue. PB ran successfully.

**Comment by kristip17** [comment]
Push after commit was to remove changes to space formatting that I didn't want to merge.

**Comment by kristip17** [comment]
#libbybot

**Review by jvanhill — APPROVED** [review]

**Pull request merged**
