### PR TITLE
25149 - allow for directories to be used for includes

### PR DESCRIPTION
**Pull request by rsherget**
#25149 

This change will allow for directories to be used in the location portion of the includes configuration tag as specified in the below documentation. 

https://openliberty.io/docs/latest/reference/config/include.html

Previously, it would go through all the include locations and add the valid files (valid meaning either an existing file or a remote location like a link) to the configuration. If a directory was specified, however, then it wouldn't be added as it wasn't a file or link.

What changed is now when it looks through all the paths if one is a directory location as opposed to a file or remote location then it goes through all files within that directory and adds them.

### CODE REVIEW

**Comment by rsherget** [comment]
#build

**Review by tbitonti — DISMISSED** [review]
General: Update the copyright statements to 2023.

Specific: In XMLConfigParser:

The added code can use some updates.  How about:

```
            if (includeResource != null) {
                if ( !includeResource.exists() ) {
                    if (optionalImport) {
                        Tr.warning(tc, "warn.cannot.resolve.optional.include", resolvePath(location));
                        configuration = null;
                    } else {
                        logError("error.cannot.read.location", resolvePath(location));
                        throw new ConfigParserTolerableException();
                    }

                } else {
                    // FILE, DIRECTORY, REMOTE

                    if ( !includeResource.isType(WsResource.Type.DIRECTORY) ) {
                        includes.add(includeResource);

                        Object resourceParm = ( includeResource.isType(WsResource.Type.FILE)
                                                ? includeResource.asFile()
                                                : includeResource.toExternalURI() );
                        Tr.audit(tc, "audit.include.being.processed", resourceParm);

                        parseIncludeConfiguration(includeResource, configuration, mergeBehavior);

                    } else { 
                        List<String> alphabeticalChildren = new ArrayList<String>();
                        Iterator<String> children = includeResource.getChildren();
                        while ( children.hasNext() ) {
                            alphabeticalChildren.add( children.next() );
                        }
                        Collections.sort(alphabeticalChildren);

                        for ( String child : alphabeticalChildren ) {
                            parseIncludeDir(parser, docLocation, child, includes, configuration);
                        }
                    }
                }
            }
```
I removed a 'return', not sure if that is handled now with the cascading if-else blocks.

**Comment by rsherget** [comment]
#build

**Comment by rsherget** [comment]
#build

**Comment by rsherget** [comment]
#build

**Comment by rsherget** [comment]
#libby

**Review by hlhoots — APPROVED** [review]
LGTM

**Pull request merged**
