### PR TITLE
Jsf22 flows tests ee10

### PR DESCRIPTION
**Pull request by pnicolucci**
for #22369

### CODE REVIEW

**Comment by pnicolucci** [comment]
#libby-build

**Comment by pnicolucci** [comment]
Java 17 build: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_VY66EGtWEe2VEtMj7GKy_A

**Comment by pnicolucci** [comment]
#libby-build

**Comment by wraschke** [comment]
#build

**Comment by pnicolucci** [comment]
Java 17 build was successful

**Review by isaacrivriv — APPROVED** [review]
Looks good to me, thanks!

**Review by volosied — APPROVED** [review]

**Pull request merged**
