### PR TITLE
Extra debug 3. Testing infrastructure or JDK is somehow calling COH twice in the same run, need to find out where.. and how

### PR DESCRIPTION
**Pull request by Channyboy**
#build

### CODE REVIEW

**Comment by Channyboy** [comment]
For #17768

**Comment by Channyboy** [comment]
#build

**Comment by Channyboy** [comment]
Unrelated failures, but will rebuild: #build

**Comment by Channyboy** [comment]
#build

**Review by pgunapal — APPROVED** [review]
LGTM

**Comment by Channyboy** [comment]
#build

**Comment by Channyboy** [comment]
#build

**Comment by Channyboy** [comment]
#build

**Comment by Channyboy** [comment]
UI failures not related to this PR.

**Pull request merged**
