### PR TITLE
Fix CNFEs when running com.ibm.ws.security.oidc.client_fat.spnego and…

### PR DESCRIPTION
**Pull request by jvanhill**
… com.ibm.ws.security.oidc.server_fat.spnego FATs.

### CODE REVIEW

**Comment by jvanhill** [comment]
Build from WS-CD-Open:

https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_FrIjQDwxEeygsrM6ShizkA

**Comment by jvanhill** [comment]
Respun build:

https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_0vMBEDyUEeygsrM6ShizkA

**Comment by jvanhill** [comment]
#build

**Comment by jvanhill** [comment]
Cancelled previous build. Respun with the following property changes:

- git.clone.checkout.branch=25290-RemoveSpnegoFats
- git.clone.repository.username=jlvanhil

https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_5P7nIF9sEeySV8PQupfSfg

**Comment by jvanhill** [comment]
Respun the previous build since the server tests didn't run completely.

https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_fnaNMGAOEeySV8PQupfSfg

**Comment by jvanhill** [comment]
Respun build:

https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_GSMVoGG0EeywTM1lnhUXVw

**Review by kristip17 — APPROVED** [review]

**Comment by jvanhill** [comment]
#libby

**Pull request merged**
