### PR TITLE
Use quick log test for testMaxFileSizePriorityRolling

### PR DESCRIPTION
**Pull request by ellen-lau**
#build

### CODE REVIEW

**Comment by ellen-lau** [comment]
#build

**Comment by ellen-lau** [comment]
#libby
#build

**Review by tonyreigns — APPROVED** [review]
LGTM

**Comment by ellen-lau** [comment]
Ran 4 builds for this, with 50 runs of the FAT test in between the four -- did not see any related test failures in those four builds.

**Comment by ellen-lau** [comment]
fixes: #21026
fixes: #21052

**Pull request merged**
