### PR TITLE
Compare OS using lower case

### PR DESCRIPTION
**Pull request by fmhwong**
Fix the OS comparison with lower case introduced in #15439

### CODE REVIEW

**Comment by fmhwong** [comment]
PB: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_XtjfQFTkEeuFI6_BZVYvOw&tab=com.ibm.team.build.web.ui.internal.editors.result.overview.OverviewPage

**Comment by wraschke** [comment]
#run-libby

**Comment by fmhwong** [comment]
#build

**Review by Channyboy — APPROVED** [review]
lgtm

**Pull request merged**
