### PR TITLE
#15132-Remove Beta Fence for expandLocation for GA

### PR DESCRIPTION
**Pull request by hlhoots**
#build

### CODE REVIEW

**Comment by hlhoots** [comment]
Questions/Issues resolved.  Removing beta fence for 21.0.0.4

#build

**Review by cbridgha — APPROVED** [review]
Looks good!

**Comment by hlhoots** [comment]
#run-libby-bot

**Comment by hlhoots** [comment]
Build had one unrelated error.  Merging.

**Pull request merged**
