### PR TITLE
MP OpenAPI UI Customization and FAT tests

### PR DESCRIPTION
**Pull request by arturdzm**

### CODE REVIEW

**Comment by arturdzm** [comment]
#build

**Comment by leochr** [comment]
The personal build https://wasrtc.hursley.ibm.com:9443/jazz/resource/itemOid/com.ibm.team.build.BuildResult/_jcbrUBJpEeiStsw2He7iFw is fine. Failures are in unrelated components. 

Kicking off another one since some commits were reverted as part of resolving the buildcon issues and in case they affect indirectly

#build

**Comment by leochr** [comment]
@ewhoch please merge these commits once you are ready to accept new commits. These are needed for 1Q18. Thanks!

**Comment by arturdzm** [comment]
This changes are included in #2275. Closing this PR

**Pull request closed without merging**
