### PR TITLE
Fix MP RS 3.0 TCK performance issue

### LINKED ISSUE #25644: Run the MicroProfile RSO 3.0 TCK
Run the MicroProfile RSO 3.0 TCK automatically in the build

### PR DESCRIPTION
**Pull request by tevans78**
We eventually discovered that there was a new poll timeout that needed to be changed from the default value. Also took this opportunity to use an injected ScheduledExecutorService.

fixes https://github.com/OpenLiberty/open-liberty/issues/25644

### CODE REVIEW

**Comment by tevans78** [comment]
#build

**Comment by tevans78** [comment]
#build

**Review by abutch3r — APPROVED** [review]
LGTM

**Comment by abutch3r** [comment]
#libby

**Pull request merged**
