### PR TITLE
Adjust db competeforlogs method

### LINKED ISSUE #15503: Transactions Cloud FAT suites testDBRecoveryCompeteForLog can fail on slow infra
I think that this is at the root of a problem observed in our regression suites. It is possible for the modifyLeaseOwner method action to be overridden by a lease update prior to server crash.

### PR DESCRIPTION
**Pull request by neilgsyoung**
fixes #15503

### CODE REVIEW

**Comment by wraschke** [comment]
#run-libby

**Comment by neilgsyoung** [comment]
#build

**Comment by neilgsyoung** [comment]
#run-libby-bot

**Comment by neilgsyoung** [comment]
#build

**Comment by neilgsyoung** [comment]
#run-libby-bot

**Comment by neilgsyoung** [comment]
#build

**Review by jonhawkes — APPROVED** [review]

**Pull request merged**
