### PR TITLE
Add test for ZonedDateTime comparisons

### PR DESCRIPTION
**Pull request by KyleAure**
- [x] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [x] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [x] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

### CODE REVIEW

**Comment by KyleAure** [comment]
#build - personal build
#libby - check headers

**Comment by contbld** [comment]
Your personal pipeline request is at https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=bdb0bec6-8053-4880-98b0-f2319cbf0500

Target locations of links might be accessible only to IBM employees.

**Comment by contbld** [comment]
Your personal pipeline request is at https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=2b6c4765-7802-4c6f-ba45-eccc5451a8f5

Target locations of links might be accessible only to IBM employees.

**Comment by contbld** [comment]
<h3>Code analysis and actions</h3>
DO NOT DELETE THIS COMMENT.

- 2 FAT files were changed, added, or removed.
 - Check that the build did not break the affected FAT suite(s).

**Comment by contbld** [comment]
<h3>Code analysis and actions</h3>
DO NOT DELETE THIS COMMENT.

- 2 FAT files were changed, added, or removed.
 - Check that the build did not break the affected FAT suite(s).

**Comment by contbld** [comment]
https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=bdb0bec6-8053-4880-98b0-f2319cbf0500 completed successfully!

**Comment by contbld** [comment]
https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=2b6c4765-7802-4c6f-ba45-eccc5451a8f5 completed successfully!

**Comment by KyleAure** [comment]
Personal Database SOE (DB2 and Oracle): https://libh-proxy1.fyre.ibm.com/cognitive-dev/pipelineAnalysis.html?pipelineId=e38410c9-f371-4fc7-83b2-beb4ef7b484b

Target locations of links might be accessible only to IBM employees.

**Comment by KyleAure** [comment]
RTC Build: Passed
Pipeline: Passed
Database SOE (DB2 and Oracle): Passed

Ready to merge once reviewed.

**Comment by ajaypaul-ibm** [comment]
Hi @KyleAure , Can you please resolve the conflicts ? 
Also the build passed right without any BLOB errors ? Are you getting that only on local ?

**Review by ajaypaul-ibm — DISMISSED** [review]

**Comment by KyleAure** [comment]
#build - redo personal build after resolving merge conflict
#libby - check headers

**Comment by contbld** [comment]
Your personal pipeline request is at https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=38b8bcd9-f924-4577-94f5-398e0e64d7ba

Target locations of links might be accessible only to IBM employees.

**Comment by contbld** [comment]
Your personal pipeline request is at https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=470e86a8-2bf8-474d-b49c-4624ea518c04

Target locations of links might be accessible only to IBM employees.

**Comment by contbld** [comment]
<h3>Code analysis and actions</h3>
DO NOT DELETE THIS COMMENT.

- 2 FAT files were changed, added, or removed.
 - Check that the build did not break the affected FAT suite(s).
- **Please describe in a separate comment how you tested your changes.**
- 1 messages files were changed and need an L2 review.

- @OpenLiberty/message-reviewer Please review.
  - --nlsFiles

**Comment by contbld** [comment]
<h3>Code analysis and actions</h3>
DO NOT DELETE THIS COMMENT.

- 2 FAT files were changed, added, or removed.
 - Check that the build did not break the affected FAT suite(s).
- **Please describe in a separate comment how you tested your changes.**
- 1 messages files were changed and need an L2 review.

- @OpenLiberty/message-reviewer Please review.
  - --nlsFiles

**Comment by contbld** [comment]
https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=470e86a8-2bf8-474d-b49c-4624ea518c04 completed successfully!

**Comment by contbld** [comment]
https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=38b8bcd9-f924-4577-94f5-398e0e64d7ba completed successfully!

**Comment by KyleAure** [comment]
Ready to merge upon re-review.

**Review by ajaypaul-ibm — APPROVED** [review]

**Comment by ajaypaul-ibm** [comment]
LGTM

**Pull request merged**
