### PR TITLE
Add activator for MPTelemetry-1.0

### PR DESCRIPTION
**Pull request by Yas-Franco**
For issue #22689

### CODE REVIEW

**Comment by Yas-Franco** [comment]
#build

**Review by Azquelt — APPROVED** [review]

**Comment by Azquelt** [comment]
#libby

**Comment by Yas-Franco** [comment]
The build failure was unrelated to this change

**Comment by yasmin-aumeeruddy** [comment]
#23038

**Comment by Yas-Franco** [comment]
#build

**Comment by Yas-Franco** [comment]
#libby

**Pull request merged**
