### PR TITLE
MYFACES-4503

### LINKED ISSUE #23407: MYFACES-4503
https://issues.apache.org/jira/browse/MYFACES-4503

### PR DESCRIPTION
**Pull request by pnicolucci**
fixes #23407

### CODE REVIEW

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
#libby-build

**Comment by pnicolucci** [comment]
#libby #build

**Review by volosied — APPROVED** [review]
Looks good!

**Pull request merged**
