### PR TITLE
Upgrade to Gradle 8.3 and support compiling Java 21 projects

### PR DESCRIPTION
**Pull request by fritze2**
Deprecated:
```
The AbstractArchiveTask.version property has been deprecated. |  
-- | --
  | This is scheduled to be removed in Gradle 8.0. |  
  | Please use the archiveVersion property instead. |  
  | Documentation |  
  | 1882 usages |  
 
  | The Report.enabled property has been deprecated. |  
  | This is scheduled to be removed in Gradle 8.0. |  
  | Please use the required property instead. |  
  | Documentation |  
  | 1881 usages |  
 
  | The AbstractArchiveTask.archiveName property has been deprecated. |  
  | This is scheduled to be removed in Gradle 8.0. |  
  | Please use the archiveFileName property instead. |  
  | Documentation |  
  | 790 usages |  
 
  | The AbstractArchiveTask.baseName property has been deprecated. |  
  | This is scheduled to be removed in Gradle 8.0. |  
  | Please use the archiveBaseName property instead. |  
  | Documentation |  
  | 681 usages |  
 
  | The JavaExec.main property has been deprecated. |  
  | This is scheduled to be removed in Gradle 8.0. |  
  | Please use the mainClass property instead. |  
  | Documentation |  
  | 680 usages |  
 
  | The AbstractArchiveTask.destinationDir property has been deprecated. |  
  | This is scheduled to be removed in Gradle 8.0. |  
  | Please use the destinationDirectory property instead. |  
  | Documentation |  
  | 35 usages |  
 
  | Using force on a dependency has been deprecated. |  
  | This is scheduled to be removed in Gradle 8.0. |  
  | Consider using strict version constraints instead (version { strictly ... } }). |  
  | Documentation |  
  | 3 usages |  
 
  | The TestReport.destinationDir property has been deprecated. |  
  | This is scheduled to be removed in Gradle 8.0. |  
  | Please use the destinationDirectory property instead. |  
  | Documentation |  
  | 1 usage |  
 
  | The TestReport.reportOn(Object...) method has been deprecated. |  
  | This is scheduled to be removed in Gradle 8.0. |  
  | Please use the testResults method instead. |  
  | Documentation |  
  | 1 usage

The AbstractArchiveTask.version property has been deprecated.	
This is scheduled to be removed in Gradle 8.0.	
Please use the archiveVersion property instead.	
[Documentation](https://docs.gradle.org/7.4.1/dsl/org.gradle.api.tasks.bundling.AbstractArchiveTask.html#org.gradle.api.tasks.bundling.AbstractArchiveTask:version)	
1882 usages	
The Report.enabled property has been deprecated.	
This is scheduled to be removed in Gradle 8.0.	
Please use the required property instead.	
[Documentation](https://docs.gradle.org/7.4.1/dsl/org.gradle.api.reporting.Report.html#org.gradle.api.reporting.Report:enabled)	
1881 usages	
The AbstractArchiveTask.archiveName property has been deprecated.	
This is scheduled to be removed in Gradle 8.0.	
Please use the archiveFileName property instead.	
[Documentation](https://docs.gradle.org/7.4.1/dsl/org.gradle.api.tasks.bundling.AbstractArchiveTask.html#org.gradle.api.tasks.bundling.AbstractArchiveTask:archiveName)	
790 usages	
The AbstractArchiveTask.baseName property has been deprecated.	
This is scheduled to be removed in Gradle 8.0.	
Please use the archiveBaseName property instead.	
[Documentation](https://docs.gradle.org/7.4.1/dsl/org.gradle.api.tasks.bundling.AbstractArchiveTask.html#org.gradle.api.tasks.bundling.AbstractArchiveTask:baseName)	
681 usages	
The JavaExec.main property has been deprecated.	
This is scheduled to be removed in Gradle 8.0.	
Please use the mainClass property instead.	
[Documentation](https://docs.gradle.org/7.4.1/dsl/org.gradle.api.tasks.JavaExec.html#org.gradle.api.tasks.JavaExec:main)	
680 usages	
The AbstractArchiveTask.destinationDir property has been deprecated.	
This is scheduled to be removed in Gradle 8.0.	
Please use the destinationDirectory property instead.	
[Documentation](https://docs.gradle.org/7.4.1/dsl/org.gradle.api.tasks.bundling.AbstractArchiveTask.html#org.gradle.api.tasks.bundling.AbstractArchiveTask:destinationDir)	
35 usages	
Using force on a dependency has been deprecated.	
This is scheduled to be removed in Gradle 8.0.	
Consider using strict version constraints instead (version { strictly ... } }).	
[Documentation](https://docs.gradle.org/7.4.1/userguide/upgrading_version_5.html#forced_dependencies)	
3 usages	
The TestReport.destinationDir property has been deprecated.	
This is scheduled to be removed in Gradle 8.0.	
Please use the destinationDirectory property instead.	
[Documentation](https://docs.gradle.org/7.4.1/dsl/org.gradle.api.tasks.testing.TestReport.html#org.gradle.api.tasks.testing.TestReport:destinationDir)	
1 usage	
The TestReport.reportOn(Object...) method has been deprecated.	
This is scheduled to be removed in Gradle 8.0.	
Please use the testResults method instead.	
[Documentation](https://docs.gradle.org/7.4.1/dsl/org.gradle.api.tasks.testing.TestReport.html#org.gradle.api.tasks.testing.TestReport:testResults)	
1 usage
```

### CODE REVIEW

**Comment by fritze2** [comment]
#build

**Comment by jhanders34** [comment]
For reference, the deprecation issues that Ethan posted in the description of this PR were resolved with #25882 (with a fix afterward of #25914) and with #25921.

**Comment by fritze2** [comment]
Submitted a build with `gradle.version` set to 8.3 because CI builds default to a source controlled Gradle version in build scripts using that property.
https://wasrtc.hursley.ibm.com:9443/jazz/resource/itemOid/com.ibm.team.build.BuildResult/_bmA-0EHIEe6Z3JPws1j0ig

I'll update the property in source control (located in an internal IBM repo) after this PR and changes needed to upgrade WebSphere Liberty to Gradle 8.3 work.

**Comment by jhanders34** [comment]
#libby

**Review by jhanders34 — APPROVED** [review]

**Pull request merged**
