### PR TITLE
increase timeout

### PR DESCRIPTION
**Pull request by benjamin-confino**
Increases the timeout to fix https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.workitem.viewWorkItem&id=290801

### CODE REVIEW

**Review by Azquelt — APPROVED** [review]

**Comment by benjamin-confino** [comment]
#build

**Comment by benjamin-confino** [comment]
#libby

**Comment by benjamin-confino** [comment]
#run-libby-bot

**Comment by benjamin-confino** [comment]
#libby-bot

**Pull request merged**
