### PR TITLE
22979: Update wsoc test

### LINKED ISSUE #22979: Wsoc test update
Split a single test into two separate tests

The test was using two different classes onClose and onOpen, which each had onClose and onOpen methods.  The methods were getting intermingled when a message was being sent, and depending on the order of the onClose.onOpen, onOpen.onOpen, on onOpen.onClose, OnClose.onClose, we were sometimes getting an Array index out of range.
I split the test case into two test cases to avoid the mingling of the two classes.  Now each test uses one of the classes.

### PR DESCRIPTION
**Pull request by loriadi**
fixes #22979

### CODE REVIEW

**Comment by loriadi** [comment]
#build #spawn.fullfat.buckets=io.openliberty.wsoc.internal_fat

**Comment by loriadi** [comment]
#build #spawn.fullfat.buckets=io.openliberty.wsoc.internal_fat

**Comment by loriadi** [comment]
fixes #22979

**Comment by loriadi** [comment]
#libbybot

**Comment by loriadi** [comment]
z/OS build:
https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_IR4ZQE40Ee2fv7PFprXZfA

**Comment by wraschke** [comment]
A comment for automation testing. Please ignore.

**Comment by loriadi** [comment]
re-build with z/os and full fats:
https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_32SsUE7-Ee2fv7PFprXZfA

**Comment by loriadi** [comment]
https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_estIME8_Ee2fv7PFprXZfA

**Review by isaacrivriv — APPROVED** [review]
Changes look good to me, thanks!

**Pull request merged**
