### PR TITLE
ClassNotFoundException in com.ibm.ws.wssecurity_fat.wsscxf

### PR DESCRIPTION
**Pull request by BerksanAtes**
for #16591

### CODE REVIEW

**Comment by BerksanAtes** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.wssecurity_fat.wsscxf

**Comment by BerksanAtes** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.wssecurity_fat.wsscxf

**Comment by BerksanAtes** [comment]
#build

**Comment by BerksanAtes** [comment]
#build

**Review by meiaus — APPROVED** [review]

**Comment by BerksanAtes** [comment]
#run-libby-bot

**Pull request merged**
