### PR TITLE
empty list of entities

### PR DESCRIPTION
**Pull request by njr-11**
Detect and raise an error when supplied an empty list of entities. Also add error messages for errors that occur during getAttribute.

- [x] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [x] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [x] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

### CODE REVIEW

**Comment by njr-11** [comment]
#build
#libby

**Comment by contbld** [comment]
Your personal pipeline request is at https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=b886128c-3c46-4f84-97ca-85d1ce316eba

Target locations of links might be accessible only to IBM employees.

**Comment by contbld** [comment]
Your personal pipeline request is at https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=b0d602e3-eccc-4486-ba5a-0bc57adfa928

Target locations of links might be accessible only to IBM employees.

**Comment by contbld** [comment]
<h3>Code analysis and actions</h3>
DO NOT DELETE THIS COMMENT.

- 4 FAT files were changed, added, or removed.
 - Check that the build did not break the affected FAT suite(s).

- 4 product code files were changed.

**Comment by contbld** [comment]
<h3>Code analysis and actions</h3>
DO NOT DELETE THIS COMMENT.

- 4 FAT files were changed, added, or removed.
 - Check that the build did not break the affected FAT suite(s).

- 4 product code files were changed.

**Comment by contbld** [comment]
https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=b0d602e3-eccc-4486-ba5a-0bc57adfa928 completed successfully!

**Comment by contbld** [comment]
https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=b886128c-3c46-4f84-97ca-85d1ce316eba has errors/failures.

**Review by gjwatts — APPROVED** [review]

**Pull request merged**
