### PR TITLE
Issue #15740: Fix timeout issue with running KTPASS command on the KD…

### LINKED ISSUE #15740: Test Failure (20201118-0738): junit.framework.TestSuite.com.ibm.ws.security.spnego.fat.FATSuite
The test fails because the ktpass command being issued to the remote KDC failed to complete within 5 minutes. After adding debug I can see that the command is awaiting user input (that will never occur):

```
[STDERR] Do you really want to delete any previous servicePrincipalName values on xxxxx [y/n]?
```

I have updated the ktpass command to pass `+Answer` which should answer yes to any queries.

Failure stack follows.

```
java.lang.Exception: Common setup failed, tests will not run: The SSH command timed out while executing. The timeout was 300 seconds.
at com.ibm.ws.security.spnego.fat.FATSuite$1.before(FATSuite.java:84)
Caused by: java.io.IOException: The SSH command timed out while executing. The timeout was 300 seconds.
at com.ibm.ws.security.spnego.fat.config.KdcHelper.executeSshCommand(KdcHelper.java:913)
at com.ibm.ws.security.spnego.fat.config.MsKdcHelper.executeRemoteCommand(MsKdcHelper.java:454)
at com.ibm.ws.security.spnego.fat.config.MsKdcHelper.createUserAndKeytabFile(MsKdcHelper.java:396)
at com.ibm.ws.security.spnego.fat.config.MsKdcHelper.createSpnAndKeytab(MsKdcHelper.java:118)
at com.ibm.ws.security.spnego.fat.config.CommonTest.commonSetUp(CommonTest.java:324)
at com.ibm.ws.security.spnego.fat.FATSuite$1.before(FATSuite.java:76)
```

### PR DESCRIPTION
**Pull request by jvanhill**
…C. Add more debugging to remote command execution in order help with these sort of issues in the future.

fixes #15740

### CODE REVIEW

**Comment by jvanhill** [comment]
#build
#libby

**Comment by jvanhill** [comment]
Some SPNEGO fats failed since other FVTs replaced the updated createWinKeytabFile.bat file with a non-updated version. This happens when the existing OL FATs run with the old version, or when WS-CD-Open FVTs run with a version that I have not updated. I will need to determine how I can get around this issue.

**Comment by jvanhill** [comment]
#build
#libby

**Comment by jvanhill** [comment]
#build
#libby

**Comment by jvanhill** [comment]
#libby
#build

**Comment by jvanhill** [comment]
#build
#libby

**Review by Zech-Hein — APPROVED** [review]

**Pull request merged**
