### PR TITLE
Update the default Java used to build to be Java 17

### PR DESCRIPTION
**Pull request by jhanders34**
- Require Java 17 for Open Liberty builds
- Update projects to use Java 17 where appropriate for Java 17 + FATs and Jakarta Data feature.

### CODE REVIEW

**Comment by jhanders34** [comment]
#build

**Review by KyleAure — DISMISSED** [review]

**Review by njr-11 — DISMISSED** [review]

**Review by cbridgha — DISMISSED** [review]
Thanks looks good

**Review by gjwatts — DISMISSED** [review]

**Comment by jhanders34** [comment]
#libby #build

**Review by njr-11 — DISMISSED** [review]

**Review by njr-11 — APPROVED** [review]

**Comment by jhanders34** [comment]
#libby

**Pull request merged**
