### PR TITLE
Remove feature version from FeatureInfo output

### LINKED ISSUE #19021: Feature Subsystem-Version is not useful
- The `Subsystem-Version` feature header is not used by the runtime for anything.
- Internally the value can be obtained through the `com.ibm.wsspi.kernel.feature.LibertyFeature` interface but this is not a public SPI (despite the package name).
- It is displayed in the output of `wlp/bin/productInfo featureInfo` e.g. (the value in square brackets)
```
wasJmsClient-2.0 [1.0.0]
wasJmsSecurity-1.0 [1.0.0]
wasJmsServer-1.0 [1.0.0]
webCache-1.0 [1.0.0]
webProfile-7.0 [7.0.0]
webProfile-8.0 [8.0.0]
```
- For the vast majority of features, it is set to `1.0.0` ... either explicitly or by default.
- Of the few features which set the value to something other than `1.0.0`, it is not consistent e.g.
```
appSecurity-1.0 [1.1.0]
microProfile-1.0 [7.0.0]
```

- What is the correct value?
   - Should it usually be `1.0.0`?
   - It could be set to the same as the version defined in the feature name but then it would be redundant information.
- When should it be updated (if ever)?
   - What kind of change to a feature would require a Subsystem-Version change?

Possible Actions:
1. Require that all new features (e.g. EE9 & MP5) should set the value correctly
2. Update all existing features to be "correct"
3. Remove the header from all feature files and let it default to `1.0.0` in all cases
4. Stop generating the header in the feature manifest and remove the version from the output of `productInfo featureInfo`
5. Do nothing, don't worry if the value is "wrong"

### PR DESCRIPTION
**Pull request by tevans78**
fixes OpenLiberty#19021
#build

### CODE REVIEW

**Review by tjwatson — APPROVED** [review]

**Comment by tevans78** [comment]
#build

**Comment by tevans78** [comment]
Need to update a test over in WS-CD
```
junit.framework.AssertionFailedError: 2021-10-19-15:42:07:198 The output should contain usr product feature: user.ext.version.info [1.0.0].
	at com.ibm.ws.product.utility.fat.ProductToolTestCommon.testPrintFeatureInfoForAllProductsInstalled(ProductToolTestCommon.java:243)
	at com.ibm.ws.product.utility.fat.ProductUtilToolTest.testProdUtilToolPrintFeatureInfoForAllProductsInstalled(ProductUtilToolTest.java:49)
```

**Comment by tevans78** [comment]
#build

**Comment by tevans78** [comment]
#build

**Pull request merged**
