### PR TITLE
Liberty accesses readOnly subject

### LINKED ISSUE #25046: Liberty accesses readonly subject
**Describe the bug**  

Stack error in the customer FFDC log:

Stack Dump = java.lang.IllegalStateException: Subject is read-only
at javax.security.auth.Subject$SecureSet.add(Subject.java:1326)
at java.util.Collections$SynchronizedCollection.add(Collections.java:2048)
at com.ibm.ws.webcontainer.security.internal.TAIAuthenticator.removeInternalProps(TAIAuthenticator.java:391)
at com.ibm.ws.webcontainer.security.internal.TAIAuthenticator.authenticateWithSubject(TAIAuthenticator.java:376)
at com.ibm.ws.webcontainer.security.internal.TAIAuthenticator.loginWithTAIUserName(TAIAuthenticator.java:351)
at com.ibm.ws.webcontainer.security.internal.TAIAuthenticator.authenticateWithTAIResult(TAIAuthenticator.java:313)
at com.ibm.ws.webcontainer.security.internal.TAIAuthenticator.handleTaiResult(TAIAuthenticator.java:252)
at com.ibm.ws.webcontainer.security.internal.TAIAuthenticator.authenticate(TAIAuthenticator.java:167)
at com.ibm.ws.webcontainer.security.WebProviderAuthenticatorProxy.handleTAI(WebProviderAuthenticatorProxy.java:337)

**Steps to Reproduce**  
Steps to reproduce the bug

**Expected behavior**  
No error should be thrown
**Diagnostic information:**
I see an error in Liberty 22.0.0.12 + Java 8.0.7.20 with

**Additional context**  
 a stack that is almost identical to this GitHub issue:
https://github.com/OpenLiberty/open-liberty/issues/17489

### PR DESCRIPTION
**Pull request by una-tapa**
This PR is trying to resolve https://github.com/OpenLiberty/open-liberty/issues/25046

### CODE REVIEW

**Comment by una-tapa** [comment]
#build

**Comment by una-tapa** [comment]
- Received positive feedback from the user.
- The build results only showed an UI test failure that is network related.

**Comment by una-tapa** [comment]
The user provided a positive feedback.  
The one line code change is to check if the subject is readonly. 
If needed, will have a quick review in the upcoming scrum meeting

**Comment by emilytee** [comment]
Yes, please, let's review at the next scrum meeting - in case, anyone sees something not quite right.

Regards,
Emily

Emily Tuczkowski
Senior Software Engineer
WebSphere Security Development
WebSphere L3 Security Customer Support
PSIRT Responder for IBM Cloud Pak for Apps, M2M, TA, AppNavigator, WDT and Hybrid Edition
Organization Security Compliance Focal
________________________________
From: Hiroko Takamiya ***@***.***>
Sent: Saturday, April 22, 2023 4:12 PM
To: OpenLiberty/open-liberty ***@***.***>
Cc: Emily Tuczkowski ***@***.***>; Review requested ***@***.***>
Subject: [EXTERNAL] Re: [OpenLiberty/open-liberty] Liberty accesses readOnly subject (PR #25066)

The user provided a positive feedback. The one line code change is to check if the subject is readonly. If needed, will have a quick review in the upcoming scrum meeting — Reply to this email directly, view it on GitHub, or unsubscribe. You
ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
This message came from outside your organization.

ZjQcmQRYFpfptBannerEnd

The user provided a positive feedback.
The one line code change is to check if the subject is readonly.
If needed, will have a quick review in the upcoming scrum meeting

**Review by utle — CHANGES_REQUESTED** [review]
The caller already checked for subject is readonly. 

                if (hashtable != null && !subject.isReadOnly()) {
                    removeInternalProps(new_subject, subjectHelper, AuthenticationConstants.INTERNAL_DISABLE_SSO_LTPA_COOKIE, hashtable);
                }

**Comment by una-tapa** [comment]
@utle 
Here is the callstack.  The customer gave us positive feedback. 
This is to make the code robust, in addition to the code Ut pointed (suggested by Ut earlier) 
https://github.com/OpenLiberty/open-liberty/issues/25046#issue-1674097914

**Review by utle — CHANGES_REQUESTED** [review]
The caller already check for subject is read only. Not sure why we have to check again in removeInternalProps method? do I miss something here?
if (hashtable != null && !subject.isReadOnly()) {                    removeInternalProps(new_subject, subjectHelper, AuthenticationConstants.INTERNAL_DISABLE_SSO_LTPA_COOKIE, hashtable);                }

**Comment by una-tapa** [comment]
Hi, @utle  Thanks to your previous suggestions to resolve the issue, we put the check here and there as you pointed. Unfortunately, they were not successful in resolving the problem.  The reporting user pointed the following issues are not complete.
https://github.com/OpenLiberty/open-liberty/issues/21666
https://github.com/OpenLiberty/open-liberty/issues/17489
However, this one line code successfully eliminated the issue by putting the check right in removeInternalProps(). Would it be possible to consider this solution as the way forward?  


The proposed solution appears to have a potential issue, as there may be a time gap between the isReadOnly check and the execution of the remove() method. If, during this period, the subject is marked as readOnly, it could result in the occurrence of the issue.  To mitigate this risk, it may be advisable to perform the isReadOnly check directly within the removal method, in order to ensure that any potential conflicts are immediately identified and addressed before proceeding further.

**Comment by una-tapa** [comment]
#build

**Review by emilytee — DISMISSED** [review]

**Comment by una-tapa** [comment]
#libby

**Comment by una-tapa** [comment]
#build

**Comment by una-tapa** [comment]
It has been a while, Adding @arunavemulapalli's suggestions to run the build again.

**Comment by una-tapa** [comment]
#build

**Comment by una-tapa** [comment]
Trying to start over so the PR is cleaner.  Closing for now.

**Pull request closed without merging**
