### PR TITLE
Add Face 3.0 test for the new faces-config.xml

### LINKED ISSUE #14904: Create test for new FacesConfig Version 3.0
Adding test for #14424

### PR DESCRIPTION
**Pull request by volosied**
fixes  #14904

Modeled off https://github.com/OpenLiberty/open-liberty/commit/7192ea6a8edc031aa5b51ccdeee613fecc0260a3

### CODE REVIEW

**Comment by volosied** [comment]
#build

**Comment by volosied** [comment]
#build

**Comment by volosied** [comment]
#run-libby-bot

**Review by isaacrivriv — APPROVED** [review]
Looks good! Thanks!

**Comment by pnicolucci** [comment]
For reference we have a FAT in the JSF 2.3 FAT bucket as well :https://github.com/OpenLiberty/open-liberty/pull/14427

**Review by pnicolucci — APPROVED** [review]

**Comment by volosied** [comment]
#run-libby-bot

**Pull request merged**
