### PR TITLE
Update Swagger UI to 4.6.2

### PR DESCRIPTION
**Pull request by Azquelt**
Update Swagger UI and its dependencies and rebuild the OpenAPI UI

### CODE REVIEW

**Comment by Azquelt** [comment]
#build

**Comment by Azquelt** [comment]
#libby #build

**Comment by Azquelt** [comment]
#libby
#build

**Comment by Azquelt** [comment]
I have run the [manual test procedure](https://github.com/OpenLiberty/openapi-ui-test-app#test-procedure) successfully on the output from the personal build above.

**Review by Emily-Jiang — APPROVED** [review]
LGTM

**Pull request merged**
