### PR TITLE
Get things building in eclipse again

### PR DESCRIPTION
**Pull request by jhanders34**
- Remove references to linked source that isn't there any longer
- Update build.gradle to not reference test-bundles that aren't there any longer
- Update io.openliberty.xmlWS.3.0.internal.tools projects to be in xmlWS directory instead of xmlws directory in order to match the project and bundle names.
- Add com.github.docker-java:docker-java-api dependency to projects to remove indirect reference errors.
- Update cdi fat project to have classes in the right directory.
- Add missing bndtools prefs file

### CODE REVIEW

**Comment by jhanders34** [comment]
#build

**Review by KyleAure — APPROVED** [review]

**Comment by tkburroughs** [comment]
@jhanders34 Thank you!

**Review by benjamin-confino — APPROVED** [review]
I approve the changes to com.ibm.ws.cdi.jee_fat

**Review by neuwerk — COMMENTED** [review]
xmlWS-3.0 changes look good

**Pull request merged**
