### PR TITLE
Scan for approved packages at build time

### PR DESCRIPTION
**Pull request by aguibert**
Currently packages approvals are checked very late in the delivery process, and the master list is housed in a separate github repository, which makes updates tedious to coordinate.

Replace this approval mechanism with a list of approved packages in each project's `bnd.bnd` file via a new `wlp.approved.packages` property list, such as:
```
wlp.approved.packages: \
  com.ibm.json,\
  com.ibm.json.java,\
  com.ibm.json.java.internal,\
  com.ibm.json.xml,\
  com.ibm.json.xml.internal
```

If any new packages are added and are not approved by legal, they would be caught immediately at build time with clear instructions on how to resolve the missing approval.

Sample failure output:
```
$ ./gradlew :com.ibm.json4j:assemble

...

> Task :com.ibm.json4j:approvedPackages FAILED

FAILURE: Build failed with an exception.

* Where:
Script '/Users/aguibert/dev/git/open-liberty/dev/wlp-gradle/subprojects/tasks.gradle' line: 189

* What went wrong:
Execution failed for task ':com.ibm.json4j:approvedPackages'.
> Found new packages which have not been approved by the legal team yet.
  Add the new packages to the 'wlp.approved.packages' property in /Users/aguibert/dev/git/open-liberty/dev/com.ibm.json4j/bnd.bnd
  and seek a code review from the legal team to ensure they are aware of the new package.
  Unapproved packages located:
  [com.ibm.json.java.internal, com.ibm.json.xml.internal]

BUILD FAILED in 17s
7 actionable tasks: 4 executed, 3 up-to-date
```

### CODE REVIEW

**Comment by CassTucker** [comment]
Andrew, I know we discussed this on slack but let me digest this before I approve.  I'll approve tomorrow at latest.

**Comment by CassTucker** [comment]
Chuck so yes I'd still need to see something at least until the PTC takes over say until end of year.  They are actually using the OpenLiberty all and WLP-beta GM zips to create AWSOM proposals so if the OSSC report is a subset of monthly GM zips, I will definitely agree and approve this new process.

**Comment by aguibert** [comment]
@cbridgha my hope is that we can just get rid of the global approved package list and let each project track its own approved packages.
If we do still need to have a global list, I could write a script/task that collects the approved package lists from each individual project into a global list -- but I haven't heard any evidence of needing such a mechanism so far.

**Comment by aguibert** [comment]
closing this work item in favor of a different process that @cbridgha @wraschke and I discussed which will do a mapping of GA features to OSS dependencies

**Pull request closed without merging**
