### PR TITLE
Update Yoko version with improved doPriv usage

### PR DESCRIPTION
**Pull request by ngmr**

### CODE REVIEW

**Comment by ngmr** [comment]
#run-libby-bot

**Comment by ngmr** [comment]
#build

**Comment by ngmr** [comment]
#run-libby-bot

**Comment by ngmr** [comment]
#run-libby-bot

**Comment by ngmr** [comment]
#build

**Comment by ngmr** [comment]
#build

**Review by joe-chacko — APPROVED** [review]
.

**Comment by joe-chacko** [comment]
#run-libby-bot

**Pull request merged**
