### PR TITLE
Update OpenTracing to RC4

### PR DESCRIPTION
**Pull request by tonyreigns**
Upgrading OpenTracing to use the 3.0-RC4 API, updating Rest-Client API to RC5 in the OT TCK and adding OpenTracing to MicroProfileActions.

### CODE REVIEW

**Comment by tonyreigns** [comment]
#build

**Review by fmhwong — APPROVED** [review]
LGTM

**Comment by tonyreigns** [comment]
Started a new build without `.im.` properties in case builds are still failing due to lack of disk space: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_wpeKEDyuEeygsrM6ShizkA&tab=com.ibm.team.build.web.ui.internal.editors.result.overview.OverviewPage

**Comment by tonyreigns** [comment]
The build error is not due to my changes.
#libby

**Pull request merged**
