### PR TITLE
Add session cookieSameSite to the ibmui cookies group

### LINKED ISSUE #27394: Fix location of `cookieSameSite` within the `httpSession` metatype
Link to the `httpSession` configuration: https://openliberty.io/docs/latest/reference/config/httpSession.html

Currently the `cookieSameSite` configuration is not under `Cookies` group when looking at the published server configuration.

The `cookieSameSite` configuration is:

```
        <AD id="cookieSameSite"
            name="%cookie.same.site"
            description="%cookie.same.site.desc"
            required="false" type="String" default="Disabled">
            <Option label="%cookie.same.site.disabled" value="Disabled"/>
            <Option label="%cookie.same.site.lax" value="Lax"/>
            <Option label="%cookie.same.site.none" value="None"/>
            <Option label="%cookie.same.site.strict" value="Strict"/>
        </AD>
```

```
The `cookieHttpOnly` configuration is:

        <AD id="cookieHttpOnly" 
            name="%cookie.http.only" 
            description="%cookie.http.only.desc" 
            ibmui:group="cookies"
            required="false" type="Boolean" default="true" /> 
```

For `cookieSameSite` the declaration is missing `ibmuigroup="cookies"`

### PR DESCRIPTION
**Pull request by pnicolucci**
fixes #27394

### CODE REVIEW

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
#build

**Review by zhang-ca — APPROVED** [review]
Looks good.

**Comment by pnicolucci** [comment]
#libby

**Pull request merged**
