### PR TITLE
Be more selective about when to restart an app

### PR DESCRIPTION
**Pull request by andymc12**
Currently, when an app is deployed/extracted to a Liberty server (without using loose config), the app will restart on changes to things like JSPs, that should not require a restart.

We should be more selective.  If the user modifies something fairly critical to the app - like the web.xml, ejb-jar.xml, bindings files, etc. - then we still need to restart the app.  But for files like JSPs, static content, etc. we should not restart the app.

For class file changes, we should restart the app, but we should also prepare the way for a "hot re-deploy" scenario where we could re-define the class if only minor changes are made to it (i.e. only changing the internals of a method body).

### CODE REVIEW

**Comment by andymc12** [comment]
Let's #build this thing.

**Comment by wraschke** [comment]
#hey-ladies

**Comment by andymc12** [comment]
Adding a couple more builtin file patterns to address JPA and app manager failures. New #build with these changes...

**Comment by andymc12** [comment]
Changing gears and restarting on any file change except for JSP-related files - new #build to account for this new change.

**Comment by andymc12** [comment]
The only test failure is a known intermittent failure - merging.

**Pull request merged**
