### PR TITLE
Fix Expression Factory Annotations for TCK EL Signature Test

### LINKED ISSUE #16176: Fix ee9 el-4.0 tck signature failure
A new annotation was added to the jakarta.el.ExpressionFactory in the Tomcat EL API:
`@ServiceConsumer(value=jakarta.el.ExpressionFactory.class)`

This causes the signature test for the class to fail as it does not match the EL Spec Reference jar.

Annotation should be removed from Liberty. 

Links:
https://github.com/eclipse-ee4j/jakartaee-tck/issues/643
https://github.com/apache/tomcat/commit/9d3896a434e35cf8e9ebf1c95a81e1fcb739866e

### PR DESCRIPTION
**Pull request by volosied**
fixes #16176

We may wait on this PR if we chose have this fixed upsteam first instead.

### CODE REVIEW

**Comment by volosied** [comment]
#build

**Comment by volosied** [comment]
#build

**Comment by volosied** [comment]
#build

**Review by pnicolucci — APPROVED** [review]

**Comment by volosied** [comment]
#run-libby-bot

**Pull request merged**
