### PR TITLE
Make wsoc-2.0 API private feature

### LINKED ISSUE #15323: The Jakarta 9 Websocket 2.0 API needs a private feature
Currently the websocket-2.0 feature just pulls in the API bundle.

In addition the faces-3.0 feature also pulls in the WebSocket 2.0 API bundle.

We should make a private feature for the WebSocket 2.0 API , that also includes the EE9 compatibility feature and follows a similar structure to other Jakarta EE9 private API features.

The faces-3.0 feature and the websocket-2.0 feature should then include this new private feature rather than the API bundle.

### PR DESCRIPTION
**Pull request by isaacrivriv**
fixes #15323

### CODE REVIEW

**Comment by isaacrivriv** [comment]
#build
#spawn.fullfat.buckets=io.openliberty.wsoc.internal_fat,com.ibm.ws.jsf.2.3_fat,com.ibm.ws.jsf.2.2_fat

**Comment by isaacrivriv** [comment]
#build

**Comment by isaacrivriv** [comment]
#build

**Comment by isaacrivriv** [comment]
#build

**Comment by isaacrivriv** [comment]
#build

**Comment by isaacrivriv** [comment]
#build

**Review by pnicolucci — APPROVED** [review]

**Comment by isaacrivriv** [comment]
Closing and creating a new PR to see if the oauth unit tests failures are unrelated to the changes

**Pull request closed without merging**
