### PR TITLE
Rename `ServiceCaller.call(Function)` to `run` to avoid ambiguity

### PR DESCRIPTION
**Pull request by Azquelt**
`call(Consumer)` and `call(Function)` are ambiguous when called with a lambda which doesn't return a value.

~~I picked "run" to match Runnable/Callable, even though we're actually using Consumer and Function.~~ See discussion below, we're now using `call` and `run`, but with the _opposite_ meaning of Runnable and Callable...

The upstream version does not have this issue because it does not have the `call(Function)` variant.

I could not find any existing code using the `call(Consumer)` variant.

- [x] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [x] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [x] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

### CODE REVIEW

**Comment by Azquelt** [comment]
#build

**Comment by tjwatson** [comment]
I know this is more work since we don't appear to have any references to `call(Consumer)`.  But I would prefer we rename the variants that use `call(Function)` since the original `ServiceCaller` only had the `call(Consumer)` variants.

https://github.com/eclipse-equinox/equinox/blob/master/bundles/org.eclipse.equinox.common/src/org/eclipse/core/runtime/ServiceCaller.java

This would ease any possible efforts to push back the enhancements and fixes we have done back to Eclipse.

**Comment by Azquelt** [comment]
> I know this is more work since we don't appear to have any references to `call(Consumer)`. But I would prefer we rename the variants that use `call(Function)` since the original `ServiceCaller` only had the `call(Consumer)` variants.

Yeah, sure. Do you have any suggests for a name? I liked run/call being similar to `Runnable` and `Callable`.

**Comment by Azquelt** [comment]
Oh, another thing that occurred to me, it might be preferable to have a variant of `call(Consumer)` that throws an exception if the service is not present.

I expect that the most common use case is that you're going to expect the service to be present and care if it is not.

`call(Function)` is more explicit in that it expects you to handle an `Optional`

**Comment by tjwatson** [comment]
> Oh, another thing that occurred to me, it might be preferable to have a variant of `call(Consumer)` that throws an exception if the service is not present.

Because we have no current references to `call(Consumer)` I think I can wait until there is a need for that.  Even then, if the calling code cared they could just use the function equivalent instead to get the Optional.

> Yeah, sure. Do you have any suggests for a name? I liked run/call being similar to Runnable and Callable.

I think a `run(Function)` variant is fine.  We run the `Function` vs. call the `Consumer`.

**Comment by Azquelt** [comment]
I don't really like it because the use of `call` and `run` is now the opposite of `Callable` and `Runnable`, but I think it's more important to resolve the ambiguity.

#build

**Comment by Azquelt** [comment]
@tjwatson Forgot to tag you. I've switched around the names of `call` and `run` and this is ready for re-review.

#libby

**Review by tjwatson — APPROVED** [review]
Thanks, LGTM

**Comment by tjwatson** [comment]
> https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=0ee58201-5c1d-418d-93ce-95902f722650 has errors/failures.

Are the failures in the MP TCKs related to this change?

**Comment by Azquelt** [comment]
> > https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=0ee58201-5c1d-418d-93ce-95902f722650 has errors/failures.
> 
> Are the failures in the MP TCKs related to this change?

I don't think so.

I picked a couple of buckets at random to look at. From the Rest Client TCK log, it looks like it took almost 45 minutes to start the test run, then about 15 minutes to run the test. Similarly the Health 4.0 bucket shows that it didn't get to start the test, with the maven build having taken almost an hour to do a clean and then get the dependencies.

Those look like infrastructure issues and are not related to this change. Based on that and that the RTC build (which has now finished) does not show the same problems, I'm going to go ahead with merging this.

**Pull request merged**
