### PR TITLE
Update mpOpenAPI-2.0 Artifacts

### LINKED ISSUE #15451: Consume OpenAPI 2.x
As MicroProfile OpenAPI 2.0 is now available, Open Liberty should be updated to consume the newest versions of the MicroProfile API. 

Currently, these are OpenAPI 2.0, and OpenAPI 2.1.0-RC2.

This stems from https://github.com/OpenLiberty/open-liberty/issues/11020#issuecomment-755738602

### PR DESCRIPTION
**Pull request by scottcurtis2605**
Updated references to consume `mpOpenAPI-2.0` using MP2.0 and SmallRye 2.1.0-RC2 libraries from artifactory.

resolves #15451

#build 
#spawn.fullfat.buckets=com.ibm.ws.microprofile.openapi_fat,com.ibm.ws.microprofile.openapi_fat_tck,com.ibm.ws.microprofile.openapi.1.1_fat_tck,io.openliberty.microprofile.openapi.2.0.internal_fat,io.openliberty.microprofile.openapi.2.0.internal_fat_tck

### CODE REVIEW

**Review by Emily-Jiang — APPROVED** [review]

**Comment by scottcurtis2605** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.microprofile.openapi_fat,com.ibm.ws.microprofile.openapi_fat_tck,com.ibm.ws.microprofile.openapi.1.1_fat_tck,io.openliberty.microprofile.openapi.2.0.internal_fat,io.openliberty.microprofile.openapi.2.0.internal_fat_tck

**Comment by wraschke** [comment]
#run-libby-bot

**Comment by wraschke** [comment]
Another test.

**Review by Joseph-Cass — APPROVED** [review]
LGTM :)

**Review by msmiths — APPROVED** [review]
LGTM

**Comment by wraschke** [comment]
Hello, this is just a test comment.

**Pull request merged**
