### PR TITLE
spnego fat fix - delete vbs scripts in afterRule

### PR DESCRIPTION
**Pull request by Zech-Hein**
Fix for issue #24883

### CODE REVIEW

**Comment by Zech-Hein** [comment]
#build #libby

**Review by wrodrig — DISMISSED** [review]

**Comment by Zech-Hein** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.security.spnego_fat,com.ibm.ws.security.spnego_fat.1,com.ibm.ws.security.spnego_fat.2

**Comment by Zech-Hein** [comment]
build results look good. ui failure is unrelated to the changes.

**Comment by Zech-Hein** [comment]
#libby

**Review by wrodrig — APPROVED** [review]
Approve, pending Build results

**Pull request merged**
