### PR TITLE
Update Java 20 FAT WAR with GA Java 20 build

### PR DESCRIPTION
**Pull request by gjwatts**
This PR will update the Java 20 FAT WAR with one built from the GA level of Java 20.

### CODE REVIEW

**Review by jgrassel — APPROVED** [review]

**Comment by gjwatts** [comment]
#build

**Comment by gjwatts** [comment]
#pbbeta

**Comment by gjwatts** [comment]
I also have a Java 20 build running against this branch.

**Comment by gjwatts** [comment]
#libbybot

**Comment by gjwatts** [comment]
The Java 20 build also completed successfully.  Merging.

**Pull request merged**
