### PR TITLE
Check var dir files on restore and monitor config files after restore

### PR DESCRIPTION
**Pull request by tjwatson**

### CODE REVIEW

**Comment by tjwatson** [comment]
#build

**Comment by tjwatson** [comment]
#build

**Review by dazavala — DISMISSED** [review]
I've one concern, but approved in case the concern is moot.

At line 138 the ctor for `ConfigVariableRegistry` passes a lambda behavior into method `processVarFiles()`.  And at line 200 method processVarFiles() invokes the passed behavior with `java.io.File` args (`f`, `varFile`).  To maintain the same behavior as the previous version of the ctor, the call to `f.getName()` within the passed behavior cannot end with ".properties".   Is this true and do we care?

**Comment by tjwatson** [comment]
#build

**Review by dazavala — APPROVED** [review]
Changes in [Only process as properties files if in root variables folder](https://github.com/OpenLiberty/open-liberty/pull/27950/commits/16360098d2b2bc283e4794a6ddfd42d4e56cb3cc) look good.

**Comment by tjwatson** [comment]
#libby

**Pull request merged**
