### PR TITLE
Add xxxContainer versionless features

### LINKED ISSUE #29224: Versionless: Enable xxxContainer features as versionless features
"xxxContainer" features were not enabled as versionless features for the initial GA:

- data
- faces / jsf
- persistence / jpa
- jsonb
- jsonp

https://github.com/OpenLiberty/docs/issues/7522 is the doc issue for this change
https://github.com/OpenLiberty/open-liberty/issues/29571 is the GA blog issue for this change

### PR DESCRIPTION
**Pull request by jhanders34**
- Update test case to handle noship and beta features and generate the features with the right kind / edition
- Add processing of Container features for Java / Jakarta EE
- Add Container versionless feature files

Fixes #29224

- [x] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [x] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [x] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

### CODE REVIEW

**Review by rsherget — APPROVED** [review]
LGTM pending good build

**Comment by tbitonti** [comment]
Created issue #29224

**Comment by tbitonti** [comment]
Created issue #29225 to add corresponding feature resolver FAT test data for the new features.

**Review by tbitonti — APPROVED** [review]
Looks good.
I created issue #29225 to fill in resolver FAT data for the new features.

**Comment by jhanders34** [comment]
#build

**Pull request merged**
