### PR TITLE
Test to demonstrate FFDC on tran log delete at shutdown

### LINKED ISSUE #23869: In a peer recovery environment a long running tran may generate an FFDC at shutdown
Use this issue to deliver a test that demonstrates this problem.

### PR DESCRIPTION
**Pull request by neilgsyoung**
fixes #23869

### CODE REVIEW

**Comment by neilgsyoung** [comment]
#build

**Review by jonhawkes — DISMISSED** [review]

**Comment by neilgsyoung** [comment]
#run-libby-bot

**Comment by neilgsyoung** [comment]
#build

**Review by jonhawkes — APPROVED** [review]

**Comment by wraschke** [comment]
Hi, Neil. Unfortunately, we must revert this PR because it introduced build breaks in many com.ibm.ws.transaction.cloud_fat.* buckets running in LAOS continuous builds. Please see https://ibm-cloud.slack.com/archives/C30NGUQ9E/p1674079512958969 for details.

**Pull request merged**
