### PR TITLE
Issue #13096: Add mdb-4.0 feature

### PR DESCRIPTION
**Pull request by tkburroughs**
Added the new mdb-4.0 feature for Jakarta EE 9
(Jakarta Enterprise Beans 4.0)

for #13096

### CODE REVIEW

**Comment by tkburroughs** [comment]
#build

**Comment by tkburroughs** [comment]
#run-libby-bot

**Comment by andrea-pichler** [comment]
No message review requested from L2

**Comment by tkburroughs** [comment]
#run-libby-bot

**Comment by tkburroughs** [comment]
#build

**Comment by tkburroughs** [comment]
#run-libby-bot

**Comment by tkburroughs** [comment]
#build

**Comment by tkburroughs** [comment]
#build

**Comment by tkburroughs** [comment]
#build

**Comment by tkburroughs** [comment]
#build

**Comment by tkburroughs** [comment]
1 test failure is a known issue; unrelated to this change.

**Pull request merged**
