### PR TITLE
Restructure test class packages for consistency

### LINKED ISSUE #14623: restructure jsfContainer_2.2_fat test classes for consistency with jsfContainer_2.3_fat
Minor changes so the package structure for the two test buckets is the same and makes comparing classes a bit easier when debugging issues between the two buckets.

### PR DESCRIPTION
**Pull request by pnicolucci**
fixes #14623

### CODE REVIEW

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Review by volosied — APPROVED** [review]
LGTM

**Review by isaacrivriv — APPROVED** [review]
LGTM

**Comment by pnicolucci** [comment]
#run-libby-bot

**Pull request merged**
