### PR TITLE
PH52739 - Use the new file utilities to create temporary files.

### PR DESCRIPTION
**Pull request by WhiteCat22**
Update Resteasy Core and Multipart Provider to 4.8.9.Final

### CODE REVIEW

**Comment by WhiteCat22** [comment]
#libby #build

**Comment by WhiteCat22** [comment]
Fixes #PH52739

**Review by jim-krueger — APPROVED** [review]
Looks like you found a couple that needed to be upgraded from 4.7.0 to 4.7.2 as well.  LGTM

**Comment by WhiteCat22** [comment]
Fixes #PH53883

**Pull request merged**
