### PR TITLE
Fix issue #4806 - First WebServer should use default host

### PR DESCRIPTION
**Pull request by tjwatson**
Same as PR #4826 for issue #4806 to fix this for 18.0.0.3

Libby please #build

### CODE REVIEW

**Comment by tjwatson** [comment]
#build

**Comment by tjwatson** [comment]
All failures on in other buckets that do not use Spring Boot features.

**Comment by tjwatson** [comment]
The latest build has errors in other buckets not related or using the Spring Boot features.  This pull request only changes the spring boot feature and its tests.

**Comment by tevans78** [comment]
Merging into 18003

**Pull request merged**
