### PR TITLE
 beta autoCloseConnections (HandleList)

### PR DESCRIPTION
**Pull request by njr-11**
Beta the HandleList implementation, which is enbaled via the autoCloseConnections property of connectionManager.

### CODE REVIEW

**Comment by njr-11** [comment]
#build

**Comment by njr-11** [comment]
Build failed on feature validation where a beta autofeature activates based on ga features only.  After discussion with Tom Evans, one approach to take here is to have the auto-feature GA but with all of its actual function beta-guarded, which is achieved by the autoCloseConnections beta metatype attribute.  The autofeature only aids in collecting the appropriate data for the autoCloseConnections implementation to use.
#build
#run-libby-bot

**Comment by njr-11** [comment]
#build

**Comment by njr-11** [comment]
#build

**Review by aguibert — APPROVED** [review]

**Comment by njr-11** [comment]
The previous build was good enough for delivery, but we didn't have approval yet.
I'm requesting another build because it has been a few weeks.
#build

**Pull request merged**
