### PR TITLE
dnslookup to simple regex

### PR DESCRIPTION
**Pull request by una-tapa**
This PR is associated with following issue. 
https://github.com/OpenLiberty/open-liberty/issues/15336

### CODE REVIEW

**Comment by una-tapa** [comment]
#build

**Comment by una-tapa** [comment]
Since it does not make sense to create additional test cases for regex test, I create a standalone Java program below. 
https://github.com/una-tapa/SimpleIpAddressTestWithRegex/blob/main/IpAddressTestOutput.txt

**Review by wrodrig — APPROVED** [review]
Code looks good, standalone test code looks good, also the build failure is not related to your code. Thanks for your hard work on these changes 😄

**Comment by una-tapa** [comment]
#build

**Comment by una-tapa** [comment]
I submitted the second build with automated full test.  The webcontainer error no longer appears.  It must have been the timing issue in the first build.  Screenshot (Target locations of links might be accessible only to IBM employees.)  https://ibm.box.com/s/ano1x1pn51jlahrgnjyirkd7wgfwqfi5

**Comment by una-tapa** [comment]
#build

**Comment by una-tapa** [comment]
Received positive feedback.  Proceeding with merge after one more build since it has been a while.

**Comment by una-tapa** [comment]
100% unit test.  The fvt results has 2 SSL signer issues with client. 
This is irrelevant with this issue (dnslookup & regex) Merging and closing this issue.

**Pull request merged**
