### PR TITLE
fix installFeature .esa case

### LINKED ISSUE #23478: NullPointerException in InstallFeatureAction for .esa files
Executing `./featureUtility installFeature x.esa` with any .esa file results in a NullPointerException. It doesn't matter whether the file exists or not, as it's the file existence check that throws the exception.

```
null
java.lang.NullPointerException
        at com.ibm.ws.install.internal.InstallUtils.getFeatureName(InstallUtils.java:794)
        at com.ibm.ws.install.featureUtility.cli.InstallFeatureAction.esaInstallInit(InstallFeatureAction.java:188)
        at com.ibm.ws.install.featureUtility.cli.InstallFeatureAction.handleFeatureArguments(InstallFeatureAction.java:169)
        at com.ibm.ws.install.featureUtility.cli.InstallFeatureAction.initialize(InstallFeatureAction.java:128)
        at com.ibm.ws.install.featureUtility.cli.InstallFeatureAction.handleTask(InstallFeatureAction.java:74)
        at com.ibm.ws.install.featureUtility.cli.FeatureAction.handleTask(FeatureAction.java:100)
        at com.ibm.ws.install.featureUtility.FeatureUtilityExecutor.main(FeatureUtilityExecutor.java:58)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.ibm.ws.kernel.boot.cmdline.UtilityMain.internal_main(UtilityMain.java:173)
        at com.ibm.ws.kernel.boot.cmdline.UtilityMain.main(UtilityMain.java:53)
        at com.ibm.ws.kernel.boot.cmdline.Main.main(Main.java:52)
```
https://github.com/OpenLiberty/open-liberty/commit/a0b4a6d3f6a755d0a563e43471b81d6eb71cbf6e removed the initialization of the private `esaFile` field, so the subsequent call to `InstallUtils.getFeatureName(esaFile)` now throws a NullPointerException when checking if the supplied `File` exists as it doesn't do a null check.

### PR DESCRIPTION
**Pull request by jjiwooLim**
Fixes #23478

### CODE REVIEW

**Comment by jjiwooLim** [comment]
#build

**Comment by jjiwooLim** [comment]
#build

**Review by bensonlatibm — APPROVED** [review]
lgtm!

**Comment by jjiwooLim** [comment]
#libby-bot

**Pull request merged**
