### PR TITLE
Remove ignoreDuplicateEJBBindings beta metatype we decided to not support

### PR DESCRIPTION
**Pull request by olendvcook**
#13161

### CODE REVIEW

**Comment by olendvcook** [comment]
@OpenLiberty/message-reviewer I'm removing a BETA metatype element so id review not needed.

**Comment by olendvcook** [comment]
#build

**Comment by andrea-pichler** [comment]
No message review requested from L2

**Comment by olendvcook** [comment]
build has unrelated failures

**Comment by tkburroughs** [comment]
@olendvcook merged

**Pull request merged**
