### PR TITLE
Get providerMetadata from Discovery and allow for null metadata on serialization

### PR DESCRIPTION
**Pull request by kristip17**
Resolve fetching the providerMetadata from Discovery during OidcIdentityStore.validate. 
- Added unit tests to MetadataUtilsTest and OpenIdContextImplTest
- Did the Json/JSON conversion in `io.openliberty.security.jakartasec.3.0.internal` because doing it in MetadataUtils required feature changes that seemed like it would have excessive changes (multi FATs had feature checker failures for Json).
- Added an FFDC ignore to the FAT test, which seemed appropriate for the test intention (no providerURL which is the FFDC produced with these changes)

While working on this PR, realized that the serialization for OpenIdContextImpl didn't account for a null providerMetadata. 
- Added a boolean for having providerMetadata or not
- Updated the unit test, OpenIdContextImplSerializationTest. The diff is a little tricky -- I made a common method to check all the field and two tests for null/not null conditions.

Per prior discussion, removed `private String state; // TODO: Determine if storage values can be obtained without relying on state.`

### CODE REVIEW

**Comment by kristip17** [comment]
#build
#spawn.fullfat.buckets=io.openliberty.security.jakartasec.3.0.internal_fat,io.openliberty.security.jakartasec.3.0.internal_fat.config

**Comment by kristip17** [comment]
Build failure is a known issue in a different bucket.

**Review by ayoho — APPROVED** [review]

**Comment by kristip17** [comment]
#build
#spawn.fullfat.buckets=io.openliberty.security.jakartasec.3.0.internal_fat,io.openliberty.security.jakartasec.3.0.internal_fat.config,io.openliberty.security.jakartasec.3.0.internal_fat.refresh,io.openliberty.security.jakartasec.3.0.internal_fat.logout

**Comment by kristip17** [comment]
Two failures in the PB are known issues.

**Comment by kristip17** [comment]
#libby

**Pull request merged**
