### PR TITLE
update weld-5.1.1.SP1 to weld-5.1.1.SP2

### LINKED ISSUE #29555: weld 5.1.1.SP1 has a memory leak and should be updated to (at least) 5.1.1.SP2
**Describe the bug**  
weld 5.1.1.SP1 has a memory leak (which we are effected of).
bug description is here: https://issues.redhat.com/browse/WELD-2750

**Steps to Reproduce**  
see WELD-Bug description

**Expected behavior**  
an upgrade of weld to at least 5.1.1.SP2 should be done.

in fact we patched openliberty to get the changes of weld-5.1.1.SP2 and the memory leak was gone. And we didn't see any negative side-effects.

The upgrade to 5.1.1.SP2 shouldn't be too risky anyway, since the bugfix of this leak ist the only change between 5.1.1.SP1 and 5.1.1.SP2.

But there would also be more recent versions of weld available (5.1.2.Final or even 5.1.3.Final) with more fixes.

### PR DESCRIPTION
**Pull request by pellmont**
Fixes #29555 memory leak in weld

- [ x] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [ x] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).

### CODE REVIEW

**Comment by pellmont** [comment]
we patched openliberty 24.0.0.3 and following versions and use the patched version in several production applications. Could not find any negative side effects

**Comment by pellmont** [comment]
@benjamin-confino I saw you updated weld to 5.1.1.SP1 in the past. What do you think?

**Comment by benjamin-confino** [comment]
@pellmont It all looks good to me. There is a more recent version of weld we should reconsume but I see no reason not to merge this PR until we get around to doing that. Assuming a personal build is good of course.

**Comment by benjamin-confino** [comment]
#build

**Review by benjamin-confino — APPROVED** [review]

**Comment by pellmont** [comment]
Thanks @benjamin-confino

**Comment by pellmont** [comment]
> I cannot process this build request due to one or both of the following:
> - The comment author is not a member of the organization.
> - The pull request creator did not send a signed CLA.

?
Do i have to sign and send a CLA for each OpenLiberty-PR separately?

**Comment by Azquelt** [comment]
No, you only need to sign it once. You can ignore that message.

**Comment by websterc87** [comment]
Apologies about the confusing message, I will raise a task to improve our internal tooling to be less confusing.

**Comment by benjamin-confino** [comment]
The build (run on another PR as per the process for external contributions) https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=97466ec6-ea9c-4326-bf2c-2b7316486ce8&tab=Analysis was good. I'll merge this in.

Thank you @pellmont :)

**Pull request merged**
