### PR TITLE
Update features to not include public / protected tolerates

### PR DESCRIPTION
**Pull request by jhanders34**
- To aid user feature and product extension feature developers that want to support EE 6 through EE 10 like our value-add features do, these changes are necessary to not require the user feature to depend need to include a transitive dependency that is not possible because it will cause a conflict.  This excludes the expected EE features that have the same prefix for all EE levels: com.ibm.websphere.appserver.jdbc-4.x, com.ibm.websphere.appserver.servlet-x.y and com.ibm.websphere.appserver.transaction-x.y
- MicroProfile, openapi and opentracing features are not following this convention today, but could in the future to allow user features and product extensions to be able to support all MicroProfile features.
- Update io.openliberty.connectors-2.0.internal and io.openliberty.connectors-2.1.internal to io.openliberty.connectors.internal base name with 2.0 and 2.1 versions.  These features were private and they cause confusion with the existing public io.openliberty.connectors based feature names.
- Add FAT that uses a user feature that shows can support all EE levels.  FAT test uses a user feature that have private features to different EE levels.  This FAT shows that auto features are not required in order to do this since we are not doing tolerates.  With the name change for features, it would be impossible to not require the tolerates to flow to the user feature without the update in this PR.

### CODE REVIEW

**Comment by jhanders34** [comment]
#build

**Comment by jhanders34** [comment]
#libby #build

**Comment by jhanders34** [comment]
#libby #build

**Review by mswatosh — DISMISSED** [review]
Bean Validation changes look good to me

**Review by tkburroughs — DISMISSED** [review]
EJB Changes look good

**Comment by jhanders34** [comment]
#libby #build

**Review by njr-11 — APPROVED** [review]

**Review by tkburroughs — APPROVED** [review]

**Pull request merged**
