### PR TITLE
Remove unavailable ASM packages from JPA thirdparty declaration

### PR DESCRIPTION
**Pull request by dazey3**
Feature Checker has been failing with these errors:
```
22009config10/error.xml:    <issue level="INFO" short="[MISSING_3RDPARTYSPECINTERNAL_PACKAGE org.eclipse.persistence.internal.libraries.asm.util@null]">INFO  feature com.ibm.websphere.appserver.jpa-2.1 declared org.eclipse.persistence.internal.libraries.asm.util@null as ibm-api but the package was not seen exported by any bundle, package was declared as ibm-api with types of [third-party] (This message is informational, because the package is not declared to be ibm-api/ibm-spi)</issue>
22009config10/error.xml:    <issue level="INFO" short="[MISSING_3RDPARTYSPECINTERNAL_PACKAGE org.eclipse.persistence.internal.libraries.asm.xml@null]">INFO  feature com.ibm.websphere.appserver.jpa-2.1 declared org.eclipse.persistence.internal.libraries.asm.xml@null as ibm-api but the package was not seen exported by any bundle, package was declared as ibm-api with types of [third-party] (This message is informational, because the package is not declared to be ibm-api/ibm-spi)</issue>
```

It appears that when 2.6_WAS was updated (https://github.com/OpenLiberty/open-liberty/pull/19457), the latest EclipseLink ASM has removed these packages. We need to also remove these packages from our feature thirdparty declaration as well.

Signed-off-by: Will Dazey <dazeydev.3@gmail.com>

### CODE REVIEW

**Comment by dazey3** [comment]
#build

**Review by jhanders34 — DISMISSED** [review]

**Comment by dazey3** [comment]
#build

**Comment by dazey3** [comment]
#build

**Comment by dazey3** [comment]
#build

**Review by jhanders34 — DISMISSED** [review]

**Comment by jhanders34** [comment]
feature checker changes are now in release

#libby #build

**Comment by dazey3** [comment]
#build

**Review by jhanders34 — APPROVED** [review]

**Comment by jhanders34** [comment]
#libby

**Pull request merged**
