### PR TITLE
Fix resteasy when mpConfig-3.0 is present

### PR DESCRIPTION
**Pull request by tevans78**
The RestEasy classes were still able to find the MP Config classes. This PR prevents that from happening and allows the two features to work at the same time. At some point soon the integration will need to be done properly. This is just a stop-gap solution.

### CODE REVIEW

**Comment by tevans78** [comment]
#build

**Review by andymc12 — APPROVED** [review]
LGTM - thanks @tevans78!

**Review by andymc12 — APPROVED** [review]
Updates look good - thanks again.

**Comment by tevans78** [comment]
#build

**Comment by tevans78** [comment]
#run-libby-bot

**Pull request merged**
