### PR TITLE
Migrate JPA Query FAT Loop Query XML tests to OL.

### PR DESCRIPTION
**Pull request by jgrassel**
Adding the XML version of the Loop Query tests.

### CODE REVIEW

**Comment by jgrassel** [comment]
#build

**Review by dazey3 — APPROVED** [review]
LGTM

**Comment by jgrassel** [comment]
#build

**Comment by jgrassel** [comment]
#run-libby-bot
#build

**Comment by jgrassel** [comment]
#build
#run-libby-bot

**Comment by jgrassel** [comment]
#build

Kicking off another build, looks like the build machine hung.

**Comment by jgrassel** [comment]
#build

Build died again, rebasing and trying again.

**Comment by jgrassel** [comment]
Rebase exposed the fat changes to failures caused by changes brought in by the rebase. #build #run-libby-bot

**Pull request merged**
