### PR TITLE
Pull Request for Issue #1815 fix view action to flow

### PR DESCRIPTION
**Pull request by jsartoris**
Pull Request for Issue #1815

### CODE REVIEW

**Comment by jsartoris** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jsf.2.3_fat,com.ibm.ws.jsf.2.2_fat_jsf2.3,com.ibm.ws.jsf_fat_jsf2.3,com.ibm.ws.jsf_fat_lWAS_jsf2.3

**Comment by jsartoris** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jsf.2.3_fat,com.ibm.ws.jsf.2.2_fat_jsf2.3,com.ibm.ws.jsf_fat_jsf2.3,com.ibm.ws.jsf_fat_lWAS_jsf2.3

**Comment by jsartoris** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jsf.2.3_fat,com.ibm.ws.jsf.2.2_fat_jsf2.3,com.ibm.ws.jsf_fat_jsf2.3,com.ibm.ws.jsf_fat_lWAS_jsf2.3

**Comment by pnicolucci** [comment]
Jay can you attach this as a patch to the MyFaces issue you have opened and I'll commit it this weekend so we can get it into a snapshot build?

**Comment by jsartoris** [comment]
Thanks Paul.  Yes, I'll get a patch attached.  I just want to make sure this personal build is clean first.

**Pull request merged**
