### PR TITLE
Fix WIMRegistryException that occurs when there is a delimiter in the username

### LINKED ISSUE #7464: getUserAltName Unexpected Exception retrieving user security name -- only when federatedRepository is not configured in XML configuration (NullPointerException)
[4/8/19 15:20:03:711 PDT] 00001437 id=00000000 LibertyAuthHelper W getUserAltName Unexpected Exception retrieving user security name
com.ibm.websphere.security.CustomRegistryException
at com.ibm.ws.security.registry.internal.UserRegistryWrapper.getUserSecurityName(UserRegistryWrapper.java:138)
at com.ibm.smai.cscs.ftmahelper.bundle.util.LibertyAuthHelper.getUserAltName(LibertyAuthHelper.java:139)
at com.ibm.apm.cscs.ftmahelper.bundle.FtmaHelperBean.getUserAltName(FtmaHelperBean.java:1979)
at com.ibm.apm.cscs.ftmahelper.bundle.FtmaHelperBean.getUserAltName(FtmaHelperBean.java:1982)
at com.ibm.apm.cscs.ftmahelper.bundle.FtmaHelperBean.getUserAltName(FtmaHelperBean.java:1982)
at Proxyc1a89987_a110_4b40_9dbf_bc6bf87d33e8.getUserAltName(Unknown Source)
at com.ibm.smai.cscs.rest.resource.UsersResource.getAllUsers(UsersResource.java:130)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
at java.lang.reflect.Method.invoke(Method.java:508)
at org.apache.wink.server.internal.handlers.InvokeMethodHandler.handleRequest(InvokeMethodHandler.java:63)
at org.apache.wink.server.handlers.AbstractHandler.handleRequest(AbstractHandler.java:33)
at org.apache.wink.server.handlers.RequestHandlersChain.handle(RequestHandlersChain.java:26)
at org.apache.wink.server.handlers.RequestHandlersChain.handle(RequestHandlersChain.java:22)
...
...
Caused by: com.ibm.ws.security.registry.RegistryException
at com.ibm.ws.security.wim.registry.WIMUserRegistry.getUserSecurityName(WIMUserRegistry.java:332)
at com.ibm.ws.security.registry.internal.UserRegistryWrapper.getUserSecurityName(UserRegistryWrapper.java:136)
... 87 more
Caused by: java.lang.NullPointerException
at com.ibm.ws.security.wim.registry.util.BridgeUtils.seperateIDAndRealm(BridgeUtils.java:257)
at com.ibm.ws.security.wim.registry.util.BridgeUtils.separateIDAndRealm(BridgeUtils.java:222)
at com.ibm.ws.security.wim.registry.util.SecurityNameBridge.getUserSecurityName(SecurityNameBridge.java:81)
at com.ibm.ws.security.wim.registry.WIMUserRegistry.getUserSecurityName(WIMUserRegistry.java:327)
... 88 more

### PR DESCRIPTION
**Pull request by agiridharan**
fixes #7464

### CODE REVIEW

**Comment by agiridharan** [comment]
#build

**Comment by agiridharan** [comment]
#build

**Comment by agiridharan** [comment]
#build

**Comment by agiridharan** [comment]
#build

**Comment by agiridharan** [comment]
#build

**Comment by agiridharan** [comment]
#build

**Comment by jvanhill** [comment]
@agiridharan - Please clean up the PR as we had talked and then close it.

**Pull request closed without merging**
