### PR TITLE
Issue #19405: Reduce the number of server restarts

### LINKED ISSUE #19405: Reduce server restarts for Servlet 4.0 WCResponseHeadersTest.java

### PR DESCRIPTION
**Pull request by pnicolucci**
fixes #19405

### CODE REVIEW

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
The usual execution time was around 16.5 minutes we've now gotten it down to about 11 minutes

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
#build

**Review by mrsaldana — APPROVED** [review]
LGTM, thanks!

**Comment by pnicolucci** [comment]
#libby

**Pull request merged**
