### PR TITLE
fattest.simplicity updates

### PR DESCRIPTION
**Pull request by jhanders34**
- Synchronize with websphere liberty fattest.simplicity
- Remove websphere specific config elements from ServerConfiguration
- Update to make some things extendable in order for it to be extended in websphere liberty specific subclasses
- Remove all calls to RemoteFile constructor and rely on Machine.getFile() to create a RemoteFile which may be a subclass

 Update com.ibm.ws.rest.handler FATs for HttpsRequest changes
- Changes from using HttpUtils to set HttpsURLConnections to using HttpsRequest methods to set things.  HttpsRequest doesn't use HttpsUrlConnection any longer so need to set things up to pass things to the connection / request.
- Update URLs to encode special characters like brackets that were not encoded.  Apache commons httpclient doesn't support brackets not being encoded because it uses URI where HttpsUrlConnection was using URL.

### CODE REVIEW

**Comment by jhanders34** [comment]
#build

**Comment by jhanders34** [comment]
#libby #build

**Comment by jhanders34** [comment]
#build

**Comment by jhanders34** [comment]
#libby #build

**Comment by jhanders34** [comment]
#libby

**Comment by jhanders34** [comment]
#build

**Comment by jhanders34** [comment]
#libby #build

**Comment by jhanders34** [comment]
#libby

**Comment by jhanders34** [comment]
#build

**Comment by jhanders34** [comment]
#libby #build

**Comment by jhanders34** [comment]
#build

**Comment by jhanders34** [comment]
#libby #build

**Comment by jhanders34** [comment]
#build

**Comment by jhanders34** [comment]
#build

**Comment by jhanders34** [comment]
#build

**Comment by jhanders34** [comment]
@KyleAure I added you on review for overall review of the changes and both you and @njr-11  specifically for commit #3.

**Review by KyleAure — APPROVED** [review]
Changes for testcontainer's look good.

**Review by njr-11 — APPROVED** [review]

**Comment by jhanders34** [comment]
#libby

**Pull request merged**
