### PR TITLE
Repeat com.ibm.ws.microprofile.openapi_fat

### PR DESCRIPTION
**Pull request by tevans78**
This PR replaces https://github.com/OpenLiberty/open-liberty/pull/19137

### CODE REVIEW

**Comment by tevans78** [comment]
#build

**Comment by tevans78** [comment]
#build

**Review by Azquelt — APPROVED** [review]

**Comment by tevans78** [comment]
#build

**Comment by tevans78** [comment]
#libby

**Comment by tevans78** [comment]
#build

**Comment by tevans78** [comment]
#build

**Comment by tevans78** [comment]
#libby

**Pull request merged**
