### PR TITLE
Enable JSF 2.2 JSFCompELTests for Faces 4.0 (EE10)

### PR DESCRIPTION
**Pull request by pnicolucci**
for #22369

### CODE REVIEW

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
Java 17 build: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_GTw7kE6IEe2fv7PFprXZfA

**Comment by pnicolucci** [comment]
Java 17 tests were successful

**Review by isaacrivriv — APPROVED** [review]
Changes look good to me, thanks!

**Pull request merged**
