### PR TITLE
Changing trace message being tested and code cleanup

### PR DESCRIPTION
**Pull request by tonyreigns**
- [x] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [x] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [x] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

Fixes: RTC #301000

After further investigation, the string the trace test was using, was reverted yesterday...https://github.com/OpenLiberty/open-liberty/commit/988c8decc9046b88af21ea698e9986a08761ae97

### CODE REVIEW

**Comment by tonyreigns** [comment]
#build

**Comment by tonyreigns** [comment]
#build

**Comment by tonyreigns** [comment]
After further investigation, the string the trace test was using, was reverted yesterday...https://github.com/OpenLiberty/open-liberty/commit/988c8decc9046b88af21ea698e9986a08761ae97

**Comment by tonyreigns** [comment]
#build

**Comment by tonyreigns** [comment]
#build

**Review by pgunapal — APPROVED** [review]
LGTM

**Pull request merged**
