### PR TITLE
Clean up special handling for old Java releases

### PR DESCRIPTION
**Pull request by jhanders34**
Update test code to remove code for older Java versions
- Remove special code for Java 6 and Java 7
- Remove MinimumJavaLevel annotations for Java 8 since that is now the minimum Java level for all testing and code.

Update runtime code to not have handling for old Java releases
- Remove special handling for Java 6 and Java 7.
- Use java.util.Base64 for doing encoding and decoding without the special handling for older Java versions and the use of reflection.
- Use java.time instead of JAXB now always and remove the special handling for older java versions and the use of reflection.

### CODE REVIEW

**Comment by jhanders34** [comment]
#build

**Comment by jhanders34** [comment]
#build
#libby

**Comment by olendvcook** [comment]
> Use java.time instead of JAXB now always and remove the special handling for older java versions and the use of reflection.

I specifically reviewed just this part so I'm not going to mark my review as "approved" yet, but this part looks good to me.

**Comment by jhanders34** [comment]
> I only looked at the logging and opentracing changes. Please remove the unused `import componenttest.annotation.MinimumJavaLevel;`

@fmhwong I have removed the unused imports for MinimumJavaLevel.

**Comment by jhanders34** [comment]
#libby

**Comment by jhanders34** [comment]
#libby

**Pull request merged**
