### PR TITLE
Adding Test Case and TestMode tags

### LINKED ISSUE #18604: WCResponseHeadersTest needs to have a mix of `FULL` and `LITE` mode tests and add test case
Organize tests in `FULL` and `LITE` modes and add the following test:

Adding a simple test for the remove option for when the configured header is not present on the response. The expected behavior is for the response to be unaffected by the header being missing.

### PR DESCRIPTION
**Pull request by mrsaldana**
fixes #18604

Adding a simple test for the `remove` option for when the configured header is not present on the response. The expected behavior is for the response to be unaffected by the header being missing. 

This PR also sets some of the baseline configuration tests to run only when TestMode is set to FULL.

### CODE REVIEW

**Comment by mrsaldana** [comment]
#build

**Comment by mrsaldana** [comment]
#build

**Review by pnicolucci — APPROVED** [review]

**Comment by mrsaldana** [comment]
#build

**Comment by mrsaldana** [comment]
#run-libby-bot

**Pull request merged**
