### PR TITLE
support ehcache config files (using version 2 schema) and ws-security.cache.config.file option for wss4j

### PR DESCRIPTION
**Pull request by arunavemulapalli**

### CODE REVIEW

**Comment by arunavemulapalli** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.wssecurity_fat.wsscxf,com.ibm.ws.wssecurity_fat.wsscxf.1,com.ibm.ws.wssecurity_fat.wsscxf.saml,com.ibm.ws.wssecurity_fat.wsscxf.saml.1,com.ibm.ws.wssecurity_fat.wsscxf.saml.2,com.ibm.ws.wssecurity_fat.wsscxf.saml.3,com.ibm.ws.wssecurity_fat.wsscxf.saml.4,com.ibm.ws.wssecurity_fat.wsscxf.saml.5

**Comment by arunavemulapalli** [comment]
#build

**Review by neuwerk — APPROVED** [review]
Changes look good to me!

**Comment by arunavemulapalli** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.wssecurity_fat.wsscxf,com.ibm.ws.wssecurity_fat.wsscxf.saml.1

**Comment by arunavemulapalli** [comment]
#libby

**Comment by arunavemulapalli** [comment]
#libby

**Comment by arunavemulapalli** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.wssecurity_fat.wsscxf,com.ibm.ws.wssecurity_fat.wsscxf.saml.1

**Comment by arunavemulapalli** [comment]
#libby

**Pull request merged**
