### PR TITLE
App prereq monitor fix

### PR DESCRIPTION
**Pull request by joe-chacko**
#build

### CODE REVIEW

**Comment by joe-chacko** [comment]
#build

**Comment by joe-chacko** [comment]
There are several failures, but only one that isn't explained by an existing defect.
There is an intermittent server quiesce timeout in one of the app prereq tests.
I've enabled additional trace to see what is holding up server quiesce, so we'll need another #build

**Comment by joe-chacko** [comment]
#build

**Comment by joe-chacko** [comment]
#build

**Review by AndrewDJBanks — DISMISSED** [review]

**Comment by joe-chacko** [comment]
#build

**Comment by joe-chacko** [comment]
#libbybot

**Comment by joe-chacko** [comment]
#build #run-libby-bot

**Comment by joe-chacko** [comment]
#build

**Review by AndrewDJBanks — DISMISSED** [review]

**Comment by joe-chacko** [comment]
#build

**Comment by joe-chacko** [comment]
#build again just for kicks

**Review by AndrewDJBanks — APPROVED** [review]

**Comment by AndrewDJBanks** [comment]
#libbybot

**Pull request merged**
