### PR TITLE
PII NLS Returns from 19005 Shipment 1

### PR DESCRIPTION
**Pull request by pnickoll**

### CODE REVIEW

**Comment by pnickoll** [comment]
#build

**Comment by andrea-pichler** [comment]
Hi @pnickoll 
can you please clarify which messages need an L2 review? I don't speak all the languages so am wondering what exactly to review.
Many thanks in advance!
Andrea

**Comment by pnickoll** [comment]
@andrea-pichler  None of these messages need a L2 review as far as I know. I believe L2 only check the English files

**Comment by pnickoll** [comment]
#build

**Pull request merged**
