### PR TITLE
Removal of suppressUncovered.. from metatype.  Additional Servlet3.1 check

### PR DESCRIPTION
**Pull request by una-tapa**
Issue #3520

### CODE REVIEW

**Comment by sishida** [comment]
The two lines were deleted from dev/com.ibm.ws.app.manager/resources/OSGI-INF/l10n/metatype.properties, correct? If that's all, I will mark this pull request as "ID review not needed." :)

Please let me know if you need review for any additional changes. Thank you!

**Comment by una-tapa** [comment]
@sishida Yes, it was decided we remove configuration option for `suppressUncoveredHttpWarning` (along with any doc about it) as there's another function that achieve the same goal.   It is good to know that doc team was already notified and took a quick review on update in metatype.   For details,  please refer to Issue #3520.  Thanks!

**Comment by una-tapa** [comment]
#build

**Comment by una-tapa** [comment]
#build

**Comment by una-tapa** [comment]
#build

**Comment by una-tapa** [comment]
Finally good build  Asking for review.

**Comment by una-tapa** [comment]
@brenthdaniel  Thank you!!

**Pull request merged**
