### PR TITLE
Update Open Liberty Welcome Page

### LINKED ISSUE #29802: The Gitter link in the default page returns 404
**Describe the bug**
The Gitter link in the following default page (http://localhost:9080/) returns 404. Also, the Twitter link should be updated because Twitter was renamed to X.

Screenshot 2024-10-08 at 10 07 13 AM

**Steps to Reproduce**  
- Go to https://openliberty.io/start/ to generate a starter project
- unzip the project
- run `./mvnw liberty:dev`
- visit http://localhost:9080

**Expected behavior**  
- Gitter link should return to https://app.gitter.im/#/room/#OpenLiberty_development:gitter.im
- Twitter link should be removed or renamed to X

**Diagnostic information:**  
 - OpenLiberty Version: tried with OL 24.0.0.10
 - Affected feature(s): not sure
 - Java Version: any supported version
 - server.xml configuration (WITHOUT sensitive information like passwords)
   - see it from a starter project 
 - If it would be useful, upload the messages.log file found in `$WLP_OUTPUT_DIR/messages.log`

**Additional context**  
None

### PR DESCRIPTION
**Pull request by pmd1nh**
- [X] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [X] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [X] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

################################################################################################
Updated link to `Gitter` and removed Twitter.

fixes #29802

### CODE REVIEW

**Comment by pmd1nh** [comment]
cherry-pick from #29885

**Comment by pmd1nh** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.transport.http_test

**Comment by pmd1nh** [comment]
Local test
image

Also verify Gitter link is working.

image

**Comment by pmd1nh** [comment]
#libby

**Comment by pmd1nh** [comment]
iPad pro simulated view

image

**Review by isaacrivriv — APPROVED** [review]
Changes look okay to me, thanks for working on this. My only comment is now the spacing is a little messed up and we did our best to make it look okay but in wide screens where the divs of first and second row are shown one next to the other, the spacing of the removed logo is noticeable. We'll have to work on another way of making this look even if possible.

**Comment by pmd1nh** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.transport.http_test

**Comment by pmd1nh** [comment]
#libby

**Comment by gkwan-ibm** [comment]
hi @pmd1nh 

I knew you fixed the issue but closed [Rivaldo's PR](https://github.com/OpenLiberty/open-liberty/pull/29885). His contribution was ignored from the commits. Is there a hole in the process for any third-party (from non WAS users or non IBMers) contribution?

**Pull request merged**
