### PR TITLE
Jakarta Data spec API updates post M3

### PR DESCRIPTION
**Pull request by njr-11**
These updates to the Jakarta Data API can go in now that we have passed the cutoff for the beta of Jakarta Data M3.

### CODE REVIEW

**Comment by njr-11** [comment]
#build

**Review by mswatosh — APPROVED** [review]

**Comment by njr-11** [comment]
#build

**Comment by njr-11** [comment]
#build

**Comment by njr-11** [comment]
This build completed successfully with all tests passing.
> https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=ac627a32-c814-4826-adf3-acbdcafa4cc4 completed.

**Pull request merged**
