### PR TITLE
Change to use proper intantiation of EntityPart objects.

### LINKED ISSUE #22884: Enable EE10 spec multipart support to work along side the IBM  proprietary multipart support
Currently the EE10 spec version of multipart support has been disabled to allow the IBM proprietary multipart support from JAXRS 2.1 and EE9 to function.   Prior to EE10 GA both alternatives should function.

### PR DESCRIPTION
**Pull request by jim-krueger**
Fixes #22884 
Changed the new EE10 multipart tests to instantiate the EntityPart objects correctly rather than using the internal use builder.

### CODE REVIEW

**Comment by jim-krueger** [comment]
#run-libby-bot

**Comment by jim-krueger** [comment]
#run-libby-bot

**Comment by jim-krueger** [comment]
#libby-build

**Comment by jim-krueger** [comment]
#build

**Review by WhiteCat22 — APPROVED** [review]

**Comment by jim-krueger** [comment]
#build

**Pull request merged**
