### PR TITLE
Update CXF rt-core version

### PR DESCRIPTION
**Pull request by andymc12**
The updated code in this module guards against loading 
bus-extensions.txt files from JAX-RS bundles.  The JAX-RS CXF bundles
have bus-extensions.txt files that will conflict with those used by
JAX-WS causing runtime failures.  Bypassing the JAX-RS bundles allows
the JAX-WS runtime to run successfully.

### CODE REVIEW

**Comment by andymc12** [comment]
#build

**Comment by andymc12** [comment]
#build

**Comment by andymc12** [comment]
#build

**Comment by wraschke** [comment]
#build

**Comment by wraschke** [comment]
#build

**Comment by andymc12** [comment]
Just #build dang it all!

**Pull request merged**
