### PR TITLE
update to get oidc provider without accessing request parameter or header

### LINKED ISSUE #29221: openid connect client feature fails SRVE0216E: post body contains less bytes than specified by content-length
- openidConnectClient feature in WLP 24.0.0.3 cause failure accessing body/payload of the POST request 

**stack trace**
`Messages.log: [7/17/24, 22:31:30:148 EDT] 00000328 com.ibm.ws.webcontainer.srt E SRVE0133E: An error occurred while parsing parameters. {0} java.io.IOException: SRVE0216E: post body contains less bytes than specified by content-length at com.ibm.ws.webcontainer.servlet.RequestUtils.getPostBody(RequestUtils.java:252) at com.ibm.ws.webcontainer.servlet.RequestUtils.parsePostData(RequestUtils.java:288) at com.ibm.ws.webcontainer.servlet.RequestUtils.parsePostDataLong(RequestUtils.java:308) at com.ibm.ws.webcontainer31.srt.SRTServletRequest31.parsePostData(SRTServletRequest31.java:303) at com.ibm.ws.webcontainer.srt.SRTServletRequest.parseParameters(SRTServletRequest.java:2447) at com.ibm.ws.webcontainer.srt.SRTServletRequest.getParameter(SRTServletRequest.java:1974) at javax.servlet.ServletRequestWrapper.getParameter(ServletRequestWrapper.java:194) at com.ibm.mdr.common.CommonServletRequest.getParameter(CommonServletRequest.java:89) at com.ibm.webnav.servlet.WnTransactionManager.processTransaction(WnTransactionManager.java:820) at com.ibm.webnav.servlet.WnTransactionThread.run(WnTransactionThread.java:143)`

**Diagnostic information:**  
 - OpenLiberty Version: [24.0.0.3 ]
 - Affected feature(s) [openidConnectClient-1.0]

### PR DESCRIPTION
**Pull request by arunavemulapalli**
- [x] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [x] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [x] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".
fixes #29221

### CODE REVIEW

**Comment by arunavemulapalli** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.security.oidc.client_fat.1,com.ibm.ws.security.oidc.client_fat.2,com.ibm.ws.security.oidc.client_fat.e2e,com.ibm.ws.security.oidc.client_fat.jaxrs,com.ibm.ws.security.oidc.client_fat.saml,com.ibm.ws.security.oidc.client_fat.spnego,com.ibm.ws.security.oidc.server_fat.app-passwords,com.ibm.ws.security.oidc.server_fat.app-passwords.DerbyDB.jwt,com.ibm.ws.security.oidc.server_fat.app-passwords.DerbyDB.opaque,com.ibm.ws.security.oidc.server_fat.app-passwords.LocalStore.jwt,com.ibm.ws.security.oidc.server_fat.app-passwords.LocalStore.opaque,com.ibm.ws.security.oidc.server_fat.app-tokens,com.ibm.ws.security.oidc.server_fat.app-tokens.DerbyDB.jwt,com.ibm.ws.security.oidc.server_fat.app-tokens.DerbyDB.opaque,com.ibm.ws.security.oidc.server_fat.app-tokens.LocalStore.jwt,com.ibm.ws.security.oidc.server_fat.app-tokens.LocalStore.opaque,com.ibm.ws.security.oidc.server_fat.clientregistration,com.ibm.ws.security.oidc.server_fat.config,com.ibm.ws.security.oidc.server_fat.config.oauth,com.ibm.ws.security.oidc.server_fat.config.oidc,com.ibm.ws.security.oidc.server_fat.endpoint.authorize,com.ibm.ws.security.oidc.server_fat.endpoint.coveragemap,com.ibm.ws.security.oidc.server_fat.endpoint.discovery,com.ibm.ws.security.oidc.server_fat.endpoint.end_session,com.ibm.ws.security.oidc.server_fat.endpoint.introspect,com.ibm.ws.security.oidc.server_fat.endpoint.revoke,com.ibm.ws.security.oidc.server_fat.endpoint.token,com.ibm.ws.security.oidc.server_fat.endpoint.userinfo,com.ibm.ws.security.oidc.server_fat.feature,com.ibm.ws.security.oidc.server_fat.granttype.jwt,com.ibm.ws.security.oidc.server_fat.gui.tokenMgmt,com.ibm.ws.security.oidc.server_fat.jaxrs,com.ibm.ws.security.oidc.server_fat.oidc,com.ibm.ws.security.oidc.server_fat.saml,com.ibm.ws.security.social_fat,com.ibm.ws.security.social_fat.LibertyOP.1,com.ibm.ws.security.social_fat.LibertyOP.2,com.ibm.ws.security.social_fat.OpenShift,com.ibm.ws.security.social_fat.delegated,com.ibm.ws.security.social_fat.multiProvider,com.ibm.ws.security.oidc.client_fat.backchannelLogout.1,com.ibm.ws.security.oidc.client_fat.backchannelLogout.2,com.ibm.ws.security.oidc.client_fat.backchannelLogout.saml.1,com.ibm.ws.security.oidc.client_fat.backchannelLogout.saml.2,com.ibm.ws.security.oidc.server_fat.backchannelLogout,com.ibm.ws.security.social_fat.LibertyOP.backchannelLogout.1,com.ibm.ws.security.social_fat.LibertyOP.backchannelLogout.2

**Comment by arunavemulapalli** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.security.oidc.client_fat.1,com.ibm.ws.security.oidc.client_fat.2,com.ibm.ws.security.oidc.client_fat.3,com.ibm.ws.security.oidc.client_fat.4,com.ibm.ws.security.oidc.client_fat.e2e,com.ibm.ws.security.oidc.client_fat.jaxrs,com.ibm.ws.security.oidc.client_fat.saml,com.ibm.ws.security.oidc.client_fat.spnego,com.ibm.ws.security.oidc.client_fat.claimPropagation,com.ibm.ws.security.social_fat,com.ibm.ws.security.social_fat.LibertyOP.1,com.ibm.ws.security.social_fat.LibertyOP.2,com.ibm.ws.security.social_fat.LibertyOP.3,com.ibm.ws.security.social_fat.OpenShift,com.ibm.ws.security.social_fat.delegated,com.ibm.ws.security.social_fat.multiProvider,com.ibm.ws.security.oidc.client_fat.backchannelLogout.1,com.ibm.ws.security.oidc.client_fat.backchannelLogout.2,com.ibm.ws.security.oidc.client_fat.backchannelLogout.saml.1,com.ibm.ws.security.oidc.client_fat.backchannelLogout.saml.2,com.ibm.ws.security.oidc.server_fat.backchannelLogout,com.ibm.ws.security.social_fat.LibertyOP.backchannelLogout.1,com.ibm.ws.security.social_fat.LibertyOP.backchannelLogout.2

**Comment by arunavemulapalli** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.security.oidc.client_fat.1,com.ibm.ws.security.oidc.client_fat.2,com.ibm.ws.security.oidc.client_fat.3,com.ibm.ws.security.oidc.client_fat.4,com.ibm.ws.security.oidc.client_fat.e2e,com.ibm.ws.security.oidc.client_fat.jaxrs,com.ibm.ws.security.oidc.client_fat.saml,com.ibm.ws.security.oidc.client_fat.spnego,com.ibm.ws.security.oidc.client_fat.claimPropagation,com.ibm.ws.security.social_fat,com.ibm.ws.security.social_fat.LibertyOP.1,com.ibm.ws.security.social_fat.LibertyOP.2,com.ibm.ws.security.social_fat.LibertyOP.3,com.ibm.ws.security.social_fat.OpenShift,com.ibm.ws.security.social_fat.delegated,com.ibm.ws.security.social_fat.multiProvider,com.ibm.ws.security.oidc.client_fat.backchannelLogout.1,com.ibm.ws.security.oidc.client_fat.backchannelLogout.2,com.ibm.ws.security.oidc.client_fat.backchannelLogout.saml.1,com.ibm.ws.security.oidc.client_fat.backchannelLogout.saml.2,com.ibm.ws.security.oidc.server_fat.backchannelLogout,com.ibm.ws.security.social_fat.LibertyOP.backchannelLogout.1,com.ibm.ws.security.social_fat.LibertyOP.backchannelLogout.2

**Review by ayoho — APPROVED** [review]

**Comment by arunavemulapalli** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.security.oidc.client_fat.1,com.ibm.ws.security.oidc.client_fat.2,com.ibm.ws.security.oidc.client_fat.3,com.ibm.ws.security.oidc.client_fat.4,com.ibm.ws.security.oidc.client_fat.e2e,com.ibm.ws.security.oidc.client_fat.jaxrs,com.ibm.ws.security.oidc.client_fat.saml,com.ibm.ws.security.oidc.client_fat.spnego,com.ibm.ws.security.oidc.client_fat.claimPropagation,com.ibm.ws.security.social_fat,com.ibm.ws.security.social_fat.LibertyOP.1,com.ibm.ws.security.social_fat.LibertyOP.2,com.ibm.ws.security.social_fat.LibertyOP.3,com.ibm.ws.security.social_fat.OpenShift,com.ibm.ws.security.social_fat.delegated,com.ibm.ws.security.social_fat.multiProvider,com.ibm.ws.security.oidc.client_fat.backchannelLogout.1,com.ibm.ws.security.oidc.client_fat.backchannelLogout.2,com.ibm.ws.security.oidc.client_fat.backchannelLogout.saml.1,com.ibm.ws.security.oidc.client_fat.backchannelLogout.saml.2,com.ibm.ws.security.oidc.server_fat.backchannelLogout,com.ibm.ws.security.social_fat.LibertyOP.backchannelLogout.1,com.ibm.ws.security.social_fat.LibertyOP.backchannelLogout.2

**Comment by arunavemulapalli** [comment]
build looks good except one failure and one error (both look unrelated to the changes in this pr)
merging

**Pull request merged**
