### PR TITLE
Memory leak when using NAPTR lookups

### LINKED ISSUE #28266: Investigate possible memory leak in sipcontainer
Opening this issue to investigate a possible memory leak seen in websphere liberty server in a deployment running a SIP proxy application.

### PR DESCRIPTION
**Pull request by TiborBeres**
Memory leak seen in sipcontainer when dnsAutoResolve is set to true. 

Fixes #28266

### CODE REVIEW

**Comment by TiborBeres** [comment]
#build
 ([view Open Liberty Personal Build](https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?pipelineId=e540220b-b852-433f-82b9-25bdd83ba2f5) - :x: completed with errors/failures.)
#fat.buckets.to.run=com.ibm.ws.sipcontainer_fat,com.ibm.ws.sipcontainer_fat_1,com.ibm.ws.sipcontainer_fat_2,com.ibm.ws.sipcontainer_fat_3,com.ibm.ws.sipcontainer_fat_4,com.ibm.ws.sipcontainer_fat_5,com.ibm.ws.sipcontainer_fat_6,com.ibm.ws.sipcontainer_fat_7
#spawn.fullfat.buckets=com.ibm.ws.sipcontainer_fat,com.ibm.ws.sipcontainer_fat_1,com.ibm.ws.sipcontainer_fat_2,com.ibm.ws.sipcontainer_fat_3,com.ibm.ws.sipcontainer_fat_4,com.ibm.ws.sipcontainer_fat_5,com.ibm.ws.sipcontainer_fat_6,com.ibm.ws.sipcontainer_fat_7 

_Note: Target locations of links might be accessible only to IBM employees._

**Comment by TiborBeres** [comment]
Liberty build only contains known intermittent test failures, failing in one run and passing in a consequent run

**Comment by TiborBeres** [comment]
#build
 ([view Open Liberty Personal Build](https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?pipelineId=db993659-b1ae-4151-9760-3fdb621114fc) - :x: completed with errors/failures.)
#fat.buckets.to.run=com.ibm.ws.sipcontainer_fat,com.ibm.ws.sipcontainer_fat_1,com.ibm.ws.sipcontainer_fat_2,com.ibm.ws.sipcontainer_fat_3,com.ibm.ws.sipcontainer_fat_4,com.ibm.ws.sipcontainer_fat_5,com.ibm.ws.sipcontainer_fat_6,com.ibm.ws.sipcontainer_fat_7
#spawn.fullfat.buckets=com.ibm.ws.sipcontainer_fat,com.ibm.ws.sipcontainer_fat_1,com.ibm.ws.sipcontainer_fat_2,com.ibm.ws.sipcontainer_fat_3,com.ibm.ws.sipcontainer_fat_4,com.ibm.ws.sipcontainer_fat_5,com.ibm.ws.sipcontainer_fat_6,com.ibm.ws.sipcontainer_fat_7

_Note: Target locations of links might be accessible only to IBM employees._

**Comment by volosied** [comment]
Closing in favor of #30437

**Pull request closed without merging**
