### PR TITLE
Dump threads on a server timeout

### PR DESCRIPTION
**Pull request by brenthdaniel**
Adding debug when an embedded server start times out in minify tests

### CODE REVIEW

**Comment by brenthdaniel** [comment]
#build

**Comment by brenthdaniel** [comment]
#build

**Comment by brenthdaniel** [comment]
The personal build failures are caused by a different work item, but I'm going to run another build just to be safe given that this is in the same area. 

#build

**Review by hlhoots — APPROVED** [review]
LGTM

**Comment by brenthdaniel** [comment]
#run-libby-bot

**Comment by brenthdaniel** [comment]
The last build had failures that haven't been seen before, but seem to be related to a failure to create a keystore in secure web services tests. That code could not possibly be affected by the test code that was changed here.

**Pull request merged**
