### PR TITLE
Remove unused imports web container

### LINKED ISSUE #11805: Remove unused imports in WebContainer.java
Remove unused imports from WebContainer.java

### PR DESCRIPTION
**Pull request by pnicolucci**
fixes #11805

### CODE REVIEW

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
@pmd1nh he can add what ever imports he needs when/if he delivers any code. As it is right now this is unused. Objections to merging?

**Comment by pmd1nh** [comment]
k, approved

**Comment by pnicolucci** [comment]
#run-libby-bot

**Pull request merged**
