### PR TITLE
Set current deployment when shutting down app

### LINKED ISSUE #17382: Port PH34673 to OpenLiberty
On twas APAR PH34673 a customer hit an NPE because CDI.current() did not work during a thread that was shutting down an application. To fix this we set the current deployment thread local in CDIContainerImpl when an app shuts down.

### PR DESCRIPTION
**Pull request by benjamin-confino**
This fixes #17382

### CODE REVIEW

**Comment by benjamin-confino** [comment]
#build

**Review by Emily-Jiang — APPROVED** [review]

**Comment by benjamin-confino** [comment]
#build

**Comment by benjamin-confino** [comment]
#build

**Comment by benjamin-confino** [comment]
#build

**Comment by benjamin-confino** [comment]
#build

**Comment by benjamin-confino** [comment]
#run-libby-bot

**Pull request merged**
