### PR TITLE
experiment with concurrency async

### PR DESCRIPTION
**Pull request by njr-11**
Experiment with the `@Asynchronous` equivalent that is being considered for Concurrency 3.0.
Specifically, this looks at how this could integrate with managed CompletableFutures that are backed by a ManagedExecutorService, including things like thread context and exceptional completion and getting access to the completable future instance that will actually be returned by the caller so that the method could decide to end prematurely if it was canceled or forcibly completed by other means. Some more exploration is still needed, but this is at least a starting point.

### CODE REVIEW

**Comment by njr-11** [comment]
#build

**Comment by njr-11** [comment]
#run-libby-bot
#build

**Comment by njr-11** [comment]
#run-libby-bot
#build

**Comment by njr-11** [comment]
#build

**Comment by njr-11** [comment]
#build

**Comment by njr-11** [comment]
#build
#run-libby-bot

**Comment by njr-11** [comment]
#build

**Review by KyleAure — APPROVED** [review]

**Pull request merged**
