### PR TITLE
Tests to validate issuer as filter 

### PR DESCRIPTION
**Pull request by c00crane**
Create tests to validate the behavior of issuer as filter with JWT access tokens.
Test behavior with combinations of config attributes in oidcConnectClients:
   authFilters (with good/bad, without)
   issuerIdentifier (with match/do not match what is in an access_token (and what the provider specifies), and without a value - use what would be the "default" issuer value of http(s)//hostname:port/oidc/endpoint/<providerId> and some other string
Test behavior when specifying oidcAuthnHint or oidc_client in the header.
Test behavior when an opaque access_token token is used.
Test behavior when a JWE access_token is used.

### CODE REVIEW

**Comment by c00crane** [comment]
ID - This pull will only deliver the FAT - the product changes will be delivered using a separate pull.  I'll update this pull once Teddy delivers his changes.

**Comment by c00crane** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.security.oidc.client_fat.1,com.ibm.ws.security.oidc.client_fat.2,com.ibm.ws.security.oidc.client_fat.jaxrs,com.ibm.ws.security.oidc.client_fat.spnego,com.ibm.ws.security.oidc.server_fat.jaxrs.config,com.ibm.ws.security.oidc.server_fat.oidc,com.ibm.ws.security.oidc.server_fat.spnego,com.ibm.ws.security.oidc.social_fat.backchannelLogout,com.ibm.ws.security.oidc.social_fat.claimPropagation,com.ibm.ws.security.saml.sso_fat,com.ibm.ws.security.saml.sso_fat.2,com.ibm.ws.security.saml.sso_fat.3,com.ibm.ws.security.saml.sso_fat.config,com.ibm.ws.security.saml.sso_fat.config.mapToUserRegistry,com.ibm.ws.security.saml.sso_fat.endpoint.samlmetadata,com.ibm.ws.security.saml.sso_fat.jaxrs,com.ibm.ws.security.saml.sso_fat.jaxrs.config,com.ibm.ws.security.saml.sso_fat.logout,com.ibm.ws.security.saml.sso_fat.logout.httpServletRequest,com.ibm.ws.security.saml.sso_fat.logout.ibm_security_logout,com.ibm.ws.security.saml.sso_fat.logout.IDP_initiated,com.ibm.ws.security.social_fat,com.ibm.ws.security.social_fat.commonTest.LibertyOP,com.ibm.ws.security.social_fat.delegated,com.ibm.ws.security.social_fat.LibertyOP.1,com.ibm.ws.security.social_fat.LibertyOP.2,com.ibm.ws.security.social_fat.multiProvider,com.ibm.ws.security.social_fat.okdServiceLogin,com.ibm.ws.security.social_fat.OpenShift

**Comment by c00crane** [comment]
#run-libby-bot

**Comment by c00crane** [comment]
Updated commits with a small change to the product code from Teddy.

**Review by teddyjtorres — APPROVED** [review]

**Comment by teddyjtorres** [comment]
#libby

**Comment by c00crane** [comment]
Merged with integration and running a new build just to make sure all is good with the latest code.
#run-libby-bot
#build
#spawn.fullfat.buckets=com.ibm.ws.security.oidc.client_fat.1,com.ibm.ws.security.oidc.client_fat.2,com.ibm.ws.security.oidc.client_fat.jaxrs,com.ibm.ws.security.oidc.client_fat.spnego,com.ibm.ws.security.oidc.server_fat.jaxrs.config,com.ibm.ws.security.oidc.server_fat.oidc,com.ibm.ws.security.oidc.server_fat.spnego,com.ibm.ws.security.oidc.social_fat.backchannelLogout,com.ibm.ws.security.oidc.social_fat.claimPropagation,com.ibm.ws.security.saml.sso_fat,com.ibm.ws.security.saml.sso_fat.2,com.ibm.ws.security.saml.sso_fat.3,com.ibm.ws.security.saml.sso_fat.config,com.ibm.ws.security.saml.sso_fat.config.mapToUserRegistry,com.ibm.ws.security.saml.sso_fat.endpoint.samlmetadata,com.ibm.ws.security.saml.sso_fat.jaxrs,com.ibm.ws.security.saml.sso_fat.jaxrs.config,com.ibm.ws.security.saml.sso_fat.logout,com.ibm.ws.security.saml.sso_fat.logout.httpServletRequest,com.ibm.ws.security.saml.sso_fat.logout.ibm_security_logout,com.ibm.ws.security.saml.sso_fat.logout.IDP_initiated,com.ibm.ws.security.social_fat,com.ibm.ws.security.social_fat.commonTest.LibertyOP,com.ibm.ws.security.social_fat.delegated,com.ibm.ws.security.social_fat.LibertyOP.1,com.ibm.ws.security.social_fat.LibertyOP.2,com.ibm.ws.security.social_fat.multiProvider,com.ibm.ws.security.social_fat.okdServiceLogin,com.ibm.ws.security.social_fat.OpenShift

**Pull request merged**
