### PR TITLE
GA all MicroProfile 4.0 features and remove beta guards for MP JWT 1.2

### LINKED ISSUE #14993: Remove beta guards from MP JWT 1.2 feature
Move the feature to GA and remove all the beta guards.

### PR DESCRIPTION
**Pull request by ayoho**
Resolves #14993

### CODE REVIEW

**Comment by ayoho** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.security.mp.jwt.1.1_fat,com.ibm.ws.security.mp.jwt.1.2_fat

**Comment by ayoho** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.security.mp.jwt.1.1_fat,com.ibm.ws.security.mp.jwt.1.2_fat

**Comment by ayoho** [comment]
Good personal build: https://wasrtc.hursley.ibm.com:9443/jazz/resource/itemOid/com.ibm.team.build.BuildResult/_stJjQGV6EeugLoxDBRF4WA

**Comment by ayoho** [comment]
#libby

**Comment by tevans78** [comment]
Also resolves https://github.com/OpenLiberty/open-liberty/issues/15651

**Review by Emily-Jiang — APPROVED** [review]

**Comment by ayoho** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.security.mp.jwt.1.1_fat,com.ibm.ws.security.mp.jwt.1.2_fat

**Comment by tevans78** [comment]
Just a single UI failure in the PB (unrelated to this change). Merging.

**Pull request merged**
