### PR TITLE
Tolerate CWWKC1503W in testTimerFailsOverWhenServerStops

### PR DESCRIPTION
**Pull request by aguibert**
#build

### CODE REVIEW

**Review by njr-11 — APPROVED** [review]

**Comment by aguibert** [comment]
new build: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_42LLYA_XEeuo9On9wZGDtQ

**Review by njr-11 — APPROVED** [review]

**Comment by aguibert** [comment]
new build: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_e9iJUBIPEeuFUN9G2T7ZeA

**Comment by aguibert** [comment]
new build: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_Row_UBPKEeuFUN9G2T7ZeA

**Comment by aguibert** [comment]
#run-libby-bot

**Pull request merged**
