### PR TITLE
Changes to deliver EclipseLink Snapshot 5.0.0.20240807

### PR DESCRIPTION
**Pull request by ajaypaul-ibm**
This PR contains the changes needed for EclipseLink Snapshot 5.0.0.20240807

### CODE REVIEW

**Comment by tkburroughs** [comment]
#libby

**Comment by jhanders34** [comment]
#libby

**Comment by ajaypaul-ibm** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jpa.tests.beanvalidation_jpa_3.2_fat,com.ibm.ws.jpa.tests.container.checkpoint_jpa_3.2_fat,com.ibm.ws.jpa.tests.container.client_fat,com.ibm.ws.jpa.tests.eclipselink_jpa_3.2_fat,com.ibm.ws.jpa.tests.eclipselink.query_jpa_3.2_fat,com.ibm.ws.jpa.tests.jpa_32_fat,com.ibm.ws.jpa.tests.jpaconfig_jpa_3.2_fat,com.ibm.ws.jpa.tests.spec10.callback_jpa_3.2_fat,com.ibm.ws.jpa.tests.spec10.embeddable_jpa_3.2_fat,com.ibm.ws.jpa.tests.spec10.entity_jpa_3.2_fat,com.ibm.ws.jpa.tests.spec10.entitymanager_jpa_3.2_fat,com.ibm.ws.jpa.tests.spec10.inheritance_jpa_3.2_fat,com.ibm.ws.jpa.tests.spec10.injection.defaultPersistenceUnit_fat,com.ibm.ws.jpa.tests.spec10.injection.dfi_fat,com.ibm.ws.jpa.tests.spec10.injection.dmi_fat,com.ibm.ws.jpa.tests.spec10.injection.ejbinwar_fat,com.ibm.ws.jpa.tests.spec10.injection.jarfile_fat,com.ibm.ws.jpa.tests.spec10.injection.jndi_fat,com.ibm.ws.jpa.tests.spec10.injection.mdb_fat,com.ibm.ws.jpa.tests.spec10.issues_fat,com.ibm.ws.jpa.tests.spec10.packaging_jpa_3.2_fat,com.ibm.ws.jpa.tests.spec10.query_jpa_3.2_fat,com.ibm.ws.jpa.tests.spec10.relationships.manyXmany_jpa_3.2_fat,com.ibm.ws.jpa.tests.spec10.relationships.manyXone_jpa_3.2_fat,com.ibm.ws.jpa.tests.spec10.relationships.oneXmany_jpa_3.2_fat,com.ibm.ws.jpa.tests.spec10.relationships.oneXone_jpa_3.2_fat,com.ibm.ws.jpa.tests.spec20_jpa_3.2_fat,com.ibm.ws.jpa.tests.spec21.cdi_fat,com.ibm.ws.jpa.tests.spec21.issues_fat,com.ibm.ws.jpa.tests.spec21.txsynchronization_fat

**Review by tkburroughs — APPROVED** [review]

**Comment by ajaypaul-ibm** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jpa.tests.beanvalidation_jpa_3.2_fat,com.ibm.ws.jpa.tests.container.checkpoint_jpa_3.2_fat,com.ibm.ws.jpa.tests.container.client_fat,com.ibm.ws.jpa.tests.eclipselink_jpa_3.2_fat,com.ibm.ws.jpa.tests.eclipselink.query_jpa_3.2_fat,com.ibm.ws.jpa.tests.jpa_32_fat,com.ibm.ws.jpa.tests.jpaconfig_jpa_3.2_fat,com.ibm.ws.jpa.tests.spec10.callback_jpa_3.2_fat,com.ibm.ws.jpa.tests.spec10.embeddable_jpa_3.2_fat,com.ibm.ws.jpa.tests.spec10.entity_jpa_3.2_fat,com.ibm.ws.jpa.tests.spec10.entitymanager_jpa_3.2_fat,com.ibm.ws.jpa.tests.spec10.inheritance_jpa_3.2_fat,com.ibm.ws.jpa.tests.spec10.injection.defaultPersistenceUnit_fat,com.ibm.ws.jpa.tests.spec10.injection.dfi_fat,com.ibm.ws.jpa.tests.spec10.injection.dmi_fat,com.ibm.ws.jpa.tests.spec10.injection.ejbinwar_fat,com.ibm.ws.jpa.tests.spec10.injection.jarfile_fat,com.ibm.ws.jpa.tests.spec10.injection.jndi_fat,com.ibm.ws.jpa.tests.spec10.injection.mdb_fat,com.ibm.ws.jpa.tests.spec10.issues_fat,com.ibm.ws.jpa.tests.spec10.packaging_jpa_3.2_fat,com.ibm.ws.jpa.tests.spec10.query_jpa_3.2_fat,com.ibm.ws.jpa.tests.spec10.relationships.manyXmany_jpa_3.2_fat,com.ibm.ws.jpa.tests.spec10.relationships.manyXone_jpa_3.2_fat,com.ibm.ws.jpa.tests.spec10.relationships.oneXmany_jpa_3.2_fat,com.ibm.ws.jpa.tests.spec10.relationships.oneXone_jpa_3.2_fat,com.ibm.ws.jpa.tests.spec20_jpa_3.2_fat,com.ibm.ws.jpa.tests.spec21.cdi_fat,com.ibm.ws.jpa.tests.spec21.issues_fat,com.ibm.ws.jpa.tests.spec21.txsynchronization_fat

**Comment by ajaypaul-ibm** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jpa.tests.beanvalidation_jpa_3.2_fat,com.ibm.ws.jpa.tests.container.checkpoint_jpa_3.2_fat,com.ibm.ws.jpa.tests.container.client_fat,com.ibm.ws.jpa.tests.eclipselink_jpa_3.2_fat,com.ibm.ws.jpa.tests.eclipselink.query_jpa_3.2_fat,com.ibm.ws.jpa.tests.jpa_32_fat,com.ibm.ws.jpa.tests.jpaconfig_jpa_3.2_fat,com.ibm.ws.jpa.tests.spec10.callback_jpa_3.2_fat,com.ibm.ws.jpa.tests.spec10.embeddable_jpa_3.2_fat,com.ibm.ws.jpa.tests.spec10.entity_jpa_3.2_fat,com.ibm.ws.jpa.tests.spec10.entitymanager_jpa_3.2_fat,com.ibm.ws.jpa.tests.spec10.inheritance_jpa_3.2_fat,com.ibm.ws.jpa.tests.spec10.injection.defaultPersistenceUnit_fat,com.ibm.ws.jpa.tests.spec10.injection.dfi_fat,com.ibm.ws.jpa.tests.spec10.injection.dmi_fat,com.ibm.ws.jpa.tests.spec10.injection.ejbinwar_fat,com.ibm.ws.jpa.tests.spec10.injection.jarfile_fat,com.ibm.ws.jpa.tests.spec10.injection.jndi_fat,com.ibm.ws.jpa.tests.spec10.injection.mdb_fat,com.ibm.ws.jpa.tests.spec10.issues_fat,com.ibm.ws.jpa.tests.spec10.packaging_jpa_3.2_fat,com.ibm.ws.jpa.tests.spec10.query_jpa_3.2_fat,com.ibm.ws.jpa.tests.spec10.relationships.manyXmany_jpa_3.2_fat,com.ibm.ws.jpa.tests.spec10.relationships.manyXone_jpa_3.2_fat,com.ibm.ws.jpa.tests.spec10.relationships.oneXmany_jpa_3.2_fat,com.ibm.ws.jpa.tests.spec10.relationships.oneXone_jpa_3.2_fat,com.ibm.ws.jpa.tests.spec20_jpa_3.2_fat,com.ibm.ws.jpa.tests.spec21.cdi_fat,com.ibm.ws.jpa.tests.spec21.issues_fat,com.ibm.ws.jpa.tests.spec21.txsynchronization_fat

**Pull request closed without merging**
