### PR TITLE
Remove duplicate NLS message bundles for MP Metrics

### LINKED ISSUE #17493: Add common bundle for MP Metrics 1.x/2.x/3.x NLS messages
Related to: https://github.com/OpenLiberty/open-liberty/issues/17353

Currently, the NLS messages for each MP Health version is copied over and duplicated, which shows duplicated messages in https://www.ibm.com/docs/en/was-liberty/core?topic=messages-cwmmc, since the messageIDs are duplicated.

Multiple message bundles should not re-use the same messageIDs in more than one messages bundle.

Solution:
Place the NLS messages in a common bundle so every version, it uses the common messages bundle.
Update that common message bundle for future addition of NLS messages.

### PR DESCRIPTION
**Pull request by Channyboy**
#build 
fixes #17493

### CODE REVIEW

**Comment by Channyboy** [comment]
#build 
#run-libby-bot

**Comment by Channyboy** [comment]
Message review not needed as this is consolidation of messages into a central file.

**Comment by Channyboy** [comment]
The bundles that are expected to contain the NLS messages are not packaged in the build. Kicking off another build:
#build

**Comment by Channyboy** [comment]
#build 
#run-libby-bot
Running another build after successful custom build here: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_0G2ooNghEeujOaz2UKTqBQ

**Review by fmhwong — APPROVED** [review]
LGTM

**Comment by Channyboy** [comment]
The build con was at level 2 when this PR was approved.
Will re-run a PB to ensure no issues.
#build

**Comment by Channyboy** [comment]
Build failed to fetch WS-CD... rebuilding: #build

**Pull request merged**
