### PR TITLE
Actually call the Java 20 FAT test

### PR DESCRIPTION
**Pull request by gjwatts**
Actually call the Java 20 FAT test

### CODE REVIEW

**Comment by gjwatts** [comment]
#build

**Review by jgrassel — DISMISSED** [review]

**Comment by wraschke** [comment]
#pbbeta

**Comment by gjwatts** [comment]
Force push to just rename confusing FAT name from testJava19App to testJava20App.  No code was changed.

**Review by jgrassel — APPROVED** [review]

**Comment by gjwatts** [comment]
#libbybot

**Comment by gjwatts** [comment]
All the tests passed in the Java 20 build.  Merging.

**Comment by gjwatts** [comment]
Resulting failures in build gjwatts-24669-20230313-1202 were unrelated (connection failure to RTC).  The FAT tests passed fine, but irrelevant since they ran under Java 11 and the affected FAT only runs under Java 20.

**Pull request merged**
