### PR TITLE
set service ranking

### PR DESCRIPTION
**Pull request by benjamin-confino**
fixes https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.workitem.viewWorkItem&id=296993

### CODE REVIEW

**Comment by benjamin-confino** [comment]
#build

**Comment by benjamin-confino** [comment]
#build

**Review by tjwatson — APPROVED** [review]

**Comment by benjamin-confino** [comment]
#build 
#spawn.fullfat.buckets=com.ibm.ws.microprofile.health.2.0_fat

**Review by pgunapal — APPROVED** [review]

**Review by tjwatson — CHANGES_REQUESTED** [review]
This change should no longer be needed with the fix in PR #26032 merged.

**Comment by benjamin-confino** [comment]
No longer needed as this was fixed in the web component.

**Pull request closed without merging**
