### PR TITLE
Issue #4882 - update release version to 18.0.0.4

### LINKED ISSUE #4882: Update release and microversions after baselines have been updated
Next version is 18.0.0.4
Next microversion is 23

### PR DESCRIPTION
**Pull request by tevans78**
#build 
fixes #4882

### CODE REVIEW

**Comment by tevans78** [comment]
#build

**Comment by tevans78** [comment]
#build

**Comment by tevans78** [comment]
#build

**Comment by naumanna** [comment]
@tevans78, I had updated the baseline for packaging verification to 18.0.0.3, but unexpectedly that caused an issue in the release build so I moved it back temporarily.  I will post a comment here once everything is updated in packaging verification again and we can merge this update.

**Comment by naumanna** [comment]
This is safe to deliver now.

**Pull request merged**
