### PR TITLE
#12606-Fix Issue with jvm.options file

### PR DESCRIPTION
**Pull request by hlhoots**

### CODE REVIEW

**Comment by hlhoots** [comment]
#build

**Comment by hlhoots** [comment]
fixes #12606

**Review by jimblye — APPROVED** [review]
I think the following word order would be more clear in the comment.

# This location is intentionally not documented ...

**Comment by hlhoots** [comment]
#build 

Changed the comment line in both files.

**Comment by hlhoots** [comment]
#run-libby-bot

**Comment by hlhoots** [comment]
build had a couple of unrelated errors.  merging.

**Pull request merged**
