### PR TITLE
Add baggage.propagation api to Telemetry feature

### PR DESCRIPTION
**Pull request by Yas-Franco**
For issue #23925

### CODE REVIEW

**Comment by Azquelt** [comment]
Does this need a test?

I know @tevans78 found this while writing tests, does that mean we already have some ready to be added?

**Comment by tevans78** [comment]
> Does this need a test?
> 
> I know @tevans78 found this while writing tests, does that mean we already have some ready to be added?

At the moment my new test is super basic and is only really checking that the API is accessible. It is not an exhaustive test of the API.
https://github.com/OpenLiberty/open-liberty/pull/23932/files#diff-b265c9191268e742a61494fee19cd7106aae6e94836ae4478c8a750edc6a6562

**Review by Azquelt — APPROVED** [review]

**Comment by Azquelt** [comment]
ok, this can be merged as-is and the test from #23932 enabled later (either as part of that PR, or separately)

**Comment by Yas-Franco** [comment]
#libby
#build

**Pull request merged**
