### PR TITLE
Rename Classes for HTTP Stats

### PR DESCRIPTION
**Pull request by Channyboy**
Include  `server ` in the classes and MBean + change the monitor group to just HTTP
#build

### CODE REVIEW

**Comment by Channyboy** [comment]
#build #libby

**Comment by Channyboy** [comment]
#build #libby

**Comment by Channyboy** [comment]
#build

**Comment by Channyboy** [comment]
The errors scene are related to the GUI buckets and are not related to this PR.

**Review by fmhwong — APPROVED** [review]
LGTM

**Pull request merged**
