### PR TITLE
#565 Update Servlet4 NameSpace

### PR DESCRIPTION
**Pull request by pmd1nh**

### CODE REVIEW

**Comment by pmd1nh** [comment]
#build

**Comment by pmd1nh** [comment]
#build

**Comment by pnicolucci** [comment]
Fixes issue #565

**Comment by pmd1nh** [comment]
#build

**Comment by pmd1nh** [comment]
Feature Checker failure

ERROR: com.ibm.websphere.appserver.javaeedd-1.0
[BAD_PACKAGE_VERSION com.ibm.ws.javaee.dd.web@1.1.0]
Changes were detected in package com.ibm.ws.javaee.dd.web@1.1.0 which mean the package version is now incorrect. The baseline knows the package at version 1.1.0 Change the version of the package from its current version 1.1.0 to 1.2.0
For More Information, visit http://was.pok.ibm.com/xwiki/bin/view/Build/FeatureChecker

Updated com.ibm.ws.javaee.dd.web.package-info.java to 1.2.

**Comment by pmd1nh** [comment]
Test for this will be in 

https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.workitem.viewWorkItem&id=247615

**Comment by pmd1nh** [comment]
The maxVersion is needed since Liberty support multiple servlet features 3.0, 3.1 and 4.0 which specified in server.xml.  The vers is set from the application web.xml.  That way a 3.1 application will not deploy on a 3.0 server, and  4.0 app will not deploy on 3.1 server.

**Comment by pnicolucci** [comment]
Thanks for the information, approved.

**Pull request merged**
