### PR TITLE
Add Oracle Derby SQLServer HADB Tests

### LINKED ISSUE #15969: Add  Transaction HA Database tests for supported RDBMS
Currently we test Derby and SQLServer only.

### PR DESCRIPTION
**Pull request by neilgsyoung**
fixes #15969

### CODE REVIEW

**Comment by neilgsyoung** [comment]
#build

**Comment by neilgsyoung** [comment]
#run-libby-bot

**Comment by neilgsyoung** [comment]
#build

**Comment by neilgsyoung** [comment]
#run-libby-bot

**Comment by neilgsyoung** [comment]
#build

**Review by jonhawkes — APPROVED** [review]

**Comment by neilgsyoung** [comment]
#build

**Pull request merged**
