### PR TITLE
test leaked JMS connection handles

### PR DESCRIPTION
**Pull request by njr-11**
Write tests that attempts to keep JMS connection handles open across servlet requests.  One test runs with HandleList enabled, and the other with it disabled.  Verify that the HandleList, when enabled, causes the leaked JMS connection to be automatically closed.  Verify that, when HandleList is disabled, the JMS connection remains usable in a second servlet request.

### CODE REVIEW

**Review by jmstephensgit — APPROVED** [review]

**Comment by njr-11** [comment]
#build

**Review by jmstephensgit — APPROVED** [review]

**Comment by njr-11** [comment]
#build
#run-libby-bot

**Comment by njr-11** [comment]
#build

**Comment by njr-11** [comment]
#build
#run-libby-bot

**Comment by njr-11** [comment]
#build

**Comment by njr-11** [comment]
#build
#run-libby-bot

**Pull request merged**
