### PR TITLE
debug: Add arquillian trace for Concurrency TCK

### PR DESCRIPTION
**Pull request by KyleAure**
- [x] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [x] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [x] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

### CODE REVIEW

**Comment by KyleAure** [comment]
#build - personal build
#libby - check headers

**Comment by contbld** [comment]
Your personal pipeline request is at https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=56945bea-836f-42bd-83c3-1d11cdde581a

Target locations of links might be accessible only to IBM employees.

**Comment by contbld** [comment]
Your personal pipeline request is at https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=9898107e-3c2b-45a8-8a7a-ab23b0721a6e

Target locations of links might be accessible only to IBM employees.

**Review by gjwatts — APPROVED** [review]

**Comment by contbld** [comment]
<h3>Code analysis and actions</h3>
DO NOT DELETE THIS COMMENT.

- 2 FAT files were changed, added, or removed.
 - Check that the build did not break the affected FAT suite(s).

**Comment by contbld** [comment]
<h3>Code analysis and actions</h3>
DO NOT DELETE THIS COMMENT.

- 2 FAT files were changed, added, or removed.
 - Check that the build did not break the affected FAT suite(s).

**Comment by contbld** [comment]
https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=9898107e-3c2b-45a8-8a7a-ab23b0721a6e completed successfully!

**Comment by contbld** [comment]
https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=56945bea-836f-42bd-83c3-1d11cdde581a completed successfully!

**Comment by contbld** [comment]
The build KyleAure-30115-20241108-2310
https://wasrtc.hursley.ibm.com:9443/jazz/resource/itemOid/com.ibm.team.build.BuildResult/_MOHUEJ5gEe-M9e5esDPP_g
completed successfully!

**Pull request merged**
