### PR TITLE
Ltpa fixes

### PR DESCRIPTION
**Pull request by Zech-Hein**
#libby
#build

### CODE REVIEW

**Comment by Zech-Hein** [comment]
Starting another build with the simplest change force pushed after review from Ajay.
#libby
#build

**Review by arkarkala — APPROVED** [review]

**Review by utle — APPROVED** [review]

**Comment by mshah0722** [comment]
Unrelated build errors and failures. Merging change.

**Comment by wrodrig** [comment]
Fixes #26750

**Comment by clarkek123** [comment]
Fixes #PH57579

**Pull request merged**
