### PR TITLE
Jakarta EE11: Expression Language 6.0 initial work

### LINKED ISSUE #25703: Expression Language 6.0: pull in initial API/IMPL for Expression Language 6.0

### PR DESCRIPTION
**Pull request by pnicolucci**
fixes #25703

Had to do a number of things to get this working initially in Open Liberty:
1) Had to overlay all of the API and IMPL sources so we could build with Java17. The API/IMPL we pull in are built with Java 21 so we were getting the following sorts of errors when running with Java17: 

> java.lang.UnsupportedClassVersionError: JVMCFRE199E bad major version 65.0 of class=jakarta/el/ELProcessor, the maximum supported major version is 61.0; offset=6

2) 

> [7/13/23, 15:30:15:000 EDT] 0000002e LogService-26-io.openliberty.el.internal.cdi.jakarta         E CWWKE0702E: Could not resolve module: io.openliberty.el.internal.cdi.jakarta [26]
  Unresolved requirement: Import-Package: jakarta.el; version="[4.0.0,6.0.0)"

Needed to update elp-jakartaee-transform/rules/jakarta-versions.properties to be: [4.0.0,7.0.0)

3) ExpressionFactoryImpl, remove the annotation so we don't end up with a service entry that isn't necessary, if it is there we get:
	

> ... 37 more
> Caused by: java.lang.ClassNotFoundException: org.apache.el.ExpressionFactoryImpl
> 	at com.ibm.ws.classloading.internal.UnifiedClassLoader.findClass(UnifiedClassLoader.java:167)
> 	at com.ibm.ws.classloading.internal.ThreadContextClassLoader.findClass(ThreadContextClassLoader.java:145)
> 	at com.ibm.ws.classloading.internal.UnifiedClassLoader.loadClass0(UnifiedClassLoader.java:141)
> 	at com.ibm.ws.classloading.internal.UnifiedClassLoader$Delegation.loadClass(UnifiedClassLoader.java:87)
> 	at com.ibm.ws.classloading.internal.UnifiedClassLoader.loadClass(UnifiedClassLoader.java:106)
> 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1094)
> 	at jakarta.el.ExpressionFactory.newInstance(ExpressionFactory.java:117)
> 	... 43 more

4) Need to disable java2 security in the FAT because all references to the `SecurityManager` went away with Expression Language 6.0  in EE11: `websphere.java.security.exempt=true` 

5) pages-4.0 won't resolve:

> Launching test (Open Liberty 23.0.0.8/wlp-1.0.80.202307181029) on Eclipse OpenJ9 VM, version 17.0.7+7 (en_US)
> [AUDIT   ] CWWKE0001I: The server test has been launched.
> [ERROR   ] CWWKE0702E: Could not resolve module: io.openliberty.tags.3.0.facade [92]
>   Unresolved requirement: Import-Package: jakarta.el; version="[5.0.0,6.0.0)"

This one is resolved by updating the ee10 tags facade to include the 6.0 import. File change is io.openlberty.jstl.2.0.facade/ee10.bnd

6) Another pages-4.0 issue:

>   [AUDIT   ] CWWKE0001I: The server test has been launched.
> [ERROR   ] CWWKE0702E: Could not resolve module: io.openliberty.tags.3.0.facade [92]
>   Unresolved requirement: Import-Package: jakarta.servlet.jsp; version="[3.1.0,4.0.0)"
>     -> Export-Package: jakarta.servlet.jsp; bundle-symbolic-name="io.openliberty.jakarta.pages.3.1"; bundle-version="1.0.80.202307181029"; version="3.1.1"; uses:="jakarta.el,jakarta.servlet,jakarta.servlet.http,jakarta.servlet.jsp.el,jakarta.servlet.jsp.tagext"
>        io.openliberty.jakarta.pages.3.1 [86]
>          Unresolved requirement: Import-Package: jakarta.el; version="[5.0.0,6.0.0)"
>   Unresolved requirement: Import-Package: jakarta.servlet.jsp.el; version="[3.1.0,4.0.0)"
>     -> Export-Package: jakarta.servlet.jsp.el; bundle-symbolic-name="io.openliberty.jakarta.pages.3.1"; bundle-version="1.0.80.202307181029"; version="3.1.1"; uses:="jakarta.el"

Resolution:  Create a new pages.4.0.bnd as a current place holder to update the `jakarta.el` import to include `6.0`. `io.openliberty.jakarta/pages.4.0.bnd`
        * Everything else is left alone and is the same as the `pages.3.1.bnd`
Updated the `io.openliberty.jakarta.pages-4.0.feature` file to include the new bundle
        * We leave the mavencoordinates alone for now until we have a new API JAR to include 
7)     

> Launching test (Open Liberty 23.0.0.8/wlp-1.0.80.202307181145) on Eclipse OpenJ9 VM, version 17.0.7+7 (en_US)
> [AUDIT   ] CWWKE0001I: The server test has been launched.
> [ERROR   ] CWWKE0702E: Could not resolve module: io.openliberty.tags.3.0.facade [92]
>   Unresolved requirement: Import-Package: jakarta.servlet.jsp.jstl.core; version="[3.0.0,4.0.0)"
>     -> Export-Package: jakarta.servlet.jsp.jstl.core; bundle-symbolic-name="io.openliberty.jakarta.tags.3.0"; bundle-version="1.0.80.202307181145"; version="3.0.0"; uses:="jakarta.el,jakarta.servlet,jakarta.servlet.http,jakarta.servlet.jsp,jakarta.servlet.jsp.tagext"
>        io.openliberty.jakarta.tags.3.0 [89]
>          Unresolved requirement: Import-Package: jakarta.el; version="[5.0.0,6.0.0)"
>   Unresolved requirement: Import-Package: jakarta.servlet.jsp.jstl.fmt; version="[3.0.0,4.0.0)"
>     -> Export-Package: jakarta.servlet.jsp.jstl.fmt; bundle-symbolic-name="io.openliberty.jakarta.tags.3.0"; bundle-version="1.0.80.202307181145"; version="3.0.0"; uses:="jakarta.servlet.jsp"

Resolution: This is because the tags.3.0.bnd needs to also work with ee11 so update the import to include `jakarta.el` at the `6.0.0` level.

### CODE REVIEW

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Review by volosied — APPROVED** [review]
It looks good to me. I'm sure there might be  an issue or two here that 's not obvious, but I don't see any problems here.

**Comment by pnicolucci** [comment]
#libby

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#libby

**Pull request merged**
