### PR TITLE
Fix DerbyRA Checkpoint test failure

### PR DESCRIPTION
**Pull request by KyleAure**
- [x] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [x] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [x] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

Ensure application has started before running tests.

### CODE REVIEW

**Comment by KyleAure** [comment]
#build - could not test this solution locally, so relying on personal build.

**Comment by wraschke** [comment]
#libby

**Comment by KyleAure** [comment]
Personal build passed. Ready for review.

**Review by dazavala — APPROVED** [review]
@KyleAure Looks good.  I'll discuss w/ Tom your suggestion to verify app start within LibertyServer.checkpointRestore().  It was an oversight not to include such assertions in the test methods before submitting work to the test servers.  Thank you for making the changes.

**Pull request merged**
