### PR TITLE
close streams of Files.list() - Fixes #29556 

### LINKED ISSUE #29556: Resource Leakage: File Handlers to tranlog directory
**Describe the bug**  
open-liberty opens file handlers without closing them. this leads to a small but still noticable off-heap-memory leak (especially for small services).

we could track down the (native) memory be allocated in UnixNativeDispatcher_fdopendir which led us to introspect the opened file handlers. There we could find thousans of open file handlers to the tranlog directory.

the resource leakage was introduced with PR #27928. this is why open-liberty versions from 24.0.0.4 and upwards suffer by this memory leak and we were not able to upgrade.

in this PR there are two locations where Files.list(...) is called but the returned stream is not closed. So we assume this causes the resource leakage (at least with Java 21).

**Steps to Reproduce**  
start an openliberty on java 21 in a kubernetes pod with -XX:MaxRAMPercentage=50.0 and memory limits at a few 100MB. After a while (a few weeks) the container will be OOM-Killed because the Off-Heap-Memory will grow too big.

**Expected behavior**  
File Handles should be closed after usage so the allocated resources (buffer/cache, whatever) can be freed.

**Diagnostic information:**  
 - OpenLiberty Version: [e.g. 24.0.0.4 - 24.0.0.8]
 - Java Version: [openjdk version 21.0.4+7]

**Additional context**  
ls -l /proc/1/fd | grep tranlog | wc -l
4914 -> growing

in versions before 24.0.0.4 where are 4 open file descriptors

I'll submit a PR to close the streams.

### PR DESCRIPTION
**Pull request by pellmont**
Fixes #29556 

keeping Stream opened caused a native memory leak (more and more open file handles). see https://github.com/OpenLiberty/open-liberty/issues/29556

- [ x] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [x ] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [ ] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

### CODE REVIEW

**Comment by pellmont** [comment]
Where do I have to send the CLA to?

**Comment by jonhawkes** [comment]
@pellmont please send your signed CLA to [cla@openliberty.io](mailto:cla@openliberty.io)

**Comment by jonhawkes** [comment]
#build

**Review by jonhawkes — APPROVED** [review]

**Comment by pellmont** [comment]
just sent the CLA

**Comment by jonhawkes** [comment]
Fixes #PH63066

**Comment by pellmont** [comment]
Thanks for review and merge @jonhawkes !

**Pull request merged**
