### PR TITLE
Mptelemetry 1.0

### PR DESCRIPTION
**Pull request by Yas-Franco**
For issue #19172

### CODE REVIEW

**Comment by Yas-Franco** [comment]
#build

**Comment by posmith** [comment]
L2 message review not required

**Review by tevans78 — APPROVED** [review]
There are plenty of things that need to be worked on here before GA, but we'd still like to get this delivered at a beta level.

**Comment by tevans78** [comment]
#libby

**Comment by tevans78** [comment]
Merging without Copyright check because Libby is being very slow

**Pull request merged**
