### PR TITLE
Better clean up after ServerEnvTest fat

### LINKED ISSUE #25493: File default.log exists after ServerEnvTest runs.
The ServerEnvTest sets the LOG_FILE variable in server.env and changes the name of the log file.   It attempts to rename that to console.log at the end of each test.   The rename is failing because the server is still running at that point.
There are several other tests that are failing because console.log does not exist.   I don't think ServerEnvTest is the cause of the other tests failing, because console.log should be created every time the server is started.    But to remove any doubt, the ServerEnvTest can be modified to use another means of testing besides changing the log file name.

### PR DESCRIPTION
**Pull request by jimblye**
Test bug.   Failures during cleanup phase of ServerEnvTest are causing other tests to fail.
Fixes #25493

### CODE REVIEW

**Comment by jimblye** [comment]
#build

**Review by hlhoots — APPROVED** [review]
LGTM

**Comment by jimblye** [comment]
#build

**Comment by jimblye** [comment]
#libby

**Comment by jimblye** [comment]
#build

**Comment by jimblye** [comment]
#build

**Comment by jimblye** [comment]
#build

**Pull request merged**
