### PR TITLE
Add MP7 repeats for Metrics

### PR DESCRIPTION
**Pull request by tevans78**
Add MP7 repeats to mpMetrics-5.1 FAT buckets. This currently translates to MP61, MP70_EE10 and MP70_EE11 ... although in most cases, the set of features for MP61 and MP70_EE10 are the same in Metrics tests.

### CODE REVIEW

**Comment by tevans78** [comment]
#build

**Review by Channyboy — DISMISSED** [review]
lgtm

**Comment by tevans78** [comment]
#build

**Review by Channyboy — DISMISSED** [review]
lgtm

**Comment by Channyboy** [comment]
#build #libby

**Comment by Channyboy** [comment]
#build #libby

**Review by fmhwong — APPROVED** [review]
LGTM

**Comment by Channyboy** [comment]
Errors seen in latest build are not related to this PR (or MP for that matter).

**Pull request merged**
