### PR TITLE
serverConfig - retrieve file list under configDropins for admin role only

### PR DESCRIPTION
**Pull request by aknguyen7**
fixed issue [28837](https://github.ibm.com/websphere/WS-CD-Open/issues/28837)

### CODE REVIEW

**Comment by aknguyen7** [comment]
#build

**Comment by aknguyen7** [comment]
server config tests ran successfully
image

**Review by k8vance88 — APPROVED** [review]
LGTM

**Comment by aknguyen7** [comment]
#libby

**Pull request merged**
