### PR TITLE
Rename and change gradle repo props

### PR DESCRIPTION
**Pull request by cbridgha**

### CODE REVIEW

**Comment by cbridgha** [comment]
#build

**Comment by wraschke** [comment]
#build

**Comment by wraschke** [comment]
Defects https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.workitem.viewWorkItem&id=269157 is pre-existing for `com.ibm.ws.collective.routing.controller_fat: com.ibm.ws.collective.routing.controller.fat.RoutingInfoManagerMBeanTest.testDumpToLog` failure and https://wasrtc.hursley.ibm.com:9443/jazz/resource/itemName/com.ibm.team.workitem.WorkItem/275557 for `com.ibm.ws.microprofile.reactive.messaging_fat: junit.framework.TestSuite.com.ibm.ws.microprofile.reactive.messaging.fat.suite.PlaintextTests` failure.

**Comment by wraschke** [comment]
The lowered time from 5 minutes to 3 minutes means that the invocation will fail faster, but we should all be understanding that these adjustments are being done on a trial, iterative basis.

**Comment by cbridgha** [comment]
#libby

**Comment by wraschke** [comment]
#link 273120

**Pull request merged**
