### PR TITLE
check the hostname value before assigning to the dnsName

### PR DESCRIPTION
**Pull request by acdemyers**
On certs created during server startup check the hostname for characters not allowed in the dnsName part of the subject alternative name.

### CODE REVIEW

**Comment by acdemyers** [comment]
#build

**Comment by acdemyers** [comment]
#build

**Comment by acdemyers** [comment]
#build

**Review by una-tapa — APPROVED** [review]
I chat with Alaine and agree with her evaluation that this this code area is rarely called 
  No performance concerns.  Approving. Thank you! 

        try {
            addr = InetAddress.getByName(hostname);
        } catch (Exception e) {
            //hostname likely does not resolve to an address
        }


Alaine >> Only when a cert is created and they specify a defaultHostName variable in the configuration.  That code path is only seen when a customize hostname value is set in the configuration.  I don't know how often that happens.

**Comment by acdemyers** [comment]
#libbybot

**Pull request merged**
