### PR TITLE
swidtags for OL25

### PR DESCRIPTION
**Pull request by bensonlatibm**
- [x] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [ ] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [ ] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

### CODE REVIEW

**Comment by bensonlatibm** [comment]
#build

**Comment by contbld** [comment]
Your personal pipeline request is at https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=2c7e2249-99fc-471e-a346-3609dd8d33e4

Target locations of links might be accessible only to IBM employees.

**Comment by contbld** [comment]
<h3>Code analysis and actions</h3>
DO NOT DELETE THIS COMMENT.

- 2 product code files were changed.- **Please describe in a separate comment how you tested your changes.**
- 1 messages files were changed and need an L2 review.

- @OpenLiberty/message-reviewer Please review.
  - --nlsFiles

**Review by jjiwooLim — APPROVED** [review]
lgtm!

**Pull request merged**
