### PR TITLE
Adding option values to logging attributes that were missing them

### PR DESCRIPTION
**Pull request by lamkavan**
In relation to https://github.com/OpenLiberty/open-liberty/issues/9978

### CODE REVIEW

**Comment by lamkavan** [comment]
#build

**Comment by lamkavan** [comment]
#build

**Comment by andrea-pichler** [comment]
No review requested from L2

**Comment by lamkavan** [comment]
#build

**Comment by pgunapal** [comment]
@lamkavan The changes in this PR is included in PR #10156. This PR can be closed.

**Pull request closed without merging**
