### PR TITLE
Update dependency version

### PR DESCRIPTION
**Pull request by automatictester**

### CODE REVIEW

**Comment by aguibert** [comment]
hi @automatictester, thanks for the PR!  Before we can build/test this change, can you sign the contributor license agreement (CLA)?  Details can be found here: https://github.com/OpenLiberty/open-liberty/blob/integration/CONTRIBUTING.md

**Comment by automatictester** [comment]
Hi @aguibert. I consider this to be a trivial change which doesn't require ICLA. If you believe otherwise, then I'm sorry, I don't think I'll to do that - too formal/heavyweight process for me. If that means this PR needs to be closed without merging, that's fine. In that case, perhaps someone who already signed the ICLA would be able to provide similar code change. Many thanks!

**Comment by tevans78** [comment]
#build

**Comment by aguibert** [comment]
ah, I didn't know there was an exemption for trivial changes, but asking around a bit you are indeed correct.
I don't think our build automation is set up to allow builds for trivial changes where the CLA hasn't been signed yet.  We'll look into this and see if we can get your changes merged in.

**Comment by aguibert** [comment]
#build

**Comment by andymc12** [comment]
I think the code changes look fine - and I tested them locally.  These same changes were made in the CXF community, so if there is a licensing issue with making the changes from @automatictester , I would be willing to make the same changes under my user account, with @automatictester's explicit permission.  Ireneusz, can you reply in a comment that you approve of me making this same change?  Then we can close this PR, and I can submit the same changes in a new PR.  Thanks, Andy

**Comment by automatictester** [comment]
No probs @andymc12, please go ahead.

**Comment by tevans78** [comment]
The change is trivial so a CLA is not required ... but our automation is being quite strict about it.

**Comment by tevans78** [comment]
I requested a build manually:
https://wasrtc.hursley.ibm.com:9443/jazz/resource/itemOid/com.ibm.team.build.BuildResult/_rSTIEBT2EemJj5Oykri-vA

**Comment by andymc12** [comment]
@automatictester - I've merged the change using PR 6163, so I'll close this PR.  Thanks for the initial pull request!  Much appreciated!

**Pull request closed without merging**
