### PR TITLE
Re-add jbatch_fat after revert

### LINKED ISSUE #15278: Re-introduce change reverted from 15245
Re-introduce change reverted from https://github.com/OpenLiberty/open-liberty/pull/15245

### PR DESCRIPTION
**Pull request by cgianfra**
The commit for the port of jbatch_fat was reverted due to the common fat tooling project being named _fat, causing it to be treated as a FAT project. This re-delivers the ported projects but with jbatch.common_fat renamed to jbatch.fat.common.

Fixes #15278

### CODE REVIEW

**Comment by cgianfra** [comment]
Fixes #15278

**Comment by cgianfra** [comment]
#build

**Review by jhanders34 — CHANGES_REQUESTED** [review]
I notice that ojdbc6.jar is checked in twice.  We do not check in binary files usually.  We get them from open source and bring them in via gradle or some other way.  They should not be checked into github.  if it isn't needed it should be removed, but otherwise it should be done differently.

**Comment by cgianfra** [comment]
#build

**Comment by cgianfra** [comment]
#build

**Review by jhanders34 — APPROVED** [review]

**Comment by cgianfra** [comment]
#libby

**Pull request merged**
