### PR TITLE
grpc_fat improvements

### PR DESCRIPTION
**Pull request by wtlucy**
* ignore IOE during error condition test
* standardize server.xml updating
* skip app startup verification for some apps

### CODE REVIEW

**Comment by wtlucy** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.grpc_fat

**Review by billw1024 — APPROVED** [review]

**Comment by wtlucy** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.grpc_fat

**Comment by wtlucy** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.grpc_fat

**Comment by wtlucy** [comment]
#run-libby-bot

**Pull request merged**
