### PR TITLE
Use separate RTC build definition to allow more builds to be kept

### PR DESCRIPTION
**Pull request by wraschke**
#pb #pbbeta

### CODE REVIEW

**Comment by wraschke** [comment]
#libby

**Comment by wraschke** [comment]
#pb #pbbeta

**Comment by wraschke** [comment]
The beta pipeline was mostly great. It ran into 

```
Caused by: /home/jazz_build/Build/jbe/build/WS-CD-Open/dev/ant_build/public_imports/internal_imports/delivery_validation.xml:271: Could not identify any suitable builds to compare to on the definition Open Liberty Personal Build CI Orchestrator - EBC
```

during an Ant task flow that's really an obsoleted leftover from days past (revertChangesets custom task); this failed because the underlying code was looking for previous builds of that type and since this is the first one requested, it couldn't find any other and thus failed. And then the packaging verification build failed due to a problem with libertyfs:

```
[15-Mar-2023 02:50:18:103 PDT] 00000050 BUILD FAILED
[15-Mar-2023 02:50:18:103 PDT] 00000050 /home/jazz_build/Build/jbe/build/dev/ant_build/build-packaging-verification.xml:132: Encountered an exception while searching for matching files. Directory was: /liberty/dev/Xo/release/cl230220230222-1257-_Iaaa0LKoEe2syNb0fJgimw
```

This was discussed at https://ibm-cloud.slack.com/archives/C30NGUQ9E/p1678879575805539.

Anyway, I'm re-requesting more.

**Comment by wraschke** [comment]
#libby

**Comment by wraschke** [comment]
#pb #pbbeta

**Comment by wraschke** [comment]
#libby

**Review by fritze2 — APPROVED** [review]

**Comment by wraschke** [comment]
The two beta pipelines requested

- https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=087e523d-cd01-4cfc-9497-c22ba6a7c274
- https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=790e3c64-25fa-45e3-9535-a56d7e19384e

had the expected result, which is for the compile step's build to be of type `Open Liberty Personal Build CI Orchestrator - EBC`, the new definition I created by copying `Liberty Personal Build CI Orchestrator - EBC`.

The FAT failures are not related.

Additionally, the compile step with UUID `_WtGzEMNsEe2wjvvdiFn2gA` for pipeline `087e523d-cd01-4cfc-9497-c22ba6a7c274` that I requested after my last commit to change the `fat.buckets.to.exclude` property had the expected value for this property (no value) to match what the Rosie builds have. And I saw in previous pipelines that those FATs that were in the previous value were being run anyway (i.e., `com.ibm.ws.os.packaging_fat` and Admin Center GUI FATs).

Lastly, the [non-beta pipeline](https://libh-proxy1.fyre.ibm.com/cognitive-dev/pipelineAnalysis.html?uuid=8f276554-7a22-4303-a1aa-09431e2f6804) has fatal status because it timed out--the RTC FAT child builds were taking too long. But most importantly, this PR's changes don't affect that type of pipeline.

I consulted with Ethan about these pipelines and he said it was fine to merge.

**Pull request merged**
