### PR TITLE
`io.openliberty.microprofile.telemetry.internal.monitor_fat` improvements

### PR DESCRIPTION
**Pull request by Channyboy**
- [x] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [x] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [x] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

################################################################################################

### CODE REVIEW

**Comment by Channyboy** [comment]
#build

**Comment by contbld** [comment]
Your personal pipeline request is at https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=64004b35-6622-4612-80db-1547304761e8

Target locations of links might be accessible only to IBM employees.

**Comment by contbld** [comment]
<h3>Code analysis and actions</h3>
DO NOT DELETE THIS COMMENT.

- 5 FAT files were changed, added, or removed.
 - Check that the build did not break the affected FAT suite(s).

**Comment by contbld** [comment]
https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=64004b35-6622-4612-80db-1547304761e8 completed successfully!

**Review by tonyreigns — APPROVED** [review]
LGTM

**Comment by contbld** [comment]
The build Channyboy-30106-20241108-1144
https://wasrtc.hursley.ibm.com:9443/jazz/resource/itemOid/com.ibm.team.build.BuildResult/_lSxocJ29Ee-M9e5esDPP_g
completed and has errors or failures.

For help analyzing your personal build, go to https://libh-proxy1.fyre.ibm.com/cognitive/buildAnalysis.html?uuid=_lSxocJ29Ee-M9e5esDPP_g

**Pull request merged**
