### PR TITLE
Include all resources from JavaMail implementation

### PR DESCRIPTION
**Pull request by Thihup**
Fixes issue #17666

### CODE REVIEW

**Comment by tevans78** [comment]
I'm going to mark this as `CLA trivial` but @LibbyBot is a little dumb about it so if I remove `CLA Needed` it will get put straight back on :-(

**Comment by tevans78** [comment]
#build

**Comment by tevans78** [comment]
#build

**Comment by neuwerk** [comment]
@Thihup I'm going to manually request a build for you, and I'll post the link for it shortly.

**Comment by neuwerk** [comment]
Here's the PB I've requested https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_vis3UNUIEeuW56aVtfPMFw

As Libby likes to say: Target locations of links might be accessible only to IBM employees.

So I'll keep an eye on it's progress.

**Review by neuwerk — APPROVED** [review]
Personal Build results were good (failure was unrelated), and changes look great! Thanks again for doing this!

**Pull request merged**
