### PR TITLE
refresh netty libraries to 4_1_86_Final

### PR DESCRIPTION
**Pull request by hutchig**
Refresh netty libraries.

Refresh to:
https://search.maven.org/remotecontent?filepath=io/netty/netty-buffer/4.1.86.Final/netty-buffer-4.1.86.Final.jar
https://search.maven.org/remotecontent?filepath=io/netty/netty-codec-http2/4.1.86.Final/netty-codec-http2-4.1.86.Final.jar
https://search.maven.org/remotecontent?filepath=io/netty/netty-codec-http/4.1.86.Final/netty-codec-http-4.1.86.Final.jar
https://search.maven.org/remotecontent?filepath=io/netty/netty-codec-socks/4.1.86.Final/netty-codec-socks-4.1.86.Final.jar
https://search.maven.org/remotecontent?filepath=io/netty/netty-codec/4.1.86.Final/netty-codec-4.1.86.Final.jar
https://search.maven.org/remotecontent?filepath=io/netty/netty-common/4.1.86.Final/netty-common-4.1.86.Final.jar
https://search.maven.org/remotecontent?filepath=io/netty/netty-handler-proxy/4.1.86.Final/netty-handler-proxy-4.1.86.Final.jar
https://search.maven.org/remotecontent?filepath=io/netty/netty-handler/4.1.86.Final/netty-handler-4.1.86.Final.jar
https://search.maven.org/remotecontent?filepath=io/netty/netty-resolver/4.1.86.Final/netty-resolver-4.1.86.Final.jar
https://search.maven.org/remotecontent?filepath=io/netty/netty-transport/4.1.86.Final/netty-transport-4.1.86.Final.jar

### CODE REVIEW

**Comment by hutchig** [comment]
cd ~/.ibmartifactory/repository/io/netty
for J in `ls`; do cp ~/Downloads/*$J* ./$J\/4.1.86.Final/; done
Will enable a local build until https://paddleandroll1.fyre.ibm.com:9443/uploader/ is working

find . -type f | grep 86 | grep -v \(
./netty-codec-http/4.1.86.Final/netty-codec-http-4.1.86.Final.jar
./netty-codec-http/4.1.86.Final/netty-codec-http2-4.1.86.Final.jar
./netty-handler/4.1.86.Final/netty-handler-proxy-4.1.86.Final.jar
./netty-handler/4.1.86.Final/netty-handler-4.1.86.Final.jar
./netty-codec/4.1.86.Final/netty-codec-http-4.1.86.Final.jar
./netty-codec/4.1.86.Final/netty-codec-http2-4.1.86.Final.jar
./netty-codec/4.1.86.Final/netty-codec-4.1.86.Final.jar
./netty-codec/4.1.86.Final/netty-codec-socks-4.1.86.Final.jar
./netty-common/4.1.86.Final/netty-common-4.1.86.Final.jar
./netty-resolver/4.1.86.Final/netty-resolver-4.1.86.Final.jar
./netty-codec-http2/4.1.86.Final/netty-codec-http2-4.1.86.Final.jar
./netty-transport/4.1.86.Final/netty-transport-4.1.86.Final.jar
./netty-buffer/4.1.86.Final/netty-buffer-4.1.86.Final.jar
./netty-codec-socks/4.1.86.Final/netty-codec-socks-4.1.86.Final.jar
./netty-handler-proxy/4.1.86.Final/netty-handler-proxy-4.1.86.Final.jar
~/.ibmartifactory/repository/io/netty

**Comment by hutchig** [comment]
Builds and assembles OK locally with above library...
Running grpc_fat tests locally...

**Review by mrsaldana — DISMISSED** [review]
LGTM

**Comment by hutchig** [comment]
#build

**Comment by hutchig** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.grpc_fat

**Comment by hutchig** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.grpc_fat #fat.test.mode=full

**Comment by hutchig** [comment]
Expecting build test failures (as some local at the mo), just want a different perspective.

**Comment by hutchig** [comment]
Can be compared to https://github.com/OpenLiberty/open-liberty/pull/21049

**Comment by hutchig** [comment]
FAT failure is due to...
[20/12/2022, 12:55:47:619 GMT] 00000024 id=00000000 LogService-78-io.openliberty.io.netty.ssl                    E CWWKE0702E: Could not resolve module: io.openliberty.io.netty.ssl [78]
  Unresolved requirement: Import-Package: io.netty.channel.unix
etc...
The 4.1.86 code now references io.netty.channel.unix package so we will need to make some bnd changes to accomodate:
image

**Comment by hutchig** [comment]
I have tried hard to minimize this second commit's contents and tested that every line in it will cause a grpc_fat failure if removed. (Also the review dismissal is automatic upon adding a new commit.)

#build

**Comment by hutchig** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.grpc_fat

**Comment by hutchig** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.grpc_fat #fat.test.mode=full

**Review by mrsaldana — APPROVED** [review]
Thanks for adding the new dependencies, looks good, re-approving.

**Comment by hutchig** [comment]
#libbybot

**Comment by hutchig** [comment]
I confirmed the green builds results and checked the failing test (typo) in the failing one.

**Pull request merged**
