### PR TITLE
Initial MP Rest Client 1.1 Implementation

### PR DESCRIPTION
**Pull request by andymc12**
New Feature: MicroProfile Rest Client 1.1 Implementation

Based on Apache CXF 3.2.6 Snapshot - this is a work in progress.

### CODE REVIEW

**Comment by andymc12** [comment]
#build

**Comment by mhldr** [comment]
issues discussed in #was-liberty-ops caused the build to fail so I'm respinning this incase it's needed (you ***may*** already have the results you need but if not hopefully this respin will help)
#build

**Comment by andymc12** [comment]
#build

**Comment by andymc12** [comment]
#build

**Comment by andymc12** [comment]
#build

**Comment by andymc12** [comment]
#build

**Comment by andymc12** [comment]
#build

**Comment by andymc12** [comment]
#build

**Comment by andymc12** [comment]
#build

**Comment by andymc12** [comment]
#build

**Comment by andymc12** [comment]
#build

**Comment by andymc12** [comment]
Failures in latest build are unrelated to these changes.  Snapshot build of the Liberty Arquillian plugin from @Azquelt (thanks Andrew!) avoided all of the intermittent TCK app install failures from previous 2-3 builds.  Time to deliver!

**Comment by Azquelt** [comment]
Good to know it fixed your problem. Ideally, we don't want to leave it depending on that snapshot as snapshots aren't maintained indefinitely so we should attempt to get a new liberty-arquillian release asap. (Or failing that check in a development snapshot in a more permanent manner)

**Comment by andymc12** [comment]
This is the implementation for Epic Issue #4519

**Pull request merged**
