### PR TITLE
MYFACES-4666

### LINKED ISSUE #29587: Faces 4.1: Pull in MYFACES-4666
https://issues.apache.org/jira/browse/MYFACES-4666

### PR DESCRIPTION
**Pull request by pnicolucci**
- [x] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [x] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [x] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

fixes #29587

### CODE REVIEW

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Review by volosied — APPROVED** [review]
Looks good to me

**Comment by volosied** [comment]
#libby

**Comment by pnicolucci** [comment]
One failure in the RTC build is due to `Exception attempting to connect to Consul servers` not related to these Faces changes.

**Pull request merged**
