### PR TITLE
remove mpCompatible dependency on mpVersion

### PR DESCRIPTION
**Pull request by rsherget**

### CODE REVIEW

**Comment by rsherget** [comment]
#build

**Comment by rsherget** [comment]
#build

**Comment by rsherget** [comment]
#build

**Comment by rsherget** [comment]
#build

**Comment by rsherget** [comment]
#build

**Comment by rsherget** [comment]
#build

**Review by cbridgha — APPROVED** [review]
Looks good

**Comment by rsherget** [comment]
#libby

**Pull request merged**
