### PR TITLE
cleanup JAX-RS 2.1 feature and upgrade to 2.1.1 API jar

### PR DESCRIPTION
**Pull request by WhiteCat22**
Basically just upgrading the API jar from [2.1-m09](https://mvnrepository.com/artifact/javax.ws.rs/javax.ws.rs-api/2.1-m09) to [2.1.1](https://mvnrepository.com/artifact/javax.ws.rs/javax.ws.rs-api/2.1.1)

### CODE REVIEW

**Comment by WhiteCat22** [comment]
I have compared the 2 jars and verified that the only differences are the new copyright headers and a couple minor javadoc updates.

**Comment by WhiteCat22** [comment]
#libby #build #spawn.fullfat.buckets=com.ibm.ws.jaxrs.2.0_fat,com.ibm.ws.jaxrs.2.0.client_fat,com.ibm.ws.jaxrs.2.1_fat,com.ibm.ws.jaxrs.2.1_fat_executor,com.ibm.ws.jaxrs.2.1_fat_extended,com.ibm.ws.jaxrs.2.1.sse_fat

**Review by neuwerk — APPROVED** [review]
LGTM!

**Review by jim-krueger — APPROVED** [review]

**Review by jhanders34 — APPROVED** [review]

**Comment by WhiteCat22** [comment]
#libby

**Pull request merged**
