### PR TITLE
Update scheduledPersonalBuilds.yml

### PR DESCRIPTION
**Pull request by fritze2**
- Update scheduledPersonalBuilds.yml to match personalbuild.yml.
- Change product from OpenLiberty to Liberty.
- Change name from "OpenLiberty Personal Build" to "Open Liberty Personal Build".
- Prefix "Open Liberty " in triggerName.
- Add spawn.fullfat.buckets to compile step properties.
- Set FAT step to use the libfsfe04.hursley.ibm.com fileserver. This change isn't necessary anymore, but I think it is better to be consistent with what's in the personalbuild.yml.

### CODE REVIEW

**Review by wraschke — DISMISSED** [review]
Thanks for inserting the space!

**Comment by fritze2** [comment]
#pb

**Comment by fritze2** [comment]
#pbbeta

**Review by wraschke — APPROVED** [review]

**Comment by fritze2** [comment]
#libby

**Comment by fritze2** [comment]
> We could not perform your request. We allow builds for authorized users and trusted code only.

These messages are happening because this is merging from a branch in the OpenLiberty organization and OpenLiberty doesn't have permissions to run pipelines. I should have made this against my fork instead.

**Pull request merged**
