### PR TITLE
Pull in final WebSocket 2.2 API

### LINKED ISSUE #28035: WebSocket 2.2: Pull in 2.2 final API jar
Currently staged here: https://jakarta.oss.sonatype.org/content/repositories/staging/jakarta/websocket/ once on maven central we should pull these in.

### PR DESCRIPTION
**Pull request by pnicolucci**
fixes #28035

### CODE REVIEW

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Review by volosied — APPROVED** [review]

**Comment by pnicolucci** [comment]
#libby

**Pull request merged**
