### PR TITLE
More eclipse cleanup

### PR DESCRIPTION
**Pull request by jhanders34**
Get com.ibm.ws.messaging.open_clientcontainer_fat building in eclipse.
- Class directory names didn't match package names
- .classpath file did not depend on bnd and referenced jars and projects instead.

Additional eclipse and bnd updates

- Add missing source directories that are in bnd, but not eclipse .classpath files.
- Update bnd source directories to match eclipse settings where the src directory was not complete, but a parent directory was used instead.
- Add missing bndtools prefs file
- Remove facet xml file from feature util .settings directory

### CODE REVIEW

**Comment by jhanders34** [comment]
#build

**Comment by dhaggart** [comment]
Jared, we didn't want the package name to conflict with the CL package hence the choice of package name.  It would be preferable to rename directories if that is what is required.

**Comment by jhanders34** [comment]
#run-libby-bot

**Comment by jhanders34** [comment]
#run-libby-bot
#build

**Pull request merged**
