### PR TITLE
8458 - Loop until cfw chain is closed

### PR DESCRIPTION
**Pull request by loriadi**
#fixes 8458

### CODE REVIEW

**Comment by loriadi** [comment]
#build

**Comment by loriadi** [comment]
There were two test failures, I don't believe either have any bearing on this change.  One of them however, was a server stop issue, but it's root cause seems to be something different.

**Comment by pnicolucci** [comment]
fixes #8458

**Comment by loriadi** [comment]
Oh, duh.  Pretty sure I did that, but probably forgot to save it.  Thank you!
 
Thanks,Lori AdingtonIBM WebSphere Java Focal PointDelta WebSphere Lab Advocate
 
 
----- Original message -----From: "Paul A. Nicolucci" <notifications@github.com>To: OpenLiberty/open-liberty <open-liberty@noreply.github.com>Cc: Lori Adington <loriad@us.ibm.com>, State change <state_change@noreply.github.com>Subject: [EXTERNAL] Re: [OpenLiberty/open-liberty] 8458 - Loop until cfw chain is closed (#8460)Date: Thu, Aug 8, 2019 9:48 AM 
fixes #8458

**Pull request merged**
