### PR TITLE
allow reproxy of request on cancelled branch

### LINKED ISSUE #28193: Sipcontainer does not allow reproxying a SIP request if 4xx response was received on a proxy branch
Customer is reporting that sipcontainer does not allow to reproxy a SIP request if a 4xx response code was received on a proxy branch. This behavior is different from the sipcontainer behavior in traditional WebSphere Application Server, where a SIP request can be reproxyed to a different destination.

### PR DESCRIPTION
**Pull request by TiborBeres**
Fixes #28193

### CODE REVIEW

**Comment by TiborBeres** [comment]
#build 
#fat.buckets.to.run=com.ibm.ws.sipcontainer_fat,com.ibm.ws.sipcontainer_fat_1,com.ibm.ws.sipcontainer_fat_2,com.ibm.ws.sipcontainer_fat_3,com.ibm.ws.sipcontainer_fat_4,com.ibm.ws.sipcontainer_fat_5,com.ibm.ws.sipcontainer_fat_6,com.ibm.ws.sipcontainer_fat_7 
#spawn.fullfat.buckets=com.ibm.ws.sipcontainer_fat,com.ibm.ws.sipcontainer_fat_1,com.ibm.ws.sipcontainer_fat_2,com.ibm.ws.sipcontainer_fat_3,com.ibm.ws.sipcontainer_fat_4,com.ibm.ws.sipcontainer_fat_5,com.ibm.ws.sipcontainer_fat_6,com.ibm.ws.sipcontainer_fat_7

**Comment by TiborBeres** [comment]
#build
#fat.buckets.to.run=com.ibm.ws.sipcontainer_fat,com.ibm.ws.sipcontainer_fat_1,com.ibm.ws.sipcontainer_fat_2,com.ibm.ws.sipcontainer_fat_3,com.ibm.ws.sipcontainer_fat_4,com.ibm.ws.sipcontainer_fat_5,com.ibm.ws.sipcontainer_fat_6,com.ibm.ws.sipcontainer_fat_7
#spawn.fullfat.buckets=com.ibm.ws.sipcontainer_fat,com.ibm.ws.sipcontainer_fat_1,com.ibm.ws.sipcontainer_fat_2,com.ibm.ws.sipcontainer_fat_3,com.ibm.ws.sipcontainer_fat_4,com.ibm.ws.sipcontainer_fat_5,com.ibm.ws.sipcontainer_fat_6,com.ibm.ws.sipcontainer_fat_7

**Comment by TiborBeres** [comment]
#build
#fat.buckets.to.run=com.ibm.ws.sipcontainer_fat,com.ibm.ws.sipcontainer_fat_1,com.ibm.ws.sipcontainer_fat_2,com.ibm.ws.sipcontainer_fat_3,com.ibm.ws.sipcontainer_fat_4,com.ibm.ws.sipcontainer_fat_5,com.ibm.ws.sipcontainer_fat_6,com.ibm.ws.sipcontainer_fat_7
#spawn.fullfat.buckets=com.ibm.ws.sipcontainer_fat,com.ibm.ws.sipcontainer_fat_1,com.ibm.ws.sipcontainer_fat_2,com.ibm.ws.sipcontainer_fat_3,com.ibm.ws.sipcontainer_fat_4,com.ibm.ws.sipcontainer_fat_5,com.ibm.ws.sipcontainer_fat_6,com.ibm.ws.sipcontainer_fat_7

**Comment by TiborBeres** [comment]
#build
#fat.buckets.to.run=com.ibm.ws.sipcontainer_fat,com.ibm.ws.sipcontainer_fat_1,com.ibm.ws.sipcontainer_fat_2,com.ibm.ws.sipcontainer_fat_3,com.ibm.ws.sipcontainer_fat_4,com.ibm.ws.sipcontainer_fat_5,com.ibm.ws.sipcontainer_fat_6,com.ibm.ws.sipcontainer_fat_7
#spawn.fullfat.buckets=com.ibm.ws.sipcontainer_fat,com.ibm.ws.sipcontainer_fat_1,com.ibm.ws.sipcontainer_fat_2,com.ibm.ws.sipcontainer_fat_3,com.ibm.ws.sipcontainer_fat_4,com.ibm.ws.sipcontainer_fat_5,com.ibm.ws.sipcontainer_fat_6,com.ibm.ws.sipcontainer_fat_7

**Comment by TiborBeres** [comment]
#build
#fat.buckets.to.run=com.ibm.ws.sipcontainer_fat,com.ibm.ws.sipcontainer_fat_1,com.ibm.ws.sipcontainer_fat_2,com.ibm.ws.sipcontainer_fat_3,com.ibm.ws.sipcontainer_fat_4,com.ibm.ws.sipcontainer_fat_5,com.ibm.ws.sipcontainer_fat_6,com.ibm.ws.sipcontainer_fat_7
#spawn.fullfat.buckets=com.ibm.ws.sipcontainer_fat,com.ibm.ws.sipcontainer_fat_1,com.ibm.ws.sipcontainer_fat_2,com.ibm.ws.sipcontainer_fat_3,com.ibm.ws.sipcontainer_fat_4,com.ibm.ws.sipcontainer_fat_5,com.ibm.ws.sipcontainer_fat_6,com.ibm.ws.sipcontainer_fat_7

**Comment by TiborBeres** [comment]
All of the sipcontainer_fat tests have passed in the personal build. There were intermittent failures, where a testcase would fail in one build but pass on the next execution.

**Comment by TiborBeres** [comment]
We already provided these changes to our customer as an iFix on liberty v24.0.0.9, see PR https://github.ibm.com/websphere/open-liberty-service/pull/1225.  Changes were throughly tested.

**Review by sushmitha37 — APPROVED** [review]

**Review by Sushmitha-Mosali — APPROVED** [review]

**Comment by TiborBeres** [comment]
#libby

**Comment by TiborBeres** [comment]
#build
#fat.buckets.to.run=com.ibm.ws.sipcontainer_fat,com.ibm.ws.sipcontainer_fat_1,com.ibm.ws.sipcontainer_fat_2,com.ibm.ws.sipcontainer_fat_3,com.ibm.ws.sipcontainer_fat_4,com.ibm.ws.sipcontainer_fat_5,com.ibm.ws.sipcontainer_fat_6,com.ibm.ws.sipcontainer_fat_7
#spawn.fullfat.buckets=com.ibm.ws.sipcontainer_fat,com.ibm.ws.sipcontainer_fat_1,com.ibm.ws.sipcontainer_fat_2,com.ibm.ws.sipcontainer_fat_3,com.ibm.ws.sipcontainer_fat_4,com.ibm.ws.sipcontainer_fat_5,com.ibm.ws.sipcontainer_fat_6,com.ibm.ws.sipcontainer_fat_7

**Pull request merged**
