### PR TITLE
Sync Simplicity JavaInfo with kernel

### PR DESCRIPTION
**Pull request by tkburroughs**
Revert Simplicity JavaInfo so it calculates java vendor the same
way the kernel does. Java vendor should not be used to determine
behavior, but the way it is determined has not changed.
Corrects a failure in JavaInfoTest.testJavaVendor()

### CODE REVIEW

**Comment by tkburroughs** [comment]
#build

**Comment by jhanders34** [comment]
I can approve this PR, but it could potentially cause breakage.  Places that currently use the JavaInfo.vendor() in fattest.simplicity should be changed to use isClassAvailable() which doesn't exist yet in the fattest.simplicity, but probably should.

**Comment by tkburroughs** [comment]
@jhanders34 So more complicated than I thought.  A few options:
- if the PB for this change fails, then just assign the existing BB to the functional area of the failures in this PB to sort out.
OR
- if the PB passes, then merge; and if new failures occur in Full or SOE, then open new BB to those functional areas to sort out
OR
- if you know the best functional area to handle the existing BB, then discard this PR and assign to correct functional area

**Comment by tevans78** [comment]
> I can approve this PR, but it could potentially cause breakage. Places that currently use the JavaInfo.vendor() in fattest.simplicity should be changed to use isClassAvailable() which doesn't exist yet in the fattest.simplicity, but probably should.

In the kernel version of JavaInfo, the vendor() method has been deprecated. I think that this change is technically correct but that vendor() should be deprecated here too and we need to start removing it's use. Most current usages are actually for debug... in the kernel version, I added a method called debugString which should be the preferred way to do debug and thereby isolate any usage of vendor.

Longer term it would be nice to find a way to make the code common between the kernel and Simplicity

**Comment by tkburroughs** [comment]
@jhanders34 @tevans78 
Please review the new version:
- vendor() is now deprecated, and contains deprecation comments consistent with the kernel version.
- detectIBMJava() has been converted to isAccessible() as a convenience method consistent with the kernel
- debugString() has been added, consistent with the kernel version

I suspect that one of the points of a separate class like this in simplicity is to provide a way for testing to detect when the kernel version has changed in an incompatible way, which is why there is currently a build break.  Delivering this change will fix the current build break and encourage those that use the deprecated method to avoid it over time.  It is possible it would result in additional build breaks in SOE runs, but those can be assigned to the FAT buckets that need to be updated to stop using vendor().

**Comment by tkburroughs** [comment]
#run-libby-bot

**Comment by tkburroughs** [comment]
#build

**Comment by tkburroughs** [comment]
The 2 failures in the build are known intermittent issues.

**Review by tevans78 — APPROVED** [review]

**Comment by tkburroughs** [comment]
Perhaps a bit stale; Rebased to latest and running build again.
#libby #build

**Comment by tkburroughs** [comment]
The 3 failing FAT have known intermittent failures, and none of them use the modified JavaInfo. Ready to merge.

**Pull request merged**
