### PR TITLE
JSR375: Integrate jaspic session cookie to the existing sso cookie.

### PR DESCRIPTION
**Pull request by toshiyamamoto**

### CODE REVIEW

**Comment by rhpeters** [comment]
@toshiyamamoto : It appears as though there are no new messages for ID to review here. Is that correct?

**Comment by toshiyamamoto** [comment]
#build

**Comment by toshiyamamoto** [comment]
the build has not been started, therefore it will pick up the last force update.

**Comment by toshiyamamoto** [comment]
#build

**Pull request merged**
