### PR TITLE
Initial code pass of configured H2 enablement

### PR DESCRIPTION
**Pull request by mrsaldana**

### CODE REVIEW

**Comment by mrsaldana** [comment]
Using this PR as a mock up for proposed HTTP/2.0 configuration. The current design is:

- For Servlet 3.0, HTTP/2.0 is disabled and no way of enabling.
- For Servlet 3.1, HTTP/2.0 is disabled but optional. In order to enable set:
      <httpOptions insecureUpgradeProtocol="h2c"/> for an HTTP Channel
      <sslOptions alpnProtocols="h2"/> for an SSL Channel
-For Servlet 4.0, HTTP/2.0 is enabled, with no way of disabling. 

In order to ensure there is not a race condition with channels starting up and the value being set onto the CHFWBundle by the declarative service, the ReferenceCardinality has been set to MANDATORY. Discussed this with Erik Hochstedt last week and it was decided to create this to ensure this is the correct design/approach.

**Comment by ewhoch** [comment]
To achieve the function described, the approach I suggested was to have the containers provide a property requesting how the channels act. 

In other words, the containers raise the property to "Act as H2", "Don't act as H2" or "Act as H2 if configured" and the channel framework will reference that property and react to it.

However due to the asynchronous startup, the channel may start and begin opening channels before the reference is set by the container, leading to channels being opened that aren't H2 even if the ultimate configuration is to do so.

I could see a few ways to fix it, namely:
1) If a change in the H2 configuration requested comes in, destroy the current channels and create new ones
2) Create a new bundle for the servlet 4 feature to request, something like "ChannelH2" (sort of how there are servlet 3.0 and 3.1 extensions of the general root 'webcontainer') 
3) Inspect the start-order configurations like "CONTAINER_EARLY", "CONTAINER_LATE", etc to hint to the channel to activate after the containers.
4) Set the property to configure the H2 channel state as mandatory (as Manuel did in this PR). This however then forces any user of the channel to provide this property, the server will never start otherwise. It makes the components slightly less decoupled. Also if the provisioning of the channel is itself an external, it could break previous users of that channel bundle. 

Suggested this PR and wanted to add @NottyCode to the discussion since I'm not 100% sure it's the right direction, but also don't know if any of the alternatives would be better.

**Comment by covener** [comment]
> For Servlet 4.0, HTTP/2.0 is enabled, with no way of disabling.

This is a little rough in the serviceability department.  I don't think it's much of a stretch to envision "does it fail w/o HTTP/2" being a question support would be interested in, and an application doesn't necessarily work with an older servlet API.

**Comment by billw1024** [comment]
We need a way to turn off negotiating of H2 when servlet/4 is specified in server.xml as a feature, since that may allow users to workaround an H2 bug, while still running their servlet apps that require access to servlet/4 APIs in order to load and run.  Servlet/4 servlets can run over HTTP/1.1, they just don't make use of H2 underneath them, it is transparent to the app, H2 is only an optimization.

To this end, here would be what we need to do, to keep this as simple and intuitive as possible:

If Servlet/4 (or higher) is defined in server.xml then:
H2 negotiating is ON by default
it can be turned OFF for secure ports by setting:
<sslOptions alpnProtocols="http/1.1"/>

it can be turned OFF for insecure ports by setting:
<httpOptions http2="disabled" />


If Servlet/3.1 is defined in server.xml then:
H2 negotiating is OFF by default, it can be turned ON for secure ports by setting:
<sslOptions alpnProtocols="h2c"/>

it can be turned ON for insecure ports by setting:
<httpOptions http2="enabled" />


Or, we just go back to the original WAD design, and just have HTTP2 setting decoupled from the Servlet/4 feature setting, and require that each port simply turn it ON, otherwise it is off by default.  I would suggest this is the most straightforward way of doing things.

Slightly different topic/point, it is ok on startup to do Http/1.1 and then switch over to Http2 once the server is fully loaded.  In other words, we don't have to stress if we don't recognized http2 in the config right away during startup.

**Comment by mrsaldana** [comment]
Pull request updated with final design that was proposed from the discussion thread. As it stands, the default values for HTTP/2 are depicted by the servlet feature being used. 

```xml
<featureManager>
      <feature>servlet-3.0</feature>
</featureManager>
```
_Servlet 3.0 will never use HTTP/2, even if the endpoint is specifically configured to do so._

```xml
<featureManager>
      <feature>servlet-3.1</feature>
</featureManager>
```
_Servlet 3.1 will not use HTTP/2 by default.  The endpoint could be configured to enable the use of HTTP/2._

```xml
<featureManager>
      <feature>servlet-4.0</feature>
</featureManager>
```
Servlet 4.0 will use HTTP/2 by default. The endpoint could be configured to set the protocol version to HTTP/1.1 instead.

An endpoint could be configured to use HTTP/2 as follows:

```xml
<httpEndpoint id="defaultHttpEndpoint" protocolVersion="http/2" httpPort="9080" httpsPort="9443" />
```
Similarly, an endpoint could be configured to use HTTP/1.1 as follows:
```xml
<httpEndpoint id="defaultHttpEndpoint" protocolVersion="http/1.1" httpPort="9080" httpsPort="9443" />
```

**Comment by mrsaldana** [comment]
#build

**Comment by mrsaldana** [comment]
#build

**Comment by mrsaldana** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.transport.http2_fat

**Comment by mrsaldana** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.transport.http2_fat

**Comment by mrsaldana** [comment]
The failing H2 test in due to a race condition in the bucket that is being looked into. This PR does not affect that code.

**Pull request merged**
