### PR TITLE
Personal build configuration file for Open Liberty

### PR DESCRIPTION
**Pull request by wraschke**

### CODE REVIEW

**Comment by wraschke** [comment]
#ol-pbbeta@dev

**Comment by wraschke** [comment]
#ol-pbbeta@dev

**Comment by wraschke** [comment]
#ol-pbbeta@dev

**Comment by wraschke** [comment]
#libby

**Comment by wraschke** [comment]
Another one. We the best PR!

**Comment by wraschke** [comment]
Wendy's comment!

**Comment by wraschke** [comment]
Unique, distinguished content.

**Comment by wraschke** [comment]
#libby

**Comment by wraschke** [comment]
Sitting in the park waiting for you.

**Comment by wraschke** [comment]
#ol-pbbeta@dev

**Comment by wraschke** [comment]
Hey, it's a beautiful morning.

**Comment by wraschke** [comment]
#ol-pbbeta@dev

**Comment by wraschke** [comment]
#ol-pbbeta@dev

**Comment by wraschke** [comment]
#ol-pbbeta@dev

**Comment by wraschke** [comment]
#ol-pbbeta@dev

**Comment by wraschke** [comment]
#ol-pbbeta@dev

**Comment by wraschke** [comment]
#ol-pbbeta@dev

**Comment by wraschke** [comment]
#ol-pbbeta@dev

**Comment by wasbrdge** [comment]
#ol-pbbeta@dev

**Comment by wraschke** [comment]
#ol-pbbeta@dev

**Comment by wraschke** [comment]
#ol-pbbeta@dev

**Comment by wraschke** [comment]
#ol-pbbeta@dev

**Comment by wraschke** [comment]
#ol-pbbeta@dev

**Comment by wasbrdge** [comment]
I am a good doggo!

#ol-pbbeta@dev

**Comment by wraschke** [comment]
Closing since I merged 23070, which has the same code.

**Pull request closed without merging**
