### PR TITLE
versionless features fix errors CWWKF0054E and CWWKF0055E

### PR DESCRIPTION
**Pull request by rsherget**
- [ ] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [ ] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [ ] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

If a platform is specified, the CWWKF0055E error should not get spit out. The CWWKF0054E error should consistently get spit out of a versionless feature does not have a version for the resolved platform.

### CODE REVIEW

**Comment by rsherget** [comment]
#build

**Comment by wraschke** [comment]
#build

**Review by cbridgha — APPROVED** [review]
Looks good

**Comment by cbridgha** [comment]
#libby

**Pull request closed without merging**
