### PR TITLE
keystore update should be immediate

### PR DESCRIPTION
**Pull request by arunavemulapalli**

### CODE REVIEW

**Comment by ayoho** [comment]
Is this pull request still needed?

**Comment by ayoho** [comment]
@arunavemulapalli Is this pull request needed?

**Comment by ayoho** [comment]
@arunavemulapalli Checking again - is this pull request needed?

**Comment by arunavemulapalli** [comment]
There were improvements in keystore service/management and so we don't need this change in the components that depend on keystore service

**Pull request closed without merging**
