### PR TITLE
Enable default SSL configuration if none is selected by user

### PR DESCRIPTION
**Pull request by andymc12**
Part of JAX-RS 3.0 - ensuring that the default SSL configuration (from Liberty config) is used if no SSL config was specified by the user.

### CODE REVIEW

**Comment by andymc12** [comment]
#build

**Comment by andymc12** [comment]
Fixing NPE discovered in some of the jaxrs.2.1 tests. New #build

**Review by jkoehler22 — APPROVED** [review]

**Comment by andymc12** [comment]
Tweak to one test case - new #build

**Comment by andymc12** [comment]
CI is on the floor, but the official personal build only had one failure that is unrelated to these changes.

**Comment by andymc12** [comment]
#libby

**Pull request merged**
