### PR TITLE
check bundle state during generateXML

### PR DESCRIPTION
**Pull request by volosied**
For some cases, the applications and the servlet feature are removed all at once. (i.e adminCenter-1.0) 

This can create a timing issue where the generateXML is running, pauses momentarily, and the webcontainer bundle is stopped and uninstalled (due to the servlet feature removal).  Once the thread resumes, a copyFile is performed, but, since the bundle is deactivated, a missing file exception is thrown because the cached file is no longer exits.  

This was tested locally by adding Thread.sleep to delay the plugin generation and give the bundle time to deactivate.

### CODE REVIEW

**Comment by volosied** [comment]
#build

**Comment by pnicolucci** [comment]
@volosied  can you attach this PR to an issue and link?

**Comment by volosied** [comment]
fixes #10552

**Comment by volosied** [comment]
Further testing showed a few issues, so, instead, storing a reference to the bundle.  And to avoid a context is not valid error (other threads lined up for generateXML) , I'm also checking for the bundle status at the start of the generateXML method.

**Comment by volosied** [comment]
#build

**Comment by volosied** [comment]
#build

**Comment by volosied** [comment]
#build

**Comment by volosied** [comment]
#build

**Comment by volosied** [comment]
#build

**Comment by volosied** [comment]
#build

**Comment by volosied** [comment]
#build

**Comment by pnicolucci** [comment]
@volosied I know you've been working on a few changes to this PR. Are you confident in the fix and ready for a review? The latest build looks to have failures are they unrelated?

**Comment by volosied** [comment]
@pnicolucci it's ready, the failures are unrelated

**Comment by volosied** [comment]
#run-libby-bot

**Pull request merged**
