### PR TITLE
Update adminCenter batch auto feature

### PR DESCRIPTION
**Pull request by jhanders34**
- Add OR condition for batchManagement-2.0

#build

### CODE REVIEW

**Comment by amyreit** [comment]
approved

**Review by amyreit — APPROVED** [review]

**Comment by jhanders34** [comment]
#build

**Comment by jhanders34** [comment]
#libby

**Comment by jhanders34** [comment]
#build

**Comment by jhanders34** [comment]
#build

**Comment by jhanders34** [comment]
#build

**Comment by jhanders34** [comment]
#libby

**Pull request merged**
