### PR TITLE
Add tested.features for iSeries

### PR DESCRIPTION
**Pull request by jonhawkes**
#build

### CODE REVIEW

**Review by neilgsyoung — DISMISSED** [review]
Looks good

**Comment by wraschke** [comment]
#pbbeta

**Comment by jonhawkes** [comment]
#libby #build

**Review by neilgsyoung — APPROVED** [review]
Looks good

**Comment by wraschke** [comment]
#pbbeta

**Comment by wraschke** [comment]
Hello.

**Comment by wraschke** [comment]
#build

**Pull request merged**
