### PR TITLE
JAX-WS: Refactor JAX-WS WSAT Integration FAT

### PR DESCRIPTION
**Pull request by neuwerk**
This PR refactors the `com.ibm.ws.jaxws.X.wsat_fat` to `io.openliberty.jaxws.wsat_fat`

### CODE REVIEW

**Comment by neuwerk** [comment]
#build

**Comment by neuwerk** [comment]
#build

**Comment by neuwerk** [comment]
#build

**Review by BerksanAtes — APPROVED** [review]
Looks good to me!

**Comment by neuwerk** [comment]
#libby

**Pull request merged**
