### PR TITLE
Remove some overhead checking if http2 and encoding

### PR DESCRIPTION
**Pull request by jhanders34**
- Do not convert to a String, but just compare the bytes to avoid having to make the String which adds extra overhead.
- Pass Charset instead of String for encoding to avoid looking it up each time.

### CODE REVIEW

**Comment by jhanders34** [comment]
#build

**Comment by jhanders34** [comment]
#build

**Review by loriadi — APPROVED** [review]
Looks good.

**Comment by jhanders34** [comment]
#libby

**Pull request merged**
