### PR TITLE
Jsf22 view action and phase id tests ee10

### PR DESCRIPTION
**Pull request by pnicolucci**
for #22369

### CODE REVIEW

**Comment by pnicolucci** [comment]
#libby #build

**Comment by pnicolucci** [comment]
Java 17 build: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_CTUKoEm2Ee2vN7J6vLoevQ

**Comment by pnicolucci** [comment]
Java17 build timedout but ran the jsf 2.2 tests successfully, I'm running another build just to be safe

**Comment by pnicolucci** [comment]
New Jav17 build: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_RWuBUEoXEe2vN7J6vLoevQ

**Comment by pnicolucci** [comment]
Java 17 tests were successful as well.

**Review by isaacrivriv — APPROVED** [review]
Changes look good to me thanks!

**Pull request merged**
