### PR TITLE
update server include docs

### PR DESCRIPTION
**Pull request by rsherget**
update the docs for the includes tag within the server.xml. The changes will reflect allowing the user to include a directory as the location of the includes tag. 

#26551

### CODE REVIEW

**Comment by posmith** [comment]
L2 message review completed.

**Comment by rsherget** [comment]
#build

**Comment by rsherget** [comment]
#build

**Comment by rsherget** [comment]
#build

**Comment by rsherget** [comment]
#build

**Review by jimblye — APPROVED** [review]

**Pull request merged**
