### PR TITLE
Update SpringBootThinUtil for Spring Boot 3.2.x

### LINKED ISSUE #27243: Update SpringBootThinUtil for Spring Boot 3.2.x
Update the thin app utility to remove 3.2.x libraries from a spring boot app.

### PR DESCRIPTION
**Pull request by jimblye**
Fixes #27243

### CODE REVIEW

**Comment by jimblye** [comment]
#build

**Review by cbridgha — DISMISSED** [review]
Looks good

**Review by hlhoots — DISMISSED** [review]
LGTM2!

**Comment by jimblye** [comment]
#build

**Review by hlhoots — APPROVED** [review]
LGTM

**Comment by jimblye** [comment]
#libby

**Pull request merged**
