### PR TITLE
Ensure JAX-RS 3.0 Client can run in Java SE env without needing OSGi

### PR DESCRIPTION
**Pull request by andymc12**
Verified manually - still need following dependencies:
- Jakarta RESTful WS 3.0
- Jakarta Activation 2.0
- Jakarta Annotations 2.0
- Liberty logging (com.ibm.ws.logging)
- JBoss logging (com.ibm.ws.org.jboss.logging)
- Reactive Streams (com.ibm.websphere.org.reactivestreams.reactive-streams.1.0)

### CODE REVIEW

**Comment by andymc12** [comment]
#build

**Review by jim-krueger — APPROVED** [review]

**Comment by andymc12** [comment]
#build

**Comment by andymc12** [comment]
The personal build contained an intermittent failure unrelated to these changes. I've added some diagnostics for that failure in this PR, and am submitting a new #build request.

**Comment by andymc12** [comment]
#libby

**Pull request merged**
