### PR TITLE
CDI FAT repeats (part 2)

### PR DESCRIPTION
**Pull request by tevans78**
Repeat existing CDI FAT buckets using EE11

### CODE REVIEW

**Comment by tevans78** [comment]
#build

**Comment by tevans78** [comment]
#build

**Comment by tevans78** [comment]
#build

**Comment by tevans78** [comment]
#pbbeta

**Review by abutch3r — APPROVED** [review]
LGTM, the number of tests run is strange, but given it did run the repeats then should be fine

**Comment by tevans78** [comment]
#libby

**Pull request merged**
