### PR TITLE
Missing string transformation for faces 3.0

### LINKED ISSUE #14306: Investigate missing javax references for My Faces
Look into the bundles of faces-3.0 feature and check if there are any missing strings or any javax references that still need to be updated

After some investigation there are a couple of projects related to My Faces which I will list with the appropriate changes needed if any.

- [ ] com.ibm.ws.jsf.beanvalidation

> - [ ] com/ibm/ws/jsf/beanvalidation/extprocessor/JSFBeanValidationExtensionFactory contains **javax.faces.validator.beanValidator.ValidatorFactory** which should be updated to **jakarta.faces.validator.beanValidator.ValidatorFactory** according to [here](https://jakarta.ee/specifications/platform/9/apidocs/constant-values.html#jakarta.faces.validator.BeanValidator.VALIDATOR_FACTORY_KEY)
- [x] com.ibm.ws.jsf.shared **No changes need to happen here**
- [x] com.ibm.ws.cdi.2.0.jsf **No changes need to happen here**
- [x] io.openliberty.faces.internal **No changes need to happen here**
- [x] io.openliberty.org.apache.myfaces.3.0

> - [x] org/apache/myfaces/shared/util/ExternalContextUtils **No changes need to happen here since portlet was not transformed**
> javax.portlet.PortletContext
> javax.portlet.PortletConfig
> javax.portlet.ActionRequest
> javax.portlet.RenderRequest
> javax.portlet.ResourceRequest
> javax.portlet.faces.Bridge
> - [x] org/apache/myfaces/shared/webapp/webxml/WebXmlParser **Delivered in open source [here](https://issues.apache.org/jira/browse/MYFACES-4364)**
> private static final String WEB_APP_2_2_RESOURCE = "javax/servlet/resources/web-app_2_2.dtd";
> private static final String WEB_APP_2_3_RESOURCE = "javax/servlet/resources/web-app_2_3.dtd";

- [x] io.openliberty.thirdparty.faces-3.0 **Delivered in open source [here](https://issues.apache.org/jira/browse/MYFACES-4364)**
> - [x] org/apache/myfaces/shared/renderkit/html/HtmlRendererUtils
> javax_faces_developmentstage_messages

Last changes were delivered in the Open Source, until the next delivery comes, we need to make some overlays to liberty to include the fixes. Tracked [here](https://github.com/OpenLiberty/open-liberty/issues/14654)

### PR DESCRIPTION
**Pull request by isaacrivriv**
fixes #14306
Added missing string transformation for jsf and beanvalidation bundle

### CODE REVIEW

**Comment by isaacrivriv** [comment]
#build

**Comment by isaacrivriv** [comment]
#build

**Review by pnicolucci — APPROVED** [review]
Looks good to me!

**Comment by pnicolucci** [comment]
#run-libby-bot

**Pull request merged**
