### PR TITLE
Ignore ApplicationComponentMetaData for Bean Validation start up

### LINKED ISSUE #28515: Warning "Validation not enabled for module" when <feature>persistenceContainer-3.1</feature> + <feature>beanValidation-3.0</feature>
**Describe the bug**  
In Server.xml declaring : 
```xml
<feature>persistenceContainer-3.1</feature>
<feature>beanValidation-3.0</feature>
```

and using as JPA implementation :

```xml
<groupId>org.hibernate</groupId>
<artifactId>hibernate-core</artifactId>
<version>6.4.3.Final</version> 
```
implies, for each jpa entities during application startup, many messages : 

```
[5/22/24, 17:27:56:118 CEST] 00000070 id=         org.hibernate.boot.beanvalidation.TypeSafeActivator          W applyRelationalConstraints HHH000274: Unable to apply constraints on DDL for com.packagename.common.entity.MyEntity
jakarta.validation.ValidationException: Validation not enabled for module myApp-ear-0.0.1-SNAPSHOT-liberty
	at com.ibm.ws.beanvalidation.OSGiBeanValidationImpl.getValidatorFactoryHVProvider(OSGiBeanValidationImpl.java:152)
	at com.ibm.ws.beanvalidation.OSGiBeanValidationImpl.getValidatorFactory(OSGiBeanValidationImpl.java:142)
	at com.ibm.ws.beanvalidation.OSGiBeanValidationImpl.getValidatorFactory(OSGiBeanValidationImpl.java:132)
	at com.ibm.ws.beanvalidation.OSGiBeanValidationImpl.getValidatorFactory(OSGiBeanValidationImpl.java:127)
	at com.ibm.ws.beanvalidation.AbstractBeanValidation.getValidatorFactory(AbstractBeanValidation.java:76)
	at com.ibm.ws.beanvalidation.AbstractBeanValidation.getValidatorFactoryOrDefault(AbstractBeanValidation.java:87)
	at com.ibm.ws.jpa.container.beanvalidation.JPABV20ComponentImpl.getValidatorFactory(JPABV20ComponentImpl.java:45)
	at com.ibm.ws.jpa.container.beanvalidation.JPAValidator.obtainValidator(JPAValidator.java:177)
	at com.ibm.ws.jpa.container.beanvalidation.JPAValidator.getConstraintsForClass(JPAValidator.java:235)
	at org.hibernate.boot.beanvalidation.TypeSafeActivator.applyDDL(TypeSafeActivator.java:205)
	at org.hibernate.boot.beanvalidation.TypeSafeActivator.applyRelationalConstraints(TypeSafeActivator.java:189)
at org.hibernate.boot.beanvalidation.TypeSafeActivator.applyRelationalConstraints(TypeSafeActivator.java:148)
at org.hibernate.boot.beanvalidation.TypeSafeActivator.activate(TypeSafeActivator.java:97)
at jdk.internal.reflect.GeneratedMethodAccessor873.invoke(Unknown Source)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.hibernate.boot.beanvalidation.BeanValidationIntegrator.integrate(BeanValidationIntegrator.java:139)
at org.hibernate.internal.SessionFactoryImpl.integrate(SessionFactoryImpl.java:506)
at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:269)
at org.hibernate.boot.internal.SessionFactoryBuilderImpl.build(SessionFactoryBuilderImpl.java:450)
at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:1507)
at org.hibernate.jpa.HibernatePersistenceProvider.createContainerEntityManagerFactory(HibernatePersistenceProvider.java:142)
at com.ibm.ws.jpa.management.JPAPUnitInfo.createEMFactory(JPAPUnitInfo.java:984)
at com.ibm.ws.jpa.management.JPAPUnitInfo.initialize(JPAPUnitInfo.java:819)
at com.ibm.ws.jpa.management.JPAPxmlInfo.extractPersistenceUnits(JPAPxmlInfo.java:190)
at com.ibm.ws.jpa.management.JPAScopeInfo.processPersistenceUnit(JPAScopeInfo.java:90)
at com.ibm.ws.jpa.management.JPAApplInfo.addPersistenceUnits(JPAApplInfo.java:121)
at com.ibm.ws.jpa.container.osgi.internal.JPAComponentImpl.processLibraryJarPersistenceXml(JPAComponentImpl.java:548)
at com.ibm.ws.jpa.container.osgi.internal.JPAComponentImpl.applicationStarting(JPAComponentImpl.java:333)
at com.ibm.ws.container.service.state.internal.ApplicationStateManager.fireStarting(ApplicationStateManager.java:53)
at com.ibm.ws.container.service.state.internal.StateChangeServiceImpl.fireApplicationStarting(StateChangeServiceImpl.java:52)
at com.ibm.ws.app.manager.module.internal.SimpleDeployedAppInfoBase.preDeployApp(SimpleDeployedAppInfoBase.java:550)
at com.ibm.ws.app.manager.module.internal.SimpleDeployedAppInfoBase.installApp(SimpleDeployedAppInfoBase.java:511)
at com.ibm.ws.app.manager.module.internal.DeployedAppInfoBase.deployApp(DeployedAppInfoBase.java:625)
at com.ibm.ws.app.manager.ear.internal.EARApplicationHandlerImpl.install(EARApplicationHandlerImpl.java:79)
at com.ibm.ws.app.manager.internal.statemachine.StartAction.execute(StartAction.java:189)
at com.ibm.ws.app.manager.internal.statemachine.ApplicationStateMachineImpl.enterState(ApplicationStateMachineImpl.java:1369)
at com.ibm.ws.app.manager.internal.statemachine.ApplicationStateMachineImpl.run(ApplicationStateMachineImpl.java:912)
at com.ibm.ws.threading.internal.ExecutorServiceImpl$RunnableWrapper.run(ExecutorServiceImpl.java:280)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:857)
```

**Steps to Reproduce**  
See above for server.xml and pom.xml, declaring some JPA entities having ` <property name="hibernate.hbm2ddl.auto" value="update" />` in persistence.xml

**Expected behavior**  
No warning messages during application startup

**Diagnostic information:**  
 - OpenLiberty Version: 24.0.0.5
 - Affected feature(s) : persistenceContainer-3.1 with beanValidation-3.0
 - Java Version: JDK 17 (open j9)
 - server.xml see features above.

**Additional context**  
Our diagnose is that open liberty "beanValidation-3.0" relies on hibernate validator v7.x (regarding OL logs). If removing "beanValidation-3.0" feature, but adding hibernate validator v8.x packaged within application ear, seems to solve the issue (hibernate validator documentation describes that v8.X is dedicated to Jakarta EE 10, but v7.x is dedicated to Jakarta EE 9).

### PR DESCRIPTION
**Pull request by mswatosh**
Prevents sending ApplicationComponentMetaData to Bean Validation during app startup, which was causing warnings when Hibernate is used as a JPA provider. When ApplicationComponentMetaData is on the thread, Bean Validation attempts to find a validator factory associated with it instead of using the default validator factory.

fixes #28515

### CODE REVIEW

**Comment by mswatosh** [comment]
#build

**Review by njr-11 — DISMISSED** [review]

**Review by tkburroughs — DISMISSED** [review]
Kind of a minor point, but I would prefer that the 2 metadata classes were moved to a different package.  Moving from `jpa.container` to `jpa.container.core` is the correct thing to do, but I would prefer they move to one of these:
- com.ibm.ws.jpa.managment
- com.ibm.ws.jpa.metadata
- com.ibm.ws.jpa.management.metadata

Just moving them to `com.ibm.ws.jpa.managment` would avoid needing the new package-info or the new export in bnd.bnd.  For whatever reason, the JPA Container proper is in the jpa.management package.  Also, while these metadata classes are currently used from a Liberty specific "osgi" package, that "osgi" class is actually an extension of a class in "com.ibm.ws.jpa.management"... so in the future, these metadata classes may well be used from code in "com.ibm.ws.jpa.management". There is also already another metadata class in this package, GenericDatabaseMetaData.

Otherwise, if you still prefer a different package, I think "metadata" is nice because it is consistent with what it implements, in runtime.metadata.

Above is really just my personal preference; functionally everything looks good; so approving.

**Comment by mswatosh** [comment]
Thanks for pointing that out, I think you're right,  `com.ibm.ws.jpa.managment` makes sense. I moved the meta data classes to that package.

**Comment by mswatosh** [comment]
#build
#libby

**Review by tkburroughs — APPROVED** [review]

**Pull request merged**
