### PR TITLE
Re-use (histogram) Meter

### PR DESCRIPTION
**Pull request by Channyboy**
- [x] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [x] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [x] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

################################################################################################
#build

### CODE REVIEW

**Review by donbourne — APPROVED** [review]

**Comment by Channyboy** [comment]
#build (rtc didn't start)

**Comment by Channyboy** [comment]
Errors seen in pipeline and RTC are unrelated to the contents of this PR.

**Comment by Channyboy** [comment]
#libby

**Review by jdmcclur — APPROVED** [review]

**Comment by Channyboy** [comment]
#libby

**Pull request merged**
