### PR TITLE
Issue1617: BundleException: Cannot connect region 'system.bundle' to itself

### PR DESCRIPTION
**Pull request by anjumfatima90**

### CODE REVIEW

**Comment by anjumfatima90** [comment]
#build

**Comment by anjumfatima90** [comment]
#build

**Comment by anjumfatima90** [comment]
#build

**Comment by anjumfatima90** [comment]
#build

**Comment by anjumfatima90** [comment]
#build

**Comment by anjumfatima90** [comment]
#build

**Comment by anjumfatima90** [comment]
#build

**Comment by naumanna** [comment]
The Packaging Verification errors in the personal build results for this pull request can be ignored.  They are due to a problem with the verification code parsing the name of the build, not related to this pull request at all.  No need to hold off on merging due to those errors.

**Pull request merged**
