### PR TITLE
Revert "Add Jakarta Messaging 3.1 API bundles to messaging-3.1 features"

### PR DESCRIPTION
**Pull request by jim-krueger**
Reverts OpenLiberty/open-liberty#21269

### CODE REVIEW

**Review by wraschke — APPROVED** [review]

**Comment by wraschke** [comment]
#run-libby

**Comment by wraschke** [comment]
#libby

**Comment by jim-krueger** [comment]
Causing problems in builds:
[com.ibm.ws.injectionengine.osgi.internal.OSGiInjectionEngineImpl(193)] : The registerInjectionProcessorProvider method has thrown an exception java.lang.UnsupportedClassVersionError: JVMCFRE003 bad major version; class=jakarta/jms/JMSConnectionFactoryDefinition, offset=6

Build:  https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_GJM5gOArEeymtZSUeIeeVA&tab=com.ibm.team.build.web.ui.internal.editors.result.overview.OverviewPage

**Comment by wraschke** [comment]
Test

**Comment by wraschke** [comment]
LibbyBot would redo the copyright header check and is not responding to the directives I gave above. So, I'll use my admin privilege to merge.

**Pull request merged**
