### PR TITLE
add missing JSPG0077E

### LINKED ISSUE #23425: A syntax error in JSP compile should consistently output error JSPG0077E
**Describe the bug**  
JSPG0077E needs to be output to messages.log and console.log in all cases of a JSP Syntax Error (JspCoreException).   This message will be missing if the syntax error is hit in a JSP that previously wasn't compiled and precompile is disabled.

**Steps to Reproduce**  
Have a war containing a jsp with this line in it:
<%="hello jsp">
Attempting to call it, without precompile, results in a HTTP 500 error, but nothing is logged if it hadn't previously compiled on the server. 

**Expected behavior**  
The following message is output to messages.log and console.log from a JSP syntax error if precompile is enabled.  This message is missing without precompile if the servlet did not previously exist.  

[WARNING ] Unexpected exception while processing jsp /xxxx.jsp
/xxxx.jsp(2,1) JSPG0077E: End of file reached while processing scripting element "yyyyy"&gt;^M
 at Line: 1 Col: 1

**Diagnostic information:**  
 - OpenLiberty Version: all
 - Affected feature(s): jsp-2.2, jsp-2.3
 - Java Version: all
 - server.xml configuration: see above
 - If it would be useful, upload the messages.log file found in `$WLP_OUTPUT_DIR/messages.log`

### PR DESCRIPTION
**Pull request by epj**
fixes #23425

### CODE REVIEW

**Comment by wraschke** [comment]
#libby

**Comment by epj** [comment]
#build

**Review by volosied — DISMISSED** [review]

**Comment by epj** [comment]
#libbybot

**Comment by epj** [comment]
#build

**Comment by epj** [comment]
I need to make an additional change so that only JSPG0077E is output.  Initial try at this fix was getting other JSPGxxxx messages that weren't expected.

**Comment by epj** [comment]
#libbybot

**Comment by epj** [comment]
#build

**Comment by epj** [comment]
Yesterday's build has only a single test failure and it is in an unrelated area, JMS.

**Review by volosied — APPROVED** [review]

**Pull request merged**
