### PR TITLE
test that handles parked when left open by message driven bean are closed when transaction ends

### PR DESCRIPTION
**Pull request by njr-11**
Write a test of HandleList for message driven beans, where the message driven bean caches a connection handle.  The connection handle is initially parked when DissociatableManagedConnection is not supported by the resource adapter, but the server must automatically close the connection handle when the transaction ends.

### CODE REVIEW

**Comment by njr-11** [comment]
#build

**Comment by njr-11** [comment]
#build
#run-libby-bot

**Comment by njr-11** [comment]
#build
#run-libby-bot

**Review by jmstephensgit — APPROVED** [review]

**Comment by njr-11** [comment]
Build has 2 intermittent test failures which are unrelated.

**Pull request merged**
