### PR TITLE
[16031] Multipart response implementation and test cases

### PR DESCRIPTION
**Pull request by andymc12**
Implementation of #16031

### CODE REVIEW

**Comment by andymc12** [comment]
#build

**Comment by andymc12** [comment]
#build - after making some tweaks that should resolve the feature checker issues and tests that things work in EE9.

**Comment by andymc12** [comment]
A few more tweaks (and rebased) - new #build

**Comment by andymc12** [comment]
fixing a javadoc issue - #build

**Comment by andymc12** [comment]
another javadoc issue - #build

**Comment by andymc12** [comment]
Tweaked the bnd for the API bundle - should fix some more failures.  The feature checker is now complaining that I should _not_ have changed the minor version of the API bundle after first complaining that I needed to change it... may need to deal with that after this new #build

**Comment by andymc12** [comment]
Moving `newBuilder()` to `IAttachment` so that the feature verifier will (hopefully) stop complaining...

**Comment by andymc12** [comment]
#build

**Comment by andymc12** [comment]
little bit of rework... new #build

**Comment by andymc12** [comment]
Ok - I figured out the feature verifier issues. (1) I do need to update the minor version of the API jar, and (2) I will need to add some ignore rules to the feature verifier. I've updated the minor version here and will update the ignore rules in a separate PR (since it is in a separate repo).  So this #build should still fail with the feature verifier issues, but I want to ensure that nothing else is broken.

**Review by WhiteCat22 — APPROVED** [review]

**Comment by andymc12** [comment]
#libby

**Pull request merged**
