### PR TITLE
Updates to not include more in autoFVT.zip files than necessary

### PR DESCRIPTION
**Pull request by jhanders34**
- Remove things that are not needed in requiredLibs since they are either not used or already part of the list of jars that are already available to all fats like io.openliberty.org.apache.commons.logging
- Switch to have requiredLibs and other configs possibly to not load transitively to not load everything that is in the buildpath for a project.  This change prevents adding extra jars to autoFVT.zip since they are not needed.
- This is a start of the changes that can be done to remove extra stuff from the autoFVT.zip files.  More changes will be done in follow-on PRs.

- [x] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [x] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [x] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

### CODE REVIEW

**Comment by jhanders34** [comment]
#build

**Comment by jhanders34** [comment]
#libby #build

**Comment by jhanders34** [comment]
#libby #build

**Comment by jhanders34** [comment]
#libby #build

**Comment by jhanders34** [comment]
#libby #build

**Comment by jhanders34** [comment]
#build

**Comment by jhanders34** [comment]
#libby #build

**Comment by jhanders34** [comment]
#libby #build

**Comment by jhanders34** [comment]
#build

**Comment by jhanders34** [comment]
#libby #build

**Review by tkburroughs — APPROVED** [review]
EJBContainer and Injection FAT changes look good to me.

**Review by jonhawkes — APPROVED** [review]

**Pull request merged**
