### PR TITLE
Config3.1: Updating SmallRye Jars

### LINKED ISSUE #26663: Update MP Config 3.1 API, TCK & SmallRye jars
Update to final version of API and TCK jars.
Update to latest applicable version of SmallRye Config.

### PR DESCRIPTION
**Pull request by jakub-pomykala**
- Updating SmallRye-config to 3.5.2
- Updating SmallRye-config-common to 3.5.2
- Updating SmallRye-config-core to 3.5.2
- Updating SmallRye-common to 2.2.0

fixes #26663

### CODE REVIEW

**Review by tevans78 — DISMISSED** [review]

**Comment by jakub-pomykala** [comment]
#build

**Comment by jakub-pomykala** [comment]
#build

**Comment by jakub-pomykala** [comment]
#build

**Review by tevans78 — APPROVED** [review]

**Comment by jakub-pomykala** [comment]
#libby

**Pull request merged**
