### PR TITLE
Issue #17606: Remove SharedServer

### LINKED ISSUE #17606: Remove SharedServer from WCSendRedirectRelativeURLDefault servlet 4.0 tests

### PR DESCRIPTION
**Pull request by pnicolucci**
fixes #17606

### CODE REVIEW

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Review by isaacrivriv — APPROVED** [review]
Looks good thanks!

**Comment by pnicolucci** [comment]
#run-libby-bot

**Pull request merged**
