### PR TITLE
Catch up the pb.yml to latest and run pbbeta on build keyword

### PR DESCRIPTION
**Pull request by fritze2**

### CODE REVIEW

**Comment by fritze2** [comment]
#build@dev

**Comment by fritze2** [comment]
#fullpbbeta@dev

**Comment by fritze2** [comment]
#fullpbbeta
git.clone.repository.sshUrl=git@github.ibm.com:erfritz/WS-CD-Open.git
git.clone.checkout.branch=fix-fullpbbeta

**Comment by fritze2** [comment]
#pbbeta
git.clone.repository.sshUrl=git@github.ibm.com:erfritz/WS-CD-Open.git
git.clone.checkout.branch=fix-fullpbbeta

**Review by dave-waddling — APPROVED** [review]

**Comment by dave-waddling** [comment]
Approved, but we should check out the test failures as they seem unique to CI Orch.

**Comment by fritze2** [comment]
#fullpbbeta

**Comment by fritze2** [comment]
#run-libby

**Pull request merged**
