### PR TITLE
make streaming tests configurable

### PR DESCRIPTION
**Pull request by billw1024**

### CODE REVIEW

**Comment by billw1024** [comment]
#build #build #spawn.fullfat.buckets=com.ibm.ws.grpc_fat

**Comment by billw1024** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.grpc_fat

**Comment by billw1024** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.grpc_fat

**Comment by billw1024** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.grpc_fat

**Comment by billw1024** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.grpc_fat

**Review by wtlucy — APPROVED** [review]

**Comment by billw1024** [comment]
green build

**Comment by billw1024** [comment]
#run-libby-bot

**Pull request merged**
