### PR TITLE
Add local feature install testcase to feature utility

### PR DESCRIPTION
**Pull request by TayyabDev**
- Added support for unzipping the generated maven artifact repo.zip into ~/.m2
- Created test case that uses feature utility to install a feature only from m2; no downloading involved

### CODE REVIEW

**Comment by TayyabDev** [comment]
#build

**Comment by TayyabDev** [comment]
Abandoned above build

#build
#upload.all.test.logs=true

**Comment by TayyabDev** [comment]
That doesnt seem to work. Created a personal build here https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_isRU8BeVEeq0d_ql2J9EnA with upload.all.test.logs set to true

**Comment by TayyabDev** [comment]
personal build https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewDefinition&id=_JWdEUD7dEemKFI0xRbWJ_w

**Comment by TayyabDev** [comment]
https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_A8SAcBqvEeqOxqTQwEzk7g&tab=com.ibm.team.build.web.ui.internal.editors.result.properties.PropertiesProvider

**Comment by alvinso** [comment]
#run-libby-bot

**Pull request closed without merging**
