### PR TITLE
mpOpenApi-2.0: remove multi-module beta guard

### PR DESCRIPTION
**Pull request by Azquelt**
For #16628

### CODE REVIEW

**Comment by Azquelt** [comment]
#build

**Comment by Azquelt** [comment]
#libby
#build

**Comment by tevans78** [comment]
#build

**Review by tevans78 — APPROVED** [review]

**Comment by Azquelt** [comment]
Thanks for the fixes @tevans78, looks good :+1:

**Comment by tevans78** [comment]
#build

**Comment by Azquelt** [comment]
#libby

**Pull request merged**
