### PR TITLE
Issue16045-AddCustomPrincipalsToSubjectForJaspic

### PR DESCRIPTION
**Pull request by emilytee**

### CODE REVIEW

**Comment by emilytee** [comment]
#build

**Comment by emilytee** [comment]
Green PB:  https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_rZbgkHrOEeu8SN1zElUVXg

**Comment by emilytee** [comment]
Green PB:  https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_rZbgkHrOEeu8SN1zElUVXg

**Comment by emilytee** [comment]
#run-libby-bot

**Comment by emilytee** [comment]
#build

**Comment by una-tapa** [comment]
Thanks Emily.  I missed the code review meeting.  The code looks good.

**Review by acdemyers — APPROVED** [review]

**Pull request merged**
