### PR TITLE
Issue #13740: Rename ejbLite-4.0

### LINKED ISSUE #13740: Jakarta EE 9 : Rename ejbLite-4.0 and ejbHome-4.0 to enterpriseBeansXxxx-4.0
Use the new naming conention, which is the Jakarta Enterprise Beans short name, enterprise-beans as the name of the enterprise bean features going forward.

### PR DESCRIPTION
**Pull request by tkburroughs**
Rename the following features:
- ejbLite-4.0 to enterpriseBeansLite-4.0
- ejbHome-4.0 to enterpriseBeansHome-4.0

Correct all features that reference them and
correct all FAT that test them

fixes #13740

### CODE REVIEW

**Comment by tkburroughs** [comment]
#build

**Comment by dmuelle** [comment]
since this is just a name change I'm thinking no ID review is needed? If that's not correct just let me know- thanks

**Comment by tkburroughs** [comment]
#build

**Comment by olendvcook** [comment]
#run-libby-bot

**Pull request merged**
