### PR TITLE
Repeat io.openliberty.wsoc.internal_fat for Jakarta EE11

### PR DESCRIPTION
**Pull request by pnicolucci**
for #25779

### CODE REVIEW

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Review by pmd1nh — APPROVED** [review]

**Comment by pnicolucci** [comment]
#libby

**Pull request merged**
