### PR TITLE
Clear test resources at the right time

### PR DESCRIPTION
**Pull request by jonhawkes**
#build

### CODE REVIEW

**Comment by jonhawkes** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.wsat.recovery_fat.lps,com.ibm.ws.wsat.recovery_fat.multi.1,com.ibm.ws.wsat.recovery_fat.multi.2,com.ibm.ws.wsat.recovery_fat.multi.3,com.ibm.ws.wsat.recovery_fat.multi.4,com.ibm.ws.wsat.recovery_fat.single

**Comment by jonhawkes** [comment]
#libby
#build
#spawn.fullfat.buckets=com.ibm.ws.wsat.recovery_fat.lps,com.ibm.ws.wsat.recovery_fat.multi.1,com.ibm.ws.wsat.recovery_fat.multi.2,com.ibm.ws.wsat.recovery_fat.multi.3,com.ibm.ws.wsat.recovery_fat.multi.4,com.ibm.ws.wsat.recovery_fat.single

**Comment by jonhawkes** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.wsat.recovery_fat.lps,com.ibm.ws.wsat.recovery_fat.multi.1,com.ibm.ws.wsat.recovery_fat.multi.2,com.ibm.ws.wsat.recovery_fat.multi.3,com.ibm.ws.wsat.recovery_fat.multi.4,com.ibm.ws.wsat.recovery_fat.single

**Comment by jonhawkes** [comment]
#libby
#build
#spawn.fullfat.buckets=com.ibm.ws.wsat.recovery_fat.lps,com.ibm.ws.wsat.recovery_fat.multi.1,com.ibm.ws.wsat.recovery_fat.multi.2,com.ibm.ws.wsat.recovery_fat.multi.3,com.ibm.ws.wsat.recovery_fat.multi.4,com.ibm.ws.wsat.recovery_fat.single

**Comment by jonhawkes** [comment]
#build

**Review by neilgsyoung — APPROVED** [review]
Looks good

**Comment by jonhawkes** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.wsat.recovery_fat.lps,com.ibm.ws.wsat.recovery_fat.multi.1,com.ibm.ws.wsat.recovery_fat.multi.2,com.ibm.ws.wsat.recovery_fat.multi.3,com.ibm.ws.wsat.recovery_fat.multi.4,com.ibm.ws.wsat.recovery_fat.single

**Comment by jonhawkes** [comment]
#libby

**Pull request merged**
