### PR TITLE
Fix test failure in RTC 278913.

### PR DESCRIPTION
**Pull request by jvanhill**

### CODE REVIEW

**Comment by jvanhill** [comment]
#build

**Review by kristip17 — APPROVED** [review]

**Comment by jvanhill** [comment]
#build

**Comment by jvanhill** [comment]
#build
#libby

**Comment by jvanhill** [comment]
#build
#libby

**Comment by jvanhill** [comment]
#build
#libby

**Comment by jvanhill** [comment]
#libby
#build

**Pull request merged**
