### PR TITLE
revert original serial filter.

### LINKED ISSUE #9248: Revert the original serial filter implementation which no longer be used.
The original serial filter function has been merged and released as beta, however since now all of transports which Liberty implements work with JDK's serial filter, there is no need to implement different implementation. This issue intends to remove the original implementation which was merged by PR #6010.

### PR DESCRIPTION
**Pull request by toshiyamamoto**
fixes #9248
Removes the original serial filter code which no longer used.

### CODE REVIEW

**Comment by toshiyamamoto** [comment]
#build

**Comment by andrea-pichler** [comment]
Requested message review completed by L2

**Comment by toshiyamamoto** [comment]
#build

**Comment by toshiyamamoto** [comment]
#build

**Pull request merged**
