### PR TITLE
JAX-WS: Add JAX-WS fat tests to io.openliberty.jaxws_fat project

### PR DESCRIPTION
**Pull request by neuwerk**
This PR add some older JAX-WS tests to Open Liberty in a new `io.openliberty.jaxws_fat` project

### CODE REVIEW

**Comment by neuwerk** [comment]
#build

**Comment by neuwerk** [comment]
#build

**Comment by neuwerk** [comment]
#build

**Comment by neuwerk** [comment]
#build

**Review by BerksanAtes — APPROVED** [review]
Looks good to me!

**Comment by neuwerk** [comment]
#libby

**Pull request merged**
