### PR TITLE
update to snapshot build from Dec 6

### PR DESCRIPTION
**Pull request by njr-11**
Snapshot build of Concurrency 3.0 from December 6, 2021.

### CODE REVIEW

**Review by KyleAure — APPROVED** [review]

**Comment by njr-11** [comment]
#build

**Comment by njr-11** [comment]
#build

**Review by tevans78 — CHANGES_REQUESTED** [review]
Did you fix DHE?
https://github.com/OpenLiberty/open-liberty/pull/19568#issuecomment-987331643

**Comment by njr-11** [comment]
> Did you fix DHE? [#19568 (comment)](https://github.com/OpenLiberty/open-liberty/pull/19568#issuecomment-987331643)

@tevans78  DHE didn't need fixing, it just needed the file uploaded to there by a developer with write access.  I found someone to do that, but it still takes time for the file to move from staging to available.  It appears to be there now, so I'll run the check again,

#run-libby-bot

**Review by tevans78 — APPROVED** [review]
@njr-11 thank you

**Pull request merged**
