### PR TITLE
25259 ltpa key rotation fat

### LINKED ISSUE #25669: Feature Test Summary -  for LTPA key rotation enhancement
## Test Strategy

**Describe the test strategy & approach for this feature, and describe how the approach verifies the functions delivered by this feature.**

_For any feature, be aware that only FAT tests (not unit or BVT) are executed in our cross platform testing. To ensure cross platform testing ensure you have sufficient FAT coverage to verify the feature._

_If delivering tests outside of the standard Liberty FAT framework, do the tests push the results into cognitive testing database (if not, consult with the CSI Team who can provide advice and verify if results are being received)?_

### List of FAT projects affected

*  existing FAT project: _dev/com.ibm.ws.security.token.ltpa_fat/_

### Test strategy

* What functionality is new or modified by this feature?
   * Support LTPA keys rotation without causing the clients' existing tokens to re-authenticate (#18499).

* What are the positive and negative tests for that functionality? (Tell me the specific scenarios you tested. What kind of tests do you have for when everything ends up working (positive tests)? What about tests that verify we fail gracefully when things go wrong (negative tests)? See the [Positive and negative tests](https://github.ibm.com/websphere/WS-CD-Open/wiki/Feature-Review-(Feature-Test-Summary-Process)#positive-and-negative-tests) section of the Feature Test Summary Process wiki for more detail.)

**Automated Testcases:**

###  Existing FAT project: _dev/com.ibm.ws.security.token.ltpa_fat/_
1. `testLTPAFileCreationDeletion_monitorDirectory_true_monitorInterval_5`
2. `testLTPAFileReplacement_newValidKey_monitorDirectory_true_monitorInterval_5`
3. `testLTPAFileReplacement_newInvalidKey_monitorDirectory_true_monitorInterval_5`
4. `testLTPAFileCreationDeletion_monitorDirectory_false_monitorInterval_0`
5. `testLTPAFileReplacement_newValidKey_monitorDirectory_false_monitorInterval_0`
6. `testLTPAFileCreationDeletion_monitorDirectory_false_monitorInterval_5`
7. `testLTPAFileReplacement_newValidKey_monitorDirectory_false_monitorInterval_5`
8. `testLTPAFileCreationDeletion_monitorDirectory_true_monitorInterval_0`
9. `testLTPAFileReplacement_newValidKey_monitorDirectory_true_monitorInterval_0`
10. `testValidationKeys_fileNameAttribute`
       - fileName isn't configured
       - fileName is set to a non-existent file
       - fileName is in a different directory than the default ltpa.keys file
       - fileName points to a malformed file
11. `testValidationKeys_passwordAttribute`
       - password isn't configured
       - password is incorrect
12. `testValidationKeys_notUseAfterDateAttribute`
       - notUseAfterDate isn't configured
       - notUseAfterDate is empty
       - notUseAfterDate is set to an invalid date string
       - notUseAfterDate is set to a date in the past
13. `testConfiguredValidationKeys`
14. `testNotUseAfterDate_expiringAfterConfigurationAndUsage`
       - notUseAfterDate expires after usage

* What manual tests are there (if any)? (Note: Automated testing is expected for all features with manual testing considered an exception to the rule.)

## Confidence Level

**Collectively as a team you need to assess your confidence in the testing delivered based on the values below.  This should be done as a team and not an individual to ensure more eyes are on it and that pressures to deliver quickly are absorbed by the team as a whole.**

**4 - We have delivered all automated testing we believe is needed for the golden paths of this feature and have good coverage of the error/outlying scenarios.  While more testing of the error/outlying scenarios could be added we believe there is minimal risk here and the cost of providing these is considered higher than the benefit they would provide.**

### PR DESCRIPTION
**Pull request by mshah0722**
LTPA Key Rotation Fat Tests

What we're testing: `<ltpa keysFileName="${server.config.dir}/resources/security/ltpa.keys" monitorInterval = "5" monitorDirectory="true" />`

We created a new test class called: `LTPAKeyRotationTests.java`

We created 4 new test cases:
1. `testLTPAFileCreationDeletion_monitorDirectory_true_monitorInterval_5`
2. `testLTPAFileReplacement_newValidKey_monitorDirectory_true_monitorInterval_5`
3. `testLTPAFileReplacement_newInvalidKey_monitorDirectory_true_monitorInterval_5`
4. `testLTPAFileCreationDeletion_monitorDirectory_false_monitorInterval_0`

### CODE REVIEW

**Comment by mshah0722** [comment]
#build
#spawn.fullfat.buckets=com.ibm.ws.security.jwt_fat.builder,com.ibm.ws.security.jwt_fat.consumer,com.ibm.ws.security.jwtsso_fat.mpJwt-1.1,com.ibm.ws.security.jwtsso_fat.mpJwt-1.2,com.ibm.ws.security.jwtsso_fat.mpJwt-2.0,com.ibm.ws.security.jwtsso_fat.mpJwt-2.1,com.ibm.ws.security.jwtsso_fat.noMpJwt,com.ibm.ws.security.mp.jwt.1.1_fat.mpJwt-1.1,com.ibm.ws.security.mp.jwt.1.1_fat.mpJwt-1.2,com.ibm.ws.security.mp.jwt.1.1_fat.mpJwt-2.0,com.ibm.ws.security.mp.jwt.1.1_fat.mpJwt-2.0.envVars,com.ibm.ws.security.mp.jwt.1.1_fat.mpJwt-2.0.sysProps,com.ibm.ws.security.mp.jwt.1.1_fat.mpJwt-2.1,com.ibm.ws.security.mp.jwt.1.1_fat.mpJwt-2.1.envVars,com.ibm.ws.security.mp.jwt.1.1_fat.mpJwt-2.1.sysProps,com.ibm.ws.security.mp.jwt.1.2_fat.mpJwt-1.2,com.ibm.ws.security.mp.jwt.1.2_fat.mpJwt-2.0,com.ibm.ws.security.mp.jwt.1.2_fat.mpJwt-2.1,com.ibm.ws.security.oidc.client_fat.config.1,com.ibm.ws.security.oidc.client_fat.config.2,com.ibm.ws.security.oidc.client_fat.backchannelLogout,com.ibm.ws.security.oidc.client_fat.claimPropagation,com.ibm.ws.security.oidc.client_fat.e2e,com.ibm.ws.security.oidc.client_fat.jaxrs,com.ibm.ws.security.oidc.client_fat.saml,com.ibm.ws.security.oidc.client_fat.spnego,com.ibm.ws.security.oidc.client_fat.1,com.ibm.ws.security.oidc.client_fat.2,com.ibm.ws.security.oidc.client_fat.3,com.ibm.ws.security.oidc.server_fat.app-passwords,com.ibm.ws.security.oidc.server_fat.app-passwords.DerbyDB.jwt,com.ibm.ws.security.oidc.server_fat.app-passwords.DerbyDB.opaque,com.ibm.ws.security.oidc.server_fat.app-passwords.LocalStore.jwt,com.ibm.ws.security.oidc.server_fat.app-passwords.LocalStore.opaque,com.ibm.ws.security.oidc.server_fat.app-tokens,com.ibm.ws.security.oidc.server_fat.app-tokens.DerbyDB.jwt,com.ibm.ws.security.oidc.server_fat.app-tokens.DerbyDB.opaque,com.ibm.ws.security.oidc.server_fat.app-tokens.LocalStore.jwt,com.ibm.ws.security.oidc.server_fat.app-tokens.LocalStore.opaque,com.ibm.ws.security.oidc.server_fat.backchannelLogout,com.ibm.ws.security.oidc.server_fat.clientregistration,com.ibm.ws.security.oidc.server_fat.config,com.ibm.ws.security.oidc.server_fat.config.oauth,com.ibm.ws.security.oidc.server_fat.config.oidc,com.ibm.ws.security.oidc.server_fat.endpoint.authorize,com.ibm.ws.security.oidc.server_fat.endpoint.coveragemap,com.ibm.ws.security.oidc.server_fat.endpoint.discovery,com.ibm.ws.security.oidc.server_fat.endpoint.end_session,com.ibm.ws.security.oidc.server_fat.endpoint.introspect,com.ibm.ws.security.oidc.server_fat.endpoint.revoke,com.ibm.ws.security.oidc.server_fat.endpoint.token,com.ibm.ws.security.oidc.server_fat.endpoint.userinfo,com.ibm.ws.security.oidc.server_fat.feature,com.ibm.ws.security.oidc.server_fat.granttype.jwt,com.ibm.ws.security.oidc.server_fat.jaxrs,com.ibm.ws.security.oidc.server_fat.oauth,com.ibm.ws.security.oidc.server_fat.oidc,com.ibm.ws.security.oidc.server_fat.saml,com.ibm.ws.security.oidc.server_fat.spnego,com.ibm.ws.security.social_fat.LibertyOP.1,com.ibm.ws.security.social_fat.LibertyOP.2,com.ibm.ws.security.social_fat.LibertyOP.backchannelLogout,com.ibm.ws.security.social_fat.LibertyOP.claimPropagation,com.ibm.ws.security.social_fat.OpenShift,com.ibm.ws.security.social_fat.delegated,com.ibm.ws.security.social_fat.multiProvider,com.ibm.ws.security.social_fat.okdServiceLogin,io.openliberty.security.jakartasec.3.0.internal_fat,io.openliberty.security.jakartasec.3.0.internal_fat.config.1,io.openliberty.security.jakartasec.3.0.internal_fat.config.2,io.openliberty.security.jakartasec.3.0.internal_fat.logout,io.openliberty.security.jakartasec.3.0.internal_fat.refresh,com.ibm.ws.security.saml.sso_fat,com.ibm.ws.security.saml.sso_fat.2,com.ibm.ws.security.saml.sso_fat.3,com.ibm.ws.security.saml.sso_fat.config,com.ibm.ws.security.saml.sso_fat.config.mapToUserRegistry,com.ibm.ws.security.saml.sso_fat.jaxrs,com.ibm.ws.security.saml.sso_fat.jaxrs.config,com.ibm.ws.security.saml.sso_fat.logout,com.ibm.ws.security.saml.sso_fat.logout.IDP_initiated,com.ibm.ws.security.saml.sso_fat.logout.httpServletRequest,com.ibm.ws.security.saml.sso_fat.logout.ibm_security_logout

**Comment by mshah0722** [comment]
#libby

**Comment by Zech-Hein** [comment]
#build

**Review by Zech-Hein — APPROVED** [review]
Changes look good to me!

**Comment by mshah0722** [comment]
The collective repository FAT failures are unrelated to this PR. The rest of the PB results look good.

**Pull request merged**
