### PR TITLE
Move com.ibm.ws.ui_fat test bucket to open liberty

### PR DESCRIPTION
**Pull request by lavenal**
Move com.ibm.ws.ui_fat test bucket to open liberty with changes including 

- naming the project as com.ibm.ws.ui_rest_fat 
- a new CommonHttpsRequest subclass that uses HttpURLConnection to handle the rest request and return additional response body types
- new Bookmark and ToolEntry classes to use for this FAT project only. This eliminates the need to export those private classes from com.ibm.ws.ui project.
- new/change get/post/put/delete methods to use the new CommonHttpsRequest class
- other test changes to use the new classes/methods/responses

### CODE REVIEW

**Comment by lavenal** [comment]
#build

**Comment by lavenal** [comment]
#build

**Comment by lavenal** [comment]
#run-libby-bot

**Review by amyreit — APPROVED** [review]

**Comment by lavenal** [comment]
#run-libby-bot

**Pull request merged**
