### PR TITLE
Jms20 fat jakarta 2

### PR DESCRIPTION
**Pull request by tbitonti**
Attempt number two at adding a jakarta repeat to JMS20 FAT.

The main content of this update is the addition of the jakarta repeat action to the FAT.

To enable that update, a number of j2ee-management tests were disabled under the jakarta repeat, since j2ee-management is not available under jakarta, and is in conflict with a number of features.

The tests all pass locally.  Tests involving injection do not currently work: WELD is throwing injection exceptions, and these must still be resolved.  The failing injection tests are disable for running under jakarta within this pull request.

This update removes the import of fattest.properties from the test server configurations.  The rewrite of the server configuration which occurs when updating the server feature list for jakarta destructively modifies he configuration by re-ordering the import and variable elements.  This breaks the tests by causing incorrect variable definitions to have precedence.  The content of fattest.properties was placed directly in server configurations, and the import was removed.

Note: The fattest.simplicity changes are actually no-ops.  Ghost differences appear because of the branch and commit structure and how git diff works relative to that structure.  The changes which show up to fattest.simplicity within this PR are already present in integration.

### CODE REVIEW

**Comment by tbitonti** [comment]
#liberty

**Comment by tbitonti** [comment]
#build

**Comment by tbitonti** [comment]
#libby

**Review by dazavala — APPROVED** [review]

**Comment by tbitonti** [comment]
#libby

**Comment by tbitonti** [comment]
#build

**Comment by dazavala** [comment]
The open_jms20_fat passed.  I didn't see the `testSetDeliveryMode_TCP_SecOff` and `testSetDeliveryMode_B_SecOff` tests in the results.  Let's merge and continue with the MDB fixes.

**Pull request merged**
