### PR TITLE
Delete AbstractInMemoryJSPExtensionServletWrapper.java

### LINKED ISSUE #15035: Investigate JSP's AbstractInMemoryJSPExtensionServletWrapper
AbstractInMemoryJSPExtensionServletWrapper isn't used anywhere in Liberty, and it appears to be left over from tWAS.  

It’s an abstract class, and I don’t see any other classes that implement it.

### PR DESCRIPTION
**Pull request by volosied**
fixes #15035

### CODE REVIEW

**Comment by volosied** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jsp.2.3_fat

**Comment by volosied** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jsp.2.3_fat,com.ibm.ws.jsf.2.2_fat,com.ibm.ws.jsf.2.3_fat,com.ibm.ws.webcontainer.servlet.3.1_fat,com.ibm.ws.webcontainer.servlet.4.0_fat,com.ibm.ws.jsf_fat,com.ibm.ws.jsf_fat_jsf2.2,com.ibm.ws.jsf_fat_jsf2.3,com.ibm.ws.jsp_fat,com.ibm.ws.jsp_fat_lWAS,com.ibm.ws.webcontainer_fat_lWAS,com.ibm.ws.webcontainer_fat_servlet31,com.ibm.ws.webcontainer.cors_fat

**Comment by volosied** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jsp.2.3_fat,com.ibm.ws.jsf.2.2_fat,com.ibm.ws.jsf.2.3_fat,com.ibm.ws.webcontainer.servlet.3.1_fat,com.ibm.ws.webcontainer.servlet.4.0_fat,com.ibm.ws.jsf_fat,com.ibm.ws.jsf_fat_jsf2.2,com.ibm.ws.jsf_fat_jsf2.3,com.ibm.ws.jsp_fat,com.ibm.ws.jsp_fat_lWAS,com.ibm.ws.webcontainer_fat_lWAS,com.ibm.ws.webcontainer_fat_servlet31

**Comment by volosied** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jsp.2.3_fat,com.ibm.ws.jsf.2.2_fat,com.ibm.ws.jsf.2.3_fat,com.ibm.ws.webcontainer.servlet.3.1_fat,com.ibm.ws.webcontainer.servlet.4.0_fat,com.ibm.ws.jsf_fat,com.ibm.ws.jsf_fat_jsf2.2,com.ibm.ws.jsf_fat_jsf2.3,com.ibm.ws.jsp_fat,com.ibm.ws.jsp_fat_lWAS,com.ibm.ws.webcontainer_fat_lWAS,com.ibm.ws.webcontainer_fat_servlet31

**Comment by volosied** [comment]
Trying again... Builds failing due to:
```
* What went wrong:
Execution failed for task ':com.ibm.ws.org.opensaml.opensaml:audit'.
> Too many requests (429): Use OSS Index credentials for increased rate limit.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':com.ibm.ws.org.opensaml.opensaml.messaging.impl.3.4.5:audit'.
> Too many requests (429): Use OSS Index credentials for increased rate limit.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

3: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':io.openliberty.jakarta.faces.3.0:audit'.
> Too many requests (429): Use OSS Index credentials for increased rate limit.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

4: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':io.openliberty.org.apache.jasper.expressionLanguage.4.0:audit'.
> Too many requests (429): Use OSS Index credentials for increased rate limit.

```

**Comment by volosied** [comment]
#build #spawn.fullfat.buckets=com.ibm.ws.jsp.2.3_fat,com.ibm.ws.jsf.2.2_fat,com.ibm.ws.jsf.2.3_fat,com.ibm.ws.webcontainer.servlet.3.1_fat,com.ibm.ws.webcontainer.servlet.4.0_fat,com.ibm.ws.jsf_fat,com.ibm.ws.jsf_fat_jsf2.2,com.ibm.ws.jsf_fat_jsf2.3,com.ibm.ws.jsp_fat

**Review by epj — APPROVED** [review]

**Comment by volosied** [comment]
Holding off until #15240 is resolved.

We need to find out more about _useInMemory_.

**Pull request closed without merging**
