### PR TITLE
Don't run LRA TCK on z/OS

### PR DESCRIPTION
**Pull request by Azquelt**
Currently there's a test setup problem which is causing this test to fail to start and we don't have the time to investigate and fix properly.

For RTC 297181

### CODE REVIEW

**Comment by Azquelt** [comment]
#build

**Comment by Azquelt** [comment]
z/OS build: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_e4H9gLuSEe64zdT7X42CIQ

**Review by idlewis — DISMISSED** [review]

**Review by idlewis — APPROVED** [review]
LGTM

**Comment by Azquelt** [comment]
New builds:
Regular: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_-aMcILudEe64zdT7X42CIQ
z/OS: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=__z1voLudEe64zdT7X42CIQ

**Comment by Azquelt** [comment]
#libby

**Comment by Azquelt** [comment]
Build results look correct with the tests running and passing in the regular build and not running at all on the z/OS build.

**Pull request merged**
