### PR TITLE
JAX-WS: Java2Permissions modification

### PR DESCRIPTION
**Pull request by BerksanAtes**
- [x]  I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [x]  If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify release bug label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [x]  If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

` java.lang.RuntimePermission:accessClassInPackage.sun.misc` is given for Java 17 for SAML FAT tests

### CODE REVIEW

**Comment by BerksanAtes** [comment]
#build

**Comment by BerksanAtes** [comment]
This is the PB on pipeline for Suse 22.04 with Java Semeru 17. Exact configuration that the defect observed.
https://libh-proxy1.fyre.ibm.com/cognitive-dev/pipelineAnalysis.html?pipelineId=e4dc33ef-b3c1-467a-834b-fa27e87f7d84

**Comment by BerksanAtes** [comment]
#build

**Review by sawadood — APPROVED** [review]
Changes look good.

**Pull request merged**
