### PR TITLE
Pull Request for Issue #282 download jsf23 source

### PR DESCRIPTION
**Pull request by jsartoris**
Pull Request for #282 to pull in to:
- use an updated MyFaces snapshot build
- delete source files that are no longer needed as they are included in the snapshot build
- modify build.gradle files to download the source and javadoc files to the project's build directory during a build.

### CODE REVIEW

**Comment by jsartoris** [comment]
#build

**Comment by pnicolucci** [comment]
#build

**Comment by pnicolucci** [comment]
I don't think you requested a new build after you made the bnd.bnd changes and updated to the org.apache.myfaces.ee package that was changed from org.apache.myfaces.ee6. I just requested one.

**Comment by jsartoris** [comment]
@pnicolucci I had a couple of builds that ran overnight.  I didn't link them to the Issue or PR.  The CDI tests are failing for some reason.  Debugging now.

**Comment by jsartoris** [comment]
#build

**Comment by jsartoris** [comment]
The failure in the FAT of the personal build has nothing to do with the changes in this PR.  Merging the code.

**Pull request merged**
