### PR TITLE
Update microProfile1 server template to use microProfile-1.3

### LINKED ISSUE #2529: microProfile1 server template needs to be updated to use microProfile-1.3

### PR DESCRIPTION
**Pull request by garypicher**
fixes #2529

### CODE REVIEW

**Comment by garypicher** [comment]
#build

**Comment by ewhoch** [comment]
Sorry for the confusion on the checklist, this is 1 of 6 PRs that were affected by the rollout of checklists for openliberty. It's not quite ready yet and being turned off, so for this PR please ignore the 'yellow' status check below, but do be on the lookout for future changes to how PRs are created and managed.

**Comment by garypicher** [comment]
Personal Build had 1 error, which is a match to a known issue.

**Comment by ewhoch** [comment]
Simple update to that template. looks fine.

**Pull request merged**
