### PR TITLE
look up app-defined resources for Concurrency spec

### PR DESCRIPTION
**Pull request by njr-11**
Add just enough code to make it possible to look up application-defined concurrency resources that are defined with a ContextServiceDefinition, ManagedExecutorDefinition, ManagedScheduledExecutorDefinition, or ManagedThreadFactoryDefinition annotation.  Interpreting and honoring the values in the annotation fields will come later.  The first step is just to verify that the annotations as defined are at least usable the most basic sense.

### CODE REVIEW

**Comment by njr-11** [comment]
#build

**Comment by njr-11** [comment]
#build

**Comment by njr-11** [comment]
rebased onto latest
#build
#run-libby-bot

**Comment by njr-11** [comment]
#build

**Comment by njr-11** [comment]
#run-libby-bot

**Comment by njr-11** [comment]
#build
#run-libby-bot

**Review by mswatosh — APPROVED** [review]

**Comment by njr-11** [comment]
#build
#run-libby-bot

**Comment by njr-11** [comment]
#build
#run-libby-bot

**Comment by njr-11** [comment]
#build
#run-libby-bot

**Comment by njr-11** [comment]
#build
#run-libby-bot

**Comment by njr-11** [comment]
Build has 1 test failure, which is a duplicate of a pre-existing issue in an unrelated test bucket.

**Pull request merged**
