### PR TITLE
Issue #17457: Add ImplementationVersion to Faces 3.0 thirdparty bnd.bnd

### LINKED ISSUE #17457: Add Implementation-Version variable to io.openliberty.faces.3.0.thirdparty/bnd.bnd
Doing this work makes updating to a new version a bit easier and less error prone.

We already do this in 2.3 here:  https://github.com/OpenLiberty/open-liberty/blob/integration/dev/com.ibm.websphere.appserver.thirdparty.jsf-2.3/bnd.bnd

### PR DESCRIPTION
**Pull request by pnicolucci**
fixes #17457

### CODE REVIEW

**Comment by pnicolucci** [comment]
#build

**Review by volosied — APPROVED** [review]
Looks good to me.

**Review by wtlucy — COMMENTED** [review]
Will the artifact version in the buildpath always match this new Implementation-Version - that is `org.apache.myfaces.core:myfaces-impl;version=3.0.0`? If so we should replace that version as well.

**Comment by pnicolucci** [comment]
@wtlucy  good call we also do that for the JSF 2.3 third-party bnd.bnd.  I've made the change thanks for catching that!

**Comment by pnicolucci** [comment]
#build

**Review by wtlucy — APPROVED** [review]

**Comment by pnicolucci** [comment]
#run-libby-bot

**Pull request merged**
