### PR TITLE
Set intervals to 1 second like the rest of the FAT

### PR DESCRIPTION
**Pull request by Channyboy**
- [x] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [x] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [x] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

################################################################################################

### CODE REVIEW

**Comment by Channyboy** [comment]
#build

**Comment by contbld** [comment]
Your personal pipeline request is at https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=94155fa9-f162-4db9-a851-7b9de34daab7

Target locations of links might be accessible only to IBM employees.

**Comment by contbld** [comment]
<h3>Code analysis and actions</h3>
DO NOT DELETE THIS COMMENT.

- 2 FAT files were changed, added, or removed.
 - Check that the build did not break the affected FAT suite(s).
- **Please describe in a separate comment how you tested your changes.**
- 1 messages files were changed and need an L2 review.

- @OpenLiberty/message-reviewer Please review.
  - --nlsFiles

**Comment by Channyboy** [comment]
~#build~
~#spawn.fullfat.buckets=io.openliberty.microprofile.health.3.1.internal_fat~

Wrong PR

**Review by tonyreigns — APPROVED** [review]
LGTM

**Pull request merged**
