### PR TITLE
Allow server.xml to override context root in application.xml

### PR DESCRIPTION
**Pull request by jimblye**

### CODE REVIEW

**Comment by jimblye** [comment]
#build
#libby

**Review by tbitonti — CHANGES_REQUESTED** [review]
Minor problem: The call in WebAppConfiguratorHelper.configureInit to Tr.exit now happens before the call to configureContextRoot.  Shouldn't the call to Tr.exit be last?

**Comment by jimblye** [comment]
#build

**Comment by jimblye** [comment]
#build

**Comment by jimblye** [comment]
#build

**Review by brenthdaniel — APPROVED** [review]
This is fine, but if you didn't want to add the new SPI method you could probably look up the component directly in WebAppConfigurator (or maybe just get the config -- not sure what's available at that point in the web container)

**Review by tbitonti — APPROVED** [review]

**Comment by jimblye** [comment]
#libby

**Comment by jimblye** [comment]
#build

**Comment by jimblye** [comment]
#build

**Pull request merged**
