### PR TITLE
Update EclipseLink ASM to 9.7.1

### PR DESCRIPTION
**Pull request by anija-anil**
Update EclipseLink ASM to 9.7.1 for Java 24 support.

### CODE REVIEW

**Comment by anija-anil** [comment]
#build

**Review by tkburroughs — APPROVED** [review]

**Comment by anija-anil** [comment]
#build

**Comment by anija-anil** [comment]
#build

**Comment by anija-anil** [comment]
@tkburroughs The build failed with some unclear errors. I've already made the necessary changes in the WS-CD, and the PR have been merged. Could you please assist with this?

**Comment by tkburroughs** [comment]
@anija-anil Merging the code to WS-CD-Open is not enough; that only merges the code t othe integration branch; you must also wait for the code to then be merged to the release branch; only then will the feature checker errors be resolved.

That has now happened; kicking off another build:

#build

**Comment by contbld** [comment]
https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=76aa4ec4-2a02-4783-a6cb-7b31bfd4c6b8 has errors/failures.

**Comment by contbld** [comment]
The build anija-anil-30031-20241107-1532
https://wasrtc.hursley.ibm.com:9443/jazz/resource/itemOid/com.ibm.team.build.BuildResult/_53MNgJ1WEe-M9e5esDPP_g
completed and has errors or failures.

For help analyzing your personal build, go to https://libh-proxy1.fyre.ibm.com/cognitive/buildAnalysis.html?uuid=_53MNgJ1WEe-M9e5esDPP_g

**Comment by tkburroughs** [comment]
Test failures are associated with an known defect; merging.

**Pull request merged**
