### PR TITLE
switch to ZonedDateTime to prepare for ZonedTrigger

### PR DESCRIPTION
**Pull request by njr-11**
In order to prepare for properly supporting ZonedTrigger, switch the existing implementation over to recording times as ZonedDateTime.

### CODE REVIEW

**Comment by njr-11** [comment]
#build

**Comment by wraschke** [comment]
#build

**Comment by wraschke** [comment]
#libby

**Comment by njr-11** [comment]
#build
#run-libby-bot

**Review by jmstephensgit — APPROVED** [review]

**Pull request merged**
